### ISSUE TITLE
Cannot run finsql.exe after creating new container from new Business Central image

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#100]
Hi team,
I've created new container with next command
`New-NavContainer -accept_eula -alwaysPull -imageName "navinsider.azurecr.io/dynamics-nav:11.0.21063.0" -containerName D365BC-W1 -includeCSide -licenseFile C:\Users\vmadmin\Downloads\D365FFApps.flf
`
after that I've got 3 client shortcuts on desktop:
1) D365BC-W1 Web Client : works well
2) D365BC-W1 Windows Client : works well
3) D365BC-W1 CSIDE : don't work. After running i get error.

`---------------------------
finsql.exe - System Error
---------------------------
The code execution cannot proceed because MSVCP120.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
`

**Comment by freddydk** [comment]
From https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

2. You cannot connect to the Classic Development Environment (CSide)
a. Are you missing the prerequisites?
Whether you are running CSide using Click-Once, through the navcontainerhelper or you manually copied the binaries to a shared folder, you need to have the pre-requisites installed on the computer on which you are running CSide.

If CSide complains about missing DLL's or giving an ODBC error, you probably need to install these pre-requisites:

https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
https://download.microsoft.com/download/3/A/6/3A632674-A016-4E31-A675-94BE390EA739/ENU/x64/sqlncli.msi

**Comment by dkatson** [comment]
Sorry, @freddydk  - my fault. Did not know about prerequisites. Now now, and it works!
Thank you for quick answer!

**Comment by freddydk** [comment]
No problem, due to the very detailed error description it took only a few seconds to answer.

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by freddydk** [comment]
In the next version of the navcontainerhelper, the Remove-NavContainer will fail if files are locked in the container folder, meaning that you shouldn't be able to get this issue again (have tried this myself a few times).

**Comment by freddydk** [comment]
0.2.7.1 is released with this check
