### ISSUE TITLE
Release Pipeline to local docker container (CICD)

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1000]
Do you have any guidance/reference for using a release pipeline to a local container (not Azure/Saas)?

The Deploy-App.ps1 script only has "deploymentType" options for AzureVM and onlineTenant.  Would I have to add a new deploymentType and use logic similar to the Invoke-WebRequest logic found in the "onlineTenant" deployment options?

Is there an easier way?

**Comment by freddydk** [comment]
Maybe set the reusecontainer to false - and then use the build container?
But basically, what you want to do is to create a container and use publish-bccontainerapp to publish the app including -sync and -install.

**Comment by GreatScott000** [comment]
Thank you @freddydk it turned out to be fairly simple for a local Docker container (from where the Pipeline/agent is).

Next step is for me to test release to an AzureVM with a local install (no container).

**Comment by freddydk** [comment]
On the DVD you will find some PowerShell Cmdlets for publishing and installing apps.
