### ISSUE TITLE
IncludeCSide is no longer supported in Dynamics 365 Business Central 2019 wave 2 release (1910 / 15.x)

### ISSUE THREAD

**Issue by rarrese** [microsoft/navcontainerhelper#1001]
Hi Freddy,

I´m instaling my first image following the documentation on:
https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-container-sandbox
The message that I received is:
bb567ade2524: Pull complete
Digest: sha256:0c5390038cbe19a3b94918bb300afdc4dfb3211c537d0a35b1edaa86222c02de
Status: Downloaded newer image for mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-mx-ltsc2019
mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-mx-ltsc2019
Using image mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-mx-ltsc2019
Creating Container ErroContainer
Version: 16.1.12629.12805-mx
Style: sandbox
Platform: 16.0.12630.12758
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.18362.836 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale es-MX
IncludeCSide is no longer supported in Dynamics 365 Business Central 2019 wave 2 release (1910 / 15.x)
En C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.11\ContainerHandling\New-NavContainer.ps1: 785 Carácter: 9
+         throw "IncludeCSide is no longer supported in Dynamics 365 Bu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (IncludeCSide is...e (1910 / 15.x):String) [], RuntimeException
    + FullyQualifiedErrorId : IncludeCSide is no longer supported in Dynamics 365 Business Central 2019 wave 2 release (1910 / 15.x)

Thanks

Rafael

**Comment by freddydk** [comment]
Remove the -includeCSIDE parameter.
Read my blog for more info: https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/

**Comment by rarrese** [comment]
Thank Freddy and congratulations on this technology; It is easy to understand and follow
 The container was successfully created but send the following error:
Initialization took 206 seconds
Ready for connections!
Reading CustomSettings.config from ErroContainer
Creating Desktop Shortcuts for ErroContainer
Container ErroContainer successfully created
Copy from container ErroContainer (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\Progra
mData\NavContainerHelper\Extensions\ErroContainer\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\ErroContainer\_Microsoft_System Application Test Library.app
docker : Publish-NavApp : Your program license does not allow you to publish 'User 
En C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: 105 
Carácter: 13
+             docker exec $containerName powershell $file
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Publish-NavApp ... publish 'User :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError


Thanks

Rafael

**Comment by freddydk** [comment]
-includeTestToolkit will import testtoolkit and all tests. You need a partner license to do this.
you can add -includeOnlyTestLibraries to avoid the tests, but this still imports the app above, which requires a partner license.
you can instead add -includeOnlyTestFramework - that should work - or you could remove the -includetesttoolkit.

**Comment by rarrese** [comment]
Thanks
