### ISSUE TITLE
##[warning]Atleast for one assembly start time was not obtained due to tag not present or parsing issue, total run duration will now be summation of time taken by each assembly

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#1002]
**Describe the issue**
In some pipeline runs I get this warning when publishing the test results:
##[warning]Atleast for one assembly start time was not obtained due to tag not present or parsing issue, total run duration will now be summation of time taken by each assembly

I've hunted it down to that this is depending on the time format of the container. I get this in the Finnish localization, and they have a dot (.) as time separator - not colon (:) as many others.
So in the test result file we get `run-time="11.25.21"` instead of `run-time="11:25:21"`, which is unexpected by DevOps...

Now I found out that the `datetime.ToString("HH:mm:ss")` does not do what you expect. The : in the format string says that it should use the current configured time separator, not : as we write. (ref: https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings#timeSeparator)

The solution is to wrap the : inside '
`datetime.ToString("HH':'mm':'ss")`

A PR to fix this is on it's way...

**Comment by freddydk** [comment]
What version is this? - is this when writing the XUnit compatible test results?

**Comment by jwikman** [comment]
I'm running 0.6.5.10, but the code is the same in latest version.
Yes, the XUnitResultFileName is set.

**Comment by jwikman** [comment]
I got this before:
`  <assembly name="50105 NABCI General Tester" test-framework="PS Test Runner" run-date="2020-05-28" run-time="14.04.22" total="7" passed="7" failed="0" skipped="0" time="69.121">`


And after my fix I get this:
`  <assembly name="50105 NABCI General Tester" test-framework="PS Test Runner" run-date="2020-05-28" run-time="14:25:32" total="7" passed="7" failed="0" skipped="0" time="68.326">`

**Comment by jwikman** [comment]
it's easy to repro in PowerShell, just set you regional settings to Finnish and run below:

```
[datetime]$dt = Get-Date
$dt.ToString("HH:mm:ss")
$dt.ToString("HH':'mm':'ss")
```
