### ISSUE TITLE
DockerDo : failed to register layer: re-exec error: exit status 1: output: BackupWrite

### ISSUE THREAD

**Issue by MBK75** [microsoft/navcontainerhelper#1005]
**Describe the issue**
I am trying to use New-NavContainer to download a BC v16 image on a brand new laptop.  I changed my data-root to an E:\ drive location which is an external SSD drive.

After running this command:
New-NavContainer -accept_eula -containerName "MYCONTAINER" -auth NavUserPassword -imageName "mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-us-ltsc2016" -licenseFile "E:\NAVLicense\fin.flf" -memoryLimit 3G -accept_outdated -includeAL -updateHosts #-useBestContainerOS

I get the normal downloading messages, "verifying checksum, download complete", etc.  After a while, the process runs for a while and then ends with this error:
`3f2dc84033e7: Verifying Checksum
3f2dc84033e7: Download complete
3889bb8d808b: Verifying Checksum
3889bb8d808b: Download complete
DockerDo : failed to register layer: re-exec error: exit status 1: output: BackupWrite 
\\?\E:\Docker\windowsfilter\5de4c611cc3173839f29a861f8a8622b9bbc5bcccc04692dbbd7a141785ed441\Files\Documents and Settings: Incorrect function.
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-us-ltsc2016
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.11\ContainerHandling\New-NavContainer.ps1:446 char:13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo`

**Scripts used to create container and cause the issue**
```
New-NavContainer -accept_eula -containerName "MYCONTAINER" -auth NavUserPassword -imageName "mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-us-ltsc2016" -licenseFile "E:\NAVLicense\fin.flf" -memoryLimit 3G -accept_outdated -includeAL -updateHosts #-useBestContainerOS
```

**Full output of scripts**
```
`PS C:\Windows\system32> E:\PowerShell\CreateContainer.ps1
Not logged in to https://index.docker.io/v1/
NavContainerHelper is version 0.6.5.11
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Pulling image mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-us-ltsc2016
16.1.12629.12805-us-ltsc2016: Pulling from businesscentral/sandbox
3889bb8d808b: Pulling fs layer
31f9df80631e: Pulling fs layer
99b0f6ec9b51: Pulling fs layer
51b73b8637de: Pulling fs layer
252befb26488: Pulling fs layer
ae2d6ba61bc6: Pulling fs layer
354f1a1a1663: Pulling fs layer
87ff8d40bc47: Pulling fs layer
4ce4377aed05: Pulling fs layer
8f141bcf6865: Pulling fs layer
645ab54e2c61: Pulling fs layer
989e88de41eb: Pulling fs layer
289665f47974: Pulling fs layer
93f430e37d2f: Pulling fs layer
00b2449aeef2: Pulling fs layer
c8453c93a5c4: Pulling fs layer
0a40d840ded0: Pulling fs layer
1f5974feb625: Pulling fs layer
acf4a23352c7: Pulling fs layer
4ce4377aed05: Waiting
8f141bcf6865: Waiting
ce9365912f4c: Pulling fs layer
645ab54e2c61: Waiting
989e88de41eb: Waiting
289665f47974: Waiting
6dbce37aa86d: Pulling fs layer
93f430e37d2f: Waiting
00b2449aeef2: Waiting
c8453c93a5c4: Waiting
ae2d6ba61bc6: Waiting
51b73b8637de: Waiting
7d6761823f3f: Pulling fs layer
354f1a1a1663: Waiting
252befb26488: Waiting
87ff8d40bc47: Waiting
ce9365912f4c: Waiting
16b45cf5dda6: Pulling fs layer
acf4a23352c7: Waiting
1f5974feb625: Waiting
0a40d840ded0: Waiting
7d6761823f3f: Waiting
b29c8a0236f7: Pulling fs layer
16b45cf5dda6: Waiting
b1183e0336fe: Pulling fs layer
b29c8a0236f7: Waiting
664dc633d425: Pulling fs layer
b1183e0336fe: Waiting
122ec13e5f71: Pulling fs layer
664dc633d425: Waiting
122ec13e5f71: Waiting
3f2dc84033e7: Pulling fs layer
1a20922aa4d1: Pulling fs layer
3f2dc84033e7: Waiting
c03c44e34882: Pulling fs layer
9e8d707b3136: Pulling fs layer
ff4dd20ca199: Pulling fs layer
94dfe51487c0: Pulling fs layer
4b741eb1127a: Pulling fs layer
1a20922aa4d1: Waiting
c03c44e34882: Waiting
9e8d707b3136: Waiting
9a9eeb1c5ec6: Pulling fs layer
ff4dd20ca199: Waiting
94dfe51487c0: Waiting
4b741eb1127a: Waiting
bf20fb306a0d: Pulling fs layer
bf20fb306a0d: Waiting
99b0f6ec9b51: Verifying Checksum
99b0f6ec9b51: Download complete
51b73b8637de: Verifying Checksum
51b73b8637de: Download complete
252befb26488: Verifying Checksum
252befb26488: Download complete
ae2d6ba61bc6: Verifying Checksum
ae2d6ba61bc6: Download complete
354f1a1a1663: Verifying Checksum
354f1a1a1663: Download complete
87ff8d40bc47: Verifying Checksum
87ff8d40bc47: Download complete
4ce4377aed05: Verifying Checksum
4ce4377aed05: Download complete
8f141bcf6865: Verifying Checksum
8f141bcf6865: Download complete
31f9df80631e: Download complete
989e88de41eb: Verifying Checksum
989e88de41eb: Download complete
289665f47974: Verifying Checksum
289665f47974: Download complete
93f430e37d2f: Verifying Checksum
93f430e37d2f: Download complete
00b2449aeef2: Download complete
c8453c93a5c4: Verifying Checksum
c8453c93a5c4: Download complete
0a40d840ded0: Verifying Checksum
0a40d840ded0: Download complete
1f5974feb625: Verifying Checksum
1f5974feb625: Download complete
acf4a23352c7: Download complete
ce9365912f4c: Verifying Checksum
ce9365912f4c: Download complete
6dbce37aa86d: Verifying Checksum
6dbce37aa86d: Download complete
7d6761823f3f: Verifying Checksum
7d6761823f3f: Download complete
16b45cf5dda6: Verifying Checksum
16b45cf5dda6: Download complete
b29c8a0236f7: Verifying Checksum
b29c8a0236f7: Download complete
b1183e0336fe: Verifying Checksum
b1183e0336fe: Download complete
664dc633d425: Verifying Checksum
664dc633d425: Download complete
122ec13e5f71: Verifying Checksum
122ec13e5f71: Download complete
645ab54e2c61: Verifying Checksum
645ab54e2c61: Download complete
1a20922aa4d1: Download complete
c03c44e34882: Verifying Checksum
c03c44e34882: Download complete
9e8d707b3136: Verifying Checksum
9e8d707b3136: Download complete
ff4dd20ca199: Verifying Checksum
ff4dd20ca199: Download complete
94dfe51487c0: Download complete
4b741eb1127a: Verifying Checksum
4b741eb1127a: Download complete
9a9eeb1c5ec6: Verifying Checksum
9a9eeb1c5ec6: Download complete
bf20fb306a0d: Verifying Checksum
bf20fb306a0d: Download complete
3f2dc84033e7: Verifying Checksum
3f2dc84033e7: Download complete
3889bb8d808b: Verifying Checksum
3889bb8d808b: Download complete
DockerDo : failed to register layer: re-exec error: exit status 1: output: BackupWrite 
\\?\E:\Docker\windowsfilter\5de4c611cc3173839f29a861f8a8622b9bbc5bcccc04692dbbd7a141785ed441\Files\Documents and Settings: Incorrect function.
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/businesscentral/sandbox:16.1.12629.12805-us-ltsc2016
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.11\ContainerHandling\New-NavContainer.ps1:446 char:13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo`
...
```

**Screenshots**

**Additional context**
- does it happen all the time? Yes, it has happened multiple times.  I have uninstalled Docker Desktop, rebooted, and reinstalled to no avail.
- did it use to work?  The same command worked on my old laptop, but I didn't use an external SSD drive for the data-root

Thanks for the help!

**Comment by freddydk** [comment]
Your OS is 1909 - you should use ltsc2019 and not ltsc2016.
Not sure that this is the reason, but you can try.

**Comment by MBK75** [comment]
Thanks, Freddy.  I gave that a shot and had the same experience.  Any other suggestions?  I appreciate the help!

**Comment by freddydk** [comment]
The problem seems to be your docker installation.
I would guess you also cannot pull and run other containers then, maybe search docker forums for help? or reinstall standard.

**Comment by MBK75** [comment]
Thanks again, Freddy.  I spent a good chunk of time searching the forums last night, and the only two potential solutions I could find were:

1. Enable Bitlocker and disable it
2. Uninstall OneDrive, Dropbox, etc. (none of which should be installed)

I have left a message on the Docker Desktop issues list but I am not very hopeful of receiving a response.  I will keep you posted.  Right now, I reset the data-root setting and am trying again.  If that fails, then I will try to uninstall, reboot, and reinstall without the data-root setting.  I have reinstalled twice now trying to fix it but no luck.

**Comment by MBK75** [comment]
Update: I removed the data-root setting, and the image downloaded and created the container.  Strange - both my D:\ and E:\ drives throw the incorrect function error.  I will try again now that I have successfully downloaded an image to C:\

**Comment by MBK75** [comment]
The data-root setting seems to be the issue.  Putting it back in fails

**Comment by MBK75** [comment]
Any takers on this one?  I really would like to keep my images and containers off of my C:\ drive if possible.

**Comment by freddydk** [comment]
No problem.
