### ISSUE TITLE
Issue while running base testcodeunit in al test tool

### ISSUE THREAD

**Issue by srinivasbanny** [microsoft/navcontainerhelper#1007]
Hi @freddydk 

I was testing base test codeunit (134087-ERM Update Currency - Sales) in al test tool page(130451)
it gives me error but when i run the same test codeunit through old test tool page  (130401) it passes . I saw the issue which is related to page controls(sales line type ) don't know why is this giving error 
attaching the error list .Please do needful 

[Error List.xlsx](https://github.com/microsoft/navcontainerhelper/files/4723412/Error.List.xlsx)

**Comment by freddydk** [comment]
You would need to give me a lot more info.
Version numbers, scripts, container output etc.
Also, I don't download and watch attachments, they should be copy/pasted into the issue and marked the "insert code"

**Comment by srinivasbanny** [comment]
Version Number :Version: US Business Central 16.1 (Platform 16.0.12630.13398 + Application 16.1.12629.13468)
I am running through manual al test tool page 
Docker Container image : mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019

![image](https://user-images.githubusercontent.com/39740300/83642031-efe61980-a5cb-11ea-9a9f-c2667ddb37e9.png)
<img width="889" alt="Error list" src="https://user-images.githubusercontent.com/39740300/83642160-1b690400-a5cc-11ea-973f-f506d815ae11.png">



134087	UpdateCurrencyCodeOnSalesQuotePage---->	Error Message: The field with ID = 317934071 is not found on the page. - Error Call Stack: "ERM Update Currency - Sales"(CodeUnit 134087).UpdateCurrencyCodeOnSalesQuotePage line 15 - Tests-ERM by Microsoft\"Test Runner - Mgt"(CodeUnit 130454).RunTests - Test Runner by Microsoft\"Test Runner - Isol. Disabled"(CodeUnit 130451).OnRun - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunTests - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunSelectedTests - Test Runner by Microsoft\"AL Test Tool"(Page 130451)."RunSelectedTests - OnAction" - Test Runner by Microsoft\
134087	UpdateCurrencyCodeOnSalesOrderPage---->	Error Message: The field with ID = 364865599 is not found on the page. - Error Call Stack: "ERM Update Currency - Sales"(CodeUnit 134087).UpdateCurrencyCodeOnSalesOrderPage line 15 - Tests-ERM by Microsoft\"Test Runner - Mgt"(CodeUnit 130454).RunTests - Test Runner by Microsoft\"Test Runner - Isol. Disabled"(CodeUnit 130451).OnRun - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunTests - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunSelectedTests - Test Runner by Microsoft\"AL Test Tool"(Page 130451)."RunSelectedTests - OnAction" - Test Runner by Microsoft\
134087	UpdateCurrencyCodeOnSalesInvoicePage--->Error Message: The field with ID = 2116990794 is not found on the page. - Error Call Stack: "ERM Update Currency - Sales"(CodeUnit 134087).UpdateCurrencyCodeOnSalesInvoicePage line 15 - Tests-ERM by Microsoft\"Test Runner - Mgt"(CodeUnit 130454).RunTests - Test Runner by Microsoft\"Test Runner - Isol. Disabled"(CodeUnit 130451).OnRun - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunTests - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunSelectedTests - Test Runner by Microsoft\"AL Test Tool"(Page 130451)."RunSelectedTests - OnAction" - Test Runner by Microsoft\
134087	UpdateCurrencyCodeOnSalesCrMemoPage---->Error Message: The field with ID = 744207890 is not found on the page. - Error Call Stack: "ERM Update Currency - Sales"(CodeUnit 134087).UpdateCurrencyCodeOnSalesCrMemoPage line 15 - Tests-ERM by Microsoft\"Test Runner - Mgt"(CodeUnit 130454).RunTests - Test Runner by Microsoft\"Test Runner - Isol. Disabled"(CodeUnit 130451).OnRun - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunTests - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunSelectedTests - Test Runner by Microsoft\"AL Test Tool"(Page 130451)."RunSelectedTests - OnAction" - Test Runner by Microsoft\
134087	UpdateCurrencyCodeOnSalesReturnOrderPage---->Error Message: The field with ID = 1029367703 is not found on the page. - Error Call Stack: "ERM Update Currency - Sales"(CodeUnit 134087).UpdateCurrencyCodeOnSalesReturnOrderPage line 15 - Tests-ERM by Microsoft\"Test Runner - Mgt"(CodeUnit 130454).RunTests - Test Runner by Microsoft\"Test Runner - Isol. Disabled"(CodeUnit 130451).OnRun - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunTests - Test Runner by Microsoft\"Test Suite Mgt."(CodeUnit 130456).RunSelectedTests - Test Runner by Microsoft\"AL Test Tool"(Page 130451)."RunSelectedTests - OnAction" - Test Runner by Microsoft\

**Comment by srinivasbanny** [comment]
hi @freddydk  any luck please

**Comment by freddydk** [comment]
I have heard that this is due to the old page resetting the library random.
I think it will be fixed in a future release.
Sorry that I don't know more - but this is primarily for helping out on docker related issues, it is hard to know everything about everything.
