### ISSUE TITLE
Issue with DevOps Pipeline and the Container that it creates

### ISSUE THREAD

**Issue by JayDashti** [microsoft/navcontainerhelper#1019]
I am having the following issue with BC docker images on my DevOps Pipeline. Any help will be appreciated:

On my server I have several pulled images and multiple containers, like 30+ of them. When I pull the following image in my Pipeline script to run test units and then drop the container, it creates the container successfully but from another image and not the one that the script has just pulled!
 
I don’t know why this is happening! If I don’t have any image pulled (if I prune them), then it creates from the one that it just pulls. Here is how my script looks like where the imgeName along with the other variables are parameters that are being passed on my Pipeline:

```
$imageName = 'bcinsider.azurecr.io/bcsandbox-master:us'
docker pull $imageName
New-NavContainer -accept_eula: $true `
-doNotCheckHealth `
-updateHosts `
-containerName bcmaster `
-imageName $imageName `
-alwaysPull:$true `
-auth 'UserPassword' `
-Credential $credential `
-licenseFile $license `
-doNotUseRuntimePackages
```

Here is what I see in Pipeline log:
NavContainerHelper is version 0.7.0.3 
NavContainerHelper is running as administrator 
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016 
Docker Client Version is 19.03.5 
Docker Server Version is 19.03.5 
Removing bcmaster from host hosts file 
Removing C:\ProgramData\NavContainerHelper\Extensions\bcmaster
Using image bcinsider.azurecr.io/bcsandbox-master:us-ltsc2016 
Disabling Health Check (always report healthy) 
Creating Container bcmaster
**Version: 16.0.10467.0-us** 
Style: sandbox 
**Platform: 15.0.37746.0** 
Generic Tag: 0.0.9.96 
Container OS Version: 10.0.14393.3274 (ltsc2016) 
Host OS Version: 10.0.14393.3750 (ltsc2016) 
WARNING: The container operating system matches the host operating system, but the revision is different. 
If you encounter issues, you might want to specify -isolation hyperv 
Using locale en-US 
Using process isolation 
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable) 
Using license file C:\License\D365BC16.flf 
Files in C:\ProgramData\NavContainerHelper\Extensions\bcmaster\my: 
- AdditionalOutput.ps1 
- license.flf 
- MainLoop.ps1 
- SetupVariables.ps1 
- SetupWebClient.ps1 
- updatehosts.ps1 
Creating container bcmaster from image bcinsider.azurecr.io/bcsandbox-master:us-ltsc2016 
1c481c31b00d8c10a0064feb79b1fe0fc9f587fdbc9102d7b4c88b5559f94957
Waiting for container bcmaster to be ready
…

**Comment by freddydk** [comment]
Could you mark the code section piece above with "insert code" from the toolbar?
It is strange that you are asking for bcinsider.azurecr.io/bcsandbox-master:us but getting an old bcinsider.azurecr.io/bcsandbox:us - must be some syntax problem.

**Comment by JayDashti** [comment]
I did. Thanks.

**Comment by JayDashti** [comment]
I updated the log. Shouldn't it create Version 17.X with platform 16.X today?

**Comment by freddydk** [comment]
When i run your script I get:
Creating Container bcmaster
Version: 17.0.13913.0-us
Style: sandbox
Platform: 16.0.13877.0
Generic Tag: 0.0.9.99

**Comment by freddydk** [comment]
maybe reset your docker, reinstall, remove all images or something like that.
The problem is local unfortunately

**Comment by JayDashti** [comment]
Okay, thanks. I'll dig more.

**Comment by freddydk** [comment]
maybe try docker logout and docker login again to the bcinsider.
