### ISSUE TITLE
Can't access the host from container using transparent network

### ISSUE THREAD

**Issue by miraquel** [microsoft/navcontainerhelper#1023]
**Describe the issue**
I want to access the host from the container, the name host.docker.internal exists on the container, but the request always timed out when I pinged it. the host can access the container. but not vice versa.

I'm using a transparent network. the container and the host share the same subnet and gateway.

I'm sorry I can't share the docker inspect because I'm using the transparent network.

did I miss something when creating the container with NavContainerHelper?

Thanks in advance.

**Comment by freddydk** [comment]
Have you checked that host.docker.internal is in fact the host?
I add that to the hosts file inside the container and set it to the gateway (as the host is the gateway when using NAT).
When you are switching to transparent network you might need to get the IP address from somewhere else.

**Comment by miraquel** [comment]
> Have you checked that host.docker.internal is in fact the host?
> I add that to the hosts file inside the container and set it to the gateway (as the host is the gateway when using NAT).
> When you are switching to transparent network you might need to get the IP address from somewhere else.

Yes, I checked the hosts file inside the container and confirm that the host exists.
the transparent network and the host share the same subnet and gateway.
I'm sorry, I don't know what you mean by get the IP address from somewhere else.

**Comment by freddydk** [comment]
I would like to understand why you are switching to transparent networking?

**Comment by miraquel** [comment]
because I want to share the container with my private network.

**Comment by freddydk** [comment]
You could do that by publishing ports on the host as well.
I must admit that I have never used transparent networking and all that I have done is setup using NAT - primarily because using transparent networking will heavily rely on the network and how it is setup.
In our corporate network - we cannot use transparent networking (would be like somebody would plug in a foreign computer on the network) that is not allowed.

**Comment by miraquel** [comment]
I'm not sure why I can't access the host. But, because I'm using transparent network, now the container is becoming the part of my local network, and I realized, i can access another computer from that network.
I think that's enough to fulfill my requirements for now.
