### ISSUE TITLE
Error while downloading images

### ISSUE THREAD

**Issue by SUD-D365** [microsoft/navcontainerhelper#1028]
Hi There,

I am running below PS script. Trying to get V17 from insider.
I am not sure if it is wrong. I am getting an error in powershell. However it seems images are downloading but actually they are not.

```
install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'TestV17'
$navdockerimage = 'bcinsider.azurecr.io/bcsandbox-master:us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -memoryLimit 4GB `
                 -Credential $credential `
                 -includeAL:$true
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

```

![image](https://user-images.githubusercontent.com/33481576/85317697-765f8e00-b4dc-11ea-8648-088c68d5ca27.png)
![image](https://user-images.githubusercontent.com/33481576/85317736-87100400-b4dc-11ea-8c52-8ccd39d34ae0.png)

Thanks
SUD
@freddydk

**Comment by freddydk** [comment]
Please do not include passwords you have downloaded from Collaborate in public places like this (I have removed it)

The error seems to be when updating the powershell module.
You can manually uninstall the module, restart ISE and try again.

**Comment by SUD-D365** [comment]
Sorry about that passwords. but it was spelled wrong :). It will not work.

So you want to me remove navcontainerhelper module manually.
and then run the same script again, right?

**Comment by freddydk** [comment]
Looking at the error, the problem is local.
You can also just comment out the line with install-module - the rest of the script seems to be pulling the image.

**Comment by SUD-D365** [comment]
Ok i will comment it and then run.
But if i am not wrong, you can see its pulling image from
**Pulling image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2016**
Is it ok? Since i am trying to pull from insiders.

**Comment by freddydk** [comment]
Ok, didn't see that - not sure what.
Could you paste the full output of the new-navcontainer (and mark it with "insert code")

**Comment by SUD-D365** [comment]
Ok.
So the script is below.

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

docker login "bcinsider.azurecr.io" -u "" -p ""

$containername = 'TestV17'
$navdockerimage = 'bcinsider.azurecr.io/bcsandbox-master:us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -memoryLimit 4GB `
                 -Credential $credential `
                 -includeAL:$true
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password


And the output is.

docker : WARNING! Using --password via the CLI is insecure. Use --password-stdin.
At line:6 char:1
+ docker login "bcinsider.azurecr.io" -u "2151f4c8-8fc2-4c87-a360-4f6c7 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING! Using ...password-stdin.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Login Succeeded
NavContainerHelper is version 0.6.1.1
Host is Microsoft Windows 10 Pro - 1703
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Pulling image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2016
latest-ltsc2016: Pulling from businesscentral/onprem
3889bb8d808b: Pulling fs layer
31f9df80631e: Pulling fs layer
99b0f6ec9b51: Pulling fs layer
51b73b8637de: Pulling fs layer
252befb26488: Pulling fs layer
99b0f6ec9b51: Download complete
252befb26488: Waiting
ae2d6ba61bc6: Pulling fs layer
354f1a1a1663: Pulling fs layer
ae2d6ba61bc6: Waiting
87ff8d40bc47: Pulling fs layer
4ce4377aed05: Pulling fs layer
8f141bcf6865: Pulling fs layer
645ab54e2c61: Pulling fs layer
989e88de41eb: Pulling fs layer
289665f47974: Pulling fs layer
93f430e37d2f: Pulling fs layer
00b2449aeef2: Pulling fs layer
c8453c93a5c4: Pulling fs layer
0a40d840ded0: Pulling fs layer
33217d01499d: Pulling fs layer
216e6c265bea: Pulling fs layer
11aaeaad1d49: Pulling fs layer
52b6cb373ffc: Pulling fs layer
decdde33ff42: Pulling fs layer
bf3dbdf2b62b: Pulling fs layer
93f430e37d2f: Waiting
354f1a1a1663: Waiting
bd03e04fd71a: Pulling fs layer
87ff8d40bc47: Waiting
4ce4377aed05: Waiting
8f141bcf6865: Waiting
645ab54e2c61: Waiting
989e88de41eb: Waiting
289665f47974: Waiting
216e6c265bea: Waiting
00b2449aeef2: Waiting
c8453c93a5c4: Waiting
0a40d840ded0: Waiting
5c0069019789: Pulling fs layer
33217d01499d: Waiting
52b6cb373ffc: Waiting
11aaeaad1d49: Waiting
decdde33ff42: Waiting
bf3dbdf2b62b: Waiting
a115a01a8191: Pulling fs layer
bd03e04fd71a: Waiting
e838f9c0b5b4: Pulling fs layer
5c0069019789: Waiting
5f64705828a2: Pulling fs layer
b6ab0fa57cee: Pulling fs layer
bcfaf7b1cc83: Pulling fs layer
bcfaf7b1cc83: Waiting
a115a01a8191: Waiting
e838f9c0b5b4: Waiting
5f64705828a2: Waiting
b6ab0fa57cee: Waiting

**Comment by SUD-D365** [comment]
Hi @freddydk ,

I just found the issue (forget to add ` sign). If i am not wrong. And fixed it.
Now its pulling from the insiders.
Will let you know in case of any further issue.

**Comment by SUD-D365** [comment]
Hi @freddydk ,

I am getting below issue!!
![image](https://user-images.githubusercontent.com/33481576/85389472-152fcd00-b565-11ea-8dd2-256795dad3c8.png)

Can you please help me out?

Thanks
SUD

**Comment by freddydk** [comment]
Seems like you have some sharing violation.
Have you removed other containers?
Else maybe you would have to reset docker to factory settings - or uninstall and install - this issue is seems to be docker itself.

**Comment by SUD-D365** [comment]
So all images that i have downloaded will be removed?
Will i need to download these images again, right?

**Comment by freddydk** [comment]
If the problem is the images, yes.
If the problem is the containers - no.

**Comment by SUD-D365** [comment]
![image](https://user-images.githubusercontent.com/33481576/85401191-3994a500-b577-11ea-8cb4-4c8f3f5dfbbb.png)

I tried everything that i can.
Removing docker, Enable/Disable Hyper-V, Container.
But still i am facing the issue with install-navcontainerhelper

Any help ?

Thanks
SUD

**Comment by freddydk** [comment]
You are jumping back and forth between errors.
One error is that you cannot install the containerhelper is a powershell problem - nothing to do with Docker. However you already have the containerhelper and that error could maybe be ignored.
The other is a docker error - again local to your machine - resetting or reinstalling docker should get rid of that.
Both errors are local to your machine and are very hard to troubleshoot, unless somebody else have had exactly the same issue. I haven't seen them before.

BTW - you are running PowerShell x64 as administrator right?

Maybe you can read these blog posts. which might give you something: https://freddysblog.com/?s=non-experts&submit=Search

**Comment by SUD-D365** [comment]
Yes you are right. :(
I am not sure why i am not able to run **Update-Help** from powershell. It seems it cant connect to internet from powershell(this is new issue :)).
Now i am trying to Registering the PSRepositry module.

Yes i am running it as admin.

**Comment by SUD-D365** [comment]
Hi @freddydk ,

So the issue was powershell could not connect to the network. I did realize it by below steps.

1. Unregister-PSRepository
2. Register-PSRepository -Default
3. Get-PSRepository (this then give me hint about breaking network).
4. Then i add this command before run step 1 to 3. ([Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12)
5. Now everything is working.

So this is the fix for me.

Thanks
SUD

**Comment by freddydk** [comment]
BTW - i just saw that you are running Windows 10 1703 - a very very old version which had a lot of issues with docker back then. You should update windows.

**Comment by freddydk** [comment]
Please update windows. You probably need to uninstall docker before the update and install again afterwards.
1703 is an unsupported Windows Version (https://en.wikipedia.org/wiki/Windows_10_version_history#Version_1703_(Creators_Update))

**Comment by freddydk** [comment]
If the problem persists after this. please open a new issue with the script and the full output of the script.
