### ISSUE TITLE
Docker reports contaner as unhealthy when https with internal cert. is used

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#1032]
**Describe the issue**
Docker reports container as unhealthy if https is used with local domain certificate or any other untrusted cert.

Problem is in the checkhealth.ps1 script when calling invoke-webrequest to the web client. It ends with

> The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.

Solution is e.g. to disable certificate check for the calls by using e.g. 

'''
add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
'''

before the call.

**Comment by freddydk** [comment]
I have actually deliberately done of of the certificatevalidation disable/enable in containerhelper - and not in the actual docker container.
I will investigate, but you could also add -doNotCheckHealth to ignore health checks.

**Comment by freddydk** [comment]
Kamil, I will close this one.
You can either skip health check or override the script to perform this locally.
