### ISSUE TITLE
Downloading DotNetCore: "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

### ISSUE THREAD

**Issue by pkoutsogilas** [microsoft/navcontainerhelper#1039]
When using the new artifacts, I get an error when starting the a new docker, it errors when trying to download the DotNetCore installation executable with the following error message "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

I used the following command to start a new docker:
`New-BCContainer -accept_eula -containerName test -artifactUrl (Get-BCArtifactUrl -version 16.2 -select Latest -type OnPrem) -updateHosts -useBestContainerOS -isolation process`

This is the output of the script:

```
NavContainerHelper is version 0.7.0.7
NavContainerHelper is not running as administrator
Host is Microsoft  - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Removing container test
Removing test from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\test
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.900-generic
Creating Container test
Version: 16.2.13509.13779-w1
Style: onprem
Generic Tag: 0.1.0.6
Container OS Version: 10.0.18363.900 (1909)
Host OS Version: 10.0.18363.900 (1909)
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container test from image mcr.microsoft.com/dynamicsnav:10.0.18363.900-generic
194fcf8468431352a215fd2156935046a0d4429544d5c8941d2fe8a882dd3f77
Waiting for container test to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.2.13509.13779/w1
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copy Licensefile
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Downloading DotNetCore
Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
at <ScriptBlock>, C:\Run\navinstall.ps1: line 40
at <ScriptBlock>, C:\Run\start.ps1: line 209
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.2.13509.13779/w1
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copy Licensefile
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Downloading DotNetCore
Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
at <ScriptBlock>, C:\Run\navinstall.ps1: line 40
at <ScriptBlock>, C:\Run\start.ps1: line 209
at <ScriptBlock>, <No file>: line 1
Initialization of container test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.7\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container test failed

```

If I try the same download in a PowerShell script on the host the error does not ocurr:

```
 $dotnetCoreDownloadUrl = "https://go.microsoft.com/fwlink/?LinkID=844461"
 $dotnetCoreExe = "DotNetCore.1.0.4_1.1.1-WindowsHosting.exe"
 [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
 (New-Object System.Net.WebClient).DownloadFile($dotnetCoreDownloadUrl, $dotnetCoreExe)
```

I tried the following in the navinstall.ps1 script in the container: [System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true} which is of course just a workaround.

```
if (Test-Path "$NavDvdPath\Prerequisite Components\DotNetCore") {
    $dotnetCoreExe = (Get-ChildItem -Path "$NavDvdPath\Prerequisite Components\DotNetCore" -Filter "*.exe").FullName
} else {
    Write-Host "Downloading DotNetCore"
    $dotnetCoreDownloadUrl = "https://go.microsoft.com/fwlink/?LinkID=844461"
    $dotnetCoreExe = "$NavDvdPath\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe"
    $dotnetCoreFolder = [System.IO.Path]::GetDirectoryName($dotnetCoreExe)
    if (!(Test-Path $dotnetCoreFolder)) {
        New-Item -Path $dotnetCoreFolder -ItemType Directory | Out-Null
    }
    # ignore ServerCertificateValidationCheck
	[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
    (New-Object System.Net.WebClient).DownloadFile($dotnetCoreDownloadUrl, $dotnetCoreExe)
}

```

Then running start.ps1 again, the script then is able to download DotNetCore but fails later on with "aes.key" not found.
Is there an option I should use? I'm I missing something?

Please let me know if you need more information.

**Comment by freddydk** [comment]
Does your container have a working dns?
Maybe try to add -dns "8.8.8.8"?

**Comment by pkoutsogilas** [comment]
Unfortunately adding -dns "8.8.8.8" still results in a failure to download DotNetCore with the same error message.

**Comment by freddydk** [comment]
Hmmm - the problem is local to your machine - I have done exactly this from a lot of different machines and it works.
You don't have fiddler running or some other proxy that can cause this right?

**Comment by pkoutsogilas** [comment]
I will try a fresh install of windows 10 and docker desktop on a different machine and see if I get the same error. I will also try to investigate if maybe the anti-virus software is preventing the download. If the new machine has no problems I might have to reinstall my main system.

As far as I know I'm not using fiddler or other proxies.

Will keep you posted if I find out more.

**Comment by freddydk** [comment]
Thanks

**Comment by pkoutsogilas** [comment]
Ok, it is definitely the anti-virus, disabling it will remove the error. No I only have to figure out what exception I have to add to the anti-virus. The issue can be closed.

**Comment by pkoutsogilas** [comment]
And I also found the setting I have to change in the anti-virus :)

**Comment by freddydk** [comment]
Could you share that setting here?
(and what Anti Virus that is?)

**Comment by pkoutsogilas** [comment]
I'm using Avast Premium Securtity, I had to disable to following settings:

![image](https://user-images.githubusercontent.com/23651693/85830528-0a578100-b78d-11ea-9e85-0204293391e7.png)

and disable the firewall:

![image](https://user-images.githubusercontent.com/23651693/85830579-1fccab00-b78d-11ea-8497-d77407738209.png)

I still have to see if I can enable the firewall and create a custom rule.

**Comment by pkoutsogilas** [comment]
You can close this, see #1042

**Comment by freddydk** [comment]
Thanks
