### ISSUE TITLE
Extend timeout in Wait-NavContainerReady.ps1 or change to parameter

### ISSUE THREAD

**Issue by StHillmann** [Microsoft/navcontainerhelper#104]
especially when using a BacPac for creating a new container, it may take longer than 5 minutes to create the container. Please extend the timeout for Wait-NavContainerReady or change it into a parameter.

**Comment by freddydk** [comment]
0.2.7.3 has been uploaded and the timeout is now 30 minutes.
I am likely to change this later to handle bacpacs better, but for now, this should work (hopefully)
