### ISSUE TITLE
Mount-NavTenant Error

### ISSUE THREAD

**Issue by Andrii-Soroka** [microsoft/navcontainerhelper#1040]
When I try to mount new tenant database restored from bacpac as described in https://freddysblog.com/2019/11/04/using-sql-server-on-the-host/ I get error
The following SQL error was unexpected:
The transaction operation cannot be performed because there are pending requests working on this transaction.

at <ScriptBlock>, <No file>: line 15
The following SQL error was unexpected:
The transaction operation cannot be performed because there are pending requests working on this transaction.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.6\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Mount-NAVTenant], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/MyData,Microsoft.Dynamics.Nav.Management.Cmdlets.MountNavTenant

**Comment by freddydk** [comment]
Where do you have the .bacpac from?
Is there anything in the eventlog? (get-navcontainereventlog)

**Comment by freddydk** [comment]
Please reopen and provide more info if the problem persists
