### ISSUE TITLE
Create ARM-VM with Docker and AAD failed

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/navcontainerhelper#1043]
Hi,
I tried to create a new VM for Buisiness Central using aka.ms/getbc fpr BC 14 by using AAD-Authorization.
But when navcontainerhelper wants to create the Aad Apps it failed with the following error message:

```
<font color="Gray">1:18:58 AM Creating Aad Apps for Office 365 integration</font>
<font color="Red">1:19:16 AM Error occurred while executing NewApplication 
Code: Request_BadRequest
Message: One or more properties contains invalid values.
RequestId: 1d052078-1404-4bfc-804b-d459ef02eff7
DateTimeStamp: Thu, 25 Jun 2020 23:19:16 GMT
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
```

Mybe this occured by change the name of Office 365 to Microsoft 365 and thereby REST-Api was changed.

**Comment by StefanMartinEnjoy** [comment]
Hi Freedy,

still the same error message by using latest BC14-de container.

Regards Stefan

**Comment by StefanMartinEnjoy** [comment]
and same by using business central 16.2

`<font color="Gray">12:29:33 PM Version 16.2.13509.13779</font>
<font color="Gray">12:29:33 PM Locale de-DE</font>
<font color="Gray">12:29:33 PM Running mcr.microsoft.com/businesscentral/onprem:de-ltsc2019 (this will take a few minutes)</font>
<font color="Red">12:38:11 PM The remote server returned an error: (401) Unauthorized.</font>
<font color="Red">12:38:11 PM at Invoke-NavContainerApi, C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.7\Api\Invoke-NavContainerApi.ps1: line 154</font>
<font color="Red">12:38:11 PM at Get-NavContainerApiCompanyId, C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.7\Api\Get-NavContainerApiCompanyId.ps1: line 63</font>
<font color="Red">12:38:11 PM at <ScriptBlock>, C:\demo\SetupNavContainer.ps1: line 295</font>
<font color="Red">12:38:11 PM at <ScriptBlock>, C:\DEMO\SetupVm.ps1: line 289</font>
<font color="Red">12:38:11 PM at <ScriptBlock>, <No file>: line 1</font>`

**Comment by freddydk** [comment]
I will look into this sometime next week.
Until then, you would have to use Username/Password auth - or you can setup the VM with username password and change to AAD manually afterwards.

**Comment by StefanMartinEnjoy** [comment]
Thanks for your answer.
How do I change to AAD afterwards. Is there also a skript or a BLOG where I can read ist.

**Comment by freddydk** [comment]
That would be like doing it on-premise - there are documentation articles about that.

**Comment by StefanMartinEnjoy** [comment]
The problem occured, because the aad app already exissts.
The VM get wrong by updates. Thereby I deleted the VM and wanted to recreate it by using the same (old) name.
But, I did the same in the past severla times. So I think something has changed that now I get that error message.

**Comment by freddydk** [comment]
Could it be that upper/lowercase wasn't the same?
The code does this:

    # Remove "old" AD Application
    Get-AzureADApplication -All $true | Where-Object { $_.IdentifierUris.Contains($appIdUri) } | Remove-AzureADApplication

I can change it to do a case insensitive contains.

**Comment by freddydk** [comment]
Will assume that this fixed the issue

**Comment by StefanMartinEnjoy** [comment]
I think, now, it works.
