### ISSUE TITLE
[Suggestion] Static Artifact URL for latest artifact

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#1044]
Currently we use a yaml template in our pipelines for the creation of the BC container.
This template had the image (+tags) as parameter.
Now we want to change it to the new artifacts.
The current sandbox image can only be determined at pipeline runtime, so we can't use it at queue time and therefore not in the pipeline template.

Wouldn't it be an idea to publish the latest sandbox artifact urls via a static url?
Something like this:
aka.ms/getbcsandboxartifact_us
aka.ms/getbcsandboxartifact_en
aka.ms/getbcsandboxartifact_us_nextminor (insider only)
aka.ms/getbcsandboxartifact_us_nextmajor (insider only)

**Comment by freddydk** [comment]
I would rather not be the one having to maintain this.
If you have a look here: https://dev.azure.com/businesscentralapps/_git/BingMaps
I have done it like this:

I used to have a setting called imageName to point to the image to use.
Now, I have an artifact (not artifact Url).

Example:

"artifact": "bcartifacts/sandbox/16.2.13509.14082/us/Latest",

This string is split by /'s and these values are passed to Get-BcArtifactUrl and the first artifactUrl returned is the one used, like:

```
$segments = "$artifact/////".Split('/')
$artifactUrl = Get-BCArtifactUrl -storageAccount $segments[0] -type $segments[1] -version $segments[2] -country $segments[3] -select $segments[4] -sasToken $env:InsiderSasToken | Select-Object -First 1
```
artifact for nextminor is "bcinsider/sandbox//us/SecondToLastMajor"
artifact for nextmajor is "bcinsider/sandbox//us/Latest"

**Comment by ChrisBlankDe** [comment]
good idea. thanks

definitely better than having to update any static urls

**Comment by freddydk** [comment]
this was the reason for the strange SecondToLastMajor thingy - will also update the HOL and the hello world repo.
