### ISSUE TITLE
Get-BCArtifactUrl -storageAccount bcinsider not supported yet?

### ISSUE THREAD

**Issue by hsiungw** [microsoft/navcontainerhelper#1045]
**Describe the issue**
What is the way moving forward to access the insider build? As I have tried -storageAccount bcinsider but it does not seems to be supported yet?

**Scripts used to create container and cause the issue**
Get-BCArtifactUrl -storageAccount bcartifacts
https://bcartifacts.azureedge.net/sandbox/16.2.13509.14155/w1
PS C:\> Get-BCArtifactUrl -storageAccount bcinsider
Invoke-RestMethod : ResourceNotFoundThe specified resource does not exist.
RequestId:3b82255c-b01e-0067-589d-4be369000000
Time:2020-06-26T09:36:19.4885001Z
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.8\Misc\Get-BcArtifactUrl.ps1:86 char:21
+ ... $Response = Invoke-RestMethod -Method Get -Uri "$GetListUrl$nextMarke ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by freddydk** [comment]
You will need a sastoken which will make available on collaborate later today/tonight.

**Comment by freddydk** [comment]
Package with title Working with Business Central Insider Builds is available on http://aka.ms/collaborate now.
