### ISSUE TITLE
Unpacking platform artifact issue

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/navcontainerhelper#1047]
**Describe issue**

I could not success to unpack platrofm artifact. The same problem was with application artifact, and after few times, he  success to unpack application artifact. Between problem with unpacking, I also receive this message (few times) while I was trying to download artifacts.

> Downloading C:\Temp\ba8562d5-92b7-4046-88cc-b858ae507029.zip
> Retrying download...
> Downloading C:\Temp\ba8562d5-92b7-4046-88cc-b858ae507029.zip
> Download-File : Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out."
> At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.8\Misc\Download-Artifacts.ps1:129 char:21
> + ...             Download-File -sourceUrl $platformUrl -destinationFile $p ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
>     + FullyQualifiedErrorId : WebException,Download-File

**Scripts used to create container and cause the issue**

> $artifactUrl = Get-BCArtifactUrl -version 16.2 -country is -select Latest -type OnPrem
> $containerName = "IcelandCloud"
> $auth = "Windows"
> $licenseFile = "C:\BC16.flf"
> New-NavContainer `
>         -containerName $containerName `
>         -accept_eula `
>         -accept_outdated `
>         -assignPremiumPlan `
>         -auth $auth `
>         -artifactUrl $artifactUrl `
>         -includeAL `
>         -isolation hyperv `
>         -licenseFile $licenseFile `
>         -restart no `
>         -shortcuts Desktop `
>         -updateHosts `
>         -alwaysPull
> 

**Full output of scripts**

> NavContainerHelper is version 0.7.0.8
> NavContainerHelper is running as administrator
> Host is Microsoft Windows 10 Enterprise - 1909
> Docker Client Version is 18.09.11
> Docker Server Version is 18.09.11
> Removing C:\ProgramData\NavContainerHelper\Extensions\IcelandCloud
> Pulling image mcr.microsoft.com/dynamicsnav:10.0.18363.836-generic
> 10.0.18363.836-generic: Pulling from dynamicsnav
> Digest: sha256:cbc86fccc7acc78d13075a5d64b70d60ec197f507eb833830c5bdf9e5362905a
> Status: Image is up to date for mcr.microsoft.com/dynamicsnav:10.0.18363.836-generic
> Using image mcr.microsoft.com/dynamicsnav:10.0.18363.836-generic
> Downloading platform artifact /onprem/16.2.13509.13779/platform
> Downloading C:\Temp\71a190ed-7b2f-4df2-b78c-b3776c082bed.zip
> Unpacking platform artifact
> Remove-Item : Cannot find path 'C:\bcartifacts.cache\onprem\16.2.13509.13779\platform-tmp\Applications\APIV1\Source' because it does not exist.

Did I doing something wrong?

**Comment by freddydk** [comment]
I don't have a timeout on the download and it looks like the download on your machine is taking longer than the standard timeout causing this issue.
I will fix this in the next NavContainerHelper (probably shipped tomorrow morning).
