### ISSUE TITLE
Ability to update password when using Windows Authentication

### ISSUE THREAD

**Issue by KFrellsen** [Microsoft/navcontainerhelper#105]
Hi.

I changed my password for my windows login yesterday and after that the Windows authitication didn't work anymore (I know it's because docker uses a local user with the same username and password) however it would be nice if we could update the password for the user in the container and maintaining the Windows Authentication.

**Comment by freddydk** [comment]
If you open the PowerShell prompt of the container and run this:

$credential = Get-Credential
Set-LocalUser -Name $credential.UserName -Password $credential.Password

That should do the trick

**Comment by KFrellsen** [comment]
Thank you Freddy for the speedy reply.
