### ISSUE TITLE
The name resolution inside a container to external services does not work (Kaspersky Endpoint Security)

### ISSUE THREAD

**Issue by Sven-Niehus** [microsoft/navcontainerhelper#1050]
**Describe the issue**
After creating a new BC container the container is not able to resolve domain names via DNS.

**Scripts used to create container and cause the issue**
```PowerShell
$containerName = "BC"

$artifactType = "Sandbox"
$artifactCountry = "de"
$artifactVersion = ""
$artifactSelect = "Latest"
$artifactUrl = Get-BCArtifactUrl -type $artifactType `
				-country $artifactCountry `
				-version $artifactVersion `
				-select $artifactSelect;
				
$auth = "NavUserPassword"

$licenseFile = "***"
$UserName = "***"
$Password = "***"

$includeCSide = $false
$includeTestToolkit = $true
$useSSL = $false
$pull = $true

$Credential = New-Object pscredential -ArgumentList $UserName , (ConvertTo-SecureString -String $Password -AsPlainText -Force);

Remove-Module navcontainerhelper -Force;
Install-Module navcontainerhelper -Force;
Import-Module navcontainerhelper -Force -DisableNameChecking;
Remove-BCContainer -containerName $containerName -ErrorAction Ignore;


New-BCContainer -containerName $ContainerName `
	-artifactUrl $artifactUrl `
	-useBestContainerOs `
	-licenseFile $licenseFile `
	-auth $auth `
	-useSSL:$useSSL `
	-Credential $Credential `
	-includeCSide:$includeCSide `
	-accept_eula `
	-accept_outdated `
	-includeTestToolkit:$includeTestToolkit `
	-EnableTaskScheduler:$enableTaskScheduler `
	-alwaysPull:$pull `
	-dns "8.8.8.8";
```

**Full output of scripts**
```
NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
...
```

**Example**
The following source code fails with this error message: 
![image](https://user-images.githubusercontent.com/9822857/85979460-d4123f80-b9e0-11ea-8551-af880a40bf19.png)
```
pageextension 50100 CustomerListExt extends "Customer List"
{
    trigger OnOpenPage();
    var
        Client: HttpClient;
        Response: HttpResponseMessage;
        Content: HttpContent;
        ContentText: Text;
        ContentHeaders: HttpHeaders;
    begin
        Client.Get('https://jsonplaceholder.typicode.com/posts/1', Response);
        Content := Response.Content;
        Content.ReadAs(ContentText);
        Content.GetHeaders(ContentHeaders);
        Message('ContentText: ' + ContentText);
    end;
}
```
My host has no problem with the name resolution:
```PowerShell
C:\Users\niehus> nslookup
Standardserver:  ***
Address:  192.168.***.***

> jsonplaceholder.typicode.com
Server:  ***
Address:  192.168.***.***

Nicht autorisierende Antwort:
Name:    jsonplaceholder.typicode.com
Addresses:  2606:4700:3033::681c:1319
          2606:4700:3032::ac43:818d
          2606:4700:3030::681c:1219
          104.28.19.25
          104.28.18.25
          172.67.129.141
```
but nslookup fails on the container:
```PowerShell
PS C:\> nslookup
DNS request timed out.
    timeout was 2 seconds.
Default Server:  UnKnown
Address:  192.168.176.1

> jsonplaceholder.typicode.com
Server:  UnKnown
Address:  192.168.176.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out
```

**Additional context**
- Related to #1042

**Comment by Sven-Niehus** [comment]
This screen does show up and I allowed all requests from the extension:
![image](https://user-images.githubusercontent.com/9822857/85980246-518a7f80-b9e2-11ea-90f7-1d25d37e3ec5.png)

**Comment by freddydk** [comment]
If you inside the container write

ping www.google.com

Does that resolve? (probably not)

The problem is likely on your machine and it is very hard for me to troubleshoot.

If you spin up a standard Windows Servercore image like:

docker run --dns "8.8.8.8" -it mcr.microsoft.com/windows/servercore:ltsc2019 cmd

and write

ping www.google.com

does that resolve? (probably not)

BTW - on my machine (in a container) it looks like this:
![image](https://user-images.githubusercontent.com/10775043/85981063-d4600a00-b9e3-11ea-91ce-9c86bc220ab1.png)

My assumption is that you have to look at firewalls, antivirus, network protection things etc.

**Comment by Sven-Niehus** [comment]
On my machine the resolution inside the Windows Server Core image does work: 
```PowerShell
C:\Users\niehus> docker run --dns "8.8.8.8" -it mcr.microsoft.com/windows/servercore:ltsc2019 cmd
Unable to find image 'mcr.microsoft.com/windows/servercore:ltsc2019' locally
ltsc2019: Pulling from windows/servercore
4612f6d0b889: Pull complete
666079ee0460: Pull complete
Digest: sha256:0594b3bb67e2b5e57ab4414d7ce012a72582a6094b04b536c421ea1a23b7e7c7
Status: Downloaded newer image for mcr.microsoft.com/windows/servercore:ltsc2019
Microsoft Windows [Version 10.0.17763.1282]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\>nslookup
Default Server:  UnKnown
Address:  192.168.176.1

> google.com
Server:  UnKnown
Address:  192.168.176.1

*** UnKnown can't find google.com: Server failed
> server 8.8.8.8
Default Server:  [8.8.8.8]
Address:  8.8.8.8

> google.com
Server:  [8.8.8.8]
Address:  8.8.8.8

Non-authoritative answer:
Name:    google.com
Addresses:  2a00:1450:4001:820::200e
          216.58.208.46
```
and on my host it works as well:
```PowerShell
C:\Users\niehus> nslookup
Standardserver: ***
Address:  192.168.***.***

> google.com
Server:  ***
Address:  192.168.***.***

Nicht autorisierende Antwort:
Name:    google.com
Addresses:  2a00:1450:400e:800::200e
          216.58.214.14

> server 8.8.8.8
Standardserver:  dns.google
Address:  8.8.8.8

> google.com
Server:  dns.google
Address:  8.8.8.8

Nicht autorisierende Antwort:
Name:    google.com
Addresses:  2a00:1450:4001:820::200e
          216.58.205.238
```
it only does not work inside a BC container:
```PowerShell
PS C:\> nslookup
DNS request timed out.
    timeout was 2 seconds.
Default Server:  UnKnown
> google.com
Server:  UnKnown
Address:  192.168.176.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out
> server 8.8.8.8
DNS request timed out.
    timeout was 2 seconds.
Default Server:  [8.8.8.8]
Address:  8.8.8.8

> google.com
Server:  [8.8.8.8]
Address:  8.8.8.8

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to [8.8.8.8] timed-out
```

**Comment by freddydk** [comment]
Did you try with -isolation hyperv?

**Comment by freddydk** [comment]
I have taken your script from above and run it on my machine - and everything works fine.
Also there are 1000s of machines running pipelines with containers where dns resolutions is a must, so i am looking for differences in your setup and everybody else.
Reason for suggesting hyperv is that when you are using docker run above - you get the windows servercore in hyperv mode.

**Comment by pkoutsogilas** [comment]
@Sven-Niehus are you running any anti-virus software that includes a builtin firewall (additionally to the windows firewall). I turned the firewall of the anti-virus off, that solved the my issue with no connection could be made to outside systems.

**Comment by Sven-Niehus** [comment]
We are using Kasperksy Endpoint Security. I already asked IT if they can disable Kaspersky for troubleshooting purposses. I will report back once I can test without Kaspersky

**Comment by Sven-Niehus** [comment]
I can confirm that it is working after disabling Kaspersky. 

@freddydk do you maybe know which processes should be whitelisted?

**Comment by freddydk** [comment]
Unfortunately no, I don't run Kaspersky.
Googling docker and kaspersky yields a lot of results.
One quick one could be this one (if your network card inside the container isn't right).

Also if there are restrictions on your network profiles (i.e. public), consider changing the default "unidentified network" for the "vEthernet (DockerNAT)" card to private via this PowerShell command before doing the above:

Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private

**Comment by freddydk** [comment]
Will close this one - nothing I can do about this.
The troubleshooting guide here: https://freddysblog.com/2020/10/12/troubleshooting-business-central-on-docker/ is the closest I can get to a solution on this.
