### ISSUE TITLE
Cannot download symbols

### ISSUE THREAD

**Issue by peterz84** [microsoft/navcontainerhelper#1051]
Just testing out the new New-BcContainer with ArtifactURL functionality, which is great!

Used this script:
```
$artifactUrl` = Get-BCArtifactUrl -country nl -storageAccount bcinsider -sasToken $sasToken 
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$sasToken = "somethingverysecret"
New-BcContainer `
    -accept_eula `
    -containerName BC17200629 `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -updateHosts

```

Output:

> NavContainerHelper is version 0.7.0.9
NavContainerHelper is running as administrator
Host is Microsoft  - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Removing C:\ProgramData\NavContainerHelper\Extensions\BC17200629
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.900-generic
Creating Container BC17200629
Version: 17.0.14291.0-NL
Style: sandbox
Generic Tag: 0.1.0.6
Container OS Version: 10.0.18363.900 (1909)
Host OS Version: 10.0.18363.900 (1909)
Using locale nl-NL
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\BC17200629\my:
>- AdditionalOutput.ps1
>- MainLoop.ps1
>- SetupVariables.ps1
>- updatehosts.ps1
Creating container BC17200629 from image mcr.microsoft.com/dynamicsnav:10.0.18363.900-generic
732072be114f5a95ab3623a260ce2fc551f1a95467b7cfd2f7a65fcc60e46a6c
Waiting for container BC17200629 to be ready
Using artifactUrl https://bcinsider.azureedge.net/sandbox/17.0.14291.0/nl
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying ConfigurationPackages
Copying Extensions
Copying Applications.*
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.*
Copying ReportBuilder
Determining Database Collation
Changing Database Server Collation to Latin1_General_100_CS_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing CRONUS license file
Stopping Business Central Service Tier
Installation took 175 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.25 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.25 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.29.128.1 in container hosts file
Starting Container
Hostname is BC17200629
PublicDnsName is BC17200629
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 0AD7F13AE24879BA09C9FF967B77DB787913681B
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.29.135.245
Container Hostname  : BC17200629
Container Dns Name  : BC17200629
Web Client          : http://BC17200629/BC/
Dev. Server         : http://BC17200629
Dev. ServerInstance : BC
Setting BC17200629 to 172.29.135.245 in host hosts file
>
>Files:
>http://BC17200629:8080/ALLanguage.vsix
>
>Initialization took 71 seconds
Ready for connections!
Reading CustomSettings.config from BC17200629
Creating Desktop Shortcuts for BC17200629
Container BC17200629 successfully created

Then tried to download symbols, but it keeps asking voor username/password. It must be something I'm missing, but what is it?
I can run the web client successfully.

Launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://BC17200629",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
        }
    ]
}
```

**Comment by freddydk** [comment]
Did you try to clear credentials cache in VS Code - and how does your app.json look?

**Comment by peterz84** [comment]
Yes sir, I did. 

My app.json look like this:

> {
>   "id": "baadeb2d-024c-44b5-951a-146ab48f442c",
>   "name": "BC17",
>   "publisher": "Default publisher",
>   "version": "1.0.0.0",
>   "brief": "",
>   "description": "",
>   "privacyStatement": "",
>   "EULA": "",
>   "help": "",
>   "url": "",
>   "logo": "",
>   "dependencies": [],
>   "screenshots": [],
>   "platform": "17.0.0.0",
>   "application": "17.0.0.0",
>   "idRanges": [
>     {
>       "from": 50100,
>       "to": 50149
>     }
>   ],
>   "contextSensitiveHelpUrl": "https://BC17.com/help/",
>   "showMyCode": true,
>   "runtime": "6.0"
> }

**Comment by peterz84** [comment]
Output still the same:
```
[2020-06-29 16:06:00.71] Using user name and password authentication. User name used is: 'admin'.
[2020-06-29 16:06:00.71] Sending request to http://bc17200629:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.0.0
[2020-06-29 16:06:00.71] Sending request to http://bc17200629:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0
```

**Comment by peterz84** [comment]
Ok got a little further. Restarted PC because I had a VPN open previously. After shutting down VPN, still didnt work, but after restart of PC it kind of worked.

Output:

> [2020-06-29 16:38:57.00] Using reference symbols cache path: c:\Users\Peter-Paul Eckhardt\Documents\AL\BC17\./.alpackages
> [2020-06-29 16:38:57.01] Sending request to http://bc17200629:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=17.0.0.0
> [2020-06-29 16:38:57.01] Sending request to http://bc17200629:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0
> [2020-06-29 16:38:57.03] The request for path /BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
> [2020-06-29 16:38:57.03] The following dependencies will be queried for propagated dependencies:
> System Application by Microsoft (17.0.0.0)
> Base Application by Microsoft (17.0.0.0)
> [2020-06-29 16:38:57.03] Sending request to http://bc17200629:7049/BC/dev/packages?publisher=Microsoft&appName=System Application&versionText=17.0.0.0
> [2020-06-29 16:38:57.03] Sending request to http://bc17200629:7049/BC/dev/packages?publisher=Microsoft&appName=Base Application&versionText=17.0.0.0
> [2020-06-29 16:38:58.71] Could not download reference symbols. Please ensure that:
> 1. The correct server name and instance are specified in the launch.json file.
> 2. The correct application version is specified in the app.json file.
> 3. The dependencies are correctly specified in the app.json file.

But the files are downloaded?!
![image](https://user-images.githubusercontent.com/25202313/86019688-2e35f380-ba27-11ea-8397-0febd30c4bb6.png)

**Comment by freddydk** [comment]
I think the platform should be 16.0.0.0 still

**Comment by freddydk** [comment]
Indeed - platform is still version 16.
![image](https://user-images.githubusercontent.com/10775043/86042373-5a616c80-ba47-11ea-93f8-14d67021ce4f.png)

**Comment by peterz84** [comment]
Thanks, that was it!
