### ISSUE TITLE
Cannot unpack platform artifact

### ISSUE THREAD

**Issue by tomasevicstefan** [microsoft/navcontainerhelper#1052]
**Describe the issue**
Application artifact is downloaded and unpacked. Platform artifact is downloaded in temp folder, but when it start to unpack it goes into this error.

**Scripts used to create container and cause the issue**
```
$artifactUrl = Get-BCArtifactUrl -version 16.2 -country is -select Latest -type OnPrem
$containerName = "IcelandCloud"
$auth = "Windows"
$licenseFile = "C:\License\license.flf"
New-BCContainer `
        -containerName $containerName `
        -accept_eula `
        -accept_outdated `
        -assignPremiumPlan `
        -auth $auth `
        -artifactUrl $artifactUrl `
        -includeAL `
        -isolation hyperv `
        -licenseFile $licenseFile `
        -restart no `
        -shortcuts Desktop `
        -updateHosts `
        -alwaysPull
```

**Full output of scripts**
```
PS C:\WINDOWS\system32> $artifactUrl = Get-BCArtifactUrl -version 16.2 -country is -select Latest -type OnPrem
$containerName = "IcelandCloud"
$auth = "Windows"
$licenseFile = "C:\License\license.flf"
New-BCContainer `
        -containerName $containerName `
        -accept_eula `
        -accept_outdated `
        -assignPremiumPlan `
        -auth $auth `
        -artifactUrl $artifactUrl `
        -includeAL `
        -isolation hyperv `
        -licenseFile $licenseFile `
        -restart no `
        -shortcuts Desktop `
        -updateHosts `
        -alwaysPull
NavContainerHelper is version 0.7.0.9
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 18.09.11
Docker Server Version is 18.09.11
Removing C:\ProgramData\NavContainerHelper\Extensions\IcelandCloud
Pulling image mcr.microsoft.com/dynamicsnav:10.0.18363.836-generic
10.0.18363.836-generic: Pulling from dynamicsnav
Digest: sha256:cbc86fccc7acc78d13075a5d64b70d60ec197f507eb833830c5bdf9e5362905a
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.836-generic
Downloading platform artifact /onprem/16.2.13509.13779/platform
Downloading C:\Temp\bb479f40-48a0-4d93-95e9-53d0167169af.zip
Unpacking platform artifact
Remove-Item : Cannot find path 'C:\bcartifacts.cache\onprem\16.2.13509.13779\platform-tmp\Applications\APIV1\Source' because it does not exist.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:411 char:46
+ ...                 $expandedItems | % { Remove-Item $_ -Force -Recurse }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\bcartifacts....ns\APIV1\Source:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
...
```

**Screenshots**
![1](https://user-images.githubusercontent.com/31925856/86103665-57a15e80-babd-11ea-8809-18855030299b.png)

**Comment by freddydk** [comment]
Could you try to run Flush-ContainerHelperCache and then retry?

**Comment by tomasevicstefan** [comment]
Same thing, 

He download and unpack application artifact, and download platform artifact, but when it start to unpack it, at some point he throw an error.

**Comment by tomasevicstefan** [comment]
I saw it in temp folder that platform artifact zip file is around 607mb size. I suppose that is the right size of file?

**Comment by freddydk** [comment]
If you download the file manually - can you then extract it?
https://bcartifacts.azureedge.net/onprem/16.2.13509.13779/platform
(rename to platform.zip after download)

**Comment by freddydk** [comment]
next thing you could try would be

Download-Artifacts -artifactUrl https://bcartifacts.azureedge.net/onprem/16.2.13509.13779/is -includePlatform -basePath c:\temp

works fine here

**Comment by tomasevicstefan** [comment]
Downloaded manually and extract it without any problem.

But Download-Artifacts command cannot unpack downloaded package, this time for application artifact

![1](https://user-images.githubusercontent.com/31925856/86129915-b2e64780-bae3-11ea-95d6-6585d7a7b38f.png)

**Comment by freddydk** [comment]
That is very very strange.
Are you running any antivirus software that could cause this?

**Comment by tomasevicstefan** [comment]
No, we are on standard windows security features.

**Comment by tomasevicstefan** [comment]
I successed to download artifacts with Download-Artifacts command, and after that to create container. I suppose that the problem was in my network or something like that.

What is the reason to download platform artifact while creating new container, if I already downloaded artifacts with download-artifacts command?

Thanks for help Freddy!

**Comment by freddydk** [comment]
Download artifacts with -includeplatform should download once and not needed again.
Using it all the time.
Will close this as the original problem is solved.
