### ISSUE TITLE
Cannot create a docker container with image BC 14 CU13...

### ISSUE THREAD

**Issue by malue1991** [microsoft/navcontainerhelper#1053]
Hey guys,

I do not know why it is not working. I had never this kind of errors during the creation of a docker container....

This is my script:
![grafik](https://user-images.githubusercontent.com/59683024/86223956-833d4b00-bb88-11ea-8ba0-2c86949202ca.png)

That is the error stack:
![grafik](https://user-images.githubusercontent.com/59683024/86224089-b7187080-bb88-11ea-8b19-e3027766c2c6.png)
It says: Error during the execution of program"docker": No application is assigned to the specified file.

How can I solve this?

Thank you ;)

**Comment by freddydk** [comment]
Do you have docker installed?

**Comment by malue1991** [comment]
Yes, I have^^ and it is also running. That is why I was able to pull the image for my docker container.

**Comment by freddydk** [comment]
For some reason, your powershell prompt cannot run docker.exe - I don't know why

**Comment by malue1991** [comment]
One month ago, it could...maybe there was meanwhile a windows update...

**Comment by freddydk** [comment]
I think the problem is the executionpolicy - you would need to use unrestricted to get NavContainerHelper to work I think.

**Comment by freddydk** [comment]
Did you resolve the issue?

**Comment by malue1991** [comment]
Instead of using Set-ExecutionPolicy remotesigned -Force I used Set-ExecutionPolicy unrestricted -Force, but I got the same error message...is that what you meant?

**Comment by freddydk** [comment]
Are you running as administrator?
Are you running the 64 bit version of PowerShell?
What happens if you run 
docker version

**Comment by malue1991** [comment]
I run the script as an administrator.
I don't know if I'm using the 64 version. The PowerShell is just called Windows PowerShell ISE. 
What do you mean by "What happens if you run docker version"? Do you mean a special command?

**Comment by freddydk** [comment]
In PowerShell ISE - run

docker version

**Comment by malue1991** [comment]
I run the command in cmd, because in PowerShell the command is not known.

That is the output I get from the cmd:

![grafik](https://user-images.githubusercontent.com/59683024/86564801-14386b80-bf67-11ea-9f1b-818f0bc34720.png)

**Comment by freddydk** [comment]
Well - that is the problem.
If you cannot run docker inside PowerShell - there is something wrong with your PowerShell / Docker installation.

Unfortunately that is not something I can help you troubleshoot on a distance.
When creating a container, it needs to be able to run docker.exe in PowerShell (hence my first question - is it installed...)

When you can run docker version inside PowerShell ISE - then you can probably also create a container.

**Comment by malue1991** [comment]
But one month ago, I have installed in the same way my docker container^^ and it worked...

**Comment by freddydk** [comment]
back then - docker.exe worked in PowerShell.
I cannot tell you what you have changed since then on your computer.
You could try to uninstall Docker and re-install.

**Comment by malue1991** [comment]
Ok, could be a way.
Now I gave in: "docker run version" and it says: unable to find image 'version:latest' locally. But I think it knows docker.
The PowerShell is 32bit.

**Comment by freddydk** [comment]
You cannot create a Business Central container in 32bit PowerShell.
you need to make docker.exe work in 64it

**Comment by freddydk** [comment]
and docker run version will try to run an image called version
docker version will tell you the docker version
