### ISSUE TITLE
New BC Container using artifacts doesn't include System Application Test Library

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#1056]
Hi @freddydk!

We use an adapted version of your [Hello World CI/CD](https://dev.azure.com/businesscentralapps/HelloWorld).
According to your latest [posts](https://community.dynamics.com/business/b/freddysblog/posts/run-business-central-in-docker-using-a-custom-generic-image) I switched from a regular docker container for Business Central to a Generic image with artifacts.

In my case I am using "bcartifacts/onprem/16/de/Latest" as artifact which works so far.

My problem: [Create-Container.ps1](https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2FCreate-Container.ps1) only installs the following three Test Apps:
- Publishing C:\ProgramData\NavContainerHelper\Extensions\Industry28\_Microsoft_Any.app
- Publishing C:\ProgramData\NavContainerHelper\Extensions\Industry28\_Microsoft_Library Assert.app
- Publishing C:\ProgramData\NavContainerHelper\Extensions\Industry28\_Microsoft_Test Runner.app

these three apps are missing:
- Microsoft_System Application Test Library.app
- Microsoft_Tests-TestLibraries.app
- Microsoft_System Application Test.app

Therefore the compilation of my own test app fails.

Do I require another artifact?

**Comment by freddydk** [comment]
change -includeTestFrameworkOnly to -includeTestLibrariesOnly in the Create-Container.ps1

**Comment by ralf-escher** [comment]
`Publishing C:\ProgramData\NavContainerHelper\Extensions\Industry28\_Microsoft_System Application Test Library.app `

Works! That was fast...
