### ISSUE TITLE
Suggestion ShowMyCode switch in Get-NavContainerAppRuntimePackage

### ISSUE THREAD

**Issue by jefkeers** [microsoft/navcontainerhelper#1057]
In the standard MS script you can add the switch ShowMyCode, it will be handy to do the same for the containerscripts

https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.apps.management/get-navappruntimepackage?view=businesscentral-ps-16

**Comment by freddydk** [comment]
Shipped in 0.7.0.9
