### ISSUE TITLE
Extend New-CsideDevContainer Cmdlet with Database parameters

### ISSUE THREAD

**Issue by PierrevdMoosdijk** [Microsoft/navcontainerhelper#106]
Hi,

Can you please extend the New-CsideDevContainer cmdlet. with the 4 databaseparameters ( databaseServer, databaseInstance, databaseName  and databaseCredential) that are available in the New-NavContainer cmdlet.

**Comment by freddydk** [comment]
Just use New-NavContainer with -includeCSIDE and you have the same thing (see the source here: 

https://github.com/Microsoft/navcontainerhelper/blob/master/ContainerHandling/New-CSideDevContainer.ps1)

New-CSideDevContainer is likely to be removed in the future.
