### ISSUE TITLE
Folders everywhere - but never where I want them :)

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#1060]
**Describe the issue**
I got used to ProgramData navcontainerhelper as the "root" folder for - well - navcontainer helper. I collect while doing internal education quite some backfire why it needs to be the C drive. and if it can be moved somewhere else. Never went into it so I simply said: no - not possible :)

So now is a new kid in town, and it is on the root of my C drive! I could have understood that it will be ProgramData again but for some reason it is not. And again it is C ... for a "version data grave" (quite likly if the further steps will form an image) that in a team would really make sense to get shared (again like an image) ...

so this is not an issue but a wish to get more control over the way navcontainer is maintaining its data =)
push the artifacts at least into the ProgramData folder would be nice. Being able to control where it actually ends up would be awesome!

**Comment by freddydk** [comment]
Originally I placed the artifacts cache under programdata\navcontainerhelper - but I ran into the 260 character file length limitation of PowerShell - so, it became the root.
I will create a way to configure things - until then, your only option is to either not use containerhelper or use images.

**Comment by KristofKlein** [comment]
Ah I see! Yes... that is a valid explanation for it! 

A good while ago I was playing around with New-PSDrive - maybe that could help?!

**Comment by hemisphera** [comment]
I stumbled across this too. I've dropped you a PR: #1069

**Comment by freddydk** [comment]
0.7.0.11 introduces a way to change this.

c:\bcartifacts.cache is default
if a config file c:\programdata\navcontainerhelper\navcontainerhelper.config.json exists - values in this overrides the default
$navcontainerhelperconfig.bcartifactscachefolder can override this in code as well - and code is king.

the format of the config file is:

{
    "bcartifactsCacheFolder":  "c:\\bcart.cache"
}
