### ISSUE TITLE
Container creation on Win10 required -isolation = hyperv

### ISSUE THREAD

**Issue by ABaludin** [microsoft/navcontainerhelper#1064]
Freddy that's the issue we are told about in Twitter.
New-NavContainer crushes if I not set -isolation = hyperv parameter.
My Win10 build is 1809. 
Docker desktop version 2.3.0.3

**Scripts used to create container and cause the issue**
```
$artifactUrl = Get-NavArtifactUrl -nav 2017 -country 'ru' -select latest
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)

new-navcontainer -accept_eula `
	            -containername nav2017 `
                -auth UserPassword `
                -credential $credential `
	            -artifactUrl $artifactUrl `
	            -includecside `
                -licensefile "c:\temp\lic.flf" `
                -updatehosts `
                -donotexportobjectstotext `
                -alwayspull

**Full output of scripts**
```
NavContainerHelper is version 0.7.0.9
NavContainerHelper is running as administrator
Host is Майкрософт Windows 10 Корпоративная - ltsc2019
Docker Client Version is 19.03.3
Docker Server Version is 19.03.8
Removing container nav2017
Removing nav2017 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\nav2017
Pulling image mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
10.0.17763.1282-generic: Pulling from dynamicsnav
Digest: sha256:e27e27b7f105252fc38316209078d8f6111a5cf6e55a8e273672945e6549eca7
Status: Image is up to date for mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
Using image mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
Creating Container nav2017
Version: 10.0.30284.0-ru
Style: onprem
Generic Tag: 0.1.0.6
Container OS Version: 10.0.17763.1282 (ltsc2019)
Host OS Version: 10.0.17763.1282 (ltsc2019)
Using locale ru-RU
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\nav2017\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container nav2017 from image mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
3a29e17da95edd803b89e01dc7765b9bcf0275a40638819ebfbe9f48c5db2bb8
Waiting for container nav2017 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/10.0.30284.0/ru
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing NAV
Starting Local SQL Server
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The remote computer refused the network connection.)
at <ScriptBlock>, C:\Run\navinstall.ps1: line 110
at <ScriptBlock>, C:\Run\start.ps1: line 209
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/10.0.30284.0/ru
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing NAV
Starting Local SQL Server
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The remote computer refused the network connection.)
at <ScriptBlock>, C:\Run\navinstall.ps1: line 110
at <ScriptBlock>, C:\Run\start.ps1: line 209
at <ScriptBlock>, <No file>: line 1
Initialization of container nav2017 failed
C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.9\ContainerHandling\Wait-NavContainerReady.ps1:44 знак:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... nav2017 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container nav2017 failed
...
```


Also error occurred with old-way container creation using -image parameter:

new-navcontainer -accept_eula `
	            -containername sb `
                -auth UserPassword `
                -credential $credential `
                -imageName mcr.microsoft.com/dynamicsnav:2017 `
	            -includecside `
	            -updatehosts `
                -donotexportobjectstotext `
                -alwayspull

Script output:
NavContainerHelper is version 0.7.0.9
NavContainerHelper is running as administrator
Host is Майкрософт Windows 10 Корпоративная - ltsc2019
Docker Client Version is 19.03.3
Docker Server Version is 19.03.8
Removing container sb
Removing sb from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\sb
Pulling image mcr.microsoft.com/dynamicsnav:2017-ltsc2019
2017-ltsc2019: Pulling from dynamicsnav
Digest: sha256:2988688b51113d927c90f5924aa9525c43f3b7b9c05536c6fe05b8dac1cc207b
Status: Image is up to date for mcr.microsoft.com/dynamicsnav:2017-ltsc2019
mcr.microsoft.com/dynamicsnav:2017-ltsc2019
Using image mcr.microsoft.com/dynamicsnav:2017-ltsc2019
Creating Container sb
Version: 10.0.30284.0-W1
Style: onprem
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1282 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\sb\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container sb from image mcr.microsoft.com/dynamicsnav:2017-ltsc2019
99b509112fdd04f23e06471430b633a8e192bbeefb44d7edd79ddcc7e9bffe9d
Waiting for container sb to be ready
Initializing...
Setting host.docker.internal to 192.168.1.100 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.100 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.112.1 in container hosts file
Starting Container
Hostname is sb
PublicDnsName is sb
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FE17E13AE3DE7F9B18971A9F674BB6467EBECDDB
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating Web Site
Creating Web Server Instance
Creating ManagementServicesPort and setting it to 7045
Creating http download site
Setting SA Password and enabling SA
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
at <ScriptBlock>, C:\Run\SetupSqlUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 183
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.docker.internal to 192.168.1.100 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.100 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.112.1 in container hosts file
Starting Container
Hostname is sb
PublicDnsName is sb
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FE17E13AE3DE7F9B18971A9F674BB6467EBECDDB
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating Web Site
Creating Web Server Instance
Creating ManagementServicesPort and setting it to 7045
Creating http download site
Setting SA Password and enabling SA
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)
at <ScriptBlock>, C:\Run\SetupSqlUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 183
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container sb failed
C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.9\ContainerHandling\Wait-NavContainerReady.ps1:44 знак:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container sb failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container sb failed


**Additional context**
If I add -isolation hyperv parameter - everything runs smoothly in both cases.

**Comment by freddydk** [comment]
This is likely due to compatibility problems between host and container.
You should try to do the same using artifacts, where it is possible to get the same build/release of the generic image to base the container on.
I will close this one.
Please open a new one if the problem persists using artifacts.
