### ISSUE TITLE
Error while using New-BCImage in Windows Server 2016 (10.0.14393) - "The variable '$useBestContainerOS' cannot be retrieved because it has not been set"

### ISSUE THREAD

**Issue by hsiungw** [microsoft/navcontainerhelper#1068]
**Describe the issue**
In Windows Server 2016 (10.0.14393), run New-BCImage 

**Screenshots**
![image](https://user-images.githubusercontent.com/16015694/86540417-c2c4b800-bf37-11ea-9464-243675deaf1d.png)

In New-NavImage.ps1, the variable $useBestContainerOS is only used in below.

![image](https://user-images.githubusercontent.com/16015694/86540452-f99ace00-bf37-11ea-8a36-2a5f13a9556f.png)

**Comment by freddydk** [comment]
Yeah, that is a copy/paste error - will be fixed in next version

**Comment by freddydk** [comment]
fixed in 0.7.0.11
