### ISSUE TITLE
Shortcut to WindowsClient using correct container ClientUserSettings.config

### ISSUE THREAD

**Issue by MicAlter31** [Microsoft/navcontainerhelper#107]
The created desktop shortcut does not contain the correct path to container-specific ClientUserSettings.config. This may cause problems when a local installation of NAV exists with a **different** ClientServiceCredentialType settings.

The simple solution is to add a commandline parameter to use the ClientUserSettings.config of the container:

**Currently created Desktop Shortcut**
"C:\ProgramData\NavContainerHelper\Extensions\nav2016cu3\Program Files\90\RoleTailored Client\Microsoft.Dynamics.Nav.Client.exe"

**Solution**
"C:\ProgramData\NavContainerHelper\Extensions\_{container}_\Program Files\_{navversion}_\RoleTailored Client\Microsoft.Dynamics.Nav.Client.exe" -settings:"C:\ProgramData\NavContainerHelper\Extensions\_{container}_\Program Files\_{navversion}_\RoleTailored Client\ClientUserSettings.config"

A problem could be that the whole command line is too large for a desktop shortcut. So the ClientUserSettings.config must be copied to another location. For  e.g. "C:\ProgramData\NavContainerHelper\Extensions\_{container}_\config"

**Comment by richardrobberse** [comment]
This is fixed in the latest version of the containerhelper 0.2.7.0.
