### ISSUE TITLE
New-BcContainer error:  The request is not supported

### ISSUE THREAD

**Issue by steveendow** [microsoft/navcontainerhelper#1098]
I used the New-BcContainerWizard to create a New-BcContainer script, based on this post:

https://freddysblog.com/2020/07/03/business-central-on-docker-script-generator/

I primarily used the wizard defaults, but chose to create a named image.

When I run the script, I get an error that says "The request is not supported".   

```
docker : hcsshim::CreateComputeSystem 430e5798fe9f22badd413f4c129ff25f20e33fd94f4d7ad40eed240e0b84ab9a: The request is not supported.
```

I've tried commenting out different parameters for New-BcContainer, but get the same error, resulting in what appears to be orphaned containers and images.

![image](https://user-images.githubusercontent.com/11199908/87099018-904be100-c1fd-11ea-9203-6be432e2c695.png)

**PS script:**

```
$containerName = 'sandbox1'
$password = 'P@ssword'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'us' -select 'Latest'
$licenseFile = 'c:\zdisks\business central\2020-06bcv16license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'mybc16' `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -dns '192.168.25.21' `
    -updateHosts
Setup-BcContainerTestUsers -containerName $containerName -Password $credential.Password -credential $credential
```

**Last portion of output:**

```
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\16.3.14085.14363\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\16.3.14085.14363\platform\Prerequisite Components\Microsoft Report Viewer 2015\ReportViewer.msi
Downloading c:\bcartifacts.cache\sandbox\16.3.14085.14363\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\16.3.14085.14363\platform\Prerequisite Components\Microsoft Report Viewer 2015\SQLSysClrTypes.msi
Downloading c:\bcartifacts.cache\sandbox\16.3.14085.14363\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Copying Platform Artifacts
Copy Database
Copy ConfigurationPackages
Copy Extensions
Copy Applications.*
c:\$TMP$-mybc16-sandbox-16.3.14085.14363-us
Sending build context to Docker daemon  1.868GB

Step 1/6 : FROM mcr.microsoft.com/dynamicsnav:10.0.17763.437-generic
 ---> c9779293490e
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/16.3.14085.14363/us
 ---> Running in 7a1ded183828
Removing intermediate container 7a1ded183828
 ---> ac235fecaf70
Step 3/6 : COPY my /run/
 ---> d5df05a299c8
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> d0ec30d0e948
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in 430e5798fe9f
docker : hcsshim::CreateComputeSystem 430e5798fe9f22badd413f4c129ff25f20e33fd94f4d7ad40eed240e0b84ab9a: The request is not supported.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.13\ContainerHandling\New-NavImage.ps1:294 char:1
+ docker build --isolation=$isolation --memory $memory --tag $imageName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (hcsshim::Create... not supported.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by steveendow** [comment]
I deleted all BC containers and images, including the generic image, and then ran the script again.  It completed successfully.

**Comment by freddydk** [comment]
Very strange.
The imagename parameter will save the image and that should actually be the safe route (like if the other one fails)
Could you dump the full output of the container generation when you leave out imagename?
Thanks

**Comment by steveendow** [comment]
I ran this script to create "sandbox3", without the imageName parameter.  The container was created successfully.

```
$containerName = 'sandbox3'
$password = 'P@ssword'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'us' -select 'Latest'
$licenseFile = 'c:\zdisks\business central\2020-06bcv16license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -updateHosts `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -dns '192.168.25.21' 
    #`
    #-imageName 'mybc16' 

Setup-BcContainerTestUsers -containerName $containerName -Password $credential.Password -credential $credential
```

![image](https://user-images.githubusercontent.com/11199908/87118729-f4d46380-c230-11ea-9f8d-51b69f2ba2c5.png)

Attached is the output from the successful container generation process.

[sandbox3 log.txt](https://github.com/microsoft/navcontainerhelper/files/4901068/sandbox3.log.txt)

**Comment by freddydk** [comment]
Your host is 10.0.17763.107 - that is a very very old un-updated Windows and that is likely the reason for this.
Could you try to add -isolation hyperv to the script when using -imagename to see whether that changes anything?
Thanks

**Comment by steveendow** [comment]
Thank you!

It looks like Windows Update had a few updates that failed, and that was preventing any new updates. 

I cleared out the failed updates, rebooted, then applied the latest 1809 update. 

It’s now on 17763.1282. 

Tomorrow I will delete all containers and images and try the script again.

**Comment by TRASERDanielGorski** [comment]
I had the same issue and I've changed "isolation" the from hyper-v to process.
I also updated docker on my windows-server by following this:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/set-up-environment?tabs=Windows-Server

**Comment by steveendow** [comment]
After installing the Windows Updates and getting on build 17763.1282, the New-BcContainer script is working properly with the imageName parameter.

The script no longer issues the warning about the Host OS mismatch!  Yeah!

![image](https://user-images.githubusercontent.com/11199908/87178371-de122900-c291-11ea-9d3e-23342c399a5c.png)

I learned several lessons from this and will be doing a video on it.

Thanks for the help Freddy!

**Comment by steveendow** [comment]
Issue resolved by installing Windows Updates, removing containers and generic image based on older Windows version, and then re-running the New-BcContainer script with the imageName parameter. 👍

**Comment by steveendow** [comment]
Issue resolved by installing Windows Updates, removing containers and generic image based on older Windows version, and then re-running the New-BcContainer script with the imageName parameter. 👍
