### ISSUE TITLE
Error using CSIDE

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/navcontainerhelper#11]
On a blank Windows server 2016, I installed containers using the navcontainerhelper, and when running C/SIDE, it gives me this error:
![image](https://user-images.githubusercontent.com/12088142/32485229-ec04fef2-c3a2-11e7-9aa6-5acd29d4b224.png)

**Comment by freddydk** [comment]
Correct - I do not currently install pre-reqs on the host - maybe I should.
They are here:
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
and
https://download.microsoft.com/download/3/A/6/3A632674-A016-4E31-A675-94BE390EA739/ENU/x64/sqlncli.msi

**Comment by waldo1001** [comment]
Could be yet another navcontainerhelper-function?  Install-navcsideprereqs or something?

If you want, I turn that into a function and create a (clean :)) pull request?

**Comment by freddydk** [comment]
Better would be to have an internal function, which checks whether pre-reqs are installed and if not - install them. This function should then be called from the new-navcontainer if -includeCSide switch is on.

**Comment by waldo1001** [comment]
Agreed.

**Comment by freddydk** [comment]
for now, I have included a section on this in my troubleshooting blog post
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/
and I have put it on the list of ideas for navcontainerhelper
