### ISSUE TITLE
Error $customConfig cannot be retrieved because it has not been set

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/navcontainerhelper#110]
When creating a container with -includeCSide and -shortcuts None the script throws the following error: The variable '$customConfig' cannot be retrieved because it has not been set.

This happens because the custom settings are only read when shortcuts -ne "none".
New-NavContainer.ps1 line 401 - customsettings are read.
New-NavContainer.ps1 line 443 - $customConfig is used without a read.

This occurs on the latest version (0.2.7.3)

**Comment by freddydk** [comment]
Thanks - will fix this asap

**Comment by richardrobberse** [comment]
Thanks :)

**Comment by freddydk** [comment]
Fixed in 0.2.7.4
