### ISSUE TITLE
Get-BestBcContainerImageName returns image name without ltsc2019

### ISSUE THREAD

**Issue by ernestasjuska** [microsoft/navcontainerhelper#1101]
**Describe the issue**
2004 is both tag for BC version (2020 Wave I) and Windows build 2004. Because of that cmdlet does not append ltsc2019 when it should.
See first `if` in https://github.com/microsoft/navcontainerhelper/blob/master/ContainerHandling/Get-BestNavContainerImageName.ps1.

**Example**

`Get-BestBcContainerImageName -imageName mcr.microsoft.com/businesscentral/onprem:2004` returns `mcr.microsoft.com/businesscentral/onprem:2004`,
but `Get-BestBcContainerImageName -imageName mcr.microsoft.com/businesscentral/onprem:1910` returns `mcr.microsoft.com/businesscentral/onprem:1910-ltsc2019`.

**Additional context**

navcontainerhelper v0.7.0.13

![image](https://user-images.githubusercontent.com/53167314/87163503-251f0f00-c2d0-11ea-9efc-3840a0b7e44a.png)

**Comment by ernestasjuska** [comment]
For now adding ltsc2019 manually. I only needed that our in devops pipeline where we manually pull image (with some timeout for ALOps).

**Comment by freddydk** [comment]
Thanks.
As you might have seen on my blog (http://www.freddysblog.com) we are changing from images to artifacts.
This means that soon we will stop building images altogether and eventually we will delete the existing images.
I know ALOps has support for artifacts already, you should switch.

**Comment by ernestasjuska** [comment]
Thanks. Will checkout ALOps.
