### ISSUE TITLE
Remove-NavContainer does not remove folder with shortcuts from desktop

### ISSUE THREAD

**Issue by git-no** [microsoft/navcontainerhelper#1102]
Remove-NavContainer does not remove the shortcut Folder, neither shortcuts within the folder from desktop.

The folder with shortcuts was previously created with parameter `-shortcuts DesktopFolder` of command `New-NavContainer`.

**Comment by freddydk** [comment]
tried to create a container and remove it again - works fine.
what name did you use for the container?
Did it leave one or all shortcuts in the folder?

**Comment by freddydk** [comment]
Shipped in 0.7.0.14
