### ISSUE TITLE
Shortcuts are not deleted when containers are deleted

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#1105]
Wenn removing a container the startmenu shortcuts wont be deleted.

source of the error is probably that the $name variable is edited several times (once for Desktop and once for CommonDesktop) --> the corresponding shortcut is no longer found in the second block of the function

https://github.com/microsoft/navcontainerhelper/blob/3f9383d77a9c3290617f7b36ab055df6be8cd6c4/Misc/Remove-DesktopShortcut.ps1#L23

**Comment by ChrisBlankDe** [comment]
copy of #1102. sry.

**Comment by freddydk** [comment]
Not really a copy - that one stated that shortcuts in the desktop folders wasn't deleted - but the reason might be the same.
