### ISSUE TITLE
Specify Windows server version for generic image in combination with artifacts

### ISSUE THREAD

**Issue by mitrov** [microsoft/navcontainerhelper#1107]
**Describe the issue**
Before the change from docker images to artifacts we used to download -ltsc2016 images.

For instance: https://mcr.microsoft.com/businesscentral/onprem:ch-ltsc2016

With the new artifacts functionality the generic image is automatically selected according to Freddy: https://twitter.com/freddydk/status/1282657912050126848?s=20

However, I have a Windows 2019 host and I need to run an Windows 2016 image.

The question is: Is it still possible to specifiy that? If not, what would be the best workaround?

**Comment by freddydk** [comment]
Yes, specify -useGenericImage mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic will select the current latest Windows Server 2016 version of the generic image.

This expression will give you the latest 2016:

"mcr.microsoft.com/dynamicsnav:$((Get-NavContainerImageTags -imageName "mcr.microsoft.com/dynamicsnav").tags | Where-Object { $_.Startswith('10.0.14393') -and $_.EndsWith('-generic') } | Sort-Object | Select-Object -Last 1)"

**Comment by freddydk** [comment]
Fixed in 0.7.0.18
