### ISSUE TITLE
Docker-Compose

### ISSUE THREAD

**Issue by stefanoPrimo** [microsoft/navcontainerhelper#1109]
Hi,
Now, with the artifacts, generic containers, etc. It can be useful to create containers through the Docker-Compose? 
e.g.
1. Base OS
2. SQL Server
3. BC instance

it might be something like that? 
Last question: Is it worth to work with docker-compose?

linking related old issue: https://github.com/microsoft/navcontainerhelper/issues/768

**Comment by freddydk** [comment]
It isn't something I will work on, but yes, it is definitely possible.

**Comment by stefanoPrimo** [comment]
Thanks,
Maybe I will ask on the yammer group for suggestions!
