### ISSUE TITLE
New-NavContainer does not work Nano Server

### ISSUE THREAD

**Issue by yukonn** [Microsoft/navcontainerhelper#111]
I'm using nano server and docker is running on it. New-navcontainer cmdlet is failed when I run the it from nano server using remote. Because some script are not compatible with nano server. After I did some changes on ps, it can run. Here is file list of changes to run on nano server.

navcontainerhelper 0.2.6.4

ContainerHandling\
New-NavContainer.ps1
Remove-NavContainer.ps1

ContainerInfo\
Get-NavContainerCountry.ps1
Get-NavContainerDebugInfo.ps1
Get-NavContainerEula.ps1
Get-NavContainerGenericTag.ps1
Get-NavContainerImageName.ps1
Get-NavContainerIpAddress.ps1
Get-NavContainerLegal.ps1
Get-NavContainerNavVersion.ps1
Get-NavContainerOsVersion.ps1
Get-NavContainers.ps1
Get-NavContainerSharedFolders.ps1
Test-NavContainer.ps1

Misc\
New-DesktopShortcut.ps1

[0.2.6.4.zip](https://github.com/Microsoft/navcontainerhelper/files/1852178/0.2.6.4.zip)

**Comment by freddydk** [comment]
So you are running a Nano-Server and docker inside of that - and then spinning up Nav Containers inside the nano Server in Windows Server Core instances???
What is it you want to achieve with that?

**Comment by yukonn** [comment]
I'm running Nano-Server (VM) and docker is inside the VM. And then spinning up nav containers inside the Nano-Server. 
@Kauffmann wrote the [blog ](https://www.kauffmann.nl/2017/12/02/running-nav-docker-containers-on-a-local-hyper-v-virtual-machine/)how to run nav container inside the windows server core. It was perfect but we need windows server license to run the windows server core. I understand from some blog nano server no need the license for windows. I plan to use Nav container to run inside the Nano Server and access from other pc.

**Comment by freddydk** [comment]
I see, thanks - I will consider what to do about this.

**Comment by NAVspecialist** [comment]
As far as I understand it - it is no longer possible to install a Nano Server 2016 - It has been removed from build 1709 - and only exists as a docker image. So you have to run a Windows Server 2016 Standard (Core)

**Comment by yukonn** [comment]
@NAVspecialist thanks for your link and information. I didn't notice this news. Anyway, I just only report what is going on if we use nano server instead of windows core. I do respect @freddydk decision.

**Comment by freddydk** [comment]
https://blog.docker.com/2017/01/docker-windows-server-image2docker/

For production, licensing is at the host level, i.e. each machine or VM which is running Docker. Your Windows licence on the host allows you to run any number of Windows Docker containers on that host. With Windows Server 2016 you get the commercially supported version of Docker included in the licence costs, with support from Microsoft and Docker, Inc.
For development, Docker for Windows runs on Windows 10 and is free, open-source software. Like the server version, your Windows 10 licence allows you to run any number of Windows Docker containers.

I will not pursue any changes to support running navcontainerhelper inside a nano server.
