### ISSUE TITLE
CICD Question

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1115]
Freddy, I was wondering if you had a suggestion on how I might approach this?

I have a PTE (that will someday be in AppSource) that we built a custom extension that is dependent on the PTE on for a client.  The PTE and custom extension reside in different repos.  How can I include the build/test of the PTE in my pipeline for custom extension?  Or should I do something else?  If so, what?  

The PTE has its own pipeline.  Can I somehow get the PTE's latest build artifacts and install the app in the custom extension's pipeline?

Not sure how to approach this.  Any suggestions on how to handle this or where to look for ideas would be appreciated.

**Comment by freddydk** [comment]
I guess you could publish the PTE as part of it's release pipeline and then use the latest from that in the other pipeline.
I am looking at how to do this with my BingMaps project - but I do not have a best-practices solution yet.

**Comment by GreatScott000** [comment]
I am not following what yoy mean by "publish the PTE as part of it's release pipeline".  Publish where/how?  I publish it to my container as it will be lost when the container is recreated (db restored).  As an Artifact?  

Sorry if I am being dense.

**Comment by GreatScott000** [comment]
Just found this, maybe this is what I want to do.
[Check out multiple repositories in your pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops)

**Comment by freddydk** [comment]
If you checkout multiple - you can build them all.
You can also have one pipeline copy the artifacts (the .app file) to a storage account - and then use it from the other. (release pipeline)

**Comment by GreatScott000** [comment]
I decided to go the "copy artifacts" route.  I have managed to get this to work.  The Check out multiple repositories presented some challenges within the CICD scripts. 

As always, thanks for your help.

**Comment by freddydk** [comment]
Nice.
This is the same approach you would use if you have a dependency on a 3rd party app - you would ask for a location where to download that app.
