### ISSUE TITLE
CR: Add Switch Force to Sync-NavContainerApp

### ISSUE THREAD

**Issue by git-no** [microsoft/navcontainerhelper#1134]
## Change Request
Add switch `-Force` to `Sync-NavContainerApp`.

### Reason

`Sync-NavContainerApp -mode Clean` asks the user for permission 

_"Confirm synchronization of the extension in Clean mode (y/n)?"_

To skip this question the `-Force` parameter is required.
`Sync-NavApp`does support already `-Force`.

**Comment by freddydk** [comment]
Fixed in 0.7.0.18
