### ISSUE TITLE
secondToLastMajor returns strange version

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/navcontainerhelper#1139]
**Describe the issue**
When I run the command:  Get-BCArtifactUrl -country us -select **secondToLastMajor**
I get: https://bcartifacts.azureedge.net/sandbox/15.4.41023.43755/us

Is it really supposed to return version **15**?

**Additional context**
- does it happen all the time? **Yes**
The county doesn't seem to matter. Same result for dk.
-select latest works fine.
My navcontainerhelper version is 0.7.0.17.

**Comment by freddydk** [comment]
16 is the last public release.
15.4 is the last public sandbox release in the secondtolastmajor

You need insider sas token and storageaccount bcinsider if you want next minor
