### ISSUE TITLE
Suggestion: Include upgrade toolkit

### ISSUE THREAD

**Issue by epernst** [Microsoft/navcontainerhelper#114]
The last thing we really need to be able to fully automate an upgrade, is in my mind the ability the to also have the upgrade toolkit in the Docker images. 
Right now there is no way around downloading the actual DVD, when you have to test your upgrade.

So it would be great to get an -includeUpgradeToolkit parameter in New-NavContainer, in the same way as we got -IncludeTestToolkit? 👍

**Comment by MikeGlue** [comment]
The upgrade toolkit is in the container at C:\UpgradeToolkit

![image](https://user-images.githubusercontent.com/5204734/38109088-feefb87c-3364-11e8-881b-815a2be5ced2.png)
