### ISSUE TITLE
SQL Server 2019

### ISSUE THREAD

**Issue by 50009abp** [microsoft/navcontainerhelper#1142]
It's more of a question. Is it possible to use SQL Server 2019 in a container?

**Comment by freddydk** [comment]
I haven't tried, but I would guess so.
You could use this approach: https://freddysblog.com/2020/06/29/run-business-central-in-docker-using-a-custom-generic-image/ to install SQL 2019 in a custom generic image.

**Comment by 50009abp** [comment]
Thanks!!! I try it
