### ISSUE TITLE
Cannot create "company with no data" in Sandbox created within a container

### ISSUE THREAD

**Issue by dkiehl** [microsoft/navcontainerhelper#1145]
Created a new docker container with 
Get-BCArtifactURL -type Sandbox -Version 16 -select Latest -country us 
(https://bcartifacts.azureedge.net/sandbox/16.3.14085.14841/us)
and it seems to work very well - until I try to create a new company with the "no data' option.  I get 'something went wrong' (see image).
![error](https://user-images.githubusercontent.com/35543518/88067746-5eac1180-cb3d-11ea-9928-ffddc9e164fb.jpg)

Also attached is the script I used:
[Build_Script.txt](https://github.com/microsoft/navcontainerhelper/files/4954122/Build_Script.txt)
and the output from the script.
[output.txt](https://github.com/microsoft/navcontainerhelper/files/4954119/output.txt)

**Comment by freddydk** [comment]
I think you need to do this using the PowerShell cmdlets.
Within the UI, the container thinks that it is an online tenant, and a number of things will not work there.

If you create an onprem container, it should work as well.

**Comment by dkiehl** [comment]
Can't use an onprem container - need to test/learn about an app only available in the marketplace.

Can you point me in the right direction with powershell - I'm not great with powershell.

**Comment by freddydk** [comment]
New-CompanyInBCContainer $containername

or

Invoke-scriptinBcContainer $containername -scriptblock {
   new-navcompany...
}

https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navcompany?view=businesscentral-ps-16

**Comment by dkiehl** [comment]
Just tried: 
new-companyinbccontainer -containerName TSDEMO -companyName DAK

and got:
Creating company DAK in default
The server "BC" was unable to process the request. The application will close.
at <ScriptBlock>, <No file>: line 3
The server "BC" was unable to process the request. The application will close.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.17\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [New-NAVCompany], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/default,Microsoft.Dynamics.Nav.Management.Cmdlets.NewNavCompany
    + PSComputerName        : b6219cedb71669094f518e8b19f2ca3af2662b669ecb5b02edd5517838598beb

Have not yet figured out the second option you suggested.

DK

**Comment by dkiehl** [comment]
I was successful in using both of the above methods on a container built with OnPrem but both of them fail using Sandbox.

**Comment by freddydk** [comment]
For some reason, company creation only works in multitenant sandbox containers.
Add -multitenant to the new-bccontainer statement - then you should be good.

**Comment by dkiehl** [comment]
That did what I needed.  Thanks!

**Comment by phamhainguyen68** [comment]
@freddydk I found the root cause. Somehow, in Single-tenant deployment, the **$ndo$tenantproperty** table of the database has its **tenantid** value blank. It supposes to be populated with the ID of the tenant, which is **default** in Single-tenant mode. After filling this cell with **default**, I am able to create and delete companies.
![image](https://user-images.githubusercontent.com/6713074/95141182-be25c080-072d-11eb-9757-8752898624b7.png)


Could you send this back to corresponding teams in Microsoft and have them to take a look?
