### ISSUE TITLE
Build container with latest platform

### ISSUE THREAD

**Issue by dkiehl** [microsoft/navcontainerhelper#1149]
Trying to build a new container with the latest 16.3 app and platform available but I am getting 16.3 for the app, and 16.0 for the platform.

Trying using the -includePlatform option on Download-Artifacts but it didn't make a difference.

There is a hotfix that was released in platform 16.2 that I need in my container but am having no luck.

Any suggestions?

**Comment by freddydk** [comment]
Latest platform is in the latest app - if that is 16.0 - then that is what it is.
I think 17.0 insider builds also have 16.0 platform - don't think about it.

**Comment by freddydk** [comment]
Send me the information about the hotfix you are talking about?

**Comment by dkiehl** [comment]
https://support.microsoft.com/en-us/help/4549686/update-16-1-for-microsoft-dynamics-365-business-central-2020-release-w

**Comment by freddydk** [comment]
16.1 on prem is
 
Get-BCArtifactUrl -type OnPrem -version '16.1' -country w1

Application version number 16.1.12629.12805 (stamped inside the database)
Platform version number 16.0.12630.12758 (version number of the service tier exe file)
![image](https://user-images.githubusercontent.com/10775043/88178503-c8561980-cc2a-11ea-926a-ea85d1737233.png)

I don't know why the headlines in the article is different, but these are the actual version numbers and with artifacts you always go for the application version number.

**Comment by freddydk** [comment]
So if you need some 16.2 - grab latest 16.2 - and the platform in there is what you are looking for.

**Comment by dkiehl** [comment]
The above is still giving you platform 16.0 (not 16.1).  The issue that was resolved with 16.1 is not resolved.

**Comment by freddydk** [comment]
Download the DVD in the article - unpack and check the exe file - 16.0.12630.12758.
If it is fixed in the DVD, then it is fixed in the artifacts - that isn't anything I have control over.

**Comment by freddydk** [comment]
And again - even if you download 17.x insider build - platform exe files are 16.0.x.y
