### ISSUE TITLE
Suggestion: Include Extensions folder from DVD

### ISSUE THREAD

**Issue by epernst** [Microsoft/navcontainerhelper#115]
I'm not sure how many customers/partners previously needed to change the default Extensions. But here in Denmark most of the localizations have now moved to extensions. This have made the content of the Extensions folder on the DVD important, and must be checked into your NAV source code repository, together with the standard C/AL / new syntax. 

So in the order to not having to download the old DVD's anymore, could we then get an -includeExtensions option?

And should I have suggested this on nav-docker instead?

**Comment by MikeGlue** [comment]
They can be found at C:\Extensions in the container.
