### ISSUE TITLE
vsix path/name

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#116]
Is there easy way how to find the vsix path name/path?
I have only find the Env in inspect with VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.17720.vsix.
From there I can take the file name and construct the URL for download. But it will be nice to have some function or final URL available as variable or some cmdlet...

Thanks.

**Comment by richardrobberse** [comment]
docker logs <containername> | where-object {$_ -like '*vsix*' | select-object -first 1

**Comment by kine** [comment]
Yes, but it is not path to the container, but to some blob storage which is not accessible...

**Comment by kine** [comment]
Ok, it is a way. But I do not like it too much... thanks

**Comment by richardrobberse** [comment]
Me neither, but sometimes you have to work with what's available :)

**Comment by Koubek** [comment]
You could also use `docker exec`. For example:
```PowerShell
docker exec -t [container_name] PowerShell.exe '(Get-ChildItem "c:\inetpub\*.vsix" -Recurse | Select-Object -First 1).FullName'
```

**Comment by Koubek** [comment]
Maybe you can go even further and try the following:

```PowerShell
# Set a shared folder or a folder that will be later copied from the container using docker cp
$targetDir = '[your path]'
# Find VSIX file
$vsix = (Get-ChildItem 'c:\inetpub\*.vsix' -Recurse | Select-Object -First 1)
# Load the assembly
[System.Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem") | Out-Null
# Unzip the file
[System.IO.Compression.ZipFile]::ExtractToDirectory($vsix.FullName, $targetDir)
```

**Comment by Koubek** [comment]
The following works:
```PowerShell
docker exec -t [container_name] PowerShell.exe -Command {$targetDir = "c:\run\my\extracted"; $vsix = (Get-ChildItem "c:\inetpub\*.vsix" -Recurse | Select-Object -First 1); [System.Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem") | Out-Null;[System.IO.Compression.ZipFile]::ExtractToDirectory($vsix.FullName, $targetDir)}
```

The example expects you share a host folder with the container and the folder is mapped as `c:\run\my\` inside the container.

You can just put your container name and go...

**Comment by freddydk** [comment]
When I get to set up CI CD etc. - then my thought is not to copy the compiler out of the container, but instead share a folder with my project to the container and override navstart with a small script, which uses the vsix to compile the project.
This would mean that the container would start in seconds, perform the compile and shut down. No housekeeping, no cleanup, easy cheasy (unless I forgot something:-))

**Comment by Koubek** [comment]
@freddydk You are right, IMO, this is the best approach. I just wanted to show there is a possibility to localize VSIX using `docker exec` (something a very close @kine was asking for) and eventually extract it.

**Comment by kine** [comment]
Thanks for all inputs. The CI CD is not so easy yet (alsymbols, alc.exe gives another output than VSCode using Microsoft.Dynamics.Nav.EditorServices.Host.exe etc.). I will be solving other things in separate issues. Compiling app in the container is the way I want to go, but for now not the actual one, until we will get better/newer version of VSIX in the NAV2018 containers. There is version 12 which is really unusable...

**Comment by richardrobberse** [comment]
@kine The output of alc.exe is fine as far as I know, I got this to work some time ago already.
You just have to ignore the first (3?) lines in order to catch the output you want to have.

**Comment by kine** [comment]
Yes, but how to enable code analyzer in alc.exe?

**Comment by richardrobberse** [comment]
Ah I thought you were just referring to the output containing the compile errors, I have no idea how to catch the output of the code analyzer(s), sorry, that would be awesome though :)

**Comment by freddydk** [comment]
You could also do:

$id = "test"
$tempFolder = "$env:TEMP\$id"
New-Item $tempFolder -ItemType Directory | Out-Null
docker cp ${id}:c:\run $tempFolder
Get-item -Path "$tempFolder\Run\*.vsix" | % { Copy-Item -Path $_.FullName -Destination c:\temp\my.vsix }
Remove-Item $tempFolder -Recurse -Force

Unfortunately docker cp doesn't support wildcards, so you have to take the full run folder and remove it again - but this script takes ~11 seconds.
If you don't need the running container, you can also

$id = docker create microsoft/dynamics-nav:12.0.21229.0
$tempFolder = "$env:TEMP\$id"
New-Item $tempFolder -ItemType Directory | Out-Null
docker cp ${id}:c:\run $tempFolder
docker rm $id | Out-Null
Get-item -Path "$tempFolder\Run\*.vsix" | % { Copy-Item -Path $_.FullName -Destination c:\temp\my.vsix }
Remove-Item $tempFolder -Recurse -Force

Which also takes 11 secons and never actually starts the container.

I will consider what to do about ALC and VSIX.

**Comment by kine** [comment]
Ok, of course this will not work for Windows 10 (Hyper-V) containers. Going in Jakub's way to be sure.

**Comment by Koubek** [comment]
@kine Hi again, I've found a way how to export probably faster, just based on an image (almost).

The trick is to `create` a container instead of `run` it. When you create, you don't run anything inside but instantiate the filesystem. It is very fast. And the result is a stopped container so you can use `docker cp`.

This is my script:
```PowerShell
# Configs:
#  - Extracted VSIX path:
$targetDir = 'c:\temp\extracted_vsix'
#  - Temp path where the whole c:\run will be copied into:
$extractPath = 'c:\temp\extracted'
#  - Image name:
$image = 'microsoft/dynamics-nav:2018-cu3-es'

# Proceed all steps:
$cid = docker create $image
docker cp $cid`:c:\run $extractPath
$vsix = (Get-ChildItem $(Join-Path $extractPath '*.vsix') -Recurse | Select-Object -First 1)
[System.Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem") | Out-Null;[System.IO.Compression.ZipFile]::ExtractToDirectory($vsix.FullName, $targetDir)

# Cleanup:
Remove-Item $extractPath -Recurse -Force
docker rm $cid
```
