### ISSUE TITLE
Restoring production backup into tenant within container with V16 and V16 database

### ISSUE THREAD

**Issue by davmac1** [microsoft/navcontainerhelper#1161]
I am getting the same errors as #937 but I am restoring a v16 database from a bacpac.
I restored it locally to see what the version is, and it shows application version: 16.0.11240.11946 in the table 
$ndo$tenantdatabaseproperty.

I pasted more info below the error on the container build.

**Creating Container bcbuild
Version: 16.3.14085.14363-us
Style: sandbox
Platform: 16.0.14073.14279**

Error:
The following SQL error was unexpected:
The transaction operation cannot be performed because there are pending requests working on this transaction.

at <ScriptBlock>, <No file>: line 19
The following SQL error was unexpected:
The transaction operation cannot be performed because there are pending requests working on this transaction.
At C:\Users\dmachanick\Documents\WindowsPowerShell\Modules\NavContainerHelper\0.7.0.19\ContainerHandling\Invoke-ScriptInNavContainer.
ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Mount-NAVTenant], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/GC,Microsoft.Dynamics.Nav.Management.Cmdlets.MountNavTenant
    + PSComputerName        : b312adb5aa5c06dc03f64af75b0e35c55b78afeaeac9aeebeaf83c06fc1975a9

This is what I am loading:
Pulling image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
us-ltsc2019: Pulling from businesscentral/sandbox
Using image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Creating Container bcbuild
Version: 16.3.14085.14363-us
Style: sandbox
Platform: 16.0.14073.14279
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.19041.388 (2004)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation

**Comment by freddydk** [comment]
Sorry, but I have no idea what you are trying to do or what script you are trying to run.
If you are trying to restore a production tenant into a container, you need to find a Business Central version close to the version you have online (above you are trying to restore a 16.0 database into a 16.3 container)
You get the artifacts by using: Get-BCArtifactUrl -country us -version 16.0.11240.11946 -select Closest
But I can see you haven't started using artifacts yet - you should probably read a few blog posts about that on freddysblog.com and then try that - it isn't a big change.

**Comment by davmac1** [comment]
Thanks Freddy.
I will give this a try.
