### ISSUE TITLE
Add switch to prevent mixed-plans error when opening company

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/navcontainerhelper#1169]
We'd like to add some test users to our container however [Setup-NavContainerTestUsers](https://github.com/microsoft/navcontainerhelper/blob/master/UserHandling/Setup-NavContainerTestUsers.ps1) inserts mixed plans (Basic and Premium). This causes an error to show on CompanyOpen where mixed plans are checked:

> One or more users are not assigned to the same Business Central license. For example, we found that users %1 and %2 are assigned to different licenses, but there may be other mismatches. In your Microsoft 365 admin center, make sure that all users are assigned to the same Business Central license, either Basic, Essential, or Premium.  Afterward, update Business Central by opening the Users page and using the ''Update Users from Office 365'' action.'

This interferes with CI testing which instead sees that dialog (when collecting tests) from the Test Tool page.

The [Setup-NavContainerTestUsers](https://github.com/microsoft/navcontainerhelper/blob/master/UserHandling/Setup-NavContainerTestUsers.ps1) runs a pre-compiled NAV App. 

Can we get the test users enhanced to not add mixed plans in? i.e. just Premium or just Basic via a switch?

We'd use [New-NavContainerNavUser](https://github.com/microsoft/navcontainerhelper/blob/master/UserHandling/New-NavContainerNavUser.ps1) but it doesn't support Team plans.

**Comment by freddydk** [comment]
The pre-compiled app is this: https://dev.azure.com/businesscentralapps/CreateTestUsers
(if you want to have a look at this before I have the time)

**Comment by ShadowXVII** [comment]
Thanks for the source. I had a look in the compiled cs to figure out what was happening.

Specifically the `CreateUsers`, `AssignPlansToUsers` and `AssignPlanUserGroupsToUsers` all need to create **either** `EssentialUserNameTok` or `PremiumUserNameTok` but not both ([code](https://dev.azure.com/businesscentralapps/_git/CreateTestUsers?path=%2Fapp%2Fapi%2050000%20-%20CreateTestUsers.al&version=GBmaster&line=100&lineEnd=101&lineStartColumn=1&lineEndColumn=79&lineStyle=plain))

**Comment by freddydk** [comment]
Setup-BcContainerTestUsers will get a -select parameter, where you can select Essential or Premium.
default is to install all (as before)

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 1.0.2-preview153
