### ISSUE TITLE
New-NavContainer - bakFile Paramter with OnPrem Database "...Dynamics 365 Business Central because the database is too recent."

### ISSUE THREAD

**Issue by aptMattKoe** [microsoft/navcontainerhelper#1170]
**Describe the issue**
I want to use an customer bak file with "New-NavContainer" of an installed OnPrem database for the version "16.0.13440.13772".
![image](https://user-images.githubusercontent.com/57363453/88680189-8298c580-d0f0-11ea-81b2-da1d0de0ab06.png)

But it breaks while starting the servicetier:

> ...
> Starting Service Tier
> Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
> at <ScriptBlock>, C:\Run\navstart.ps1: line 147
> at <ScriptBlock>, C:\Run\start.ps1: line 223
> at <ScriptBlock>, <No file>: line 1
> Initialization of container BC16 failed
> In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.20\ContainerHandling\Wait-NavContainerReady.ps1:44 Zeichen:17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization of container BC16 failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container BC16 failed

The Problem is that the installed OnPrem is an higher version as my container and I could not get an higher artifact.
This is the closest I get:
![image](https://user-images.githubusercontent.com/57363453/88680001-554c1780-d0f0-11ea-9c51-722f2a448841.png)

and its also the latest:
![image](https://user-images.githubusercontent.com/57363453/88680047-609f4300-d0f0-11ea-9fca-3f81088401b4.png)

**Scripts used to create container and cause the issue**
```
##PARAMATER########################################################################################
$containerName = "BC16"

$ArtifactURL = Get-BCArtifactUrl -country "de" -type OnPrem -version "16.0.13440.13772" -select Closest
$ArtifactURL = Get-BCArtifactUrl -country "de" -type OnPrem -select Latest -version "16.0"



$licenseFile = "C:\ProgramData\NavContainerHelper\mybak\myLicense.flf";

$auth = "NavUserPassword"
$UserName = "BCAdmin"
$Password = "P@ssword"

##Creating Credential Object##
If ($auth = "NavUserPassword") {
    $Credential = New-Object pscredential -ArgumentList $UserName , (ConvertTo-SecureString -String $Password -AsPlainText -Force)
}
else {
    $Credential = Get-Credential
}

New-NavContainer -containerName $ContainerName `
    -imageName $imageName `
    -licenseFile $licenseFile `
    -auth $auth `
    -Credential $Credential `
    -accept_eula `
    -accept_outdated `
    -artifactUrl $ArtifactURL `
    -includeTestToolkit `
    -bakFile "C:\ProgramData\NavContainerHelper\mybak\customerDatabaseBAK.bak"
    
    
# update hosts with kaspersky
##Selecting hostname of the container that was last started
$containers = docker ps -aq
$lastcontainerid = $containers.Item(0)
$hostname = docker inspect -f '{{ .Config.Hostname}}' $lastcontainerid

##elevating PS if necessary
if (!([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) { Start-Process powershell.exe "-NoProfile -ExecutionPolicy Bypass -File "$PSCommandPath"" -Verb RunAs; exit }

##Remove existing line
Set-Content -Path "$env:windir\System32\Drivers\etc\hosts" -Value (get-content -Path "$env:windir\System32\Drivers\etc\hosts" | Select-String -Pattern $hostname -NotMatch)

##add ip:host mapping to host file
$ipadd = docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $hostname
Add-Content -Value "${ipadd} $hostname" -Path "$env:windir\System32\Drivers\etc\hosts"
```

**Full output of scripts**
```
NavContainerHelper is version 0.7.0.20
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Removing container BC16
Removing BC16 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\BC16
ArtifactUrl and ImageName specified
Image mcr.microsoft.com/businesscentral/onprem:16.0.11240.12076-de-ltsc2019 already exists
Using image mcr.microsoft.com/businesscentral/onprem:16.0.11240.12076-de-ltsc2019
Creating Container BC16
Version: 16.0.11240.12085-de
Style: onprem
Platform: 16.0.11233.12078
Generic Tag: 0.1.0.7
Container OS Version: 10.0.18363.959 (1909)
Host OS Version: 10.0.18363.959 (1909)
Using locale de-DE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\ProgramData\NavContainerHelper\mybak\myLicense.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\BC16\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC16 from image mcr.microsoft.com/businesscentral/onprem:16.0.11240.12076-de-ltsc2019
3c9bfff2d0ee9a32ddbcd3e3a9e563269b8637531c98dab8ed8ae59d8913a9cf
Waiting for container BC16 to be ready
Initializing...
Setting host.containerhelper.internal to 172.31.112.1 in container hosts file
Starting Container
Hostname is BC16
PublicDnsName is BC16
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'C:\ProgramData\NavContainerHelper\mybak\customerDatabaseBAK.bak'
Using database server localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FB6638360E948ECD25DBD5A998062753FA1D9C70
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 147
at <ScriptBlock>, C:\Run\start.ps1: line 223
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.containerhelper.internal to 172.31.112.1 in container hosts file
Starting Container
Hostname is BC16
PublicDnsName is BC16
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'C:\ProgramData\NavContainerHelper\mybak\customerDatabaseBAK.bak'
Using database server localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FB6638360E948ECD25DBD5A998062753FA1D9C70
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 147
at <ScriptBlock>, C:\Run\start.ps1: line 223
at <ScriptBlock>, <No file>: line 1
Initialization of container BC16 failed
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.20\ContainerHandling\Wait-NavContainerReady.ps1:44 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container BC16 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC16 failed

```

**Screenshots**
In the corresponsing eventlog you could see the detailed message of the title:
![image](https://user-images.githubusercontent.com/57363453/88679772-128a3f80-d0f0-11ea-9504-94f6aaf9e6bf.png)

**Comment by freddydk** [comment]
Where did you get the version number from: 16.0.13440.13772 ?

**Comment by aptMattKoe** [comment]
I use the "Get-NAVServerInstance" Powershell command (first Screenshot). Is that wrong?

**Comment by freddydk** [comment]
ahh - that is likely the platform version number - you cannot use that.
The version above is likely 16.2

**Comment by aptMattKoe** [comment]
ahh okay.
And how could I see what is the correct version?

**Comment by freddydk** [comment]
Partner or Customer must know that they are on 16.2 (somebody downloaded and installed the 16.2 dvd)

https://support.microsoft.com/en-us/help/4564072/update-16-2-for-microsoft-dynamics-365-business-central-2020-release-w

**Comment by aptMattKoe** [comment]
Yes, for sure :D "kowing" is one way but is there a was for "looking"?

**Comment by freddydk** [comment]
System Information dialog in the app.
When you download the artifacts for 16.2 - you will see the platform version in the manifest file - it matches.

**Comment by aptMattKoe** [comment]
okay, now I get another error (something to do with the Users) but you helped me with my fault! :) thanks!
The other error is something for tomorrow for me (and I have an idea, like in the upgrades back then :))

**Comment by aptMattKoe** [comment]
I have another question to this.
I tried another database of another customer and have the same question.
I've looked the Version like this:
![image](https://user-images.githubusercontent.com/57363453/88894563-57c18500-d248-11ea-9471-32e5d3933503.png)

and like this:
![image](https://user-images.githubusercontent.com/57363453/88894831-d5859080-d248-11ea-8cd1-93b87fb6378b.png)

but get the same error with the "too recent database".
"MessageWithoutPrivateInformation: The mydatabase database on the LOCALHOST\SQLEXPRESS server cannot be opened by this version of Dynamics 365 Business Central because the database is too recent."

I'm sure (or again wrong?!) that the version is correct but I do not get this message. 

I would like to give you the bak buts a customer database :/

**Comment by freddydk** [comment]
Is that the same customer as above?

**Comment by aptMattKoe** [comment]
No, another. (want to try my CustomerDataToContainerData Script :D)

**Comment by freddydk** [comment]
and which container are you using for this one?
If you download the corresponding DVD, do you then get the same error?
I assume so and solving that would also solve the docker issue (I assume again).

**Comment by aptMattKoe** [comment]
freddy...sorry I wasted your time (again?).... it was an d*mn copy paste error....
Then I use this to say: Thank you for your work and realy quick help here! :)
