### ISSUE TITLE
Compile-AppInNavContainer: Error log not displayed correctly for Azure DevOps

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#1177]
We are using Compile-AppInNavContainer in our pipeline with the AzureDevOps switch turned on.

Whereas compiler warnings are displayed correctly as:
##[warning]C:\Git\App\Source\Codeunit.al(192,9): warning AA0137: Variable 'Field' is unused "
the errors are displayed without the source reference (C:\Git\App\Source\Codeunit.al and line/column).

I can see that Compile-AppInNavContainer  is calling Convert-AlcOutputToAzureDevOps to convert the Alc output. And here I can also see that it has a regex based switch, where it always select the
                     $newLine = "##vso[task.logissue type=error;code=$($Matches[2]);]$($Matches[3])"
option instead of 
                    $newLine = "##vso[task.logissue type=error;sourcepath=$($Matches[1]);linenumber=$($Matches[2]);columnnumber=$($Matches[3]);code=$($Matches[4]);]$($Matches[5])"

I am not really a shark when it comes to debugging regex, so where not able to see what's wrong here, maybe @kine knows the answer, as he wrote the original code.

And other option, and in my mind better option, would be to support the compiler "/errorlog:file.log" option, which would give us the full compiler log file, instead of (just) the current compiler output.

**Comment by kine** [comment]
Hmm, do not understand. If the result is warning in the pipeline, than it cannot select the "$newLine = "##vso[task.logissue type=error;code=$($Matches[2]);]$($Matches[3])"" because this will produce Error, not warning... :-/

Could you post full output of the task?

**Comment by epernst** [comment]
No problems with the warning, they are displaying correctly.

The problems are errors not showing the source reference.

**Comment by kine** [comment]
@epernst could you send me the output of the pipeline with the error? I need the exact text of the error as produced by the command before it is processed by the function to be able to check the regex.

**Comment by epernst** [comment]
Sorry missed your reply. Will get you the exact error (without ADO formatting), as soon as possible....

**Comment by freddydk** [comment]
Erik, did you ever get the information to Kamil?

**Comment by freddydk** [comment]
@epernst - I will close this as cannot repro.
Please add a repro scenario and reopen if needed.
