### ISSUE TITLE
The container operating system does not match the host operating system.

### ISSUE THREAD

**Issue by DavidRoys** [microsoft/navcontainerhelper#1179]
**Describe the issue**
I have a docker container based on image bcnzimage:sandbox-16.3.14085.14583-nz that I created using a script that was generated through the New-BCContainerWizard cmdlet. It has worked fine since it was created on 15th July. This was on a new laptop and was on a clean install of Docker I have diabled auto updates. Today I was working with no internet connection (probably not relevant) and tried to start my container which had a status of Exited (4 days ago). When I try to start the container I get the error message "The container operating system does not match the host operating system." There was a lot more to this error message which I can provide if you think it might be relevant.

**Scripts used to create container and cause the issue**
```
$containerName = 'bcnz'
$User = "davidr"
$PWord = ConvertTo-SecureString -String "NotAStrongPassword" -AsPlainText -Force
$Credential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'nz' -select 'Latest'
$licenseFile = 'https://www.dropbox.com/s/thisisnotmylicensefile.flf?dl=1'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'bcnzimage' `
    -includeTestToolkit `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -updateHosts
Setup-BcContainerTestUsers -containerName $containerName -Password $credential.Password -credential $credential
```

**Full output of scripts**
```
Sorry I don't have the output of the script when it was run. I have been using the container without problems for a couple of weeks now.  
```

**Screenshots**

**Additional context**
So maybe this is not a problem with NAVContainerHelper and more of an issue with Docker and Windows, but this is the first time I have created a container that is using Artifacts. It's also the first container on a new Windows install and a new laptop, so anything could be different to how it ran previously. When I get an internet connection I will run my script again and create a new container, until then I guess I'll have to find something else to do. Happy if you decide this is not related to NAVContainerHelper and you just want to close the issue - just thought with it being the new artifacts process this might be of some use if it is also happening to others.

**Comment by freddydk** [comment]
Could you provide the information given by winver.exe on the host and the info given by get-bccontainerdebuginfo of the container?
My assumption is that the script created a container using process isolation and that you had an update of Windows on the host,
Re-running the script should remove the container and create a new one.

**Comment by DavidRoys** [comment]
Winver output:

Windows 10
Version 2004 (OS Build 19041.388)

{
    "container.logs":  [
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.22.80.1 in container hosts file",
                           "Starting Container",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Creating Self Signed Certificate",
                           "Self Signed Certificate Thumbprint 7C8150C1E2108A80146982314125EAEB3499A315",
                           "Modifying Service Tier Config File with Instance Specific Settings",
                           "Starting Service Tier",
                           "Registering event sources",
                           "Creating DotNetCore Web Server Instance",
                           "Enabling Financials User Experience",
                           "Using license file \u0027c:\\run\\my\\license.flf\u0027",
                           "Import License",
                           "Creating http download site",
                           "Setting SA Password and enabling SA",
                           "Creating davidr as SQL User and add to sysadmin",
                           "Creating SUPER user",
                           "Assign Premium plan for DAVIDR",
                           "Container IP Address: 172.22.89.200",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.22.89.200 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 98 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.26.160.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.26.164.147",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.26.164.147 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 158 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.22.16.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.22.16.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.22.25.29",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.22.25.29 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 166 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.81 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.81 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.24.64.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.24.64.246",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.24.64.246 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 158 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.81 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.81 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.18.240.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.18.248.5",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.18.248.5 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 159 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.70 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.70 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.18.240.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.18.248.37",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.18.248.37 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 35 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.18.240.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.18.250.187",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.18.250.187 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 157 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.80 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.18.240.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.18.249.219",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.18.249.219 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 154 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.78 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.78 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.18.240.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.18.241.201",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.18.241.201 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 157 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.78 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.78 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.18.240.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.18.252.170",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.18.252.170 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 159 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 10.3.32.61 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 10.3.32.61 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.24.64.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.24.77.185",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.24.77.185 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 172 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 10.3.32.61 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 10.3.32.61 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.31.144.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Initializing...",
                           "Setting host.docker.internal to 169.254.161.149 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 169.254.161.149 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.31.144.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.31.148.61",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.31.148.61 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 193 seconds",
                           "Ready for connections!",
                           "Initializing...",
                           "Setting host.docker.internal to 192.168.1.78 in container hosts file (copy from host hosts file)",
                           "Setting gateway.docker.internal to 192.168.1.78 in container hosts file (copy from host hosts file)",
                           "Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)",
                           "Setting host.containerhelper.internal to 172.31.144.1 in container hosts file",
                           "Restarting Container",
                           "PublicDnsName unchanged",
                           "Hostname is bcnz",
                           "PublicDnsName is bcnz",
                           "Using NavUserPassword Authentication",
                           "Starting Local SQL Server",
                           "Starting Internet Information Server",
                           "Starting Service Tier",
                           "Container IP Address: 172.31.145.38",
                           "Container Hostname  : bcnz",
                           "Container Dns Name  : bcnz",
                           "Web Client          : http://bcnz/BC/",
                           "Dev. Server         : http://bcnz",
                           "Dev. ServerInstance : BC",
                           "Setting bcnz to 172.31.145.38 in host hosts file",
                           "",
                           "Files:",
                           "http://bcnz:8080/ALLanguage.vsix",
                           "",
                           "Initialization took 38 seconds",
                           "Ready for connections!"
                       ],
    "docker.info":  [
                        "Client:",
                        " Debug Mode: false",
                        "",
                        "Server:",
                        " Containers: 2",
                        "  Running: 1",
                        "  Paused: 0",
                        "  Stopped: 1",
                        " Images: 12",
                        " Server Version: 19.03.8",
                        " Storage Driver: windowsfilter",
                        "  Windows: ",
                        " Logging Driver: json-file",
                        " Plugins:",
                        "  Volume: local",
                        "  Network: ics internal l2bridge l2tunnel nat null overlay private transparent",
                        "  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog",
                        " Swarm: inactive",
                        " Default Isolation: hyperv",
                        " Kernel Version: 10.0 19041 (19041.1.amd64fre.vb_release.191206-1406)",
                        " Operating System: Windows 10 Enterprise Version 2004 (OS Build 19041.388)",
                        " OSType: windows",
                        " Architecture: x86_64",
                        " CPUs: 8",
                        " Total Memory: 15.78GiB",
                        " Name: DESKTOP-S4PPI5V",
                        " ID: SBV3:PDQU:4ZEL:C73H:7EHO:DA5Q:MFTR:LDK5:AN6K:QKET:RT4F:U4SW",
                        " Docker Root Dir: C:\\ProgramData\\Docker",
                        " Debug Mode: true",
                        "  File Descriptors: -1",
                        "  Goroutines: 29",
                        "  System Time: 2020-08-02T18:33:50.5596864+12:00",
                        "  EventsListeners: 1",
                        " Registry: https://index.docker.io/v1/",
                        " Labels:",
                        " Experimental: false",
                        " Insecure Registries:",
                        "  127.0.0.0/8",
                        " Live Restore Enabled: false",
                        " Product License: Community Engine",
                        ""
                    ],
    "container.labels":  {
                             "country":  "NZ",
                             "created":  "202007110426",
                             "cu":  "",
                             "eula":  "https://go.microsoft.com/fwlink/?linkid=861843",
                             "legal":  "http://go.microsoft.com/fwlink/?LinkId=837447",
                             "maintainer":  "Dynamics SMB",
                             "nav":  "",
                             "osversion":  "10.0.18363.900",
                             "platform":  "16.0.14073.14508",
                             "tag":  "0.1.0.7",
                             "version":  "16.3.14085.14583"
                         },
    "container.ping":  [
                           "",
                           "Pinging bcnz [172.31.145.38] with 32 bytes of data:",
                           "Request timed out.",
                           "Request timed out.",
                           "Request timed out.",
                           "Request timed out.",
                           "",
                           "Ping statistics for 172.31.145.38:",
                           "    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),"
                       ],
    "container.env":  [
                          "username=davidr",
                          "accept_eula=Y",
                          "ExitOnError=N",
                          "locale=en-NZ",
                          "securePassword=\u003cspecified\u003e",
                          "removePasswordKeyFile=Y",
                          "accept_outdated=Y",
                          "useSSL=N",
                          "passwordKeyFile=c:\\run\\my\\aes.key",
                          "licenseFile=\u003cspecified\u003e",
                          "auth=NavUserPassword",
                          "databaseServer=",
                          "databaseInstance=",
                          "enableApiServices=Y",
                          "DOTNET_RUNNING_IN_CONTAINER=true",
                          "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                          "DatabaseName=CRONUS",
                          "IsBcSandbox=Y",
                          "artifactUrl=https://bcartifacts.azureedge.net/sandbox/16.3.14085.14583/nz"
                      ]
}

**Comment by freddydk** [comment]
Winver: 10.0.19041.388
container osversion: 10.0.18363.900

Your machine has an upgrade from 1909 to 2004.
You won't be able to start your process isolation container - you would have to re-run the script.
And the error message you got is accurate.

**Comment by DavidRoys** [comment]
Thanks Freddy. Is there anything I can do to avoid Windows updates killing my containers or should I just accept that rebuilding containers regularly is part of life? I realize this is not an issue with NAVContainerHelper, so feel free to close this issue without answering. Thanks again!

**Comment by freddydk** [comment]
Yeah, rebuilding containers is something we do... - since very early days I have told people to save the script creating the container, don't try to save to container.
If you want to keep a container running your best bet is to use Hyperv - they do not break as frequently as process isolation containers.
