### ISSUE TITLE
New-BCContainerWizard not working in 0.7.0.18 - 0.7.0.22 ?

### ISSUE THREAD

**Issue by steveendow** [microsoft/navcontainerhelper#1180]
(credit to Nitin Verma, who emailed me about this issue)

In recent versions of NavContainerHelper, it seems that **New-BCContainerWizard** no longer works.  

When the New-BCContainerWizard command is issued in versions 0.7.0.18 - 22, a blank PowerShell window appears to briefly open, then closes immediately.  It looks like an error might sometimes flash in the new window, but it's so brief that I can't read it. No other error is displayed, and the wizard does not start in the PowerShell session.

Start-Transcript does not capture any activity or errors in the calling session.

Here is an animated gif of the issue:

![NewBCWizard](https://user-images.githubusercontent.com/11199908/89144780-88811300-d503-11ea-87ff-8a60d34618c2.gif)

If I roll back to version 0.7.0.17, the wizard works.  

I am able to reproduce the issue on 3 different servers.

Please let me know if you have any questions or need any additional information.

**Comment by freddydk** [comment]
Problem is the space in the path where navcontainerhelper gets installed.
during my tests, it is located elsewhere:-(

**Comment by steveendow** [comment]
No worries, thanks!

**Comment by freddydk** [comment]
Shipped in 0.7.0.23

**Comment by erolkunman** [comment]
This issue is back for me.

using BcContainerHelper version 6.0.11
Running on Windows, PowerShell 5.1.22621.2506

**Comment by freddydk** [comment]
you need 6.0.12 (which right now is in preview) - will ship tomorrow
