### ISSUE TITLE
Transition from NavContainerHelper to BcContainerHelper is not easy

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#1183]
I decided to move from navcontainerhelper to bccontainerhelper. The move is more complex that it looked. Biggest issue is, that I need to recreate all running containers, because they are now mapped to c:\programdata\navcontainerhelper but the bccontainerhelper needs them to be mapped to c:\programdata\bccontainerhelper.

Example is cmdlet Publish-BcContainerApp, which fails with error:
'''
Could not find a part of the path 'C:\ProgramData\BcContainerHelper\Extensions\<containername>\<appfilename>'
'''
Yes, because the container was created from navcontainerhelper.

BcContainerHelper 1.0.1-preview146

Is there some simple tool/path how to remap the containers to the new folder?
Could bccontainerhelper support such a containers? (backward compatibility).

**Comment by freddydk** [comment]
if you place a file in c:\programdata\bccontainerhelper called bccontainerhelper.config.json
containing

```
{
    "hostHelperFolder": "c:\\programdata\navcontainerhelper",
    "containerHelperFolder": "c:\\programdata\navcontainerhelper"
}
```

Then it should use the same folder as navcontainerhelper.

**Comment by kine** [comment]
Thanks!

It is working as expected.
