### ISSUE TITLE
AL source code not installed with New-BCContainer

### ISSUE THREAD

**Issue by heinrichvermeulen** [microsoft/navcontainerhelper#1188]
Previously when installing using New-NavContainer the source code was installed in the 'c:\ProgramData\NavContainerHelper\Extensions\' folder, for example 'Original-16.0.11240.12076-W1-al' the folder name relating to the BC version you installed.

Since using the New-BCContainer as part of the latest version of New-BcContainerWizard script.
Is there a switch to use that I need to add to export the AL source code?

NavContainerHelper is version 0.7.0.13
NavContainerHelper is running as administrator
Host is Microsoft Windows [Version 10.0.18363.959]
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12

**Comment by TheDenSter** [comment]
try adding -includeAL

**Comment by freddydk** [comment]
exactly, add -includeAL and you will get the source.
If you don't, then please reopen and provide the script used and the full output you get.

**Comment by heinrichvermeulen** [comment]
It still does not produce the source code if I use -includeAL as detailed in the script and output below:
$containerName = 'v163'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '' -country 'w1' -select 'Latest'
$licenseFile = 'c:\temp\licenses\license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts
    -includeAL

**The output:**
C:\temp\newbc.ps1
NavContainerHelper is version 0.7.0.23
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.18363.959-generic
10.0.18363.959-generic: Pulling from dynamicsnav
9038b92872bc: Already exists
49433c3fd77f: Pulling fs layer
f0dd1ef39f8a: Pulling fs layer
8e658e5753d1: Pulling fs layer
4f009c99d363: Pulling fs layer
cd61b72f6b55: Pulling fs layer
4f009c99d363: Waiting
ac7baddb4a74: Pulling fs layer
56ad7076ae14: Pulling fs layer
99a0ba530958: Pulling fs layer
55fe3bf45010: Pulling fs layer
cd61b72f6b55: Waiting
ac7baddb4a74: Waiting
56ad7076ae14: Waiting
7a9423eff044: Pulling fs layer
99a0ba530958: Waiting
379963b42dbf: Pulling fs layer
55fe3bf45010: Waiting
7a9423eff044: Waiting
0dfdcbcac835: Pulling fs layer
379963b42dbf: Waiting
8a3e74c3a38f: Pulling fs layer
0dfdcbcac835: Waiting
8a3e74c3a38f: Waiting
d4af92441f8a: Pulling fs layer
9c81727cf490: Pulling fs layer
d4af92441f8a: Waiting
fb1753465ad8: Pulling fs layer
c390c0d3ac0d: Pulling fs layer
9c81727cf490: Waiting
1ea0f8217868: Pulling fs layer
c390c0d3ac0d: Waiting
8e658e5753d1: Verifying Checksum
8e658e5753d1: Download complete
4f009c99d363: Retrying in 5 seconds
4f009c99d363: Retrying in 4 seconds
4f009c99d363: Retrying in 3 seconds
4f009c99d363: Retrying in 2 seconds
4f009c99d363: Retrying in 1 second
4f009c99d363: Verifying Checksum
4f009c99d363: Download complete
cd61b72f6b55: Verifying Checksum
cd61b72f6b55: Download complete
ac7baddb4a74: Verifying Checksum
ac7baddb4a74: Download complete
56ad7076ae14: Verifying Checksum
56ad7076ae14: Download complete
99a0ba530958: Verifying Checksum
99a0ba530958: Download complete
55fe3bf45010: Retrying in 5 seconds
f0dd1ef39f8a: Retrying in 5 seconds
49433c3fd77f: Retrying in 5 seconds
55fe3bf45010: Retrying in 4 seconds
f0dd1ef39f8a: Retrying in 4 seconds
49433c3fd77f: Retrying in 4 seconds
55fe3bf45010: Retrying in 3 seconds
f0dd1ef39f8a: Retrying in 3 seconds
49433c3fd77f: Retrying in 3 seconds
55fe3bf45010: Retrying in 2 seconds
f0dd1ef39f8a: Retrying in 2 seconds
49433c3fd77f: Retrying in 2 seconds
55fe3bf45010: Retrying in 1 second
f0dd1ef39f8a: Retrying in 1 second
49433c3fd77f: Retrying in 1 second
f0dd1ef39f8a: Retrying in 10 seconds
f0dd1ef39f8a: Retrying in 9 seconds
f0dd1ef39f8a: Retrying in 8 seconds
f0dd1ef39f8a: Retrying in 7 seconds
f0dd1ef39f8a: Retrying in 6 seconds
f0dd1ef39f8a: Retrying in 5 seconds
f0dd1ef39f8a: Retrying in 4 seconds
f0dd1ef39f8a: Retrying in 3 seconds
f0dd1ef39f8a: Retrying in 2 seconds
f0dd1ef39f8a: Retrying in 1 second
f0dd1ef39f8a: Verifying Checksum
f0dd1ef39f8a: Download complete
7a9423eff044: Verifying Checksum
7a9423eff044: Download complete
379963b42dbf: Verifying Checksum
379963b42dbf: Download complete
0dfdcbcac835: Verifying Checksum
0dfdcbcac835: Download complete
8a3e74c3a38f: Verifying Checksum
8a3e74c3a38f: Download complete
d4af92441f8a: Verifying Checksum
d4af92441f8a: Download complete
9c81727cf490: Verifying Checksum
9c81727cf490: Download complete
fb1753465ad8: Verifying Checksum
fb1753465ad8: Download complete
c390c0d3ac0d: Verifying Checksum
c390c0d3ac0d: Download complete
1ea0f8217868: Verifying Checksum
1ea0f8217868: Download complete
55fe3bf45010: Retrying in 10 seconds
55fe3bf45010: Retrying in 9 seconds
55fe3bf45010: Retrying in 8 seconds
55fe3bf45010: Retrying in 7 seconds
55fe3bf45010: Retrying in 6 seconds
55fe3bf45010: Retrying in 5 seconds
55fe3bf45010: Retrying in 4 seconds
55fe3bf45010: Retrying in 3 seconds
55fe3bf45010: Retrying in 2 seconds
55fe3bf45010: Retrying in 1 second
55fe3bf45010: Verifying Checksum
55fe3bf45010: Download complete
49433c3fd77f: Retrying in 10 seconds
49433c3fd77f: Retrying in 9 seconds
49433c3fd77f: Retrying in 8 seconds
49433c3fd77f: Retrying in 7 seconds
49433c3fd77f: Retrying in 6 seconds
49433c3fd77f: Retrying in 5 seconds
49433c3fd77f: Retrying in 4 seconds
49433c3fd77f: Retrying in 3 seconds
49433c3fd77f: Retrying in 2 seconds
49433c3fd77f: Retrying in 1 second
49433c3fd77f: Verifying Checksum
49433c3fd77f: Download complete
49433c3fd77f: Pull complete
f0dd1ef39f8a: Pull complete
8e658e5753d1: Pull complete
4f009c99d363: Pull complete
cd61b72f6b55: Pull complete
ac7baddb4a74: Pull complete
56ad7076ae14: Pull complete
99a0ba530958: Pull complete
55fe3bf45010: Pull complete
7a9423eff044: Pull complete
379963b42dbf: Pull complete
0dfdcbcac835: Pull complete
8a3e74c3a38f: Pull complete
d4af92441f8a: Pull complete
9c81727cf490: Pull complete
fb1753465ad8: Pull complete
c390c0d3ac0d: Pull complete
1ea0f8217868: Pull complete
Digest: sha256:cd0c67c6f24c8f841466dc491bcb75f4568c054fd8ac718fa2cead213c62b38c
Status: Downloaded newer image for mcr.microsoft.com/dynamicsnav:10.0.18363.959-generic
mcr.microsoft.com/dynamicsnav:10.0.18363.959-generic
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.959-generic
Creating Container v163
Version: 16.3.14085.14238-w1
Style: onprem
Platform: 16.0.14073.14195
Generic Tag: 0.1.0.13
Container OS Version: 10.0.18363.959 (1909)
Host OS Version: 10.0.18363.959 (1909)
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file c:\temp\licenses\braintree d365 bc16 on-prem all isvs 20200529.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\v163\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container v163 from image mcr.microsoft.com/dynamicsnav:10.0.18363.959-generic
6059391e959ef8cf36bf6a63fbb1a4a634a89ccd7e33deaa6b39f75930da7534
Waiting for container v163 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.3.14085.14238/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\16.3.14085.14238\w1\database\Demo Database NAV (16-0).bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing CRONUS license file
Stopping Business Central Service Tier
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Installation took 4258 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.0.100 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.100 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.29.112.1 in container hosts file
Starting Container
Hostname is v163
PublicDnsName is v163
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 2173BAFC4308B32187E96176E8D67E82FB85F6F9
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.29.118.59
Container Hostname  : v163
Container Dns Name  : v163
Web Client          : http://v163/BC/
Dev. Server         : http://v163
Dev. ServerInstance : BC
Setting v163 to 172.29.118.59 in host hosts file

Files:
http://v163:8080/ALLanguage.vsix

Initialization took 747 seconds
Ready for connections!
Reading CustomSettings.config from v163
Creating Desktop Shortcuts for v163
Container v163 successfully created
-includeAL : The term '-includeAL' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
included, verify that the path is correct and try again.
At C:\temp\newbc.ps1:16 char:5
+     -includeAL
+     ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-includeAL:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by freddydk** [comment]
I have modified your script and can see you forgot to add a ` to the line before -includeAL.
This means that -includeAL is seen as a new command, which causes:

```
-includeAL : The term '-includeAL' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

Search for "The Grave" here https://freddysblog.com/2019/08/04/powershell-for-non-experts/ to read more.

**Comment by heinrichvermeulen** [comment]
Thanks so much!
