### ISSUE TITLE
External SQL Database with Database Credentials

### ISSUE THREAD

**Issue by eknraw** [Microsoft/navcontainerhelper#119]
Running into an issue using SQL Auth with an existing database.  I can use the Windows Client just fine but if the container restarts I am unable to access.  

I noticed this is being logged in the container logs AFTER I restart the container:  
Initializing...
Cannot find path 'C:\run\my\aes.key' because it does not exist.
at <ScriptBlock>, C:\Run\SetupVariables.ps1: line 44
at <ScriptBlock>, C:\Run\navstart.ps1: line 23
at <ScriptBlock>, C:\Run\start.ps1: line 102
at <ScriptBlock>, <No file>: line 1

If I quick grab a copy of aes.key and re-copy that back into the directory before the restart then everything works fine.   I don't think I changed anything in my setup, I'll try and trace thought through a bit better later but if I'm missing some new options or something that would be great if someone could set me straight. :)

**Comment by freddydk** [comment]
This is a bug.
If you add another environment variable to your call:

RemovePasswordKeyFile=N

then the keyfile will not be removed, and everything should work.
Will be fixed in the next update

**Comment by freddydk** [comment]
Version 0.2.9.0 has been released
