### ISSUE TITLE
Upgrade BC version in existing container [enhancement]

### ISSUE THREAD

**Issue by pmatsconsulting** [microsoft/navcontainerhelper#1192]
Hi,

As now navcontainerhelper is based on generic container images and BC artifacts, it should be possible (for cloud developement projects with Docker) to have the ability to upgrade the BC version (from a new artifact with its platform and apps files) on a existing container. 
Currently we have to recreate the container and loosing data inside or consume time for not loosing them with export/import processes.

**Comment by freddydk** [comment]
The recommended way to upgrade a database is to place the database on the host and use that
