### ISSUE TITLE
How to get original codebase with new container

### ISSUE THREAD

**Issue by naveksa** [microsoft/navcontainerhelper#1196]
**Describe the issue**
Until BC 16.1 when we created a new docker container we got the original codebase downloaded in
C:\ProgramData\NavContainerHelper\Extensions
e.g.
C:\ProgramData\NavContainerHelper\Extensions\Original-16.1.11449.0-dk-al

This no longer happens.
Is there a new parameter we need to add, to get the codebase downloaded with BC 16.3 and onwards ?

**Script**

```
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated: $accept_out `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -auth Windows `
                 -alwaysPull `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters `
                 -licenseFile 'C:\Naveksa\5692763_BC16_300620.flf'
```

**Comment by freddydk** [comment]
I have formatted your script to show the parameters.
Exporting the AL source only happened if you specified -includeAL as parameter to new-bccontainer and that hasn't changed.
Add -includeAL and you will get the source.

**Comment by naveksa** [comment]
Thanks a lot.
The parameter must have been removed by accident. Sorry.
Works again  - Great 👍
