### ISSUE TITLE
Artifact URLs for BC 15.2

### ISSUE THREAD

**Issue by Pavel-Titov** [microsoft/navcontainerhelper#1197]
Hi, one question.
We are currently using 15.2. The new artifacts are available from 15.4 and on.
How long old Images will be supported?

Thanks!

**Comment by freddydk** [comment]
15.2 are available as onprem artifacts (-type onprem)
Are you saying that your online tenant is still on 15.2?
We will keep the existing images for quite some time, we are just not building new ones.

**Comment by Pavel-Titov** [comment]
yes, you are right. with the option OnPrem can I see them all! Thanks!
