### ISSUE TITLE
Question: Real Release for BCContainerHelper

### ISSUE THREAD

**Issue by CriticalMax** [microsoft/navcontainerhelper#1198]
Hey Freddy, not an Issue, more of a general question. Please don't take this the wrong way! 

We kinda have a problem with multitenancy and as luck would have it you already got a fix ready in the BCContainerHelper. Because of the way our pipelines are setup we can't just implement the PreRelease version though.

So my question would be: When do you plan on releasing the BCContainerHelper as non-prerelease?

**Comment by freddydk** [comment]
I will create a 1.0.1 release later today.

**Comment by freddydk** [comment]
You can also use 

install-module bccontainerhelper -force -allowprerelease

to get it right now.

**Comment by CriticalMax** [comment]
Thanks for the quick reply and seems like luck is on our side once again! And yeah, I know of the parameter, but because we have the navcontainerhelper setup a certain way in our pipelines, we don't want to throw that completely over board for a prerelease.
