### ISSUE TITLE
databaseServer in additional parameters

### ISSUE THREAD

**Issue by acyvas** [Microsoft/navcontainerhelper#12]
New-NavContainer fails, resulting in no container created, if i specify database server in additional parameters. Are databaseServer parameters not supported, or I am doing  it in wrong syntax ?
$params =  @('--env databaseServer= "localhost" ')
-additionalParameters $prarams

Thanks!

**Comment by freddydk** [comment]
Yeah, It takes a lot more than that to specify a different database server.
You need to specify databaseServer, instance and database name. The database needs to be present and the user in the container need to have access - or you need to create credentials+encryption keys for the database.
The scenario is possible, but once we have documented some examples on how to do this, it will be much easier for you:-)

**Comment by freddydk** [comment]
database parameters are included in 0.2.1.0 - you can now also specify database credentials.
