### ISSUE TITLE
Host Locally script from MsDyn365BC does not work properly

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#120]
Hi team.
I've tested "Host Locally" option for Sandbox Environment creation on Business Central trial tenant.

My tenant (I guess) 4D367C9D-2698-4F20-A81F-CE4562F69B59

1. In trial tenant I go to >Search> Sandbox Environment (Container) > Host Locally > Downloaded CreateBCSandbox.ps1 script

2. I've changed $accept_eula = $true
3. I've changed $containername = 'AirApps-Sandbox'
4. When I run script i receive error

`Pulling docker Image microsoft/bcsandbox:12.0.21502.0-us
Error response from daemon: manifest for microsoft/bcsandbox:12.0.21502.0-us not found
Error: No such object: microsoft/bcsandbox:12.0.21502.0-us
The property 'Config' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.8.5\ContainerHandling\New-NavContainer.ps1:197 char:23
+ ... devCountry = Get-NavContainerCountry -containerOrImageName $imageName
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-NavContainerCountry], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-NavContainerCountry`

Full script is here
`install-module navcontainerhelper -force

$accept_eula = $true

$containername = 'AirApps-Sandbox'
$navdockerimage = 'microsoft/bcsandbox:12.0.21502.0-us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password
`

**Comment by freddydk** [comment]
Thanks
Apparently US servers was upgraded (or started to deploy 21502) without the docker image having been deployed. I will have a look at the process and fix it.

/Freddy

**Comment by freddydk** [comment]
Should be available now.
