### ISSUE TITLE
Compiling a Test App

### ISSUE THREAD

**Issue by bennyvanlyssebettens** [microsoft/navcontainerhelper#1200]
Container Image: mcr.microsoft.com/businesscentral/onprem:16.3.14085.14238-w1-ltsc2019
AL Compiler: 5.0.312966

I have a test-code-unit

```
codeunit 50147 "Test Attachment"
{
    Subtype = Test;
    TestPermissions = Disabled;

    var
        IsInitialized: Boolean;

    [Test]
    procedure TestAttachment()
    var
        Attachment: record Attachment;
        ProjectGeneralLibrary: codeunit "Project General Library";
        LibraryMarketing: Codeunit "Library - Marketing";

    begin
        ProjectGeneralLibrary.Initialize(Codeunit::"Test Attachment", isInitialized);
        LibraryMarketing.CreateAttachment(Attachment);
    end;
}
```
I receive the following error when I try to compile this App

C:\Run\KTN\Source\test\src\TestAttachment.Codeunit.al(18,43): error AL0133: Argument 1: cannot convert from 'Record Attachment' to 'var __MissingTypeSymbol__'

Installed extensions in this docker, I 'm pretty sure It contains the project (main App) and all the necessary test toolkit stuff

![image](https://user-images.githubusercontent.com/38490754/89643581-5df1da00-d8b6-11ea-8264-938b8fcab3f1.png)

And knows comes the strange part... If I use VS Code studio code with the same codebase and I press package... I dont' receive the error. My launch.json directs to different container since VS Code runs local on my machine ( Windows 10 generic image + artifacts 16.3.14085.14238-w1 )

![image](https://user-images.githubusercontent.com/38490754/89644287-dc9b4700-d8b7-11ea-9a13-f7a7559bc27d.png)

And even stranger, if I install this Test app in the first container, where the compilation failed, it get's published & synced. No problem at all.

I don't get it...

**Comment by freddydk** [comment]
I have no idea what this is, but it doesn't seem related to docker.
I have no idea where the Attachment record is defined, but it seems like a missing reference to this.

**Comment by freddydk** [comment]
Please re-open with more information if the problem persists.
