### ISSUE TITLE
Use External SQL Database in a nav/bc container from development purpose

### ISSUE THREAD

**Issue by Steven-Bale** [microsoft/navcontainerhelper#1201]
Hello,

I tried to set up a connection in a container of an external SQL Database of 60gb.
i tried some script but i always the following message :
docker run -it --name sqlconnectiontest microsoft/mssql-server-windows-developer powershell -command "Invoke-Sqlcmd -ServerInstance 'localhost' -Username 'sa' -Password '{Apassword}' -Database 'test' -Query 'SELECT COUNT(*) FROM [dbo].[User]'"
[2J[H[1;31;40mInvoke-Sqlcmd : A connection was successfully established with the server, but [22;37;40m
[1;31;40mthen an error occurred during the login process. (provider: Shared Memory [22;37;40m
[1;31;40mProvider, error: 0 - No process is on the other end of the pipe.)[22;37;40m
[1;31;40mAt line:1 char:1[22;37;40m
[1;31;40m+ Invoke-Sqlcmd -ServerInstance 'localhost' -Username 'sa' -Password 'B ...[22;37;40m
[1;31;40m+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[22;37;40m
[1;31;40m    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlExcept [22;37;40m
[1;31;40m   ion[22;37;40m
[1;31;40m    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management. [22;37;40m
[1;31;40m   PowerShell.GetScriptCommand[22;37;40m
[1;31;40m [22;37;40m
[1;31;40mInvoke-Sqlcmd : [22;37;40m
[1;31;40mAt line:1 char:1[22;37;40m
[1;31;40m+ Invoke-Sqlcmd -ServerInstance 'localhost' -Username 'sa' -Password 'B ...[22;37;40m
[1;31;40m+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[22;37;40m
[1;31;40m    + CategoryInfo          : ParserError: (:) [Invoke-Sqlcmd], ParserExceptio [22;37;40m
[1;31;40m   n[22;37;40m
[1;31;40m    + FullyQualifiedErrorId : ExecutionFailureException,Microsoft.SqlServer.Ma [22;37;40m
[1;31;40m   nagement.PowerShell.GetScriptCommand[22;37;40m
[1;31;40m [22;37;40m

Could you tell me what is wrong in my installation ?

Thanks.

**Comment by freddydk** [comment]
SQL Server images on Windows are very old and not something I can support here.
My recommendation is to install SQL Server on the host or a server if you want to host the database outside the NAV/BC container.

**Comment by freddydk** [comment]
Read more about that here: https://freddysblog.com/2019/11/04/using-sql-server-on-the-host/
