### ISSUE TITLE
BcContainerHelper generated script issue

### ISSUE THREAD

**Issue by SVirlan** [microsoft/navcontainerhelper#1203]
Running the script generated with New-BcContainerWizzard 
#####################################################
"$containerName = 'bc-wizz-cont'
$credential = Get-Credential -Message 'Using Windows authentication. Please enter your Windows credentials for the host computer.

$auth = 'Windows'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '14.6.36463' -country 'na' -select 'Latest'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'nav2017cu5wizz' `
    -licenseFile "C:\Containers\DEV_LIC\BC14.flf" `
    -includeCSIDE
#####################################################

gives me this error:

#####################################################
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.27.230.80
Container Hostname  : bc-wizz-cont
Container Dns Name  : bc-wizz-cont
Web Client          : http://bc-wizz-cont/NAV/
Dev. Server         : http://bc-wizz-cont
Dev. ServerInstance : NAV

Files:
http://bc-wizz-cont:8080/ALLanguage.vsix

Initialization took 155 seconds
Ready for connections!
Reading CustomSettings.config from bc-wizz-cont
Creating Desktop Shortcuts for bc-wizz-cont
Export-BcContainerObjects : The term 'Export-BcContainerObjects' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.1\ContainerHandling\New-NavContainer.ps1:1773 char:17
+                 Export-BcContainerObjects -containerName $containerNa ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Export-BcContainerObjects:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
#####################################################

Any idea why?

**Comment by freddydk** [comment]
Yes, Export-BcContainerObjects doesn't exist - that is a bug in New-BcContainer, it needs to be Export-NavContainerObjects.

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 1.0.2-preview153
