### ISSUE TITLE
The value of deployment parameter 'BCDockerImage' is null. Please specify the value or use the parameter reference. 

### ISSUE THREAD

**Issue by mhenricus** [microsoft/navcontainerhelper#1205]
**Describe the issue**
When creating an container on Azure with the ARM template http://aka.ms/getbc, the parameter 'BC Docker Image' is empty by default, the error seems to want it filled, ignoring the artifact url.

**Scripts used to create container and cause the issue**
```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": {
      "value": "bcsandbox-w1"
    },
    "TimezoneId": {
      "value": "GMT Standard Time"
    },
    "AcceptEula": {
      "value": "Yes"
    },
    "RemoteDesktopAccess": {
      "value": "82.169.122.134"
    },
    "WinRMAccess": {
      "value": "-"
    },
    "OperatingSystem": {
      "value": "Windows Server 2019 with Containers"
    },
    "vmSize": {
      "value": "Standard_D4s_v3"
    },
    "Isolation": {
      "value": "Default"
    },
    "vmAdminUsername": {
      "value": "vmadmin"
    },
    "BCAdminUsername": {
      "value": "admin"
    },
    "adminPassword": {
      "value": "..."
    },
    "ArtifactUrl": {
      "value": "bcartifacts/onprem//w1/latest"
    },
    "BCDockerImage": {
      "value": null
    },
    "AssignPremiumPlan": {
      "value": "Yes"
    },
    "CreateTestUsers": {
      "value": "Yes"
    },
    "LicenseFileUri": {
      "value": null
    },
    "EnableTaskScheduler": {
      "value": "Yes"
    },
    "Office365UserName": {
      "value": null
    },
    "Office365Password": {
      "value": null
    },
    "CreateAadUsers": {
      "value": "No"
    },
    "BingMapsKey": {
      "value": null
    },
    "RunWindowsUpdate": {
      "value": "No"
    },
    "ContactEMailForLetsEncrypt": {
      "value": null
    },
    "AutoShutdown": {
      "value": "Enabled"
    },
    "AutoShutdownTime": {
      "value": "20:00"
    },
    "AddTraefik": {
      "value": "No"
    }
  }
}
```

**Full output of scripts**
```
na.
```

**Screenshots**
![image](https://user-images.githubusercontent.com/69308907/89753898-5448bc00-dada-11ea-929a-5c7fba5ad928.png)
![image](https://user-images.githubusercontent.com/69308907/89753908-60347e00-dada-11ea-8dcf-dcab40dfcb94.png)
![image](https://user-images.githubusercontent.com/69308907/89753924-66c2f580-dada-11ea-9354-abfbebcd0513.png)

{"telemetryId":"4640f724-5b9f-4cac-9517-09ba0989fa31","bladeInstanceId":"Blade_caf9b51e5fc3401e8b819136957f3004_1_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"InvalidDeploymentParameterValue","message":"The value of deployment parameter 'BCDockerImage' is null. Please specify the value or use the parameter reference. See https://aka.ms/resource-manager-parameter-files for details."}

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by mhenricus** [comment]
I just tried http://aka.ms/bcsandboxazure, and now the license file seems mandatory!? 

{"telemetryId":"ebc72402-55f4-45e1-afd7-0cb493f3e498","bladeInstanceId":"Blade_3513229d897c4b4ea0231a467c47ac5c_1_0","galleryItemId":"Microsoft.Template","createBlade":"DeployToAzure","code":"InvalidDeploymentParameterValue","message":"The value of deployment parameter 'LicenseFileUri' is null. Please specify the value or use the parameter reference. See https://aka.ms/resource-manager-parameter-files for details."}

**Scripts used to create container and cause the issue**

{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "vmName": {
      "value": "bcsandbox-d"
    },
    "TimezoneId": {
      "value": "GMT Standard Time"
    },
    "AcceptEula": {
      "value": "Yes"
    },
    "RemoteDesktopAccess": {
      "value": "*"
    },
    "OperatingSystem": {
      "value": "Windows Server 2019 with Containers"
    },
    "vmSize": {
      "value": "Standard_D4s_v3"
    },
    "vmAdminUsername": {
      "value": "vmadmin"
    },
    "navAdminUsername": {
      "value": "admin"
    },
    "azureSqlAdminUsername": {
      "value": "sqladmin"
    },
    "adminPassword": {
      "value": "..."
    },
    "ArtifactUrl": {
      "value": "bcartifacts/sandbox//us/latest"
    },
    "navDockerImage": {
      "value": "mcr.microsoft.com/businesscentral/sandbox:us"
    },
    "AssignPremiumPlan": {
      "value": "Yes"
    },
    "CreateTestUsers": {
      "value": "Yes"
    },
    "LicenseFileUri": {
      "value": null
    },
    "SQLServerType": {
      "value": "SQLExpress"
    },
    "AppBacpacUri": {
      "value": null
    },
    "TenantBacpacUri": {
      "value": null
    },
    "IncludeAppUris": {
      "value": null
    },
    "RunWindowsUpdate": {
      "value": "No"
    },
    "ContactEMailForLetsEncrypt": {
      "value": null
    },
    "AutoShutdown": {
      "value": "Enabled"
    },
    "AutoShutdownTime": {
      "value": "20:00"
    },
    "AddTraefik": {
      "value": "No"
    }
  }
}

**Comment by freddydk** [comment]
When you launch the URL - are you then using the Edit Parameters button to modify values - or are you modifying values directly in the template?

**Comment by freddydk** [comment]
I mean - what is the exact process to get this problem.
If I launch the template, accept the eula, set names and password and press create - then everything works.

**Comment by mhenricus** [comment]
1. I click on the url from you blog page: https://freddysblog.com/2020/07/02/the-arm-templates-now-supports-artifacts-and-images/
2. Sign in to Azure
3. Fill in the required parameters
4. Click Edit parameters: to be able to copy the parameters file to put these here on github
5. Discard changes: to return to the page with parameters
6. Click 'Purchase'

I just tried another time without step 4 and 5, and now it is deploying. So, going to the parameters page seems to be the problem.

**Comment by freddydk** [comment]
Not sure what the azure portal is doing in this case. but this is the first time I have heard this and I am not sure that this is something I can fix.
