### ISSUE TITLE
Unable to use SQL server on host

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#1210]
I've restored a backup to my own SQL server, and wanted to use an image to connect and handle it. However it seems that I am missing something. (sa user and pw are correct) 

```
$containerName = 'upg2016'
$credential = Get-Credential -Message 'Using Windows authentication. Please enter your Windows credentials for the host computer.'
$auth = 'Windows'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '9.0.46621.0' -country 'dk' -select 'Closest'
$databaseServer = 'SH-PC'
$databaseInstance = 'SQL2019'
$databaseName = '6X_PROD'
$databaseUsername = 'sa'
$databasePassword = 'P@ssw0rd'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = 'c:\nav\infar\devlicens_2016.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'upg2016' `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -shortcuts CommonDesktopFolder `
    -updateHosts

```

This script has a dependency on the PowerShell module BcContainerHelper.
See more here: https://www.powershellgallery.com/packages/bccontainerhelper
Use 'Install-Module BcContainerHelper -force' to install in PowerShell
PS C:\Windows\system32> New-BcContainerWizard

```
PS C:\Windows\system32> C:\Users\sh\Documents\upg2016.ps1
NavContainerHelper is version 0.7.0.23
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
ArtifactUrl and ImageName specified
Fetching all docker images
Image upg2016:onprem-9.0.46621.0-dk-nodb doesn't exist
Building image upg2016:onprem-9.0.46621.0-dk-nodb based on https://bcartifacts.azureedge.net/onprem/9.0.46621.0/dk
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.18363.959-generic
10.0.18363.959-generic: Pulling from dynamicsnav
Generic Tag: 0.1.0.14
Container OS Version: 10.0.18363.959 (1909)
Host OS Version: 10.0.18363.959 (1909)
Copying Platform Artifacts
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
c:\bcartifacts.cache\tmp637326697265593912
Sending build context to Docker daemon    392MB

Step 1/6 : FROM mcr.microsoft.com/dynamicsnav:10.0.18363.959-generic
 ---> 07ecc36d8c21
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/9.0.46621.0/dk
 ---> Using cache
 ---> 3ce9a9508a0d
Step 3/6 : COPY my /run/
 ---> Using cache
 ---> e2f0ae4e4cec
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 0913162619d5
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in a6352e938d42
Using installer from C:\Run\90
Installing NAV
Starting Local SQL Server
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Skipping restore of Cronus database
Installing C:\NAVDVD\Installers\DK\OlAddin\OutlookAddIn.Local.Dk.msi
Installing C:\NAVDVD\Installers\DK\RTC\RoleTailoredClient.Local.Dk.msi
Installing C:\NAVDVD\Installers\DK\Server\Server.Local.Dk.msi
Installing C:\NAVDVD\Installers\DK\WebClient\WebClient.Local.Dk.msi
Skipping C:\NAVDVD\Installers\DK\WebHelp\WebHelp.Local.Dk.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 59 seconds
Installation complete
Removing intermediate container a6352e938d42
 ---> bd6863003933
Step 6/6 : LABEL legal="http://go.microsoft.com/fwlink/?LinkId=837447"       created="202008101322"       nav="2016"       cu="cu10"       skipdatabase="Y" country="dk"       version="9.0.4662
1.0"       platform="9.0.46621.0"
 ---> Running in 5ff659a32ef5
Removing intermediate container 5ff659a32ef5
 ---> 00020a72aaf2
Successfully built 00020a72aaf2
Successfully tagged upg2016:onprem-9.0.46621.0-dk-nodb
Building image took 121 seconds
Using image upg2016:onprem-9.0.46621.0-dk-nodb
Creating Container upg2016
Version: 9.0.46621.0-dk
Style: onprem
Platform: 9.0.46621.0
Generic Tag: 0.1.0.14
Container OS Version: 10.0.18363.959 (1909)
Host OS Version: 10.0.18363.959 (1909)
Using locale da-DK
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file c:\nav\infar\devlicens_2016.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\upg2016\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container upg2016 from image upg2016:onprem-9.0.46621.0-dk-nodb
54bc76fd47663051971162d37d333844b05c2f6d21e72689e57d7ed72bfd0a29
Waiting for container upg2016 to be ready
Initializing...
Setting host.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.208.1 in container hosts file
Starting Container
Hostname is upg2016
PublicDnsName is upg2016
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Der kan ikke oprettes en forbindelse til SQL-serveren/databasen. 
  
Det kan bl.a. skyldes Ã©t af fÃ¸lgende:

* SQL-serveren er ikke startet.
* Databasen findes ikke.
* Der er ikke tildelt de korrekte tilladelser til NAV-serverkontoen.

PrÃ¸v igen senere, eller kontakt systemadministratoren.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 135
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 338
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.208.1 in container hosts file
Starting Container
Hostname is upg2016
PublicDnsName is upg2016
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Der kan ikke oprettes en forbindelse til SQL-serveren/databasen. 
  
Det kan bl.a. skyldes Ã©t af fÃ¸lgende:

* SQL-serveren er ikke startet.
* Databasen findes ikke.
* Der er ikke tildelt de korrekte tilladelser til NAV-serverkontoen.

PrÃ¸v igen senere, eller kontakt systemadministratoren.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 135
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 338
at <ScriptBlock>, <No file>: line 1
Initialization of container upg2016 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.23\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... upg2016 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container upg2016 failed


```
PS C:\Windows\system32> get-navcontainereventlog upg2016
Getting event log for upg2016

PS C:\Windows\system32> 

Only errors I can find in the log relate o Security-SSP:
Licensaktivering (slui.exe) mislykkedes med følgende fejlkode: 
hr=0x8007232B
Kommandolinjeargumenter: 
RuleId=eeba1977-569e-4571-b639-7623d8bfecc0;Action=AutoActivate;AppId=55c92734-d682-4d71-983e-d6ec3f16059f;SkuId=90c362e5-0da1-4bfd-b53b-b87d309ade43;NotificationInterval=1440;Trigger=TimerEvent

[upg2016 2020-08-10 15.29.46.txt](https://github.com/microsoft/navcontainerhelper/files/5051139/upg2016.2020-08-10.15.29.46.txt)

**Comment by Rukkulakki** [comment]
NB: Firewall disabled

**Comment by freddydk** [comment]
The container is probably still running.
If you enter the container (enter-bccontainer) - did you try to ping the sql server and see whether you have access to that machine from inside the container?

**Comment by Rukkulakki** [comment]
PS C:\Windows\system32> Enter-BCContainer upg2016
Welcome to the NAV Container PowerShell prompt


[UPG2016]: PS C:\Run> ping sh-pc
Ping request could not find host sh-pc. Please check the name and try again.


It can ping my IP, so will try to run it while entering IP instead

**Comment by freddydk** [comment]
if SH-PC is the host, you should use host.containerhelper.internal as the databaseserver.
https://freddysblog.com/2019/11/04/using-sql-server-on-the-host/

**Comment by Rukkulakki** [comment]
Tried with host.containerhelper.internal, and it gets a bit further.

Files:

Initialization took 20 seconds
Ready for connections!
Reading CustomSettings.config from upg2016b
Creating Desktop Shortcuts for upg2016b
Container upg2016b successfully created
upg2016
Waiting for container upg2016 to be ready

Initializing...
Setting host.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.208.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is upg2016
PublicDnsName is upg2016
Using Windows Authentication
Starting Internet Information Server
Starting Service Tier
Container IP Address: 192.168.213.81
Container Hostname  : upg2016
Container Dns Name  : upg2016
Web Client          : 
Setting upg2016 to 192.168.213.81 in host hosts file

Files:
Cannot find path 'C:\inetpub\wwwroot\http' because it does not exist.
at <ScriptBlock>, C:\Run\navstart.ps1: line 247
at <ScriptBlock>, C:\Run\start.ps1: line 338
at <ScriptBlock>, <No file>: line 1Error

Initializing...
Setting host.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.208.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is upg2016
PublicDnsName is upg2016
Using Windows Authentication
Starting Internet Information Server
Starting Service Tier
Container IP Address: 192.168.213.81
Container Hostname  : upg2016
Container Dns Name  : upg2016
Web Client          : 
Setting upg2016 to 192.168.213.81 in host hosts file

Files:
Cannot find path 'C:\inetpub\wwwroot\http' because it does not exist.
at <ScriptBlock>, C:\Run\navstart.ps1: line 247
at <ScriptBlock>, C:\Run\start.ps1: line 338
at <ScriptBlock>, <No file>: line 1
Initialization of container upg2016 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.23\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... upg2016 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container upg2016 failed
 

PS C:\Windows\system32> Enter-BCContainer upg2016b
Pinging host.containerhelper.internal [192.168.208.1] with 32 bytes of data:
Reply from 192.168.208.1: bytes=32 time<1ms TTL=128
Reply from 192.168.208.1: bytes=32 time<1ms TTL=128
Reply from 192.168.208.1: bytes=32 time<1ms TTL=128
Reply from 192.168.208.1: bytes=32 time<1ms TTL=128

Ping statistics for 192.168.208.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

**Comment by freddydk** [comment]
seems to be a different problem - please include the full script and output and please format it with "insert code" in the toolbar.
Also please remove the old image upg2016

**Comment by Rukkulakki** [comment]
I think you may have written the incorrect variable above. Reading the messages and your blog, I ran the wizzard again using "UserPasswrod" and host.docker.internal. And now it works 👍 

Full script:
$containerName = 'upg2016b'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '9.0.46621.0' -country 'dk' -select 'Closest'
$databaseServer = 'host.docker.internal'
$databaseInstance = 'SQL2019'
$databaseName = '6X_PROD'
$databaseUsername = 'sa'
$databasePassword = 'P@ssw0rd'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = 'c:\nav\infar\devlicens_2016.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'upg2016c' `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -includeCSIDE `
    -shortcuts CommonDesktopFolder `
    -updateHosts


And then just create a user with New-NavContainerNavUser

**Comment by freddydk** [comment]
What does this mean?
"I think you may have written the incorrect variable above"

**Comment by Rukkulakki** [comment]
Earlier you wrote "if SH-PC is the host, you should use host.**containerhelper**.internal as the databaseserver." But I got it to work when I used host.**docker**.internal.
So I guessed that you wrote a different variablename than the one you thought about in the suggestion.

**Comment by freddydk** [comment]
Ahh - it all depends on what your SQL server is listening on.
In the output you see the options:

Setting host.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.28.52 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.208.1 in container hosts file

**Comment by freddydk** [comment]
I will close the issue as resolved.
