### ISSUE TITLE
BcContainerHelper installation issue

### ISSUE THREAD

**Issue by SVirlan** [microsoft/navcontainerhelper#1211]
Trying to install the latest BcContainerHelper errors out:

**********************************************************
Install-Module -Name BcContainerHelper -AllowPrerelease
Install-Module : A parameter cannot be found that matches parameter name 'AllowPrerelease'.
At line:1 char:40
+ Install-Module -Name BcContainerHelper -AllowPrerelease
+                                        ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module
**********************************************************

Am I missing something?

**Comment by freddydk** [comment]
https://docs.microsoft.com/en-us/powershell/scripting/gallery/concepts/module-prerelease-support

**Comment by freddydk** [comment]
You need to update powershellget

**Comment by freddydk** [comment]
https://twitter.com/MVPKine/status/1290192525735731200

**Comment by SVirlan** [comment]
Installing powershellget solved the problem. 

>>Install-Module -Name PowerShellGet -Repository PSGallery -Force

Thanks Freddy!
