### ISSUE TITLE
More detailed instructions for moving to BCContainerHelper

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/navcontainerhelper#1212]
Thanks for releasing BC Container Helper. We're keen to get it in use.

Aside from the obvious updating of our scripts, is there a correct method to use when migrating from the old container helper to the new one? I.e. should we uninstall navcontainerhelper, then install new one?

Some updated instructions under https://github.com/microsoft/navcontainerhelper#branches would be great just to make sure we're not missing anything.

**Comment by freddydk** [comment]
Yep, I will write a blog post about changing from nav to bc container helper (very soon)

**Comment by ShadowXVII** [comment]
Sweet, looking forward to it.

**Comment by freddydk** [comment]
https://freddysblog.com/2020/08/11/bccontainerhelper/
