### ISSUE TITLE
Generate-SymbolsInNavContainer.ps1 does not have BC alias

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#1219]
Running Import-TestToolkitToBCContainer in a v14 container with Symbol generation enabled fails with:

_The term 'Generate-SymbolsInBcContainer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
            at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.2\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 238_

And it seems that its because there are no alias for Generate-SymbolsInBcContainer.

**Comment by freddydk** [comment]
I will fix this at the call level - the missing alias is on purpose.
You can not generate symbols in a bc (AL) container - only in a nav (C/AL) container

**Comment by freddydk** [comment]
Fix will be in a pre-release in a few hours.

**Comment by freddydk** [comment]
Included in 1.0.3 as well.
