### ISSUE TITLE
Database name when using own backup file

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#122]
When I use own bak file for the database inside the container, the database is named mydatabase, but in docker inspect output the environment variable DatabaseName is still CronusXX. I will expect to have it as mydatabase.

**Comment by freddydk** [comment]
The environment variables on docker inspect are set as they are after build/run of the container. They cannot be changed from within.

**Comment by kine** [comment]
Ok, than I will go around. Thanks.
