### ISSUE TITLE
Documentation about BcContainerHelper.config.json

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/navcontainerhelper#1223]
Hi Freddy!

I just figured out what the possible settings are by looking into BcContanierHelper.psm1, nontheless a short blog post would be usefull for others in the future, I guess.

Thank you, keep up the great work!

**Comment by freddydk** [comment]
https://freddysblog.com/2020/08/11/bccontainerhelper/ states a little about this, but a blog post is planned.

**Comment by freddydk** [comment]
https://freddysblog.com/2020/10/10/bccontainerhelper-configuration/
