### ISSUE TITLE
404 Error - Download Prerequisites

### ISSUE THREAD

**Issue by NAVRockClimber** [microsoft/navcontainerhelper#1224]
**Describe the issue**
If you try to download the artifacts with the include plattform tag you receive a 404 error during download of the url rewrite module.

**Scripts used to create container and cause the issue**
```
Flush-ContainerHelperCache
$msToken = "..."
$artefactUrl = Get-BCArtifactUrl -type Sandbox -country de -storageAccount bcinsider -sasToken $msToken -select SecondToLastMajor
Download-Artifacts -artifactUrl $artefactUrl -includePlatform
```

**Full output of scripts**
```
Downloading platform artifact /sandbox/16.5.15639.0/platform
Downloading C:\Users\<user>\AppData\Local\Temp\3f8e0d63-1eaf-4483-89f1-bd76f6463eac.zip
Unpacking platform artifact to tmp folder using 7zip
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\16.5.15639.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\16.5.15639.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Download-File : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.23\Misc\Download-Artifacts.ps1:206 char:45
+ ...             Download-File -sourceUrl $url -destinationFile $path -tim ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File
```

**Screenshots**
n/a

**Additional context**
- I checked the urls in Prerequisite Components.json.
- If I throw the URL for the rewrite module into a browser I receive a 404.
- did it use to work? yes

**Same for**
```
Flush-ContainerHelperCache
$artefactUrl = Get-BCArtifactUrl -type Sandbox -country de 
Download-Artifacts -artifactUrl $artefactUrl -includePlatform
```

**Comment by freddydk** [comment]
https://freddysblog.com/2020/08/18/one-of-these-days/

**Comment by freddydk** [comment]
Fix shipped in BcContainerHelper 1.0.3
Fix will ship in NavContainerHelper 0.7.0.25

**Comment by NAVRockClimber** [comment]
Sorry, I did not check your blog & twitter.

**Comment by freddydk** [comment]
No problem - it is fine to have an issue here - will leave it open for other people to find.

**Comment by FrankAuwers** [comment]
The error is still the same in version 1.0.3
PS C:\WINDOWS\system32> Get-Module -All -ListAvailable -Name BcContainerHelper
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands                                                
---------- -------    ----                                ----------------                                                
Script     1.0.3      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-BcC...
Script     1.0.3      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-BcC...

But with execution of New-BcContainer command it says that is still version 1.0.2
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'scaptify' `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -licenseFile $licenseFile `
    -dns '8.8.8.8' `
    -usessl -installCertificateOnHost `
    -memoryLimit 8G `
    -updateHosts
BcContainerHelper is **version 1.0.2**
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 2004

**Error**
Downloading c:\bcartifacts.cache\sandbox\16.4.14693.15627\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Download-File : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.2\Misc\Download-Artifacts.ps1:206 char:45
+ ...             Download-File -sourceUrl $url -destinationFile $path -tim ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File

**Comment by catadumitru** [comment]
I still get the error with version 0.7.0.25
Script output:
Create BuildPV2-build from https://bcinsider.azureedge.net/sandbox/16.5.15646.0/w1
 NavContainerHelper is version **0.7.0.25**
 NavContainerHelper is running as administrator
 Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
...
Downloading Url Rewrite
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
at InstallPrerequisite, C:\Run\HelperFunctions.ps1: line 579
at <ScriptBlock>, C:\Run\navinstall.ps1: line 26
at <ScriptBlock>, C:\Run\start.ps1: line 209
at <ScriptBlock>, <No file>: line 1

At C:\Program 

Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.25\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17

+ ...             throw "Initialization of container $containerName failed" ...

**Comment by freddydk** [comment]
That is not the same as above.
Above you used Download-Artifacts - this is something in the container.
Somehow you haven't gotten the latest generic image - you need to provide full script + full output.
