### ISSUE TITLE
Getting Error while Integrating Bussiness Central with Outlook 

### ISSUE THREAD

**Issue by VAIBHAV-NAGAR** [microsoft/navcontainerhelper#1226]
Hi 

I am try to integrate the Bussiness Central with the Outlook. I am using docker, when i am running the assisted setup its giving me below error.
![image](https://user-images.githubusercontent.com/58846308/90502218-1b0fec00-e16b-11ea-817a-230a03c8230f.png)

Steps 
Go to Assisted Setup in BC 
Then under **Do More with Business Central** click on **Setup your Business Inbox In Outlook**
Then complete the setup by providing all the details such as Email and password 
when i click on finish its giving me the error

Its possible to run this setup using docker ?
If anyone knows the solution and can help me out , it would be great

Thanks 
Vaibhav

**Comment by freddydk** [comment]
If you specify -useSSL (and potentially -installcertificateonhost) when creating your container, you will get https and maybe that helps?

**Comment by VAIBHAV-NAGAR** [comment]
Hi Freddy 

Thanks for the reply !

I have created the Container Using -useSSL  but its not compiling throught the VSCode and when I am open it in Web 
(outlook is the Container Name)
![image](https://user-images.githubusercontent.com/58846308/90606900-1a845d80-e21e-11ea-9370-835949e377d0.png)
When I click On the Advance its showing me the below error 
![image](https://user-images.githubusercontent.com/58846308/90606763-e315b100-e21d-11ea-8486-5855de6486f5.png)

Thanks 
Vaibhav Nagar

**Comment by freddydk** [comment]
Yes, useSSL creates a self-signed certificate. If you add -installCertificateonhost then containerhelper will install and trust the certificate. If you want to use a trusted certificate you need to buy one  yourself or use letsencrypt (which https://aka.ms/getbc does).
This old blog post talks about certificates: https://freddysblog.com/2017/02/06/ssl-certificates-101/
