### ISSUE TITLE
BC16.4 container creation fails

### ISSUE THREAD

**Issue by SirBETE** [microsoft/navcontainerhelper#1228]
**Describe the issue**
BC16.4 artifact downloads dynamicsnav:10.0.14393.3808-generic, but fails with error "The system cannot find the file specified." Or "There is not enough space on the disk."

Uses BC10.0 image to create the container

**Scripts used to create container and cause the issue**
```
Get-Module BCContainerHelper -ListAvailable
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
Remove-Module NavContainerHelper
Install-Module -Name BCContainerHelper -RequiredVersion 1.0.3
#Use BCContainerHelper instead of NavContainerHelper

#BC16.4+
$version = "16.4"
$ContainerName = "Master"
$auth = "Windows"
#$auth = "UserPassword"
#$credential = New-Object pscredential 'P', (ConvertTo-SecureString -String 'P' -AsPlainText -Force)
$License = 'C:\License\us.flf'

#Lijst:
#Get-BCArtifactUrl -country "be" -version $version -select All

$artifactUrl = Get-BCArtifactUrl -country "be" -version $version

Write-Host -ForegroundColor Yellow "creating $ContainerName $artifactUrl"
Download-Artifacts -artifactUrl $artifactUrl  -includePlatform

Write-Host -ForegroundColor Yellow "bcimage"
New-BCImage -artifactUrl $artifactUrl -imageName myownimage

Write-Host -ForegroundColor Yellow "Creating container $ContainerName"
Remove-BCContainer $ContainerName

Measure-Command {
    New-BCContainer `
        -accept_eula `
        -containerName $ContainerName `
        -artifactUrl $artifactUrl `
        -updateHosts `
        -auth $auth `
        -licenseFile $License `
        -includeAL `
        -imagename myownimage
}
```

**Full output of scripts**
```
ModuleType Version    Name                                ExportedCommands                                                                                                                                        
---------- -------    ----                                ----------------                                                                                                                                        
Script     1.0.3      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-BcContainerDatabases, Check-BcContainerHelperPermissions...}                                  
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those modules exist in the runspace.
At C:\Users\b\Documents\NAVMaster\PowerShell\InstallContainerArtifacts.ps1:3 char:1
+ Remove-Module NavContainerHelper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
 
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'BCContainerHelper'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 
creating Master https://bcartifacts.azureedge.net/sandbox/16.4.14693.15645/be
Downloading application artifact /sandbox/16.4.14693.15645/be
Downloading C:\Users\b\AppData\Local\Temp\6a698be5-ebf2-4f35-b013-2d49a257f300.zip
Unpacking application artifact to tmp folder using 7zip
c:\bcartifacts.cache\sandbox\16.4.14693.15645\be
Downloading platform artifact /sandbox/16.4.14693.15645/platform
Downloading C:\Users\b\AppData\Local\Temp\9e7b9236-f1dd-4261-9515-05571a45eee4.zip
Unpacking platform artifact to tmp folder using 7zip
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\16.4.14693.15645\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\16.4.14693.15645\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\16.4.14693.15645\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
c:\bcartifacts.cache\sandbox\16.4.14693.15645\platform
bcimage
Building image myownimage:sandbox-16.4.14693.15645-be based on mcr.microsoft.com/dynamicsnav:10.0.14393.3808-generic
myownimage:sandbox-16.4.14693.15645-be
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.14393.3808-generic
10.0.14393.3808-generic: Pulling from dynamicsnav
Generic Tag: 0.1.0.16
Container OS Version: 10.0.14393.3808 (ltsc2016)
Host OS Version: 10.0.14393.3808 (ltsc2016)
Using process isolation
Files in c:\bcartifacts.cache\tmp637333527557152873\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Extensions
Copying Applications.BE
c:\bcartifacts.cache\tmp637333527557152873
Sending build context to Docker daemon  1.783GB

Step 1/6 : FROM mcr.microsoft.com/dynamicsnav:10.0.14393.3808-generic
 ---> 919a8b4f600a
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/16.4.14693.15645/be
 ---> Running in fdae7625ef56
Removing intermediate container fdae7625ef56
 ---> f007330f56f4
Step 3/6 : COPY my /run/
 ---> af6f77cf3b19
Step 4/6 : COPY NAVDVD /NAVDVD/
docker : failed to copy files: failed to copy directory: chtimes \\?\Volume{b74e77cd-ba8e-11e9-9c1f-bbbb99aed92d}\NAVDVD\ServiceTier\program files\Microsoft Dynamics NAV\160\Service\Microsoft.Owin.dll: The syst
em cannot find the file specified.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\ContainerHandling\New-NavImage.ps1:346 char:1
+ docker build --isolation=$isolation --memory $memory --tag $imageName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (failed to copy ...file specified.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Screenshots**
/

**Additional context**
- does it happen all the time? yep
- did it use to work? Can create containers with old navcontainerhelper without artifacts for bc16.3

**Comment by SirBETE** [comment]
When I leave out the BC Image
#New-BCImage -artifactUrl $artifactUrl -imageName myownimage
it also fails:
Creating DotNetCore Web Server Instancedocker : . : The term 'c:\Run\MainLoop.ps1' is not recognized as the name of a cmdlet, 

```
ModuleType Version    Name                                ExportedCommands                                                                                                                                        
---------- -------    ----                                ----------------                                                                                                                                        
Script     1.0.3      BcContainerHelper                   {Add-FontsToBcContainer, Add-GitToAlProjectFolder, Backup-BcContainerDatabases, Check-BcContainerHelperPermissions...}                                  
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those modules exist in the runspace.
At C:\Users\b\Documents\NAVMaster\PowerShell\InstallContainerArtifacts.ps1:3 char:1
+ Remove-Module NavContainerHelper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
 
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'BCContainerHelper'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 
creating Master https://bcartifacts.azureedge.net/sandbox/16.4.14693.15645/be
c:\bcartifacts.cache\sandbox\16.4.14693.15645\be
c:\bcartifacts.cache\sandbox\16.4.14693.15645\platform
bcimage
Creating container Master
BcContainerHelper is version 1.0.3
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.14393.3808-generic
Creating Container Master
Version: 16.4.14693.15645-BE
Style: sandbox
Multitenant: Yes
Platform: 16.0.14648.15622
Generic Tag: 0.1.0.16
Container OS Version: 10.0.14393.3808 (ltsc2016)
Host OS Version: 10.0.14393.3808 (ltsc2016)
Using process isolation
Using locale nl-BE
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\License\us.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\Master\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container Master from image mcr.microsoft.com/dynamicsnav:10.0.14393.3808-generic
bd78a9437e2e22f7ffb7ebbc809c6c694aa9f661d1536d283bc8219120b7e878
Waiting for container Master to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/16.4.14693.15645/be
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\16.4.14693.15645\be\BusinessCentral-BE.bak
Restoring CRONUS Demo Database
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing CRONUS license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.BE
Installation took 297 seconds
Installation complete
Initializing...
Starting Container
Hostname is Master
PublicDnsName is Master
WARNING: DNS resolution not working from within the container.
Using Windows Authentication
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instancedocker : . : The term 'c:\Run\MainLoop.ps1' is not recognized as the name of a cmdlet, 
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\ContainerHandling\Wait-NavContainerReady.ps1:31 char:21
+             $logs = docker logs $containerName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (. : The term 'c...e of a cmdlet, :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by freddydk** [comment]
Could you try to add -isolation hyperv to your new-navcontainer command?

**Comment by SirBETE** [comment]
Without using BC Image, has it created an "unhealthy" container master, that's unable to run.

Log:
{"log":"Using artifactUrl https://bcartifacts.azureedge.net/sandbox/16.4.14693.15645/be\n","stream":"stdout","time":"2020-08-18T11:17:26.0913582Z"}
{"log":"Using installer from C:\\Run\\150-new\n","stream":"stdout","time":"2020-08-18T11:17:26.817309Z"}
{"log":"Installing Business Central\n","stream":"stdout","time":"2020-08-18T11:17:27.0839517Z"}
{"log":"Installing from artifacts\n","stream":"stdout","time":"2020-08-18T11:17:27.1010182Z"}
{"log":"Starting Local SQL Server\n","stream":"stdout","time":"2020-08-18T11:17:27.1020189Z"}
{"log":"WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to \r\n","stream":"stdout","time":"2020-08-18T11:17:36.2152793Z"}
{"log":"start...\n","stream":"stdout","time":"2020-08-18T11:17:36.2152793Z"}
{"log":"Starting Internet Information Server\n","stream":"stdout","time":"2020-08-18T11:17:36.4791958Z"}
{"log":"Copying Service Tier Files\n","stream":"stdout","time":"2020-08-18T11:17:36.8999361Z"}
{"log":"Copying PowerShell Scripts\n","stream":"stdout","time":"2020-08-18T11:17:57.7279826Z"}
{"log":"Copying dependencies\n","stream":"stdout","time":"2020-08-18T11:17:59.6057778Z"}
{"log":"Copying ReportBuilder\n","stream":"stdout","time":"2020-08-18T11:17:59.7937867Z"}
{"log":"Importing PowerShell Modules\n","stream":"stdout","time":"2020-08-18T11:17:59.9513539Z"}
{"log":"Determining Database Collation from c:\\dl\\sandbox\\16.4.14693.15645\\be\\BusinessCentral-BE.bak\n","stream":"stdout","time":"2020-08-18T11:18:00.0941758Z"}
{"log":"Restoring CRONUS Demo Database\n","stream":"stdout","time":"2020-08-18T11:18:02.527573Z"}
{"log":"Exporting Application to CRONUS\n","stream":"stdout","time":"2020-08-18T11:18:07.1360469Z"}
{"log":"Removing Application from tenant\n","stream":"stdout","time":"2020-08-18T11:19:48.5323783Z"}
{"log":"Modifying Business Central Service Tier Config File for Docker\n","stream":"stdout","time":"2020-08-18T11:19:54.1923233Z"}
{"log":"Creating Business Central Service Tier\n","stream":"stdout","time":"2020-08-18T11:19:54.2373224Z"}
{"log":"Installing SIP crypto provider: 'C:\\Windows\\System32\\NavSip.dll'\n","stream":"stdout","time":"2020-08-18T11:19:54.349487Z"}
{"log":"Starting Business Central Service Tier\n","stream":"stdout","time":"2020-08-18T11:19:54.628808Z"}
{"log":"Importing CRONUS license file\n","stream":"stdout","time":"2020-08-18T11:20:09.2700281Z"}
{"log":"Copying Database on localhost\\SQLEXPRESS from tenant to default\n","stream":"stdout","time":"2020-08-18T11:20:10.1185331Z"}
{"log":"Taking database tenant offline\n","stream":"stdout","time":"2020-08-18T11:20:10.2154117Z"}
{"log":"Copying database files\n","stream":"stdout","time":"2020-08-18T11:20:10.8481528Z"}
{"log":"Attaching files as new Database default\n","stream":"stdout","time":"2020-08-18T11:20:12.6138085Z"}
{"log":"Putting database tenant back online\n","stream":"stdout","time":"2020-08-18T11:20:13.9323154Z"}
{"log":"Mounting tenant database\n","stream":"stdout","time":"2020-08-18T11:20:14.0993328Z"}
{"log":"Mounting Database for default on server localhost\\SQLEXPRESS\n","stream":"stdout","time":"2020-08-18T11:20:14.1073311Z"}
{"log":"Sync'ing Tenant\n","stream":"stdout","time":"2020-08-18T11:22:21.8228354Z"}
{"log":"Tenant is Operational\n","stream":"stdout","time":"2020-08-18T11:22:23.9115977Z"}
{"log":"Stopping Business Central Service Tier\n","stream":"stdout","time":"2020-08-18T11:22:23.9115977Z"}
{"log":"Copying Web Client Files\n","stream":"stdout","time":"2020-08-18T11:22:24.3067913Z"}
{"log":"Copying Client Files\n","stream":"stdout","time":"2020-08-18T11:22:24.3067913Z"}
{"log":"Copying ModernDev Files\n","stream":"stdout","time":"2020-08-18T11:22:24.3067913Z"}
{"log":"Copying additional files\n","stream":"stdout","time":"2020-08-18T11:22:24.3067913Z"}
{"log":"Copying ConfigurationPackages\n","stream":"stdout","time":"2020-08-18T11:22:24.3077891Z"}
{"log":"Copying Test Assemblies\n","stream":"stdout","time":"2020-08-18T11:22:24.3077891Z"}
{"log":"Copying Extensions\n","stream":"stdout","time":"2020-08-18T11:22:24.3077891Z"}
{"log":"Copying Applications\n","stream":"stdout","time":"2020-08-18T11:22:24.3088503Z"}
{"log":"Copying Applications.BE\n","stream":"stdout","time":"2020-08-18T11:22:24.3088503Z"}
{"log":"Installation took 297 seconds\n","stream":"stdout","time":"2020-08-18T11:22:24.3157908Z"}
{"log":"Installation complete\n","stream":"stdout","time":"2020-08-18T11:22:24.3157908Z"}
{"log":"Initializing...\n","stream":"stdout","time":"2020-08-18T11:22:24.3542352Z"}
{"log":"Starting Container\n","stream":"stdout","time":"2020-08-18T11:22:25.4900485Z"}
{"log":"Hostname is Master\n","stream":"stdout","time":"2020-08-18T11:22:25.4940472Z"}
{"log":"PublicDnsName is Master\n","stream":"stdout","time":"2020-08-18T11:22:25.4940472Z"}
{"log":"WARNING: DNS resolution not working from within the container.\n","stream":"stdout","time":"2020-08-18T11:22:26.0830951Z"}
{"log":"Using Windows Authentication\n","stream":"stdout","time":"2020-08-18T11:22:26.6832606Z"}
{"log":"Modifying Service Tier Config File with Instance Specific Settings\n","stream":"stdout","time":"2020-08-18T11:22:26.7752656Z"}
{"log":"Starting Service Tier\n","stream":"stdout","time":"2020-08-18T11:22:27.9032605Z"}
{"log":"Registering event sources\n","stream":"stdout","time":"2020-08-18T11:22:37.1792857Z"}
{"log":"Creating DotNetCore Web Server Instance\n","stream":"stdout","time":"2020-08-18T11:22:37.2302876Z"}
{"log":"Access to the path 'fr-CA' is denied.\n","stream":"stdout","time":"2020-08-18T11:22:56.3179206Z"}
{"log":"at New-NavWebSite, C:\\Program Files\\Microsoft Dynamics NAV\\160\\Web Client\\Modules\\NAVWebClientManagement\\NAVWebClientManagement.psm1: line 566\r\n","stream":"stdout","time":"2020-08-18T11:22:56.3199185Z"}
{"log":"at New-NAVWebServerInstance, C:\\Program Files\\Microsoft Dynamics NAV\\160\\Web Client\\Modules\\NAVWebClientManagement\\NAVWebClientManagement.psm1: line 501\r\n","stream":"stdout","time":"2020-08-18T11:22:56.3199185Z"}
{"log":"at \u003cScriptBlock\u003e, C:\\Run\\SetupWebClient.ps1: line 26\r\n","stream":"stdout","time":"2020-08-18T11:22:56.3199185Z"}
{"log":"at \u003cScriptBlock\u003e, C:\\Run\\navstart.ps1: line 157\r\n","stream":"stdout","time":"2020-08-18T11:22:56.3199185Z"}
{"log":"at \u003cScriptBlock\u003e, C:\\Run\\start.ps1: line 338\r\n","stream":"stdout","time":"2020-08-18T11:22:56.3199185Z"}
{"log":"at \u003cScriptBlock\u003e, \u003cNo file\u003e: line 1\n","stream":"stdout","time":"2020-08-18T11:22:56.3199185Z"}
{"log":". : The term 'c:\\Run\\MainLoop.ps1' is not recognized as the name of a cmdlet, \r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"function, script file, or operable program. Check the spelling of the name, or \r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"if a path was included, verify that the path is correct and try again.\r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"At C:\\Run\\start.ps1:361 char:7\r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"+     . (Get-MyFilePath \"MainLoop.ps1\")\r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"    + CategoryInfo          : ObjectNotFound: (c:\\Run\\MainLoop.ps1:String) [], \r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"    ParentContainsErrorRecordException\r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":"    + FullyQualifiedErrorId : CommandNotFoundException\r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}
{"log":" \r\n","stream":"stderr","time":"2020-08-18T11:22:56.3862631Z"}



------

with -isolation hyperv  to containercreation without BC Image


Creating container Master from image mcr.microsoft.com/dynamicsnav:10.0.14393.3808-generic
77e7356e49dd6559ae70451900068a600c40ef703048e268013972451a83b648
DockerDo : docker.exe: Error response from daemon: CreateComputeSystem 77e7356e49dd6559ae70451900068a600c40ef703048e268013972451a83b648: No hypervisor is present on this system.
[Event Detail: Cannot start Hyper-V Container '77e7356e49dd6559ae70451900068a600c40ef703048e268013972451a83b648' since the hypervisor is not running in the host. Provider: 17103e3f-3c6e-4677-bb17-3b267eb5be57 E
ventID: 12001]
(extra info: {"SystemType":"Container","Name":"77e7356e49dd6559ae70451900068a600c40ef703048e268013972451a83b648","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windo
wsfilter\\77e7356e49dd6559ae70451900068a600c40ef703048e268013972451a83b648","Layers":[{"ID":"016b593a-28f4-511e-8f5f-fb6f968470e2","Path":"C:\\ProgramData\\docker\\windowsfilter\\e720298755f3fe59f6bd210e5c70af4
cec657c35261bfce0c6b6913e775289cd"},{"ID":"d7c0c2f6-57fd-5f40-8a57-f984228fb705","Path":"C:\\ProgramData\\docker\\windowsfilter\\a3c319e051e4579990c3fd5ea65ff7b6aae2d72d2945ec5a781fa33246edb3ab"},{"ID":"fdc3449
4-5798-5d13-8d05-ac98008c7e46","Path":"C:\\ProgramData\\docker\\windowsfilter\\2def0363c080a6d80c71a8846c5a034f5e3439e4db75d4a58e8bd6f922ce3b8b"},{"ID":"a19dcae7-1216-5502-9da8-d61d431978ee","Path":"C:\\Program
Data\\docker\\windowsfilter\\9a3b0cfff61f7339b63ff1287af944cd7f15c6dd62614447e808f675f9c91e79"},{"ID":"dab8abc1-0e08-50c5-97f5-20623a9cfb27","Path":"C:\\ProgramData\\docker\\windowsfilter\\2d6717c2f4359ec185099
be8de82f532f9f96d9850cf46072b65c343bff3b8f8"},{"ID":"5cbc1db3-177e-5cb0-a523-21da9d0461a1","Path":"C:\\ProgramData\\docker\\windowsfilter\\c00eb4a56e6e4f4f1a4ae25196fc5d556c4b6f7291fb4131a480969d2a523bab"},{"ID
":"4cb520f0-e3db-5d2b-b156-11760d0ccc4f","Path":"C:\\ProgramData\\docker\\windowsfilter\\1ae31b0bab06dac820465774ee75d78bc6eb4d2f47bd7b6f535899f07b7047dc"},{"ID":"dcfc17d1-910b-5e07-a5b3-7744c2dde171","Path":"C
:\\ProgramData\\docker\\windowsfilter\\8a1f46054ea37b52c459ddb0b3539bd9969e04221efecdb1c203451f102d5902"},{"ID":"b977a62d-d100-55a7-bcfc-a3bd38fc335d","Path":"C:\\ProgramData\\docker\\windowsfilter\\8c2c2c5ab73
85aafb7ed1d9633b52d37f287451651868dd8e5bb441978710b3e"},{"ID":"62c057fb-50cf-5057-9249-884eb3ab471b","Path":"C:\\ProgramData\\docker\\windowsfilter\\e80935d69bcfd0a7bf5906474d117f01e53b08e0c691b5469bd55f3fd37f6
ebb"},{"ID":"93719cc7-e7ef-5ef2-97db-270bbadd34ab","Path":"C:\\ProgramData\\docker\\windowsfilter\\2753c7611c7b066acfd22489493f5c93b4f011f86c6747ecc4b5f23dcb2c476f"},{"ID":"112f2233-875c-5a3a-b1dc-731340f6d6f5"
,"Path":"C:\\ProgramData\\docker\\windowsfilter\\a6fd9b4c36501b885d6935fad1fd38693d77cb66e181cf88f76c2623d62922ab"},{"ID":"af1e2435-2845-54f5-ad01-201cf30f36ea","Path":"C:\\ProgramData\\docker\\windowsfilter\\2
d0a2543791439ff9665c369c8d8ee0813075db80d14e33d296d3def83c1574a"},{"ID":"5f104553-2e31-5f8c-a360-ee37b8f72ae1","Path":"C:\\ProgramData\\docker\\windowsfilter\\d005707cf6c967c3ee360e77c15b6224b23960538ca270dd803
1dc85a4d22196"},{"ID":"76ab0d6c-0507-5251-9e38-450020725e06","Path":"C:\\ProgramData\\docker\\windowsfilter\\ef2ac01084aabd09ae0e8683b6ee14b191f81ec07cf997a253ef79750f4c8002"},{"ID":"1fb1c691-08a5-5163-afb8-3d3
265b4e6e9","Path":"C:\\ProgramData\\docker\\windowsfilter\\a3e2dd642c1623570424cb4da138d92d0a92e48e2e52065ce7aea54b5ebfe333"},{"ID":"56c0b548-c9bd-546b-80c0-ec076db10575","Path":"C:\\ProgramData\\docker\\window
sfilter\\cf716f99372d873e37098b11f1fffc46c469218a27d41d15778304fe114d6ea4"},{"ID":"19d66994-9599-59d7-a1fc-f86484f95725","Path":"C:\\ProgramData\\docker\\windowsfilter\\19807d421d55c124971b3b878d3d4896935e4e929
ccc386258a3fe5ceedc5bac"},{"ID":"7ae563e5-9079-57e0-a83b-6d2009a3724b","Path":"C:\\ProgramData\\docker\\windowsfilter\\f7704e18e565303e14cc2fda776989e5d8d28490b8f674a1caa5a3219095dadf"},{"ID":"dd76ba09-bf66-57f
4-95e1-e8a4dc0fd2bb","Path":"C:\\ProgramData\\docker\\windowsfilter\\852efe60c04d7ee14a67b35335c44eaa0d9e7d01b21914951fc3099f18c06bee"},{"ID":"2e0e27ea-25ea-5693-934a-e97cb842e998","Path":"C:\\ProgramData\\dock
er\\windowsfilter\\11efb8fb0cc4b23174c4e76bfdc78834034eef3e925ea71a71040506b97696cf"},{"ID":"43520bf6-9d94-5380-b8b7-afa8f8e2fd55","Path":"C:\\ProgramData\\docker\\windowsfilter\\6c7de13a6af27750ea9a304b365b049
758e50fc7bcd1b342b33a006c8a53924d"}],"MemoryMaximumInMB":4096,"HostName":"GeneralMaster","MappedDirectories":[{"HostPath":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,
"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\bcartifacts.cache","ContainerPath":"c:\\dl","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"Ho
stPath":"c:\\programdata\\bccontainerhelper","ContainerPath":"c:\\programdata\\bccontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\b
ccontainerhelper\\extensions\\generalmaster\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"HvRuntime":{"ImagePath":"C:\\
ProgramData\\docker\\windowsfilter\\11efb8fb0cc4b23174c4e76bfdc78834034eef3e925ea71a71040506b97696cf\\UtilityVM"}}).
ExitCode: 125
Commandline: docker run --volume c:\bcartifacts.cache:c:\dl --label nav= --env isBcSandbox=Y --label version=16.4.14693.15645 --label platform=16.0.14648.15622 --label country=BE --env artifactUrl=https://bcart
ifacts.azureedge.net/sandbox/16.4.14693.15645/be --env multitenant=Y --env licenseFile="c:\run\my\license.flf" --name GeneralMaster --hostname GeneralMaster --env auth=Windows --env username="b" 
--env ExitOnError=N --env locale=nl-BE --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume "C:\ProgramData\BcContainerHelper\E
xtensions\GeneralMaster\my:C:\Run\my" --isolation hyperv --restart unless-stopped --memory 4G --env enableApiServices=Y --env useSSL=N --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePasswo
rd=X= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.c
om/dynamicsnav:10.0.14393.3808-generic
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\ContainerHandling\New-NavContainer.ps1:1593 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
And you have enough disk space on the machine?
I have just tried to build that exact image (with that generic) - and it works fine here.

**Comment by SirBETE** [comment]
1.43GB/149GB free, so doubt it ... :( 

Although I don't have any room I can create.

![image](https://user-images.githubusercontent.com/34303738/90510093-a634b600-e15a-11ea-8b9f-226050a67642.png)
I need those other 4 images.

![image](https://user-images.githubusercontent.com/34303738/90510291-00357b80-e15b-11ea-9d49-f27354dc6524.png)

In C:\ProgramData\docker\windowsfilter are some folders marked with "-removing" but still there.
So perhaps if I can delete those.

dynamicsnav:10.0.14393.3808-generic is also taking "unneeded" space ... :s

**Comment by freddydk** [comment]
You should never manually remove files in WindowsFilter.
You can try with Flush-Containerhelpercache.
and you can remove unused images - the generic image is basically the only one you need.

**Comment by SirBETE** [comment]
How else can I delete 50GB (used to be so much) of unneeded imageparts that won't go away ... :(
managed to remove it all, but somehow it came back.
Guess my server is broken :'( 

I need those other images for my other projects ...
I need to upgrade the BC16.3 sandbox projects to the BC16.4 , but rather don't do that until I got my new containers.
Just to be sure.
Or do you mean I can also recreate all those other images+containers, based on the generic one?

Flush-Containerhelpercache didn't help.

**Comment by freddydk** [comment]
With artifacts we don't use images anymore - everything can be rebuilt (unless you have something in a container which you need to keep - which I do not recommend)

This tool: https://freddysblog.com/2018/12/11/clean-up-after-yourself-docker-your-mom-isnt-here/

should be able to remove all docker images - and then they can re-download / re-build

**Comment by SirBETE** [comment]
Hmmn, ok will try that tool and recreate whatever I need with artifacts.

Thank you for your time, brain and assistance!
