### ISSUE TITLE
Get-NavContainerIpAddress cannot return multiple addresses

### ISSUE THREAD

**Issue by ewaldventer** [Microsoft/navcontainerhelper#123]
When multiple interfaces are attached to the container, it currently returns:
`
Get-NavContainerIpAddress : Cannot convert 'System.Object[]' to the type 'System.String'
`

Maybe a parameter could be added to specify for which interface it must return the IP address or return all in addresses in an array?

**Comment by freddydk** [comment]
If you could share with me why and how you create a container with multiple interfaces, that would save me some time:-)
Thanks

**Comment by ewaldventer** [comment]
Yes, I think I might be going long way round here. So please correct me if I'm wrong.

If there is an easier way to manage/access multiple containers running on a single host by assigned an name from a separate host, other than described below, please let me know. Even if you can just point me to the correct reading material, it would be appreciated.

This is all on a local machine  (NOT domain attached):
Created container with navcontainerhelper on a Windows Server 2016 VM (domain attached)
* also, will be creating multiple containers on this host. I know that, as on Azure, you can use the host name to access container, but how do you access multiple containers on same host?

Dev environment is a Windows 10 VM  (domain attached).
They're connected through an internal vSwitch.

Created transparent docker network with:
`
docker network create -d transparent -o com.docker.network.windowsshim.interface="vInternal" InternalNet
`

Able to now access container from connected machines.
New IP is assigned to container every time it restarts.
Idea is to edit Hosts file every time on startup by using combination of Get-NavContainers and Get-NAVContainerIP.

Can write my own version of Get-NavContainerIP using following:


```
$inspect = docker inspect $containerName | ConvertFrom-Json
$networkObj = $inspect.NetworkSettings.Networks
$networknames = ($networkObj | get-member -MemberType NoteProperty | select Name).Name
$array = @()

$networknames | ForEach-Object -process {
    $array += ($networkObj | Select-Object -ExpandProperty $_).IPAddress
}

```

Which brings me to another problem (will try and solve myself) - can't obtain DHCP assigned IP through docker inspect.

**Comment by freddydk** [comment]
By design - no change will be made
