### ISSUE TITLE
Idea - return info-object in New-BcImage

### ISSUE THREAD

**Issue by waldo1001** [microsoft/navcontainerhelper#1230]
Would it be an idea for "New-BcImage" to return an object with as much info as at all possible?  Like:
- Platform / BC version
- ImageName
- HostOS
- ...

**Comment by freddydk** [comment]
Maybe just return the image name - then docker inspect can give you the rest if you need it?
(to avoid spending time on docker inspect every time)

**Comment by waldo1001** [comment]
That works as well :)

**Comment by freddydk** [comment]
That already happens in BcContainerHelper:

```
$imageName = New-BCImage -artifactUrl (Get-BCArtifactUrl -country us)
$imageName

returns:
myimage:sandbox-16.4.14693.15680-us

today
```
