### ISSUE TITLE
Show windows permission error only when docker is installed

### ISSUE THREAD

**Issue by mitrov** [microsoft/navcontainerhelper#1231]
**Describe the issue**
When you run "Import-Module bccontainerhelper" on a machine where docker is not installed you get this error:

![image](https://user-images.githubusercontent.com/8106202/90654968-46fda100-e241-11ea-9968-c446622992fb.png)

**Additional context**
In my case I use the bccontainerhelper just for looking up bcartifacts locally and run a powershell script on a remote computer where docker is installed and the container is created.

Suggestion: 
The error should only show up in case you actually have docker.exe installed locally.
If docker.exe is missing it should be a warning.

**Comment by freddydk** [comment]
Will consider to change this into a warning instead

**Comment by freddydk** [comment]
I thought that the containerhelper module wouldn't load and you couldn't use it.
I can see that it does load and is useable - but it gives you an error during startup that docker is not installed.
This is by design.
If you run containerhelper as administrator, I don't make those checks.
