### ISSUE TITLE
Publish-BcContainerApp fails with "Copy-Item : Could not find a part of the path"

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/navcontainerhelper#1232]
**Describe the issue**
When publishing an app, the above error is displayed.

**Scripts used to create container and cause the issue**
```
Publish-BcContainerApp -appFile  $latestLib.FullName -skipVerification -containerName $containerName
```

**Full output of scripts**
```
Copy-Item : Could not find a part of the path 'C:\ProgramData\BcContainerHelper\Extensions\navserver\file.app'.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\AppHandling\Publish-NavContainerApp.ps1:103 char:17
+                 Copy-Item -Path $appFile -Destination $sharedAppFile
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand
```

**Additional context**
The folder navserver didn't exist. Wasn't created in the process and thus this fails. I manually created it to resolve this.

**Comment by freddydk** [comment]
What context is this happening in?
Publish-BcContainerApp is used extensively all over - could it be that $containerName is empty?

**Comment by mjmatthiesen** [comment]
Context is that I have a running instance called navserver, then I issue the command with all those params filled in.
At some point, within Publish-NavContainerApp.ps1, it wants to copy the app.
![image](https://user-images.githubusercontent.com/16603906/90684108-e06a8a00-e224-11ea-93d4-367261116876.png)
The issue is that sharedAppFile wants to move it to a folder that doesn't exist and that errors out Copy-Item, namely the service instance subfolder (navserver in my case)
C:\ProgramData\BcContainerHelper\Extensions\navserver\

I hope that makes sense? Afaik, you just need to add the force param so it will create the folder when it doesn't exist.

**Comment by freddydk** [comment]
When you create a container using new-bccontainer - it creates that folder.
If you had a container created by NavContainerHelper - and shifted to BcContainerHelper without recreating the container, then that is the reason.
BcContainerHelper and NavContainerHelper is using different base folders,.
