### ISSUE TITLE
SetupAzureAdApp failing during setup of http://aka.ms/getbcext

### ISSUE THREAD

**Issue by dhvr** [microsoft/navcontainerhelper#1234]
I am trying to create a VM using http://aka.ms/getbcext
Artifact URL: bcartifacts/onprem//nz/latest
Using AAD authentication
NavContainerHelper is version 0.7.0.25
Docker Client Version is 19.03.11
Docker Server Version is 19.03.11
Version: 16.4.14693.15445-nz
Platform: 16.0.14648.15420
Generic Tag: 0.1.0.16

A few weeks ago,when I first tried this, it worked fine.

Lately, it always fails in line 376 of c:\DEMO\SetupNavContainer.ps1
        $parameters = @{ 
            "name" = "SetupAzureAdApp"
            "value" = "$PowerBiAdAppId,$PowerBiAdAppKeyValue"
        }
        **Invoke-NavContainerApi -containerName $containerName -tenant "default" -credential $credential -APIPublisher "Microsoft" -APIGroup "Setup" -APIVersion "beta" -CompanyId $companyId -Method "POST" -Query "aadApps" -body $parameters | Out-Null**

My current workaround is to
-comment out line 376 in SetupNavContainer.ps1
-run SetupNavContainer.ps1 again
-run Setup Azure Active Directory in Assisted Setup in BC and enter the values from c:\DEMO\settings.ps1.

This is the error:
Invoke GET on https://172.25.170.52:7048/BC/api/beta/companies?$filter=name%20eq%20%27CRONUS%20New%20Zealand%20Ltd.%27&tenant=default
Invoke POST on https://172.25.170.52:7048/BC/api/Microsoft/Setup/beta/companies(632464d5-d9db-ea11-bb40-001dd8b76a32)/aadApps?tenant=default
Invoke-RestMethod : {"error":{"code":"Unknown","message":"Function ID 1924145256 was called. The object with ID 6300 does not have a member with that ID.  
CorrelationId:  0717b299-297b-4915-975c-c5d858bc0380."}}
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.25\Api\Invoke-NavContainerApi.ps1:154 char:5
     Invoke-RestMethod -Method $Method -uri "$url" -Headers $headers @ ...
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
     FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

Probably an issue in the latest NZ BC version, so not sure, if this is the right place to raise this issue.

**Comment by dhvr** [comment]
Just confirming that SetupNavContainer.ps1 succeeds on 
artifactUrl=https://bcartifacts.azureedge.net/onprem/16.4.14693.15090/nz
but fails on 
artifactUrl=https://bcartifacts.azureedge.net/onprem/16.4.14693.15445/nz

**Comment by dhvr** [comment]
Also fails on
https://bcinsider.azureedge.net/sandbox/17.0.15839.0/nz

**Comment by freddydk** [comment]
I have a repro and I know what went wrong, trying to find out the best way to solve this

**Comment by dhvr** [comment]
Great! Thanks for looking into this.

**Comment by freddydk** [comment]
If you replace this line
```
        if (([System.Version]$navVersion).Major -ge 15) {
```
in SetupNavContainer.ps1 with these lines:
```
        if (([System.Version]$navVersion) -ge ([System.Version]"16.4.14693.15445")) {
            Download-File -sourceUrl "http://aka.ms/Microsoft_AzureAdAppSetup_16.4.app" -destinationFile $appfile
        }
        elseif (([System.Version]$navVersion).Major -ge 15) {
```

Then it should grab a newer version of the app, which is compatible with the breaking change in the table.
and re-run.

This will be part of a checkin today to nav-arm-templates, which also shifts to use BcContainerHelper instead of NavContainerHelper.

**Comment by freddydk** [comment]
This is fixed in the ARM templates now.

**Comment by dhvr** [comment]
Hi Freddy
Excellent, thank you!
I have created a VM using http://aka.ms/getbcext and everything ran smoothly.
The only thing I noticed, is that the NavContainerHelper shortcut on the Desktop should have the following target:
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noexit "& { Write-**BC**ContainerHelperWelcomeText }"

Cheers
Detlef

**Comment by freddydk** [comment]
Thanks, will fix that right away.
