### ISSUE TITLE
Creating a new BCContainer for  BC16.5 docker image

### ISSUE THREAD

**Issue by Nagaraju17** [microsoft/navcontainerhelper#1235]
**Describe the issue**
 I have created new BCcontainer for BC16.4 version based on BCconatiner helper and it is created successfully.
After that i tried to create one more new BContainer for BC16.5 version but am facing below issue(Am using BCcontainerhelper version 1.0.3)

**Scripts used to create container and cause the issue**
```
New-BCContainer -containerName BC165 -accept_eula -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -artifactUrl (Get-BCArtifactUrl -storageAccount "bcinsider" -type Sandbox -select Latest -country nl -version 16.5 -sasToken "") -includeAL -includeTestLibrariesOnly -includeTestToolkit -licenseFile "C:\TEMP\BC16_03072020.flf" –updateHosts -additionalParameters @('--cpu-count 4') -memoryLimit 10G -isolation hyperv -multitenant:$false
```

**Full output of scripts**
BcContainerHelper is version 1.0.3
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.1016-generic
Downloading application artifact /sandbox/16.5.15695.0/nl
Downloading C:\Users\nagarajuk\AppData\Local\Temp\90fea4cb-492b-4494-ae3c-e6e7710a3827.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/16.5.15695.0/platform
Downloading C:\Users\nagarajuk\AppData\Local\Temp\097978a3-cd2b-4cff-9747-377b7b5a5d41.zip
Retrying download...
Downloading C:\Users\nagarajuk\AppData\Local\Temp\097978a3-cd2b-4cff-9747-377b7b5a5d41.zip
Download-File : Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\Misc\Download-Artifacts.ps1:173 char:29
+ ...             Download-File -sourceUrl $platformUrl -destinationFile $p ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by freddydk** [comment]
I have removed the sas token from your request.

**Please do not add a token to a public issues list, which you have received on collaborate under NDA!**

If you use get-bcartifacturl and try that URL in a browser, you should get the artifact.
If not, then you probably have a copy/paste error in the sastoken or some other typo.

**Comment by bvbeek** [comment]
Get-BCArtifactUrl is broken at this moment I think, I don't get an URL back

**Comment by freddydk** [comment]
As stated in an email a moment ago - country needs to be lower case - Get-BcArtifactUrl works fine!

**Comment by bvbeek** [comment]
happy with lowercase uppercase
