### ISSUE TITLE
Downloading Url Rewrite fails in version 1.0.3

### ISSUE THREAD

**Issue by ThomasSig75** [microsoft/navcontainerhelper#1236]
Downloading Url Rewrite fails in version 1.0.3

Script and output:
$containerName = 'BC14-Demo'
$Localization = 'dk' 
$bcVersion = '14.8' 
$licenseFile = "c:\C2IT Repositories\C2IT-BC14.flf"

$credential = Get-Credential -Message 'Using NAVUserPassword authentication. Please enter credentials for this container only.'
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type OnPrem -version $bcVersion -country $Localization -select Latest
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -dns '8.8.8.8' `
    -updateHosts `
    -includeCSide
BcContainerHelper is version 1.0.3
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.1016-generic
Creating Container BC14-Demo
Version: 14.8.38658.0-dk
Style: onprem
Multitenant: No
Platform: 14.0.38650.0
Generic Tag: 0.1.0.15
Container OS Version: 10.0.18363.1016 (1909)
Host OS Version: 10.0.18363.1016 (1909)
Using process isolation
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file c:\C2IT Repositories\C2IT-BC14.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\BC14-Demo\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC14-Demo from image mcr.microsoft.com/dynamicsnav:10.0.18363.1016-generic
e49087d1aa38aba6c7cf615fd4676a4bab512d10133ed98bb8c171c96f33c28b
Waiting for container BC14-Demo to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.8.38658.0/dk
Using installer from C:\Run\130
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing Business Central
Downloading Url Rewrite
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
at InstallPrerequisite, C:\Run\HelperFunctions.ps1: line 579
at <ScriptBlock>, C:\Run\navinstall.ps1: line 30
at <ScriptBlock>, C:\Run\start.ps1: line 282
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.8.38658.0/dk
Using installer from C:\Run\130
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing Business Central
**Downloading Url Rewrite
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."**
at InstallPrerequisite, C:\Run\HelperFunctions.ps1: line 579
at <ScriptBlock>, C:\Run\navinstall.ps1: line 30
at <ScriptBlock>, C:\Run\start.ps1: line 282
at <ScriptBlock>, <No file>: line 1
Initialization of container BC14-Demo failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...C14-Demo failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC14-Demo failed

**Comment by freddydk** [comment]
Looks like you have an old version of the generic image - add -alwayspull or use

docker pull mcr.microsoft.com/dynamicsnav:10.0.18363.1016-generic

**Comment by ThomasSig75** [comment]
Of course - thanks it worked :-)
