### ISSUE TITLE
New-BCContainer and New-NavContainer build fails with -shortcuts Desktop

### ISSUE THREAD

**Issue by davmac1** [microsoft/navcontainerhelper#1240]
I am creating a docker vm with BC14 - if I change shortcuts from None to Desktop, it fails every time.
I am creating an upgrade path which is why I need C/AL with BC14 so I can use the new extension upgrade procedures.
(How do I bring up the C/Side dev client without shortcuts?)

```
New-BCContainer @parameters `
                -accept_eula `
                -containerName $ContainerName `
                -artifactUrl $artifactURL `
                -auth NAVUserPassword `
                -Credential $credential `
                -updateHosts `
                -assignPremiumPlan `
                -**shortcuts None** `
                -licenseFile $ContainerLicFile `
                -EnableTaskSchedule:$false `
                -memoryLimit 8G `
                -includeAL `
                -alwaysPull `
                -includeCSIDE `
                -isolation hyperv

NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro Build 19041
Docker Client Version is 19.03.12
Docker Server Version is
...
```
![DockerFailureError](https://user-images.githubusercontent.com/15961672/90992431-50567880-e575-11ea-9d6d-75b5cc4cf0dd.JPG)
**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?
![DockerFailureError](https://user-images.githubusercontent.com/15961672/90992443-62381b80-e575-11ea-8420-f89792c9cf39.JPG)
Using license file C:\Docker\dockercontainer-master\dockercontainer-master\.\4829960.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=False
Files in C:\ProgramData\NavContainerHelper\Extensions\V14Base\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container V14Base from image mcr.microsoft.com/dynamicsnav:10.0.19041.450-generic
9674d7f89a2878bc105e4daf032cd861c2163b1ca053a2e71d7dd4a6ed569308
Docker : Error response from daemon: container 9674d7f89a2878bc105e4daf032cd861c2163b1ca053a2e71d7dd4a6ed569308: driver 
"windowsfilter" failed to remove root filesystem: failed to detach VHD: The device is not ready.: rename 
C:\ProgramData\Docker\windowsfilter\9674d7f89a2878bc105e4daf032cd861c2163b1ca053a2e71d7dd4a6ed569308 
C:\ProgramData\Docker\windowsfilter\9674d7f89a2878bc105e4daf032cd861c2163b1ca053a2e71d7dd4a6ed569308-removing: Access is denied.
At C:\Users\dmachanick\Documents\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\HelperFunctions.ps1:124 char:17
+                 Docker rm $out -f
+                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...cess is denied.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by freddydk** [comment]
The error you are seeing is a docker problem. You probably have to reset your docker to factory defaults (which removes all containers and removes all images) and then start from scratch.
On how to access C/SIDE without shortcuts - I would create a container with shortcuts and see the path of the shortcuts - then you can see which program to launch. (I cannot remember the exact path)

**Comment by davmac1** [comment]
yes - if shortcuts are set to be created, it gets the error.
It is a corporate controlled desktop.
Running Symantec endpoint protection

**Comment by davmac1** [comment]
I have been able to execute finsql by navigating to the path externally

**Comment by freddydk** [comment]
and you are running PowerShell elevated (as administrator)?
have you tried the other options for shortcuts (e.g. startmenu)?

**Comment by davmac1** [comment]
yes - running as administrator
did not try startmenu yet
are there any additional options for shortcuts?

**Comment by freddydk** [comment]
when you press space after writing -shortcuts you will see the options.

**Comment by davmac1** [comment]
running it now - thanks for the tip - I will have to get used to the space feature

**Comment by davmac1** [comment]
Startmenu worked - maybe it was a permission issue with the desktop.
I have noticed every file I download is blocked and I have to unblock it.
Thanks.
