### ISSUE TITLE
file access error

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/navcontainerhelper#1244]
Build server has 5 build agents.

Two are building using the same artifact.
One has the following error.

The process cannot access the file 'C:\ProgramData\NavContainerHelper\Extensions\onprem-Applications-16.4.14693.15859-IS\Microsoft_Tests-TestLibraries_16.4.14693.15859.runtime.app' because it is being used by another process.

**Comment by freddydk** [comment]
That error has probably always been there.
If you use -doNotUseRuntimePackages, then this error shouldn't appear.
I will put a mutex around this (like artifact download)

**Comment by gunnargestsson** [comment]
Perfect!

**Comment by freddydk** [comment]
Note that this fix will only be made in BcContainerHelper
