### ISSUE TITLE
Run-TestsInBCContainer CommunicationError : An error occurred while sending the request.

### ISSUE THREAD

**Issue by Pavel-Titov** [microsoft/navcontainerhelper#1248]
Does anyone else experienced the problem like I do?
The skript was running fine in the past, but now I am getting errors...
What could be a reason for that? Any suggestions?

```
PS C:\windows\system32> Run-TestsInBCContainer -containerName 'Build-KnkTests' 
                -credential $Credential 
                -extensionId $testApp.appId 
                -detailed 
                -XUnitResultFileName 'C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\my\Results.xml' 
                -debugMode;
CommunicationError : An error occurred while sending the request.
at <ScriptBlock>, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 89
at AwaitState, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 194
at OpenSession, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 172
at Initialize, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 59
at ClientContext, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 26
at New-ClientContext, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 55
ClientSession State is Uninitialized (Wait time 10 seconds)
at AwaitState, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 206
at OpenSession, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 172
at Initialize, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 59
at ClientContext, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 26
at New-ClientContext, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 55
at AwaitState, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 206
at OpenSession, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 172
at Initialize, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 59
at ClientContext, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\ClientContext.ps1: line 26
at New-ClientContext, C:\ProgramData\NavContainerHelper\Extensions\Build-KnkTests\PsTestTool-6\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 55
ClientSession State is Uninitialized (Wait time 10 seconds)
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\AppHandling\Run-TestsInNavContainer.ps1:415 Zeichen:17
+                 throw $_.Exception.Message
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ClientSession S...ime 10 seconds):String) [], RuntimeException
    + FullyQualifiedErrorId : ClientSession State is Uninitialized (Wait time 10 seconds)
```

**Comment by freddydk** [comment]
What changed, which made it stop working?
Was it working with an old version and suddenly not anymore? if you go back to the version, where it used to work - does it then still work?

It would be very helpful to see the script that creates the container and the full output from that in order to see version numbers and other things?

**Comment by Pavel-Titov** [comment]
no, nothing did change neither in the Pipeline-Script, nor in the TestApp...
I am attaching 2 skripts: 1) is where the Container is created and the App is build 2) where the app is being installed to container and the tests are being performed.
Thank you for your help!
[knkTests.txt](https://github.com/microsoft/navcontainerhelper/files/5130094/knkTests.txt)
[knkTests GO.txt](https://github.com/microsoft/navcontainerhelper/files/5130093/knkTests.GO.txt)

**Comment by freddydk** [comment]
Can you go back and find the output of a pipeline, which worked and submit the same two output files here?

**Comment by freddydk** [comment]
Also, try to use Get-BcContainerEventLog to download the eventlog from the container and see whether that reveals anything?

**Comment by Pavel-Titov** [comment]
OK, here is the Event Log. Here I can only see: 
Error accessing Website 
OpenSessionCompleted

and the last successfull log of the pipeline.
[Build-KnkTestsGO.zip](https://github.com/microsoft/navcontainerhelper/files/5130182/Build-KnkTestsGO.zip)
[knkTests GO - worked.txt](https://github.com/microsoft/navcontainerhelper/files/5130184/knkTests.GO.-.worked.txt)

**Comment by freddydk** [comment]
I need the container generation output from the working pipeline.
99% of the time, the problem can be spotted during container generation

**Comment by Pavel-Titov** [comment]
Here you go...
[knkTests - worked.txt](https://github.com/microsoft/navcontainerhelper/files/5130253/knkTests.-.worked.txt)

**Comment by freddydk** [comment]
I think a lot of things changed...
The working one uses docker image, the error one uses artifacts.
The error one exposes a number of ports on the host (-p 8381:80 etc.) - not sure why that or whether that can be a problem.

Could you submit the script that creates the container (both the working one and the failing one)
Remember to include all values for additionalparameters etc.

**Comment by Pavel-Titov** [comment]
yes, I just switched today the pipeline from the images to artifacts, so it could not be definently a problem. The pipeline is not working from 12th of August.
yes, we expose the ports to access the container later when the pipeline is finished. To evaluate the test results and rerun the tests again. So I am not deleting the container, but keeping it, and it will be recreated with the new Pipeline run. This was also running fine in the past...
I am not sure if I can share the script worldwide, do you think I can send it to you privately?

**Comment by freddydk** [comment]
Can you share the output from August 12th then - it is valuable to compare the latest working with the first non-working if we are to find out what went wrong.

**Comment by Pavel-Titov** [comment]
Here are the logs from the last worked pipeline and the first non-worked pipeline...
[logs_1163.zip](https://github.com/microsoft/navcontainerhelper/files/5148847/logs_1163.zip)
[logs_1176.zip](https://github.com/microsoft/navcontainerhelper/files/5148848/logs_1176.zip)
Thank you so much for your help!

**Comment by Pavel-Titov** [comment]
Hi @freddydk , do you have any idea what went wrong?

**Comment by freddydk** [comment]
I have been through the code and did find a few things, which could cause this.
Do you still experience the issue?

**Comment by Pavel-Titov** [comment]
Hi @freddydk, yes, we do. We would appreciate, if you have some ideas how to fix it...

**Comment by freddydk** [comment]
Sorry for the delay.
If I am going to investigate this one, I will need the script used to create the container, the full output of that and the full output of the failing command.
Does it fail every time - or only occasionally?

thanks

**Comment by Pavel-Titov** [comment]
Hi @freddydk, I have just send the scripts and logs to your email.

**Comment by freddydk** [comment]
Did the switch to BcContainerHelper fix the issue?
