### ISSUE TITLE
WIndows 10 20H2

### ISSUE THREAD

**Issue by FrankAuwers** [microsoft/navcontainerhelper#1250]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Unable to find matching generic image for your host OS. You must pull and specify baseImage manually.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\ContainerHandling\New-NavImage.ps1:90 char:13
+             throw "Unable to find matching generic image for your hos ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to find ...Image manually.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to find matching generic image for your host OS. You must pull and specify baseImage 
    manually.
**Scripts used to create container and cause the issue**
```
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'us' -select 'Latest'
$licenseFile = 'c:\data\license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'scaptify' `
    -licenseFile $licenseFile `
    -dns '8.8.8.8' `
    -usessl -installCertificateOnHost `
    -memoryLimit 8G `
    -updateHosts
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.3
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - Unknown/Insider build
Docker Client Version is 18.09.4
Docker Server Version is 19.03.12
ArtifactUrl and ImageName specified
Fetching all docker images
Image scaptify:sandbox-16.4.14693.15903-us-mt doesn't exist
Building multitenant image scaptify:sandbox-16.4.14693.15903-us-mt based on https://bcartifacts.azureedge.net/sandbox/16.4.
14693.15903/us
Unable to find matching generic image for your host OS. You must pull and specify baseImage manually.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.3\ContainerHandling\New-NavImage.ps1:90 char:13
+             throw "Unable to find matching generic image for your hos ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unable to find ...Image manually.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unable to find matching generic image for your host OS. You must pull and specify baseImage 
    manually.
...
```

**Additional context**
- does it happen all the time? Yes
- did it use to work? Before my my Windows was updated to 20H2 it worked fine

**Comment by freddydk** [comment]
What does winver return?

**Comment by FrankAuwers** [comment]
[cid:image001.png@01D67C4C.7C0920A0]


Frank Auwers
Frank.Auwers@scapta.com
+32 477 498 527
Scapta
Corda Campus Kempische Steenweg 293 bus 38, 3500 Hasselt
Phone: +32 11 600 600
info@scapta.com
www.scapta.com
Scapta neemt een aantal uitzonderlijke maatregelen om de verspreiding van het coronavirus in te dijken.
This email may contain confidential information and/or
copyright material. This email is intended for the use of the addressee only.
Any unauthorized use may be unlawful. If you receive this mail by mistake,
please advise the sender immediately by using the reply facility in your email
software. Please don't print this e-mail unless you really need to.

**Comment by freddydk** [comment]
I cannot see that

**Comment by FrankAuwers** [comment]
Windows 10
Microsoft Windows
Version 20H2 (OS Build 19042.450)


Frank Auwers
Frank.Auwers@scapta.com
+32 477 498 527
Scapta
Corda Campus Kempische Steenweg 293 bus 38, 3500 Hasselt
Phone: +32 11 600 600
info@scapta.com
www.scapta.com
Scapta neemt een aantal uitzonderlijke maatregelen om de verspreiding van het coronavirus in te dijken.
This email may contain confidential information and/or
copyright material. This email is intended for the use of the addressee only.
Any unauthorized use may be unlawful. If you receive this mail by mistake,
please advise the sender immediately by using the reply facility in your email
software. Please don't print this e-mail unless you really need to.

**Comment by FrankAuwers** [comment]
Edition  Windows 10 Pro
Version 20H2
Installed on         ‎17/‎04/‎2020
OS build               19042.450
Experience         Windows Feature Experience Pack 120.2212.31.0


Frank Auwers
Frank.Auwers@scapta.com
+32 477 498 527
Scapta
Corda Campus Kempische Steenweg 293 bus 38, 3500 Hasselt
Phone: +32 11 600 600
info@scapta.com
www.scapta.com
Scapta neemt een aantal uitzonderlijke maatregelen om de verspreiding van het coronavirus in te dijken.
This email may contain confidential information and/or
copyright material. This email is intended for the use of the addressee only.
Any unauthorized use may be unlawful. If you receive this mail by mistake,
please advise the sender immediately by using the reply facility in your email
software. Please don't print this e-mail unless you really need to.

**Comment by freddydk** [comment]
When using New-BcImage (or New-BcContainer with -imageName) - it needs a matching OS Build.
At this time, there isn't a matching build for your version of Windows.

You can either avoid -imagename - or you can add -usegenericimage (Get-BestGenericImageName) to new-bccontainer.
Then you will get the best matching OS version and force hyperv isolation.

**Comment by freddydk** [comment]
btw - you are running a very old docker client version and a new docker server version - not sure how you have managed that.

**Comment by FrankAuwers** [comment]
I also don’t know how. I’m not a docker expert. I have just installed the docker desktop and do an update several times.


Frank Auwers
Frank.Auwers@scapta.com
+32 477 498 527
Scapta
Corda Campus Kempische Steenweg 293 bus 38, 3500 Hasselt
Phone: +32 11 600 600
info@scapta.com
www.scapta.com
Scapta neemt een aantal uitzonderlijke maatregelen om de verspreiding van het coronavirus in te dijken.
This email may contain confidential information and/or
copyright material. This email is intended for the use of the addressee only.
Any unauthorized use may be unlawful. If you receive this mail by mistake,
please advise the sender immediately by using the reply facility in your email
software. Please don't print this e-mail unless you really need to.

**Comment by freddydk** [comment]
Please note that when replying to a github issue by email - you include your entire email signature in every reply with phone numbers and more. You can edit these and remove them on github,

**Comment by freddydk** [comment]
Assuming that you made this work.
