### ISSUE TITLE
Import Font override seams to replace the Default Font for Business Central

### ISSUE THREAD

**Issue by megel** [microsoft/navcontainerhelper#1251]
When I create a new container with:

`New-BCContainer bcserver -imageName mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019 -accept_eula -auth UserPassword -updateHosts`

I can run a Report like "Customer Top 10 List":
![2020-08-27_08-26-32](https://user-images.githubusercontent.com/15800069/91399931-220bbe00-e83f-11ea-8eb5-86229fe87e69.png)

Then I get as result a correct layouted report:
![2020-08-27_08-18-28](https://user-images.githubusercontent.com/15800069/91399973-3354ca80-e83f-11ea-8424-0c90f28dbe36.png)

When I add a BarCode Font 3to9 (e.g. from https://fonts2u.com/free-3-of-9-regular.font) **AND restart the NST** with:
`Add-FontsToBCContainer -containerName bcserver -path .\fre3of9x.ttf`

Then looks the "Customer Top 10 List" like:
![2020-08-27_08-21-52](https://user-images.githubusercontent.com/15800069/91400213-90508080-e83f-11ea-8032-5a2b9d589526.png)

Is it possible, when the `Add-FontsToBCContainer` replace the default font for Business Central?

**Comment by freddydk** [comment]
I think the default font for Business Central isn't included in the image and somehow Windows thinks that the above font matches better.
Maybe try to add all fonts by specifying c:\windows\fonts
If you use the latest bccontainerhelper - it is much faster than earlier.

**Comment by megel** [comment]
@freddydk, you mean, to copy the fonts into 'c:\windows\fonts' is enough? You don't have to register the fonts like you do in Add-FontsToBCContainer?

**Comment by freddydk** [comment]
no, use add-fontstobccontainer -path c:\windows\fonts

then it installs all your fonts

**Comment by megel** [comment]
But I only want to add an additional font to the container - not all my fonts. Or does it mean I have to include the BC default fonts as well?

**Comment by freddydk** [comment]
I guess so - I don't know - different containers have different fonts.
Adding all fonts only takes 5-10 seconds with the new version (and they are included in the image when using -imageName and -addfontsfrompath to new-bccontainer).

**Comment by megel** [comment]
Yes, adding additional fonts from Windows (SegoUI, ...) helps to solve the issue.

**Comment by freddydk** [comment]
The idea is that you create a folder with all the fonts you need in your containers - and specify that folder instead of installing fonts individually - or yes, grab all fonts on the host:-)
