### ISSUE TITLE
Misleading error message on Compile-AppInBCContainer: (404) Not Found.

### ISSUE THREAD

**Issue by NKarolak** [microsoft/navcontainerhelper#1259]
**Describe the issue**
Our pipeline is using navcontainerhelper 0.7.0.26, as confirmed by the logs.
When (unintentionally) deploying an app on bcinsider SecondToLastMajor (= currently 16.6.15966.0-DE)
that is dependant on BC 17, Compile-AppInBCContainer returns the following error message:

```
Downloading symbols: Microsoft_System_16.0.15930.0.app
Url : http://OurIP:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.15855.0&tenant=default
##[error]Compile-AppInBCContainer : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an 
##[error]error: (404) Not Found."

##[error]At E:\BuildAgent\_work\_temp\46d0e53a-0083-430d-8d6a-43d331a5c237.ps1:31 char:10

##[error]+   $app = Compile-AppInBCContainer -containerName $ContainerName -cred ...

##[error]+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

##[error]    + CategoryInfo          : NotSpecified: (:) [Compile-AppInNavContainer], MethodInvocationException

##[error]    + FullyQualifiedErrorId : WebException,Compile-AppInNavContainer

##[error] 

##[error]PowerShell exited with code '1'.
```

Is there a chance to make the error message better descriptive?
I first thought, it's again an issue with the images or the navcontainerhelper version, but apparently it's only an app compatibility issue.

**Comment by freddydk** [comment]
it is hard - the url asks for symbols for version 17.0.15855.0 and gets a 404 from the server.
If I should do anything, I should issue suggestions based on the error code.

**Comment by NKarolak** [comment]
I see. 
Or, do you have access within Compile-AppInBCContainer to both versions nunbers (current 16.x artifacts vs versionText=17.0.15855.0) , so you could compare them yourself and throw an error message yourself before actually targeting the server?

**Comment by freddydk** [comment]
Yes, but then I would have to look at which apps are part of system - it could be that you had a dependency to myapp 21.0 in yourapp 16.0 using platform 15.0 - that's why I just try to download the symbols you ask for.
Not sure I want to go there.

**Comment by NKarolak** [comment]
OK, then just keep it as it is :-)
