### ISSUE TITLE
Export-BcContainerDatabasesAsBacpac - Exception "The remote name could not be resolved: 'download.microsoft.com'"

### ISSUE THREAD

**Issue by unnur** [microsoft/navcontainerhelper#1260]
Hi Freddy,

We're getting this exception when using the Export-BcContainerDatabasesAsBacpac command. 

PS C:\WINDOWS\system32> Export-BcContainerDatabasesAsBacpac -containerName $containerName -sqlCredential $credential -tenant default -diagnostics 
Downloading Dac Framework 18.2
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'download.microsoft.com'"
at InstallPrerequisite, <No file>: line 20
at Install-DACFx, <No file>: line 30
at <ScriptBlock>, <No file>: line 230
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'download.microsoft.com'"
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.4\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [InstallPrerequisite], MethodInvocationException
    + FullyQualifiedErrorId : WebException,InstallPrerequisite
    + PSComputerName        : 8e636bd906f5c0c58b3f89ec9f53d46d2f435767d85dd5ee30218578ae1c4a3c
 
Using bccontainerhelper v. 1.0.4 now, but also tried with navcontainerhelper 0.7.0.25 and 0.7.0.26.

**Comment by freddydk** [comment]
If you look at the output during container creation, it probably tells you that WARNING: DNS resolution doesn't work inside the container. if you add -dns 8.8.8.8 to the container when creating it, it will use googles public DNS server (if your network allows it).
You can also use PSEdit to edit the hosts file and insert the IP address of microsoft download in that one.

**Comment by unnur** [comment]
Oh, missed that one. Adding the dns switch solved it. Thank you :)
