### ISSUE TITLE
Can't install BcContainerHelper

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/navcontainerhelper#1261]
Not sure what to make of this:
![image](https://user-images.githubusercontent.com/23434319/91748130-4e437980-eb74-11ea-993b-d3cdc71e1a24.png)
Are there any new prerequisites?

**Comment by mitrov** [comment]
What is the output of Get-PSRepository ?

**Comment by richardrobberse** [comment]
@TheDenSter Looks like this is your issue: https://dev.to/darksmile92/powershell-disabled-support-for-tls-1-0-for-the-gallery-update-module-and-install-module-broken-1oii

TLS 1.0 is not supported anymore.

**Comment by freddydk** [comment]
Yep, same as this https://github.com/microsoft/navcontainerhelper/issues/954

**Comment by freddydk** [comment]
Assuming you made this work.

**Comment by TheDenSter** [comment]
I didn't. I tried the TLS thing but that did not fix it. Not sure if that was the problem or not, but a VM that has been working for years stopped working from one day to the next. I ended up just creating a new VM and that worked. Should have done that from the start anyway, it might actually be my go-to approach from here on out :)
