### ISSUE TITLE
NavInvalidCredentialException

### ISSUE THREAD

**Issue by olivierchristiaens** [microsoft/navcontainerhelper#1262]
I'm recreating a AzureContainer for bc17 insider - using BcContainerHelper version 1.0.4 and this script:
This used this script multiple times before last week without any problems.

$sasToken = "*****"
$Bc17InsiderUrl = Get-BCArtifactUrl -country be -storageAccount bcinsider -sasToken $sasToken -select Latest
$EnvironmentVariable = @{ACCEPT_EULA='Y';USESSL='N';ArtifactUrl=$Bc17InsiderUrl}
$Image = 'mcr.microsoft.com/dynamicsnav:10.0.17763.973-generic'

New-AzureRmContainerGroup -ResourceGroupName $ResourceGroupName -Location $Location -Name $ContainerName `
 -Image $Image -OsType Windows -EnvironmentVariable $EnvironmentVariable `
 -Cpu 2 -MemoryInGB 8 -DnsNameLabel $ContainerName -IpAddressType Public -Port 80,443,7048,7049,8080
while ((Get-AzureRmContainerGroup -ResourceGroupName $ResourceGroupName -Name $ContainerName).State -eq 'Pending')
{
    (Get-AzureRmContainerGroup -ResourceGroupName $ResourceGroupName -Name $ContainerName).ProvisioningState; Start-Sleep -Seconds 60;
}
(Get-AzureRmContainerGroup -ResourceGroupName $ResourceGroupName -Name $ContainerName).Fqdn
Get-AzureRmContainerInstanceLog -ResourceGroupName $ResourceGroupName -ContainerGroupName $ContainerName | Out-File "c:\temp\$ContainerName.txt"
#-----------------------------

The startup script is infite looping - see output below with 2 warning and 1 error repeating continuously.
It looks like the User (with NavUserPwd) was not created or added...
error:
Message (NavInvalidCredentialException): RootException: NavInvalidCredentialException
You do not have access to {0}. Verify that you have been set up as a valid user in {0}.

complete output:
Adding WK-CAAS-5BC7C82 to hosts file
Using artifactUrl https://bcinsider.azureedge.net/sandbox/17.0.16010.0/be
Downloading application artifact /sandbox/17.0.16010.0/be
Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\6a96904f-54b0-47fa-8a44-1ec73e93f840.zip
Unpacking application artifact
Downloading platform artifact /sandbox/17.0.16010.0/platform
Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\4b5667aa-fd65-4679-a135-7e17b9af94b6.zip
Unpacking platform artifact
Downloading Prerequisite Components
Downloading c:\dl\sandbox\17.0.16010.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\dl\sandbox\17.0.16010.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\dl\sandbox\17.0.16010.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.0.16010.0\be\BusinessCentral-BE.bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.BE
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 195 seconds
Installation complete
Initializing...
Starting Container
Hostname is wk-caas-5bc7c82735d746efbe0ccba7e469556b-5ff34d2d3c4983da2b3d3c
PublicDnsName is wk-caas-5bc7c82735d746efbe0ccba7e469556b-5ff34d2d3c4983da2b3d3c
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 16B95B00A9E70E5138E3D36CDE44C58CEAE96877
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 10.244.202.81
Container Hostname  : wk-caas-5bc7c82735d746efbe0ccba7e469556b-5ff34d2d3c4983da2b3d3c
Container Dns Name  : wk-caas-5bc7c82735d746efbe0ccba7e469556b-5ff34d2d3c4983da2b3d3c
Web Client          : http://wk-caas-5bc7c82735d746efbe0ccba7e469556b-5ff34d2d3c4983da2b3d3c/BC/
Admin Username      : admin
Admin Password      : Keve6510
Dev. Server         : http://wk-caas-5bc7c82735d746efbe0ccba7e469556b-5ff34d2d3c4983da2b3d3c
Dev. ServerInstance : BC

Files:
http://wk-caas-5bc7c82735d746efbe0ccba7e469556b-5ff34d2d3c4983da2b3d3c:8080/ALLanguage.vsix

WARNING: You are running a container which is 78 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 45 seconds
Ready for connections!
Starting EventLog Monitor
Monitoring EventSources from EventLog[Application]:
- MicrosoftDynamicsNAVClientClientService
- MicrosoftDynamicsNAVClientWebClient
- MicrosoftDynamicsNavServer$BC
- MSSQL$SQLEXPRESS

TimeGenerated : 08/31/2020 15:21:44
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Category: CacheSynchronization
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 9b27c903-e8be-47a0-8d52-241aae156965
EventTime: 08/31/2020 15:21:44
Message Last read record is missing, we need to clear the cache newestReadTimestamp 450024 lastreadTimestamp 0
ProcessId: 1384
Tag: 00001U4
ThreadId: 28
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 08/31/2020 15:22:37
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Category: Security
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: dd1afa07-6201-459a-bef8-da60823c293a
ServerSessionUniqueId: e6eb38f8-d472-4ab9-9b1d-8cf9730d9415
ServerActivityId: f986a2ec-58c9-4443-a30a-c880ee63c944
EventTime: 08/31/2020 15:22:37
Message A security token was received that is associated with an unknown or disabled user account in Azure Active Directory.
ProcessId: 1384
Tag: 00009QY
ThreadId: 36
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 08/31/2020 15:22:37
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Tenant: default
Environment Name: 
Environment Type: Sandbox
Session type: Background
Session ID: 17
This license is not compatible with this version of Business Central.

TimeGenerated : 08/31/2020 15:22:37
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Error
Message : 
Server instance: BC
Category: TaskScheduling
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: dd1afa07-6201-459a-bef8-da60823c293a
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 9b27c903-e8be-47a0-8d52-241aae156965
EventTime: 08/31/2020 15:22:37
Message (NavInvalidCredentialException): RootException: NavInvalidCredentialException
You do not have access to {0}. Verify that you have been set up as a valid user in {0}.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavSession.Open(Boolean useUserPersonalization, Byte[] licenseToUse, Boolean allowAppsDisabledMode)
   at Microsoft.Dynamics.Nav.Runtime.TaskRunnerCodeUnit.TaskSpecificInternalRun()
   at Microsoft.Dynamics.Nav.Runtime.TaskRunner.InternalRun()
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.TaskRunner.InternalRun()
   at Microsoft.Dynamics.Nav.Runtime.NavTaskFactory.<>c__DisplayClass1_0.<RunTask>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

ProcessId: 1384
Tag: 000003P
ThreadId: 36
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 08/31/2020 15:22:37
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Category: Security
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 96ca0128-fcd3-41c1-a321-70b6225ef2b2
ServerSessionUniqueId: e6eb38f8-d472-4ab9-9b1d-8cf9730d9415
ServerActivityId: f986a2ec-58c9-4443-a30a-c880ee63c944
EventTime: 08/31/2020 15:22:37
Message A security token was received that is associated with an unknown or disabled user account in Azure Active Directory.
ProcessId: 1384
Tag: 00009QY
ThreadId: 31
CounterInformation: 
CustomParameters: {
}
GatewayCorrelationId: 

TimeGenerated : 08/31/2020 15:22:37
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Warning
Message : 
Server instance: BC
Tenant: default
Environment Name: 
Environment Type: Sandbox
Session type: Background
Session ID: 19
This license is not compatible with this version of Business Central.

TimeGenerated : 08/31/2020 15:22:37
EventSource: MicrosoftDynamicsNavServer$BC
EntryType : Error
Message : 
Server instance: BC
Category: TaskScheduling
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 96ca0128-fcd3-41c1-a321-70b6225ef2b2
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 9b27c903-e8be-47a0-8d52-241aae156965
EventTime: 08/31/2020 15:22:37
Message (NavInvalidCredentialException): RootException: NavInvalidCredentialException
You do not have access to {0}. Verify that you have been set up as a valid user in {0}.
ExceptionStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.NavSession.Open(Boolean useUserPersonalization, Byte[] licenseToUse, Boolean allowAppsDisabledMode)
   at Microsoft.Dynamics.Nav.Runtime.TaskRunnerCodeUnit.TaskSpecificInternalRun()
   at Microsoft.Dynamics.Nav.Runtime.TaskRunner.InternalRun()
CallerStackTrace:
   at Microsoft.Dynamics.Nav.Runtime.TaskRunner.InternalRun()
   at Microsoft.Dynamics.Nav.Runtime.NavTaskFactory.<>c__DisplayClass1_0.<RunTask>b__0()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by freddydk** [comment]
It looks like everything works fine, except for the taskscheduler.

I don't think anything changed in that - the task scheduler can be disabled by specifying CustomNavSettings=EnableTaskScheduler=false as an environment variable.

btw - why are you hardcoding the windows version 17763.973 (Windows 2019 server January 2020 update)?
You can get the latest generic from windows 2019 by using Get-BestGenericImageName -hostOsVersion 10.0.17763

**Comment by olivierchristiaens** [comment]
Correct, instance is working fine, but I don't know why we get this error since last week.
Anyway, I will disable Task Scheduler if we don't need it.
And, correct, better not to hardcode the image for future use !
