### ISSUE TITLE
Generate Symbol in other language than English

### ISSUE THREAD

**Issue by Steven-Bale** [microsoft/navcontainerhelper#1264]
Hello,

I have an issue regarding Generate Symbols because of fields named with french accent in CAL (i know it is dirty, the code guidelines mentioned that should be in English, but this is ISV developed by another partner), in VS Code, accent are not well generated for example é is �.

I test with nav2018 local installation to compile from the cside client dev (with generatesymbolreference = yes and language UI in french) objects with fields named with accent => it works.

So the question is : is the language mananged in a container when generate symbols ?

Thanks,
Steven

**Comment by freddydk** [comment]
It depends on whether you are running 2016 containers or 2019 or later containers and whether you are running hyperv or process isolation.

**Comment by Steven-Bale** [comment]
ok thank you.
here is the command used :
New-BCContainer `
    -accept_outdated `
    -accept_eula `
    -containerName $containerName `
    -imageName $imageName `
    -updateHosts `
    -auth UserPassword `
    -Credential $credential `
    -databaseServer 'host.containerhelper.internal' `
    -databaseInstance '' `
    -databaseName $DatabaseName `
    -databaseCredential $dbcredentials `
    -dumpEventLog `
    -includecside `
    -isolation hyperv `
    -enableSymbolLoading `
    -licensefile "Somewhere"

**Comment by freddydk** [comment]
The only thing I can see here is that it is Hyperv and that you haven't switched to artifacts.
I think you need the 2016 version of the containers if running hyperv.

**Comment by Steven-Bale** [comment]
ok and the symbol should work witj accent as in local ?

**Comment by freddydk** [comment]
I think so.
I did a lot of work to ensure these things were working back in the days.
In the meantime I only work with AL and BC - and everything is unicode.
Is hyperv - it needs to be 2016 - else process isolation should work.
If you switch to artifacts - you always get the same windows as the host (hence process) unless you are running an insider or ancient windows build on the host.

**Comment by Steven-Bale** [comment]
ok thanks i switched to 2016.
Unsing artifacts are mandatory for this version ? or still use an image ?

**Comment by freddydk** [comment]
Not mandatory - the images are still there, but they are no longer being updated,
New versions are no longer published as images.
All old versions are also as artifacts.

**Comment by Steven-Bale** [comment]
ok.
I tried to use this image microsoft/dynamics-nav:2018-cu6-fr-ltsc2016 to have a 2016 version on my PC (Windows 10) with the same script.

I got this error message :
NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Professionnel - 1903
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Using image microsoft/dynamics-nav:2018-cu6-fr-ltsc2016
Removing test from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\test
Creating Container test
Version: 11.0.22292.0-fr
Style: onprem
Generic Tag: 0.0.9.2
Container OS Version: 10.0.14393.2791 (ltsc2016)
Host OS Version: 10.0.18362.1016 (1903)
Using locale fr-FR
Using hyperv isolation
Using license file D:\OneDrive - SBSI Consulting\Professionnel\Licences\6809377.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container test from image microsoft/dynamics-nav:2018-cu6-fr-ltsc2016
8703bc453fd052acd4799f67c0c484418b777f09dc88609b7dba7cfa9f0c2fde
DockerDo : docker.exe: Error response from daemon: container 8703bc453fd052acd4799f67c0c484418b777f09dc88609b7dba7cfa9f0c2fde encountered an error during hcsshim::System::Start: failure in a Windows system call: 
The virtual machine or container exited unexpectedly. (0xc0370106).
ExitCode: 125
Commandline: docker run --env licenseFile="c:\run\my\license.flf" --name test --hostname test --env auth=NavUserPassword --env username="admin" --env ExitOnError=N --env locale=fr-FR --env 
databaseServer="host.containerhelper.internal" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\test\my:C:\Run\my" --isolation hyperv --restart unless-stopped --memory 4G --env databaseName="test" --env enableSymbolLoading=Y --env useSSL=N --volume 
"C:\ProgramData\NavContainerHelper\Extensions\test\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AFcAVgBCADUAU
wBVAHAASgBTAFQAeQBpAEcARABPAEYAbABwAGQAZwBWAFEAPQA9AHwAZAAwADUAMAA0ADQANgBkAGYAZQA5ADYAMQA1ADYANQAxADkANwBiAGMAOAA1ADMAYwA5AGEAYwBmADQAOQA1AGIAYgBmAGEAMwBhADEANQAyADIAOABmAGUANABkADUANQAyAGUAMwA4ADQAZgBlAGQAZgBiA
DUAMgAyAGMAZAA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env databaseUsername=sa --env databaseSecurePassword=76492d1116743f0423413b16050a5345MgB8AFIAQgBpAFMAcwBhAGEATgBuAHEAdAAyA
DcAQQBUAHgAZQBqAHcAcgBrAHcAPQA9AHwAYQA4AGQAOQAzAGIAMQBkAGIAYgA3ADEAZgBlADQANwBkADAAMwAzAGQAZQAzAGMANgBkAGYAOAAzAGEAMgBmADQAMgA0AGMAOAAyADgAYgA1ADUAOAAwADcAZgBlADIAMAA0ADIAYwA0AGIAYQBiAGYANQBkAGEANgA5ADEAZAA= 
--env encryptionSecurePassword=76492d1116743f0423413b16050a5345MgB8AFIAQgBpAFMAcwBhAGEATgBuAHEAdAAyADcAQQBUAHgAZQBqAHcAcgBrAHcAPQA9AHwAYQA4AGQAOQAzAGIAMQBkAGIAYgA3ADEAZgBlADQANwBkADAAMwAzAGQAZQAzAGMANgBkAGYAOAAzA
GEAMgBmADQAMgA0AGMAOAAyADgAYgA1ADUAOAAwADcAZgBlADIAMAA0ADIAYwA0AGIAYQBiAGYANQBkAGEANgA5ADEAZAA= --env accept_eula=Y --env accept_outdated=Y --detach microsoft/dynamics-nav:2018-cu6-fr-ltsc2016
Au caractère C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.0\ContainerHandling\New-NavContainer.ps1:1244 : 19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
These errors are typically because of some issue with docker and it might be better to reset to factory defaults and retry.
Furthermore - you are running a very old Windows 10 version - and you containerhelper is also not the newest - that doesn't cause the issue, I just saw that.

**Comment by Steven-Bale** [comment]
Thanks it works.
