### ISSUE TITLE
New-NavContainerTenant.ps1: Add parameter to set [AllowAppDatabaseWrite].

### ISSUE THREAD

**Issue by ekeukens** [microsoft/navcontainerhelper#1265]
In New-NavContainerTenant.ps1 the mount of a tenant is executed. Would it be possible to add a parameter to be able to control [AllowAppDatabaseWite]. Because I don't think there's a cmdlet to change this value afterwards (not with Set-NavTenant as well).

Or can this be solved by adding a argument list, to be able to change more standard options?

**Comment by freddydk** [comment]
The default tenant is mounted with AllowAppDatabaseWrite.
Thinking that that is a very uncommon scenario in multitenancy, I thought that was enough:-)
Why would you want allowappdatabaseWrite?

**Comment by ekeukens** [comment]
We are in the embedapp program.

We would like to simulate a SaaS environment in a docker container in azure. So we assume [AllowAppDatabaseWrite] must be set to false, to simulate SaaS tenants the best way. After the default tenant is created by the container cmdlets we'll add extra tenants. 
Trying to test if [permission sets] of type [system] can't be modified from the tenant in this case. If I set [AllowAppDatabase] to false I think it still is possible to do this. So we assume this is disabled by some other trigger in SaaS.
Same goes for [webservice]. We would like to avoid users to update them (like it was SaaS).

**Comment by freddydk** [comment]
I think both permissions and webservices has a tenant version of the app database to enable people to have tenant specific web services: 
![image](https://user-images.githubusercontent.com/10775043/93185381-9c907500-f73d-11ea-8e34-54e454c12b93.png)
New tenants are indeed with AllowAppDatabaseWrite set to false and I won't change this.
