### ISSUE TITLE
A parameter cannot be found that matches parameter name 'includePerformanceToolkit'

### ISSUE THREAD

**Issue by mitrov** [microsoft/navcontainerhelper#1267]
**Describe the issue**
Using 1.0.5-preview172
Error concerning -includePerformanceToolkit

**Scripts used to create container and cause the issue**
Set-Location $PSScriptRoot
Import-Module bccontainerhelper

$ComputerName = '********'
$Username = '*******'
$ArtifactUrl = Get-ArtifactUrl
$ContainerName = Read-Host -Prompt "ContainerName"

Invoke-Command -Verbose -ComputerName $ComputerName -Credential $Username -EnableNetworkAccess -ScriptBlock {
    
    function Install-SwSContainer {
        [CmdletBinding()]
        param (        
            [Parameter(Mandatory = $true)]
            [ValidateNotNullOrEmpty()]
            [string]$ArtifactUrl,
            [Parameter(Mandatory = $true)]
            [ValidateNotNullOrEmpty()]
            [string]$ContainerName,
            [Parameter(Mandatory = $true)]
            [ValidateNotNullOrEmpty()]
            [ValidateSet('Windows', 'NavUserPassword', 'AAD')]
            [string]$Auth,
            [Parameter(Mandatory = $true)]
            [ValidateNotNullOrEmpty()]
            [pscredential]$Credential,
            [pscredential]$DatabaseCredential,
            [string]$DatabaseServer,
            [string]$DatabaseInstance,
            [string]$DatabaseName
        )
        begin {
            # Sanity checks
            if ($env:computername -ne '*********')
            { Write-Error "You are running this script on the wrong computer!" }
    
            $RootPath = 'E:\CONTAINERS'
            if (-Not (Test-Path $RootPath -PathType Container))
            { Write-Error "$RootPath does not exist" }

            $LicenseFile = "E:\*******.flf"
        }
        
        process {

            $ErrorActionPreference = "Stop"
            $params = @{            
                accept_eula              = $true
                accept_outdated          = $true
                auth                     = $Auth
                containerName            = $ContainerName
                credential               = $Credential
                artifactUrl              = $ArtifactUrl
                imageName                = "$($ContainerName.ToLowerInvariant())"
                includeAL                = $true
                includeTestToolkit       = $true
                includeTestLibrariesOnly = $true
                licenseFile              = $LicenseFile
                shortcuts                = 'Desktop'
                updateHosts              = $true
                useGenericImage          = "$(Get-BestGenericImageName)-dev"
            }
            
            if ($DatabaseCredential)
            { $params['databaseCredential'] = $DatabaseCredential }
            if ($DatabaseServer) 
            { $params['databaseServer'] = $DatabaseServer }
            if ($DatabaseInstance) 
            { $params['databaseInstance'] = $DatabaseInstance }
            if ($DatabaseName)
            { $params['databaseName'] = $DatabaseName }
                                                
            $ContainerPath = Join-Path $RootPath $ContainerName        
            $ContainerSharePath = Join-Path $ContainerPath 'Share'
            $ContainerIconsPath = Join-Path $ContainerPath 'Icons'
                    
            New-Item -ItemType Directory -Force -Path $ContainerPath | Out-Null
            New-Item -ItemType Directory -Force -Path $ContainerSharePath | Out-Null
            New-Item -ItemType Directory -Force -Path $ContainerIconsPath | Out-Null

            $additionalParameters = @("-v $($ContainerSharePath):c:\Share --network=tlan")        
            $params['additionalParameters'] = $additionalParameters                                                

            New-BCContainer @params
            Write-Host "-------------------------------------------------------------------------------------------------------------"
            Backup-BCContainerDatabases -containerName $ContainerName            
            Write-Host "Use Restore-DatabasesInBCContainer -containerName $ContainerName to restore the database"
            Write-Host "-------------------------------------------------------------------------------------------------------------"
            Flush-ContainerHelperCache -cache all -keepDays 10 -Verbose
        }    
        end {
            $DesktopPath = [Environment]::GetFolderPath("Desktop")
            $FileFilter = $ContainerName + '*'
            Get-ChildItem -Path $DesktopPath -Filter $FileFilter | Move-Item -Destination $ContainerIconsPath -Force
        }
    }
    
    $Credential = New-Object pscredential 'username', (ConvertTo-SecureString -String 'password' -AsPlainText -Force)
    $ArtifactUrl = $args[0]
    $ContainerName = $args[1]
    Install-SwSContainer -ArtifactUrl $ArtifactUrl -ContainerName $ContainerName -Auth 'NavUserPassword' -Credential $Credential
} -ArgumentList @($ArtifactUrl,$ContainerName)

**Full output of scripts**
Setting bcartifactsCacheFolder = e:\bcartifacts.cache
BcContainerHelper is version 1.0.5
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
ArtifactUrl and ImageName specified
Fetching all docker images
Image azmunew:sandbox-16.4.14693.16102-ch-mt doesn't exist
Building multitenant image azmunew:sandbox-16.4.14693.16102-ch-mt based on https://bcartifacts.azureedge.net/sandbox/16.4.14693.16102/ch
A parameter cannot be found that matches parameter name 'includePerformanceToolkit'.
    + CategoryInfo          : InvalidArgument: (:) [Install-SwSContainer], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-SwSContainer
    + PSComputerName        : **********

**Comment by mitrov** [comment]
PS C:\Windows\system32> Get-BestGenericImageName
Setting bcartifactsCacheFolder = d:\bcartifacts.cache
mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
PS C:\Windows\system32>

**Comment by freddydk** [comment]
and docker inspect that one?
The generic tag

**Comment by mitrov** [comment]
Not sure what you mean. I know how to use "docker inspect containerX" .. but what do you mean with generic tag label?

**Comment by freddydk** [comment]
docker inspect mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
 search for labels

```
            "Labels": {
                "created": "202009020358",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "maintainer": "Dynamics SMB",
                "osversion": "10.0.19041.450",
                "tag": "0.1.0.21"
            },

```

**Comment by mitrov** [comment]
PS C:\Windows\system32> docker inspect mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
[]
Error: No such object: mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic
PS C:\Windows\system32>

**Comment by freddydk** [comment]
ahhh - you are using the -dev

docker inspect mcr.microsoft.com/dynamicsnav:10.0.17763.1282-generic-dev

**Comment by mitrov** [comment]
"Labels": {
                "created": "202008281422",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "maintainer": "Dynamics SMB",
                "osversion": "10.0.17763.1282",
                "tag": "0.1.0.20"
            },

**Comment by freddydk** [comment]
could you try to add -alwayspull to your new-bccontainer

**Comment by freddydk** [comment]
Two things.
The new bccontainerhelper doesn't work with 0.1.0.20 generic image - will fix that asap.
You are specifying a generic imagename with -useGenericImage  containerhelper won't pull a new if it already exists - hence you don't get 0.1.0.21 without -alwayspull

**Comment by freddydk** [comment]
Actually the bug is also that New-BcImage is missing that parameter as well - so you need to remove -imageName for this to work right now.

**Comment by mitrov** [comment]
Ok, got. I thought for some reason the -alwayspull is not needed anymore but that's obviously not the case. 
Will reintroduce the param in our scripts. Thanks!

**Comment by mitrov** [comment]
But in order to get the fastest *rebuilding* containers I need -usegenericimage in combination with the artefacts right?

**Comment by freddydk** [comment]
But note that I will publish generic images to -dev to test whether something works - so it might be broken sometimes

**Comment by mitrov** [comment]
Ok.... so summary:

- I'll remove -alwaysPull and -usegenericimage from the scripts
- I'll add  { "genericImageName": "mcr.microsoft.com/dynamicsnav:{0}-generic" } to bccontainerhelper.config.json  (no -dev)

and that should give us fast recreation of containers and has always latest image?

**Comment by freddydk** [comment]
New bccontainerhelper preview should be available in ~2 hours

**Comment by freddydk** [comment]
Shipped in https://www.powershellgallery.com/packages/BcContainerHelper/1.0.5-preview173
