### ISSUE TITLE
Unable to connect to the sql host database

### ISSUE THREAD

**Issue by ittechie** [microsoft/navcontainerhelper#1269]
I want to use my SQL2019 instance for docker databases.
Config: OS 2019 - Build 1809
SQL : 15.0.2070.41

I restored a database and have firewall turned off, also remote connections in sql are on and tcp is enable (and restarted)
Use the following script:

$containerName = 'testen'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'w1' -select 'Latest'
$databaseServer = 'host.containerhelper.internal'
$databaseInstance = 'mssqlserver'
$databaseName = 'Cronus_W1'
$databaseUsername = 'docker'
$databasePassword = 'docker'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -assignPremiumPlan `
    -updateHosts

When i enter the container i can ping the host server (host.containerhelper.internal) or ip adres
PS C:\Windows\system32> enter-bccontainer testen
Welcome to the NAV Container PowerShell prompt

[TESTEN]: PS C:\Run> ping host.containerhelper.internal

Pinging host.containerhelper.internal [172.30.128.1] with 32 bytes of data:
Reply from 172.30.128.1: bytes=32 time<1ms TTL=128
Reply from 172.30.128.1: bytes=32 time<1ms TTL=128
Reply from 172.30.128.1: bytes=32 time<1ms TTL=128
Reply from 172.30.128.1: bytes=32 time<1ms TTL=128

Ping statistics for 172.30.128.1:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

From sql management studio i can access also de instance by ip adres:

But after running script im getting error that i cant connect to the sql server.

install with host sql.ps1
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.11
Docker Server Version is 19.03.11
Removing container testen
Removing testen from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\testen
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.17763.1397-generic
Creating Container testen
Version: 16.4.14693.16178-W1
Style: sandbox
Platform: 16.0.14648.15997
Generic Tag: 0.1.0.21
Container OS Version: 10.0.17763.1397 (ltsc2019)
Host OS Version: 10.0.17763.1432 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\testen\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container testen from image mcr.microsoft.com/dynamicsnav:10.0.17763.1397-generic
a71cf0076d569537f70a579820c29d03d3a4c533de2f2b16e769f3a86f9c3374
Waiting for container testen to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/16.4.14693.16178/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Installation took 26 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.30.128.1 in container hosts file
Starting Container
Hostname is testen
PublicDnsName is testen
Using NavUserPassword Authentication
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 148
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 346
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/16.4.14693.16178/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Installation took 26 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.30.128.1 in container hosts file
Starting Container
Hostname is testen
PublicDnsName is testen
Using NavUserPassword Authentication
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 148
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 346
at <ScriptBlock>, <No file>: line 1
Initialization of container testen failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r testen failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container testen failed

Any idea what is going wrong

**Comment by freddydk** [comment]
Did you check the 6 items described here: https://freddysblog.com/2019/11/04/using-sql-server-on-the-host/

**Comment by ittechie** [comment]
Navcontainer helper was up to date,
-UpdateHosts was already used.
Extract the Database from a Container and attach -> also working
after running the next script to the container:
Initialization of container testen failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...r testen failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container testen failed
 
I will try to setup a local new machine (without domain maybe the issue is there)

**Comment by freddydk** [comment]
These 6:

1. Install SQL Server 2017 Developer edition on my laptop (my docker host)
2. Install SSMS (SQL Server Management Studio) on my laptop
3. Open SQL Server 2017 Configuration Manager and enable TCP/IP protocol for SQL Server.
4. Open SSMS, connect to localhost SQL Server, select Properties on localhost, Security and enable SQL Server and Windows Authentication mode.
5. In the Object Explorer in SSMS, expand Security and Logins. Select properties on sa and set a password (under General) and enable sa (under Status).
6. Open port 1433 for inbound traffic in the Firewall.

**Comment by freddydk** [comment]
DId you make this work?

**Comment by ittechie** [comment]
Hi

I had build a temp server on azure with sql2017.

After running the scripts it Worked!  Will try it now onprem

Thanks 

Verstuurd vanaf mijn iPhone
