### ISSUE TITLE
Shortcuts in Startmenu / Desktop

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/navcontainerhelper#127]
Maybe just a question: I run a Win Server 2016 with docker for a development team. Now when I deploy a new Container the very convenient shortcuts are generated in the user context, so nobody else sees them.

Is there a way to have the shortcuts generated for all users instead?

**Comment by freddydk** [comment]
Today this is not possible, you can only do Desktop, Startmenu or none.
I guess it would be easy to include CommonStartMenu in the enum.

**Comment by RafaelKoch** [comment]
That would be cool

**Comment by freddydk** [comment]
This will be included in the next version of navcontainerhelper.

**Comment by freddydk** [comment]
Version 0.2.9.0 has been released
