### ISSUE TITLE
Error while New-BCContainer(Download-File : Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved:)

### ISSUE THREAD

**Issue by Renee0312** [microsoft/navcontainerhelper#1270]
Hi Freddy,
     I've used the below scrip to create BC Container Version 17.
     But I've faced the error "Download-File : Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved:.........".
     Do I miss something?
     Could you please help me to check this issue?
     Thank you.
 ===============================================================================

$artifactUrl = Get-BCArtifactUrl -country tw -storageAccount bcinsider -sasToken $sasToken
New-BCContainer -accept_eula `
                -artifactUrl $artifactUrl `
                -containerName "BC17-0907-W1-AL" `
                -auth Windows `
                -credential $credential `
                -licenseFile "C:\Temp\KS_BC16wISV0715.flf" `
                -updateHosts `
                -alwaysPull
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Standard - ltsc2016
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic
10.0.14393.3750-generic: Pulling from dynamicsnav
3889bb8d808b: Already exists
375fbabb8494: Pulling fs layer
d9c806d48a44: Pulling fs layer
6bda70be0d6b: Pulling fs layer
504a31f350fa: Pulling fs layer
da09557a5897: Pulling fs layer
504a31f350fa: Waiting
da09557a5897: Waiting
cd17eb049aa6: Pulling fs layer
b62110c14133: Pulling fs layer
cd17eb049aa6: Waiting
723738a89b84: Pulling fs layer
b62110c14133: Waiting
723738a89b84: Waiting
767c3c8cc3ae: Pulling fs layer
767c3c8cc3ae: Waiting
a29255cf0d33: Pulling fs layer
8db7a2847167: Pulling fs layer
e0a5777774a8: Pulling fs layer
a29255cf0d33: Waiting
8db7a2847167: Waiting
e0a5777774a8: Waiting
152288e6d368: Pulling fs layer
e5a655eaf1cf: Pulling fs layer
4b0a35950219: Pulling fs layer
152288e6d368: Waiting
e5a655eaf1cf: Waiting
5f67178aa257: Pulling fs layer
4b0a35950219: Waiting
6fec2ea1adfb: Pulling fs layer
0cf4a01160db: Pulling fs layer
6fec2ea1adfb: Waiting
867d02107af5: Pulling fs layer
0cf4a01160db: Waiting
883ec9038d10: Pulling fs layer
867d02107af5: Waiting
57aac4d1b8da: Pulling fs layer
883ec9038d10: Waiting
29c326e5acea: Pulling fs layer
57aac4d1b8da: Waiting
acef4297322d: Pulling fs layer
29c326e5acea: Waiting
acef4297322d: Waiting
6bda70be0d6b: Verifying Checksum
6bda70be0d6b: Download complete
504a31f350fa: Verifying Checksum
504a31f350fa: Download complete
d9c806d48a44: Verifying Checksum
d9c806d48a44: Download complete
cd17eb049aa6: Verifying Checksum
cd17eb049aa6: Download complete
b62110c14133: Verifying Checksum
b62110c14133: Download complete
723738a89b84: Verifying Checksum
723738a89b84: Download complete
767c3c8cc3ae: Verifying Checksum
767c3c8cc3ae: Download complete
da09557a5897: Verifying Checksum
da09557a5897: Download complete
8db7a2847167: Verifying Checksum
8db7a2847167: Download complete
e0a5777774a8: Verifying Checksum
e0a5777774a8: Download complete
152288e6d368: Verifying Checksum
152288e6d368: Download complete
e5a655eaf1cf: Verifying Checksum
4b0a35950219: Verifying Checksum
4b0a35950219: Download complete
5f67178aa257: Verifying Checksum
5f67178aa257: Download complete
6fec2ea1adfb: Verifying Checksum
6fec2ea1adfb: Download complete
0cf4a01160db: Verifying Checksum
0cf4a01160db: Download complete
867d02107af5: Verifying Checksum
867d02107af5: Download complete
a29255cf0d33: Verifying Checksum
a29255cf0d33: Download complete
57aac4d1b8da: Downloading
57aac4d1b8da: Retrying in 5 seconds
57aac4d1b8da: Retrying in 4 seconds
57aac4d1b8da: Retrying in 3 seconds
57aac4d1b8da: Retrying in 2 seconds
57aac4d1b8da: Retrying in 1 second
883ec9038d10: Verifying Checksum
883ec9038d10: Download complete
57aac4d1b8da: Verifying Checksum
57aac4d1b8da: Download complete
29c326e5acea: Verifying Checksum
29c326e5acea: Download complete
acef4297322d: Verifying Checksum
acef4297322d: Download complete
375fbabb8494: Verifying Checksum
375fbabb8494: Download complete
375fbabb8494: Pull complete
d9c806d48a44: Pull complete
6bda70be0d6b: Pull complete
504a31f350fa: Pull complete
da09557a5897: Pull complete
cd17eb049aa6: Pull complete
b62110c14133: Pull complete
723738a89b84: Pull complete
767c3c8cc3ae: Pull complete
a29255cf0d33: Pull complete
8db7a2847167: Pull complete
e0a5777774a8: Pull complete
152288e6d368: Pull complete
e5a655eaf1cf: Pull complete
4b0a35950219: Pull complete
5f67178aa257: Pull complete
6fec2ea1adfb: Pull complete
0cf4a01160db: Pull complete
867d02107af5: Pull complete
883ec9038d10: Pull complete
57aac4d1b8da: Pull complete
29c326e5acea: Pull complete
acef4297322d: Pull complete
Digest: sha256:78af28e64bacbfc92b615544eb2b794ab1a57661fe89c5f729edfb3578820684
Status: Downloaded newer image for mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic
mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic
Using image mcr.microsoft.com/dynamicsnav:10.0.14393.3750-generic
Downloading application artifact /sandbox/17.0.16244.0/tw
Downloading C:\Users\renee_lu.KS\AppData\Local\Temp\563b5902-9666-47c6-a63e-d456f07932bd.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/17.0.16244.0/platform
Downloading C:\Users\renee_lu.KS\AppData\Local\Temp\ae8dc66f-28cd-418f-b802-794028eeebc6.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\17.0.16244.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\
OpenXMLSDKv25.msi
Download-File : Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 
'bcartifacts.azureedge.net'"
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\Misc\Download-Artifacts.ps1:206 char:45
+ ...             Download-File -sourceUrl $url -destinationFile $path -tim ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File

**Comment by freddydk** [comment]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Comment by freddydk** [comment]
I have deleted the token, but anybody subscribing to this issue list will now have the token in their email.

**Comment by Renee0312** [comment]
Hi Freddy,
    Sorry about that. ^^
    Thank you.

Renee
