### ISSUE TITLE
Error while install-module navcontainerhelper -force

### ISSUE THREAD

**Issue by Renee0312** [microsoft/navcontainerhelper#1271]
Hi Freddy,
     I have another server and it run fine (*) in the early of August. 
     * install the newest navcontainerhelper
     * New-BCContainer from bcinsider (BCArtifactUrl)

     But now, when I've tried to install the newest navcontainerhelp, I've got the error.
     I've tried to find the solution but I could not get any luck. 
      ===================================================================
      PS C:\Windows\system32> install-module navcontainerhelper -force
      WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2/'.
      PackageManagement\Install-Package : No match was found for the specified search criteria and module name
      'navcontainerhelper'. Try Get-PSRepository to see all available registered module repositories.
      At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.1\PSModule.psm1:9683 char:34
      + ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
      +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Ex
      ception
      + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by freddydk** [comment]
https://github.com/microsoft/navcontainerhelper/issues/1261

**Comment by Renee0312** [comment]
Dear Freddy,
    Thank you for the information.

Renee
