### ISSUE TITLE
Demanding pull of one version and getting another

### ISSUE THREAD

**Issue by naveksa** [microsoft/navcontainerhelper#1278]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
We are trying to pull a version 14.0 DK and what we get is version 16.3 W1

**Scripts used to create container and cause the issue**

```
install-module navcontainerhelper -force

Update-Module navcontainerhelper -Force

$accept_eula = $true
$accept_out  = $true

$containername = 'NAVEKSA14AF'

$artifactUrl = Get-BCArtifactUrl -version 14.0 -country dk

$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated: $accept_out `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -auth Windows `
                 -alwaysPull `
                 -includeAL `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -additionalParameters $additionalParameters `
                 -licenseFile 'C:\Naveksa\5692763_BC16_300620.flf'

Setup-BCContainerTestUsers -containerName $containername -password $credential.Password

```
**Full output of scripts**

NavContainerHelper is version 0.7.0.23
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Removing container NAVEKSA14AF
Removing NAVEKSA14AF from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA14AF
Fetching all docker images
Pulling image mcr.microsoft.com/businesscentral/onprem:ltsc2019
ltsc2019: Pulling from businesscentral/onprem
Using image mcr.microsoft.com/businesscentral/onprem:ltsc2019
Creating Container NAVEKSA14AF
Version: 16.3.14085.14238-W1
Style: onprem
Platform: 16.0.14073.14195
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1397 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Naveksa\5692763_BC16_300620.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA14AF\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container NAVEKSA14AF from image mcr.microsoft.com/businesscentral/onprem:ltsc2019
aae1f9242d590f5789c35dd5ba62ec4ff9455c4c36400f5492f8e8d23692aff1
Waiting for container NAVEKSA14AF to be ready
Initializing...
Setting host.containerhelper.internal to 172.19.176.1 in container hosts file
Starting Container
Hostname is NAVEKSA14AF
PublicDnsName is NAVEKSA14AF
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user vmadmin
Setting SA Password and enabling SA
Creating SUPER user
Assign Premium plan for NAVEKSA14AF\VMADMIN
Container IP Address: 172.19.191.144
Container Hostname  : NAVEKSA14AF
Container Dns Name  : NAVEKSA14AF
Web Client          : http://NAVEKSA14AF/BC/
Dev. Server         : http://NAVEKSA14AF
Dev. ServerInstance : BC
Setting NAVEKSA14AF to 172.19.191.144 in host hosts file

Files:
http://NAVEKSA14AF:8080/ALLanguage.vsix

WARNING: You are running a container which is 208 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 80 seconds
Ready for connections!
Reading CustomSettings.config from NAVEKSA14AF
Creating Desktop Shortcuts for NAVEKSA14AF
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\160\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\160\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container NAVEKSA14AF successfully created
Copy from container NAVEKSA14AF (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\NavContainerHelper\E
xtensions\NAVEKSA14AF\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA14AF\_Microsoft_System Application Test Library.app
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
App successfully published
Downloading C:\Users\vmadmin\AppData\Local\Temp\16\CreateTestUsers.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA14AF\_CreateTestUsers.app
Synchronizing CreateTestUsers on tenant default
Installing CreateTestUsers on tenant default
App successfully published
Invoke GET on http://172.19.191.144:7048/BC/api/beta/companies?$filter=name%20eq%20%27CRONUS%20International%20Ltd.%27&tenant=default
Invoke POST on http://172.19.191.144:7048/BC/api/Microsoft/Setup/beta/companies(b90f8813-44b7-ea11-bb4a-000d3a390d67)/testUsers?tenant=default
Uninstalling CreateTestUsers from tenant default
Unpublishing CreateTestUsers
App successfully unpublished
Uninstalling System Application Test Library from tenant default
Unpublishing System Application Test Library
App successfully unpublished

**Screenshots**

![image](https://user-images.githubusercontent.com/40754213/92598275-e34b1e80-f2a8-11ea-8ff9-5fe04b588f9b.png)

**Comment by freddydk** [comment]
if you run a container with empty artifact - it uses default

if you run: 
Get-BCArtifactUrl -version 14.0 -country dk

it returns blank, meaning there are no sandbox artifacts for 14.0
If you are looking for onprem - you need to add -type onprem

**Comment by naveksa** [comment]
Tried with
$artifactUrl = Get-BCArtifactUrl -version 14.0 -country dk -type OnPrem
and
$artifactUrl = Get-BCArtifactUrl -version 14.1 -country dk -type OnPrem

Both results in the following error

NavContainerHelper is version 0.7.0.23
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Removing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA14AF
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.17763.1397-generic
10.0.17763.1397-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.17763.1397-generic
Downloading application artifact /onprem/14.1.32615.0/dk
Downloading C:\Users\vmadmin\AppData\Local\Temp\16\6ab65e97-bfc5-41ce-b802-d7e99814a185.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /onprem/14.1.32615.0/platform
Downloading C:\Users\vmadmin\AppData\Local\Temp\16\140d2195-b1fb-4e2e-b6cc-cfc4aee45373.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\onprem\14.1.32615.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\onprem\14.1.32615.0\platform\Prerequisite Components\Microsoft Report Viewer 2015\ReportViewer.msi
Downloading c:\bcartifacts.cache\onprem\14.1.32615.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Download-File : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.23\Misc\Download-Artifacts.ps1:206 char:45
+ ...             Download-File -sourceUrl $url -destinationFile $path -tim ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File

**Comment by NAVspecialist** [comment]
Could it be:

**Comment by freddydk** [comment]
That error is described here: https://freddysblog.com/2020/08/18/one-of-these-days/ - which also describes how to overcome that.

**Comment by naveksa** [comment]
OK, was confused because it worked with pulling a new version 16 image
but that was apparently because there already was some part of that already installed.

Tried to replace
install-module navcontainerhelper -force
with
install-module bccontainerhelper -force

Now we got the correct version and without any errors.

Thanks.

**Comment by freddydk** [comment]
That is because bccontainerhelper uses a different cache folder.
You could probably have used Flush-ContainerHelperCache to get rid of old caches too.
