### ISSUE TITLE
Own backup - no access - super user not created

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#128]
I am using own backup to restore inside the container and even when in the NavContainerHelper.md is stated that "NAV Super user will be created", the user is not created and I am unable to login into Desktop Client nor Web client ("You do not have access..."). I am able to connect to C/Side and sync tables OK.

I have checked the users in the database and there is no new user added for the local window account.

**Comment by freddydk** [comment]
Are you using the -bakfile parameter?
Could you share the output from starting the container?

**Comment by kine** [comment]
>     New-NavContainer -accept_eula `
>                     -containerName $containerName `
>                     -imageName $imageName `
>                     -licenseFile $licenseFile `
>                     -Credential $credentials `
>                     -includeCSide `
>                     -doNotExportObjectsToText `
>                     -alwaysPull `
>                     -memoryLimit $RAM `
>                     -auth Windows `
>                     -myScripts @($bakFile) `
>                     -additionalParameters @("--env bakfile=`"c:\run\my\$bakFileName`"",'--env SqlTimeout=36000')

**Comment by freddydk** [comment]
and the output?

**Comment by kine** [comment]
> Initializing...
> Starting Container
> Hostname is NVR2018CSYDeve
> PublicDnsName is NVR2018CSYDeve
> Using Windows Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Using Database .bak file 'c:\run\my\NVR2018_CSY_Devel_20180424.3.bak'
> Modifying Service Tier Config File with Instance Specific Settings
> Starting NAV Service Tier
> Using license file 'c:\run\my\license.flf'
> Import License
> Creating DotNetCore NAV Web Server Instance
> Creating http download site
> Creating Windows user ksacek
> Setting SA Password and enabling SA
> Container IP Address: 172.21.144.168
> Container Hostname  : NVR2018CSYDeve
> Container Dns Name  : NVR2018CSYDeve
> Web Client          : http://NVR2018CSYDeve/NAV/
> Dev. Server         : http://NVR2018CSYDeve
> Dev. ServerInstance : NAV
> 
> Files:
> http://NVR2018CSYDeve:8080/al-0.12.17720.vsix
> 
> Initialization took 113 seconds
> Ready for connections!
> Initializing...

**Comment by kine** [comment]
the last initializing is from stop/start of the container... just ignore it.

**Comment by freddydk** [comment]
and docker inspect with the labels (version tags etc.)

**Comment by NAVspecialist** [comment]
Have you tried just for "fun" if you use NAVuserPassword and not Windows authentication? that also might give an idea of where the problem lies..

**Comment by kine** [comment]
> [
>     {
>         "Id": "49feafec31e431de38ec71f5d8b66dc0c1a6bce1568153f9ee5ee8833b35a470",
>         "Created": "2018-04-25T07:07:49.3776003Z",
>         "Path": "powershell",
>         "Args": [
>             "-Command",
>             "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
>             ".\\Run\\start.ps1"
>         ],
>         "State": {
>             "Status": "running",
>             "Running": true,
>             "Paused": false,
>             "Restarting": false,
>             "OOMKilled": false,
>             "Dead": false,
>             "Pid": 1924,
>             "ExitCode": 0,
>             "Error": "",
>             "StartedAt": "2018-04-25T07:28:17.5287711Z",
>             "FinishedAt": "2018-04-25T09:27:43.3545353+02:00",
>             "Health": {
>                 "Status": "healthy",
>                 "FailingStreak": 0,
>                 "Log": [
>                     {
>                         "Start": "2018-04-25T11:00:12.6968104+02:00",
>                         "End": "2018-04-25T11:00:13.0445897+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-04-25T11:00:43.127287+02:00",
>                         "End": "2018-04-25T11:00:43.5257139+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-04-25T11:01:13.5864491+02:00",
>                         "End": "2018-04-25T11:01:13.9195712+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-04-25T11:01:43.9883798+02:00",
>                         "End": "2018-04-25T11:01:44.333642+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     },
>                     {
>                         "Start": "2018-04-25T11:02:14.422422+02:00",
>                         "End": "2018-04-25T11:02:14.8156643+02:00",
>                         "ExitCode": 0,
>                         "Output": ""
>                     }
>                 ]
>             }
>         },
>         "Image": "sha256:ad537ff10ec1747eb90b5b9275bac658aa2df74e8cfa95e4798eb0cbf887c439",
>         "ResolvConfPath": "",
>         "HostnamePath": "",
>         "HostsPath": "",
>         "LogPath": "G:\\ProgramData\\docker\\containers\\49feafec31e431de38ec71f5d8b66dc0c1a6bce1568153f9ee5ee8833b35a470\\49feafec31e431de38ec71f5d8b66dc0c1a6bce1568153f9ee5ee8833b35a470-json.log",
>         "Name": "/NVR2018CSYDeve",
>         "RestartCount": 0,
>         "Driver": "windowsfilter",
>         "Platform": "windows",
>         "MountLabel": "",
>         "ProcessLabel": "",
>         "AppArmorProfile": "",
>         "ExecIDs": null,
>         "HostConfig": {
>             "Binds": [
>                 "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
>                 "C:\\ProgramData\\NavContainerHelper\\Extensions\\NVR2018CSYDeve\\my:C:\\Run\\my",
>                 "C:\\ProgramData\\NavContainerHelper\\Extensions\\NVR2018CSYDeve\\Program Files:C:\\navpfiles"
>             ],
>             "ContainerIDFile": "",
>             "LogConfig": {
>                 "Type": "json-file",
>                 "Config": {}
>             },
>             "NetworkMode": "default",
>             "PortBindings": {},
>             "RestartPolicy": {
>                 "Name": "unless-stopped",
>                 "MaximumRetryCount": 0
>             },
>             "AutoRemove": false,
>             "VolumeDriver": "",
>             "VolumesFrom": null,
>             "CapAdd": null,
>             "CapDrop": null,
>             "Dns": [],
>             "DnsOptions": [],
>             "DnsSearch": [],
>             "ExtraHosts": null,
>             "GroupAdd": null,
>             "IpcMode": "",
>             "Cgroup": "",
>             "Links": null,
>             "OomScoreAdj": 0,
>             "PidMode": "",
>             "Privileged": false,
>             "PublishAllPorts": false,
>             "ReadonlyRootfs": false,
>             "SecurityOpt": null,
>             "UTSMode": "",
>             "UsernsMode": "",
>             "ShmSize": 0,
>             "ConsoleSize": [
>                 0,
>                 0
>             ],
>             "Isolation": "hyperv",
>             "CpuShares": 0,
>             "Memory": 6442450944,
>             "NanoCpus": 0,
>             "CgroupParent": "",
>             "BlkioWeight": 0,
>             "BlkioWeightDevice": [],
>             "BlkioDeviceReadBps": null,
>             "BlkioDeviceWriteBps": null,
>             "BlkioDeviceReadIOps": null,
>             "BlkioDeviceWriteIOps": null,
>             "CpuPeriod": 0,
>             "CpuQuota": 0,
>             "CpuRealtimePeriod": 0,
>             "CpuRealtimeRuntime": 0,
>             "CpusetCpus": "",
>             "CpusetMems": "",
>             "Devices": [],
>             "DeviceCgroupRules": null,
>             "DiskQuota": 0,
>             "KernelMemory": 0,
>             "MemoryReservation": 0,
>             "MemorySwap": 0,
>             "MemorySwappiness": null,
>             "OomKillDisable": false,
>             "PidsLimit": 0,
>             "Ulimits": null,
>             "CpuCount": 0,
>             "CpuPercent": 0,
>             "IOMaximumIOps": 0,
>             "IOMaximumBandwidth": 0
>         },
>         "GraphDriver": {
>             "Data": {
>                 "dir": "G:\\ProgramData\\docker\\windowsfilter\\49feafec31e431de38ec71f5d8b66dc0c1a6bce1568153f9ee5ee8833b35a470"
>             },
>             "Name": "windowsfilter"
>         },
>         "Mounts": [
>             {
>                 "Type": "bind",
>                 "Source": "c:\\programdata\\navcontainerhelper\\extensions\\nvr2018csydeve\\program files",
>                 "Destination": "c:\\navpfiles",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": ""
>             },
>             {
>                 "Type": "bind",
>                 "Source": "c:\\programdata\\navcontainerhelper",
>                 "Destination": "c:\\programdata\\navcontainerhelper",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": ""
>             },
>             {
>                 "Type": "bind",
>                 "Source": "c:\\programdata\\navcontainerhelper\\extensions\\nvr2018csydeve\\my",
>                 "Destination": "c:\\run\\my",
>                 "Mode": "",
>                 "RW": true,
>                 "Propagation": ""
>             }
>         ],
>         "Config": {
>             "Hostname": "NVR2018CSYDeve",
>             "Domainname": "",
>             "User": "",
>             "AttachStdin": false,
>             "AttachStdout": false,
>             "AttachStderr": false,
>             "ExposedPorts": {
>                 "1433/tcp": {},
>                 "443/tcp": {},
>                 "7045/tcp": {},
>                 "7046/tcp": {},
>                 "7047/tcp": {},
>                 "7048/tcp": {},
>                 "7049/tcp": {},
>                 "80/tcp": {},
>                 "8080/tcp": {}
>             },
>             "Tty": false,
>             "OpenStdin": false,
>             "StdinOnce": false,
>             "Env": [
>                 "ExitOnError=N",
>                 "databaseInstance=",
>                 "useSSL=N",
>                 "passwordKeyFile=c:\\run\\my\\aes.key",
>                 "licenseFile=c:\\run\\my\\license.flf",
>                 "SqlTimeout=36000",
>                 "auth=Windows",
>                 "locale=cs-CZ",
>                 "removePasswordKeyFile=Y",
>                 "username=ksacek",
>                 "databaseServer=",
>                 "securePassword="xxxx",
>                 "bakfile=c:\\run\\my\\NVR2018_CSY_Devel_20180424.3.bak",
>                 "accept_eula=Y",
>                 "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/e9e59c86-ea86-4efd-98a5-6eda0e67b9c8",
>                 "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.17720.vsix",
>                 "DatabaseName=CronusCZ",
>                 "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/9b7c0199-fb2d-4dd3-bce9-55b90f04845a"
>             ],
>             "Cmd": [
>                 "powershell",
>                 "-Command",
>                 "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
>                 ".\\Run\\start.ps1"
>             ],
>             "Healthcheck": {
>                 "Test": [
>                     "CMD",
>                     "powershell",
>                     ".\\Run\\HealthCheck.ps1"
>                 ],
>                 "Interval": 30000000000,
>                 "Timeout": 10000000000
>             },
>             "ArgsEscaped": true,
>             "Image": "microsoft/dynamics-nav:2018-cu3-cz",
>             "Volumes": null,
>             "WorkingDir": "",
>             "Entrypoint": null,
>             "OnBuild": null,
>             "Labels": {
>                 "country": "cz",
>                 "created": "201803281652",
>                 "cu": "cu3",
>                 "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
>                 "legal": "http://go.microsoft.com/fwlink/?LinkId=826604",
>                 "maintainer": "Dynamics SMB",
>                 "nav": "2018",
>                 "osversion": "10.0.14393.2125",
>                 "tag": "0.0.5.5",
>                 "version": "11.0.20783.0"
>             }
>         },
>         "NetworkSettings": {
>             "Bridge": "",
>             "SandboxID": "49feafec31e431de38ec71f5d8b66dc0c1a6bce1568153f9ee5ee8833b35a470",
>             "HairpinMode": false,
>             "LinkLocalIPv6Address": "",
>             "LinkLocalIPv6PrefixLen": 0,
>             "Ports": {
>                 "1433/tcp": null,
>                 "443/tcp": null,
>                 "7045/tcp": null,
>                 "7046/tcp": null,
>                 "7047/tcp": null,
>                 "7048/tcp": null,
>                 "7049/tcp": null,
>                 "80/tcp": null,
>                 "8080/tcp": null
>             },
>             "SandboxKey": "49feafec31e431de38ec71f5d8b66dc0c1a6bce1568153f9ee5ee8833b35a470",
>             "SecondaryIPAddresses": null,
>             "SecondaryIPv6Addresses": null,
>             "EndpointID": "",
>             "Gateway": "",
>             "GlobalIPv6Address": "",
>             "GlobalIPv6PrefixLen": 0,
>             "IPAddress": "",
>             "IPPrefixLen": 0,
>             "IPv6Gateway": "",
>             "MacAddress": "",
>             "Networks": {
>                 "nat": {
>                     "IPAMConfig": null,
>                     "Links": null,
>                     "Aliases": null,
>                     "NetworkID": "67059d989dc51df1958b04063030bff62416b87def69244b8d06957ab69280bb",
>                     "EndpointID": "fd5c90b5aacd2522c13d6ee9e69df684ba0cec2a4c8e20bfbe1fb3d55c9ed61e",
>                     "Gateway": "172.21.144.1",
>                     "IPAddress": "172.21.152.32",
>                     "IPPrefixLen": 16,
>                     "IPv6Gateway": "",
>                     "GlobalIPv6Address": "",
>                     "GlobalIPv6PrefixLen": 0,
>                     "MacAddress": "00:15:5d:63:98:43",
>                     "DriverOpts": null
>                 }
>             }
>         }
>     }
> ]

**Comment by freddydk** [comment]
In navstart.ps1 you are running into this code:

```
    if ($usingLocalSQLServer) {
        . (Get-MyFilePath "SetupSqlUsers.ps1")
        . (Get-MyFilePath "SetupNavUsers.ps1")
    }

```
We know that you are running into SetupSqlUsers.ps1 (enabling SA in the log)
The code in SetupNavUsers you are running into is:

```
if ($auth -eq "Windows") {
    if ($username -ne "") {
        if (!(Get-NAVServerUser -ServerInstance NAV @tenantParam -ErrorAction Ignore | Where-Object { $_.UserName.EndsWith("\$username", [System.StringComparison]::InvariantCultureIgnoreCase) -or $_.UserName -eq $username })) {
            Write-Host "Creating SUPER user"
            New-NavServerUser -ServerInstance NAV @tenantParam -WindowsAccount $username
            New-NavServerUserPermissionSet -ServerInstance NAV @tenantParam -WindowsAccount $username -PermissionSetId SUPER
        }
    }

```
auth is winodws
username is not blank (as I can see in the log that it is creating the Windows User.
so... 
It looks like there is a user in the bak file already????
Or that Get-NAVServerUser fails????

maybe try to connect to the container and run Get-NAVServerUser -ServerInstance NAV

**Comment by kine** [comment]
Yes, there already user navertica\ksacek but this do not work, and seems like this is source of the problem.

Sent from my Windows 10 phone

________________________________

**Comment by freddydk** [comment]
Probably a different SID for the user.
You will have to remove the user before you restore - or after you start the container

**Comment by richardrobberse** [comment]
I'm not sure in what kind of context you're doing this but if you have the backup process automated, I would remove the user before creating the backup so that you don't have to adjust/override any container related scripts.

**Comment by kine** [comment]
Why the skip if the user exists with different domain? You ill create .\username and this is different…

Sent from my Windows 10 phone

________________________________

**Comment by kine** [comment]
I do not agree. The mapping is, that it will look for local account with same user login. It means it will authenticate me in this case as "NVR2018CSYDEVE\KSACEK". And this user does not exists in NAV now. I can confirm, that when I did 
` New-NAVServerUser -WindowsAccount KSACEK -ServerInstance NAV`
and
`New-NAVServerUserPermissionSet -WindowsAccount KSACEK -PermissionSetI
d SUPER -ServerInstance NAV`

User with name NVR2018CSYDEVE\KSACEK was created and all is working correctly now. It means the condition about existing same user name with any domain is incorrect.

**Comment by freddydk** [comment]
These things are different in Windows 10, Windows 2016 and whether or not you are running a domain or just Windows Users.
Feel free to override SetupNavUsers with your own version, but for now, I am not going to prioritize a fix like this, which will come with a huge risk IMO.

**Comment by NAVspecialist** [comment]
I agree with Freddy on this - An override is a bad idea. Mainly because if you later do a backup of your SQL and want to restore it back to the SQL the database came from - then you have to change the SID for the user again. 

And that was why I suggested that a NavUserPassword solution was chosen over Windows Authentication.

**Comment by kine** [comment]
What I remember, it is same for long time and I remember this from times when I was working with work groups only. But as you wish. I think that there is no risk when you create user for local account. It will be used or not. But may be you know something more than me when you were creating the scripts and you experience some problems around. May be fixing the sentence in the NavContainerHelper.md will be enough, that the user is created only when there is no user like *\username.

**Comment by kine** [comment]
@NAVspecialist it is not override. It is just same create of user like when using cronus DB. If I create backup and restore it outside, it will be same like when I am restoring the backup from outside in the container. I have our domain users there now, I will have one additional local user there. No change, no difference.

NavUserPasword is no go for me because I need to be able to run Schema Sync from C/Side in this case.

**Comment by freddydk** [comment]
I am not referring to the functionality in windows but in containers. This code was (I think) as you suggest, and something else fell apart. Very tricky to test all combinations on this, therefore you will just have to create the user after you create the container in this case.
Sorry.
I will update the doc. Thanks

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by freddydk** [comment]
Documentation is updated.
