### ISSUE TITLE
New-BcContainer - access is denied

### ISSUE THREAD

**Issue by pzentner** [microsoft/navcontainerhelper#1288]
**Description:**
When creating a new container for Version 16.0, I am getting the following error during the image creation:

DockerDo : failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer
\\?\D:\DockerData\windowsfilter\55ae460ae44e1dbe80c00f60a0234b283aea11b7406c2430249dbb1728580060: Access is denied.
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.6\ContainerHandling\New-NavImage.ps1:121 char:9
+         DockerDo -command pull -imageName $baseImage | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

This started happening a couple days ago. Since then I have reinstalled docker, moved the Docker folder to a different drive, formatted the drives, and a few other things. It doesn't matter, if it is an insider build or a normal build (tried it also with the latest insider for 17, to see, if there is a difference).

Any idea what that could be? I am pulling my hair out and the wall is already bloody from banging my head against it. Using 1.0.6-preview181

**Scripts used:**
$url = Get-BCArtifactUrl -type OnPrem -country na -version 16.0 -select Latest
New-BcContainer -accept_eula -accept_outdated -containerName test -imageName navx:16.0-na-OnPrem -artifactUrl $url -licenseFile [license] -Credential (Get-Credential) -memoryLimit 12GB -updateHosts -includeAL -enableTaskScheduler:$false -alwaysPull -useBestContainerOS -auth NavUserPassword -dns "8.8.8.8"

**Full output of scripts**

BcContainerHelper is version 1.0.6
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
ArtifactUrl and ImageName specified
Fetching all docker images
Image navx:16.0-na-OnPrem doesn't exist
Building image navx:16.0-na-OnPrem based on https://bcartifacts.azureedge.net/onprem/16.0.11240.12085/na
Building image navx:16.0-na-OnPrem based on mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
navx:16.0-na-OnPrem
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
295f12394c4f: Pulling fs layer
fbc68affb523: Pulling fs layer
54909e05a1be: Pulling fs layer
975f8c606567: Pulling fs layer
b21585eb8358: Pulling fs layer
36508056fc76: Pulling fs layer
ff80e88f1945: Pulling fs layer
0de3a359dfb1: Pulling fs layer
e8ae433a2170: Pulling fs layer
3da9157d8cf8: Pulling fs layer
975f8c606567: Waiting
e98650f27ce0: Pulling fs layer
b21585eb8358: Waiting
36508056fc76: Waiting
ff80e88f1945: Waiting
f153b24a8b70: Pulling fs layer
e8ae433a2170: Waiting
3da9157d8cf8: Waiting
0de3a359dfb1: Waiting
f3c97324096a: Pulling fs layer
f153b24a8b70: Waiting
e98650f27ce0: Waiting
f3c97324096a: Waiting
887011bce52f: Pulling fs layer
523bce31be18: Pulling fs layer
887011bce52f: Waiting
523bce31be18: Waiting
d351adf6f48d: Pulling fs layer
d351adf6f48d: Waiting
54909e05a1be: Verifying Checksum
54909e05a1be: Download complete
975f8c606567: Verifying Checksum
975f8c606567: Download complete
b21585eb8358: Verifying Checksum
b21585eb8358: Download complete
36508056fc76: Verifying Checksum
36508056fc76: Download complete
ff80e88f1945: Verifying Checksum
ff80e88f1945: Download complete
0de3a359dfb1: Verifying Checksum
0de3a359dfb1: Download complete
e8ae433a2170: Verifying Checksum
e8ae433a2170: Download complete
fbc68affb523: Verifying Checksum
fbc68affb523: Download complete
e98650f27ce0: Verifying Checksum
e98650f27ce0: Download complete
3da9157d8cf8: Verifying Checksum
3da9157d8cf8: Download complete
f3c97324096a: Verifying Checksum
f3c97324096a: Download complete
887011bce52f: Verifying Checksum
887011bce52f: Download complete
523bce31be18: Verifying Checksum
523bce31be18: Download complete
d351adf6f48d: Verifying Checksum
d351adf6f48d: Download complete
f153b24a8b70: Verifying Checksum
f153b24a8b70: Download complete
295f12394c4f: Verifying Checksum
295f12394c4f: Download complete
DockerDo : failed to register layer: re-exec error: exit status 1: output: ProcessBaseLayer
\\?\D:\DockerData\windowsfilter\8132dc62d5de1fd2f9aa412569438d75f54b682ea16bf05e6cbada1615d3f1b0: Access is denied.
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.6\ContainerHandling\New-NavImage.ps1:121 char:9
+         DockerDo -command pull -imageName $baseImage | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
What does winver.exe display?
What does docker version in a cmd prompt display?

**Comment by pzentner** [comment]
Winver: Version 2004 (OS Build 19041.508) - Windows 10

Docker version:

Client: Docker Engine - Community
 Azure integration  0.1.15
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:43:18 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:57:30 2020
  OS/Arch:          windows/amd64
  Experimental:     true

**Comment by freddydk** [comment]
I have the same windows version and the same docker version

I don't know whether this is the exact same error as you have been seeing from before reinstall etc. - but I have seen other people having problems when moving docker data to D:, so I would remove that setting - and remove the experimental setting as well.
If you still have problems,. I would disable antivirus and see

**Comment by pzentner** [comment]
Thanks Freddy! You are always a life saver ;) 

It seems to be working again after moving the data back to C (removing the setting), disabling the experimental features, and turning off Anti Virus. Now I have to try to get it back into shape so that it works with Anti Virus at least.
