### ISSUE TITLE
Question - Automatically apply configuration package (rapidstart)

### ISSUE THREAD

**Issue by borisimple** [microsoft/navcontainerhelper#1289]
I've extended New-BcContainer script a bit so it will import .rapidstart packages after a new container has been created.
I would like to Apply those packages automatically.

But those packages are available under "Pre-Defined Packages" inside Business Central (Table 2000000170), meaning that I need manually to click on every single package in order to get it imported into Table Config. Package (8623).

![Screenshot 2020-09-16 135116](https://user-images.githubusercontent.com/16119596/93333519-b73d1980-f823-11ea-9bcd-1e9bd0e18559.jpg)

After that I can apply every package by using Apply function from BC.

Is there any way to automate this? Specifically the part where I can transfer pre-defined package to Config. Package Table.

I was looking around and saw that we have the Codeunit "Config. Package Management", containing bunch of functions which could be used, but I cannot find any documentation regarding them😁

Sorry if I am asking in a wrong place 😊

**Comment by freddydk** [comment]
Maybe you can find what you need here: https://freddysblog.com/2019/09/19/using-apis-on-containers/

**Comment by borisimple** [comment]
It seems that this is exactly what I am looking for.
I will take a look.

Tnx 😉
