### ISSUE TITLE
Settings in Docker image not aligned with selected country

### ISSUE THREAD

**Issue by naveksa** [microsoft/navcontainerhelper#1291]
We download an image for BC, with country code DK.
We get the correct image setup, but the current settings are for US.
We expected the settings to follow the country-specific settings, at least Region and Time Zone.

Function we use for call:

$artifactUrl = Get-BCArtifactUrl -country dk -select Latest

New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated: $accept_out `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -auth Windows `
                 -alwaysPull `
                 -includeAL `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -additionalParameters $additionalParameters `
                 -licenseFile 'C:\Naveksa\5692763_BC16_300620.flf'

Setup-BCContainerTestUsers -containerName $containername -password $credential.Password

The version we get downloaded is correct:

![image](https://user-images.githubusercontent.com/40754213/93446801-ec07aa00-f8d1-11ea-8441-d25c9b3583b5.png)

Settings are as follows:

![image](https://user-images.githubusercontent.com/40754213/93446832-f629a880-f8d1-11ea-8f2b-07469bcdb379.png)

We expected the settings to be like this:

![image](https://user-images.githubusercontent.com/40754213/93446869-03df2e00-f8d2-11ea-8118-f9c4c9e9ae02.png)

Is there some docker commands that we are missing, which can assure correct settings,
instead of having to change them manually each time ?

**Comment by freddydk** [comment]
I think this is your browser settings.
If I create a DK container and open the web client in Edge - I get english settings (browser is english - managed by MS)
If I then create a new DK container and open the Web Client in Chrome - I get Danish.
First time you login as a user, the user settings are taken from the browser settings as far as I know.
