### ISSUE TITLE
Import-BcContainerLicense null argument error

### ISSUE THREAD

**Issue by klauskaan** [microsoft/navcontainerhelper#1298]
When i run the following:

$containerName = 'BC16DK'
$licenseFile = 'C:\key\16W1.flf'

Import-BcContainerLicense -containerName $containerName -licenseFile $licenseFile -restart

I get this result:

Copying license file 'C:\key\16W1.flf' to container
Importing License 
Cannot validate argument on parameter 'LicenseFile'. The argument is null or empty. Provide an argument that i
s not null or empty, and then try the command again.
at <ScriptBlock>, <No file>: line 4
Cannot validate argument on parameter 'LicenseFile'. The argument is null or empty. Provide an argument that 
is not null or empty, and then try the command again.
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.6\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 
char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Import-NAVServerLicense], ParameterBindingValidationExceptio 
   n
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Dynamics.Nav.Management.Cmdlets.Imp 
   ortNavServerLicense
    + PSComputerName        : d6d48ed56dc4916e9d3de950a9cf0f58d396a1d89a2abf71a4ff90566884540f

**Comment by freddydk** [comment]
I have to assume that this is a spelling mistake or like in your script:

```
PS C:\WINDOWS\system32> Import-BcContainerLicense -containerName $containerName -licenseFile 'c:\temp\license.flf' -restart
Copying license file 'c:\temp\license.flf' to container
Importing License C:\ProgramData\BcContainerHelper\Extensions\BingMaps-AppSource-Current\my\license.flf
Restarting Service Tier
```

Alternatively you need to specify how you created the container - full command and output.

**Comment by klauskaan** [comment]
I looked in the wiki, but i did not find any information about a template for reporting bugs. Where might i find that?

**Comment by freddydk** [comment]
When creating a new issue:
![image](https://user-images.githubusercontent.com/10775043/93757434-0bbb0d00-fc07-11ea-8b49-ff060cfb7246.png)

**Comment by freddydk** [comment]
Basically it states that I always need the full script + output of the container generation.
The commands typically works (else hell would break loose) - so something was different in the way the container was created in order to cause the issue (that's why)

**Comment by klauskaan** [comment]
ok, so im blind, sorry to waste your time.

Fact is that this container was created months ago and i have no reliable way to extract the script that was run back then.
Any tips on how to update an expiring license on a 16.2 container?

**Comment by freddydk** [comment]
Was the container created using NavContainerHelper - then you cannot manage it with BcContainerHelper. You can place the file in c:\programdata\navcontainerhelper and use docker exec -it <containername> powershell - run c:\run\prompt.ps1 and then you have the standard nav powershell cmdlets available and can import the license from that folder (which is shared with the container).

**Comment by klauskaan** [comment]
Bingo, thanks Freddy :)
Sorry to bother you with this!

**Comment by freddydk** [comment]
Np. made me realize that I needed to add to my blog that you need to remove all containers before switching to bccontainerhelper.
