### ISSUE TITLE
PackageType support in Publish-NAVContainerApp, 

### ISSUE THREAD

**Issue by epernst** [Microsoft/navcontainerhelper#130]
Currently there is no support for the PackageType parameter in Publish-NAVContainerApp. The ability to specify SymbolsOnly is especially important, when you need to publish the symbols extension app files to an database which was upgraded from a previous version. 

In the same way, then it would be very help full also to have the SymbolsOnly option in the Get-NavContainerAppInfo cmdlet. This would allow you to verify, if the symbols where already installed.
Ref: [https://blogs.msdn.microsoft.com/nav/2018/02/02/import-symbols-in-new-or-upgrade-databases-with-microsoft-dynamics-nav-2018/](https://blogs.msdn.microsoft.com/nav/2018/02/02/import-symbols-in-new-or-upgrade-databases-with-microsoft-dynamics-nav-2018/)

**Comment by freddydk** [comment]
Version 0.2.9.0 has been released
