### ISSUE TITLE
Publish runtime app per tenant scope

### ISSUE THREAD

**Issue by Koubek** [microsoft/navcontainerhelper#1302]
**Question**: Is it possible to publish runtime package per tenant scope?

**Scripts used to create container and cause the issue**
```
Publish-NavContainerApp
```

**Additional context**
I need to publish runtime app per tenant scope and I am not able to use the standard ```Publish-NAVApp``` (this one seems to be not able to publish per tenant scope at all) or ```Publish-NavContainerApp``` (we used this but now with runtime packages this doesn't work and I don't know whether the dev api allows publishing of runtime packages).

**Comment by freddydk** [comment]
I would assume so, but I would have to test it.

**Comment by Koubek** [comment]
@freddydk, please, as this is an undocumented feature (as far as I know the dev endpoint API is), I would be very grateful if you could check if this feature is available or not. It would help me to narrow one important failing process (as we switched to runtime packages).

Thanks a lot!!!

**Comment by freddydk** [comment]
Thinking about it - I don't think the dev endpoint will work.
dev endpoint is used when publishing from VS Code and will put apps in, ready for debugging.

I would assume that Publish-NavApp could do this.

**Comment by freddydk** [comment]
![image](https://user-images.githubusercontent.com/10775043/94074596-e6dabb80-fdf9-11ea-87bd-0365280594cd.png)

**Comment by freddydk** [comment]
-scope tenant ???

**Comment by freddydk** [comment]
and this command seems to work just fine:

```
Publish-BcContainerApp -containerName BingMaps-Current -appFile https://businesscentralapps.blob.core.windows.net/enableencryption/latest/runtimepackages.zip -skipVerification -sync -scope Tenant -tenant default -install
Publishing C:\ProgramData\BcContainerHelper\Extensions\BingMaps-Current\__runtimepackages.zip\RuntimePackages\Microsoft_EnableEncryption_15.0.10215.0.app
Synchronizing EnableEncryption on tenant default
Installing EnableEncryption on tenant default
App successfully published
```

**Comment by Koubek** [comment]
Doesn't work, not sure why. I am just getting a weird error. I will try again and paste it here but I think it wasn't able to see anything valuable.

**Comment by Koubek** [comment]
> and this command seems to work just fine:
> 
> ```
> Publish-BcContainerApp -containerName BingMaps-Current -appFile https://businesscentralapps.blob.core.windows.net/enableencryption/latest/runtimepackages.zip -skipVerification -sync -scope Tenant -tenant default -install
> Publishing C:\ProgramData\BcContainerHelper\Extensions\BingMaps-Current\__runtimepackages.zip\RuntimePackages\Microsoft_EnableEncryption_15.0.10215.0.app
> Synchronizing EnableEncryption on tenant default
> Installing EnableEncryption on tenant default
> App successfully published
> ```

Hmmm, that is odd. So it means that dev endpoint is actually able to publish runtime app, do I understand correctly?

**Comment by freddydk** [comment]
Get-BcContainerAppInfo -containerName BingMaps-Current -tenant default -tenantSpecificProperties
```
ServerInstance                        : MicrosoftDynamicsNavServer$BC
ExtensionDataVersion                  : 15.0.10215.0
IsInstalled                           : True
SyncState                             : Synced
NeedsUpgrade                          : False
IsPublished                           : True
PSComputerName                        : b4188588b745771abdfd4fddcd8ebe45ef52578451a6d430b8f4c2f5d5ca4c0e
RunspaceId                            : 6b382815-fc2a-411d-938e-1e53afeafd21
Brief                                 : 
Description                           : 
CompatibilityId                       : 0.0.0.0
PrivacyStatement                      : 
Eula                                  : 
Help                                  : 
Url                                   : 
Logo                                  : 
DeveloperTenantId                     : 
ScreenShots                           : {}
Dependencies                          : {Application, Microsoft, 15.0.0.0, False}
Capabilities                          : {}
PackageId                             : c74a1a0d-f32e-4fdd-bccc-433ac342dca3
PublisherAzureActiveDirectoryTenantId : 
AppId                                 : d5566404-0b9d-4936-a34c-8c1b45fadb7b
Name                                  : EnableEncryption
Publisher                             : Microsoft
Version                               : 15.0.10215.0
ExtensionType                         : ModernDev
Scope                                 : Tenant
Tenant                                : default
```

**Comment by freddydk** [comment]
No, not the dev endpoint.
Publish-BcContainerApp uses Publish-NavApp unless you specify -usedevendpoint and I don't think that will work.
dev endpoint is designed to get apps from vscode and they are not runtime packages.

**Comment by Koubek** [comment]
OK, great Freddy. Then I think there must be something wrong with our app or scripts or ... I will try to go through everything again.

Many thanks for your input (so late!!!).

**Comment by freddydk** [comment]
np - see you

**Comment by Koubek** [comment]
> No, not the dev endpoint.
> Publish-BcContainerApp uses Publish-NavApp unless you specify -usedevendpoint and I don't think that will work.
> dev endpoint is designed to get apps from vscode and they are not runtime packages.

Ahhh, ok. You know, we use separated scripts. I reuse a lot of code but tbh, I don't like these super valuable scripts you provide are so coupled with containers. Yeah, it's a sort of paradox as we use them in containers but you predeterminate the way how everyone has to execute them. So it's a big value you provide but limited to be used only in the way of navcontainerhelper and I think (IMHO) it's a big pity ;)

**Comment by freddydk** [comment]
It is what it is.
My assumption is that 95+% of people using BC on docker are using the containerhelper - I will optimize for helping them and providing open source code for the people who want to do things on their own.

BTW - I think the only thing you need (if you create containers yourself) is to share a few folders with the host and then I guess most containerhelper functions might work.

**Comment by Koubek** [comment]
I just confirm it was our issue, our runtime package was produced by another CU build thant the container that was running and trying to install it. This was ok for non-runtime packages but it's failing for runtime apps.

Thanks Freddy!!!
