### ISSUE TITLE
MultiTenant + AssignPremiumPlan doesn't work

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/navcontainerhelper#131]
When using the New-NavContainer command, using a combination of '-multitenant' and '-assignPremiumPlan' does not work. The record does not get created for the premium plan.

My full command is below. If I remove the '-multitenant' parameter the user plan is added properly.

New-NavContainer -containerName $containerName `
                 -accept_eula `
                 -accept_outdated `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -doNotExportObjectsToText `
                 -imageName $imageName `
                 -includeCSide `
                 -licenseFile $licenseFile `
                 -memoryLimit 6g  `
                 -updateHosts `
                 -useSSL `
                 -alwaysPull `
                 -shortcuts Desktop `
                 -restart no `
                 -includeTestToolkit `
                 -assignPremiumPlan `
                 -multitenant

**Comment by freddydk** [comment]
I have a fix for that - need to get things checked in and published.
Expect next weekend.

**Comment by freddydk** [comment]
version 0.2.9.0 has been released
