### ISSUE TITLE
The variable '$codeSignPfxFile' cannot be retrieved because it has not been set in Devops Release.

### ISSUE THREAD

**Issue by OscarEJ** [microsoft/navcontainerhelper#1310]
Running Run-A Pipeline on a Release Devops generates an error in the part of signing the Apps.

I think the error could be from the variables names used in lines 536, 537, 693 and 694. They don't match the variable names received as parameters in the script.

Scripts used in Devops and cause the issue

Run-AlPipeline @params `
    -pipelinename $pipelineName `
    -containerName $containerName `
    -artifact $artifact.replace('{INSIDERSASTOKEN}', $insiderSasToken) `
    -memoryLimit $memoryLimit `
    -baseFolder $baseFolder `
    -licenseFile $LicenseFile `
...

Error:

##[error]ForEach-Object : The variable '$codeSignPfxFile' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\bcContainerHelper\1.0.6\AppHandling\Run-AlPipeline.ps1:406 char:9

![image](https://user-images.githubusercontent.com/33268906/94411143-812f5c00-0178-11eb-83a0-8c884a7012d1.png)

Screenshots:
![image](https://user-images.githubusercontent.com/33268906/94409914-12053800-0177-11eb-99d1-f614c1a1656b.png)

![image](https://user-images.githubusercontent.com/33268906/94409962-221d1780-0177-11eb-836c-ed876563ee19.png)

![image](https://user-images.githubusercontent.com/33268906/94409987-28ab8f00-0177-11eb-8b12-5a6ca5aac305.png)

**Comment by freddydk** [comment]
You are right . that is a typo - will fix that right away.

**Comment by freddydk** [comment]
This is fixed in a 1.0.7-preview, which should be ready in a few hours.
Run-alPipeline is very much in preview, but slowly getting to the point where I will add the documentation and include it in the HOL - I am using it myself today, but I don't have any projects with certificates running at this time.
Thanks for reporting this.

**Comment by OscarEJ** [comment]
Thank you very much, I will temporarily modify the ps1 file locally.
