### ISSUE TITLE
Request for added functionality for dummies

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#1313]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Is there an option to specify the artifact.cache location.
Something like specifying the -basePath at the same time as creating the image? 

I am trying to set up an environment where I can run the various options for BCContainer, without it filling up my system drive. 
Download-Artifacts will let you specify the -basePath so that you get all the files to a specified drive/folder, but if you are just spinning up a Container, it always seems to to fill up c:\bcartifacts.cache. 
Is there some way that I could have it use the same base folder that I am already using for downloading the artifacts?
NB: I've set up my Docker to use "data-root": "D:/Docker/" so the container is already being moved from c-drive. Now I just need to move the cache folder (Option to move the ProgramData\bcContainerHelper would also be nice, but it is not as place and time consuming as the artifacts)

**Scripts used to create container and cause the issue**
$containerName = 'test'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '15.1.0.0' -country 'dk' -select Closest
$licenseFile = 'd:\nav\infar\udvikling\bc15.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -includeAL `
    -shortcuts CommonDesktopFolder `
    -updateHosts

*
*
*
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\onprem\15.1.37881.38071\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\onprem\15.1.37881.38071\platform\Prerequisite Components\Microsoft Report Viewer 2015\ReportViewer.msi
Downloading c:\bcartifacts.cache\onprem\15.1.37881.38071\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\onprem\15.1.37881.38071\platform\Prerequisite Components\Microsoft Report Viewer 2015\SQLSysClrTypes.msi
Downloading c:\bcartifacts.cache\onprem\15.1.37881.38071\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
*
*
*

**Comment by freddydk** [comment]
If You are using BcContainerHelper, you can create a file called
c:\programdata\bccontainerhelper\bccontainerhelper.config.json
and add the following values:

{
    "bcartifactsCacheFolder":  "d:\\bcartifacts.cache",
    "hostHelperFolder":  "d:\\ProgramData\\BcContainerHelper"
}

Then the containerhelper will use these folders instead.
Note that you should remove existing containers first and you can remove c:\bcartifacts.cache afterwards and also the remaining contents of c:\programdata\bccontainerhelper - the .json file needs to stay though.

**Comment by Rukkulakki** [comment]
Something with the hostHelperFolder seems to make some other logic fail. If I remove it from the json file, the container is created succesfully. Below is the result when it fails.

PS C:\ProgramData\BcContainerHelper> type .\bccontainerhelper.config.json
{
"bcartifactsCacheFolder": "d:\\artifacts",
"hostHelperFolder": "d:\\BcContainerHelper"
}

PS C:\ProgramData\BcContainerHelper> docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

PS C:\ProgramData\BcContainerHelper> $containerName = 'test'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '15.1.0.0' -country 'dk' -select Closest
$licenseFile = 'd:\nav\infar\udvikling\bc15.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -includeAL `
    -shortcuts CommonDesktopFolder `
    -updateHosts

Setting bcartifactsCacheFolder = d:\artifacts
Setting hostHelperFolder = d:\BcContainerHelper
BcContainerHelper is version 1.0.6
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Downloading application artifact /onprem/15.1.37881.38071/dk
Downloading C:\Users\Svend\AppData\Local\Temp\566bbbb3-59b6-4e1a-bfc5-0f0c1fee4b44.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /onprem/15.1.37881.38071/platform
Downloading C:\Users\Svend\AppData\Local\Temp\c180dc7c-8592-4db2-8886-ad83a7dadd2f.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading d:\artifacts\onprem\15.1.37881.38071\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading d:\artifacts\onprem\15.1.37881.38071\platform\Prerequisite Components\Microsoft Report Viewer 2015\ReportViewer.msi
Downloading d:\artifacts\onprem\15.1.37881.38071\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading d:\artifacts\onprem\15.1.37881.38071\platform\Prerequisite Components\Microsoft Report Viewer 2015\SQLSysClrTypes.msi
Downloading d:\artifacts\onprem\15.1.37881.38071\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Creating Container test
Version: 15.1.37881.38071-dk
Style: onprem
Multitenant: No
Platform: 15.0.37898.0
Generic Tag: 0.1.0.21
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file d:\nav\infar\udvikling\bc15.flf
Files in d:\BcContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container test from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
624c9f009b4cca14212ad1ea96748cff2c88ba6d89185c813663624f2f13c97f
Waiting for container test to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/15.1.37881.38071/dk
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\15.1.37881.38071\dk\database\Demo Database NAV (15-0).bak
Changing Database Server Collation to Danish_Greenlandic_100_CI_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 110 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.2.200 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.200 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.31.144.1 in container hosts file
Starting Container
Hostname is test
PublicDnsName is test
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 2F5B7F6585DBF7EC3FFCF932A9C59EA11018D463
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.31.157.209
Container Hostname  : test
Container Dns Name  : test
Web Client          : http://test/BC/
Dev. Server         : http://test
Dev. ServerInstance : BC
Setting test to 172.31.157.209 in host hosts file

Files:
http://test:8080/ALLanguage.vsix

Initialization took 46 seconds
Ready for connections!
Reading CustomSettings.config from test
Creating Desktop Shortcuts for test
Extracting C:\Applications\BaseApp\Source\Base Application.Source.zip
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Cannot find drive. A drive with the name 'd' does not exist.
at <ScriptBlock>, <No file>: line 19
at <ScriptBlock>, <No file>: line 17
Cannot find drive. A drive with the name 'd' does not exist.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.6\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (d:String) [Copy-Item], DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
    + PSComputerName        : 624c9f009b4cca14212ad1ea96748cff2c88ba6d89185c813663624f2f13c97f
 

PS C:\ProgramData\BcContainerHelper>

**Comment by freddydk** [comment]
Looks like something in -includeAL which doesn't support the hosthelperfolder - will check and fix

**Comment by freddydk** [comment]
Shipped in 1.0.7
