### ISSUE TITLE
UnPublish-NavContainerApp: The specified Extension is not published.

### ISSUE THREAD

**Issue by georgii01** [microsoft/navcontainerhelper#1320]
Probably need to pass the name of the tenant.

`UnPublish-BCContainerApp -containerName se17 -appName "Demo" -publisher "Demo" -version 17.0.0.0 -unInstall -force`

Error message: The specified Extension is not published.

![image](https://user-images.githubusercontent.com/43332950/94671620-65f95380-0314-11eb-881e-acf49f5297d8.png)

BcContainer configuration: Multitenant = "Yes"

NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 1809
Client: Docker Engine - Enterprise
 Version:           19.03.2
 API version:       1.40
 Go version:        go1.12.8
 Git commit:        c92ab06ed9
 Built:             09/03/2019 16:38:11
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise
 Engine:
  Version:          19.03.2
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.8
  Git commit:       c92ab06ed9
  Built:            09/03/2019 16:35:47
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by freddydk** [comment]
I think this is fixed in the latest BcContainerHelper - maybe you need the 1.0.7-preview

**Comment by georgii01** [comment]
Thanks.
