### ISSUE TITLE
Access to the path 'C:\$tmp$' is denied.

### ISSUE THREAD

**Issue by mortenseifert** [microsoft/navcontainerhelper#1322]
When creating a container with New-BCContainer the script oftens failes with the follow error message

Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Access to the path 'C:\$tmp$' is denied.
at <ScriptBlock>, C:\Run\start.ps1: line 281
at <ScriptBlock>, <No file>: line 1

In BCContainerHelper version 1.0.5 the error is wher the NAVDVD directory is created. I suspect the root cause is our Anti Virus (Heimdal Thor) which somehow is still scanning the file and this does not allow renaming the file.

If I change the sleep i line 280 from 10 seconds to 100 seconds it solves the problem and my container is created. However the creating is somehow cumbersome.

1. Create container and wait for it to fail
1. Copy the start.ps1 script
1. Modify the line
1. Copy start.ps1 back into container
1. Restart container

```
                       try {
                            Rename-Item -Path $tmpFolder -NewName 'NAVDVD'
                        }
                        catch {
                            Start-Sleep -Seconds 100
                            Rename-Item -Path $tmpFolder -NewName 'NAVDVD'
                        }
```

so, can you change the script to something longer than 10 seconds. Perhaps a look over 10 x 10 seconds or do you think that something else is wrong. I have colleagues with same problem - using the same anti virum program.

**Scripts used to create container and cause the issue**
```
$secpasswd = ConvertTo-SecureString "password" -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential ("admin", $secpasswd)
$artifactUrl = Get-BCArtifactUrl -type OnPrem -version 14.13 -country dk -select Latest
New-BCContainer `
    -containerName test `
    -accept_outdated `
    -accept_eula `
    -artifactUrl $artifactUrl `
    -doNotExportObjectsToText `
    -auth "NavUserPassword" `
    -Credential $cred `
    -usessl:$false `
    -updateHosts `
    -shortcuts None 
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.5
BcContainerHelper is not running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Removing container test
Removing test from host hosts file
Removing test-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\test
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Creating Container test
Version: 14.13.42648.0-dk
Style: onprem
Multitenant: No
Platform: 14.0.42627.0
Generic Tag: 0.1.0.21
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container test from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
209a21ecaeb6d04526deda12687dfeb0fdac55b460d39976058e4a12502ff6ea
Wait-BcContainerReady : The variable '$fimeout' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.5\ContainerHandling\New-NavContainer.ps1:1630 char:
13
+             Wait-BcContainerReady $containerName -timeout $timeout
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (fimeout:String) [Wait-BcContainerReady], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,Wait-BcContainerReady```

**Comment by freddydk** [comment]
Thanks for the detailed description.
As you can guess the sleep and re-rename was inserted for exactly this reason.
I will change the code to be more resilient (retry loop) with next generic image.

for now, you can do two things:
- You could also exclude c:\programdata\docker from your antivirus.
- You can take a copy of start.ps1 - change the timeout to 100 and provide -myscripts @("<fullpathofyourmodifiedstart.ps1>")
(name needs to be start.ps1)

**Comment by freddydk** [comment]
I will replace the code in start.ps1 with this:

                        while (Test-Path $tmpFolder) {
                            try {
                                Rename-Item -Path $tmpFolder -NewName 'NAVDVD'
                            }
                            catch {
                                Write-Host "Unable to rename temp folder, waiting 10 seconds for access..."
                                Start-Sleep -Seconds 10
                            }
                        }

This means that instead of failing the container will hang here forever if access is not given. Then you can break the script and kill the container.

**Comment by freddydk** [comment]
generic image 0.1.0.23 has this functionality, was shipped today

**Comment by mortenseifert** [comment]
Thanks for fixing this so fast! Oh, and the work you do with BcContainerHelper is awesome and helps keep the community running. Thanks again.
