### ISSUE TITLE
Cannot publish app after publishing runtime

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/navcontainerhelper#1323]
**Describe the issue**
I successfully publish a runtime. I then try to publish a standard app, i.e. non-runtime, using the exact same commands, but am hit with a, to me, nondescript error. Issue happens as regular user or admin.

```
One or more errors occurred.
This program location is thought to be unreachable. Array
at <ScriptBlock>, <No file>: line 12
One or more errors occurred.
This program location is thought to be unreachable. Array
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : 2611f571476f8751d4a026f128d7da573badb95379d10adcc0fee1defc6f3d6b
```

**Scripts used to create container and cause the issue**
```
Publish-NavContainerApp -appFile  $file -skipVerification
Sync-NAVContainerApp -appName $name
Install-NavContainerApp -appName $name
```

**Full output of scripts**
```
NavContainerHelper is version 0.6.5.11
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
```

**Screenshots**
![image](https://user-images.githubusercontent.com/16603906/94872839-e69a7b80-040a-11eb-8d0b-a653d1937281.png)

**Additional context**
- does it happen all the time? Yes
- did it use to work? Yes

**Comment by freddydk** [comment]
I have never seen that error before and if I google the error it seems to be some code analyzer giving the problem.

You are running a very old version of NavContainerHelper and I don't know what version of Business Central you are running, but it looks like you are running a very old VM, created by running http://aka.ms/getbc

My recommendation is to create a new VM, which would then switch to using artifacts and use the latest BcContainerHelper - then retry the things you are doing and if you get the same problem, then maybe I will be able to reproduce the steps or look at it.

**Comment by mjmatthiesen** [comment]
I'm writing this over several hours of trying many many different thing.

Our automated builds happen via the artifacts. It had this issue, which is why I tried to do it manually. The VM I develop against just happened to be from an image. Didn't want to replace something that isn't broken, just eats time.

BC Version: Platform 15.0.36510.0 + Application 15.0.36560.0
Updated navcontainerhelper to 0.7.0.26. Same result.

Tried building with the v4 vsix, same result.

So then I recreated the VM from artifacts. So now I'm running bccontainerhelper, but am still experiencing the same issue.
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.7      bccontainerhelper

I created the VM brand new from aka.ms/getbc using "bcartifacts/onprem/15.0/w1/latest" which looks to have resolved to "https://bcartifacts.azureedge.net/onprem/15.0.36626.36675/w1".
Which creates the following:
Platform 15.0.36510.0 + Application 15.0.36626.36675

I tried installing the runtime, and then the my dependent app. Same error.
Tried installing a non-runtime version, and then my dependent app. Same error.

So now I am creating yet another VM from the image, to just double check.

**Comment by mjmatthiesen** [comment]
I looked at the event log within docker as well.

   Index Time          EntryType   Source                 InstanceID Message
   ----- ----          ---------   ------                 ---------- -------
     927 Oct 02 13:42  Error       Microsoft.Dynamic...            0 Type: System.Management.Automation.PipelineStop...
     926 Oct 02 13:42  Error       Microsoft.Dynamic...            0 Type: System.InvalidOperationException...
     925 Oct 02 13:42  Error       MicrosoftDynamics...          701 Server instance: BC...

(Get-Eventlog -index 927 application).message
Type: System.Management.Automation.PipelineStoppedException
WasThrownFromThrowStatement: False
Message: The pipeline has been stopped.
StackTrace:
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object targ
et, Boolean rethrow)
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception)
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.PublishToService()
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Management
HResult: -2146233087
StackTrace:
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception, ErrorCategory category, Object targ
et, Boolean rethrow)
     at Microsoft.Dynamics.Nav.Management.NavCommand.WriteError(Exception exception)
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.PublishToService()
     at Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()

(Get-Eventlog -index 926 application).message
Type: System.InvalidOperationException
Message:
  One or more errors occurred.
  This program location is thought to be unreachable. Array
HResult: -2146233079

(Get-Eventlog -index 925 application).message
Server instance: BC
Category: Extensions
ClientSessionId: 3857e122-6e7d-4d9b-aaad-d4166bb3c953
ClientActivityId: cf00536d-08b9-417b-931c-ddd4f5ab85ff
ServerSessionUniqueId: 8921c54f-f455-4acb-a6a2-3adc48b08dc9
ServerActivityId: 1103481b-58a6-46e6-a4fc-671cc8b8c0c6
EventTime: 10/02/2020 19:42:29
Message One or more errors occurred.
This program location is thought to be unreachable. Array
ProcessId: 4460
Tag: 00001YW
ThreadId: 112
CounterInformation:
CustomParameters: 00000000-0000-0000-0000-000000000000

**Comment by mjmatthiesen** [comment]
I'm closing this. It's a BC15 bug. https://github.com/microsoft/AL/issues/5528
