### ISSUE TITLE
Add the parameter enableSymbolLoading to New-CSideDevContainer 

### ISSUE THREAD

**Issue by megel** [Microsoft/navcontainerhelper#133]
Add this Parameter `enableSymbolLoading`, e.g.:
```
.Parameter enableSymbolLoading
Include this switch if you want to do development in both CSide and VS Code to have symbols automatically generated for your changes in CSide
```
to the function `New-CSideDevContainer` and call `New-NavContainer` with this switch.

**Comment by freddydk** [comment]
The plan is to remove new-csidedevcontainer - not copy all parameters from new-navcontainer to it:-)

**Comment by megel** [comment]
ohh - I have added a Pull Request :)

**Comment by freddydk** [comment]
Why wouldn't you just use new-navcontainer with -includecside (which does exactly the same)?

**Comment by megel** [comment]
Yes you are Right - I discovered during implementing :)
