### ISSUE TITLE
Error: repository name must be lowercase

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1336]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Getting error creating new container 
In nvalid reference format: repository name must be lowercase.
**Scripts used to create container and cause the issue**
```
$containerName = 'vect'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '45' -country 'gb'
$databaseServer = 'host.containerhelper.internal'
$databaseInstance = ''
$databaseName = '"<dbname>"'
$databaseUsername = '<SQLUser>'
$databasePassword = '<SQLpassword>'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = '\\navdev1\c$\Users\Todd.Scott\Desktop\NAV2018License.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'navimage' `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -licenseFile $licenseFile `
    -memoryLimit 4G `
    -includeCSIDE `
    -updateHosts
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Removing vect from host hosts file
Removing vect-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\vect
ArtifactUrl and ImageName specified
Fetching all docker images
Image navimage:onprem-9.0.51476.0-gb-nodb already exists
Using image navimage:onprem-9.0.51476.0-gb-nodb
Creating Container vect
Version: 9.0.51476.0-gb
Style: onprem
Multitenant: No
Platform: 9.0.51476.0
Generic Tag: 0.1.0.23
Container OS Version: 10.0.17763.1457 (ltsc2019)
Host OS Version: 10.0.17763.1457 (ltsc2019)
Using process isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file \\navdev1\c$\Users\Todd.Scott\Desktop\NAV2018License.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\vect\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container vect from image navimage:onprem-9.0.51476.0-gb-nodb
DockerDo : docker: invalid reference format: repository name must be lowercase.
See 'docker run --help'.
ExitCode: 125
Commandline: docker run --env licenseFile="c:\run\my\license.flf" --name vect --hostname vect --env auth=NavUserPassword --env username="admin" 
--env ExitOnError=N --env locale=en-GB --env databaseServer="host.containerhelper.internal" --env databaseInstance="" --volume 
"C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume "C:\ProgramData\BcContainerHelper\Extensions\vect\my:C:\Run\my" 
--isolation process --restart unless-stopped --memory 4G --env databaseName=""<dbname>"" --env useSSL=N --volume 
"C:\ProgramData\BcContainerHelper\Extensions\vect\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env secu
rePassword=76492d1116743f0423413b16050a5345MgB8AG4AYQBNADYAawAvAGwARQBpAHoAaABUAGgAdgBSAEQAeQBwAEoATABIAHcAPQA9AHwAYwA4AGYAYwA5AGQAYgA3ADIAOABjAD
UANAA2AGMAYgA0ADUAYQA0AGMAOQBkAGMAZABjAGUAMQA5ADAANwBiAGMANgA0AGEANgA0ADQAMQAxADAAZgAxADYAYwBhAGYAOABhADYAMgBiADcANQBkAGUANQA1ADUAOABhAGIAZQA= 
--env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env databaseUsername=Docker --env databaseSecurePassword=76492d1116743f
0423413b16050a5345MgB8AGMAdgBuAEIAMQB6AFAAVwBEAGcAYwBpAFYAOQBSADAAbgB3AEwAZgBtAHcAPQA9AHwAYwBjADMAOQA2ADQAOAA3ADEAOAA0AGIAYQA2ADYAZQBlAGIANwA2ADI
AZQAwAGYAYwA5ADYANQAyAGUAZQBlAGEAYQA0ADcANgAwADQAYwBmADQAYQBiAGEAYgA0AGEAMAA0AGQAMAA2ADIAMQAyAGQAZQBlADYAZgAzAGUAZAA= --env encryptionSecurePassw
ord=76492d1116743f0423413b16050a5345MgB8AGMAdgBuAEIAMQB6AFAAVwBEAGcAYwBpAFYAOQBSADAAbgB3AEwAZgBtAHcAPQA9AHwAYwBjADMAOQA2ADQAOAA3ADEAOAA0AGIAYQA2A
DYAZQBlAGIANwA2ADIAZQAwAGYAYwA5ADYANQAyAGUAZQBlAGEAYQA0ADcANgAwADQAYwBmADQAYQBiAGEAYgA0AGEAMAA0AGQAMAA2ADIAMQAyAGQAZQBlADYAZgAzAGUAZAA= --env 
accept_eula=Y --env accept_outdated=Y --detach navimage:onprem-9.0.51476.0-gb-nodb
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.7\ContainerHandling\New-NavContainer.ps1:1646 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
 
```

**Screenshots**
<None>

**Additional context**
Originally ran script with $containerName of vect09045 and got the same error.  
- does it happen all the time?
It happens with this script.  Does not happen with a script for another container
This script works, created just to test if container setup on Windows Server 2019 was working.
```
$containerName = 'my'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'gb' -select 'Latest'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -updateHosts
```

- did it use to work?
Newly created scripts, new Windows Server 2019 server (Azure VM).

**Comment by GreatScott000** [comment]
BTW, created both scripts using

`Invoke-Expression (New-Object System.Net.WebClient).DownloadString("http://aka.ms/bcdockerscript")`

**Comment by GreatScott000** [comment]
Hmm, if I remove the external database reference the script works.  The error message does not seem to indicate that.  Thoughts on what the real error is?  The database name and login exist and appear to work.

**Comment by freddydk** [comment]
and it isn't like if you run it again then maybe it works or fails?
Is this a random bug - or repro'able?

**Comment by GreatScott000** [comment]
It happens everytime I run the script that tries to connect to an external SQL server (on another server in the domain).  I realized I used "localhost" in the script I posted but then changed it and still get the same error.

Updated script:
```
$containerName = 'vecta'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '45' -country 'gb'
$databaseServer = 'navdev1'
$databaseInstance = ''
$databaseName = '"<dbname>"'
$databaseUsername = '<SQLUser>'
$databasePassword = '<SQLPassword>'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = 'F:\License\NAV2018License.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'navimage' `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -memoryLimit 4G `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts
```

**Comment by GreatScott000** [comment]
I can, via SQL Management Studio on the docker machine, login to the remote SQL server and perform a query on the database from the script.  I can also use the PowerShell Invoke-SQLCmd cmdlet to execute the same query against the same SQL server and database.

**Comment by GreatScott000** [comment]
Well since I installed the SqlServer PowerShell module and SQL Management Studio on the server I have gotten further. But still have an issue.

This is the script:
```
$containerName = 'vecta'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '45' -country 'gb'
$databaseServer = 'navdev1'
$databaseInstance = ''
$databaseName = '<dbname'
$databaseCredential = Get-Credential -UserName <SQLUser>-Message 'SQL Auth user/password'
$licenseFile = 'F:\License\NAV2018License.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'navimage' `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -memoryLimit 4G `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts

```
This is the output

> BcContainerHelper is version 1.0.7
> BcContainerHelper is running as administrator
> Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
> Docker Client Version is 19.03.12
> Docker Server Version is 19.03.12
> Removing vecta from host hosts file
> Removing vecta-* from host hosts file
> Removing C:\ProgramData\BcContainerHelper\Extensions\vecta
> ArtifactUrl and ImageName specified
> Fetching all docker images
> Image navimage:onprem-9.0.51476.0-gb-nodb already exists
> Using image navimage:onprem-9.0.51476.0-gb-nodb
> Creating Container vecta
> Version: 9.0.51476.0-gb
> Style: onprem
> Multitenant: No
> Platform: 9.0.51476.0
> Generic Tag: 0.1.0.23
> Container OS Version: 10.0.17763.1457 (ltsc2019)
> Host OS Version: 10.0.17763.1457 (ltsc2019)
> Using process isolation
> Using locale en-GB
> Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
> Using license file F:\License\NAV2018License.flf
> Files in C:\ProgramData\BcContainerHelper\Extensions\vecta\my:
> - AdditionalOutput.ps1
> - AdditionalSetup.ps1
> - license.flf
> - MainLoop.ps1
> - SetupVariables.ps1
> - updatehosts.ps1
> Creating container vecta from image navimage:onprem-9.0.51476.0-gb-nodb
> d85b25fc8c2e79654644e89256132ce99b380b3771e2496fa6cb39c68dc0a7db
> Waiting for container vecta to be ready
> Initializing...
> Setting host.containerhelper.internal to 172.22.16.1 in container hosts file
> Starting Container
> Hostname is vecta
> PublicDnsName is vecta
> Using NavUserPassword Authentication
> Starting Internet Information Server
> Import Encryption Key
> Cannot establish a connection to the SQL Server/Database. 
>   
> This could be due to one of the following reasons:
> 
> * The SQL server is not started.
> * The database does not exist.
> * Proper permissions have not been given to the NAV Server Account.
> 
> Try again later or contact your system administrator.
> at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 148
> at <ScriptBlock>, C:\Run\navstart.ps1: line 113
> at <ScriptBlock>, C:\Run\start.ps1: line 349
> at <ScriptBlock>, <No file>: line 1Error
> Initializing...
> Setting host.containerhelper.internal to 172.22.16.1 in container hosts file
> Starting Container
> Hostname is vecta
> PublicDnsName is vecta
> Using NavUserPassword Authentication
> Starting Internet Information Server
> Import Encryption Key
> Cannot establish a connection to the SQL Server/Database. 
>   
> This could be due to one of the following reasons:
> 
> * The SQL server is not started.
> * The database does not exist.
> * Proper permissions have not been given to the NAV Server Account.
> 
> Try again later or contact your system administrator.
> at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 148
> at <ScriptBlock>, C:\Run\navstart.ps1: line 113
> at <ScriptBlock>, C:\Run\start.ps1: line 349
> at <ScriptBlock>, <No file>: line 1
> Initialization of container vecta failed
> At C:\Program 
> Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.7\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization of container vecta failed:String) [], RuntimeExcepti 
>    on
>     + FullyQualifiedErrorId : Initialization of container vecta failed

**Comment by GreatScott000** [comment]
Switched the script above to create the credential rather than using Get-Credential just in case it was a typo.  Still getting the SQL connection issue.

```
$databaseUsername = '<SQLUser>'
$databasePassword = '<SQLPassword'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
```

**Comment by freddydk** [comment]
After running this, the container is probably still running.
You can use enter-bccontainer in ISE or docker exec -it containername powershell to enter the container.
Then try to ping the databaseserver from inside the container?
and try invoke-sqlcmd from inside the container.

**Comment by GreatScott000** [comment]
Okay, I will try that


Outside the container this script works.
```
$databaseServer = 'navdev1'
$databaseInstance = ''
$databaseName = 'VECT001 Production 20200907'

$databaseUsername = 'SQLuser'
$databasePassword = 'SQLpassword'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword

$dbPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($databaseCredential.Password))
$databaseServerInstance = @{ $true = "$databaseServer\$databaseInstance"; $false = "$databaseServer"}["$databaseInstance" -ne ""]

Invoke-Sqlcmd -ServerInstance $databaseServerInstance -Username $($databaseCredential.Username) -Password $dbPassword -Database $databaseName -Query 'SELECT COUNT(*) FROM [dbo].[User]'


```

**Comment by freddydk** [comment]
you likely cannot just ping the database server from inside the container.
Then you maybe need to switch to transparent network or like.

**Comment by GreatScott000** [comment]
Okay, it will not work with the server NAME as $databaseServer.  I switch to server IP and it works.  

Is there an easy way I could add the HOSTS entry to the container or is the answer transparent network/Traefik?

I will look at transparent networking (I think I have Tobias' video somewhere :)),

This is all (docker server, ADDC, SQL server) in an Azure VM/Virtual Network.

**Comment by freddydk** [comment]
I will share a script you can use

**Comment by GreatScott000** [comment]
That would be great!

**Comment by freddydk** [comment]
Not sure whether resolve-dnsname would give you the ip address of the database server - but on the host you should locate the ip address before new-bccontainer:

```
$ipaddress = (Resolve-DnsName 'www.google.com' -Type A).IPAddress
```

and then add this to new-bccontainer

```
-myScripts @{ "SetupDatabase.ps1" = "Add-Content -Path 'C:\Windows\System32\drivers\etc\hosts' -Value '$ipaddress dbserver'; . 'c:\run\SetupDatabase.ps1'" }
```
This will override the SetupDatabase function and add an entry to the hosts file inside the container.
Then you can use dbserver as database server name inside the container (what you specify)

Let me know if it works

**Comment by GreatScott000** [comment]
That works thank you.
