### ISSUE TITLE
Get-BCArtifactUrl gives old version

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1339]
Hey @freddydk, 
I want to get Artifacts URL for latest October CU for BCSpring2019 edition, but it still gives me September CU link

Here's the command i use:
`Get-BCArtifactUrl -type OnPrem -country w1 -version 14`
it results:
`https://bcartifacts.azureedge.net/onprem/14.17.44663.0/w1`

Here's overview of all released CUs
https://support.microsoft.com/en-ca/help/4501292/released-cumulative-updates-for-microsoft-dynamics-365-business

NavContainerHelper is version 0.7.0.26

**Comment by freddydk** [comment]
That is likely because the October release isn't out on artifacts yet
It should be - will see what happened

**Comment by freddydk** [comment]
Remove a clog in the pipeline - builds should be there now.
