### ISSUE TITLE
Run-TestsInBCContainer | Failed to publish test results: Test result completed date must be greater than test result start date

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#1346]
Hope you guys can help.

The problem is with the publishing of the XUnit to devops, somehow there are negative times per test as a result from Run-TestsInBCContainer 

The following scenario runned by a DevOps pipeline.
We run in docker our tests by this command:

Run-TestsInBCContainer -containerName $ContainerName -companyName '999 AUTO' -XUnitResultFileName (Join-Path $ContainerStoragePath 'TestResults.xml') -AppendToXUnitResultFile -AzureDevOps 'Error'

Next we publish the Xunit through Yaml by this command:

![image](https://user-images.githubusercontent.com/48794854/95311048-68682a00-088d-11eb-87de-67b92410ef4f.png)

During the publish sometimes we got this error, and allot of tests are therefore not uploaded to the DevOps dashboard of tests.
![image](https://user-images.githubusercontent.com/48794854/95310988-55555a00-088d-11eb-8a76-dd3b700e0155.png)

I Guess that it takes the startdatetime from the test and calculates the enddatetime with the runned time. But if i check the TestResult.XML i see that some test have a Negative runtime. so i think this causes the problem

![image](https://user-images.githubusercontent.com/48794854/95311367-ceed4800-088d-11eb-8cfe-a1be56b6879b.png)

the thing is, this test did not fail, all test in this codeunit where succesfull
![image](https://user-images.githubusercontent.com/48794854/95311599-1a9ff180-088e-11eb-993c-847366f69ce7.png)

hope you guys can help.

**Comment by freddydk** [comment]
That is a very very fast computer you have there.
It is capable of finishing a test before it started...

Just kidding I will double check this and make sure that if any test has a negative timespan - it will be 0.

**Comment by freddydk** [comment]
Looked in the code - I get the start and finish time from the test run and it seems like some of them might have an issue.
I will fix the PS test runner to be more resilient and not place negative numbers in test duration.

**Comment by hvandenborn** [comment]
thnx!

**Comment by freddydk** [comment]
Shipped in 1.0.8-preview204
