### ISSUE TITLE
Compiling 2 objects fail after importing them as txt, in a Navison Docker Container

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#135]
For now we are still using image "microsoft/dynamics-nav:2017-cu9" tag 0.0.5.5 and navcontainerhelper version 0.2.8.5

I'm having a problem when compiling 2 objects after importing them as txt.
They are Table 5062 and CodeUnit 5054.

Because we want to run an automated build and release system with docker, we don't want to intervene manually to try to recompile from a developer environment.
We receive following 2 error messages:

: [31588355] Could not load type 'Microsoft.Office.Interop.Word.ApplicationClass.'Microsoft.Office.Interop.Word, Version=14.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c''. -- Object: Codeunit 5054 WordManagement
[31588355] Could not load type 'Microsoft.Office.Interop.Word.Document.'Microsoft.Office.Interop.Word, Version=14.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c''. -- Object: Codeunit 5054 WordManagement
[23462397] You have specified an unknown variable.
ApplicationClass
Define the variable under 'Global C/AL symbols'. -- Object: Codeunit 5054 WordManagement

: [19071033] Could not load the selected type library. -- Object: Table 5062 Attachment

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Compile-NAVApplicationObject
    + PSComputerName        : 8ff606030115fa43d08bc0bceffca8788ef1ad22edde940155a624de142fd265

But when trying to recompile the objects manually anyway, just to test, I also receive:

Could not load type 'Microsoft.Dynamics.Nav.Integration.Office.Outlook.OutlookHelper.'Microsoft.Dynamics.Nav.Integration.Office, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35''

It's kind of obvious that several registered office dll's are missing.
My question is, is there a way to resolve this, like importing and registering some dll's, or (not) installing a complete office-installation into the Docker Container.

**Comment by freddydk** [comment]
If you can find these DLL's you can probably just share a folder with the DLLs to the container into the Add-ins folder - but I have not tried.

**Comment by mheijkant** [comment]
It turn's out these object's are more or less outdated in our database and haven't been modified since 5 years. I  tried to compile both objects from the Desktop Client that was installed which gave the same error's. I made a summary of my findings. Hopefully you and others will find this usefull.
1. The client add-in directory laks the office integration add-in directory. I could copy this one from the service\add-in directory were it was installed already. Maybe you can also add this office add-in by default to the client directory inside the container and outside the container.
2. Both objects were compiled with interop version 14,  while Navision already ships with version 15 for years now, so when modifing or compiling a text import you receive a compiler error. We will resolve this by recompiling with interop v15. For this to work I still have to copy the Microsoft.Office.Interop.* files from the client directory to the add-in directory. Can this also be done by default? Or maybe these dll's aren't available during compilation because of some missing registry settings.
3. There are still some homemade automation variables releated to Word that we have to get ride of asap ourselves.

**Comment by freddydk** [comment]
In the next version of the docker images, the office DLLs from the roletailored client folder will be copied to the Office folder in the ServiceTier add-ins folder.
You can test this behavior by adding this parameter to your new-navcontainer:

`-myScripts @{"AdditionalOutput.ps1" = 'Copy-Item -Path (Join-Path $roleTailoredClientFolder "*office*.dll") -Destination (Join-Path $serviceTierFolder "Add-ins\Office")'}
`

**Comment by freddydk** [comment]
Included in version 0.3.1.0
