### ISSUE TITLE
Feature Request 4 Run-AlPipeline : Make it possible to run tests stored within the same app for 

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1359]
Hey @freddydk, 
Could you please add possibility to run tests for the app stored within the same app. Now, you are forced to specify test folder where test app is programmed. We do store test code within the same app.

I tried to trick your scripts by running like this:
`Run-AlPipeline -imageName myregistry.azurecr.io/imv:latest -pipelineName baseFolder "C:\Users\gintautas\Documents\MyCode\Extensions\AddConsignmentLine" -appFolders "\" -artifact "" -testFolders "\"`

but it fails with the following error:
```
ForEach-Object : Item has already been added. Key in dictionary: '61879e98-e3c3-4196-8044-fe754ca941da'  Key being added: '61879e98-
e3c3-4196-8044-fe754ca941da'
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\1.0.8\AppHandling\Sort-AppFoldersByDependencies.ps1:32 char:19
+     $appFolders | ForEach-Object {
+                   ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [ForEach-Object], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ForEachObjectCommand

```

**Comment by freddydk** [comment]
How will that ever work with AppSource apps and/or Per Tenant Extensions?

**Comment by gintuoklis** [comment]
Those rules are just for publishing extensions to the appsource. Platform itself allows me write test code within the same app, right? 

IMHO testing should be first class citizen of any programming language. If we want to promote developers to write test code it should easy for them todo that. Making separate extensions, handling dependencies, opening test tool or writing test installation logic is not what i call easy. If i have command AL:GO on VSCode, i should also have a command AL:Test that runs all the tests i wrote in my app. If AppSource requires code to exclude test code, perhaps AL compiler should have an option for it. Sorry for offtopic :)

My point is that, I believe many partners are coding extensions within the same app for sake of simplicity, and Run-AlPipeline would benefit with this feature as well.

**Comment by freddydk** [comment]
These rules are for appsource, but you also would not be allowed to upload the app as a per tenant extension as the test apps are not part of production environments and Run-AlPipeline is very much focused on AppSource and PTE's.

Also, I don't think I have ever programmed in any programming language and on any system where app and test was in the same project - IMO it is a bad practice and not really what this function is designed for.

I will consider whether you can override something to make this happen on your own.

**Comment by freddydk** [comment]
Thinking while walking the dog, it would probably be easy to add a switch called RunTestsInAppFolders.
I still think it is a bad architecture though and with the localpipeline (where I compile and publish apps to dev endpoint) you will have a container with all apps ready for RAD afterwards - multiple apps with dependencies works really nicely.

**Comment by freddydk** [comment]
To your points that test needs to be integrated into VS Code - that is in the backlog.
You will eventually be able to run tests directly from VS Code, but we will always need to be able to do it from pipelines as well.
it is totally against my beliefs to have test code and production code in the same extension, you should never ship test code.
Test apps cannot be uploaded to production tenants in the cloud.
I even think that the test extension should be in the public object range and not in the extension range.
Test apps shouldn't follow cop rules etc. etc.
So if you ever want to move the extension you are working on to the cloud - you should not mix the two.

Having said all of that - it is a very easy fix to allow you to specify the same folder as app and test folder, and I guess that I shouldn't be dictating how people work, so I will allow this - but... - be warned, IMO these things should be split for millions of reasons and there is only one reason to keep them together - it is easier.

**Comment by gintuoklis** [comment]
Wow @freddydk , you are full of surprises :)
I was already thinking of writing script to split my test folder to the separate app before running **Run-AlPipeline**.
Did not expect you will come with a changes that quickly.

I tried again with the latest bccontainerhelper

` Run-AlPipeline -imageName myrepository.azurecr.io/imv:latest -pipelineName baseFolder "C:\Users\gintautas\Documents\MyCode\Extensions\AdditionalPurchaseCostAndTaxManagement" -appFolders "\" -artifact "" -testFolders "\" -ImportTestToolkitToBcContainer {Write-Host "Do Not Import Toolkit"}`

Now, it works fine until it tries to run test.

I already have testrunner as part of the object withing my database (C/AL, v.14). Nevertheless, it tries to import it and fails due to codepage problem. Can i disable import of TestToolkit? I tried it by using ImportTestToolkitToBcContainer, but it seems something else.

```
Importing Objects from C:\ProgramData\BcContainerHelper\Extensions\basefolder-bld\PsTestTool\PSTestToolPage.fob (container path)
: [6146889] There is no system code page on your computer that matches the 1252 code page of the Latin1_General_100_CI_AS collation for the CRONUS database.
Your system code pages are: ANSI: 65001, OEM: 65001.
 |  __ \                         (_)              / ____|          | |      (_)
 | |__) |___ _ __ ___   _____   ___ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __
 |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | |____ (_) | | | | |_ (_| | | | | |  __/ |
 |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                           __/ |
                                          |___/

Removing container basefolder-bld
Removing basefolder-bld from host hosts file
Removing basefolder-bld-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\basefolder-bld

Removing container took 38 seconds
: [6146889] There is no system code page on your computer that matches the 1252 code page of the Latin1_General_100_CI_AS collation for the
 CRONUS database.
Your system code pages are: ANSI: 65001, OEM: 65001.
Ensure that the Regional Options of the computer use the correct system language and locale for the code pages to match.
You can also disable the 'Validate Collation' setting for this database. It is possible that certain text data will not be converted correc
tly when stored in the database.
Click OK to disable the 'Validate Collation' setting and continue to use the database, or click Cancel to exit. -- File: C:\ProgramData\BcC
ontainerHelper\Extensions\basefolder-bld\PsTestTool\PSTestToolPage.fob
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by freddydk** [comment]
you could try to add
-ImportTestToolkitToBcContainer { Param([Hashtable]$parameters) Write-Host "Test Toolkit already exists" }

That would override the import-testtoolkit call and skip that.

**Comment by gintuoklis** [comment]
I already tried it. See my script above. Seems that Run-TestsInBcContainer has it's own idea on test toolkit import.

**Comment by freddydk** [comment]
Run-Tests are using a special .fob file (it cannot use the old test runner).
You can see what is happening here:
https://github.com/microsoft/navcontainerhelper/blob/38b962175db7bda60591dba2d072bb5403c693cc/AppHandling/Run-TestsInNavContainer.ps1#L161

I guess you can create the folder and copy to two .ps1 files to the folder yourself - and then run-tests shouldn't import anything - but you would have to download and include the .fob manually.

if you display he full script and output of the pipeline run, I might have other ideas.
