### ISSUE TITLE
Download symbol successfully, but not source code inside

### ISSUE THREAD

**Issue by Kelly-cn** [microsoft/navcontainerhelper#1363]
Good afternoon, I'm trying to find the source code of the "Dynamics GP Intelligent Cloud" and "Business Central Cloud Migration - Previous Release". 

I included them in app.json file and download symbol successfully, then I extracted .app files. No source code inside except SymbolReference.json file.  Please help.

Regards, 
Kelly

**Comment by freddydk** [comment]
I am sorry, but that doesn't seem like a docker problem.
The apps we ship are as .app files inside the container and on the DVD - I don't know whether this app is there.

**Comment by freddydk** [comment]
The cloud migration apps are no longer on the DVD as they are not supposed to be installed locally.
They are to be installed in cloud and connect to local database.
