### ISSUE TITLE
Get-BcArtifactUrl country attribute is case sensitive

### ISSUE THREAD

**Issue by git-no** [microsoft/navcontainerhelper#1364]
## Issue
Attribute `-country` of command `Get-BcArtifactUrl` is case sensitive and therefore the command does not work sometimes.

## Impact
New-BCContainer / container creation fails because of empty image URL (return value of Get-BcArtifactUrl). 

## Example

`Get-BcArtifactUrl -type 'OnPrem' -country 'ch' -select Latest`returns an URL.

`Get-BcArtifactUrl -type 'OnPrem' -country 'CH' -select Latest` **does not** return an URL

## Request

Make attribute `-country` in `Get-BcArtifactURL` case insensitive.

**Comment by freddydk** [comment]
Shipped in 1.0.9
