### ISSUE TITLE
Hyperv isolation on Run-AlPipeline

### ISSUE THREAD

**Issue by dfredborg** [microsoft/navcontainerhelper#1365]
Is there a way to force Hyper V isolation when I use the the Run-AlPipeline?

Because if I do not use Hyper V for my containers I always run into a lot of strange problems with Docker.

**Comment by freddydk** [comment]
If your machine requires hyperv isolation, you should add that to bccontainerhelper.config.json as described here:
https://freddysblog.com/2020/10/10/bccontainerhelper-configuration/

alternatively, you can override NewBcContainer in run-alpipeline as described here: https://freddysblog.com/2020/10/08/run-alpipeline/ and add the extra parameter.

**Comment by dfredborg** [comment]
I do not have a file called C:\ProgramData\BcContainerHelper\BcContainerHelper.config.json so when I try to run

$bcContainerHelperConfig.defaultNewContainerParameters = @{
    "Accept_Eula" = $true
    "Auth" = "UserPassword"
    "UpdateHosts" = $true
    "Isolation" = "hyperv"
}
$bcContainerHelperConfig | ConvertTo-Json | Set-Content "C:\ProgramData\BcContainerHelper\BcContainerHelper.config.json"

I get an error:
The property 'defaultNewContainerParameters' cannot be found on this object. Verify that the proper
ty exists and can be set.

I then tried to create the file and added the following manually:

"defaultNewContainerParameters":  {
    "Accept_Eula":  true,
    "Isolation":  "hyperv",
    "UpdateHosts":  true,
    "Auth":  "UserPassword"
}

But this gives me the following error when i try to import the bccontainerhelper:

![image](https://user-images.githubusercontent.com/19800807/96090489-8c002580-0ec8-11eb-851c-cf2d6f224b2d.png)
 
What am I doing wrong? I am guessing that my BcContainerHelper.config.json is not a vaild format, but how should it be formatted?

**Comment by freddydk** [comment]
What version of bccontainerhelper are you running?

**Comment by dfredborg** [comment]
![image](https://user-images.githubusercontent.com/19800807/96094334-88bb6880-0ecd-11eb-8f9c-56015b2e4cff.png)

**Comment by freddydk** [comment]
You need 1.0.9 in order for this to work (has been available in preview for some time, released now):
1.0.9
Fix issue when setting bccontainerhelperconfig.defaultnewcontainerparameters.credential in the same session as using it
Add parameter AllowAppDatabaseWrite to New-BcContainerTenant. Works with generic image 0.1.0.24 or later.
Merge AdditionalParameters and MyScripts with defaultNewContainerParameters config file settings
Add build number for Windows 10 20H2
Do not install the test toolkit before compiling test apps
Add 2 more overrides ImportTestToolkitToBcContainer and GetBcContainerAppInfo
Issue #1359 Allow apps to contain test code (but not for AppSource Apps or PTEs)
Add useGenericImage parameter to run-alpipeline
Issue #1364 country attribute needs to be case insensitive
Add parameter additionalCountries to allow Run-AlPipeline to test additional countries during the pipeline
Issue #1367 - If two processes build the same image at the same time, the second one always rebuilds

**Comment by dfredborg** [comment]
arg sorry rookie mistake not to be running the latest build 🤦‍♂️, but thanks for the help it solved the problem 👍

**Comment by freddydk** [comment]
1.0.9 was released this morning - you are on the edge of things here:-)
