### ISSUE TITLE
Shared folder between an exisiting nav container and the host

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/navcontainerhelper#137]
Any way to share a folder between an exisiting nav container and the host (using navcontainer helper)?
Just installed a container with BC, and tried to export the standard objects but getting this error on powershell: 

Export-NavContainerObjects SoftstoreBC 'C:\sample'
The folder C:\sample is not shared with the container SampleBC

**Comment by richardrobberse** [comment]
I don't think that's possible, you can work around this by using the folder which is always mapped:
C:\ProgramData\NavContainerHelper\Extensions\<ContainerName>

**Comment by martinhocosta88** [comment]
Thanks a lot Richard. Didn't know that had already one mapped by default. Now I'm getting **'You do not have permission to run the 'File, Export, Text' System.'** but I think it's because business central license.

**Comment by richardrobberse** [comment]
No problem :)
That must be related to your license indeed, you should be able to export with a dev. license.
