### ISSUE TITLE
Question: Create company with advanced evaluation

### ISSUE THREAD

**Issue by MJECloud** [microsoft/navcontainerhelper#1386]
Hi Freddy, 

just a quick question.
Do you know if it is possible to create a new company in BC with advanced evaluation? 
![image](https://user-images.githubusercontent.com/22131101/96560966-3d36ff00-12bf-11eb-86a8-f17c121ff2d8.png)

Looking at the function ```New-CompanyInBcContainer``` you can only create an empty one or with evaluation.  

Thank you. 

Cheers, 
Maurice

**Comment by freddydk** [comment]
You are touching an area here, where I know very little.
Are you using onprem or sandbox containers?

**Comment by MJECloud** [comment]
I'm using sandbox containers. 

What i found out today is when you select an option it imports a special rapidstart package.

'Advanced Evaluation' = EXTENDED 
'Production' = STANDARD
'Evaluation' = EVALUATION
 
The location of the rapidstart packages are in the container under C:\ConfigurationPackages

So i think i'll build a script to create an empty company and then import and apply the configuration package which is needed.

**Comment by freddydk** [comment]
You might be able to find some help here: https://freddysblog.com/2019/09/19/using-apis-on-containers/

**Comment by MJECloud** [comment]
Thank you! :) 

Would'nt it be a great addition to the bccontainerhelper too?

**Comment by freddydk** [comment]
I have it on my list of todos but the priority is low as the blog post explains exactly how to do.
