### ISSUE TITLE
Run-AlPipeline: DockerDo : failed to register layer: re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the file specified.

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/navcontainerhelper#1388]
**Describe the issue**
Today I updated to BcContainterhelper and I have managed to create a container with New-BCContainer.
I have cloned the https://dev.azure.com/businesscentralapps/_git/BingMaps (cloned to C:\Git\bingmaps) and used the template for calling Run-AIPipeline but with my own parameters but the creation of the container seems to fail since it immediatly tries to remove it with error.
After a second glance I can see in the output that it already fails in pulling of generic image
```
Pulling mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
failed to register layer: re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the file specified. (0x2)
```

**Scripts used to create container and cause the issue**
```
Run-AlPipeline `
    -pipelineName "BingMaps" `
    -licenseFile "C:\git\bingmaps\DeveloperLicense.flf" `
    -baseFolder "C:\git\bingmaps" `
    -appFolders @("app") `
    -testFolders @("test") `
    -installTestFramework `
    -enablePerTenantExtensionCop `
    -enableUICop
```

**Full output of scripts**
```
=====> PowerShell Integrated Console v2020.6.0 <=====

PS C:\GIT\BingMaps> Run-AlPipeline `
    -pipelineName "BingMaps" `
    -licenseFile "C:\git\bingmaps\DeveloperLicense.flf" `
    -baseFolder "C:\git\bingmaps" `
    -appFolders @("app") `
    -testFolders @("test") `
    -installTestFramework `
    -enablePerTenantExtensionCop `
    -enableUICop
  _____                               _
 |  __ \                             | |
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___ 
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Pipeline name               BingMaps
Container name              bingmaps-bld
Image name                  my
ArtifactUrl                 https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
SasToken                    Not Specified
Credential                  admin/Decu5314
MemoryLimit                 8G
Enable Task Scheduler       False
Assign Premium Plan         False
Install Test Framework      True
Install Test Libraries      False
Install Perf. Toolkit       False
enableCodeCop               False
enableAppSourceCop          False
enableUICop                 True
enablePerTenantExtensionCop True
azureDevOps                 False
License file                Specified
CodeSignCertPfxFile         Not specified
TestResultsFile             C:\git\bingmaps\TestResults.xml
TestResultsFormat           JUnit
AdditionalCountries
PackagesFolder              C:\git\bingmaps\.packages
OutputFolder                C:\git\bingmaps\.output
BuildArtifactFolder
CreateRuntimePackages       False
AppBuild                    0
AppRevision                 0
Install Apps
- None
Previous Apps
- None
Application folders
- C:\git\bingmaps\app
Test application folders
- C:\git\bingmaps\test

  _____       _ _ _                                          _        _
 |  __ \     | | (_)                                        (_)      (_)
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |
                          |___/   |___/                                                 |___/

Pulling mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
failed to register layer: re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the file specified. (0x2)

Pulling generic image took 7 seconds

   _____                _   _                               _        _
  / ____|              | | (_)                             | |      (_)
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                     __/ |
                                    |___/

BcContainerHelper is version 1.0.9
BcContainerHelper is not running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 18.09.7
Docker Server Version is 19.03.13
Downloading application artifact /sandbox/17.0.17126.17839/us
Downloading C:\Users\margus\AppData\Local\Temp\11b6210a-11b6-4294-9e67-8c62a73091b2.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/17.0.17126.17839/platform
Downloading C:\Users\margus\AppData\Local\Temp\7b57c65f-adaf-49a5-8919-f79d2135c6f9.zip
Retrying download...
Downloading C:\Users\margus\AppData\Local\Temp\7b57c65f-adaf-49a5-8919-f79d2135c6f9.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\17.0.17126.17839\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\17.0.17126.17839\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\17.0.17126.17839\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Fetching all docker images
ArtifactUrl and ImageName specified
Building multitenant image my:sandbox-17.0.17126.17839-us-mt based on mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic with https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
295f12394c4f: Already exists
fbc68affb523: Already exists
54909e05a1be: Already exists
975f8c606567: Already exists
b21585eb8358: Already exists
36508056fc76: Already exists
ff80e88f1945: Already exists
0de3a359dfb1: Already exists
e8ae433a2170: Already exists
3da9157d8cf8: Already exists
e98650f27ce0: Already exists
f153b24a8b70: Already exists
f3c97324096a: Already exists
887011bce52f: Already exists
523bce31be18: Already exists
d351adf6f48d: Already exists
4ea2bb70da16: Pulling fs layer
c2510c44c41b: Pulling fs layer
c2510c44c41b: Verifying Checksum
c2510c44c41b: Download complete
4ea2bb70da16: Download complete

  _____                           _                _____            _        _
 |  __ \                         (_)              / ____|          | |      (_)
 | |__) |___ _ __ ___   _____   ___ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | |____ (_) | | | | |_ (_| | | | | |  __/ |
 |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                           __/ |
                                          |___/


Removing container took 0 seconds
DockerDo : failed to register layer: re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the file specified.
 (0x2)
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\New-NavImage.ps1:231 char:17
+                 DockerDo -command pull -imageName $baseImage | Out-Nu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

PS C:\GIT\BingMaps> 
```

**Comment by freddydk** [comment]
Have you checked these things: https://freddysblog.com/2020/10/12/troubleshooting-business-central-on-docker/

**Comment by freddydk** [comment]
It is strange that a container with new-bccontainer worked. I don't understand why it needs to pull the generic image here (that one should be needed in the normal container as well). Did you create a container based on an image or artifatcs?
It looks like an issue in the file system when trying to pull the generic image - I would reset docker to factory settings or use https://freddysblog.com/2018/12/11/clean-up-after-yourself-docker-your-mom-isnt-here/

**Comment by TheGreatBorg** [comment]
Wow a doublet in the same 2 hours - what's the odds for that?  :-) 

> 725f541a8160: Pulling fs layer
> 725f541a8160: Verifying Checksum
> 395da6675996: Verifying Checksum
> 395da6675996: Download complete
> 725f541a8160: Download complete
> DockerDo : failed to register layer: re-exec error: exit status 1: output: hcsshim::ImportLayer - failed failed in Win32: The system cannot find the file specified. (
> 0x2)
> ExitCode: 1
> Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.18363.1082-generic
> At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\New-NavContainer.ps1:657 char:13
>              DockerDo -command pull -imageName $bestImageName | Out-Nu ...
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
>

**Comment by freddydk** [comment]
New-NavContainer is just an alias for New-BcContainer
Again - this likely doesn't have anything to do with run-alpipeline.
I think the simplest container from here: https://freddysblog.com/2020/10/12/troubleshooting-business-central-on-docker/ also fails.

**Comment by TheGreatBorg** [comment]
Hm - Windows-servercore could get in:

`PS C:\> docker pull mcr.microsoft.com/windows/servercore:10.0.18363.1082
10.0.18363.1082: Pulling from windows/servercore
9038b92872bc: Already exists
b1397fff109a: Already exists
Digest: sha256:d80302fbe66b705c133375e76bf81b4c36d670a589c93b93da001fad6e19a5ee
Status: Downloaded newer image for mcr.microsoft.com/windows/servercore:10.0.18363.1082
mcr.microsoft.com/windows/servercore:10.0.18363.1082`

**Comment by NAVFreak** [comment]
Ok, now I have tried to reset my docker to factory settings. Couldn't do that for some reasons. So in the end I choosed Clean/Purge data, manually deleted the container folders. Uninstalled docker desktop, installed it again.
And finally 🥁 it worked!
However it still had to download mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic image. It sounded like a problem to you Freddy or Im wrong.

Here is the output, which ended in error but I have already read that is an ongoing error with the testtoolkit.
Summary: Clean/Purge docker desktop och reinstall solved the issue.
`
PS C:\GIT\BingMaps> Run-AlPipeline `
    -pipelineName "BingMaps" `
    -licenseFile "C:\git\bingmaps\DeveloperLicense.flf" `
    -baseFolder "C:\git\bingmaps" `
    -appFolders @("app") `
    -testFolders @("test") `
    -installTestFramework `
    -enablePerTenantExtensionCop `
    -enableUICop
  _____                               _
 |  __ \                             | |
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___ 
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Pipeline name               BingMaps
Container name              bingmaps-bld
Image name                  my
ArtifactUrl                 https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
SasToken                    Not Specified
Credential                  admin/Teri4135
MemoryLimit                 8G
Enable Task Scheduler       False
Assign Premium Plan         False
Install Test Framework      True
Install Test Libraries      False
Install Perf. Toolkit       False
enableCodeCop               False
enableAppSourceCop          False
enableUICop                 True
enablePerTenantExtensionCop True
azureDevOps                 False
License file                Specified
CodeSignCertPfxFile         Not specified
TestResultsFile             C:\git\bingmaps\TestResults.xml
TestResultsFormat           JUnit
AdditionalCountries
PackagesFolder              C:\git\bingmaps\.packages
OutputFolder                C:\git\bingmaps\.output
BuildArtifactFolder
CreateRuntimePackages       False
AppBuild                    0
AppRevision                 0
Install Apps
- None
Previous Apps
- None
Application folders
- C:\git\bingmaps\app
Test application folders
- C:\git\bingmaps\test

  _____       _ _ _                                          _        _
 |  __ \     | | (_)                                        (_)      (_)
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___ 
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |
                          |___/   |___/                                                 |___/

Pulling mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic

Pulling generic image took 2728 seconds

   _____                _   _                               _        _
  / ____|              | | (_)                             | |      (_)
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                     __/ |
                                    |___/

BcContainerHelper is version 1.0.9
BcContainerHelper is not running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 18.09.7
Docker Server Version is 19.03.13
Fetching all docker images
ArtifactUrl and ImageName specified
Building multitenant image my:sandbox-17.0.17126.17839-us-mt based on mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic with https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
Generic Tag: 0.1.0.24
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using license file C:\git\bingmaps\DeveloperLicense.flf
Files in c:\bcartifacts.cache\tmp637388081190430847\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Extensions
Copying Applications.US
c:\bcartifacts.cache\tmp637388081190430847
Sending build context to Docker daemon  1.778GB

Step 1/6 : FROM mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
 ---> a1beef6c2e2c
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
 ---> Running in 067fea784be8
Removing intermediate container 067fea784be8
 ---> b518ee4e6db1
Step 3/6 : COPY my /run/
 ---> 3d1618a2cda2
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 7f9df9b7450e
Step 5/6 : RUN \Run\start.ps1 -installOnly -multitenant
 ---> Running in 4b87256794c0
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation
Restoring CRONUS Demo Database
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Starting Business Central Service Tier
Importing CRONUS license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 243 seconds
Installation complete
Removing intermediate container 4b87256794c0
 ---> dde4e7813e54
Step 6/6 : LABEL legal="http://go.microsoft.com/fwlink/?LinkId=837447"       created="202010201429"       nav=""       cu=""       multitenant="Y" country="US"      
 version="17.0.17126.17839"       platform="17.0.17020.17774"
 ---> Running in 0f4b96b4bef4
Removing intermediate container 0f4b96b4bef4
 ---> 398420ea6a82
Successfully built 398420ea6a82
Successfully tagged my:sandbox-17.0.17126.17839-us-mt
Building image took 607 seconds
Using image my:sandbox-17.0.17126.17839-us-mt
Creating Container bingmaps-bld
Version: 17.0.17126.17839-US
Style: sandbox
Multitenant: Yes
Platform: 17.0.17020.17774
Generic Tag: 0.1.0.24
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\git\bingmaps\DeveloperLicense.flf
Additional Parameters:
--volume C:\git\bingmaps:c:\sources
--env customNavSettings=EnableTaskScheduler=False
Files in C:\ProgramData\BcContainerHelper\Extensions\bingmaps-bld\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bingmaps-bld from image my:sandbox-17.0.17126.17839-us-mt
a945bfa4ca737150494c1d9bd2cbbbfa78860b5dc18efbf57c0e19c444b3d80a
Waiting for container bingmaps-bld to be ready
Initializing...
Setting host.docker.internal to 192.168.1.103 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.103 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.25.16.1 in container hosts file
Starting Container
Hostname is bingmaps-bld
PublicDnsName is bingmaps-bld
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint E1B7C1FA16B140AA1ED1B0406FF4BCDF0B0FD691
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Enabling rewrite rule: Don't rewrite system files
Enabling rewrite rule: Already have tenant specified
Enabling rewrite rule: Hostname (without port) to tenant
Using license file 'c:\run\my\license.flf'
Import License
Dismounting Tenant
Mounting Tenant
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.25.22.146
Container Hostname  : bingmaps-bld
Container Dns Name  : bingmaps-bld
Web Client          : http://bingmaps-bld/BC/?tenant=default
Dev. Server         : http://bingmaps-bld
Dev. ServerInstance : BC
Dev. Server Tenant  : default
Setting bingmaps-bld to 172.25.22.146 in host hosts file
Setting bingmaps-bld-default to 172.25.22.146 in host hosts file

Files:
http://bingmaps-bld:8080/ALLanguage.vsix

Container Total Physical Memory is 31.7Gb
Container Free Physical Memory is 10.6Gb

Initialization took 38 seconds
Ready for connections!
Reading CustomSettings.config from bingmaps-bld
Creating Desktop Shortcuts for bingmaps-bld
Container bingmaps-bld successfully created

Use:
Get-BcContainerEventLog -containerName bingmaps-bld to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bingmaps-bld to get debug information about the container
Enter-BcContainer -containerName bingmaps-bld to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bingmaps-bld to remove the container again
docker logs bingmaps-bld to retrieve information about URL's again

Creating container took 660 seconds

   _____                      _ _ _
  / ____|                    (_) (_)
 | |     ___  _ __ ___  _ __  _| |_ _ __   __ _    __ _ _ __  _ __  ___
 | |    / _ \| '_ ` _ \| '_ \| | | | '_ \ / _` |  / _` | '_ \| '_ \/ __|
 | |____ (_) | | | | | | |_) | | | | | | | (_| | | (_| | |_) | |_) \__ \
  \_____\___/|_| |_| |_| .__/|_|_|_|_| |_|\__, |  \__,_| .__/| .__/|___/
                       | |                 __/ |       | |   | |
                       |_|                |___/        |_|   |_|

Using Symbols Folder: C:\git\bingmaps\.packages
Downloading symbols: Microsoft_Application_17.0.17126.17839.app
Url : http://172.25.22.146:7049/BC/dev/packages?publisher=Microsoft&appName=Application&versionText=16.0.0.0&tenant=default
Adding dependency to System Application from Microsoft
Adding dependency to Base Application from Microsoft
Downloading symbols: Microsoft_System_17.0.17020.17774.app
Url : http://172.25.22.146:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=16.0.0.0&tenant=default
Downloading symbols: Microsoft_System Application_17.0.17126.17839.app
Url : http://172.25.22.146:7049/BC/dev/packages?publisher=Microsoft&appName=System Application&versionText=17.0.0.0&tenant=default
Downloading symbols: Microsoft_Base Application_17.0.17126.17839.app
Url : http://172.25.22.146:7049/BC/dev/packages?publisher=Microsoft&appName=Base Application&versionText=17.0.0.0&tenant=default
Compiling...
.\alc.exe /project:"c:\sources\app" /packagecachepath:"c:\sources\.packages" /out:"c:\sources\.output\Freddy Kristiansen_BingMaps_16.0.0.0.app" /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.PerTenantExtensionCop.dll /analyzer:C:\build\vsix\extension\bin\Analyzers\Microsoft.Dynamics.Nav.UICop.dll /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\170\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\170\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\Windows\Microsoft.NET\Assembly","C:\Test Assemblies\Mock Assemblies"
Microsoft (R) AL Compiler version 6.0.5.10826
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'BingMaps' containing '11' files at '16:39:59.615'.

c:\sources\app\Api BingMaps Settings.al(20,38): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps CustomerMap.al(11,26): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Api BingMaps Customer.al(20,27): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps Setup.al(24,39): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an 
error in a future release.
c:\sources\app\Api BingMaps Customer.al(24,29): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Api BingMaps Settings.al(25,29): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps Setup.al(34,42): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an 
error in a future release.
c:\sources\app\Api BingMaps Customer.al(28,29): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Api BingMaps Settings.al(30,30): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Api BingMaps Customer.al(32,32): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Api BingMaps Customer.al(36,30): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps Setup.al(39,48): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an 
error in a future release.
c:\sources\app\Page BingMaps Setup.al(43,43): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an 
error in a future release.
c:\sources\app\Api BingMaps Customer.al(71,33): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps Setup.al(102,16): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps Setup.al(103,13): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps Setup.al(104,13): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Api BingMaps Settings.al(45,14): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Api BingMaps Settings.al(51,56): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps CustomerMap.al(46,25): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps CustomerMap.al(47,35): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps CustomerMap.al(48,36): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps CustomerMap.al(49,31): warning AL0604: Use of implicit 'with' will be removed in the future. Qualify with 'Rec.'. This warning will become an error in a future release.
c:\sources\app\Page BingMaps Setup.al(55,20): info AW0011: Group "processing" only contains promoted actions that are not set to PromotedOnly="true".
c:\sources\app\Page BingMaps Setup.al(77,20): info AW0011: Group "processing" only contains promoted actions that are not set to PromotedOnly="true".
c:\sources\app\Permissions.xml(1,1): info AL1027: The file at location 'c:\sources\app\Permissions.xml' matches the definition for 'PermissionSet'.
c:\sources\app\Web Services.xml(1,1): info AL1027: The file at location 'c:\sources\app\Web Services.xml' matches the definition for 'TenantWebService'.

Compilation ended at '16:40:4.828'.

C:\git\bingmaps\.output\Freddy Kristiansen_BingMaps_16.0.0.0.app successfully created in 36 seconds
Freddy Kristiansen_BingMaps_16.0.0.0.app copied to C:\git\bingmaps\.packages
  _____                            _   _               _______       _     _______          _ _    _ _   
 |_   _|                          | | (_)             |__   __|     | |   |__   __|        | | |  (_) |
   | |  _ __ ___  _ __   ___  _ __| |_ _ _ __   __ _     | | ___ ___| |_     | | ___   ___ | | | ___| |_ 
   | | | '_ ` _ \| '_ \ / _ \| '__| __| | '_ \ / _` |    | |/ _ \ __| __|    | |/ _ \ / _ \| | |/ / | __|
  _| |_| | | | | | |_) | (_) | |  | |_| | | | | (_| |    | |  __\__ \ |_     | | (_) | (_) | |   <| | |_
 |_____|_| |_| |_| .__/ \___/|_|   \__|_|_| |_|\__, |    |_|\___|___/\__|    |_|\___/ \___/|_|_|\_\_|\__|
                 | |                            __/ |
                 |_|                           |___/

  _____                           _                _____            _        _
 |  __ \                         (_)              / ____|          | |      (_)
 | |__) |___ _ __ ___   _____   ___ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | |____ (_) | | | | |_ (_| | | | | |  __/ |
 |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|
                                           __/ |
                                          |___/

Removing container bingmaps-bld
Removing bingmaps-bld from host hosts file
Removing bingmaps-bld-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\bingmaps-bld

Removing container took 4 seconds
% : The property 'IsInstalled' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ObjectHandling\Import-TestToolkitToNavContainer.ps1:127 char:21
+         $appFiles | % {
+                     ~~~
    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.ForEachObjectCommand`

**Comment by freddydk** [comment]
That error is this one - https://github.com/microsoft/navcontainerhelper/issues/1380
Will publish a new containerhelper tonight
