### ISSUE TITLE
Setup-BcContainerTestUsers  err on BC 17

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/navcontainerhelper#1389]
use the command to create test users
Setup-BcContainerTestUsers  on BC 17

gives error:

Copy from container mem (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\BcCont
ainerHelper\Extensions\mem\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\BcContainerHelper\Extensions\mem\_Microsoft_System Application Test Library.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols fo
r the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols 
for the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Publi 
   shNavApp
    + PSComputerName        : 245eb51eaafbe1e62cb644adc0a507608e5a5dd1bf3394e6d57620b87e68eb18

**Comment by freddydk** [comment]
Please add script and full output of container generation as well.

**Comment by shashiBssi** [comment]
New-BcContainer -containerName $oldcontainer `
        -accept_eula `
        -auth NavUserPassword `
        -doNotExportObjectsToText `
        -artifactUrl $artifactUrl `
        -credential $credential `
        -licenseFile $mylicense `
        -updateHosts `
        -memoryLimit 5G `
        -assignPremiumPlan `
        -dns 8.8.8.8 `
        -useSSL `
        -installCertificateOnHost `
        -multitenant:$false `
        -alwayspull `
        -finalizeDatabasesScriptBlock {
        New-NavContainerNavUser -Credential $credentialT -ChangePasswordAtNextLogOn 0 -containerName $oldcontainer
        $SecurePassword = ConvertTo-SecureString sv –asplaintext –force 

        Setup-NavContainerTestUsers -containerName $oldcontainer -tenant default  -password $SecurePassword -credential $credential




BcContainerHelper is version 1.0.9
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Creating Container mem2
Version: 17.0.17126.17839-US
Style: sandbox
Multitenant: No
Platform: 17.0.17020.17774
Generic Tag: 0.1.0.24
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file E:\bc license\D365BC-V17.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\mem2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container mem2 from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa
Waiting for container mem2 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.0.17126.17839\us\BusinessCentral-US.bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 421 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.208.1 in container hosts file
Starting Container
Hostname is mem2
PublicDnsName is mem2
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B639011945276F62210BE4C19BD473D12AC27B7A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating sv as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Assign Premium plan for SV
Container IP Address: 172.19.217.39
Container Hostname  : mem2
Container Dns Name  : mem2
Web Client          : https://mem2/BC/
Dev. Server         : https://mem2
Dev. ServerInstance : BC
Setting mem2 to 172.19.217.39 in host hosts file

Files:
http://mem2:8080/ALLanguage.vsix
http://mem2:8080/certificate.cer

Container Total Physical Memory is 31.9Gb
Container Free Physical Memory is 6.9Gb

Initialization took 72 seconds
Ready for connections!
Reading CustomSettings.config from mem2
Certificate with thumbprint B639011945276F62210BE4C19BD473D12AC27B7A imported successfully
Creating Desktop Shortcuts for mem2
Creating User svt
WARNING: The password that you entered does not meet the minimum requirements. It should be at least 8 characters long and contain at le
ast one uppercase letter, one lowercase letter, and one number.
Assigning Permission Set SUPER to svt
Copy from container mem2 (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\BcCon
tainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\BcContainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols fo
r the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols 
for the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Publi 
   shNavApp
    + PSComputerName        : 93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa

**Comment by freddydk** [comment]
Please format things with "insert code" to ensure readability

**Comment by shashiBssi** [comment]
`BcContainerHelper is version 1.0.9
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Creating Container mem2
Version: 17.0.17126.17839-US
Style: sandbox
Multitenant: No
Platform: 17.0.17020.17774
Generic Tag: 0.1.0.24
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file E:\bc license\D365BC-V17.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\mem2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container mem2 from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa
Waiting for container mem2 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.0.17126.17839\us\BusinessCentral-US.bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 421 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.208.1 in container hosts file
Starting Container
Hostname is mem2
PublicDnsName is mem2
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B639011945276F62210BE4C19BD473D12AC27B7A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating sv as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Assign Premium plan for SV
Container IP Address: 172.19.217.39
Container Hostname  : mem2
Container Dns Name  : mem2
Web Client          : https://mem2/BC/
Dev. Server         : https://mem2
Dev. ServerInstance : BC
Setting mem2 to 172.19.217.39 in host hosts file

Files:
http://mem2:8080/ALLanguage.vsix
http://mem2:8080/certificate.cer

Container Total Physical Memory is 31.9Gb
Container Free Physical Memory is 6.9Gb

Initialization took 72 seconds
Ready for connections!
Reading CustomSettings.config from mem2
Certificate with thumbprint B639011945276F62210BE4C19BD473D12AC27B7A imported successfully
Creating Desktop Shortcuts for mem2
Creating User svt
WARNING: The password that you entered does not meet the minimum requirements. It should be at least 8 characters long and contain at le
ast one uppercase letter, one lowercase letter, and one number.
Assigning Permission Set SUPER to svt
Copy from container mem2 (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\BcCon
tainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\BcContainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols fo
r the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols 
for the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Publi 
   shNavApp
    + PSComputerName        : 93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa`

**Comment by shashiBssi** [comment]
`BcContainerHelper is version 1.0.9
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Creating Container mem2
Version: 17.0.17126.17839-US
Style: sandbox
Multitenant: No
Platform: 17.0.17020.17774
Generic Tag: 0.1.0.24
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file E:\bc license\D365BC-V17.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\mem2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container mem2 from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa
Waiting for container mem2 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.0.17126.17839\us\BusinessCentral-US.bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 421 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.208.1 in container hosts file
Starting Container
Hostname is mem2
PublicDnsName is mem2
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B639011945276F62210BE4C19BD473D12AC27B7A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating sv as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Assign Premium plan for SV
Container IP Address: 172.19.217.39
Container Hostname  : mem2
Container Dns Name  : mem2
Web Client          : https://mem2/BC/
Dev. Server         : https://mem2
Dev. ServerInstance : BC
Setting mem2 to 172.19.217.39 in host hosts file

Files:
http://mem2:8080/ALLanguage.vsix
http://mem2:8080/certificate.cer

Container Total Physical Memory is 31.9Gb
Container Free Physical Memory is 6.9Gb

Initialization took 72 seconds
Ready for connections!
Reading CustomSettings.config from mem2
Certificate with thumbprint B639011945276F62210BE4C19BD473D12AC27B7A imported successfully
Creating Desktop Shortcuts for mem2
Creating User svt
WARNING: The password that you entered does not meet the minimum requirements. It should be at least 8 characters long and contain at le
ast one uppercase letter, one lowercase letter, and one number.
Assigning Permission Set SUPER to svt
Copy from container mem2 (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\BcCon
tainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\BcContainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols fo
r the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols 
for the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Publi 
   shNavApp
    + PSComputerName        : 93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa`

**Comment by freddydk** [comment]
![image](https://user-images.githubusercontent.com/10775043/96586001-a11def80-12e0-11eb-914e-46167f330d6a.png)

**Comment by freddydk** [comment]
![image](https://user-images.githubusercontent.com/10775043/96586059-b72bb000-12e0-11eb-9f9d-5a1efb695ed3.png)

**Comment by shashiBssi** [comment]
`BcContainerHelper is version 1.0.9
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
10.0.19041.508-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
Creating Container mem2
Version: 17.0.17126.17839-US
Style: sandbox
Multitenant: No
Platform: 17.0.17020.17774
Generic Tag: 0.1.0.24
Container OS Version: 10.0.19041.508 (2004)
Host OS Version: 10.0.19041.508 (2004)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file E:\bc license\D365BC-V17.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\mem2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container mem2 from image mcr.microsoft.com/dynamicsnav:10.0.19041.508-generic
93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa
Waiting for container mem2 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.0.17126.17839/us
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.0.17126.17839\us\BusinessCentral-US.bak
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.US
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 421 seconds
Installation complete
Initializing...
Setting host.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.0.0.165 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.208.1 in container hosts file
Starting Container
Hostname is mem2
PublicDnsName is mem2
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B639011945276F62210BE4C19BD473D12AC27B7A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating sv as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Assign Premium plan for SV
Container IP Address: 172.19.217.39
Container Hostname  : mem2
Container Dns Name  : mem2
Web Client          : https://mem2/BC/
Dev. Server         : https://mem2
Dev. ServerInstance : BC
Setting mem2 to 172.19.217.39 in host hosts file

Files:
http://mem2:8080/ALLanguage.vsix
http://mem2:8080/certificate.cer

Container Total Physical Memory is 31.9Gb
Container Free Physical Memory is 6.9Gb

Initialization took 72 seconds
Ready for connections!
Reading CustomSettings.config from mem2
Certificate with thumbprint B639011945276F62210BE4C19BD473D12AC27B7A imported successfully
Creating Desktop Shortcuts for mem2
Creating User svt
WARNING: The password that you entered does not meet the minimum requirements. It should be at least 8 characters long and contain at le
ast one uppercase letter, one lowercase letter, and one number.
Assigning Permission Set SUPER to svt
Copy from container mem2 (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\BcCon
tainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\BcContainerHelper\Extensions\mem2\_Microsoft_System Application Test Library.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols fo
r the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols 
for the requested app Any by Microsoft 17.0.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Publi 
   shNavApp
    + PSComputerName        : 93f627d3db8b33df82a362c0b1e097d4b7b81f8a27ff0e70de2206fdcd08abaa`

**Comment by shashiBssi** [comment]
even if i run this command separately (not as a part of conatiner creation script). it gives the same error

**Comment by freddydk** [comment]
When you create an issue here, please format the script and output like I just did with the first issue.
It makes it possible for me to read and help you.

You probably need to add -includeTestToolkit -includeTestLibrariesOnly to the container creation - the app it asks for is part of the test framework
