### ISSUE TITLE
New-BCContainerWizard closes if font size for Powershell to too big

### ISSUE THREAD

**Issue by hougaard** [microsoft/navcontainerhelper#1392]
Set the font size for Powershell window to be 36 or higher (on my machine) and New-BCContainerWizard will close the window again after briefly opening it.

![image](https://user-images.githubusercontent.com/3357237/96789108-66cc5500-13a9-11eb-9cde-600a607363af.png)

**Comment by freddydk** [comment]
Fix shipped in 1.0.10
