### ISSUE TITLE
Helloworld settings.json and Read-Settings.ps1 set $doNotSignApp needs to be $signApp

### ISSUE THREAD

**Issue by eknraw** [microsoft/navcontainerhelper#1393]
**Describe the issue**
The businesscentralapps Helloworld and Helloworld.AppSource don't have functionaing certificate signing. 

setting.json and Read-Settings.json set a $doNoSignApp variable but the DevOps-Pipeline.ps1 is looking for a variable called $signApp

Referenced as $doNotSign here:

[settings.json](https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2Fsettings.json&version=GBmaster&line=11&lineEnd=11&lineStartColumn=5&lineEndColumn=26&lineStyle=plain)

[Read-Settings.ps1](https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2FRead-Settings.ps1&version=GBmaster&line=52&lineEnd=52&lineStartColumn=177&lineEndColumn=192&lineStyle=plain)

$signApp here:

[Devops-Pipeline.ps1](https://dev.azure.com/businesscentralapps/HelloWorld.AppSource/_git/HelloWorld.AppSource?path=%2Fscripts%2FDevOps-Pipeline.ps1&version=GBmaster&line=29&lineEnd=29&lineStartColumn=1&lineEndColumn=42&lineStyle=plain
)

**Comment by freddydk** [comment]
Thanks

I changed this from signapp to donotsignapp as I wanted the default to be, that if a certificate was specified - the app is signed.
Then you should be able to specify for individual pipelines (nextmajor and nextminor) that these doesn't need signing as the artifact isn't stored.

**Comment by freddydk** [comment]
DevOps-Pipeline has been fixed.

**Comment by eknraw** [comment]
Thanks much!
