### ISSUE TITLE
HelloWorld Feature Request: Add $vaultname to settings.json

### ISSUE THREAD

**Issue by eknraw** [microsoft/navcontainerhelper#1395]
We have a need to have multiple Azure Vaults to pass in different licenses.  Would it be possible to add the vaultname to the settings.json file? 

[Local-DevEnv.ps1](https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2FLocal-DevEnv.ps1&version=GBmaster&line=20&lineEnd=20&lineStartColumn=1&lineEndColumn=30&lineStyle=plain)

Thanks!

**Comment by freddydk** [comment]
Sounds like a good idea - and use that form local-devenv and local-pipeline

**Comment by freddydk** [comment]
"vaultNameforLocal" is the settings name.
I am not using this in DevOps-Pipeline, because the devops-pipeline needs to be able to run on agents, which doesn't have access to my vault. In DevOps, the vault should be accessed by the pipeline definition in Azure f.ex.
