### ISSUE TITLE
Include a helpserver inside the Navsion Container

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#140]
I'm still using microsoft/dynamics-nav:2017-cu9, going soon to microsoft/dynamics-nav:2017-cu18.
Is there already an option to include a helpserver to the Navision container. 
When going to a helpserver at this moment it goes to localhost:49000, but it's not there.
Nor is this port exposed on the container.

**Comment by freddydk** [comment]
Unfortunately, the help server has a dependency on Windows Search, which cannot run in WindowsServerCore.

**Comment by Koubek** [comment]
@freddydk Respecting what we talked a few weeks ago about publishing the sources of the helper or eventually to have a possibility to publish it explicitly via an environmental parameter, is there any progress or did you reconsider it again and discarded this option? I think this would a really nice to have the help pages available even in the case you won't be able to search from the helper website (I confirmed that at least you can press F1 and navigate directly from NAV to a specific page).

I know that from the perspective of the new NAV (AL) and the new "Get Help" feature integrated using the VS Code AL plugin it is pointless but there are still a lot of developers working in C/SIDE and using Docker and IMO, this would help us very much.

**Comment by freddydk** [comment]
Good point Jakub, yes I have that on my list to look into - have just been caught up with other stuff over the last month.

**Comment by Koubek** [comment]
I can imagine... Is there any chance to help you somehow? I have one free week before going to CPH so I could help somehow.

**Comment by freddydk** [comment]
Thanks for the very kind offer Jakub - I am in the US this week and will definitely see if there is anything I can offload (anything that doesn't require you to be on our corporate network).
See you
