### ISSUE TITLE
Helloworld Possible Feature Request - Relative BCContainerhelper

### ISSUE THREAD

**Issue by eknraw** [microsoft/navcontainerhelper#1403]
I've been adding the below block of code below the Install-BCContainerHelper.ps1 in the Local-DevEnv.ps1 and DevOps-Pipeline.ps1 scripts to pick up a local copy of BCContainerhelper that's been added to the /Scripts directory.  

The goal being: 
1.  If a project has an edge case they can customize the scripts without additional infrastructure
2.  Project can temporarily work around temporary issues with bccontainerhelper (ie. timestamp server is down)
3.  The entire solution including scripts should be "buildable" on clone given either 1 or 2

Would it be possible to include a check for a relative path location for the scripts? 

```
Write-Host "Use bcContainerHelper Version: $bcContainerHelperVersion"
. (Join-Path $PSScriptRoot "Install-BcContainerHelper.ps1") -bcContainerHelperVersion $bcContainerHelperVersion

# Start
$modulePath = Join-Path $PSScriptRoot "navcontainerhelper\BCContainerHelper.psm1"
if (Test-Path $modulePath) {
    Write-Host "Loaded BcContainerHelper at path: $modulePath"
    Import-Module $modulePath -DisableNameChecking
}
# End
```

**Comment by freddydk** [comment]
In the latest versions of the script (here: https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2FInstall-BcContainerHelper.ps1)
You will find this:
```
    $bcContainerHelperVersion = $bcContainerHelperVersion.Replace('{HOME}',$HOME.TrimEnd('\'))
    if ($bcContainerHelperVersion -like "?:\*") {
        if (Test-Path $bcContainerHelperVersion) {
            $bch = Get-Item (Join-Path $bcContainerHelperVersion '*ContainerHelper.ps1')
            if ($bch) {
                Write-Host "Using $bch"
                . "$bch"
                return
            }
        }
        $bcContainerHelperVersion = "https://github.com/microsoft/navcontainerhelper/archive/dev.zip"
    }
```
so if you set the bccontainerhelperversion to a path (possibly with {HOME}) then it will indeed import containerhelper from there.

**Comment by eknraw** [comment]
That could work but I was looking to avoid having to set bccontainerhelper in the settings as this would be a different fixed path for one developer to another and when it runs on our build server.   

I'd just want it to find a folder called navcontainerhelper and use that version: 
/Scripts/ <- default behavior will use installed module on system
/Scripts/navcontainerhelper/ <- if found now use this version

Perhaps if there were a way to run a custom script after settings were read then I could customize a script to alter $bcContainerHelperVersion.  Similar to myScripts in bccontainerhelper?   This would probably be the better solution for me as I'm also running a custom script to override the InstallApps variable.

**Comment by freddydk** [comment]
I think it is totally fine to override the Install-BcContainerHelper and not use the one I have provided.
In the end - you could replace that with a script with a few lines that does what you need.

**Comment by eknraw** [comment]
Yep, which is what I am doing.  I am trying to reduce or eliminate the amount of rebasing I have to do on top of your Helloworld project. :)

I have two "hooks" essentially now that I will maintain in your code, after the Read-Settings.ps1 and then right after the Run-AlPipeline command.

**Comment by freddydk** [comment]
Thanks - I will consider if I can make these as "hooks" - I also have a project, where I have a change (which I frequently override)
You might have given me a good idea here.

**Comment by eknraw** [comment]
I have an internal "Helloworld" and use yours as a remote that I rebase my repo onto and then push up to my internal git remote.  I consider your work here to be the "standard" in terms of build scripts so I would like as much of my customizations to be removed.

I think a "hook" after the settings are read and then another after the Run-ALPipeline would take care of everything I'd want at the moment.  I can then run a custom script to set $bcContainerHelperVersion.    

After the container is created locally we also do things like load fonts and then import a rapid start.  

Thanks for all the work on this!

**Comment by freddydk** [comment]
Due to the outage of PS Gallery and some performance enhancements, I have modified the Install-BcContainerHelper and don't support the files based dependency anymore. I am still considering how I can make hooks for custom stuff.

**Comment by freddydk** [comment]
Due to a bug in Azure DevOps, the helloworld project might be inaccessible.
I have created a copy here: https://github.com/microsoft/BusinessCentralHelloWorld
and https://github.com/microsoft/BusinessCentralHelloWorld.AppSource

**Comment by freddydk** [comment]
I have added the idea of hooks to my list of things to add.
