### ISSUE TITLE
Request: Run-AlPipeline: custom script to copy files into container

### ISSUE THREAD

**Issue by ahenkel** [microsoft/navcontainerhelper#1406]
I am looking for a way to copy custom *.dll into the container before compile the app using run-alpipeline command.
The new command is great but now i am missing the a way to copy custom files into the container. Can you add additional parameter to add a script that executes between new-container command and compile app command?

**Comment by freddydk** [comment]
Run-AlPipeline is not for all.
It is designed primarily for PTEs and AppSource Apps.
but...
You can override the NewBcContainer scriptblock and issue your own New-BcContainer with the parameters and add a share or a script.
