### ISSUE TITLE
Suggestion:  Add shortcut for the Containers Extension folder in BCContainerHelper

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1408]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
One thing I find I do all the time is having to copy files to the "MY" folder in C:\ProgramData\BCContainerHelper\Extension\<containerName> folder and navigating down that chain is always a pain.  It is a lot of clicks.  It is often hidden because ProgramData is normally hidden, so it is extra work to get to it.

**SUGGESTION:**
It would be handy to have a shortcut created for this folder just like is created for the Web Client, PowerShell, Command Prompt.

**Comment by freddydk** [comment]
I suggest that you manually create a shortcut to the extensions folder, then you have all container folders handy - and that one is easier to find.
I have already gotten feedback that there are too many shortcuts:-)
