### ISSUE TITLE
Running the Windows Powershell ISE Command

### ISSUE THREAD

**Issue by armela1981** [Microsoft/navcontainerhelper#141]
I am running the following command

install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'MyBizCentralApp'
$navdockerimage = 'microsoft/bcsandbox:12.0.22269.0-us'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

and getting following error. Any ideas ???

9c2638817a57: Waiting
cd9ca9ec3996: Waiting
docker : image operating system "windows" cannot be used on this platform
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.8.5\ContainerHandling\New-NavContainer.ps1:157 char:9
+         docker pull $imageName
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (image operating...n this platform:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

PS C:\Windows\system32>

**Comment by freddydk** [comment]
Sounds like you are running into item no 1 in the troubleshooting list:
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

**Comment by armela1981** [comment]
Thank you for all the info.
That helped.
Now I am running into another issue and I am hoping you can help.

So I was able to run the NAV on Docker and all the shortcuts created on the desktop.
Now I am the following website with instructions

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-get-started-container-sandbox

and I am at the part of setting up visual studio code.
I ran through the steps but there seems to be an error with the Launch.json.

I looks like this

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Your own server",
            "type": "al",
            "request": "launch",
            "server": "http://MyBizCentralApp",
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 22
        },
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://MyBizCentralApp",
            "serverInstance": "NAV"
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page"
        }
    ]
}

This can’t connect to the new database I just loaded via docker.
Any ideas ?
Armela Kamenica
Direct: 224-345-2021   | Fax: 847-590-0912
Cell – 847-912-6938
armela@solsyst.com<mailto:armela@solsyst.com> | www.solsyst.com<http://www.solsyst.com/>
[solsystemailfooter]

**Comment by richardrobberse** [comment]
Why do you have two configurations in your launch.json with the same data?
Please try to remove one of the configurations.

**Comment by armela1981** [comment]
Not sure how I did that.

Started a new project  and here is what I have now

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Your own server",
            "type": "al",
            "request": "launch",
            "server": "http://MyBizCentralApp",
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 22
        }
          ]
}

I think I am having an issue connection AL to the BC database I created vis Shell ISE and Docker.

When I am in Visual studio and select AL GO, I get a message to select my own database on the local server and asks me for user name and password.
I am using the one I got from the Microsoft  subscription but that does not work.

Any ideas ???


Armela Kamenica
Direct: 224-345-2021   | Fax: 847-590-0912
Cell – 847-912-6938
armela@solsyst.com<mailto:armela@solsyst.com> | www.solsyst.com<http://www.solsyst.com/>
[solsystemailfooter]

**Comment by armela1981** [comment]
I have another question for you guys.
So  I Used Powershell ISE  to run the PS1 file and It created shortcuts on my desktop for NAV Cside and all.

When trying to  open MyBizCentral Cside I get the following . What do I enter at this point ? Selecting OK gives me an error.  I think that may be related to my auth error when using Visual Studio.

Thanks


[cid:image001.png@01D3F67A.D0677340]

Armela Kamenica
Direct: 224-345-2021   | Fax: 847-590-0912
Cell – 847-912-6938
armela@solsyst.com<mailto:armela@solsyst.com> | www.solsyst.com<http://www.solsyst.com/>
[solsystemailfooter]

**Comment by richardrobberse** [comment]
I can't see the screenshot you've provided, probably because you've replied by email.
When using NavUserPassword authentication you're responsible for providing the username and pw, so when you created the container you were prompted to enter a username and a password.

To me, it sounds like you don't remember the username and password so please recreate the container.

**Comment by armela1981** [comment]
Ok,
I tried to recreate.
Here is the error I get now on the Powershell ISE  . What am I doing wrong ?? SO sorry to bother you with all these questions.

Creating container MyBizCentralApp from image microsoft/bcsandbox:12.0.22269.0-us
adf24062488cf74367033c5590da71f190b2f0c86073b409abbe976a4a2fa7e5

docker.exe: Error response from daemon: container adf24062488cf74367033c5590da71f190b2f0c86073b409abbe976a4a2fa7e5 encountered an erro
r during Start: failure in a Windows system call: The operation timed out because a response was not received from the Virtual Machine
hosting the Container. (0xc0370109).

Commandline: docker run --name MyBizCentralApp --hostname MyBizCentralApp --env auth=Windows --env username="armela" --env ExitOnError
=N --env locale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelp
er:C:\ProgramData\NavContainerHelper" --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\my:C:\Run\my" --restart u
nless-stopped --memory 4G --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\Extensions\MyBizCentralApp\Program Files:C:\navpf
iles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AHQAagA1AFYAcA
BrAEoAawAxAHkAZgBSAFYARQAvAE4AagB4AEkAQwB1AEEAPQA9AHwAYwAwADEAYgBkAGUAYgA4ADcANgAwAGEAYgBkADkAZQAwADAAMQAyADAAMgBlADUAMQA4ADYANwA1AGUA
YQA3ADkAZgAzADAAMgBjAGYAMgAwADkAOQAxADIANABjADkAMQA1ADEAYgA2AGEAYwAyADEAMwBiAGYAMgA2AGEAYgA= --env passwordKeyFile="c:\run\my\aes.key"
--env removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/bcsandbox:12.0.22269.0-us
Downloading C:\Users\armela\AppData\Local\Temp\CreateTestUsers.fob
New-PSSession : The input ContainerId adf24062488cf74367033c5590da71f190b2f0c86073b409abbe976a4a2fa7e5 does not exist, or the
corresponding container is not running.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.8.5\ContainerHandling\Get-NavContainerSession.ps1:37 char:24
+ ...  $session = New-PSSession -ContainerId $containerId -RunAsAdministrat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-PSSession], PSInvalidOperationException
    + FullyQualifiedErrorId : CreateRemoteRunspaceForContainerFailed,Microsoft.PowerShell.Commands.NewPSSessionCommand

PS C:\Windows\system32>


Armela Kamenica
Direct: 224-345-2021   | Fax: 847-590-0912
Cell – 847-912-6938
armela@solsyst.com<mailto:armela@solsyst.com> | www.solsyst.com<http://www.solsyst.com/>
[solsystemailfooter]

**Comment by armela1981** [comment]
Ok, I was able to re-run the “Create Container “.
I had a certificate issue.
I still can’t access the newly created databases on my desktop via just clicking on them (RTC or DEV) or via Visual Studio.

Any ideas ?


Armela Kamenica
Direct: 224-345-2021   | Fax: 847-590-0912
Cell – 847-912-6938
armela@solsyst.com<mailto:armela@solsyst.com> | www.solsyst.com<http://www.solsyst.com/>
[solsystemailfooter]
