### ISSUE TITLE
Creating NAV Container

### ISSUE THREAD

**Issue by TestUserBC** [microsoft/navcontainerhelper#1411]
I'm unable to create a new nav container as it is giving an error to run import-module navcontainer helper command

![image](https://user-images.githubusercontent.com/73337962/97484407-b947db80-197e-11eb-9044-70dbbf2c3d6e.png)

After executing the command, another error comes up. 

![image](https://user-images.githubusercontent.com/73337962/97484631-fa3ff000-197e-11eb-873e-fd9689edf7ef.png)

I have carefully installed docker as well as pull up the bc image on my machine having win 10 1909 version. And, i'm fullfilling all the necessary requirements needed for development.

Also, I have checked the navcontainerhelper entire directory whether such file is present or not, but there's no file with the name "Replace- DependenciesinAppFile" exist.

Please help in resolving the issue with the appropriate solution.

**Comment by freddydk** [comment]
```
uninstall-module navcontainerhelper -allversions
install-module bccontainerhelper -force
```

**Comment by arjunanand7** [comment]
Nothing Happend....Issue still exist.

**Comment by freddydk** [comment]
If you remove
c:\program files\windowspowershell\modules\navcontainerhelper
and
c:\program files\windowspowershell\modules\bccontainerhelper

and restart powershell and/or computer

and then install bccontainerhelper 

then something must be different (as the above things refers to navcontainerhelper)

**Comment by arjunanand7** [comment]
I did as you directed, but no other response received

**Comment by freddydk** [comment]
Are you saying that after removing the navcontainerhelper - your machine still says:
![image](https://user-images.githubusercontent.com/10775043/97559674-0909bf80-19de-11eb-9a0b-e13381d47fd4.png)

**Comment by arjunanand7** [comment]
It's showing same error for BC container helper

![image](https://user-images.githubusercontent.com/73337962/97564597-d0cca600-1a0a-11eb-9a72-eb873bede084.png)

**Comment by arjunanand7** [comment]
After executing this command "install-module BcContainerhelper -force", when execute
"import-module BcContainerHelper "  the error shows up
![image](https://user-images.githubusercontent.com/73337962/97565065-99aac480-1a0b-11eb-85ad-bad9f43ed036.png)

**Comment by freddydk** [comment]
Seems like your machine for some reason doesn't like that file????
There are a lot of successful downloads and executions of the module, meaning that the module is not the problem. My assumption is that it is something on your machine or something happened during the download.

You could check anti-virus logs to see whether something has removed the file?

or you could grab the file manually and see if you get an error: The file is included: https://www.powershellgallery.com/packages/BcContainerHelper/1.0.12/Content/AppHandling%5CReplace-DependenciesInAppFile.ps1

**Comment by arjunanand7** [comment]
could you help in storing this file?
https://www.powershellgallery.com/packages/BcContainerHelper/1.0.12/Content/AppHandling%5CReplace-DependenciesInAppFile.ps1

**Comment by freddydk** [comment]
Copy the content and Paste it into PowerShell ISE and save in the path given in the error above.

**Comment by TestUserBC** [comment]
I did it but system automatically delete the file from the path. I really don't know what's happening

**Comment by freddydk** [comment]
what antivirus are you using?
it is likely stuff like this seeing this file as a false positive, not something I can fix

**Comment by freddydk** [comment]
I will close the issue - this is not anything I can help with, sorry.
