### ISSUE TITLE
Setup Test Users

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/navcontainerhelper#1415]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When I run Setup-BcContainerTestUsers, I get the following error "Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols for the requested app Any by Microsoft 17.0.0.0 could not be found 
in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing"

**Scripts used to create container and cause the issue**
    New-BCContainer `
    -doNotCheckHealth `
    -updateHosts `
    -containerName $ContainerName `
    -artifactUrl $artifactUrl `
    -auth NavUserPassword `
    -Credential $credential `
    -memoryLimit 8g `
    -licenseFile "C:\License\BCLIC.flf" `
    -assignPremiumPlan `
    -accept_eula `
    -accept_outdated

**Full output of scripts**
Copy from container SWCT-US (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\BcContainerHelper\Extensions\SWCT-US\_Microsoft_System Application Tes
t Library.app
Publishing C:\ProgramData\BcContainerHelper\Extensions\SWCT-US\_Microsoft_System Application Test Library.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols for the requested app Any by Microsoft 17.0.0.0 could not be found in 
the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.0.0.0' could not be loaded. Symbols for the requested app Any by Microsoft 17.0.0.0 could not be found 
in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\1.0.10\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : f9df319be0a280bb28e1678d23896bb3e2196655b9d6f63bea3cd2d1f3f5d0c7

**Screenshots**

**Additional context**
This has been happening for a while

**Comment by freddydk** [comment]
Setup-BcContainerTestUsers has a dependency on the test framework.
I have added a line to check and import the test framework if missing in the function.

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 1.0.13-preview256
