### ISSUE TITLE
Confusing parameter $credential on Run-TestsInNavContainer 

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1416]
Hey @freddydk, 

I have container which is configured with NavUserNamePassword authentificaion, and linked with external database server. 
When running tests with **Run-TestsInNavContainer**, I pass credential parameters for my user (the same user i open Web/RTC client)

`Run-TestsInBcContainer -containerName develop -companyName "AutoTest" -credential (Get-Credential)`

It fails while trying to import import test page using the user credentials, not sql credentials

![image](https://user-images.githubusercontent.com/16342128/97695133-daeeb300-1aa3-11eb-82c4-2023763f81c7.png)

If I pass my sqlcredentials instead, all works fine (not sure actually why, since i don't have SQL user configured as NAV user)

I believe, you should have two different parameters in Run-TestsInNavContainer: sqlcredetnial, and credential to differentiate from user who logins to application, and user who imports objects.

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 1.0.13-preview256
