### ISSUE TITLE
Export-NavContainerObjects WARNING: Attempted to divide by zero.

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/navcontainerhelper#142]
Hello I'm trying to export BC native objects to the default shared folder (using Export-NavContainerObjects) and I'm getting a following warning: Attempted to divide by zero

Previously I was able to export. Any idea?

**Comment by freddydk** [comment]
It would help if you write what exact command you are trying to execute (all parameters)

**Comment by freddydk** [comment]
And what is the output of that function?

**Comment by martinhocosta88** [comment]
Nothing exported on the folder. On Console I'm just getting the following:

```
Export Objects with filter 'modified=Yes' (new syntax) to C:\ProgramData\NavContainerHelper\Extensions\SoftstoreBCW1\my\objects.txt (container path)
Split C:\ProgramData\NavContainerHelper\Extensions\SoftstoreBCW1\my\objects.txt to C:\ProgramData\NavContainerHelper\Extensions\SoftstoreBCW1\my (container paths)
WARNING: Attempted to divide by zero.
```

**Comment by freddydk** [comment]
The default filter is "modified=Yes"
Do you have any modified objects in the database?
Probably not.
The export goes fine, split apparently gives you a warning.
try to add -filter "" to your export.
The reason for this is that new-navcontainer already exports all objects if you -includecside, Export-NavContainerObjects then defaults to export what has been modified.
