### ISSUE TITLE
Suggestion: when using includePerformanceToolkit parameter also add the "Performance Toolkit Tests" app

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#1426]
When I am adding the Performance Test toolkit to my container using **includePerformanceToolkit** parameter I would have expected that the _Performance Toolkit Test_ app was also added.

So I would like to suggest to get that included.

**Comment by freddydk** [comment]
Today, you need to add -includeTestToolkit and -includeTestFrameworkOnly for that to happen (due to dependencies)
Next version, this will happen automatically.

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 1.0.13-preview256

**Comment by lvanvugt** [comment]
@freddydk, I just build a new container base on latest BC17 build (/onprem/17.1.18256.18792/w1) with `-includePerformanceToolkit`.
It does now want to install the examples, but throws and error:

```
Copy from container BC17w1UserPW (C:\Applications\TestFramework\PerformanceToolkit\Microsoft_Performance Toolkit Samples.app) to C:\P
rogramData\BcContainerHelper\Extensions\BC17w1UserPW\_Microsoft_Performance Toolkit Samples.app
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC17w1UserPW\_Microsoft_Performance Toolkit Samples.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Performance Toolkit', and a version compatible with '17.1.0.0' could not be
 loaded. Symbols for the requested app Performance Toolkit by Microsoft 17.1.0.0 could not be found in the database
src/BCPTCreatePOWithNLines.Codeunit.al(15,26): error AL0185: Codeunit 'BCPT Test Context' is missing
src/BCPTCreatePOWithNLines.Codeunit.al(43,62): error AL0185: Codeunit 'BCPT Test Context' is missing
src/BCPTCreatePOWithNLines.Codeunit.al(1,58): error AL0185: Interface '"BCPT Test Param. Provider"' is missing
src/BCPTCreateSOWithNLines.Codeunit.al(15,26): error AL0185: Codeunit 'BCPT Test Context' is missing
src/BCPTCreateSOWithNLines.Codeunit.al(43,59): error AL0185: Codeunit 'BCPT Test Context' is missing
src/BCPTCreateSOWithNLines.Codeunit.al(1,58): error AL0185: Interface '"BCPT Test Param. Provider"' is missing
src/BCPTCreateSQWithNLines.Codeunit.al(15,26): error AL0185: Codeunit 'BCPT Test Context' is missing
src/TestCodeunitsWithParams.Enum.al(1,59): error AL0247: The target Enum "BCPT Test Param. Enum" for the extension object is not foun
d
src/BCPTCreateSQWithNLines.Codeunit.al(42,59): error AL0185: Codeunit 'BCPT Test Context' is missing
src/BCPTCreateSQWithNLines.Codeunit.al(1,58): error AL0185: Interface '"BCPT Test Param. Provider"' is missing
at <ScriptBlock>, <No file>: line 12
```
Want me to log a new issue for this?

**Comment by freddydk** [comment]
This is because they added the samples to the me folder as the toolkit and the code locating the apps to install ends up installing the samples before the toolkit.
Will fix this in the next bccontainerhelper preview (in a few hours)
btw - I will do it like this:
if you add -includeTestFrameWorkOnly, I will NOT include the samples.
so if you want the perf test samples and NOT all the tests, you should not includeTestFrameWorkOnly - you should includeTestLibrariesOnly.
Sorry, but I didn't want another switch and I really didn't want to force people to install all tests in order to get the perf test samples - it is a tradeoff.

**Comment by freddydk** [comment]
If you are creating a cached image - this will also fail - the same issue is in the generic image.
You can add https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/HelperFunctions.ps1 to -myscripts on new-bcimage - that will fix the bug, but you cannot fix the bug in new-bccontainer with -imagename AND -artifacturl until I have generated a fix of the generic image.
