### ISSUE TITLE
Fail pipeline on failed tests

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/navcontainerhelper#1427]
I am running the command successfully on GitLab, but as far as I can see a GitLab pipeline only failes if one of the command raises an error. 

Would it be possible to raise an error if at least one test failed? 
Maybe controllable via switch?

**Comment by freddydk** [comment]
Run-TestsInBcContainer has a switch called -returnTrueIfAllPassed
Add that - and if it returns false - throw.
Will that work?

**Comment by StefanMaron** [comment]
Sorry, forgot to write that I use the "Run-AlPipeline" command. Does something like this exists with this command too?

**Comment by freddydk** [comment]
Nope - I should add a parameter like -azureDevOps called -gitlab to set these things.

**Comment by freddydk** [comment]
and -githubActions

**Comment by freddydk** [comment]
Is it only Run-Tests you are running into at this time?

**Comment by StefanMaron** [comment]
Cant tell for sure. The rest of the pipeline works for now.

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 1.0.13-preview256
