### ISSUE TITLE
October 20, 2020—KB4580390 - Hyper-V only

### ISSUE THREAD

**Issue by TGosselink** [microsoft/navcontainerhelper#1428]
Sinds october 20 this year, KB4580390 has been released for Windows Server 2019
With that, the buildnr is increased to 1554.

Result: BC OS is build 1339 and OS build is 1554
Therefore it can now only run in Hyper-V mode and no longer in Process isolation

Platform: 16.0.15884.15941
Generic Tag: 0.1.0.24
Container OS Version: 10.0.17763.1518 (ltsc2019)
Host OS Version: 10.0.17763.1554 (ltsc2019)
Using hyperv isolation

Previously, before the update:
Generic Tag: 0.1.0.24
Container OS Version: 10.0.17763.1339 (ltsc2019)
Host OS Version: 10.0.17763.1339 (ltsc2019)
Using process isolation

Update:
Removed KB4580390 and OS returns to: 10.0.17763.1518
I added the Process isolation parameter to force process isolation always.

**Comment by freddydk** [comment]
just add -isolation process - it just defaults to hyperv

**Comment by freddydk** [comment]
Will check the generic image and update.

**Comment by freddydk** [comment]
There is nothing really I can do about this. Windows team hasn't shipped an updated container OS. These are the shipped versions of Windows Server Core:
```
10.0.19042.572
10.0.19041.572
10.0.19041.508
10.0.19041.450
10.0.19041.388
10.0.19041.329
10.0.19041.264
10.0.17763.1518
10.0.17763.1457
10.0.17763.1397
10.0.17763.1339
10.0.17763.1282
10.0.17763.1217
10.0.17763.1158
10.0.17763.1098
10.0.17763.1040
10.0.17763.1039
10.0.17763.973
10.0.17763.914
10.0.17763.864
10.0.17763.805
10.0.17763.737
10.0.17763.678
10.0.17763.615
10.0.17763.557
10.0.17763.504
10.0.17763.503
10.0.17763.437
10.0.17763.379
10.0.17763.316
```

Only option really is that you add -isolation process (you can add that to bccontainerhelper.config.json to always use that).
