### ISSUE TITLE
Parameter Desktop-Shortcut <Container> CSIDE not correct

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#143]
I've managed to make an external SQL-Container with the use of Windows Authentication. But I've noticed that this combination is not supported with the creation of the desktop Shortcut CSIDE.
The code below is from the New-NavContainer function. As I understand, as soon as I use databaseCredentials, is assumes it also uses databaseauthentication. I presume you must have had a sittuation where this check was necessary.
My change request is to modify the code, to support my configuration.

function New-NavContainer
        if ($databaseCredential -ne $null -and $databaseCredential -ne [System.Management.Automation.PSCredential]::Empty) {
            $ntauth="0"
        } elseif ($auth -eq "Windows") {
            $ntauth="1"
        } else {
            $ntauth="0"
        }
        if ($databaseInstance) { $databaseServer += "\$databaseInstance" }
        $csideParameters = "servername=$databaseServer, Database=$databaseName, ntauthentication=$ntauth"

**Comment by freddydk** [comment]
Sounds like a good idea, I will include that in the next update (scheduled next week)

**Comment by mheijkant** [comment]
Great, thanks.

**Comment by freddydk** [comment]
I think I misunderstood your request.
Can you tell me how you want to modify the code?
The assumption is, that if you use databaseCredentials, then you are using username/password auth.
How are you creating the container where this is not the case???

**Comment by mheijkant** [comment]
These parameters say:
 
.Parameter databaseInstance
  Name of database instance when using external SQL Server (omit if using database inside the container)
.Parameter databaseName
  Name of database to connect to when using external SQL Server (omit if using database inside the container)
 .Parameter databaseName
  Name of database to connect to when using external SQL Server (omit if using database inside the container)
 .Parameter databaseCredential
  Credentials for the database connection when using external SQL Server (omit if using database inside the container)

I'm using an external database. As I understand, the $databaseCredential is used for the Navision Service to make a connection to the SQL-Server and Database.
But i'm also using Windows Auth, for my users to connect to Navision Container.

But the script code assumes database Auth is used (ntauthentication=$ntauth")
So I expected the Desktop shortcut to be ntauthentication=1 instead of ntauthentication=0"

**Comment by freddydk** [comment]
The Classic client (CSIDE) connects to the database directly - meaning ntauth=0 - it doesn't know anything about the NAV users.

**Comment by mheijkant** [comment]
true, but for me that doesn't work. When I use databaseauth only, I'm unable to modify and compile tables in the developer environment. I think I read this somewhere or even asked a question about it on this blog, that I had to use windows authentication. After configuring and using Windows authentication with gmsa, I was able to modify the tables. So I now have windows authentication configured to start my RTC client, WebClient and Developer environment. Only thing laking, although it is a minor bug for me, is the ntauthentication=1 parameter in the developer environment desktop icon. I expected that if you use parameter auth=windows, it is a general setting for the RTC web client en dev environment.
If that isn't the idea behind the usage of this parameter, i won't be disappointed.

**Comment by freddydk** [comment]
Are you saying that the shortcut works if you change ntauth=1 ?

**Comment by mheijkant** [comment]
That's correct.

**Comment by freddydk** [comment]
I have removed the check, since using databasecredentials from the servicetier doesn't imply database auth from CSIDE.

**Comment by freddydk** [comment]
Included in version 0.3.1.0
