### ISSUE TITLE
Run-ALPipeline take long time in DevOps CI/CD

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/navcontainerhelper#1431]
First of all, I would like to thanks you about the great work you do.

I rise that issue, but not sure that is a BCContainerHelper issue. May be just a DevOps lack of Knowledge.

**Context**: International app for AppSource. (for all countries available for BC)
In that context, MS ask to test the app in all localizations.
As it take more than 20min for one country, and there are more than 20 countries to test, this takes more than 6 Hours (Max time for a MS Hosted Agent Job). I tried on a Host Agent, put it seems than the limit for a job is 1 Hour.

Do you have any idea, advice or workaround for that ?

**Comment by freddydk** [comment]
https://github.com/microsoft/BusinessCentralHelloWorld.AppSource/blob/master/scripts/CI.yml

See timeoutinminutes

**Comment by YvesDesrumaux** [comment]
Thanks a lot ! This is what I needed.
