### ISSUE TITLE
Run-AIPipline How to override -NewBcContainer

### ISSUE THREAD

**Issue by tben2010** [microsoft/navcontainerhelper#1432]
Hello Freddy, I have a question about the syntax, how to override -NewBcContainer?

this is my attempt

$ParamNewBCContainer = @{
    "accept_eula" = $true
    "containerName" = $containerName
    "imageName" = $imageName
    "artifactUrl" = $artifactUrl
    "useGenericImage" = $useGenericImage
    "Credential" = $credential
    "auth" = 'UserPassword'
    "updateHosts" = $true
    "licenseFile" = $licenseFile
    "EnableTaskScheduler" = $enableTaskScheduler
    "AssignPremiumPlan" = $assignPremiumPlan
    "MemoryLimit" = $memoryLimit
    "additionalParameters" = @("--volume ""$($baseFolder):c:\sources""")
    "bakFile" = $bakFile
}

Run-AlPipeline
    -pipelineName $pipelineName
    -containerName $containerName
    -imageName $imageName
    -artifact $artifact.replace('{INSIDERSASTOKEN}',$insiderSasToken)
    -memoryLimit $memoryLimit
    -baseFolder $baseFolder
    -licenseFile $licenseFile
    -installApps $installApps
    -appFolders $appFolders
    -testFolders $testFolders
    -testResultsFile $testResultsFile
    -testResultsFormat 'JUnit'
    -installTestFramework:$installTestFramework
    -installTestLibraries:$installTestLibraries
    -installPerformanceToolkit:$installPerformanceToolkit
    -credential $credential
    -doNotRunTests
    -useDevEndpoint
    -updateLaunchJson "Local Sandbox"
    -keepContainer
     -NewBcContainer $ParamNewBCContainer

best regards

tben

**Comment by freddydk** [comment]
the -newbccontainer parameter is a scriptblock. Meaning that you override that with a scriptblock which is responsible for creating the container.
The default scriptblock is:

```
{
    Param([Hashtable]$parameters)
    New-BcContainer @parameters
    Invoke-ScriptInBcContainer $parameters.ContainerName -scriptblock {
        $progressPreference = 'SilentlyContinue'
    }
}
```
so basically, override with another scriptblock and add or replace the parameters you need.

**Comment by tben2010** [comment]
This is exactly my problem, I do not understand how to do it. 
For example to add the parameter bakFile

**Comment by freddydk** [comment]
I think it would be something like this:
```
Run-AlPipeline `
<other parameters> `
    -NewBcContainer {
        Param([Hashtable]$parameters)
        $parameters += @{ "bakfile" = "c:\temp\bakfile.bak" }
        New-BcContainer @parameters
        Invoke-ScriptInBcContainer $parameters.ContainerName -scriptblock {
            $progressPreference = 'SilentlyContinue'
        }
    }
```

**Comment by tben2010** [comment]
Super thanks, that's exactly what I was missing.
It works
