### ISSUE TITLE
VS Code launch.json settings to connect to traefik-based container

### ISSUE THREAD

**Issue by miraquel** [microsoft/navcontainerhelper#1434]
I have started a container using -useTraefik, now I want to publish the extension from outside the VM from VS Code, which does not work like the address doesn't found the endpoint.

I'm trying to resolve the issue by following the #802 issue. but it also doesn't work.

So I try to check the docker log when creating the container, I see the standard URL **https://servername/instancename:7049/dev/metadata** got replaced by **https://servername/instancenamedev/dev/metadata**, and then I try to enter the URL to a browser. the result is the browser returns a JSON about the metadata of the development environment.

But when I use the URL to publish an extension on VS Code, the URL changed to **https://servername:7049/instancenamedev/dev/metadata** and cause an error because the endpoint was not found.

Trying to change the port config to 0 (assuming it would leave the port empty) and 80 (assuming it using the standard port so it would leave the port empty). but it doesn't work.

**Comment by freddydk** [comment]
port should be 443 for https
You should be able to see the url's on the landing page if this was created by aka.ms/getbc

**Comment by miraquel** [comment]
Thanks, that resolve the issue about the address.

but now the error message is about the certificate, although the certificate that I'm using is right (got the certificate from C:\ProgramData\NavContainerHelper\Extensions\instancename).

`[2020-11-05 23:00:10.96] Error: The SSL connection could not be established, see inner exception.
The remote certificate is invalid according to the validation procedure.`

**Comment by freddydk** [comment]
It is impossible for me to help without seeing what you have done.
My recommendation when using traefik is to use letsencrypt, which removes the self-signed problems.

**Comment by miraquel** [comment]
Clear enough for me, I'm trying to use let's encrypt for now, I will open another issue if let's encrypt still doesn't work.
