### ISSUE TITLE
publish defective app in pipeline: non-descriptive error raised

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/navcontainerhelper#1436]
**Describe the issue**
When installing apps in a pipeline with one of those defects described, the pipeline terminates with an non-descriptive error:

```
WARNING: UnhandledErrorMessage
The socket connection was aborted. This could be caused by an error processing your message or a receive timeout being exceeded by the remote host, or an underlying network resource issue. Local socket timeout was '10675199.02:48:05.4775807'.
at <ScriptBlock>, <No file>: line 39
```

The actual error can be one of those two:

- app extends a table and uses a field id that has already been defined by another app
- app extends an enum with an id, that has been already defined by another app

In both cases publishing from VS Code surfaces the correct error.

**Expected behaviour**

The actual publishing error makes it to the pipeline output.

**Comment by freddydk** [comment]
In the next version I have fixed the issue when publishing via DevEndpoint - that it always says: Unprocessibly Entity - now it will display the error reason. I think however that in this case you are not using dev endpoint.
I cannot repro the issue. When I try, I get:

```
Publish-BcContainerApp -containerName bingmaps-ci -appFile "C:\Users\freddyk\Documents\AL\ALProject8\Default publisher3_ALProject83_1.0.0.0.app" -install -sync -skipVerification
Publishing C:\ProgramData\BcContainerHelper\Extensions\bingmaps-ci\_Default publisher3_ALProject83_1.0.0.0.app
Synchronizing ALProject83 on tenant default
Installing ALProject83 on tenant default
The field ID '50100' can only appear once in the table 'Customer'. The field is declared in multiple apps with IDs: '37a86068-0bde-4261-bf81-23b5f47b85af', '27a86068-0bde-4261-bf81-
23b5f47b85af'.
```

which is very descriptive.
If you still have the issue, please provide a repro scenario - maybe two .app files I can try to publish and see the error (including artifact url used).

Thanks

**Comment by RafaelKoch** [comment]
Thanks for taking a look! 
Between me reporting this and You investigating we have had a CU update and a major update of the al compiler - maybe that changed it.
I will close this issue and open a new one IF this ever resurfaces.
