### ISSUE TITLE
Impossible to start a container

### ISSUE THREAD

**Issue by mfferrari** [microsoft/navcontainerhelper#1440]
Hi, since some weeks, my containers become exited in few days and the instruction _docker start_ gives me this error:

docker : Error response from daemon: hcsshim::ActivateLayer - failed failed in Win32: The process cannot access the file because it is being used by another process. (0x20)

Containers are correctly created with this script:

```
install-module navcontainerhelper -Force

$artifactUrl = Get-BCArtifactUrl -country w1 -select Latest -type OnPrem
$containerName = "BCW1"
$navcredential = New-Object System.Management.Automation.PSCredential -argumentList "admin", (ConvertTo-SecureString -String "Admin123" -AsPlainText -Force)

New-BCContainer -accept_eula `
-containerName $containerName `
-Auth NavUserPassword `
-artifactUrl $artifactUrl `
-Credential $navcredential `
-assignPremiumPlan `
-updateHosts `
-includeAL
```

Please note that containers work successfully, but for just one or two days. Restarting computer or docker does not solve this issue.

Anyone having the same problem?

Thanks
Marco

**Comment by freddydk** [comment]
I would switch to BcContainerHelper - NavContainerHelper is no longer being maintained.
That probably won't fix the above issue though, but if you post the full output of creating one of the containers with BcContainerHelper i can get valuable information about your OS, Memory, Isolation and other things, which I can use to troubleshoot.

**Comment by mfferrari** [comment]
Hi, unfortunately by using bccontainerhelper the script does not work, this is the final error:

Digest: sha256:7b614d14f02892f20d4bec100681af9bbc7594bccbb7df915f9ef3279cf34536
Status: Downloaded newer image for mcr.microsoft.com/dynamicsnav:10.0.18363.1139-generic
mcr.microsoft.com/dynamicsnav:10.0.18363.1139-generic
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.1139-generic
Creating Container BCIT
Version: 17.1.18256.18474-it
Style: onprem
Platform: 17.0.18204.18458
Generic Tag: 0.1.0.24
Container OS Version: 10.0.18363.1139 (1909)
Host OS Version: 10.0.18363.1139 (1909)
Using locale it-IT
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Copy-Item : Impossibile trovare il percorso 'C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\updatehosts.ps1' perché non esiste.
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\New-NavContainer.ps1:1363 car:5
+     Copy-Item -Path (Join-Path $PSScriptRoot "updatehosts.ps1") -Dest ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...updatehosts.ps1:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by mfferrari** [comment]
In any case, by using NavContainerHelper, the output is this one:

PS C:\WINDOWS\system32> $artifactUrl = Get-BCArtifactUrl -country it -select Latest -type OnPrem
$containerName = "BCIT"
$navcredential = New-Object System.Management.Automation.PSCredential -argumentList "admin", (ConvertTo-SecureString -String "Admin123" -AsPlainText -Force)

New-BCContainer -accept_eula `
-containerName $containerName `
-Auth NavUserPassword `
-artifactUrl $artifactUrl `
-Credential $navcredential `
-assignPremiumPlan `
-updateHosts `
-includeAL
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.13
Docker Server Version is 19.03.13
Removing C:\ProgramData\NavContainerHelper\Extensions\BCIT
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.18363.1139-generic
Creating Container BCIT
Version: 17.1.18256.18474-it
Style: onprem
Platform: 17.0.18204.18458
Generic Tag: 0.1.0.24
Container OS Version: 10.0.18363.1139 (1909)
Host OS Version: 10.0.18363.1139 (1909)
Using locale it-IT
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\BCIT\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BCIT from image mcr.microsoft.com/dynamicsnav:10.0.18363.1139-generic
7470b6eb1db4fdf4047abbcd83e4921e980b1c293032382dadbab815396ec1af
Waiting for container BCIT to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.1.18256.18474/it
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\17.1.18256.18474\it\database\Demo Database NAV (17-0).bak
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 136 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.88 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.88 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.20.224.1 in container hosts file
Starting Container
Hostname is BCIT
PublicDnsName is BCIT
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 238A46CE1BCF566C7184883D56828621DB0B2B1C
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Assign Premium plan for ADMIN
Container IP Address: 172.20.226.111
Container Hostname  : BCIT
Container Dns Name  : BCIT
Web Client          : http://BCIT/BC/
Dev. Server         : http://BCIT
Dev. ServerInstance : BC
Setting BCIT to 172.20.226.111 in host hosts file

Files:
http://BCIT:8080/ALLanguage.vsix

Container Total Physical Memory is 15.8Gb
Container Free Physical Memory is 5.7Gb

Initialization took 53 seconds
Ready for connections!
Reading CustomSettings.config from BCIT
Creating Desktop Shortcuts for BCIT
Extracting C:\Applications\BaseApp\Source\Base Application.Source.zip
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\170\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\170\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath

**Comment by freddydk** [comment]
In the reply where you describe that you use bccontainerhelper: 
```
Copy-Item : Impossibile trovare il percorso 'C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\updatehosts.ps1' perché non esiste.
In C:\Program Files\WindowsPowerShell\Modules\**navcontainerhelper\0.7.0.26**\ContainerHandling\New-NavContainer.ps1:1363 car:5
```

That is not bccontainerhelper.
You would need to remove all containers and run

uninstall-module navcontainerhelper -allversions -force

restart powershell

install-module bccontainerhelper -force

and then try again.

BTW - did you try to use the IP number instead of the host name?

**Comment by mfferrari** [comment]
Hi, I removed the old navcontainerhelper but did not restarted PowerShell. Now I recreated a new container with the new module, and this is the output (I don't know how much time will last):

**Comment by freddydk** [comment]
ok, looks fine - report back here if the same happens again with the output from docker logs, thanks.

**Comment by mfferrari** [comment]
Unfortunately today my container has expired and, as before, it's impossible to start it manually. Attached you can see the error

![image](https://user-images.githubusercontent.com/57940590/99394467-34961080-28df-11eb-9074-24caa7865989.png)

Thanks for your help
Marco

**Comment by freddydk** [comment]
If you run WinVer.exe - what windows version do you have now? (did it update in the background)

**Comment by mfferrari** [comment]
This is the version, and the OS has the automatic update activated

![image](https://user-images.githubusercontent.com/57940590/99399362-db7dab00-28e5-11eb-9b63-481d2c038758.png)

**Comment by freddydk** [comment]
So in this case, you got a windows update between the time you created the container and the time you restart it - that is probably the reason (combined with 1909 - I don't see this behavior in Windows 10 2009)

You should try to recreate the container and see whether next time this happens also is because of a windows update.

**Comment by mfferrari** [comment]
That's what I've done, but everytime I have the same problem. In the past after a Windows update Docker stopped after reboot, but when I restarted it manually all the containers worked, so I cannot understand what's changed.
Thanks in any case.

**Comment by freddydk** [comment]
You would try to run your containers using hyperv isolation - then they are not as tightly connected to the host OS.
