### ISSUE TITLE
Get-BcContainerAppInfo - Same result with and without "tenant" specified

### ISSUE THREAD

**Issue by trylvis** [microsoft/navcontainerhelper#1442]
**Describe the issue**
Get-BcContainerAppInfo seem to not pass in the tenant name, as "Get-BcContainerAppInfo -containerName myContainer" and "Get-BcContainerAppInfo -containerName myContainer -Tenant default" returns exactly the same Apps.

So this seems like the "Get-NavAppInfo" command that is being run in the container itself, does not include the "tenant" parameter even if it´s specified in Get-BcContainerAppInfo.

This is resulting in always seeing the Published apps, whereas the excepted result when including tenant would be to see only the installed Apps.

**Scripts used to create container and cause the issue**

Container running image: mcr.microsoft.com/dynamicsnav:10.0.17763.1457-generic
BcContainerHelper version: 1.0.13
Steps to reproduce: Publish apps and install only some of them in the default tenant.

Some commands where you can see the number of Apps returned from various commands:

From inside the container (Enter-BcContainer):
```
(Get-NavAppInfo -ServerInstance BC).Count
94
(Get-NavAppInfo -ServerInstance BC -Tenant default).Count
65
```
From bccontainerhelper: 
```
(Get-BcContainerAppInfo -containerName myContainer).Count
94
(Get-BcContainerAppInfo -containerName myContainer -Tenant default).Count
94
```

"(Get-BcContainerAppInfo -containerName myContainer -Tenant default).Count" should return 65.

**Comment by freddydk** [comment]
You can always do:
```
Invoke-scriptinBcContainer mycontainer -scriptblock { get-navappinfo $serverInstance }
```
to get the raw command output

Get-BcContainerAppInfo is designed to be able to sort the output based on dependencies, so it does a lot of stuff more.
if you only want the ones installed, you need to do this:

```
(Get-BcContainerAppInfo -tenantSpecificProperties -tenant default | Where-Object { $_.IsInstalled }).Count
```

I do realize that I can be confusing, but it isn't something I can change today as many pipelines rely on the way the function works today.

**Comment by trylvis** [comment]
Thanks for the fast response, "IsInstalled" is solves it. Keep up the great work! 👍
