### ISSUE TITLE
Possible timeout issue on Compile-AppInBCContainer

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#1443]
Hi,

In a project, I created 3 apps A and B that are independent, and C that depends on A and B.

My Build Pipeline started failing suddenly, I'm trying to figure out what the issue is.

In the pipeline, there is a step to compile the 3 apps, in the order A,B,C.

A and B are compiling successfully but C is failing with the following error:
##[error]Compile-AppInBCContainer : Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an 
error: (404) Not Found." 

Strange that if I run the same command to compile the apps in the server where the agent is installed it compiles without issues.

Today I made another test splitting the compilation step in 2:
1) Compile A,B
2) Compile C
and it worked.

Docker and BcContainerHelpers are updated.

Have you had any similar experience? Maybe there is a timeout in the command to compile the apps?

**Comment by freddydk** [comment]
Please include the output of the container generation + compilation

**Comment by eclipses** [comment]
Closing this issue because started working again and I'm not able to reproduce anymore.
