### ISSUE TITLE
New-BCImage with -includeTestToolkit ?

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#1444]
Not sure if I'm doing it wrong or if I'm misunderstanding the purpose of includeTestToolkit in New-BcImage.
I thought that specifying the testtoolkit here would include the testtoolkit objects in the database, so that I would save the time it takes to import the test objects and generate symbols for them.

But as far as I can see then it does nothing.

At some point doing start.ps1 it calls navinstall.ps1 with the includeTestToolkit param, but this script does not have a includeTestToolkit param. When creating the image it says it's using the run/130 installer (without the testtoolkit param), but this folder does not exist (at least not in the container it creates later). Instead it has a run150-new folder (with the testtoolkit param).
So it looks likes something is wrong...

The script I have been running:
$ArtUrl = Get-BCArtifactUrl -type OnPrem -country w1 -version 14 -select Latest 
New-BcImage -artifactUrl $ArtUrl -includeTestToolkit -licenseFile $LicenseFile -imageName 'myimage/onprem:14'
New-BcContainer -accept_eula -artifactUrl $ArtUrl -imageName 'myimage/onprem:14' -updateHosts -licenseFile $LicenseFile -Credential $Credential

**Comment by freddydk** [comment]
Yep, that optimization was only performed for 15.0 and higher.

**Comment by epernst** [comment]
Oh no, not happy about that. Could it not get work for v14 also?

**Comment by freddydk** [comment]
I probably won't have the time to look into this for the foreseeable future, sorry.
You can download and modify navinstall.ps1 from 130 yourself - make the change and add it to -myscripts on new-bcimage - then you will have it.
You can also submit a PR with the fix on nav-docker.

**Comment by epernst** [comment]
Ok,  will see how much time I can find to do this, but it would be great to cut of 5-10 minutes of every build....

**Comment by freddydk** [comment]
Basically, you need to insert a block of code here: https://github.com/microsoft/nav-docker/blob/87bddd0390b0084b7477d44e84f559294a024cf6/generic/Run/130/navinstall.ps1#L236

and the block of code is here: https://github.com/microsoft/navcontainerhelper/blob/85bd2389775d59dc8b04348e542eac95a12088b0/ObjectHandling/Import-TestToolkitToNavContainer.ps1#L180-L229

Maybe some variables are already there.
