### ISSUE TITLE
Run-AlPipeline, RunTestsInBcContainer, and -companyName

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/navcontainerhelper#1445]
RunTestsInBcContainer has the parameter -companyName, but because that is now layered inside Run-AlPipeline, we can no longer set that parameter during a devops build. Many of our automated tests need a completely blank company, not Cronus, to validate the test. This also means that we probably need a mechanism to create that blank company.

Using the latest 1.0.13.

**Comment by freddydk** [comment]
You can override the way Run-AlPipeline creates the container (to create an empty company) and the way it invokes the Run-Tests to use that company.
See example here: https://github.com/microsoft/navcontainerhelper/issues/1432

**Comment by freddydk** [comment]
There is also a new override called ImportTestDataInBcContainer coming in 1.0.15, which allows you to prep the data needed using rapid start packages or remove and create companies.
