### ISSUE TITLE
Compile-AppInNavContainer is missing "features" parameter

### ISSUE THREAD

**Issue by Gerdna** [microsoft/navcontainerhelper#1448]
The Compile-AppInNavContainer is missing the alc.exe parameter "/features". 

By default the alc.exe will not generate the translation file. Therefore the /feature parameter is used. 
This is neccessary to build a pipeline to verify that all captions are translated.

See PR: #1447

**Comment by freddydk** [comment]
Looks good - could you add a line to releasenotes.txt in the root, thanks.
I like that it doesn't break running on old versions etc.
