### ISSUE TITLE
How to open a new Port for Eventviewer from host?

### ISSUE THREAD

**Issue by elweilando** [Microsoft/navcontainerhelper#145]
I would like to access the the docker eventlogs with the eventvwr.exe from the host.
If I try to connect to the docker, eventvwr.exe tells me, that I have no access. 
I think the reason is, that the port TCP 135 is not mapped. If I try to open the Port with -p 135:135 I always get this error:

`docker.exe: Error response from daemon: failed to create endpoint <NAME> on network nat: HNS failed with error : Unspecified error.`

It seems to be this one https://github.com/docker/for-win/issues/667

Is there another option to access the docker event logs with the eventvwr.exe?

**Comment by freddydk** [comment]
You cannot connect the event log to the container, but you can use navcontainerhelper, which has a function called get-navcontainereventlog, which basically downloads an evtx file and open it in the hosts event viewer.
