### ISSUE TITLE
Compiling Translation and Compiling again

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#1458]
In my pipeline i compile the app, translate the xlif files, and recompile the app, unfortunately compiling takes over 7 min so, I need twice 7min just to compile creates translations and recompile.

Is there any possibility to make this process faster? maybe create the translation file without compiling? Or is there any way to push the translated files back into the app file?

We need to create the translation file in the pipeline because it is they change often with big merge work. Maybe anybody has a better idea?

**Comment by freddydk** [comment]
There is also a thread on Yammer in the Business Central App Development group about the same topic.
Alex states that there is no way to do this in one go.

I haven't worked with this, but maybe you could check whether the generated files are different from last time and if not, it would be sufficient with one compile?

If isn't something I can fix in Docker.
