### ISSUE TITLE
Install NAVSipCryptoProvider only successfully executed every second time

### ISSUE THREAD

**Issue by DBiernat** [microsoft/navcontainerhelper#1469]
**Describe the issue**

Prerequisite: Always started PowerShell "As Administrator".

1. Start Powershell and execute Install-NAVSipCryptoProviderFromBcContainer -containerName "DoesNotMatter". It will be 
    executed successfully.
2. Close the window. 
3. Repeat step 1. An error message will occure.

**Full output of scripts**

```
PS C:\Windows\system32> Install-NAVSipCryptoProviderFromBcContainer R-DE-14-17
Copy SIP crypto provider from container R-DE-14-17
Copy from container R-DE-14-17 (C:\Windows\System32\NavSip.dll) to C:\Windows\System32\NavSip.dll
Move-Item : Cannot create a file when that file already exists.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.13\Misc\Copy-FileFromNavContainer.ps1:40 char:13
+             Move-Item -Path $tempFile -Destination $localPath -Force
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Windows\System32\NavSip.dll:FileInfo) [Move-Item], IOException
    + FullyQualifiedErrorId : MoveFileInfoItemIOError,Microsoft.PowerShell.Commands.MoveItemCommand
```

**Additional context**
- It doesn't matter which container I'm using.

BcContainerHelper is version 1.0.13-dev
BcContainerHelper is not running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.13
Docker Server Version is 19.03.13

- BcContainerHelper version doesn't matter, also occured in older versions. Same for Docker.

**Comment by freddydk** [comment]
Shipped in 1.0.15-preview269
