### ISSUE TITLE
Update hosts file not correct when changing the container's hostname

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#147]
When changing the hostname of the Nav-Container the host file contains
"ip-address hostname" instead of  "ip-address containername"
This again causes the Development Desktop Shortcut to fail because it starts with parameter
servername=<containername>\SQLEXPRESS
I expect this to fail, because the  New-NavContainer script uses the containername as hostname by default.
New-NavContainer uses the code below and show's it uses the hostname, which should be the ContainerName.

    if ($updateHosts) {
        $parameters += "--volume ""c:\windows\system32\drivers\etc:C:\driversetc"""
        Copy-Item -Path (Join-Path $PSScriptRoot "updatehosts.ps1") -Destination $myfolder -Force
        '
        . (Join-Path $PSScriptRoot "updatehosts.ps1") -hostsFile "c:\driversetc\hosts" -hostname $hostname -ipAddress $ip
        ' | Add-Content -Path "$myfolder\AdditionalOutput.ps1"
    }

I use the script below to create my container.

$param = @("-p 8046:80 -p 8048:7046 -p 8052:1433")
$param += "--security-opt credentialspec=file://NAV-Container.json"
$param += "--hostname NAV-Container"

New-NavContainer -accept_eula `
                -containerName "NAV2017W1CU18" `
                -auth Windows `
                -updateHosts `
                -imageName "microsoft/dynamics-nav:2017-cu18" `
                -Credential $MyCredential `
                -restart always `
                -licenseFile "c:\users\michel\foodware\Licenses\5164953 NAV2017.flf" `
                -memoryLimit "3G" `
                -shortcuts "Desktop" `
                -includeCSide `
                -doNotExportObjectsToText `
                -AdditionalParameters @($param)

**Comment by freddydk** [comment]
Why would you want to change the hostname to something different than the containername?
In the script, you cannot change $hostname to $containername as the code is running from inside the container - overriding AdditionalOutput.ps1. Inside the container, there is no variable called $containername.
hostname should always be the same as $containername - else you will get a lot of issues.

**Comment by mheijkant** [comment]
Hopefully you will find this information useful. Or you can give my some further insight on how to deal with this.

Strictly speaking, it’s not necessary to change the hostname of the container when using Windows Or NavUserPassword authentication.
It’s more of a practical issue when I’m using Windows Authentication and having gmsa configured.

As you can read on this link, there’s an important notice to have gmsa configured and working.
”The container hostname (-h parameter) must match the name of the gmsa account in order for the container to be able to communicate with the domain controller”
https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/ServiceAccounts

This is all fine, but here comes the practicality issue for me. If I create 100 containers, I have to create 100 service account’s.
Still doable, when you have administrator rights to create these accounts, and have a clear view of what’s happening in your domain.
I’m not an administrator, nor are most of my colleagues. So going to my administrator every time I want to create a new container is unpractical.
So I’ve received 2 service account’s. One for my SQL containers and one for my NAV containers.

That’s why I want to change the hostname to one of these service account’s when I create a new Container.

**Comment by freddydk** [comment]
are you saying that you then will have multiple contianers with the same hostname, but different container names running at the same time?

**Comment by mheijkant** [comment]
That's correct. It looks fine because the NAV Containers won't communicate directly with the "outside world" or they communicate with a single external SQL container. Clients connect to the host-server by naming the hostserver name and including a port number.
By the way I mentioned 100 containers, only tested it with a few, but it will become larger in no time.

**Comment by freddydk** [comment]
This is fixed in navcontainerhelper 0.2.9.3 and newer.
