### ISSUE TITLE
Run-AlPipeline in new avalaibles countries where Cronus is not available

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/navcontainerhelper#1471]
**Describe the issue**

*Context:* International app for AppSource. (for all countries available for BC)
In that context, MS ask to test the app in all localizations against the Cronus evaluation company.
In some contries (EE, HK, JP, KR, PL...) the Cronus company do not exist directly in the sandbox, and the existing company is empty. We can create the company with the new company function in sandbox. May be using the *New-CompanyInBcContainer* function. But how to make a condition by container ?

Do you have any idea to face this issue? Today I use the *Run-AlPipeline* with succes except on those countries.

**Comment by freddydk** [comment]
In Next version of Run-AlPipeline, you can specify a function to load test data in a parameter called:
```
  -ImportTestDataInBcContainer
```
The value of this is a scriptblock.

In the next preview, there will also be a new function called: UploadImportAndApply-ConfigPackageInBcContainer
You can kind of guess what it does:-)

This can be used with the new parameter override in Run-AlPipeline:
```
Run-AlPipeline `
    -parameter `
    -parameter `
    -ImportTestDataInBcContainer { Param([Hashtable]$parameters) 
        $country = Get-BcContainerCountry $parameters.containerName
        if ($country -eq "hk") {
            UploadImportAndApply-ConfigPackageInBcContainer @parameters -configPackage 'W1.ENU.STANDARD'
            UploadImportAndApply-ConfigPackageInBcContainer @parameters -configPackage 'W1.ENU.EVALUATION'
        }
    }
```

**Comment by freddydk** [comment]
Shipped in 1.0.15-preview269

**Comment by YvesDesrumaux** [comment]
Perfect !
As we prepare containers images before the CI/CD. Can we imagine to get that option also in New-bcImage ?

**Comment by freddydk** [comment]
I am planning to add a -bakfile parameter to new-bcimage - to use a bakfile.
Then you would have to prepare your database in a container and use that for the container.
The more specific you make the images, the less useful they are.
