### ISSUE TITLE
Publish-BCContainerApp doesn't start upgrade before install

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/navcontainerhelper#1472]
Hello,

**Describe the issue**
I am using function "Publish-BCContainerApp" for publish new version of extension. Problem is that earlier version was installed. I need run Start-NAVAppDataUpgrade so I used switch "-upgrade". However, the error below occurs during this function. I checked this function and I found that you run "Start-NAVAppDataUpgrade", but after "Install-NavApp". So I suppose it would be enough to change the order of calling these functions inside "Publish-BCContainerApp". 
Can you please check it or advise me what i am doing wrong?

Thank you

**Scripts used to create container and cause the issue**
```
Publish-BCContainerApp -containerName $containerName -appFile $_.FullName -skipVerification:$skipVerification -sync -upgrade -install
```

**Full output of scripts**
```
[error]Cannot install the extension TestExtension by SampleCompany17.0.0.21 for the tenant default because an earlier version was
 already installed. Run Start-NAVAppDataUpgrade to upgrade the extension.
...
```

**Screenshots**

**Additional context**
- it happens all time when extension exists

**Comment by freddydk** [comment]
It's either -install or -upgrade - not both.

**Comment by fridrichovsky** [comment]
You do not plan to modify this feature to allow the use of -install and -upgrade at the same time?

**Comment by freddydk** [comment]
?
You either install or you upgrade
You don't need to install after the upgrade if that is what you are thinking.
