### ISSUE TITLE
Documentation Request: Docker Setup for BC Container with Windows Authentication

### ISSUE THREAD

**Issue by louagej** [microsoft/navcontainerhelper#1478]
Hi,

When creating a new BC Container with windows authentication, the container gets created and started.
The web client opens and I get a pop-up asking my to enter my WIndows Credentials.
Unfortunately, this pop-up window returns and I can't seem to continue.

```
New-BCContainer `
    -containerName $containerName `
    -artifactUrl $artifactUrl `
    -licenseFile  $licenceFile `
    -auth Windows`
    ...
```

**Documentation**

On the [documentation page](https://github.com/microsoft/navcontainerhelper/blob/master/NavContainerHelper.md#setup-windows-authentication-with-the-windows-user-on-the-host-computer)  I noticed the `Note`:
>***
>![image](https://user-images.githubusercontent.com/7229592/99953703-f044bd80-2d81-11eb-98b5-520b28f3ebf8.png)
>***

In order to reach the domain controller, I found some documentation online that we should modify the json Docker daemon:

- add the ip address of the domain controller in the dns part
- add the dns name in the dns-search

So I ended up with my json like this:
```json
{
      "registry-mirrors": [],
      "insecure-registries": [],
      "debug": true,
      "experimental": false,
      "dns": [
        "10.0.0.0" //But then our companies domain controller ip address
      ],
      "dns-search": [
        "myawesomedomain.com"//But then our companies dns name
      ]
}
```

But that that didn't work as well. 😞
Do you have any idea how to get this authentication type working inside a Docker Container for  BC?

**Comment by freddydk** [comment]
Did you specify our windows credentials as credentials for starting the container?

**Comment by louagej** [comment]
Hi,

I just passed my windows credentials in a cred object but that didn't gave my the result I was hoping for.

![SNAG-0000 2020 11 23 13 57 14 (3)](https://user-images.githubusercontent.com/7229592/99965627-656dbe00-2d95-11eb-9466-78b02ad42264.jpg)


If I understand this correct, the BC Instance in the container creates a dummy Windows user.
Because when I enter my Windows credentials, I receive this error.

I receive this error message:

![SNAG-0000 2020 11 23 13 58 26](https://user-images.githubusercontent.com/7229592/99964725-0e1b1e00-2d94-11eb-9361-61ad2ff4e016.jpg)


I thought it was possible to direct the auth. part to a domain controller, so when I change my password, the BC Instance should pass my credentials to the domain controller instead of entering a dummy Windows User

**Comment by freddydk** [comment]
Correct, containers cannot join a domain.
Instead windows authentication lives off the fact that it works when the user inside the container has the same username/password as the windows user on the host.
And when you change password on the host, you need to do the same in the container - they are disconnected.
You need to setup group managed service accounts in order to make it work correctly.

**Comment by louagej** [comment]
Hi Freddy,
Thanks for making this clear.
