### ISSUE TITLE
Exporting Objects from a nav2018 CU6 W1 container fail

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#148]
Exporting objects from the container fail. 

New-NavContainer `
-accept_eula `
-containerName "NAV2018W1CU6T" `
-auth Windows `
-updateHosts `
-imageName "microsoft/dynamics-nav:2018-cu6-w1" `
-Credential $credential `
-restart always `
-licenseFile "C:\Users\michel\Foodware\Licenses\5164953 NAV2018.flf" `
-memoryLimit "3G" `
-shortcuts "Desktop" `
-includeCSide

followed by this error:

WARNING: UnhandledErrorMessage
!
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.9.2\ObjectHandling\Export-NavContainerObjects.ps1:44 char:5
+     Invoke-Command -Session $session -ScriptBlock { Param($filter, $o ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-NAVApplicationObject

When including -doNotExportObjectsToText, the container is created and is accessible.
When opening the DeveloperClient with NAV2018W1CU6T, I can export the objects manually, without any error.

I'm also creating similar 2017 containers with the same parameters, but a different license. Exporting those objects, run correct.

**Comment by mheijkant** [comment]
I did try doNotExportObjectsToText and use Export-NavContainerObjects afterwards. But not from inside the container. First thing tomorrow is ask for a new license file and try again. Although as you might have read, I can access the Container, and export objects from the Developer Environment. License looked fine sofar.

**Comment by freddydk** [comment]
My spelling mistake - inside the container it is export-navapplicationobject.
Also, what version of the navcontainerhelper do you have?
On march 20th a bug was fixed, which caused the underlying export-navapplicationobject to be called without -ExportTxtSkipUnlicensed.

**Comment by mheijkant** [comment]
I'm using navcontainerhelper\0.2.9.2.
I'm trying to use export-navapplicationobject from inside the container, but the command isn't recognised, nor is load-module. I'm opening powershell by: "docker exec -it <mycontainer> powershell"

**Comment by freddydk** [comment]
use the shortcut on the desktop.
It runs a script called c:\run\prompt.ps1 (or run this in your docker exec).
Then you have all modules loaded.

**Comment by mheijkant** [comment]
Inside the container I have the same error.
PS C:\> Export-NAVApplicationObject

cmdlet Export-NAVApplicationObject at command pipeline position 1
Supply values for the following parameters:
DatabaseName: CRONUS
Path: c:\temp

Confirm
c:\temp already exists. If you continue, c:\temp will be overwritten.
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"): y
Export-NAVApplicationObject : !
At line:1 char:1
+ Export-NAVApplicationObject
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-NAVApplicationObject

**Comment by freddydk** [comment]
Could you try to set the logpath and get the log and see if we can see anything from that?

**Comment by mheijkant** [comment]
Sorry for this, but it's not working for me. there's no log.

PS C:\> Export-NAVApplicationObject -LogPath c:\log -DatabaseName CRONUS -Path c:\temp

Confirm
c:\temp already exists. If you continue, c:\temp will be overwritten.
[Y] Yes  [N] No  [S] Suspend  [?] Help (default is "Y"):
Export-NAVApplicationObject : !
At line:1 char:1
+ Export-NAVApplicationObject -LogPath c:\log -DatabaseName CRONUS -Pat ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-NAVApplicationObject

**Comment by freddydk** [comment]
Can you shoot an email to freddyk at microsoft dot com, then we can continue offline.
Thanks

**Comment by freddydk** [comment]
We found that the cause of this was, that the host wasn't updated with the latest windows updates.
Due to this, the containers were using a newer version of windows server than the host and when running process isolation this caused the problem.
Updating the host fixed the problem.
I think the problem would also disappear when running hyperv isolation.

**Comment by nemanjabrdar** [comment]
I believe that this issue can be solved by using set-executionpolicy unrestricted through NAV develompent shell first.
