### ISSUE TITLE
if error is raise during ImportTestDataInBcContainer, the country loop is broken

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/navcontainerhelper#1481]
**Describe the issue**
If any error is raised during the Importing Test Data step, the Run-ALPipeline stop.

**Full output of scripts**
BcContainerHelper version 1.0.15-preview270
Running as administrator
Checking permissions to C:\ProgramData\BcContainerHelper
isaDevOpBC\AzureAdmin has the right permissions to C:\ProgramData\BcContainerHelper
Checking permissions to C:\windows\System32\drivers\etc\hosts
isaDevOpBC\AzureAdmin has the right permissions to C:\windows\System32\drivers\etc\hosts
Checking permissions to docker commands
isaDevOpBC\AzureAdmin has the right permissions to run docker commands

**Screenshots**
Screenshot of process joined.
![TestDataErr](https://user-images.githubusercontent.com/30075742/99984982-05374600-2dae-11eb-8831-c004c59f2afc.png)

**Comment by freddydk** [comment]
Which country is this?
Did you try that country and that package manually?

**Comment by freddydk** [comment]
If you want to do it differently, you are in control.
In the override - put a try/catch around the call to import the configuration package - then you decide what to do if it fails.

**Comment by YvesDesrumaux** [comment]
This is EE localization and Yes, I manage to import the package manually on my local sandbox container.

**Comment by freddydk** [comment]
Could you use -keepContainer and then go to the machine and get the event log from the container (get-bccontainereventlog) to see why this fails?

**Comment by YvesDesrumaux** [comment]
I have the issue on the 8 countries (EE, HK, JP, KR, PL, RS, TH, TW). I joined the 8 evtx files.
But honestly, I do not know what to look for in those files.
[isatech-ncm 2020-11-23.zip](https://github.com/microsoft/navcontainerhelper/files/5588146/isatech-ncm.2020-11-23.zip)



Below, the block code
ImportTestDataInBcContainer = { Param([Hashtable]$parameters) 
              $containerCountry = Get-BcContainerCountry $parameters.containerName;
              if (@("ee", "hk", "jp", "kr", "pl", "rs", "th", "tw").Contains($containerCountry.ToLowerInvariant())) {
                Try { UploadImportAndApply-ConfigPackageInBcContainer @parameters -configPackage 'W1.ENU.EVALUATION' }
                Catch {
                  Get-BcContainerEventLog -containerName $parameters.containerName -doNotOpen;
                  $myFolder = Join-Path (Join-Path "$($bcContainerHelperConfig.hostHelperFolder)\Extensions" $parameters.containerName) "my";
                  $evtx = Get-Item "$myFolder\*.evtx";
                  Move-Item -Path $evtx -Destination "C:\$containerCountry_$($evtx.name)" -Force;
                  }
              } else { Write-Host "No Test Data requiered" }
            }

**Comment by freddydk** [comment]
Could I get the full output of the pipeline (container generation and all)
You can email it to freddyk at microsoft dot com if you don't want to post it here.

**Comment by freddydk** [comment]
I can repro this.

Not sure why, but in my tests I did this:
        UploadImportAndApply-ConfigPackageInBcContainer @parameters -configPackage 'W1.ENU.STANDARD'
        UploadImportAndApply-ConfigPackageInBcContainer @parameters -configPackage 'W1.ENU.EVALUATION'

and that works.
Maybe when you login and do it manually, some initialization is happening, I don't know.

**Comment by YvesDesrumaux** [comment]
I did first that. Yes with success for importing but then some settings were not initialized and tests Fails

And in https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/compliance/apptest-testingyourextension#use-the-correct-data-when-you-test-your-app then only say to use 'W1.ENU.EVALUATION'.
Which works fine manually.

**Comment by freddydk** [comment]
Ok, will investigate.
Something seem to be not initialized when importing the eval...:-(

**Comment by freddydk** [comment]
Try this:

```
    -ImportTestDataInBcContainer { Param([Hashtable]$parameters) 
        if (!(Get-CompanyInBcContainer -containerName $parameters.containerName -tenant $parameters.tenant | Where-Object { $_.companyname -like "*CRONUS*" })) {
            New-CompanyInBcContainer -containerName $parameters.containerName -tenant $parameters.tenant -companyName "CRONUS" -evaluationCompany
            Invoke-NavContainerCodeunit -containerName $parameters.containerName -tenant $parameters.tenant -CompanyName "CRONUS" -Codeunitid 2 6> $null
            UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -tenant $parameters.tenant -companyName "CRONUS" -Credential $Parameters.credential -configPackage 'W1.ENU.EVALUATION'
        }
    }
```

**Comment by YvesDesrumaux** [comment]
Seems much better, but I still having errors messages on those companies.
These kind of error are typically due to Application Areas that, I suppose, are not set in the new CRONUS company.
![image](https://user-images.githubusercontent.com/30075742/100217070-56ad1580-2f13-11eb-8607-a7d2d2720519.png)
Those errors occured on standard page fields.

When I create the company manually with the package, I do not get the error. All tests are successfull.

**Comment by freddydk** [comment]
Did you ever find a solution to this problem?

**Comment by YvesDesrumaux** [comment]
The issue is still live :(

**Comment by freddydk** [comment]
Would t be possible to provide a repro scenario for me?
A script I can run end 2 end, which showcases the problem.
Then I will probably be able to find the reason why.

**Comment by YvesDesrumaux** [comment]
Ok I will try to provide you a extension source and PS Script to reproduce it.

**Comment by freddydk** [comment]
Did you change the approach to map these missing countries to base instead - and thus don't have this problem anymore?
If you still have the problem, please provide me with a PowerShell script (not pipeline), which reproes the problem and I can have a look.

**Comment by YvesDesrumaux** [comment]
Hello Freddy,
Yes, I changed the approach to map those countries to Base. Therefore, no more issue.
