### ISSUE TITLE
Sign-NavContainerApp SHA1 instead of SHA256

### ISSUE THREAD

**Issue by TGosselink** [microsoft/navcontainerhelper#1497]
Sign-NavContainerApp generates SHA1 signatures by default
Hover the tool used: SignTool.exe recomments SHA256

According to:
"/fd | Specifies the file digest algorithm to use for creating file signatures. Note: A warning is generated if the/fd switch is not provided while signing. The default algorithm is SHA1 but SHA256 is recommended."

Would be great to change to SHA256 to make it more secure.

Thanks so much...

**Comment by freddydk** [comment]
Same comment made in 1550 - I will add a parameter.

In this case, the only thing a code signing certificate does is to allow Microsoft to see who created the appfile and that the appfile wasn't tampered with from the time you signed it and until the time we are uploading to appsource.

It does NOT protect your .app file from being extracted and inspected - only runtime packages are safe in that regards.

I would not assume that this would be the primary area of attack for any hacker, trying to intercept .app files and inject malicious code and make sure that the SHA1 doesn't detect that.

I will update this to allow a parameter for that, but please don't think that there is any significant security risk in using SHA1.

**Comment by freddydk** [comment]
Shipped in 1.0.17
There is a parameter on Sign-BcContainer called -digestAlgorithm. Set this to SHA256.
The default for that parameter settable in configuration $bcContainerHelperConfig.digestAlgorithm or in the configuration file.
default for the configuration is blank (same behavior as before)

Please let me know whether this works for SHA256 - I do not have access to the MS code signing cert's.

**Comment by TGosselink** [comment]
Unfortunately the new parameter doesn't work correctly
Used Parameters:
**Sign-BcContainerApp -appFile $_.FullName -pfxFile $MyPfx -pfxPassword $MyPassword -containerName $mycontainerName -digestAlgorithm sha256**

Error returned: 
**SignTool Error: The /t option is incompatible with the /td option.**

Reason:
/t should not be used with SHA256 but /tr instead.
In your code, that's an easy fix.

Source: https://www.thegeekstuff.com/2017/01/signtool-examples/

_Example 2: Code Sign using SHA256 Algorithm
To code sign using SHA256, in the Windows command prompt, enter the following command.

signtool.exe sign /a /tr http://timestamp.geotrust.com/tsa /td sha256 /fd sha256 /v "c:\thegeekstuff.exe"
In the above command:

/tr – “tr” here stands for time stamp server RFC 3161. For this, you have to make sure the time stamp server is a RFC 3161 support. If not, this will return an error message as shown below. I’ve used the geotrust.com URL. You can also use this RFC 3161 URL: http://timestamp.digicert.com
/td – “td” here stands time server digest algorithm. This is used to request the specified digest algorithm (in this case, sha256) from the specified RFC 3161 time server. Make sure the /td switch is declared after the /tr switch. If you specify this before the /tr switch, then the timestamp will be returned from SHA1 algorithm and from SHA256 as you would hope for.
/fd – “fd” here stands for File Digest Algorithm. By default when you don’t specify this parameter, it will use the SHA-1 algorithm. In this example, it will use the SHA256 algorithm to digitally sign the file.
Error 1: If you specify /t option (instead of /tr) when you give /td, it will throw the following incompatible option error message.

C:\> signtool.exe sign /a /t http://timestamp.verisign.com/scripts/timstamp.dll /td sha256 /fd sha256 /v "c:\thegeekstuff.exe"
SignTool Error: The /t option is incompatible with the /td option._
