### ISSUE TITLE
  Le terme «-includePerformanceToolkit» n'est pas reconnu

### ISSUE THREAD

**Issue by gtrennert** [microsoft/navcontainerhelper#1498]
**Describe the issue**
Error concerning -includePerformanceToolkit on New-BcContainer

**Scripts used to create container and cause the issue**
```
New-BcContainer `
    -accept_eula `
    -accept_outdated `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -includeTestLibrariesOnly `                
    -includePerformanceToolkit `
    -licenseFile $licenseFile `
    -memoryLimit 8G `
    -vsixFile (Get-LatestAlLanguageExtensionUrl) `
    -shortcuts Desktop `
    -assignPremiumPlan `
    -useBestContainerOS `
    -isolation hyperv `
    -updateHosts `
	-hostHelperFolder $hostHelperFolder `
    -bcartifactsCacheFolder $bcartifactsCacheFolder `
    -alwaysPull `

```

**Full output of scripts**
BcContainerHelper version 1.0.14-dev
BcContainerHelper is version 1.0.14-dev
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Professionnel - 2004
Docker Client Version is 19.03.13
Docker Server Version is 19.03.13
Removing container bcfr-17
Removing C:\ProgramData\BcContainerHelper\Extensions\bcfr-17
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.19041.630-generic
Creating Container bcfr-17
Version: 17.1.18256.18792-fr
Style: onprem
Multitenant: No
Platform: 17.0.18204.18738
Generic Tag: 0.1.0.24
Container OS Version: 10.0.19041.630 (2004)
Host OS Version: 10.0.19041.630 (2004)
Using process isolation
Using locale fr-FR
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\bcfr-17\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container bcfr-17 from image mcr.microsoft.com/dynamicsnav:10.0.19041.630-generic
70a72da30eb4bf60211b2ea05968047f3e1e6a17a26803e067d9c6b9f200e989
Waiting for container bcfr-17 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.1.18256.18792/fr
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\17.1.18256.18792\fr\database\Demo Database NAV (17-0).bak
Changing Database Server Collation to French_100_CI_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 73 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.30.16.1 in container hosts file
Starting Container
Hostname is bcfr-17
PublicDnsName is bcfr-17
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 51D5637A87F9AFFB7F41C446A9B41C78D909F6D6
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating Admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.30.28.191
Container Hostname  : bcfr-17
Container Dns Name  : bcfr-17
Web Client          : http://bcfr-17/BC/
Dev. Server         : http://bcfr-17
Dev. ServerInstance : BC

Files:
http://bcfr-17:8080/ALLanguage.vsix

Container Total Physical Memory is 15.9Gb
Container Free Physical Memory is 7.7Gb

Initialization took 24 seconds
Ready for connections!
Reading CustomSettings.config from bcfr-17
Creating Desktop Shortcuts for bcfr-17
Container bcfr-17 successfully created

Use:
Get-BcContainerEventLog -containerName bcfr-17 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bcfr-17 to get debug information about the container
Enter-BcContainer -containerName bcfr-17 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bcfr-17 to remove the container again
docker logs bcfr-17 to retrieve information about URL's again
-includePerformanceToolkit : Le terme «-includePerformanceToolkit» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez 
l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère xxx\Script Create BCContainer.ps1:35 : 5
+     -includePerformanceToolkit `
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-includePerformanceToolkit:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by freddydk** [comment]
You have some spaces after the grave symbol, which invalidates the grave symbol.
![image](https://user-images.githubusercontent.com/10775043/100495506-bcd0ad00-314c-11eb-9dee-49d777418180.png)
You can read more about it here: https://freddysblog.com/2019/08/04/powershell-for-non-experts/ (search for the Grave Symbol)

**Comment by freddydk** [comment]
BTW - I think you also need to include the  -includeTestToolkit parameter.
