### ISSUE TITLE
Powershell 7.1 on OSX

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#1499]
**Describe the issue**
Can not import-Module BcContainerHelper on OSX with Powershell 7.1
**Scripts used to create container and cause the issue**
```
Import-Module BcContainerHelper```

**Full output of scripts**
```
Import-Module: The script 'BcContainerHelper.psm1' cannot be run because it contained a "#requires" statement for PowerShell editions 'Desktop'. The edition of PowerShell that is required by the script does not match the currently running PowerShell Core edition.
```

**Comment by freddydk** [comment]
ContainerHelper doesn't run on OSX nor on PowerShell core.
I also don't think you can run Windows Containers on OSX - if you can, then you can use docker commands or wait until ContainerHelper shifts to PS Core. That is probably 1-2 years out.

**Comment by KristofKlein** [comment]
Well I was not even interest in running  a container... I was more seeking for the get-artefacts to do AL development on OSX ... But point taken...
(And no, right now you can not run a windows containers on OSX native...still you could point the Docker CLI to another machine that could be windows...)

**Comment by freddydk** [comment]
You could. BcContainerHelper needs to share folders with the container for a lot of the functionality though, that wouldn't work.
If you want to, you could take this: https://github.com/microsoft/navcontainerhelper/blob/master/Misc/Get-BCArtifactUrl.ps1 and remove the export-function line. That function might work on OSX.
