### ISSUE TITLE
Question: Using NavContainerHelper to upgrade tenant to new build

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/navcontainerhelper#150]
Hi, 

We are using Export-NavContainerDatabasesAsBacpac to provide app.bacpac and tenant.bacpac files for the embed app program. Our bacpac files would sometimes be on a different BC build and we would need to upgrade existing tenants.

Is there an easy way for us to test upgrade of the existing tenant (maybe using that tenant.bacpac or tenant.bak file) and mounting it to a new container that is using more recent build? Also running all the sync and app upgrade procedures.

So far I can only see New-NavContainerTenant but that is creating a copy of existing tenant from that container, and not giving me the ability to point to new database or .bak file coming from different environment.

**Comment by freddydk** [comment]
The idea was to spin up a new container with the bacpacs with the new version - but what you are alluding to here is that you want to be able to move a tenant from the old version to the new version.
I will add this capability to new-navcontainertenant - in order for you to test the upgrade as requested.

**Comment by ivandjordjevic** [comment]
If we can spin a new container with the new version from the bacpacs created from previous build, I think that should work as well.
