### ISSUE TITLE
[Question] Run-AlPipeline: $RunTestsInBcContainer -missing parameters-

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#1501]
Hi @freddydk,

we are using an adapted version from your Hello World CI/CD example to run our build pipelines.

Within DevOps-Pipeline.ps1 we successfully overload the $NewBcContainer & $RemoveBcContainer script blocks in Run-AlPipeline.ps1.

Now we want to run our own test script ($RunTestsInBcContainer), but we have problems to transfer the $testfolders parameter to that script block.

```
if ( -not $doNotRunTests ) {
    $RunTestsInBcContainer = { Param([Hashtable]$parameters) `
            .\scripts\Run-Tests -containerName $parameters.ContainerName -appFolders $testFolders }
}

Run-AlPipeline @params `
    [...]
    -appFolders $appFolders `
    -testFolders $testFolders `
    -doNotRunTests:$doNotRunTests `
    -RunTestsInBcContainer $RunTestsInBcContainer `
```

We tried to define the $testFolders parameter as a global variable, but that $RunTestsInBcContainer scriptblock runs inside its own session, where it doesn't knows those global vars.

As a temporary solution I am running the Read-Settings.ps1 script again to get the $testFolders variable from the settings.

Any suggestions?

**Comment by freddydk** [comment]
You can do like this:
```
Run-AlPipeline @params `
    [...]
    -appFolders $appFolders `
    -testFolders $testFolders `
    -doNotRunTests:$doNotRunTests `
    -RunTestsInBcContainer { MyrunTests ...   } `
```
If you have a codeblock there, you have access to variables in this scope and can transfer them to your function.

**Comment by freddydk** [comment]
Alternatively you can use global variables

$global:somevar = "test"

should be the same allover
