### ISSUE TITLE
NextMinor and NextMajor for On-Prem

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#1502]
Hi,

This is more of a request for information. 

How to get NextMinor and NextMajor for On-Prem? 

I have SaaS Token but seems there are artifacts only for Sandbox. I have a pipeline failing because the repository contains an EDM Type Installation codeunit, that functionality to insert new EDM Types is not available in SaaS but only on-Prem.

Error message:  
`You do not have permission to insert 'OData Edm Type' records because the tenant is mounted with the application database as read-only.`

Is there any plan to have NextMinor and NextMajor for On-Prem as well?

Please let me know

Thank you

**Comment by freddydk** [comment]
If you create a container based on the sandbox artifacts and remove the contents of these tables:

```
"Membership Entitlement"
"Entitlement Set"
"Entitlement"
```

Then you should have something very close to on-prem (not the demo data though)

**Comment by eclipses** [comment]
Thank you for the information, unfortunately, this does not fix the error received.

Do you know if there is any plan for Microsoft to generate Artifacts for preview versions for On-Prem? Maybe not needed to be daily built.

**Comment by freddydk** [comment]
We do not have plans to generate previews of onprem.
Isn't the above error a licensing issue?

**Comment by eclipses** [comment]
It's not a license issue.
OData EDM table is a system table and by design can be added records in it only in On-Prem version. The error probably is because in a multi-tenant SaaS environment, the application database is read-only.

I don't like the idea to create an environment and apply changes to make the pipeline working but if there is no possibility to have On-Prem artifacts for previews I will fix the errors and make it to work.

Thank you for your support, I'm closing this issue
