### ISSUE TITLE
[QUESTION] possibility to use Publish-PerTenantExtensionApps on Dev End point?

### ISSUE THREAD

**Issue by AcererakTheLich** [microsoft/navcontainerhelper#1503]
Hi,

I'm trying to automatize extensions publication to BC tenants using DevOps release pipelines while working on "AppSource" extensions. Of course this intends for internal test sandboxes deployment only. (And it works fine for real PTE)
We previously tried using method found in older Hello World's Deploy-App.ps1 script and now try using Publish-PerTenantExtensionApps function (although its name is self-explanatory).
None of this methods were successful because of this expected error "An App with same app Id 'xxxx' is Already published 
with Global scope"
The only possibility we discovered for now is to manually publish from VSCode, which works well, and I did not find yet how to reproduce it into release pipeline.

My question is: would it be possible to include a switch to Publish-PerTenantExtensionApps function to enable Dev End point publication to reproduce VSCode one and then allow easy automatized deployment, even related to AppSource already deployed extension?
Or maybe I simply missed some documentations somewhere to do that in another way? 

Here is used script and result (expected results anyway)
Publish-PerTenantExtensionApps -useNewLine `
    -ClientID $PublisherAppClientID `
    -ClientSecret $PublisherAppClientSecret `
    -tenantId $TenantId `
    -environment $Environment `
    -companyName $CompanyName `
    -appFiles @("myFile.app")

Result 
Invoke-WebRequest : {"error":{"code":"Unknown","message":"An App with same app Id 'xxxxxxx' is Already published 
with Global scope with name 'xxxxxxx'. Please use the Extension market place to install the extension or use a new app id 
for the current extension. CorrelationId: xxxxx."}}
Au caractère C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.14\AppHandling\Publish-PerTenantExtensionApps.ps1:119 : 17
+ ...             Invoke-WebRequest -Headers ($authHeaders+(@{"If-Match" =  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by AcererakTheLich** [comment]
Hi,

Thanks' to your last bcContainerHelper modifications as described in your "Publishing apps to a Business Central Online Environment" blog post my "issue" is now solved.
I can use Publish-BcContainerApp with bcAuthContext and environment within my pipelines to publish AppSource apps to the Development scope in a Sandbox environment.

Thank you.

**Comment by freddydk** [comment]
Yep, I ment to write this here, but I forgot.
Sorry, but good you found it yourself.
