### ISSUE TITLE
The login is from an untrusted domain and cannot be used with Windows authentication.

### ISSUE THREAD

**Issue by DavidRoys** [Microsoft/navcontainerhelper#152]
I have a docker container that no longer allows me to authenticate using my host Windows credentials. When I try to run the CSIDE client I get this:

```
---------------------------
Microsoft Dynamics NAV Development Environment
---------------------------
The following SQL Server error or errors occurred:

18452,"28000",[Microsoft][SQL Server Native Client 11.0][SQL Server]Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.
---------------------------
OK   
---------------------------

```
When I try to run the Windows client I get this:

```
---------------------------
Microsoft Dynamics NAV
---------------------------
The program could not create a connection to the server. Do you want to try again?
---------------------------
Yes   No   
---------------------------

```
And the Web client will prompt for username/password three times at which point I get:

```
401 - Unauthorized: Access is denied due to invalid credentials.
You do not have permission to view this directory or page using the credentials that you supplied.

```

The docker container is healthy and I can launch a Powershell prompt on it and restart the NAV server instance, etc.

Is there anything you can suggest to try to re-establish the trust relationship or will I need to spin up a new container? It's not a drama obviously, I'd just like to try to understand what broke it and what if anything could fix it.

Since it last worked I installed a new container (using NavContainerHelper) for NAV2018 using latest. The failing container is BC. Here are my containers:

```
IMAGE                               CREATED      STATUS                  PORTS                                                NAMES
microsoft/dynamics-nav:nz           3 days ago   Up 7 minutes (healthy)  80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 8080/tcp   NAV2018
microsoft/bcsandbox:12.0.21576.0-us 6 weeks ago  Up 7 minutes (healthy)  80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 8080/tcp   MyBCDevEnv2
```
I found a similar thing happened the last time I changed my Windows logon password but this has not happened. My NAV2018 container still works correctly.

Any ideas or suggestions?

**Comment by freddydk** [comment]
Are you using Windows Server or Windows 10 as a host?`
(Process vs. Hyperv isolation?)

**Comment by Koubek** [comment]
Actually, I usually use short-time living containers to develop something and push the code to the repo but I recently I left some code in one long-living container and after several weeks I tried to access it and I experienced the same problem.

I was running on Windows 10 (so no gMSA), WinAuth, no password change (moreover, the company had no password oriented policy enabled). As I wasn't able to access so I decided to delete it. This experience convinced me that I should definitely use containers without gMSA only to develop and destroy and sync my code with some SCM. 

Actually, containers (generally) were always considered to serve more for DevOps and this reflects this approach (create a container, develop, push your code, destroy the container).

Anyway, if you have any idea about what has happened here (with emulated WinAuth) I would like to know it...

Thanks!!!

**Comment by kine** [comment]
In standard environment I will think about time difference between SQL and client, or client and domain server, but in this case, could be some time difference between container and host? If they are sharing the OS services, the time should be same, no? I know that this situation sometimes happen when I forget to disconnect from some VPN etc. But in this case...

**Comment by Koubek** [comment]
Cool idea @kine, that's true. Thank you very much!

**Comment by DavidRoys** [comment]
@freddydk Windows 10.

I don't really know where to find whether I'm using process or Hyper-V isolation. Is it the Default Isolation: hyperv in the info below?

Server Version: 18.03.1-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd gelf json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise

**Comment by kine** [comment]
Windows 10 is always HyperV isolation.


________________________________

**Comment by DavidRoys** [comment]
I frequently use VPN connection back to the office so maybe that is the cause. I don't understand why this would cause the problem but for me that is certainly a possibility.

**Comment by freddydk** [comment]
for Windows Authentication to work the way it is setup in Docker without gMSA, you need to be connected to the network where your AD server is - cached credentials doesn't work.
