### ISSUE TITLE
SQL Server restore issues

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#1521]
After the recent update of BcContainerHelper, then we get this error, when we try to restore our application database to our onprem-environment using SQL 2017:

_The database was backed up on a server running version 15.00.2000. That version is incompatible with this server, which is running version 14.00.1000._

I assume it has to do with the recent update to SQL 2019 as per your blog post, and that we need to specify baseImage when creating our new images?

**Comment by freddydk** [comment]
If you need SQL 2017 in the generic image you will have to set the generic image in the config file on the machine to 

mcr.microsoft.com/businesscentral:{0]-0.1.0.25

or use "$(get-bestgenericimagename)-0.1.0.25" as baseimage in new-bcimage.

until you have updated the other servers to SQL 2019.

**Comment by epernst** [comment]
Thanks. I'm rebuilding our VMScaleSet agents with this param right now. Hope it works!

**Comment by freddydk** [comment]
This is the situation where I am happy that I decided to keep a SQL 2017 version around - somebody might need it for a while:-)
Sorry for the disruption though.

**Comment by epernst** [comment]
And likewise I'm happy I'm not updating BcContainerHelper automatically in my build pipeline. BcContainerHelper is only updated when our ScaleSet agent pipeline is running, so the problem only effected one of our pipelines (which still updated BcCH).

**Comment by epernst** [comment]
Seems a bit more problematic to fix. I started by updating the images on our build agents with the "$(get-bestgenericimagename)-0.1.0.25" on New-BcImage. Now when I run my builds using the same image name and artifact url it complains with:
_Image bhit/onprem:14.16.44342.0-w1-tt has generic Tag 0.1.0.25, should be 1.0.1.0
Building image bhit/onprem:14.16.44342.0-w1-tt based on mcr.microsoft.com/businesscentral:10.0.17763.1577 with https://bcartifacts.azureedge.net/onprem/14.16.44342.0/w1
Pulling latest image mcr.microsoft.com/businesscentral:10.0.17763.1577_

And then it rebuilds everything.

So I also have to specify the same UseGenericImage = "$(get-bestgenericimagename)-0.1.0.25", when running New-BcContainer. 

Hope you're not planning to drop this right away, as I'm afraid it may take months, before we can get all the SQL servers updated...

**Comment by freddydk** [comment]
You should drop these parameters and create a line in bccontainerhelper.config.json with 

"genericimage": "mcr.microsoft.com/businesscentral:{0}-0.1.0.25"

then everything will be automatic.

**Comment by freddydk** [comment]
Fix shipped in 1.0.16

**Comment by freddydk** [comment]
The SQL 2017 version will stay.
New features might not be available in that generic image, but it will work for the foreseeable future.
closing this issue.
