### ISSUE TITLE
Run-AlValidation not finding control addins

### ISSUE THREAD

**Issue by catadumitru** [microsoft/navcontainerhelper#1522]
**Describe the issue**
When running the Run-AlValidation command with an app that has control addins the validation fails.
When the app file is compiled, the file structure is not the same as in the project.
That gives the error AL0327: Missing file

The app passed the MS validation in the past
**Scripts used to create container and cause the issue**
```
$validationResult = Run-AlValidation -licenseFile $licenseFile `
                                     -previousApps $previousApps `
                                     -apps $apps `
                                     -validateCurrent `
                                     -countries $countries `
                                     -affixes $affixes `
                                     -supportedCountries $countries `
```

**Screenshots**
![image](https://user-images.githubusercontent.com/45454411/101472430-e2c63080-3948-11eb-85e7-153afe36b4ff.png)

**Comment by freddydk** [comment]
Will investigate and fix.

**Comment by freddydk** [comment]
Fix shipped in 1.0.16

**Comment by petegonnella** [comment]
this has reappeared in the BC22 validation

**Comment by freddydk** [comment]
@petegonnella - please create a new issue with full log, thanks
