### ISSUE TITLE
Change request: remove users from sql backup

### ISSUE THREAD

**Issue by JanBoes** [microsoft/navcontainerhelper#1526]
**Script output:**

BcContainerHelper version 1.0.15
BcContainerHelper is version 1.0.15
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 19.03.13
Docker Server Version is 19.03.13
Removing container ****-Test
Removing C:\ProgramData\BcContainerHelper\Extensions\*****-Test
Fetching all docker images
Using image mcr.microsoft.com/businesscentral:10.0.19042.630
Creating Container *****-Test
Version: 16.7.18411.0-w1
Style: onprem
Multitenant: No
Platform: 16.0.18359.0
Generic Tag: 1.0.1.0
Container OS Version: 10.0.19042.630 (20H2)
Host OS Version: 10.0.19042.630 (20H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file c:\mprise\project\Licenties\BC\******.flf
Additional Parameters:
--volume "c:\mprise\project\*****-Test\Docker\Share:c:\project\dockershare" --env bakfile="c:\project\dockershare\bak\201208 *****_BC16_SANDBOX.bak"
Files in C:\ProgramData\BcContainerHelper\Extensions\****-Test\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container ****-Test from image mcr.microsoft.com/businesscentral:10.0.19042.630
1187b82dee4649f25d13d7e4c0d426b7ccd0dab678da95ee4ea580351a34a0b1
Waiting for container *****-Test to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.7.18411.0/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Installation took 27 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.28.240.1 in container hosts file
Starting Container
Hostname is *****-Test
PublicDnsName is Ball-Test
Using NavUserPassword Authentication
Using Database .bak file 'c:\project\dockershare\bak\201208 *****_BC16_SANDBOX.bak'
Using database server localhost\SQLEXPRESS
Setting CompatibilityLevel for mydatabase on localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 155FD343423B9174BA49A36AA3B5AB0DFCAF4885
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating Admin as SQL User and add to sysadmin
Creating SUPER user
The new users do not meet the terms of the current license. The current license allows 10 full users and 20 limited users.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 202
at <ScriptBlock>, C:\Run\start.ps1: line 350
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/onprem/16.7.18411.0/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Installation took 27 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.28.240.1 in container hosts file
Starting Container
Hostname is *****-Test
PublicDnsName is ******-Test
Using NavUserPassword Authentication
Using Database .bak file 'c:\project\dockershare\bak\201208 ******_BC16_SANDBOX.bak'
Using database server localhost\SQLEXPRESS
Setting CompatibilityLevel for mydatabase on localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 155FD343423B9174BA49A36AA3B5AB0DFCAF4885
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating Admin as SQL User and add to sysadmin
Creating SUPER user
The new users do not meet the terms of the current license. The current license allows 10 full users and 20 limited users.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\navstart.ps1: line 202
at <ScriptBlock>, C:\Run\start.ps1: line 350
at <ScriptBlock>, <No file>: line 1
Initialization of container *****-Test failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.15\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ****-Test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container *****-Test failed

---------------------------------
Change Request:
As you can see I am trying to use a sql backup  which contains too many users for my BC development license).
Is it possible to remove all users before creating the ADMIN users?
Any other way which results in a working docker environment is also fine

**Comment by freddydk** [comment]
The SetupNavUsers will check whether the user you specified as -credential already exists.
If it does, it will not create the user. I see two options for you:
1. To reuse a user who is already in the database
2. to override SetupNavUsers.ps1 and use:
```
Get-NAVServerUser $ServerInstance -Tenant default | % { Set-NAVServerUser -ServerInstance $ServerInstance -Tenant default -UserName $_.Username -State Disabled -ErrorAction SilentlyContinue }
```
Before calling the default SetupNavUsers.ps1. This will disable all users (except for one SUPER user)
