### ISSUE TITLE
Error running script (Delete-NavApplicationObject) in container.

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1528]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I am getting an error trying to run a script in a container.  I suspect it maybe related to accessing a remote SQL server (#1518).  I am attempting step 2 in Task 9 of [Upgrading the Data to Business Central: Single-Tenant Deployment](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrading-the-data#CompSysTables)

I get the same error when running the Delete-NAVApplicationObject command from PowerShell after entering the container.

Any assistance would be appreciated.

> : [27590710] Unable to process table changes because the Microsoft Dynamics NAV Development Environment cannot connect to the specified Microsoft Dynamics NAV Server instance:
> Server Name: 
> erver Instance: 
> anagement Port: 0
> Microsoft Dynamics NAV Development Environment will detect a running server automatically.
> Check that:
> . The Microsoft Dynamics NAV Server is running
> . The management service is configured
> . The firewall is open for the management port if remote
> . The server is running with only one tenant
> . Microsoft Dynamics NAV Development Environment is running as Administrator, or
> . UAC is turned off.
> 
> at Delete-NAVApplicationObject, C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 473
> 

This is the container's hosts file (without the standard comments):
> 10.0.1.4 dbserver.containerhelper.internal
> 172.31.96.1 host.containerhelper.internal
 

```
$databaseName = 'vect001 upgrade'
$DatabaseServer = 'dbserver.containerhelper.internal'
$user = 'Docker'
$uPass = '6Hash######'

        Invoke-ScriptInBCContainer -containerName $config.Container -scriptblock {
            param ($databaseName, $databaseServer, $user, $uPass)
            Delete-NAVApplicationObject -DatabaseName $databaseName -DatabaseServer $DatabaseServer -userName $user -password $uPass `
                -Filter 'Type=Table;Id=470|824|825|827|828|829|1510' `
                -SynchronizeSchemaChanges Force -Confirm:$false 
```

**Scripts used to create container and cause the issue**
```
$sqlserver'; . 'c:\run\SetupDatabase.ps1'" } `
Clear-Host

$containerName = 'vect14017'
$password = '<password>'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '45' -country 'gb'
$databaseServer = 'dbserver.containerhelper.internal' #per #1518 
$databaseInstance = ''
$databaseName = 'vect001 upgrade'
$databaseUsername = 'Docker'
$databasePassword = '<password>'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = 'F:\License\NAV2018License.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -dns '10.0.1.4' `
    -updateHosts 
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.15
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.12
Docker Server Version is 19.03.12
Removing container vect14017
Removing vect14017 from host hosts file
Removing vect14017-* from host hosts file
Removing f:\bccontainerhelper\Extensions\vect14017
Fetching all docker images
ArtifactUrl and ImageName specified
Image internal:onprem-14.17.44663.0-gb-nodb already exists
Using image internal:onprem-14.17.44663.0-gb-nodb
Creating Container vect14017
Version: 14.17.44663.0-gb
Style: onprem
Multitenant: No
Platform: 14.0.44656.0
Generic Tag: 1.0.1.0
Container OS Version: 10.0.17763.1577 (ltsc2019)
Host OS Version: 10.0.17763.1577 (ltsc2019)
Using process isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file F:\License\BC14License.flf
Additional Parameters:
-v "F:\Clients\VECT001\Shared":C:\Shared
Files in f:\bccontainerhelper\Extensions\vect14017\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container vect14017 from image internal:onprem-14.17.44663.0-gb-nodb
fc8b7c7b785eb0c395ee608b34b9da74882a0b0c8049e88d736bbc01c5a07d3f
Waiting for container vect14017 to be ready
Initializing...
Setting dbserver.containerhelper.internal to 10.0.1.4 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.31.96.1 in container hosts file
Starting Container
Hostname is vect14017
PublicDnsName is vect14017
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 7DB673E07D01E8D3674BBDFBC7CF5BDB9C7316F7
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Container IP Address: 172.31.104.115
Container Hostname  : vect14017
Container Dns Name  : vect14017
Web Client          : http://vect14017/NAV/
Dev. Server         : http://vect14017
Dev. ServerInstance : NAV
Setting vect14017 to 172.31.104.115 in host hosts file

Files:
http://vect14017:8080/ALLanguage.vsix

Container Total Physical Memory is 28.0Gb
Container Free Physical Memory is 19.3Gb

Initialization took 145 seconds
Ready for connections!
Reading CustomSettings.config from vect14017
Creating Desktop Shortcuts for vect14017
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\140\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container vect14017 successfully created

Use:
Get-BcContainerEventLog -containerName vect14017 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName vect14017 to get debug information about the container
Enter-BcContainer -containerName vect14017 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName vect14017 to remove the container again
docker logs vect14017 to retrieve information about URL's again
Creation time 209 seconds
Creating User Docker
Assigning Permission Set SUPER to Docker```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
- does it happen all the time? YES
- did it use to work? outside of a container it works.

**Comment by freddydk** [comment]
Don't you need to specify -NavServerInstance as well? 
Looked in the docs - sorry, but I don't know a lot about these commands.

**Comment by GreatScott000** [comment]
Not normally but I have tried adding that and still have the problem.

**Comment by freddydk** [comment]
You tried to specify all 3 parameters?
When I look inside the compile-objectsInNavContainer - it specifies all 3

  -NavServerName localhost `
  -NavServerInstance $ServerInstance `
  -NavServerManagementPort "$managementServicesPort"

**Comment by GreatScott000** [comment]
I have and had the same results.  

```
$databaseName = 'vect001 upgrade'
$DatabaseServer = 'dbserver.containerhelper.internal'
$user = 'Docker'
$uPass = '6Hash######'

Delete-NAVApplicationObject -DatabaseName $databaseName -DatabaseServer $DatabaseServer -userName $user -password $uPass -Filter 'Type=Table;Id=470|824|825|827|828|829|1510' -SynchronizeSchemaChanges Force -Confirm:$false -NavServerInstance 'NAV' -NavServerName 'vect14017' -NavServerManagementPort 7045 -Verbose -SuppressElevationCheck Yes
```

> VERBOSE: Delete application objects from vect001 upgrade database.
> VERBOSE: Running command: & "C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\finsql.exe" --% Command=DeleteObjects,SynchronizeSchemaChange
> s=Force,Filter="Type=Table;Id=470|824|825|827|828|829|1510",LogFile="C:\Users\ContainerAdministrator\AppData\Local\Temp\NavIde\5e0c6a52-2d08-4775-a38c-1507c09c7
> 66d\naverrorlog.txt",ntauthentication=No,username="Docker",password="6Hash######",ServerName="dbserver.containerhelper.internal",Database="vect001 upgrade",NavS
> erverName="vect14017",NavServerInstance="NAV",NavServerManagementport=7045,SuppressElevationCheck="Yes" | Out-Null
> : [27590710] Unable to process table changes because the Microsoft Dynamics NAV Development Environment cannot connect to the specified Microsoft Dynamics NAV 
> Server instance:
> Server Name: 
> erver Instance: 
> anagement Port: 0
> Microsoft Dynamics NAV Development Environment will detect a running server automatically.
> Check that:
> . The Microsoft Dynamics NAV Server is running
> . The management service is configured
> . The firewall is open for the management port if remote
> . The server is running with only one tenant
> . Microsoft Dynamics NAV Development Environment is running as Administrator, or
> . UAC is turned off.
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Delete-NAVApplicationObject
>

**Comment by GreatScott000** [comment]
So it works from a BC install on the Docker Host so it has to be related to how the container is configured.


```
$databaseName = 'vect001 upgrade'
$DatabaseServer = 'dbserver.containerhelper.internal'
$user = 'Docker'
$uPass = '6Hash######'
$navServerInstance = 'BC140'
$NavServerName = 'localhost'

Delete-NAVApplicationObject -DatabaseName $databaseName -DatabaseServer $DatabaseServer -userName $user -password $uPass -Filter 'Type=Table;Id=470|824|825|827|828|829|1510' -SynchronizeSchemaChanges Force -Confirm:$false -NavServerInstance $navServerInstance -NavServerName $NavServerName -NavServerManagementPort 7045 -Verbose -SuppressElevationCheck Yes
```

> PS C:\windows\system32> 
> VERBOSE: Delete application objects from vect001 upgrade database.
> VERBOSE: Running command: & "F:\Program Files (x86)\Microsoft Dynamics 365 Business Central\140\RoleTailored Client\finsql.exe" --% Command=DeleteObjects,Synchr
> onizeSchemaChanges=Force,Filter="Type=Table;Id=470|824|825|827|828|829|1510",LogFile="C:\Users\todd.scott\AppData\Local\Temp\NavIde\1b74ad98-d3fa-40c0-bf6a-e6d0
> 10584142\naverrorlog.txt",ntauthentication=No,username="Docker",password="6Hash######",ServerName="dbserver.containerhelper.internal",Database="vect001 upgrade"
> ,NavServerName="localhost",NavServerInstance="BC140",NavServerManagementport=7045,SuppressElevationCheck="Yes" | Out-Null
> 
> PS C:\windows\system32>

**Comment by freddydk** [comment]
When running inside the container, you would set NavServerName to localhost (you are on the machine with the NavServer) and you should replace ntauthentication=No with ntauthentication=0

**Comment by GreatScott000** [comment]
NavServerName = localhost does not seem to correct the issue.  ntAuthentication is NOT a parameter on the [Delete-NAVApplicationObject](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/delete-navapplicationobject?view=businesscentral-ps) cmdlet.  It is put there by the Microsoft.Dynamics.Nav.Ide.psm1 that "translates" the cmdlet to a FINSQL command line.

Updated script...
```
$databaseName = 'vect001 upgrade'
$DatabaseServer = 'dbserver.containerhelper.internal'
$user = 'Docker'
$uPass = '6Hash######'
$navServerInstance = 'NAV'
$NavServerName = 'localhost'

Delete-NAVApplicationObject -DatabaseName $databaseName -DatabaseServer $DatabaseServer -userName $user -password $uPass `
    -Filter 'Type=Table;Id=470|824|825|827|828|829|1510' `
    -NavServerInstance $NavServerInstance `
    -NavServerName $NavServerName `
    -NavServerManagementPort 7045 `
    -SynchronizeSchemaChanges Force `
    -SuppressElevationCheck Yes `
    -Confirm:$false `
    -Verbose

```

**Comment by GreatScott000** [comment]
I have recreated the containers a number of times and was still having an issue.  Now it works!?!
