### ISSUE TITLE
Run-AlValidation can't run with multiple $previousApp

### ISSUE THREAD

**Issue by dkorinets** [microsoft/navcontainerhelper#1532]
Hey Freddy, 
I can't finalize successfully Run-AlValidation with an array of previous apps versions. 
Below, you can find the place where it happens. 
Looks like that in variable $previousAppVersions is going to save 2 lines of the array with the same key value. 
Is that something I missed, or a bug in code?    

![image](https://user-images.githubusercontent.com/31474116/101810061-0217b600-3b21-11eb-87f3-b03edec96890.png)

**Comment by dkorinets** [comment]
ah I see, coz I thought that might be multiple based on the example in your blog post:
"-previousApps @( "path/url to your previous version of the .app files"

Thank you for your fast response

**Comment by freddydk** [comment]
the reason for the array is that you put apps and library apps in apps and previousapps - but only one version of each.
