### ISSUE TITLE
[Question] Is it possible to generate permissionSets.xml for an extension using powershell?

### ISSUE THREAD

**Issue by ThierryPermentier** [microsoft/navcontainerhelper#1540]
Using build pipelines in DevOps, it would be usefull to have the possibility to generate permissionSets.xml file by using powershell for an extension. Now it is only possible in VSC.

**Comment by freddydk** [comment]
I don't think there is a cmdlet to do this.
There are some VS Code extensions which include this option and I think upcoming versions will have a new way to specify permission sets (not XML - even though the old probably will be supported for some versions as well).
