### ISSUE TITLE
Remove-BcContainer removes similarly named containers from hosts file

### ISSUE THREAD

**Issue by zorngiebel** [microsoft/navcontainerhelper#1547]
Hi,

we notices that when removing a container with "Remove-BcContainer", any similarly named (with an additional suffix) containers are removed from the hosts file:
![grafik](https://user-images.githubusercontent.com/32073858/102237717-3ca09a80-3ef5-11eb-826f-7438ea016610.png)

In this instance, the second container was named "CR19-TEST-123", and although it still exists and is running, it is not available and can no longer be accessed:
![grafik](https://user-images.githubusercontent.com/32073858/102237963-85f0ea00-3ef5-11eb-8f28-4109936bfd0c.png)

We are currently using BcContainerHelper v. 1.0.16

This can also be reproduced.

Is this a known issue and if so, is there any way to prevent this?

Thanks in advance.

**Comment by freddydk** [comment]
The reason for this is that ContainerHelper registeres a number of entries in the hosts file.
One for every tenant.
These are created as $containerName-$tenantName
in order for people to access those directly from webclient, web services, apis and more.

This means that I remove everything $container-*

if you use an _ instead or just no - then your hostname will stay.
