### ISSUE TITLE
Traefik enabled containers unable to download symbols - AAD Authentication with MFA

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/navcontainerhelper#1549]
**Describe the issue**
I have setup traefik and a bc container on an azure VM. Webclient works perfectly, but i am unable to download symbols.
I have MFA enabled and such MFA is used when logging into the WebClient.

It seems the problem is that VS code is not requesting a token and as such is unauthorized.

Is AAD at all supported for OnPrem containers through VS Code?

**Scripts used to create container and cause the issue**
```
New-BcContainer -accept_eula `
-containerName aadtest3 `
-artifactUrl 'https://bcartifacts.azureedge.net/OnPrem/17.0.16993.0/dk' `
-auth AAD`
-shortcuts CommonDesktopFolder `
-multitenant:$false `
-licenseFile "C:\Temp\BC17.flf" `
-Credential $credential `
-updatehosts `
-useTraefik `
-PublicDnsName servername.northeurope.cloudapp.azure.com `
-isolation Process `
-authenticationEMail 'xxx'


Create-AadAppsForBC -appIdUri https://servername.northeurope.cloudapp.azure.com/aadtest3/ -AadAdminCredential $credential
```

**Screenshots**
VS Code error:
![image](https://user-images.githubusercontent.com/968411/102351669-205d3600-3fa7-11eb-9fee-0f24cfe82e00.png)

Error from Container Event log:
![image](https://user-images.githubusercontent.com/968411/102351981-9497d980-3fa7-11eb-836f-22d8e357ec2c.png)

**Additional context**
- I've tried with multiple users in the same AAD, same error.
- I've tried resetting password.
- If i change authentication to NavUserPassword, it works with an ordinary BC user.

**Comment by JeppeBylov** [comment]
I suspect this might have something to do with it:
![image](https://user-images.githubusercontent.com/968411/102354895-7502b000-3fab-11eb-90d3-28ca914225f2.png)


**Does this mean that you cannot have a container that is accessible with AAD accounts with webclient AND also accessible from VS Code?**

**Comment by freddydk** [comment]
Yes

**Comment by freddydk** [comment]
It is hardcoded to go and authenticate towards BC cloud sandboxes

**Comment by JeppeBylov** [comment]
Is it a part of any pipeline to support this for OnPrem?

**Comment by freddydk** [comment]
I don't think so

**Comment by JeppeBylov** [comment]
I suspect it could be possible to do this if not running a Container, but ordinary NST with 2 instances - one for AAD and one for NavUserPassword.
But are there any known workarounds for containers?

**Comment by freddydk** [comment]
If you are using AAD for containers, you should still be able to use Username Password auth,
Just use the username/password used to create the container

**Comment by JeppeBylov** [comment]
> If you are using AAD for containers, you should still be able to use Username Password auth,
> Just use the username/password used to create the container

Just tried that suggestion, hit the same error:

**Container creation:**

`$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'NotMyPassword' -AsPlainText -Force)
New-BcContainer -accept_eula `
-containerName aadtest `
-artifactUrl $artifacturl `
-auth AAD `
-shortcuts CommonDesktopFolder `
-multitenant:$false `
-licenseFile "C:\Temp\BC17.flf" `
-updatehosts `
-Credential $credential `
-PublicDnsName NotTheRealServerName.northeurope.cloudapp.azure.com `
-useTraefik `
-authenticationEMail 'aad@email.dk `
-isolation Process`

**VS Code Launch.json: - Using admin credentials from container creation
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Your own server",
            "request": "launch",
            "type": "al",
            "environmentType": "OnPrem",
            "server": "https://NotTheRealServerName.northeurope.cloudapp.azure.com/",
            "serverInstance": "aadtestdev",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default",
            "port": 443
        }
    ]
}`

Gives me this error:
![image](https://user-images.githubusercontent.com/968411/102361370-72a45400-3fb3-11eb-9ac2-3ded915e6093.png)

**Comment by freddydk** [comment]
What is in customsettings.config as auth?

**Comment by JeppeBylov** [comment]
![image](https://user-images.githubusercontent.com/968411/102362348-9320de00-3fb4-11eb-92b9-ed0f72795c59.png)

This is from C:\Program Files\Microsoft Dynamics NAV\160\Service\CustomSettings.config

**Comment by freddydk** [comment]
Could you try to change that to NavUserPassword (after you have setup the container)
WebClient should still be setup for AAD

**Comment by JeppeBylov** [comment]
That did the trick!
Webclient now requests AAD login and i can download symbols..
And i can have multiple BC users - great!

Thanks Freddy
