### ISSUE TITLE
Support for passing the hashing method in the Sign-BcContainerApp function

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/navcontainerhelper#1550]
**Describe the issue**
Is actually not an error at all, but rather a new request. In the function Sign-BcContainerApp a signing of an extension takes place within the container. But you can only specify the timestamp server. It would be desirably, if one can indicate likewise still, which kind of the Hashes one would like to have. By default, this is SHA1, which is considered to be largely insecure. Here it would be desirable if you could also choose SHA256 or pass it somehow.

The command for the Sign Tool would not be more complicated for this.

**Scripts used to create container and cause the issue**
There are no scripts that lead to an error because it is a new request.

**Full output of scripts**
Of course, since there are no scripts, there is also no output

**Screenshots**
There are no screenshots.

**Additional context**

For example, the Sign Tool call could be to set the type of hash:

`signtool.exe sign /v /a /sm -fd sha256 /td sha256 /tr <Timestamp Server> <Extension Package Path>`

**Comment by freddydk** [comment]
A duplicate of #1497 

In this case, the only thing a code signing certificate does is to allow Microsoft to see who created the appfile and that the appfile wasn't tampered with from the time you signed it and until the time we are uploading to appsource.

It does NOT protect your .app file from being extracted and inspected - only runtime packages are safe in that regards.

I would not assume that this would be the primary area of attack for any hacker, trying to intercept .app files and inject malicious code and make sure that the SHA1 doesn't detect that.

I will update this to allow a parameter for that, but please don't think that there is any significant security risk in using SHA1.

**Comment by freddydk** [comment]
Shipped in 1.0.17

**Comment by freddydk** [comment]
There is a parameter on Sign-BcContainer called -digestAlgorithm. Set this to SHA256.
The default for that parameter settable in configuration $bcContainerHelperConfig.digestAlgorithm or in the configuration file.
default for the configuration is blank (same behavior as before)

Please let me know whether this works for SHA256 - I do not have access to the MS code signing cert's.
