### ISSUE TITLE
Question:  How to share DynamicsNAVKey between containers.

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1554]
In #1518 you said I could share a DynamicsNAV.Key file between containers 

> If using a foreign database, you could generate a DynamicsNAV.key on the host somewhere and share that to -myscripts, encrypted with the password of the databasecredentials for the external database - then all containers should use the same and always work.

Are you saying just to add this to my script?
`-myscripts @(c:\shared\DynamicsNAV.key)`

Then `New-BCContainer` will pick up this key rather than create a new one?

**Comment by freddydk** [comment]
Yes

**Comment by GreatScott000** [comment]
Thank you Freddy, that appears to work well.
