### ISSUE TITLE
Handling of Hungary artifacts

### ISSUE THREAD

**Issue by tfenster** [microsoft/navcontainerhelper#1559]
Since BC17 there are official artifacts for HU. Therefore [this](https://github.com/microsoft/navcontainerhelper/blob/master/BcContainerHelper.psm1#L44) is correct until BC 16 but not later. What would be a good way to support that scenario? Maybe add a version check [here](https://github.com/microsoft/navcontainerhelper/blob/master/Misc/Get-BCArtifactUrl.ps1#L47)?

**Comment by freddydk** [comment]
I have changed the mapping to only try the mapping if the specified country couldn't be found.
Mapping only happens with sandbox and only place I can see where this is odd is that if I request ALL artifacts for HU - then I get all HU artifacts and not a mix between w1 in earlier versions and hu later. If I request ALL artifacts for RO - then I get all W1.
I think searching for all artifacts across versions are very seldom though.

**Comment by freddydk** [comment]
Fix shipped in https://www.powershellgallery.com/packages/BcContainerHelper/1.0.18-preview292

**Comment by freddydk** [comment]
Shipped in 1.0.18
