### ISSUE TITLE
DownloadFile throws RemoteException 

### ISSUE THREAD

**Issue by mitrov** [microsoft/navcontainerhelper#1562]
**Describe the issue**
Since a couple of days (3 nights) one of our scripts fails with a remote exception:

System.Management.Automation.RemoteException: Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Der Remotename konnte nicht aufgelöst werden: 'bcartifacts.azureedge.net'"

..... so the remotename bcartifacts.azureedge.net could not be resolved

**Scripts used to create container and cause the issue**
Write-Host "Download-Artifacts ...."

$sasToken = "xxxxxx"

Download-Artifacts -artifactUrl (Get-BCArtifactUrl -type Sandbox -select Current -country ch) -includePlatform
Download-Artifacts -artifactUrl (Get-BCArtifactUrl -type Sandbox -select NextMinor -country ch -sasToken $sasToken) -includePlatform
Download-Artifacts -artifactUrl (Get-BCArtifactUrl -type Sandbox -select NextMajor -country ch -sasToken $sasToken) -includePlatform

**Additional context**
I just tried running the same script during the day and it worked without any issues.
We run the script as part of nightly scripts around midnight.  Any idea what could be causing this remote exception?

**Comment by freddydk** [comment]
Are you running Windows Server 2016?

**Comment by mitrov** [comment]
Windows Server 2019, Version 1809 (Build 17763.1577)

**Comment by freddydk** [comment]
I have seen downloads from azureedge.net fails occasionally, which is why there is a retry mechanism.
Could you try to send me the full output, so that I can see what gets tried?

**Comment by mitrov** [comment]
Last night the script had no issues  🤷‍♂️ 

I'll close this issue for now and reopen it as soon as it fails again
