### ISSUE TITLE
Ruleset Error When Running Run-AlCops for Multiple Apps

### ISSUE THREAD

**Issue by jimmymcp** [microsoft/navcontainerhelper#1563]
When running Run-AlCops for multiple apps (we found this running Run-AlValidation for multiple apps) we get a ruleset error:

An error occurred while loading the included rule set file C:\ProgramData\BcContainerHelper\a13d1f4b-1a0a-4109-
a465-5b1f686a9317\ruleset.json - Could not find a part of the path 'C:\ProgramData\BcContainerHelper\9e3b2879-ba9a-42e6-a75c-
128ea394703e\ruleset.json'.

This seems to be due to due to these lines in Run-AlCops.ps1

if ($rulesetFile) {
    $ruleset.includedRuleSets += @(@{ 
        "action" = "Default"
        "path" = $ruleSetFile
    })
}

On the first run the rulesetFile does not exist and is created to include the AppSourceCop ruleset file. For the second app, the ruleset file does exist and the above lines include the ruleset file itself. Causing the above error. Commenting out these lines has allowed us to call Run-AlValidation for multiple apps successfully.

**Comment by freddydk** [comment]
Fix shipped in https://www.powershellgallery.com/packages/BcContainerHelper/1.0.18-preview292

**Comment by jimmymcp** [comment]
That was quick, thanks! 🚀

**Comment by freddydk** [comment]
Shipped in 1.0.18
