### ISSUE TITLE
Issue with the Unpublish and Uninstall

### ISSUE THREAD

**Issue by mynavblog** [microsoft/navcontainerhelper#1568]
**Describe the issue**
Hi Freddy,

I know that can be a very narrow example - it turns out because of our mistake in naming the extensions but it may be worth checking.

Is it possible to add to UnInstall-BcContainerApp parameter with the publisher? In this case, if you have two apps with the same name and the same version but from two different publishers, you can have a problem uninstalling them. 

A second issue which I had with UnPublish-BcContainerApp is that if the uninstall is marked it does not "transfer" parameter with version and publisher to uninstall method - and I got an error to specify the version (even if it was specified)  

Best regards,
Krzysztof

**Scripts used to create container and cause the issue**
```
UnPublish-BCContainerApp -containerName eamtest -appName 'XXX' -unInstall  -publisher 'YYY' -version '1.2.0.0' 
UnPublish-BCContainerApp -containerName eamtest -appName 'XXX' -unInstall  -publisher 'ZZZ' -version '1.0.0.0' 

```

**Full output of scripts**
```
Uninstalling XXX from tenant default
Multiple published extensions match the provided arguments. You must specify additional information, such as publisher, version or tenant.
Multiple published extensions match the provided arguments. You must specify additional information, such as 
publisher, version or tenant.
...
```

**Screenshots**
![image](https://user-images.githubusercontent.com/37371997/102992344-55bfd180-451b-11eb-9104-4d8c20e7a5aa.png)

**Comment by freddydk** [comment]
Shipped in 1.0.18
