### ISSUE TITLE
Why red Output instead of error?

### ISSUE THREAD

**Issue by ChrisBlankDe** [Microsoft/navcontainerhelper#158]
If container creation (or any other docker daemon process) fails, the error will be red written in the console (See [here](https://github.com/Microsoft/navcontainerhelper/blob/920555d3d056782edc3392e1f2281922c7b633b8/HelperFunctions.ps1#L88) and [here](https://github.com/Microsoft/navcontainerhelper/blob/920555d3d056782edc3392e1f2281922c7b633b8/HelperFunctions.ps1#L2)). in this case the powershell thinks everything done fine.
Why not use `write-error`?

If the command ~does~ doesn't fail with `write-error` or `throw` its very hard or impossible to use in larger automations.

**Comment by freddydk** [comment]
I think your does in the second sentence should be doesn't.
It is on my list to go though the containerhelper and fix this, this is wrong.

**Comment by ChrisBlankDe** [comment]
I would be very happy to have this in the next release. Can i support you with a PR or did you already started?

**Comment by freddydk** [comment]
PR is welcome

**Comment by freddydk** [comment]
0.3.0.1 is released
