### ISSUE TITLE
NavMetadataNotFoundException after upgrade from 14

### ISSUE THREAD

**Issue by elweilando** [microsoft/navcontainerhelper#1586]
I don't know if this issue has an relation to bccontainerhelper, bcartifact.cache or docker.

I try to upgrade from an unmodified v14. I tried this to 15.2.39040,0, 16.5.15897.15953, 17.0.16993 and 17.2.19367.19735 and it ends always in the same error.

I follow exactly the instructions from

- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v16
- https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/upgrade/upgrade-unmodified-application-v14-v17

The steps complete all without errors. But after login I get in Eventlog always an NavMetadataNotFoundException.

It seems that no Metadata exists. Even if I try to get an table with ?table=36 I get 

Message (NavMetadataNotFoundException): RootException: NavMetadataNotFoundException
Das Metadatenobjekt Table 36 wurde nicht gefunden.

I use the BCContainerHelper for creating the instances and I use Azure SQL for the databases. I take the symbols from the bcartifact.cache folder and the corresponding version folder. All containers runs with this setup without errors.

Just the upgrade ends in the NavMetadataNotFoundException.

**Comment by freddydk** [comment]
Not sure I understand how you are following that with docker?
Are you installing version 15 inside the 14 container - or are you placing the database on the host?
I created this blogpost shortly after 15 was released: https://freddysblog.com/2019/11/24/upgrading-to-15-x-from-14-x-c-al-our-nav-techdays-2019-demo/ - that explains how to do this with docker.

**Comment by elweilando** [comment]
Thanks for the link to the blog post. It works now.
