### ISSUE TITLE
[Feature Request] Fail Pipeline on Cops warnings

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/navcontainerhelper#1591]
When using `Run-ALPipeline` I would like my pipelines to fail if one of the given cops has any warnings.
Note that I run my pipelines in gitlab using the -gitlab flag. 

But I think this could be useful for other platforms as well.

**Comment by freddydk** [comment]
In the next version, Run-AlPipeline has a parameter called failOn.
Default failOn is error - meaning that builds will fail on errors.
You can set it to warning to fail the build on warnings.

```
 -gitLab -failOn warning `
```

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 2.0.0
