### ISSUE TITLE
[Question] How to install apps on New-BcContainer?

### ISSUE THREAD

**Issue by NKarolak** [microsoft/navcontainerhelper#1594]
Sorry if it's mentioned somewhere, but I couldn't find it:

Is it possible to publish and install additional (our own) apps when running `New-BcContainer`, where I can simply specify any local app file paths?

If not, is there any convenient alternative, other than after `New-BcContainer`, copy the file(s) to the container's `my` folder and then run `Enter-BcContainer` to publish and install it/them from the `my` folder?

**Comment by freddydk** [comment]
Publish-BcContainerApp should do it all for you

**Comment by NKarolak** [comment]
Perfect, thanks for your quick help!
