### ISSUE TITLE
New-CsideDevContainer - warning

### ISSUE THREAD

**Issue by joemathis** [Microsoft/navcontainerhelper#16]
When using the `New-CSideDevContainer` with `-devImageName microsoft/dynamics-nav:devpreview` 
I expect and receive no warning. Everything worked.

When using the `New-CsideDevContainer` with `-devImageName microsoft/dynamics-nav:2017-na`
I get this warning:
>Export Objects (new syntax) to C:\DEMO\Extensions\Original-10.0.18976.0-na-newsyntax.txt
>Split C:\DEMO\Extensions\Original-10.0.18976.0-na-newsyntax.txt to C:\DEMO\Extensions\Original->10.0.18976.0-na-newsyntax
>WARNING: UnhandledErrorMessage
>A parameter cannot be found that matches parameter name 'ExportToNewSyntax'.
>At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.1.1.9\NavContainerHelper.psm1:1087 char:5
>+     Invoke-Command -Session $session -ScriptBlock { Param($filter, $o ...
>+     >~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    + CategoryInfo          : InvalidArgument: (:) [Export-NAVApplicationObject], ParameterBindingException
>    + FullyQualifiedErrorId : NamedParameterNotFound,Export-NAVApplicationObject

All on a server I created today, and after the warning everything is running as expected.

**Comment by freddydk** [comment]
Good point, the code should of course test whether the container is greater than 2017 before exporting to new syntax. - will fix that,

Thanks

**Comment by freddydk** [comment]
I have fixed this in the source - it will be in the next update to PS Gallery
