### ISSUE TITLE
Do not prune images when creating new ones

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#1606]
# The issue
We're creating a lot of images i parallell in a pipeline every night (if new version is released). Now and then there are some images that are failing with error similar to `##[error]unable to find image "sha256:d9318e1f43871e8d41854fc6adde882e51dcaca3c7aab074c139e0a1ca9e9511"`

This seems to be caused by one of the other image builds that just removed image `d9318e1f43871e8d41854fc6adde882e51dcaca3c7aab074c139e0a1ca9e9511` before that image being built.

## Scenario
The issue happens only with a specific timing, so it is quite hard to reproduce. 
But from what I've seen in the logs I think the scenario is something like this, simplified with me just having two images - current:se and current:nz:

1. Job 1 calls `docker rmi current:se -f` and that will remove the current:se image but keep the parent images since they are used by current:dk
2. Job 1 starts to build the new image with step 1/6
3. Job 2 calls `docker rmi current:nz -f` and that will remove the current:nz image and also all parent images, since they are not in use at the moment. Output below.
4. Job 1 proceeds to step 2/6 and now it expects that images that existed in step 1/6 still exists - but now they are removed and this fails. Output below.

## Output
Output from Job 1:
```
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Extensions
Copying Applications.SE
Untagged: current:se
f:\bcartifacts.cache\0lkiwjwi.pqj
Sending build context to Docker daemon  1.853GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.1637
 ---> 0f9096121e62
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/17.2.19367.20615/se
##[error]unable to find image "sha256:d9318e1f43871e8d41854fc6adde882e51dcaca3c7aab074c139e0a1ca9e9511"

```

Output from job 2:
```
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Extensions
Copying Applications.NZ
Untagged: current:nz
Deleted: sha256:46fcdb3050453489c56d2d1cdb8015cce0bfd11083a8b72071c944297a926186
Deleted: sha256:ba9c2e55537cd5eec5c079b769994786c9de5a110b9f52da1974e0d607c57f7f
Deleted: sha256:f0557561c27c113171dabb964f8983bc5e36ab1951529f852c39c16abb59a020
Deleted: sha256:b135babfc6cdb5a919b0b0386707a1a2805e99a1d02f980196e9d2be0d7081d6
Deleted: sha256:33d293423fc4facaa0ce4f6bb8aef1475f58a96bebb5b28056674d0938dc4ca7
Deleted: sha256:a5b1d112aeb1a0b26c69a42f53d61b1cc7861cbaeddd961a146d6c5f5aa3f16b
Deleted: sha256:20c4a2085a01e6776baa72255f4418ec23c87cd7ac0d746d3bcfecdac71dd0ce
Deleted: sha256:19069b8842d39fb3ab611a2ceb91742f6cafbed8d35f5374c2652de610f88a5d
Deleted: sha256:d9318e1f43871e8d41854fc6adde882e51dcaca3c7aab074c139e0a1ca9e9511
Deleted: sha256:1b661acb039965e2fd3d8c96a56d3fe0914f764178f3b711d2a88f048ffb7bb0
f:\bcartifacts.cache\zn55do5s.usl
Sending build context to Docker daemon  1.861GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.1637
 ---> 0f9096121e62
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/17.2.19367.20615/nz
 ---> Running in 1d4cd3f526fd
Removing intermediate container 1d4cd3f526fd
 ---> 95f6b60965df
Step 3/6 : COPY my /run/
 ---> a419c6a7bd87
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 38e83e7abd08
Step 5/6 : RUN \Run\start.ps1 -installOnly -includeTestToolkit -includeTestLibrariesOnly
 ---> Running in 6971c305167d
```

## Suggested solution
I've tracked this down to the following line of code in New-NavImage.ps1:
`docker rmi $imageName -f | Out-Host `

I would suggest changing by adding the --no-prune switch (read more in [docker docs](https://docs.docker.com/engine/reference/commandline/rmi/)):
`docker rmi --no-prune $imageName -f | Out-Host`

That would keep any parent images that are unused at the moment. Instead we let Flush-ContainerHelperCache.ps1 do the pruning later on, when all images are created.

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 2.0.0
