### ISSUE TITLE
Get-BCArtifactUrl - version number handled differently now?

### ISSUE THREAD

**Issue by ryancairnsy** [microsoft/navcontainerhelper#1609]
**Issue**
Using bccontainerhelper 1.0.19

When using Get-BCArtifactUrl previously we were able to use the exact Application build taken from the cumulative updates pages. For example 16.5.15941. I know this definitely worked last Novemember
Now this no longer returns a URL.

If we use a shortened 16.5 this does work and returns the URL

**Scripts used to create container and cause the issue**
```
1. Doesn't work:
Get-BCArtifactUrl -type onprem -version "16.5.15941" -country gb

2. Does work
Get-BCArtifactUrl -type onprem -version "16.5" -country gb
https://bcartifacts.azureedge.net/onprem/16.5.15897.15953/gb
```

**Additional context**
Is this an intentional change? Thanks

**Comment by freddydk** [comment]
Nothing has changed, artifacts has always been versioned by application build and not by platform build, but you cannot use the 3 digit version number from the CU page directly (a lot of former versions where this also doesn't work).
Use 16.5 - that works - for onprem - there will be only one.

**Comment by ryancairnsy** [comment]
Hi Freddy - that's fine although just to let you know that 16.5.15941 is the application build. I have always been using that full application build (not the platform one) so something seems to have changed for me the last month but I may have been using an older version of navcontainerhelper.

Can I just finally confirm that RTM is 16.0, 17.0 etc?

**Comment by freddydk** [comment]
![image](https://user-images.githubusercontent.com/10775043/104304786-1fe38c80-54cc-11eb-9e67-ab51a4ef9827.png)

Yes 16.0 is RTM - and there actually is two 16.0 builds, there was a hotfix deployed shortly after. The latest is RTM.
and 17.0 is RTM

**Comment by freddydk** [comment]
```
PS C:\WINDOWS\system32> Get-BCArtifactUrl -type OnPrem -country gb -select all -version 16
https://bcartifacts.azureedge.net/onprem/16.0.11240.12076/gb
https://bcartifacts.azureedge.net/onprem/16.0.11240.12085/gb
https://bcartifacts.azureedge.net/onprem/16.1.12629.12805/gb
https://bcartifacts.azureedge.net/onprem/16.2.13509.13779/gb
https://bcartifacts.azureedge.net/onprem/16.3.14085.14238/gb
https://bcartifacts.azureedge.net/onprem/16.4.14693.15090/gb
https://bcartifacts.azureedge.net/onprem/16.4.14693.15445/gb
https://bcartifacts.azureedge.net/onprem/16.5.15897.15953/gb
https://bcartifacts.azureedge.net/onprem/16.6.17046.0/gb
https://bcartifacts.azureedge.net/onprem/16.7.18411.0/gb
https://bcartifacts.azureedge.net/onprem/16.8.19389.0/gb
```
The 1:1 mapping with the CU doc page only works when it ends with a .0

**Comment by ryancairnsy** [comment]
Great thanks for the help - I didn't know about the -select all parameter very useful when in doubt!

**Comment by ryancairnsy** [comment]
Sorry Freddy just saw your screenshot - I am confused by the application build numbers. This is what I tend to use 
![image](https://user-images.githubusercontent.com/21360381/104305741-f6733280-54c4-11eb-83ed-5fcffa44ceb5.png)

**Comment by freddydk** [comment]
It seems like somebody turned them around in the doc. there.

**Comment by ryancairnsy** [comment]
Mystery solved. Definitely must be a recent thing - can you report it?

**Comment by freddydk** [comment]
If you can tell me what URL has the wrong info

**Comment by ryancairnsy** [comment]
https://support.microsoft.com/en-gb/help/4549687/released-updates-for-microsoft-dynamics-365-business-central-2020

**Comment by freddydk** [comment]
Sent this to the docs team.
thanks
