### ISSUE TITLE
Compile-AppInNavContainer | 401 Unauthorized

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#1610]
Freddy,

I try to set-up a pipeline that runs on my own backup. so i start new-navcontainer with my own backup.bak. that works fine. 
i run the container with auth = windows.
i install some apps, that works perfect. 

but on Compile of an app it goes wrong when downloading symbols:
![image](https://user-images.githubusercontent.com/48794854/104312660-33482500-54d7-11eb-9219-76c1a7946392.png)

![image](https://user-images.githubusercontent.com/48794854/104312738-4fe45d00-54d7-11eb-8757-d9db55f5a0ea.png)

i already added USER MANAGER\CONTAINERADMINISTRATOR: with the code below. 
![image](https://user-images.githubusercontent.com/48794854/104312822-6ee2ef00-54d7-11eb-9e0e-a37cf89eaf1d.png)

i have know idea which other user i need to add for the authorization to work on my custom backup.
some advice?

**Comment by freddydk** [comment]
I always request the script used to create the container and the full output of that.
That will answer the 3-4 questions I could write here.

**Comment by freddydk** [comment]
Did you try Username / password auth? (and provide the credentials to compile as well)
Windows auth is one of the common reasons for problems.

**Comment by hvandenborn** [comment]
the username / password auth works.

only i would guess that some user is created in the database with windows Auth? if i only could add that one i would be done...


Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user Build
Setting SA Password and enabling SA
Container IP Address: 172.21.112.106
Container Hostname  : MSBUILD141
Container Dns Name  : MSBUILD141
Web Client          : http://MSBUILD141/BC/
Dev. Server         : http://MSBUILD141
Dev. ServerInstance : BC
Setting MSBUILD141 to 172.21.112.106 in host hosts file

Files:
http://MSBUILD141:8080/ALLanguage.vsix

Container Total Physical Memory is 16.0Gb
Container Free Physical Memory is 10.6Gb

Initialization took 149 seconds
Ready for connections!
Reading CustomSettings.config from MSBUILD141
Set SQL Server memory limit to 7373 MB
Set TimeZone in Container to W. Europe Standard Time
Creating Desktop Shortcuts for MSBUILD141
Container MSBUILD141 successfully created

**Comment by freddydk** [comment]
It creates the windows user from the host.
Build is the username.
And it downloads the symbols in the context of the host, so if you create the container with the same username AND password as the Windows User on the host, it should work.
There are a lot of things that can make it fail though - one is if the machine cannot contact the AD Server.

**Comment by hvandenborn** [comment]
ok lets try that, Thnx
