### ISSUE TITLE
Failed validation because of null value, parameter source

### ISSUE THREAD

**Issue by PP1986** [microsoft/navcontainerhelper#1611]
Issue:

My app upgrade fails validation with the below error and I cannot figure out what is wrong.
Error is: Value cannot be null.
Parameter name: source

**Scripts used to create container and cause the issue**
https://www.dropbox.com/s/0gvl0zyj9qli68d/ValidationFailed.txt?dl=0

I used the latest BCContainerHelper (preview).

**Comment by freddydk** [comment]
Could you email me the IDYN B.V._ConnectIT 365_17.3.0.0.app file (freddyk at microsoft dot com) (you might need to rename to .txt)

**Comment by freddydk** [comment]
Issue was due to an added SqlIndex - problem occured during publish/upgrade.
