### ISSUE TITLE
Use the FilesOnly switch and/or add the InstallOnly environment variable

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/navcontainerhelper#1612]
**Describe the issue**
I discovered in the source code of the BcContainerHelper that you can set the switch "filesOnly". This is then passed to the container creation via the environment variables. But apparently not correctly. 

https://github.com/microsoft/navcontainerhelper/blob/4e35247976412dcfa71a097386fd1f7c2d6f1b3e/ContainerHandling/New-NavContainer.ps1#L1307-L1309

When I look at the code that is triggered by this, then various checks are made whether "filesOnly" is actually used. But none of the checks are true, even though the parameter is passed on. Am I doing something wrong here? 

https://github.com/microsoft/nav-docker/blob/3e99377394214accd5c21124f57f44683c073d9c/generic/Run/150-new/navinstall.ps1#L49-L59

My goal would actually be to just install the container, but not set it up, meaning not install a database etc. For this there is also a special parameter inside the container "installOnly". If I try to set it the same way as the "filesOnly" parameter, then it is also ignored. For this I simply used the following switch, but unfortunately without effect...

`-additionalParameters @("--env installOnly=$true")`

Parts of the code, which should not be executed according to the code, are run through. But I have set both parameters in parallel, so the following condition should not be true.

https://github.com/microsoft/nav-docker/blob/3e99377394214accd5c21124f57f44683c073d9c/generic/Run/150-new/navinstall.ps1#L325-L327

https://github.com/microsoft/nav-docker/blob/3e99377394214accd5c21124f57f44683c073d9c/generic/Run/150-new/navinstall.ps1#L49-L54

Am I doing something wrong in principle here, or does it just not work correctly with the environment variables "filesOnly" and "installOnly" within the container?

Or do I have to do something else to be able to work like this? Unfortunately I can't find any documentation about these environment variables, so I wanted to ask here if I'm doing something wrong.

**Scripts used to create container and cause the issue**
```
$securePassword = ConvertTo-SecureString -String "********" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "test", $securePassword

New-BcContainer -accept_eula `
                -accept_outdated `
                -assignPremiumPlan `
                -auth NavUserPassword `
                -containerName test-container `
                -doNotCheckHealth `
                -doNotExportObjectsToText `
                -filesOnly `
                -Credential $credential `
                -artifactUrl (Get-BCArtifactUrl -country de -storageAccount bcartifacts -version 17.2 -type OnPrem) `
                -additionalParameters @("--env installOnly=$true")
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.19-dev
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Fetching all docker images
Using image mcr.microsoft.com/dynamicsnav:10.0.14393.4046-generic
Disabling Health Check (always report healthy)
Creating Container test-container
Version: 17.2.19367.19735-de
Style: onprem
Multitenant: No
Platform: 17.0.19353.19730
Generic Tag: 0.1.0.24
Container OS Version: 10.0.14393.4046 (ltsc2016)
Host OS Version: 10.0.14393.4104 (ltsc2016)
WARNING: Host OS and Base Image Container OS doesn't match and Hyper-V is not installed. If you encounter issues, you could try to install Hyper-V.
Using process isolation
Using locale de-DE
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Additional Parameters:
--env installOnly=True
Files in C:\ProgramData\BcContainerHelper\Extensions\test-container\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container test-container from image mcr.microsoft.com/dynamicsnav:10.0.14393.4046-generic
316d4cf7e3582be1a73be151e8dd58e001b0b9806540ea5059a0991507919e17
Waiting for container test-container to be ready
Using artifactUrl https://bcartifacts.blob.core.windows.net/onprem/17.2.19367.19735/de
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\17.2.19367.19735\de\database\Demo Database NAV (17-0).bak
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 417 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.30.96.1 in container hosts file
Starting Container
Hostname is test-container
PublicDnsName is test-container
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 40193F196F98132CA6F09D35E5AB689C2ACB11FD
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating test as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Assign Premium plan for TEST
Container IP Address: 172.30.110.126
Container Hostname  : test-container
Container Dns Name  : test-container
Web Client          : http://test-container/BC/
Dev. Server         : http://test-container
Dev. ServerInstance : BC

Files:
http://test-container:8080/ALLanguage.vsix

WARNING: You are running a container which is 62 days old.
Microsoft recommends that you always run the latest version of our containers.

Container Total Physical Memory is 32.0Gb
Container Free Physical Memory is 2.7Gb

Initialization took 154 seconds
Ready for connections!
Reading CustomSettings.config from test-container
Creating Desktop Shortcuts for test-container
Container test-container successfully created

Use:
Get-BcContainerEventLog -containerName test-container to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName test-container to get debug information about the container
Enter-BcContainer -containerName test-container to open a PowerShell prompt inside the container
Remove-BcContainer -containerName test-container to remove the container again
docker logs test-container to retrieve information about URL's again
...
```

**Screenshots**
Screenshots don't make sense in this context. Error must be evident from the attached logs and options.

**Additional context**
- does it happen all the time?
  I have not managed to set this environment variable, at least so far, so yes.
- did it use to work?
  I have not managed to set this environment variable, at least so far, so no.

**Comment by freddydk** [comment]
filesOnly is work in progress - BcContainerHelper preview version.

filesOnly requires a new generic image - you are using the old generic images from mcr.microsoft.com/dynamicsnav:10.0.14393.4046-generic - you should switch to use the new ones (the ones that the new BcContainerHelper uses by default)

1.0.1.3 is being released as we speak. That version has support for filesOnly, meaning that the container will be created with all files, but nothing is installed.

Compile-AppInBcContainer has support for using these containers and if you use -CopySymbolsFromContainer it will grab the symbols from the container to avoid download.

I am also working on allowing you to create a files only container and using an online sandbox as the BC engine (for symbols, publishing and test running - again work in progress - a few weeks out).

I will blog about these things when they are done.

**Comment by FSharpCSharp** [comment]
> filesOnly is work in progress - BcContainerHelper preview version.

Sounds great, thanks for the info.

> filesOnly requires a new generic image - you are using the old generic images from mcr.microsoft.com/dynamicsnav:10.0.14393.4046-generic - you should switch to use the new ones (the ones that the new BcContainerHelper uses by default)

All clear! I will try it out.

> 1.0.1.3 is being released as we speak. That version has support for filesOnly, meaning that the container will be created with all files, but nothing is installed.

Unfortunately, I don't really understand that. What exactly are you referring to here?

Final question:
Is it then enough to specify "FilesOnly" in the future if you want to have a container that contains only the files and not a running BC instance and SQL database? For me such a container would be completely sufficient.

**Comment by freddydk** [comment]
1.0.1.3 is the generic tag (will be output when creating a container)
on your final question:
Yes!
