### ISSUE TITLE
Get-NAVAppRuntimePackage BC13 error AL1032 ... has the same target language as another translation file.

### ISSUE THREAD

**Issue by Phfo** [microsoft/navcontainerhelper#1615]
**Describe the issue**
Trying to make a runtimepackage for our BC13 app gives error AL1032 

**Scripts used to create container and cause the issue**
Get-NAVAppRuntimePackage -ServerInstance NAV -Name 'xxxxx' -Version '1.0.0.4' -Path 'xxxxx.app'

**Full output of scripts**
...
Extension compilation failed
error AL1032: Translation file '(en-US, /xxxxx.g.xlf)' has the same target language as another translation file.
error AL1032: Translation file '(en-US, /xxxxx.EN-US.xlf)' has the same target language as another translation file.
    + CategoryInfo          : InvalidOperation: (:) [Get-NavAppRuntimePackage], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.GetNavAppRuntimePackage

**Screenshots**
**Additional context**

**Comment by freddydk** [comment]
I would need the app and the exact version number to create a repro.
You can email these to freddyk at microsoft dot com.
Remember to rename the .app file to .txt (app files gets blocked)

**Comment by freddydk** [comment]
This has nothing to do with Docker and it isn't something I can do anything about.
You would get the same result if you install version 13 and try there.

Version 13 doesn't support having multiple translation files with the same target. The .g. one is created by the compiler and the other one if probably created by you, I don't know how you can handle this, sorry.

**Comment by Phfo** [comment]
Hi Freddy

Of course, I overlooked this, after deleting the extra en-us.xlf file it works.

Ok, thank you very much for your assistance.

Best regards
Philip Foncke

Van: Freddy Kristiansen <notifications@github.com>
Verzonden: dinsdag 19 januari 2021 8:04
Aan: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
CC: Philip Foncke <philip.foncke@sde.be>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/navcontainerhelper] Get-NAVAppRuntimePackage BC13 error AL1032 ... has the same target language as another translation file. (#1615)


This has nothing to do with Docker and it isn't something I can do anything about.
You would get the same result if you install version 13 and try there.

Version 13 doesn't support having multiple translation files with the same target. The .g. one is created by the compiler and the other one if probably created by you, I don't know how you can handle this, sorry.
