### ISSUE TITLE
Multiple dependencies failing in Run-AlValidation

### ISSUE THREAD

**Issue by renebrummel** [microsoft/navcontainerhelper#1616]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I have a dependency in my app which in turn depends on another app which depends on a third app. When I run Run-AlValidation I specify all three in the -installApps switch. The first two are installed correctly. The third one fails saying the codeinits in it's depending app are not available

**Scripts used to create container and cause the issue**
```
Run-AlValidation `
    -licenseFile $licenseFile `
    -installApps @("_Build\ForNAV_ForNAV Language Module_5.4.0.1.app", "_Build\ForNAV_ForNAV Core_5.4.0.1.app", "_Build\ForNAV_Customizable Report Pack_5.4.0.1.app") `
    -apps @("_Build\Red and Bundle_Multiple Report Layout Selector_2.0.0.0.app") `
    -affixes "red" `
    -countries "us"
```

**Full output of scripts**
```Publishing C:\ProgramData\BcContainerHelper\Extensions\bcserver\_ForNAV_ForNAV Language Module_5.4.0.1.app
Synchronizing ForNAV Language Module on tenant default
Installing ForNAV Language Module on tenant default
App successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bcserver\_ForNAV_ForNAV Core_5.4.0.1.app
Synchronizing ForNAV Core on tenant default
Installing ForNAV Core on tenant default
App successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bcserver\_ForNAV_Customizable Report Pack_5.4.0.1.app
Extension compilation failed
Tools/GetForNAVReports.Codeunit.al(39,23): error AL0185: Codeunit 'ForNAV Document Archive Mgt.' is missing
NavContainerHelper is version latest
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro
Docker Client Version is v20.10.2
Docker Server Version is v20.10.2
...
```

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/20247116/104507874-afca2900-55e7-11eb-8439-b2ec0c391539.png)

**Additional context**
- does it happen all the time? yes
- did it use to work? no

**Comment by freddydk** [comment]
Could you e-mail me the apps, then i Can try to make a repro.
Also, what version of bccontainerhelper are you using?

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: René Brummel <notifications@github.com>
Sendt: Wednesday, January 13, 2021 9:41:57 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Assign <assign@noreply.github.com>
Emne: [microsoft/navcontainerhelper] Multiple dependencies failing in Run-AlValidation (#1616)


PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

Describe the issue
I have a dependency in my app which in turn depends on another app which depends on a third app. When I run Run-AlValidation I specify all three in the -installApps switch. The first two are installed correctly. The third one fails saying the codeinits in it's depending app are not available

Scripts used to create container and cause the issue

Run-AlValidation `
    -licenseFile $licenseFile `
    -installApps @("_Build\ForNAV_ForNAV Language Module_5.4.0.1.app", "_Build\ForNAV_ForNAV Core_5.4.0.1.app", "_Build\ForNAV_Customizable Report Pack_5.4.0.1.app") `
    -apps @("_Build\Red and Bundle_Multiple Report Layout Selector_2.0.0.0.app") `
    -affixes "red" `
    -countries "us"


Full output of scripts

Synchronizing ForNAV Language Module on tenant default
Installing ForNAV Language Module on tenant default
App successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bcserver\_ForNAV_ForNAV Core_5.4.0.1.app
Synchronizing ForNAV Core on tenant default
Installing ForNAV Core on tenant default
App successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bcserver\_ForNAV_Customizable Report Pack_5.4.0.1.app
Extension compilation failed
Tools/GetForNAVReports.Codeunit.al(39,23): error AL0185: Codeunit 'ForNAV Document Archive Mgt.' is missing
NavContainerHelper is version latest
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro
Docker Client Version is v20.10.2
Docker Server Version is v20.10.2
...


Screenshots
[afbeelding]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F20247116%2F104507874-afca2900-55e7-11eb-8439-b2ec0c391539.png&data=04%7C01%7Cfreddy.kristiansen%40microsoft.com%7Cbf1956a88dbd446df6ab08d8b803abf6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637461673214908726%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xBVoKrT11Q4TEnhBhi1MFDXVRDrfwgyqbEKSs6LlJvo%3D&reserved=0>

Additional context

  *   does it happen all the time? yes
  *   did it use to work? no

**Comment by freddydk** [comment]
The apps in -installApps are available in our depot, so I tried a different app validation with these three with the latest version of BcContainerHelper:

![image](https://user-images.githubusercontent.com/10775043/104550646-9354dd80-5635-11eb-9056-e741a5dad0ba.png)

So, please include the full output of the validation (which includes information about BcContainerHelper versions, OS Versions etc. etc.)

**Comment by renebrummel** [comment]
I was thinking it had something to do with the apps I'm using. Can I also
get the apps from you depot? That would help.

**Comment by freddydk** [comment]
We cannot provide apps from the depot to partners, you will have to get those from the provider.
If you send me the apps you are using, I can try those.
They might be runtime packages, which should work for installApps - but runtime packages are very version dependent and can only be used with the same version as they were built for (like .fobs)

**Comment by renebrummel** [comment]
I have used the publishers app files and it works fine now. I had just used the .app files from my .alpackages folder.

You can find them here: https://ln.sync.com/dl/0dcd09db0/i2cahtvz-ryz8vvzb-24bvrabm-uxsvved4

**Comment by freddydk** [comment]
These might be symbols and not real apps.
Thanks for the explanation, other people might run into the same.
