### ISSUE TITLE
Problem with Build Pipeline and Run-AlPipeline

### ISSUE THREAD

**Issue by MBK75** [microsoft/navcontainerhelper#1618]
Hi Freddy, we are trying to upgrade our build pipelines to use BCContainerHelper instead of NAVContainerHelper.  However, we are having trouble with an error in the Run-AlPipeline script:

##[error]Directory 'c:\sources\..\_BuildPipeline' could not be found

The way our workspace for this project is structured is as follows:

.\ (root)
.\\_BuildPipelineScripts\CI.Yml
.\\_BuildPipelineScripts\scripts\ (all the PS scripts)
.\Extension1\
.\Extension2\
.\Extension3\
.\BaseExtension\

To account for this structure, I have fiddled with the scripts and parameters a bit - I think this may boil down to line 21 on the DevOps-Pipeline.ps1 script:

$baseFolder = (Get-Item (Join-Path $PSScriptRoot "..")).FullName

If I leave the Join-Path parameter as "..", then the container won't create.  The $PSScriptRoot would be .\_BuildPipelineScripts\scripts, so it would navigate up only to .\_BuildPipelineScripts\ and won't find the folders.  When I change this to navigate two directories up (to .\), then I get the error above with c:\sources\..\_BuildPipeline not being found.

The Run-AlPipeline script specifies this folder on line 221 I believe.

    New-BcContainer `
        -accept_eula `
        -containerName $containerName `
        -imageName $imageName `
        -artifactUrl $artifactUrl `
        -Credential $credential `
        -auth UserPassword `
        -updateHosts `
        -licenseFile $licenseFile `
        -EnableTaskScheduler:$enableTaskScheduler `
        -MemoryLimit $memoryLimit `
        -additionalParameters @("--volume $($baseFolder):c:\sources")

Is there a way to work with this directory structure?  I am puzzled by the error and will try to move our script files around, but there may be another way to fix it.

Thank you!

**Comment by MBK75** [comment]
Hi Freddy, please disregard.  This suddenly started working - I'm not sure what happened.  Sorry for the trouble.

**Comment by freddydk** [comment]
7 minutes for self-healing to work:-)

Have a nice weekend.
