### ISSUE TITLE
AL0132: 'Report' does not contain a definition for 'Copy Sales Document'

### ISSUE THREAD

**Issue by MaxFalcone** [microsoft/navcontainerhelper#1626]
Hello, I'm using navcontainerhelper in AzureDevops pipeline to build and test my app (using Run-AlPipeline cmdlet).
Normally pipeline is successfull, but from time to time it fails with the following error

> error AL0132: 'Report' does not contain a definition for 'Copy Sales Document'

If I just queue the same build again it will work.
I have a subscriber to the report in my extension. Report in base app is modified (it is BC14 so....)
Everithyng is running on-premise. Container is created with database restored from backup. Backup isn't changing between builds (it is only updated by another pipeline, so I can be sure of that).
In recent dev pipeline it fails 3 out of 8 builds.

Here is how the step of pipeline looks like
```yml
steps:
- task: PowerShell@2
  displayName: Create new container
  inputs:
    targetType: 'inline'
    script: 'Run-AlPipeline `
              -pipelineName MarkingCodes -baseFolder "$(Agent.BuildDirectory)" -memoryLimit 6G `
              -keepContainer -containerName ${{ variables.ContainerName }} `
              -artifact "https://bcartifacts.azureedge.net/onprem/14.8.38658.0/ru"
              -appFolders "$(Build.SourcesDirectory)\App" -testFolders "$(Build.SourcesDirectory)\Test" `
              -testResultsFile "$(Common.TestResultsDirectory)\TestResult.xml" -testResultsFormat XUnit `
              -createRuntimePackages `
              -buildArtifactFolder "$(Build.ArtifactStagingDirectory)" `
              -NewBcContainer { Param([Hashtable]$parameters) New-BcContainer -bakFile "${{ variables.BackupFile }}" -enableSymbolLoading -doNotExportObjectsToText -useBestContainerOS @parameters; Invoke-ScriptInBcContainer $parameters.ContainerName -scriptblock { $progressPreference = "SilentlyContinue" } } `
              -RunTestsInBcContainer { Param([Hashtable]$parameters) $parameters.Remove("extensionId"); $parameters.Add("testSuite", "${{ variables.TestSuite }}"); Run-TestsInBcContainer @parameters; }'
```
Log fom pipeline attached
[5.txt](https://github.com/microsoft/navcontainerhelper/files/5830900/5.txt)

**Comment by freddydk** [comment]
You are using an old BcContainerHelper and a very old generic image. I always recommend that people are using the latest, else it is hard to do any troubleshooting. This issue might not be related to this hough.

Do you know whether  'Copy Sales Document' report is available in the standard russian 14.8 or is this something that is only available in your special .bak file?

**Comment by MaxFalcone** [comment]
I'll update BcContainerHelper and try again. But not sure what can I do with the image. Am I missing som flag like `alwayspull` or something?
The reports are standard, but I don't think it's matter since it is a BC14 and it still has C/AL in it. All objects are compiled with dev environment running with `generatesymbolreference=yes` flag. This must be enough for extension to see an object and be able compile. Lots of other non-standard objects are used in our solution and none of them are causing similar problem.

**Comment by freddydk** [comment]
You should probably get a new generic automatically when upgrading bccontainerhelper
You should try to add a start-sleep to the newbccontainer override to see if this is something with symbol generation based on container startup.

**Comment by MaxFalcone** [comment]
I updated BcContainerHelper and image. Didn't help.
Then I added some sleep after New-BCContainer and it seems fine now... but I don't understand why.
Symbols are not generated on the container startup. They are just present in the backup, and the backup is the same.

**Comment by freddydk** [comment]
There is probably some stuff going on during the start of the service tier due to symbols.
Symbol generation might happen delayed (if you don't wait for the process before creating the BAK file).

Happy you found a workaround - it is not something I will do anything to fix in ContainerHelper.
