### ISSUE TITLE
[Question] Why manually assign generic images?

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#1633]
**Describtion:**

You once published a blog article about: "Moving the generic images". 

From this I took the following: Generic images are automatically chosen by the BcContainerHelper with the best osversion. 
You also stated that in a tweet -> Its now all automatic. At least I think, that is what it means.

https://twitter.com/freddydk/status/1335484239069011968

**Now to the actual question:** 

You can still choose your generic image manually, but should you? Is there a special case where you even need to specify it manually? The origin of that question lies in a colleagues idea of manually assigning the generic images per server? But I still don´t get it. Why assigning it manually when "everything" is automatic? 

Thanks in advance. 

SilentApproach

**Comment by freddydk** [comment]
The primary reason for manually selecting generic images or images would be if you create them yourself - or if you decide that you need the sql2017 version - or you find that an update of the generic image conflicts with something and breaks your pipeline, then you can select an old version - or you can select the preview of the next generic.
Majority should not though - they should just use what containerhelper selects.

**Comment by Silentapproach** [comment]
Ok, thanks. Is there some sort of version list for the generic images? I have not yet found one.

**Comment by freddydk** [comment]
get-bestgenericimagename returns the image that natches your os best
(get-bccontainerimagetags -imagename 'mcr.microsoft.com/businesscentral').tags returns all tags.
