### ISSUE TITLE
The file "Microsoft_Tests-ERM_17.0.16993.0.app" does not show any content

### ISSUE THREAD

**Issue by mckasp** [microsoft/navcontainerhelper#1637]
**Describe the bug**
I want to start with automated testing and therefore am experimenting with the Standard TestToolkit. I have downloaded all the Microsoft Standard tests and would like to look at the source code to learn how things are done. Just as an example: When I want to display the content of the file "Microsoft_Tests-ERM_17.0.16993.0.app" in the directory .alpackages it does not show any content. I also tried to open the app file with 7Zip which normally gives me access to the source code/al files. But with this file I get an error message in 7Zip that this is not an archive and therefore cannot be opened. If I do the same e.g. with the file "Microsoft_Base Application_17.0.16993.0.app" it gives me all the al files and I can look at the source code.

**To Reproduce**
Steps and to reproduce the behavior:
Create a docker container "OnPrem" version: 17.0.0.0 / CH -> do not use the parameter "-includeTestToolkit"
($artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '17.0.0.0' -country 'ch' -select 'Closest')
After the container is created use the powershell command "Import-TestToolkitToNavContainer -containerName xxx"

``` AL Code to reproduce the issue ```
not applicable

**Expected behavior**
I would like access to the al files (source code) of the Microsoft Standard tests.

**Screenshots**

![image](https://user-images.githubusercontent.com/28837885/103235720-117d6880-4943-11eb-868e-d897ad5b71fd.png)

![image](https://user-images.githubusercontent.com/28837885/103235741-1a6e3a00-4943-11eb-962e-c1a97895a781.png)

The app is installed. (I have added it in the app.json under dependencies in order to download the symbols)
![image](https://user-images.githubusercontent.com/28837885/103235644-e430ba80-4942-11eb-907e-f68cd4f3a329.png)

**5. Versions:**
 - AL Language: v6.1.381323
 - Business Central: Version: CH Business Central 17.0 (Plattform 17.0.16974.0 + Anwendung 17.0.16993.0)

**Comment by atoader** [comment]
I transferred the issue to the correct repository. That being said, have you published this application? I don't think test projects are published by default.

**Comment by freddydk** [comment]
If you are trying to see what the app contains, you can use

```
Extract-AppFileToFolder -appFilename $appFile -appFolder $tmpFolder -generateAppJson
```

it isn't just a .zip file.

**Comment by freddydk** [comment]
Also the files in .alPackages are just symbols.
If you are using default artifacts location, the ERM app file is here:
```
"C:\bcartifacts.cache\onprem\17.0.16993.0\ch\Applications\BaseApp\Test\Microsoft_Tests-ERM.app"
```
and the source file is here:
```
"C:\bcartifacts.cache\onprem\17.0.16993.0\ch\Applications\BaseApp\Test\Tests-ERM.Source.zip"
```
Just checked the 17.0 onprem ch artifacts - they work just fine

**Comment by mckasp** [comment]
@atoader Thank you for transferring the issue to the correct respository

@freddydk Thank you for this information. Understanding the context now I was able to use "Extract-AppFileToFolder". Now I can see the al source code :-)
