### ISSUE TITLE
Build failures 

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1644]
Hi Freddy 
Are you aware that the current builds in https://dev.azure.com/businesscentralapps/HelloWorld.AppSource and https://dev.azure.com/businesscentralapps/HelloWorld are failing with this error?

> Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden.

We were running through the CI/CD examples and getting the same error.

**Comment by freddydk** [comment]
I think there was a problem last night with downloading from blob store - a lot of pipelines failed with this.
A rerun later should solve the issue.

**Comment by freddydk** [comment]
Fix shipped in 2.0.5
