### ISSUE TITLE
CI/CD workshop pdf - improve section release pipeline

### ISSUE THREAD

**Issue by tobiaskluge** [microsoft/navcontainerhelper#1648]
**Describe the issue**
CI/CD workshop pdf -improvements for the release pipeline section
- Add an information, to create the specific container on the blob storage before running the deployment.
- Add a short note that "StorageConnectionString" should be added/checked in the Deployment group BuildVariables section before running the deployment.

PS: If you could upload the word doc e.g. using MD/ascii doc, I could create a pull request for this.

**Comment by freddydk** [comment]
Maybe I should convert the document to .md and allow for source control here - will see what I can do there

**Comment by OtterWhisperer** [comment]
Since this the official repository of Microsoft, I wanted to ask if the PDF (Markdown in the near future) file can also be extended to include instructions on how to integrate the pipeline into GitLab. TIA

**Comment by TheNCuber** [comment]
I took an effort and converted/reformated the current pdf version of the [aka.ms/cicdhol](aka.ms/cicdhol) by @freddydk into a 700 lines (!) markdown file including all the screenshots.

[Link to markdown](https://github.com/TheNCuber/navcontainerhelper/blob/master/CI_CD_Workshop.md)

If that is of any use, I am happy to open a pull request 🙂.

**Comment by freddydk** [comment]
@TheNCuber, please do:-)

**Comment by NAVspecialist** [comment]
Took a look at it - Nice work @TheNCuber!

**Comment by freddydk** [comment]
@TheNCuber - FYI - I will move the CI/CD workshop to a new github repo.
All checkins in NavContainerHelper repo goes through a 3 hour pipeline running a lot of tests - this should not be necessary for CI/CD workshop changes (didn't think of this:-))

**Comment by dannoe** [comment]
You could also exclude the docs folder and the markdown file from the pipeline trigger.

**Comment by freddydk** [comment]
https://github.com/microsoft/AL-Go is the replacement of the CI/CD HOL.
https://freddysblog.com/2022/04/27/migrating-to-al-go-for-github/ describes what to do to move from the HOL scripts to AL-Go for GitHub.
The HOL will no longer be maintained
