### ISSUE TITLE
Error creating container for version 17

### ISSUE THREAD

**Issue by naveksa** [microsoft/navcontainerhelper#1653]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
We assume our issue might have already been answerd in some other # and we just can't find it.
We appologize for that.

The issue is, that when we use the -select latest parameter in Get-BCArtifactUrl we get errors telling that extension compilation failed.
When we specify any version 17.x we get the same errors.
When we specify version 16.5 we don't get any errors.
What is a bit strange, is that in any case we get the container created and apparently they are correct and working.
So the problem is not that big. We just wonder if we could avoid the errors by changing somthing in our script.

The error we get is:

Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.3.0.0' could not be loaded. Symbols for the requested app Any by Microsoft 17.3.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.3.0.0' could not be loaded. Symbols for the requested app Any by Microsoft 17.3.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : ff8f77d16e7b5bcef024798c1015377c66b383de19f468836378ee819019ea02

**Scripts used to create container and cause the issue**
```
# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true
$accept_out  = $true

$containername = 'NAVEKSA173'
$artifactUrl = Get-BCArtifactUrl -version 17.3 -country dk -type OnPrem
# $artifactUrl = Get-BCArtifactUrl -country dk -type OnPrem -select Latest

$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated: $accept_out `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -auth Windows `
                 -alwaysPull `
                 -includeAL `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -additionalParameters $additionalParameters `
                 -licenseFile 'C:\Naveksa\BC17_5692763_JAN2021.flf'

Setup-BCContainerTestUsers -containerName $containername -password $credential.Password
```
**Full output of scripts**
```
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Removing container NAVEKSA173
Removing NAVEKSA173 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA173
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.17763.1577-generic
10.0.17763.1577-generic: Pulling from dynamicsnav
Using image mcr.microsoft.com/dynamicsnav:10.0.17763.1577-generic
Creating Container NAVEKSA173
Version: 17.3.20469.20605-dk
Style: onprem
Platform: 17.0.20458.20517
Generic Tag: 0.1.0.24
Container OS Version: 10.0.17763.1577 (ltsc2019)
Host OS Version: 10.0.17763.1697 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale da-DK
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Naveksa\BC17_5692763_JAN2021.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA173\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container NAVEKSA173 from image mcr.microsoft.com/dynamicsnav:10.0.17763.1577-generic
c1ac6033288b4ecf3be45aea73572cf83cd466786bc42dbc02d724774625970e
Waiting for container NAVEKSA173 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.3.20469.20605/dk
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\17.3.20469.20605\dk\database\Demo Database NAV (17-0).bak
Changing Database Server Collation to Danish_Greenlandic_100_CI_AS
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 345 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 192.168.160.1 in container hosts file
Starting Container
Hostname is NAVEKSA173
PublicDnsName is NAVEKSA173
Using Windows Authentication
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user vmadmin
Setting SA Password and enabling SA
Creating SUPER user
Assign Premium plan for NAVEKSA173\VMADMIN
Container IP Address: 192.168.171.242
Container Hostname  : NAVEKSA173
Container Dns Name  : NAVEKSA173
Web Client          : http://NAVEKSA173/BC/
Dev. Server         : http://NAVEKSA173
Dev. ServerInstance : BC
Setting NAVEKSA173 to 192.168.171.242 in host hosts file

Files:
http://NAVEKSA173:8080/ALLanguage.vsix

WARNING: You are running a container which is 78 days old.
Microsoft recommends that you always run the latest version of our containers.

Container Total Physical Memory is 16.0Gb
Container Free Physical Memory is 1.3Gb

Initialization took 143 seconds
Ready for connections!
Reading CustomSettings.config from NAVEKSA173
Creating Desktop Shortcuts for NAVEKSA173
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\170\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\170\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container NAVEKSA173 successfully created
Copy from container NAVEKSA173 (C:\Applications\System Application\Test\Microsoft_System Application Test Library.app) to C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA173\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA173\_Microsoft_System Application Test Library.app
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.3.0.0' could not be loaded. Symbols for the requested app Any by Microsoft 17.3.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
error AL1024: A package with publisher 'Microsoft', name 'Any', and a version compatible with '17.3.0.0' could not be loaded. Symbols for the requested app Any by Microsoft 17.3.0.0 could not be found in the database
Email/src/ConnectorMock.Codeunit.al(113,14): error AL0185: Codeunit 'Any' is missing
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\Invoke-ScriptInNavContainer.ps1:39 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : c1ac6033288b4ecf3be45aea73572cf83cd466786bc42dbc02d724774625970e
```

**Screenshots**

**Additional context**
Get-BCArtifactUrl -country dk -type OnPrem -select Latest = error
Get-BCArtifactUrl -version 17.3 -country dk -type OnPrem = error
Get-BCArtifactUrl -version 17.2 -country dk -type OnPrem = error
Get-BCArtifactUrl -version 17.1 -country dk -type OnPrem = error
Get-BCArtifactUrl -version 16.5 -country dk -type OnPrem = OK

Selecting version 16.5 end with the following:

Container NAVEKSA173 successfully created
Copy from container NAVEKSA173 (C:\Applications\system application\test\Microsoft_System Application Test Library.app) to C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA173\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA173\_Microsoft_System Application Test Library.app
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
App successfully published
Downloading C:\Users\vmadmin\AppData\Local\Temp\16\CreateTestUsers.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\NAVEKSA173\_CreateTestUsers.app
Synchronizing CreateTestUsers on tenant default
Installing CreateTestUsers on tenant default
App successfully published
Invoke GET on http://192.168.163.21:7048/BC/api/beta/companies?$filter=name%20eq%20%27CRONUS%20Danmark%27&tenant=default
Invoke POST on http://192.168.163.21:7048/BC/api/Microsoft/Setup/beta/companies(d13c4ad9-f0e8-ea11-bb41-001dd8b76c1a)/testUsers?tenant=default
Uninstalling CreateTestUsers from tenant default
Unpublishing CreateTestUsers
App successfully unpublished
Uninstalling System Application Test Library from tenant default
Unpublishing System Application Test Library
App successfully unpublished

By the way. How can be solve the comment:

WARNING: You are running a container which is 78 days old.
Microsoft recommends that you always run the latest version of our containers.

**Comment by freddydk** [comment]
I do not fix issues in NavContainerHelper anymore.
Please remove all containers, remove all versions of NavContainerHelper, restart PowerShell and install **BcContainerHelper**.
Then it should work.

**Comment by naveksa** [comment]
Sorry, apparently missing something.

Removed all containers, 
unistall NavContainerHelper - force
restarted

Running following script:

Install-Module BcContainerHelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true
$accept_out  = $true

$containername = 'NAVEKSA173'
# $artifactUrl = Get-BCArtifactUrl -version 16.5 -country dk -type OnPrem
$artifactUrl = Get-BCArtifactUrl -country dk -type OnPrem -select Latest

$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated: $accept_out `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -auth Windows `
                 -alwaysPull `
                 -includeAL `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -additionalParameters $additionalParameters `
                 -licenseFile 'C:\Naveksa\BC17_5692763_JAN2021.flf'

Setup-BCContainerTestUsers -containerName $containername -password $credential.Password


With result:

BcContainerHelper version 2.0.2
New-BCContainer : The term 'New-BCContainer' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\vmadmin\Downloads\CreateBCSandbox_DK_Artefact.ps1:20 char:1
+ New-BCContainer -accept_eula:$accept_eula `
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (New-BCContainer:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Setup-BCContainerTestUsers : The term 'Setup-BCContainerTestUsers' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try agai
n.
At C:\Users\vmadmin\Downloads\CreateBCSandbox_DK_Artefact.ps1:34 char:1
+ Setup-BCContainerTestUsers -containerName $containername -password $c ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Setup-BCContainerTestUsers:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by freddydk** [comment]
uninstall-module navcontainerhelper -allversions
uninstall-module bccontainerhelper -allversions
restart
install-module bccontainerhelper -force

**Comment by naveksa** [comment]
Great. Thanks a lot.
Everything seems to working now.
You know, as long as you don't fully understand, you are sometime forced to keep on asking.
Have a nice evening.
