### ISSUE TITLE
Issue with Publish-BcContainerApp

### ISSUE THREAD

**Issue by gregoral** [microsoft/navcontainerhelper#1654]
There appears to be an issue with Publish-BcContainerApp in version 2.0.2.

After the version of BcContainerHelper was updated to the latest version yesterday our build pipelines started failing.

The script that actually fails is Get-BcContainerAppRuntimePackage.
This is the error message:
> BcContainerHelper version 2.0.2
> No published package matches the provided arguments.

But the real issue is that the package was not installed by Publish-BcContainerApp.
This is what was called:
> Publish-BcContainerApp -containerName $containername -appFile $appFile -skipVerification:$true -sync -install -scope Global

Package was not published and there are no errors and no warnings.

When I tried to debug manually i found out that $extensionsFolder in line 90 is not defined anywhere in the function.
> $appFolder = Join-Path $extensionsFolder "$containerName\$([guid]::NewGuid().ToString())"

This is the error message I get when I call Publish-BcContainerApp manually:
> Join-Path : Cannot bind argument to parameter 'Path' because it is null.

It appears this error message is either suppressed or not generated when the script is called inside our Az DevOps pipeline.

**Comment by freddydk** [comment]
$extensionsfolder is a global variable defined in bccontainerhelper.psm1 - used in a lot of locations.
Any chance that I could get the full pipeline output?

**Comment by freddydk** [comment]
I would be mostly interested in knowing what $appFile is when calling publish-bccontainerapp?
2.0.2 does contain some changes to Publish-BcContainerApp, so I would very much like to get some more info.

**Comment by gregoral** [comment]
Hi Freddy, I assume what you are asking about is this:
"C:\Agent\_w\14\a\App\AdLoc.code\OurCompany_OurExtensionName_17.0.16993.2021012802.app"

The logs contain a lot of sensitive data, so I don't want to post that publicly.
But I can provide it to you, I just don't know what is the best way.

We reverted back to 2.0.0. and our pipelines are now working again.
I didn't have enough time yet to get to the bottom of the issue.

Global variables are not the best way to pass values to a function.
We're calling: CompileApp, SignApp, PublishApp, GetRuntimeApp in this order.

I will try to diagnose again later, but I need to setup a different environment  so others are not affected.

**Comment by freddydk** [comment]
The global variables are module variables used all over bccontainerhelper - not really passed to functions.
If you can email me the log as a text file to freddyk at microsoft dot com, then I will see if I can see anything.
Thanks

**Comment by gregoral** [comment]
In our build pipeline Publish-NavContainerApp gets called in this way:
Get-ChildItem -Path "C:\.....\AppFolder" | ForEach-Object {
        Publish-NavContainerApp -containerName $containername -appFile $_.FullName -skipVerification:$skipVerification -sync -install -scope Global
    }

**Comment by gregoral** [comment]
The issue appears to be in:
> HelperFunctions.ps1 :: CopyAppFilesToFolder

A comma split is performed:
> if ($appFiles -is [String]) { $appFiles = @($appFiles.Split(',').Trim() | Where-Object { $_ }) }

But our extension has a comma in the name of the extension.
hope that helps

**Comment by gregoral** [comment]
After additional testing, the problem is indeed in:
>HelperFunctions.ps1 :: CopyAppFilesToFolder

I changed the split character from comma to semicolon which is used to separate windows search path.
This solves the issue for us, but the core issue remains.

I have just tested this and I can create files and directories with ; ( semicolon ) in the name of a file and in the name of a directory, so semicolon is also not the best choice for a separator character.

Perhaps | ( pipe ) character would be a better choice or some other restricted character:
```< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
```
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file

But the real solution would need to consider quoted filenames:
>separators inside of quotes should be ignored

Consider this twisted case:
"C:\a;folder\An;App.app";"C:\folder;b\App;Two.app";

**Comment by freddydk** [comment]
Ok, yeah I was assuming that something like this was the issue.
I am indeed using comma as a separator to be able to publish a comma separated string of apps, did not consider that people would have , in the name of a file (actually thought it wasn't allowed).

**Comment by freddydk** [comment]
I have added a backwards compatibility fix.

**Comment by freddydk** [comment]
people with , in files names can specify multiple apps in an array : @( "file,1", "file,2" )

**Comment by freddydk** [comment]
2.0.3-preview328 shipped with a fix for this

**Comment by freddydk** [comment]
2.0.3 was shipped
