### ISSUE TITLE
bc container failed to start

### ISSUE THREAD

**Issue by CNAPilaro** [microsoft/navcontainerhelper#1661]
Upon installing the bc-container helper with this wizzard:
Invoke-Expression (New-Object System.Net.WebClient).DownloadString("http://aka.ms/bcdockerscript")

It successfully creates a container and runs smootly.
However if I turn off the container and try to start it again I get this error:

(HTTP code 500) server error - hcsshim::CreateComputeSystem d760c940a71265b52a0157fa633f4841447585af8a205ef23a2c46ebd67e0b23: The requested resource is in use. (extra info: {"SystemType":"Container","Name":"d760c940a71265b52a0157fa633f4841447585af8a205ef23a2c46ebd67e0b23","Owner":"docker","LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\d760c940a71265b52a0157fa633f4841447585af8a205ef23a2c46ebd67e0b23","Layers":[{"ID":"52283be9-3f4a-5087-8a4d-024bc61a28b9","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a9b2e2e7ac00b0add709afb7eec8c3f64c3fa5c372e79e2bdfeefdb031ee16f2"},{"ID":"3c73d09b-fbf6-57de-a1b1-36299d1639ec","Path":"C:\\ProgramData\\Docker\\windowsfilter\\aa2ec9a247365b1ef4408d14fe3d5fbf192ba4825d28a052f10ca2d1fc9d7289"},{"ID":"78c862dd-34b2-5867-bcce-f68b0f15e9a8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0125f9aff2ad81c4994e48487731734ae9c85c51fb33f2e0e06565c7f11cc069"},{"ID":"1ee10c2f-f52a-5f3a-a8e1-350f927483e1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f146edc02e5408871c6f20dec3a407dc4f1197cf72073528bb3c08e49e6a6553"},{"ID":"468e5eed-5ca3-58a5-83c6-f0b11a076d5c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\40c6367dc41296150af3313a4c3abe072a73f384fecc76eecc110cba01141f0f"},{"ID":"db05e7ba-c9f9-575c-a01a-18007038d15c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b3c82a5b6ecbbc3db918ad63e93af212b613d2a88c35a5a7eae2bdc34cee2372"},{"ID":"dd3dad10-1911-5d66-89e7-ca252c789407","Path":"C:\\ProgramData\\Docker\\windowsfilter\\562c2f792f011cf2fd02514fac7339637ee683fd5eda54b7e39d4ef82d127283"},{"ID":"338319cb-aa69-574a-9dcb-eb99ffe18695","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4e5d949ad39aa7308796668889451073055faa76be7130a8bad1a179cb4728cc"},{"ID":"cfbb5c22-d7a5-5bdc-90af-0b21d95a6c6b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fe4eaf0477846ddaa2bcf7e905422306bdaf71d8f9b7b89f0ce8655a362c0ba1"},{"ID":"dfad63be-c101-5972-b24f-cf14c03dafdf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\96bf1ee6f8140a9be4952b6f1c19dfa10b73a60455217a95003a72a592b985e1"},{"ID":"b35a7e59-7ef8-5a71-8f0f-b74eb1828938","Path":"C:\\ProgramData\\Docker\\windowsfilter\\863411aefe794289fce644c9598506a5fbd07da0060c67313b7392182da32aab"},{"ID":"518dcf46-ab39-54c8-ac42-940926686e91","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2d780f0e1d18742e46b64a55c7d2cf5fb22c6cdebcf3b3dbb93bc57fda0bbf34"},{"ID":"6a27d105-14ad-524d-a9c1-68f6674d0d82","Path":"C:\\ProgramData\\Docker\\windowsfilter\\aa6f6f73be94684c5307340ce4fce7247a7f37d9fcd5039664161c92bebf5a2c"},{"ID":"138a97dc-528b-5eba-8b87-e0dca7cea4c4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\314a4d141a548d747b9f6a49309bb77d143fb2d652fc0295ad75f18c21cb3c7f"},{"ID":"71054461-bf94-5d70-93bf-c52b4732e244","Path":"C:\\ProgramData\\Docker\\windowsfilter\\22ed261e1b1eacf2dcd0d000a514ff47cbdce772e0650a67c43c6dcb0bde07d1"},{"ID":"e7aaa78b-a331-5865-95fc-6444069bc34e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\74e00611d3b02d6301d24bcdb100dd89153695bfbc61ab79b75fc20e8ca11016"},{"ID":"b3d8bd75-c44e-53b4-9348-224074b91c7e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5756d030c2fe4197eac4e978e0cd2d695d91e5ce6f4352091d59da127bbaa173"},{"ID":"bff56bb4-b163-5463-97f3-dcfe0da06d97","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6cb74f71ef0996910521ac29246fe3540ce0cdf7366cd19a2f58bdb5487142d8"},{"ID":"e1466dea-3c5b-51c8-a5a8-4755393a3382","Path":"C:\\ProgramData\\Docker\\windowsfilter\\31e4d869a9840503e289b7b91d1f0d60e7b50f0d7fcac1e43628772df031140b"},{"ID":"662bf73d-e928-56fc-add3-43e167fe4304","Path":"C:\\ProgramData\\Docker\\windowsfilter\\49caba57af280772e03e2ff6c8b96d5b32ff3dcb2d9cd8452bb703b07c130d31"},{"ID":"ebe4a5a8-d396-5373-a0ff-b73b6b7a8fe7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f9d00e764187cc76326b2188094f3474bef443ea0c19eb27ff771acdaec7819f"},{"ID":"d8febbe0-51aa-5df1-96b5-a747cd9c4c1a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1fd40275709f02113b2a83832d83e1adeb857a6410c1d7121c100041ff4fe786"},{"ID":"7c857574-e922-53e7-b6c3-59bdd1e609e6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\05676885264f95b6ca0903f5832781bfef0546411831de969c1ca182f163ed01"}],"MemoryMaximumInMB":4096,"HostName":"bc","MappedDirectories":[{"HostPath":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\bcartifacts.cache","ContainerPath":"c:\\dl","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\bccontainerhelper","ContainerPath":"c:\\programdata\\bccontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\bccontainerhelper\\extensions\\bc\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["f826dcc5-cdc9-47c6-9edb-01130698a190"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\1fd40275709f02113b2a83832d83e1adeb857a6410c1d7121c100041ff4fe786\\UtilityVM"},"AllowUnqualifiedDNSQuery":true})

Same thing happens if i delete container and make a new one, works well until i stop it then the error occurs

Anyone got some clues on which files there seems to be locked

**Comment by freddydk** [comment]
Typically this error has been a memory issue

**Comment by CNAPilaro** [comment]
So delete and try again and again or is there a fix? Do i need to delete the image aswell?

**Comment by freddydk** [comment]
You didn't post the script, so I don't know whether it created an image or what you are trying to do.
You just posted the error and I say that that error is typically due to lack of memory.

Deleting and retrying probably won't fix that.

More memory, a restart of the computer, removal of other containers or other things that clean up memory might help.

This is mentioned here as well: https://freddysblog.com/2020/10/12/troubleshooting-business-central-on-docker/

**Comment by freddydk** [comment]
Assuming you make this work, closing the issue.
