### ISSUE TITLE
Copy-FileToBcContainer: allow to copy multiple files and recursive subforder structure

### ISSUE THREAD

**Issue by ti-jalopez** [microsoft/navcontainerhelper#1673]
I propose you a new functionalty to improve the process to copy files to the container.

When I copy dlls add-in into a "add-ins folder" of de BC Container, I need to copy source foder estructure because there are some setup files used by some dlls that requires get the setup file from the same folder where each dll is.

Nowadays, Copy-FileToBcContainer not allow to copy more than one file or recursive subfolders.

**Describe the issue**
To do that manually, I can do a script that select files from source folder recursively, but I need to recalculate de target forder comparing the source forder, the current source file (a subforder of the source folder) and extract this part of subdiretory to target path in container. For example, y my source folder has this structure:
```
 c:\temp\add-ins\**myaddin1**
 c:\temp\add-ins\**myaddin1\mydll1.dll**
 c:\temp\add-ins\**myaddin1\mydll1.dll.config**
 c:\temp\add-ins\**myaddin2**
 c:\temp\add-ins\**myaddin2\mydll2.dll**
```
And the target folders in container than I want:
```
 C:\Program Files\Microsoft Dynamics NAV\170\Service\Add-Ins\**myaddin1**
 C:\Program Files\Microsoft Dynamics NAV\170\Service\Add-Ins\**myaddin1\mydll1.dll**
 C:\Program Files\Microsoft Dynamics NAV\170\Service\Add-Ins\**myaddin1\mydll1.dll.config**
 C:\Program Files\Microsoft Dynamics NAV\170\Service\Add-Ins\**myaddin2**
 C:\Program Files\Microsoft Dynamics NAV\170\Service\Add-Ins\**myaddin2\mydll2.dl**l

```

I think if Copy-FileToBcContainer or a new command allows to copy multiple files with a recursive subforder search is more easy, because I don't need calculate the current subforder relative from source subforder if the new powershell process do that:

1. Copy source subfolder with subforder in a termorary folder (similar to https://github.com/microsoft/navcontainerhelper/blob/d9cb3b66e9a0dc510dac2a3b431b1f4ab4842c06/Misc/Copy-FileToNavContainer.ps1#L34, but using folder instead file).
2. In the script block that run in container use Copy-Item -Recurse and Remove-Item (temporary)  (similar to https://github.com/microsoft/navcontainerhelper/blob/d9cb3b66e9a0dc510dac2a3b431b1f4ab4842c06/Misc/Copy-FileToNavContainer.ps1#L43).  At this point, copy files recursively automatically creates de subfolder structure from source path, without calculate de relative path by code.

Maybe, you can add some params to Copy-FileToBcContainer for reuse current command that allows this new functionalities:

- New param: CopyMode with values:
    * "SilgleFile" : current mode, only copy a file
    * "MultiFile" : allow copy multiple files, but not -Recurse mode added
    * "Recuse": allow copy multiple files recursively

This is all.

Best regards,

José Antonio López
Datanet Consultores

**Comment by freddydk** [comment]
Copying files to a container is not very performant and is really a last way out.
For the add-ins, the best solution (IMO) is to share your c:\temp\add-ins to c:\run\add-ins in the container.
Then the SetupAddIns script in the generic image (https://github.com/microsoft/nav-docker/blob/master/generic/Run/SetupAddIns.ps1) will copy the add-ins to the add-ins folders.

This parameter should share your folder to the container.
```
-additionalparamaters @("--volume c:\temp\add-ins:c:\run\add-ins") 
```

You can also share your local add-ins folder directly to the add-ins folder of the service tier if you know the container path (you have the version number), then no copying is needed.

**Comment by ti-jalopez** [comment]
Ok @freddydk ,

I'll do that, it is clear a easy to do.

Thanks!
