### ISSUE TITLE
502 - Web server received an invalid response while acting as a gateway or proxy server

### ISSUE THREAD

**Issue by Egancc** [Microsoft/navcontainerhelper#168]
Anyone knows how to troubleshoot or resolve the issue above?

It appears when I tried to re-access Dynamics BC on Container Sandbox

thanks.

**Comment by freddydk** [comment]
We would need a lot more info to give any kind of guidance.
How is the container created?
What do you mean by re-access?

**Comment by Egancc** [comment]
Hi Freddy,

Thanks for your follow up.

You may proceed to close the case.


[cid:image004.jpg@01D0B8D9.97DA1410]


Esther Gan | Business Development Director
Awansoft Technology Sdn Bhd
B-10-11 Plaza Mont’ Kiara, 2 Jalan Kiara, 50480 Kuala Lumpur, Malaysia.
M: +6012 300 2000
O:  +603 6419 0010     F: +603 6419 0020
Careline: +6017 555 2100
Skype ID: esther.gan
E: esther@awansoft.biz<mailto:esther@awansoft.biz>  |  URL: www.awansoft.biz<http://www.awansoft.biz/>
Malaysia • Singapore • Australia
