### ISSUE TITLE
Convert-BcAppsToRuntimePackages container handling

### ISSUE THREAD

**Issue by lktraser** [microsoft/navcontainerhelper#1680]
**Describe the issue**
Big fan of the new functionality. I'd like to use it in my pipeline. Especially usefull with the new way to compile against Saas Evironments. But would it be possible to handle the container usage within the Convert-BcAppsToRuntimePackages cmdlet differently? During my build process I already have a container to use for this step and I would like not to create another one. Futhermore I'd like to take care of removal myself as well. I understand that this is a very handy all in one script but it doesn't really fit together with all the rest of bccontainerhelper which to me is more of a general toolbox.
I would propose to have a similar signature to other features: with -credentials for the container if it exists and if it doesn't the current form could still be used. That would also mean artifacturl and licensefile become optional parameters if the container already exists. Worst case scenario right now someone would remove a container they never ment to remove.

Thanks for considering, Leon

**Comment by freddydk** [comment]
For that, you have Get-BcContainerAppRuntimePackage to download a runtime package from an existing container.
I use that in run-alpipeline to download runtimepackages after test-publishing them.

**Comment by lktraser** [comment]
Okay let me describe my usecase further: 
I have an app that depends on apps from another partner that are available on appsource. So I create a -filesOnly Container, download symbols from saas, compile and then I would like to also create runtime-packages without publishing anywhere. This case doesn't have a test app so having a full container is just a waste.

**Comment by freddydk** [comment]
The Convert-BcAppsToRuntimePackages doesn't work with a filesonly container. It needs to publish the app. The only "thing" that can create a runtime package is the service tier.

**Comment by lktraser** [comment]
Aaaah, alright wrong assumtion on my end then. I'll plan this a different way then thanks for the information.
