### ISSUE TITLE
Question: where to find the bcContainerHelper.config.json?

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#1681]
@freddydk, in various of your blog posts you mention that the **bcContainerHelper.config.json** is stored in the folder _c:\programdata\bccontainerhelper_.

Wanting to get hold of this json file I cannot find it at that location.

Has its location been changed with the recent changes to the BcContainerHelper?

**Comment by freddydk** [comment]
Nope, if the file isn't there, you are using default settings.
This blog post: https://freddysblog.com/2020/10/10/bccontainerhelper-configuration/ describes how you can create the file and see default settings.
You should only create the file if you actually want to modify it, and only with the settings you want to change.

**Comment by lvanvugt** [comment]
Thanx, @freddydk. Clear, and do not need new glasses (yet).
