### ISSUE TITLE
Problem with Sort-AppFoldersByDependencies.ps1

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/navcontainerhelper#1687]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I have problem with function "Sort-AppFoldersByDependencies.ps1" during release. I am using this function in release pipeline and when this pipeline is started first time I get error. When I use redeploy everything works perfectly. So it happens only with new release. Parameters "$appFolders2=My Project" and "$baseFolder=C:\Agent\_work\r15\a\_Deploy My Project\output". 
Error appears at 103 line in "Sort-AppFoldersByDependencies.ps1".

I don't know what is wrong. Can you help me?

**Scripts used to create container and cause the issue**
```
Sort-AppFoldersByDependencies -appFolders $appFolders2.Split("|") -baseFolder $baseFolder -WarningAction SilentlyContinue
```

**Full output of scripts**
```
BcContainerHelper version 2.0.4
at Sort-AppFoldersByDependencies, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.4\AppHandling\Sort-AppFoldersByDependencies.ps1: line 103
at <ScriptBlock>, <No file>: line 314
[error]The property 'Name' cannot be found on this object. Verify that the property exists.
[error]At C:\Agent_PS_Scripts\Publish-AppToEnvironment.ps1:129 char:5
```

**Screenshots**

**Additional context**
- it happens with first run on new release

**Comment by freddydk** [comment]
Sort-AppFoldersByDependencies is sorting a number of folders with an app.json file inside.
In release pipelines I would expect people to use Sort-AppFilesByDependencies.
Could it be the same reason as this: https://github.com/microsoft/navcontainerhelper/issues/1677

**Comment by freddydk** [comment]
If you can provide me with a .zip file with a folder structure and a command to sort this folder structure (which fails), then I can see what the problem is and fix the issue, thanks

**Comment by fridrichovsky** [comment]
Hi Freddy,
I changed my code to Sort-AppFilesByDependencies. So I will see :-).
