### ISSUE TITLE
The example for "Create a SQL Server container and restore a .bak file" is missing the image name

### ISSUE THREAD

**Issue by Sven-Niehus** [Microsoft/navcontainerhelper#169]
Hi, 

[this script example](https://github.com/Microsoft/navcontainerhelper/blob/master/NavContainerHelper.md#create-a-sql-server-container-and-restore-a-bak-file) is missing the image name for the container that is being generated in line 4. 
I think that the image name should be _microsoft/mssql-server-windows-express_.

**Comment by freddydk** [comment]
That sounds right

**Comment by freddydk** [comment]
Fixed
