### ISSUE TITLE
The virtual machine could not be started  because a required feature is not installed

### ISSUE THREAD

**Issue by yrest** [microsoft/navcontainerhelper#1694]
**Describe the issue**
After recent Windows Updates on server 2019 in Azure create container fails

**Scripts used to create container and cause the issue**
$credential = New-Object PSCredential 
$artifactUrl = Get-BCArtifactUrl -type OnPrem -country gb -version 17.0.16993.0 -select Latest
New-BCContainer -alwaysPull -accept_eula -accept_outdated -auth UserPassword -Credential $credential -artifactUrl $artifactUrl -containerName bc170 -installCertificateOnHost -updateHosts -useBestContainerOS 

**Full output of scripts**
BcContainerHelper is version 2.0.5
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Fetching all docker images
Pulling image mcr.microsoft.com/businesscentral:10.0.17763.1697
10.0.17763.1697: Pulling from businesscentral
Digest: sha256:b6494c512dff5ee566ef2171641747c9b43902916ef6a0a6d729e4560050ac0f
Using image mcr.microsoft.com/businesscentral:10.0.17763.1697
Creating Container bc170
Version: 17.0.16993.0-gb
Style: onprem
Multitenant: No
Platform: 17.0.16974.0
Generic Tag: 1.0.1.3
Container OS Version: 10.0.17763.1697 (ltsc2019)
Host OS Version: 10.0.17763.1757 (ltsc2019)
Using hyperv isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\bc170\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc170 from image mcr.microsoft.com/businesscentral:10.0.17763.1697
c860c0819c7364c09faa7aef0000ef58b0e728c47feee1c5e55555ff9ee84235
DockerDo : docker.exe: Error response from daemon: hcsshim::CreateComputeSystem c860c0819c7364c09faa7aef0000ef58b0e728c47feee1c5e55555ff9ee84235: The virtual machine could not be started 
because a required feature is not installed.
(extra info: {"SystemType":"Container","Name":"c860c0819c7364c09faa7aef0000ef58b0e728c47feee1c5e55555ff9ee84235","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\Progra
mData\\docker\\windowsfilter\\c860c0819c7364c09faa7aef0000ef58b0e728c47feee1c5e55555ff9ee84235","Layers":[{"ID":"9c21ce22-c67b-583b-9974-e909a3a178eb","Path":"C:\\ProgramData\\docker\\window
sfilter\\93fe8673fc011ce41ae04e173fe8044697665a908642b66c600bf83925c6b09e"},{"ID":"073a3fc7-6eab-56e4-a599-773c6e0accaa","Path":"C:\\ProgramData\\docker\\windowsfilter\\2acc0aec6cfb4425f8cd2
8c9d960152a964f20d6d3c5b0ae3ee2609f93df961f"},{"ID":"9e531cb1-d124-524b-b874-977ad88cf88b","Path":"C:\\ProgramData\\docker\\windowsfilter\\0fb34efc6eb61593fa8f5fd4703dffb45e0dd4c8c3dfe992611
72880749760af"},{"ID":"a492c43d-4c44-5c6b-a2e2-bfa159014850","Path":"C:\\ProgramData\\docker\\windowsfilter\\0546890059e80e612c1e879426fc33742762627cdf346b4cce1561989ed4695d"},{"ID":"1a280f9
6-c3f3-5e11-abf6-97a72ee7dbd8","Path":"C:\\ProgramData\\docker\\windowsfilter\\e734386f94675cda47c2a7f6a7ea67742803bed49466f120c92de9ffe3daf623"},{"ID":"dfcbcd74-3640-5f8f-b07e-4f2ad0e2acec"
,"Path":"C:\\ProgramData\\docker\\windowsfilter\\622542efd95cc5e43765df51e5d6fec6b10fdaffa1166a7940e7d1437699d6ac"},{"ID":"a05c75f4-f3d4-57aa-9fd9-50f31a79711e","Path":"C:\\ProgramData\\dock
er\\windowsfilter\\cecfddccc8b4ed5edc0897ed67fa6d403fac9d51d859f0b1f9185eeeff57db2a"},{"ID":"ce891f84-c95c-5813-9c6f-6ebabaf594b6","Path":"C:\\ProgramData\\docker\\windowsfilter\\d84dc1b82fe
363a24c9deaba69eb26608a5d1d8602f132b70cbe16cca69d357c"},{"ID":"84aaf90a-3928-53cd-80ad-3221c6910d22","Path":"C:\\ProgramData\\docker\\windowsfilter\\636573b7f320b55cea614fe5ed898dbed7c6167ef
8bcec53120eb55250290ca5"},{"ID":"fd17d5ad-d06c-5ac5-a2b6-da7c5c2472a9","Path":"C:\\ProgramData\\docker\\windowsfilter\\4fca2605b59811b69b797a0f76c699faa611cab41fcd099cc2cdc06c7b7459dd"},{"ID
":"a921d5f9-9ef3-5a60-a2c5-501f75dd287d","Path":"C:\\ProgramData\\docker\\windowsfilter\\68aa4742615f23758cad240b890a2dcee70edc8c6576c40617ad77076b718673"},{"ID":"c8edcc79-5eb3-577e-a085-133
e2d8b5e83","Path":"C:\\ProgramData\\docker\\windowsfilter\\45ea9a7848c492f76450e6dd6ae66179690a1e93964d15f05d5cde3b564ae315"},{"ID":"952f7e05-8d5e-5348-85ed-39f4f6f18c34","Path":"C:\\Program
Data\\docker\\windowsfilter\\019748a0e59326f2bac9923c65c573df08e236c7b40d7741b45fb839d9e5285a"},{"ID":"ff1ee8b6-5b4b-50b9-b125-44d1b670147c","Path":"C:\\ProgramData\\docker\\windowsfilter\\e
a86070ec844ea48478ea610b626bf61b7db7455cf92d3c5e524c69101f72bd2"},{"ID":"9fb7f6cb-84da-5c36-b6de-db205ae54641","Path":"C:\\ProgramData\\docker\\windowsfilter\\47f50475f01b1187c71b885df1eba14
d4ccf345c60a4896e992a97fb38e8590a"}],"MemoryMaximumInMB":8192,"HostName":"bc170","MappedDirectories":[{"HostPath":"c:\\bcartifacts.cache","ContainerPath":"c:\\dl","ReadOnly":false,"Bandwidth
Maximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0
,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\bccontainerhelper","ContainerPath":"c:\\programdata\\bccontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"Creat
eInUtilityVM":false},{"HostPath":"c:\\programdata\\bccontainerhelper\\extensions\\bc170\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtil
ityVM":false}],"HvPartition":true,"EndpointList":["19C5136F-A677-4E26-9807-9DF599976DD6"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\docker\\windowsfilter\\ea86070ec844ea48478ea610b626bf61b7
db7455cf92d3c5e524c69101f72bd2\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).
ExitCode: 125
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav= --label version=17.0.16993.0 --label platform=17.0.16974.0 --label country=gb --env 
artifactUrl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/gb --env licenseFile="" --name bc170 --hostname bc170 --env auth=NavUserPassword --env username="admin" --env ExitOnError=N 
--env locale=en-GB --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume 
"C:\ProgramData\BcContainerHelper\Extensions\bc170\my:C:\Run\my" --isolation hyperv --restart unless-stopped --env filesOnly=False --memory 8G --env enableApiServices=Y --env useSSL=N 
--volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AFMAUwBpAEIAaQBmAFoAQQBRAGMAcgBGAEgALwBNAE0ASgBBAGMAaABaAGcAPQA9AHwAYQA5ADcA
NAAxAGYAYwA2AGIAZgA4ADAAMABiADAAYwBiADcAYgA4ADUAMAA2ADMAYQA5AGEAMwBmADQAYwAyAGIAYwA3AGEAOQA1ADIAOQAzAGUAZQA2ADAANgBiAGEAYQBlADgAMwBhAGQANABjADQAYwBhAGMAMQA2ADQAZgA= --env 
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral:10.0.17763.1697
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ContainerHandling\New-NavContainer.ps1:1613 char:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Additional context**
- does it happen all the time?
Restart, clean up does not help

- did it use to work?
Up until yesterday.

**Comment by freddydk** [comment]
You upgraded your Windows Version before we managed to publish generic images for the new Windows Version.

You have 3 options
1. wait until generic images for the new windows version is published (running right now)
2. install hyperv
3. specify -isolation process

number 3 is by far the easiest

**Comment by yrest** [comment]
Thanks Freddy! Yellow Warning on process isolation threw me off, but yeah, it works perfectly! :) We didn't upgrade our Windows server, Microsoft pushed new updates on Tuesday and they applies automatically. When do you think new images will be available?

**Comment by freddydk** [comment]
Might already be done - else it will happen within the next hours.
