### ISSUE TITLE
Quick Question - Al-Pipeline installTestApps parameter

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#1698]
Should using a URL for for the installTestApps parameter work?  I am trying to use a url for a build artificat from another organisation/pipeline (still belongs to us) and getting an error.

**Comment by GreatScott000** [comment]
I resolved this but use an Azure storage link instead.  Don't know if it was a permissions issue or not.

**Comment by freddydk** [comment]
Some of the devops links requires authentication and the pipeline doesn't have this built in.
If you have a URL, which requires some kind of auth, the solution is to download to a folder and transfer the local file.
