### ISSUE TITLE
Suggestion: Separate all functions in the psm1 to individual files

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/navcontainerhelper#17]
Would it be an idea to separate all functions in the psm1 file to all individual files?
It would make the module somewhat more readable in my opinion.. .

**Comment by freddydk** [comment]
Yeah - that is a good idea - I will do that.

**Comment by waldo1001** [comment]
Just a hint - this is how I created my PSM1 file..
https://github.com/waldo1001/Cloud.Ready.Software.PowerShell/blob/master/PSModules/Cloud.Ready.Software.NAV/Cloud.Ready.Software.NAV.psm1

I also have scripts to update my manifest with the functionnames .. (to automate publishing to the gallery) .. same principle..

**Comment by freddydk** [comment]
Thanks, I decided to go with the same mechanism already in place for the other WindowsPowerShellScripts (from the DVD).
For publishing, I have a private script for the publishing piece which automatically generates the .psd1 based on the .psm1
The split is now checked in.
