### ISSUE TITLE
Traefik and snapshot debugging

### ISSUE THREAD

**Issue by chrischbo** [microsoft/navcontainerhelper#1702]
Hi,

in a local docker environment it is possible to do snapshot debugging but if it comes to a traefik remote container I can't access the instance. The snapshot debugger isn't triggered. How to setup the port forwarding for 7083 in the New-NavContainer command? Any hints for this?

Thx in advance
Christian

**Comment by tfenster** [comment]
According to https://twitter.com/pborringms/status/1354146742795689988?s=20 this is not (yet) possible in a container. Are you sure it works locally? The traefik part should be fairly easy

**Comment by chrischbo** [comment]
Sorry for missing your twitter post on this.
And yes it worked in a local environment (type sandbox) of course without traefik

**Comment by tfenster** [comment]
No problem. Could you share step by step how you get it to work in the container? Either here or via email, whatever works better for you. I tried a couple of months ago when the snapshot debugger came out but couldn't get it to work. If we can get it to work locally, I would look into the traefik enablement

**Comment by chrischbo** [comment]
Nothing special. Set up a new local docker container, published my app, set breakpoints in vs code, added snapshot config to launch.json:
{
            "name": "snapshotInitialize: Your own server",
            "type": "al",
            "request": "snapshotInitialize",
            "environmentType": "Sandbox",
            "server": "http://bc174de",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "breakOnNext": "WebClient"
        },

Start snapshot debugging (F7 in VS Code).
On the next new session a message will be shown:
 
![image](https://user-images.githubusercontent.com/15926999/108033784-cde6d700-7034-11eb-8634-0f7b7f5231d8.png)

Used AL Language in VS Code (6.5.413786)

**Comment by tfenster** [comment]
@chrischbo yeah, it works! @freddydk Not sure if that was intentionally fixed, but it looks good now :) PR will follow
