### ISSUE TITLE
[QUESTION] Build Container with artifacts from a network drive.

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#1703]
Describing the 'issue'.

I don´t know if that is a common use case or if that is even possible, but we want to supply every docker container that we build with artifacts which we pre-downloaded on a network-drive. So far everything we tried worked pretty well, BcContainerHelper pulled the artifact from the network drive and worked with it. Except when it wanted to write something to the network drive, which is (as far as I know) not possible. Then a colleage came up with an idea: mklink

mklink /D C:\temp11111 \\server\share\foldername\

We used that command to create a folder on our local drive that is virtually linked to that same folder on the network drive. 
It still doesn´t work. Seemed like that there is some sort of permission problem. 

Is there any way to deal with that scenario, building a docker container with BcContainerHelper based on an artifact that´s located on a network drive? 

Thanks in advance.

**Comment by freddydk** [comment]
BcContainerHelper tries to signal the lastused timestamp like this:

try { [System.IO.File]::WriteAllText((Join-Path $platformArtifactPath 'lastused'), "$([datetime]::UtcNow.Ticks)") } catch {}

That shouldn't fail - what error do you get?

**Comment by Silentapproach** [comment]
BcContainerHelper is somehow not allowed to write the file. There is some sort of permission problem, but that´s not something I can manage. My colleage whose managing the permissions, gave the docker user, basically everything, full access. I can try to recreate the error tomorrow and send the error message.

**Comment by Silentapproach** [comment]
So we figured it out, it was a problem with our permissions. Everything is set now and we´re runnning containers from our network drive.
