### ISSUE TITLE
Permission Error "Azure AD User Management"

### ISSUE THREAD

**Issue by nickrobbo** [Microsoft/navcontainerhelper#171]
Hi, I have the following situation:

- Create container for NAV 2017 CU5 GB. Using Windows Auth.
- Container successfully created checked license is applied in C Side Dev environment.
- Try to open the Web/Windows client and get the following error:
- "You do not have the following permissions on CodeUnit Azure AD User Management: Execute"
- I have checked in SQL and my user is there, with SUPER permissions.
Is there anything else I can check to resolve this error?

**Comment by freddydk** [comment]
Looks like that permission is missing in your license. Not sure why it is needed, but it doesn't seem to be related to docker.

**Comment by nickrobbo** [comment]
Right OK, this is strange. We are running this license in both our development and live environment and have never had this error.

**Comment by freddydk** [comment]
What is the command you use for creating the container?

**Comment by nickrobbo** [comment]
I am using this extension:

https://marketplace.visualstudio.com/items?itemName=NAVBaaS.git

so I don't have visibility of the command but I do know it is using the navcontainerhelper.

**Comment by freddydk** [comment]
Ok, could you try manually to create the container using new-navcontainer yourself.
It might be setting up test users or like which causes this.

**Comment by richardrobberse** [comment]
It is not creating test users, if needed I can provide the code that creates the container.

**Comment by freddydk** [comment]
Just searched 2017-cu5-gb for usages of codeunit 9010 - doesn't really show anything.
for bcsandbox however - there are a lot of situatoins where 9010 is called.
Could you do docker inspect containername and send the labels and the environment variables?

**Comment by nickrobbo** [comment]
I have attached the sections from the docker inspection command, if you need any other parts let me know.  I have just added the labels and environment variables. 

[docker-test-container.txt](https://github.com/Microsoft/navcontainerhelper/files/2216366/docker-test-container.txt)

**Comment by nickrobbo** [comment]
I think there is definitely an issue with the license, I don't think this is an issue with any of your functions.  I will check my license with our partner. Thanks for your help anyways.  I will close this issue.
