### ISSUE TITLE
UploadImportAndApply-ConfigPackageInBcContainer doesn't work with filename

### ISSUE THREAD

**Issue by martinm1000** [microsoft/navcontainerhelper#1710]
**Describe the issue**

Hi, I'm new here and playing with the scripts and BC, and when specifying a package file to the UploadImportAndApply-ConfigPackageInBcContainer command, the script fail :

**Scripts used to create container and cause the issue**
```
UploadImportAndApply-ConfigPackageInBcContainer `
  -containerName test1 `
  -configPackage .\PackageTESTA.rapidstart
```

It fails with:
```
UploadImportAndApply-ConfigPackageInBcContainer : Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.
Parameter name: length"
At line:1 char:1
+ UploadImportAndApply-ConfigPackageInBcContainer -containerName test1  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [UploadImportAnd...geInBcContainer], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException,UploadImportAndApply-ConfigPackageInBcContainer
``` 

I think the following line is the problem, as a 20 character position is hardcoded and doesn't match the file path length on the system:
```
$packageId = ([System.IO.Path]::GetFileNameWithoutExtension($configPackage)).SubString(0,20)
```

**Full output of scripts**
```
Script     2.0.5      BcContainerHelper
```

**Comment by martinm1000** [comment]
Hi, I do have a question here - When I save a rapidstart package (just to test things), its name defaults to PackageXXXX.rapidstart where XXXX is the actual name we seems to need in $packageId. Is this normal ? My temp fix was to remove `^Package` from it, which the code doesn't do...

**Comment by freddydk** [comment]
I will add the packageId as a parameter and if you don't specify that, I will use the filename.
