### ISSUE TITLE
SuppressBuildSearchIndex and Import-ObjectsToNavContainer

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1720]
Hey @freddydk, 

I wanted to do another improvement for bccontainerhelper. This time I missed **SuppressBuildSearchIndex** parameter for Import-ObjectsToNavContainer. Importing objects is working pretty slow with SearchIndex updates.

I tried to add it locally first, and issue pull request, but could not get it working. My  change is straightforward.

![image](https://user-images.githubusercontent.com/16342128/108428597-1540b380-723f-11eb-9593-319b3de5ac1a.png)

But it seems this parameter is not supported (or at least for my container build 14.5)

![image](https://user-images.githubusercontent.com/16342128/108428798-69e42e80-723f-11eb-8fc1-88424076a7ed.png)

But this parameter is clearly [documented ](https://docs.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.ide/import-navapplicationobject?view=businesscentral-ps
)for v14.

Do you know from which build on it's available? Do you think we could add SuppressBuildSearchIndex at least for later builds? 

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
I do not know from which build it exists.
Instead of adding the parameter directly to the Import-NavApplicationObject call, you can add the parameter to the $params hashtable - if it is set (if ($suppress) { $params += @{ "suppress..." = $true } }
This means that if you don't set the switch, the parameter won't be specified.

**Comment by freddydk** [comment]
You can see in this PR how this could be achieved - you probably forgot to add the suppress variable to the invoke-script call and transfer the value to the container script (have made this mistake approx. 1.000.000 times myself)

**Comment by gintuoklis** [comment]
great news @freddydk. Thanks for the addition. Do you know when you are going to ship 2.0.7?

**Comment by freddydk** [comment]
Already did - 16 hours ago and 830 downloads.
https://www.powershellgallery.com/packages/BcContainerHelper/2.0.7

**Comment by gintuoklis** [comment]
Just for your information, SuppressBuildSearchIndex  parameter was added in 14.6 (on v14). So, if you use it earlier builds, you will get an error message about missing parameter.

**Comment by freddydk** [comment]
Ok, thanks.
I do not have the version number handy in the function. I will leave it to the caller to only specify this if they are running on 14.6 or later.
