### ISSUE TITLE
Run-AlValidation flag request to write errors on standard output.

### ISSUE THREAD

**Issue by xcyanx** [microsoft/navcontainerhelper#1726]
**Describe the issue**
In Azure DevOps besides using the Run-AlPipeline, i am also using the Run-AlValidation.
The possible validation errors that occur from the execution of the Run-AlValidation are only written to the
standard output. Therefore, the Azure DevOps won't stop the execution of the pipeline even though some things have already failed during the execution of the Run-AlValidation.

It would be great if there was a flag to activate/deactivate writting any validation errors into the standard error stream.

**Comment by freddydk** [comment]
I will add a switch called -throwOnError

**Comment by freddydk** [comment]
https://freddysblog.com/2021/02/28/running-business-central-in-docker-using-sql-on-the-host/
