### ISSUE TITLE
Creating container does not compelte

### ISSUE THREAD

**Issue by thomasbook** [Microsoft/navcontainerhelper#173]
After running script twice with two containers created each time the third one starts and does not complete?

CommandType     Name                                               Version    Source                                                   
-----------     ----                                               -------    ------                                                   
Function        Backup-NavContainerDatabases                       0.3.0.2    navcontainerhelper                                       
Function        Compile-AppInNavContainer                          0.3.0.2    navcontainerhelper                                       
Function        Compile-ObjectsInNavContainer                      0.3.0.2    navcontainerhelper                                       
Function        Convert-ModifiedObjectsToAl                        0.3.0.2    navcontainerhelper                                       
Function        Convert-Txt2Al                                     0.3.0.2    navcontainerhelper                                       
Function        Copy-FileFromNavContainer                          0.3.0.2    navcontainerhelper                                       
Function        Copy-FileToNavContainer                            0.3.0.2    navcontainerhelper                                       
Function        Create-AadAppsForNav                               0.3.0.2    navcontainerhelper                                       
Function        Create-AadUsersInNavContainer                      0.3.0.2    navcontainerhelper                                       
Function        Create-MyDeltaFolder                               0.3.0.2    navcontainerhelper                                       
Function        Create-MyOriginalFolder                            0.3.0.2    navcontainerhelper                                       
Function        Download-File                                      0.3.0.2    navcontainerhelper                                       
Function        Enter-NavContainer                                 0.3.0.2    navcontainerhelper                                       
Function        Export-ModifiedObjectsAsDeltas                     0.3.0.2    navcontainerhelper                                       
Function        Export-NavContainerDatabasesAsBacpac               0.3.0.2    navcontainerhelper                                       
Function        Export-NavContainerObjects                         0.3.0.2    navcontainerhelper                                       
Function        Get-CompanyInNavContainer                          0.3.0.2    navcontainerhelper                                       
Function        Get-LocaleFromCountry                              0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerAppInfo                            0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerCountry                            0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerDebugInfo                          0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerEula                               0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerEventLog                           0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerGenericTag                         0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerId                                 0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerImageName                          0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerIpAddress                          0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerLegal                              0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerName                               0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerNavUser                            0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerNavVersion                         0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerOsVersion                          0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerPath                               0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainers                                  0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerServerConfiguration                0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerSession                            0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerSharedFolders                      0.3.0.2    navcontainerhelper                                       
Function        Get-NavContainerTenants                            0.3.0.2    navcontainerhelper                                       
Function        Get-NavVersionFromVersionInfo                      0.3.0.2    navcontainerhelper                                       
Function        Import-ConfigPackageInNavContainer                 0.3.0.2    navcontainerhelper                                       
Function        Import-DeltasToNavContainer                        0.3.0.2    navcontainerhelper                                       
Function        Import-NavContainerLicense                         0.3.0.2    navcontainerhelper                                       
Function        Import-ObjectsToNavContainer                       0.3.0.2    navcontainerhelper                                       
Function        Import-TestToolkitToNavContainer                   0.3.0.2    navcontainerhelper                                       
Function        Install-NavContainerApp                            0.3.0.2    navcontainerhelper                                       
Function        Install-NAVSipCryptoProviderFromNavContainer       0.3.0.2    navcontainerhelper                                       
Function        Invoke-NavContainerCodeunit                        0.3.0.2    navcontainerhelper                                       
Function        New-CompanyInNavContainer                          0.3.0.2    navcontainerhelper                                       
Function        New-CSideDevContainer                              0.3.0.2    navcontainerhelper                                       
Function        New-DesktopShortcut                                0.3.0.2    navcontainerhelper                                       
Function        New-LetsEncryptCertificate                         0.3.0.2    navcontainerhelper                                       
Function        New-NavContainer                                   0.3.0.2    navcontainerhelper                                       
Function        New-NavContainerNavUser                            0.3.0.2    navcontainerhelper                                       
Function        New-NavContainerTenant                             0.3.0.2    navcontainerhelper                                       
Function        New-NavContainerWindowsUser                        0.3.0.2    navcontainerhelper                                       
Function        Open-NavContainer                                  0.3.0.2    navcontainerhelper                                       
Function        Publish-NavContainerApp                            0.3.0.2    navcontainerhelper                                       
Function        Remove-CompanyInNavContainer                       0.3.0.2    navcontainerhelper                                       
Function        Remove-ConfigPackageInNavContainer                 0.3.0.2    navcontainerhelper                                       
Function        Remove-DesktopShortcut                             0.3.0.2    navcontainerhelper                                       
Function        Remove-NavContainer                                0.3.0.2    navcontainerhelper                                       
Function        Remove-NavContainerSession                         0.3.0.2    navcontainerhelper                                       
Function        Remove-NavContainerTenant                          0.3.0.2    navcontainerhelper                                       
Function        Renew-LetsEncryptCertificate                       0.3.0.2    navcontainerhelper                                       
Function        Replace-NavServerContainer                         0.3.0.2    navcontainerhelper                                       
Function        Restart-NavContainer                               0.3.0.2    navcontainerhelper                                       
Function        Setup-NavContainerTestUsers                        0.3.0.2    navcontainerhelper                                       
Function        Start-NavContainer                                 0.3.0.2    navcontainerhelper                                       
Function        Start-NavContainerAppDataUpgrade                   0.3.0.2    navcontainerhelper                                       
Function        Stop-NavContainer                                  0.3.0.2    navcontainerhelper                                       
Function        Sync-NavContainerApp                               0.3.0.2    navcontainerhelper                                       
Function        Test-NavContainer                                  0.3.0.2    navcontainerhelper                                       
Function        UnInstall-NavContainerApp                          0.3.0.2    navcontainerhelper                                       
Function        UnPublish-NavContainerApp                          0.3.0.2    navcontainerhelper                                       
Function        Wait-NavContainerReady                             0.3.0.2    navcontainerhelper                                       
Function        Write-NavContainerHelperWelcomeText                0.3.0.2    navcontainerhelper                                       
Pulling docker Image microsoft/bcsandbox:us
us: Pulling from microsoft/bcsandbox
Digest: sha256:585b9daf8a6546c185ef4ad02969c003c08aef038c12907f21e70bbbd1e90a47
Status: Image is up to date for microsoft/bcsandbox:us
Creating Nav container dyn-sandbox
Using image microsoft/bcsandbox:us
Using license file C:\Binn\Dev 2017.flf
NAV Version: 12.2.22932.23097-US
Generic Tag: 0.0.6.3
Removing dyn-sandbox from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\dyn-sandbox
Creating container dyn-sandbox from image microsoft/bcsandbox:us

**Comment by freddydk** [comment]
When the script stops at this point, the issue typically is with Docker.
Try to cancel and use 

docker logs dyn-sandbox

to get the logs and display them here.
Probably you need to restart, delete other containers, clean up or like.

**Comment by thomasbook** [comment]
It has no logs, it has to do then to Docker.  I've asked them about the issues now.  Thanks!
