### ISSUE TITLE
SQL2019 in generic image

### ISSUE THREAD

**Issue by peterz84** [microsoft/navcontainerhelper#1735]
You can try to add this setting to your bccontainerhelper.config.json (in c:\programdata\bccontainerhelper) 
{
    "genericImageName": "mcr.microsoft.com/businesscentral:{0}"
}

This is where the generic image is moving to - and I am right now populating this with images for the various versions of windows.
This new generic image has sql express 2019 - you can test that.
The old address for the generic image will likely stay until January 2nd 2021.

_Originally posted by @freddydk in https://github.com/microsoft/navcontainerhelper/issues/1451#issuecomment-729126479_

I would like to use SQL2019 in my container, and restore a bak file to it. Found this issue, but I cannot find the file bccontainerhelper.config.json. How can I use SQL2019 without creating a new custom image?

**Comment by freddydk** [comment]
That is an old message - today sql 2019 is default.
You can find a lot about that on my blog.

https://freddysblog.com

**Comment by peterz84** [comment]
But why am I getting this error:

Using NavUserPassword Authentication
Using Database .bak file 'C:\ProgramData\NavContainerHelper\Extensions\BC17-1\database.bak'
Using database server localhost\SQLEXPRESS
The database restore operation failed due to the following error returned by SQL Server:
The database was backed up on a server running version 15.00.4083. That version is incompatible with this server, which is running version 14.00.1000. Either restore the da
tabase on a server that supports the backup, or use a backup that is compatible with this server.
RESTORE DATABASE is terminating abnormally.

**Comment by peterz84** [comment]
hmm probably seeing the issue myself, NavContainerHelper instead of BCContainerHelper.

**Comment by freddydk** [comment]
Because you are running a container which uses 14.x SQL Server.
Can be caused by old BcContainerHelper, NavContainerHelper, Missing image downloads, wrong configurations and a million of other things.
Cannot help without getting a full output of your run.
