### ISSUE TITLE
Install all apps from a given folder.

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#1736]
When passing a folder to an InstallApps Parameter in various scripts the CopyAppFilesToFolder throws an error in the line https://github.com/microsoft/navcontainerhelper/blob/0ae7815208bfac936c1b7e8d2ded50653055b2d7/HelperFunctions.ps1#L360.
 It would be very useful to be able to pass in folders and then have the CopyAppFilesToFolder iterate through the given folders and copy all apps within those folders.

**Comment by freddydk** [comment]
You should just use
-installApps (get-childitem $myFolder -Filter '*.app' -Recurse)

much more flexible and gives you the ability to do recurse, filters and exclude special things.

**Comment by jonaswre** [comment]
Thanks for the quick response. I've been doing that, but i would like to change as little as possible in your scripts from the Hello-World AL Project. This makes it easier to integrate changes.
Any reason not to do that in the helper itself?

**Comment by freddydk** [comment]
I will consider checking whether the path is a folder and then grabbing all .app files recursively.

**Comment by jonaswre** [comment]
Thanks that would be great.

**Comment by freddydk** [comment]
Shipped in 2.0.6-preview355

**Comment by jonaswre** [comment]
Thanks
