### ISSUE TITLE
[Docker 3.1.0 (51484)] Infinite script

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/navcontainerhelper#1738]
**Describe the issue**

When running New-BCContainer, the script is taking too long and seems to be "locked". I've opened an issue about this behavior here: https://github.com/microsoft/navcontainerhelper/issues/1672 
You offers me to update my windows version. 

After updating my windows version, I was able to create a new container without any problem. 
Now, when I want to creater another one, the script has the exact same behavior: it seems locked, here at:
**"Exporting Application to CRONUS"**

Today, my company has replaced my machine with a new one so I'm starting with a very fresh windows installation, and a very fresh docker installation too. But the problem is still there ..!

Do you have any clue to solve this ?

Thanks a lot

**Scripts used to create container and cause the issue**
```
New-BCContainer -accept_eula `
    -artifactUrl "https://bcartifacts.azureedge.net/sandbox/17.3.20469.21636/base" `
    -containerName "test" `
    -auth "UserPassword" `
    -credential $credential `
    -licenseFile $licenseFile `
    -includeTestToolkit:$false`
    -includeTestLibrariesOnly:$false `
    -enableTaskScheduler:$true`
    -restart no `
    -isolation 'HyperV' `
    -updateHosts `
    -includeAL
```

**Full output of scripts**
```
c:\Users\jds\Documents\repos\PowershellTools\GetBCDockerImage\GetBCDockerWithArtifact.ps1
https://bcartifacts.azureedge.net/sandbox/17.4.21491.22480/base
BcContainerHelper is version 2.0.5
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Professionnel - 20H2
Docker Client Version is 20.10.2
Docker Server Version is 20.10.2
Fetching all docker images
Using image mcr.microsoft.com/businesscentral:10.0.19042.804
Creating Container test
Version: 17.4.21491.22480-W1
Style: sandbox
Multitenant: Yes
Platform: 17.0.21485.22451
Generic Tag: 1.0.1.3
Container OS Version: 10.0.19042.804 (20H2)
Host OS Version: 10.0.19042.804 (20H2)
Using hyperv isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:/Users/jds/Documents/_Licenses/Licence AC 17 ISV FR_210404.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=True
Files in C:\ProgramData\BcContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container test from image mcr.microsoft.com/businesscentral:10.0.19042.804
324e819f2c6a7109f444557d6e1b6673f72d709f4a772a869d15c1e46e57cd3a
Waiting for container test to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.4.21491.22480/base
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.4.21491.22480\base\Demo Database NAV (17-0).bak
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by JulienDecottignies** [comment]
I just tried to unplug my ethernet cable, now the script goes to the end.

Do you have any explanation about this ? I know, it seems only related to docker but I really don't understand what is happening...

**Comment by freddydk** [comment]
A few things to try (1 by 1)
- disable your antivirus (or exclude c:\programdata\docker)
- remove -isolation hyperv
- add -multitenant:$false

**Comment by freddydk** [comment]
It seems related to something on your setup.
Antivirus is my best guess, let us know if you find out what causes this.

**Comment by JulienDecottignies** [comment]
I will ! Thanks for your help
