### ISSUE TITLE
debug session from VS can't be launched, container build: 12.2.22932.23097-US

### ISSUE THREAD

**Issue by lgtrrez** [Microsoft/navcontainerhelper#174]
Created a new container from latest build, same as before, but the debugging session from VS can't be launched, the app is published though. This is the output from debug console:
_[2018-08-02 09:20:47.47] Sending request to http://odtrm-nover:7049/nav/dev/apps?SchemaUpdateMode=synchronize
[2018-08-02 09:21:41.88] Success: The package 'App_365_2.3.0.2.app' has been published to the server.
[2018-08-02 09:21:42.21] Error: An internal error has occurred_

The EventLog from the container shows some errors:
![capture](https://user-images.githubusercontent.com/38257551/43594295-213d3da2-9637-11e8-9732-65a0dc917be6.PNG)

The logs from container:
_PS C:\windows\system32> docker logs ODTRM-NOVER
Initializing...
Starting Container
Hostname is ODTRM-NOVER
PublicDnsName is ODTRM-NOVER
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 55ABA182C74D2262E7F829C3B884C2E1E000DD89
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import License
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user laura
Setting SA Password and enabling SA
Creating laura as SQL User and add to sysadmin
Creating SUPER user_

I also checked the setting for NetFx40 in Microsoft.Dynamics.Nav.Server.exe.config and the enabled is set to False.

I can launch debug session from previous container without any issue, the same command was used for creating those previous ones (New-NavContainer -accept_eula -containerName $containerName -imageName microsoft/bcsandbox:us -shortcuts Desktop -includeCSide -enableSymbolLoading -alwaysPull -auth NavUserPassword -restart unless-stopped -licenseFile $licenseFile -accept_outdated), I thought it could be a docker problem, because it crashed about 2 days ago and I had to reset it, losing all containers & images, but the problem persists after creating the container again, I also had the New-NavContainer with the specific build version (microsoft/bcsandbox:12.0.21229.0-us), but the latest container was created specifying only "us", wanted to make sure that the version I was pulling was the latest one, and it was (result from new-navcontainer):
 __New-NavContainer -accept_eula -containerName $containerName -imageName $imageName -shortcuts Desktop -includeCSide -enableSymbolLoading -alwaysPull -auth NavUserPassword -restart unless-stopped -li
censeFile $licenseFile -accept_outdated -updateHosts
>>
Pulling docker Image microsoft/bcsandbox:us
us: Pulling from microsoft/bcsandbox
Digest: sha256:585b9daf8a6546c185ef4ad02969c003c08aef038c12907f21e70bbbd1e90a47
Status: Downloaded newer image for microsoft/bcsandbox:us
Creating Nav container ODTRM-NOVER
Using image microsoft/bcsandbox:us
Using license file D:\Work\xx.flf
NAV Version: 12.2.22932.23097-US
Generic Tag: 0.0.6.3
Creating container ODTRM-NOVER from image microsoft/bcsandbox:us
Waiting for container ODTRM-NOVER to be ready
Initializing...
Starting Container
Hostname is ODTRM-NOVER
PublicDnsName is ODTRM-NOVER
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 55ABA182C74D2262E7F829C3B884C2E1E000DD89
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import License
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user laura
Setting SA Password and enabling SA
Creating laura as SQL User and add to sysadmin
Creating SUPER user__

**Comment by freddydk** [comment]
This bug is fixed with the next release, which is due within the next couple of days.
If you use Ctrl+F5 (start without debugger) it works normally.

**Comment by lgtrrez** [comment]
yes, the app is always deployed; we'll have to wait for the next release. Thanks
