### ISSUE TITLE
disabledTests seems not to work in Run-TestsInBCContainer

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#1740]
I am trying to run Run-TestsInBCContainer and feed it with a DIsabledTests.json. But it appears it is just running the test(codeunit)s that are listed in that .json file.
As you can see below I am only running of the MS Tests-Permissions test app. They run fine in the sense that all tests, abd yes all tests, are run. Some fail, some succeed. Technically doing fine. But, as je can see in the listing of the **DisabledTest.json** below a number of tests (being 2 whole test codunits and a single test method) should be disbled (or skipped), but they are not. See the **TestResults.xml** below (attached as a .txt).

**Script**
Find below the script that runs the test (no error is that execution).
```
$containername = 'Bc17w1UPS'
$xunitResultsFile = "C:\ProgramData\BcContainerHelper\Extensions\Bc17w1UPS\my\TestResults.xml"
$disabledTestsFile = "C:\ProgramData\BcContainerHelper\Extensions\Bc17w1UPS\my\DisabledTests.json"
$credentials = New-Object pscredential 'me', (ConvertTo-SecureString -String 'xxx' -AsPlainText -Force)

$app = Get-NavContainerAppInfo $containerName | Where-Object { $_.Name -eq "Tests-Permissions" }

Run-TestsInBCContainer `
    -containerName $containerName `
    -credential $credentials `
    -detailed `
    -disabledTests $disabledTestsFile `
    -XUnitResultFileName $xunitResultsFile `
    -testSuite 'DEFAULT' `
    -extensionId $app.AppId
```
I have only put the script that calls Run-TestsInBCContainer. The New-BcContainer script seems not relevant to the issue, but if needed it can be provided.

**DisabledTest.json**
```
[
    { "codeunitId": 134612,"codeunitName": "Test Editing Permissions","method": "*" },
    { "codeunitId": 135413,"codeunitName": "Service Mgmt. Plan-based E2E","method": "TestSignAndCreateServiceContractAsEssentialISVEmb" },
    { "codeunitId": 139430,"codeunitName": "Permission Test Verification","method": "*" }
]
```
**TestResults.xml**
[TestResults.txt](https://github.com/microsoft/navcontainerhelper/files/6044039/TestResults.txt)

Question of course is whether I am doing something wrong or indeed the DisabledTests.json is neglected.

**Comment by lvanvugt** [comment]
Forgotten to add some screen shots.

### Test results from the AL Test Tool after `Run-TestsInBCContainer `
As you can see no skipped tests.
![image](https://user-images.githubusercontent.com/18466198/109192200-3c473a00-7797-11eb-8b6a-b7746626e6b0.png)

### Test results from ALOps test run
As you can here a part of the test are skipped (based on DisabledTests.json).
![image](https://user-images.githubusercontent.com/18466198/109192408-744e7d00-7797-11eb-82da-9fd190ad386b.png)

One side note: the number skipped is somewhat higher as all test from "codeunitId": 135413,"codeunitName": "Service Mgmt. Plan-based E2E" are skipped.

**Comment by freddydk** [comment]
The disabledTests parameter is missing help, sorry
It should not be a filename - it should be an array of disabled tests (hence not DisabledTestsFile)

-disabledTests (Get-Content "filename" | ConvertFrom-Json)

This is done in order for you to be able to disable tests and re-run tests without having to write files in-between.

I will add help to the function for this parameter

**Comment by lvanvugt** [comment]
Thanx. It's funny now reading your blog post [Running Tests In Containers](https://freddysblog.com/2019/10/22/running-tests-in-containers-2/) it's clearly stated there. But thought I did get my code example form some other ost (of you?).
Nevertheless, thanx for the feedback and the fix. Working fine.

![image](https://user-images.githubusercontent.com/18466198/109269093-45beb980-780c-11eb-8f77-77bcff651779.png)

**Comment by freddydk** [comment]
This one: https://github.com/microsoft/navcontainerhelper/issues/748#issuecomment-564728120
also shares the disabledTests (not the file):-)
