### ISSUE TITLE
Why is a number added to the runtime apps and not the normal apps?

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#1741]
I was wondering, whats the reasioning behind numbering runtime apps while not doing it for normal apps.

https://github.com/microsoft/navcontainerhelper/blob/b4d29fb7c3b0b13bc754d920a2a55132184a7f1f/AppHandling/Run-AlPipeline.ps1#L1484

Thanks alot!

**Comment by freddydk** [comment]
When I wrote the Al-Pipeline, I wasn't able to sort runtime packages after dependencies which is why I had to add the numbering in the output.
Normal apps can be published using publish functions, which sorts them by dependencies first.
Runtime apps also do that now (if a container is specified).

**Comment by jonaswre** [comment]
Thanks so much
