### ISSUE TITLE
NAV2016 images are not supported anymore?

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#175]
Hi Freddy, team.
When I look here https://hub.docker.com/r/microsoft/dynamics-nav/ i see that NAV2016 images are supported

> Version currently is 2016, 2017 or 2018 (omit to get newest)

However, I can't find a tag for NAV2016 under [tags tab](https://hub.docker.com/r/microsoft/dynamics-nav/tags/).

And when i use $navdockerimage = 'microsoft/dynamics-nav:2016-cu27' or $navdockerimage = 'microsoft/dynamics-nav:2016' it pulls me microsoft/bcsandbox:us

So can I create container for NAV2016?

**Comment by freddydk** [comment]
The tags list on docker hub only shows x tags - and there are over 1000 images up there.
When I do docker pull microsoft/dynamics-nav:2016 I get 
            "Labels": {
                "country": "W1",
                "created": "201807101718",
                "cu": "cu33",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=617572",
                "maintainer": "Dynamics SMB",
                "nav": "2016",
                "osversion": "10.0.14393.2312",
                "tag": "0.0.6.3",
                "version": "9.0.50458.0"
            },

which is the latest 2016 image - cu34 is due in a few days.
cu27 is also available.
Not sure what went wrong in your script...

**Comment by dkatson** [comment]
Thanks, @freddydk ,
That was my fault. I commented one parameter in the middle and thought that he will pickup parameters after, but seems that this syntax comments also all parameters after.

`New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
				 #-assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -licenseFile $licenseFile `
                 -additionalParameters $additionalParameters
`

**Comment by freddydk** [comment]
Correct - annoying PowerShell behavior
