### ISSUE TITLE
New-BcContainer scripts fails when SQL Server 2019 is used as host

### ISSUE THREAD

**Issue by yuranshrestha** [microsoft/navcontainerhelper#1754]
**Describe the issue**
New-BcContainer scripts fails when SQL Server 2019 is used as host

**Scripts used to create container and cause the issue**
```
$licenseFile = "C:\run\my\license.flf"
$auth = "UserPassword"
$credential = New-Object pscredential 'dynamics', (ConvertTo-SecureString -String 'Welcome@2021' -AsPlainText -Force)
$artifactUrl = "https://bcartifacts.azureedge.net/sandbox/17.4.21491.22635/gb"
$containerName = "bcserver"

$databaseParams = @{
    "databaseServer" = 'host.containerhelper.internal'
    "databaseInstance" = ''
    "databasePrefix" = "$containerName-"
    "databaseName" = 'CRONUS'
    "databaseCredential" = $credential
    "multitenant" = $true
}

New-BcContainer @databaseParams -replaceExternalDatabases `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts `
    -accept_outdated
```

**Full output of scripts**
```
PS C:\WINDOWS\system32> $licenseFile = "C:\run\my\license.flf"
$auth = "UserPassword"
$credential = New-Object pscredential 'dynamics', (ConvertTo-SecureString -String 'Welcome@2021' -AsPlainText -Force)
$artifactUrl = "https://bcartifacts.azureedge.net/sandbox/17.4.21491.22635/gb"
$containerName = "bcserver"

$databaseParams = @{
    "databaseServer" = 'host.containerhelper.internal'
    "databaseInstance" = ''
    "databasePrefix" = "$containerName-"
    "databaseName" = 'CRONUS'
    "databaseCredential" = $credential
    "multitenant" = $true
}

New-BcContainer @databaseParams -replaceExternalDatabases `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts `
    -accept_outdated
BcContainerHelper is version 2.0.6
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.2
Docker Server Version is 20.10.2
Removing bcserver from host hosts file
Removing bcserver-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\bcserver
Setting database bcserver-tenant offline
Removing database bcserver-tenant
Setting database bcserver-CRONUS offline
Removing database bcserver-CRONUS
Starting Database Restore job from https://bcartifacts.azureedge.net/sandbox/17.4.21491.22635/gb
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.804
Creating Container bcserver
Version: 17.4.21491.22635-GB
Style: sandbox
Multitenant: Yes
Platform: 17.0.21485.22555
Generic Tag: 1.0.1.3
Container OS Version: 10.0.19042.804 (20H2)
Host OS Version: 10.0.19042.804 (20H2)
Using process isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\run\my\license.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\bcserver\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupDatabase.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bcserver from image mcr.microsoft.com/businesscentral:10.0.19042.804
bd4e06c421c2c06de9f0ca05557e089506fc84f6665f79931f2573b6cdb178ef
Waiting for container bcserver to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.4.21491.22635/gb
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.GB
Installation took 44 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.67 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.67 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.80.1 in container hosts file
Starting Container
Hostname is bcserver
PublicDnsName is bcserver
Using NavUserPassword Authentication
Waiting for database creation to finish..............................................................................
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\run\setupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\my\SetupDatabase.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 121
at <ScriptBlock>, C:\Run\start.ps1: line 359
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/17.4.21491.22635/gb
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying PowerShell Scripts
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying additional files
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying Applications.GB
Installation took 44 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.67 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.67 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.80.1 in container hosts file
Starting Container
Hostname is bcserver
PublicDnsName is bcserver
Using NavUserPassword Authentication
Waiting for database creation to finish..............................................................................
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\run\setupDatabase.ps1: line 152
at <ScriptBlock>, C:\Run\my\SetupDatabase.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 121
at <ScriptBlock>, C:\Run\start.ps1: line 359
at <ScriptBlock>, <No file>: line 1
Initialization of container bcserver failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.6\ContainerHandling\Wait-NavContainerReady.ps1:43 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...bcserver failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bcserver failed
...
```

**Screenshots: It creates the database even if script fails as shown in below screen shot**
![tempsnip](https://user-images.githubusercontent.com/34326189/109465214-ef61ad00-7a8f-11eb-8e0a-5caf4ff5e01a.png)

**Additional context**
- does it happen all the time?
Yes it happens all the time.
- did it use to work?
No

**Comment by freddydk** [comment]
The databases are created by the Restore-BcDatabasesFromArtifacts function, which runs on the host.
The place in the script, where it fails is the first time it tries to connect to the SQL Server.
Is you SQL Server setup for TCP/IP (Network) connections?

**Comment by yuranshrestha** [comment]
![Capture](https://user-images.githubusercontent.com/34326189/109481191-905a6300-7aa4-11eb-9717-d332253c8dce.PNG)
Yes, its enabled.

**Comment by freddydk** [comment]
I just tried to upgrade my SQL 2017 developer to SQL 2019 and got the same problem.
For me, it was that the MSSQLSERVER user didn't have full control over this folder:
C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA
![image](https://user-images.githubusercontent.com/10775043/109490643-cd186100-7a88-11eb-83eb-ed6bb7de0d46.png)
After giving full control - the script worked again.

Are you connecting as SA?
Is SA enabled and has the right password?

**Comment by yuranshrestha** [comment]
Yes , SA is already enabled. This script works if I replace 
$artifactUrl = "https://bcartifacts.azureedge.net/sandbox/17.4.21491.22635/gb"
by 
$artifactUrl = Get-BcArtifactUrl -country us

So, i think it is only working for "us" localization in my case. It does not work for "gb".

**Comment by freddydk** [comment]
us and gb works fine here (with my newly installed SQL 2019)
Maybe there is a problem with the artifacts - maybe you have had a download issue with the artifacts.
You could try to use Flush-ContainerHelperCache and then retry

**Comment by kine** [comment]
Hi Freddy, have you updated the SQL with all available updates? After my last update of the servers (windows and SQL) the SQL started to behave differently (scripts which were running stopped and I had connection issues from container to my external SQL 2019). In my case helped to use FQDN of the SQL instead just server name. But in his example I see that FQDN is already used. (and in my case I was using windows authentication and problem was in Test-NAVDatabase function which was connecting under windows account - gMSA...)

**Comment by freddydk** [comment]
When it works with us and not with gb - then it shouldn't be something with the connection I think.
That's why I am guessing that the artifacts might be wrongly downloaded.

**Comment by yuranshrestha** [comment]
Unfortunately, its not working even after I use Flush-ContainerHelperCache. Surprisingly it works for "us" localization but not for "gb".

**Comment by freddydk** [comment]
Puzzled
Maybe try and use Get-BcContainerEventlog to see what the cause of the failure is.

**Comment by yuranshrestha** [comment]
In bcserver eventlog I can see following 3 errors.
1. **The Cryptographic Services service failed to initialize the Catalog Database. The ESENT error was: -1409.**
2. **License Activation (slui.exe) failed with the following error code: hr=0x8007007B**
3. **Failed to collect hardware data. Error code 0xD0000034.**
Following are the warnings coming from bcserver
 **1.**A provider, SQLServerEventProvider, has been registered in the Windows Management Instrumentation namespace root\Microsoft\SqlServer\ServerEvents\SQLEXPRESS to use the LocalSystem account. This account is privileged and the provider may cause a security violation if it does not correctly impersonate user requests.
 **2.**Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideException
Remappable: True
ErrorCode: 22924076
ErrorNumber: 52012
ModuleNumber: 93
SuppressMessage: False
ContainsPersonalOrRestrictedInformation: False
DiagnosticsSuppress: True
NavTenantId: nav-systemapplication
EnvironmentType: Production
MessageWithoutPrivateInformation:
  Cannot establish a connection to the SQL Server/Database.
  
  This could be due to one of the following reasons:
  
  * SQL Server is not started.
  * The database does not exist.
  * Proper permissions have not been given to the NAV Server Account.
  
  Try again later or contact your system administrator.
SuppressExceptionCreatedEvent: False
FatalityScope: None
ErrorLevel: Error
Message:
  Cannot establish a connection to the SQL Server/Database.
  
  This could be due to one of the following reasons:
  
  * SQL Server is not started.
  * The database does not exist.
  * Proper permissions have not been given to the NAV Server Account.
  
  Try again later or contact your system administrator.
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnection(Int32 attemptCount)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey, Boolean isNewDatabase)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.HandleEncryptionKeyChangeInApplicationDatabase(String newPublicKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnection(Int32 attemptCount)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey, Boolean isNewDatabase)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.HandleEncryptionKeyChangeInApplicationDatabase(String newPublicKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()

**Comment by yuranshrestha** [comment]
Here is another error I can see from host
exec's CreateProcess() failed [exec=e65f7438e63b5f1472fef5fb731c53d3ffc98ddb275e8f4c75a2129dea40bc8e error=container 915efa47405a0512f6d0dbff7d28187ada4df10ba3af674abae3419cf115de51 encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"CommandLine":"cmd.exe /C \"ECHO 192.168.1.67    host.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts \u0026 ECHO 192.168.1.67    gateway.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts\"","User":"Administrator","WorkingDirectory":"/","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","DOTNET_RUNNING_IN_CONTAINER":"true","ExitOnError":"N","accept_eula":"Y","accept_outdated":"Y","artifactUrl":"https://bcartifacts.azureedge.net/sandbox/17.4.21491.22689/gb","auth":"NavUserPassword","databaseInstance":"","databaseName":"bcserver-CRONUS","databaseSecurePassword":"76492d1116743f0423413b16050a5345MgB8AHUARQBiAGgAVwA3AFMAVwB2AFQAaAAwACsAVgBqAGMAQgBIAGwAagBQAGcAPQA9AHwAZAAxAGMAOAA0AGEANAA0ADgAZQBlAGUAMwA1AGMAZQAyADEANQA4AGMAYwBmAGEANgA0ADEANABmAGYAMAA2ADMAMgBjADMANABmADAANAAzAGQAYgA2AGQAYgAxADkAMABiADUAZgAwADgAOAAxAGIAZgAyADUAZgAwAGQAYgA=","databaseServer":"host.containerhelper.internal","databaseUsername":"sa","enableApiServices":"Y","encryptionSecurePassword":"76492d1116743f0423413b16050a5345MgB8AHUARQBiAGgAVwA3AFMAVwB2AFQAaAAwACsAVgBqAGMAQgBIAGwAagBQAGcAPQA9AHwAZAAxAGMAOAA0AGEANAA0ADgAZQBlAGUAMwA1AGMAZQAyADEANQA4AGMAYwBmAGEANgA0ADEANABmAGYAMAA2ADMAMgBjADMANABmADAANAAzAGQAYgA2AGQAYgAxADkAMABiADUAZgAwADgAOAAxAGIAZgAyADUAZgAwAGQAYgA=","filesOnly":"False","isBcSandbox":"Y","licenseFile":"c:\\run\\my\\license.flf","locale":"en-GB","multitenant":"Y","passwordKeyFile":"c:\\run\\my\\aes.key","removePasswordKeyFile":"Y","securePassword":"76492d1116743f0423413b16050a5345MgB8AHkAdgAzADMASgAvAEoAYgA5ADcAcgB0AEMAcAByAG8AUgBlADUATQBnAFEAPQA9AHwAZAA4AGYAMQAxAGQAOABmADIAYQAxADAAYQAzAGUAYgA4ADAAMwA2AGQAZAAxAGYAYwAzAGYANQBmADkAZgAwAGUAZgBmADEAMABmAGMANAA1AGEANgA1AGQAZABjADYAMgBiADIAYQAzADkAMAAyADcAYQA1ADUAMgA3AGQANwA=","useSSL":"N","username":"dynamics"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]} module=libcontainerd namespace=moby container=915efa47405a0512f6d0dbff7d28187ada4df10ba3af674abae3419cf115de51]

**Comment by freddydk** [comment]
Do you get the second error every time or is that just once?
That one I have only seen due to antivirus before.

**Comment by dannoe** [comment]
@yuranshrestha  Maybe a firewall problem?

**Comment by slehoux** [comment]
I have exactly the same problem! I've gone through the list of items mentionned earlier without any success. The only thing I've found is that even after the script completes, the ID of the Docker Container is not added to the host file.

Other detail, I hjad installed HyperV in the pas for Docker so that may have an impact.

**Comment by dannoe** [comment]
@slehoux Can you execute ```Enter-BcContainer <yourcontainer>``` and run a ```ping host.containerhelper.internal```
And check if the firewall on your host is blocking incoming connections on port 1433.

**Comment by slehoux** [comment]
When I did my last tests, I had completely deactivated my local firewall (Bitdefender) and the Windows Firewall. The only remaining Firewall (Which I couldn't deactivate) was the corporate Firewall, which is, of course, outisde my jurisdiction.

Same result.

And I did what you asked and here is the result:

Ping request could not find host host.containerhelper.internal. Please check the name and try again.

**Comment by freddydk** [comment]
@slehoux are you using -updatehosts?

**Comment by slehoux** [comment]
> @slehoux are you using -updatehosts?

Yes, yes I am. :)

**Comment by freddydk** [comment]
and 

```
Invoke-scriptinbccontainer -containerName $containerName -scriptblock {
    ping host.containerhelper.internal
}
```

fails?

**Comment by slehoux** [comment]
> and
> 
> ```
> Invoke-scriptinbccontainer -containerName $containerName -scriptblock {
>     ping host.containerhelper.internal
> }
> ```
> 
> fails?

Now it works since I readded the line I mentionned above.

Again, will let you know what my latest attempt.

**Comment by freddydk** [comment]
host.containerhelper.internal should not be in your hosts file.
It is generated by BcContainerHelper automatically pointing to your host.
With 127.0.0.1 - the container will not point to the host - it will point to itself.

Please create a new issue with full script and full output instead of continuing on this issue, thanks.
