### ISSUE TITLE
manifest for mcr.microsoft.com/dynamicsnav:10.0.19041.388-generic not found

### ISSUE THREAD

**Issue by davmac1** [microsoft/navcontainerhelper#1757]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
it looks like the version of Windows is no longer available.
I ran UpdateBCContainerHelper.ps1 and the version I had 2.0.6 was confirmed as the latest version.

**Scripts used to create container and cause the issue**
```
New-BCContainer @parameters `
                -accept_eula `
                -containerName $ContainerName `
                -artifactUrl $artifactURL `
                -auth NAVUserPassword `
                -Credential $credential `
                -updateHosts `
                -assignPremiumPlan `
                -shortcuts StartMenu `
                -licenseFile $ContainerLicFile `
                -EnableTaskSchedule:$false `
                -memoryLimit 8G `
                -includeAL `
                -alwaysPull `
                -isolation hyperv
```

**Full output of scripts**

PS C:\WINDOWS\system32> C:\Docker\dockercontainer-master\dockercontainer-master\CreateNavContaineFromArtifactStandardOnly.ps1
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - Unknown/Insider build
Docker Client Version is 20.10.2
Docker Server Version is 20.10.2
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.388-generic
DockerDo : Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.19041.388-generic not found: manifest 
unknown: manifest tagged by "10.0.19041.388-generic" is not found
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.19041.388-generic
At C:\Users\dmachanick\Documents\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\New-NavContainer.ps1:622 
char:13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
```
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 

...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- used to work - worked last week - stopped working today.

**Comment by freddydk** [comment]
https://freddysblog.com/2021/03/01/navcontainerhelper-doesnt-work-anymore/

**Comment by davmac1** [comment]
Our internal scripts are pointing to the older product. I will get them corrected and see if it fixes the problem.

**Comment by BernhardKloibmueller** [comment]
I am using BC Container Helper 1.0.13-dev and I am getting a similar error:

nvx-sandbox-17.3.20469.22634-at:sandbox-17.3.20469.22634-at-nodb
Fetching all docker images
Building image nvx-sandbox-17.3.20469.22634-at:sandbox-17.3.20469.22634-at-nodb based on mcr.microsoft.com/dynamicsnav:10.0.17763.1158-generic with 
https://bcartifacts.azureedge.net/sandbox/17.3.20469.22634/at without database
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.17763.1158-generic
Creating Image was not successfulError response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.17763.1158-generic not found: manifest unknown: manifest tagged by 
\"10.0.17763.1158-generic\" is not found

**Comment by MODUSCarstenScholling** [comment]
Same here with BcContainerHelper 2.0.6: Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.17763.1577-generic not found: manifest unknown: manifest tagged by "10.0.17763.1577-generic" is not found

I am passing artifactUrl=https://bcartifacts.azureedge.net/sandbox/17.4.21491.21867/de and imageName=sandbox:17.4.21491.21867-de which is found by "docker image inspect".

Call stack (line numbers of parent script) : 
New-BcContainer -> 
New-BcImage (547) -> 
Get-BcContainerImageLabels (183) -> 
$webclient.DownloadString("https://$registry/v2/$repository/manifests/$tag") (69)

https://$registry/v2/$repository/manifests/$tag evaluates to https://mcr.microsoft.com/v2/dynamicsnav/manifests/10.0.17763.1577-generic. And on this URL the return is 
{"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest tagged by \"10.0.17763.1577-generic\" is not found","detail":{"Tag":"10.0.17763.1577-generic"}}]}, even in a browser...

And 2 containers already running using this image:

CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                  PORTS
3b90a1f1ea1a        sandbox:17.4.21491.21867-de             "powershell -Commandâ€¦"   4 days ago          Up 4 days (healthy)     80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 7083/tcp, 8080/tcp
633cdbe8ba61        sandbox:17.4.21491.21867-de             "powershell -Commandâ€¦"   5 days ago          Up 5 days (healthy)     80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 7083/tcp, 8080/tcp

**Comment by MODUSCarstenScholling** [comment]
Ok, got it: 
We are using a different location for the artifacts cache. Therefore we created a custom config that long time ago. The genericImageName config still was "mcr.microsoft.com/dynamicsnav". On my local machine all worked as usual with "mcr.microsoft.com/businesscentral" from the default config...

Is there a more elegant and fully working way to specify the artifacts cache path instead of providing a custom config?

**Comment by freddydk** [comment]
@BernhardKloibmueller - you probably also have a config file with wrong settings.
Else, please post the full output of the generation here and I can quickly tell you what is wrong.

**Comment by davmac1** [comment]
We are using settings.json. Is there a separate config file I should look for?
Sandbox pulls from businesscentral and onPrem pulls from dynamicsnav for the windows images.
The person who built our libraries is out sick today, so I am trying to figure this out without disturbing him.

**Comment by freddydk** [comment]
c:\programdata\bccontainerhelper\bccontainerhelper.config.json

**Comment by freddydk** [comment]
But @davmac1  - you are running NavContainerHelper - visible in your output.
That will never work.

**Comment by davmac1** [comment]
@freddydk I don't have a config file in either of the helper directories.
I have a command - Get-BCArtifactUrl that is executing the NavContinerHelper script instead of the BcContainerHelper which I have.
Do I need to update get-artifacturl or change to a different script?

**Comment by davmac1** [comment]
@freddydk I am running UnInstall-Module NavContainerHelper -allversions
This I hope will have my process running BCContainerHelper instead.
How long does the uninstall process take?
It has been running for about an hour.

**Comment by freddydk** [comment]
typically a few minutes.
Maybe reboot and try again.

**Comment by davmac1** [comment]
I rebooted and it ran, but it only deleted the older version.
I have tried running this several times and even explicitly deleting the version, but the current version of navcontainerhelper does not get deleted 0.7.0.26. And it is still being called.
I rebooted after uninstalling - still there.
I am running ISE in admin mode.
Do you have any suggestion on another way to get rid of it?

**Comment by freddydk** [comment]
reboot and before you start PowerShell, remove the folder: "C:\Program Files\WindowsPowerShell\Modules\NavContainerHelper"
You might have something in a PowerShell profile, which uses NavContainerHelper - check out the profiles, I cannot remember where they are - there is a user one and a global one.

**Comment by MODUSCarstenScholling** [comment]
I like to emphasize my question again: Is there a more elegant and fully working way to specify the artifacts cache path instead of providing a custom config? :)

**Comment by freddydk** [comment]
Creating a custom config file with just that one setting is absolutely the simplest way.
You can also set the variable in code $bcContainerHelperConfig.bcartifactscachepath (I think is the name) - but the config file is simplest.
Not sure how it could be simpler than a config file with one line?

**Comment by MODUSCarstenScholling** [comment]
Thx, I wasn't aware of the one line possibility.

**Comment by freddydk** [comment]
You only need to specify the config settings you want to change, I thought that was how all config files worked.

**Comment by BernhardKloibmueller** [comment]
@freddydk I am trying to change the settings and come back to you with an update

**Comment by freddydk** [comment]
Just remove the settings, you don't want to change - then BcContainerHelper works.

**Comment by BernhardKloibmueller** [comment]
unforunately he tries to take the DynamicsNAV again when I remove it, when I use BusinessCentral he doesnt find it either, I will now update the BCContainerHelper, I hope whit will work, keep you updated

Thank you in the meantime for the support!

**Comment by davmac1** [comment]
@freddydk I had a folder in my documents directory which was causing the problem.
This was created when I had just started my current job last July. 
It finally stopped working this week.
I removed it like you instructed, and it is working now.

By custom config do you mean this?
c:\programdata\bccontainerhelper\bccontainerhelper.config.json

Thanks for all your help.

**Comment by BernhardKloibmueller** [comment]
My problem is solved with the update of the bc container helper

After investigation I found that my problem was, that my default generic Name was DynamicsNAV (Version 1.0.13)

I tried this on my second docker server and if I use the correct generic image name (which I located in the source files: "mcr.microsoft.com/businesscentral:{0}" ) it was working fine.

But my solution is to update to the latest version and clean your settings like it was suggested by @freddydk 

Thank you again for the support!

**Comment by freddydk** [comment]
@davmac1 that is the bccontainerhelper config, yes
There is a blog post on my blog explaining the different values you can set in that.
