### ISSUE TITLE
New-NavContainer Username problem

### ISSUE THREAD

**Issue by XceSx6** [Microsoft/navcontainerhelper#176]
My username is in the format of "Name@Company.CountryAlpha2" ..

**When running this command:**
New-NavContainer -accept_eula -containerName "test" -auth NavUserPassword -imageName "microsoft/dynamics-nav"

**It spits out this error:**
Creating name@company.be as SQL User and add to sysadmin
Msg 102, Level 15, State 1, Server TEST\SQLEXPRESS, Line 6
Incorrect syntax near '.'.

**Comment by freddydk** [comment]
The username used for navuserpassword should be a simple name.
If you want AAD authentication, then the name@company.be should be used as authentication email.

**Comment by XceSx6** [comment]
Changing to the following seems to agree more:
New-NavContainer -accept_eula -containerName "Test" -auth NavUserPassword -credential $null -imageName "microsoft/dynamics-nav"

It now gets to the end successfully

**Comment by freddydk** [comment]
That should be the default (https://github.com/Microsoft/navcontainerhelper/blob/master/ContainerHandling/New-NavContainer.ps1 line 84)
