### ISSUE TITLE
BC-Container Not able to download symbols 

### ISSUE THREAD

**Issue by Aleckspad** [microsoft/navcontainerhelper#1762]
**Describe the issue**
I'm creating a bc-container to generate test scripts in order to submit the app to the app store. the issue right now is that I'm not able now to download symbols and make the container recognize the test libraries.

```
$containerName = 'vctest3'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'us' -select 'Latest'
$databaseServer = 'host.containerhelper.internal'
$databaseInstance = ''
$databaseName = 'Navision_NAV_US_FullApplication'
$databaseUsername = 'admin'
$databasePassword = 'P@ssw0rd'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = 'xxxxxxx'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -includeTestToolkit -includeTestLibrariesOnly `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -memoryLimit 8G `
    -updateHosts

```
The error that we are getting at the moment 
<img width="769" alt="2021-03-02 13_41_34-BCAppSource - 104 43 242 128_3389 - Remote Desktop Connection" src="https://user-images.githubusercontent.com/79926425/109705220-23ef6a80-7b5d-11eb-973f-e09f9f679541.png">

**Comment by freddydk** [comment]
On the script, it looks like you already have restored the database on the host and you are using that?
Is that what you aim to do?
Please share the full output of the script (marked with Insert Code as I have done with your original script) and also add your launch.json.
