### ISSUE TITLE
Team Member not able to logon to BC18 container

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#1763]
**Describe the issue**
We're using `Setup-BcContainerTestUsers` to have the different users added to our local containers.

When trying to logon to a BC18 container with the TEAMMEMBER user we get this error
```
You do not have the following permissions on CodeUnit System Initialization Impl.: Execute.

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '439'.
```

**Scripts used to create container and cause the issue**
1. Create a BC18 container (I was using https://bcinsider.azureedge.net/sandbox/18.0.22700.0/se )
2. Create test users with below cmdlet
```
Setup-BcContainerTestUsers -containerName $containerName -credential $credential -Password $TestUsersPassword
```

**Additional context**
- I tried to logon with this user since I got a test that lowered the permissions to a TEAM MEMBER, and it failed with another missing execute permission on another codeunit. 
- I do not know if this is an issue with how bccontainerhelper creates the TEAMMEMBER user, or if this is some bug inside BC18... Let me know if I should report this somewhere else

**Comment by freddydk** [comment]
In 18, permissionsets moved to extensions instead of being in the database.
We have a switch in the config file (in order to support technical upgrades where people have the permissions in the database)
That switch will be set to true by default (one of the next days) - today, it is false (=permissions are in the database - and they are not).

Until the setting is defaulted to true, you can add this to your New-BcContainer:

 -additionalParameters @("--env customnavsettings=UsePermissionSetsFromExtensions=true")

Then it is true - and your TEAMMEMBER should be able to login.

**Comment by jwikman** [comment]
Thanks Freddy,

Then I'll add this parameter for BC18 only.

**Comment by freddydk** [comment]
In a few days it will be default.

**Comment by jwikman** [comment]
Will that be in an update of bccontainerhelper, or in the bc artifact?

**Comment by freddydk** [comment]
In the artifacts (default customsettings) - no change needed

**Comment by jwikman** [comment]
Aah, good. 

Then I'll just wait for that

**Comment by jwikman** [comment]
@freddydk any news on when this will be updated in the artifacts?

Still get this today, using https://bcinsider.azureedge.net/sandbox/18.0.23023.0/se

Our consultants are eager to test our apps on BC18 before submitting on AppSource

If it's still "in a few days", I might need to implement the workaround ;-)

**Comment by freddydk** [comment]
Still a few days is what I hear:-(

**Comment by jwikman** [comment]
Ok, thanks for info.

Then I'll add
`-additionalParameters @("--env customnavsettings=UsePermissionSetsFromExtensions=true")
`
