### ISSUE TITLE
Compile-AppInBcContainer can't download symbols with character "&" in the name

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#1764]
**Describe the issue**
I have an extension with the character "&" in the name: Service & Inventorys.app
now i complie a app which uses this app as a dependency and the script want to download this "Service & Inventory.app" but it gets an error that it could not be found.

VSCode download the app: "Service %26 Inventory.app" and it works.

so i changed the code in the Compile-AppInBcContainer to 
```$apphtmlname = $name -replace '&','%26'```

**Scripts Compile-AppInBcContainer i changed**
```
                $symbolsFile = Join-Path $appSymbolsFolder $symbolsName
                Write-Host "Downloading symbols: $symbolsName"
    
                $publisher = [uri]::EscapeDataString($publisher)

                $apphtmlname = $name -replace '&','%26'

                $url = "$devServerUrl/dev/packages?publisher=$($publisher)&appName=$($apphtmlname)&versionText=$($version)&tenant=$tenant"
                Write-Host "Url : $Url"
```

**Full output of error**
```
##[error]The remote server returned an error: (404) Not Found. No published package matches the provided arguments. 
...
```

**Additional context**
- BCContainerHelper is version 2.0.5
- in vscode if i use the action "AL Download Symbols" the vscode convert the "&" to "%26"

**Comment by freddydk** [comment]
I think this was fixed in 2.0.6:
https://github.com/microsoft/navcontainerhelper/commit/eb3340f135248ed7fad43445ef01639ae9ccadb5#diff-4922da596363ce3dde1c78c17fb3c4ce85688d439487f9abe3d3391bdecbac02

**Comment by Spycoclown** [comment]
Oh no, i'm sry. i will try thanks.

**Comment by freddydk** [comment]
no problem

**Comment by Spycoclown** [comment]
it works, thank you :)
