### ISSUE TITLE
License issues with 16.7 on prem importing test libraries

### ISSUE THREAD

**Issue by MarkCWEV** [microsoft/navcontainerhelper#1765]
When I create a container with -country na -version 16.7 -select Latest -type OnPrem) with the switch -includeTestToolkit, I get this error. We THINK we need application builder license, but our partner has contacted microsoft and they are able to confirm. I'm trying to figure out if this is a bug or we need the license, before we go ahead and spend $9.2k on something we may not need.

Publishing C:\ProgramData\BcContainerHelper\Extensions\Dev167\49353296-94c9-45fc-a61e-bd9a561146b4\Microsoft_Test Runner.app
Your program license does not allow you to publish 'AL Test Suite'.
at <ScriptBlock>, <No file>: line 15
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\AppHandling\Publish-NavContainerApp.ps1: line 257
at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\AppHandling\Publish-NavContainerApp.ps1: line 113
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 185
at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 153
at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ContainerHandling\New-NavContainer.ps1: line 1750
at <ScriptBlock>, D:\OneDrive\OneDrive - Clesen Wholesale\Documents\PowerShell\Get Nav Container 16.7 on prem.ps1: line 14
Your program license does not allow you to publish 'AL Test Suite'.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Your program li...AL Test Suite'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Your program license does not allow you to publish 'AL Test Suite'.

**Comment by freddydk** [comment]
I will investigate, give me a few days.

**Comment by freddydk** [comment]
QQ Are you a partner or are you a customer who wants to do development yourself?

**Comment by freddydk** [comment]
I am told that there are changes coming to the license terms by April 1st, which should allow you to run tests without the Application Builder license. You will have to wait for the exact wording/content of this change when it gets published.
I will paste a link here once I have the documentation.

**Comment by freddydk** [comment]
The licensing guide was updated, but that is on PartnerSource.
https://businesscenter.mbs.microsoft.com/#contentdetail/Dyn365PricingandLicensing
I don't know when/how this information will be public, but you can work with your partner to understand the changes and see when this is available for you.
