### ISSUE TITLE
Import-ObjectsToNavContainer issues

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#1766]
**Describe the issue**

When I import the attached [FOB](https://github.com/microsoft/navcontainerhelper/files/6079055/mod.zip) into a container with xxx, the name of _CRM Connection Setup_ in table 5330 changes to _Microsoft Dynamics 365 Connection Setup_ in the symbols, which is the en-us label. All other objects have disappeared in the symbol file.

**Powershell:**
```Import-ObjectsToNavContainer -containerName bc14docker -objectsFile "C:\Users\myuser\Desktop\mod.fob" -ImportAction Overwrite -SynchronizeSchemaChanges Yes``` 

When I do the same on a DVD installation, this does not happen and works as expected.

**Powershell:**
```Import-NAVApplicationObject -Path "C:\Users\myuser\Desktop\mod.fob" -DatabaseServer localhost\bcdemo -DatabaseName "Demo Database BC (14-0)" -ImportAction Overwrite -SynchronizeSchemaChanges Yes```

**Scripts used to create container and cause the issue**
```
New-NavContainer -accept_eula -accept_outdated -containername bc14docker -artifactUrl "https://bcartifacts.azureedge.net/onprem/14.22.46358.0/de" -PublicDnsName dockerhost.some.company -useSSL -useTraefik -shortcuts None -myscripts @("C:\ProgramData\mycompany\SetupCertificate.ps1", "C:\ProgramData\mycompany\mycompanySSL2020.PFX") -auth NavUserPassword -Credential $credential -additionalParameters @("--volume C:\ProgramData\mycompany\dockerBakFiles\:c:\bak", "--volume C:\ProgramData\mycompany\dockerAddIns:c:\addins") -enableSymbolLoading -assignPremiumPlan -licenseFile "C:\ProgramData\mycompany\dockerLicenseFiles\2021-02-11_mycompany_BC.flf" -sqlMemoryLimit "1G"
```

**Full output of scripts**
```
BcContainerHelper is version 1.0.19
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.14
Docker Server Version is 19.03.14
Fetching all docker images
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image mcr.microsoft.com/businesscentral:10.0.17763.1757
PublicDnsName is dockerhost.some.company
Creating Container bc14docker
Version: 14.22.46358.0-de
Style: onprem
Multitenant: No
Platform: 14.0.46351.0
Generic Tag: 1.0.1.4
Container OS Version: 10.0.17763.1757 (ltsc2019)
Host OS Version: 10.0.17763.1757 (ltsc2019)
Using process isolation
Using locale de-DE
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\ProgramData\mycompany\dockerLicenseFiles\2021-02-11_mycompany_BC.flf
Additional Parameters:
--volume C:\ProgramData\mycompany\dockerBakFiles\:c:\bak
--volume C:\ProgramData\mycompany\dockerAddIns:c:\addins
--hostname pi-dockertest
-e webserverinstance=bc14docker
-e publicdnsname=dockerhost.some.company
-l "traefik.protocol=https"
-l "traefik.web.frontend.rule=PathPrefix:/bc14docker"
-l "traefik.web.port=443"
-l "traefik.soap.frontend.rule=PathPrefix:/bc14dockersoap;ReplacePathRegex: ^/bc14dockersoap(.*) /NAV$1"
-l "traefik.soap.port=7047"
-l "traefik.rest.frontend.rule=PathPrefix:/bc14dockerrest;ReplacePathRegex: ^/bc14dockerrest(.*) /NAV$1"
-l "traefik.rest.port=7048"
-l "traefik.dev.frontend.rule=PathPrefix:/bc14dockerdev;ReplacePathRegex: ^/bc14dockerdev(.*) /NAV$1"
-l "traefik.dev.port=7049"
-l "traefik.dl.frontend.rule=PathPrefixStrip:/bc14dockerdl"
-l "traefik.dl.port=8080"
-l "traefik.dl.protocol=http"
-l "traefik.enable=true"
-l "traefik.frontend.entryPoints=https"
--env customNavSettings=PublicODataBaseUrl=https://dockerhost.some.company/bc14dockerrest/odata,PublicSOAPBaseUrl=https://dockerhost.some.company/bc14dockersoap/ws,PublicWebBaseUrl=https://dockerhost.some.company/bc14docker
Files in C:\ProgramData\BcContainerHelper\Extensions\bc14docker\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- license.flf
- MainLoop.ps1
- mycompanySSL2020.PFX
- SetupCertificate.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container bc14docker from image mcr.microsoft.com/businesscentral:10.0.17763.1757
da5432f06d00a086cfc87b79ae56b78a55ee22f7684e6971a4c0f964da85034f
Waiting for container bc14docker to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.22.46358.0/de
Using installer from C:\Run\130
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\DE\RTC\RoleTailoredClient.Local.De.msi
Skipping C:\NAVDVD\Installers\DE\WebHelp\WebHelp.Local.De.msi
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 124 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.31.144.1 in container hosts file
Starting Container
Hostname is pi-dockertest
PublicDnsName is dockerhost.some.company
Using NavUserPassword Authentication
Certificate File Thumbprint 6ACA6C1529F27493A8915CD0215D9DA9339EB27E
Import Certificate to LocalMachine\my
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting PublicODataBaseUrl to https://dockerhost.some.company/bc14dockerrest/odata
Setting PublicSOAPBaseUrl to https://dockerhost.some.company/bc14dockersoap/ws
Setting PublicWebBaseUrl to https://dockerhost.some.company/bc14docker
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Assign Premium plan for ADMIN
Container IP Address: 172.31.158.51
Container Hostname  : pi-dockertest
Container Dns Name  : pi-dockertest.dockertest.mycompany-informatik.de
Web Client          : https://pi-dockertest.dockertest.mycompany-informatik.de/bc14docker/
Dev. Server         : https://pi-dockertest.dockertest.mycompany-informatik.de
Dev. ServerInstance : NAV

Files:
http://pi-dockertest.dockertest.mycompany-informatik.de:8080/ALLanguage.vsix

Container Total Physical Memory is 32.0Gb
Container Free Physical Memory is 25.2Gb

Initialization took 84 seconds
Ready for connections!
Reading CustomSettings.config from bc14docker
Set SQL Server memory limit to 1024 MB
Container bc14docker successfully created
Because of Traefik, the following URLs need to be used when accessing the container from outside your Docker host:
Web Client:        https://dockerhost.some.company/bc14docker
SOAP WebServices:  https://dockerhost.some.company/bc14dockersoap
OData WebServices: https://dockerhost.some.company/bc14dockerrest
Dev Service:       https://dockerhost.some.company/bc14dockerdev
File downloads:    https://dockerhost.some.company/bc14dockerdl

Use:
Get-BcContainerEventLog -containerName bc14docker to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bc14docker to get debug information about the container
Enter-BcContainer -containerName bc14docker to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bc14docker to remove the container again
docker logs bc14docker to retrieve information about URL's again
```

**Screenshots**
#Docker Version in AL Object Browser (AZ AL Dev Tools/AL Code Outline)
<img width="1532" alt="Screenshot" src="https://user-images.githubusercontent.com/9556549/109870062-efb5a000-7c69-11eb-977b-eb9257dde5d5.png">
#DVD Installation Version in AL Object Browser (AZ AL Dev Tools/AL Code Outline)
<img width="1920" alt="Screenshot dvd installation" src="https://user-images.githubusercontent.com/9556549/109870409-589d1800-7c6a-11eb-8571-24f6ff9e7f3e.png">

**Comment by freddydk** [comment]
Could you compare the customsettings.config between the Docker version and the locally installed version?
(You can use Copy-FileFromBcContainer to copy the file out of the container - or Enter-BcContainer in PowerShell ISE and then PSEdit to edit a file directly in the ISE)

**Comment by freddydk** [comment]
You could also try to place the fob file in C:\ProgramData\bccontainerhelper and use;
Invoke-scriptInBcContainer -containername $containerName -scriptblock {
   Import-NAVApplicationObject -Path "C:\ProgramData\bccontainerhelper\mod.fob" -DatabaseServer localhost\sqlexpress -DatabaseName "CRONUS" -ImportAction Overwrite -SynchronizeSchemaChanges Yes
}

**Comment by freddydk** [comment]
I removed the two other comments after looked in the code.

Please try this first.
Right after creating the container, run: 
```
Generate-SymbolsInNavContainer -containerName bc14docker -sqlCredential $credential
```

and then do the other tests.
Let me know if this works - then I have a bug to fix.

Thanks

**Comment by DanielGoehler** [comment]
I created a new docker container and did this:
```
PS C:\Windows\system32> Generate-SymbolsInNavContainer -containerName bc14docker 
Creating application symbols in bc14docker 
[0] [04.03.21 12:48:53] The command completed successfully in '233' seconds.
Symbols successfully generated

PS C:\Windows\system32> Import-ObjectsToNavContainer -containerName bc14docker -objectsFile "C:\Users\myuser\Desktop\mod.fob" -ImportAction Overwrite -SynchronizeSchemaChanges Yes
Copy C:\Users\myuser\Desktop\mod.fob to container bc14docker  (c:\run\mod.fob)
Importing Objects from c:\run\mod.fob (container path)
Objects successfully imported

PS C:\Windows\system32> 
```
The Symbols [Microsoft_Application_14.22.46358.0.app.zip](https://github.com/microsoft/navcontainerhelper/files/6083429/Microsoft_Application_14.22.46358.0.app.zip) contain now all objects, but table 5330 has still the wrong name (Caption **Microsoft Dynamics 365 Connection Setup** instead of Name **CRM Connection Setup**)
<img width="1920" alt="Screenshot docker" src="https://user-images.githubusercontent.com/9556549/109960231-d6a00400-7ce8-11eb-9220-2ffbdeabd8a7.png">

**Comment by freddydk** [comment]
I don't think that is a docker problem
It looks like that is a deliberate rename - are you sure that isn't a rename in that version?

**Comment by DanielGoehler** [comment]
What do you mean with rename?

**Comment by freddydk** [comment]
Something that has changed in the product - I cannot imagine that docker can do that.

**Comment by DanielGoehler** [comment]
I'm not sure if this is a recent change. We discovered this in the [ALOps build pipeline](https://github.com/HodorNV/ALOps/issues/250#issuecomment-726779596) at BC 14 CU 6 in and the problem occurs up to the current CU 22. I am trying to recreate the problem with the DVD installation.

**Comment by DanielGoehler** [comment]
Could it be that this hack causes this issue?
https://github.com/microsoft/navcontainerhelper/blob/aea21fb54d8398d60c4ddc95be1099e46360cba3/ObjectHandling/Import-ObjectsToNavContainer.ps1#L68

**Comment by DanielGoehler** [comment]
Since there is no **GenerateSymbolReference** on **Import-NAVApplicationObject** I did **Compile-NAVApplicationObject** afterwards and that worked - at least BC14 CU 16.
```
PS C:\Windows\system32> Import-NAVApplicationObject -Path "C:\Users\myuser\Desktop\mod.fob" -DatabaseName CRONUS -DatabaseServer localhost\SQLEXPRESS -ImportAction Overwrite -SynchronizeSchemaChanges Yes -NavServerName localhost -NavServerInstance nav -NavServerManagementPort 7045 -Confirm:$false
PS C:\Windows\system32> Compile-NAVApplicationObject -DatabaseName CRONUS -DatabaseServer localhost\SQLEXPRESS -Filter 'Type=Table;Id=5330' -SynchronizeSchemaChanges Yes -NavServerName localhost -NavServerInstance nav -NavServerManagementPort 7045 -GenerateSymbolReference -Recompile
```
A while ago I wrote a FOB parser. It could be helpful to know which objects have to be compiled. 
```
var sr = new StreamReader(file);
while (!sr.EndOfStream)
{
    var navObject = new NavObject();
    var line = sr.ReadLine();
    sr.ReadLine();
    if (line != null)
    {
        if (line.StartsWith("")) //Hex 1A
            break;
        navObject.ObjectType = line.Substring(0, 10).TrimEnd();
        navObject.ObjectNo = line.Substring(10, 10).Trim();
        navObject.ObjectName = line.Substring(21, 30).TrimEnd();
    }
    objects.Add(navObject);
}
```
Could be another approach to importing FOBs. What do you think?

**Comment by freddydk** [comment]
I am not sure I can follow what is happening here?

When you create the container and generate symbols and then import your .fob file - everything works (except for one table which has a different name)
Did this table change name before or after the .fob import?
When you import inside a container session and compile. then the table will not change name? (you still did the initial generatesymbols after starting the container right)?

I want this to work. I want you to be able to use this, but C/AL and FOBs are dying technologies, so I do not want to spend a lot of time on fancy features in this area - also knowing that every time I change a bit, it might break somebody else.

Hope you understand.

**Comment by DanielGoehler** [comment]
> Did this table change name before or after the .fob import?

No, I did not change the name of the table.

> When you import inside a container session and compile. then the table will not change name? 

Yes

> (you still did the initial generatesymbols after starting the container right)?

Yes

> I am not sure I can follow what is happening here?

Yeah, ...

### Summary
**finsql.exe command=importobjects** creates symbols with the en-US caption instead of the name. If they are the same, there is no problem. In the case of table 5330, they are not. There is the same problem with pages, but I wanted to describe the problem as simply as possible.

### Details
I'm afraid I don't know exactly how the PowerShell CmdLet internally work, but I'm starting to get a feel for it. In the case of the CmdLet **Import-NAVApplicationObject** there is no GenerateSymbolReference. Because of that, you needed your hack.

I don't know what happens inside Import-NAVApplicationObject. But your hack makes me think that **finsql.exe command=importobjects** is called. I have now tried this with the DVD installation, can now reproduce the problem. Now I can open Microsoft Support case.

Since Import-NAVApplicationObject does not do a GenerateSymbolReference, I could not reproduce the problem at the DVD installation. If Microsoft fixes this, no need to change BCContainerHelper.

Unfortunately, BC14 will be around a least two more years.

If it is okay with you, I close this issue and come back if BCContainerHelper change would be necessary.

**Comment by freddydk** [comment]
got it.

Back in the day when I created Import-ObjectsInBcContainer, we didn't have the Invoke-Script function, hence a lot of override functions.
With Invoke-ScriptInBcContainer you can invoke all the standard NAV cmdlets inside the container and it makes the override functions less necessary.
If the BcContainerHelper functions doesn't work correctly, I will probably point at using a workaround and use Invoke-script...
Chances are that people who are using BcContainerHelper will break if I change the behavior of the function.

**Comment by DanielGoehler** [comment]
Hello @freddydk,
you may have already heard: I just got feedback from Microsoft support that this issue will not be not resolved, but they will update the documentation that this does not work.

This three steps worked for me.
```
Import-ObjectsToNavContainer -containerName bc14docker -objectsFile "C:\Users\myuser\Desktop\mod.fob" -ImportAction Overwrite -SynchronizeSchemaChanges Yes
Compile-ObjectsInNavContainer -containerName bc14docker -generatesymbolreference -SynchronizeSchemaChanges Yes
Invoke-ScriptInNavContainer bc14docker -scriptblock {Sync-NAVTenant nav -Force}
```

When you import large amounts of objects, I find that the **State** of the service tier is **OperationalWithSyncPending** and you can't access the database or download symbols. So run **Sync-NAVTenant** and everything works fine. I know **SynchronizeSchemaChanges** is set to **yes**, but I don't want to bother Microsoft support again with this because I suspect the result will be the same as in this support case.
