### ISSUE TITLE
Question regarding Run-TestsInBcContainer performance

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1768]
Hey @freddydk, 

I have been testing Run-TestsInBcContainer with two almost identical containers and comparing test performance:

- one container runs SQLServer within itself
- second cotnainer, connects to another sql server

My idea was move build database to external SQL server, hoping for the performance boost (since it's big and powerful machine compared to the host machine for containers). But, in the end results was opposite. Test runs **twice** faster in container with it's own database.

- my both containers runs on the same host machine
- container configuration is almost identical ( difference just in database setup)
- platform and application identical (databases are identical)
- containers host is just VM on Azure. SQL server is just another VM with SQL installed. It's under the same resource group, network, and proximity group. So latency between VMs should be minimal.
- I'm running very simple UI tests (opens like few hundred pages)
- database is very small. it's mainly empty company with few setup tables prepopulated
- tried to rerun the same test codeunit multiple times.  First run is always longer due to metadata cache. The following test runs are consistent.

Do you know if there's something I could do, to improve this performance when running container with external SQL? Or it's just loss due to additional networking layer (authentification), and should just forget it?:)

![image](https://user-images.githubusercontent.com/16342128/110041683-c87fd100-7d44-11eb-9515-c3d17722c578.png)

**Comment by freddydk** [comment]
Thanks for trying this out.
Did you test the latency between the two VMs? (you can use psping: https://docs.microsoft.com/en-us/sysinternals/downloads/psping)
When using SQL in the container, I don't think communication with the SQL Server ever reaches the TCP stack - it will probably use Shared Memory protocol.
You could also try to re-run the same tests with the SQL server on the Docker Host? to avoid that traffic leaves the host.

**Comment by gintuoklis** [comment]
I checked the latency between:
- SQL VM, & Host VM
- SQL VM & Container
 
There's a slight difference, but when latency is so low it does not matter.
![image](https://user-images.githubusercontent.com/16342128/110108692-c81b2080-7dac-11eb-8bf3-b4c62415b24d.png)

For the comparison, latency between my local machine & SQL VM/Host VM is ~6ms.

Will try to run container on the same machine as SQL server, to see if we brings any difference.

**Comment by gintuoklis** [comment]
short update. running container on the same machine as SQL server, produces results somewhere in between previous results. It's not very scientifically comparison, since specs of SQL server machine, and container host machine, I used in previous tests, is different. So it's hard to draw conclusions now. 

![image](https://user-images.githubusercontent.com/16342128/110692099-4715bc00-81e6-11eb-8a55-fbc2c33fb233.png)

**Comment by freddydk** [comment]
Did you ever reach any conclusion on this?
I assume that adding the network layer is the difference, but I have to say that I am as surprised by the result as you.
I would assume that a SQL Server placed on the host or like would be faster.

**Comment by gintuoklis** [comment]
Initially I wanted to use central SQL server linked to containers for build & tests. Hoping it would perform faster, and I could utilize resources better. Since the speed of running tests is important for us, ended up spinning docker images with SQL.

**Comment by freddydk** [comment]
Thanks
