### ISSUE TITLE
Compiler Output from Compile-AppInNavContainer

### ISSUE THREAD

**Issue by ChrisBlankDe** [Microsoft/navcontainerhelper#177]
While Compiling an app in the container the function will redirect the compiler Output to the Host.

> Microsoft (R) AL Compiler version 0.16.26913
> Copyright (C) Microsoft Corporation. All rights reserved
> 
> info AL1027: The file at location 'C:\agent\_work\1\s\CC\PermissionSets\CC EDIT.xml' matches the definition for 'PermissionSet'.
> info AL1027: The file at location 'C:\agent\_work\1\s\CC\PermissionSets\CC VIEW.xml' matches the definition for 'PermissionSet'.
> info AL1027: The file at location 'C:\agent\_work\1\s\CC\PermissionSets\CC.xml' matches the definition for 'PermissionSet'.
> warning AL1025: The file at location 'C:\agent\_work\1\s\CC\Media\Infos\TermsOfUse.txt' does not match any definition.

If its written with out-host we couldn't get it into an variable, right?
Is there any other possibility to get it into an variable?
It would be very helpful for CI/CD if we could parse it.

**Comment by richardrobberse** [comment]
I haven't looked into the command but write-host ends up in the information stream and not in the output stream.

I remember that I've assigned the output of the compiler to a variable and removed the first 3 lines of the array to just have the errors.

Ideally the cmdlet returns the compile errors as errors, this is definitely possible.

**Comment by ChrisBlankDe** [comment]
You are right. Write-Host will write into the Information Stream but the used Out-Host did not do this.

The line with the Out-Host I mean: https://github.com/Microsoft/navcontainerhelper/blob/e876571f1369afd66b5728e9bea38d9c884e457d/AppHandling/Compile-AppInNavContainer.ps1#L143

My code for testing:
```PowerShell
$Info =""
$Result = Compile-AppInNavContainer -containerName ABC -credential $credential -appProjectFolder $ProjectDir -InformationVariable info
Write-Host "The Info: $Info"
Write-Host "The Result: $Result"
```
Console output:
```
Using Symbols Folder:  C:\agent\_work\1\s\ComplianceCheck\symbols
Compiling...
Microsoft (R) AL Compiler version 0.16.26913
Copyright (C) Microsoft Corporation. All rights reserved

info AL1027: The file at location 'C:\agent\_work\1\s\CC\PermissionSets\CC EDIT.xml' matches the definition for 'PermissionSet'.
[...]
C:\agent\_work\1\s\CC\output\AwesomeApp_2.0.0.1.app successfully created in 18 seconds
The Result: C:\agent\_work\1\s\CC\output\AwesomeApp_2.0.0.1.app
The Info: Using Symbols Folder:  C:\agent\_work\1\s\CC\symbols Compiling... C:\agent\_work\1\s\CC\output\AwesomeApp_2.0.0.1_2.0.0.1.app successfully created in 19 seconds
```

**Comment by freddydk** [comment]
in 0.3.1.1 the Compile-AppInNavContainer has a flag called -AzureDevOps which will output errors in the right format to the build pipeine (Thanks Kamil Sacek for the PR)
In the next version there are also functions to convert Test Results to XUnit Xml format.
