### ISSUE TITLE
[New-BCContainer] LicenseFile parameter value always shown in output

### ISSUE THREAD

**Issue by JulienDecottignies** [microsoft/navcontainerhelper#1773]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Hi,

I have a Pipeline running in Azure DevOps that uses the New-BCContainer command. 
The pipeline uses a Library containing a licenseFile secret variable like this:
![image](https://user-images.githubusercontent.com/29598240/110313595-f3994780-8006-11eb-84c7-bd83212ae6b3.png)

I store in this variable the blob url to an azure container containing my license file.

The problem is that the license url value is shown in the output of my pipeline when New-BCContainer is executed
![image](https://user-images.githubusercontent.com/29598240/110313857-57bc0b80-8007-11eb-8958-ca53147a3fb9.png)

I've tried to convert it to a securestring before passing it to the licenseFile parameter but I have an error saying:
cannot find path 'c:\agent(...)**.System.security.SecureString**'

And if I "unsecure" my licenseFile url before using:
`$unsecureLicenseFile = ([System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureLicenseFile)))`

The result is the same: the ouput will show my blob url.

Before NEw-BCContainer executes, if I Write-Host my $licenseFile variable, the output shows me ***: this is what I expect to see when New-BCContainer Writes "using license (...) " to the host:
![image](https://user-images.githubusercontent.com/29598240/110314661-6f47c400-8008-11eb-816f-7024bf93ecdf.png)

How can I set the -licenseFile parameter and not showing its value in the pipeline output ?

Thanks for your help.

**Scripts used to create container and cause the issue**
New-BCContainer -artifactUrl $artifactUrl `
    -doNotCheckHealth `
    -updateHosts `
    -licenseFile $licenseFile `
    -containerName $containerName `
    -alwaysPull `
    -auth "UserPassword" `
    -Credential $credential `

**Full output of scripts**
```
licenseFile = ***
BcContainerHelper version 1.0.18
using artifact url https://bcartifacts.azureedge.net/sandbox/17.5.22499.22982/base
User 'admin' will be created with 'admin' as *** for this container
BUILD ENV = AzureDevOps
BcContainerHelper is version 1.0.18
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Removing container build
Removing build from host hosts file
Removing build-* from host hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\build
Fetching all docker images
Pulling image mcr.microsoft.com/businesscentral:10.0.17763.1757
10.0.17763.1757: Pulling from businesscentral
Using image mcr.microsoft.com/businesscentral:10.0.17763.1757
Disabling Health Check (always report healthy)
Creating Container build
Version: 17.5.22499.22982-W1
Style: sandbox
Multitenant: Yes
Platform: 17.0.22463.22964
Generic Tag: 1.0.1.4
Container OS Version: 10.0.17763.1757 (ltsc2019)
Host OS Version: 10.0.17763.1757 (ltsc2019)
Using hyperV isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file https://blablabla.flf
Downloading C:\ProgramData\BcContainerHelper\Extensions\build\my\license.flf
Additional Parameters:
--volume "C:\Agent:C:\Agent"
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\17.5.22499.22982\base\Demo Database NAV (17-0).bak
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by freddydk** [comment]
You license file should never be a public URL - you should use a secure URL (like a SAS token).
New-BcContainer will strip all parameters ?accesstoken=hkjadhakjshdjkahd off the URL and only show the public part.
In general this happens with all URLs (also URLs to apps being installed etc.)

**Comment by JulienDecottignies** [comment]
My bad, I was using anonymous read access as access level instead of private ... So even if the url was correctly truncated as you mentionned, I was still able to download it.
So yes, no matter if the first part of the url is shown in the output if we can't use it..!

Thanks for your help!
