### ISSUE TITLE
dynamicsnav:10.0.19041.572-generic not found: manifest unknown

### ISSUE THREAD

**Issue by gtrennert** [microsoft/navcontainerhelper#1778]
Hello

I removed all images / containers with zap

then I run the New-BcContainerWizard

Got this script : 

$containerName = 'bcfr-15-cu5'
$credential = Get-Credential -Message 'Using UserPassword authentication. Please enter credentials for the container.'
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '15.5' -country 'fr' #-select 'Latest'
New-BcContainer `
-accept_eula `
-containerName $containerName `
-credential $credential `
-auth $auth `
-artifactUrl $artifactUrl `
-licenseFile $licenseFile `
-memoryLimit 8G `
-updateHosts

The running script I get this errors : 

BcContainerHelper is version 1.0.14-dev
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Professionnel - 2004
Docker Client Version is 20.10.3
Docker Server Version is 20.10.3
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.572-generic
DockerDo : Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.19041.572-generic not found: manifest unknown: manifest tagged by "10.0.19041.572-generic" is not found
ExitCode: 1
Commandline: docker pull mcr.microsoft.com/dynamicsnav:10.0.19041.572-generic
Au caractère C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.14\ContainerHandling\New-NavContainer.ps1:681 : 13
+ DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

Could anybody help ?

**Comment by freddydk** [comment]
https://freddysblog.com/2021/03/01/navcontainerhelper-doesnt-work-anymore/

**Comment by gtrennert** [comment]
Hello I uninstalled NavContainerhelper and installed last version of BCContainerHelper
Now I have another issue : 
I want to use folders on my x: drive so I setup this BcContainerHelper.config.json :
{
    "hostHelperFolder": "x:\\BCContainers\\hostHelper",
    "bcartifactsCacheFolder": "x:\\BCContainers\\bcartifactsCache",
    "containerHelperFolder": "x:\\BCContainers\\containerHelper"
}

But this ends up with errors : 
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Professionnel - 2004
Docker Client Version is 20.10.2
Docker Server Version is 20.10.2
Downloading application artifact /onprem/15.5.41926.0/fr
Downloading X:\TMP\9fe6dc5d-cfad-49a1-b822-ab352064426e.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /onprem/15.5.41926.0/platform
Downloading X:\TMP\63a6d060-7564-4883-9dea-fd761cdc2318.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading x:\BCContainers\bcartifactsCache\onprem\15.5.41926.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading x:\BCContainers\bcartifactsCache\onprem\15.5.41926.0\platform\Prerequisite Components\Microsoft Report Viewer 2015\ReportViewer.msi
Downloading x:\BCContainers\bcartifactsCache\onprem\15.5.41926.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading x:\BCContainers\bcartifactsCache\onprem\15.5.41926.0\platform\Prerequisite Components\Microsoft Report Viewer 2015\SQLSysClrTypes.msi
Downloading x:\BCContainers\bcartifactsCache\onprem\15.5.41926.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
...
Digest: sha256:b6687c512167da6c778003abcef989f7f521f2db49ec8d4bf93af58edba3c22e
Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.19041.867
mcr.microsoft.com/businesscentral:10.0.19041.867
Using image mcr.microsoft.com/businesscentral:10.0.19041.867
Creating Container bcfr-15-cu5
Version: 15.5.41926.0-fr
Style: onprem
Multitenant: No
Platform: 15.0.41893.0
Generic Tag: 1.0.1.4
Container OS Version: 10.0.19041.867 (2004)
Host OS Version: 10.0.19041.867 (2004)
Using process isolation
Using locale fr-FR
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file xxx
Files in x:\BCContainers\hostHelper\Extensions\bcfr-15-cu5\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bcfr-15-cu5 from image mcr.microsoft.com/businesscentral:10.0.19041.867
750059f4d2cafd06daf3bf748b166f098bceca4106270635808958a00607ecff
DockerDo : docker: Error response from daemon: hcsshim::CreateComputeSystem 750059f4d2cafd06daf3bf748b166f098bceca4106270635808958a00607ecff: ParamÃ¨tre incorrect.
(extra info: {"SystemType":"Container","Name":"750059f4d2cafd06daf3bf748b166f098bceca4106270635808958a00607ecff","Owner":"docker","VolumePath":"\\\\?\\Volume{216cb3f7-682e-4cec-96c0-39056e02
ed59}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\750059f4d2cafd06daf3bf748b166f098bceca4106270635808958a00607ecff","Layers":[{"ID":"ba487442-2
819-53c5-98d7-1ff2a1f9fdb4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\31a41d8f3edd1ae692db0c317f80bc6d89b55e116d072c25e94a239093a16aaf"},{"ID":"c0c3ca7c-316c-5b67-9b8d-473dd3cb8fa0","P
ath":"C:\\ProgramData\\Docker\\windowsfilter\\769e6f93729331ac4fa3847082e725c8ed4b446a397bed838a02f8e1b54c1815"},{"ID":"88782571-a976-5559-a372-89544e2ecea4","Path":"C:\\ProgramData\\Docker\
\windowsfilter\\0b95a200ceab28b9fe8a5615772232676508e9422c0439ef7277fc77a8b0391a"},{"ID":"b6028852-ec82-5da4-b6d2-79a1e8f79444","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ef32d6152f2e93
1a2d706125913b83f4c3df4a8d4e107d69abf00d276e4e031d"},{"ID":"ddf77ed8-0c02-5f8a-b02a-5d8cced98336","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4f428c3b9696d4c9e9441b767ca0c2035ccd8040a3f3
6289a73f32f0a8a5bcba"},{"ID":"ae2d27e8-9212-572e-bbdf-48a83d93f3f1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\76de5bbbeaf888044156b181364eecaaf6fd8e0178bae45d360a4a96fb3a1832"},{"ID":"
554ee45d-a4c1-5b2f-9848-8be8222cf2d5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7784c635b23b79f5711284d8482a362ce50699a783ca6cd73d8b2971f48099d8"},{"ID":"dc0fe6a0-0879-5a4a-a8bc-f6d50b
1395c7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7a6b31fe07d6dde41bc46aa070166612f2bf76e7700f5132e3cbb1d72800092f"},{"ID":"42f0e435-3058-5454-a1e5-f9a4c6575167","Path":"C:\\ProgramDat
a\\Docker\\windowsfilter\\f9c03c6f9186e69304ab2df02d5a725051fcc88a2e9e73b3c9cb70e46070b09e"},{"ID":"4c34125b-c646-53e0-bbbb-37211d8b6263","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8246
68283c276424c0943cf8a855927345e594f80f8ec43a49974e3f7542a36e"},{"ID":"ab1f86b1-36a2-51aa-a1c4-ab6638a242b4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\69a7b0e8e63af410dd15b658abaf069e7a
c4991091693b48dc9351b84da12480"},{"ID":"36d93f62-8e88-53d9-b29f-0042f72df704","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6cc472e7dfa8547e158c5d0dad410745cb4fb4979a83545e05cd33cf68021089
"},{"ID":"e3b7c115-286f-5880-876f-cf6128b15c9f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7ab6aa255eedfa50e543672d5f49d9e4f19311c5f10b2a55a5aa32d9e23c096e"},{"ID":"fff5f487-aec4-5018-a
258-e69df9a59b64","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cf978d0037fb953603b32b3e1db38170d91afa537932e483672e486fc61ca6a8"},{"ID":"68b8df97-408a-58b0-9eb7-df8f7f1a688b","Path":"C:\\
ProgramData\\Docker\\windowsfilter\\a8a5bb8aa5239af70abd4df4dee1fbfb56a77cfa5cf3c578615e8f2541294c09"}],"MemoryMaximumInMB":8192,"HostName":"bcfr-15-cu5","MappedDirectories":[{"HostPath":"x:
\\bccontainers\\bcartifactscache","ContainerPath":"c:\\dl","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\windows\\system32\\drivers\\etc",
"ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"x:\\bccontainers\\hosthelper","ContainerPath":"x:\\bccontainers
\\containerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"x:\\bccontainers\\hosthelper\\extensions\\bcfr-15-cu5\\my","ContainerPath":"c
:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointList":["eb12b1ca-5a44-4936-bc6e-d2a52b57c67a"],"AllowUnqualifiedDNS
Query":true}).
ExitCode: 125
Commandline: docker run --volume "x:\BCContainers\bcartifactsCache:c:\dl" --label nav=1910 --label cu=cu5 --env isBcSandbox=N --label version=15.5.41926.0 --label platform=15.0.41893.0 
--label country=fr --env artifactUrl=https://bcartifacts.azureedge.net/onprem/15.5.41926.0/fr --env licenseFile="c:\run\my\license.flf" --name bcfr-15-cu5 --hostname bcfr-15-cu5 --env 
auth=NavUserPassword --env username="Admin" --env ExitOnError=N --env locale=fr-FR --env databaseServer="" --env databaseInstance="" --volume 
"x:\BCContainers\hostHelper:x:\BCContainers\containerHelper" --volume "x:\BCContainers\hostHelper\Extensions\bcfr-15-cu5\my:C:\Run\my" --isolation process --restart unless-stopped --env 
filesOnly=False --memory 8G --env enableApiServices=Y --env useSSL=N --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8ADgAbwB
LAE4AaQBoAGsAVgAxAHIAawBlAEEAeAArADgAQgAxAGsAUABZAFEAPQA9AHwAMgA5ADUANQBlADIAOABhAGEAMQBiADgAMwBmADMAMwA4ADUAOQA1ADQAMgA1ADcAZgAwADIANABjADEAMgAzADYAYgA2AGEAZgA3ADQAYwBhADUANAA4ADcANQA3ADAAY
gBmADEAYwA0AGEANwBjADEANwA5AGUAZQAyAGQANQA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach 
mcr.microsoft.com/businesscentral:10.0.19041.867
Au caractère C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\New-NavContainer.ps1:1660 : 15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
Sorry, I didn't see this message. It would be better to create a new issue when there is a new problem.
In this case, my guess is that you should remove "containerHelperFolder" from your config file.

**containerHelperFolder**
This folder is the folder INSIDE THE CONTAINER, which is mapped to the hostHelperFolder on the host. This value does not have to be the same as hostHelperFolder.
Source: https://freddysblog.com/2020/10/10/bccontainerhelper-configuration/
