### ISSUE TITLE
Cannot publish Extension to Business Central image

### ISSUE THREAD

**Issue by equisyscr** [Microsoft/navcontainerhelper#178]
Hi,

I try to publish an extension to a BusinessCentral image (microsoft/bcsandbox:gb).
I face an error when using the command `Publish-NavContainerApp -containerName yyyy -appFile "d:\xxx.app" -skipVerification -sync -install`

The error seems kinda explicit, but I cannot make my head around.
> docker : Error response from daemon: filesystem operations against a running Hyper-V container are not supported

How are we supposed to publish an extension to an image apparently using the Hyper-V ?

**Comment by freddydk** [comment]
The Cmdlet tries to copy the app to the container, which apparently doesn't work in your case.
If you place the app in c:\programdata\navcontainerhelper - then this folder is shared with the container and the container can pick the app from there.

**Comment by equisyscr** [comment]
Thanks freddydk, good to know we have an easy shared folder.

For this particular example, I went another route as I am the owner of the app code and directly setup visual studio code with the AL extension to install the .app on the docker image, which solved my issue.

for others that could face the issue, here is the configuration needed in the launch.json:
>  {
>             "type": "al",
>             "request": "launch",
>             "name": "Microsoft cloud sandbox",
>             "server": "http://containerName",
>             "serverInstance": "NAV",
>             "authentication": "UserPassword"
> }

**Comment by freddydk** [comment]
Looked a little more into this.
I think the reason for the error might be that you were not running the PowerShell prompt as administrator.
Can you confirm this for me?

Thanks

**Comment by freddydk** [comment]
Please reopen if this is NOT caused by the cmdlet is running as non-administrator.
