### ISSUE TITLE
license file not loading

### ISSUE THREAD

**Issue by davmac1** [microsoft/navcontainerhelper#1783]
I was receiving a license error when trying to install automated tests in OnPrem
Since I have a partner license, this should not be a problem.
My $ContainerLicFile  is set to my partner license C:\BC\9999.flf (actual number not shown here)
script shown below.
I also found for OnPrem I had to specify country us (na only works for version 16 and below).

```
New-BCContainer @parameters `
                -accept_eula `
                -containerName $ContainerName `
                -artifactUrl $artifactURL `
                -auth NAVUserPassword `
                -Credential $credential `
                -updateHosts `
                -assignPremiumPlan `
                -includeTestToolkit
                -shortcuts StartMenu `
                -licenseFile $ContainerLicFile `
                -EnableTaskSchedule:$false `
                -memoryLimit 8G `
                -includeAL `
                -alwaysPull `
                -isolation hyperv
```

**Comment by freddydk** [comment]
What error?
I need the ourput if I am to look at anything

Yes, from 17, onprem ships as us, ca and mx instead of NA - that is not only docker, that is also the .zip downloads

**Comment by davmac1** [comment]
The problem is I don't get an error until it tries to load the test automation.
I then checked and saw I have the Cronus license installed and not my license file.

**Comment by freddydk** [comment]
I have formatted the script above with the "Insert Code" marking.
Now it is obvious that you are missing a ` after the -installTestToolkit line.
Meaning that all subsequent lines are seen as a new command.

**Comment by davmac1** [comment]
thanks - I had inserted the line since I had not been in the script before.
I was visually processing it was there since it should have been there.

So far all our BC17 work has been sandbox.
The onprem clients are slower to upgrade even though it is easy.
This includes build updates as well.
