### ISSUE TITLE
Error Handling & Compile-ObjectsInNavContainer

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1784]
Hey @freddydk, 

I am working on a script to compile the objects in navcontainer. I am want to catch the errors, and try compilation again. But, cannot get Compile-ObjectsInNavContainer to work for me. It always throws an error. See what i tried bellow. Is there something I can do?

simple compliation - no error handling here. fails as expected
`Compile-ObjectsInNavContainer -containerName develop -filter 'Type=5;ID=50000' -sqlCredential (Get-StoredCredential sa) `

trying to use common parameters (erroraction/errorvariable). standard NAV command `Compile-NAVApplicationObject `works perfectly with them
`Compile-ObjectsInNavContainer -containerName develop -filter 'Type=5;ID=50000' -sqlCredential (Get-StoredCredential sa) -ErrorAction SilentlyContinue -ErrorVariable compilationError`

assigning to variable:
`$result = Compile-ObjectsInNavContainer -containerName develop -filter 'Type=5;ID=50000' -sqlCredential (Get-StoredCredential sa)`

outputting to null:
`Compile-ObjectsInNavContainer -containerName develop -filter 'Type=5;ID=50000' -sqlCredential (Get-StoredCredential sa) |out-null`

use try/catch:
`try {Compile-ObjectsInNavContainer -containerName develop -filter 'Type=5;ID=50000' -sqlCredential (Get-StoredCredential sa) } catch {"error occured"}`

every time, powershell prints the error for me:

![image](https://user-images.githubusercontent.com/16342128/110814645-ecce3700-8289-11eb-93ef-ab8f63de7ea6.png)

**Comment by freddydk** [comment]
Could you include script + output of the container generation.

**Comment by gintuoklis** [comment]
```
$Credential = Get-Credential
$additionalParameters = @("--volume ""$('"C:\Users\master\Documents\DLLs"'):c:\run\Add-ins""")
 New-BcContainer -containerName build-test `
            -accept_eula `
            -accept_outdated `
            -artifactUrl (Get-BCArtifactUrl -type OnPrem -country 'w1' -version '14.18') `
            -auth NavUserPassword `
            -Credential $Credential `
            -doNotExportObjectsToText `
            -doNotCheckHealth `
            -licenseFile "C:\Users\master\Desktop\NAV BC on Prem - 5194146 - 22012021 v15.flf" `
            -locale "nl-NL" `
            -updateHosts `
            -additionalParameters $additionalParameters
```


BcContainerHelper is version 2.0.6
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.17763.1817
Disabling Health Check (always report healthy)
Creating Container build-test
Version: 14.18.45015.0-w1
Style: onprem
Multitenant: No
Platform: 14.0.45012.0
Generic Tag: 1.0.1.4
Container OS Version: 10.0.17763.1817 (ltsc2019)
Host OS Version: 10.0.17763.1817 (ltsc2019)
Using process isolation
Using locale nl-NL
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\master\Desktop\NAV BC on Prem - 5194146 - 22012021 v15.flf
Additional Parameters:
--volume ""C:\Users\master\Documents\DLLs":c:\run\Add-ins"
Files in C:\ProgramData\BcContainerHelper\Extensions\build-test\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container build-test from image mcr.microsoft.com/businesscentral:10.0.17763.1817
2e102871618e9c76164bd44e5fc8e77318e65ecd5a6bb21c27809873673be8c1
Waiting for container build-test to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.18.45015.0/w1
Using installer from C:\Run\130
Copying Platform Artifacts
Copying Application Artifacts
Copying Database
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
Restoring CRONUS Demo Database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 43 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.31.224.1 in container hosts file
Starting Container
Hostname is build-test
PublicDnsName is build-test
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint E6457EB5D88A7F06E71A0E77C1E89FD3844EDC49
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating gps as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.31.228.185
Container Hostname  : build-test
Container Dns Name  : build-test
Web Client          : http://build-test/NAV/
Dev. Server         : http://build-test
Dev. ServerInstance : NAV
Setting build-test to 172.31.228.185 in host hosts file

Files:
http://build-test:8080/ALLanguage.vsix

Container Total Physical Memory is 16.0Gb
Container Free Physical Memory is 4.6Gb

Initialization took 39 seconds
Ready for connections!
Reading CustomSettings.config from build-test
Creating Desktop Shortcuts for build-test
Container build-test successfully created

Use:
Get-BcContainerEventLog -containerName build-test to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName build-test to get debug information about the container
Enter-BcContainer -containerName build-test to open a PowerShell prompt inside the container
Remove-BcContainer -containerName build-test to remove the container again
docker logs build-test to retrieve information about URL's again

**Comment by freddydk** [comment]
Changing these functions will require me to do extensive testing on C/AL functionality and I am not sure my time is best spend on that.
I recommend that you use:

```
Invoke-ScriptInBcContainer -containername $containerName -scriptblock {
    Compile-NAVApplicationObject your parameters
}
```
Instead of using Compile-ObjectsInBcContainer.
This way you are in 100% control.

If you then find something that works for you, you are more than welcome to share it here - then I might add that to the function.

Hope you understand.
