### ISSUE TITLE
Publish failes because Path in Sort-AppFilesByDependencies is null

### ISSUE THREAD

**Issue by michvllni** [microsoft/navcontainerhelper#1785]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I'm trying to publish using `Publish-BcContainerApp`. It always fails because apparently it can't find my App File. The app file is definetely shared with the container, I've confirmed it with `Get-BcContainerPath`. The error get's thrown when the script tries to sort the app files. 

It tries to find the file in `C:\ProgramData\BcContainerHelper\Extensions\DEV\8f014eb1-3e9f-4162-a8b2-5b3e3a159027\myapp_1.0.0.0.app` which ist not a path that my container can reach. Does this path get injected by your scripts into the container? Unfortunately, I cannot use `New-BcContainer` to create the container as im using docker-compose.

Do i need to add this directory as a volume?

**Scripts used to create container and cause the issue**
I created the image with this
```
$url = Get-BCArtifactUrl -country "DE" -version "17.4" -type OnPrem
$baseImage = Get-BestGenericImageName -onlyMatchingBuilds

New-BcImage -artifactUrl $url `
-imageName "$repository/myimage:latest" `
-isolation "hyperv" `
-addFontsFromPath "$fontDir" `
-baseImage $baseImage `
-memory "20G"
```
This is the docker-compose.yml
```
version: '3.3'
services:
  DEV:
      image:  myimage:latest
      container_name: DEV
      hostname: DEV
      volumes:
        - c:\Docker\additionalsetup:c:\run\my
        - c:\public:c:\public
        - C:\Docker\dotnet:C:\dotnet
      environment: 
        - ACCEPT_OUTDATED=Y
        - accept_eula=y
        - bakFile=C:\Program Files\Microsoft Dynamics NAV\170\database\database.bak
        - usessl=n
        - ExitOnError=N
```

And this is the call to the function
```Publish-BcContainerApp -containerName DEV -appFile "C:\public\me_myapp_1.0.0.0.app" -skipVerification -sync -syncMode ForceSync -install -upgrade -credential $cred -ShowMyCode True```
**Full output of scripts**
```
BcContainerHelper version 2.0.7
Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
bei Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Zeile 39
bei <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\AppHandling\Sort-AppFilesByDependencies.ps1: Zeile 42
bei Sort-AppFilesByDependencies, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\AppHandling\Sort-AppFilesByDependencies.ps1: Zeile 36
bei Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\AppHandling\Publish-NavContainerApp.ps1: Zeile 111
bei <ScriptBlock>, <Keine Datei>: Zeile 1
bei Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Zeile 44
bei <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\AppHandling\Sort-AppFilesByDependencies.ps1: Zeile 42
bei Sort-AppFilesByDependencies, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\AppHandling\Sort-AppFilesByDependencies.ps1: Zeile 36
bei Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\AppHandling\Publish-NavContainerApp.ps1: Zeile 111
bei <ScriptBlock>, <Keine Datei>: Zeile 1
Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\Invoke-Script
InNavContainer.ps1:45 Zeichen:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot validate... command again.:String) [], Runti
   meException
    + FullyQualifiedErrorId : Cannot validate argument on parameter 'Path'. The argument is null or
   empty. Provide an argument that is not null or empty, and then try the command again.
...
```

**Additional context**
Windows Version: Windows 10 20H2 19042.804

I also tested it on a Windows Server 1809 17763.1757 (With a slightly different image with isolation=process) and the same thing happened.

- did it use to work? yes, back when i was at 1.12 it worked. It is most likely connected to [this commit (lines 41-43)](https://github.com/microsoft/navcontainerhelper/commit/7aaf9779e44e9c69226f48c9afe77925b7f05b68#diff-148e6879a3c70d96d1fe53f6e8ee0a7cc511c7a428225f8074345e84d533218c)

**Comment by freddydk** [comment]
In general, I would assume that a lot of the commands in BcContainerHelper will assume that the hosthelperfolder is shared with the container.

Two things you can do to fix the issue.
1. in BcContainerhelper.config.json, you can set the hostHelperFolder to a folder, which is shared with the container.
2. you can share c:\programdata\bccontainerhelper with the container.

The reason for the change is to be able to sort runtime packages as well as normal apps - and in that case I use the container.

**Comment by michvllni** [comment]
Okay, thanks for the quick reply :)

I will add the directory as a volume.
