### ISSUE TITLE
Pipeline does not fail when using Run-TestsInBCContainer with AzureDevops error parameter

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1786]
Hey @freddydk, 

There's something suspicious about Run-TestsInBCContainer command. I want my pipeline to fail, if test cases fails.

Plesek check the screesnshot. As you can see, test runner writes errors to the output, but task still goes green anyway.

![image](https://user-images.githubusercontent.com/16342128/110934920-007fa900-832f-11eb-984a-2da5b8139226.png)

Here's my pipeline code. Function "Run-NAVTests" is just a wrapper around yours Run-TestsInBCContainer (we use our function, since some developers are working with docker, and some with locally installed instances. so we basically support both scenarios within our function. For the docker part, we fully use bccontainerhelper functions)

```
 - powershell: |
              Import-Module $(Pipeline.Workspace)\scripts\imvcicd.psm1
              $cred = New-Object pscredential $(user), (ConvertTo-SecureString -String $(psw) -AsPlainText -Force)
              $resultFile = join-path $($(Get-BcContainerSharedFolders -containerName $(containerName)).keys)[0] "TestResults$(Build.BuildId).xml"
              echo "##vso[task.setvariable variable=testresultFile]$resultFile"
              $testCompanyName = 'AutoTest'
              $autoTestCompanyExist = Get-CompanyInBcContainer $(containerName) | Where-Object -Property CompanyName -eq $testCompanyName
              if (!$autoTestCompanyExist) {
                New-CompanyInNavContainer -containerName $(containerName) -companyName $testCompanyName
              }
              Update-NAVTestsSuite -containerName $(containerName) -companyName $testCompanyName
              Run-NAVTests -containerName $(containerName) -credential $cred -companyName $testCompanyName -AzureDevOps "Error" -XUnitResultFileName $resultFile
            displayName: RunTests                
- task: PublishTestResults@2
            displayName: 'Publish Test Results'
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: XUnit
              testResultsFiles: $(testresultFile)
              testRunTitle: 'BC Test Results: $(Build.BuildId)'   

```

According to your blog [post](https://freddysblog.com/2019/10/22/running-tests-in-containers-2/), if I set AzureDevOps to "Error" it should cause the pipeline to fail.
![image](https://user-images.githubusercontent.com/16342128/110936285-f199f600-8330-11eb-8cbe-0e89a6247a45.png)

Container is running BC 14

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
Personally I use:
- task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: and(succeeded(),ne(variables['TestResults'],''))
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '$(testResults)'
      failTaskOnFailedTests: true

I don't want the pipeline to fail on running the tests, I want it to fail when analyzing the tests.

**Comment by freddydk** [comment]
If the AzureDevOps was set correctly, it should spit out:

##vso[task.logissue type=$AzureDevOps;sourcepath=$name;]$firstError
and not ##[Error]
I cannot find anywhere in PsTestFunctions where I output ##[Error] - that is a riddle to me?

**Comment by gintuoklis** [comment]
I think, azuredevops translate this code
`Write-Host "##vso[task.logissue type=$AzureDevOps;sourcepath=$($_.method);]$($_.message)"`
to 
##[Error]...

I looked at the official documentation, and i believe you are missing `exit 1` at the end of test run. 
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=azure-devops

![image](https://user-images.githubusercontent.com/16342128/110948937-45f9a180-8342-11eb-9147-84f34b280178.png)

Nevermind, i will try your approach with failTaskOnFailedTests on PublishTestResults

**Comment by freddydk** [comment]
This is how my pipelines look:
![image](https://user-images.githubusercontent.com/10775043/111289572-95431900-8645-11eb-941f-3bb9bc9d78d8.png)
inside:
![image](https://user-images.githubusercontent.com/10775043/111289663-a855e900-8645-11eb-8bd3-b6b968a52e76.png)
If you have 10 test apps you want to run, you do not want the pipeline to fail after the first.
You want to run all test and collect the results, so I definitely do not wait to add an exit 1.

**Comment by epernst** [comment]
If you don't do as Freddy suggest, then you will not be able to use the Azure DevOps test feature to mark individual failing tests as flaky.
