### ISSUE TITLE
Using Get-BcInstalledExtensions gets ErrorCode 400

### ISSUE THREAD

**Issue by DanjoDE** [microsoft/navcontainerhelper#1787]
Hi,
I am trying to get a list of my installed Extensions inside out Production-Tenant.

Error in German:
Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.  (ms-correlation-x = 7a1ab01e-63a8-4920-816b-d7e934d77eea)
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\BcSaaS\Get-BcInstalledExtensions.ps1:44 Zeichen:9
+         throw (GetExtenedErrorMessage $_.Exception)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Der Remoteserve...b-d7e934d77eea):String) [], RuntimeException
    + FullyQualifiedErrorId : Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.  (ms-correlation-x = 7a1ab01e-63a8-4920-816b-d7e934d77eea)
 
Using Get-BcEnviroments with the same bcAuthContect works like a charm.
Is there anything I can do to get more information on the error when calling the funtion?

**Comment by freddydk** [comment]
I think maybe the Get-BcInstalledExtensions needs a user in BC, where Get-BcEnvironments needs a delegated admin?

**Comment by DanjoDE** [comment]
That was the problem.
The user had no longer an assigned license.
Tanks a lot :-)
