### ISSUE TITLE
Idea: Cmdlet for installation or update of ALLanguage.vsix in VSCode

### ISSUE THREAD

**Issue by mitrov** [microsoft/navcontainerhelper#1789]
**Describe the issue**
We develop our app against different BC versions (BC15, BC16, BC17, BC18, ...  onPrem & SaaS). One mistake which happens a lot is that the developer doesn't have the latest ALLanguage.vsix installed in VSCode. So the developer might see errors in VSCode which are not real errors, but doesn't know because it's not obvious.

My understanding is that the ALLanguage.vsix is backward compatible and we could always install the **latest** ALLanguage.vsix available (including the ones from nextMinor / nextMajor). Please correct me if I'm wrong.

My question is: Could we have something like Get-ALLanguageVSIX as part of the BCContainerHelper?
It could work like the Get-BcArtifactUrl which returns an URL to the VSIX. VSCode supports command line installation of extensions.

So the Cmdlet could be used for adhoc installation of latest VSIX on dev machines or automatic nightly scripts.
What are your thoughts on this?

**Comment by freddydk** [comment]
Get-LatestAlLanguageExtensionUrl exists.
This will give you the latest vsix from marketplace.

if you want the latest insider, then you would need:
```
$artifactUrl = Get-BCArtifactUrl -country us -select NextMajor -sasToken $insiderSasToken
$paths = Download-Artifacts -artifactUrl $artifactUrl -includePlatform
$vsixPath = (get-childItem -path $paths[1] -Filter 'ALLanguage.vsix' -Recurse | Select-Object -First 1).FullName
```
Installing the vsix in code can be done from the command line as well - I don't do that in Containerhelper.

**Comment by mitrov** [comment]
Thanks @freddydk

I'll probably implement the second script as a nightly job since it's downloading the entire 2 GB of artifacts.
