### ISSUE TITLE
Suggestion for Flush-ContainerHelperCache: different keepDays for Sandbox, insider Sandbox and OnPrem

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#1790]
**Describe the issue**
When I use the _BCContainerHelper_ in the build pipeline, it would be nice if I could run **Flush-ContainerHelperCache** with different **keepDays** for **Sandbox**, **Insider Sandbox** and **OnPrem**.

- **Sandbox**: I notice that there are many builds within each CU. These accumulate a bit over the course of a month. The old builds are no longer used and could be removed to free up hard disk space.
- **Insider Sandbox**: Because every day there is a build, the next day there is a new build. That accumulates pretty quickly over the course of a month. The old builds are no longer used and could be removed to free up hard disk space.
- **OnPrem**: The customer has specific CU installed and this version will be used several times a month.

**Comment by freddydk** [comment]
Good idea, will think about that.

**Comment by freddydk** [comment]
Looked at the code.
I cannot see in the artifacts cache whether the artifacts came from insider, public preview or normal bcartifacts.
I can see whether they are onprem or sandbox.

I will add a cache option for sandboxartifacts.

Flush-ContainerHelperCache -cache sandboxartifacts -keepdays 3
Removes all sandbox artifacts not used within the last three days.

Flush-ContainerHelperCache -keepdays 30
Removes all other cache items not used within the last 30 days (including all images from artifacts no longer present)

**Comment by DanielGoehler** [comment]
This would be really nice.

**Comment by freddydk** [comment]
Shipped in 2.0.9
