### ISSUE TITLE
Restore-BcDatabaseFromArtifacts does not seem to work

### ISSUE THREAD

**Issue by Sven-Niehus** [microsoft/navcontainerhelper#1792]
**Describe the issue**
Restore-BcDatabaseFromArtifacts does not work, because the PowerShell module that is imported in [line 82](https://github.com/microsoft/navcontainerhelper/blob/12d7d232bd71447f4f43776c5103fb36ef4b4b52/Bacpac/Restore-BcDatabaseFromArtifacts.ps1#L82) does not exist nor can it be installed anymore. The SqlServer PowerShell module should be used as stated in this Microsoft document: https://docs.microsoft.com/en-US/sql/powershell/download-sql-server-ps-module?view=sql-server-ver15

**Scripts used to create container and cause the issue**
```
```

**Full output of scripts**
```
```

**Screenshots**

**Additional context**

**Comment by freddydk** [comment]
The reason for this is that New-NavDatabase uses sqlps and the current code uses that.
Furthermore, I use the smoServer, which I can load after importing sqlps.
sqlps comes with SQL Server (not sure if it is part of client sdk)

I might extend the function with check on whether sqlps is there and if not - then do the same without, but that is a future idea.

**Comment by freddydk** [comment]
As of Preview404 - this should now work.
#1800 is the same issue from @kine which came together with a PR for the solution.
