### ISSUE TITLE
401 after initialization when changed from NAVcontainerhelper to BCcontainerhelper

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/navcontainerhelper#1795]
Hi,

having rewritten our scripts to use bccontainerhelper instead of navcontainerhelper, I keep getting 401 when trying to download symbols. 

Here's the full initialization:
(artifacturl https://bcinsider.azureedge.net/sandbox/18.0.23013.23365/fi?sv=2019-12-12..)

```
$password = ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force
$credential = New-Object PSCredential 'admin', $password
New-BcContainer -updatehosts -containername $containername -artifactUrl $artifactUrl -accept_eula -memoryLimit "5g" -accept_outdated -auth UserPassword -credential $credential -licenseFile  $licensefilepath -verbose -additionalParameters $additionalParameters -myscripts @( @{ "SetupVariables.ps1" = 'if (Get-ItemProperty -Path "HKLM:\system\CurrentControlSet\control" | Select-Object -ExpandProperty "ServicesPipeTimeout" -ErrorAction SilentlyContinue) {
        Write-host "ServicesPipeTimeout already set"
        $restartingInstance = $false
        $newPublicDnsName = $true
        . "c:\run\SetupVariables.ps1"
        }
        else {
        Write-host "Set ServicesPipeTimeout and restart"
        Set-ItemProperty -Path "HKLM:\system\CurrentControlSet\control" -name "ServicesPipeTimeout" -Value 2000000 -Type DWORD -Force
        Restart-computer
        Start-Sleep -seconds 10000
        }' 
    })
```

Username exists in sql db.

> ALTER ROLE db_datareader ADD MEMBER admin
2> go
Msg 15151, Level 16, State 1, Server BCCONT\SQLEXPRESS, Line 1
User, group, or role 'admin' already exists in the current database

I also tried with removing the credential-parameter and manually entering a password. Did not make a difference. Username-parameter userpassword and navuserpassword end in the same result.

Using Authorization : Basic ----xcbzxcb----
Fetching @{appname=System; version=17.0.0.0} from http://172.20.5.63:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=17.0.0.0.. 
Error in downloading symbols, aborting.
Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (401) Unauthorized."

Nor can I connect from VS Code.

**Comment by freddydk** [comment]
The user used by VS Code is not a SQL User - it is the BC user.
After creating the container - you can try:
```
New-BcContainerBcUser -containerName $containerName -Credential $credential -PermissionSetId SUPER -ChangePasswordAtNextLogOn:$false 
```

**Comment by navdotnetreqs** [comment]
$pw = convertto-securestring -AsPlainText -Force -String $bcpassword
$credential = new-object -typename System.Management.Automation.PSCredential -argumentlist $bcusername,$pw

New-BcContainerBcUser -containerName BCkontti -Credential $credential -PermissionSetId SUPER -ChangePasswordAtNextLogOn:$false

->Creating User bcuser
->Assigning Permission Set SUPER to bcuser

Still 401 when trying to download symbols or connect from vs code.

**Comment by freddydk** [comment]
What does your launch.json look like?
and you are using the bcuser from VS Code right?

**Comment by navdotnetreqs** [comment]
Am using the exact credentials that were created and the webclient accepted. This launch-json and everything else worked before switching to BChelper and a newer docker image. Only ip has changed.

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Bc container",
            "server": "http://172.20.2.55",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true
        }
    ]
}

**Comment by navdotnetreqs** [comment]
After wasting half a day on this, I found similar problems online, and adding

            "tenant": "default"

to the launch.json solved this.

I am tired of being both a guinea pig and debugger for constant breaking changes, I wish we could invoice Microsoft for each such issue.

**Comment by freddydk** [comment]
Sorry for that. BcContainerHelper has always used multitenancy by default, so this breaking change was done in August 2020.
VS Code adds tenant: default to new launch.json files since x months as well.

But, this is also why I always need people to post scripts, full output and as much information as possible (like launch.json) then I can answer these questions faster. For me it is also a waste of time to ask for more info 10 times before I can answer. But... I guess you would say that that is my job.
