### ISSUE TITLE
Get-bcartifacts is ridiculously slow, ref #1646

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/navcontainerhelper#1796]
BcContainerHelper version 2.0.8-preview402

Measure-Command {Get-BCArtifactUrl -country fi -storageAccount bcartifacts -type sandbox}
Days              : 0
Hours             : 0
Minutes           : 2
Seconds           : 47
Milliseconds      : 787
Ticks             : 1677876080
TotalDays         : 0,0019419862037037
TotalHours        : 0,0466076688888889
TotalMinutes      : 2,79646013333333
TotalSeconds      : 167,787608
TotalMilliseconds : 167787,608

**Comment by freddydk** [comment]
Is that still the case?
Here, I get:
![image](https://user-images.githubusercontent.com/10775043/111538649-3d073680-876d-11eb-9acb-592867bec1cb.png)

**Comment by freddydk** [comment]
I think this was a temporary glitch in storage accounts - I got another issue from somebody who couldn't download artifacts.

**Comment by navdotnetreqs** [comment]
Ok, thanks. How much data is transferred in the call? Could be a network issue as well, if processing is done after downloading a huge amount of stuff. Coulnd't it be done server-side?

**Comment by freddydk** [comment]
There is no Server-side.

The function is basically enumerating blobs to see which blobs are there - it does set filters where it can.
That list can be long, but on my machine this is typically less than 10 seconds.

**Comment by navdotnetreqs** [comment]
Hi, 42 seconds now.

I know there is no server side now, but IMO there should be. Why should every user always fetch a ridiculous list of blobs to filter locally, when the filter parameters could be passed in the http-request and only relevant blobs returned? Something only ms could fix.

**Comment by freddydk** [comment]
There is a filter, you can set the version number (or parts of it)

```
Measure-Command {Get-BCArtifactUrl -country fi -storageAccount bcartifacts -type sandbox -version 17}
```
takes 4 seconds here.
and this:
```
Measure-Command {Get-BCArtifactUrl -country fi -storageAccount bcartifacts -type sandbox -version 17.5}
```
takes 0,4 seconds.
