### ISSUE TITLE
Could not download from https://bcartifacts.azureedge.net/..., retrying from https://bcartifacts.blob.core.windows.net/...

### ISSUE THREAD

**Issue by MBK75** [microsoft/navcontainerhelper#1797]
Hello, it looks like artifact images are not available today, but I want to make sure nothing is wrong on my end.

My script:
```
$containerName = 'mycontainer'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'us' -select 'Latest'
$licenseFile = 'BC v17 Dev License.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -multitenant:$false `
    -licenseFile $licenseFile `
    -updateHosts
```

The output (this hangs at the end quite a while):
`Could not download from https://bcartifacts.azureedge.net/..., retrying from https://bcartifacts.blob.core.windows.net/...`

Then errors out:

`Download-File : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.19\Misc\Download-Artifacts.ps1:157 char:21
+ ...             Download-File -sourceUrl $platformUrl -destinationFile $p ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File`

**Comment by freddydk** [comment]
Could you share what $artifactUrl is?

**Comment by MBK75** [comment]
Hi Freddy, thanks for the reply.  I ran `Get-BcArtifactUrl -type 'Sandbox' -country 'us' -select 'Latest'` and the output is: https://bcartifacts.azureedge.net/sandbox/17.5.22499.23364/us

**Comment by freddydk** [comment]
I copied your script and ran it (only changing the license file) - works fine here.
could be something with the CDN, not sure.
Do you still get an error?

**Comment by freddydk** [comment]
Note that you are running an old BcContainerHelper - not that I think that is the issue here.

**Comment by MBK75** [comment]
Hi Freddy, it works now.  Sorry for the trouble - must have been a temporary hiccup somewhere

**Comment by freddydk** [comment]
Yeah, storage accounts also had a problem after the big breakdown - maybe a follow up after that.
