### ISSUE TITLE
c:\Run\MainLoop.ps1' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by navdotnetreqs** [microsoft/navcontainerhelper#1802]
Hi,

BcContainerHelper 2.0.8-preview402 crashes when trying to create a bc-docker,

...
Using artifactUrl https://bcinsider.azureedge.net/sandbox/18.0.23013.23421/fi
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Serverdocker : . : The term 'c:\Run\MainLoop.ps1' is not recognized as the name of a cmdlet, 
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.8\ContainerHandling\Wait-NavContainerReady.ps1:31 char:21
+             $logs = docker logs $containerName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (. : The term 'c...e of a cmdlet, :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Looking through sources I found that when passing -dumpEventLog I can skip this bug.

**Comment by navdotnetreqs** [comment]
However, with -dumpEventLog, creation crashes with


Changing Database Server Collation to Finnish_Swedish_100_CS_ASdocker : 
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.8\ContainerHandling\Wait-NavContainerReady.ps1:31 char:21
+             $logs = docker logs $containerName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by freddydk** [comment]
Please post the script you are using to get this error?
