### ISSUE TITLE
Invoke-ScriptInBCContainer ends with "The Hyper-V socket target process has ended."

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#1803]
When using Invoke-ScriptInBCContainer e.g. when sync-navapp for Base Application during database upgrade, when the script takes longer time and no output during this time the call ends with error like:

```
The background process reported an error with the following message: "The Hyper-V socket target process has ended.".
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.8\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 39
```
It seems that the problem is Timeout of the Session created to the container. There is no way how to set the timeout.

Temporary solution for me was to modify Get-NAVContainerSession.ps1 and use this:
```
        $so = New-PSSessionOption -IdleTimeout 600000
        $session = New-PSSession -ContainerId $containerId -RunAsAdministrator -SessionOption $so
```
I can prepare PR but what will be optimal way how to set the timeout? New parameter? But where? Because if I call Invoke-ScriptInBCContainer, it could reuse existing session already created with some different timeout...

**Comment by freddydk** [comment]
I will set the idletimeout to 0 - no timeout.
I actually didn't notice that there is a 3 minute timeout - sitting now thinking how in earth.... :-)

You can always remove the session or the container, I do not see any case where I want my script to be stopped by a timeout.

**Comment by kine** [comment]
Now I am experiencing the issue https://github.com/microsoft/navcontainerhelper/issues/1807 . Interesting is, that it worked like that before, now giving the error. Or maybe I didn't hit the point where the session must be generated? Do not know...

Definitely no parameterset with ContainerID and SessionOption on the new-pssession.

**Comment by freddydk** [comment]
Having reverted the SessionOption, I guess you are back at this problem.
There are three different ways that Invoke-ScriptInBcContainer can end up running your script in the container.
1. PSSession to Process Isolation container
2. PSSession to HyperV Isolation container
3. Docker Exec

If you are running as non-admin or if New-PsSession fails, I will revert to 3.

I have created 3 containers and I am not running an idle script in each of those for 1 hour.
None of those seems to fail with the above error.

Doing this, I have a sense of Deja-Vu - I think I have made these tests before and there doesn't seem to be a timeout on container sessions, so my guess is that something else made the session fail.

**Comment by kine** [comment]
Yup, I think it was combination of things leading to the event when I was using HyperV isolation and 6GB RAM which was too low to do the update of the apps, leading to failing container session. 

Sorry for "false positive" result with the timeout. The HyperV was the reason (and thus limit of RAM).

**Comment by freddydk** [comment]
No problem
