### ISSUE TITLE
Publish-NavContainerApp is not using Publish-NAVApp -Force which leads to user interaction in some situations

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#1810]
In my script, I am installing some app, which have dependency on app which is published but not installed. In this case, the Publish-NAVContainerApp will lead to this prompt:
![image](https://user-images.githubusercontent.com/110221/111758501-e39e2500-889c-11eb-8b6c-d56a24685fa7.png)

There is no way how to force the -force switch.

I can prepare PR but need to know if you want to solve it with new parameter of the Publish-NAVContainerApp or using -force by default.

**Comment by freddydk** [comment]
I would just add the -force on Publish-NavApp

**Comment by epernst** [comment]
I think this change will actually allow me to skip most of my current encapsulation of Publish-BcContainerHelper.

**Comment by freddydk** [comment]
Shipped in 2.0.9
