### ISSUE TITLE
Idea: Allow array of paths for -addFontsFromPath

### ISSUE THREAD

**Issue by dannoe** [microsoft/navcontainerhelper#1812]
**Describe the idea**
I have two barcode fonts in my repo that I want to add to the container on New-BcContainer, but I also have to add the default fonts of windows (else my reports are barcode only). I could only add my windows fonts, but it could happen, that a developer does not have the barcode fonts installed on their host.

**Example usage**
```
New-BcContainer `
    ...
    -addFontsFromPath @("C:\windows\fonts\", ".\myfonts\") `
    ...
```

PS: I know I could just call "Add-FontsToBcContainer" after my New-BcContainer call.

Would you accept a PR for this?

**Comment by freddydk** [comment]
The fix should include Add-FontsToBcContainer, then I am open for that.

**Comment by freddydk** [comment]
Thanks

**Comment by freddydk** [comment]
I learned something new today...
I learned that Get-ChildItem takes an array of paths.
Thanks
