### ISSUE TITLE
The named pipe target process has ended | Compile-AppInNavContainer

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#1818]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
A clear and concise description of what the issue is.

**Scripts used to create container and cause the issue**
```
New-BcContainer `
    -accept_eula `
    -imagename...
```

**Full output of scripts**
```
NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by freddydk** [comment]
I assume this was wrongly created as it contains no info at all.

**Comment by hvandenborn** [comment]
something went wrong with chrome
