### ISSUE TITLE
Test Symbols will be not downloaded in Compile-AppInNavContainer

### ISSUE THREAD

**Issue by ChrisBlankDe** [Microsoft/navcontainerhelper#182]
If a version for test is defined in app.json the specific symbols version must be downloaded.
The Download Link could be build like the system and Applikation package:
https://server:7049/nav/dev/packages?publisher=Microsoft&appName=Test&versionText=11.0.0.0

https://github.com/Microsoft/navcontainerhelper/blob/e876571f1369afd66b5728e9bea38d9c884e457d/AppHandling/Compile-AppInNavContainer.ps1#L72

**Comment by freddydk** [comment]
I have accepted the PR - will be included in the next update (within a week).
