### ISSUE TITLE
Restore-DatabasesInBcContainer | SQL timeout

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#1820]
Freddy,

i use the new-BCContainer with a backup. most backups are not so big, and all is well.
but there are sometimes the backup is big, and the agent server is not so fast or its also bussy with other builds that de restore is slower, then i hit the 5 min timeout of the function below: Restore-DatabasesInBcContainer

![image](https://user-images.githubusercontent.com/48794854/111989415-01c08b00-8b12-11eb-9ec7-7e4249afe5d5.png)

is there a change you can change its default into 600 ? (10 min) or make a parameter on the new-BCContainer ?

function Restore-DatabasesInBcContainer {
    Param(
        [string] $containerName = $bcContainerHelperConfig.defaultContainerName, 
        [string] $bakFolder = "",
        [string] $bakFile = "",
        [string] $databaseName = "",
        [string[]] $tenant,
        [Parameter(Mandatory=$false)]
        [string] $databaseFolder = "c:\databases",
        [int] $sqlTimeout = 300

**Comment by freddydk** [comment]
I will add a sqlTimeout on New-BcContainer.

**Comment by hvandenborn** [comment]
Great!, many thanks

**Comment by freddydk** [comment]
Shipped in 2.0.9
