### ISSUE TITLE
Manifest not found

### ISSUE THREAD

**Issue by radovandokic** [microsoft/navcontainerhelper#1821]
Hello,

I am trying to instal NAV container, version 2016, and I receive a message:
Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.14393.3384-generic not found: manifest unknown: manifest tagged by "10.0.14393.3384-generic" is not found

**Scripts used to create container and cause the issue**

$artifactUrl = Get-NAVArtifactUrl -nav 2016 -cu 3 -country "na" #-select Latest
$imageName = 'local'
$originalContainerName = 'UPG2016'
$auth = "NavUserPassword"
$username = 'rdokic'
$password = 'rdokic'
$credential = New-Object pscredential $username, (ConvertTo-SecureString -String $password -AsPlainText -Force)
$licenseFile = "C:\myfolder\newlicence.flf"
New-NavContainer -accept_eula `
                 -imageName $imageName `
                 -artifactUrl $artifactUrl `
                 -containerName $originalContainerName `
                 -licenseFile $licenseFile `
                 -auth $auth `
                 -memoryLimit 14G `
                 -Credential $Credential `
                 -includeCSide `
                 -multitenant `
                 -enableSymbolLoading `
                 -updateHosts `
                 -accept_outdated `
                 -bakFile "C:\Users\rdokic\backup\test.bak"

**Full output of scripts**
PS C:\> $artifactUrl = Get-NAVArtifactUrl -nav 2016 -cu 3 -country "na" #-select Latest
$imageName = 'local'
$originalContainerName = 'UPG2016'
$auth = "NavUserPassword"
$username = 'rdokic'
$password = 'rdokic'
$credential = New-Object pscredential $username, (ConvertTo-SecureString -String $password -AsPlainText -Force)
$licenseFile = "C:\myfolder\newlicence.flf"
New-NavContainer -accept_eula `
                 -imageName $imageName `
                 -artifactUrl $artifactUrl `
                 -containerName $originalContainerName `
                 -licenseFile $licenseFile `
                 -auth $auth `
                 -memoryLimit 14G `
                 -Credential $Credential `
                 -includeCSide `
                 -multitenant `
                 -enableSymbolLoading `
                 -updateHosts `
                 -accept_outdated `
                 -bakFile "C:\Users\rdokic\backup\test.bak"
NavContainerHelper is version 0.7.0.26
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Standard - ltsc2016
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
ArtifactUrl and ImageName specified
Fetching all docker images
Image local:onprem-9.0.44365.0-na-nodb doesn't exist
Building image local:onprem-9.0.44365.0-na-nodb based on https://bcartifacts.azureedge.net/onprem/9.0.44365.0/na
Pulling latest image mcr.microsoft.com/dynamicsnav:10.0.14393.3384-generic
DockerDo : Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.14393.3384-generic not found: manifest unknown: manifest tagged by "10.0.14393.3384-generic" is not found
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.14393.3384-generic
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.7.0.26\ContainerHandling\New-NavImage.ps1:87 char:9
+         DockerDo -command pull -imageName $baseImage | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
 

Any help is more than welcome.

**Comment by freddydk** [comment]
https://freddysblog.com/2021/03/01/navcontainerhelper-doesnt-work-anymore/
