### ISSUE TITLE
Container created from NAV2016 image via BCContainerHelper will not recognize DotNet 3.5 library

### ISSUE THREAD

**Issue by rsaritzky** [microsoft/navcontainerhelper#1824]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
NAV enviornment is NAV2016.  Trying to compile objects provided by ISV.  ISV includes a Add-in DLL that uses DotNet3.5.  Even after enabling DotNet3.5, the objects will not compile.  The "Types" listing in the Development Environment don't display the Types and a compile error "Could not load type 'EasyPost.Address.'EasyPost.Net35, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null''." is displayed.

We use Advania-Git scripts to create our environments

After creating the container with the script below, I attempted to enable DotNet3.5 support via the following commands:

##Enable Windows Update Service
Set-Service -Name wuauserv -StartupType "Manual"
##EnableDotNet
DISM.EXE /Online /Add-Capability /CapabilityName:NetFx3~~~~

See screenshots below

**Scripts used to create container and cause the issue**
```
if (![String]::IsNullOrEmpty($SetupParameters.dockerImage) -or ![String]::IsNullOrEmpty($SetupParameters.artifact)) {
    if ($BranchSettings.instanceName -eq "") {
        Write-Host "Starting Docker Image Development Container for Branch ..."
        $params = @{
            SetupParameters = $SetupParameters 
            BranchSettings = $BranchSettings
        }
        if ($SetupParameters.dockerAdminPasswordId) {
            Import-Module RemoteManagement -DisableNameChecking | Out-Null
            $DockerAdmin = Get-NAVPasswordStateUser -PasswordId $SetupParameters.dockerAdminPasswordId
            Write-Host "Using stored authentication for Docker Container..."
            $params += @{
                AdminUsername = $DockerAdmin.UserName 
                AdminPassword = $DockerAdmin.Password
            }
        }
        if ($SetupParameters.dockerMemoryLimit) {
            Write-Host "Using configured memory limit for Docker Container..."
            $params += @{                
                MemoryLimit = $SetupParameters.DockerMemoryLimit
            }
        }
        if ($SetupParameters.dockerRestoreBackup) {
            $BackupFilePath = Get-NAVBackupFilePath -SetupParameters $SetupParameters
            if (Test-Path -Path $BackupFilePath) {
                Write-Host "Using backup file for Docker Container..."
                $params += @{
                    BackupFilePath = $BackupFilePath
                }
            }
        }
        if (![string]::IsNullOrEmpty($SetupParameters.LicenseFilePath)) {
            if (Test-Path $SetupParameters.LicenseFilePath) {  
                    $params += @{
                        LicenseFilePath = $SetupParameters.LicenseFilePath
                    }
            }            
        }
        Start-DockerContainer @params
        $BranchSettings = Get-BranchSettings -SetupParameters $SetupParameters
        & (Join-path $PSScriptRoot Verify-RepositorySetupInContainer.ps1)
    } 
}

if ($BranchSettings.dockerContainerName -gt "") {
    ReStart-DockerContainer -BranchSettings $BranchSettings
} else {
    Load-InstanceAdminTools -SetupParameters $SetupParameters
    if ($BranchSettings.instanceName -eq "") {
        Write-Host "Requesting new NAV Environment for branch" $Setupparameters.projectName
        $BackupFilePath = Get-NAVBackupFilePath -SetupParameters $SetupParameters
        $ServerInstance = "NAV" + $($Setupparameters.navRelease) + "DEV" + (Get-EnvironmentNo)
        $params = @{ 
            BackupFilePath = $BackupFilePath
            DatabaseServer = $SetupParameters.defaultDatabaseServer
            DatabaseName = $ServerInstance
            DatabasePath = $SetupParameters.DatabasePath }
        if ($SetupParameters.defaultDatabaseInstance -ne "") { $params.DatabaseInstance = $SetupParameters.defaultDatabaseInstance }
        Write-Host "Restoring database..."
        Restore-NAVBackup @params
        Remove-Item -Path $BackupFilePath -Force -ErrorAction SilentlyContinue
        $BranchSettings.databaseInstance = $SetupParameters.defaultDatabaseInstance
        $BranchSettings.databaseServer = $SetupParameters.defaultDatabaseServer
        $BranchSettings.databaseName = $ServerInstance
        $BranchSettings.instanceName = "" 
        Write-Host "Upgrading database..."
        Invoke-NAVDatabaseConversion -SetupParameters $SetupParameters -BranchSettings $BranchSettings
        Write-Host "Simplifying Database..."
        Set-NAVDatabaseToSimpleRecovery -DatabaseServer $SetupParameters.defaultDatabaseServer -DatabaseInstance $SetupParameters.defaultDatabaseInstance -DatabaseName $ServerInstance
        Write-Host "Compiling Service Objects..."
        Compile-NAVApplicationGITObject -SetupParameters $SetupParameters -BranchSettings $BranchSettings -Filter "Type=Table;Id=2000000004..2000000999" -SynchronizeSchemaChanges No 
        Write-Host "Creating Service..."
        $DefaultInstanceSettings = Get-DefaultInstanceSettings -SetupParameters $SetupParameters -BranchSettings $BranchSettings
        $BranchSettings.clientServicesPort = $DefaultInstanceSettings.DocumentElement.appSettings.SelectSingleNode("add[@key='ClientServicesPort']").Attributes["value"].Value
        $BranchSettings.managementServicesPort = $DefaultInstanceSettings.DocumentElement.appSettings.SelectSingleNode("add[@key='ManagementServicesPort']").Attributes["value"].Value
        $params = @{       
          ServerInstance = $ServerInstance 
          DatabaseName = $BranchSettings.databaseName
          DatabaseServer = $BranchSettings.databaseServer
          ManagementServicesPort = $DefaultInstanceSettings.DocumentElement.appSettings.SelectSingleNode("add[@key='ManagementServicesPort']").Attributes["value"].Value
          ClientServicesPort = $DefaultInstanceSettings.DocumentElement.appSettings.SelectSingleNode("add[@key='ClientServicesPort']").Attributes["value"].Value
          SOAPServicesPort = $DefaultInstanceSettings.DocumentElement.appSettings.SelectSingleNode("add[@key='SOAPServicesPort']").Attributes["value"].Value
          ODataServicesPort = $DefaultInstanceSettings.DocumentElement.appSettings.SelectSingleNode("add[@key='ODataServicesPort']").Attributes["value"].Value          
        }
        if ($BranchSettings.databaseInstance -ne "") { $params.DatabaseInstance = $BranchSettings.databaseInstance }
        New-NAVServerInstance @params -Force -ServiceAccount NetworkService -ErrorAction Stop
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName ServicesDefaultTimeZone -KeyValue 'UTC' 
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName ServicesLanguage -KeyValue 'en-US' 
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName ODataServicesSSLEnabled -KeyValue $false 
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName ODataServicesEnabled -KeyValue $true 
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName SOAPServicesSSLEnabled -KeyValue $false 
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName SOAPServicesEnabled -KeyValue $true 
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName DataCacheSize -KeyValue 7 
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName CompileBusinessApplicationAtStartup -KeyValue $false
        Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName PublicWebBaseUrl -KeyValue "http://$($env:COMPUTERNAME):$(Get-WebClientPort -MainVersion $SetupParameters.mainVersion)/${ServerInstance}/WebClient"
        if ($SetupParameters.developerService -eq $true) {
            Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName DeveloperServicesEnabled -KeyValue $true 
            Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName DefaultClient -KeyValue 'Web'
            Set-NAVServerConfiguration -ServerInstance $ServerInstance -KeyName EnableSymbolLoadingAtServerStartup -KeyValue $true
            $BranchSettings.developerServicesPort = $DefaultInstanceSettings.DocumentElement.appSettings.SelectSingleNode("add[@key='DeveloperServicesPort']").Attributes["value"].Value
        } else {
            $BranchSettings.developerServicesPort = ""
        }
        $BranchSettings.instanceName = $ServerInstance
        Enable-DelayedStartForNAVService -BranchSettings $BranchSettings
        Enable-TcpPortSharingForNAVService -BranchSettings $BranchSettings
        Write-Host "Starting Service..."
        Set-NAVServerInstance -ServerInstance $ServerInstance -Start -Force 
        Write-Host "Syncronizing Database..."
        Get-NAVServerInstance -ServerInstance $ServerInstance | Where-Object -Property State -EQ Running | Sync-NAVTenant -Mode ForceSync -Force
        Write-Host "Creating Web Server Instance..."
        New-NAVWebServerInstance -ClientServicesPort $BranchSettings.clientServicesPort -Server $env:COMPUTERNAME -ServerInstance $ServerInstance -WebServerInstance $ServerInstance
        Enable-NAVWebClientDesigner -BranchSettings $BranchSettings
        Enable-NAVWebClientPersonalization -BranchSettings $BranchSettings
        Update-BranchSettings -BranchSettings $BranchSettings
        Write-Host "Environment build completed..."
    } else {
        Write-Host "Environment already created..."
    }

    if (![string]::IsNullOrEmpty($SetupParameters.LicenseFilePath)) {
        if (Test-Path $SetupParameters.LicenseFilePath) {  
            Update-NAVLicense -BranchSettings $BranchSettings -LicenseFilePath $SetupParameters.LicenseFilePath 
        }
    }
    UnLoad-InstanceAdminTools

}

if (![string]::IsNullOrEmpty($Setupparameters.uidOffset)) {
    Write-Host "Set uidoffset in database $($BranchSettings.databaseName) to $($Setupparameters.uidOffset)"
    $command = 'UPDATE [dbo].[$ndo$dbproperty] SET [uidoffset] = ' + $Setupparameters.uidOffset
    $Result = Get-SQLCommandResult -Server (Get-DatabaseServer -BranchSettings $BranchSettings) -Database $BranchSettings.databaseName -Command $command -Username $SetupParameters.SqlUsername -Password $SetupParameters.SqlPassword   
}

**Full output of scripts**
```
PS C:\AdvaniaGIT\Workspace\NAV2016_CCB> Start-AdvaniaGITAction -Repository "c:\AdvaniaGIT\Workspace\NAV2016_CCB" -ScriptName "Build-NavEnvironmentFromGIT.ps1" -Wait $false
Using License: Cryobank.flf on C:\AdvaniaGIT\License\Cryobank.flf
Starting Docker Image Development Container for Branch ...
Using backup file for Docker Container...
Connecting to repository navdocker.azurecr.io...
Preparing Docker Container for Dynamics NAV...
BcContainerHelper is version 2.0.4
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1809
Docker Client Version is 20.10.2
Docker Server Version is 20.10.2
Fetching all docker images
ArtifactUrl and ImageName specified
Image custombuild:onprem-9.0.50357.0-na already exists
Using image custombuild:onprem-9.0.50357.0-na
Disabling Health Check (always report healthy)
Creating Container Cryobank
Version: 9.0.50357.0-na
Style: onprem
Multitenant: No
Platform: 9.0.50357.0
Generic Tag: 1.0.1.4
Container OS Version: 10.0.17763.1697 (ltsc2019)
Host OS Version: 10.0.17763.1697 (1809)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\AdvaniaGIT\License\Cryobank.flf
Additional Parameters:
--volume "c:\AdvaniaGIT\Workspace\NAV2016_CCB:C:\GIT"
--volume "C:\AdvaniaGIT:C:\Host"
--env SqlTimeout=1200
--dns 8.8.8.8
--restart always
--volume "c:\AdvaniaGIT\Workspace\NAV2016_CCB\Add-Ins:c:\run\Add-Ins"
--env bakfile="C:\Host\Log\d7555a61-f87d-4eaa-adf4-47ece16b57ce\NAVBackup.bak"
--env customNavSettings=EnableTaskScheduler=False
Files in C:\ProgramData\BcContainerHelper\Extensions\Cryobank\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container Cryobank from image custombuild:onprem-9.0.50357.0-na
c5bc76cdd429c4bac151faf01de0371a91a7a2c8408bd90a48c396eacea79e3e
Waiting for container Cryobank to be ready
Initializing...
Setting host.docker.internal to 192.168.0.8 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.8 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.25.128.1 in container hosts file
Starting Container
Hostname is Cryobank
PublicDnsName is Cryobank
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'C:\Host\Log\d7555a61-f87d-4eaa-adf4-47ece16b57ce\NAVBackup.bak'
Using database server localhost\SQLEXPRESS
Setting CompatibilityLevel for mydatabase on localhost\SQLEXPRESS
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Creating EnableTaskScheduler and setting it to False
Starting Service Tier
Creating Web Site
Creating Web Server Instance
Creating ManagementServicesPort and setting it to 7045
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user rons
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.25.141.228
Container Hostname  : Cryobank
Container Dns Name  : Cryobank
Web Client          : http://Cryobank/NAV/WebClient/
Setting Cryobank to 172.25.141.228 in host hosts file

Files:

WARNING: You are running a container which is 68 days old.
Microsoft recommends that you always run the latest version of our containers.

Container Total Physical Memory is 15.6Gb
Container Free Physical Memory is 5.6Gb

Initialization took 56 seconds
Ready for connections!
Reading CustomSettings.config from Cryobank
Container Cryobank successfully created

Use:
Get-BcContainerEventLog -containerName Cryobank to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName Cryobank to get debug information about the container
Enter-BcContainer -containerName Cryobank to open a PowerShell prompt inside the container
Remove-BcContainer -containerName Cryobank to remove the container again
docker logs Cryobank to retrieve information about URL's again
Extending PSModulePath with C:\AdvaniaGIT\Scripts
Extending Computer wide PSModulePath with C:\AdvaniaGIT\Scripts
Importing the modules
Extending Path with C:\AdvaniaGIT\Tools
Extending Computer wide Path with C:\AdvaniaGIT\Tools
Updating BranchSettings.json...
Updating GITSettings.json...
Set uidoffset in database mydatabase to 50200
Docker Image on Cryobank is responding correctly...
...
```

**Screenshots**
If applicable, add screenshots to help explain your problem.
In Development Environment, codeunit objects which have the addon specified will not compile with the error message specified above.  The addon's Types are not displayed when "looked up" inside the variable definition
![image](https://user-images.githubusercontent.com/50466531/112026912-eb0b3b80-8af3-11eb-959b-8da0465dc8c7.png)

We also have a local NAV2016 environment.  When the same objects are inspected, the Addon's Types are properly displayed and the object compiles correctly:
![image](https://user-images.githubusercontent.com/50466531/112027176-2c035000-8af4-11eb-8095-457455e543bb.png)

**Additional context**
- does it happen all the time? Yes - any container built will display this error (tried on multiple machines)

- did it use to work? No - We are trying to install this ISV's addon for the first time.  ISV does not use Docker for NAV2016 development.

**Comment by rsaritzky** [comment]
Not sure if the screenshots appeared in the submission above, so I am resubmitting here.
In NAV2016 Development Environment inside container, codeunit objects which have the addon specified will not compile with the error message specified above.  The addon's Types are not displayed when "looked up" inside the variable definition

![Docker Dev Environment](https://user-images.githubusercontent.com/50466531/112027769-c06db280-8af4-11eb-8162-c18f6314c3da.jpg)

We also have a local NAV2016 environment.  When the same objects are inspected, the Addon's Types are properly displayed and the object compiles correctly:
![Local Dev Environment](https://user-images.githubusercontent.com/50466531/112028038-0165c700-8af5-11eb-8b41-5123327c9e0f.jpg)

**Comment by freddydk** [comment]
If you clone the nav-docker repository and open this file in PowerShell ISE:
https://github.com/microsoft/nav-docker/blob/master/generic/build.ps1
Then you can build your own generic image.
In the DOCKERFILE, you can add the dotnet35 binaries and run the installer (like SQLEXPRESS and the other things are installed)

Then you can use this generic image when you start your container.

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by rsaritzky** [comment]
Hi Freddy,

Yes, we were able to make this work – I think that we were not adding the Dotnet Library to the server image within the container.  This script seems to have done the trick – our containername is “Cryobank”:

##Start Powershell within Docker
C:\WINDOWS\system32\CMD.EXE /C docker.exe exec -it Cryobank powershell -noexit c:\run\prompt.ps1
##Enable Windows Update Service
Set-Service -Name wuauserv -StartupType "Manual"
##EnableDotNet
DISM.EXE /Online /Add-Capability /CapabilityName:NetFx3~~~~
##Display enabled features
DISM.EXE /Online /Get-Capabilities


Thank you for the followup.

Ron

**Comment by freddydk** [comment]
Thanks
