### ISSUE TITLE
Issue importing module

### ISSUE THREAD

**Issue by nicko777** [microsoft/navcontainerhelper#1829]
When I try to import-module bccontainerhelper I get the following error 

% : The property 'Name' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\2.0.7\BcContainerHelper.psm1:75 char:21
+             $keys | % {
+                     ~~~
    + CategoryInfo          : InvalidOperation: (:) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.ForEachObjectCommand
 
Import-Module : The module to process 'BcContainerHelper.psm1', listed in field 'ModuleToProcess/RootModule' of module manifest 'C:\Program 
Files\WindowsPowerShell\Modules\bccontainerhelper\2.0.7\bccontainerhelper.psd1' was not processed because no valid module was found in any module directory.
At line:1 char:1
+ Import-Module bccontainerhelper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (bccontainerhelper:String) [Import-Module], PSInvalidOperationException
    + FullyQualifiedErrorId : Modules_ModuleFileNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by freddydk** [comment]
Seems like you have an error in the configuration file.
Remove or fix c:\programdata\bccontainerhelper\bccontainerhelper.config.json

**Comment by nicko777** [comment]
Thanks the config file was empty so deleting it has fixed it

**Comment by freddydk** [comment]
Shipped in 2.0.9
