### ISSUE TITLE
Dismount-NavTenant not working

### ISSUE THREAD

**Issue by lktraser** [microsoft/navcontainerhelper#1831]
**Describe the issue**
I want to dismount and remount a tenant to set 'AllowAppDatabaseWrite' to true. This works fine on my local container. But if I try the same thing on my containers with useTraefik I don't get the usual output on dismount and the tenant remains operational. Is there a better way to set this flag? Maybe even on container creation?

**Scripts used to create container and cause the issue**
```
 Dismount-NAVTenant -Tenant dafault -ServerInstance BC -Force -Verbose
```

**Full output of scripts**
```
AUSFÜHRLICH: Opening channel to ServerInstance 'MicrosoftDynamicsNavServer$BC'
AUSFÜHRLICH: Channel to ServerInstance 'MicrosoftDynamicsNavServer$BC' has been opened
AUSFÜHRLICH: Performing the operation "Dismount-NAVTenant" on target "ServerInstance = MicrosoftDynamicsNavServer$BC, Tenant = dafault".
AUSFÜHRLICH: Tenant 'dafault' was dismounted.
AUSFÜHRLICH: Closing channel to ServerInstance 'MicrosoftDynamicsNavServer$BC'
AUSFÜHRLICH: Channel to ServerInstance 'MicrosoftDynamicsNavServer$BC' has been closed
```

**Additional context**
- it only happens on my useTraefik containers but on all of them

**Comment by freddydk** [comment]
You should probably use: 
Dismount-NAVTenant -Tenant dafault -ServerInstance $serverInstance -Force -Verbose

In traefik, the serverInstance is different.

You can also create a new tenant using the New-BcContainerTenant - there you can set -allowAppDatabaseWrite
or you can add -additionalparameters @("--env defaultTenantHasAllowAppDatabaseWrite=Y") when creating the container

**Comment by lktraser** [comment]
I'll include that additional parameter for my future containers. 

$serverInstance gives me 'BC' in my traefik containers and I can also run 
```
Get-NAVTenant -ServerInstance BC


ServerInstance                         : MicrosoftDynamicsNavServer$BC
DatabaseName                           : default
DatabaseServer                         : localhost\SQLEXPRESS
DatabaseUserName                       :
State                                  : Operational
DetailedState                          :
DeletionState                          : Not deleted
IsInExclusiveAccessMode                : False
TenantDataVersion                      : 17.5.22499.23535
Compression                            : Page
Id                                     : default
AlternateId                            : {hub-default}
AllowAppDatabaseWrite                  : False
NasServicesEnabled                     : False
RunNasWithAdminRights                  : False
EncryptionProvider                     : LocalKeyFile
AzureKeyVaultSettings                  :
DefaultCompany                         :
DefaultTimeZone                        : UTC
ExchangeAuthenticationMetadataLocation :
AadTenantId                            :
ApplicationInsightsKey                 :
DisplayName                            :
EnvironmentName                        :
EnvironmentType                        : Sandbox
EnvironmentSettings                    :

```

**Comment by freddydk** [comment]
You are right that the serverinstance is BC even with traefik - I remembered that wrongly.
I assume that you have solved the problem with the parameter,
