### ISSUE TITLE
Problems with filesonly/BC18 insider containers

### ISSUE THREAD

**Issue by zorngiebel** [microsoft/navcontainerhelper#1834]
Hi, 

we experienced occasional errors when trying to create BC18 insider containers with the -filesonly parameter.
The script itself (without -filesonly) works perfectly fine. 
With -filesonly, it sometimes works and sometimes doesn´t, so we unfortunately have no real way of reliably reproducing the error.

Script:

$baseContainerName = "xyz"
$mylicense = xyz
$baseImageName = "mcr.microsoft.com/businesscentral/sandbox"
#$languages = @("","at","ch","de","gb","us")
#$languages = @("at","ch","de","gb","us")
$languages = @("de")
#$workitem = "PREV"

    New-BcContainer -accept_eula `
                     -alwaysPull `
                     -containerName $containerName `
                     -artifactUrl (Get-BCArtifactUrl xyz -select Latest) `
                     -auth NavUserPassword `
                     -licensefile $mylicense `
                     -updateHosts `
                     -assignPremiumPlan `
                     -includeTestToolkit `
                     -includeTestLibrariesOnly `
                     -WebClientPort $Ports[0] `
                     -ManagementServicesPort $Ports[1] `
                     -SoapServicesPort $Ports[2] `
                     -ODataServicesPort $Ports[3] `
                     -DeveloperServicesPort $Ports[4] `
                     -PublishPorts $Ports `
                     -clickonce `
                     -shortcuts CommonStartMenu `
                     -doNotExportObjectsToText `
                     -useBestContainerOS `
                     -filesonly `
                     -Credential $credential
}

Output
```
BcContainerHelper version 2.0.7
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.17763.1757-filesonly
10.0.17763.1757-filesonly: Pulling from businesscentral
4612f6d0b889: Already exists
db4edcf0861f: Pulling fs layer
7996bd9db3a5: Pulling fs layer
9eda03e01803: Pulling fs layer
c73bfe1702b0: Pulling fs layer
8977d932950f: Pulling fs layer
3f3d788ee1fa: Pulling fs layer
0537a67e5db8: Pulling fs layer
503e716e8139: Pulling fs layer
aa2ae198fa6d: Pulling fs layer
d4cfaf12a5e5: Pulling fs layer
a19464f8d1ee: Pulling fs layer
8977d932950f: Waiting
3f3d788ee1fa: Waiting
0537a67e5db8: Waiting
503e716e8139: Waiting
aa2ae198fa6d: Waiting
d4cfaf12a5e5: Waiting
a19464f8d1ee: Waiting
c73bfe1702b0: Waiting
7996bd9db3a5: Verifying Checksum
7996bd9db3a5: Download complete
c73bfe1702b0: Verifying Checksum
c73bfe1702b0: Download complete
8977d932950f: Verifying Checksum
8977d932950f: Download complete
3f3d788ee1fa: Verifying Checksum
3f3d788ee1fa: Download complete
0537a67e5db8: Verifying Checksum
0537a67e5db8: Download complete
503e716e8139: Verifying Checksum
503e716e8139: Download complete
aa2ae198fa6d: Verifying Checksum
aa2ae198fa6d: Download complete
d4cfaf12a5e5: Verifying Checksum
d4cfaf12a5e5: Download complete
a19464f8d1ee: Verifying Checksum
a19464f8d1ee: Download complete
db4edcf0861f: Verifying Checksum
db4edcf0861f: Download complete
9eda03e01803: Verifying Checksum
9eda03e01803: Download complete
db4edcf0861f: Pull complete
7996bd9db3a5: Pull complete
fail: ##[error]Error executing the PowerShell script
##[error]System.Management.Automation.ActionPreferenceStopException: Der ausgefÃ¼hrte Befehl wurde beendet, da die Einstellungsvariable "ErrorActionPreference" oder ein allgemeiner Parameter auf "Stop" festgelegt ist: failed to register layer: rename C:\ProgramData\docker\image\windowsfilter\layerdb\tmp\write-set-561046881 C:\ProgramData\docker\image\windowsfilter\layerdb\sha256\f2d8efd51e09029ab6960a3d43799e247244604a74a949b7f81557a6860db40a: Zugriff verweigert
       ExitCode: 1
...
```

Thank you and looking forward to hearing from you.

**Comment by freddydk** [comment]
Is this problem on one machine?

**Comment by freddydk** [comment]
A filesonly container creates a container with files only without installing Business Central, no database and no IIS.

Therefore almost all parameters doesn't make sense.
No license file needed. no ports, no test toolkit, no....

I don't know if that is the reason. This should be fine:

```
$containerName = "bcfilesonly"
$auth = "UserPassword"
$credential = New-Object pscredential -ArgumentList 'admin', $passwordSecret.SecretValue
$licenseFile = $licenseFileSecret.SecretValueText
$artifactUrl = Get-BCArtifactUrl -country us -storageAccount bcpublicpreview -type sandbox

New-BcContainer `
    -containerName $containerName `
    -accept_eula `
    -auth $auth `
    -Credential $credential `
    -artifactUrl $artifactUrl `
    -filesOnly
```

**Comment by freddydk** [comment]
Please re-open with more info if you need me to look into this.
