### ISSUE TITLE
18.0 Preview Container publishing an app error

### ISSUE THREAD

**Issue by NedimYami** [microsoft/navcontainerhelper#1838]
**Describe the issue**
Hello,
I installed an Bc 18.0 preview container.
I have tried to publish app from visual studio code by using launch json configration.
But I could't select Runtime 7.0 now.
How can I skip the runtime error?

![image](https://user-images.githubusercontent.com/42783080/112374079-ba452500-8cf2-11eb-87fd-26aa9f85a4ca.png)

**Comment by freddydk** [comment]
Install the .vsix that comes with the container.

**Comment by NedimYami** [comment]
Thank you so much
