### ISSUE TITLE
bccontainerhelper uses a function called Expand-7zipArchive that breaks commands

### ISSUE THREAD

**Issue by florinangelescu** [microsoft/navcontainerhelper#1842]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When using Download-Artifacts on a local machine just to download the artifacts, the cmdlet will fail when using Expand-7zipArchive.
The function Expand-7zipArchive doesn't seem to be part of bccontainerhelper module and the module also doesn't mention any dependent modules in it's manifest.

**Scripts used to create container and cause the issue**
```
Download-Artifacts -artifactUrl $ArtifactUrl
```

**Full output of scripts**
```
Download-Artifacts -artifactUrl $ArtifactUrl -basePath $DestinationPath
Downloading application artifact /onprem/17.5.22499.22546/nl
Downloading C:\Users\XXX\AppData\Local\Temp\5b23446c-a8db-43e3-9187-a8ced44b9515.zip
Unpacking application artifact to tmp folder Expand-7zipArchive : The property 'use7zipIfAvailable
' cannot be found on this object. Verify 
that the property exists.
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.4\Misc\Download-Artifacts.ps1:84 char:21
+ ...             Expand-7zipArchive -Path $appZip -DestinationPath $tmpFol ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Expand-7zipArchive], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Expand-7zipArchive
...
```

**Screenshots**

**Additional context**
It happens all the time.
I don't know if it worked before, this is the first time I am trying it.

**Comment by freddydk** [comment]
Try to run
Import-Module BcContainerHelper

before using Download-Artifacts

**Comment by florinangelescu** [comment]
Already doing that, no luck. The module is loaded. As you can see, the download of the artifact doesn't give issues, only the extraction part.

**Comment by florinangelescu** [comment]
If I list the cmdlets available in the module, I don't see any Expand-7ZipArchive.

**Comment by freddydk** [comment]
That is an internal function using a variable, which is initialized in the module initialization code.

**Comment by freddydk** [comment]
Are you explicitely running Import-Module (I know it is loaded - but what did that line print out)?

**Comment by florinangelescu** [comment]
I forced the load and worked this time.
Thanks for the help.

**Comment by freddydk** [comment]
I will change the use of the variable in the expand-7zip function to call the function, which initializes the variable.
This way, this shouldn't happen again
