### ISSUE TITLE
create container with already existing Multi tenant backup.

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#1844]
Freddy,

Can you point the way here for me?
i have a multi tenant database that i want to be restored in the container. 
i studied the new-bccontainer script, 
it has the multitenant flag..

and i checked that later on in the code there is a search on app.bak  (as application backup) (in combination with -bakfolder) and all the other backups are the tenants backups. (which probebly defines the tenant name as well?)

So i copy the folder T1702-Template which contains **app.bak** and **T1702.bak** to the workspace of the agent (devops agent)
and i pass this folder to the new-bccontainer (in my case) F:\DevOps\MSBUILD15-1\_work\1\T1702-Template

but it will fail like below. 

Is this way even possible? is multitenant with bakfolder intendend for this purpose? 
how could i make this work? 
i could not find allot of docu around this.

------------
(the issue below is because the ArtifactURL is made empty after creating the image:
![image](https://user-images.githubusercontent.com/48794854/112627248-a3f1b300-8e31-11eb-9b28-8f18542d9c0e.png)
and then lateron 
![image](https://user-images.githubusercontent.com/48794854/112627292-b370fc00-8e31-11eb-99be-d3390e0fad07.png)
will not be true so it moves to the else...
--------------
but i guess ist more of a wrong using of the parameters i guess? 

-- container generation --- 
BcContainerHelper version 2.0.7
Actual imagename is  bcimage-Multitenant:onprem-17.4.21491.21531-nl
MemoryLimit set to 10G
SQL MemoryLimit set to 30%
use traefik
Public DNS is MSBUILD15.MyDomain.nl
License found at F:\DevOps\MSBUILD15-1\_work\1\s\Licenses\18.flf
Multi-tenant -> use backupfolder
backupfolder from : \\MyDomain\share\MSFBUILDS\ContainerizedTestenBackups\T1702-Template
VERBOSE: Performing the operation "Copy Directory" on target "Item: 
\\MyDomain\share\MSFBUILDS\ContainerizedTestenBackups\T1702-Template Destination: 
F:\DevOps\MSBUILD15-1\_work\1\T1702-Template".
VERBOSE: Performing the operation "Create Directory" on target "Destination: 
F:\DevOps\MSBUILD15-1\_work\1\T1702-Template".
backupfolder agent F:\DevOps\MSBUILD15-1\_work\1\T1702-Template
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.14
Docker Server Version is 19.03.14
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Image bcimage-multitenant:onprem-17.4.21491.21531-nl already exists
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image bcimage-multitenant:onprem-17.4.21491.21531-nl
PublicDnsName is MSBUILD15.MyDomain.nl
Get-Item : Cannot find path 'F:\DevOps\MSBUILD15-1\_work\1\s\True\ServiceTier\program files\Microsoft Dynamics NAV' bec
ause it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\New-NavContainer.ps1:886 char:2
8
+ ... vversion = (Get-Item -Path "$dvdPath\ServiceTier\program files\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (F:\DevOps\MSBUI...ft Dynamics NAV:String) [Get-Item], ItemNotFoundExcep 
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

**Comment by freddydk** [comment]
New-BcContainer has a parameter called -bakFolder
First time you run a container like this:
```
New-BcContainer `
    -containerName $containerName `
    -accept_eula `
    -auth $auth `
    -Credential $credential `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -bakFolder "c:\programdata\bccontainerhelper\mybakfolder"
```
It will populate the folder with .bak files for the databases in the container.
Next time you run the exact same command it will reuse the database backups in this folder (and be faster)
Description:
```
 .Parameter bakFolder
  A folder in which a backup of the database(s) will be placed after the container has been created and initialized
  If the folder already exists, then the database(s) in this folder will be restored and used.
```
I don't think this can be used for New-BcImage though, that is probably not supported, but if you place your databases in this folder and maybe set databaseName to the name of the app database, then you should get a container with your databases.

**Comment by hvandenborn** [comment]
thnx ill try this out next week

**Comment by freddydk** [comment]
Did you make this work?

**Comment by hvandenborn** [comment]
Freddy, the priority on the job had changed last weeks, Next week i will be on it for the whole week again, i will let you know ok?

**Comment by hvandenborn** [comment]
Freddy, it wont start, i get the same message as posted in the first post. 

![image](https://user-images.githubusercontent.com/48794854/116996400-a0c4cf00-acdb-11eb-8c77-3379ac3fbbf6.png)


![image](https://user-images.githubusercontent.com/48794854/116996308-83900080-acdb-11eb-9cee-2a8ac3e54035.png)

somehow it takes a turn in the New-BcContainer where it walks against this error.

    New-BcContainer `
        -accept_eula `
        -accept_outdated `
        -containerName $ContainerName `
        -artifactUrl $ArtifactURL `
        -auth $Auth  `
        -credential $credential  `
        -licensefile $LicensePath `
        -imageName $imageName `
        -updateHosts `
        -doNotExportObjectsToText `
        -TimeZoneId "W. Europe Standard Time" `
        -memoryLimit $MemoryLimit `
        -sqlMemoryLimit $MemoryLimitSQL `
        -useTraefik
        -PublicDnsName $PublicDNS `
        -bakFolder $backupFolder `
        -multitenant
        -sqlTimeout 600

**Comment by freddydk** [comment]
Instead of posting screenshots, I would appreciate if you post the text marked with the "insert Code" attribute in the toolbar.

**Comment by hvandenborn** [comment]
Yes Sir,

`"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'F:\DevOps\MSBUILD15-1\_work\_temp\dc57f9c1-1716-4f9a-9225-6d0fd6fe71a6.ps1'"
BcContainerHelper version 2.0.11
Actual imagename is  bcimage-Multitenant:onprem-18.0.23013.23795-nl
MemoryLimit set to 12G
SQL MemoryLimit set to 30%
use traefik
Public DNS is MSBUILD15.mysolution.nl
License found at F:\DevOps\MSBUILD15-1\_work\1\s\Licenses\18.flf
Multi-tenant -> use backupfolder
backupfolder from : \\msfile01\share\MSFBUILDS\ContainerizedTestenBackups\T1702-Template
backupfolder agent C:\ProgramData\BCContainerHelper\T1702-Template
BcContainerHelper is version 2.0.11
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.14
Docker Server Version is 19.03.14
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Image bcimage-multitenant:onprem-18.0.23013.23795-nlwith_db already exists
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image bcimage-multitenant:onprem-18.0.23013.23795-nlwith_db
PublicDnsName is MSBUILD15.mysolution.nl
Get-Item : Cannot find path 'F:\DevOps\MSBUILD15-1\_work\1\s\True\ServiceTier\program files\Microsoft Dynamics NAV' bec
ause it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\New-NavContainer.ps1:903 char:
28
+ ... vversion = (Get-Item -Path "$dvdPath\ServiceTier\program files\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (F:\DevOps\MSBUI...ft Dynamics NAV:String) [Get-Item], ItemNotFoundExcep 
   tion
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
 
##[error]PowerShell exited with code '1'.
Finishing: Create Build Container
`

**Comment by freddydk** [comment]
And if you remove the imageName parameter to avoid the image creation alltogether?

**Comment by hvandenborn** [comment]
Every run takes a long time on container creation.

"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'F:\DevOps\MSBUILD15-1\_work\_temp\d269a066-30b0-4063-bf3e-04c509a3648c.ps1'"
BcContainerHelper version 2.0.11
Actual imagename is  bcimage-Multitenant:onprem-18.0.23013.23795-nl
MemoryLimit set to 12G
SQL MemoryLimit set to 30%
use traefik
Public DNS is MSBUILD15.MyDomain.nl
License found at F:\DevOps\MSBUILD15-1\_work\1\s\Licenses\18.flf
Multi-tenant -> use backupfolder
backupfolder from : \\msfile01\share\MSFBUILDS\ContainerizedTestenBackups\T1702-Template
VERBOSE: Performing the operation "Copy Directory" on target "Item: 
\\msfile01\share\MSFBUILDS\ContainerizedTestenBackups\T1702-Template Destination: 
C:\ProgramData\BCContainerHelper\T1702-Template".
VERBOSE: Performing the operation "Create Directory" on target "Destination: 
C:\ProgramData\BCContainerHelper\T1702-Template".
VERBOSE: Performing the operation "Copy File" on target "Item: 
\\msfile01\share\MSFBUILDS\ContainerizedTestenBackups\T1702-Template\app.bak Destination: 
C:\ProgramData\BCContainerHelper\T1702-Template\app.bak".
VERBOSE: Performing the operation "Copy File" on target "Item: 
\\msfile01\share\MSFBUILDS\ContainerizedTestenBackups\T1702-Template\T1702.bak Destination: 
C:\ProgramData\BCContainerHelper\T1702-Template\T1702.bak".
backupfolder agent C:\ProgramData\BCContainerHelper\T1702-Template
BcContainerHelper is version 2.0.11
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.14
Docker Server Version is 19.03.14
Fetching all docker images
Fetching all docker volumes
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image mcr.microsoft.com/businesscentral:10.0.17763.1817
PublicDnsName is MSBUILD15.MyDomain.nl
Creating Container MSBUILD151
Version: 18.0.23013.23795-nl
Style: onprem
Multitenant: Yes
Platform: 18.0.22893.23773
Generic Tag: 1.0.1.6
Container OS Version: 10.0.17763.1817 (ltsc2019)
Host OS Version: 10.0.17763.1817 (ltsc2019)
Using process isolation
Using locale nl-NL
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Additional Parameters:
-e webserverinstance=MSBUILD151
-e publicdnsname=MSBUILD15.MyDomain.nl
-l "traefik.protocol=https"

-l "traefik.soap.frontend.rule=PathPrefix:/MSBUILD151soap;ReplacePathRegex: ^/MSBUILD151soap(.*) /BC$1"
-l "traefik.soap.port=7047"
-l "traefik.rest.frontend.rule=PathPrefix:/MSBUILD151rest;ReplacePathRegex: ^/MSBUILD151rest(.*) /BC$1"
-l "traefik.rest.port=7048"
-l "traefik.dev.frontend.rule=PathPrefix:/MSBUILD151dev;ReplacePathRegex: ^/MSBUILD151dev(.*) /BC$1"
-l "traefik.dev.port=7049"
-l "traefik.snap.frontend.rule=PathPrefix:/MSBUILD151snap;ReplacePathRegex: ^/MSBUILD151snap(.*) /BC$1"
-l "traefik.snap.port=7083"
-l "traefik.dl.frontend.rule=PathPrefixStrip:/MSBUILD151dl"
-l "traefik.dl.port=8080"
-l "traefik.dl.protocol=http"
-l "traefik.enable=true"
-l "traefik.frontend.entryPoints=https"
--env customNavSettings=PublicODataBaseUrl=https://MSBUILD15.MyDomain.nl/MSBUILD151rest/odata,PublicSOAPBaseUrl=https://MSBUILD15.MyDomain.nl/MSBUILD151soap/ws,PublicWebBaseUrl=https://MSBUILD15.MyDomain.nl/MSBUILD151
Files in C:\ProgramData\BcContainerHelper\Extensions\MSBUILD151\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container MSBUILD151 from image mcr.microsoft.com/businesscentral:10.0.17763.1817
811d2c749f869192f725ad49db00fea983e517517d95d68931d48bcdfac60ed9
Waiting for container MSBUILD151 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/18.0.23013.23795/nl
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\18.0.23013.23795\platform\ServiceTier\Program Files
c:\dl\onprem\18.0.23013.23795\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\18.0.23013.23795\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\18.0.23013.23795\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\18.0.23013.23795\nl\database\Demo Database NAV (18-0).bak
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\18.0.23013.23795\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.0.23013.23795\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\18.0.23013.23795\platform
c:\dl\onprem\18.0.23013.23795\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\18.0.23013.23795\nl\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\18.0.23013.23795\platform\Test Assemblies
Copying Applications
C:\dl\onprem\18.0.23013.23795\nl\Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 432 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.20.224.1 in container hosts file
Starting Container
Hostname is MSBUILD151
PublicDnsName is MSBUILD15.MyDomain.nl
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 98874D2E1A4A2D830F3A172C7D1754DEEF4E29D4
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting PublicODataBaseUrl to https://MSBUILD15.MyDomain.nl/MSBUILD151rest/odata
Setting PublicSOAPBaseUrl to https://MSBUILD15.MyDomain.nl/MSBUILD151soap/ws
Setting PublicWebBaseUrl to https://MSBUILD15.MyDomain.nl/MSBUILD151
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating Build as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.20.225.82
Container Hostname  : MSBUILD151
Container Dns Name  : MSBUILD15.MyDomain.nl
Web Client          : https://MSBUILD15.MyDomain.nl/MSBUILD151/
Dev. Server         : https://MSBUILD15.MyDomain.nl
Dev. ServerInstance : BC
Setting MSBUILD151 to 172.20.225.82 in host hosts file

Files:
http://MSBUILD15.MyDomain.nl:8080/ALLanguage.vsix
http://MSBUILD15.MyDomain.nl:8080/certificate.cer

Container Total Physical Memory is 8.0Gb
Container Free Physical Memory is 2.5Gb

Initialization took 144 seconds
Ready for connections!
Reading CustomSettings.config from MSBUILD151
Set SQL Server memory limit to 3686 MB
Set TimeZone in Container to W. Europe Standard Time
Creating Desktop Shortcuts for MSBUILD151
WARNING: The new settings value will not take effect until you stop and restart the service.
Removing Database CRONUS from localhost\SQLEXPRESS
Restoring C:\ProgramData\BcContainerHelper\T1702-Template\app.bak to CRONUS
Restoring C:\ProgramData\BcContainerHelper\T1702-Template\T1702.bak to T1702
The database restore operation failed due to the following error returned by SQL Server:
Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
at Restore, <No file>: line 25
at <ScriptBlock>, <No file>: line 54
at <ScriptBlock>, <No file>: line 53
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at Restore-DatabasesInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\Bacpac\Restore-DatabasesInNavContainer.ps1: line 70
at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\New-NavContainer.ps1: line 1828
at <ScriptBlock><Process>, F:\DevOps\MSBUILD15-1\_work\1\s\Build_tools\BuildScripts\Create-BC-Container.ps1: line 192
at <ScriptBlock>, F:\DevOps\MSBUILD15-1\_work\_temp\d269a066-30b0-4063-bf3e-04c509a3648c.ps1: line 3
at <ScriptBlock>, <No file>: line 1
The database restore operation failed due to the following error returned by SQL Server:

i set the sql timeout to 1200 but i think this restore does not pickup the parameter of the new-bccontainer?

**Comment by hvandenborn** [comment]
Freddy, I have a workaround,

i just make a normal container based on a image, and then i just set some settings on the NST, restore with bakfolder and then dismount and mount and all is fine.
