### ISSUE TITLE
Invalid/Dead link

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#1845]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I wanted to use the containers to upgrade a customer NAV2016 to Business Central. But the link to the NAV2016 manifest is not working

**Scripts used to create container and cause the issue**
$containerName = 'upgrade2016'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '7' -country 'dk'
$databaseServer = 'host.containerhelper.internal'
$databaseInstance = ''
$databaseName = 'customerDatabase'
$databaseUsername = 'sa'
$databasePassword = '*********'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = 'd:\nav\infar\udvikling\bc13.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -shortcuts DesktopFolder `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts

**Full output of scripts**
```
New-BcContainerWizard
Setting usePsSession = True
Setting hostHelperFolder = D:\BcContainerHelper
Setting use7zipIfAvailable = True
Setting defaultNewContainerParameters = @{Credential=; Accept_Eula=True; Isolation=Process; UpdateHosts=True; Auth=UserPassword}
Setting containerHelperFolder = C:\ProgramData\BcContainerHelper
Setting defaultContainerName = bcserver
Setting sandboxContainersAreMultitenantByDefault = True
Setting genericImageName = mcr.microsoft.com/dynamicsnav:{0}-generic
Setting bcartifactsCacheFolder = D:\Artifacts.cache
BcContainerHelper version 2.0.1
Launching C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.1\CreateScript.ps1
```
```
$containerName = 'upgrade2016'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2016' -cu '7' -country 'dk'
$databaseServer = 'host.containerhelper.internal'
$databaseInstance = ''
$databaseName = 'customerDatabase'
$databaseUsername = 'sa'
$databasePassword = '*********'
$databaseSecurePassword = ConvertTo-SecureString -String $databasePassword -AsPlainText -Force
$databaseCredential = New-Object pscredential $databaseUsername, $databaseSecurePassword
$licenseFile = 'd:\nav\infar\udvikling\bc13.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $databaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -shortcuts DesktopFolder `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts

Default parameter Isolation = Process
BcContainerHelper is version 2.0.1
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Downloading application artifact /onprem/9.0.45834.0/dk
Downloading C:\Users\Svend\AppData\Local\Temp\66914d4d-9cb0-45f8-936e-dee0d26e16a7.zip
Unpacking application artifact to tmp folder using 7zip
Downloading platform artifact /onprem/9.0.45834.0/platform
Downloading C:\Users\Svend\AppData\Local\Temp\230f823d-13b1-455a-86f4-c76988623713.zip
Unpacking platform artifact to tmp folder using 7zip
Downloading Prerequisite Components
Downloading D:\Artifacts.cache\onprem\9.0.45834.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading D:\Artifacts.cache\onprem\9.0.45834.0\platform\Prerequisite Components\Microsoft Report Viewer 2015\ReportViewer.msi
Downloading D:\Artifacts.cache\onprem\9.0.45834.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading D:\Artifacts.cache\onprem\9.0.45834.0\platform\Prerequisite Components\Microsoft Report Viewer 2015\SQLSysClrTypes.msi
Downloading D:\Artifacts.cache\onprem\9.0.45834.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Fetching all docker images
Pulling image mcr.microsoft.com/dynamicsnav:10.0.19041.685-generic
DockerDo : Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.19041.685-generic not found: manifest unknown: manifest tagged 
by "10.0.19041.685-generic" is not found
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.19041.685-generic
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.1\ContainerHandling\New-NavContainer.ps1:703 char:13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
```

**Screenshots**

**Additional context**
Tried updating the bccontainerhelper just to make sure, but get the same error.

Sidenote or request: Us docker newbies don't know the various conventions, so perhaps a small on containernaming while the wizard helps create the script? My first result had a containername starting with numerics (and contained uncerscore "_" ) Your HelperFunctions did not like that :) 
Container name should start with a letter (a-z)
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.1\HelperFunctions.ps1:174 char:9
+         throw "Container name should start with a letter (a-z)"

**Comment by freddydk** [comment]
Remove this line from your c:\programdata\bccontainerhelper\bccontainerhelper.config.json file:

`"genericImageName": "mcr.microsoft.com/dynamicsnav:{0}-generic",
`

**Comment by Rukkulakki** [comment]
Small step further

Setting usePsSession = True
Setting hostHelperFolder = D:\BcContainerHelper
Setting use7zipIfAvailable = True
Setting defaultNewContainerParameters = @{Credential=; Accept_Eula=True; Isolation=Process; UpdateHosts=True; Auth=UserPassword}
Setting containerHelperFolder = C:\ProgramData\BcContainerHelper
Setting defaultContainerName = bcserver
Setting sandboxContainersAreMultitenantByDefault = True
Setting bcartifactsCacheFolder = D:\Artifacts.cache
BcContainerHelper version 2.0.7
Default parameter Credential
Default parameter Isolation = Process
Default parameter UpdateHosts = True
Default parameter Auth = UserPassword
BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 2004
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
Fetching all docker images
Fetching all docker volumes
You have to specify artifactUrl or imageName when creating a new container.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\New-NavContainer.ps1:677 char:13
+             throw "You have to specify artifactUrl or imageName when  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You have to spe... new container.:String) [], RuntimeException
    + FullyQualifiedErrorId : You have to specify artifactUrl or imageName when creating a new container.

**Comment by Rukkulakki** [comment]
Also, should I leave the line out for good, or only when using old NAV versions?

**Comment by freddydk** [comment]
For good - you should only include settings in the settings file which you have a reason to change.
Not sure why artifacturl is empty:

```
Get-NavArtifactUrl -nav '2016' -cu '7' -country 'dk'
https://bcartifacts.azureedge.net/onprem/9.0.45834.0/dk
```

Check the variables and more

**Comment by Rukkulakki** [comment]
artifactUrl had value here as well. Tried running full script again, but did not help.
However restarting with New-bccontainerwizard and going through the motions seem to have done the trick. Currently downloading and verifying checksums :)
Thank you
