### ISSUE TITLE
manifest unknown: manifest tagged by... (Windows 21H1)

### ISSUE THREAD

**Issue by deadmouse** [microsoft/navcontainerhelper#1847]
**Describe the issue**
DockerDo : Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.19041.388-generic not found: manifest unknown: manifest tagged by "10.0.19041.388-generic" is not found

**Scripts used to create container and cause the issue**
```
$containerName = 'dockerbc'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '' -country 'es' -select 'Latest'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -assignPremiumPlan `
    -updateHosts
```

**Full output of scripts**
```
DockerDo : Error response from daemon: manifest for mcr.microsoft.com/dynamicsnav:10.0.19041.388-generic not found: manifest unknown: manifest tagged by "10.0.19041.388-generic" is not found
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/dynamicsnav:10.0.19041.388-generic
En C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\1.0.4\ContainerHandling\New-NavContainer.ps1: 690 Carácter: 13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
```

**Additional context**
My windows version is Windows 10 Pro 21H1 (19043.867). My BcContainerHelper version is 2.0.8.

**Comment by freddydk** [comment]
https://github.com/microsoft/navcontainerhelper/issues/1821

**Comment by deadmouse** [comment]
Thank you very much for you fast answer. I checked I have the latest BcContainerHelper version (I do) and I didn't have c:\programdata\bccontainerhelper\bccontainerhelper.config.json, so, I deleted two folders and then it worked!, which are:

- c:\programdata\bccontainerhelper
- c:\programdata\navcontainerhelper

**Comment by freddydk** [comment]
In the output above, you were running 1.0.4:

...BcContainerHelper\**1.0.4**\ContainerHandling...

Which definitely wasn't the latest.
You could probably just have updated and restarted PowerShell.
