### ISSUE TITLE
Replace Self Signed Certificate

### ISSUE THREAD

**Issue by MaxBelohoubek** [Microsoft/navcontainerhelper#185]
Is it possible to pass a _Let's Encrypt_ certificate to the container while it is being created?
The creation of the cert is not a problem, I just need a way to tell the containerhelper to use my cert instead of the self-signed one.

**Comment by freddydk** [comment]
Yes, if you use http://aka.ms/getnav that is exactly what happens.
The code for that is in the nav-arm-templates on GitHub or you can deploy an azure vm and disassemble.

**Comment by MaxBelohoubek** [comment]
Looks like I can use that. Thanks for the quick help!
