### ISSUE TITLE
Runtime can not be published in images using /onprem/17.0.16993.0/de

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#1854]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Runtime packages can not be published in a container thats uses artifact /onprem/17.0.16993.0/de or /onprem/17.0.16993.0/w1.

##[error]Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 
'System.Collections.Generic.List`1[Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageEmittedContent]' because the 
type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is 
a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object. Path 'PlatformVersion', line 1, position 19. At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13 +             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : OperationStopped: (Cannot deserial...1, position 19.:String) [], RuntimeException

    + FullyQualifiedErrorId : Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Col 

   lections.Generic.List`1[Microsoft.Dynamics.Nav.CodeAnalysis.Packaging.PackageEmittedContent]' because the type req  

  uires a JSON array (e.g. [1,2,3]) to deserialize correctly.

    To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it 

    is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) th  

  at can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deseri   

 alize from a JSON object.

Path 'PlatformVersion', line 1, position 19.

I've tried two diffrent runtimes by two diffrent vendors. On a normal OnPrem (in that version) these packages can be published and installed.

This is a deep as i could track the error.
https://github.com/microsoft/navcontainerhelper/blob/0931455f18071df620a4c3140b4ab7e01cfbe709/AppHandling/Publish-NavContainerApp.ps1#L274

Maybe there is something wrong with the NAVAdminTools

I get this Warning when Publishing against a newer version. Not related but might give you an insight in the package.
> WARNING: The Packet was created on a diffrent version then the current. Packet:17.0.18204.18738, Server: 17.0.18204.18458.

Thanks

**Comment by freddydk** [comment]
Runtime packages are only supported on the same platform and app version as they are created,

**Comment by jonaswre** [comment]
But its working in that case its just warning me.
> WARNING: The Packet was created on a diffrent version then the current. Packet:17.0.18204.18738, Server: 17.0.18204.18458.

But its not working with the artifacts above.

**Comment by freddydk** [comment]
They probably changed something in the format - runtime packages are compiled packages - if anything is different - things might break.
We do not block importing - like with .fob files we import, but with .fob files you could compile afterwards - you cannot do that with runtime packages - the source is not there - only the code.

**Comment by jonaswre** [comment]
Okay, i'll try and go to the vendors an get an older runtime. I was hoping there was something wrong with the dlls that would be fixed easily. 

Thanks a lot!

**Comment by freddydk** [comment]
If the partner is using containerHelper, you can tell them about:

Convert-BcAppsToRuntimePackages - which basically converts a set of apps to match an artifactUrl.
