### ISSUE TITLE
Start-NavContainerAppDataUpgrade gives an error "You must choose a company"

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#186]
Hi Freddy,
I want to publish app with increased version no in the local container with Ctrl+F5 and get an error
![image](https://user-images.githubusercontent.com/29101017/44526644-577bef00-a6ed-11e8-85de-9caf95c6f207.png)

Reasonable.
But when i run  Start-NavContainerAppDataUpgrade i get strange error
![image](https://user-images.githubusercontent.com/29101017/44526701-7ed2bc00-a6ed-11e8-8cc6-20477a499715.png)

Can you check, what i'm doing wrong?

**Comment by dkatson** [comment]
Ah, ok.
I found what's the reason.

I've added code in OnUpgradePerDatabase trigger.
Uff... May be to make error more user friendly?

**Comment by freddydk** [comment]
Yeah, I think I am just surfacing the error I get from the platform and I guess you could write code which doesn't touch company specific data and you would be fine without selecting a company.
I think the error stems from AL accessing a company specific table.

**Comment by dkatson** [comment]
Correct. I just populate my table with data during installation procedure, using install codeunit. And i missed up with trigger. Used InstallPerDatabases instead of InstallPerCompany. Spent about 1 hour trying to understand whats going wrong. As we can’t debug installation process it’s difficult to find a problem quickly with such errors.
But it’s not topic of this repository)
Thanks, and sorry for distirb.

Dmitry
