### ISSUE TITLE
Wizard - still require license file for automate tests development

### ISSUE THREAD

**Issue by mynavblog** [microsoft/navcontainerhelper#1860]
**Describe the issue**
I just tested and it is not needed to use license file for below parameters
    -includeTestToolkit `
    -includeTestLibrariesOnly `
 However when using New-BcContainerWizard it still says that I need to put custom license file when choose option **b** on screen below.

**Scripts used to create container and cause the issue**
```
New-BcContainerWizard

```

**Full output of scripts**
```
None

```

**Screenshots**
![image](https://user-images.githubusercontent.com/37371997/113427898-28b27300-93d6-11eb-8a0b-c2323900962d.png)

**Additional context**
none

**Comment by freddydk** [comment]
Shipped in 2.0.10
