### ISSUE TITLE
[Question] NAS Service from Container with external database

### ISSUE THREAD

**Issue by sirhc101** [microsoft/navcontainerhelper#1862]
Hi freddy,

this may is unrelated to BcContainerHelper but I'll try anyway.
I've a docker container, using an external SQL database, running with `Azure Active Directory` authentication. Everything works pretty well, except for publishing from VSCode, which is not supported yet. So I created another container targeting the same external database using `NavUserPassword` authentication. Thanks to your shared encryption key enhancement for BcContainerHelper this also works pretty well.

Now we have the problem, that one ISV module which is installed in the database requires multiple NAS services (one per company) to be run. It seems for me, that with AAD authentication you cannot run a NAS service. I think I understand why: You cannot authenticate. So I though it would may be the best idea to create another container using `Windows` authentication for this purpose. I created a container using `New-BcContainer`. Afterwards I invoked another script to create the necessary Server Instances, disabled Client, Soap, OData, Development, Snapshot, Management, Task Scheduler Service and activated the NAS Service with the required parameters. So far so good... but I simply get stuck with this error message:
> The Microsoft Dynamics 365 Business Central Application Server session for tenant 'default' has failed and will be restarted in 0 seconds. Reason: Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavInvalidCredentialException

I already added the `NT AUTHORITY\NETWORK SERVICE` (this is the service account) as a Business Central Windows user but this does not help.

I know it's not directly related to BcContainerHelper, but I hope you may have an idea how to do this.

Thank you!

**Comment by freddydk** [comment]
I don't know much about NAS and the setup of these.
Service Tier in containers are running as NT AUTHORITY\SYSTEM if I remember right (couldn't get network service to work).
Don't know if this is part of the problem - alternatively you may need to setup GMSA - I haver never tried this myself.

**Comment by sirhc101** [comment]
Thank you for your feedback freddy!

I got the service up and running using network service, but it was a little tricky, that's true.
I will play around with it and see if I can get it to work. I'll update this issue if you like!?

**Comment by sirhc101** [comment]
`NASServicesRunWithAdminRights` server property solved the problem. As documented you do not need to setup the NAS Service User when enabling this option.

**Comment by freddydk** [comment]
So, shouldn't this server property just be set when creating a container always?

**Comment by sirhc101** [comment]
@freddydk that's a pretty good question. NAS Services are not activated on default and I guess, based on the feedback I received while asking and searching for solutions, no one really uses NAS Services anymore. Me too, I didn't missed it ever since first docker images where released.

What I want to say: you have to configure NAS services manually anyway, so you may change this setting. I think it's not easy to make sure it will set to true in any case.
I think it would just make sense if there would be an option to create a container with enabled NAS services in New-BCContainer.

So I would say no, it's not necessary. Through google anyone should now find this issue and can solve it this way
