### ISSUE TITLE
Issue creating Container

### ISSUE THREAD

**Issue by Bssivivek** [Microsoft/navcontainerhelper#187]
Hi,
Currently we are working in NAV business central.
I downloaded the image by issuing following command - **docker pull microsoft/bcsandbox:us**
After downloading the image, i issue following command to create the container
**New-NavContainer -containerName SB-D365BC-US -accept_eula -auth NavUserPassword -imageName microsoft/bcsandbox:us -includeCSide -licenseFile "C:\Temp\SB NAV2018.flf"**
Now its stuck
PS C:\WINDOWS\system32> New-NavContainer -containerName SB-D365BC-US -accept_eula -auth NavUserPassword -imageName microsoft/bcsandbox:us -includeCSide -licenseFile "C:\Temp\SB NAV2018.flf"
Creating Nav container SB-D365BC-US
Using image microsoft/bcsandbox:us
Using license file C:\Temp\SB NAV2018.flf
NAV Version: 12.3.23590.23828-US
Generic Tag: 0.0.6.4
Removing C:\ProgramData\NavContainerHelper\Extensions\SB-D365BC-US
**Creating container SB-D365BC-US from image microsoft/bcsandbox:us**
Now its struck for long time. I check the task manager and i see that disk is 0% which means there is no disk operation.

Can some one help please.

**Comment by Update-Mark** [comment]
I have also run into this today.  Opening another powershell window and looking at the logs showed that the container was running and when browsing to it allowed login and access.

**Comment by freddydk** [comment]
Very strange - will have to debug the wait-containerready code - this shouldn't happen...

**Comment by Update-Mark** [comment]
Interestingly, I deleted the container and reran the process, no issues.

**Comment by freddydk** [comment]
Thanks
