### ISSUE TITLE
Flush-BCContainerHelper deletes images used by stopped containers

### ISSUE THREAD

**Issue by nudelwerfer** [microsoft/navcontainerhelper#1870]
**Describe the issue**
Hi,

we use the Flush-ContainerHelperCache function with -keepdays 14 on central host. The cmdlet deletes images from containers that are exited longer than 14 days but still exist on the host. So after 14 days you can't start the container anymore.
I would consider this as a bug, as the image is still in use by the exited container and therefore should not be removed by the cmdlet. Correct me if im wrong :)

**Screenshots**
Error when you try to start a container -> the image is missing
![123](https://user-images.githubusercontent.com/82083658/113831899-61f93300-9788-11eb-9a5f-911b9d39d1b9.png)

**Additional context**
Do you maybe have an idea how to fix container which broke because of this problem?

**Comment by freddydk** [comment]
I see this as a bug as well.
I must admit I never tried this and I did expect docker to NOT remove images in use by stopped containers.
Unfortunately, there is no way you can create the image again and get your container back.
If the container contained anything, which you absolutely need, you might be able to find it in the programdata\docker\windowsfilter - but not certain.

I will investigate whether I can fix this.

**Comment by nudelwerfer** [comment]
Thanks for the quick reply! I already thought so that you can't get it back.
A fix would be much appreciated, otherwise we sure will find a workaround :)

**Comment by freddydk** [comment]
Shipped in 2.0.11
