### ISSUE TITLE
Suggestion: Also provide a preview of the upcoming CUs of older Business Central Versions

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#1879]
**Describe the idea**.
Every time something gets fixed due to a support case, I get a download link of a preview of the next Business Central CU update e.g. BC14.25. I have to download this zip, create a new VM, install the service tier, install web server, SQL Express, etc.... 

It would be cool if I could also get a preview of the upcoming CU from older Business Central versions via **bccontainerhelp**. E.g. with the insider key. So I just need to create a new Docker, test the fix and I'm done.

**Comment by tfenster** [comment]
@DanielGoehler I have to admit that I haven't seen one of those packages for some time, but if I remember correctly, they were basically the same structure as the "DVD" downloads, right? If yes, then you could easily use the already existing mechanism to create an image. Again, it's quite some time ago, but I think I recall that I did this successfully

**Comment by DanielGoehler** [comment]
@tfenster My suggestion is to skip the hole download the dvd part and fetching the upcoming cu also via artifacts download.

**Comment by DanielGoehler** [comment]
@tfenster You are right, creating a container from DVD is very simple. I was not aware of it.  Today Microsoft support provided me with the following script. Works great and it's not a big deal as I thought....
```
$containerName = "BC-14-25-DE"
$dvdPath = 'c:\temp\w1dvd.zip'                                    
$mylicense = 'C:\DOCKER\LICENSE\14.flf'
$dvdCountry = 'de'

Write-Host "Targeting hybrid BC DVD : $dvdPath" -ForegroundColor Cyan
Write-Host ""
    
New-BCContainer -accept_eula `
-containerName $containerName `
-licenseFile $mylicense `
-dvdPath $dvdPath `
-dvdCountry $dvdCountry `
-auth UserPassword `
-accept_outdated `
-alwaysPull `
-updateHosts `
-useBestContainerOS  `
-dns '8.8.8.8' `
-doNotExportObjectsToText `
-includeCSide    
```
