### ISSUE TITLE
Need Advice: What is the easiest way to copy an existing container?

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#1880]
**Describe the issue**
I want to try something and I have prepared a Docker with demo data and apps that I want to copy for this purpose. What would be the easiest way to copy an existing container?

Sure I can export a SQL Server backup and use that to create a new Docker container. I can see the build number, but I don't know if the existing container was created from the OnPrem, Cloud Sandbox, Insider or Preview artifacts. It could also be with an OnPrem container that I had to install additional DLLs and the new container would need also this DLLs.

Is there an easier way than SQL Server backup and use this backup while creating a new container to copy a Docker container?

**Comment by TGosselink** [comment]
Sure, this is the way I do it:

Write-Host "Prepare Docker image" -ForegroundColor Yellow
$dockerid = Get-BcContainerId $dockername
Write-Host "  Stop Docker image" -ForegroundColor Yellow
docker stop $dockerid
Write-Host "  Commmit Docker image to $mycontainerName" -ForegroundColor Yellow
docker commit $dockerid $mycontainerName
Write-Host "Restart Docker image" -ForegroundColor Yellow
docker start $dockerid

Now, start 2 second container from the saved image ($mycontainerName)

**Comment by DanielGoehler** [comment]
Hi @TGosselink, thank you! For the purposes of completeness I created a docker container like this afterwards: `New-NavContainer -containername mycopy -imageName $mycontainerName [..]`
