### ISSUE TITLE
[Question] What is the recommended way to set server configuration?

### ISSUE THREAD

**Issue by thomas-tarp** [microsoft/navcontainerhelper#1881]
Hi,

I wish to change the setup of a Business Central 14 On-prem server instance on startup, specifically increasing SOAPServicesMaxMsgSize.

Is there a recommended way to do this?

**Comment by tfenster** [comment]
@thomas-tarp AFAIK the best way is to use the `customNavSettings` environment param. So if you want to increase `SOAPServicesMaxMsgSize` to 2048 with bccontainerhelper it would look like this:

New-BCContainer -additionalParameters @("-e customNavSettings=SOAPServicesMaxMsgSize=2048") ...

with `...` being your additional parameters

**Comment by thomas-tarp** [comment]
Thank you, @tfenster - very simple and works brilliantly :-)
