### ISSUE TITLE
QUESTION: Backup-BcContainerDatabases

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#1882]
**Describe the issue**
Everytime I run the Backup-BcContainerDatabases command on a container with a Business Central Sandox environment, it creates two bak files.

app.bak 
default.bak

**Scripts used to create container and cause the issue**
Backup-BcContainerDatabases

I thought I would only get one bak file?

**Comment by tfenster** [comment]
@Silentapproach the sandbox containers are multi-tenant by default, so you get one .bak for the application database and one .bak for the tenant database. If you want/need to dig deeper, [this](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/multitenant-deployment-architecture) explains multi-tenancy and [this](https://freddysblog.com/2020/10/12/multitenant-sandbox-containers-changes-behavior/) gives a bit more information about the sandbox container config

**Comment by Silentapproach** [comment]
Ok, that already helped a lot! I actually don't need to dig deeper. Thanks!
