### ISSUE TITLE
Add Option for Debug Mode in Run-AlPipeline

### ISSUE THREAD

**Issue by MatthewMcCarthy7** [microsoft/navcontainerhelper#1885]
I will get issues sometimes in my Run-AlPipeline on the Run Test Functions in my CI pipelines.  I will rerun the pipeline again, and the error won't show up.  I was wondering if we could add the parameter -debugMode from Run-TestInBCContainer into Run-AlPipeline so that I could catch these issues.

**Comment by freddydk** [comment]
You can add this parameter to Run-AlPipeline:
```
    -RunTestsInBcContainer { Param([Hashtable]$parameters) Run-TestsInBcContainer -debugMode @parameters }
```
Then Run-Tests should run with DebugMode.

**Comment by MatthewMcCarthy7** [comment]
Thank you. That solution for me.
