### ISSUE TITLE
Publish app error: Unsupported symbol type 393321

### ISSUE THREAD

**Issue by sousalopes** [microsoft/navcontainerhelper#1889]
**Describe the issue**
When publishing an App an "unsupported symbol" error is thwoned

**Scripts used to create container and cause the issue**
`Publish-NAVApp -ServerInstance BC -Path 'c:\Extensions\locpt.app' -PassThru -SkipVerification

**Full output of scripts**
Publish-NAVApp : Unsupported symbol type 393321
At line:1 char:1
+ Publish-NAVApp -ServerInstance BC -Path 'c:\Extensions\locpt.app' -Pa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Manageme
   nt.Cmdlets.PublishNavApp

**Comment by freddydk** [comment]
What version of Business Central?
What version of BcContainerHelper?
Is the app a runtime package or a "real" app file?

**Comment by sousalopes** [comment]
What version of Business Central?
W1 18.0 (Plataform 18.0.22893.24464 + Aplication 18.0.23013.24471)

What version of BcContainerHelper?
2.0.10

Is the app a runtime package or a "real" app file?
"real"

**Comment by freddydk** [comment]
and was the app built for 18.0?

**Comment by freddydk** [comment]
I probably need the .app file - if you can email me a link where I can download the app (freddyk at microsoft dot com)

**Comment by sousalopes** [comment]
GRRR... Sorry Freddy, my fault... it was an issue with the version of BC (solved now). Thanks for your quick answer.
