### ISSUE TITLE
Question: use testapps from older version

### ISSUE THREAD

**Issue by peterz84** [microsoft/navcontainerhelper#1893]
We are using the following script to generate a container which is technically on version 17.1 but the modified base app is on version 17.0.:

```
$artifactUrl = Get-BCArtifactUrl -country "nl" -version "17.1" -storageAccount bcartifacts -type “OnPrem” 
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$dbcredentials = New-Object PSCredential -ArgumentList 'sa', $credential.Password
$containername = "BC17-1"
$DatabaseName = "MY-CUSTOM-BASE-17CU00"
$licenseFile = "C:\17.flf"
New-BcContainer `
    -accept_eula `
    -containerName $containername `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -updateHosts `
    -licenseFile $licenseFile `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -databaseServer 'host.containerhelper.internal' `
    -databaseInstance '' `
    -databaseName $DatabaseName `
    -databaseCredential $dbcredentials
```

this creates the following error: 
![image](https://user-images.githubusercontent.com/25202313/115680475-e1bff980-a353-11eb-8ee9-9f079d82cce6.png)

Which I understand, because the system application of 17.1 is not available in the custom database.
Is it possible to install the Test-apps from version 17.0?

**Comment by freddydk** [comment]
You cannot get New-BcContainer to install test applications from a different version using the automated parameters.
You can create the container without the test framework and then download the 17.0 artifacts and install the test apps from there.
If you want to do this, you would need to download the artifacts from 17 and grab the test apps from there.
Unfortunately this isn't as simple as it sounds, but the code below should grab the needed apps:
```
$ver17artifacts = Get-BCArtifactUrl -version 17 -country us -type OnPrem
$paths = Download-Artifacts -artifactUrl $ver17artifacts -includePlatform
$testapps = @()
$paths | ForEach-Object { 
    $path = $_
    'Applications\testframework\TestRunner\*.app', 'Applications\testframework\TestLibraries\*.app', 'Applications\BaseApp\Test\Microsoft_Tests-TestLibraries.app' | ForEach-Object {
        Get-ChildItem -Path (Join-Path $path $_) -Recurse | ForEach-Object {
            $app = $_
            if (!($testapps | Where-Object { $_.Name -eq $app.Name })) {
                $testapps += @($app)
            }
        }
    }
}
$testapps.FullName | ForEach-Object {
    Publish-BcContainerApp     
}
```
Next preview of Business central will have a parameter on Publish-BcContainerApp called -ignoreIfExists - you can use this if some of the apps are already in the database.
