### ISSUE TITLE
New versions of BCContainerHelper refer to the previous version when building new container - which errors.

### ISSUE THREAD

**Issue by dkiehl** [microsoft/navcontainerhelper#1896]
**Describe the issue**
New-BCContainer uses the wrong version which is causing an error.  At the top, we remove all versions of BCContainerHelper and re-install the latest version - and confirm it with a Get-InstalledModule.  The version shows 2.0.11 - but the New-BCContainerHelper displays version 2.0.10.. and then errors.  This has been happening since before version 2.x was released - been using the work-around mentioned below.

**Scripts used to create container and cause the issue**
```
$containername = "Test18"
$ver = "18"

$modName = "BCContainerHelper"

clear-host
write-host "** Latest Version available: " (Find-Module $modName).Version.ToString()

write-host "** Uninstalling ALL versions"
Uninstall-Module $modName -AllVersions -Force

write-host "** Installing Latest Version"
Install-Module $modName -Force

write-host "** Now Using Version: " (Get-InstalledModule $modName).Version.ToString()
write-host

$artifactUrl = Get-BCArtifactUrl -type OnPrem -version 18 -select Latest -country w1
write-host "** Using artifacts: " $artifactURL
Download-Artifacts -artifactUrl $artifacturl -includePlatform

$PublicDNSName = "abc.azure.com"
$MainUser = "<user here>"
$MainPass = "<password here>"

$localLicenseFile = "C:\Support\Build Containers\Licenses\BC18\5414366.flf"
                             
$auth = "NavUserPassword"
$securePassword = ConvertTo-SecureString -String $MainPass -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList $MainUser, $securePassword

New-BCContainer `
    -accept_eula `
    -containerName $containername `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -updateHosts `
    -multitenant `
    -includeAL `
    -useTraefik `
    -PublicDNSName $PublicDNSName `
    -licenseFile $localLicenseFile


$extension = "tegossuite.Core_Runtime_18.0.843.0_(Platform 17.0.22463.22540).app"
Publish-BCContainerApp -containerName $containername `
        -appFile $extension `
        –SkipVerification `
        -install `
        -sync forcesync

...
```

**Full output of scripts**
```
** Latest Version available:  2.0.11
** Uninstalling ALL versions
** Installing Latest Version
** Now Using Version:  2.0.11

** Using artifacts:  https://bcartifacts.azureedge.net/onprem/18.0.23013.23795/w1
c:\bcartifacts.cache\onprem\18.0.23013.23795\w1
c:\bcartifacts.cache\onprem\18.0.23013.23795\platform
BcContainerHelper is version 2.0.10
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Removing C:\ProgramData\BcContainerHelper\Extensions\Test18
Fetching all docker images
Fetching all docker volumes
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image mcr.microsoft.com/businesscentral:10.0.17763.1879
PublicDnsName is itaddocker.eastus2.cloudapp.azure.com
Creating Container Test18
Version: 18.0.23013.23795-w1
Style: onprem
Multitenant: Yes
Platform: 18.0.22893.23773
Generic Tag: 1.0.1.6
Container OS Version: 10.0.17763.1879 (ltsc2019)
Host OS Version: 10.0.17763.1879 (ltsc2019)
Using process isolation
Using locale en-US
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Support\Build Containers\Licenses\BC18\5414366.flf
Copy-Item : Cannot find path 'C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\updatehosts.ps1' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\New-NavContainer.ps1:1491 char:9
+         Copy-Item -Path (Join-Path $PSScriptRoot "updatehosts.ps1") - ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...updatehosts.ps1:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
 

PS 04/22/2021 12:27:25>  
...
```

**Screenshots**
![error](https://user-images.githubusercontent.com/35543518/115752546-33727f00-a368-11eb-8242-be96acafe1b0.jpg)

**Additional context**
This always happens - my 'work around' is to go into "Program Files\WindowsPowershellScripts\Modules\BCContainerHelper" an copy the new version directory (in this example, 2.0.11) to a new directory I create called 2.0.10 and then I can proceed (until the next version is released, which I have to do this again.

**Comment by freddydk** [comment]
Have you tried to use

Remove-Module BcContainerHelper
Uninstall-module bccontainerHelper -allversions
Install-module bccontainerhelper

Restart PowerShell

What version is now the latest?

**Comment by dkiehl** [comment]
Just tried the following (Remove-Module didn't seem to work)
```
$modName = "BCContainerHelper"

clear-host
write-host "** Current Version: "  (Get-InstalledModule $modName).Version.ToString()
write-host "** Latest Version available: " (Find-Module $modName).Version.ToString()

write-host "** Removing Module: " $modName
Remove-Module $modName

write-host "** Uninstalling ALL versions"
Uninstall-Module $modName -AllVersions -Force

write-host "** Installing Latest Version"
Install-Module $modName -Force

write-host "** Now Using Version: " (Get-InstalledModule $modName).Version.ToString()
write-host
```
and the result was
![image](https://user-images.githubusercontent.com/35543518/115774613-ccf95b00-a37f-11eb-96cd-dab17d2cae80.jpg)

I then restarted Powershell and ran the original script and it seems to work.  I would conclude that I need a separate script to upgrade BCContainerHelper - then restart powershell - and continue on building/rebuilding the container.

**Comment by freddydk** [comment]
This is all standard PowerShell - nothing special with BcContainerHelper.

Remove-Module removes a module from memory - if it fails, it is because the module is not in memory.
Import-Module imports a module to memory (opposite of Remove-Module)
When PowerShell uses a command from a module the first time, it implicitly imports the latest module into memory.

Install-Module installs a module on disk.
If the module is already imported, install-module just adds another folder to the module directory - it doesn't import that.
Uninstall-Module uninstalls a module from disk.

My assumption is that this:

```
Remove-Module $modName -ErrorAction Ignore
Uninstall-Module $modName -AllVersions -Force
Install-Module $modName -Force
Import-module $modName -DisableNameChecking
```

would cause the latest containerhelper to be used in this session.
Note, that when running this in two PowerShell prompts in the same time can lead one to remove things from the other.
Removing the UnInstall-Module would prevent this, but would also cause multiple versions of the module to be installed, but only the latest to be loaded.

A simple Install-module followed by a PowerShell restart should also load the latest.

**Comment by dkiehl** [comment]
Thanks.
