### ISSUE TITLE
Using parameters bakFolder & licenseFile together

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#1897]
Hey @freddydk, 

We are using bakFolder parameter to speed up our builds. It was all working great until the license got expired. Apparently license is not updated, even if you specifiy licenseFile. Is it expected behaviour or a bug? How would you recommend to setup the pipeline so, we could use bakfolder, & update the license together?

Our code snippet for creating container looks like this:

```
New-BcContainer -containerName $containerName `
            -accept_eula `
            -accept_outdated `
            -artifactUrl (Get-BCArtifactUrl -type OnPrem -country 'w1' -version $setttings.platformBuildVersion) `
            -auth NavUserPassword `
            -Credential $Credential `
            -doNotExportObjectsToText `
            -doNotCheckHealth `
            -licenseFile $licenseFilePath `
            -locale "nl-NL" `
            -additionalParameters $additionalParameters `
            -isolation process `
            -myScripts $myScripts `
            -bakFolder $containerName
```

BcContainerHelper version 2.0.7

Best Regards,
Gintautas

**Comment by gintuoklis** [comment]
clear, 
will add a scripts todo that. Once license expires within a backup, container could not be created any longer.

**Comment by hvandenborn** [comment]
hint: store backup on a sql, and rip every week or something the backup to bak. to use for the builds. 
then before you rip the backup, update the license (with sql query)
