### ISSUE TITLE
docker container always restarts

### ISSUE THREAD

**Issue by sodgeronimo** [Microsoft/navcontainerhelper#19]
Hi Freddy,

at the moment i have 5 nav containers running on my local system.
however on reboot of my machine they all boot up as well. (which takes most of my RAM away as they each have 3G on a win10 machine)

i know i can stop them with the docker stop command. 

i had a further look and have seen that the origin is found in the restart parameter so for now i have updated my containers with the following command to counter this behavior

`docker update --restart=no <containername>`

however the source of this behaviour is found in the new-navcontainer file (line 155)
```
    $parameters = @(
                    "--name $containerName",
                    "--hostname $containerName",
                    "--env auth=$auth"
                    "--env username=$vmAdminUsername",
                    "--env ExitOnError=N",
                    "--env locale=$locale",
                    "--env licenseFile=""$containerLicenseFile""",
                    "--memory $memoryLimit",
                    "--volume ""${demoFolder}:$containerDemoFolder""",
                    "--volume ""${myFolder}:C:\Run\my""",
                    "--restart always"
                   )
```
is there a possibility to make this parameter accessible from the command so i don't have to update them anymore? (i'm still new to github so i don't see how i need to edit and suggest this yet)

kind regards,
sodgeronimo

**Comment by freddydk** [comment]
You can add parameters to new-navcontainer like:
 -additionalParameters @("--restart no")
That should overwrite the prior setting for --restart.
You could also install Windows Server 2016 - which doesn't pre-allocate memory for containers but instead shares the resources from the host to all the containers.

**Comment by sodgeronimo** [comment]
thanks for the quick respons @freddydk 

i didnt know it would overrule the setting, another thing learned. i just tried it with the new-csidedevcontainer and it works like a charm when i inspect my container :)

looking forward to seeing you on navtechdays next week
