### ISSUE TITLE
Error by New-NavContainer

### ISSUE THREAD

**Issue by Fravid** [Microsoft/navcontainerhelper#190]
Hello,

when I try to run the command New-NavContainer an error  occures when it tries to create a container .

the scripts stops at: Creating container BC from image microsoft/bcsandbox:de

[Error_log.txt](https://github.com/Microsoft/navcontainerhelper/files/2331841/Error_log.txt)

`
Handler for POST /v1.38/containers/c99d22a1b5e0194610487af6c586e1802698c877c9107fa8460ca7f395874b23/start returned error: container c99d22a1b5e0194610487af6c586e1802698c877c9107fa8460ca7f395874b23 encountered an error during CreateContainer: failure in a Windows system call: Dieser Vorgang wurde wegen Zeitüberschreitung zurückgegeben. (0x5b4) extra info: {"SystemType":"Container","Name":"c99d22a1b5e0194610487af6c586e1802698c877c9107fa8460ca7f395874b23","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\c99d22a1b5e0194610487af6c586e1802698c877c9107fa8460ca7f395874b23","Layers":[{"ID":"866ee007-c8f1-5ebf-bb8b-00cf0efe9e93","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d36ba94a2aeca13d47d9282d5358f4be0cc5e29e341ef18c0d0eebb3d11c668d"},{"ID":"ab71bae4-50ce-5756-925d-65936c63a24f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\de119f8ed1f53ebfc8202159bbca3a1a71fbb33cd232cfc3ecb25ffbf5c381a8"},{"ID":"1ea652ec-4ba4-5658-a41b-4cc6b296eade","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eb18f558cf449312a246c451788fe74fbb11eac69a4ed7dc31542befeadb5217"},{"ID":"0d09ef43-47eb-5b44-81fc-7e0cbbc2061b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7a18c5924c6c1b4cbe2b7335b8ae06015aefaa41f7a27605b3e10166119a240c"},{"ID":"9e12e8c7-271d-5821-9d83-b51d93e351d9","Path":"C:\\ProgramData\\Docker\\windowsfilter\\188ca59866e5737afbbef81b81345a50716e22ebe97a2da5a4d7287cc0775beb"},{"ID":"55f418f4-997f-5bae-801d-e09ab20f4afb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9b4dee4cf97122c941f1da6f1ea7c0d4203428252b3810ff409e6ff8071d999c"},{"ID":"5ee8879a-3fdc-5b18-b818-c3fafe86becc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cc48f8e3965d21e4baa33d852a4a797bcbf4541fdaf08cce35f2b6032d49a4dc"},{"ID":"babcef20-5ad3-57f9-bb4c-aef46389e287","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1dcd8ed028062c6b239aa976651b78e36a16e0885e8ea298cf7297a92e465abb"},{"ID":"26d7c380-9100-51a4-b97b-ec77096f21dd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bffa7978d82901bdebc950ed76223657a2510046c29230c5c12adc462c1b0e01"},{"ID":"1a725fd9-25ac-558b-a95f-2117df1fbc2c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7f05eec34a882b617ec046fd3da976e7df92f55102cae57af22727774045e16f"},{"ID":"5a089b9e-7e78-5479-90a2-6d7588107153","Path":"C:\\ProgramData\\Docker\\windowsfilter\\603c87b82a185e7ac6ff73b318380d9bc9f9294a5d610a1b294c2de1cf488b42"},{"ID":"d1c50eb5-3054-5d60-b1e4-0a623a5d65fa","Path":"C:\\ProgramData\\Docker\\windowsfilter\\15814042b34aeaff6a0730316cb62ae73ff9ea52b9da60520bfb34b3f08d9610"},{"ID":"53da5df0-ed1f-5fde-9e61-28cc6e1d6089","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a7bd9a0ef95159f63979a0dc7af7e6180937faf2f3912a88415aabfb1bde3b6a"},{"ID":"46f224a8-f3b8-5161-beeb-05e7d976a8e5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d39e2ede0cfcbb43d7faa1ae57b1d4fe40cdefc1b324a7abe34e6fc68f1deff7"},{"ID":"b37953f2-a6e6-5758-b1c7-e5d778c6cd78","Path":"C:\\ProgramData\\Docker\\windowsfilter\\56d28a079082eb4bf7a10b3f088836803ae316132d6d65a0fefb48010c5e8a5c"},{"ID":"270ae881-6cee-559f-8989-ed5805ab3613","Path":"C:\\ProgramData\\Docker\\windowsfilter\\68e00948a2a815cb28adac1ad87f06dc98de224e2aea4f4c7b847e61653040a3"},{"ID":"debc1b89-d261-5b20-ad26-07f531061eaf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3ae9e790800732a14a4318a16c5434bd0328619ec5e7dd00a735514044f9e9b4"},{"ID":"bb5d54aa-d69e-5ca1-bb12-0477dde9028a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4a4d5a74b75224c40135f394aef9454c29843acbdc2898936df482be502a5ba2"},{"ID":"481e777a-8886-5df4-b400-5a5f633503fc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\11130252dbf21d562b725c71ab7231ddf591c8802a346e553d4575b6f9e4587e"},{"ID":"4675a3e0-9689-5669-8a07-106656ab37e2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\93fd0a759a64bc70ec96388dd25bad58763e80ebb54e424553d6e4d375ed0d6f"},{"ID":"92b91461-c605-51d8-900b-974f84790075","Path":"C:\\ProgramData\\Docker\\windowsfilter\\78a18477db25977af6e5cef3335aaa729b22d9412f646488f7e7f60134f4dff7"},{"ID":"c48c5b63-4119-5026-a45c-ee261eb2e092","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1e14744cedf62ee7a22477b8b9bfcdf04c1ebde0e7309a4313bcfc20712e9e16"}],"MemoryMaximumInMB":4096,"HostName":"BC","MappedDirectories":[{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\bc\\program files","ContainerPath":"c:\\navpfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper","ContainerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\bc\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["d447b981-7429-453c-b881-71a4703b2f25"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\78a18477db25977af6e5cef3335aaa729b22d9412f646488f7e7f60134f4dff7\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
`

**Comment by Fravid** [comment]
docker logs bc 
--> empty result

docker inspect bc

docker inspect BC
[
    {
        "Id": "55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d7c18be42f",
        "Created": "2018-08-29T14:43:47.3870119Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "created",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 128,
            "Error": "container 55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d7c18be42f encountered an error during CreateContainer: failure in a Windows system call: Di
eser Vorgang wurde wegen ZeitÃ¼berschreitung zurÃ¼ckgegeben. (0x5b4) extra info: {\"SystemType\":\"Container\",\"Name\":\"55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d7
c18be42f\",\"Owner\":\"docker\",\"IgnoreFlushesDuringBoot\":true,\"LayerFolderPath\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\55a65977ee7da672b65c8fe345d7188c7a018ee4f90
2a9c1b35373d7c18be42f\",\"Layers\":[{\"ID\":\"866ee007-c8f1-5ebf-bb8b-00cf0efe9e93\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\d36ba94a2aeca13d47d9282d5358f4be0c
c5e29e341ef18c0d0eebb3d11c668d\"},{\"ID\":\"ab71bae4-50ce-5756-925d-65936c63a24f\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\de119f8ed1f53ebfc8202159bbca3a1a71fb
b33cd232cfc3ecb25ffbf5c381a8\"},{\"ID\":\"1ea652ec-4ba4-5658-a41b-4cc6b296eade\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\eb18f558cf449312a246c451788fe74fbb11ea
c69a4ed7dc31542befeadb5217\"},{\"ID\":\"0d09ef43-47eb-5b44-81fc-7e0cbbc2061b\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\7a18c5924c6c1b4cbe2b7335b8ae06015aefaa41
f7a27605b3e10166119a240c\"},{\"ID\":\"9e12e8c7-271d-5821-9d83-b51d93e351d9\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\188ca59866e5737afbbef81b81345a50716e22ebe9
7a2da5a4d7287cc0775beb\"},{\"ID\":\"55f418f4-997f-5bae-801d-e09ab20f4afb\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\9b4dee4cf97122c941f1da6f1ea7c0d4203428252b38
10ff409e6ff8071d999c\"},{\"ID\":\"5ee8879a-3fdc-5b18-b818-c3fafe86becc\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\cc48f8e3965d21e4baa33d852a4a797bcbf4541fdaf08c
ce35f2b6032d49a4dc\"},{\"ID\":\"babcef20-5ad3-57f9-bb4c-aef46389e287\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\1dcd8ed028062c6b239aa976651b78e36a16e0885e8ea298
cf7297a92e465abb\"},{\"ID\":\"26d7c380-9100-51a4-b97b-ec77096f21dd\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\bffa7978d82901bdebc950ed76223657a2510046c29230c5c1
2adc462c1b0e01\"},{\"ID\":\"1a725fd9-25ac-558b-a95f-2117df1fbc2c\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\7f05eec34a882b617ec046fd3da976e7df92f55102cae57af227
27774045e16f\"},{\"ID\":\"5a089b9e-7e78-5479-90a2-6d7588107153\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\603c87b82a185e7ac6ff73b318380d9bc9f9294a5d610a1b294c2d
e1cf488b42\"},{\"ID\":\"d1c50eb5-3054-5d60-b1e4-0a623a5d65fa\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\15814042b34aeaff6a0730316cb62ae73ff9ea52b9da60520bfb34b3
f08d9610\"},{\"ID\":\"53da5df0-ed1f-5fde-9e61-28cc6e1d6089\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\a7bd9a0ef95159f63979a0dc7af7e6180937faf2f3912a88415aabfb1b
de3b6a\"},{\"ID\":\"46f224a8-f3b8-5161-beeb-05e7d976a8e5\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\d39e2ede0cfcbb43d7faa1ae57b1d4fe40cdefc1b324a7abe34e6fc68f1d
eff7\"},{\"ID\":\"b37953f2-a6e6-5758-b1c7-e5d778c6cd78\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\56d28a079082eb4bf7a10b3f088836803ae316132d6d65a0fefb48010c5e8a
5c\"},{\"ID\":\"270ae881-6cee-559f-8989-ed5805ab3613\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\68e00948a2a815cb28adac1ad87f06dc98de224e2aea4f4c7b847e61653040a3
\"},{\"ID\":\"debc1b89-d261-5b20-ad26-07f531061eaf\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\3ae9e790800732a14a4318a16c5434bd0328619ec5e7dd00a735514044f9e9b4\"
},{\"ID\":\"bb5d54aa-d69e-5ca1-bb12-0477dde9028a\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\4a4d5a74b75224c40135f394aef9454c29843acbdc2898936df482be502a5ba2\"},
{\"ID\":\"481e777a-8886-5df4-b400-5a5f633503fc\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\11130252dbf21d562b725c71ab7231ddf591c8802a346e553d4575b6f9e4587e\"},{\
"ID\":\"4675a3e0-9689-5669-8a07-106656ab37e2\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\93fd0a759a64bc70ec96388dd25bad58763e80ebb54e424553d6e4d375ed0d6f\"},{\"I
D\":\"92b91461-c605-51d8-900b-974f84790075\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\78a18477db25977af6e5cef3335aaa729b22d9412f646488f7e7f60134f4dff7\"},{\"ID\
":\"c48c5b63-4119-5026-a45c-ee261eb2e092\",\"Path\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\1e14744cedf62ee7a22477b8b9bfcdf04c1ebde0e7309a4313bcfc20712e9e16\"}],\"Memor
yMaximumInMB\":4096,\"HostName\":\"BC\",\"MappedDirectories\":[{\"HostPath\":\"c:\\\\programdata\\\\navcontainerhelper\\\\extensions\\\\bc\\\\program files\",\"ContainerPath\":\"
c:\\\\navpfiles\",\"ReadOnly\":false,\"BandwidthMaximum\":0,\"IOPSMaximum\":0,\"CreateInUtilityVM\":false},{\"HostPath\":\"c:\\\\programdata\\\\navcontainerhelper\",\"ContainerPa
th\":\"c:\\\\programdata\\\\navcontainerhelper\",\"ReadOnly\":false,\"BandwidthMaximum\":0,\"IOPSMaximum\":0,\"CreateInUtilityVM\":false},{\"HostPath\":\"c:\\\\programdata\\\\nav
containerhelper\\\\extensions\\\\bc\\\\my\",\"ContainerPath\":\"c:\\\\run\\\\my\",\"ReadOnly\":false,\"BandwidthMaximum\":0,\"IOPSMaximum\":0,\"CreateInUtilityVM\":false}],\"HvPa
rtition\":true,\"EndpointList\":[\"afe9514a-6580-431e-ac12-eaf5779dc1ed\"],\"HvRuntime\":{\"ImagePath\":\"C:\\\\ProgramData\\\\Docker\\\\windowsfilter\\\\78a18477db25977af6e5cef3
335aaa729b22d9412f646488f7e7f60134f4dff7\\\\UtilityVM\"},\"AllowUnqualifiedDNSQuery\":true}",
            "StartedAt": "0001-01-01T00:00:00Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:e6eabf8eaea853385961624f8d3022de07317e35d778b3b4c70e6986b830d716",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d7c18be42f\\55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d
7c18be42f-json.log",
        "Name": "/BC",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\BC\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\BC\\Program Files:C:\\navpfiles"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d7c18be42f"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bc\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bc\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "BC",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "locale=de-DE",
                "useSSL=N",
                "removePasswordKeyFile=Y",
                "accept_eula=Y",
                "auth=NavUserPassword",
                "username=Administrator",
                "databaseServer=",
                "databaseInstance=",
                "enableApiServices=Y",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AEEAVQBUAHMATQB6AE8ATAByAHMAcQBzAEkAZgBIAEYASQBGAGoARQB6AHcAPQA9AHwAZgAwAGYAYwBmADUANQBiADIAYgA3ADgAZQAyAGMAZQ
A2AGYAMQAxADkANwBjADUANABiADUAYgBlADMAZQAyAGIAYQBiADUAZgA2ADkAZQBkADUAZQAzADkAMwBjADQAZAA4ADEAYgA4ADcAYgAyAGIAOQBiADAANABjAGIAOQA=",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "ExitOnError=N",
                "licenseFile=c:\\run\\my\\license.flf",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/fca3a4c6-727a-4b3d-b1b5-eb7e4c5a1378",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-0.16.26913.vsix",
                "IsBcSandbox=Y",
                "DatabaseName=FinancialsDE",
                "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/d54f9670-e084-4506-a907-71f03dc4a83b"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/bcsandbox:de",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "DE",
                "created": "201808281213",
                "cu": "",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.14393.2430",
                "tag": "0.0.6.5",
                "version": "12.3.23590.23945"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d7c18be42f",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "55a65977ee7da672b65c8fe345d7188c7a018ee4f902a9c1b35373d7c18be42f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "e3673b22fda1d26535d1030fc9b5ac631528a8e0b5086eb655d79e4931925d9c",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by freddydk** [comment]
How much memory do you have on the host?
How much is available?

**Comment by Fravid** [comment]
After closing everything I do not need, I now have more than 4 GB RAM available.
![image](https://user-images.githubusercontent.com/39947102/44836877-6a844700-ac38-11e8-96ee-f362f3287236.png)

But now I am getting new Errors:
[Error_log.txt](https://github.com/Microsoft/navcontainerhelper/files/2335130/Error_log.txt)

> d500e12bee4f173b1d6cc45aa4e1130a1573ef9c17e1da0b7211e82a25c042c5 cleanup: failed to delete container from containerd: no such container 

and 

> Handler for POST /v1.38/containers/d500e12bee4f173b1d6cc45aa4e1130a1573ef9c17e1da0b7211e82a25c042c5/start returned error: container d500e12bee4f173b1d6cc45aa4e1130a1573ef9c17e1da0b7211e82a25c042c5 encountered an error during CreateContainer: failure in a Windows system call: Anmeldung fehlgeschlagen: Der Benutzer besitzt nicht den benötigten Anmeldetyp auf diesem Computer. (0x569) extra info: {"SystemType":"Container","Name":"d500e12bee4f173b1d6cc45aa4e1130a1573ef9c17e1da0b7211e82a25c042c5","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\d500e12bee4f173b1d6cc45aa4e1130a1573ef9c17e1da0b7211e82a25c042c5","Layers":[{"ID":"866ee007-c8f1-5ebf-bb8b-00cf0efe9e93","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d36ba94a2aeca13d47d9282d5358f4be0cc5e29e341ef18c0d0eebb3d11c668d"},{"ID":"ab71bae4-50ce-5756-925d-65936c63a24f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\de119f8ed1f53ebfc8202159bbca3a1a71fbb33cd232cfc3ecb25ffbf5c381a8"},{"ID":"1ea652ec-4ba4-5658-a41b-4cc6b296eade","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eb18f558cf449312a246c451788fe74fbb11eac69a4ed7dc31542befeadb5217"},{"ID":"0d09ef43-47eb-5b44-81fc-7e0cbbc2061b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7a18c5924c6c1b4cbe2b7335b8ae06015aefaa41f7a27605b3e10166119a240c"},{"ID":"9e12e8c7-271d-5821-9d83-b51d93e351d9","Path":"C:\\ProgramData\\Docker\\windowsfilter\\188ca59866e5737afbbef81b81345a50716e22ebe97a2da5a4d7287cc0775beb"},{"ID":"55f418f4-997f-5bae-801d-e09ab20f4afb","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9b4dee4cf97122c941f1da6f1ea7c0d4203428252b3810ff409e6ff8071d999c"},{"ID":"5ee8879a-3fdc-5b18-b818-c3fafe86becc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cc48f8e3965d21e4baa33d852a4a797bcbf4541fdaf08cce35f2b6032d49a4dc"},{"ID":"babcef20-5ad3-57f9-bb4c-aef46389e287","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1dcd8ed028062c6b239aa976651b78e36a16e0885e8ea298cf7297a92e465abb"},{"ID":"26d7c380-9100-51a4-b97b-ec77096f21dd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bffa7978d82901bdebc950ed76223657a2510046c29230c5c12adc462c1b0e01"},{"ID":"1a725fd9-25ac-558b-a95f-2117df1fbc2c","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7f05eec34a882b617ec046fd3da976e7df92f55102cae57af22727774045e16f"},{"ID":"5a089b9e-7e78-5479-90a2-6d7588107153","Path":"C:\\ProgramData\\Docker\\windowsfilter\\603c87b82a185e7ac6ff73b318380d9bc9f9294a5d610a1b294c2de1cf488b42"},{"ID":"d1c50eb5-3054-5d60-b1e4-0a623a5d65fa","Path":"C:\\ProgramData\\Docker\\windowsfilter\\15814042b34aeaff6a0730316cb62ae73ff9ea52b9da60520bfb34b3f08d9610"},{"ID":"53da5df0-ed1f-5fde-9e61-28cc6e1d6089","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a7bd9a0ef95159f63979a0dc7af7e6180937faf2f3912a88415aabfb1bde3b6a"},{"ID":"46f224a8-f3b8-5161-beeb-05e7d976a8e5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d39e2ede0cfcbb43d7faa1ae57b1d4fe40cdefc1b324a7abe34e6fc68f1deff7"},{"ID":"b37953f2-a6e6-5758-b1c7-e5d778c6cd78","Path":"C:\\ProgramData\\Docker\\windowsfilter\\56d28a079082eb4bf7a10b3f088836803ae316132d6d65a0fefb48010c5e8a5c"},{"ID":"270ae881-6cee-559f-8989-ed5805ab3613","Path":"C:\\ProgramData\\Docker\\windowsfilter\\68e00948a2a815cb28adac1ad87f06dc98de224e2aea4f4c7b847e61653040a3"},{"ID":"debc1b89-d261-5b20-ad26-07f531061eaf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3ae9e790800732a14a4318a16c5434bd0328619ec5e7dd00a735514044f9e9b4"},{"ID":"bb5d54aa-d69e-5ca1-bb12-0477dde9028a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4a4d5a74b75224c40135f394aef9454c29843acbdc2898936df482be502a5ba2"},{"ID":"481e777a-8886-5df4-b400-5a5f633503fc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\11130252dbf21d562b725c71ab7231ddf591c8802a346e553d4575b6f9e4587e"},{"ID":"4675a3e0-9689-5669-8a07-106656ab37e2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\93fd0a759a64bc70ec96388dd25bad58763e80ebb54e424553d6e4d375ed0d6f"},{"ID":"92b91461-c605-51d8-900b-974f84790075","Path":"C:\\ProgramData\\Docker\\windowsfilter\\78a18477db25977af6e5cef3335aaa729b22d9412f646488f7e7f60134f4dff7"},{"ID":"c48c5b63-4119-5026-a45c-ee261eb2e092","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1e14744cedf62ee7a22477b8b9bfcdf04c1ebde0e7309a4313bcfc20712e9e16"}],"MemoryMaximumInMB":4096,"HostName":"NAV","MappedDirectories":[{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\nav\\program files","ContainerPath":"c:\\navpfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper","ContainerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\nav\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["b484d934-1841-4c87-aabc-22169319e285"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\78a18477db25977af6e5cef3335aaa729b22d9412f646488f7e7f60134f4dff7\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}

**Comment by freddydk** [comment]
You can try to run the container with --memorylimit 3G - but with 8Gb it might be hard.
You can also try to manually adjust your swap file to a larger size, but the best thing would be to install more memory.
