### ISSUE TITLE
User permission can not be set in Clean-BcContainerDatabase

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#1902]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
User permission can not be set in Clean-BcContainerDatabase

**Scripts used to create container and cause the issue**
```
Clean-BcContainerDatabase -containerName $parameters.ContainerName -useNewDatabase -credential $parameters.Credential
```

**Full output of scripts**
Stopping ServiceTier in order to replace database
Copying Database on localhost\SQLEXPRESS from CRONUS to mytempdb
Taking database CRONUS offline
Copying database files
Attaching files as new Database mytempdb
Putting database CRONUS back online
Removing Database CRONUS from localhost\SQLEXPRESS
Creating new database CRONUS on localhost\SQLEXPRESS with Collation Latin1_General_100_CS_AS
Copying table [Entitlement] from original database
Copying table [Entitlement Set] from original database
Copying table [Membership Entitlement] from original database
Removing Database mytempdb from localhost\SQLEXPRESS
Starting Service Tier
Synchronizing
Importing license file
Importing License C:\ProgramData\BcContainerHelper\Extensions\baseapp-current\my\license.flf
Creating user admin
Creating User admin
Assigning Permission Set SUPER to admin
The Aggregate Permission Set does not exist. Identification fields and values: Scope='System',App ID='{00000000-0000-0000-0000-000000000000}',Role ID='SUPER'
at <ScriptBlock>, <No file>: line 54
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at New-BcContainerBcUser<Process>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\UserHandling\New-NavContainerNavUser.ps1: line 52
at Clean-BcContainerDatabase, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Clean-BcContainerDatabase.ps1: line 173
at <ScriptBlock>, C:\vsts-agent-win-x64-2.165.2\_work\27\s\scripts\DevOps-Pipeline.ps1: line 73
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Run-AlPipeline.ps1: line 651
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Run-AlPipeline.ps1: line 593
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Run-AlPipeline.ps1: line 577
at Run-AlPipeline, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Run-AlPipeline.ps1: line 544
at <ScriptBlock>, C:\vsts-agent-win-x64-2.165.2\_work\27\s\scripts\DevOps-Pipeline.ps1: line 107
at <ScriptBlock>, C:\vsts-agent-win-x64-2.165.2\_work\_temp\339ed8ad-f5bc-4f5b-b339-ddcdf2549b69.ps1: line 3
at <ScriptBlock>, <No file>: line 1

```
BcContainerHelper is version 2.0.11
BcContainerHelper is running as administrator
Host is Microsoft  - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
ArtifactUrl is ttps://bcartifacts.azureedge.net/onprem/18.0.23013.23795/w1

```

**Additional context**
The same code was working in bc 17

**Comment by jonaswre** [comment]
If I do the clean as part of the container creatation, `New-BcContainer -useNewDatabase`, it works. But executing the Clean-BcContainerDatabase afterwards fails.

**Comment by freddydk** [comment]
I just fixed this today in the latest preview.
