### ISSUE TITLE
Error " tenant default already uses a different version of it" when run command Run-AlValidation

### ISSUE THREAD

**Issue by hgnamvn** [microsoft/navcontainerhelper#1903]
When I run the command:

_$licenseFile = "C:\VASFiles\D365BC_17_VN.flf"
$previousApp = "C:\VASFiles\DiCentral Corporation_Vietnam Localization Pack for Microsoft Business Central_15.0.35903.190901.app"
$newApp = "C:\VASFiles\DiCentral Corporation_Vietnam Localization Pack_18.0.23913.210401.app"
$country = "VN"
$prefix = "DIC"
Run-AlValidation -licenseFile $licenseFile -validateCurrent -previousApps $previousApp -apps $newApp -countries $country -affixes $prefix_

I get the Errors:
![image](https://user-images.githubusercontent.com/24407031/116367315-6cf82e00-a831-11eb-828f-fe843433f684.png)
![image](https://user-images.githubusercontent.com/24407031/116367379-7ed9d100-a831-11eb-941b-be4c17fcfea4.png)

**_Note:_**
BCcontainerhelper Version: 2.0.11
Image: mcr.microsoft.com/businesscentral:10.0.17763.437
BcArtifacts: https://bcartifacts.azureedge.net/sandbox/18.0.23013.24873/w1
BC License: BC 17 License
New App Name = Vietnam Localization Pack (BC V18) vs Vietnam Localization Pack for Microsoft Business Central (BC V15)

**Comment by freddydk** [comment]
Could you copy/paste the full output of the validation?
(not screenshots)

**Comment by hgnamvn** [comment]
Here is the log of this execution.
Please view details.
[Logs.txt](https://github.com/microsoft/navcontainerhelper/files/6396115/Logs.txt)

Note:
- Today, I run, used Artifacts: https://bcartifacts.azureedge.net/sandbox/18.0.23013.24914/w1
- If I run manually by PowerShell command, Ii is OK.

**Comment by freddydk** [comment]
It looks like the version 18 of your app has a different name than the version 15 of your app, is that true?
This is the reason for this error.
You will also not be allowed to publish an app with a different name to AppSource.

**Comment by hgnamvn** [comment]
Hi.

Because when I publish my App with version 15. The App name can greater then 50 char.
But with BC version 18. The name must be less than 50 char. So, I must to decrease the App name.

So. How to handle this issue.

**Comment by freddydk** [comment]
The app version 15 was never published to AppSource then right?

**Comment by hgnamvn** [comment]
Yes, Our App is already on AppSource now (for BC version 15) with the App name greater then 50 chars.
Now, we want to upgrade the App to Version 18

**Comment by freddydk** [comment]
You will have to change the name back to the same as in version 15.
AppSource doesn't allow you to change name and if you once was approved with 50+ characters - you will also be approved now.

**Comment by hgnamvn** [comment]
OK Thank @freddydk  for your information!

**Comment by hgnamvn** [comment]
Hi @freddydk ,

When I change App Name to origin to validate.
I get the result: 

_2 errors found in DiCentral Corporation_Vietnam Localization Pack for Microsoft Business Central_18.0.23913.210401.app on https://bcartifacts.azureedge.net/sandbox/18.0.2
3013.24873/w1:
app.json(3,5): error AS0047: The length of the extension name must not exceed 50 characters.
App generation failed with exit code 1_

Is It **OK** or **Not** ???

Full Log:
[Full.Logs.txt](https://github.com/microsoft/navcontainerhelper/files/6397022/Full.Logs.txt)

**Comment by freddydk** [comment]
I just investigated the app currently in AppSource.
the app.json looks like this:
![image](https://user-images.githubusercontent.com/10775043/116533138-4f829d00-a8e1-11eb-851b-37ad10d11758.png)
This means that your version 15 is NOT the same as the version 15 you submitted to us.
You need to validate against the last successfully validated version as previousApp.

The version of our app is the same as the version you have with the long name, which means that you must have changed name without changing version number (dangerous)

You need to keep this name: Vietnam Localization Pack and you need to validate against the right app.

**Comment by hgnamvn** [comment]
Thank @freddydk !
I will check again

**Comment by hgnamvn** [comment]
Thank @freddydk ,

I checked our App. You Right.
Now, I can run-ALValidation well. So, I would like closed this.
Thank you so much.
