### ISSUE TITLE
Get-BcContainerEventLog fails with "property not found" error

### ISSUE THREAD

**Issue by cczupras** [microsoft/navcontainerhelper#1905]
**Describe the issue**
When trying to get the eventlog from a business central docker container it fails with an error that the "HostConfig" property cannot be found

**Scripts used to create container and cause the issue**
```
New-BCContainer `
>>     -accept_eula `
>>     -containerName "BC18" `
>>     -artifactUrl (Get-BCArtifactUrl -type OnPrem -version 18 -country w1) `
>>     -auth Windows `
>>     -updateHosts `
>>     -isolation hyperv `
>>     -licenseFile "license.flf" `
>>     -memoryLimit 12G
```

**Full output of scripts**
```
BcContainerHelper is version 2.0.11
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 20.10.5
Docker Server Version is 20.10.5
...
```

**Screenshots**
![image](https://user-images.githubusercontent.com/53331359/116881274-5718ad80-ac23-11eb-887a-3f64ab2e7052.png)

**Additional context**
- does it happen all the time?
   Yes
- did it use to work?
   Yes

**Comment by freddydk** [comment]
Container names in docker are case sensitive, which is one of the reasons why my recommendation always is to use short and lower case container names (or use a variable).

**Comment by cczupras** [comment]
Shame on me you are right, I forgot all about this case sensitive. It works just fine.
