### ISSUE TITLE
Run-ALValidation -> Perform Upgrades from 17 to 18? 

### ISSUE THREAD

**Issue by MJECloud** [microsoft/navcontainerhelper#1911]
Hey Freddy, 

we try to implement the AL Validation Pipeline in our release process.
We already use the AppSourceCop during compilation, but we want to make it more robust.

Looking at the source code I see that the Pipeline can perform app upgrades, but does that include an upgrade of the base app?  

For example in our case: 
Our previous release is compatible with 17.5 but not with 18.0
How does the Validation Pipeline run the upgrade code? 
Or does it skip that then?

**Comment by freddydk** [comment]
This scenario is not handled by the validation pipeline (nor Run-AlValidation)
You should run with -skipUpgrade
In BC Saas the upgrade of your app would happen during the upgrade to 18.0

**Comment by MJECloud** [comment]
Alright, thank you! :)
