### ISSUE TITLE
Access to the path 'Microsoft.Dynamics.Nav.Client.WebCommon.resources.dll' is denied.

### ISSUE THREAD

**Issue by aaaasmile** [microsoft/navcontainerhelper#1915]
Hey Freddy,

I have a similar Problem that was handled in https://github.com/microsoft/navcontainerhelper/issues/525 but ist not the same.

I have created an artifact image and a container from this url https://bcartifacts.azureedge.net/onprem/17.5.22499.22546/de
```

$auth = "UserPassword"   
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "c:\mylic\DemDev BC 17.flf"
New-BcImage -artifactUrl https://bcartifacts.azureedge.net/onprem/17.5.22499.22546/de  -imageName imgbc175OnPremde:latest
New-BCContainer -accept_eula -accept_outdated ` -imageName "imgbc175OnPremde"  -containerName  'test02' -auth $auth  -credential $credential -licenseFile $licenseFile -updateHosts -includeAL -useCleanDatabase
```
Then I have changed the container database, installed some new  extension and finally I have commited to a new image.
So far so gut, every things works as expected (by the way thanks a lot for this amazing work!).

```
docker commit test02
docker tag <..> img02
```

Now if start this command to create a new test03 container for testing some different extensions:
`New-BCContainer -accept_eula -imageName "img02:latest" -containerName "test03" -auth $auth -Credential $Credential -updateHosts`

An error is raised during the new setup:
`Access to the path 'Microsoft.Dynamics.Nav.Client.WebCommon.resources.dll' is denied.`

I have checked the code and the error happens in SetupWebClient.ps1 when this code is called (from the navstart.ps1 Line 175):
```
Get-WebSite | Remove-WebSite
Get-WebBinding | Remove-WebBinding
```

I have found this workaround:
Remote powershell into the new fault container test03 
Call following:
```
Get-WebSite | Remove-WebSite
Get-WebBinding | Remove-WebBinding
```
and then create a new image

```
docker commit container test03 
docker tag <..> img03
```

and from this new image img03 a new container with another name is created with New-BCContainer and works as expected. 

Do I have missed something  in the process of committing an image from a container and use it as basis for a new container with a different container name?

**Comment by freddydk** [comment]
Using docker commit and docker tag isn't something I have done any work to support.
Not sure you can make that work in all cases.

**Comment by aaaasmile** [comment]
Understood thank's.
