### ISSUE TITLE
To Telemetry, or not to Telemetry, that is the question

### ISSUE THREAD

**Issue by mitrov** [microsoft/navcontainerhelper#1919]
**Describe the issue**
As an ISV publishing our app to AppSource and also to OnPrem customers, we decided to add the instrumentation key to the app.json file so that we get extension level telemetry data in our telemetry resource on Azure.  This is great as long as we have data from production environments where people actually do things and we know that the telemetry data is actually meaningful.
However, we and our partners use our app also in Docker containers for development, testing, AL validation, build pipelines, etc. And all of those containers send telemetry data to that one Azure telemetry resource. Having telemetry data from Docker containers doesn't really help us because the data in there has not much of value. There is no aad tanant id for instance.
I understand that there are scenarios where you actually want to have telemetry enabled in Docker containers for testing purposes... but I don't think it should be enabled by default, tbqh.

My questions for @freddydk :
- What is the easiest way to disable telemetry when creating new containers today?
- Could you add -DisableTelemetry to New-NavContainer.ps1?

**Comment by freddydk** [comment]
I will look into this

**Comment by RafaelKoch** [comment]
AFAIK there is no way to disable app telemetry getting emitted. 
(BTW there is also no tenant id emitted from on-premises.)
If You want the data from actual environments You can filter out any company named CRONUS. Also, make sure to filter on app versions that are actually released if You want only those.

We use telemetry from pipelines and dev/test systems extensively  - if you know how to interpret it the data allows a very good first assessment of relevant issues.

**Comment by freddydk** [comment]
There is no good way to "disable" telemetry in a container.
Only hack I can think of would be to add an entry in the hosts file, redirecting telemetry traffic to 127.0.0.1
But I don't know which hostname to redirect.

**Comment by RafaelKoch** [comment]
> thanks @RafaelKoch
> 
> > AFAIK there is no way to disable app telemetry getting emitted.
> 
> Yeah,I think it’s all or no telemetry at all per container. Which is fine.
> 
> > (BTW there is also no tenant id emitted from on-premises.)
> 
> I know. So how do you make sure that you don’t mix data from totally different onPrem installations?

Why would I care?
-> If You absolutely want isolated environment telemetry, set the entire environment to a dedicated AppInsights Instance. There You will accumulate all telemetry emitted from this environment.
-> The company name gets emitted for a great many if not all signals, Filter on that if you do not want to use multiple AppInsights instances.
-> for Extension-level telemetry: You usually want to accumulate as much data as possible to make reasonable assessment of impact.

> > We use telemetry from pipelines and dev/test systems extensively - if you know how to interpret it the data allows a very good first assessment of relevant issues.
> 
> How do you make sure you don’t mix data of individual pipeline runs / al validation/ dev / test? And can you give an example of what you are talking about?
> Thanks

Again, why would I need to? But if we must: There is always company name, extension version, ... to narrow the data down. Anything named CRONUS is definitely not production. Date combined with major/minor version of our apps can also tell, if this is run in pre-production scenarios. But... how do I care? If Telemetry shows a perf issue recurring in some app, some version, whatever environments it will warrant inspection no matter the origin. Never look at single occurrences, always look at the truly recurring things and You will automatically disregard odd things that were not structural.

**Comment by freddydk** [comment]
As this isn't something I can fix in ContainerHelper, I will close this issue.
