### ISSUE TITLE
Add /GenerateCrossReferences switch from alc.exe to Compile-AppInBcContainer 

### ISSUE THREAD

**Issue by Sven-Niehus** [microsoft/navcontainerhelper#1921]
Hi @freddydk,

could you maybe add the /GenerateCrossReferences switch from the alc.exe to the Compile-AppInBcContainer commandlet?

(Thanks @demiliani for showcasing this feature in your latest blog post!)

**Comment by freddydk** [comment]
Added it to Compile-AppInBcContainer and Run-AlPipeline.

**Comment by freddydk** [comment]
Shipped in 2.0.13
