### ISSUE TITLE
Problem with restoring database in Container

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/navcontainerhelper#1924]
I have BC18 Container (18.0.23013.23795/us). By default it uses standard CRONUS database. 
I copy another database inside container using next powershell script and then restoring it by MSSQL Management Studio:

`Copy-FileToBcContainer -localPath "c:\BC18 Stay Backup.bak" -containerName "bc18-Softera-OneSpan"`

After that I change "tenant" parameter in Visual Code in launch.json to database name and get error when trying to download 
symbols:
![image](https://user-images.githubusercontent.com/8793706/118377564-ab823c80-b5d6-11eb-9d9a-8c45b5ad89cd.png)

Also I can't use web client, it shows next error:
![image](https://user-images.githubusercontent.com/8793706/118377510-50e8e080-b5d6-11eb-8ac8-bcf1ed03f80f.png)

When I trying to create new user in power shell using next script i get error "The tenant 'newdb' is not mounted or does not exist.":

`$credentials = New-Object pscredential 'username, (ConvertTo-SecureString -String 'userpassword' -AsPlainText -Force)
New-BcContainerBcUser -Credential $credentials -assignPremiumPlan -containerName "containername" -PermissionSetId super -tenant newdb.`

**Comment by freddydk** [comment]
After restoring the database in the container, did you mount the database?
Inside the container, you would have to run 

Mount-NavDatabase

Just as you would have to do in any multitenant installation.
In PowerShell ISE you can use Enter-BcContainer to get a PowerShell prompt inside the container
Or you can use Invoke-ScriptInBcContainer

In both cases, all standard NAV/BC cmdlets are loaded for you.
