### ISSUE TITLE
Errors while creating BC18 container with test libraries.

### ISSUE THREAD

**Issue by MrPashkovskiy** [microsoft/navcontainerhelper#1925]
I create BC Container(18.0.23013.23795) with checked IncludeTestLibraries abd IncludeTestToolkit. Part of them are published with out any problems except Microsoft_Tests-TestLibraries_18.0.23013.23795.app:

`Publishing C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\2a5cd6a4-ae1d-49f4-a2b6-79d3a8ed8fa2\Microsoft_Tests-TestLibraries_18.0.23013.23795.app
Extension compilation failed
LibrarySales.Codeunit.al(719,54): error AL0185: Table 'Deposit Header' is missing
LibrarySales.Codeunit.al(815,54): error AL0185: Table 'Deposit Header' is missing
LibraryLocalFunctionality.codeunit.al(11,56): error AL0185: Table 'IRS 1099 Form-Box' is missing
LibraryLocalFunctionality.codeunit.al(25,62): error AL0185: Table 'IRS 1099 Adjustment' is missing
LibraryERM.Codeunit.al(315,54): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(323,50): error AL0185: Table 'Bank Rec. Line' is missing
LibraryERM.Codeunit.al(323,90): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(337,58): error AL0185: Table 'Bank Comment Line' is missing
LibraryERMCountryData.Codeunit.al(229,30): error AL0185: Table 'Posted Bank Rec. Header' is missing
LibraryERMCountryData.Codeunit.al(230,28): error AL0185: Table 'Posted Bank Rec. Line' is missing
LibraryERMCountryData.Codeunit.al(231,30): error AL0185: Table 'Posted Deposit Header' is missing
LibraryERMCountryData.Codeunit.al(232,28): error AL0185: Table 'Posted Deposit Line' is missing
at <ScriptBlock>, <No file>: line 18
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Publish-NavContainerApp.ps1: line 257
at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Publish-NavContainerApp.ps1: line 117
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 185
at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 153
at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\New-NavContainer.ps1: line 1843
at <ScriptBlock>, <No file>: line 1
Extension compilation failed
LibrarySales.Codeunit.al(719,54): error AL0185: Table 'Deposit Header' is missing
LibrarySales.Codeunit.al(815,54): error AL0185: Table 'Deposit Header' is missing
LibraryLocalFunctionality.codeunit.al(11,56): error AL0185: Table 'IRS 1099 Form-Box' is missing
LibraryLocalFunctionality.codeunit.al(25,62): error AL0185: Table 'IRS 1099 Adjustment' is missing
LibraryERM.Codeunit.al(315,54): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(323,50): error AL0185: Table 'Bank Rec. Line' is missing
LibraryERM.Codeunit.al(323,90): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(337,58): error AL0185: Table 'Bank Comment Line' is missing
LibraryERMCountryData.Codeunit.al(229,30): error AL0185: Table 'Posted Bank Rec. Header' is missing
LibraryERMCountryData.Codeunit.al(230,28): error AL0185: Table 'Posted Bank Rec. Line' is missing
LibraryERMCountryData.Codeunit.al(231,30): error AL0185: Table 'Posted Deposit Header' is missing
LibraryERMCountryData.Codeunit.al(232,28): error AL0185: Table 'Posted Deposit Line' is missing
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Extension compi...ine' is missing:String) [], RuntimeException
    + FullyQualifiedErrorId : Extension compilation failed
LibrarySales.Codeunit.al(719,54): error AL0185: Table 'Deposit Header' is missing
LibrarySales.Codeunit.al(815,54): error AL0185: Table 'Deposit Header' is missing
LibraryLocalFunctionality.codeunit.al(11,56): error AL0185: Table 'IRS 1099 Form-Box' is missing
LibraryLocalFunctionality.codeunit.al(25,62): error AL0185: Table 'IRS 1099 Adjustment' is missing
LibraryERM.Codeunit.al(315,54): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(323,50): error AL0185: Table 'Bank Rec. Line' is missing
LibraryERM.Codeunit.al(323,90): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(337,58): error AL0185: Table 'Bank Comment Line' is missing
LibraryERMCountryData.Codeunit.al(229,30): error AL0185: Table 'Posted Bank Rec. Header' is missing
LibraryERMCountryData.Codeunit.al(230,28): error AL0185: Table 'Posted Bank Rec. Line' is missing
LibraryERMCountryData.Codeunit.al(231,30): error AL0185: Table 'Posted Deposit Header' is missing
LibraryERMCountryData.Codeunit.al(232,28): error AL0185: Table 'Posted Deposit Line' is `missing`

**Comment by freddydk** [comment]
It would help me to get the full script and full output, thanks.

**Comment by MrPashkovskiy** [comment]
> It would help me to get the full script and full output, thanks.

Here is full log

PS C:\WINDOWS\system32> New-BcContainer -accept_eula -artifactUrl https://bcartifacts.azureedge.net/sandbox/18.0.23013.23795/us -assignPremiumPlan -auth UserPassword -bakFile "C:\BC18 Stay Backup.bak" -containerName bc18-Softera-Stay -Credential (get-credential -UserName $env:USERNAME -Message 'Using Windows Authentication. Please enter your Windows credentials.') -includeTestLibrariesOnly -licenseFile "D:\5205116 (7).flf" -shortcuts Desktop -updateHosts
WARNING: Container name should not exceed 15 characters
BcContainerHelper is version 2.0.11
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.6
Docker Server Version is 20.10.6
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.928
Creating Container bc18-Softera-Stay
Version: 18.0.23013.23795-US
Style: sandbox
Multitenant: No
Platform: 18.0.22893.23773
Generic Tag: 1.0.1.6
Container OS Version: 10.0.19042.928 (20H2)
Host OS Version: 10.0.19042.928 (20H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file D:\5205116 (7).flf
Files in C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc18-Softera-Stay from image mcr.microsoft.com/businesscentral:10.0.19042.928
dc9d4a77d25ce5741ba1c03219a93dffdb5928bfec28ee9ddb09d2b77379f0c6
Waiting for container bc18-Softera-Stay to be ready
Adding BC18-SOFTERA-ST to hosts file
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/18.0.23013.23795/us
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\18.0.23013.23795\platform\ServiceTier\Program Files
c:\dl\sandbox\18.0.23013.23795\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\18.0.23013.23795\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\18.0.23013.23795\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\sandbox\18.0.23013.23795\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\sandbox\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\sandbox\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\sandbox\18.0.23013.23795\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\sandbox\18.0.23013.23795\platform
c:\dl\sandbox\18.0.23013.23795\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\18.0.23013.23795\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\18.0.23013.23795\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\18.0.23013.23795\us\Extensions
Copying Applications
C:\dl\sandbox\18.0.23013.23795\platform\Applications
Copying Applications.US
C:\dl\sandbox\18.0.23013.23795\us\Applications.US
Installation took 79 seconds
Installation complete
Initializing...
Setting host.docker.internal to 100.100.100.127 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 100.100.100.127 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.27.112.1 in container hosts file
Starting Container
Hostname is bc18-Softera-Stay
PublicDnsName is bc18-Softera-Stay
Using NavUserPassword Authentication
Using Database .bak file 'C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\database.bak'
Using database server localhost\SQLEXPRESS
Setting CompatibilityLevel for mydatabase on localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 889D785E4C33501CA5C85CDAD52B9C38DFC2221F
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating pam as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.27.118.239
Container Hostname  : bc18-Softera-Stay
Container Dns Name  : bc18-Softera-Stay
Web Client          : http://bc18-Softera-Stay/BC/
Dev. Server         : http://bc18-Softera-Stay
Dev. ServerInstance : BC
Setting bc18-Softera-Stay to 172.27.118.239 in host hosts file

Files:
http://bc18-Softera-Stay:8080/ALLanguage.vsix

Container Total Physical Memory is 15.9Gb
Container Free Physical Memory is 5.6Gb

Initialization took 287 seconds
Ready for connections!
Reading CustomSettings.config from bc18-Softera-Stay
Creating Desktop Shortcuts for bc18-Softera-Stay
Container bc18-Softera-Stay successfully created

Use:
Get-BcContainerEventLog -containerName bc18-Softera-Stay to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bc18-Softera-Stay to get debug information about the container
Enter-BcContainer -containerName bc18-Softera-Stay to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bc18-Softera-Stay to remove the container again
docker logs bc18-Softera-Stay to retrieve information about URL's again

PS C:\WINDOWS\system32> New-BcContainer -accept_eula -artifactUrl https://bcartifacts.azureedge.net/sandbox/18.0.23013.23795/us -assignPremiumPlan -auth UserPassword -bakFile "C:\BC18 Stay Backup.bak" -containerName bc18-Softera-Stay -Credential (get-credential -UserName $env:USERNAME -Message 'Using Windows Authentication. Please enter your Windows credentials.') -databaseName bc18-cu0-Softera-Stay -includeTestLibrariesOnly -includeTestToolkit -licenseFile "D:\5205116 (7).flf" -shortcuts Desktop -updateHosts
WARNING: Container name should not exceed 15 characters
BcContainerHelper is version 2.0.11
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.6
Docker Server Version is 20.10.6
Removing container bc18-Softera-Stay
Removing bc18-Softera-Stay from container hosts file
Removing bc18-Softera-Stay-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.928
Creating Container bc18-Softera-Stay
Version: 18.0.23013.23795-US
Style: sandbox
Multitenant: No
Platform: 18.0.22893.23773
Generic Tag: 1.0.1.6
Container OS Version: 10.0.19042.928 (20H2)
Host OS Version: 10.0.19042.928 (20H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file D:\5205116 (7).flf
Files in C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc18-Softera-Stay from image mcr.microsoft.com/businesscentral:10.0.19042.928
d27c225c8393d01f944a82439789ede995fce49e2f022018cfab741696eba78e
Waiting for container bc18-Softera-Stay to be ready
Adding BC18-SOFTERA-ST to hosts file
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/18.0.23013.23795/us
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\18.0.23013.23795\platform\ServiceTier\Program Files
c:\dl\sandbox\18.0.23013.23795\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\18.0.23013.23795\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\18.0.23013.23795\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\sandbox\18.0.23013.23795\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\sandbox\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\sandbox\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\sandbox\18.0.23013.23795\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\sandbox\18.0.23013.23795\platform
c:\dl\sandbox\18.0.23013.23795\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\18.0.23013.23795\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\18.0.23013.23795\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\18.0.23013.23795\us\Extensions
Copying Applications
C:\dl\sandbox\18.0.23013.23795\platform\Applications
Copying Applications.US
C:\dl\sandbox\18.0.23013.23795\us\Applications.US
Installation took 65 seconds
Installation complete
Initializing...
Setting host.docker.internal to 100.100.100.127 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 100.100.100.127 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.27.112.1 in container hosts file
Starting Container
Hostname is bc18-Softera-Stay
PublicDnsName is bc18-Softera-Stay
Using NavUserPassword Authentication
Using Database .bak file 'C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\database.bak'
Using database server localhost\SQLEXPRESS
Setting CompatibilityLevel for mydatabase on localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint AD11E3C896911D0EC078AF8025FFFC7B0F33344C
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating pam as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.27.119.226
Container Hostname  : bc18-Softera-Stay
Container Dns Name  : bc18-Softera-Stay
Web Client          : http://bc18-Softera-Stay/BC/
Dev. Server         : http://bc18-Softera-Stay
Dev. ServerInstance : BC
Setting bc18-Softera-Stay to 172.27.119.226 in host hosts file

Files:
http://bc18-Softera-Stay:8080/ALLanguage.vsix

Container Total Physical Memory is 15.9Gb
Container Free Physical Memory is 4.7Gb

Initialization took 268 seconds
Ready for connections!
Reading CustomSettings.config from bc18-Softera-Stay
Creating Desktop Shortcuts for bc18-Softera-Stay
Synchronizing Test Runner on default
App successfully synchronized
Installing Test Runner on default
App successfully installed
Publishing C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\9282746b-ac97-4c34-a8f0-538d67489b28\Microsoft_Any_18.0.23013.23795.app
Synchronizing Any on tenant default
Installing Any on tenant default
App Microsoft_Any_18.0.23013.23795.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\57790e87-6473-487d-bcdc-791ed9a63b85\Microsoft_Library Assert_18.0.23013.23795.app
Synchronizing Library Assert on tenant default
Installing Library Assert on tenant default
App Microsoft_Library Assert_18.0.23013.23795.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\07bffc63-d771-43f9-87eb-5d68fbebb70c\Microsoft_Library Variable Storage_18.0.23013.23795.app
Synchronizing Library Variable Storage on tenant default
Installing Library Variable Storage on tenant default
App Microsoft_Library Variable Storage_18.0.23013.23795.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\e798fcbb-8e7f-45d2-9749-3bb88763bb57\Microsoft_System Application Test Library_18.0.23013.23795.app
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
App Microsoft_System Application Test Library_18.0.23013.23795.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\bc18-Softera-Stay\2a5cd6a4-ae1d-49f4-a2b6-79d3a8ed8fa2\Microsoft_Tests-TestLibraries_18.0.23013.23795.app
Extension compilation failed
LibrarySales.Codeunit.al(719,54): error AL0185: Table 'Deposit Header' is missing
LibrarySales.Codeunit.al(815,54): error AL0185: Table 'Deposit Header' is missing
LibraryLocalFunctionality.codeunit.al(11,56): error AL0185: Table 'IRS 1099 Form-Box' is missing
LibraryLocalFunctionality.codeunit.al(25,62): error AL0185: Table 'IRS 1099 Adjustment' is missing
LibraryERM.Codeunit.al(315,54): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(323,50): error AL0185: Table 'Bank Rec. Line' is missing
LibraryERM.Codeunit.al(323,90): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(337,58): error AL0185: Table 'Bank Comment Line' is missing
LibraryERMCountryData.Codeunit.al(229,30): error AL0185: Table 'Posted Bank Rec. Header' is missing
LibraryERMCountryData.Codeunit.al(230,28): error AL0185: Table 'Posted Bank Rec. Line' is missing
LibraryERMCountryData.Codeunit.al(231,30): error AL0185: Table 'Posted Deposit Header' is missing
LibraryERMCountryData.Codeunit.al(232,28): error AL0185: Table 'Posted Deposit Line' is missing
at <ScriptBlock>, <No file>: line 18
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Publish-NavContainerApp.ps1: line 257
at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Publish-NavContainerApp.ps1: line 117
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 185
at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 153
at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\New-NavContainer.ps1: line 1843
at <ScriptBlock>, <No file>: line 1
Extension compilation failed
LibrarySales.Codeunit.al(719,54): error AL0185: Table 'Deposit Header' is missing
LibrarySales.Codeunit.al(815,54): error AL0185: Table 'Deposit Header' is missing
LibraryLocalFunctionality.codeunit.al(11,56): error AL0185: Table 'IRS 1099 Form-Box' is missing
LibraryLocalFunctionality.codeunit.al(25,62): error AL0185: Table 'IRS 1099 Adjustment' is missing
LibraryERM.Codeunit.al(315,54): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(323,50): error AL0185: Table 'Bank Rec. Line' is missing
LibraryERM.Codeunit.al(323,90): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(337,58): error AL0185: Table 'Bank Comment Line' is missing
LibraryERMCountryData.Codeunit.al(229,30): error AL0185: Table 'Posted Bank Rec. Header' is missing
LibraryERMCountryData.Codeunit.al(230,28): error AL0185: Table 'Posted Bank Rec. Line' is missing
LibraryERMCountryData.Codeunit.al(231,30): error AL0185: Table 'Posted Deposit Header' is missing
LibraryERMCountryData.Codeunit.al(232,28): error AL0185: Table 'Posted Deposit Line' is missing
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Extension compi...ine' is missing:String) [], RuntimeException
    + FullyQualifiedErrorId : Extension compilation failed
LibrarySales.Codeunit.al(719,54): error AL0185: Table 'Deposit Header' is missing
LibrarySales.Codeunit.al(815,54): error AL0185: Table 'Deposit Header' is missing
LibraryLocalFunctionality.codeunit.al(11,56): error AL0185: Table 'IRS 1099 Form-Box' is missing
LibraryLocalFunctionality.codeunit.al(25,62): error AL0185: Table 'IRS 1099 Adjustment' is missing
LibraryERM.Codeunit.al(315,54): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(323,50): error AL0185: Table 'Bank Rec. Line' is missing
LibraryERM.Codeunit.al(323,90): error AL0185: Table 'Bank Rec. Header' is missing
LibraryERM.Codeunit.al(337,58): error AL0185: Table 'Bank Comment Line' is missing
LibraryERMCountryData.Codeunit.al(229,30): error AL0185: Table 'Posted Bank Rec. Header' is missing
LibraryERMCountryData.Codeunit.al(230,28): error AL0185: Table 'Posted Bank Rec. Line' is missing
LibraryERMCountryData.Codeunit.al(231,30): error AL0185: Table 'Posted Deposit Header' is missing
LibraryERMCountryData.Codeunit.al(232,28): error AL0185: Table 'Posted Deposit Line' is missing

**Comment by freddydk** [comment]
The Microsoft_Tests-TestLibraries_18.0.23013.23795.app is different on different localizations of Business Central.
You are restoring your own database, which probably comes from a different localization than the US version of the container you are spinning up - and then you are trying to install the US Test Libraries on that base app.
