### ISSUE TITLE
Not enough disc space

### ISSUE THREAD

**Issue by PleachiM** [microsoft/navcontainerhelper#1926]
Hello,
I need the database from a container which is not able to start. 
If I try to start the container it will try to run start.ps1 over and over again and I have no time to connect to my container before he restarts. So I tried to rename start.ps1 but now container is in the same state where he always tries to restart. 

Would be nice to just copy the database to not lose my setup. I can rebuild everything from scratch but I wonder if there is any solution for an "not enough space" error.

ANY idea?

**Comment by freddydk** [comment]
I haven't tried this, but if the container was started using containerhelper, then you can maybe place script called start.ps1 in the my folder on the host with this content:

. "c:\run\MainLoop.ps1"

**Comment by PleachiM** [comment]
I'm not sure but I guess I killed my container. 

`
.\Run\start.ps1 : The term '.\Run\start.ps1' is not recognized as the name of
a cmdlet, function, script file, or operable program. Check the spelling of
the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:76
+ ... e = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\Run\start.ps1
+                                                           ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\Run\start.ps1:String) [], Par
   entContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
`

**Comment by freddydk** [comment]
Did you create a start.ps1 file and place it in the my folder?
What is the full/exact content of that?

**Comment by PleachiM** [comment]
```
Param(
[switch] $installOnly,
[switch] $filesOnly,
[switch] $multitenant,
[string] $artifactUrl = "",
[switch] $includeTestToolkit,
[switch] $includeTestLibrariesOnly,
[switch] $includeTestFrameworkOnly,
[switch] $includePerformanceToolkit
)

. "c:\run\MainLoop.ps1"
```

**Comment by freddydk** [comment]
and the container is currently stopped - and when you state:

docker start bcserver

when you get the error above?

**Comment by PleachiM** [comment]
Yes thats correct. 
The container is about 5-10 seconds in the state of starting. After this he jumps to restarting. Over and over again.

**Comment by freddydk** [comment]
Strange - and if you remove the start.ps1 from the my folder you are back to out of disc space?
Maybe you can copy the database from the stopped container using docker cp ?

**Comment by PleachiM** [comment]
Removing the start.ps1 does not help. 
Can you give me a hint on how to pass the path?

docker cp bcserver:c:\databases\Demo Database NAV (11-0)_Data.mdf C:\tmp\
does not work. 

docker cp bcserver:"c:\databases\Demo Database NAV (11-0)_Data.mdf" C:\tmp\
also not working 

Haven't done this for a long time

**Comment by freddydk** [comment]
docker cp "bcserver:c:\databases\CRONUS.mdf" C:\tmp

**Comment by freddydk** [comment]
Not sure what the name of the database is - you would need to create a similar container to be sure to have the name right

**Comment by PleachiM** [comment]
That's it. 
docker cp "bcserver:c:\databases\Demo Database NAV (14-0)_Log.ldf" C:\tmp
docker cp "bcserver:c:\databases\Demo Database NAV (14-0)_Data.mdf" C:\tmp
