### ISSUE TITLE
Error create container all versions

### ISSUE THREAD

**Issue by npablo-suitech** [microsoft/navcontainerhelper#1928]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Create container using V16 and V18

**Scripts used to create container and cause the issue**
$artifactUrl = Get-BCArtifactUrl -country "es" -version 16.0.11240.12085 -type onprem
$License = "C:\Temp\License.flf"
$containerName = "prueba"
$auth = "NavUserPassword"
$params = @{ "includeAL" = $true }
$additionalParameters = @('--env RemovePasswordKeyFile=N',
'--volume C:\Temp:C:\Temp',
'--env bakfile="C:\Temp\backup.bak"')

$params += @{ "assignPremiumPlan" = $true }
$additionalParameters += @('--env CustomNavSettings=EnableTaskScheduler=true')
$credential = New-Object pscredential 'Admin', (ConvertTo-SecureString -String 'password' -AsPlainText -Force)

New-BcContainer -accept_eula -accept_outdated @params -containerName $containerName -AlwaysPull -updateHosts -auth $Auth -additionalParameters $additionalParameters -licensefile $License -doNotCheckHealth -artifactUrl $artifactUrl -Credential $Credential -dns "8.8.8.8" -isolation hyperv -imageName docker

**Full output of scripts**
BcContainerHelper is version 2.0.11
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.6
Docker Server Version is 20.10.6
Downloading application artifact /onprem/16.0.11240.12085/es
Downloading C:\Users\50009\AppData\Local\Temp\df0e09b7-7d62-46b2-8d1d-cabf4758fe74.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /onprem/16.0.11240.12085/platform
Downloading C:\Users\50009\AppData\Local\Temp\b25f1241-24bc-47b6-8219-30d688722244.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\onprem\16.0.11240.12085\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\onprem\16.0.11240.12085\platform\Prerequisite Components\Microsoft Report Viewer 2015\ReportViewer.msi
Downloading c:\bcartifacts.cache\onprem\16.0.11240.12085\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\onprem\16.0.11240.12085\platform\Prerequisite Components\Microsoft Report Viewer 2015\SQLSysClrTypes.msi
Downloading c:\bcartifacts.cache\onprem\16.0.11240.12085\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Fetching all docker images
Building image docker:onprem-16.0.11240.12085-es based on mcr.microsoft.com/businesscentral:10.0.19042.985 with https://bcartifacts.azureedge.net/onprem
/16.0.11240.12085/es
Pulling latest image mcr.microsoft.com/businesscentral:10.0.19042.985
10.0.19042.985: Pulling from businesscentral
18ae6bebe21d: Pulling fs layer
182d4887a30d: Pulling fs layer
3a5d5a57b789: Pulling fs layer
61324dd37327: Pulling fs layer
6262fe3a8971: Pulling fs layer
3a9b71ceeafb: Pulling fs layer
3d65d011d7f7: Pulling fs layer
9352475eea8b: Pulling fs layer
61a1bcdd232e: Pulling fs layer
f0092d7fa678: Pulling fs layer
3d35a685094b: Pulling fs layer
bdcee482a3dd: Pulling fs layer
61324dd37327: Waiting
6262fe3a8971: Waiting
2f3f94f9fa53: Pulling fs layer
3a9b71ceeafb: Waiting
b967dbda482c: Pulling fs layer
63cdd1cc770c: Pulling fs layer
9352475eea8b: Waiting
61a1bcdd232e: Waiting
f0092d7fa678: Waiting
3d35a685094b: Waiting
bdcee482a3dd: Waiting
2f3f94f9fa53: Waiting
b967dbda482c: Waiting
63cdd1cc770c: Waiting
3d65d011d7f7: Waiting
3a5d5a57b789: Verifying Checksum
3a5d5a57b789: Download complete
61324dd37327: Verifying Checksum
61324dd37327: Download complete
6262fe3a8971: Verifying Checksum
6262fe3a8971: Download complete
3a9b71ceeafb: Verifying Checksum
3a9b71ceeafb: Download complete
3d65d011d7f7: Verifying Checksum
3d65d011d7f7: Download complete
9352475eea8b: Verifying Checksum
9352475eea8b: Download complete
182d4887a30d: Verifying Checksum
182d4887a30d: Download complete
61a1bcdd232e: Verifying Checksum
61a1bcdd232e: Download complete
f0092d7fa678: Download complete
bdcee482a3dd: Verifying Checksum
bdcee482a3dd: Download complete
2f3f94f9fa53: Verifying Checksum
2f3f94f9fa53: Download complete
b967dbda482c: Verifying Checksum
b967dbda482c: Download complete
63cdd1cc770c: Verifying Checksum
63cdd1cc770c: Download complete
18ae6bebe21d: Verifying Checksum
18ae6bebe21d: Download complete
3d35a685094b: Verifying Checksum
3d35a685094b: Download complete
18ae6bebe21d: Pull complete
182d4887a30d: Pull complete
3a5d5a57b789: Pull complete
61324dd37327: Pull complete
6262fe3a8971: Pull complete
3a9b71ceeafb: Pull complete
3d65d011d7f7: Pull complete
9352475eea8b: Pull complete
61a1bcdd232e: Pull complete
f0092d7fa678: Pull complete
3d35a685094b: Pull complete
bdcee482a3dd: Pull complete
2f3f94f9fa53: Pull complete
b967dbda482c: Pull complete
63cdd1cc770c: Pull complete
Digest: sha256:15f621c991fd2c908bda9b692661c169cf511b64bad2ecd8aa510b24ccabbcf7
Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.19042.985
mcr.microsoft.com/businesscentral:10.0.19042.985
Generic Tag: 1.0.1.6
Container OS Version: 10.0.19042.985 (20H2)
Host OS Version: 10.0.19042.985 (20H2)
Using hyperv isolation
Using license file C:\Suitech\License.flf
Files in c:\bcartifacts.cache\tfa3lu4e.rbk\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying Installers
Copying Applications
c:\bcartifacts.cache\tfa3lu4e.rbk
Sending build context to Docker daemon   1.36GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.19042.985
 ---> f8ab88dcad11
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onpr
em/16.0.11240.12085/es filesOnly=False
 ---> Running in cc215c1075d1
Removing intermediate container cc215c1075d1
 ---> 690489e80720
Step 3/6 : COPY my /run/
 ---> 36edd4a7186c
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 980cddf2d256
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in 61091f32d57f
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation
Changing Database Server Collation to Modern_Spanish_100_CI_AS
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
C:\NAVDVD\WebClient\Microsoft Dynamics NAV
Copying Client Files
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\systemFolder
Copying ModernDev Files
C:\NAVDVD
C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\NAVDVD\ConfigurationPackages
Copying Test Assemblies
C:\NAVDVD\Test Assemblies
Copying Applications
C:\NAVDVD\Applications
Starting Business Central Service Tier
Importing CRONUS license file
Stopping Business Central Service Tier
Installation took 133 seconds
Installation complete
Removing intermediate container 61091f32d57f
 ---> aa01353f1046
Step 6/6 : LABEL legal="http://go.microsoft.com/fwlink/?LinkId=837447"       created="202105171019"       nav="2004"       cu="rtm"       country="es"  
     version="16.0.11240.12085"       platform="16.0.11233.12078"
 ---> Running in 9798d7e827d8
Removing intermediate container 9798d7e827d8
 ---> bd6067faddbf
Successfully built bd6067faddbf
Successfully tagged docker:onprem-16.0.11240.12085-es
docker : 
En C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\New-NavImage.ps1: 540 Carácter: 1
+ docker build --isolation=$isolation --memory $memory --tag $imageName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Additional context**
It happens in all versions, I have tested with 16 and with 18.

**Comment by freddydk** [comment]
What happens if you remove the -imageName parameter?

**Comment by npablo-suitech** [comment]
Works!!! Why?

**Comment by freddydk** [comment]
It looks like creating the image is causing the problem.
Not sure why, but I had a similar problem on a computer last week.
Will use this issue to remember/fix the issue.

**Comment by freddydk** [comment]
Apparently Docker Built has started to throw an exception when used in PowerShell (even though nothing is wrong).
Created a workaround hack in ContainerHelper and will investigate further.

**Comment by freddydk** [comment]
Shipped in 2.0.12
