### ISSUE TITLE
Add -DoNotSaveData to UnInstall-NavContainerApp

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#193]
Hi Freddy, 
Can you add -DoNotSaveData parameter to [UnInstall-NavContainerApp](https://github.com/Microsoft/navcontainerhelper/blob/master/AppHandling/UnInstall-NavContainerApp.ps1) function?

This could be very useful in the app installation logic development process.

**Comment by freddydk** [comment]
Will be included in the next version

**Comment by freddydk** [comment]
Shipped in 0.3.1.3
