### ISSUE TITLE
Error creating a docker container with external database with BCContainerHelper 2.0.11 / 2.0.12

### ISSUE THREAD

**Issue by RaKuNbg** [microsoft/navcontainerhelper#1930]
I get this error message when I try to setup a new container with BCContainerHelper 2.0.11 or 2.0.12

![image](https://user-images.githubusercontent.com/46022628/118626088-d92fd700-b7ca-11eb-9b63-711da9e8c583.png)

The script I used:

Set-ExecutionPolicy unrestricted -Scope CurrentUser

#please change
$artifactUrl = Get-BCArtifactUrl -version 17.4 -select Latest -country de -type OnPrem
$gitSourceFolder = "F:\_git\KatarGoCore"
$containerName = "KatarGo18Core"
$License = "D:\Download\Lizenzen\license.flf" 
$AddInsPath = Join-Path $gitSourceFolder 'KatarGo\.netPackages' 
$AppsPath = Join-Path $gitSourceFolder '.AppPackagesContent' 
$memoryLimit = "8G"
$navUser = "XXX"
$navPwd = "YYY"
$databaseServer = "host.docker.internal"
$databaseName = "KatarGo18-REL"
$sqluser = "AAA"
$sqlPwd = "AAA"

#do not change
$navCredentials = New-Object System.Management.Automation.PSCredential -ArgumentList $navUser, ($navPwd | ConvertTo-SecureString -AsPlainText -Force)
$sqlCredential = New-Object System.Management.Automation.PSCredential -argumentList $sqluser, ($sqlPwd | ConvertTo-SecureString -AsPlainText -Force)
$additionalPars = @('--volume "' + $addInsPath + ':c:\run\Add-Ins"')

New-BCContainer -accept_eula -accept_outdated -artifactUrl $artifactUrl -containerName $containerName `
                -auth NavUserPassword -Credential $navCredentials -memoryLimit $memoryLimit -shortcuts DesktopFolder `
                -databaseServer 'host.docker.internal' -databaseCredential $sqlCredential -databaseName $databaseName `
                -updateHosts -licenseFile $License -alwaysPull -includeAL -doNotExportObjectsToText -additionalParameters $additionalPars

New-BCContainerBCUser -containerName $containerName -Credential $navCredentials -ChangePasswordAtNextLogOn $false -ErrorAction SilentlyContinue

**Full output of scripts**
I don't have the full output in the moment.
After some tries I uninstalled the current version and installed old version 2.0.5 (that I had before).
==> With this old version I was able to create the container without any problems.
If you need the complete output, I have to switch back to version 2.0.12 and destroy again my container (which I would not do if not absolutely neccessary because I already spent half a day looking for the cause of the problem).

**Comment by freddydk** [comment]
With 2.0.12 - you can try to set

$bcContainerHelperConfig.useSharedEncryptionKeys = $false
(or set this in the config file)

Before introducing this functionality, I had a lot of people having issues when creating two containers connecting to the same database server due to encryption key problems.

**Comment by freddydk** [comment]
Please reopen with more info if the problem persists.
