### ISSUE TITLE
API Access of Cloud Sandbox doesn't work: Web service call failed because user could not be authenticated or authorized.

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#1936]
**Describe the issue**
When I try to access the API with username and password or username and webservice api key of the created container (https://dockerhub.somecompany.com/test-bc18-1rest/api/v2.0), I get the error message **Webservice call failed because user could not be authenticated or authorized**.

With the OnPrem container of BC16, 17 and 18 API Access works with username and password. 

**Scripts used to create container and cause the issue**
```
New-NavContainer `
-accept_eula `
-alwaysPull `
-addFontsFromPath C:\Windows\Fonts `
-updateHosts `
-containername test-bc18-1 `
-artifactUrl "https://bcartifacts.azureedge.net/sandbox/18.1.24822.26020/de" `
-PublicDnsName dockerhub.somecompany.com `
-useSSL `
-useTraefik `
-shortcuts None `
-auth NavUserPassword `
-Credential $credential `
-licenseFile "C:\ProgramData\company\dockerLicenseFiles\2021-04-06_company_BC.flf"
```

**Full Error Message**
```json
{
    "error": {
        "code": "Authentication_InvalidCredentials",
        "message": "Web service call failed because user could not be authenticated or authorized.  CorrelationId:  4d6d8587-8948-466a-a5b6-3c5ffbb8285c."
    }
}
...
```

**Comment by freddydk** [comment]
Does it work without traefik?

**Comment by DanielGoehler** [comment]
No, but while testing without traefik I found out that I also have to name the tenant. https://dockerhub.somecompany.com/test-bc18-1rest/api/v2.0?tenant=default works.
