### ISSUE TITLE
Suggestion: Include Tenantname in the URL Schema

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#1937]
**Describe the issue**
It would be nice if the tenant name - currently appended with ?tenant=default - would be part of the URI scheme, as in the Cloud Environments:

|Old|New|
|-|-|
|https://dockerhub.somecompany.com/test-bc18-1/?tenant=default|https://dockerhub.somecompany.com/test-bc18-1/default|
|https://dockerhub.somecompany.com:443/test-bc18-1soap?tenant=default|https://dockerhub.somecompany.com/test-bc18-1soap/default/|
|https://dockerhub.somecompany.com:443/test-bc18-1rest/odatav4?tenant=default|https://dockerhub.somecompany.com:443/test-bc18-1rest/default/odatav4/|
|https://dockerhub.somecompany.com:443/test-bc18-1rest/api?tenant=default|https://dockerhub.somecompany.com:443/test-bc18-1rest/default/api/|

**Comment by DanielGoehler** [comment]
With traefik?

**Comment by freddydk** [comment]
I don't know if traefik would be able to do that.

**Comment by DanielGoehler** [comment]
To bad, thanks.
