### ISSUE TITLE
The requested resource is in use

### ISSUE THREAD

**Issue by bluehenve** [microsoft/navcontainerhelper#1945]
**Describe the issue**
Business Central ran as a dream at my first attempt with Docker.
But now I keep getting 'The requested resource is in use'.

**Scripts used to create container and cause the issue**
docker run --name hvBC -e accept_eula=Y -m 4G -e artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us mcr.microsoft.com/businesscentral:10.0.19041.928

**Full output of scripts**
PS C:\Users\HenrikVestergaard> docker run --name hvBC -e accept_eula=Y -m 4G -e artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us mcr.microsoft.com/businesscentral:10.0.19041.928
Unable to find image 'mcr.microsoft.com/businesscentral:10.0.19041.928' locally
10.0.19041.928: Pulling from businesscentral
295f12394c4f: Pull complete
2d44bfce6197: Pull complete
139497e00fa9: Pull complete
cce5d28dbbe0: Pull complete
48d27b5fb124: Pull complete
58d4ad761f39: Pull complete
ddcee573fef9: Pull complete
2757c90676c0: Pull complete
0d70e0b2e5f8: Pull complete
828ae02ca5b9: Pull complete
6ae1febacfae: Pull complete
de4a9854c853: Pull complete
39b0fd06e13c: Pull complete
09b21f74a2e9: Pull complete
dd09aa96b8fd: Pull complete
4b7f296bd2b0: Pull complete
9a2d98be0721: Pull complete
57f22c35dc03: Pull complete
497650f73e73: Pull complete
e193283e720e: Pull complete
Digest: sha256:e1385ba19023b8da52ca7f3c542506b9bddd6dd1a0314bba88bd074301e703fe
Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.19041.928
docker: Error response from daemon: hcsshim::CreateComputeSystem dfcf742e71bfeda8892ce3f89bb841f1837f05911dc84ed6ee00a6fce485a81a: The requested resource is in use.
(extra info: {"SystemType":"Container","Name":"dfcf742e71bfeda8892ce3f89bb841f1837f05911dc84ed6ee00a6fce485a81a","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\dfcf742e71bfeda8892ce3f89bb841f1837f05911dc84ed6ee00a6fce485a81a","Layers":[{"ID":"583aad51-30d5-5758-b3ce-80162a6a7863","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0867d743b07d8224107160683febeac6f6116dc974318ce27fabd828fac8d0a7"},{"ID":"2c47a0c4-73f5-53d4-9222-1990276d673b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7f29879d4f6d3a880555feceef5abd93e8441e8c977b1192ff6177c443121b54"},{"ID":"93e9397b-e023-5513-9cc2-b2666a4ec7e4","Path":"C:\\ProgramData\\Docker\\windowsfilter\\70264212ed1a8edddbb77a0224bd05f14ef80eff8417b9f4aa30b2c9a6d1e199"},{"ID":"11b70ee0-bb6b-506b-be6a-ccab8245481f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c8074859f86a0f43170b17e5cda8b4b01f3abbcab16c51da3a7ec050bb9cb89e"},{"ID":"f04b9a07-4b49-55c4-a38d-7d2500d0b7bf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cf0b21943d4df554082b6009aa1d6146774009683a2e2a045f7409a006a0a3bb"},{"ID":"059bccfb-cbdb-54ba-afe1-0d64baf18631","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c455f7d599ebc42ac71df3aded4abb09d3bc9af65aebae1ece8b1548bda02f5b"},{"ID":"897a15d1-8fec-5073-a118-274be8f27fc7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\358f8306e35d818557c01398be7f221a50239004915009559b53ff1ab85fee8b"},{"ID":"2384d8ae-c285-59f7-95f1-4948175d529e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0e365cb242a61f6bc6feef49be094a1866ee2fee5b472955bcfb6b7b9fec1df2"},{"ID":"a5c5672c-8169-5f87-9c55-4cbab00f8bd6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ab2a6d830bb35c24fe62b1542f2ec65ec3e5ebab66586a8d72a0e458511e0b76"},{"ID":"59b37d02-1745-5ac6-818c-6c438c646934","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e17eafd93c81f42cad5e01ea247eea91ba272d5a791e2e74f608695b2ba54a90"},{"ID":"8b216983-60b3-5b20-8e6d-f0b18b546d3a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\16320021843c6fdbdab68cde07f52c7210c199db4e6c6654cad0d447824bb233"},{"ID":"f9b1f4b5-b4df-5526-ba72-dc197730a897","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8d0fb7c10a9dddec22c536c79c1566b5abb8c292987e5e1b4a32cd9d26a02896"},{"ID":"45e23829-dce2-517d-9e12-dee28e4f1493","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cf034cc2840cead1405ab7c246798e3714e4e99151ec8ba1db83ef1f036ec7f0"},{"ID":"e28e174a-8af9-5b21-b1c1-8e1628ee62ba","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9ba95dc76d6114a562b4a42418ea1d2c6d9d528c5f686ccadaf6fc79928c3a3b"},{"ID":"159e0a00-d5ca-56e0-a512-9992b9ce0e11","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c70efcab2722277b95be91e38e6531cbb1645fadbcb31e0c6eae05cc4976d8ed"},{"ID":"2e792cee-5162-5b03-99c9-83afb8aff131","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2ee130ddca32b0937c93a6fae7fb2f334f8712450045309a91eec33b6290c253"},{"ID":"2e597440-e644-55e2-ac7d-124f25a4d8ca","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fdd054e7064cc02356ce88542eba6234dbcfdcf66d387c8dfb5bd8cc004a16ef"},{"ID":"66968d5f-a913-5c79-b181-408d8ef52a04","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d93e6ebea0575119264772f926d534e434afa5d834955f7df651f7dcab362b8d"},{"ID":"965a79af-af7d-5a38-8083-1da7777e15c0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dfe1d210594bdd53d09fb40ad45c944b2d66bb8e2ca43a50e10d70bc348c82a1"},{"ID":"8aa8c61d-51be-5f4d-968f-891fb096393a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c190fd35c0860626ae8ec818361f2d67010c282457cfa979ae9bcc4388114046"}],"MemoryMaximumInMB":4096,"HostName":"dfcf742e71bf","HvPartition":true,"EndpointList":["b2a09b11-bbb3-40e6-b3e5-3c7cb013ba79"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\dfe1d210594bdd53d09fb40ad45c944b2d66bb8e2ca43a50e10d70bc348c82a1\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).
PS C:\Users\HenrikVestergaard>

**Screenshots**
I made this note 02-05-2021 when it started with succes:
PowerShell 7.1.3
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\HenrikVestergaard> docker images
REPOSITORY                          TAG              IMAGE ID       CREATED       SIZE
mcr.microsoft.com/businesscentral   10.0.19042.928   0ba97ff6bd58   11 days ago   8.39GB

PS C:\Users\HenrikVestergaard> docker run -e accept_eula=Y -m 4G -e artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us mcr.microsoft.com/businesscentral:10.0.19042.928

Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us
	Downloading application artifact /onprem/17.0.16993.0/us
	Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\ada01b06-9806-44d5-b94b-ddf6fd368419.zip
	Unpacking application artifact
	Downloading platform artifact /onprem/17.0.16993.0/platform
	Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\df51a0b2-45a7-45ee-a644-ebe2eaa90b50.zip
	Unpacking platform artifact
	Downloading Prerequisite Components
	Downloading c:\dl\onprem\17.0.16993.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
	Downloading c:\dl\onprem\17.0.16993.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
	Downloading c:\dl\onprem\17.0.16993.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
	Using installer from C:\Run\150-new
Installing Business Central
	Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
	c:\dl\onprem\17.0.16993.0\platform\ServiceTier\Program Files
	c:\dl\onprem\17.0.16993.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
	c:\dl\onprem\17.0.16993.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
	c:\dl\onprem\17.0.16993.0\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\17.0.16993.0\us\database\Demo Database NAV (17-0).bak
	Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
	Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
	c:\dl\onprem\17.0.16993.0\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
	c:\dl\onprem\17.0.16993.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
	c:\dl\onprem\17.0.16993.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
	c:\dl\onprem\17.0.16993.0\platform\LegacyDlls\systemFolder
Copying ModernDev Files
	c:\dl\onprem\17.0.16993.0\platform
	c:\dl\onprem\17.0.16993.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
	C:\dl\onprem\17.0.16993.0\us\ConfigurationPackages
Copying Test Assemblies
	C:\dl\onprem\17.0.16993.0\platform\Test Assemblies
Copying Applications
	C:\dl\onprem\17.0.16993.0\us\Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier

Installation took 125 seconds
Installation complete

Initializing…
Starting Container
Hostname is 8a3e0979187f
PublicDnsName is 8a3e0979187f
WARNING: Container starts with TimeZone = Rom, normaltid, which is not recognized in the list of TimeZones.

Using NavUserPassword Authentication
	Creating Self Signed Certificate
	Self Signed Certificate Thumbprint 0A16D1B02B4DB506E78BD2A80B590CE900A1231F  
Modifying Service Tier Config File with Instance Specific Settings
	Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
	Creating admin as SQL User and add to sysadmin
	Creating SUPER user
Container IP Address: 172.17.211.183
Container Hostname  : 8a3e0979187f
Container Dns Name  : 8a3e0979187f
Web Client          :    https://46806b9fe393/BC/
Admin Username      : admin
Admin Password      :  xxxxxxxx
Dev. Server         : https://603766831f4c/BC/
Dev. ServerInstance : BC

Files:
http://8a3e0979187f:8080/ALLanguage.vsix
http://603766831f4c:8080/certificate.cer

Container Total Physical Memory is 4.5Gb
Container Free Physical Memory is 1.7Gb

Initialization took 37 seconds
Ready for connections!
Starting EventLog Monitor
Monitoring EventSources from EventLog[Application]:
- MicrosoftDynamicsNAVClientClientService
- MicrosoftDynamicsNAVClientWebClient
- MicrosoftDynamicsNavServer$BC
- MSSQL$SQLEXPRESS

**Additional context**
- does it happen all the time?
	Yes
- did it use to work?
	Yes

**Comment by bluehenve** [comment]
I just tried 19042, which work for me 02-05-2021, but it gives the same error, se attatched
![run 19042](https://user-images.githubusercontent.com/70111241/120099838-fe630480-c13d-11eb-8fa8-d75be13a511e.png)
![download 19042](https://user-images.githubusercontent.com/70111241/120099840-00c55e80-c13e-11eb-9af6-2fae59eac93f.png)

**Comment by freddydk** [comment]
The image that works for me on 21H1 is 10.0.19041.985
Hoping that 19043 will be released soon

**Comment by bluehenve** [comment]
Alas, same error:

PS C:\Users\HenrikVestergaard> docker run --name hvBC2 -e accept_eula=Y -m 4G -e artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us mcr.microsoft.com/businesscentral:10.0.19041.985
docker: Error response from daemon: hcsshim::CreateComputeSystem 5074554a42af54bb7de713b4e84ccc314beb13280736ab25fbb5309567aba25b: The requested resource is in use.
(extra info: {"SystemType":"Container","Name":"5074554a42af54bb7de713b4e84ccc314beb13280736ab25fbb5309567aba25b","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\5074554a42af54bb7de713b4e84ccc314beb13280736ab25fbb5309567aba25b","Layers":[{"ID":"e4e8b0a5-46dd-5638-afa7-18592edf47d6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e9c49713758a8d2d18fee9cebc72b4c9d0bbc15cf0e328fdfc42a754b4fe169c"},{"ID":"102bfb6a-9099-5e6f-87f5-98f1509b6ab1","Path":"C:\\ProgramData\\Docker\\windowsfilter\\63af476b60fec7181d935f49fc8c4f4289c92829b6e89239634cb3453fe7515d"},{"ID":"b320d55f-f6a2-512c-90e9-d7251331c18b","Path":"C:\\ProgramData\\Docker\\windowsfilter\\59c037f43c6f349fd6c1b3f23c16720afc39283127b0878e80a73a4bddbdb5ff"},{"ID":"fe8c7bee-2f9e-534b-b909-d3facfac0b23","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cfb280597ce28f689052255a5edf124f5b626df57c6826b138ea711e3b14528e"},{"ID":"05bbe0c0-1bc2-52dd-927b-32b58137af77","Path":"C:\\ProgramData\\Docker\\windowsfilter\\30e4c2a6e68478379c5b1787e88f8e45955c8229f4dd984bbed7e3eb4558d7a2"},{"ID":"8a5610eb-4ac0-5dc7-99be-b584e0277cbc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\21c77d000d548d76ae2061580e2b73596142ad78b76da23799d43eed9bef150f"},{"ID":"8cb054fe-4d05-51ac-aea6-4d4f34805fb5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\35c9b179adfb444a9a08249f4e3ea19eed776ff535f9df47e8b2130aa8d25c6a"},{"ID":"a3b01feb-e971-5a4d-8792-da8af9617a10","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7b02b06234c4eccf79bc988b53dc5896c15a08c4fe43acff83e2629b98303c54"},{"ID":"029b9007-4774-5d36-a97e-a8ad3193b791","Path":"C:\\ProgramData\\Docker\\windowsfilter\\05dcf16c65433fe9f010b9c818abcaee1748d7609374a0e7535a7697e09d9a30"},{"ID":"4277eda5-e34a-5ad8-ae16-fb28f7050aa7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cc675fc33527941f74a0764e7bb54a3e45c4a246c1238caf9b38a9956caaeed8"},{"ID":"27a1cdd3-7082-591f-ae72-ad19cf91b40d","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ccc2ea2b57da489c903309554dd0231c2d3692d070b5ae3d395d39691d0f33ce"},{"ID":"9556cf1d-547f-586b-a65d-838ba67bb925","Path":"C:\\ProgramData\\Docker\\windowsfilter\\525cbe6cf8768a55c9406edcc7694fcde39d44e609defc63a19ffa27bf4bc0d8"},{"ID":"d4063a42-02c7-5ae5-97d5-b2793b596dc5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6a7d9f7cd4a97e9fe3c4778e859788d40d79536b8a5fa8a2a3f9c7329cd91b0b"},{"ID":"07825ae9-b62d-5b64-9a65-250984f8d6de","Path":"C:\\ProgramData\\Docker\\windowsfilter\\2729b8f41b02ffe4578093d6ac36fabc7e02ab3b7be6a3d6e40fcbe51962889d"},{"ID":"cf5ec331-8543-51c8-9e85-451950db0627","Path":"C:\\ProgramData\\Docker\\windowsfilter\\fa37931e68aa3d2accf95d320cce6df38723e5bdac99f53619c7228fe1daf071"},{"ID":"1247ead1-37f0-5ca0-ae74-41b90c92aa0f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\54e044bf94846da1e31c7ee16683116a5c2251b159512a209eb282d90860f538"},{"ID":"47ea26e6-61ea-5e25-bd0d-d2fb70304b3a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\3cfb6753177bdfa2405a22b35b89d4489cb511eeb147cdf2a9d6201fe21ff8a3"},{"ID":"2a9f753c-6a76-5591-9b94-9d61b8a99a83","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bfa7fb9dd3f050acc46f4e86f5e0df08114e2eda5ce60925917b9728d080d93c"}],"MemoryMaximumInMB":4096,"HostName":"5074554a42af","HvPartition":true,"EndpointList":["492141a2-8ff7-4df5-9844-e91b73d301e1"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\3cfb6753177bdfa2405a22b35b89d4489cb511eeb147cdf2a9d6201fe21ff8a3\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).

**Comment by freddydk** [comment]
with that one - try to use:

```
docker run --name hvBC2 -e accept_eula=Y --isolation process -m 4G -e artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us mcr.microsoft.com/businesscentral:10.0.19041.985
```

**Comment by bluehenve** [comment]
YES Freddiy  - SUCCES :o)
Thanks, Henrik

**Comment by freddydk** [comment]
Hope that the 21H1 image ships soon so that we can avoid these problems

**Comment by KristofKlein** [comment]
Hi Freddy, hope you are doing well,

I'm sorry to reopen this. But we see the same error (docker run ExitCode 125 - "The requested resource is in use") on a 2004 - 19041.867 host now as well. It uses -correctly - the image 10.0.19041.867. 
BcContainerHelper is 2.0.13
Using HyperV (no way for us to use isolation)

to avoid other influencer we docker ci-zap now that machine to see if it helps.
But If you have another idea, that would be great :)

**Comment by KristofKlein** [comment]
and just after I wrote to you the dev said it is working now .... case closed :D
