### ISSUE TITLE
TestToolkitToNavContainer error

### ISSUE THREAD

**Issue by martinhocosta88** [Microsoft/navcontainerhelper#195]
I'm having this error on running TestToolkitToNavContainer:

```
Cannot find path 'C:\TestToolKit' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.9.2\ObjectHandling\Import-TestToolkitToNavContainer.ps1:24 char:5
+     Invoke-Command -Session $session -ScriptBlock { Param($sqlCredent ...
    + CategoryInfo          : ObjectNotFound: (C:\TestToolKit:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
    + PSComputerName        : 04fd696a97f7c5334f3774a228c9ad21bb73606e1dbaafa5c653a1d77e077147
```

Having the same error when creating the container with the parameter to create the testtoolkit.
Any clue?

**Comment by freddydk** [comment]
Some of the countries do not have the testtoolkit included. Will be fixed this week.
If you need it now - you would need to create a w1 container and copy the testtoolkit from that.

**Comment by rkirsten** [comment]
Not sure if I should open a new issue, but also have trouble importing the module TestToolkitToNavContainer. Any idea?

`PS C:\develop\business-central\nav-docker-environment\microsoft-navcontainerhelper> Import-TestToolkitToNavContainer -containerName businesscentral
Vom Hintergrundvorgang wurde ein Fehler mit der folgenden Meldung ausgegeben: "Der Named Pipe-Zielprozess wurde beendet.".
In C:\develop\business-central\nav-docker-environment\microsoft-navcontainerhelper\ContainerHandling\Get-NavContainerSession.ps1:38 Zeichen:13
+             Invoke-Command -Session $session -ScriptBlock { Param([bo ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (7d56607b2654197...a930b58ce2d2b7b:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : 7d56607b2654197026c1111777d07351282d81bf746b4a618a930b58ce2d2b7b`

**Comment by freddydk** [comment]
It's a different error.
Is your container running? can you access Web Client etc?
If it is what command did you use to start the container?

**Comment by rkirsten** [comment]
The container is running, web client is accessible and running correctly. Not quite sure about the command, but should be this:

`New-NavContainer -accept_eula `
        -containerName $($SetupSettings.instance.name) `
        -imageName $($SetupSettings.docker.image) `
        -licenseFile $($SetupSettings.instance.licenseFile) `
        -memoryLimit 4G `
        -includeCSide `
        -doNotExportObjectsToText `
        -Credential $hostCredentials `
        -alwaysPull `
        -updateHosts `
        -auth 'NavUserPassword' `
        -additionalParameters $additionalParameters `
        -myScripts $myScripts `
        -databaseServer $databaseServer `
        -databaseName $databaseName `
        -databaseCredential $databaseCredentials`

I just added the '-includeTestToolkit' to that and got the following error:

`Nav container businesscentral successfully created
-includeTestToolkit : Die Benennung "-includeTestToolkit" wurde nicht als Name eines Cmdlet, einer Funktion, einer
Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens, oder ob der Pfad
korrekt ist (sofern enthalten), und wiederholen Sie den Vorgang.
In C:\develop\business-central\nav-docker-environment\n4-nav-docker-environment\docker\New-DockerContainerN4.ps1:90
Zeichen:9
+         -includeTestToolkit
+         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (-includeTestToolkit:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException`

**Comment by freddydk** [comment]
That error is because you put that on a seperate line without specifying that the previous line continues on the next line.
You need to put a ` after the previous line (standard PowerShell)

**Comment by freddydk** [comment]
I see what is happening now.
The includeTestToolkit flag doesn't take into account that you are connecting to a foreign database.
You can fix this by not specifying -IncludeTestToolkit and instead use
Import-TestToolkitToNavContainer -containername test -sqlCredential $databaseCredential
After you have created the container.
That should work.

**Comment by rkirsten** [comment]
> The includeTestToolkit flag doesn't take into account that you are connecting to a foreign database.

In fact it did, I assume. Your first hint worked (missing `). I still needed to download symbols again to avoid the "Abiguous object reference" error. Now it works fine and I can run my tests.
Many thanks!

**Comment by freddydk** [comment]
That is strange. The code looked like this:

```
    $sqlCredential = $null
    if ($auth -eq "NavUserPassword") {
        $sqlCredential = New-Object System.Management.Automation.PSCredential ('sa', $credential.Password)
    }

    if ($includeTestToolkit) {
        Import-TestToolkitToNavContainer -containerName $containerName -sqlCredential $sqlCredential -includeTestLibrariesOnly:$includeTestLibrariesOnly
    }

```
Which clearly indicates, the if your Sql credentials are different from the container credentials - it won't work. So you must have used the same password and be in luck.
Nevertheless - there was a bug, which will be fixed.

Thanks

**Comment by freddydk** [comment]
All images was rebuilt a week ago with generic image 0.0.8.0 - which keeps the TestToolkit from W1 if the country doesn't have a specific test toolkit.
