### ISSUE TITLE
Container creation stops at 'Installing SIP crypto provider'

### ISSUE THREAD

**Issue by ewaldventer** [microsoft/navcontainerhelper#1954]
**The issue**
Hi,

I worked through all of the above troubleshooting steps, and after Windows and Docker updates, I still get stuck at the same step:
> Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'

It just hangs there. Not sure if it is hanging on that step or trying to get to the next one.
I've left it "running" (previously) for 30minutes, but that's where it stays. Log attached at the end.

I'm convinced it is environmental, but not sure what, as it works perfectly on my personal machine which isn't attached to the company AD.

Only errors in the container event log:
> 1. License Activation (slui.exe) failed with the following error code: hr=0x8007007B
> 2. Failed to collect hardware data. Error code 0xD0000034.

There are SQL related informational messages that looks like it should be errors.
[Full log](https://github.com/microsoft/navcontainerhelper/files/6599356/Log.zip)  attached.

**Scripts used to create container and cause the issue**
```
$containerName = 'pvs174'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '17.4' -country 'w1' -select 'Latest'
$licenseFile = 'C:\Temp\partner.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -dns '8.8.8.8' `
    -usessl -installCertificateOnHost `
    -memoryLimit 12G `
    -isolation 'hyperv' `
    -updateHosts `
    -useBestContainerOS
```

Also tried the simplified script as per your [blog post](https://freddysblog.com/2020/10/12/troubleshooting-business-central-on-docker/) 
```
New-BcContainer `
     -accept_eula `
     -artifactUrl $artifactUrl `
     -auth UserPassword `
     -Credential $credential
```

**Full output of scripts**
```
BcContainerHelper is version 2.0.12
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 21H1
Docker Client Version is 20.10.6
Docker Server Version is 20.10.6
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.19042.985
Creating Container bcserver
Version: 17.4.21491.21531-w1
Style: onprem
Multitenant: No
Platform: 17.0.21485.21516
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19042.985 (20H2)
Host OS Version: 10.0.19043.985 (21H1)
Using hyperv isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\bcserver\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container bcserver from image mcr.microsoft.com/businesscentral:10.0.19042.985
fd364427d916639435b1553fb99f1480bf293e166c7c706154adae34e36d359b
Waiting for container bcserver to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.4.21491.21531/w1
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\17.4.21491.21531\platform\ServiceTier\Program Files
c:\dl\onprem\17.4.21491.21531\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\17.4.21491.21531\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\17.4.21491.21531\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\17.4.21491.21531\w1\database\Demo Database NAV (17-0).bak
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
...
```

**Comment by freddydk** [comment]
I have seen compatibility issues with 20H2 running on 21H1
Unfortunately, the Windows Team still hasn't released server core 21H1 on docker.
You could try to add
```
-useGenericImage 'mcr.microsoft.com/businesscentral:10.0.19041.985'
```
to your New-BcContainer and see if that makes a difference.
On 19041 above you can even try to add 
```
-isolation process
```

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by ewaldventer** [comment]
Unfortunately not.
With the `-useGenericImage 'mcr.microsoft.com/businesscentral:10.0.19041.985'
-isolation 'process'` or 
`-useGenericImage 'mcr.microsoft.com/businesscentral:10.0.19041.985'
-isolation 'hyperv'`, still same issue as before.

With only `-isolation process`, I get: `The container operating system does not match the
host operating system`

I was running Windows 10 version 1909 before this, and it started giving me this issue in the last couple of weeks. 
Hence the update to 21H1.

**Comment by ewaldventer** [comment]
Deleted all containers and images. Reinstalled docker. Same issue.

Deleted C:\bcartifacts.cache\onprem\17.4.21491.21531, ... fixed 🤦‍♂️
