### ISSUE TITLE
Convert-ALCOutputToAzureDevOps fails on warnings

### ISSUE THREAD

**Issue by MatDDev** [microsoft/navcontainerhelper#1956]
**Describe the issue**
I am using Convert-ALCOutputToAzureDevOps cmdlet in CI pipeline to compile apps and report results of such compilation. I am using "-FailOn error" parameter, and even when I have no errors (only warnings) the build still fails (it's being reported partially succeeded, but it has status "failed" in Azure DevOps). 

**Scripts used to create container and cause the issue**
```
$rulesetFile = Join-Path $appProjectFolder -ChildPath '.vscode\company.ruleset.json'
    $alcParameters = @("/project:""$($appProjectFolder.TrimEnd('/\'))""", "/packagecachepath:""$($symbolsFolder.TrimEnd('/\'))""", "/out:""$outputFolder""")
    $alcParameters += @("/analyzer:$(Join-Path "$compilerFolder\extension\bin\" 'Analyzers\Microsoft.Dynamics.Nav.UICop.dll')")
    $alcParameters += @("/analyzer:$(Join-Path "$compilerFolder\extension\bin\" 'Analyzers\Microsoft.Dynamics.Nav.CodeCop.dll')")
    $alcParameters += @("/ruleset:$rulesetfile")

    write-host "Compiling app:"
    Write-Host "$compilerPath $([string]::Join(' ', $alcParameters))"

    $compileExpression = '&{0} {1}' -f $compilerPath, $([string]::Join(' ', $alcParameters))
    $compileExpression += '; if ($lastexitcode -ne 0) {"App generation failed with exit code $lastexitcode"}'

    $result = Invoke-Expression -Command $compileExpression

    $devOpsResult = ""
    if ($result) {
        $devOpsResult = Convert-ALCOutputToAzureDevOps -AlcOutput $result -FailOn 'error' -DoNotWriteToHost
    }
```

**Full output of scripts**
```
BCContainerHelper is version 2.0.12
BCContainerHelper is running as administrator
Host is Microsoft Windows Server 2012 R2
...
```

**Screenshots**
![war](https://user-images.githubusercontent.com/13900033/121013751-875ee900-c799-11eb-9c1f-309b1bfbef40.png)
![2](https://user-images.githubusercontent.com/13900033/121013764-8a59d980-c799-11eb-9720-c70635ccb476.png)

Am I doing something wrong, or why does the entire pipeline seems to fail where there are no errors? If I delete the FailOn parameters, then pipeline runs successfully.

**Comment by freddydk** [comment]
Could you share the output of the compiler ($result) and the output of the function ($devOpsResult)?

**Comment by freddydk** [comment]
It should return 
```
##vso[task.complete result=SucceededWithIssues;]Succeeded With Issues.
```

**Comment by MatDDev** [comment]
It does:

Compilation ended at '15:57:32.0'.  ##vso[task.complete result=SucceededWithIssues;]Succeeded With Issues. 

The pipeline has a warning symbol
![test](https://user-images.githubusercontent.com/13900033/121030441-c432dc00-c7a9-11eb-8fb4-bf6021584e00.png)

But Azure DevOps still shows this as failed attempt.

**Comment by freddydk** [comment]
The exclamation mark is not a failed attempt - it is succeeded with issues.
Here:
![image](https://user-images.githubusercontent.com/10775043/121244159-d80c3a00-c89e-11eb-9019-b0f9919c8a51.png)
The X means failure.
In the build overview it also says warning:
![image](https://user-images.githubusercontent.com/10775043/121244301-fd00ad00-c89e-11eb-9f9e-bf1f575b8181.png)
and in the build, it completes the remaining steps and publishes artifacts and all:
![image](https://user-images.githubusercontent.com/10775043/121244371-130e6d80-c89f-11eb-9188-959334bfa1d3.png)
Everything in my pipeline is as expected.
These warnings are things that will turn into errors, and you should really fix them asap.
If you specify -failon None it will still fail the pipeline if the app cannot build - it just means that it won't fail on the output of alc.exe.

**Comment by MatDDev** [comment]
That part is ok, but then why does it specifically say "failed" on the branch, on which the pipeline run with FailOn error, where in fact there are no errors in the run? It's just quite super confusing : )

![failed](https://user-images.githubusercontent.com/13900033/121299086-2cda9f80-c8f5-11eb-89a2-0b8faef6610e.png)
![failed 2](https://user-images.githubusercontent.com/13900033/121299100-2fd59000-c8f5-11eb-9996-4bffe7750cf9.png)

When there's no parameter FailOn set, it all looks ok
![success](https://user-images.githubusercontent.com/13900033/121298892-e127f600-c8f4-11eb-95f8-86e253af1fba.png)

**Comment by freddydk** [comment]
I cannot tell you why Azure DevOps has decided to have this indicator show failed when the build is successful with warnings.
That would be a bug for Azure DevOps IMO.

**Comment by MatDDev** [comment]
Yeah, I kinda figured it out I need to post it on other place ^^ Thanks for the explanation and help.

**Comment by freddydk** [comment]
Do these pipelines also report warnings indicated as warnings by Azure DevOps? (and SucceededWithIssues)

**Comment by MatDDev** [comment]
> Do these pipelines also report warnings indicated as warnings by Azure DevOps? (and SucceededWithIssues)

Yes, although not through Convert-ALCOutputToAzureDevOps cmdlet, but Compile-AppInBcContainer. Though I can see that I don't have FailOn parameter specified there at all. Anyway, thanks for help : )
