### ISSUE TITLE
ALValidation breaking change for internal table > internal fields

### ISSUE THREAD

**Issue by PP1986** [microsoft/navcontainerhelper#1959]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Previous app version has a table with the Access property set to Internal (on Table level).
New app version has this property removed from the table, but added the Access = Internal property to most of its fields.
No AL Validation says this is breaking, because the fields were not marked as internal before. 
I would expect this to not be breaking, as the fields were actually internal in the previous version as well, as the whole table was marked as internal.

**Comment by freddydk** [comment]
I am not sure what the problem is?

**Comment by PP1986** [comment]
ALValidation says it will fail when submitting the app to app source because of a breaking chance while as far as I can see the change is not breaking.
Previous app (published on app source) has the whole table set to access = internal. So I assume this means all fields are internal. In my new app I removed the access = internal from the table, so the table is now public, but I set  some fields in this table to access = internal. 
Now validation code says these fields were not internal before, so it is breaking, but they were in a table that was completely internal, so the fields were never public. 
Concluding: I feel like the ALValidation code incorrectly says the change is breaking.

**Comment by freddydk** [comment]
Run-AlValidation just uses AppSourceCop and AppSource Validation also uses AppSourceCop.
If it fails Run-AlValidation it will 99.99% of the times also fail appsource validation.

I am not saying that it is the correct behavior, but that is how it is.
You should try to log it here: https://github.com/microsoft/AL/issues
