### ISSUE TITLE
QUESTION: Change Database the container is running on..

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#1962]
When creating a new container, specifing a databaseServer, databaseInstance, databaseName enables me to connect the container to a database that Business Central (also running in that container) uses. In our case the databases are on another server. Every once in a while a database gets renewed. Is it possible to change the database that a container is using? Via a config file or an command. Every container runs Business Central and are created through the BcContainerHelper-Package.

**Comment by freddydk** [comment]
If the database is on the same database server, you should be able to just change the database name config setting on the service tier. There is no command for that, but using Invoke-ScriptInBcContainer, you can do like this:

```
Invoke-ScriptInBcContainer -containerName $containerName -scriptblock {
    Set-NAVServerConfiguration -serverinstance $serverInstance -KeyName "DatabaseName" -KeyValue "newdatabasename"
    Set-NAVServerInstance -serverInstance $serverInstance -restart
}
```
Note that all NAV/BC CmdLets are auto-loaded in Invoke-ScriptInBcContainer and $serverInstance contains the serverInstance name.

**Comment by Silentapproach** [comment]
Ok, I'll try that out and add it to our scripts. Thanks!
