### ISSUE TITLE
Control of Feature Management

### ISSUE THREAD

**Issue by TrippyZ** [microsoft/navcontainerhelper#1963]
In the spirit of 'Keep the script, not the container' and whilst developing a test suite I need to enable the Feature called 'Write Longer Item References'.

However, I can't find any support for that in bccontainerhelper (nor bc powershell either). 

Is there something here in bccontainerhelper to do that?

**Comment by freddydk** [comment]
-featureKeys on New-BcContainer should enable you to enable featureKeys.
You can also call Set-BcContainerFeatureKeys after the container is generated.
the featureKeys parameter should be something like
```
-featureKeys @{ "featurekey" = "1", "feature2key" = "0" }
```

**Comment by TrippyZ** [comment]
Thanks.  Unfortunately this particular feature can't be set by this method;

Set-BcContainerFeatureKeys -containerName bconprem18 -featureKeys @{ "ItemReference" = "1";}

So I will continue to set it by hand for now.
