### ISSUE TITLE
Suppressing Progressbar during "Publish-NavContainerApp"

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#197]
When running "Publish-NavContainerApp -sync", from within a Powershell Console, a progressbar is shown that doesn't disappear after finishing the command. I've tried adding $ProgressPreference = 'SilentlyContinue' like I did with other commands (which worked) to suppress the progressbar but that didn't work in this case. I'm running the code below:

                $previousPreference = $ProgressPreference
                $ProgressPreference = 'SilentlyContinue' 
                Publish-NavContainerApp `
                    -containerName $containerName `
                    -appFile $_.FullName `
                    -skipVerification:$skipVerification `
                    -sync `
                    -Install
                $ProgressPreference = $previousPreference

I've added a printscreen to show you the endresult after running the command several times. I didn't find a way to remove the progressbar afterwards.
![capture](https://user-images.githubusercontent.com/30508071/45490785-55470680-b768-11e8-9cba-4fa4fb18379e.PNG)

**Comment by freddydk** [comment]
Have tried this is ISE and in a PowerShell Prompt - cannot repro

**Comment by mheijkant** [comment]
Sorry about this, I still have this problem. I ran these script lines separatly and it doesn't acure.
But if I run the script lines after some other commands, the progress bar doesn't disapear and stay's on top. Maybe you've seen some simular behaviour somewhere else.
For now I will have a look in the post scripts that I run. The cause must be somewhere else.
thanks anyway.

**Comment by mheijkant** [comment]
This might be of topic for this forum, but I think that the Sync-NavTenant or Sync-NavApp has a bug in its progress-bar handling. These commands are used in the Publish-NavContainerApp command. 
If off-topic, hopefully you can tell me where I can relay this on the correct ms/navision forum.

The issue appears when running powershells scripts from a menu, so running in a loop, and waiting for a single key-press.  When using the "$Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")" the "sync" progressbar stays on top, when using #Read-Host "Hit any key to continue", the progressbar disappears. 
Also when ending the scripts/loop or menu, the progress-bar eventually disappears. I run a dozen or so Navision-commands related scripts that show a progressbar which disappear after the they finnish, except for this one.

The above described issue, can be reproduced by placing below code in as file and running it (for now  not in a loop).

Publish-NavContainerApp `
    -containerName 'MIN-SECONDBRANC' `
    -appFile "c:\temp\my.app" `
    -skipVerification:$true `
    -sync `
    -Install
$key = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

**Comment by freddydk** [comment]
Maybe you can ask the question here: https://community.dynamics.com/business or you can file the bug on partnersource.
It isn't something I can fix here I think.
