### ISSUE TITLE
Hello World example with multiple installApps

### ISSUE THREAD

**Issue by achim-t** [microsoft/navcontainerhelper#1970]
In the HelloWorld I use the settings.json to install needed apps by defining an array of strings. The script `Read-Settings.ps1` converts this array to a string and consequently Run-AlPipeline cannot find the (now only one) app.

`["AppA", "AppB"]` -> `'AppA AppB'`

The line `Set-Variable -Name $_ -Value "$str"` should be changed to `Set-Variable -Name $_ -Value $str` (without `"` ) to preserve the array.

**Comment by freddydk** [comment]
The Read-Settings should work if you use a comma separated string in installApps - not an array.

"installApps": "https://businesscentralapps.azureedge.net/helloworld/latest/oneapp.zip,https://businesscentralapps.azureedge.net/helloworld/latest/otherapp.zip"

I will still look into supporting arrays in the .json but I would need to do some testing as some of the other settings might change type from string as well, will have to go through this.

**Comment by achim-t** [comment]
Fair enough. 
Just wanted to let you know in case someone else wants to use arrays here.

**Comment by freddydk** [comment]
Thanks.

Normally, changing the schema of .json or .xml is not recommended though, but I can see why you would do it:-)
