### ISSUE TITLE
possibility to set UsePermissionSetsFromExtensions on creation of container

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#1972]
Dear Freddy,

We are currently still using they old way of permissions, the problem now is that to set the UsePermissionSetsFromExtensions a restart of the nst is needed which will take some time. 

Could you add it as a parameter to the new-bccontainer ?

**Comment by freddydk** [comment]
You can use -additionalParameters @("-e customNavSettings=UsePermissionSetsFromExtensions=false")

**Comment by hvandenborn** [comment]
awesome!
