### ISSUE TITLE
Archive Name of MX_DIOT test app leads to problems on windows

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/navcontainerhelper#1973]
**Describe the issue**
Not sure if this is right place to report this issues but it is artifacts (OnPrem) related.
Within the MX localization in the MX_DIOT/Test folder there is a archive called "Tests for MX DIOT Extension..Source.zip"

As this is not the case for any other zip I assume this is not intended.

![image](https://user-images.githubusercontent.com/24838311/122638201-303f0980-d0f3-11eb-9866-4752699fddef.png)

**Comment by freddydk** [comment]
Just checked, this is also the case on the DVD.
Will add Nikola to this.

**Comment by freddydk** [comment]
This issue is fixed in the upcoming 18.4 release (and 19.0)
