### ISSUE TITLE
Power BI with BC Docker as source

### ISSUE THREAD

**Issue by bluehenve** [microsoft/navcontainerhelper#1978]
**Describe the issue**
I try to get data from my BC docker installation into Power BI Desktop
As a start I try to retrieve the Items table.

1. Tablenames
First I connection to the SQL server IP address, found indocker inspect <mycontainer>
I get a list of tables, but alas couldnt find the item list containing Item names,
There are seveal table where 'item no' is visible, and I found the two items I created as test.
Are all the numbers after the tables something docker related og just normal BC behavior?
![image](https://user-images.githubusercontent.com/70111241/123045447-3850bf00-d3fb-11eb-9ce4-464d3ec1aa2e.png)

2. oData
As I could not find the item table, I tried connection to a BC web service, but with no luck.
I tried to connect to:
https://a95257631dcf:7048/BC/ODataV4/Company('CRONUS%20USA%2C%20Inc.')/ItemLedgerEntries
https://a95257631dcf:7048/BC/OData/Company('CRONUS%20USA%2C%20Inc.')/ItemLedgerEntries

But it fails with:
![image](https://user-images.githubusercontent.com/70111241/123044206-a72d1880-d3f9-11eb-8519-6c6a3fbdaccb.png)

Details: "Dynamics 365 Business Central (on-premises): Request failed: The underlying connection was closed: A secure relationship with the secure SSL / TLS channel could not be established."

I guessed on something with ports, but in docker inspect it looks like the port is open:
![image](https://user-images.githubusercontent.com/70111241/123043657-e9098f00-d3f8-11eb-93e9-0b45218a4f1c.png)

Any help will be much appriciated
Below is a full 'docker inspect' of my Business Central container
---------------------------------------------------------------------------------------------------------------------------------------

PS C:\Users\HenrikVestergaard> docker inspect hvBC2
[
    {
        "Id": "a95257631dcf811bd758cb70036f69222f92785526833dec8922a4981fce134a",
        "Created": "2021-06-04T18:05:39.1981979Z",
        "Path": "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 13556,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-06-23T05:07:05.6907666Z",
            "FinishedAt": "2021-06-23T06:50:36.5185053+02:00",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2021-06-23T08:05:01.1900382+02:00",
                        "End": "2021-06-23T08:05:01.5527615+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2021-06-23T08:05:31.5750898+02:00",
                        "End": "2021-06-23T08:05:31.9149191+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2021-06-23T08:06:01.938452+02:00",
                        "End": "2021-06-23T08:06:02.2929145+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2021-06-23T08:06:32.3241713+02:00",
                        "End": "2021-06-23T08:06:32.680711+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2021-06-23T08:07:02.7075222+02:00",
                        "End": "2021-06-23T08:07:03.0566015+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:89b014c6aa1a8a139ccfbea4241c8722e77ef2eb2741396986519c31178152d1",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\a95257631dcf811bd758cb70036f69222f92785526833dec8922a4981fce134a\\a95257631dcf811bd758cb70036f69222f92785526833dec8922a4981fce134a-json.log",
        "Name": "/hvBC2",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                30,
                120
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\a95257631dcf811bd758cb70036f69222f92785526833dec8922a4981fce134a"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [],
        "Config": {
            "Hostname": "a95257631dcf",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "7083/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "accept_eula=Y",
                "artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us",
                "DOTNET_RUNNING_IN_CONTAINER=true",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0"
            ],
            "Cmd": [
                "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "mcr.microsoft.com/businesscentral:10.0.19041.985",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "created": "202105171729",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "maintainer": "Dynamics SMB",
                "osversion": "10.0.19041.985",
                "tag": "1.0.1.7"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a95257631dcf811bd758cb70036f69222f92785526833dec8922a4981fce134a",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "7083/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "a95257631dcf811bd758cb70036f69222f92785526833dec8922a4981fce134a",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "94c355e1bdb8c2a0e5b41354ba3f39e9ce895ef1d9dce4eb8efd245b9dda2329",
                    "EndpointID": "db01d6afd13384cbbaf7f6f90151af491f4c68803c5fe67e5de9a79bc0c10fa4",
                    "Gateway": "172.28.96.1",
                    "IPAddress": "172.28.107.174",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:3a:b6:e0",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by freddydk** [comment]
What script is used to create the container and what is the full output of that?

**Comment by freddydk** [comment]
BTW - on Table names - the GUID after the table name is the appid of the app "owning" the table or table extension.

**Comment by bluehenve** [comment]
PowerShell:
docker run --name hvBC -e accept_eula=Y -m 4G -e artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us mcr.microsoft.com/businesscentral:10.0.19041.985
PowerShell output   v-:
	PS C:\Users\HenrikVestergaard> docker run --name hvBC2 -e accept_eula=Y --isolation process -m 4G -e artifacturl=https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us mcr.microsoft.com/businesscentral:10.0.19041.985
	Unable to find image 'mcr.microsoft.com/businesscentral:10.0.19041.985' locally
	10.0.19041.985: Pulling from businesscentral
	295f12394c4f: Pull complete
	6ee75c9d841d: Pull complete
	afbe61956479: Pull complete
	015d83b0dcfd: Pull complete
	03fd0aefebee: Pull complete
	078f0a973592: Pull complete
	156653ac6d3c: Pull complete
	75e9e47bc7e6: Pull complete
	5d9ed5a45d2c: Pull complete
	6d4551e22b2f: Pull complete
	ebf789f3a80b: Pull complete
	7b763775d9c5: Pull complete
	fc8890595ace: Pull complete
	0ece3f248cca: Pull complete
	7e08ca69d5b8: Pull complete
	30845fda43dc: Pull complete
	27ce475656ee: Pull complete
	65d62ed9c849: Pull complete
	Digest: sha256:2c3abe1534020c1e441a35fea8dc3aca78cbcd30a0eda7cadb393d86116fa2c6
	Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.19041.985
	Using artifactUrl https://bcartifacts.azureedge.net/onprem/17.0.16993.0/us
	Downloading application artifact /onprem/17.0.16993.0/us
	Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\1b548676-ead6-4904-a7dc-60f41d5a0dca.zip
	Unpacking application artifact
	Downloading platform artifact /onprem/17.0.16993.0/platform
	Downloading C:\Users\ContainerAdministrator\AppData\Local\Temp\8a99d60d-9932-4dd2-9d98-524b64b0e121.zip
	Unpacking platform artifact
	Downloading Prerequisite Components
	Downloading c:\dl\onprem\17.0.16993.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
	Downloading c:\dl\onprem\17.0.16993.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
	Downloading c:\dl\onprem\17.0.16993.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
	Using installer from C:\Run\150-new
	Installing Business Central
	Installing from artifacts
	Starting Local SQL Server
	Starting Internet Information Server
	Copying Service Tier Files
	c:\dl\onprem\17.0.16993.0\platform\ServiceTier\Program Files
	c:\dl\onprem\17.0.16993.0\platform\ServiceTier\System64Folder
	Copying PowerShell Scripts
	c:\dl\onprem\17.0.16993.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
	c:\dl\onprem\17.0.16993.0\platform\WindowsPowerShellScripts\WebSearch
	Copying dependencies
	Copying ReportBuilder
	Importing PowerShell Modules
	Determining Database Collation from c:\dl\onprem\17.0.16993.0\us\database\Demo Database NAV (17-0).bak
	Changing Database Server Collation to Latin1_General_100_CI_AS
	Restoring CRONUS Demo Database
	Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
	Modifying Business Central Service Tier Config File for Docker
	Creating Business Central Service Tier
	Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
	Copying Web Client Files
	c:\dl\onprem\17.0.16993.0\platform\WebClient\Microsoft Dynamics NAV
	Copying Client Files
	c:\dl\onprem\17.0.16993.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
	c:\dl\onprem\17.0.16993.0\platform\LegacyDlls\program files\Microsoft Dynamics NAV
	c:\dl\onprem\17.0.16993.0\platform\LegacyDlls\systemFolder
	Copying ModernDev Files
	c:\dl\onprem\17.0.16993.0\platform
	c:\dl\onprem\17.0.16993.0\platform\ModernDev\program files\Microsoft Dynamics NAV
	Copying additional files
	Copying ConfigurationPackages
	C:\dl\onprem\17.0.16993.0\us\ConfigurationPackages
	Copying Test Assemblies
	C:\dl\onprem\17.0.16993.0\platform\Test Assemblies
	Copying Applications
	C:\dl\onprem\17.0.16993.0\us\Applications
	Starting Business Central Service Tier
	Importing license file
	Stopping Business Central Service Tier
	Installation took 163 seconds
	Installation complete
	Initializing...
	Starting Container
	Hostname is a95257631dcf
	PublicDnsName is a95257631dcf
	Using NavUserPassword Authentication
	Creating Self Signed Certificate
	Self Signed Certificate Thumbprint 506767476D712CD9118FC07A1FAD15C3196622B6
	Modifying Service Tier Config File with Instance Specific Settings
	Starting Service Tier
	Registering event sources
	Creating DotNetCore Web Server Instance
	Creating http download site
	Setting SA Password and enabling SA
	Creating admin as SQL User and add to sysadmin
	Creating SUPER user
	Container IP Address: 172.23.114.189
	Container Hostname  : a95257631dcf
	Container Dns Name  : a95257631dcf
	Web Client          : https://a95257631dcf/BC/
	Admin Username      : admin
	Admin Password      : Some1840
	Dev. Server         : https://a95257631dcf
	Dev. ServerInstance : BC
	
	Files:
	http://a95257631dcf:8080/ALLanguage.vsix
	http://a95257631dcf:8080/certificate.cer
	
	Container Total Physical Memory is 15.8Gb
	Container Free Physical Memory is 5.4Gb
	
	Initialization took 91 seconds
	Ready for connections!
	Starting EventLog Monitor
	Monitoring EventSources from EventLog[Application]:
	- MicrosoftDynamicsNAVClientClientService
	- MicrosoftDynamicsNAVClientWebClient
	- MicrosoftDynamicsNavServer$BC
	- MSSQL$SQLEXPRESS
	
	TimeGenerated : 06/04/2021 20:12:35
	EventSource: MicrosoftDynamicsNAVClientWebClient
	EntryType : Information
	Message :
	ThreadPool. MinWorkerThreads=250, MinCompletionPortThreads=8
	
	TimeGenerated : 06/04/2021 20:13:09
	EventSource: MicrosoftDynamicsNavServer$BC
	EntryType : Warning
	Message :
	Server instance: BC
	Category: CacheSynchronization
	ClientSessionId: 00000000-0000-0000-0000-000000000000
	ClientActivityId: 00000000-0000-0000-0000-000000000000
	ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
	ServerActivityId: e1101641-8f05-47cd-ab2b-233a81fdcde7
	EventTime: 06/04/2021 18:13:09
	Message Last read record is missing, we need to clear the cache newestReadTimestamp 162015 lastreadTimestamp 0
	ProcessId: 11056
	Tag: 00001U4
	ThreadId: 29
	CounterInformation:
	CustomParameters: {
	}
	GatewayCorrelationId:
	
Succes v-:
	Container IP Address: 172.23.114.189
	Container Hostname  : a95257631dcf
	Container Dns Name  : a95257631dcf
	Web Client          : https://a95257631dcf/BC/
	Admin Username      : admin
	Admin Password      : Some1840
	Dev. Server         : https://a95257631dcf
	Dev. ServerInstance : BC
	
	Initialization took 91 seconds
	Ready for connections!
	Starting EventLog Monitor
	Monitoring EventSources from EventLog[Application]:
	- MicrosoftDynamicsNAVClientClientService
	- MicrosoftDynamicsNAVClientWebClient
	- MicrosoftDynamicsNavServer$BC
- MSSQL$SQLEXPRESS

**Comment by freddydk** [comment]
The problem is that your host machine doesn't trust the self-signed certificate created in the container.

In the files section in the output, you will find the self-signed certificate created in the container.
Looks like this:
```
http://a95257631dcf:8080/certificate.cer
```
Download that and install that in the trusted root certificates on the host computer.

FYI - If you use BcContainerHelper to create the container, then New-BcContainer has a parameter called -installCertificateOnHost which will install the certificate when creating the container and removing it when removing the container.

**Comment by bluehenve** [comment]
Hi Freddy
Wonderfull!, thanks. After installing the certificate the oData connection works like a charm!
I will try BcContainerHelper later.

>BTW - on Table names - the GUID after the table name is the appid of the app "owning" the table or table extension.
Ok, I get the gist of it. Not sure which apps can own a table....

Regards, Henrik

**Comment by freddydk** [comment]
Any app can have a table or a table extension - these will all become tables in the DB like this.
The 437dbf0e... ID is the base application
c526b3e9... must be an app extending the item table
