### ISSUE TITLE
Creation of container with RU Localization for BC (insider) falls with an error

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#198]
Hi Freddy.
I try to create BC Sandbox with RU localization, but it falls with the error.
`$containername = 'BC-Latest-RU'
$navdockerimage = 'bcinsider.azurecr.io/bcsandbox-master:ru'
`
`New-NavContainer -accept_eula:$accept_eula 
    -containername $containername 
    -auth NavUserPassword 
    -Credential $credential 
    -includeCSide 
    -alwaysPull 
    -usessl:$false 
    -updateHosts 
    -assignPremiumPlan 
    -shortcuts Desktop 
    -imageName $navdockerimage 
    -licenseFile $licenseFile 
    -additionalParameters $additionalParameters 
    -doNotExportObjectsToText:$false
`

`Digest: sha256:87974df36a82a0bb44999f51fca0f4a7091c4782dd585feda1ba1d7bb0f6d07a
Status: Downloaded newer image for bcinsider.azurecr.io/bcsandbox-master:ru
Creating Nav container BC-Latest-RU
Using image bcinsider.azurecr.io/bcsandbox-master:ru
Using license file C:\ProgramData\NavContainerHelper\License\license.flf
NAV Version: 13.0.23665.0-ru
Generic Tag: 0.0.6.3
Creating container BC-Latest-RU from image bcinsider.azurecr.io/bcsandbox-master:ru
Waiting for container BC-Latest-RU to be ready
Initializing...
Starting Container
Hostname is BC-Latest-RU
PublicDnsName is BC-Latest-RU
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 53
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is BC-Latest-RU
PublicDnsName is BC-Latest-RU
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 53
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1`

`Initialization of container BC-Latest-RU failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.0\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...atest-RU failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC-Latest-RU failed`

**Comment by dkatson** [comment]
![image](https://user-images.githubusercontent.com/29101017/45503904-fc3f9880-b790-11e8-9c6b-eb8ca230422d.png)

**Comment by freddydk** [comment]
The RU version of the bcsandbox is more than 90 days old, hence the error. You can set the environment variable accept_outdated to Y (new-navcontainer -accept_outdated …) but that is likely not what you want.
I will drop you an email.
