### ISSUE TITLE
UploadImportAndApply-ConfigPackageInBcContainer never finish

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#1982]
**Describe the issue**
I'm trying to use this command: UploadImportAndApply-ConfigPackageInBcContainer with "DE.DEU.EVALUATION" but it never gets finished. After 3 hours the pipeline stopped.

**Scripts used to create container and cause the issue**
```
New-BCContainer -accept_eula `
    -containerName $containerName `
    -auth NAVUserPassword `
    -Credential $adminCredentials `
    -artifactUrl $artifactUrl `
    -licenseFile $licensefile `
    -shortcuts $shortcuts `
    -includeTestToolkit:$true`
    -doNotUseRuntimePackages `
    -assignPremiumPlan `
    -accept_outdated `
    -memoryLimit 12G `
    -multitenant:$false `
    -updateHosts `
    -useTraefik `
    -PublicDnsName $env:DNSNAME `
    -Restart always

Issue on:
UploadImportAndApply-ConfigPackageInBcContainer -containerName $containerName -configPackage $configPackageName -credential $credential
```

**Full output of scripts**
```
BcContainerHelper is version 2.0.13
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 20.10.4
Docker Server Version is 20.10.4
```

**Screenshots**
![image](https://user-images.githubusercontent.com/7090519/123943274-4757e400-d99c-11eb-819f-eb5aa3863ce6.png)

**Additional context**
- does it happen all the time? yes (5 times tried)
- did it use to work? no (first-time use)

**Comment by freddydk** [comment]
Please try to use Run-ConnectionTestToBcContainer on the container after creating it and before running the uploadimportandapply command.
If that doesn't work, please create a script, which I can copy/paste, which repros the problem (including a dummy password and all), thanks.

**Comment by Spycoclown** [comment]
CommunicationError : Response status code does not indicate success: 502 (Bad Gateway).
at <ScriptBlock>, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 110
at <ScriptBlock>, <No file>: line 62
at AwaitState, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 251
at OpenSession, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 217
at Initialize, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 78
at ClientContext, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 45
at New-ClientContext, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 55
ClientSession State is Uninitialized (Wait time 21 seconds)
at AwaitState, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 251
at OpenSession, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 217
at Initialize, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 78
at ClientContext, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\ClientContext.ps1: line 45
at New-ClientContext, C:\ProgramData\BcContainerHelper\Extensions\Agent-02\PsConnectionTestTool\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 55
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.13\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at Run-ConnectionTestToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.13\AppHandling\Run-ConnectionTestToNavContainer.ps1: line 194
at <ScriptBlock>, C:\agent-02\_work\72\s\Pipeline\Create-Environment\Create-Container.ps1: line 81
at <ScriptBlock>, C:\agent-02\_work\_temp\1ec2d97f-6325-4391-8123-8b1811f83209.ps1: line 3
at <ScriptBlock>, <No file>: line 1

**Comment by Spycoclown** [comment]
what could be the problem why it get Bad Gateway?

**Comment by freddydk** [comment]
what command (with parameters) did you run?

**Comment by Spycoclown** [comment]
`Run-ConnectionTestToBcContainer -containerName $containerName -credential $credential`

**Comment by freddydk** [comment]
please post a full script (including all variables) which fails and I can run to repro.

**Comment by Spycoclown** [comment]
```
Param(
    [Parameter(Mandatory = $true)]
    [string] $containerName,
    
    [Parameter(Mandatory = $true)]
    [string] $sharedFolder,
    
    [Parameter(Mandatory = $true)]
    [string] $bcImage,
    
    [Parameter(Mandatory = $true)]
    [string] $artifactUrl,
    
    [Parameter(Mandatory = $true)]
    [PSCredential] $adminCredentials,

    [Parameter(Mandatory = $true)]
    [string] $workingDirectory,

    [Parameter(Mandatory = $true)]
    $cleanContainer,

    [Parameter(Mandatory = $true)]
    $includeTestToolkit = $false,

    [Parameter(Mandatory = $false)]
    [string] $licensefile,

    [Parameter(Mandatory = $true)]
    $importConfigPackage = $false,

    [Parameter(Mandatory = $true)]
    [string] $configPackageName
)

Write-Host "Creating needed parameters."
$shortcuts = "None"

$additionalParameters = @("--volume ""$($sharedFolder):$($sharedFolder)""",
                          "--env customNavSettings=EnableTaskScheduler=$false")
                          
if($cleanContainer){
    $bcImage = ''
} else {
    $artifactUrl = ''
}

Write-Host "Starting to create container $containerName"
New-BCContainer -accept_eula `
    -containerName $containerName `
    -auth NAVUserPassword `
    -Credential $adminCredentials `
    -imageName $bcImage `
    -artifactUrl $artifactUrl `
    -additionalParameters $additionalParameters `
    -licenseFile $licensefile `
    -shortcuts $shortcuts `
    -includeTestToolkit:$includeTestToolkit `
    -doNotUseRuntimePackages `
    -assignPremiumPlan `
    -accept_outdated `
    -memoryLimit 12G `
    -multitenant:$false `
    -updateHosts `
    -useTraefik `
    -PublicDnsName $env:DNSNAME `
    -Restart always
    #-includePerformanceToolkit:$includeTestToolkit `

Write-Host "##[section] Set sharedFolder = $sharedFolder"
Write-Host "##vso[task.setvariable variable=sharedFolder]$sharedFolder"

Write-Host "Create Users"
$users = @("USER1","USER2","USER3")
foreach ($user in $users){
    $credential = New-Object PSCredential $user, $adminCredentials.Password
    New-BcContainerBcUser -Credential $credential -containerName $containerName -PermissionSetId 'SUPER' -ChangePasswordAtNextLogOn:$false 
}

if($importConfigPackage){
    Run-ConnectionTestToBcContainer -containerName $containerName -credential $credential
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $containerName -configPackage $configPackageName -credential $credential
}
```

**Comment by Spycoclown** [comment]
The Calling Parameter are:
`'C:\agent-02\_work\72\s\Pipeline\Create-Environment\Create-Container.ps1' -containerName "Agent-02" -sharedFolder "C:\agent-02" -bcImage "sandbox182de:TestToolkit" -artifactUrl "https://bcartifacts.azureedge.net/sandbox/18.2.26217.27444/de" -adminCredentials ([PSCredential]::new("XXXXX", (ConvertTo-SecureString -String "XXXXXX" -AsPlainText -Force))) -workingDirectory "C:\agent-02\_work\72\s" -licensefile "C:\agent-02\_work\_temp\fin.flf" -cleanContainer $True -includeTestToolkit $True -importConfigPackage $True -configPackageName "DE.DEU.EVALUATION"`

**Comment by freddydk** [comment]
enableTaskScheduler needs to be true in order to apply configuration packages.
