### ISSUE TITLE
Run-AlValidation issue

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/navcontainerhelper#1984]
**Describe the issue**
Run-AlValidation does not work if I do not add -validateVersion 18.0 -validateCurrent

**Scripts used to create container and cause the issue**
$validationResults = Run-AlValidation `
-licenseFile $licencePath `
-installApps @($AppPath) `
-previousApps @($PrevAppPath) `
-apps @($NewAppPath) `
-countries @(“US”) `
$validationResults | Write-Host -ForegroundColor Red

**Full output of scripts**
Pulling mcr.microsoft.com/businesscentral:10.0.19042.985
Pulling generic image took 1 seconds
AL Validation finished in 0 seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/61985025/123996637-621e5e80-d984-11eb-92a2-0caaa97de8fc.png)
![image](https://user-images.githubusercontent.com/61985025/123996797-8aa65880-d984-11eb-98ff-ede1f53da5d3.png)
![image](https://user-images.githubusercontent.com/61985025/123997160-eec91c80-d984-11eb-80d6-66ebbecfd063.png)

Workaround 
Using -  Run-AlValidation -validateVersion 18.0 -validateCurrent

**Comment by freddydk** [comment]
Could you try with the latest containerhelper?

**Comment by KuljitSinghParmar** [comment]
![image](https://user-images.githubusercontent.com/61985025/124004602-07d5cb80-d98d-11eb-8d22-426d432591eb.png)

I think I have the latest containerhelper but when I use - Run-AlValidation -validateVersion 18.0 -validateCurrentcontainer  is uses old one. 

![image](https://user-images.githubusercontent.com/61985025/124005115-90ed0280-d98d-11eb-9c5b-565507629473.png)

**Comment by freddydk** [comment]
And if you restart PowerShell?
Else use uninstall-module BcContainerHelper -allversions -force
and then install-module bccontainerhelper -force
and retry

**Comment by KuljitSinghParmar** [comment]
Thanks Freddy. Restarting the PowerShell worked :)

**Comment by freddydk** [comment]
and did your validation pipeline work?

**Comment by KuljitSinghParmar** [comment]
Yes it worked and I think it was faster than BcContainerHelper 1.0.17
