### ISSUE TITLE
Convert-ModifiedObjectsToAl gives strange result, because of rebuild search index (may be)

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#199]
Hi Freddy, I used Convert-ModifiedObjectsToAl a previously, and it worked fine. However today i experience strange behaviour. For some base pages it creates page-extensions with unsupported changes.

I made simple test.
1) Created new navcontainer
`$fromContainerImage = 'bcinsider.azurecr.io/bcsandbox-master'`

`New-NavContainer -accept_eula:$accept_eula 
    -containername $containername 
    -auth NavUserPassword
    -Credential $credential 
    -includeCSide 
    -alwaysPull:$false 
    -usessl:$false 
    -updateHosts 
    -assignPremiumPlan 
    -shortcuts Desktop 
    -imageName $navdockerimage 
    -licenseFile $licenseFile 
    -additionalParameters $additionalParameters 
    -doNotExportObjectsToText:$false
`

2) Imported Fob with 1 new page, trough Object Designer

3) It automatically rebuild search indexes for all pages
![image](https://user-images.githubusercontent.com/29101017/45515162-0ae97800-b7b0-11e8-9bb5-1e2700c0af99.png)

4) I converted modified objects in al
`Convert-ModifiedObjectsToAl 
    -containerName $containername 
    -startId $startID 
    -sqlCredential $credential 
    -openFolder $openFolder 
    -Verbose`

5) Expected result would be in 1 .al file, but i see pageextensions for some pages + 1 .al file

Page extensions were created for pages
- 130401 - 130415
- 99000754 - 99000959

Example of delta file

OBJECT Modification "Untracked Planning Elements"(Page 99000855)
{
  OBJECT-PROPERTIES
  {
    Date=20180820D;
    Time=120000T;
    Version List=NAVW113.00;
  }
  PROPERTIES
  {
    Target="Untracked Planning Elements"(Page 99000855);
    TargetPageType=List;
  }
  CHANGES
  {
    { PropertyModification;
                         Target=SetCaption(PROCEDURE 1);
                         Property=Attributes;
                         OriginalValue=[[External]][LineStart(509199)]]];
                         ModifiedValue=[[External]][LineStart(509433)]]] }
    { PropertyModification;
                         Target=FormatLine(PROCEDURE 3);
                         Property=Attributes;
                         OriginalValue=[[LineStart(509202)]]];
                         ModifiedValue=[[LineStart(509436)]]] }
  }
  CODE
  {

    BEGIN
    END.
  }
}

**Comment by freddydk** [comment]
The Convert-ModifiedObjectsToAl lives off the exported objects, which are stored in C:\ProgramData\NavContainerHelper\Extensions\Original-<versionnumber>-W1\
You could try to delete those folders and re-run.
The thing that might be the root cause here is that we recently have started building platform and app separately, which means that we could have a new app and the same platform. The Version number I use for these folders might be the platform version number.
I will investigate.

**Comment by dkatson** [comment]
Hi Freddy, I did that. 
I deleted everything related and started from fresh. The result was as I described earlier.

**Comment by freddydk** [comment]
Just tried, I cannot repro this.

I cannot see all parameters - I tried this:
New-NavContainer -accept_eula -imageName bcinsider.azurecr.io/bcsandbox-master -containerName test -includeCSide -licenseFile C:\temp\license.flf -updatehosts
Works as normal.

If you open CSIDE and filter on modified objects - are these objects then modified?

**Comment by freddydk** [comment]
I think this was caused by a change in the export-navapplicationobjects to include properties for LineStart. The latest version of navcontainerhelper automatically strips these properties before comparing.
