### ISSUE TITLE
Downloading symbols Tests-ERM is not working. The remote server returned an error: (404) Not Found

### ISSUE THREAD

**Issue by BennoVendrig** [microsoft/navcontainerhelper#1990]
Most of the symbols are downloaded by the Compile-AppInNavContainer.ps1 script (Test Runner, Tests-TestLibraries, etc.) but the scripts is trying to download an error appears  that the url http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=Tests-ERM&versionText=18.0.0.0&tenant=default is not found. 

Using Symbols Folder: C:\Agent_work\1\s\.packages
Downloading symbols: Microsoft_Test Runner_18.0.23013.23795.app
Url : http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=Test%20Runner&versionText=18.0.0.0&tenant=default
Downloading symbols: Microsoft_Tests-TestLibraries_18.0.23013.23795.app
Url : http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=Tests-TestLibraries&versionText=18.0.0.0&tenant=default
Downloading symbols: Microsoft_System Application Test Library_18.0.23013.23795.app
Url : http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=System%20Application%20Test%20Library&versionText=18.0.0.0&tenant=default
Adding dependency to System Application from Microsoft
Downloading symbols: Microsoft_Library Variable Storage_18.0.23013.23795.app
Url : http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=Library%20Variable%20Storage&versionText=18.0.0.0&tenant=default
Downloading symbols: Microsoft_Any_18.0.23013.23795.app
Url : http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=Any&versionText=18.0.0.0&tenant=default
Downloading symbols: Microsoft_Library Assert_18.0.23013.23795.app
Url : http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=Library%20Assert&versionText=18.0.0.0&tenant=default
**Downloading symbols: Microsoft_Tests-ERM_18.0.0.0.app
Url : http://172.25.73.67:7049/BC/dev/packages?publisher=Microsoft&appName=Tests-ERM&versionText=18.0.0.0&tenant=default
ERROR The remote server returned an error: (404) Not Found.**

Details of the error are:
##[error]The remote server returned an error: (404) Not Found. No published package matches the provided arguments. 
(ms-correlation-x = )
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.15-preview449\AppHandling\Compile-AppInNavContainer.ps1:382 
char:21
+                     throw (GetExtenedErrorMessage $_.Exception)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The remote serv...rrelation-x = ):String) [], RuntimeException
    + FullyQualifiedErrorId : The remote server returned an error: (404) Not Found. No published package matches the p 
   rovided arguments. (ms-correlation-x = )
##[error]PowerShell exited with code '1'.

What could be the cause of this issue?

**Comment by freddydk** [comment]
That is likely because Tests-ERM was not published.
All the other apps seems to be libraries you get when including only TestLibraries.
Tests-ERM are actual tests, which needs to be published as well.
If you include the script used to create the container and the full output, then it would be possible to see whether this is true.

**Comment by BennoVendrig** [comment]
Hi Freddy,
Sorry for the late reply. Hereby I send you the requested files. Hopefully you can help me. Thanks in advance
[Output log.txt](https://github.com/microsoft/navcontainerhelper/files/6777164/Output.log.txt)
[_CICD.zip](https://github.com/microsoft/navcontainerhelper/files/6777166/_CICD.zip)

**Comment by freddydk** [comment]
In the latest version of the CI/CD samples, the settings file has a InstallTestApps property, which is designed for installing apps, which your test apps depend on.
Scripts in the scripts folder have been updated accordingly to use this property - you need to update the scripts.

Then you should be able to set that to ":C:\Applications\BaseApp\Test\Microsoft_Tests-ERM.app"(include the starting :, which means that the reference is to a file inside the container)

Note that you cannot run this pipeline on a cloud based environment, as Tests-ERM cannot be published to a cloud sandbox - only to containers.

**Comment by BennoVendrig** [comment]
Hi Freddy,
Thanks. This is working with the parameter below (with double backslash):
"installTestApps": ":C:\\Applications\\BaseApp\\Test\\Microsoft_Tests-ERM.app"

Perhaps a stupid question but where can I find the latest CI/CD samples? Thanks in advance

**Comment by freddydk** [comment]
on Github:
PTE sample: https://github.com/BusinessCentralApps/HelloWorld
AppSource App sample: https://github.com/BusinessCentralApps/HelloWorld.AppSource

or on Azure DevOps (identical to the samples on Github)
PTE sample: https://dev.azure.com/businesscentralapps/HelloWorld
AppSource App sample: https://dev.azure.com/businesscentralapps/HelloWorld.AppSource

**Comment by BennoVendrig** [comment]
I was doing some testing today with the installTestApps parameter and receive the error below after publishing the Tests-ERM app in the Install Test Apps part of the Run-AIPipeline:

Extension compilation failed
2021-07-10T16:41:29.8857552Z ERMIntrastatJournal.Codeunit.al(1074,30): error AL0132: 'TestPage Intrastat Journal' does not contain a definition for 'CreateFile'
2021-07-10T16:41:29.8870296Z ERMIntrastatJournal.Codeunit.al(1144,30): error AL0132: 'TestPage Intrastat Journal' does not contain a definition for 'CreateFile'
2021-07-10T16:41:29.8882181Z ERMIntrastatJournal.Codeunit.al(1190,30): error AL0132: 'TestPage Intrastat Journal' does not contain a definition for 'CreateFile'
2021-07-10T16:41:29.8892923Z at <ScriptBlock>, <No file>: line 40

When I add the below script manually in the Run-AIPipeline.ps1 script the publishing is going well. What do I wrong? 
$testsERMApp = "C:\bcartifacts.cache\sandbox\18.0.23013.23795\nl\Applications.NL\Microsoft_Tests-ERM_18.0.23013.23795.app" 
$Parameters = @{
        "containerName" = $containerName
        "tenant" = $tenant
        "credential" = $credential
        "appFile" = $testsERMApp
        "skipVerification" = $true
        "sync" = $true
        "install" = $true
    }
Invoke-Command -ScriptBlock $PublishBcContainerApp -ArgumentList $Parameters

Thanks in advance.

See the attachment with the total log.


[Log.txt](https://github.com/microsoft/navcontainerhelper/files/6795645/Log.txt)
