### ISSUE TITLE
[Question] How to use SandboxAsOnPrem?

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#1995]
**Describe the issue**
We were trying to figure out what the best setting of parameters is in order to successfully create a BcContainer from version 18 and onwards with the runSandboxAsOnPrem-parameter active. We were unsure about whether to use OnPrem or Sandbox as the correct type. 

Following the logic run**Sandbox**asOnPrem we have to set Sandbox as the type. But what changes when using OnPrem? 

No error occured using one of those two. 

Thanks in advance.

**Comment by freddydk** [comment]
When targeting on-premises customers, you should use on-premises artifacts. BC will "think" that it is on-premises.
When targeting online customers, you should use sandbox artifacts. BC will "think" that it is an online environment.
On-premises artifacts are released monthly (CU's) and no insider builds are available.
Sandbox artifacts are continuously and insider builds are available for both NextMinor and NextMajor.

The -runSandboxAsOnPrem is used for spinning up a container using sandbox artifacts, which "thinks" that it is on-premises.

**Comment by Silentapproach** [comment]
Ah, ok. Thank you! I will close that issue.
