### ISSUE TITLE
The "generatesymbolreference" command is not valid

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#1996]
**Describe the issue**
Unable to generate symbols. 

**Scripts used to create container and cause the issue**
```
$containerName = 'nne'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2017' -cu '10' -country 'dk'
$licenseFile = 'c:\nav\infar\udvikling\nav2017.flf'
New-BcContainer -shortcuts DesktopFolder `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts```


**Screenshots**
![image](https://user-images.githubusercontent.com/25152707/124727755-492b2580-df0f-11eb-941a-31f652fcfc33.png)


**Additional context**
The container itself works fine. I can start the client and login, but I would like to be able to test the table changes I make.

**Comment by Rukkulakki** [comment]
Screenshot in textform

PS C:\WINDOWS\system32> Get-InstalledModule bccontainerhelper -allversions

Version    Name                                Repository           Description                                                                                       
-------    ----                                ----------           -----------                                                                                       
2.0.14     BcContainerHelper                   PSGallery            PowerShell module                                                                                 



PS C:\WINDOWS\system32> Generate-SymbolsInNavContainer -containerName nne
Creating application symbols in nne
[29885216] The "generatesymbolreference" command is not valid.
at <ScriptBlock>, <No file>: line 24
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.12\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at Generate-SymbolsInNavContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.12\SymbolHandling\Generate-SymbolsInNavContainer.ps1: line 23
at <ScriptBlock>, <No file>: line 1
[29885216] The "generatesymbolreference" command is not valid.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.12\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ([29885216] The ...d is not valid.:String) [], RuntimeException
    + FullyQualifiedErrorId : [29885216] The "generatesymbolreference" command is not valid.

**Comment by freddydk** [comment]
Symbol generation is when you want to get symbols to use for AL coding
NAV 2017 is C/AL only, so Generate-SymbolsInNavContainer will fail for any version prior to NAV 2018 and later than BC 14.

**Comment by Rukkulakki** [comment]
Fair enough; I just assumed that it basically handled the synchronization and metadata part. My fault :)

But then the question becomes how I get it to synchronise tablechanges? When I try to sync. schemas for tables, I get an error saying that it cannot connect to the server
Servernavn: nne
Serverforekomst: nav
Styringsport: 7045
![image](https://user-images.githubusercontent.com/25152707/124737420-38cb7880-df18-11eb-90cd-5f9c79a8023c.png)

**Comment by freddydk** [comment]
Hvis du forsøger at gøre dette fra CSIDE, så skal du nok bruge Windows Authentication.
Ellers kan du gøre det via Import-ObjectsToNavContainer, der burde sync'e som en del af det.
Du kan også i ISE bruge Enter-NavContainer nne for at få en prompt inde i containeren og bruge PowerShell (jeg kan ikke huske alle PowerShell cmdlets)

**Comment by Rukkulakki** [comment]
Sync-NAVTenant from within the container did the trick. Thank you.
