### ISSUE TITLE
Can't install Microsoft_Tests-Misc.app using Import-TestToolkitToBcContainer

### ISSUE THREAD

**Issue by Rub19Luc21** [microsoft/navcontainerhelper#1997]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

When running the Import-TestToolkitToBcContainer on an existing container it gives a compile error on the Microsoft_Tests-Misc.app.
It seems to be using the right versions. 
(as far as I can determine based on the version number of the other test apps that do install without issues).
I tried to change some of the parameters, but that doesn't solve it.

I used the following command:
Import-TestToolkitToBcContainer -containerName ***** -tenant *****

This is the Output:
(during a second attempt, that's why the preceding apps are already installed)
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Test Runner.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Any.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Library Assert.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Library Variable Storage.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_System Application Test Library.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-TestLibraries.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Bank.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Cash Flow.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Cost Accounting.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-CRM integration.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Data Exchange.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Dimension.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-ERM.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Fixed Asset.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-General Journal.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Graph.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Integration.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Invoicing.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Job.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Local.runtime.app' as it is already installed
Skipping app 'C:\ProgramData\BcContainerHelper\Extensions\sandbox-Applications-18.0.23013.24794-W1\Microsoft_Tests-Marketing.runtime.app' as it is already installed
Publishing C:\ProgramData\BcContainerHelper\Extensions\Vennegoor\11c27646-b5ba-478e-8dcb-4c4d24692dc2\Microsoft_Tests-Misc.app
Extension compilation failed
TestJobQueue.Codeunit.al(421,32): error AL0132: 'CODEUNIT' does not contain a definition for 'Job Queue Recover Job'
at <ScriptBlock>, <No file>: line 18
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Publish-NavContainerApp.ps1: line 257
at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\AppHandling\Publish-NavContainerApp.ps1: line 117
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 185
at Import-TestToolkitToBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ObjectHandling\Import-TestToolkitToNavContainer.ps1: line 153
at <ScriptBlock>, <No file>: line 1
Extension compilation failed
TestJobQueue.Codeunit.al(421,32): error AL0132: 'CODEUNIT' does not contain a definition for 'Job Queue Recover Job'
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Extension compi...ue Recover Job':String) [], RuntimeException
    + FullyQualifiedErrorId : Extension compilation failed
TestJobQueue.Codeunit.al(421,32): error AL0132: 'CODEUNIT' does not contain a definition for 'Job Queue Recover Job'

Info about the container where the Test Toolkit is deployed into:
isBcSandbox	Y
multitenant	Y
databaseServer	host.containerhelper.internal
enableApiServices	Y
artifactUrl	https://bcartifacts.azureedge.net/sandbox/18.0.23013.24794/w1
auth	NavUserPassword

```
NavContainerHelper is version 2.0.11
NavContainerHelper is running as administrator: Yes
Host is Microsoft Windows 10 Enterprise - 2004: Yes 
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5

**Additional context**
It happens on all tenants for this container.
I believe this used to work on previous versions.

**Comment by freddydk** [comment]
Please try to spin up the container without a pointer to an existing database (databaseserver / databasename parameters), my assumption is that there is something wrong with this database.

If the problem still persists, please provide the full script with which I can repro the problem and the full output.

**Comment by Rub19Luc21** [comment]
Retested it on a new container based on 18.3, it doesn't reoccur.
