### ISSUE TITLE
Issue with shortcuts and multiple CUs on same platform

### ISSUE THREAD

**Issue by MikeGlue** [Microsoft/navcontainerhelper#20]
The current script copies the executable files to the program files folder and then points the desktop shortcuts to them.

This causes an issue if you are pulling multiple CU images for the same platform. For example pulling 2017 CU2 and 2017 CU5. Whatever version you pull last "wins" as any existing files are deleted.

This will "sometimes" be ok if the 2 CUs are compatible with each other (you'll get a version warning) however if there is a database conversion between the two CUs then you will end up in a situation where you either have to convert your older version to use the newer executables, or if you pulled the older version last, you actually won't be able to access the new version any more until you re-pull the executables.

Perhaps instead of going directly into program files, the executables can be placed within a version-specific folder?

**Comment by freddydk** [comment]
The new-navcontainer creates a folder on the host in
"C:\DEMO\Extensions\<containerName>\Program Files
with the container and that is where the container will copy the executables.
This means that the binaries are container specific and the shortcuts for Cside is
"C:\DEMO\Extensions\test\Program Files\110\RoleTailored Client\finsql.exe" servername=test\SQLEXPRESS, Database=CronusDK, ntauthentication=yes, generatesymbolreference=yes
(includes databaseserver, instance and name)
This means that you can have any number of containers with any number of cside links.
the only thing that is shared is the dump of the base objects, but they are stored as version-country and they should never change base on that.

**Comment by MikeGlue** [comment]
double checked this as it was reported internally on my side.......probably should've made sure that the script being used wasn't modified to change the path :)
