### ISSUE TITLE
additionalParameters error with adding volume

### ISSUE THREAD

**Issue by thomasbook** [Microsoft/navcontainerhelper#200]
I've tried adding the parameter different was but not seem to accept the change?

$containername = 'apps-sandbox'
$navdockerimage = 'microsoft/bcsandbox:us'
$licenseFile = 'D:\Binn\Dev2018.flf'
$additionalParameters = @("--volume ""D:\Binn\Clients\bc-target:C:\run\my""")

New-NavContainer -accept_eula:$accept_eula `
    -containername $containername `
    -auth NavUserPassword `
    -includeCSide `
    -alwaysPull `
    -doNotExportObjectsToText `
    -usessl:$false `
    -updateHosts `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -shortcuts Desktop `
    -imageName $navdockerimage `
    -additionalParameters $additionalParameters
    

DockerDo : docker.exe: Error response from daemon: Duplicate mount point: c:\run\my.
See 'docker.exe run --help'.
Commandline: docker run --name apps-sandbox --hostname apps-sandbox --env auth=NavUserPassword --env username="twbook" --env ExitOnError=N --env locale=en-US --env 
licenseFile="c:\run\my\license.flf" --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\apps-sandbox\my:C:\Run\my" --restart unless-stopped --memory 4G --env enableApiServices=Y --env useSSL=N --volume 
"C:\ProgramData\NavContainerHelper\Extensions\apps-sandbox\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0
423413b16050a5345MgB8AHcAOABpAEcASAB4AE8AKwBJAFMAeAB5AHMAWgB5AG4AdQBqADAAWgA0AHcAPQA9AHwAYgA0ADYANwBlAGEANQA5AGUAZgAzADMANQBmADMANQBhADIAOQAzADgANQA3ADkAZQA5ADUAOAAxADkAMgBmADIAMgB
hADMAMAAyADgAMAA5AGYAMAA2ADcAMABiAGIAYQBmAGUAMQBjADUAYwA0ADQANQBiADYAMQAwADkAOQA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --volume 
"D:\Binn\Clients\bc-target:C:\run\my" --env accept_eula=Y --detach microsoft/bcsandbox:us
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.1\ContainerHandling\New-NavContainer.ps1:513 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by thomasbook** [comment]
At what point then can we use that parameter to change the folder it is pointing to?

**Comment by freddydk** [comment]
No, NavContainerHelper overrides some scripts based on your parameters, so it needs to be in control of the my folder.
It will always point to C:\ProgramData\NavContainerHelper\Extensions\<containername>\my
You can add scripts to override by specifying your files or folders to -myscripts - they will then be copied.
You can share other folders with the container if you are trying to share other things than script overrides (which is the my folders primary objective)

What are you trying to achieve?

**Comment by thomasbook** [comment]
I was looking to have the files exported to a custom location, though this would be a way to do it with the parameter available.  I will and a new volume for this now.

**Comment by freddydk** [comment]
c:\programdata\navcontainerhelper\extensions\containername is the same inside and outside the container - create a folder there and use that.
This location is cleaned up when deleting the container
