### ISSUE TITLE
Question - How to replicate the AppSource Validation?

### ISSUE THREAD

**Issue by catadumitru** [microsoft/navcontainerhelper#2002]
**Describe the issue**
We have made our app available to all countries on appsource and we would like to run the validation before submitting the app.
Now the number of countries available jumped from 44 to 65.
Is there a way to get the list of all available countries to build the list needed for the Run-AlValidation command?
Or hardcoding is the only option?

**Scripts used to create container and cause the issue**
```
$countries = "us,ch,be,cz,es,fi,fr,is,it,gb,nz,au,at,nl,no,se"

$validationResult = Run-AlValidation -licenseFile $licenseFile `
                                     -previousApps $previousApp `
                                     -apps $appFile `
                                     -validateCurrent `
                                     -sasToken $sastoken `
                                     -countries $countries `
                                     -affixes $affixes `
                                     -supportedCountries $countries `
                                     -containerName 'validation1'
```

**Comment by freddydk** [comment]
All additional countries are based on w1 - meaning that if you have one country included, which is based on w1, that should be fine.
Note that if you use -validateCurrent, it only validates on Current version.
If you remove that, it will also determine the lowest compatible version and validate on that (the application dependency in app.json) - the appsource validation process works like this.

**Comment by catadumitru** [comment]
Thanks for the clarification, I really appreciate all the work and help you provide!
