### ISSUE TITLE
Change GenerateReportLayout default to 'No' in Run-AlValidation

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#2003]
When we run the ALValidation the app is unpacked and recompiled for validation of the appsource rules.

IMHO, in this compilation process GenerateReportLayout should be set to 'No' by default since we want to validate the unmodified app as it was delivered.

**Comment by freddydk** [comment]
Agree

**Comment by freddydk** [comment]
Shipped in 2.0.15
