### ISSUE TITLE
Session has expired

### ISSUE THREAD

**Issue by cmasdev** [Microsoft/navcontainerhelper#201]
When I'm trying to access to the Web client I receive the message "Session has expired. Refresh the page to continue". When open the page I see this warning. How can I fix it?

**Comment by freddydk** [comment]
You probably have to give us some more info on this.
It is by design to show this when you have been away from the web client for some time - but do you get this all the time? are you unable to connect to the web client at all?

**Comment by cmasdev** [comment]
The problem was the Date/Time of the server. Changing that, the problem fixed. Thanks for your help.
