### ISSUE TITLE
Run-ALValidation Test Toolkit

### ISSUE THREAD

**Issue by miljance** [microsoft/navcontainerhelper#2010]
**Describe the issue**
As far as I have tested I do not see the possibility to install the Test Toolkit during Run-ALValidation. To my knowledge the Test Apps are not processed during AppSource validation but we still have to provide the Test app. Therefore it would make sense to be able to include the test app in this check at least from my point of view.

**Scripts used to create container and cause the issue**
```
$validationResults = Run-AlValidation `
    -licenseFile $license `
    -previousApps @(  ) `
    -apps @( "...") `
    -countries "de" `
    -affixes "DYCE" `
    -supportedCountries "de" `
```

**Full output of scripts**
```
BcContainerHelper is version 2.0.14
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.7
Docker Server Version is 20.10.7
```

**Comment by freddydk** [comment]
Run-AlValidation is ment to be a replica of the validation MS performs when you submit.
When we make changes to the validation process, this is reflected in Run-AlValidation as well.
Running tests, upgrade tests etc. should be part of your CI pipeline.

**Comment by miljance** [comment]
Thanks for the answer. Why do we have to supply the test App? Do you think this requirement will be removed then?

**Comment by freddydk** [comment]
It will be removed, yes.
I do not have an ETA

**Comment by miljance** [comment]
Thanks! Closing.
