### ISSUE TITLE
Cmdlet Import-PfxCertificateBcContainer doesnt work

### ISSUE THREAD

**Issue by ManuelvdM** [microsoft/navcontainerhelper#2011]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
After our certificate.pfx was expired, we have created a new pfx. When trying to update a existing bccontainer with the the cmdlet Import-PfxCertificateBcContainer nothing happens. Execution of the cmdlet is finished witout errors or information.
After a restart of the bccontainer, still the old certificate is being used.

**Scripts used to create container and cause the issue**
```
Import-PfxCertificateToBcContainer -containerName navserver -pfxCertificatePath "C:\ProgramData\BcContainerHelper\Extensions\navserver\my\certificate.pfx" -pfxPassword $password
```

**Full output of scripts**
```
NavContainerHelper is version 2.0.14
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter
Client: Docker Engine - Enterprise
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        0da829ac52
 Built:             06/26/2020 17:20:46
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Enterprise (Unlicensed - not for production workloads)
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.13.11
  Git commit:       0da829ac52
  Built:            06/26/2020 17:19:32
  OS/Arch:          windows/amd64
  Experimental:     false
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by freddydk** [comment]
The description of Import-PfxCertificateToBcContainer says:
Import a Pfx Certificate to the certificate store in a container
And this is what it does.
It does not reconfigure BC to use this certificate.

The Certificate can be used for accessing KeyVaults and/or AAD Apps for authentication.

Recommendation is to recreate the container if the certificate has expired.
If you are using an Azure VM (aka.ms/getbc) with Letsencrypt, then you can use Renew-LetsEncryptCertificate to renew that certificate.

**Comment by ManuelvdM** [comment]
Hi Freddy, thnx for your reply.
We have recreate the container, but still the old certificate is being used.
Can you tell me from which location the certificate is being pickup?

**Comment by freddydk** [comment]
How did you create the container?
Is this a aka.ms/getbc machine?

**Comment by ManuelvdM** [comment]
Hi Freddy,

It is fixed. We managed to perform the below steps:

Copy certificate.pfx to share folder (my folder)
Import PFX certificate inside the container
Enter-BcContainer navserver
$password = ConvertTo-SecureString -String '****' -AsPlainText -Force
Import-PfxCertificate -FilePath 'C:\Run\my\certificate.pfx' -Password $password -CertStoreLocation 'Cert:\LocalMachine\my'
Change Nav Server thumbprint
Set-NAVServerConfiguration -KeyName ServicesCertificateThumbprint -KeyValue ****** -Force -ServerInstance bc
Remove IISWebbinding
Remove-IISSiteBinding -Name navwebapplicationcontainer -Protocol https
Create new IISWEbbinding
New-IISSiteBinding -Name navwebapplicationcontainer -BindingInformation *:443: -CertificateThumbPrint "*****" -Protocol https -CertStoreLocation Cert:\LocalMachine\My
Restart bc container
Restart-BcContainer navserver

**Comment by freddydk** [comment]
Thanks for sharing

**Comment by pri-kise** [comment]
@ManuelvdM Thanks for sharing.
I used your notes to update my certifcate and ended up with the following script:

```ps
import-module bccontainerhelper
$containerName = "test-container"

$certPfxFile = "C:\myPath\xxx.pfx" 
$certPfxPassword = ConvertTo-SecureString -String "xxxx" -AsPlainText -Force

Import-PfxCertificateToBcContainer -containerName $containerName -pfxCertificatePath $certPfxFile -pfxPassword $certPfxPassword -ErrorAction Stop

$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2 -ArgumentList $certPfxFile,$certPfxPassword
$certificateThumbprint = $cert.Thumbprint
Invoke-ScriptInBcContainer -containerName $containerName -ScriptBlock { Param($certificateThumbprint)
    # Update ServerConfig
    Get-NAVServerInstance | Set-NAVServerConfiguration -KeyName ServicesCertificateThumbprint -KeyValue $certificateThumbprint -Force
    # Update IIS
    # 1. Remove Old Binding
    $defaultIISSiteBindingName = "navwebapplicationcontainer"
    Remove-IISSiteBinding -Name $defaultIISSiteBindingName -BindingInformation *:443: -Protocol https -Confirm:$false
    # 2. Create new IISWEbbinding
    New-IISSiteBinding -Name $defaultIISSiteBindingName -BindingInformation *:443: -CertificateThumbPrint $certificateThumbprint -Protocol https -CertStoreLocation Cert:\LocalMachine\My
} -ArgumentList $certificateThumbprint

# Restart to apply the changed settings
Restart-BCContainer $containerName
```
