### ISSUE TITLE
Preview build 2.0.15 preview456 is breaking our internal builds

### ISSUE THREAD

**Issue by florinangelescu** [microsoft/navcontainerhelper#2014]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
We have a regular build to test the compatibility with future releases of bccontainerhelper.
Since we started testing 2.0.15 a few days ago, we are encountering an issue coming from this block

`try {
    Add-Type -path (Join-Path $PSScriptRoot "Microsoft.ApplicationInsights.dll") -ErrorAction SilentlyContinue
} catch {}
$telemetryClient = New-Object Microsoft.ApplicationInsights.TelemetryClient
$telemetryClient.TelemetryConfiguration.DisableTelemetry = $true`

$telemetryClient.TelemetryConfiguration.DisableTelemetry - the attributes of this object do not exist and the module cannot be loaded.
If the module has some external dependencies, these should be mentioned in the manifest or automatically loaded.

**Full output of scripts**
`PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: The property 'TelemetryConfiguration' cannot be 
                        found on this object. Verify that the property exists. ---> 
                        System.Management.Automation.ParentContainsErrorRecordException: The property 
                        'TelemetryConfiguration' cannot be found on this object. Verify that the property exists.
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], RuntimeException
FullyQualifiedErrorId : PropertyNotFoundStrict
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Users\buildadmin.ne3fg7glsf33i\Documents\WindowsPowerShell\Modules\bcconta
                        inerhelper\2.0.15\BcContainerHelper.psm1: line 177
                        at Install-cdsaRepositoryModule, 
                        C:\Agent_work\21\s\DevOps.Builds\common\Install-cdsaPipelineModule.ps1: line 150
                        at <ScriptBlock>, C:\Agent_work\21\s\DevOps.Builds\common\Install-cdsaPipelineModule.ps1: line 
                        183
                        at <ScriptBlock>, C:\Agent_work\21\s\DevOps.Builds\ERP AL\Invoke-FullBuild-Prepare.ps1: line 30
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, C:\Agent_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.1
                        85.0\azurepowershell.ps1: line 232
                        at <ScriptBlock>, C:\Agent_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.1
                        85.0\azurepowershell.ps1: line 228
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 22
                        at <ScriptBlock>, <No file>: line 18
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}`

**Comment by freddydk** [comment]
There should not be any external dependencies - the DLL (Microsoft.ApplicationInsights.dll) should be part of the package as well and looking at PowerShell Gallery, it is:
![image](https://user-images.githubusercontent.com/10775043/127968902-631e9387-7b2c-49f5-ba0c-d932badda812.png)
Longshot: The problem might be that your session has an earlier version of the AppInsights dll loaded and then the Add-Type fails - which then causes the $telemetryClient to become another version of the class.
I will make this piece more resilient towards this - you can test out the next preview to see if this solves the issue.

**Comment by freddydk** [comment]
The latest preview should work for you.

**Comment by florinangelescu** [comment]
Thank you! Waiting to appear on PSGallery and will test it.

**Comment by freddydk** [comment]
Shipped in 2.0.15
