### ISSUE TITLE
Create container with option FilesOnly doesn't create the folder .NetAssemblies

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/navcontainerhelper#2018]
Created a container with options -FilesOnly and -IncludeAL

With normal containers the -IncludeAL will copy .Net assemblies to .\extensions\<Container>\.NetPackages
When using -FilesOnly this folder is missing.

My idea would be I could use the container with -FilesOnly to compile my extensions (no publish obviously)

Full script...
```
$ImageName = "local"
New-NavContainer -licenseFile $LicenseFile `
    -accept_eula `
    -containerName $ContainerName `
    -auth NavUserPassword `
    -Credential $credential `
    -updateHosts `
    -memoryLimit 15G `
    -isolation hyperv `
    -additionalParameters $AdditionalParameters `
    -artifactUrl $ArtifactURL `
    -multitenant $false `
    -includeAL -filesOnly

```

**Comment by freddydk** [comment]
Shipped in 2.0.15
