### ISSUE TITLE
New-NavContainer IOException when -navDvdPath is used with .zip file

### ISSUE THREAD

**Issue by cyranothedaft** [Microsoft/navcontainerhelper#202]
New-NavContainer consistently fails to remove the temporary directory into which it extracted the DVD zip file, possibly because Docker maintains a handle on it as a mapped volume.  This causes the function to fail with an IOException.

Attachments explained:
command.txt - the New-NavContainer command that was run (and a few possibly-relevant preliminaries)
output.txt - the function's output captured from the PowerShell window, including the error message
handle.txt - the output from running Handle.exe for the in-use temp directory

[command.txt](https://github.com/Microsoft/navcontainerhelper/files/2398694/command.txt)
[output.txt](https://github.com/Microsoft/navcontainerhelper/files/2398695/output.txt)
[handle.txt](https://github.com/Microsoft/navcontainerhelper/files/2398696/handle.txt)

**Comment by freddydk** [comment]
Next version will move the NAVDVD temp folder to the container folder under c:\programdata\navcontainerhelper\extensions\<containername>\NAVDVD where it will be deleted when the container is removed.
Thanks for reporting.

**Comment by cyranothedaft** [comment]
Sounds great!  Thank you!

**Comment by freddydk** [comment]
Shipped in 0.3.1.3
