### ISSUE TITLE
WriteErrorException in New-NavContainer

### ISSUE THREAD

**Issue by msinha82** [Microsoft/navcontainerhelper#203]
This is a new machine upgraded from Win7 to Win10Pro today.
### Expected behavior
Nav container devbcnz successfully created
### Actual behavior
Error :
PS C:\WINDOWS\system32> New-NavContainer -containerName devbcnz -accept_eula -accept_outdated -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox:nz -includeCSide -memoryLimit 3G -shortcuts Desktop -updateHosts -useSSL
Pulling docker Image microsoft/bcsandbox:nz
nz: Pulling from microsoft/bcsandbox
Digest: sha256:de570de953db0b247a604747da76126f5c4e441ba7de1fd56ef656f08171676d
Status: Image is up to date for microsoft/bcsandbox:nz
Creating Nav container devbcnz
Using image microsoft/bcsandbox:nz
NAV Version: 12.3.23590.23945-NZ
Generic Tag: 0.0.6.5
Container OS Version: 10.0.14393.2430
Host OS Version: 10.0.17134.0
The container operating system does not match the host operating system, forcing hyperv isolation.
Removing devbcnz from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\devbcnz
Creating container devbcnz from image microsoft/bcsandbox:nz
DockerDo : docker.exe: Error response from daemon: container 2a6cab166b28ecf79c21f1f9033afb80090d913d4c4ab5c21a43f6d31ed2b7ac 
encountered an error during CreateContainer: hcsshim: timeout waiting for notification extra info: {"SystemType":"Container","Name":"
2a6cab166b28ecf79c21f1f9033afb80090d913d4c4ab5c21a43f6d31ed2b7ac","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"
C:\\ProgramData\\Docker\\windowsfilter\\2a6cab166b28ecf79c21f1f9033afb80090d913d4c4ab5c21a43f6d31ed2b7ac","Layers":[{"ID":"53cf3c5e-4
8e1-5306-9419-533b45e0267e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\9c2b14bd95a4eff6e4e4fbbbf5f264b01c699288162019e997993db86
d05ab2a"},{"ID":"74b5eaf8-03f6-5e0d-acaf-35091417fbb6","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ad47ea9ab37f943f50855ada4bb03a
7e9f7677d29aafc88711a35b75274714e3"},{"ID":"70bf89c6-547f-5962-ba69-9203f8d1d542","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cab
9e97688d615a9dfe9f335e0d55242f174423b1f1d451ad5219743bbdba548"},{"ID":"2e09884b-4c3c-57e3-87d5-5abab56cdf3a","Path":"C:\\ProgramData\
\Docker\\windowsfilter\\5b9c2b6d4af66c70e43379dbfb2ae5fc69ef55ad5c6c418948a21d9980f4ed37"},{"ID":"8f65d04b-2fd8-5beb-87db-4dd8820e39a
0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\61e75f9e0e0233604a228c8506c73f34c0cfed0bd6a54e545d09899c310ecc90"},{"ID":"37266166
-ccb6-5639-831a-70e8b11f2e06","Path":"C:\\ProgramData\\Docker\\windowsfilter\\803529cb94cd898a29032d6985070b3b68dbc173b0db270a92de53b
165b512dd"},{"ID":"99d9e024-b760-5fd5-8d3f-834a776ab7ad","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0b85b30213230a561f30a22975d8
1fe4dba12a005efcb89da5972fd52ef7a635"},{"ID":"d32d4603-509c-5e2a-8836-e28294f7c3db","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1
7be33a7abfd964f0cba5479376f57e458765c6eecf1c3075acf8a26a0008f90"},{"ID":"3b8651ef-f9c6-5081-98a5-4a2d565d35d1","Path":"C:\\ProgramDat
a\\Docker\\windowsfilter\\df1bfeef1c55670fe094f67e9d76fb1fe97e9e7577ec2d3e7c21549eb3113b01"},{"ID":"c4405620-efcd-536e-b07d-886daa25d
509","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e0a6ea1939cee215c12e3cc0bcbdbec3754f80da91e5f87f9557410a62cd4b8e"},{"ID":"a1233f
10-0821-55b8-ae3a-03fcc691976e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\13457124d5ba63deda3ac1fadfb26b6623feb0276203b869088ff
85d88cb83ee"},{"ID":"472caa2a-7237-5ce7-9557-8e84f34b5257","Path":"C:\\ProgramData\\Docker\\windowsfilter\\af06fa8c9b9a822dbc59c34337
edfba467e8587b0d26edbf399a18124dd85d78"},{"ID":"b5c95ca6-ca7b-574f-80ff-e8dfe4b0c276","Path":"C:\\ProgramData\\Docker\\windowsfilter\
\dedc443b27d3fa42345d2291f9092f70ec4dcc255636c91b5c20a022f7614439"},{"ID":"74f04429-381c-575d-a2ef-a0e0c31f3f99","Path":"C:\\ProgramD
ata\\Docker\\windowsfilter\\3201cf0e5c287e9ae0b44248cbf4e32465e3efb5c62876c6a66afa8a5f8aa823"},{"ID":"a238f6aa-64be-54d1-a17d-ee30cec
2297e","Path":"C:\\ProgramData\\Docker\\windowsfilter\\84256022544aa643a4d638160f466b2b84c3b2186d12080c838a9cd8915f701e"},{"ID":"3671
a2a8-a4aa-5f72-a40c-902116ce0260","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eb0353b39a157677957b1ab0261ae91e966a9ce11f5fec23a62
0990844174f87"},{"ID":"45d8ee33-96f0-5bb9-a111-c3525a51ecf2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\05082ca2c7a59c941b8d800e
8feca7b9baa67adc7190f0ddfe302688d3c9190d"},{"ID":"79962cc4-5370-5e81-9922-1f3d5e78f6bb","Path":"C:\\ProgramData\\Docker\\windowsfilte
r\\925a34c4ae2a4b7867c9d1f99a71370ab95b94cc10bc395a357b285a99a87125"},{"ID":"3008f2b0-0f5a-559f-acef-4a3d33969ee9","Path":"C:\\Progra
mData\\Docker\\windowsfilter\\142ab7d4df5c9b8b06cbc389b2e699c60b97d765f5240a611cfab0be91d1cd8d"},{"ID":"0391d9f3-6dc6-5645-94e1-0c50d
302a786","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b8ec4048328908636b54e5b76feaf4e7fbed4cc798fe5b5a72aa70a4e8e8a819"},{"ID":"fb
416a5e-02ad-5856-a6f8-32ce9d7461d5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\25f2d2ab03d2f12a995fb36e9d291bb27b68bcf628275a916
819b2073ea63c2b"},{"ID":"6d64f010-2271-532b-b6f9-14275da29a40","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cf4272dd0598ebe91845df
174390a646d378a4f64e3172055c56463df977532f"}],"MemoryMaximumInMB":3072,"HostName":"devbcnz","MappedDirectories":[{"HostPath":"c:\\win
dows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtility
VM":false},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\devbcnz\\program files","ContainerPath":"c:\\navpfiles","Rea
dOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper","Conta
inerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"Ho
stPath":"c:\\programdata\\navcontainerhelper\\extensions\\devbcnz\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaxim
um":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["582c8667-7e5d-4dde-af72-808b098297b9"],"HvRunti
me":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\25f2d2ab03d2f12a995fb36e9d291bb27b68bcf628275a916819b2073ea63c2b\\UtilityVM
"},"AllowUnqualifiedDNSQuery":true}.
ExitCode: 125
Commandline: docker run --name devbcnz --hostname devbcnz --env auth=NavUserPassword --env username="admin" --env ExitOnError=N 
--env locale=en-NZ --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\devbcnz\my:C:\Run\my" --restart unless-stopped --memory 3G --isolation hyperv --env 
enableApiServices=Y --env enableSymbolLoading=Y --env useSSL=Y --volume 
"C:\ProgramData\NavContainerHelper\Extensions\devbcnz\Program Files:C:\navpfiles" --volume 
"c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8ADkANABwAEYAZwBFAGIAWgBFAHoA
YwBqAHkASgBGADQAeABMAEoASgBDAGcAPQA9AHwAOAA5ADEAZABmADYANwA2ADcAMAA0AGUAZgBlADEANAA3AGEAMQAyAGIAMwA3ADcAZQBmAGEANQBlAGEAMgA0AGQAOQBlA
GQAOAA0ADQANQA3ADgAMABlADgAOAAzAGUAMgA1AGEANQBjADgANgAwAGQANwA3AGIAZgAzADQAOAA= --env passwordKeyFile="c:\run\my\aes.key" --env 
removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach microsoft/bcsandbox:nz
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.2\ContainerHandling\New-NavContainer.ps1:530 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
 
PS C:\WINDOWS\system32> 

### Information

  - Windows Version: Win 10 Pro
  - Docker for Windows Version: CE 18.06.1-ce-win73(19507)

### Steps to reproduce the behavior

  1. Install docker.
  2. Run below command in PowerShell (Run as Administrator)

Set-ExecutionPolicy Unrestricted

Install-Module -Name navcontainerhelper

docker pull microsoft/bcsandbox:nz

New-NavContainer -containerName devbcnz -accept_eula -accept_outdated -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox:nz -includeCSide -includeTestToolkit -memoryLimit 4G -shortcuts Desktop -updateHosts -useSSL

**Comment by freddydk** [comment]
Seems like a lot of people are having this issue, but it isn't related the the nav containers.

https://github.com/Microsoft/hcsshim/issues/152

Haven't ready though all, but did you run all windows updates before installing docker?

**Comment by EasyStep2Lean** [comment]
Any news on this issue?

**Comment by msinha82** [comment]
Last weekend I tried but no luck. 
1. Reinstall docker
2. Download fresh image 
Lets hope this weekend I will find some new error text at least.

**Comment by freddydk** [comment]
I think the error is related to windows 10 and the hardware you are running on.
It could also be related to the version of the containers - currently they are ltsc2016.
If you have a NAV DVD zip file - you could try (with a new navcontainerhelper) and run new-navcontainer -accept_eula -navdvdpath <location of zip> - this should run the right generic images and just-in-time install the dvd.
If this works, then we know that once Windows Server 2019 ships (happend in October) the problem might be solved.

**Comment by freddydk** [comment]
If you update your NavContainerHelper and specify -useBestContainerOS, then it should work now. Read more here: https://blogs.msdn.microsoft.com/freddyk/2018/10/24/windows-10-and-docker-images-for-business-central-nav/
