### ISSUE TITLE
The import failed and the encryption key file cannot be decrypted

### ISSUE THREAD

**Issue by EniShima** [microsoft/navcontainerhelper#2035]
Hi Freddy, I have a problem when I'm trying to create a container with a license key. It shows an error message when the system tries to import the license key, and I don't know how to fix it. The license file worked correctly before. 

![errir1234](https://user-images.githubusercontent.com/25667122/130263984-d2028b46-1234-44f8-bea1-46210a93a6f5.png)

I don't know what is the cause of the problem. I have used the same script before and it was ok .

**Comment by freddydk** [comment]
It isn't the license file, it is the encryption key file.
I know that some people have had problems the GMSa. I never used that and probably cannot help you much if you do.
I assume you specify database credentials somewhere as well - the encryption keys are cached (encrypted with the database password) and reused.
You can try to set 
$bccontainerhelperconfig.useSharedEncryptionKeys = $false
or you can make sure the database credentials are the same.

**Comment by freddydk** [comment]
Did this solve the issue?

**Comment by zaxie** [comment]
I do get the same error when trying to create a new container with external database.
I have tried with BC 14.27 with the standard cronus db.
If testing with latest BC18.4 and cronus it works fine.

I do get BC14.27 with cronus db to work when using $bccontainerhelperconfig.useSharedEncryptionKeys = $false.
However I still get issues with my customer db with same BC14.27 and external db.  Customers db is a standard system with no customization or extensions installed.
This procedure to setup a customer test system has worked before flawless.

I tries with database credentials on the external sql and UserPassword credentials on Container.

Parameters;
-enableSymbolLoading: True
-isolation: process
-includeTestFrameworkOnly: False 
-databaseCredential: System.Management.Automation.PSCredential 
-containerName: customer 
-includeTestLibrariesOnly: False 
-credential: System.Management.Automation.PSCredential 
-memoryLimit: 5G 
-databaseServer: DEVELOPER 
-databaseName: customer 
-accept_eula: True 
-artifactUrl: https://bcartifacts.azureedge.net/onprem/14.27.47563.0/se 
-includeTestToolkit: False 
-includeCSIDE: True 
-auth: UserPassword 
-licenseFile: D:\LicenseFiles\Sweden BC_14 Developer License.flf 
-updateHosts: True

**Comment by freddydk** [comment]
@cmuris you are right
I will modify the sharedencryptionkey feature to store the encryption key with a major version number.
It is primarily useful for having multiple containers connect to the same database and this should be fine.

**Comment by freddydk** [comment]
Fixed in 2.0.19
