### ISSUE TITLE
Tenant could not be mounted because  of missing apps although the apps are installed

### ISSUE THREAD

**Issue by elweilando** [microsoft/navcontainerhelper#2037]
I am trying to install an online database in a local sandbox. For this I followed the principle of https://freddysblog.com/2021/03/02/restoring-your-online-business-central-database-locally/. But a little bit modified.
- I have taken the same sandbox version as the online version
- I exported the app database from the sandbox as bacpac and imported it into azure sql
- I exported a backup of the online tenant and imported it as bacpac into azure sql
- I start the local sandbox as multitenant and take app-database on azure sql
- I publish all non defaults apps in the app-database

This works up to here without problems

Then I mount the tenant database from azure sql and get the message

```
The tenant default could not be mounted because the following installed NAV extensions are missing, matching content
could not be found, or have a higher version than those that are published and synchronized:
```

But only for a few extensions - not for all. The missing extensions are installed with the same name, publisher and version like I can see in the tenant database in `Select * from [dbo].[NAV App Installed App]`. These apps are installed before the tenant backup was created. They are the same.

Does anybody know why this happens or how can I investigate in that?

**Comment by freddydk** [comment]
Did you try Get-BcContainerEventLog to see if there is any info in the eventlog about which app and whY?

**Comment by elweilando** [comment]
In the Eventlog I can only see the same error like in powershell.
There are a total of 13 non-default apps published in the app database, but 6 have this error.

Type: System.ServiceModel.FaultException`1[[Microsoft.Dynamics.Nav.Types.ServerFault, Microsoft.Dynamics.Nav.Types, Version=18.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]
Action: http://www.microsoft.com/Dynamics/NAV/51/ServerFault
Message:
  The tenant default could not be mounted because the following installed NAV extensions are missing, matching content could not be found, or have a higher version than those that are published and synchronized: 
 "app" by publisher, version 18.1801.20210615.0
  "app" by publisher, version 4.2.0.0
  "app" by publisher, version 18.0.0.1
  "app" by publisher, version 18.0.9.0
  "app*" by publisher, version 17.4.1.28
  "app" by publisher, version 18.0.1.1.
StackTrace:
  
  Server stack trace: 
     at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
  
  Exception rethrown at [0]: 
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at Microsoft.Dynamics.Nav.Types.ITenantManagementService.MountTenant(MountTenantArguments mountTenantArguments)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.MountNavTenant.MountUsingServer(NavTenantSettings settings)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.MountNavTenant.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: mscorlib
HResult: -2146233087
StackTrace:
  
  Server stack trace: 
     at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
     at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
     at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)
  
  Exception rethrown at [0]: 
     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
     at Microsoft.Dynamics.Nav.Types.ITenantManagementService.MountTenant(MountTenantArguments mountTenantArguments)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.MountNavTenant.MountUsingServer(NavTenantSettings settings)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.MountNavTenant.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()

**Comment by freddydk** [comment]
Did you try with a SQL Server on the host (like the blog post describes)?
Does that give the same problem?

**Comment by elweilando** [comment]
It is the same problem.
I have installed a local SQLExpress on the host and imported the app database and backup with the management studio as bacpac.

**Comment by freddydk** [comment]
OK - did you try to run a SQL script to modify the Package ID in the database?

**Comment by elweilando** [comment]
I was able to fix it by adjusting the PackageIds.

**Comment by freddydk** [comment]
Could you share the script (SQL statements)?

**Comment by lippertmarkus** [comment]
Here's the container script part we used in AdditionalSetup.ps1 to mount the tenant from a SaaS backup (after publishing and installing all needed apps before):
```powershell
Write-Host "HANDLING SaaS BAKFILE"

$bak = $env:saasbakfile
$tenantId = "saas"

Write-Host " - Restoring SaaS db"
New-NAVDatabase -DatabaseServer $DatabaseServer `
                    -DatabaseInstance $DatabaseInstance `
                    -DatabaseName "$tenantId" `
                    -FilePath "$bak" `
                    -DestinationPath "$databaseFolder" `
                    -Timeout $SqlTimeout -Force | Out-Null

Write-Host " - Adapting package IDs"
$diffPackageIds = Invoke-Sqlcmd -Query "select da.[App ID], da.[Package ID] FROM [default].[dbo].[NAV App Installed App] da JOIN [$tenantId].[dbo].[NAV App Installed App] ta ON da.[App ID] = ta.[App ID] AND da.[Version Major] = ta.[Version Major] AND da.[Version Minor] = ta.[Version Minor] AND da.[Version Build] = ta.[Version Build] AND da.[Version Revision] = ta.[Version Revision] AND da.[Package ID] != ta.[Package ID]"
foreach ($app in $diffPackageIds) {
    Invoke-Sqlcmd -Database $tenantId -Query "UPDATE [dbo].[NAV App Installed App] SET [Package ID] = '$($app.'Package ID')' WHERE [App ID] = '$($app.'App ID')'"
}

Write-Host " - Replacing default tenant database with new SaaS database"
Dismount-NAVTenant -ServerInstance $ServerInstance -Tenant "default" -Force
Invoke-SqlCmd -Query "alter database [default] set single_user with rollback immediate; DROP DATABASE [default]"
Invoke-SqlCmd -Query "ALTER DATABASE $tenantId SET SINGLE_USER WITH ROLLBACK IMMEDIATE; ALTER DATABASE $tenantId MODIFY NAME = [default]; ALTER DATABASE [default] SET MULTI_USER"
$tenantId = "default"

Write-Host " - Mounting SaaS tenant"
Mount-NavTenant `
    -ServerInstance $ServerInstance `
    -id $tenantId `
    -databasename $tenantId `
    -databaseserver $DatabaseServer `
    -databaseinstance $DatabaseInstance `
    -EnvironmentType Sandbox `
    -OverwriteTenantIdInDatabase `
    -Force

Write-Host " - Syncing new tenant"
Sync-NavTenant `
    -ServerInstance $ServerInstance `
    -Tenant $tenantId `
    -Force

Write-Host " - Syncing all apps"
for ($i = 0; $i -lt 10; $i++) {
    Get-NAVAppInfo -ServerInstance $ServerInstance -Tenant $tenantId | Sync-NAVApp -ServerInstance $ServerInstance -Tenant $tenantId -ErrorAction silentlycontinue -WarningAction silentlycontinue
}

Write-Host " - Upgrading all apps"
Get-NAVAppInfo -ServerInstance $ServerInstance -Tenant $tenantId | Start-NAVAppDataUpgrade -ServerInstance $ServerInstance -Tenant $tenantId -ErrorAction silentlycontinue

Write-Host " - Upgrading tenant"
Start-NAVDataUpgrade `
        -ServerInstance $ServerInstance `
        -Tenant $tenantId `
        -Force `
        -FunctionExecutionMode Serial `
        -SkipIfAlreadyUpgraded
Get-NAVDataUpgrade `
    -ServerInstance $ServerInstance `
    -Tenant $tenantId `
    -Progress

Write-Host " - Create user in new tenant"
New-NAVServerUser -ServerInstance $ServerInstance -Tenant $tenantId -UserName $env:username -Password $securePassword
New-NAVServerUserPermissionSet -ServerInstance $ServerInstance -Tenant $tenantId -UserName $env:username -PermissionSetId SUPER

Write-Host " - Importing License to new tenant"
Invoke-Sqlcmd -Database $tenantId -Query "truncate table [dbo].[Tenant License State]"
Import-NAVServerLicense -ServerInstance $ServerInstance -Tenant $tenantId -LicenseFile "$runPath\license.flf" -Database Tenant
Set-NAVServerInstance -ServerInstance $ServerInstance -Restart
```
