### ISSUE TITLE
Production BOM area and related functionality not visible when creating container via using Sandbox artifact

### ISSUE THREAD

**Issue by jaromirchaloupka** [microsoft/navcontainerhelper#2039]
**When creating BC container via using artifact of -type Sandbox (or if not defined -type at all) then Production BOM page and all related functionality is not visible in web client. I tried to install BC container for W1, FR and CZ but still the same result. Once I created BC container via using artifact of -type OnPrem then Production BOM page and all related content is normally visible.**

**Scripts used to create container and cause the issue**
```
New-BcContainer -accept_eula `
                -accept_outdated `
                -assignPremiumPlan `
                -containerName $containerName `
                -artifactUrl (Get-BCArtifactUrl -storageAccount bcartifacts -select Latest -type Sandbox) `
                -auth $auth `
                -credential $credential `
                -updateHosts -dns '8.8.8.8' `
                -includeAL `
                -enableTaskScheduler `
                -multitenant:$false `
                -licenseFile $licenseFile
```

**Scripts used to create container which is working as expected**
```
New-BcContainer -accept_eula `
                -accept_outdated `
                -assignPremiumPlan `
                -containerName $containerName `
                -artifactUrl (Get-BCArtifactUrl -storageAccount bcartifacts -select Latest -type OnPrem -country "w1") `
                -auth $auth `
                -credential $credential `
                -updateHosts -dns '8.8.8.8' `
                -includeAL `
                -enableTaskScheduler `
                -multitenant:$false `
                -licenseFile $licenseFile
```

**Full output of scripts**
Both scripts above work fine = no issues during creation of containers. The only problem is in the web client as for container created from Sandbox artifact the Production BOM page and related content is not visible.

**Comment by freddydk** [comment]
That is likely because the user doesn't have premium plan assigned.
Try to add -assignPremiumPlan and/or use the Setup-BcContainerTestUsers command to create test users with different entitlements.

**Comment by jaromirchaloupka** [comment]
Hi Freddy, thank you very much. I used AssignPremiumPlan and also executed Setup-BcContainerTestUsers command but what really helped me to solve the issue and be able to see Production BOM page was to change User Experience from Essential to Premium on Company Information page. We can close this issue. Thank you. Have a good day.
