### ISSUE TITLE
Business Inbox fail when using Create-AadAppsForNav

### ISSUE THREAD

**Issue by AskeHolst** [Microsoft/navcontainerhelper#204]
I set up a fresh (alwayspull) bcinsider.azurecr.io/bcsandbox-master:base container with AAD and ran Create-AadAppsForNav and Create-AadUsersInNavContainer today.
Logging in to the web client using AAD works fine and the Edit-in-Excel also works, I take that as the registrations in AzureAD went well (I see them in the portal).

If I run the assisted setup for "Setup you Business Inbox in Outlook" I get the add-ins in Outlook as expected. When opening the add-in taskpane I get the following message:
![image](https://user-images.githubusercontent.com/8398485/45810842-ec154500-bccb-11e8-874a-ab7561bfbb0e.png)
Pressing OK just empties the pane. Same behavior in both desktop Outlook and Outlook online.

Trying to inspect the traffic I see a call to https://outlook.office365.com/owa/service.svc?action=GetClientAccessToken&EP=1&ID=-60&AC=1 which returns a "Success" response with a token. Next call is to https://REDACTED.pgseu.com/nav/auth?OfficeContext=Outlook-TaskPane&Version=2.0.0.0&et=&dc=tablet&aid=NAV giving the error "code":-32000 and the response above. So it seems to be my BC instance not liking the token it gets. 

Now I don't know if I'm missing something or this is just not part of what the navcontainerhelper can help with. But I'm quite stuck and trying to port over an outlook add-in that worked fine on NAV2018 so I really need the sandbox to test and just getting the default add-ins running is the first step. 

I can add that I even set up another sandbox with NavUserPassword and the results are the exact same.

**Comment by freddydk** [comment]
Is this the first time you have done this - or did this use to work?
Are you running single tenancy or multi-tenancy?

**Comment by AskeHolst** [comment]
It is the first time I try the outlook add-in on a BC sandbox. It worked fine on NAV2018 containers. 
Single tenancy.

**Comment by freddydk** [comment]
This might be because the BC Sandbox inside thinks that it is a Business Central Online Sandbox.
This is the reason for Edit In Excel not working.
Since you do have access to bcinsider - you can try the on-prem Business Central containers:
bcinsider.azurecr.io/bconprem:w1 (this is fall release RC3 just announced today)
And see if this resolves the issue.

**Comment by AskeHolst** [comment]
Edit In Excel _does_ work, which made me think Outlook might also work.
I'll try the onprem and get back, hopefully with good results :-)

**Comment by AskeHolst** [comment]
Same result with the bconprem image.
I was wondering is anything additional needs to be set up, similar to adding the ExcelAddInAzureActiveDirectoryClientId to the instance configuration?

**Comment by freddydk** [comment]
In the c:\myfolder\SetupConfiguration.ps1, there are two lines commented out.
Could you try to uncomment these and run Replace-NavServerContainer?
These lines are setting the AzureAadClientId and Secret.

**Comment by AskeHolst** [comment]
Unfortunately I have a "clean" VM so I cannot use the Replace-NavServerContainer or have the same demo setup folders. The SetupConfiguration.ps1 I have in my container has no commented lines.
I could spin up a new VM using aka.ms/getnav if that makes it easier to troubleshoot.

**Comment by freddydk** [comment]
If you ran Create-AadUsersInNavContainer - which values did you then set in your customsettings.config?

**Comment by AskeHolst** [comment]
Nothing, never thought of it as logging in with AAD and everything else just worked after running Create-AadUsersInNavContainer, but maybe I was just lucky.

**Comment by freddydk** [comment]
You can see here: https://github.com/Microsoft/nav-arm-templates/blob/master/SetupNavContainer.ps1 which values I set in the SetupConfiguration override, which ends up being set inside the container.

**Comment by AskeHolst** [comment]
Went for a new VM from aka.ms/getnav (that sure is a nice experience, thanks!). 
As Replace-NavServerContainer creates new App-registrations manual changes to SetupConfiguration.ps1 made no differences. So I ended up uncommenting the two commented lines in SetupNavContainer.ps1 where it generates SetupConfiguration.ps1 

The problem is not really solved though. I found add-in does work, but only using Outlook Online, not desktop Outlook. And only after first logging in to BC in another tab first keeping that tab open. And not with Chrome and Opera (IE, Edge and Firefox works using the BC tab first trick). 

After finding out that I needed to test with Outlook Online on Edge and open BC first I tried going back to not setting ClientID and Secret, that gives the exact same result, not better or worse.
Setting ClientID and Secret might still be needed for a complete solution, but it seems to not be enough.

**Comment by DagPilaro** [comment]
Hi,
@AskeHolst, have you found a solution for this Issue? I think this is the same problems that I have reported here: https://github.com/Microsoft/navcontainerhelper/issues/279. 
I am always starting my demoes in Outlook - this has not been possible in BC onprem/docker..

**Comment by AskeHolst** [comment]
I have not yet found a way to get it running with docker. Except running it in Outlook online in IE after logging into BC first in another tab, but that of course times out.

**Comment by DagPilaro** [comment]
Hi,

Thanks for your feedback, then it looks as we have to wait.. 😢

Fra: Aske Holst <notifications@github.com>
Sendt: mandag 10. desember 2018 10:57
Til: Microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Kopi: Dag Salvesen <dag.salvesen@pilaro.no>; Comment <comment@noreply.github.com>
Emne: Re: [Microsoft/navcontainerhelper] Business Inbox fail when using Create-AadAppsForNav (#204)


I have not yet found a way to get it running with docker. Except running it in Outlook online in IE after logging into BC first in another tab, but that of course times out.

**Comment by freddydk** [comment]
This will be fixed in the next rebuild of images.
I will also add a fix to navcontainerhelper if you are using old images.

**Comment by freddydk** [comment]
Shipped in 0.4.3.1

**Comment by AskeHolst** [comment]
Tested and working both for onPrem and sandboxes! To think that one small missing file could cause me so much grief. 
Thank you so much for fixing this, this is seriously the best thing to happen all week.

**Comment by freddydk** [comment]
Thanks for the nice words.
Have an amazing weekend:-)
