### ISSUE TITLE
Alternative to Docker Desktop

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#2051]
I saw that "docker desktop" changes his subscription, is there any alternative so I can still use bccontainerhelper? or does it only workes with "docker desktop"?

https://www.docker.com/blog/updating-product-subscriptions/

is there any tutorial on how to use bccontainerhelper with windows containers in azure?

**Comment by freddydk** [comment]
Docker Desktop will add a small price for companies with more than 250 users or more than 10mio in revenue.
Docker EE is included in Windows Server licensing
Docker binaries are open source and free you might see blog posts from people showing how to install docker binaries directly.
Windows Containers is a foundation for docker, but cannot be used alone.
ContainerHelper works with any version of Docker, but needs docker.

**Comment by freddydk** [comment]
https://freddysblog.com/2021/10/30/docker-and-business-central/
