### ISSUE TITLE
Which licenses are required to use BcContainerHelper and Docker?

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#2052]
Please allow to ask question I have seen and heard many times the last few days. Which licenses are required to use BcContainerHelper? 

When it comes to the use on "developer machines" with Windows 10 and Docker Desktop, it used to be free. But that has changed. Two days ago Docker announced that *The use of Docker Desktop now requires a paid subscription (Pro, Team, or Business), for as little as $5 a month, for professional use in larger enterprises (more than 250 employees OR more than $10 million in annual revenue). The effective date of these terms is August 31, 2021. There is a grace period until January 31, 2022 for those that will require a paid subscription to use Docker Desktop.* Here it is pretty clear, who must pay and who must not. 

But what if you are running BcContainerHelper with Docker on a Windows Server 2019 machine? 
Here Docker Desktop is not used, instead we install the Docker Microsoft Provider using PowerShell. This is, or at least I thought it was, to install Docker Enterprise. Which maybe is free when used on Windows Server 2016 and 2019, even if its no longer Docker, but the company Mirantis who bought the Enterprise edition from Docker last year.

The topic is discussed other places, without anyone having the clear answer:
https://github.com/OneGet/MicrosoftDockerProvider/issues/84
https://github.com/microsoft/Windows-Containers/issues/135
https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1350

It seems that the Docker Microsoft Provider uses the same Docker/DockerD executables as Docker Desktop, even if I thought it was Docker Enterprise Edition. 

So would that mean we also need to buy licenses for all our Azure build and test VM's, if we use BcContainerHelper and Docker containers here? 

And how would we even count it, when most of the VM's live longer than 1-2 hours?

**Comment by freddydk** [comment]
Windows Server includes a license for Docker EE (DockerMsftProvider), which is owned by Mirantis.
Docker Desktop is for Windows 10 and is owned by Docker, this is the one, which has a new and changed license.
The docker engine is open source and free - you can build it yourself.
BcContainerHelper is open source and free, I build and publish that for you:-)
Tobias describes things here: https://tobiasfenster.io/news-in-the-windows-container-and-docker-world

**Comment by freddydk** [comment]
You might have read the other blog from Tobias talking about upcoming changes with Mirantis.
I don't know if we are going to change anything based on this.

**Comment by slonopotamus** [comment]
You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install modern Docker engine for Windows containers on both Windows Server/Client.

**Comment by freddydk** [comment]
Thanks for mentioning that project. Might be useful for some people.

I have described here: https://freddysblog.com/2021/10/30/docker-and-business-central/ what I am doing - installing/updating docker engine using a PowerShell script.
