### ISSUE TITLE
BcSaaS scripts only works on MS (businesscentral.dynamics.com) environment

### ISSUE THREAD

**Issue by ricardopaiva** [microsoft/navcontainerhelper#2060]
**Describe the issue**
Base Url is hardcoded on BcSaaS related scripts so it's not possible to use the scripts with other environments other than the Microsoft's one.

A pull request will be open with suggested changes.

**Comment by freddydk** [comment]
a function like InstallAppFromAppSource will only work on BC Saas - that would not run on any self hosted environments?
Or are you talking about embed offerings here?

**Comment by ricardopaiva** [comment]
Hi,

I'm talking about embed offerings.
We have a partner who's setting up the Automation API and using the **Publish-PerTenantExtensionApps** method to publish their extensions automatically but the base url is hardcoded.
It would be great to have a way of providing a different url, to be used on embed offerings.
Maybe I've made changes on more functions than I should... not sure about it...

Thanks

**Comment by freddydk** [comment]
That makes 100% sense.

Will review the PR today

**Comment by freddydk** [comment]
have requested a very small change in the PR

**Comment by ricardopaiva** [comment]
PR updated. Thanks.

**Comment by freddydk** [comment]
I will revert the change again, I ran into some issues and will make the change in a different way.
The URLs are also used during compile and publish functions, and these functions are called from run-pipeline etc. etc.
This means that we will have to carry the URL's to all functions and it becomes a source of error if somebody forgets.
Instead, I will add the two URLs to configuration, meaning you can set them once and they will be used all over.
Like this:
![image](https://user-images.githubusercontent.com/10775043/132937030-8584663a-a440-434f-a0fb-13cafc0457ae.png)

You can also set the values in c:\programdata\bccontainerhelper\bccontainerhelper.config.json

**Comment by ricardopaiva** [comment]
Agree.
People would have to make sure they don't forget to add the custom url to any one of the functions where the parameter was added.
It is less error-prone to have it setup in a single place.
I can do the change for you, if you want, and submit the PR.

**Comment by ricardopaiva** [comment]
It seems like you have already made the change. Awesome! Thanks.

**Comment by freddydk** [comment]
The latest preview version of ContainerHelper has these changes, let me know when you have a chance of testing these with your offering.

Thanks

**Comment by freddydk** [comment]
Shipped in 2.0.16

**Comment by freddydk** [comment]
@ricardopaiva - can you tell me what you use as scope/resource when you create a bcAuthContext for this function?
@eclipses  is trying to do the same as you did here

thanks

**Comment by ricardopaiva** [comment]
Hi @freddydk,
I haven't tried but a few partners did. Unfortunately we never got any feedback confirming which scope worked for them.
But according to @eclipses, it seems like "https://api.businesscentral.dynamics.com/.default" is the correct scope to be used even in an embed environment.

**Comment by freddydk** [comment]
I just managed to get an environment setup - and as eclipses says - it needs to be the api.... url - I have changed this in the next BcContainerHelper.
