### ISSUE TITLE
Error Creating Container

### ISSUE THREAD

**Issue by ricardonunesevosoft** [microsoft/navcontainerhelper#2064]
it seems that it doesn't recognize the host build (Windows 10 latest) and it's trying to pull windows server one?  How to solve this?

BcContainerHelper is version 2.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - **Unknown/Insider build**
Docker Client Version is 20.10.7
Docker Server Version is 20.10.7
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.20348.169
10.0.20348.169: Pulling from businesscentral
DockerDo : **a Windows version 10.0.20348-based image is incompatible with a 10.0.19043 host**
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/businesscentral:10.0.20348.169
At C:\Users\ricar\OneDrive\Documentos\WindowsPowerShell\Modules\BcContainerHelper\2.0.7\ContainerHandling\New-NavContainer.ps1:726 char:13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
What is the host windows version (what does winver show?)

**Comment by ricardonunesevosoft** [comment]
Hi Freddy,

               Good morning. Here’s the version

               ***@***.***

               Thanks

Best regards,

Ricardo Nunes
Office: +353 21 4355201
Direct: +353 21 2340150
Download Remote Support<https://get.teamviewer.com/848ch45>
***@***.******@***.***>
http://www.evosoftireland.com<http://www.evosoftireland.com/>
4 Bruach na Laoi, Union Quay, Cork.

***@***.***

Consider the environment. Please don't print this e-mail unless you really need to.

CONFIDENTIALITY: The contents of this e-mail and any attachment are the property of Evo-Soft Ireland Limited. The above message and/or the attachment is contractor/client privileged and/or confidential and is for the use of the addressee only. If you receive this communication in error please notify this office immediately and delete all copies from your computer systems. Any reader of this message, who is not the intended recipient or the employee or agent responsible to deliver the message to the intended recipient, is hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. Subsequent alterations to this electronic message after its transmission will be disregarded.  Please note that e-mails sent to and from Evo-Soft Ireland Limited are routinely monitored for record keeping, quality control and training purposes, to ensure regulatory compliance and to prevent viruses and unauthorized use of our computer systems. All quotes are subject to Evo-Soft Ireland Limited standard terms and conditions.

**Comment by yrest** [comment]
Windows version 10.0.20348-based image is incompatible with a **10.0.19043 host**

**Comment by freddydk** [comment]
@ricardonunesevosoft - that didn't show anything.
10.0.19043.1165 (which is my version) doesn't select 10.0.20348
Maybe you should start by updating the containerhelper, run again and then post full script and full output (as much as possible)

**Comment by ricardonunesevosoft** [comment]
@freddydk updating the containerhelper did the trick. Thanks for your help
