### ISSUE TITLE
S2S Authentication no longer working in 18.4 environments?

### ISSUE THREAD

**Issue by vvkjndl** [microsoft/navcontainerhelper#2066]
**Describe the issue**
I am using the Publish-PerTenantExtensionApps function to deploy my apps using S2S authentication as stated in Kauffman blogs and Micorosoft's ci/cd PDF document. However, just recently, I am now getting 401 Unauthorized errors.

Am I missing something or something changed in 18.4 release?

**Scripts used to create container and cause the issue**
```
This is a cloud environment.
```

**Full output of scripts**
```
Attempting authentication...
Authenticated as app ....
Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.
BcSaas\Publish-PerTenantExtensionApps.ps1:74 char:22
...
```

**Screenshots**
N/A

**Additional context**
- Yes, for >= 18.4 environments.
- It works on my 18.3 environments.

Any help or pointers will really be appreciated.

**Comment by freddydk** [comment]
Did you remember to add the clientId in the environment (allowed aad apps?)

**Comment by vvkjndl** [comment]
Yes, it's there. The name of the option is "Azure Active Directory Services".

I created a new record with the client ID, granted consent and added the Automation and EXTN MGT permissions.

Is "Allowed AAD Apps" a different option than "Azure Active Directory Services".

**Comment by freddydk** [comment]
No, nothing has changed there between 18.3 and 18.4 - we are probably looking for differences in your setup

**Comment by vvkjndl** [comment]
Yes, you are right, I upgraded my 18.3 tenant to 18.4 and S2S still works.

I am following the steps carefully as stated in Kauffman blog and ci/cd document, but still not get through this.

Any pointers in troubleshooting would be helpful.

**Comment by vvkjndl** [comment]
This issue has been resolved.

Cause: I was using Microsoft Azure's tenant Login ID while accepting the Consent Popup dialog.

Resolution:

- I granted admin consent within Microsoft Azure using Application Administrator.
- Then, I used the BC Cloud Tenant Login ID while accepting the Consent Popup dialog.
