### ISSUE TITLE
New-BcImage - incorrect evaluation resulting $forceRebuild is true always for us.

### ISSUE THREAD

**Issue by Koubek** [microsoft/navcontainerhelper#2069]
Hi Freddy,

finally, we use **BcContainerHelper** to rebuild images but I noticed (quite a long time ago) these have to be rebuilt always even it's not practically necessary. At least this is my feeling.

As we support multi-os images and we build more and more today this is getting to be more and more visible as the build times are just more obvious (I can control this from the management tool but I would prefer this happens on the build servers out of the box by the proper detection in your scripts).

First of all, there is a smaller detail here (should be **country** and not **Version** in the message, isn't it?):
https://github.com/microsoft/navcontainerhelper/blob/9a0f8f73d0b84921894f4ec0bde78bea55093341/ContainerHandling/New-NavImage.ps1#L213

What is more important is the part in the next lines of code where you evaluate labels. And some of the previous lines:
- ```Get-BcContainerImageLabels``` doesn't work properly for (local) images with ```\``` included. We use them also on local images to make the situation a bit cleaner. I think the problem is here:
https://github.com/microsoft/navcontainerhelper/blob/9a0f8f73d0b84921894f4ec0bde78bea55093341/ContainerInfo/Get-NavContainerImageLabels.ps1#L26
The previous could be there but it would be better IMHO to try also ```docker inspect``` with ```try ... catch``` so you would be able to get the information directly by using ```docker inspect``` on the local image (if downloaded already).
Maybe I don't get purpose of the skipping on those images including ```\```. Anyway, if I want to rebuild them from scratch, I always have (the default) option to do so by omitting ```--skipIfImageAlreadyExists```.
- So ok, the previous doesn't return labels on cached images and then you don't let us use our base images IMHO. Please, see the following where I try to explain why do I see it's impossible (maybe I am wrong):
https://github.com/microsoft/navcontainerhelper/blob/9a0f8f73d0b84921894f4ec0bde78bea55093341/ContainerHandling/New-NavImage.ps1#L201 - It doesn't accept ```-registryCredential``` to be bypassed. I just want to tell, we use authenticated (private) ACR.
- Thanks to the missing labels, the evaluation in the following fails here:
https://github.com/microsoft/navcontainerhelper/blob/9a0f8f73d0b84921894f4ec0bde78bea55093341/ContainerHandling/New-NavImage.ps1#L216 and the code terminate here (```$label``` is always null or an empty string, I don't remember now):
https://github.com/microsoft/navcontainerhelper/blob/9a0f8f73d0b84921894f4ec0bde78bea55093341/ContainerHandling/New-NavImage.ps1#L250 which causes the image has to be build again. Always!!!

**Comment by freddydk** [comment]
- On the Get-BcContainerLabels - that one was created when we had specific images and I used the / to determine whether the image was local or from the mcr. If the image is local+mcr, it is important that the function returns the values from mcr - else it will never detect whether there is a new generic version available. I will move the local attempt behind the mcr attempt, meaning that if no image was found on mcr, it will always try local.

- Beside that, I will add registryCredential (for baseimage) to New-BcImage.

I assume these two should fix your issues right?

**Comment by freddydk** [comment]
could you test this?

**Comment by Koubek** [comment]
I will test it and let you know. Thanks Freddy.

**Comment by Koubek** [comment]
I can confirm it works now ;) Thanks for a quick help!!!
