### ISSUE TITLE
Compile-AppInNavContainer is downloading symbols for app which is in the AppSymbolFolder

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#207]
The symbol download in Compile-AppInNavContainer is triggered when the file "appname.app" does not exists, even when there is app named as standard names it - "publisher_appname_version.app". It leads to downloading apps which are not in the DB, even when the app is in the folder.

The process should follow the naming rules or should use the info from the .app files to check if the app is in the folder or not. Using simplified names is not working correctly.

**Comment by freddydk** [comment]
Agree, 100% - will fix this
