### ISSUE TITLE
Looks like security update KB5005568 causes container to use HyperV

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/navcontainerhelper#2081]
Today below package was installed on our build server

![image](https://user-images.githubusercontent.com/33791875/133497321-e81cefc2-400d-4ad3-b407-e270639292e7.png)

This causes the containers to switch from process to hyperv. Which was not installed and broke the build

Disabling Health Check (always report healthy)
Creating Container C103833
Version: 18.4.28601.29407-NL
Style: sandbox
Multitenant: No
Platform: 18.0.28593.29261
Generic Tag: 1.0.1.7
Container OS Version: 10.0.17763.2114 (ltsc2019)
Host OS Version: 10.0.17763.2183 (ltsc2019)
Using hyperv isolation
Using locale nl-NL
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Agent\_work\1\s\ERP AL\licenses\dev-bc.flf
Additional Parameters:
-e customNavSettings=FeatureSwitchOverrides=disableSmartListActions,EnableTaskScheduler=True
-v C:\Agent\_work\1\a\Assemblies:c:\run\Add-ins
-v "C:\Agent\_work\1\s\ERP AL\tenantExtensions:c:\s-tenantExtensions"
-v "C:\Agent\_work\1\s\ERP AL\Extensions:c:\s-Extensions"
-e customNavSettings=UsePermissionSetsFromExtensions=false,EnableTaskScheduler=True
Files in C:\ProgramData\BcContainerHelper\Extensions\C103833\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupAddIns.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container C103833 from image local:sandbox-18.4.28601.29407-nl
8a3ab8f284be12e6192c94735789449ad5815d08d0dcb9afa19331798053ad6d
 Finishing: Create container - 0m 3s
Disconnect-AzAccount -Scope Process -ErrorAction Stop
Clear-AzContext -Scope Process -ErrorAction Stop
##[error]docker: Error response from daemon: hcsshim::CreateComputeSystem 8a3ab8f284be12e6192c94735789449ad5815d08d0dcb9afa19331798053ad6d: The virtual machine could not be started because a required feature is not installed.

**Comment by freddydk** [comment]
In this case, you managed to update the host before we managed to publish the corresponding generic images.
That can happen, if you want to be sure to run process isolation, you need to specify -isolation process.

**Comment by RonKoppelaar** [comment]
Freddy are new generic images run in parallel with bccontainerhelper upgrades, or are they independent?

**Comment by freddydk** [comment]
Independent 
Actually my bccontainerhelper build yesterday broke because of the missing container os builds.
Luckily, it seems that with Windows 11, the need for exact match between host and container OS goes away.

**Comment by freddydk** [comment]
new generic images have been deployed
