### ISSUE TITLE
Question: how to set the test runner codeunit when using Run-TestsInBcContainer

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#2084]
### Issue
When running API tests the test isolation of the test runner should be **disabled**. When running tests through ` Run-TestsInBcContainer` on a virgin BC container, however, will use the default test runner **130450 - Test Runner - Isol. Codeunit**.

### Quesrion
How can I script changing the test runner to **130451 - Test Runner - Isol. Disabled**, where it seems not to be available as parameter for ` Run-TestsInBcContainer`?

**Comment by freddydk** [comment]
That wasn't really supported.
I have added a parameter: TestRunnerCodeunitId to Run-TestsInBcContainer.
If you download this .zip file: https://github.com/microsoft/navcontainerhelper/archive/refs/heads/master.zip
unpack and in the session where you run the tests run the BcContainerhelper.ps1 then you will use a dev version with this parameter.
I will check it in - but it takes some hours to build and test the module.

**Comment by freddydk** [comment]
The parameter is in the latest preview version

**Comment by lvanvugt** [comment]
Thanx. Did not have time to test it. Too busy teaching juniors this week. ;-)

**Comment by lvanvugt** [comment]
BTW: also tried with additional parameter `-testPage 130455`, but did not help.

**Comment by freddydk** [comment]
Did you recreate the container?

**Comment by lvanvugt** [comment]
Nope. For what reason should I?

**Comment by freddydk** [comment]
PSTestFunctions.ps1 is updated in the new containerhelper - that one is copied to a folder under the container when the container is created - meaning that you are still using the old one.
Either update that script manually, delete the folder it is in (under extensions\containername) or recreate the container

**Comment by lvanvugt** [comment]
Alright!!!!!! Running the script........

**Comment by lvanvugt** [comment]
Youhou!

![image](https://user-images.githubusercontent.com/18466198/134350280-9d9c002d-b638-4865-a27c-4c25fced433b.png)

**Comment by lvanvugt** [comment]
Thanx @freddydk.
