### ISSUE TITLE
User created on Docker Container but Password does not work

### ISSUE THREAD

**Issue by fibbert** [Microsoft/navcontainerhelper#209]
I am running Docker on a Virtual Server 2016 stand alone server. I created a local user Rob with a simple password. I am using the local users and groups, have not installed AD on the server.  It is a stand alone machine.

I create a docker container using the Dynamics 365 Business Central SANDBOX (Container) Script.

The docker seems to be created properly.  The output of the docker creation is below. Running Get-LocalUser on the Docker Powershell shows the user Rob. I also tried using Set-LocalUser to change the password of the user in the Docker container.

I have tried bcsndbx\rob, rob, Rob etc... to log in when prompted.  The password I enter when prompted for credentials does not work.  If I override to use NavUserPassword I can connect, but this is not ideal.

This is my first time working with Docker and I cannot find a solution to this issue (except maybe gMSA) 

Any ideas? Do I need to install AD?

Pulling docker Image microsoft/bcsandbox:ca
ca: Pulling from microsoft/bcsandbox
Digest: sha256:2b0312cd2e1a7abcb59f71c9119bc182a53eef4dd9a0eb68a4e8c97df6e5c0d6
Status: Image is up to date for microsoft/bcsandbox:ca
Removing C:\ProgramData\NavContainerHelper\Extensions\bcsndbx
Creating Nav container bcsndbx
Using image microsoft/bcsandbox:ca
NAV Version: 12.3.23590.23945-CA
Generic Tag: 0.0.6.5
Container OS Version: 10.0.14393.2430
Host OS Version: 10.0.14393.0
Creating container bcsndbx from image microsoft/bcsandbox:ca
Waiting for container bcsndbx to be ready
Initializing...
Starting Container
Hostname is bcsndbx
PublicDnsName is bcsndbx
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user Rob
Setting SA Password and enabling SA
Creating SUPER user
Assign Premium plan for BCSNDBX\ROB
Container IP Address: 172.25.208.133
Container Hostname  : bcsndbx
Container Dns Name  : bcsndbx
Web Client          : http://bcsndbx/NAV/
Dev. Server         : http://bcsndbx
Dev. ServerInstance : NAV

Files:
http://bcsndbx:8080/al-0.16.26913.vsix

Initialization took 106 seconds
Ready for connections!
Set TimeZone in Container to Pacific Standard Time
Reading CustomSettings.config from bcsndbx
Creating Desktop Shortcuts for bcsndbx
Nav container bcsndbx successfully created
Downloading C:\Users\ADMINI~1\AppData\Local\Temp\1\CreateTestUsers.fob
Copy C:\Users\ADMINI~1\AppData\Local\Temp\1\CreateTestUsers.fob to container bcsndbx (c:\run\CreateTes
tUsers.fob)
Importing Objects from c:\run\CreateTestUsers.fob (container path)
Objects successfully imported

Client:
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:43:19 2018
 OS/Arch:      windows/amd64

Server:
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.24)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:52:17 2018
  OS/Arch:      windows/amd64
  Experimental: false

**Comment by freddydk** [comment]
It looks like you are running Windows Authentication and that the user on the host is ADMINI1.
If you are running Windows Auth. you need to create the container with the same user as you are running on the host.
If you want to be running Username Password auth - you need to specify -auth with NavUserPassword.

**Comment by fibbert** [comment]
I tried using administrator but I am having the same problem.  This is the result of my whoami command.

I tried connecting to the C/AL Dev environment as SA and it is using the correct password.

C:\Users\Administrator>whoami
win-5nk1eaafvfi\administrator

**Comment by freddydk** [comment]
So the password is correct, but clearly there is a difference on the username.
Normally I just remove the -credentials from new-navcontainer then it finds out what username is needed and I enter the password.
Some networks needs -updatehosts in the new-navcontainer but I don't think that is your problem.

**Comment by fibbert** [comment]
I built a second container bcsndbx2 and I used the Administrator account - same behaviour.  

IE and Chrome just keep asking me over and over the the password.
