### ISSUE TITLE
BC Container Fonts

### ISSUE THREAD

**Issue by BozidarP** [microsoft/navcontainerhelper#2097]
Hello, 

I try to add fonts in the container but I got this error:
![image](https://user-images.githubusercontent.com/44054400/135317336-4e189f47-27c7-45f8-8823-ed6604a73484.png)
I don't get "normal" letters in Reports. 
I use BC Container Helper ver 2.0.0.15

Windows/Fonts container content:
![image](https://user-images.githubusercontent.com/44054400/135318257-90c05dda-b460-44c3-89fa-999d4e35aace.png)

**Comment by BozidarP** [comment]
Hello, 

I try to add fonts in the container but I got this error:
![image](https://user-images.githubusercontent.com/44054400/135317336-4e189f47-27c7-45f8-8823-ed6604a73484.png)
I don't get "normal" letters in Reports. 
I use BC Ccntainer Helper ver 2.0.0.15

**Comment by freddydk** [comment]
Instead of providing an image, please use dir > x,txt and copy/paste the content of this text file.

**Comment by BozidarP** [comment]
Please, 
If you need something else
[contentFonts.txt](https://github.com/microsoft/navcontainerhelper/files/7257974/contentFonts.txt)
[error.txt](https://github.com/microsoft/navcontainerhelper/files/7257975/error.txt)
:

**Comment by freddydk** [comment]
I have added some resilience to the code.
I cannot say that this solves your issue, but there is a high likelyhood it will
The next containerhelper will ship later today and you can try with that, thanks

**Comment by BozidarP** [comment]
Ok, thanks, Freddy. I will inform you.

**Comment by freddydk** [comment]
Shipped in 2.0.16

**Comment by freddydk** [comment]
Please re-open if this doesn't solve the problem

**Comment by BozidarP** [comment]
The situation is the same.
[BCHelper_Ver_16.txt](https://github.com/microsoft/navcontainerhelper/files/7265072/BCHelper_Ver_16.txt)

**Comment by BozidarP** [comment]
@freddydk  I cant reopen the issue.

**Comment by freddydk** [comment]
Did you change the hostHelperFolder in c:\programdata\bccontainerhelper\bccontainerhelper.config.json?

**Comment by freddydk** [comment]
How did you create the container?
Script and output please?

**Comment by BozidarP** [comment]
Script:
New-BCContainer -accept_eula -accept_outdated -containerName BCv18-4-Practice-2021 -artifactUrl "https://bcartifacts.azureedge.net/onprem/18.4.28601.29139/w1" -includePlatform -auth NavUserPassword updateHosts -isolation Process -multitenant=N -usetraefik

This is ARM Template, aka.ms/getbc

**Comment by freddydk** [comment]
I have tried to create a VM using https://aka.ms/getbc - create the container using:

```
New-BCContainer `
    -accept_eula `
    -containerName BCv18-4-Practice-2021 `
    -artifactUrl "https://bcartifacts.azureedge.net/onprem/18.4.28601.29139/w1" `
    -includePlatform `
    -auth NavUserPassword `
    -updateHosts `
    -isolation Process
```
and adding fonts:
```
Add-FontsToBcContainer -containerName "BCv18-4-Practice-2021"
```
Works fine.

If I am to investigate further, I probably need access to a VM where this fails.
