### ISSUE TITLE
SecondToLastMajor artifacts missing

### ISSUE THREAD

**Issue by printvisdevelopment** [microsoft/navcontainerhelper#2098]
**Describe the issue**
Pipelines that run against second to last version are failing because we can't retrieve the artifacts.
For the latest version there is no problem

**Scripts used to create container and cause the issue**
```
 Get-BCArtifactUrl -storageAccount bcinsider -type Sandbox -country w1 -select SecondToLastMajor -sasToken $InsiderSasToken 
```

**Full output of scripts**
```
there is no output
```

**Additional context**
- did it use to work?
- Yes, it started failing today

**Comment by freddydk** [comment]
You should use **Select NextMinor** and **Select NextMajor** instead of the SecondToLastMajor.

**Comment by printvisdevelopment** [comment]
NextMinor gives a 19.0 and NextMajor 19.1
We would like to keep testing on 18, for ex: 18.6. That's why we were using SecondToLastMajor.
I can't seem to get 18.6, I also tried 
Get-BCArtifactUrl -storageAccount bcinsider -type Sandbox -country w1 -version 18 -select Latest -sasToken $InsiderSasToken
it doesn't return anything

**Comment by freddydk** [comment]
Correct.
There is nothing called 18.6 - and there will never be for sandbox containers.
After 18.5 comes 19.0
and I would not expect there to be any 18 builds on insider due to retention policy.

**Comment by printvisdevelopment** [comment]
Thank you for clarification!
