### ISSUE TITLE
CSide Container - Missing msvcp120.dll, msvcr120.dll

### ISSUE THREAD

**Issue by ewaldventer** [Microsoft/navcontainerhelper#21]
Even though all prerequisites are installed, have to manually copy these to the container rtc folders.

**Comment by freddydk** [comment]
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/

a. Are you missing the prerequisites?
Whether you are running CSide using Click-Once, through the navcontainerhelper or you manually copied the binaries to a shared folder, you need to have the pre-requisites installed on the computer on which you are running CSide.

If CSide complains about missing DLL's or giving an ODBC error, you probably need to install these pre-requisites:

https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
https://download.microsoft.com/download/3/A/6/3A632674-A016-4E31-A675-94BE390EA739/ENU/x64/sqlncli.msi

**Comment by ewaldventer** [comment]
Thank you, missed vcredit_x86.exe

**Comment by rkirsten** [comment]
https://download.microsoft.com/download/3/A/6/3A632674-A016-4E31-A675-94BE390EA739/ENU/x64/sqlncli.msi results in a 404. 

This seems to be the correct, current one: https://www.microsoft.com/de-de/download/details.aspx?id=50402

**Comment by freddydk** [comment]
This is the URL I use today:
https://download.microsoft.com/download/B/E/D/BED73AAC-3C8A-43F5-AF4F-EB4FEA6C8F3A/ENU/x64/sqlncli.msi
