### ISSUE TITLE
$accesstoken variable in Run-TestsInBcContainer

### ISSUE THREAD

**Issue by vvkjndl** [microsoft/navcontainerhelper#2103]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I am currently migrating our BC Containers from `-auth UserPassword` to `-auth AAD`.

I am not sure on how to generate an access token for a specific user for a local BC instance running in Docker container.

I have already tried passing WebAccessKey as access token, it didn't work.

**Scripts used to create container and cause the issue**
```
Run-TestsInBcContainer `
    -containerName $ContainerName `
    -tenant $TenantId `
    -companyName $runTestsInCompany `
    -credential $credential `
    -accessToken $tenantpassword ` # this is the webaccesskey
    -XUnitResultFileName $xunitResultsFile `
    -extensionId $app.AppId `
    -disabledTests $disabledTests
```

**Full output of scripts**
```
Currently not applicable.
```

**Screenshots**
Currently not applicable.

**Additional context**
- does it happen all the time?
Yes, on containers built using `-auth AAD`
- did it use to work?
Yes, on containers built using `-auth UserPassword`

Freddy. are there any known solutions to make `Run-TestsInBcContainer` work on local AAD containers?

**Comment by freddydk** [comment]
For AAD auth, you should use New-BcAuthContext and then use that.
This should work towards local AAD containers as well (with the right parameters), but I haven't tried.
If it doesn't work, I will fix the errors.

**Comment by vvkjndl** [comment]
@freddydk I made up the parameters and I'm trying this:

$ContainerName = "vjaad"
$TenantId = "tnt1"

```
$bcauthcontext = New-BcAuthContext -Resource "https://$ContainerName`:7048/BC/api/v2.0" -tenantID "?tenant=$TenantID" -credential $bcadmcred -scopes "https://$Containername`:7048/BC/api/v2.0/.default" -authority "https://$ContainerName/BC/SignIn/?tenant=$TenantID"
```

**Comment by freddydk** [comment]
What is the output of the function?

**Comment by vvkjndl** [comment]
Function output:

```
Attempting authentication to https://vjaad:7048/BC/api/v2.0/?tenant=tnt1 using username/password...
The property 'access_token' cannot be found on this object. Verify that the property exists.

Authentication failed
```

**Comment by freddydk** [comment]
Ok, I would need to debug and see the content of the token returned in line 133 in New-BcAuthContext.ps1
It seems like something is returned, but not what is expected in the script.

**Comment by vvkjndl** [comment]
I will look into those lines as well.

**Comment by vvkjndl** [comment]
@freddydk In the case of $credential, we are creating below token headers:

    $TokenRequestParams = @{
        Method = 'POST'
        Uri    = "$($authority.TrimEnd('/'))/oauth2/token"
        Body   = @{
            "grant_type" = "password"
            "client_id"  = $ClientId
            "username"   = $credential.UserName
            "password"   = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($credential.Password))
            "resource"   = $Resource
        }
    }

Do we need clientID to be passed for local container with AAD auth?

I am under the impression that New-BcAuthContext is not designed to generate access tokens for local AAD containers.

If you can give me any pointers on this issue, I'll be happy to do the testing and submit a pull request.

**Comment by vvkjndl** [comment]
@freddydk Hi Freddy, any update on when we can have the ability to run Tests on containers with AAD auth?

**Comment by freddydk** [comment]
Hope to be able to look at this next week.

**Comment by vvkjndl** [comment]
@freddydk We are still looking forward to this.

I have been digging the Run-TestsInContainer.Ps1 and PsTestTool.ps1 to find any workarounds.

So far I was able to accomplish this:

- I created a user inside tenant.
- Generated WebServicesKey for it.
- Declared serviceurl and credentials variable.
`$serviceurl = "https://vjaad:443/BC/cs?tenant=tnt1"; $tenantcredential = [pscredential]::new("UserPlaceholder@inecta.com", $(ConvertTo-SecureString -String "WebServicesKeyPlaceholder" -AsPlainText -Force))`
- Imported needed assemblies using Add-Type.
`
Microsoft.Dynamics.Framework.UI.Client.dll
Newtonsoft.Json.dll
`
- Opened ClientContext successfully.
`$clientcontext = [ClientContext]::new($serviceurl, $tenantcredential)`
- Fails while opening form.
`$clientcontext.OpenForm("130455")`
`ERROR DIALOG: You do not have access to . Verify that you have been set up as a valid user in .`

**Comment by freddydk** [comment]
WebServiceKey is for web service access.
Run-TestsInBcContainer uses client services and emulates a user session - web service key cannot be used for that.


I am working on this right now and it should be done some time this week.
It did require quite some work (rewrite of bcauthcontext to use oauth2 v2.0) - but in the latest containerhelper pre-release version, it actually should work. I can run this on my machine (with the latest containerhelper prerelease):

```
$containerName = "bcserver"
$licenseFile = $LicenseFileSecret.SecretValue | Get-PlainText
$credential = New-Object pscredential -ArgumentList 'admin', $PasswordSecret.SecretValue
$artifactUrl = Get-BCArtifactUrl -country us -type OnPrem
$aadCredential = New-Object pscredential -ArgumentList ($AadUserNameSecret.SecretValue | Get-PlainText), $AadPasswordSecret.SecretValue

$useSSL = $true
$params = @{ "useSSL" = $useSSL }
if ($useSSL) {
    $protocol = "https://"
    $params += @{
        "isolation" = "hyperv"
        "installCertificateOnHost" = $true
    }
}
else {
    $protocol = "http://"
}

$aadTenant = $aadCredential.UserName.Split('@')[1]
$appIdUri = "$protocol$containerName.$aadTenant/BC"

$AdProperties = Create-AadAppsForBC `
    -AadAdminCredential $aadCredential `
    -appIdUri $appIdUri `
    -publicWebBaseUrl "$protocol$containerName/BC" `
    -PreAuthorizePowerShell

New-BcContainer @params `
    -containerName $containerName `
    -accept_eula `
    -artifact $artifactUrl `
    -auth AAD `
    -Credential $credential `
    -licenseFile $licenseFile `
    -includeTestToolkit -includeTestFrameworkOnly `
    -updatehosts `
    -AuthenticationEMail $AadCredential.UserName `
    -AadAppId $AdProperties.SsoAdAppId `
    -AadAppIdUri $appIdUri

$authcontext = New-BcAuthContext -credential $aadCredential -scopes "$appIdUri/" -tenantID $aadTenant
Run-TestsInBcContainer -containerName $containerName -bcAuthContext $authContext
```

**Comment by vvkjndl** [comment]
@freddydk Referring to this code I integrated the needful changes on my functions.

I confirm that I was now able to run Tests on AAD containers.

Thanks much Freddy, as always.
