### ISSUE TITLE
Container creation stuck in: "Waiting for container xxx to be ready"

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#2104]
Hi Freddy,

I'm creating a new BC container in a new laptop and facing this issue, the container has been created but the script get stuck with the message "Waiting for container xxx to be ready"

I tried to debug the script, the message comes from Wait-NavContainerReady.ps1 file 

The process when get the logs  

```
$logs = docker logs $containerName
```

contains already the full log including the "Ready for connections!" string but the script continue calculating the variable $log that will be always empty entering in an infinite loop. 

BcContainerHelper version 2.0.15
Docker Client and Server version 20.10.8
Host Microsoft Windows 10 Enterprise - 1909

Same script in a different computer works correctly. Not sure if this laptop is too slow or too fast. First time facing this issue.

To test, you can try to call Wait-NavContainerReady function for an existing container

**Comment by freddydk** [comment]
Very strange - will have a look

**Comment by freddydk** [comment]
I will add some resilience to this part to avoid this scenario.

**Comment by freddydk** [comment]
Shipped in 2.0.16

**Comment by eclipses** [comment]
Thank you for the quick fix, it works correctly
