### ISSUE TITLE
The parameter is incorrect. ExitCode: 125

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#2109]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Not sure if it connected to https://github.com/microsoft/navcontainerhelper/issues/2086 or if it is a different issue. But in trying to get the system up and running again, I've run into a different errormessage. I've reset everything I can imagine, deleted all images containers, pruned the system and  deleted the data-root. Thinking that it might be some refrence issue, I 've only added the imagename and now I am getting a parameter error.

**Scripts used to create container and cause the issue**
```
$containerName = 'lanitol'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '18.2' -country 'dk' -select 'Latest'
$licenseFile = 'd:\nav\infar\udvikling\bc18.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'bc18cu2' `
    -licenseFile $licenseFile `
    -updateHosts```

**Full output of scripts**
```
Default parameter Isolation = Process
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 21H1
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Removing lanitol from container hosts file
Removing lanitol-* from container hosts file
Removing D:\NAVData\ContainerHelper\Host\Extensions\lanitol
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
INFO: Windows 10 21H1 images are not yet available, using 2004 as these are found to work better than 20H2 on 2
1H1
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.1
9041.1237
Fetching all docker images
Building image bc18cu2:onprem-18.2.26217.26490-dk based on mcr.microsoft.com/businesscentral:10.0.19041.1237 wi
th https://bcartifacts.azureedge.net/onprem/18.2.26217.26490/dk
Pulling latest image mcr.microsoft.com/businesscentral:10.0.19041.1237
10.0.19041.1237: Pulling from businesscentral
295f12394c4f: Already exists
5910daff7c6f: Pulling fs layer
b34642b347fc: Pulling fs layer
.
.
.
0eebdf174f77: Pull complete
2b961c4525d9: Pull complete
20be9a8c82d4: Pull complete
Digest: sha256:16a380c3a0a014f941a4a055f035c06f17674f8388121632f80920d0f78154dc
Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.19041.1237
mcr.microsoft.com/businesscentral:10.0.19041.1237
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19041.1237 (2004)
Host OS Version: 10.0.19043.1237 (21H1)
Using Process isolation
Using license file d:\nav\infar\udvikling\bc18.flf
Files in D:\NAVData\Artifacts\xur5sljr.vu3\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Applications
D:\NAVData\Artifacts\xur5sljr.vu3
Sending build context to Docker daemon  1.665GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.19041.1237
 ---> 7f58d7f88574
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactU
rl=https://bcartifacts.azureedge.net/onprem/18.2.26217.26490/dk filesOnly=False
 ---> Running in ab0a56cfe7be
Removing intermediate container ab0a56cfe7be
 ---> b40ecfc7d2b8
Step 3/6 : COPY my /run/
 ---> 74b03eed4e87
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 0e4f65328ba2
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in 5891187b6859
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation
Changing Database Server Collation to Danish_Greenlandic_100_CI_AS
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
C:\NAVDVD\WebClient\Microsoft Dynamics NAV
Copying Client Files
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\systemFolder
Copying ModernDev Files
C:\NAVDVD
C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\NAVDVD\ConfigurationPackages
Copying Test Assemblies
C:\NAVDVD\Test Assemblies
Copying Applications
C:\NAVDVD\Applications
Starting Business Central Service Tier
Importing CRONUS license file
Stopping Business Central Service Tier
Installation took 196 seconds
Installation complete
Removing intermediate container 5891187b6859
 ---> f89b70ac60c7
Step 6/6 : LABEL legal="http://go.microsoft.com/fwlink/?LinkId=837447"       created="202110031823"       nav="
"       cu=""       country="dk"       version="18.2.26217.26490"       platform="18.0.26213.26464"
 ---> Running in 9af66d7eed4b
Removing intermediate container 9af66d7eed4b
 ---> a675e7d9313c
Successfully built a675e7d9313c
Successfully tagged bc18cu2:onprem-18.2.26217.26490-dk
Building image took 978 seconds
Using image bc18cu2:onprem-18.2.26217.26490-dk
Creating Container lanitol
Style: onprem
Multitenant: No
Version: 18.2.26217.26490
Platform: 18.0.26213.26464
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19041.1237 (2004)
Host OS Version: 10.0.19043.1237 (21H1)
Using Process isolation
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file d:\nav\infar\udvikling\bc18.flf
Files in D:\NAVData\ContainerHelper\Host\Extensions\lanitol\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container lanitol from image bc18cu2:onprem-18.2.26217.26490-dk
eacc644fae9fc4ecd579a582110f9e36044e29abcdc84fcaeb6468b2acabee7c
DockerDo : docker: Error response from daemon: hcsshim::CreateComputeSystem 
eacc644fae9fc4ecd579a582110f9e36044e29abcdc84fcaeb6468b2acabee7c: The parameter is incorrect.
ExitCode: 125
Commandline: docker run --env licenseFile="c:\run\my\license.flf" --name lanitol --hostname lanitol --env 
auth=NavUserPassword --env username="admin" --env ExitOnError=N --env locale=da-DK --env databaseServer="" 
--env databaseInstance="" --volume "D:\NAVData\ContainerHelper\Host:D:\NAVData\ContainerHelper\Container" 
--volume "D:\NAVData\ContainerHelper\Host\Extensions\lanitol\my:C:\Run\my" --isolation Process --restart 
unless-stopped --env filesOnly=False --env enableApiServices=Y --env useSSL=N --volume 
"c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AGYAc
wBUADgAOABrAEwAZQB2AFkATABKADEAdgBsAE0ATwBXADgAbAAxAHcAPQA9AHwAMABiAGMANAAzADkAMQBiADQAOABmADIANAAzADAAOABhADg
ANQAwAGYAMABiAGUAOQBjAGMANQBiADQAMgBlADcANAA5ADQANQBjADMAMgBhADAAYQAxAGYAOAAxADkAMQBiADIANgA1ADAANwBjADYAZgA3A
DkANwBlADkAYwA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y 
--env accept_outdated=Y --detach bc18cu2:onprem-18.2.26217.26490-dk
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\New-NavContainer.ps1:1757 char:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo...
```

**Additional context**
- does it happen all the time? Tried a few versions, and they all fail.

**Comment by freddydk** [comment]
What is the content of c:\programdata\bccontainerhelper\bccontainerhelper.config.json ?

**Comment by Rukkulakki** [comment]
> What is the content of c:\programdata\bccontainerhelper\bccontainerhelper.config.json ?
BcContainerHelper.config.json
{
    "TelemetryConnectionString":  "",
    "defaultNewContainerParameters":  {
                                          "Credential":  {
                                                             "Password":  "01000000d08c9ddf0115d1118c7a00c04fc297eb01000000477e67b63d74a24e856457240ad8bf7a00000000020000000000106600000001000020000000658b0700d7bccf1fcf72d05600b9b14daf20617a71b5f826fbb3b689b02200f1000000000e8000000002000020000000d1b491ee6e00f90fdd234b23ba840a4d5068ccbb79b6d18a5c6266cec5ac0a6c200000006bcdf721f1a43202cb19a40939194d3d6dfcdb7fbd3764d1e4d4cad06580286a40000000f5fed33edf7a238a966697c2044edcee31019ded2d93cf6dd87d514d12ac11a84173760451b03de5b4479beb830fef7c13a1732d346bc148c821ebf9b8c57767",
                                                             "Username":  "admin"
                                                         },
                                          "Accept_Eula":  true,
                                          "Isolation":  "Process",
                                          "UpdateHosts":  true,
                                          "Auth":  "UserPassword"
                                      },
    "DOCKER_SCAN_SUGGEST":  false,
    "sandboxContainersAreMultitenantByDefault":  true,
    "containerHelperFolder":  "D:\\NAVData\\ContainerHelper\\Container",
    "digestAlgorithm":  "SHA256",
    "TreatWarningsAsErrors":  [
                                  "AL1026"
                              ],
    "genericImageNameFilesOnly":  "mcr.microsoft.com/businesscentral:{0}-filesonly",
    "bcartifactsCacheFolder":  "D:\\NAVData\\Artifacts",
    "TraefikUseDnsNameAsHostName":  false,
    "use7zipIfAvailable":  true,
    "hostHelperFolder":  "D:\\NAVData\\ContainerHelper\\Host",
    "useSharedEncryptionKeys":  true,
    "usePsSession":  true,
    "mapCountryCode":  {
                           "ae":  "w1",
                           "br":  "w1",
                           "bd":  "w1",
                           "co":  "w1",
                           "dz":  "w1",
                           "ee":  "w1",
                           "eg":  "w1",
                           "fo":  "dk",
                           "gl":  "dk",
                           "gr":  "w1",
                           "hk":  "w1",
                           "hr":  "w1",
                           "hu":  "w1",
                           "id":  "w1",
                           "ie":  "w1",
                           "jp":  "w1",
                           "ke":  "w1",
                           "kr":  "w1",
                           "lb":  "w1",
                           "lk":  "w1",
                           "lt":  "w1",
                           "lu":  "w1",
                           "lv":  "w1",
                           "ma":  "w1",
                           "mm":  "w1",
                           "mt":  "w1",
                           "my":  "w1",
                           "ng":  "w1",
                           "pe":  "w1",
                           "ph":  "w1",
                           "pl":  "w1",
                           "qa":  "w1",
                           "rs":  "w1",
                           "ro":  "w1",
                           "sa":  "w1",
                           "sg":  "w1",
                           "si":  "w1",
                           "th":  "w1",
                           "tn":  "w1",
                           "tw":  "w1",
                           "vn":  "w1",
                           "za":  "w1"
                       },
    "timeStampServer":  "http://timestamp.digicert.com",
    "genericImageName":  "mcr.microsoft.com/businesscentral:{0}",
    "psSessionTimeout":  0,
    "defaultContainerName":  "bcserver"
}
BcContainerHelper2.config.json
{
    "bcartifactsCacheFolder":  "D:\\Artifacts.cache",
    "usePsSession":  true,
    "hostHelperFolder":  "D:\\BcContainerHelper",
    "use7zipIfAvailable":  true,
    "genericImageName":  "mcr.microsoft.com/dynamicsnav:{0}-generic",
    "containerHelperFolder":  "C:\\ProgramData\\BcContainerHelper",
    "sandboxContainersAreMultitenantByDefault":  true,
    "defaultContainerName":  "bcserver",
    "defaultNewContainerParameters":  {
                                          "Credential":  {
                                                             "Password":  "01000000d08c9ddf0115d1118c7a00c04fc297eb01000000477e67b63d74a24e856457240ad8bf7a00000000020000000000106600000001000020000000658b0700d7bccf1fcf72d05600b9b14daf20617a71b5f826fbb3b689b02200f1000000000e8000000002000020000000d1b491ee6e00f90fdd234b23ba840a4d5068ccbb79b6d18a5c6266cec5ac0a6c200000006bcdf721f1a43202cb19a40939194d3d6dfcdb7fbd3764d1e4d4cad06580286a40000000f5fed33edf7a238a966697c2044edcee31019ded2d93cf6dd87d514d12ac11a84173760451b03de5b4479beb830fef7c13a1732d346bc148c821ebf9b8c57767",
                                                             "Username":  "admin"
                                                         },
                                          "Accept_Eula":  true,
                                          "Isolation":  "Process",
                                          "UpdateHosts":  true,
                                          "Auth":  "UserPassword"
                                      }
}

**Comment by Rukkulakki** [comment]
I notice that containerHelperFolder is different in the two files. Don't know if that is relevant though?

**Comment by freddydk** [comment]
containerhelperfolder is the shared folder inside the container - that should not be on D: drive - remove the setting.
Also, you should ONLY include the properties in the config file that you actually change - you should not have all defaults in there.

**Comment by Rukkulakki** [comment]
Hmm, removed containerhelperfolder  from the config file and got
Container Dns Name  : lanitol
Web Client          : http://lanitol/BC/
Setting lanitol to 172.24.125.127 in host hosts file

Files:
Cannot find path 'C:\inetpub\wwwroot\http' because it does not exist.
at <ScriptBlock>, C:\Run\navstart.ps1: line 266
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container lanitol failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...

Then removed hostHelperFolder from the config file and got the same error. 
Will try a new reinstall, and only move the docker data-root- and bccontainerhelper cache- folder

NB:
Not sure why all the settings are there. All I've done is try to follow your blog-intruction with:
$bcContainerHelperConfig.hostHelperFolder = "D:\NAVData\ContainerHelper\Host"
$bcContainerHelperConfig.containerHelperFolder  = "D:\NAVData\ContainerHelper\Container"
$bcContainerHelperConfig.bcartifactsCacheFolder = "D:\NAVData\Artifacts"
$bcContainerHelperConfig | ConvertTo-Json | Set-Content "C:\ProgramData\BcContainerHelper\BcContainerHelper.config.json"

**Comment by freddydk** [comment]
Got it, yeah - that construct writes everything in the .json file - didn't think of that:-(

That error looks like the windows defender problem - try disabling defender, create the container and re-enable to see if this is the issue.

**Comment by Rukkulakki** [comment]
Resetting everything and only changing data-root and cachefolder works as long as the defender is disabled :)
