### ISSUE TITLE
Sort-AppFoldersByDependencies fails with error Where-Object : The property 'Name' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by GUBLAZ** [microsoft/navcontainerhelper#2114]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
in a pipeline where we sort the current app folder for creating artifacts we got an issue in the script above.
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\AppHandling\Sort-AppFoldersByDependencies.ps1:106 char:13
+     $apps | Where-Object { $_.Name -eq "Application" } | ForEach-Obje ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Where-Object], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.WhereObjectCommand

**Scripts used to create container and cause the issue**
C:\a\1\s\BuildTemplates\Get-AppRuntimePackage.ps1' -appFolders "src" -appVersion "1.0.8.11" -buildArtifactFolder "C:\a\1\a\apps"
Sort-AppFoldersByDependencies -appFolders $appFolders.Split(',') -baseFolder $buildArtifactFolder -WarningAction SilentlyContinue

to the declaration, the "src" folder got any subfolder of each bc object types.

**Full output of scripts**
Starting: Get App RuntimePackage
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.190.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
Formatted command: . 'C:\a\1\s\BuildTemplates\Get-AppRuntimePackage.ps1' -appFolders "src" -appVersion "1.0.8.11" -buildArtifactFolder "C:\a\1\a\apps"
========================== Starting Command Output ===========================
"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\a\_temp\5c7f941a-018a-4841-a883-e768fc4268ae.ps1'"
C:\a\1\a\apps
BcContainerHelper version 2.0.16
##[error]Where-Object : The property 'Name' cannot be found on this object. Verify that the property exists.
At C:\Program 
Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\AppHandling\Sort-AppFoldersByDependencies.ps1:106 char:13
+     $apps | Where-Object { $_.Name -eq "Application" } | ForEach-Obje ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Where-Object], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.WhereObjectCommand
##[error]PowerShell exited with code '1'.
Finishing: Get App RuntimePackage

feel free to msg me if u need more input or other information.

**Comment by freddydk** [comment]
what is the content of $appfolders when calling sort-depend.....

**Comment by freddydk** [comment]
There is probably a folder in there, which is not an app folder (missing app.json).
the function isn't resilient against stuff like that.

**Comment by GUBLAZ** [comment]
hi @freddydk, thx i guess this will helps/solve the problem. i will check whats file and datastructure is downunder "$appfolders".

thx in adv. kr GUBLAZ
