### ISSUE TITLE
Issue with New Container Build for 18.4

### ISSUE THREAD

**Issue by SER-ChrisV** [microsoft/navcontainerhelper#2124]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When trying to create a new container, it gets to the very end and errors out.

**Scripts used to create container and cause the issue**
```
This has been modified to genericize the password and PI.

$MyArtifactUrl = Get-BCArtifactUrl -country us -version 18.4.0.0 -select Closest
$Password = ConvertTo-SecureString "mypassword" -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ("testuser", $Password)
$LicenseFile = "D:\Tools\BacPac Creation\Licenses\v18 BC Dev License.flf"
$MyDevContainerName ="BC184US"
$MyImageName = "sandbox-us"

# from Dmitry Chadayev, to create a container with only the System Application app installed - for Embed Apps
New-BCContainer `
    -accept_eula `
    -containerName $MyDevContainerName `
    -artifactUrl $MyArtifactUrl `
    -imageName $MyImageName `
    -licenseFile $LicenseFile `
    -Auth NavUserPassword `
    -Credential $Credential `
    -updateHosts `
    -multitenant `
    -includeAL `
    -UsecleanDatabase `
    -useNewDatabase `
    -assignPremiumPlan `
    -copyTables @('Add-in', 'Report Layout', 'Style Sheet')```

**Full output of scripts**
```
PS C:\WINDOWS\system32> D:\Tools\BacPac Creation\2. NewSysOnlyContainer.ps1
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building image sandbox-us:sandbox-18.4.28601.29356-us based on mcr.microsoft.com/businesscentral:10.0.19042.1237 with https://bcartifacts.azureedge.net/sandbox/18.4.28601.29356/us
Pulling latest image mcr.microsoft.com/businesscentral:10.0.19042.1237
10.0.19042.1237: Pulling from businesscentral
Digest: sha256:4242c01b2ba14cfc718623de33338f4796a70c58f60fec59d0651561e2ce3951
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19042.1237
mcr.microsoft.com/businesscentral:10.0.19042.1237
Generic Tag: 1.0.1.7
Container OS Version: 10.0.19042.1237 (20H2)
Host OS Version: 10.0.19042.1237 (20H2)
Using process isolation
Using license file D:\Tools\BacPac Creation\Licenses\v18 BC Dev License.flf
Files in c:\bcartifacts.cache\20bzlhpc.pe4\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying ConfigurationPackages
Copying Extensions
Copying Applications.US
c:\bcartifacts.cache\20bzlhpc.pe4
Sending build context to Docker daemon  1.956GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.19042.1237
---> ee8829be27ed
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/18.4.28601.29356/us filesOnly=False
---> Using cache
---> 51a751006c54
Step 3/6 : COPY my /run/
---> Using cache
---> 96057dedabc7
Step 4/6 : COPY NAVDVD /NAVDVD/
---> 3aa21030db2d
Step 5/6 : RUN \Run\start.ps1 -installOnly
---> Running in 4c26803b5259
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation
Docker Build failed with exit code -1
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\New-NavImage.ps1:590 char:25
+ ...              throw "Docker Build failed with exit code $LastExitCode"
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Docker Build failed with exit code -1:String) [], RuntimeException
    + FullyQualifiedErrorId : Docker Build failed with exit code -1 
...
```

**Screenshots**
N/A

**Additional context**
We perform this process every time we need to create new bacpac for uploading to LCS.
We typically run into an error if we are not on the latest version of the BCH but this time we are. 

Uninstall-Module -Name BcContainerHelper -AllVersions
Install-Module -Name BcContainerHelper -RequiredVersion 2.0.16

**Comment by freddydk** [comment]
I think this is another variant of https://github.com/microsoft/navcontainerhelper/issues/2086
Please try hyperv or try to disable antivirus during docker build

**Comment by SER-ChrisV** [comment]
This looks like it was a isolation issue.  Worked with AJ to get this figured out.  Thanks for the help.

Adding -isolation hyperv to the new container script made everything work.
Seemed odd though that the isolation was so deep that it impacted the database layer in the container.
