### ISSUE TITLE
Issue on Docker Service Start after Reboot: panic.log: Access is denied

### ISSUE THREAD

**Issue by Walwode** [microsoft/navcontainerhelper#2125]
Sorry Freddy for adding another solved issue 😂 But as I didn't found a solution here or on Google/Bing, somebody else might have the same issue and will find my solution.

**Describe the issue**
Could not start docker after reboot of Windows.

Since weeks I did not reboot my system, as after reboot I was not able to start the docker service, again. I have modified the `daemon.json` file and switched my *data-root* to `D:\Docker`. The EventLog showed an Error: `fatal: open D:\Docker\panic.log: Access is denied.`. Suggestions like adding the local *Users* group with *Full Control* to the folder didn't work.

**Solution**
I deleted the `panic.log` file in my data-root folder, as it was empty, anyway. That's simple! How couldn't I thought about this earlier...

**Comment by Walwode** [comment]
Further investigation showed me the file panic.log is always created with "Read Only" attribute. Created a custom file with full attributes and overwrite the existing one and now after each windows restart the docker service is automatically running :)

**Comment by freddydk** [comment]
Thanks - this is (was) a Docker Desktop problem.
I thought they fixed this in the latest version?

**Comment by Walwode** [comment]
I'm using the latest Docker EE I found. I also saw the issue in the release notes, but without a solution tip for those having the issue :)

**Comment by freddydk** [comment]
Thanks
