### ISSUE TITLE
Add Windows 10 21H2 (Build 10.0.19044) support

### ISSUE THREAD

**Issue by NAV-Management** [microsoft/navcontainerhelper#2129]
If your BC Container Helper is used in Windows 10 build 19044 and then you try to create a new BC Container with New-BcContainer, it tries to get the container for build 10.0.20348. Then it fails because the Docker container build is higher than the Windows build you are using.

I checked it with BCContainerhelper version 2.0.17-dev and I think the check for 19044 build is missing in your scripts. 

So I made 7 changes in Get-BestGenericImageName.ps1, New-NavContainer.ps1, New-NavImage.ps1 files for 19044 build and then I was able to download the needed container files, create the BC container, launch it successfully and work in it.

#### Get-BestGenericImageName.ps1
Overwrite in line 237:
```
                if ($hostOsVersion.Build -eq 19043 -or $hostOsVersion.Build -eq 19044) {
```

#### New-NavContainer.ps1
Add before in line 421:
```
	elseif ($os.BuildNumber -eq 19044) { 
        $hostOs = "21H2"
    }
```

Add before in line 1040:
```
	elseif ("$containerOsVersion".StartsWith('10.0.19044.')) {
        $containerOs = "21H2"
    }
```

Overwrite in line 1201:
```
    elseif (("$hostOsVersion".StartsWith('10.0.19043.') -or "$hostOsVersion".StartsWith('10.0.19044.')) -and "$containerOsVersion".StartsWith("10.0.19041.")) {
```

#### New-NavImage.ps1

Add before in line 104:
```
	elseif ($os.BuildNumber -eq 19044) { 
        $hostOs = "21H2"
    }
```
Add before in line 314:
```
            elseif ("$containerOsVersion".StartsWith('10.0.19044.')) {
                $containerOs = "21H1"
            }
 ```
Overwrite at line 347:
 ```
            elseif (("$hostOsVersion".StartsWith('10.0.19043.') -or "$hostOsVersion".StartsWith('10.0.19044.')) -and "$containerOsVersion".StartsWith("10.0.19041.")) {
 ```

**Comment by freddydk** [comment]
Shipped in 2.0.18
