### ISSUE TITLE
NAV20017 cu 11 seemingly missing

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#2130]
**Describe the issue**
Trying to create an image with NAV2017 cu11 fails, while using cu12 works

**Scripts used to create container and cause the issue**
```
$containerName = 'lanitolnav'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2017' -cu '11' -country 'dk'
$licenseFile = 'd:\nav\infar\udvikling\nav2017.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -includeCSIDE -doNotExportObjectsToText `
    -imageName nav2017cu11 `
    -shortcuts DesktopFolder `
    -updateHosts
```

**Full output of scripts**
```
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro - Unknown/Insider build
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Removing container lanitolnav
Removing lanitolnav from container hosts file
Removing lanitolnav-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\lanitolnav
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.20348.169
Building image nav2017cu11:onprem-10.0.18609.0-dk based on mcr.microsoft.com/businesscentral:10.0.20348.169 with https://bcartifacts.azureedge.net/onp
rem/10.0.18609.0/dk
Pulling latest image mcr.microsoft.com/businesscentral:10.0.20348.169
10.0.20348.169: Pulling from businesscentral
Digest: sha256:880f3c4ccb2ba04a13c6686048010cf76210a8e234d907e4faa06556151780db
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.169
mcr.microsoft.com/businesscentral:10.0.20348.169
Generic Tag: 1.0.1.7
Container OS Version: 10.0.20348.169 (ltsc2022)
Host OS Version: 10.0.22000.258 (Unknown/Insider build)
Using hyperv isolation
Using license file d:\nav\infar\udvikling\nav2017.flf
Files in D:\NAVData\Artifacts\055u3z3k.zpe\my:
Copying Platform Artifacts
Copying Database
Copying Licensefile
Copying Installers
Copying TestToolKit
Copying UpgradeToolKit
Remove-Item : Adgang til cloudfilen blev nægtet
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\New-NavImage.ps1:601 char:17
+ ...             Remove-Item $buildFolder -Recurse -Force -ErrorAction Sil ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand
...
```

**Additional context**
If you don't use the ImageName the error changes to:
at Download-Artifacts, C:\Run\HelperFunctions.ps1: line 716
at <ScriptBlock>, C:\Run\start.ps1: line 139
at <ScriptBlock>, <No file>: line 1
Initialization of container lanitolnav failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...nitolnav failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container lanitolnav failed

And if you change the script to use cu12 it will work fine.

**Comment by Rukkulakki** [comment]
Not sure if it now is caused by you rebuilding, but now I am getting the errors both with and without your parameter. It worked fine  with your parameter yesterday.

**Comment by freddydk** [comment]
Please paste your full output here?

**Comment by Rukkulakki** [comment]
Slightly changed now. Not getting a hard error, but but script quits as it cannot find image

$containerName = 'nav2dayfo'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2017' -cu '12' -country 'dk'
$licenseFile = 'd:\nav\infar\udvikling\nav2017.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -shortcuts DesktopFolder `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'nav2017cu12' `
    -licenseFile $licenseFile `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts `
    -myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/start.ps1")


Setting bcartifactsCacheFolder = D:\NAVData\Artifacts
BcContainerHelper version 2.0.16
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro - Unknown/Insider build
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Removing container nav2dayfo
Removing nav2dayfo from container hosts file
Removing nav2dayfo-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\nav2dayfo
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.20348.288
Image nav2017cu12:onprem-10.0.18976.0-dk already exists
Image nav2017cu12:onprem-10.0.18976.0-dk was built for OS Version 10.0.20348.169, should be 10.0.20348.288
Building image nav2017cu12:onprem-10.0.18976.0-dk based on mcr.microsoft.com/businesscentral:10.0.20348.288 with https://bcartifacts
.azureedge.net/onprem/10.0.18976.0/dk
Pulling latest image mcr.microsoft.com/businesscentral:10.0.20348.288
10.0.20348.288: Pulling from businesscentral
Digest: sha256:b9cdc5a4ece3317892d5bac3479c650f1d61548ee803aff30fcd887f69360548
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.288
mcr.microsoft.com/businesscentral:10.0.20348.288
Generic Tag: 1.0.1.8
Container OS Version: 10.0.20348.288 (ltsc2022)
Host OS Version: 10.0.22000.258 (Unknown/Insider build)
Using hyperv isolation
Using license file d:\nav\infar\udvikling\nav2017.flf
Files in D:\NAVData\Artifacts\1mzlvx4d.cfv\my:
Copying Platform Artifacts

PS C:\WINDOWS\system32>
