### ISSUE TITLE
Getting error Initialization of container Failed

### ISSUE THREAD

**Issue by yogimindquad** [microsoft/navcontainerhelper#2134]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

** Issue**
When I try to set up a Docker container environment for Business Central 2021 CA version I got an error.

I am using the below Powershell scripts.
$containerName = 'BC19demo'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'ca' -select 'Latest' 
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'Password' -AsPlainText -Force)

New-NavContainer `
        -accept_eula `
        -containerName $containerName `
        -artifactUrl $artifactUrl `
        -Credential $credential `
        -auth UserPassword `
        -updateHosts `
        -assignPremiumPlan `
        -includeAL `
        -memoryLimit 4G 

**Full output of scripts**
BcContainerHelper version 2.0.16
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 21H1
Docker Client Version is 20.10.8
Docker Server Version is 20.10.8
Downloading application artifact /sandbox/19.0.29894.31294/ca
Downloading C:\Users\yogi.p\AppData\Local\Temp\e017d12a-0372-416c-991c-87de2c00a3ef.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/19.0.29894.31294/platform
Downloading C:\Users\yogi.p\AppData\Local\Temp\74e64cb5-174b-4ba3-a0bb-864fd18f9374.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\19.0.29894.31294\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\19.0.29894.31294\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\19.0.29894.31294\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1
Pulling image mcr.microsoft.com/businesscentral:10.0.19041.1288
10.0.19041.1288: Pulling from businesscentral
295f12394c4f: Pulling fs layer
778142d99876: Pulling fs layer
4dc9cc154003: Pulling fs layer
716a49b0192f: Pulling fs layer
716a49b0192f: Waiting
b6d59bab030e: Pulling fs layer
77842e449bf2: Pulling fs layer
bc26cc3cfb47: Pulling fs layer
b6d59bab030e: Waiting
77842e449bf2: Waiting
8eba8feb5a62: Pulling fs layer
8eba8feb5a62: Waiting
d8434422d359: Pulling fs layer
4aab19cb6bd3: Pulling fs layer
d8434422d359: Waiting
1edb16371406: Pulling fs layer
4aab19cb6bd3: Waiting
14843d7a1167: Pulling fs layer
1edb16371406: Waiting
14843d7a1167: Waiting
4526a7cb12b2: Pulling fs layer
3fee4454d3bc: Pulling fs layer
4525053909af: Pulling fs layer
4526a7cb12b2: Waiting
4dc9cc154003: Verifying Checksum
4dc9cc154003: Download complete
716a49b0192f: Verifying Checksum
716a49b0192f: Download complete
b6d59bab030e: Verifying Checksum
b6d59bab030e: Download complete
77842e449bf2: Verifying Checksum
77842e449bf2: Download complete
bc26cc3cfb47: Verifying Checksum
bc26cc3cfb47: Download complete
8eba8feb5a62: Verifying Checksum
8eba8feb5a62: Download complete
295f12394c4f: Verifying Checksum
295f12394c4f: Download complete
4aab19cb6bd3: Verifying Checksum
4aab19cb6bd3: Download complete
778142d99876: Verifying Checksum
778142d99876: Download complete
14843d7a1167: Verifying Checksum
14843d7a1167: Download complete
4526a7cb12b2: Verifying Checksum
4526a7cb12b2: Download complete
3fee4454d3bc: Verifying Checksum
3fee4454d3bc: Download complete
4525053909af: Verifying Checksum
4525053909af: Download complete
295f12394c4f: Pull complete
d8434422d359: Verifying Checksum
d8434422d359: Download complete
778142d99876: Pull complete
4dc9cc154003: Pull complete
716a49b0192f: Pull complete
b6d59bab030e: Pull complete
77842e449bf2: Pull complete
bc26cc3cfb47: Pull complete
8eba8feb5a62: Pull complete
d8434422d359: Pull complete
4aab19cb6bd3: Pull complete
1edb16371406: Download complete
1edb16371406: Pull complete
14843d7a1167: Pull complete
4526a7cb12b2: Pull complete
3fee4454d3bc: Pull complete
4525053909af: Pull complete
Digest: sha256:0e92606977d3db824f202a6e094def931e3172a98fc79163f3a957f2068112f5
Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.19041.1288
mcr.microsoft.com/businesscentral:10.0.19041.1288
Using image mcr.microsoft.com/businesscentral:10.0.19041.1288
Creating Container BC19demo
Style: sandbox
Multitenant: Yes
Version: 19.0.29894.31294
Platform: 19.0.29884.31221
Generic Tag: 1.0.1.8
Container OS Version: 10.0.19041.1288 (2004)
Host OS Version: 10.0.19043.1288 (21H1)
WARNING: Host OS is 21H1 and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
Using locale en-CA
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\BC19demo\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC19demo from image mcr.microsoft.com/businesscentral:10.0.19041.1288
b5368b83e4bb060b7a60c1ed67a0d39e3f29559d84467435cf4a691014549579
Waiting for container BC19demo to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/19.0.29894.31294/ca
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\19.0.29894.31294\platform\ServiceTier\Program Files
c:\dl\sandbox\19.0.29894.31294\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\19.0.29894.31294\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\19.0.29894.31294\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\19.0.29894.31294\ca\BusinessCentral-CA.bak
Restoring CRONUS Demo Database
Initializing...
Setting host.docker.internal to 192.168.1.113 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.113 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.31.240.1 in container hosts file
Starting Container
Hostname is BC19demo
PublicDnsName is BC19demo
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Copying Database on localhost\SQLEXPRESS from CRONUS to tenant
Taking database CRONUS offline
Warning, exception when running: ALTER DATABASE [CRONUS] SET OFFLINE WITH ROLLBACK IMMEDIATE
Waiting... - retrying
Warning, exception when running: ALTER DATABASE [CRONUS] SET OFFLINE WITH ROLLBACK IMMEDIATE
Waiting...... - retrying
Error when running: ALTER DATABASE [CRONUS] SET OFFLINE WITH ROLLBACK IMMEDIATE
Putting database CRONUS back online
Warning, exception when running: ALTER DATABASE [CRONUS] SET ONLINE
Waiting... - retrying
Warning, exception when running: ALTER DATABASE [CRONUS] SET ONLINE
Waiting...... - retrying
Error when running: ALTER DATABASE [CRONUS] SET ONLINE
User does not have permission to alter database 'CRONUS', the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
at Invoke-SqlCmdWithRetry, C:\Run\HelperFunctions.ps1: line 429
at Copy-NavDatabase, C:\Run\HelperFunctions.ps1: line 203
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 166
at <ScriptBlock>, C:\Run\navstart.ps1: line 122
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/19.0.29894.31294/ca
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\19.0.29894.31294\platform\ServiceTier\Program Files
c:\dl\sandbox\19.0.29894.31294\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\19.0.29894.31294\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\19.0.29894.31294\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\sandbox\19.0.29894.31294\ca\BusinessCentral-CA.bak
Restoring CRONUS Demo Database
Initializing...
Setting host.docker.internal to 192.168.1.113 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.113 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.31.240.1 in container hosts file
Starting Container
Hostname is BC19demo
PublicDnsName is BC19demo
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Copying Database on localhost\SQLEXPRESS from CRONUS to tenant
Taking database CRONUS offline
Warning, exception when running: ALTER DATABASE [CRONUS] SET OFFLINE WITH ROLLBACK IMMEDIATE
Waiting... - retrying
Warning, exception when running: ALTER DATABASE [CRONUS] SET OFFLINE WITH ROLLBACK IMMEDIATE
Waiting...... - retrying
Error when running: ALTER DATABASE [CRONUS] SET OFFLINE WITH ROLLBACK IMMEDIATE
Putting database CRONUS back online
Warning, exception when running: ALTER DATABASE [CRONUS] SET ONLINE
Waiting... - retrying
Warning, exception when running: ALTER DATABASE [CRONUS] SET ONLINE
Waiting...... - retrying
Error when running: ALTER DATABASE [CRONUS] SET ONLINE
User does not have permission to alter database 'CRONUS', the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
at Invoke-SqlCmdWithRetry, C:\Run\HelperFunctions.ps1: line 429
at Copy-NavDatabase, C:\Run\HelperFunctions.ps1: line 203
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 166
at <ScriptBlock>, C:\Run\navstart.ps1: line 122
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1
Initialization of container BC19demo failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...BC19demo failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC19demo failed

**Screenshots**
![14-10-2021 07-55-21 PM](https://user-images.githubusercontent.com/46317181/137337655-88cbca59-ef44-4998-8d17-723f6f780a9e.png)

**Comment by freddydk** [comment]
This is another variation of #2086  - you can disable antivirus while building the container or update to Windows 11, where the error should be gone.
