### ISSUE TITLE
Question: Unable to read data from the transport connection

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/navcontainerhelper#2135]
**Describe the issue**
Please can you help me with my problem. I am using function Get-BCContainerApp and I get this error: "Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.". This only happens sometimes and completely randomly and I have not found any rule. When I run the function again it runs without a problem. It happens when I download Base Application (other appliactions are ok). Do you have any idea? Can helps if I set higher any of the timeouts?

Thank you for your help.

**Comment by fridrichovsky** [comment]
I have 10 containers on my PC. When I decide to upgrade the containers to a newer version, 3 of the 10 end up with this error. The error occurs more often when the PC is more busy and downloading extensions takes more time.
The problem is always with the Base Application extension, which is the largest. That's why I think it might help to increase some timeout. When I run the function again, it usually completes without problems. When the function ends with an error again, I stop one of the containers and then the function always completes without an error.
It is not even possible to simulate this, because the next time all containers are upgraded, the error can affect different containers than the first time. So they are not always the same containers.

**Comment by freddydk** [comment]
In the Get-NavContainerApp.ps1 (under Program Files\WindowsPowerShell\Modules\BcContainerHelper\version\AppHandling) line 104 - it uses Invoke-RestMethod to download the app
Invoke-RestMethod is supposed to wait indefinite (doc: https://docs.microsoft.com/da-dk/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-5.1), but I found articles indicating that there is a timeout of 100sec.
You could modify the file and add 
 -TimeoutSec 300
to that line - which would be 5 minutes.
Then give me a heads up on whether that makes a difference.

**Comment by freddydk** [comment]
I actually thought I had replaced all occurrences of Invoke-RestMethod -outfile  with Web Client download.
A similar pattern is used in Compile-AppInBcContainer
Will fix this one as well.

**Comment by fridrichovsky** [comment]
Thanks for editing. Your tool saves me from a lot of container problems every day.
