### ISSUE TITLE
$bcContainerHelperConfig is up todate after last major release ?

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/navcontainerhelper#2138]
**Describe the issue**
Using a pipeline with this helpful module, I have now issues with some countries (ee, jp, hk, rs,kr, pl, tw, th).
I wondering if those countries you be part of $bcContainerHelperConfig.mapCountryCode ?

NavContainerHelper is version 2.0.16

**Additional context**
I think that those countries do not have data in the database.

**Comment by freddydk** [comment]
Did you try?
![image](https://user-images.githubusercontent.com/10775043/137792555-e2482ed0-bcaf-4811-a35e-a4caf886685d.png)

I think these countries should work just fine?

**Comment by freddydk** [comment]
It is correct that there is no demo data in a number of the countries.
You will have to use rapidstart packages to import data into the containers after creating them.
I have asked whether we could have a w1 demo data company in these artifacts, but this request was declined.

**Comment by YvesDesrumaux** [comment]
Hello Freddy,

Thanks keeping up to date.
Unfortunately, we have another issue using the package. And you advise to $bcContainerHelperConfig propoerties for those countries without data.

Cordialement / Best regards

Yves DESRUMAUX - isatech
Mob : +33 607 978 187

De : Freddy Kristiansen ***@***.***>
Envoyé : lundi 10 janvier 2022 08:54
À : microsoft/navcontainerhelper ***@***.***>
Cc : Yves DESRUMAUX ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/navcontainerhelper] $bcContainerHelperConfig is up todate after last major release ? (#2138)


It is correct that there is no demo data in a number of the countries.
You will have to use rapidstart packages to import data into the containers after creating them.
I have asked whether we could have a w1 demo data company in these artifacts, but this request was declined.

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fnavcontainerhelper%2Fissues%2F2138%23issuecomment-1008615131&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7C42b5f82e4c6d4b4d3ea308d9d40e63c5%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637773980551455789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=qMmRSUW3L5sOBWFQNP%2FNicdGIxf0gknxHlxPAmyeB4U%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFOWXXPZBGO3ROZRSEXZ7TUVKGCDANCNFSM5GDMMPVQ&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7C42b5f82e4c6d4b4d3ea308d9d40e63c5%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637773980551455789%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zsezepzl9B67SYn4%2B8FbNoBFWWN%2FZx9amgPSHTzMPhs%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

[https://www.isatech.fr/wp-content/uploads/2021/11/crm-webinaire.jpg]<https://www.isatech.fr/demonstration-crm-microsoft-dynamics-365-centraliser-processus-metiers/>
Les informations contenues dans ces documents et leurs fichiers joints peuvent être de nature confidentielle et couvertes par le secret des correspondances (article 226-15 du Code Pénal). Elles sont destinées à l'usage exclusif du destinataire indiqué ci-dessus. Si vous n'êtes pas le destinataire, vous êtes par la présente avisés que toute divulgation, reproduction, distribution ou autre utilisation de cette communication est strictement interdite. Si vous recevez cette communication par erreur, veuillez-nous en aviser sans délais, détruire toutes les copies et la supprimer de votre système informatique. Afin de contribuer au respect de l'environnement, merci de n'imprimer cet email que si nécessaire.

**Comment by freddydk** [comment]
Sorry, I don't understand the question.

**Comment by YvesDesrumaux** [comment]
Hello Freddy,

In that case the issue 1481 if error is raise during ImportTestDataInBcContainer, the country loop is broken · Issue #1481 · microsoft/navcontainerhelper (github.com)<https://github.com/microsoft/navcontainerhelper/issues/1481> may raised again ?

Cordialement / Best regards

Yves DESRUMAUX - isatech
Mob : +33 607 978 187

De : Freddy Kristiansen ***@***.***>
Envoyé : lundi 10 janvier 2022 11:42
À : microsoft/navcontainerhelper ***@***.***>
Cc : Yves DESRUMAUX ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/navcontainerhelper] $bcContainerHelperConfig is up todate after last major release ? (#2138)


Sorry, I don't understand the question.

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fnavcontainerhelper%2Fissues%2F2138%23issuecomment-1008743317&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7Ce77bf6fad9cc445c846208d9d425cae2%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637774081051754848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XPgDiO31e2qXb1KFjIh75DtIuApcQd42fm5d0IEB05Y%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFOWXQUJ2S5ZXWV33TE46TUVKZWLANCNFSM5GDMMPVQ&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7Ce77bf6fad9cc445c846208d9d425cae2%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637774081051754848%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vI%2FhYt5qz25%2BoOMEgXW7WoFCULYBzhReTxy3AFI5pd4%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

[https://www.isatech.fr/wp-content/uploads/2021/11/crm-webinaire.jpg]<https://www.isatech.fr/demonstration-crm-microsoft-dynamics-365-centraliser-processus-metiers/>
Les informations contenues dans ces documents et leurs fichiers joints peuvent être de nature confidentielle et couvertes par le secret des correspondances (article 226-15 du Code Pénal). Elles sont destinées à l'usage exclusif du destinataire indiqué ci-dessus. Si vous n'êtes pas le destinataire, vous êtes par la présente avisés que toute divulgation, reproduction, distribution ou autre utilisation de cette communication est strictement interdite. Si vous recevez cette communication par erreur, veuillez-nous en aviser sans délais, détruire toutes les copies et la supprimer de votre système informatique. Afin de contribuer au respect de l'environnement, merci de n'imprimer cet email que si nécessaire.

**Comment by freddydk** [comment]
And why not just use base as you did in 1481?

**Comment by YvesDesrumaux** [comment]
I use it modifying the $bcContainerHelperConfig adding the countries that raise the issue.

That is why I asked who is supposed to maintaint the $bcContainerHelperConfig ?
Are you going to had those countries or do we need as users to dit on our own ?

Cordialement / Best regards

Yves DESRUMAUX - isatech
Mob : +33 607 978 187

De : Freddy Kristiansen ***@***.***>
Envoyé : lundi 10 janvier 2022 11:48
À : microsoft/navcontainerhelper ***@***.***>
Cc : Yves DESRUMAUX ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/navcontainerhelper] $bcContainerHelperConfig is up todate after last major release ? (#2138)


And why not just use base as you did in 1481?

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fnavcontainerhelper%2Fissues%2F2138%23issuecomment-1008748416&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7C4ef89db2e2164538c5a308d9d426a320%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637774084689410250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VAW%2F420dvdu51804YoGLUaAUPR8cbxW5evEAHT%2Bn6WA%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFOWXTRZQWAW3GXY5J2W3LUVK2NBANCNFSM5GDMMPVQ&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7C4ef89db2e2164538c5a308d9d426a320%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637774084689410250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ca2ha8GzOaFBDGXoKpskM8aJGNH%2B2gtcm4sVhSN4HFU%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

[https://www.isatech.fr/wp-content/uploads/2021/11/crm-webinaire.jpg]<https://www.isatech.fr/demonstration-crm-microsoft-dynamics-365-centraliser-processus-metiers/>
Les informations contenues dans ces documents et leurs fichiers joints peuvent être de nature confidentielle et couvertes par le secret des correspondances (article 226-15 du Code Pénal). Elles sont destinées à l'usage exclusif du destinataire indiqué ci-dessus. Si vous n'êtes pas le destinataire, vous êtes par la présente avisés que toute divulgation, reproduction, distribution ou autre utilisation de cette communication est strictement interdite. Si vous recevez cette communication par erreur, veuillez-nous en aviser sans délais, détruire toutes les copies et la supprimer de votre système informatique. Afin de contribuer au respect de l'environnement, merci de n'imprimer cet email que si nécessaire.

**Comment by freddydk** [comment]
Do I understand it right, that you want to know which countries are based on w1 and which countries have their own base-app (localization)?

All new countries will be based on w1, so the number of countries having their own base-app is fixed and will only change when we (sometime in the future) move localizations to apps (and base these localizations on w1 as well)

Basically, you can create an array of countries which have their own base app (thus also a CRONUS company) - no new countries will ever be added to this.

**Comment by YvesDesrumaux** [comment]
Ok that's clear for me

Thanks a lot

Cordialement / Best regards

Yves DESRUMAUX - isatech
Mob : +33 607 978 187

De : Freddy Kristiansen ***@***.***>
Envoyé : lundi 10 janvier 2022 12:29
À : microsoft/navcontainerhelper ***@***.***>
Cc : Yves DESRUMAUX ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/navcontainerhelper] $bcContainerHelperConfig is up todate after last major release ? (#2138)


Do I understand it right, that you want to know which countries are based on w1 and which countries have their own base-app (localization)?

All new countries will be based on w1, so the number of countries having their own base-app is fixed and will only change when we (sometime in the future) move localizations to apps (and base these localizations on w1 as well)

Basically, you can create an array of countries which have their own base app (thus also a CRONUS company) - no new countries will ever be added to this.

-
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fnavcontainerhelper%2Fissues%2F2138%23issuecomment-1008784964&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7C2753b7e9eabc487e1ab008d9d42c725d%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637774109632886294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QI5WTM6Uj8WVLMfIDc5QgvzoxXWQIFXJmGntSoOInlI%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHFOWXQYBCZ5T46EWBFTJM3UVK7I7ANCNFSM5GDMMPVQ&data=04%7C01%7Cyves.desrumaux%40isatech.fr%7C2753b7e9eabc487e1ab008d9d42c725d%7C599742606d1749d7b4921c295832012e%7C0%7C0%7C637774109632886294%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yStZrfjvZ2Nep80f8QGUUYMED6G1gJF9sXlkYe9LJOk%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

[https://www.isatech.fr/wp-content/uploads/2021/11/crm-webinaire.jpg]<https://www.isatech.fr/demonstration-crm-microsoft-dynamics-365-centraliser-processus-metiers/>
Les informations contenues dans ces documents et leurs fichiers joints peuvent être de nature confidentielle et couvertes par le secret des correspondances (article 226-15 du Code Pénal). Elles sont destinées à l'usage exclusif du destinataire indiqué ci-dessus. Si vous n'êtes pas le destinataire, vous êtes par la présente avisés que toute divulgation, reproduction, distribution ou autre utilisation de cette communication est strictement interdite. Si vous recevez cette communication par erreur, veuillez-nous en aviser sans délais, détruire toutes les copies et la supprimer de votre système informatique. Afin de contribuer au respect de l'environnement, merci de n'imprimer cet email que si nécessaire.
