### ISSUE TITLE
Naming symbol-files when compiling with Compile-AppInNavContainer

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#215]
When compiling an extension from VS-Code, or when downloading symbol files they are named for instance: Microsoft_Application_13.0.24284.0.app and Microsoft_System_13.0.12929.0.app.
If read that this is a default naming convention (publisher, name and version).
But when using Compile-AppInNavContainer, files Application.app and System.app are created. So you end up with 4 symbol files.
Can the same naming convention be used with the Compile-AppInNavContainer command as the default behavior that I see in VS-Code.
I gues I can skip the creation of the Symbol files, but when there are none, it would be nice to use the same naming convention.

**Comment by freddydk** [comment]
This will be fixed in the next update of navcontainerhelper.

**Comment by freddydk** [comment]
Shipped in 0.4.0.0
