### ISSUE TITLE
Create-AadAppsForBC - Grant admin consent

### ISSUE THREAD

**Issue by JeppeBylov** [microsoft/navcontainerhelper#2153]
**Describe the issue**
When we create container environments with AAD authentication, users are requested to consent to the app registration. We would like to avoid this, as we generate new environments pretty often.

Would it be possible to "grant admin consent for tenant" as a parameter?

**Scripts used to create container and cause the issue**
```
Create-AadAppsForBC -appIdUri https://bc.company.com/containerName/ -AadAdminCredential $aadcredential
```

**Full output of scripts**
```
Key   : SsoAdAppId
Value : xxx
Name  : SsoAdAppId

Key   : SsoAdAppKeyValue
Value : xxx
Name  : SsoAdAppKeyValue

Key   : AadTenant
Value : xxx
Name  : AadTenant
```

**Screenshots**
![image](https://user-images.githubusercontent.com/968411/138271899-1e3e5037-98b2-4498-8084-4441a526c20f.png)

**Comment by freddydk** [comment]
Fixed in 3.0.1
