### ISSUE TITLE
Publish-PerTenantExtensionApps - should this support schedule?

### ISSUE THREAD

**Issue by JathanM** [microsoft/navcontainerhelper#2157]
Currently using Publish-PerTenantExtensionApps in an Azure pipeline to publish an app as a Per Tenant Extension. (PTE Scope)   
Due to breaking changes in version 19, I cannot deploy a new version of the extension prior to upgrading BC (Business Central).  And the changes prevent BC from updating to Version 19.   
Thus, I need to schedule for the next major version.
 
 Current Process:
 Publish-PerTenantExtensionApps - LINE 102
 uses: PATCH automationApiUrl/companies($companyId)/extensionUpload(0)/content
 
 Suggested Change to Publish-PerTenantExtensionApps
 
 1> Add new param  -schedule  
      default: "Current version"
      validate for: "Current version", "Next minor version", "Next major version"

2> If not "Current version" Alter script to start the process with
 POST /microsoft/automation/v2.0/companies({companyId})/extensionUpload 

[https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/api/dynamics_extensionupload_create]

My concern is that Publish-PerTenantExtensionApps is going to get too messy to support long term with all the options.   The looping for status doesn't apply, etc...

**Comment by freddydk** [comment]
The script is really intended for publishing as part of CD or as part of a release pipeline.
For the same reason as you describe, I am not sure it is a good idea to try and support everything.
