### ISSUE TITLE
When will 21H1 images be available?

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#2159]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Getting this message in all my scripts.  Which means I have to use Hyper-V isolation yet you recommend process isolation in general.

> INFO: Windows 10 21H1 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1

Depending on when Microsoft starts counting it has been either 10 months (January) or 4 months (July) since 21H1 was released.  Even if it was on the off quarters (Apr/Sep) its been 8 or 2 months.

**Scripts used to create container and cause the issue**
```
$containerName = 'rms-bc14'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '14.8.38658.0' -country 'gb' -select 'Closest'
$licenseFile = 'd:\license\bc14license.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -includeTestToolkit `
    -licenseFile $licenseFile `
    -dns '192.168.0.1' `
    -usessl -installCertificateOnHost `
    -isolation 'hyperv' `
    -includeCSIDE `
    -updateHosts

```

**Full output of scripts**
```
NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by freddydk** [comment]
Windows 10 21H1 and Windows 10 21H2 will never get corresponding server core images.
I am going to share a blog post on this when I have some time...:-|

**Comment by freddydk** [comment]
Windows 11 solves SOOOOOO many issues
