### ISSUE TITLE
enableSymbolLoading only works with includeCSide

### ISSUE THREAD

**Issue by hemisphera** [Microsoft/navcontainerhelper#216]
It appears that the flag `enableSymbolLoading` is only effective if we also provide `includeCSide`. I've checked `New-NavContainer` here: https://github.com/Microsoft/navcontainerhelper/blob/77229c92e4bc83eb4241a0931edc50982fe81d52/ContainerHandling/New-NavContainer.ps1#L422

Is this intended? I usually spin up containers without CSide because I already have my clients locally and don't need the links that are created.

**Comment by freddydk** [comment]
I think there are scenarios where it does make sense to enable it without CSide, so I will move it outside that statement in the next version.

**Comment by freddydk** [comment]
Shipped in 0.4.0.0
