### ISSUE TITLE
Wrong Extension

### ISSUE THREAD

**Issue by Softstore** [microsoft/navcontainerhelper#2165]
Hi,

We have already 2 App’s on Marketplace approved by Microsoft.
One of them is the Portuguese language pack for Business Central with id “2f9675e9-d254-4b60-a615-d43e0a3baa41”.
This App is already BC19 compliant.
The APP version is 19.0.1.0, but when we installed in a Cloud tenant, the version is wrong in Extension Management (prints below).

The App version should be 19.0.1.0. Can you help?

![image](https://user-images.githubusercontent.com/61152595/139693018-8becda6e-88cf-408d-9160-8f3eedf32762.png)
![image](https://user-images.githubusercontent.com/61152595/139693060-01f98b07-1b56-4504-956b-4228c396dc07.png)

![image](https://user-images.githubusercontent.com/61152595/139693185-ebfd37c7-8b6d-459f-861e-1ca65d8dbd90.png)

**Comment by freddydk** [comment]
This issue doesn't seem to be related to BcContainerHelper.
Please file a support ticket in Business Central.
