### ISSUE TITLE
Ignore Import-Module error about 'Check-BcContainerHelperPermissions -Fix'

### ISSUE THREAD

**Issue by bvbeek** [microsoft/navcontainerhelper#2166]
Hi Freddy,

Please can you add an option to ignore these errors?
We only want to download artifacts on a server without docker containers.

![image](https://user-images.githubusercontent.com/28626283/139815285-7a8bb4dd-5fa4-4dde-900e-3453f2f740da.png)

Thanks!

**Comment by freddydk** [comment]
Next version, you will be able to use 

Import-Module BcContainerHelper -DisableNameChecking -argumentList $true

Where the $true means that the import should be silent.

**Comment by freddydk** [comment]
Shipped in the latest preview

**Comment by freddydk** [comment]
Shipped in 2.0.18

**Comment by bvbeek** [comment]
Hi Freddy,

still get this error: 

![image](https://user-images.githubusercontent.com/28626283/142383655-f3572114-2eee-4ded-ad72-7a0c24d2e10a.png)

What do I wrong?
