### ISSUE TITLE
Join-Path not work as spected in remote SQL Server

### ISSUE THREAD

**Issue by nicojmb** [microsoft/navcontainerhelper#2167]
Hi, 

When execute "Restore-BcDatabaseFromArtifacts" command, and set SQL parameters to remote server, the script checks the directory in localhost instead of sql directory.

https://github.com/microsoft/navcontainerhelper/blob/d382c494c5b30d301ca6f357e86819e03d2fc133/Bacpac/Restore-BcDatabaseFromArtifacts.ps1#L116

https://github.com/microsoft/navcontainerhelper/blob/d382c494c5b30d301ca6f357e86819e03d2fc133/Bacpac/Restore-BcDatabaseFromArtifacts.ps1#L119

If i change this two lines:

```
Line: 116
#$bakFile = Join-Path $defaultBackupPath ($bakFile | Split-Path -Leaf)
$bakFile = -join($defaultBackupPath, ($bakFile | Split-Path -Leaf))

Line: 119
#$destinationPath = Join-Path $DefaultDataPath ($databaseprefix -replace '[^a-zA-Z0-9]', '')
$destinationPath = -join($DefaultDataPath, ($databaseprefix -replace '[^a-zA-Z0-9]', ''))
```
Works great!

**Comment by freddydk** [comment]
Shipped in 2.0.18
