### ISSUE TITLE
[Info/Question] Uninstall-Module raise error Module 'BcContainerHelper' is in currently in use

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/navcontainerhelper#2180]
**Describe the issue**
I am using function that upgrade BCContainerHleper automatically. Last step is Uninstall-Module for older versions. I have a problem with Uninstall-Module because I get the following error "Module 'BcContainerHelper' is in currently in use or you don't have the required permissions."
This error I get from version 15 (I am not sure exactly with version). I checked several times to see if there was any powershell session on the server, but there was none.
I spent some time solving this problem until I found a reason to block the module. 
Module BCContainerHelper content "Microsoft.ApplicationInsights.dll" this is used by process "wsmprovhost.exe". I had several running instances of this process on server and it was reason why I can not uninstall-module.
So if you have same problem as me I recommend end all process instances and after that you can uninstall older versions. I hope that this information helps.

The question is if it is possible to somehow terminate the wsmprovhost process when the bccontainerhelper function no longer needs it.

**Comment by freddydk** [comment]
Restarting PowerShell should do the same trick.
After installing a new version, restart PowerShell and then you should be using the latest.

**Comment by fridrichovsky** [comment]
I did it many times, but I could not uninstall older version. I checked processes and there was not any powershell process. Or what do you mean restart powershell?

**Comment by fridrichovsky** [comment]
I tested the behavior of this process. I found that when I run the BcContainerHelper functions on a remote server (by New-PSSession and Invoke-Command), the wsmprovhsot.exe process remains running even after that (ended Invoke-Command and Remove-PSSession).
When I try Stop-Process during session it returns error because I stop  process that is used for Invoke-Command.
Do you have any idea how to stop this process "cleanly"?

**Comment by freddydk** [comment]
Remove-BcContainerSession should remove the session created by new-PsSession.
In these functions I also use Remove-PsSession
The applicationinsights dll from ContainerHelper is not used inside containers, BC inside the container might be using applicationinsights itself - but not the version from the containerhelper (I think).

The problem with DLL's are that they are loaded in PowerShell into the app domain and not unloaded before you exit PowerShell (a lot of blog posts about this online)

Can you share the code you use to always have the latest BcContainerHelper version loaded in your sessions (then I might have a different suggestion)

**Comment by fridrichovsky** [comment]
I am sorry that I missed one information. I am not using sessions inside container, but I am using sessions to another server. 
AzureDevOps Agent server (self-hosted) runs PowerShell commands on Docker server where I have containers. So Agent server use  New-PSSession and Invoke-Command for running PS comands on Docker server. There I use function "Install-BCContainerHelper" for update module. There is no problem if all wsmprovhost.exe are stopped. 
Problem is that process is started with first BcContainerHelper function and it remains after Remove-Session. If you publish new version of BcContainerHelper, my function update module without problem. But function can't remove older BcContainerHepler versions, because wsmprovhost.exe started from previous run use DLL file from older version. 

My function for update:
```powershell
function Install-BCContainerHelper {
    Param(
        [ValidateSet('AzureDevOps', 'Local', 'AzureVM')]
        [string] $buildEnv = "AzureDevOps",

        [Parameter(Mandatory = $false)]
        [string] $BCContainerHelperPath = '',

        [Parameter(Mandatory = $false)]
        [string] $BCContainerHelperVersion = ''
    )

    if (-not $BCContainerHelperVersion) { $BCContainerHelperVersion = "latest" }

    Write-Host "Version: $BCContainerHelperVersion"
    if ($BCContainerHelperPath -ne "" -and (Test-Path $BCContainerHelperPath)) {
        Write-Host "Using BCContainerHelper from $BCContainerHelperPath"
        . $BCContainerHelperPath
        install-module BCContainerHelper -force
    }
    else {
        $module = Get-InstalledModule -Name BCContainerHelper -ErrorAction SilentlyContinue
        if ($module) {
            $versionStr = $module.Version.ToString()
            Write-Host "BCContainerHelper $VersionStr is installed"
            if ($BCContainerHelperVersion -eq "latest") {
                Write-Host "Determine latest BCContainerHelper version"
                $latestVersion = (Find-Module -Name BCContainerHelper).Version
                $BCContainerHelperVersion = $latestVersion.ToString()
                Write-Host "BCContainerHelper $BCContainerHelperVersion is the latest version"
            }
            if ($BCContainerHelperVersion -ne $module.Version) {
                Write-Host "Updating BCContainerHelper to $BCContainerHelperVersion"
                Update-Module -Name BCContainerHelper -Force -RequiredVersion $BCContainerHelperVersion
                Write-Host "BCContainerHelper updated"
            }
        }
        else {
            if (!(Get-PackageProvider -Name NuGet -ListAvailable -ErrorAction SilentlyContinue)) {
                Write-Host "Installing NuGet Package Provider"
                Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force -WarningAction SilentlyContinue | Out-Null
            }
            if ($BCContainerHelperVersion -eq "latest") {
                Write-Host "Installing BCContainerHelper"
                Install-Module -Name BCContainerHelper -Force
            }
            else {
                Write-Host "Installing BCContainerHelper version $BCContainerHelperVersion"
                Install-Module -Name BCContainerHelper -Force -RequiredVersion $BCContainerHelperVersion
            }
            $module = Get-InstalledModule -Name BCContainerHelper -ErrorAction SilentlyContinue
            $versionStr = $module.Version.ToString()
            Write-Host "BCContainerHelper $VersionStr installed"
        }
    }
    $Latest = Get-InstalledModule BCContainerHelper
    $oldModules = Get-InstalledModule -Name BCContainerHelper -AllVersions -ErrorAction SilentlyContinue | Where-Object {$_.Version -ne $Latest.Version}
    if ($oldModules) {
        $oldModules | ForEach-Object {
            Write-Host ("Unstalling " + $_.Name + " ("  + $_.Version + ")")
            Uninstall-Module -Name $_.Name -RequiredVersion $_.Version
        }
    }
}
Export-ModuleMember -Function Install-BCContainerHelper
```

**Comment by freddydk** [comment]
This might be related to https://github.com/microsoft/navcontainerhelper/pull/2194 - which should be fixed in the latest prerelease.

**Comment by freddydk** [comment]
I have checked in a fix for this - when the new module is out, you should be able to uninstall after a reboot.
I will also create a new function that you can use as replacement for the above.

**Comment by fridrichovsky** [comment]
It is wonderfull that you find fix for this. Thank you.

**Comment by freddydk** [comment]
for local machines - if you use install-module to install a new BcContainerHelper, then you should be able to remove the old version after a restart.
The new version doesn't have the same problem, as I copy the DLL to programdata\bccontainerhelper and load it from there.

**Comment by freddydk** [comment]
On the code to use to load bccontainerhelper fast and smooth in pipelines, I will create a blog post for that.

**Comment by fridrichovsky** [comment]
Thank you. I am looking for it :-).

**Comment by freddydk** [comment]
Here is a small script, which can download and install containerhelper.
It does NOT use the PowerShell gallery - it downloads from a blob storage, where containerhelper is published as well as the gallery. This way is faster - and it is downloaded to a temp. folder and used from there - and the temp folder is cleaned up afterwards, meaning that this BcContainerHelper will only be loaded in this session and then discarded.

```
function Expand-7zipArchive {
    Param (
        [Parameter(Mandatory = $true)]
        [string] $Path,
        [string] $DestinationPath
    )

    $7zipPath = "$env:ProgramFiles\7-Zip\7z.exe"

    $use7zip = $false
    if (Test-Path -Path $7zipPath -PathType Leaf) {
        try {
            $use7zip = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($7zipPath).FileMajorPart -ge 19
        }
        catch {
            $use7zip = $false
        }
    }

    if ($use7zip) {
        Set-Alias -Name 7z -Value $7zipPath
        $command = '7z x "{0}" -o"{1}" -aoa -r' -f $Path, $DestinationPath
        Invoke-Expression -Command $command | Out-Null
    }
    else {
        Expand-Archive -Path $Path -DestinationPath "$DestinationPath" -Force
    }
}

function DownloadAndImportBcContainerHelper {
    Param(
        [string] $version = "latest",
        [switch] $checkExistingVersion
    )

    $tempName = Join-Path $env:TEMP ([Guid]::NewGuid().ToString())
    $webclient = New-Object System.Net.WebClient
    if ($version -eq "dev") {
        Write-Host "Downloading BcContainerHelper developer version"
        $webclient.DownloadFile("https://github.com/microsoft/navcontainerhelper/archive/dev.zip", "$tempName.zip")
    }
    else {
        Write-Host "Downloading BcContainerHelper $version version"
        try {
            $webclient.DownloadFile("https://bccontainerhelper.azureedge.net/public/$($version).zip", "$tempName.zip")
        }
        catch {
            $webclient.DownloadFile("https://bccontainerhelper.blob.core.windows.net/public/$($version).zip", "$tempName.zip")        
        }
    }
    Expand-7zipArchive -Path "$tempName.zip" -DestinationPath $tempName
    Remove-Item -Path "$tempName.zip"
    
    $BcContainerHelperPath = (Get-Item -Path (Join-Path $tempName "*\BcContainerHelper.ps1")).FullName

    if ($checkExistingVersion) {
        # Check existing version
        $NewVersion = Get-Content (Get-Item -Path (Join-Path $tempName "*\Version.txt")).FullName
        $module = Get-Module BcContainerHelper
        if ($module) {
            $ExistingVersion = Get-Content (Get-Item -Path (Join-Path (Split-Path $module.Path -Parent) "Version.txt")).FullName
            if ($NewVersion -eq $ExistingVersion) {
                Write-Host "BcContainerHelper version $newVersion is already installed/imported"
            }
            else {
                if ($version -eq "dev") {
                    Write-Host -ForegroundColor Yellow "BcContainerHelper version $ExistingVersion is already installed/imported. This version of AL-Go for GitHub expects the development version. If you experience issues, please uninstall all versions of BcContainerHelper from your build agent."
                }
                else {
                    Write-Host -ForegroundColor Yellow "BcContainerHelper version $ExistingVersion is already installed/imported. This version of AL-Go for GitHub expects $newVersion. If you experience issues, please uninstall all versions of BcContainerHelper from your build agent."
                }
            }
            Remove-Item $tempName -Recurse -Force
            $tempName = ""
        }
        else {
           . $BcContainerHelperPath
        }
    }
    else {
        . $BcContainerHelperPath
    }
    $tempName
}

function CleanupAfterBcContainerHelper {
    Param(
        [string] $bcContainerHelperPath
    )

    if ($bcContainerHelperPath) {
        try {
            Write-Host "Removing BcContainerHelper"
            Remove-Module BcContainerHelper
            Remove-Item $bcContainerHelperPath -Recurse -Force
        }
        catch {}
    }
}


$bcContainerHelperPath = DownloadAndImportBcContainerHelper -version dev -checkExistingVersion

# BcContainerHelper is loaded and ready to use





CleanupAfterBcContainerHelper -bcContainerHelperPath $bcContainerHelperPath
```

This is the mechanism used in AL-Go for GitHub (https://github.com/microsoft/al-go) which is our next-gen do-it-yourself CI/CD solution.
