### ISSUE TITLE
Encoding error when reading app.json

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#2181]
Your last [commit](https://github.com/microsoft/navcontainerhelper/commit/f5f48d9076b9d66370164067e9f833e5a45f2b36) where you added publisher to the Get-NavContainerAppRuntimePackage showed us an issue that has been present for a while.

We use a special character in our publisher. The special character is utf8 compatible but the default encoding for get-content seems to be utf8nobom which breaks the character. If I add -Encoding utf8 to the following line: https://github.com/microsoft/navcontainerhelper/blob/3ea704659c965026fbced850f652ff9051bb9da0/AppHandling/Run-AlPipeline.ps1#L1536 then everything works as expected.
I understand that this might be out of scope for this libary. 
I've tried to set $PSDefaultParameterValue but that doesn't work for cmdlets within a module. Maybe we can add a way to pass a default encoding. 

Since this breaks our pipelines we had to revert to 2.0.18-preview507 (last version where publisher was ignored)

**Comment by freddydk** [comment]
I do think that BcContainerHelper should be able to handle situations like this and I will check this and fix that for an upcoming version

**Comment by jonaswre** [comment]
Glad to hear it's in scope. If you need help with the implication I'd be glad to help. I would have created a PR but I'm not sure what's the best way to tackle the problem.

 Doing the DefaultParameter within the module or just add the encoding parameter to the lines that need it.

And should the module be configurable or force UTF-8? I've seen you already set UTF-8 hardcoded in some parts of the code.

**Comment by freddydk** [comment]
I will ask the Modern Dev team how the app.json file (and source files in general) should be handled and implement accordingly

**Comment by freddydk** [comment]
The fix for this is in the latest prerelease

**Comment by freddydk** [comment]
fixed in 2.0.19
