### ISSUE TITLE
[Suggestion] A DEV license valid for all countries

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#2185]
Hi Frreddy, 

I'm working in an international project with multiple BC databases around the world with different localizations.

Would be possible for Microsoft provide a DEV license to be used for CI/CD Pipelines that includes all objects ranges of the different localizations?

This would semplify the management of the licenses used in DevOps.

**Comment by freddydk** [comment]
I will discuss this with some people internally

**Comment by JesperSchulz** [comment]
May I ask, which kind of license you are using to run your CI/CD pipelines? If you're using a partner or even the demo license, it should already be open in the ID range from 1 - 50.000, which includes local ranges (10.000 - 30.000 - give or take). With a local partner or demo license, you should be able to compile and publish all other localizations as well!

**Comment by eclipses** [comment]
@JesperSchulz I use a Partner license so I do not have any issue with custom objects range 1 - 50.000.
My question is related to Standard Objects range that may be different per localization. 
When I download a Partner license from the Partner Source I need to specify for which version and which localization. Do you mean that it's irrelevant which localization I select I will get same Partner licese with same objects?
Please confirm

**Comment by JesperSchulz** [comment]
Except for the license header, the partner license should be identical regardless of the localization you choose, yes. I haven't actually tried this myself, but I would be surprised if you could not use an IT localization partner license to run an ES localization CI/CD pipeline. I would give it a shot! If anything fails, please let me know and I'll see what we can do.

**Comment by eclipses** [comment]
@JesperSchulz I did not create a failure scenario rather I've downloaded detailed report in txt for a Partner BC 19 license with IT localization and ES localization as you suggested in your example and comparing them there are differences. Maybe you can have a look as well and share your opinion.

**Comment by JesperSchulz** [comment]
I would need your license dumps, as the ones I create may be very different from yours. Could you somehow make them available to me? Maybe reach out to me on Yammer or LinkedIn for a more private forum?

**Comment by JesperSchulz** [comment]
Opinion shared in private conversation. Please close the issue, if you feel like your questions have been answered :-)
