### ISSUE TITLE
Question regarding bccontainerhelper telemtry

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#2186]
Hey @freddydk, 

I see that you are added lots of code for telemtry in bccontainerhelper. It would be very helpful when troubleshooting issues bccontainerhelper. 

Is it something that we could use already? 
Do you have a documentation/example somewhere how we can do it?

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
I am waiting for this to be reviewed - then I will enable, document and use.
Expect sometime in November...
