### ISSUE TITLE
Strange issue with Copy-FileToNavContainer.ps1 & $hostHelperFolder

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#2188]
Hey @freddydk, 

I have a strange issue with **Copy-FileToNavContainer** function. I am calling this function through **Import-ObjectsToNavContainer**. It works on my local machine, but it does not work on my agent machine, which runs the pipeline. And cannot figure it out why. Perhaps you can help me out here.

It simply fails because **$hostHelperFolder** variable is blank.  
![image](https://user-images.githubusercontent.com/16342128/141294794-1eeddbf3-d510-4fc5-bb2c-ad091beb7593.png)

I cannot find how can I fill this variable, and why does it work on my local environment. 

If i check **$bcContainerHelperConfig**, it prints me all settings nicely.

![image](https://user-images.githubusercontent.com/16342128/141295290-b364c511-3c4a-41d6-8d9d-735eb7cc9fcf.png)

When does **$hostHelperFolder**  is supposed to be initialized?

Best Regards, 
Gintautas

**Comment by gintuoklis** [comment]
mystery solved :)

on my local machine i use bccontainerhelper to spin my container.
on buildagent machine, i use ALOPS to spin my container. ALOPS does not mount volumes for bccontainerhelper. Once I added additional volumes, it started working correctly.

![image](https://user-images.githubusercontent.com/16342128/141312781-c3933fac-7b09-4139-98b5-3514a2053286.png)

**Comment by freddydk** [comment]
In general, you cannot use the BcContainerHelper commands with contaniers unless the container was generated using New-BcContainer (or... - if you know what you are doing - as you clearly do:-))
