### ISSUE TITLE
Enum Extension range issue Al-Validation

### ISSUE THREAD

**Issue by HFS-terryKane** [microsoft/navcontainerhelper#2189]
BC 19 app AlValidation run. We created an Enum Extension object with field ID in 4 and 5 range. If I changed the IDs to be within our range then AlValidation passes. However, the Validation for App Submission fails because it is expecting values 4 and 5 fields that are no longer there. How do we get past this issue? I'm running the latest BCContainerHelper stable release.

Below is the error:

2 errors found in Harvest Food Solutions_HFS DSDMFG Base_3.3.0.1448.app on https://bcartifacts.azureedge.net/sandbox/19.1.31886.32186/us:
src\MainApp\src\EnumExt\EnumExt70243477.HFSPriceCalculationHandler.al(3,14): info AS0099: The ID '5' for the EnumValue 'HFS Specific Price' is not valid. It should be within the ran
ge '[70243475..70243574]', which is allocated to the application, and outside the range '[50000..99999]', which is allocated to per-tenant customizations.
src\MainApp\src\EnumExt\EnumExt70243487.HFSPriceCalculationMethod.al(3,14): info AS0099: The ID '5' for the EnumValue 'HFS Specific Price' is not valid. It should be within the rang
e '[70243475..70243574]', which is allocated to the application, and outside the range '[50000..99999]', which is allocated to per-tenant customizations.

**Comment by freddydk** [comment]
Did you add the previous version of your app?
Validation should not complain if these fields earlier was approved with id 4 and 5 - and still are.

**Comment by HFS-terryKane** [comment]
We were using two methods from the System Base app which were removed. It wouldn't allow the BC18 previous apps to be installed for validation on BC19. So we couldn't use the BC18 upgrade option.

**Comment by freddydk** [comment]
Right now - Run-AlValidation uses the "old" validation mechanism with actually installing and upgrading apps.
The automated validation service doesn't do this.
If you add the old version and use -skipUpgrade - you might be able to succeed.

I will change the function to run validation in the same way as the validation service - just haven't had the time:-(

**Comment by HFS-terryKane** [comment]
This solution works. The only issue would be that we would fail to catch any issues normally captured during the upgrade process of the validation. Thanks freddy!

**Comment by freddydk** [comment]
Correct
For issues normally captured during validation, you should include the previous version in your build process and do upgrade tests there.
But in the end - this is why I always recommend that people keep the current version compatible with next major.
Of course you cannot uptake new functionality before the new version is out - but the version you have running for v19 now - should also work for v20 already now.

**Comment by HFS-terryKane** [comment]
I'm in agreement. We will try to do our best moving forward. Thanks!
