### ISSUE TITLE
Mismatch in BC 14 versions

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#2195]
The Artifacts for BC14 seem to be misaligned

**Scripts used to create container and cause the issue**
Get-BcArtifactUrl -type 'OnPrem' -version '14.5' -country 'dk' -select 'Latest'

**Full output of scripts**
https://bcartifacts.azureedge.net/onprem/14.5.35970.0/dk

**Additional context**
According to https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/update-versions-14 build 35970 is cumulative update 4, not 5

Not the end of the world as we can just change the version number in the script. But thought I'd bring it to your attention for when you are not busy ;)

**Comment by freddydk** [comment]
Artifacts for Business Central doesn't have CU numbers, they are just numbered 14.5, 14.6 etc.

The fact that 14.0 is called cumulative update 1 on the docs site is strange (https://support.microsoft.com/en-us/topic/cumulative-update-01-for-microsoft-dynamics-365-business-central-spring-2019-update-on-premises-application-build-14-0-32615-platform-build-14-0-32600-62fd4ee3-c5bd-0a3b-6b72-5de45d358215) not sure whether that is correct.

In the end - you request an application version number in artifacts and you get that.
