### ISSUE TITLE
License error with BC v19

### ISSUE THREAD

**Issue by alex260570** [microsoft/navcontainerhelper#2197]
I'm not able to create a new BC 2021 Wave 2 container with the test toolkit included. It gives me this error message:
Your program license does not allow you to publish 'ERM Tests Data Admin Guide'.
The error occurs when Microsoft_Tests-ERM_19.0.29894.32639.app is published
I tried with a customer license and the cronus one. I don't have a dev license, but it all worked just fine with V18.
Is there anything I can do?

**Comment by freddydk** [comment]
The test framework and the test libraries are included in the CRONUS license.
The actual Microsoft tests are not - for those you need a developer license.

**Comment by freddydk** [comment]
You might need just to add -includeTestFrameworkOnly or -includeTestLibrariesOnly to your command, but since you didn't include your command it is hard to see.
