### ISSUE TITLE
idea/proposal: Update host file after start/stop container

### ISSUE THREAD

**Issue by irijcken** [Microsoft/navcontainerhelper#22]
If you manually stop and and start a container, the container will receive a new ip-address. It would be nice if we could call a PS-function to update the hosts file if a hosts entry exists for that container name.

I might create a PR for this during the weekend.

Something like (fuzzy code):
foreach (name in docker ps) {
  Get-NavContainerIpAddress | Update-Hosts
}

**Comment by freddydk** [comment]
I have a different idea, which will automate this.
I just need to check whether it works:-)

**Comment by sodgeronimo** [comment]
i was looking into this as well and just pulled out the update hosts function to be able to do it manually for now

looking forward to see how this will be handled :-)

**Comment by irijcken** [comment]
I hold my horses.

**Comment by freddydk** [comment]
The way it is going to be is:
(in new-navcontainer)

    if ($updateHosts) {
        $parameters += "--volume ""c:\windows\system32\drivers\etc:C:\driversetc"""
        Copy-Item -Path (Join-Path $PSScriptRoot "updatehosts.ps1") -Destination $myfolder -Force
        '
        . (Join-Path $PSScriptRoot "updatehosts.ps1") -hostsFile "c:\driversetc\hosts" -hostname $hostname -ipAddress $ip
        ' | Add-Content -Path "$myfolder\AdditionalOutput.ps1"
    }

Share the drivers\etc folder with the container and ask the container to update itself upon start or restart.
In Remove-navcontainer it will check whether the folder is shared with the container and remove the entry if this is the case.

**Comment by freddydk** [comment]
Implemented in navcontainerhelper 0.2.0.1
