### ISSUE TITLE
Powershell 7 Support

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#2200]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I would like to use PowerShell 7 because in 5.1 i have many issues with Az Commands but bccontainerhelper doesn't support PowerShell 7 at the moment.

**Scripts used to create container and cause the issue**
```
Import-Module BcContainerHelper
```

**Full output of scripts**
```
Import-Module: The script 'BcContainerHelper.psm1' cannot be run because it contained a "#requires" statement for PowerShell editions 'Desktop'. The edition of PowerShell that is required by the script does not match the currently running PowerShell Core edition.
```

**Screenshots**

**Additional context**
- bccontainerhelper 2.0.19
- powershell: 7.2

**Comment by NAVspecialist** [comment]
Hi @Spycoclown 

If you have spent just a few seconds in the issues list,  you would have known that Bccontainerhelper is not supported with Powershell 7 as it requires a major rework of like everything.

Thanks

/Palle

**Comment by freddydk** [comment]
At this time, there are too many dead ends if we head down the road of using PowerShell 7.
Most likely I will keep BcContainerHelper running PowerShell 5 and gradually move things into a new PowerShell 7 project.
BcContainerHelper7 - compatible, but probably won't support pre-BC15 containers (no C/AL functions)
My assumption is that this work will start sometime over the next 6 months.

**Comment by freddydk** [comment]
I will close this one as ships in a future version.
