### ISSUE TITLE
bcsandbox: -assignPremiumPlan does not enable Manufacturing, Service, or Advanced in Application Areas

### ISSUE THREAD

**Issue by mtaanquist** [Microsoft/navcontainerhelper#221]
Apologies if this belongs in the nav-docker repository. Let me know and I will move it there.

In prep for setting up a demo with the latest version of Business Central, I wanted to set up a container to play around with. When I did that, I noted that there was none of the manufacturing functionality there. 

With help from your article on the [navteam blog](https://blogs.msdn.microsoft.com/nav/2018/04/13/enabling-premium-experience-in-business-central-sandbox-containers/), I learnt about the `-assignPremiumPlan` parameter, but it doesn't seem to be doing anything.

Running `NavContainerHelper`, version 0.3.1.4, and using the latest `microsoft/bcsandbox:dk`

**Command:**
```
New-NavContainer 
    -containerName bc-onprem-dk 
    -imageName microsoft/bcsandbox:dk 
    -accept_eula 
    -auth NavUserPassword 
    -assignPremiumPlan
    -includeCSide
    -doNotExportObjectsToText 
    -updateHosts
```

**Initialisation output:**
```
Removing container bc-onprem-dk
Removing bc-onprem-dk from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bc-onprem-dk
Creating Nav container bc-onprem-dk
Using image microsoft/bcsandbox:dk
NAV Version: 13.0.24630.24844-DK
Generic Tag: 0.0.6.6
Container OS Version: 10.0.14393.2430
Host OS Version: 10.0.17134.0
The container operating system does not match the host operating system, forcing hyperv isolation.
Creating container bc-onprem-dk from image microsoft/bcsandbox:dk
Waiting for container bc-onprem-dk to be ready
Initializing...
Starting Container
Hostname is bc-onprem-dk
PublicDnsName is bc-onprem-dk
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user mt
Setting SA Password and enabling SA
Creating SUPER user
Assign Premium plan for MT
Container IP Address: 172.28.202.140
Container Hostname  : bc-onprem-dk
Container Dns Name  : bc-onprem-dk
Web Client          : http://bc-onprem-dk/NAV/
Dev. Server         : http://bc-onprem-dk
Dev. ServerInstance : NAV

Files:
http://bc-onprem-dk:8080/al-2.0.43900.vsix

Initialization took 162 seconds
Ready for connections!
Set TimeZone in Container to Romance Standard Time
Reading CustomSettings.config from bc-onprem-dk
Creating Desktop Shortcuts for bc-onprem-dk
Nav container bc-onprem-dk successfully created
```
However, when accessing the service tier through the web client, I do not see any of Application Areas ticked in the list, and I am not able to modify them:

![image](https://user-images.githubusercontent.com/12089874/46740138-666d2f80-cca2-11e8-8490-7be20bbb2501.png)

I do not have other users to set up than my own, so I did not use the `Setup-NavContainerTestUsers` cmdlet. 

Let me know if you require any further information.

**Comment by freddydk** [comment]
You container is called bc-onprem - but you are spinning up a bcsandbox.
Looking here: https://hub.docker.com/r/microsoft/bconprem/ 
the image you want to use for on-prem is
mcr.microsoft.com/businesscentral/onprem:dk
That should not require premiumplan. I think premiumplan is something for online.

**Comment by mtaanquist** [comment]
Thank you, Freddy. 

I don't think I've seen that Docker image referred in any of the documentation I've read so far, which made me think that it was the same for both on-premise and cloud.

I'll close this out. I appreciate the quick response.
