### ISSUE TITLE
AppSourceCop reacts differently in Run-AlValidation and Compile-AppInBCContainer

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/navcontainerhelper#2212]
Our pipeline first runs Compile-AppInBCContainer to create the app package. 
Then it uses this app package and the last successfully released package to run Run-AlValidation.
We have an app which has a enumextension with an enum value without affix. This leads to the *warning AS0098*.

Compile-AppInBCContainer with enabled AppSourceCop fails with *error AS0011*

When disabling the AppSourceCop in Compile-AppInBCContainer and running Run-ALValidation on the outcoming App-File the AppSourceCop displays the expected warning *warning AS0098*.

BCContainerhelper Version is 2.0.22

**Comment by freddydk** [comment]
AS0011 is https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/appsourcecop-as0011
Sounds like you haven't setup mandatoryaffixes in the appsourcecop.json file for compile-appinbccontainer.
(Run-AlValidation creates the appsourcecop.json on the fly)

**Comment by mmenninghaus** [comment]
Excluding the appsourcecop.json in the project inevitably leads to
error AS0054: The AppSourceCop configuration must specify one of the following properties: 'mandatorySuffix', 'mandatoryPrefix', or 'mandatoryAffixes'
when compiling the app.
The affixes are setup, and in the Compile-AppInBCContainer the error AS0011 instead of an expected warning AS0098 is thrown.

**Comment by freddydk** [comment]
Next version of Run-AlValidation will validate in the same way as the validation service.
The version should be available as prerelease a little later today.
Please test out this version and let me know if it solves the issue, thanks

**Comment by freddydk** [comment]
Latest prerelease should have this fix, please confirm, thanks.

**Comment by freddydk** [comment]
shipped in 2.0.23

**Comment by mmenninghaus** [comment]
Thank you for your effort! - it does not produce the error as described above - still the warnings while using Compile-AppInBCContainer and Run-ALValidation seem to differ. I will double check the Code Cop Rules and get back to you if any further issue emerges.
