### ISSUE TITLE
AS0099 acts out in Run-ALValidation

### ISSUE THREAD

**Issue by waldo1001** [microsoft/navcontainerhelper#2215]
I also created a yammer-thread about this, but it seems a problem in the BcContainerHelper.

https://www.yammer.com/dynamicsnavdev/threads/1502614861414400

As you can see, info-message AS0099 is reported as an error:
![image](https://user-images.githubusercontent.com/12088142/144628180-93595678-6406-475c-9e91-31e09e6df36e.png)

Is it may be an idea - as we don't really want to see this "info" in the pipeline - to put AS0099 as "None" in the default ruleset?
https://bcartifacts.azureedge.net/rulesets/appsource.default.ruleset.json

**Comment by freddydk** [comment]
Run-AlCops will now ignore all infos - unless you add a parameter called -doNotIgnoreInfos

**Comment by freddydk** [comment]
2.0.23 has shipped
