### ISSUE TITLE
Run-AlValidation fails with dependency app

### ISSUE THREAD

**Issue by marianarmendes** [microsoft/navcontainerhelper#2216]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I have a dependency in my app. I have the runtime package for the 3rd party app. When I try to run the validation with the runtime package it doesn't work and I guess that is normal. The problem is, when I try to run the validation with the .app alpackage, after downloading the symbols, it doesn't work either.

**Scripts used to create container and cause the issue**
$validation = Run-AlValidation -licenseFile $licenseFile -apps ".\Arquiconsult_NAVHR_19.0.0.0.app" -installapp ".\Softstore SA_SOFTSTORE Localization Pack for Portugal_19.0.3.0.app" -affixes "QQQNHR" -countries "pt" -skipVerification

**Full output of scripts**
Creating container for country pt
BcContainerHelper is version 2.0.22
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 20.10.10
Docker Server Version is 20.10.10
Downloading application artifact /sandbox/19.1.31886.33316/pt
Downloading C:\Users\mariana.mendes\AppData\Local\Temp\4aa518c4-cf05-4b25-8c3d-f5d3a259f5c7.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/19.1.31886.33316/platform
Downloading C:\Users\mariana.mendes\AppData\Local\Temp\20cabf33-1c3e-4e1d-976c-eca556201814.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\19.1.31886.33316\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\19.1.31886.33316\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\19.1.31886.33316\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.17763.2300
Creating Container bcserver
Style: sandbox
Multitenant: No
Version: 19.1.31886.33316
Platform: 19.0.31889.33296
Generic Tag: 1.0.1.8
Container OS Version: 10.0.17763.2300 (ltsc2019)
Host OS Version: 10.0.17763.2300 (ltsc2019)
Using process isolation

**Screenshots**
![image](https://user-images.githubusercontent.com/95492223/144648898-bb351d3a-51eb-4cbb-ab47-3be6bd0dfdf1.png)

**Additional context**
- does it happen all the time? yes
- did it use to work? no

**Comment by freddydk** [comment]
Next version of Run-AlValidation will validate in the same way as the validation service and that should solve this problem.
I will let you know when the version is available as prerelease a little later today

**Comment by freddydk** [comment]
Latest prerelease should have this fix, please confirm, thanks.

**Comment by marianarmendes** [comment]
Unfortunately I have the same error. I reinstalled container helper, not sure if I had to do it. Install-Module BcContainerHelper -force. 

So as per your comment, this will not happen if I submit my app for validation?

thanks

**Comment by freddydk** [comment]
In order to get the prerelease version you need to add -allowPrerelease (see here: https://freddysblog.com/2020/08/11/bccontainerhelper/)

**Comment by freddydk** [comment]
shipped in 2.0.23

**Comment by marianarmendes** [comment]
I confim, working. thanks Freddy.
