### ISSUE TITLE
issue publishing app from visual studio code

### ISSUE THREAD

**Issue by Bssivivek** [Microsoft/navcontainerhelper#222]
Hi - I downloaded the latest Business central image (microsoft/bcsandbox:us) and created the container.
while creating the container i found some issues in the log
![container](https://user-images.githubusercontent.com/38437776/46764236-c9ee6180-cc90-11e8-828d-22f7237db89c.jpg)
However, container was created and i was able to login to Business central.
When i try to publish my app from visual studio code (by clicking ctrl + F5). I get below error

![publish_error](https://user-images.githubusercontent.com/38437776/46764365-1c2f8280-cc91-11e8-8b30-e60fff3861cf.jpg)

I also tried the same for microsoft/bcsandbox:de and still the same issue

**Comment by freddydk** [comment]
Not sure it has anything to do with the error, but the error states that you cannot have a . in the username.
In VS Code which kind of server did you choose: Cloud Sandbox or Your own server?

**Comment by Bssivivek** [comment]
thanks for clarification. wrt below error
![image](https://user-images.githubusercontent.com/38437776/46764676-efc83600-cc91-11e8-8c83-1137fd45d43e.png)
I installed the latest image and container using dockers and try publishing the app.

**Comment by freddydk** [comment]
And I asked you which kind of server you choose in VS Code?
Cloud Sandbox or Your Own Server?
How does launch.json look?

**Comment by Bssivivek** [comment]
I am using "Your own server". Pleae find the screen shot below
![image](https://user-images.githubusercontent.com/38437776/46765590-420a5680-cc94-11e8-92c0-0a3a05a07519.png)

**Comment by freddydk** [comment]
It looks like you have some upgrade code or like in your extension - some code which is executed at this time, which causes this problem.
Can that be?

**Comment by freddydk** [comment]
I think there are events on OnInstallAppPerDatabase and OnInstallAppPerCompany - not sure what they should be used for, but I guess they have a purpose, you will have to read about that elsewhere. I cannot say that you are not supposed to use them, as I don't know.

**Comment by Bssivivek** [comment]
thanks a lot Freedy!! i looked into this issue and it looks like we were trying to read data from NAVAPP table. For some reason, the license file has issue accessing NAVAPP table. There is already a open issue in github.
https://github.com/Microsoft/nav-docker/issues/268

you can close this. thanks a lot for all your help!!

**Comment by Bssivivek** [comment]
Hi Freedy!! we looked into it and narrowed down the issue. We make service call OnInstallAppPerCompany() and that's causing the below error

<img width="656" alt="image" src="https://user-images.githubusercontent.com/38437776/46824396-8efa3580-cd45-11e8-9fc5-cd0cd75f3e32.png">

However, when we comment the code, it publishes fine but when we make service call in other places we are getting below error
<img width="237" alt="image" src="https://user-images.githubusercontent.com/38437776/46824593-36776800-cd46-11e8-8277-e3d4332ab2bd.png">
<img width="238" alt="image" src="https://user-images.githubusercontent.com/38437776/46824599-3a0aef00-cd46-11e8-8b0f-d6b9b069ec65.png">

so I think it has some thing to do with service call and/or license issue (to access NAVAPP table)

**Comment by freddydk** [comment]
The question is by design, the error is because of your license file.
You need to get an updated license file with these new objects in

**Comment by shashiBssi** [comment]
@freddydk 
Hi Freddy,
Our App was working fine with earlier versions of microsoft/bcsandbox:us (i.e before 1st oct versions).

Our App is working fine  in DVD installation of OnPrem.
Our App is working fine in DVD image docker version of OnPrem.

We are only getting error of callback function in latest image of microsoft/bcsandbox:us (after 1st oct  versions).

Do you think we have license issue ?

**Comment by Bssivivek** [comment]
Hi Freddy,
Our App was working fine with earlier versions of microsoft/bcsandbox:us (i.e before 1st oct versions).
Our App is working fine in DVD installation of OnPrem.
Our App is working fine in DVD image docker version of OnPrem.
We are only getting error of callback function in latest image of microsoft/bcsandbox:us (after 1st oct versions).
Do you think we have license issue ?

**Comment by freddydk** [comment]
Yes, it is a license issue - before october 1st, you were testing on the latest releases of spring 2018 release - now you are on fall 2018 release and these tables were added.
You can also try to use fall 2018 onprem release on docker, that will probably work.
Find the docker image url here https://hub.docker.com/r/microsoft/bconprem/
