### ISSUE TITLE
AS0054 - The AppSourceCop configuration must specify one of the following properties: 'mandatorySuffix', 'mandatoryPrefix', or 'mandatoryAffixes'

### ISSUE THREAD

**Issue by BennoVendrig** [microsoft/navcontainerhelper#2222]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Our pipeline is running including the option enableAppSourceCop = true

![image](https://user-images.githubusercontent.com/85997468/145262090-c4def14b-467f-4b02-8571-9ea9d524fba1.png)

We also have the file AppSourceCop.json at the same level as the app.json file
![image](https://user-images.githubusercontent.com/85997468/145262256-7e4f0852-e624-47f7-b2c2-fce42a814bf6.png)

If we don't add the AS0054 option to have the suppressWarnings section in the app.json file the error below occurs:
The AppSourceCop configuration must specify one of the following properties: 'mandatorySuffix', 'mandatoryPrefix', or 'mandatoryAffixes'
What I also see is that the Compiling Apps part of the Run-AlPipeline.ps1 deletes the AppSourceCop.json on the build server. This is perhaps related to this issue.

```
BcContainerHelper version 2.0.21
Image bcimage:sandbox-18.5.29545.33499-nl-mt
...

**Additional context**
- does it happen all the time? Yes
- did it use to work? No

**Comment by freddydk** [comment]
The pipeline creates the appsourcecop.json on the fly - you need to provide the mandatoryaffixes array in the settings file like here: https://github.com/BusinessCentralApps/HelloWorld.AppSource/blob/master/scripts/settings.json

**Comment by BennoVendrig** [comment]
Hi Freddy,
Thanks for the answer. I've tested this before but this seems not to work. I did a test again today.

I have a file called DoubleScanInventLines.Query.al. This is not correct in our case because the filename doesn't contain the suffx ZRG. The correct fillename is DoubleScanInventLinesZRG.Query.al

**Without** the setting "appSourceCopMandatoryAffixes": "ZRG" the warning and error below exists in the pipeline:
![image](https://user-images.githubusercontent.com/85997468/145483705-7fca490c-c57a-4e7f-8c98-46f0bb13f4c8.png)

With the setting "appSourceCopMandatoryAffixes": "ZRG" I expect just the warning in the pipeline, but no warning occurs. It's correct no error occurs. The pipeline executes succcessfully, but as mentioned the pipeline should executes with a warning.

**Comment by freddydk** [comment]
The AA one is a codecop warning.
AppSource Validation does not care about codecop or UI Cop.
AppSource Cop doesn't care about your file names.

**Comment by BennoVendrig** [comment]
Hi Freddy,
This is clear. But how is it possible that with the option "appSourceCopMandatoryAffixes": "ZRG" I don't receive the AA warnings anymore? It seems the "appSourceCopMandatoryAffixes": "ZRG" option has a dependency with the codecop validations.

**Comment by freddydk** [comment]
It is just a warning - cannot remember but maybe there is a setting to filter out warnings
