### ISSUE TITLE
BC Docker v19 - invalid character '\x00'

### ISSUE THREAD

**Issue by steveflorko** [microsoft/navcontainerhelper#2224]
Has anyone run into a and error creating a new container, win 11 machines (never prior installed) and receive error  \x00

----------------------------------------------------------------------------------------------------------

PS C:\WINDOWS\system32> New-BcContainer `
>>     -accept_eula `
>>     -artifactUrl (Get-BCArtifactUrl -country us) `
>>     -auth UserPassword `
>>     -Credential (Get-Credential) `
>>     -updateHosts

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
BcContainerHelper is version 2.0.22
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro - 21H2
Docker Client Version is 20.10.11
Docker Server Version is 20.10.11
Downloading application artifact /sandbox/19.1.31886.33595/us
Downloading C:\Users\person\AppData\Local\Temp\1979bdd7-97c3-469d-b3f6-49b741c01efd.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/19.1.31886.33595/platform
Downloading C:\Users\person\AppData\Local\Temp\f2cdf82d-3853-417d-897a-1c361bb05001.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\19.1.31886.33595\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\19.1.31886.33595\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\sandbox\19.1.31886.33595\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.20348.350
Creating Container bcserver
Style: sandbox
Multitenant: Yes
Version: 19.1.31886.33595
Platform: 19.0.31889.33481
Generic Tag: 1.0.1.8
Container OS Version: 10.0.20348.350 (ltsc2022)
Host OS Version: 10.0.22000.348 (21H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\bcserver\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bcserver from image mcr.microsoft.com/businesscentral:10.0.20348.350

**DockerDo : docker: Error response from daemon: Failed to unmarshall layerchain json - invalid character '\x00' looking for beginning of value.**

See 'docker run --help'.
ExitCode: 125
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav= --env isBcSandbox=Y --label version=19.1.31886.33595 --label platform=19.0.31889.33481 --label country=US --env
artifactUrl=https://bcartifacts.azureedge.net/sandbox/19.1.31886.33595/us --env multitenant=Y --env licenseFile="" --name bcserver --hostname bcserver --env auth=NavUserPassword --env
username="person" --env ExitOnError=N --env locale=en-US --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume
"C:\ProgramData\BcContainerHelper\Extensions\bcserver\my:C:\Run\my" --isolation process --restart unless-stopped --env filesOnly=False --env enableApiServices=Y --env useSSL=N --volume
"c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=xxxxxx= --env passwordKeyFile="xxxx" --env
removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral:10.0.20348.350
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\2.0.22\ContainerHandling\New-NavContainer.ps1:1790 char:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
Looks like a problem in your docker file system.
Maybe a cleanup using the reset function of docker desktop or this tool: https://freddysblog.com/2018/12/11/clean-up-after-yourself-docker-your-mom-isnt-here/ can help you.
