### ISSUE TITLE
'is not a valid date' Issues using Export-NavContainerObjects and Import-ObjectsToNavContainer

### ISSUE THREAD

**Issue by jacmax** [microsoft/navcontainerhelper#2225]
Hello,

**Describe the issue**
I try to do a simple test of scipt for export and import objects.
First step: export object,  (Export-NavContainerObjects)
Next step: import the result of first step, (Import-ObjectsToNavContainer)
the error is:
**'20190324D;' is not a valid date. -- File: C:\ProgramData\BcContainerHelper\objects\tab9.txt**

Should I change something in docker environment?

BcContainerHelper: 2.0.16
Docker: zs-bc140:onprem-14.0.29537.0-w1

The script:
```
$SourceFolder = 'c:\programdata\bccontainerhelper\objects'
$SourceFile = 'tab9.txt'
$containerName14 = 'zs-bc140'

Export-NavContainerObjects `
    -containerName $containerName14 `
    -objectsFolder $SourceFolder `
    -filter 'modified=No;ID=9'

Import-ObjectsToNavContainer `
    -containerName $containerName14 `
    -objectsFile (Join-Path $SourceFolder $SourceFile)
```

file tab9.txt

```
OBJECT Table 9 Country/Region
{
  OBJECT-PROPERTIES
  {
    Date=20190324D;
    Time=120000T;
    Version List=NAVW114.00;
  }
  PROPERTIES
.....

```

```
: [86573217] '20190324D;' is not a valid date. -- File: C:\ProgramData\BcContainerHelper\objects\tab9.txt
[0] The import stopped at line 5. -- File: C:\ProgramData\BcContainerHelper\objects\tab9.txt

at Import-NAVApplicationObject<Process>, C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 147
at <ScriptBlock>, <No file>: line 27
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at Import-ObjectsToNavContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ObjectHandling\Import-ObjectsToNavContainer.ps1: line 47
at <ScriptBlock>, <No file>: line 10
```

**Comment by freddydk** [comment]
These functions works with C/AL - haven't looked at them in ages.
I think the export function has an -exportTo parameter to determine what format it exports to - the above looks to be the new syntax (used for converting to AL). the old syntax can be imported in NAV again.

**Comment by jacmax** [comment]
I added an option on export: -exportTo 'txt folder' `

it is working

Thank you
