### ISSUE TITLE
AL-Go for GitHub vs DevOps

### ISSUE THREAD

**Issue by BW-PA** [microsoft/navcontainerhelper#2234]
Hi Freddy,

I've noticed you mentioned [AL-Go for GitHub](https://github.com/microsoft/AL-Go) in a few issues lately and it looks fantastic.  Are you able to provide any clarification on the direction of the AL CI/CD tool chain?  We currently have our extensions in Azure DevOps, will the features in AL-Go Github be making their way to Azure DevOps also or should we be considering a move from Azure DevOps to GitHub in the near future?

I'm conscious I might be jumping the gun here, but got excited when I saw the features in AL-Go for GitHub.  So if the answer is to be patient and wait for an official announcement, I can do that 😅

**Comment by freddydk** [comment]
AL-Go for GitHub was demoed for the first time at the BC Beerinar on Friday last week.
AL-Go for GitHub is our 3rd iteration of do-it-yourself CI/CD and this one will be GitHub only.
Utilmately we want to have everybody to use CI/CD of some kind, meaning that we needed to make it plug and play.
With plug and play we had to choose one platform (not enough ressources to do both) and the selection landed on GitHub,

Why GitHub:
- Azure DevOps seems more enterprise style (complex?)
- GitHub was born for cloud, open source and agile
- Other alternatives exists for Azure DevOps (ALOps, Cosmo, …)
- We want to support codespaces
- Very good for open-source projects

**Comment by BW-PA** [comment]
Thanks Freddy,

It was the plug and play nature that appealed to me with AL-Go for GitHub.  We are an enterprise organisation (Hence Azure DevOps) and it is more complex to implement CI/CD compared to the features available in AL-Go for GitHub.  Though I need to investigate ALOps, Cosmo etc.

**Comment by freddydk** [comment]
BTW - I didn't mean to say that enterprise organizations should use Azure DevOps - I just stated that the functionality of Azure DevOps is more enterprise style - kind of like Visual Studio compared to VS Code.

**Comment by fvet** [comment]
@BW-PA Did you already chose a direction? I enfavour the Al-Go initiative too, but since we're already running Azure DevOps too, we'd like to keep all product related features in one central platform and opted for ALOps (instead of custom building using Powershell)
