### ISSUE TITLE
DockerDo : a Windows version 10.0.20348-based image is incompatible with a 10.0.19044 host

### ISSUE THREAD

**Issue by HennieBink** [microsoft/navcontainerhelper#2235]
**Script:**

$containerName = 'bc19-nl'
$credential = Get-Credential -Message 'Using UserPassword authentication. Please enter credentials for the container.'
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'nl' -select 'Latest'
$licenseFile = 'c:\xxxx.flf'
$bcartifactsCacheFolder = 'C:\xxxxx\AL\Microsoft'

Remove-BcContainer $containerName

New-BcContainer 
    -accept_eula 
    -containerName $containerName 
    -credential $credential 
    -auth $auth 
    -artifactUrl $artifactUrl 
    -imageName 'bc19-nl' 
    -licenseFile $licenseFile 
    -memoryLimit 3G 
    -updateHosts 
    -includeAL 
    -usegenericimage (Get-BestGenericImageName) 
    -isolation hyperv

Create-AlProjectFolderFromNavContainer -containerName $containerName -alProjectFolder $bcartifactsCacheFolder -useBaseLine -useBaseAppProperties

**Comment by HennieBink** [comment]
**Result**

PS C:\WINDOWS\system32> C:\xxxxx\bc19-nl - Working.ps1
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - Unknown/Insider build
Docker Client Version is 20.10.11
Docker Server Version is 20.10.11
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building image bc19-nl:onprem-19.2.32968.33504-nl based on mcr.microsoft.com/businesscentral:10.0.20348.169 with https://bcartifacts.azureedge.net/onprem/19.2.32968.33504/nl
Pulling non-existing base image mcr.microsoft.com/businesscentral:10.0.20348.169
10.0.20348.169: Pulling from businesscentral
DockerDo : a Windows version 10.0.20348-based image is incompatible with a 10.0.19044 host
ExitCode: 1
Commandline: docker pull  mcr.microsoft.com/businesscentral:10.0.20348.169
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.16\ContainerHandling\New-NavImage.ps1:270 char:21
+ ...                  DockerDo -command pull -imageName $baseImage | Out-N ...
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by HennieBink** [comment]
**Windows version host**

Microsoft Windows [Version 10.0.19044.1415]

**Comment by HennieBink** [comment]
With or without the following options give same error.

-usegenericimage (Get-BestGenericImageName)
-isolation hyperv

**Comment by freddydk** [comment]
I think this was fixes in 2.0.17 or 2.0.18

**Comment by HennieBink** [comment]
Thanks! I installed version 3.0 with the following script and now it works fine!

Remove-Module BcContainerHelper
Uninstall-module bccontainerHelper -allversions
Install-module bccontainerhelper
