### ISSUE TITLE
BcContainerHelperConfig "MicrosoftTelemetryConnectionString"

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#2239]
Hello Freddy, 

as you described in your previous post:

Setting the parameter "**MicrosoftTelemetryConnectionString**" to an empty string, disables the telemetry. 
Since this is a global setting, it will apply to all of the soon to be created containers. 

The question: 
Is there a way to enable the temeletry for a specific container if we wanted to. We have scripts running in the background that take over the container creations. We wondered if it's possible to create a container that has the telemetry activated whilst the default setting disables it.

Can I somehow add a parameter to the New-BcContainer function? That's just a wild guess cause the telemetry gets initialized during the modules import...

If you need further information, just let me now.

Thanks in advance.

**Comment by freddydk** [comment]
The only telemetry sent to Microsoft is usage statistics - i.e. which functions, artifacts, host os version etc. is used.
We use this to prioritize and optimize what we need to support etc.
It doesn't make sense to submit usage statistics for individual containers.

You can store the default value of $bccontainerhelperconfig.microsofttelemetryconnectionString and then set it to "" in code.
Then before the call to New-BcContainer, you can set it to the right value - and set it back afterwards.

**Comment by Silentapproach** [comment]
Ok, thanks. 
- Closing this issue.
