### ISSUE TITLE
Developing in Remote Container

### ISSUE THREAD

**Issue by RogerNelson66** [microsoft/navcontainerhelper#2241]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
is Developing in a Remote Container like discribed be the article:
https://code.visualstudio.com/docs/remote/containers
with navcontainerhelper possible?

**Scripts used to create container and cause the issue**
```
$containerName = 'bc180'
$password = 'xxx'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '18.0' -country 'at' -select 'Latest'
$licenseFile = 'c:\temp\DemDevBC18.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -includeAL `
    -vsixFile (Get-LatestAlLanguageExtensionUrl) `
    -updateHosts `
    -additionalParameters @("--volume C:\temp\AddIns4Docker\BC180:C:\run\add-ins")

**Full output of scripts**
```
BcContainerHelper is version 2.0.22
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 21H2
Docker Client Version is 20.10.11
Docker Server Version is 20.10.11
Removing C:\ProgramData\BcContainerHelper\Extensions\bc180
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container bc180
Style: onprem
Multitenant: No
Version: 18.0.23013.23795
Platform: 18.0.22893.23773
Generic Tag: 1.0.1.9
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19044.1415 (21H2)
WARNING: Host OS is 21H1 and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
Using locale de-AT
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\bc180\Microsoft.VisualStudio.Services.VSIXPackage.vsix
Using license file c:\temp\DemDevBC18.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\bc180\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc180 from image mcr.microsoft.com/businesscentral:10.0.19041.1415
ac935e58a8c2d3f370bd733eca2ffccaa5b750e84078d050b11c15b816e84f6a
Waiting for container bc180 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/18.0.23013.23795/at
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\18.0.23013.23795\platform\ServiceTier\Program Files
c:\dl\onprem\18.0.23013.23795\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\18.0.23013.23795\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\18.0.23013.23795\platform\WindowsPowerShellScripts\WebSearch
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Determining Database Collation from c:\dl\onprem\18.0.23013.23795\at\database\Demo Database NAV (18-0).bak
Changing Database Server Collation to Latin1_General_100_CI_AS
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Copying Web Client Files
c:\dl\onprem\18.0.23013.23795\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.0.23013.23795\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\18.0.23013.23795\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\18.0.23013.23795\platform
c:\dl\onprem\18.0.23013.23795\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\18.0.23013.23795\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\18.0.23013.23795\platform\Test Assemblies
Copying Applications
C:\dl\onprem\18.0.23013.23795\at\Applications
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 174 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.168.205 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.168.205 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.22.144.1 in container hosts file
Starting Container
Hostname is bc180
PublicDnsName is bc180
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 520DB4F8332D13EA4607A408BEAF616621BCEDB7
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.22.150.146
Container Hostname  : bc180
Container Dns Name  : bc180
Web Client          : http://bc180/BC/
Dev. Server         : http://bc180
Dev. ServerInstance : BC
Setting bc180 to 172.22.150.146 in host hosts file

Files:
http://bc180:8080/Microsoft.VisualStudio.Services.VSIXPackage.vsix

Container Total Physical Memory is 15.7Gb
Container Free Physical Memory is 2.6Gb

Initialization took 64 seconds
Ready for connections!
Reading CustomSettings.config from bc180
Creating Desktop Shortcuts for bc180
Extracting C:\Applications\BaseApp\Source\Base Application.Source.zip
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Windows\Microsoft.NET\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\180\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\180\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container bc180 successfully created

Use:
Get-BcContainerEventLog -containerName bc180 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName bc180 to get debug information about the container
Enter-BcContainer -containerName bc180 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName bc180 to remove the container again
docker logs bc180 to retrieve information about URL's again
...
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
if i try to attach to the container i'll get:

[69 ms] Remote-Containers 0.209.6 in VS Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3).
[69 ms] Start: Resolving Remote
[71 ms] Setting up container: /bc180
[88 ms] Start: Run: docker inspect --type container /bc180
[1087 ms] Start: Check Docker is running
[1088 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[1891 ms] Server API version: 1.41
[1892 ms] Start: Inspecting container
[1892 ms] Start: Run: docker inspect --type container ac935e58a8c2d3f370bd733eca2ffccaa5b750e84078d050b11c15b816e84f6a
[2878 ms] Start: Run in container: /bin/sh
[3008 ms] Start: Run in container: uname -m
[3956 ms] Start: Run in container: cat /etc/passwd
[3956 ms] Stdin closed!
[3962 ms] Shell server terminated (code: 126, signal: null)
container ac935e58a8c2d3f370bd733eca2ffccaa5b750e84078d050b11c15b816e84f6a encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: Der Benutzername oder das Kennwort ist falsch. (0x52e)

**Comment by freddydk** [comment]
Remove containers does not have support for Windows Containers yet:

(from the site)
Containers:
- x86_64 / ARMv7l (AArch32) / ARMv8l (AArch64) Debian 9+, Ubuntu 16.04+, CentOS / RHEL 7+
- x86_64 Alpine Linux 3.9+

and we cannot run BC etc. on Linux

**Comment by Kowa63** [comment]
> and we cannot run BC etc. on Linux
Since BC 20 will be the first version to run upon cross-platform .NET Standard rather than the .NET Framework in Windows, will that still apply for the versions to come?  Or can we expect a BcContainerHelper on cross-platform PowerShell 7 (or higher when available) targeting Linux servers as soon as the technology permits it?

**Comment by freddydk** [comment]
I think that is all a matter of prioritization.
Right now .NET Standard is the goal, whether we want to invest in a fully platform agnostic service tier depends on the price and the ROI - if it was cheap, we would probably do it now - my assumption is that the price tag is fairly high.
Having said that, running all our service tiers on Linux (on Saas) would decrease the necessary CPU power / cost - Linux cores are cheaper than Windows Cores.
We will have to wait and see.
