### ISSUE TITLE
Ability to skip running of the tests for the dependent apps during Run-AlPipeline

### ISSUE THREAD

**Issue by ivandjordjevic** [microsoft/navcontainerhelper#2257]
Hello,

Is there a way for us to make Run-AlPipeline run test app only for the apps that we are building and not run all dependent test apps as well?

For example, we are passing some of the tests apps as the value for **installTestApps** parameter since main test app in **testFolder** has dependency on it, but we will like to skip running all the dependent and 3rd party tests as part of the Run-AlPipeline since it takes more time.

These are the parameters for test apps I'm referring to:
**.Parameter testFolders** [test app we need to build and run all the tests from this app]
  _Array or comma separated list of folders with test apps to be compiled, published and run_

 **.Parameter installTestApps** [tests we need to build our test app but we don't want to run them]
  _Array or comma separated list of 3rd party test apps to install before compiling test apps._

**Comment by freddydk** [comment]
Not out of the box with a parameter, but...

what you can do is to override the ImportTestToolkitToBcContainer function, like:

```
$importTestToolkitScriptblock = {
    Param([Hashtable]$parameters)

    Import-TestToolkitToBcContainer @parameters

    # Install your test app dependencies
}

Run-AlPipeline -x -y -x -ImportTestToolkitToBcContainer $importTestToolkitScriptBlock
```

Then these apps won't be considered as test apps.
