### ISSUE TITLE
Cannot download ISV extensions symbols where showmycode is false when running Run-ALPipeline

### ISSUE THREAD

**Issue by jeesus450** [microsoft/navcontainerhelper#2258]
This is just a question related to onprem Version 17 solution:

We have the situation, that our app is depending on an ISV app what is a runtime app and has showmycode=false. This is the one we can publish and install with our license. 

We have the symbols and the source code separately. We cannot publish the development version of the ISV app with our license.

I did not find a way for Run-ALPipeline to use our symbols folder instead of downloading the symbols from container. Downloading from container fails, because the runtime app is published with showmycode=false.

Can I override the downloading of symbols and provide them from our own folder instead in some easy way?

**Comment by freddydk** [comment]
I assume that you could override CompileAppInBcContainer with this (and copy symbols where the comment is)

```
{
    Param([Hashtable]$parameters)

    # copy symbols

    Compile-AppInBcContainer @parameters
}
```

**Comment by freddydk** [comment]
Did you try this?
Did you manage to solve the issue?

**Comment by jeesus450** [comment]
yes. Works perfectly. Thanks.

You can close the issue.
