### ISSUE TITLE
The property 'country' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by mahadjie** [microsoft/navcontainerhelper#2260]
**Describe the issue**
Unable to create Business Central Container on Docker. The feedback is "The property 'country' cannot be found on this object. Verify that the property exists."

**Input Script**
New-BCContainer -accept_eula -assignPremiumPlan -auth UserPassword  -containerName BCContainerTest -imageName mcr.microsoft.com/businesscentral:10.0.19042.1415 -includeAL -installCertificateOnHost -memoryLimit 4G -shortcuts Desktop -updateHosts -useSSL

**Full output of scripts**
PS C:\WINDOWS\system32> New-BcContainer -accept_eula -alwaysPull -assignPremiumPlan -auth UserPassword -containerName BCContainerTest -dns 8.8.8.8 -doNotExportObjectsToText -imageName mcr.microsoft.com/businesscentral:10.0.19042.1415 -includeAL -installCertificateOnHost -memoryLimit 4G -shortcuts Desktop -updateHosts -useSSL
BcContainerHelper is version 3.0.0
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 20H2
Docker Client Version is 20.10.11
Docker Server Version is 20.10.11
Removing C:\ProgramData\BcContainerHelper\Extensions\BCContainerTest
Fetching all docker images
Fetching all docker volumes
WARNING: You are running specific Docker images from mcr.microsoft.com. These images will no longer be updated and will be removed on January 2nd 2021, 
you should switch to user Docker artifacts. See https://freddysblog.com/2020/07/05/july-updates-are-out-they-are-the-last-on-premises-docker-images/
Pulling image mcr.microsoft.com/businesscentral:10.0.19042.1415-ltsc2019
Pulling image mcr.microsoft.com/businesscentral:10.0.19042.1415
10.0.19042.1415: Pulling from businesscentral
Digest: sha256:4c52e158aec7868306220db04f4fdc3ec2d83780e07a1a26ddb8867ca6649a2d
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19042.1415
mcr.microsoft.com/businesscentral:10.0.19042.1415
Using image mcr.microsoft.com/businesscentral:10.0.19042.1415
New-BcContainer Telemetry Correlation Id: 4a83759b-05a5-4a1b-882a-64063a5d3ab0
The property 'country' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.0\ContainerHandling\New-NavContainer.ps1:957 char:9
+         $devCountry = $inspect.Config.Labels.country
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Additional context**
- does it happen all the time? Yes
- did it use to work? No

**Comment by freddydk** [comment]
That script has never worked.
You are specifying a generic image as -imageName - that won't work.
You should remove the -imagename parameter (containerhelper will determine which image to use itself) and then specify which artifacts to use.
If you haven't worked with artifacts before, then we changed the way we use containers from specific images to artifacts back in June 2020. Read more about it here: https://freddysblog.com/2020/06/25/working-with-artifacts/
