### ISSUE TITLE
Usage of NewBCContainer Parameter on Run-AlPipeline

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#2269]
Hi, 

I would like to change a bit the way the Run-ALPipeline is triggering the container creation. thereby I use the parameter(overwrite) -NewBcContainer. And this works, so far so good, but not completely. I looks like that "additional Parameters" e.g "customNavSettings" of the New-BcContainer scriptblock that I provide are lost/overwritten.

I can see that Run-AlPipeline applies the New-Container Overwrite ( visible in the script output) but also that it sets  additionalParameters on it's own:
--volume xxx:X:\sourse
--env customNavSettings=EnalbeTaskScheduler=False

So I think with line 789 in Run-AlPipeline.ps1 my additional Parameters that I handed into the script block are lost. 

It would be nice if the script could take that option into account and just adds additional settings to the given ones.

NavContainerHelper is version 0.3.0.1dev
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8

**Additional context**
- does it happen all the time?
  - yes
- did it use to work?
  - no

**Comment by freddydk** [comment]
In your override you should use something like:

```
$parameters.additionalParameters += $myadditionalparameters
new-bccontainer @parameters
```
instead of 
```
new-bccontainer @parameters -additionalparameters $myadditionalparameters
```
that should work.

**Comment by KristofKlein** [comment]
What evil Powershell magic is this?! It does work indeed! 

Guess I need to learn more about invoking scriptblocks...

**Comment by freddydk** [comment]
parameters is a hashtable and you can specify the parameters to anything using a hashtable and then @hashtable

try:
```
$parameters = @{
    "ForegroundColor" = "Yellow"
    "Object" = "This is a test"
}
Write-Host @parameters
```

**Comment by KristofKlein** [comment]
I was not aware of that with hashtables ... always something new to learn with powershell :D 

So to recap (before closing this) 

-NewBCContainer expects a Scriptblock that has a parameter of type Hash defined. That gets filled from Run-AlPipeline when it invokes the overwrite. By that it leads to the stuff you said up there, that you have to add additionalParameters within the script block and use += (like this it adds it to the parameters that Run-Alpipeline might have set already) 

A bit confusing ( in my case at least ) was the fact that the "additionalParameters" are defined outside/before Run-Alpipeline. But I guess due to Powershell using a global scope for that, it is even when invokating the scriptblock able to reach them and add them while executing.

fascinating :D

**Comment by freddydk** [comment]
Yes, the default implementation of newbccontainer scriptblock is something like:

```
{
    Param([Hashtable] $parameters)
    New-BcContainer @parameters
}
```

meaning that all parameters are set in that and you can modify those.

**Comment by KristofKlein** [comment]
Roger that! Thanks for the help!
