### ISSUE TITLE
Having issue when creating NAVContainer 

### ISSUE THREAD

**Issue by Gokulnath024** [Microsoft/navcontainerhelper#227]
DockerDo : docker.exe: Error response from daemon: container 
b26e4accdea2623fb8dd237aaff1f6a7b0bb289a9717c0da543c7ca3c00c91e6 encountered an error during 
CreateContainer: failure in a Windows system call: The locale specific resource for the desired 
message is not present. (0x3ab9) extra info: {"SystemType":"Container","Name":"b26e4accdea2623fb8dd23
7aaff1f6a7b0bb289a9717c0da543c7ca3c00c91e6","Owner":"docker","IgnoreFlushesDuringBoot":true,"LayerFol
derPath":"C:\\ProgramData\\Docker\\windowsfilter\\b26e4accdea2623fb8dd237aaff1f6a7b0bb289a9717c0da543
c7ca3c00c91e6","Layers":[{"ID":"d6a3c4f2-5af1-5c01-98ab-0ac8f885bcc5","Path":"C:\\ProgramData\\Docker
\\windowsfilter\\4bbf93effd422c58d90bc7c21293555db88a2dfde2c3b160911d628bef120ce2"},{"ID":"d1fd2412-d
953-52f1-a1d2-4d73460bc5a0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b6edac823f5c4912a785995e7
de2e6a39f3dc2db673c989dd23779806a45c222"},{"ID":"3c55dd7a-83f0-5731-977b-925af00b5d1d","Path":"C:\\Pr
ogramData\\Docker\\windowsfilter\\b794174c99e2f2546338694445b258cf78ae60a084f94c8a03267151962fa207"},
{"ID":"f2584625-2f8c-5e28-81f7-bb63f360f355","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8fe86789
92a84c952c1993b816cec04e3b740c2ecb8d49152ed856bceb7632f9"},{"ID":"f258dd8f-822c-5e9e-8c81-99f53e9af45
0","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ccc69f8cb0ef0ae81be1397bf0aef5a90090a22910e3348a97
5b141d6f48469b"},{"ID":"3d3a3ab5-f902-5bc4-b814-cd009321e758","Path":"C:\\ProgramData\\Docker\\window
sfilter\\8f1969f99c8e7004fe5d4cd7fe949f4a62d4ee0cc9e69a8983a48153695f3423"},{"ID":"d0ba0c03-256a-573a
-99b1-b88f9d70d676","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cb9f3dedead1d63676d8433d4417d207f
bd41db28feced3358203919fef6f4d7"},{"ID":"eba3298f-0551-57aa-a033-1dcef8276c4c","Path":"C:\\ProgramDat
a\\Docker\\windowsfilter\\2c30131eb8c87e894bc1df574b94d800fc6ba6b605970912aa4e3a2485cd6b7e"},{"ID":"d
df7b39d-ac5a-58f2-88ea-80187d56647f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\bf759e84d42dcdc7
725d1e752586fbe6e37e351dfec9ac284e36fa8e03230a7a"},{"ID":"67dd013d-8890-5f5f-9208-afc5873e8673","Path
":"C:\\ProgramData\\Docker\\windowsfilter\\0f1a346a03bdcd8376a9b8018463ea79c8c892617960ecb744cf69b481
73ec89"},{"ID":"98b65ae2-1cfb-5ad2-a38d-9f87277268d7","Path":"C:\\ProgramData\\Docker\\windowsfilter\
\a361f681473ec3017e0a19feabeb3344a3d0d8602008c3532c97c841d342a703"},{"ID":"41a39709-ac6f-5018-93ea-e1
bb02c4a7b8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8fee6207a9c6e274ce477649b72fa87a634ffe415
1326eaf3e1aea83e6f58f4d"},{"ID":"4e188e1c-ba82-57c7-9558-85e349428f06","Path":"C:\\ProgramData\\Docke
r\\windowsfilter\\57b5aee2da172acc5864c625baa8d312e511c2d4d3041f1a579e066286cad75b"},{"ID":"fb1e0a3b-
5cb4-56a6-97d3-ca15404ac106","Path":"C:\\ProgramData\\Docker\\windowsfilter\\94e60c5fc20a7d2cb470284f
2d5644996b386677b8930e88bfc50d37873f9a8c"},{"ID":"5cb25fc6-7fb7-592d-a970-3c771937d0db","Path":"C:\\P
rogramData\\Docker\\windowsfilter\\6cd7ab02e3e3bd7aaa4e39f85230b8b4dd4a8800a27c6e569ef849b0d8faec10"}
,{"ID":"c7737436-62c1-5e55-853a-cb066846e79a","Path":"C:\\ProgramData\\Docker\\windowsfilter\\0d2b4ac
e3389f4f53ed43898c296f0a29ac596ed0fb544af167b211762c10bbc"},{"ID":"b03e9b80-854f-5524-8d68-b10dd5047f
ee","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ce7cd5cec3fad1dc84005109a4f5d12f2b477c077938e7ab9
9c832d0b4292e1c"},{"ID":"46b3e479-fde4-58ff-86ad-d6cfd5c8dd80","Path":"C:\\ProgramData\\Docker\\windo
wsfilter\\580bdd1c542b89b32ba3d428153d7af08e69e488653fed224f161e0438e2359a"},{"ID":"77393070-2c05-518
1-aa5d-f87ca9797da7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7fd3a2ed61a48427280fcbce68c03914
b894dcbeda68749e65c63873dee5e491"},{"ID":"34007ac5-ac01-51e3-82b4-5204ee2b11dd","Path":"C:\\ProgramDa
ta\\Docker\\windowsfilter\\2902de47202eb53c8052700e0f19929d5d292b03ce7f4af2eb8a8194d5b91c18"},{"ID":"
f7e5de56-e6b1-51c8-8586-5c95749508ef","Path":"C:\\ProgramData\\Docker\\windowsfilter\\1beb8c8f4aacbc3
cdb785d3c342ee758f31d568bc4fa10f2a78238f9e75b1f34"},{"ID":"6b1afb9e-a459-56da-848a-fc3cec089f2a","Pat
h":"C:\\ProgramData\\Docker\\windowsfilter\\9a945a1a98e0fa80f092ea05c269c5086cb146b95aa27c0d7401e932c
ddbfdc2"}],"MemoryMaximumInMB":4096,"HostName":"MSD365SandboxGB","MappedDirectories":[{"HostPath":"c:
\\programdata\\navcontainerhelper\\extensions\\msd365sandboxgb\\program files","ContainerPath":"c:\\n
avpfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath
":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthM
aximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper
\\extensions\\msd365sandboxgb\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":
0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper","Conta
inerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0
,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["d6429fbf-af1e-4f9a-9235-c31c047dfec8
"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\1beb8c8f4aacbc3cdb785d3c342ee758
f31d568bc4fa10f2a78238f9e75b1f34\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}.
ExitCode: 125
Commandline: docker run --name MSD365SandboxGB --hostname MSD365SandboxGB --env auth=NavUserPassword 
--env username="admin" --env ExitOnError=N --env locale=en-GB --env 
licenseFile="c:\run\my\license.flf" --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\MSD365SandboxGB\my:C:\Run\my" --restart unless-stopped 
--memory 4G --isolation hyperv --env enableApiServices=Y --env enableSymbolLoading=Y --env useSSL=N 
--volume "C:\ProgramData\NavContainerHelper\Extensions\MSD365SandboxGB\Program Files:C:\navpfiles" 
--volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b1
6050a5345MgB8AGgAZgBlAFEAYQBuADIAcwA2ADAAcwBnAHUASABvAHEAdAAyAEYAbABDAEEAPQA9AHwANQA2AGMAOQA0ADgAZABh
AGEANwA2AGIANwA4ADAANABlAGIAOABlADYAOQAzADgAYQA1ADIANABhAGQAYgBjADMAYgBlAGUANgA5ADAANwA4AGEANgAwADUAZ
AA2ADMAYgBiAGMAZQA1ADUAZgBlADkAZQA1ADQAZQA4ADgAMwA= --env passwordKeyFile="c:\run\my\aes.key" --env 
removePasswordKeyFile=Y --env accept_eula=Y --detach microsoft/bcsandbox:gb
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.3.1.4\ContainerHandling\New-NavCon
tainer.ps1:530 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
The ExitCode 125 is typically seen with people running Windows 10 build 17134 (1803) with a specific generation of hardware, which doesn't support out ltsc2016 generation of containers.

If this doesn't match your setup, you can try to remove your containers and write: docker system prune - and see if this fixes the issue.

If it does match your setup - you could try to run this container: microsoft/dynamics-nav:2017-cu18-1803 and confirm my suspition (this is at this time the only image on the 1803 technology).

We are looking at building images for 1803 or 1809.

**Comment by freddydk** [comment]
Update your navcontainerhelper to 0.4.0.0 and add this parameter -UseBestContainerOS to the new-navcontainer command.
Our Images haven't been rebuilt yet, but this parameter will extract the necessary files from the image and use them to spin up a 1803 image, which should solve this problem.
Please let me know if this works for you.

**Comment by freddydk** [comment]
Read this https://blogs.msdn.microsoft.com/freddyk/2018/10/24/windows-10-and-docker-images-for-business-central-nav/ - and try to use -useBestContainerOs - that should work until 1809 ships.

**Comment by mnewmedia** [comment]
Same problem even when using UseBestContainerOS.

Command:
`New-NavContainer -accept_eula -imageName microsoft/dynamics-nav:2018-de -containerName navtest -UseBestContainerOS
`

Versions:
- Edition: Windows 10 Pro
- Version: 1803
- Build: 17134.376
- New-NavContainer Version: 0.4.0.2

**Comment by freddydk** [comment]
When you say same problem - you say that you get the exact same error????

**Comment by mnewmedia** [comment]
Using New-NavContainer:
```
DockerDo : ExitCode: 125
Commandline: docker run --label nav=2018 --label version=11.0.24742.0 --label country=de --label cu=cu10 --name navtest --hostname navtest --env auth=Windows --env 
username="pm" --env ExitOnError=N --env locale=de-DE --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume "C:\ProgramData\NavContainerHelper\Extensions\navtest\my:C:\Run\my" --restart 
unless-stopped --memory 4G --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\11.0.24742.0-de-Files:c:\NAVDVD" --env securePassword=76492d1116743f0423413b16050a5
345MgB8AGQARwBvAEoAaQBaAEEATwBxAHQAdgBGAEUAYQB0AEkANAAxAE8AOABDAHcAPQA9AHwAZABmAGUAYgBlAGIAMwAwADQAOQBiADEANwA5ADcANwBlADMANwBkADkANAA1AGEAZAAyADMANwBiADUAOABjAGUANgA0AD
UAOAA1ADQAYgA2ADQAOABiADIANAA2ADEANwA3ADkAMQA0AGUAZQBiAGEAZQBlADUAMAA2ADAANAA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env 
accept_eula=Y --detach microsoft/dynamics-nav:generic-1803
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.4.0.2\ContainerHandling\New-NavContainer.ps1:657 Zeichen:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
```
Then I copied the commandLine generated from New-NavContainer and did run it again:
```
docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container b2b8d0f256e1aea87884138bae01e763908e22acb075c7d95c3a88eb4c2902a0 
encountered an error during CreateContainer: failure in a Windows system call: Die gebietsschemaspezifische Ressource fÃ¼r die gewÃ¼nschte Meldung ist nicht vorhanden. 
(0x3ab9) extra info: {"SystemType":"Container","Name":"b2b8d0f256e1aea87884138bae01e763908e22acb075c7d95c3a88eb4c2902a0","Owner":"docker","IgnoreFlushesDuringBoot":true,
"LayerFolderPath":"C:\\ProgramData\\Docker\\windowsfilter\\b2b8d0f256e1aea87884138bae01e763908e22acb075c7d95c3a88eb4c2902a0","Layers":[{"ID":"326098b0-04cc-55f5-af68-aff
978c3b957","Path":"C:\\ProgramData\\Docker\\windowsfilter\\af6497310201120f461807acd75f95e9f531ee3cfb9ad735f9317eca681ff5c7"},{"ID":"9569e026-6f3d-51c4-a7c5-8b2641f9cea7
","Path":"C:\\ProgramData\\Docker\\windowsfilter\\986ba9fdf1ef96679243628e782258262766dfca6477024b02d9d37314942528"},{"ID":"66472fee-67c5-54cf-b169-ec7ba84acb36","Path":
"C:\\ProgramData\\Docker\\windowsfilter\\9824f350f9e6afb0d49d50f9800de0f6aef189ac798435e045d80da6cfea5edc"},{"ID":"4e2bb1e5-dfcf-5e37-b605-5ae55770b69d","Path":"C:\\Prog
ramData\\Docker\\windowsfilter\\ecd27614a35b75979cbcc4bf20d995415f990bac32f5bcce7b0c888caf87105c"},{"ID":"76d23958-af41-5e9a-81fc-ccdb686e365d","Path":"C:\\ProgramData\\
Docker\\windowsfilter\\00cb40e10514364b7ce6ebd49da4f8e058ed1bc9f2471864d3830e858d7208e9"},{"ID":"542542a6-8c4c-5fd8-ac7f-c7d101c76ee2","Path":"C:\\ProgramData\\Docker\\w
indowsfilter\\24a18e06ebf71d79a07d22ce20861eddeb8a03eee7a122be340df0323dcc7992"},{"ID":"54941044-10e0-55c9-b165-7ccdb4aa072a","Path":"C:\\ProgramData\\Docker\\windowsfil
ter\\1869927670d02921efaa0176a9d2c5b89d452927b14bd6294552ab7bb59a27b0"},{"ID":"7c6c3ec4-bb93-5b9e-ad73-cff1658c1220","Path":"C:\\ProgramData\\Docker\\windowsfilter\\4705
24edb03be9f4c68e1088b51d60e0b23ee7703e62fc94ffd248abc2a963ef"},{"ID":"0944f99d-c80a-582a-9912-302602f5bb83","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f6a4c14901a78
44b38d89395a81a72e143762c6440d62e10b6a985208207f707"},{"ID":"a454b7f8-68b9-5518-aeb0-b0532a6d7598","Path":"C:\\ProgramData\\Docker\\windowsfilter\\39ae14b5009cdd093cac6a
f8e0eaa28332b75a3036d8d64a77b6338e57e29659"},{"ID":"579a8635-5839-5971-9c53-bcfb7ccce0d7","Path":"C:\\ProgramData\\Docker\\windowsfilter\\c4f6108e65bec5221571a67124cb187
a838edd67c7e238b687ecd09a06afe5b4"},{"ID":"e998e0b0-0180-5225-a8cc-1e3f6cacc8c9","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f1f0ad5e37ac14c6385d8201e769e73579f93a04
aa22c625bedb1fab233e1267"},{"ID":"88f7a842-8f22-5aab-9990-dbdd02019547","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8b9a62d41c015be2958b612d710826e613098f80bfd11c256
762702fb7fb9887"},{"ID":"35594b1a-129f-5af1-ba6b-3ab4e34ca389","Path":"C:\\ProgramData\\Docker\\windowsfilter\\b9a41b7c8e2e8857a53f9b86e830e9bf4c478d46c85c70623a89758767
526ace"}],"MemoryMaximumInMB":4096,"HostName":"navtest","MappedDirectories":[{"HostPath":"c:\\programdata\\navcontainerhelper\\11.0.24742.0-de-files","ContainerPath":"c:
\\navdvd","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper","ContainerPath":"c:\\program
data\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\
navtest\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["1d7a1e3c
-8374-43d2-bf82-2933aa4ebaff"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\Docker\\windowsfilter\\8b9a62d41c015be2958b612d710826e613098f80bfd11c256762702fb7fb9887\\Utilit
yVM"},"AllowUnqualifiedDNSQuery":true}.
In Zeile:1 Zeichen:1
+ docker run --label nav=2018 --label version=11.0.24742.0 --label coun ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\Program File...NSQuery":true}.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```
Seems to me like the same error. Isn't it?

**Comment by mnewmedia** [comment]
Same error. So not related to nav. But to Windows & Docker. Also there is currently no solution around when googling.

Connected Issues:
- https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/832
- https://forums.docker.com/t/docker-run-hello-world/56408

**Comment by DecisionSystems** [comment]
I concur with mnewmedia.  Tried troubleshooting.  would not run the basic windows core image.    My HW is high-end but 3 years old. Docker Version 18.06.1-ce-win73 (19507) Windows 10 10.0.17134 Build 17134 i7 CPU @ 2.67 Ghz.  Please fix. Thanks.

**Comment by freddydk** [comment]
I am sorry, but it isn't something I can fix.

**Comment by DecisionSystems** [comment]
Not a problem. It turned out that as soon as I updated windows 10 to the latest build the problem went away. Seems like a compatibility problem with versions of Windows and Docker.

Thanks,














On Nov 17, 2018, at 10:55 PM, Freddy Kristiansen <notifications@github.com<mailto:notifications@github.com>> wrote:


I am sorry, but it isn't something I

**Comment by robertzengcn** [comment]
Hello, thanks for help, now I encounted another problem, it seems the problem has relationship with my password, but I has maked my password very complex, Including case and special characters:

Unable to update the password. The value provided for the new password does not meet the length, complexity, or history requirements of the domain.

at <ScriptBlock>, C:\Run\SetupWindowsUsers.ps1: line 12
at <ScriptBlock>, C:\Run\navstart.ps1: line 170
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container MyBizCentralApp failed
所在位置 C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.3\ContainerHandling\Wait-NavContainerReady.ps1:45 字符: 17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...ntralApp failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container MyBizCentralApp failed

**Comment by freddydk** [comment]
That error comes from Windows - I don't think you tried hard enough.
Try tmDu4C@J^#uaMH4E
(from https://passwordsgenerator.net/)

**Comment by robertzengcn** [comment]
Hello @freddydk  May I change $credential.Password to the password directly?  I don't want my computer password to complex, I mean I change: 
Setup-NavContainerTestUsers  -containerName $containername -password $credential.Password

To:
Setup-NavContainerTestUsers  -containerName $containername -password tmDu4C@J^#uaMH4E

**Comment by freddydk** [comment]
Use NavUserPassword instead of Windows Auth - that is a better way.

**Comment by robertzengcn** [comment]
thanks, but how to use NavUserPassword instead of Windows Auth?

**Comment by freddydk** [comment]
replace -auth Windows with -auth NavUserPassword

There are lot of documentation on my blog on how to use Docker and the navcontainerhelper.
Please go through these things. There you will see how to use PowerShell and what the various commands are.

**Comment by freddydk** [comment]
You can also read a lot here: https://github.com/microsoft/navcontainerhelper/blob/master/NavContainerHelper.md

**Comment by robertzengcn** [comment]
Thank you very much for your helo ^^
