### ISSUE TITLE
Latest Container Password Configuration Not Working?

### ISSUE THREAD

**Issue by mattkeyeswc** [microsoft/navcontainerhelper#2273]
I have tried the script below a few times today, but I can't log into BC after the container completes.  Is there an issue with the latest container?

```
$containerName = 'latest'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'us' -select 'Latest'
$licenseFile = 'e:\BC Licenses\BCv19.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -multitenant:$false `
    -licenseFile $licenseFile `
    -includeAL `
    -updateHosts
```

**Comment by freddydk** [comment]
You should include the output from the container generation and/or which URL you are using to connect, thanks

**Comment by freddydk** [comment]
Your script works fine here:
![image](https://user-images.githubusercontent.com/10775043/150068072-117f715e-d2e7-4657-8253-78d8e657c0fd.png)

**Comment by mattkeyeswc** [comment]
Hi Freddy, my bad - this was a license error.  An odd one as this license seems to work elsewhere, but I can do some troubleshooting now on my end.  My apologies for the red herring!

The license error I found was:
`The new users do not meet the terms of the current license. The current license allows 0 full users and 0 limited users.`

**Comment by freddydk** [comment]
Thanks for letting me know.
Next time around, just always include the output - then stuff like this will be discovered very quickly, without any need for troubleshooting, reproing etc.

**Comment by mattkeyeswc** [comment]
Thanks Freddy, will do.  The error message threw me off as there was nothing regarding the license file I was using until I did some digging
