### ISSUE TITLE
Issue creating ClickOnce Client available in Client Network Zone

### ISSUE THREAD

**Issue by SLGEORG** [Microsoft/navcontainerhelper#228]
I have a NAV Container Deployed with a ClickOnce Client. I have executed the following command:

`$additionalParameters = @("--publish 80:80",
                          "--publish 8080:8080",
                          "--publish 443:443", 
                          "--publish 7046-7049:7046-7049",
                          "--env clickonce=Y")
New-NavContainer -accept_eula -alwaysPull -imageName "navinsider.azurecr.io/dynamics-nav:11.0.21063.0-finde" -accept_outdated -auth NavUserPassword -updateHosts -containerName bctss  -additionalParameters $additionalParameters`

Docker itself runs on a server with the following hostname: S415VM1775. I gave the container the name "bctss". The ClickOnce page can be reached from my client (notebook) at the following address: "http://s415vm1775:8080/NAV/". However as soon as I want to install the client via ClickOnce the following error occurs: "The application could not be downloaded...".

Under Details you can see that the deployment URL "http://bctss:8080/NAV/Win/Deployment/Microsoft.Dynamics.Nav.Client.application" is the address of the Docker Container and not the address of the host system. How can I install the ClickOnce client without being on the server?

King regards,
slgeorg

**Comment by freddydk** [comment]
I think you need to specify publicdnsname to the container in an environment variable (additionalparametyer) - this is the url on which you can access the container from the outside.

**Comment by SLGEORG** [comment]
@freddydk Thank you so much! It worked. Is there a way to sign the ClickOnce manifest with your own certificate? As it says in the documentation, did I understand that the certificate will be used for SSL and not to sign the ClickOnce, correct?

**Comment by freddydk** [comment]
Correct, There is no automatic way to sign the click once manifest. You will have to override some of the scripts in order to do that.
Thanks
Freddy

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mheijkant** [comment]
Can you give an example how this works when I have a public address for the RTC client like "SERVER-PD09:7481/nav", or how and were you added this parameter. Is it the -additionalparameter on the New-NavContainer command?

**Comment by SLGEORG** [comment]
> Can you give an example how this works when I have a public address for the RTC client like "SERVER-PD09:7481/nav", or how and were you added this parameter. Is it the -additionalparameter on the New-NavContainer command?

`$additionalParameters = @("--publish 80:80",
                          "--publish 8080:8080",
                          "--publish 443:443", 
                          "--publish 7046-7049:7046-7049",
                          "--publish 1433:1433"
                          "--env clickonce=Y",
                          "--env PublicDnsName=YOURDNSNAME")
New-NavContainer -accept_eula -alwaysPull -imageName "IMAGENAME" -accept_outdated -auth NavUserPassword -updateHosts -containerName CONTAINERNAME-additionalParameters $additionalParameters` 

This should work for you.

**Comment by freddydk** [comment]
Yep - that works. only thing is, that you in your question use port 7481 - you would have to setup the servicetier to use that port and publish that port - you cannot use port mapping on the client services port.

**Comment by freddydk** [comment]
(added a space after CONTAINERNAME in the sample:-))

**Comment by mheijkant** [comment]
Thanks Slava and Freddy for your answer. 
A follow up question to Freddy. 
Can't the client-port be mapped in general, Because I'm not able to connect a RTC client remotely to a container with a mapped client-port.

**Comment by freddydk** [comment]
Yes, the client port can be changed
https://blogs.msdn.microsoft.com/freddyk/2018/09/03/navcontainerhelper-0-3-1-0-and-a-new-docker-generic-build-0-0-6-6/
