### ISSUE TITLE
Adding -assignPremiumPlan to DevOps pipeline giving "If sharedFolder is specified, it must be an existing folder" error.

### ISSUE THREAD

**Issue by KuljitSinghParmar** [microsoft/navcontainerhelper#2284]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I tried to add -assignPremiumPlan to DevOps pipeline but it gives below error - 
"If sharedFolder is specified, it must be an existing folder
At C:\Users\runneradmin\AppData\Local\Temp\8fa470b8-845a-4697-b377-2911cc3cf447\AppHandling\Run-AlPipeline.ps1:347 
char:5
+     throw "If sharedFolder is specified, it must be an existing folde ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (If sharedFolder...existing folder:String) [], RuntimeException
    + FullyQualifiedErrorId : If sharedFolder is specified, it must be an existing folder"

**Scripts used to create container and cause the issue**
Using these scripts - https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=/scripts 

I added the "assignPremiumPlan" : true in settings.json then added it to Read-Setting.ps and lastly to DevOps-pipeline.ps 
when I remove this parameter , pipeline works fine.   
![image](https://user-images.githubusercontent.com/61985025/151069767-27d1bea2-5943-4620-9454-fc242e9bd39f.png)
![image](https://user-images.githubusercontent.com/61985025/151069803-48b8ea93-21c1-4432-b104-b6e8597af250.png)
![image](https://user-images.githubusercontent.com/61985025/151070009-5e41eaa8-352c-4e21-8534-e525b44de898.png)

Below is full pipeline run - 
Set artifact = ///us/Current
Set pipelineName = MyApp-ci
Set containerName = myapp-ci
Set installApps = 'InstallApp\Binary Stream Software Inc._Binary Stream Inc License Management_1.1.24.0.app'
Set installTestApps = ''
Set previousApps = 'https://businesscentralapps.blob.core.windows.net/githubhelloworld/latest/apps.zip'
Set appSourceCopMandatoryAffixes = ''
Set appSourceCopSupportedCountries = ''
Set appFolders = 'app\MEM,app\Test'
Set testFolders = 'test'
Set memoryLimit = '6G'
Set additionalCountries = ''
Set genericImageName = ''
Set vaultNameForLocal = 'BuildVariables'
Set bcContainerHelperVersion = 'dev'
Set installTestRunner = True
Set installTestFramework = True
Set installTestLibraries = True
Set installPerformanceToolkit = False
Set enableCodeCop = False
Set enableAppSourceCop = False
Set enablePerTenantExtensionCop = False
Set enableUICop = True
Set doNotSignApps = True
Set doNotRunTests = False
Set cacheImage = True
Set CreateRuntimePackages = True
Set assignPremiumPlan = True
Downloading https://github.com/microsoft/navcontainerhelper/archive/dev.zip
BcContainerHelper version 3.0.2-dev
BcContainerHelper emits usage statistics telemetry to Microsoft
Run-AlPipeline Telemetry Correlation Id: 8451b36a-6094-443b-91be-0ecb2d4f5b1e
If sharedFolder is specified, it must be an existing folder
At C:\Users\runneradmin\AppData\Local\Temp\8fa470b8-845a-4697-b377-2911cc3cf447\AppHandling\Run-AlPipeline.ps1:347 
char:5
+     throw "If sharedFolder is specified, it must be an existing folde ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (If sharedFolder...existing folder:String) [], RuntimeException
    + FullyQualifiedErrorId : If sharedFolder is specified, it must be an existing folder
 
Error: Process completed with exit code 1.

**Comment by freddydk** [comment]
AssignPremiumPlan is a switch parameter on run-alpipeline.
You need to use 
```
-assignPremiumPlan:$assignPremiumPlan
```
instead of
```
-assignPremiumPlan $assignPremiumPlan
```
else the value of $assignPremiumPlain will be assigned to the next parameter not specified, which is SharedFolder.

**Comment by KuljitSinghParmar** [comment]
thanks Freddy . missed the small detail .
