### ISSUE TITLE
Various, probably container session related errors since 3.0.1 on 3 machines with 2 different docker versions

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/navcontainerhelper#2285]
**EDITED**

Removed second error: ERROR: System.Management.Automation.CmdletInvocationException: "@{Identifier=APP01; Filename=Publisher_App 01_20. 0.3.0_release.app; Id={0101F79C-5A7B-4101-B81E-970448003573}; Name=App 01; Version=20.0.3. 0; Publisher=Publisher; Type=None}" cannot be compared to "10" 

This was indeed selfmade but had no proper callstack so I assumed it was connected to the others.

**Describe the issue**
Hi Freddy,

we have a very strange, hard to describe and irregular problem.
If we use the BcContainerHelper 3.0.1, unfortunately not always reproducible, but every now and then various errors occur, but we can not define them more precisely.
With 3.0.0 we do not have these issues. And these issues occur on 3 Windows Servers with different Docker Enterprise versions (Docker version 20.10.6, Docker version 19.03.14). I can switch from always working to a process wirth errors by simply installing 3.0.0 or 3.0.1 without doing anything else.
No updates or other software has been installed, the only change is BcContainerHelper. The process is exactly the same for both versions.

**Scripts used to create container and cause the issue**
```
- Check for proper existing image -> create image if missing or not current.
			$newBcImageArgs = @{
				"artifactUrl"  = $artifactUrl
				"imageName"    = $dockerImageName
				"isolation"    = $config.Const.Isolation
				"skipDatabase" = $true
			};

			New-BcImage @newBcImageArgs;

- Create container. mcScripts contains database upgrade code if needed.
			New-BcContainer `
				-accept_eula `
				-accept_outdated `
				-assignPremiumPlan `
				-artifactUrl $artifactUrl `
				-imageName $dockerImageName `
				-containerName $config.Job.instanceName `
				-licenseFile $config.Job.LicenseFile `
				-auth 'NavUserPassword' `
				-authenticationEMail $adminUser.AuthenticationEmail `
				-Credential $bcAdminCredential `
				-memoryLimit "5G" `
				-isolation 'hyperv' `
				-shortcuts None `
				-useTraefik `
				-useSSL `
				-multitenant:$false `
				-PublicDnsName $config.Const.DnsName `
				-additionalParameters $config.Job.AdditionalParameters `
				-databaseServer 'dbserver' `
				-databaseInstance 'dbinstance' `
				-databaseName 'db' `
				-databaseCredential $databaseCredential `
				-myScripts $additionalScripts;

- Handle and add users
	$users = Get-BcContainerBcUser -containerName $config.Job.instanceName;

- Publish, install/upgrade, sync apps
	This is running in a scriptblock with Invoke-ScriptInBcContainer
```

**Full output of scripts**
These are the errors we got in the meantime. The first we get the most. It seems that we can avoid the first error when using
"Get-BcContainerSession -silent -reinit" just before Get-BcContainerBcUser.

I can't confirm it, but it seems to me that there is a problem with the serialization or the session in general during the Invoke-Command.
I couldn't find any relevant differences between 3.0.0 and 3.0.1, but maybe you can think of a change that could cause something like this or have a better idea.
```
ERROR: ServerInstance 'MicrosoftDynamicsNavServer$System.Xml.XmlElement' contains at least one invalid character. You cannot use the following characters: '.' at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.1\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Line 44
at Get-BcContainerBcUser, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.1\UserHandling\Get-NavContainerNavUser.ps1: Line 25
at AddContainerUsers<Process>, C:\mx365bc\mx365bc_functions.ps1: Line 3120
at <ScriptBlock>, C:\mx365bc\mx365bc.ps1: Line 266
```
Contained in a long running Invoke-ScriptInBcContainer:
```
The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it is in the Faulted state.
Get-NAVAppInfo causing the issue
at GetAppProperties<Process>, C:\run\MC.PowerShell\MC.Dynamics.Nav\Deployment\Publish-MultipleNavApps.ps1: line 19
at <ScriptBlock>, C:\run\MC.PowerShell\MC.Dynamics.Nav\Deployment\Publish-MultipleNavApps.ps1: line 388
at Publish-MultipleNavApps<Process>, C:\run\MC.PowerShell\MC.Dynamics.Nav\Deployment\Publish-MultipleNavApps.ps1: line 334
at <ScriptBlock>, <No file>: line 5
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.1\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Line 43
at RePublishConfiguredAppsAndAddIns<Process>, C:\mx365bc\mx365bc_functions.ps1: Line 3435
at <ScriptBlock>, C:\mx365bc\mx365bc.ps1: Line 273
```

**Additional context**
I'm sorry if I can't describe the problems any better. Since the processes are very integrated, it is difficult to separate out a repro. I hope that this information is already sufficient.

**Comment by freddydk** [comment]
so, you say that 3.0.1 randomly fails and 3.0.0 does not?

**Comment by MODUSCarstenScholling** [comment]
Right, that was my observation.
I would also have rather guessed the session-related changes in October, but the problem only occurred with the update to 3.0.1.

I have now added the session refresh in more places and the problem no longer seems to occur. But it should also work without it.

The process in which this occurs sometimes has very long steps, new image, new container, user handling, sometimes complete uninstallation and installation of apps. But it seems to be the simple commands where it occurs: Get-BcContainerBcUser, Import-BcContainerLicense...

**Comment by freddydk** [comment]
What do you mean by session refresh?

**Comment by MODUSCarstenScholling** [comment]
Get-BcContainerSession -silent -reinit

**Comment by freddydk** [comment]
Strange that the session thing should occur now - and only with 3.0.1
Will go through the changes to see if anything could be the cause of something like this,

**Comment by MODUSCarstenScholling** [comment]
Thank you. It is really strange.

**Comment by freddydk** [comment]
I will keep an eye out after other occurrences of this, thanks for your info
