### ISSUE TITLE
New-BcContainerBcUser function change request

### ISSUE THREAD

**Issue by vvkjndl** [microsoft/navcontainerhelper#2294]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
New-BcContainerBcUser uses Write-Host cmdlet to display output messages on console. I am running this command in a loop to add over hundreds of users. I am unable to find any way to **suppress the stdout** that is coming from that function.

Can we change the cmdlet from `Write-Host` to `Write-Output` in `New-BcContainerBcUser` function?

**Scripts used to create container and cause the issue**
```
New-BcContainerBcUser -containerName $ContainerName -tenant $tenant -AuthenticationEmail $AuthEmail -Credential $cred -PermissionSetId $role -assignPremiumPlan
```

**Full output of scripts**
```
Creating User abc@xyz.com
Assigning Permission Set SUPER to abc@xyz.com
Assigning Premium plan for ABC@XYZ.COM
```

**Screenshots**
N/A

**Additional context**
- does it happen all the time? Yes
- did it use to work? No

**Comment by freddydk** [comment]
Write-Output will put the values on the output stream, which is basically the same as returning the values from the function.
It would have bad consequences for BcContainerHelper if we did this.
Try to change the Write-Host in this function to Write-Output
```
function add([int]$a, [int]$b) {
    Write-Host "Adding $a and $b"
    return $a+$b
}

$c = add -a 4 -b 5
Write-Host "Result $c"
```
Normally this script would say:
```
Adding 4 and 5
Result 9
```
With Write-Output it says
```
Result Adding 4 and 5 9
```
and $c is an array consisting of a string and an int

I had not read this https://devblogs.microsoft.com/scripting/understanding-streams-redirection-and-write-host-in-powershell/ when I started using Write-Host - if I had - I would have used something else.

In the future, I might do a complete overhaul to get rid of Write-Host - but for now, we need to live with the mistake I did:-(

**Comment by freddydk** [comment]
If it is important to avoid the output, you could just use Invoke-ScriptInBcContainer and use the NAV cmdlets inside.

**Comment by vvkjndl** [comment]
> Write-Output will put the values on the output stream, which is basically the same as returning the values from the function. It would have bad consequences for BcContainerHelper if we did this. Try to change the Write-Host in this function to Write-Output
> 
> ```
> function add([int]$a, [int]$b) {
>     Write-Host "Adding $a and $b"
>     return $a+$b
> }
> 
> $c = add -a 4 -b 5
> Write-Host "Result $c"
> ```
> 
> Normally this script would say:
> 
> ```
> Adding 4 and 5
> Result 9
> ```
> 
> With Write-Output it says
> 
> ```
> Result Adding 4 and 5 9
> ```
> 
> and $c is an array consisting of a string and an int
> 
> I had not read this https://devblogs.microsoft.com/scripting/understanding-streams-redirection-and-write-host-in-powershell/ when I started using Write-Host - if I had - I would have used something else.
> 
> In the future, I might do a complete overhaul to get rid of Write-Host - but for now, we need to live with the mistake I did:-(

Makes sense and will use Invoke-ScriptInBcContainer.
