### ISSUE TITLE
Cannot pull docker image microsoft/bcsandbox

### ISSUE THREAD

**Issue by pearljo** [Microsoft/navcontainerhelper#230]
Dear all,

I create VM using Windows Server 2016 Standard and trying to get BC docker image.
When I run “docker pull microsoft/bcsandbox” in powershell, I got error like below.
 
_**"docker : read tcp xxx.xxx.x.xxx:50000->204.79.197.219:443:wsarecv: An existing connection was forcibly closed by the remote host."**_

The process to pull docker image is failed. I have tried several times and my colleague has also tried several times, but the error is still persist.
Please advise. Thanks in advance.

Best regards,
Johanna

**Comment by freddydk** [comment]
Sounds like you have an antivirus or a firewall preventing you from pulling the images - I have never heard about that before.

**Comment by freddydk** [comment]
Googling this issue, there are a number of people experiencing similar behavior with docker toolbox or wrongly installed docker (like https://github.com/docker/kitematic/issues/3555).
How did you install docker?

**Comment by pearljo** [comment]
> Sounds like you have an antivirus or a firewall preventing you from pulling the images - I have never heard about that before.

No firewall or antivirus in the vm.

**Comment by pearljo** [comment]
> Googling this issue, there are a number of people experiencing similar behavior with docker toolbox or wrongly installed docker (like [docker/kitematic#3555](https://github.com/docker/kitematic/issues/3555)).
> How did you install docker?

Below is my steps.
1. Create HyperV and Install WIndows 2016 Standard with Desktop Experience
2. Enable (all) .NET features available
3. Enable Container feature
4.Run  Windows update 
5. Install Docker
	https://docs.docker.com/install/windows/docker-ee/#install-docker-ee
	
	Command:
	Install-Module DockerMsftProvider -Force
	Install-Package Docker -ProviderName DockerMsftProvider -Force
6. Install Nav Container Helper
	install-module navcontainerhelper -force
7. Download Image and Create Container

	$ContainerName = "BCW"
	$ImageName = "microsoft/bcsandbox"
	$LicenseFile = ""
	$UserName = ""
	$Password = ConvertTo-SecureString "" -AsPlainText -Force
	$Credential = New-Object System.Management.Automation.PSCredential ($UserName, $Password)

	New-NavContainer `
		-licenseFile $LicenseFile `
		-accept_eula `
		-accept_outdated `
		-containerName "BCW1" `
		-ImageName $ImageName `
		-auth NavUserPassword `
		-Credential $Credential `
		-includeCSide `
		-verbose
	
Is there any step that I missed? Please help. Thank you.

**Comment by rvveldhuyzen** [comment]
I experienced a similair error on my Hyper-V (win10) and it seemed network related. First I used an Internal Switch(Internal Network) and got the error. I created an External Switch(External network) and the pull was succesfull. 

Maybe this helps?

**Comment by NAVspecialist** [comment]
Is it only 365BC that you cannot pull?
Can you ping google.com ?

What I did to get mine to work was:

Set-DnsClientServerAddress -InterfaceIndex 2 -ServerAddresses 8.8.8.8, 8.8.4.4 
# to use Google as DNS - so I dont get the network warning on every single new network)

# To make sure that ip-adresses can be seen from outside the Hyper-V image 
# Right click in Hyper-V, Settings on Network, Advanced, Enable Mac-address spoofing.

Stop-Service Docker
Get-ContainerNetwork -Name nat | Remove-ContainerNetwork -Force
# REM '{"bridge":"none"}' | Set-Content C:\ProgramData\docker\config\daemon.json #If this one does not work then try the one below:
# REM {"hosts": ["tcp://0.0.0.0:2375","npipe://"]}  | Set-Content C:\ProgramData\docker\config\daemon.json
Start-Service Docker

# If CSide complains about missing DLL's or giving an ODBC error, you probably need to install these pre-requisites:
https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
https://download.microsoft.com/download/3/A/6/3A632674-A016-4E31-A675-94BE390EA739/ENU/x64/sqlncli.msi

**Comment by pearljo** [comment]
> I experienced a similair error on my Hyper-V (win10) and it seemed network related. First I used an Internal Switch(Internal Network) and got the error. I created an External Switch(External network) and the pull was succesfull. Got a feeling that a firewall or something like that was blocking traffic?
> 
> Maybe this helps?

Thanks for your response, rvveldhuyzen. I have connected to External network.

**Comment by pearljo** [comment]
> Is it only 365BC that you cannot pull?
> Can you ping google.com ?
> 
> What I did to get mine to work was:
> 
> Set-DnsClientServerAddress -InterfaceIndex 2 -ServerAddresses 8.8.8.8, 8.8.4.4
> To use Google as DNS - so I dont get the network warning on every single new network)
> 
> To make sure that ip-adresses can be seen from outside the Hyper-V image
> Right click in Hyper-V, Settings on Network, Advanced, Enable Mac-address spoofing.
> 
> Stop-Service Docker
> Get-ContainerNetwork -Name nat | Remove-ContainerNetwork -Force
> '{"bridge":"none"}' | Set-Content C:\ProgramData\docker\config\daemon.json #If this one does not work then try the one below:
> {"hosts": ["tcp://0.0.0.0:2375","npipe://"]} | Set-Content C:\ProgramData\docker\config\daemon.json
> Start-Service Docker
> 
> If CSide complains about missing DLL's or giving an ODBC error, you probably need to install these pre-requisites:
> https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
> https://download.microsoft.com/download/3/A/6/3A632674-A016-4E31-A675-94BE390EA739/ENU/x64/sqlncli.msi
> 
> Sorry about the font size issue I don't know why it does this... (Fixed it was the # sign)

Thank you for your response and suggestion, NAVspecialist :)
I tried your suggestion and no error ""docker : read tcp xxx.xxx.x.xxx:50000->204.79.197.219:443:wsarecv: An existing connection was forcibly closed by the remote host."". 
But, now I got error "DockerDo -command pull -imageName $imageName | Out-Null".
Do you have any idea to solve this error?
![image](https://user-images.githubusercontent.com/30619629/48187100-b1936480-e36c-11e8-9b41-6351126b0664.png)

**Comment by freddydk** [comment]
Could you try to execute the following command:

docker run -it microsoft/windowsservercore cmd

That should create a simple Windows Server core container and place you in a prompt.
Let me know the result?

Thanks

**Comment by pearljo** [comment]
I try to pull the image (docker pull microsoft/bcsandbox) but got the error like before.
![image](https://user-images.githubusercontent.com/30619629/48188512-81e65b80-e370-11e8-91c8-f305194b6a6d.png)
Any suggestion?

**Comment by freddydk** [comment]
Please try to pull and run windowsservercore as suggested 20 minutes ago.

**Comment by freddydk** [comment]
Is the VM Azure hosted or hosted locally on a server?

**Comment by pearljo** [comment]
> docker run -it microsoft/windowsservercore cmd

Thank you for your response, Freddy.
I tried your command and the result is like below.

> 
PS C:\Users\Administrator> docker run -it microsoft/windowsservercore cmd
docker : Unable to find image 'microsoft/windowsservercore:latest' locally
At line:1 char:1
+ docker run -it microsoft/windowsservercore cmd
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to find ...latest' locally:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
latest: 
Pulling from microsoft/windowsservercore
3889bb8d808b: 
Pulling fs layer
c0f6863f3dd4: Pulling fs layer
3889bb8d808b: 
Retrying in 5 seconds
c0f6863f3dd4: Retrying in 5 seconds
c0f6863f3dd4: 
Retrying in 4 seconds
3889bb8d808b: Retrying in 4 seconds
3889bb8d808b: 
Retrying in 3 seconds
c0f6863f3dd4: Retrying in 3 seconds
c0f6863f3dd4: 
Retrying in 2 seconds
3889bb8d808b: Retrying in 2 seconds
c0f6863f3dd4: 
Retrying in 1 second
3889bb8d808b: Retrying in 1 second
c0f6863f3dd4: 
Retrying in 10 seconds
3889bb8d808b: 
Retrying in 10 seconds
3889bb8d808b: 
Retrying in 9 seconds
c0f6863f3dd4: Retrying in 9 seconds
c0f6863f3dd4: 
Retrying in 8 seconds
3889bb8d808b: Retrying in 8 seconds
3889bb8d808b: 
Retrying in 7 seconds
c0f6863f3dd4: Retrying in 7 seconds
c0f6863f3dd4: 
Retrying in 6 seconds
3889bb8d808b: Retrying in 6 seconds
3889bb8d808b: 
Retrying in 5 seconds
c0f6863f3dd4: Retrying in 5 seconds
c0f6863f3dd4: 
Retrying in 4 seconds
3889bb8d808b: 
Retrying in 4 seconds
3889bb8d808b: 
Retrying in 3 seconds
c0f6863f3dd4: Retrying in 3 seconds
c0f6863f3dd4: 
Retrying in 2 seconds
3889bb8d808b: Retrying in 2 seconds
3889bb8d808b: 
Retrying in 1 second
c0f6863f3dd4: Retrying in 1 second
c0f6863f3dd4: 
Retrying in 15 seconds
3889bb8d808b: 
Retrying in 15 seconds
c0f6863f3dd4: 
Retrying in 14 seconds
3889bb8d808b: 
Retrying in 14 seconds
c0f6863f3dd4: 
Retrying in 13 seconds
3889bb8d808b: 
Retrying in 13 seconds
c0f6863f3dd4: 
Retrying in 12 seconds
3889bb8d808b: Retrying in 12 seconds
3889bb8d808b: 
Retrying in 11 seconds
c0f6863f3dd4: Retrying in 11 seconds
c0f6863f3dd4: 
Retrying in 10 seconds
3889bb8d808b: 
Retrying in 10 seconds
c0f6863f3dd4: 
Retrying in 9 seconds
3889bb8d808b: 
Retrying in 9 seconds
3889bb8d808b: 
Retrying in 8 seconds
c0f6863f3dd4: Retrying in 8 seconds
c0f6863f3dd4: 
Retrying in 7 seconds
3889bb8d808b: 
Retrying in 7 seconds
c0f6863f3dd4: 
Retrying in 6 seconds
3889bb8d808b: Retrying in 6 seconds
c0f6863f3dd4: 
Retrying in 5 seconds
3889bb8d808b: 
Retrying in 5 seconds
3889bb8d808b: 
Retrying in 4 seconds
c0f6863f3dd4: Retrying in 4 seconds
c0f6863f3dd4: 
Retrying in 3 seconds
3889bb8d808b: 
Retrying in 3 seconds
c0f6863f3dd4: 
Retrying in 2 seconds
3889bb8d808b: 
Retrying in 2 seconds
3889bb8d808b: 
Retrying in 1 second
c0f6863f3dd4: Retrying in 1 second
c0f6863f3dd4: 
Retrying in 20 seconds
3889bb8d808b: Retrying in 20 seconds
3889bb8d808b: 
Retrying in 19 seconds
c0f6863f3dd4: Retrying in 19 seconds
3889bb8d808b: 
Retrying in 18 seconds
c0f6863f3dd4: Retrying in 18 seconds
c0f6863f3dd4: 
Retrying in 17 seconds
3889bb8d808b: Retrying in 17 seconds
c0f6863f3dd4: 
Retrying in 16 seconds
3889bb8d808b: Retrying in 16 seconds
3889bb8d808b: 
Retrying in 15 seconds
c0f6863f3dd4: Retrying in 15 seconds
c0f6863f3dd4: 
Retrying in 14 seconds
3889bb8d808b: Retrying in 14 seconds
3889bb8d808b: 
Retrying in 13 seconds
c0f6863f3dd4: Retrying in 13 seconds
c0f6863f3dd4: 
Retrying in 12 seconds
3889bb8d808b: Retrying in 12 seconds
c0f6863f3dd4: 
Retrying in 11 seconds
3889bb8d808b: Retrying in 11 seconds
3889bb8d808b: 
Retrying in 10 seconds
c0f6863f3dd4: Retrying in 10 seconds
c0f6863f3dd4: 
Retrying in 9 seconds
3889bb8d808b: 
Retrying in 9 seconds
3889bb8d808b: 
Retrying in 8 seconds
c0f6863f3dd4: Retrying in 8 seconds
c0f6863f3dd4: 
Retrying in 7 seconds
3889bb8d808b: Retrying in 7 seconds
3889bb8d808b: 
Retrying in 6 seconds
c0f6863f3dd4: Retrying in 6 seconds
c0f6863f3dd4: 
Retrying in 5 seconds
3889bb8d808b: Retrying in 5 seconds
c0f6863f3dd4: 
Retrying in 4 seconds
3889bb8d808b: Retrying in 4 seconds
3889bb8d808b: 
Retrying in 3 seconds
c0f6863f3dd4: Retrying in 3 seconds
3889bb8d808b: 
Retrying in 2 seconds
c0f6863f3dd4: Retrying in 2 seconds
c0f6863f3dd4: 
Retrying in 1 second
3889bb8d808b: Retrying in 1 second
C:\Program Files\Docker\docker.exe: read tcp 192.200.9.182:49997->204.79.197.219:443: wsarecv: An existing connection was forcibly 
closed by the remote host.
See 'C:\Program Files\Docker\docker.exe run --help'.

**Comment by pearljo** [comment]
> Is the VM Azure hosted or hosted locally on a server?

The VM is hosted locally on a server.

**Comment by pearljo** [comment]
I try to pull the microsoft/windowsservercore image and got the same error.
![image](https://user-images.githubusercontent.com/30619629/48190413-38e4d600-e375-11e8-8122-ef02b12c3e96.png)

**Comment by freddydk** [comment]
As expected the problem here is unrelated to the NAV containers.
It seems like something is wrong with the way this VM is connecting to the outside - your host might have something setup or the firewall in the company blocking something.

You might have a better chance of finding a solution to this problem on docker community sides.
Sorry.

**Comment by srifromchennai** [comment]
I changed Network Switch from DockerNAT to nat and the issue resolved.

**Comment by Kowa63** [comment]
I had the same error message just now while pulling a BC 20.4 container, but it was only temporarily, the second attempt succeeded. ![grafik](https://user-images.githubusercontent.com/16236672/187875038-f36494b2-ad7f-4e1a-90dd-89889ef7c58f.png)
