### ISSUE TITLE
Creating BC Docker Container Question - Error after Initializing

### ISSUE THREAD

**Issue by mahdyg** [microsoft/navcontainerhelper#2302]
Hi 
I am new to BC Docker Container. I tried to follow many different guidelines but I had no success. Basically everything is run and get to Initializing and then it stuck for a long time and then I receive the following error message. 
I have tried to remove all containers, images, remove docker, reinstall docker, use older BC image, use Sandbox and onprem version, download and save image and use saved image, hyperv or process isolation. All guideline I could find but had no success. I cannot pass the Initializing step and always receive the same exact error. 
Any help will greatly appreciate 

Sample of one script:
$containerName = 'bcdev20'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'us' -select 'Latest'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'script18' `
    -multitenant:$false `
    -assignPremiumPlan `
    -isolation 'process' `
    -memoryLimit 4G `
    -updateHosts

Error:

Building image took 886 seconds
Using image script18:sandbox-19.3.34541.35905-us
Creating Container bcdev20
Style: sandbox
Multitenant: No
Version: 19.3.34541.35905
Platform: 19.0.34506.35781
Generic Tag: 1.0.2.1
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19044.1526 (21H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\bcdev20\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bcdev20 from image script18:sandbox-19.3.34541.35905-us
b489cfe8e636f76a63be9cfe4167564a7d09b84bdc06ffd3523d1b9954ae2c1b
Waiting for container bcdev20 to be ready
Initializing...Error
Initializing...
New-BcContainer Telemetry Correlation Id: 18004b7a-13b0-481c-bfc4-a8a3a480fb1a
Initialization of container bcdev20 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.1\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ... throw "Initialization of container $containerName failed" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (Initialization ... bcdev20 failed:String) [], RuntimeException
+ FullyQualifiedErrorId : Initialization of container bcdev20 failed

**Comment by freddydk** [comment]
If your machine can run Windows 11 - you should upgrade - docker works much better on that.
If you stay on Windows 10, you can try to use hyperv isolation (change -isolation 'process' to -isolation 'hyperv') to the new-bccontainer command.

**Comment by mahdyg** [comment]
Some Info
I only had a success using command prompt as follow and I have a container now. But when I try to connect to it using Visual Basic / AL to get the symbols I receive the following error. I am not sure if I followed the right practice. 

How I created container: 
docker pull mcr.microsoft.com/businesscentral:10.0.19041.329
docker run -e accept_eula=Y -m 4G -e artifacturl=https://bcartifacts.azureedge.net/sandbox/16.3.14085.14363/us mcr.microsoft.com/businesscentral:10.0.19041.329

My jason file in AL: I tried both OnPrem and Sandbox 
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Your own server",
            "request": "launch",
            "type": "al",
            "environmentType": "OnPrem",
            "server": "http://mysandbox",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default"
        }
    ]
}

Error message: AL ask for user name and password after I enter them I receive the following. I can access Web Client using the same user and password. 

[2022-02-09 07:56:34.53] Using reference symbols cache path: c:\Users\MahdyG\Documents\AL\ALProject1\./.alpackages
[2022-02-09 07:56:34.57] Targeting server 'http://mysandbox', server instance 'BC' and tenant 'default'.
[2022-02-09 07:56:34.65] Please authenticate in the Visual Studio Code...
[2022-02-09 07:56:52.42] Using reference symbols cache path: c:\Users\MahdyG\Documents\AL\ALProject1\./.alpackages
[2022-02-09 07:56:52.43] Targeting server 'http://mysandbox', server instance 'BC' and tenant 'default'.
[2022-02-09 07:56:52.43] Using user name and password authentication. User name used is: 'mahdyg'.
[2022-02-09 07:56:52.44] Sending request to http://mysandbox:7049/BC/dev/metadata?tenant=default
[2022-02-09 07:56:52.46] Sending request to http://mysandbox:7049/BC/dev/metadata?tenant=default
[2022-02-09 07:56:54.75] Authorization has failed or the credentials have expired. The credential cache has been cleaned. Any access to reach Business Central would require new authorization.
The authentication has been cancelled.

**Comment by freddydk** [comment]
you could remove the -imagename property and try again,
You could also try and add -usegenericimage 'mcr.microsoft.com/businesscentral:10.0.19041.329' to specify that you want to use this image specifically.

**Comment by mahdyg** [comment]
Thanks Freddy for your help. I ended up removing each parameters and finally the following one worked for me. As soon as I add any extra parameters it get stuck at the same step. Thanks again 

$artifactUrl = Get-BcArtifactUrl -type onprem -country us -select Latest
New-BCContainer -accept_eula -containerName sandboxdev -artifactUrl $artifactUrl -assignPremiumPlan
