### ISSUE TITLE
Possibility to define a base path when publishing to Azure Storage

### ISSUE THREAD

**Issue by domingosbarreto** [microsoft/navcontainerhelper#2308]
**Describe the issue**
When publishing a package to Azure Storage, it would be helpful to have the ability to define a base folder/path for the app inside the container. 

At this moment there is only the possibility to define the Container name. If there is the need to organize the storage in a more structured way, i.e. Project (Container) > Folder > version/latest (Folder), this is not possible. This is particulary useful in a case where in the same Project there is multiple repositories (each representing an app).

I would suggest to add a new parameter (optional) to Publish-BuildOutputToStorage, where it would be possible to define a basePath and change the calls for Set-AzureStorageBlobContent to include it before ""$appVersion/$_.zip".ToLowerInvariant()" and ""latest/$_.zip".ToLowerInvariant()".

Thank you!

**Comment by freddydk** [comment]
@jonaswre - do you have any feedback on this request?

**Comment by jonaswre** [comment]
I think this would be useful and it will be easily backwards compatible. 
But you could also create new storage accounts for each project. This would give you another level of abstraction.

I think it might be useful to additionally consider adding a switch to extract every app in its own folder. This is the same way its done in Publish-BuildOutputToAzureFeed. This would allow a user to use the blob storage as a kind of feed.  @domingosbarreto is this something you try to achieve?

**Comment by jonaswre** [comment]
> I think it might be useful to additionally consider adding a switch to extract every app in its own folder. This is the same way its done in Publish-BuildOutputToAzureFeed. This would allow a user to use the blob storage as a kind of feed. @domingosbarreto is this something you try to achieve?

This point should be request separately if somebody needs it.
But If you need this you should rather use Publish-BuildOutputToAzureFeed. For explicit per App resolution.
