### ISSUE TITLE
Run-AlPipeline fails when including bcptTestFolders to include running performance tests

### ISSUE THREAD

**Issue by amea20** [microsoft/navcontainerhelper#2311]
**Describe the issue**
When trying to create a W1 sandbox container,  including the performance toolkit, the script fails due to the protection level error as shown in the screenshot below. This isn't an issue in an OnPrem container.

**Scripts used to create container and cause the issue**
```
Run-AlPipeline -pipelineName 'current' `
               -auth NavUserPassword `
               -artifact ///w1/Current `
               -containerName bcpt `
               -outputFolder Extension `
               -baseFolder $baseFolder `
               -sharedFolder '' `
               -memoryLimit 16Gb `
               -credential $credential `
               -licenseFile $licenseFileUri `
               -appFolders app `
               -testFolders '' `
               -bcptTestFolders perfTest `
               -appBuild 29894 `
               -bcptTestResultsFile bcptresults.xml `
               -AppSourceCopMandatoryAffixes TWM `
               -enableCodeCop:$false `
               -enableAppSourceCop:$true `
               -enableUICop:$false `
               -installTestLibraries `
               -installPerformanceToolkit
```

**Screenshots**
![image](https://user-images.githubusercontent.com/29795425/154060406-c457b2d8-2674-4e0f-abcd-06d8cf98598b.png)

**Additional context**
- It happens all the time

**Comment by freddydk** [comment]
What Business Central version are you using?

**Comment by amea20** [comment]
At the time of running this, it was 19.3. I just re-ran it and it's 19.4.35398.36261

**Comment by freddydk** [comment]
Must have been a bug back then have not been able to repro, 3.0.9 works (shipped this morning)
Just build support for bcpt tests into AL-Go for GitHub and tested Run-AlPipeline (which is used in AL-Go)

**Comment by amea20** [comment]
Hi Freddy,

I can confirm that the issue has been resolved.

Thanks for your help.
