### ISSUE TITLE
Collation issue on import of xml file on BC Docker Container

### ISSUE THREAD

**Issue by Charlottesaliba** [microsoft/navcontainerhelper#2313]
**Describe the issue**
I have 2 business central v. 19.0 containers, on one the special characters from the xml file import fine. and on the other they are not.
i can't figure out the setting missing. any guesses?
example: 
on Container 1: KourinLaindbäck
on Container 2: KourinLaindb“ñck

**Comment by freddydk** [comment]
are the containers running on the same machine?
are the containers running the same isolation mode?

**Comment by Charlottesaliba** [comment]
> are the containers running on the same machine? are the containers running the same isolation mode?

no they are running on 2 different azure virtual machine

**Comment by freddydk** [comment]
Just because you do not specify the isolation mode, doesn't mean that they are process - it depends on the server OS and a lot of other stuff.
Docker inspect can tell you for sure.

I can ask you a lot of questions back and forth here to try and shoot my way into why this is, or you could copy/paste the script and the full output from the container generation from both machines - then I would probably be able to tell you right away why this is.

**Comment by Charlottesaliba** [comment]
Container 1:
$artifactUrl = Get-BCArtifactUrl -type Sandbox -select Current -country $country
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -updateHosts `
    -dns '8.8.8.8' `
    -PublishPorts 80,443,7045,7046,7047,7048,7049,8080 `
    -PublicDnsName $PublicDnsName `
    -multitenant:$false `
    -memoryLimit 12G `
    -enableTaskScheduler
    
  Container 2:
  $artifactUrl = Get-BCArtifactUrl -type Sandbox -select current -country $country
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -updateHosts `
    -dns '8.8.8.8' `
    -PublishPorts 80,443,7045,7046,7047,7048,7049,8080 `
    -PublicDnsName $PublicDnsName

**Comment by freddydk** [comment]
and the output from both

**Comment by Charlottesaliba** [comment]
Is the output log saved somewhere? it's been a while since they were created :)

**Comment by Charlottesaliba** [comment]
I don't have one similar for Container 2 from the Docker Log

![image](https://user-images.githubusercontent.com/33659541/154147531-ab3154a8-40fe-4ebf-9443-0e4276612676.png)

**Comment by freddydk** [comment]
docker inspect can tell you whether they are running process or hyperv isolation.

**Comment by Charlottesaliba** [comment]
Conatiner 1:
Environment
DATABASESERVER

CUSTOMNAVSETTINGS
EnableTaskScheduler=True

ACCEPT_EULA
Y

ACCEPT_OUTDATED
Y

LICENSEFILE
c:\run\my\license.flf

ISBCSANDBOX
Y

ENABLEAPISERVICES
Y

SECUREPASSWORD
76492d1116743f0423413b16050a5345MgB8AEIAWgBrAE4AVAA4AHkAOAB6AGkAbgBMAEkAcgAyAHQAUwBQAHgANwBuAGcAPQA9AHwAMQA2AGUAMQBmAGUANABjADQAYgAxADMAMQBkADEAOQAzAGUAYQA2AGIANgAyAGQAYgAxAGQAYwA0ADYAMAAwADYAOAA3AGEAYwAwADAANAA1ADUAMAAzADgAOAA2ADQAMQBkAGEAMQA0ADEAMABjAGYAMwA2AGMAZQBjADgAYwA=

PASSWORDKEYFILE
c:\run\my\aes.key

PUBLICDNSNAME
***.westeurope.cloudapp.azure.com

LOCALE
en-GB

USESSL
N

ARTIFACTURL
https://bcartifacts.azureedge.net/sandbox/19.0.29894.32046/gb

USERNAME
vmadmin

EXITONERROR
N

DATABASEINSTANCE

FILESONLY
False

REMOVEPASSWORDKEYFILE
Y

AUTH
NavUserPassword

COMPLUS_NGENPROTECTEDPROCESS_FEATUREENABLED
0

Mounts
C:\PROGRAMDATA\BCCONTAINERHELPER
c:\programdata\bccontainerhelper

C:\RUN\MY
c:\programdata\bccontainerhelper\extensions\bc19gb\my

C:\DL
c:\bcartifacts.cache

C:\DRIVERSETC
c:\windows\system32\drivers\etc

Ports
1433/tcp
Not bound
443/tcp
0.0.0.0:443

7045/tcp
0.0.0.0:7045

7046/tcp
0.0.0.0:7046

7047/tcp
0.0.0.0:7047

7048/tcp
0.0.0.0:7048

7049/tcp
0.0.0.0:7049

7083/tcp
Not bound
80/tcp
0.0.0.0:80

8080/tcp
0.0.0.0:8080

**Comment by Charlottesaliba** [comment]
Container 2:

Environment
PUBLICDNSNAME
***.westeurope.cloudapp.azure.com

LOCALE
en-GB

ENABLEAPISERVICES
Y

PASSWORDKEYFILE
c:\run\my\aes.key

ACCEPT_EULA
Y

ACCEPT_OUTDATED
Y

MULTITENANT
Y

AUTH
NavUserPassword

EXITONERROR
N

FILESONLY
False

ISBCSANDBOX
Y

USERNAME
vmadmin

DATABASEINSTANCE

USESSL
N

SECUREPASSWORD
76492d1116743f0423413b16050a5345MgB8AEwATQBiAFgANgAvAG8AQQB2AE4AOABuAFoAVABKADYAMQBUAFMAZQBvAGcAPQA9AHwAMgAyAGQAZAAyAGIANwAyAGMAMgA5ADgAZgBhAGMAOAA5ADQAMwAyADkAMQBmADQAZAAzAGQAMwBiAGEANQA2ADMANAA4ADkAOQBlAGQAMgA4ADAANABkADEAMgAxADUAMAAxAGMAMwAyADAAYgAwADcAZgA1ADUAMgAwADQAZAA=

REMOVEPASSWORDKEYFILE
Y

ARTIFACTURL
https://bcartifacts.azureedge.net/sandbox/19.1.31886.32186/gb

LICENSEFILE
c:\run\my\license.flf

DATABASESERVER

COMPLUS_RUNNING_IN_CONTAINER
1

COMPLUS_NGENPROTECTEDPROCESS_FEATUREENABLED
0

Mounts
C:\DRIVERSETC
c:\windows\system32\drivers\etc

C:\PROGRAMDATA\BCCONTAINERHELPER
c:\programdata\bccontainerhelper

C:\RUN\MY
c:\programdata\bccontainerhelper\extensions\bc19gb\my

C:\DL
c:\bcartifacts.cache

Ports
1433/tcp
Not bound
443/tcp
0.0.0.0:443

7045/tcp
0.0.0.0:7045

7046/tcp
0.0.0.0:7046

7047/tcp
0.0.0.0:7047

7048/tcp
0.0.0.0:7048

7049/tcp
0.0.0.0:7049

7083/tcp
Not bound
80/tcp
0.0.0.0:80

8080/tcp
0.0.0.0:8080

**Comment by freddydk** [comment]
![image](https://user-images.githubusercontent.com/10775043/154152080-ee1c16ec-d9db-462b-937c-42410c37a405.png)

**Comment by Charlottesaliba** [comment]
AAAAHHh Found it.

Container 1:
"Isolation": "hyperv"

Container 2:
"Isolation": "process"

That's the issue?

**Comment by freddydk** [comment]
Well, I think to remember that Windows Server 2019 has a problem with stuff like this, but I cannot remember what works and what doesn't (I think hyperv works = the workaround)
I think Windows Server 2016 works - and Windows Server 2022 as well (+Windows 11) - but not sure.

**Comment by Charlottesaliba** [comment]
Argh I thought I've seen this somewhere but i didn't think it's my issue. A great ending for the night though thanks a lot for the help. Godnat fra Brande :)

![image](https://user-images.githubusercontent.com/33659541/154155697-0227d707-4b29-4b15-aac9-f6ecf2c73194.png)
