### ISSUE TITLE
Get-BCArtifactUrl error on windows 11

### ISSUE THREAD

**Issue by pauldelacruz-pasi** [microsoft/navcontainerhelper#2315]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Error encountered when running Get-BCArtifactUrl on Windows 11. Issue encountered on two windows 11 machines.

**Scripts used to create container and cause the issue**
```
Get-BCArtifactUrl -country base -select Current
```

**Full output of scripts**
```
Get-BCArtifactUrl -country base -select Current
Setting use7zipIfAvailable = True
Setting digestAlgorithm = SHA256
Setting baseUrl = https://businesscentral.dynamics.com
Setting DOCKER_SCAN_SUGGEST = False
Setting mapCountryCode = @{ae=w1; bd=w1; dz=w1; eg=w1; fo=dk; gl=dk; id=w1; ke=w1; lb=w1; lk=w1; lu=w1; ma=w1; mm=w1; mt=w1; my=w1; ng=w1; qa=w1; sa=w1; sg=w1; tn=
w1; ua=w1; za=w1}
Setting useVolumeForMyFolder = False
Setting psSessionTimeout = 0
Setting MicrosoftTelemetryConnectionString = InstrumentationKey=5b44407e-9750-4a07-abe9-30c3b853821b;IngestionEndpoint=https://southcentralus-0.in.applicationinsig
hts.azure.com/
Setting hostHelperFolder = C:\ProgramData\BcContainerHelper
Setting defaultContainerName = bcserver
Setting timeStampServer = http://timestamp.digicert.com
Setting bcartifactsCacheFolder = c:\Temp\bcartifacts.cache
Setting SendExtendedTelemetryToMicrosoft = False
Setting containerHelperFolder = C:\ProgramData\BcContainerHelper
Setting TraefikImage = traefik:v1.7-windowsservercore-1809
Setting apiBaseUrl = https://api.businesscentral.dynamics.com
Setting PartnerTelemetryConnectionString = 
Setting sandboxContainersAreMultitenantByDefault = True
Setting usePsSession = True
Setting genericImageName = mcr.microsoft.com/businesscentral:{0}
Setting ObjectIdForInternalUse = 88123
Setting useSharedEncryptionKeys = True
Setting TreatWarningsAsErrors = AL1026
Setting TraefikUseDnsNameAsHostName = False
Setting genericImageNameFilesOnly = mcr.microsoft.com/businesscentral:{0}-filesonly
Setting defaultNewContainerParameters = @{Accept_Eula=True; licenseFile=***; UpdateHosts=True}
BcContainerHelper version 3.0.3-preview550
BcContainerHelper emits usage statistics telemetry to Microsoft
WARNING: The names of some imported commands from the module 'BcContainerHelper' include unapproved verbs that might make them less discoverable. To find the comma
nds with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

Get-BCArtifactUrl Telemetry Correlation Id: 9a4a6108-81ab-461b-881b-ebbb8c807959
Exception calling "DownloadString" with "1" argument(s): "An exception occurred during a WebClient request."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.3\Misc\Get-BcArtifactUrl.ps1:197 char:13
+             $Response = $webClient.DownloadString("$GetListUrl$nextMa ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : WebException
```

**Screenshots**

**Additional context**
- does it happen all the time? Yes
- did it use to work? Yes

**Comment by freddydk** [comment]
could you try to use:

Get-BCArtifactUrl -country base -select Current -verbose

And display the output

BTW - you should remove all the entries in your bccontainerhelper.config.json which you don't want to explicitly set - no need to have default values there and you would not get any changes to f.ex. the country map if a new version has changes.

**Comment by pauldelacruz-pasi** [comment]
Hi Freddy,

Thank you for the advise with the bccontainerhelper.config.json. As instructed below is the result.

PS C:\Windows\system32> Get-BCArtifactUrl -country base -select Current -verbose
VERBOSE: DownloadString https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container
Get-BCArtifactUrl Telemetry Correlation Id: c319a7b7-ca7d-4c80-a8a2-c3ad103456f9
Exception calling "DownloadString" with "1" argument(s): "An exception occurred during a WebClient request."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.3\Misc\Get-BcArtifactUrl.ps1:197 char:13
+             $Response = $webClient.DownloadString("$GetListUrl$nextMa ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : WebException

**Comment by freddydk** [comment]
If you open https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container in a browser - does it return anything?

**Comment by pauldelacruz-pasi** [comment]
Yes, it outputs the URL's

![image](https://user-images.githubusercontent.com/42555550/154299855-d44179a0-983d-4660-b377-55109eebd3a1.png)

Thanks

**Comment by freddydk** [comment]
and this (in PowerShell):

```
(New-Object System.Net.WebClient).DownloadString('https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container')
```

**Comment by pauldelacruz-pasi** [comment]
I am getting the error.

![image](https://user-images.githubusercontent.com/42555550/154301516-338badb8-6d29-4ea9-84a6-d496bf964185.png)

Thanks

**Comment by freddydk** [comment]
What does this return in PowerShell

```
 [Net.ServicePointManager]::SecurityProtocol
```

**Comment by pauldelacruz-pasi** [comment]
![image](https://user-images.githubusercontent.com/42555550/154301774-fd027711-0962-4d3f-b09f-b7a2872101b0.png)

**Comment by freddydk** [comment]
try this

```
Try
{
   (New-Object System.Net.WebClient).DownloadString('https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container')
}
Catch [Exception]
{
    Write-Host $_.Exception | format-list -force
}

```

**Comment by pauldelacruz-pasi** [comment]
Below is the result.

![image](https://user-images.githubusercontent.com/42555550/154302503-9ad327d7-2785-45cd-a5f3-0dc48f3f51f8.png)

Thanks

**Comment by freddydk** [comment]
strange

and this

```
(Invoke-WebRequest -UseBasicParsing -Uri 'https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container').Content
```

**Comment by pauldelacruz-pasi** [comment]
![image](https://user-images.githubusercontent.com/42555550/154303304-17186c0f-5877-4cdb-9298-4aa799668400.png)

then i got the error

![image](https://user-images.githubusercontent.com/42555550/154303440-db6303c5-2c0a-40bf-887a-3484aaa43f1d.png)

**Comment by pauldelacruz-pasi** [comment]
Hi Freddy, 

I am not using vpn or any other antivirus except for windows security. I will check for any programs that is installed that may block the communication as suggested. Thank you for the assistance.

**Comment by freddydk** [comment]
and/or maybe try to disable defender for a test.
Haven't seen this behavior before (using Windows 11 myself)

**Comment by pauldelacruz-pasi** [comment]
Hi Freddy,

I have disabled the defender and I got the same error. It's weird that I am also experiencing the same issue on another machine which is also running windows 11.

Thanks for the help.

**Comment by freddydk** [comment]
Strange - can you download this file as a string using WebClient downloadstring?

https://raw.githubusercontent.com/microsoft/navcontainerhelper/master/Misc/Download-File.ps1

**Comment by freddydk** [comment]
Are you running PowerShell ISE or PowerShell?

**Comment by pauldelacruz-pasi** [comment]
I am running PowerShell ISE.

**Comment by pauldelacruz-pasi** [comment]
I hope I followed your instruction correctly.

![image](https://user-images.githubusercontent.com/42555550/154311352-f17fa982-5bc7-4786-af60-413de700191c.png)

**Comment by freddydk** [comment]
Could you try to run this code:

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12
[Net.ServicePointManager]::Expect100Continue = $false
(New-Object System.Net.WebClient).DownloadString('https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container')
```

**Comment by pauldelacruz-pasi** [comment]
Hi Freddy,

I got the same error.

![image](https://user-images.githubusercontent.com/42555550/154416978-cb1c4a80-9a0b-44d1-98f4-90349378b2c9.png)

Thanks

**Comment by freddydk** [comment]
How much time does it take from running the script until erroring out?

**Comment by pauldelacruz-pasi** [comment]
around 30 seconds.

Thanks

**Comment by freddydk** [comment]
???
3 seconds on mine
Could you try this
```
Download-File -sourceUrl 'https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container' -destinationFile 'c:\temp\test.xml' -timeout 1000
```
(change the destinationfile to a path where you want a test.xml to be stored)

**Comment by jonaswre** [comment]
I don't thinks its an issue with windows 11.
How long does it take to load in the browser? 
I takes about a second in my setup. 

Are you in a corporate network? 
Any Firewall/Proxy configuration that might be applied by an admin?

This just seems to be a network issue. Maybe the browser is handling bad connections better then powershell. 
maybe `tracert bcartifacts.blob.core.windows.net` will give you some insight where things go wrong. Please be aware if you post the output this might give away some sensitive information.

**Comment by pauldelacruz-pasi** [comment]
Hi Freddy,

I am getting the same error at around 30 seconds. I guess this is a network issue as suggested by [jonaswre](https://github.com/jonaswre). Running the https://bcartifacts.blob.core.windows.net/sandbox/?comp=list&restype=container on my browser also take around 30 seconds and seems to show incomplete URL's. I am currently working at home and tracert also shows time out on the result. Although I tried this last week on my laptop on a different network and I am also getting the same error. Apologies for taking your time and thank you very much for the assistance

![image](https://user-images.githubusercontent.com/42555550/154424536-730f5a7a-2ff0-4391-9af2-cd3da1f9db1a.png)

![image](https://user-images.githubusercontent.com/42555550/154426663-0ac032f1-0ae9-4029-b981-3a379e7674b6.png)

**Comment by freddydk** [comment]
You could try Tobias Fensters new Azure function: https://tobiasfenster.io/get-your-bc-artifact-urls-without-powershell
(if everything else works of course - having these network issues might surface in other places as well)

**Comment by pauldelacruz-pasi** [comment]
Thank you Freddy for the suggestion. As of now I can only generate the artifact url by specifying a version. If I use the -select parameter that is when I get the DownloadString error.

**Comment by freddydk** [comment]
ok

**Comment by freddydk** [comment]
So, you are saying that

```
Get-BCArtifactUrl -country base -select Latest
```
actually works???

**Comment by freddydk** [comment]
so 

```
Get-BCArtifactUrl -country base
```

doesn't work?
what about

```
Get-BCArtifactUrl -country base -version 19.4 -select latest
```

?

**Comment by shashiBssi** [comment]
i am also having same problem. i am on windows 11

**Comment by freddydk** [comment]
@shashiBssi And it also works if you limit the versions and specifying 19.4 or like?

**Comment by shashiBssi** [comment]
@freddydk i specified -version '19.4.35398.36119'... and it looks like its working. containercreation is still in process

**Comment by pauldelacruz-pasi** [comment]
hi, confirming that this is an issue with my ISP. my officemate who tried it on a different ISP did not encounter the issue.
