### ISSUE TITLE
Validation fail when publishing app to Microsoft Appsource

### ISSUE THREAD

**Issue by bhlDeex** [microsoft/navcontainerhelper#2318]
Hello, I am Peter Lee from Deex Korea.

I am trying to publish an App to the Microsoft Appsource but I kept on getting validation error.

The error is that the app has not been signed even if I have succesfully signed with a valid certificate. 

I am attaching the screenshot for both error and the digitally signed app.

I still do not what the issue for getting this error. 

Could I get some help with this?

Thank you.

![image](https://user-images.githubusercontent.com/48191630/154722438-09766301-cfa8-46b4-8b64-4f9b87b94934.png)

![image](https://user-images.githubusercontent.com/48191630/154723076-d54c3de6-e97b-406a-a973-ea8080feab04.png)

![image](https://user-images.githubusercontent.com/48191630/154723044-cbdb7172-ec37-44aa-9d15-363e31d13224.png)

**Comment by freddydk** [comment]
We have discovered that if you submit an app to partner center which is not signed, and then later sign this app and re-uploads the signed app, partner center won't detect the changed app.

You will need to recompile (new version number, new package id) and sign and then upload to partner center.
