### ISSUE TITLE
expanding Get-NavContainerAppInfo with -tenant parameter

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#232]
Is it possible to add the -tenant paramter to the Get-NavContainerAppInfo command.
I interpret the used nav command Get-NavAppInfo as follows, when the available -tenant parameter is used it returns the installed extensions, and when the -tenant parameter is ommited, like it is now implemented, all published extensions are returned.

I would like to use the Get-NavContainerAppInfo command to return all installed extensions on a certain tenant. following code seems to work;
    $session = Get-NavContainerSession -containerName $containerName
    Invoke-Command -Session $session -ScriptBlock { Param($tenant, $symbolsOnly)
        Get-NavAppInfo -ServerInstance NAV -Tenant $tenant #-symbolsOnly
    } -ArgumentList $tenant, $symbolsOnly

**Comment by freddydk** [comment]
Shipped in 0.4.0.0
