### ISSUE TITLE
Start-BcContainerAppDataUpgrade should Support Language

### ISSUE THREAD

**Issue by git-no** [microsoft/navcontainerhelper#2321]
## Issue
Command `Start-NAVAppDataUpgrade` does support a language setting by parameter but the command `Start-BcContainerAppDataUpgrade` does not support a **language** setting.

## Possible Impact
Data initializations are done in Englisch, not in the DB language, e.g. de-DE.

## Request 
Enhance the command `Start-BcContainerAppDataUpgrade` by a language parameter and forward this parameter to the `Start-NAVAppDataUpgrade` within the Powershell function.

**Comment by freddydk** [comment]
fixed in 3.0.4
