### ISSUE TITLE
Way to Generate AL permission set containing current extension objects

### ISSUE THREAD

**Issue by vvkjndl** [microsoft/navcontainerhelper#2323]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
In Visual Studio Code after opening an AL project, we can generate a permission set XML file using AL command palette.

Does BcContainerHelper provide any such functionality to generate this permission set file programmatically?

**Scripts used to create container and cause the issue**
```
Ctrl+Shift+P (after opening VSCode with AL project, then navigate to command "Generate AL permission set containing current extension objects")
```

**Full output of scripts**
```
It created a file named "extensionsPermissionSet.xml" in the AL project folder.
```

**Screenshots**
NA

**Additional context**
- does it happen all the time? NA
- did it use to work? NA

**Comment by freddydk** [comment]
Currently not, will check with the team whether we could add that

**Comment by freddydk** [comment]
With the change away from xml files for permissions, into specifying permissions in .al files - this is not on our radar,
We will also not add any functionality to add this to .al files, as this should be a considerate task.
