### ISSUE TITLE
Image created with New-BcContainer has insufficient space

### ISSUE THREAD

**Issue by horribleCodes** [microsoft/navcontainerhelper#2330]
Whenever I try to restore the database of my container, I get a warning that there's insufficient disk space to use the backup. This is inconsistent with my colleagues, who were able to restore the same backup using the same container- and image settings. I have also been able to restore previous backups of the same database, which had a similar file size.
The error code is as follows:
```
The database restore operation failed due to the following error returned by SQL Server:
There is insufficient free space on disk volume 'c:\' to create the database. The database requires 49215766528 additional free bytes, while only 19356622848 bytes are available.
Problems were identified while planning for the RESTORE statement. Previous messages provide details.
RESTORE DATABASE is terminating abnormally.
At C:\Program Files\WindowsPowerShell\Modules\BCContainerhelper\2.0.15\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The database re...ing abnormally.:String) [], RuntimeException
    + FullyQualifiedErrorId : The database restore operation failed due to the following error returned by SQL Server:
    There is insufficient free space on disk volume 'c:\' to create the database. The database requires 49215766528 additional free bytes, while only 19356622848 bytes are availab 
   le.
Problems were identified while planning for the RESTORE statement. Previous messages provide details.
RESTORE DATABASE is terminating abnormally.
```

I am using BCContainerhelper 2.0.15, as well as Docker Desktop 4.0.1.

I have tried resetting my PC, deleting all containers and images, purging all data, reseting to factory defaults, restoring the database using SQL Management Service Studio, and disabling the WSL 2 based engine, but nothing has worked so far.

**Comment by freddydk** [comment]
As you haven't included script and output, I cannot see how you start the container and/or which isolation mode you run.

You should upgrade to BcContainerHelper 3.0.3 (this might solve the issue by forcing process isolation)
You might be able to add -isolation process to achieve the same.

Alternatively, you can add -additionalParameters @("--storage-opt size=100GB") to allow a hyperv container to use 100Gb of disk space (not sure whether this also is required on process isolation containers.

**Comment by dkatson** [comment]
@freddydk , is it possible to increase the size of the running container? I try to import data file (navdata) and i get the next error in the log 

Server instance: NAV Tenant ID: User: Type: System.Data.SqlClient.SqlException ClientConnectionId: 1916a894-7222-4e2d-8c8c-013d934da91a Class: 17 LineNumber: 1 Number: 1101 Server: LOCALHOST\SQLEXPRESS State: 12 Source: .Net SqlClient Data Provider ErrorCode: -2146232060 Message: Could not allocate a new page for database 'mydatabase' because of insufficient disk space in filegroup 'PRIMARY'. Create the necessary space by dropping objects in the filegroup, adding additional files to the filegroup, or setting autogrowth on for existing files in the filegroup.

**Comment by freddydk** [comment]
Hi Dmitry - yeah, using this option 
 -additionalParameters @("--storage-opt size=100GB")

increases the disk space allocation in the container.
Alternatively you can use SQL on the host (have a blog post on how to on freddysblog.com)
