### ISSUE TITLE
Cannot open the question mark menu on the top right in current BCv20/NextMajor insider build

### ISSUE THREAD

**Issue by SHermann73** [microsoft/navcontainerhelper#2331]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
After loggin in into the environment, I want to check the version via the question mark menu on the top right and selecting "Help & Support". But when clicking the question mark, nothing happens.
Inside of the Chrome debugger, an error is logged (See screenshot below).
Maybe this is referencing to the source issue behind.
This is most probably not related to the BCContainerHelper, but issued here for further analysis/forwarding to the appropriate team.

**Scripts used to create container and cause the issue**
```
New-BcContainer `
    -accept_eula `
    -containerName $ContainerName `
    -artifact $artifactUrl `
    -auth UserPassword `
    -Credential $Credential `
    -updateHosts
```

**Full output of scripts**
```
...
```

**Screenshots**
![2020-03-01 - BCv20 Issue with question mark menu](https://user-images.githubusercontent.com/38069148/156171688-66ae622b-99b9-4db7-8e3d-46acdd525c40.PNG)

**Additional context**
- does it happen all the time? -> Yes
- did it use to work? -> Yes

**Comment by freddydk** [comment]
I can see you were using base (Cronus International) - also works here.
Did you try to remove cookies etc. in your browser ?

**Comment by SHermann73** [comment]
Hi Freddy
I gave it a try in incognito mode and it worked for me now as well.
I cleared the cookies in normal mode but this did not help.
I cleared even more browsing data (history, cookies, cache) and now it works in normal mode as well.
Strange thing...

Sorry for the inconveniences and thanks for your help!
