### ISSUE TITLE
issue BC container helper -Azure devops server Buusiness central

### ISSUE THREAD

**Issue by ABIDI-NOURHENE** [microsoft/navcontainerhelper#2335]
Hello,

i'm working to activate Azure devops pipeline for Buisness central.

i have issue with BCCONTAINERHELPER this my troubleshooting log.
[logs_123.zip](https://github.com/microsoft/navcontainerhelper/files/8185795/logs_123.zip)
![image](https://user-images.githubusercontent.com/80278207/156761872-74ad8c63-2fed-4564-8f0d-ef65f705e19b.png)

we work with BC onpremise and azure devops server 

Best regars !

**Comment by freddydk** [comment]
It looks like you are using a self-hosted agent running as a user, which doesn't have the rights to do what the pipeline does.
Try setting up the agent as system or network_service
