### ISSUE TITLE
[Question] How to achieve same result using Run-AlPipeline

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#2336]
Hi Freddy, 

This is just a question, not an issue at all. The following script uses _-myscript_ and _-additionalParameters._

Is there a way to pass them to the function Run-AlPipeline or some parameter to achieve same result?

```
$bacpacFolder        = <Change path to folder where the app.bacpac and tenant.bacpac are saved to, for example "C:\bacpacs">
$appBacpacUri        = "$bacpacFolder\app.bacpac"
$tenantBacpacUri     = "$bacpacFolder\tenant.bacpac"
 
New-BCContainer -containerName $containerName `
    -accept_outdated `
    -accept_eula `
    -auth NavUserPassword `
    -Credential $Credential `
    -updateHosts `
    -licenseFile $licenseFileUri `
    -memoryLimit 10G `
    -multitenant `
    -isolation hyperv `
    -includeAL `
    -artifactUrl $bcartifact `
    -dns 8.8.8.8 `
    -myScripts @($appBacpacUri, $tenantBacpacUri) `
    -additionalParameters @("--env appbacpac=c:\run\my\app.bacpac","--env tenantbacpac=c:\run\my\tenant.bacpac") 
```

Thank you

**Comment by freddydk** [comment]
Run-AlPipeline has a parameter called NewBcContainer, which is described in this topic https://github.com/microsoft/navcontainerhelper/issues/2269

**Comment by jonaswre** [comment]
I always use the following line as a starting point. 

https://github.com/microsoft/navcontainerhelper/blob/master/AppHandling/Run-AlPipeline.ps1#L602

**Comment by eclipses** [comment]
My initial idea was to add parameters to the existing ones, NewBcContainer override all parameters, I need to declare again all of them including the shared paths. Thank you for your help.

**Comment by freddydk** [comment]
Not exactly.
The default implementation of NewBcContainer is:

```
{
    Param([Hashtable] $parameters)
    New-BcContainer @parameters
}
```

The HashTable will have all parameters set.
You can just add or set the missing parameters in this hashtable before calling New-BcContainer and you are good to go.

The same concept goes again in all overrides - a hashtable with parameters and a call to the function.

**Comment by eclipses** [comment]
Hi Freddy, 

According to your previous comment, $parameters should have already all pamaters and I can add or change them.

Here my attempt:
`$NewBcContainer = { 
Param([Hashtable]$parameters)
    $parameters["additionalParameters"] += @("--env appbacpac=c:\run\my\app.bacpac","--env tenantbacpac=c:\run\my\tenant.bacpac")
    $parameters.Add("myScripts",@($appBacpacUri, $tenantBacpacUri))
    New-BCContainer $parameters;
    Invoke-ScriptInBcContainer $parameters.containerName -scriptblock { $progressPreference = 'SilentlyContinue' } 
}`

This is stopping with the error
**You have to accept the eula (See https://go.microsoft.com/fwlink/?linkid=861843) by specifying the -accept_eula switch to the function**

I've tried to add the parameter accept_eula or to set its value but still returning same error.

**Comment by freddydk** [comment]
replace
New-BCContainer $parameters
with
New-BCContainer @parameters

That is the way to transfer a hashtable as parameters as also shown in my example.

**Comment by eclipses** [comment]
You're the best! 

Thank you, I did not notice that I changed the @ with $ (my bad).

Tested and worked correctly. 

I'm closing this issue.

**Comment by freddydk** [comment]
:-)
I have made the same mistake like a million times...
