### ISSUE TITLE
[Question] Run AlValidation with bcpublicpreview

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#2337]
How can we use Run-AlValidation with bcpublicpreview?
Since bcpublicpreview differs from bcinsider preview we should validate against bcpublicpreview.

**Comment by freddydk** [comment]
bcinsider is running from the release branch, meaning that the public preview build is also available on bcinsider.
This means that bcinsider is newer than public preview and still the right build to use for validation, and the one used when using -validateNextMajor.

Get-BcArtifactUrl -select NextMajor will actually check whether public preview is newer than bcinsider and select the right one.

**Comment by ChrisBlankDe** [comment]
thank you for clarification
