### ISSUE TITLE
Download symbols or Publishing: No response connected party

### ISSUE THREAD

**Issue by HansDutting** [microsoft/navcontainerhelper#2338]
Since Friday 4-3-22 I have a problem with my development container(s) in VS Code.
Settings in VS Code app and launch.json weren't changed by anything the days before and I could download symbols.
My local development containers are running, they are reachable with the webclient.
But if I want to Download symbols, Publish, Debug I get the error:
_party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (BC19:7049)_

Docker Desktop 4.5.1 (74721)
VS Code: 1.65.0

Checked the firewall settings with our sysadmin, but these ports 7046-7049 aren't blocked.
Didnt get patches from our company on my laptop.

If I check with powershellcmd: docker port bc19 7049 the port isn't set as published. I thought that could maybe be the problem.
So I tried to create a new BC19 container with this PowerShellscript:

_$artifactUrl = Get-BCArtifactUrl -version 19 -type Sandbox -country nl

New-BCContainer -artifactUrl $artifactUrl -accept_eula -containerName bc19 -licenseFile 'Licenselocation' -auth NavUserPassword -memoryLimit '12G' -dns '8.8.8.8' -accept_outdated -includeAL -alwaysPull -updateHosts -additionalParameters @(
"--publish 7046-7049:7046-7049")_

Port 7049 is now published, but still get the same error when downloading symbols.
Tried with the newest Windows updates, bringing down the firewall, but still no response error.
Checked telnet on the ports local but no response.
I can ping the container(s) successfully.

So I'm completely lost why VS Code gives this error suddenly.
The sysadmin concludes for now the problem is in Docker, or maybe VS code?
I'm totally not an expert on docker so if someone could pinpoint me into a direction for a solution....

**Launch.json settings:**
{
"version": "0.2.0",
"configurations": [
{
"name": "Your own server",
"request": "launch",
"type": "al",
"environmentType": "OnPrem",
"server": "http://BC19",
"serverInstance": "BC",
"authentication": "UserPassword",
"startupObjectId": 22,
"startupObjectType": "Page",
"breakOnError": true,
"launchBrowser": true,
"enableLongRunningSqlStatements": true,
"enableSqlInformationDebugger": true,
"tenant": "default",
"schemaUpdateMode": "Synchronize"
}
]
}

**Comment by freddydk** [comment]
Publishing a port from a container means that the port is published on the host (where docker is running) and thus reachable from other machines in the network. It doesn't sound like you need that. If VS Code is on the same machine as docker is running (the host), then this should not be necessary.

What is the output in VSCode?

You could try to use http://bc19 (same casing as the container) in launch.json
You could try to remove the "environmentType": "Onprem" from launch.json
You could also try to add "port": 7049 to your launch json

**Comment by freddydk** [comment]
Cleaning up after docker can be done with the tool described in this blog post: https://freddysblog.com/2018/12/11/clean-up-after-yourself-docker-your-mom-isnt-here/

Not sure what the problem can be - I haven't heard about this before.
Did you try to disable defender and antivirus programs?

You could also try to add -usessl and -installCertificateOnHost on the New-BcContainer to run https and install the cert on the host (then use https://bc19 in launch)

**Comment by HansDutting** [comment]
Hi Freddy,

Thanks for your help, but it is, definitely for sure now, a (domain) firewall problem.
Had another SysAdmin checking my policies on my laptop, should be fine according to them.
I let him shutdown ALL firewalls on my machine including domain firewall.
That did the trick, i'm able to download symbols again.

They opened port 7045 to 7049 in the policy. 
My collegue abroad was able to get into the containers again except me.
Its still not clear which rule needs to be applied extra for my situation, I think.
Tomorrow they need to investigate and solve that in my policy/profile. 
If it's clear which modifications they need to do in the domain firewall, I will close this issue.

Gr,
Hans D.

**Comment by HansDutting** [comment]
Domain firewall was the problem. (or the sysadmin who closes these ports without consult :) )
All necessary ports need to be defined there.
