### ISSUE TITLE
Using a remote share from a navison container

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#234]
Up until now i've used -v to map local directories to a docker defined volume.
But I would like to use a remote share instead of a local directory on the host.
I plan to install the docker containers on a diferent host, separate from where all navison development is done.
So I need the container to access a share were my code is.
I can create a mapping inside the container like below, that is accessible for all navison commands inside the container.

ping server-ip
$net = New-Object -ComObject WScript.Network
$net.MapNetworkDrive(“H:”, “\server-ip\some-path”, $false, “username”, “password”)

This was the only solution i've seen for Docker on Windows. Most solutions relate to Linux installations.

I would like to know if you have any experience with using a remote share from a navison docker container, 
or if you have any objections or advice on using this solution. 
Do you have any intensions on implementing a solution to support remote shares?

**Comment by freddydk** [comment]
I have no plans on supporting remote shares with containers, that would be something you would have to add yourself.
I typically send a url to a .zip file to the container and then extract that inside the container when i have to transfer data into the container.
