### ISSUE TITLE
Publish-BcContainerApp with switch "-upgrade" => error when previous version in not present

### ISSUE THREAD

**Issue by ThierryPermentier** [microsoft/navcontainerhelper#2340]
When you specify the switch "-upgrade", an error is throw when a previous version of the extension is not installed/present. When looking into the script, the switch "$upgrade" is checked and modified several times. Which is great! 

Would it be possible to add a previous-version-check as well?

$installedAppInfo = Get-BcContainerAppInfo -containerName $ContainerName -installedOnly | ?{($_.Name -eq $extensionName)}
if ($installedAppInfo -lt $currentVersionOfApp) { => ok to upgrade } else { nok to upgrade => install }

**Comment by freddydk** [comment]
I think this is fixed in the preview version, could you check?

**Comment by ThierryPermentier** [comment]
With command 'Install-Module BcContainerHelper -AllowClobber -Force -AllowPrerelease' I get version 3.0.3. But in the code of function "Publish-BcContainerApp" I cannot find this test.

**Comment by freddydk** [comment]
If you specify -install and -upgrade - then it should install or upgrade.
Specifying -install only will install and fail if it is already installed.
Specifying -upgrade only will upgrade and fail if it isn't already installed.

Partly this code: https://github.com/microsoft/navcontainerhelper/blob/e19529f6d67f18fd263378448a84eefc8706261f/AppHandling/Publish-NavContainerApp.ps1#L329

**Comment by ThierryPermentier** [comment]
BcContainerHelper version 3.0.3-preview553

Code is like this (not the latest version I suppose?)

```
if($upgrade -and $install){
    $navAppInfoFromDb = Get-NAVAppInfo -ServerInstance $ServerInstance -Publisher $appPublisher -Name $appName -Version $appVersion -Tenant $tenant -TenantSpecificProperties
    if($navAppInfoFromDb.ExtensionDataVersion -eq  $navAppInfoFromDb.Version){
        $upgrade = $false
    } else {
        $install = $false
    }
}
```

**Comment by freddydk** [comment]
Yes, that is the latest - if you specify both switches it should upgrade and install.
Did you specify both switches?

**Comment by ThierryPermentier** [comment]
Yes I did, but the code is not the same as in the link you provided.

Code from BcContainerHelper version 3.0.3-preview553

```
if($upgrade -and $install){
    $navAppInfoFromDb = Get-NAVAppInfo -ServerInstance $ServerInstance -Publisher $appPublisher -Name $appName -Version $appVersion -Tenant $tenant -TenantSpecificProperties
    if($navAppInfoFromDb.ExtensionDataVersion -eq  $navAppInfoFromDb.Version){
        $upgrade = $false
    } else {
        $install = $false
    }
}
```
Code from the link:

```
if($upgrade -and $install){
    $navAppInfoFromDb = Get-NAVAppInfo -ServerInstance $ServerInstance -Publisher $appPublisher -Name $appName -Version $appVersion -Tenant $tenant -TenantSpecificProperties
    if($null -eq $navAppInfoFromDb.ExtensionDataVersion -or $navAppInfoFromDb.ExtensionDataVersion -eq  $navAppInfoFromDb.Version){
        $upgrade = $false
    } else {
        $install = $false
    }
}
```

**Comment by freddydk** [comment]
Ahh - will be included in the next preview then - maybe the last build failed.
Will check

**Comment by freddydk** [comment]
The new version should have shipped as preview now
That should work - sorry for the misunderstanding

**Comment by ThierryPermentier** [comment]
No problem and thank you!
