### ISSUE TITLE
Running tests OnPrem/Sandbox container

### ISSUE THREAD

**Issue by ThierryPermentier** [microsoft/navcontainerhelper#2346]
Running tests using "Run-TestsInNavContainer" on a OnPrem container runs just fine. Running the same tests in a "Sandbox" container will fail. Powershell scripts are the same, the only thing that we change is the switch "type" from "OnPrem" to "Sandbox" to get the artifacturl. Do we need another approach to be able to run tests in a Sandbox container?

![image](https://user-images.githubusercontent.com/50203993/157862434-01b526d4-0c87-478e-a7cc-d202527f8590.png)

**Comment by freddydk** [comment]
I guess the error you should be looking at is the error dialog.
Company name is different in sandbox containers - so maybe that is the problem.
Else - I would need to get much more info in order to give any kind of help
