### ISSUE TITLE
Using -ClientServicePort on New-NavContainer command fails

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#235]
Up until now I've used AdditionalParameters to map the navision ports. 
For instance I mapped the client port like this "-p 7481:7046", but was unable to connect an remote RTC client to the nav-container this way.
So now I'm switching to the -ClientServicePort parameter, but that doesn't seem to work either (navcontainerhelper 3.1.2)

When using the below code, the port isn't correctly setup.
when checking the portsettings with docker container ls the ports still use the default settings:'
80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 8080/tcp
When debugging the New-NavContainer command, the ClientServicesPort seems to be passed correctly.
also adding -DeveloperServicesPort 4782 doesn't seem to do anything

$navCredential = Convert-AccountToSecureCredentials `
    -accountName 'admin' `
    -secretWord 'Password0'

New-NavContainer -containerName 'TestContainer' `
    -imageName 'bcinsider.azurecr.io/bcsandbox-master' `
    -licenseFile 'C:\Users\michel\Foodware\Licenses\5164953 NAV365 on Premises.flf' `
    -Credential $navCredential `
    -auth 'NavUserPassword' `
    -shortcuts 'Desktop' `
    -includeCSide `
    -updateHosts `
    -accept_eula `
    -restart always `
    -doNotExportObjectsToText `
    -ClientServicesPort 7481

**Comment by freddydk** [comment]
Specifying -ClientServicesPort and -DeveloperservicesPort will reconfigure the service tier inside the container to listen on a different port - both works for me here.
It will not expose ports nor map ports from the container - you have to do that manually.
NavContainerHelper doesn't really go into the area of networking and doesn't know whether you are using transparent networking or NAT networking.
So - if people decide to go beyond standard ports, they will have to know a thing or two about docker networking.

**Comment by mheijkant** [comment]
Got it working.
It was unclear to me which port to map, if it was the original 7046 port or the clientserviceport 7481.
So it works when I add -clientserviceport 7481 and use -AdditionalParameter to add "-p 7481:7481" to map to a public port.
