### ISSUE TITLE
permission issue to set up email when running test via Run-TestsInBcContainer

### ISSUE THREAD

**Issue by mik67** [microsoft/navcontainerhelper#2354]
**Describe the issue**
test procedure includes code creating Test Email Account (using "Connector Mock" Codeunit).
- while running test manually at BC, all test procedures reports success
- while running test via powershell script, getting: failure message="Your user account does not give you permission to set up email. Please contact your administrator."
- in both cases I am using the same credentials

**Scripts used to run the test and cause the issue**
Run-TestsInBcContainer `
    -companyName $companyName `
    -containerName $containerName `
    -extensionId $TESTAppId `
    -credential $credential `
    -detailed 

**procedure causing the issue**
    procedure SetTestEmailAcc()
    var
        EmailAccount: Record "Email Account";
        ConnectorMock: Codeunit "Connector Mock";
        EmailAccounts: TestPage "Email Accounts";
    begin
        ConnectorMock.Initialize();
        ConnectorMock.AddAccount(EmailAccount);
        EmailAccounts.OpenView();
        EmailAccounts.GoToRecord(EmailAccount);
        EmailAccounts.MakeDefault.Invoke();
        EmailAccounts.Close();
    end;
	
**User Account info**
UserPermissionSetID: SUPER
Scope: System

Thank you,
Milos

**Comment by freddydk** [comment]
Sorry for the delay.
Could you share a repro script and the output from that.
