### ISSUE TITLE
Use of web services from the upcoming version BC 20

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/navcontainerhelper#2361]
**Describe the issue**
We have created a daily Insider Container with version 20 and wanted to test our web services against it. There have been some changes here. Among other things, authentication has been significantly strengthened. As far as I remember Basic Authentication has been completely removed.

But this currently leads to a problem. Until now, we could always log in to any published container web service with the user name and password. This does not work anymore (see picture).

How is it possible in the future with the BCContainerHelper to share the container web services with "username + password" authentication? Is this not possible anymore, is there a workaround? I ask for support.

**Scripts used to create container and cause the issue**
```
$containerName = 'Test-Container'

$securePassword = ConvertTo-SecureString -String "123frewedf544jh76" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "test", $securePassword

New-BCContainer -doNotCheckHealth `
                -updateHosts `
                -artifactUrl (Get-BCArtifactUrl -country de-select nextmajor -sasToken $sasToken) `
                -containerName $containerName `
                -auth "UserPassword" `
                -Credential $credential `
                -includeTestToolkit `
                -includeTestFrameworkOnly `
                -doNotUseRuntimePackages `
                -enableTaskScheduler:$false `
                -accept_eula `
                -accept_outdated `
                -shortcuts None
```

**Screenshots**
![image](https://user-images.githubusercontent.com/22373356/159502712-1776ac7d-b826-4432-a0d8-be3443f2a1f7.png)

**Comment by freddydk** [comment]
You could try to use -runsandboxasonprem on your new-bccontainer to see if that changes anything
