### ISSUE TITLE
Run-TestsInBcContainer fails with certificate validation error

### ISSUE THREAD

**Issue by phenno1** [microsoft/navcontainerhelper#2364]
**Describe the issue**
When executing Run-TestsInBcContainer or Get-TestsFromBcContainer in docker container created with traefik option using self-signed certificate an error is received stating: "CommunicationError : An error occurred while sending the request". 

**Scripts used to create container and cause the issue**
```
New-BCContainer -accept_eula -accept_outdated -assignPremiumPlan -doNotExportObjectsToText -useTraefik -enableTaskScheduler -includeAL -licenseFile **** -updateHosts -TimeZoneId "Central European Standard Time" -PublicDnsName ***** -auth NavUserPassword -shortcuts None -doNotCheckHealth -imageName **** -containerName ****

Run-TestsInBcContainer **** -credential (Get-Credential)
```

**Full output of scripts**
```
Run-TestsInBcContainer **** -credential (Get-Credential)

WARNING: TaskScheduler is running in the container, this can lead to test failures. Specify -EnableTaskScheduler:$false to disable Task Scheduler.
Connecting to https://****/****/cs?tenant=default
CommunicationError : An error occurred while sending the request.
at <ScriptBlock>, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 110
at AwaitState, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 239
at OpenSession, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 217
at Initialize, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 78
at ClientContext, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 45
at New-ClientContext, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 59
at AwaitState, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 251
at OpenSession, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 217
at Initialize, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 78
at ClientContext, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 45
at New-ClientContext, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 59
ClientSession State is Uninitialized (Wait time 10 seconds)
at AwaitState, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 251
at OpenSession, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 217
at Initialize, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 78
at ClientContext, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\ClientContext.ps1: line 45
at New-ClientContext, C:\programdata\navcontainerhelper\Extensions\****\PsTestTool\PsTestFunctions.ps1: line 40
at <ScriptBlock>, <No file>: line 59
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.3\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 43
at Run-TestsInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.3\AppHandling\Run-TestsInNavContainer.ps1: line 360
at <ScriptBlock>, <No file>: line 1
Run-TestsInBcContainer Telemetry Correlation Id: ****
ClientSession State is Uninitialized (Wait time 10 seconds)
    + CategoryInfo          : OperationStopped: (ClientSession S...ime 10 seconds):String) [], RuntimeException
    + FullyQualifiedErrorId : ClientSession State is Uninitialized (Wait time 10 seconds)
```

**Additional context**
We have tried several authentication options, and used -installcertificateonhost with no difference in results. After debugging and manual scripts modifications we got the inner exception of the error stating: "Could not establish trust relationship for the SSL/TLS" and "The remote certificate is invalid according to the validation procedure.". 

![image](https://user-images.githubusercontent.com/47591999/159646170-906743a8-738a-4b1c-9c88-9d3e29fa959a.png)

After that information we manually imported our self-signed certificate to the localmachine root repository inside docker container after which mentioned scripts executed properly.

We use centralized docker server on Windows 2019, no hyperv
BcContainerHelper version 3.0.3

**Comment by freddydk** [comment]
I will add the certificate install to the generic image.
It was there in an earlier version of SetupCertificate.ps1, but was removed when changing the way the certificate was created, because I didn't think it was needed.
Apparently it was.

**Comment by freddydk** [comment]
I just re-added the line, you can try to add

```
-myscripts @( "https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/SetupCertificate.ps1" )
```

to your container generation - this will override SetupCertificate.ps1 with the latest version.

**Comment by freddydk** [comment]
@phenno1 - could you please verify whether this solves the problem, thinking more about the issue, I don't think it does.

How is your traefik container created? - you specify a certificate you have created yourself?
Do you specify forceHttpWithTraefik?

in other words, Is the BC Container created with http protocol and traefik is handling all the ssl stuff?

**Comment by freddydk** [comment]
You could try to insert a line here:

https://github.com/microsoft/navcontainerhelper/blob/35b31318c5b2adcb3a8e5abaf7416b6ffaa6df0d/AppHandling/Run-TestsInNavContainer.ps1#L382

with

$disableSslVerification = $true

to see whether the problem is that the container is running http and traefik is adding https with a self-signed certificate.

**Comment by phenno1** [comment]
Dear Freddy, 
We are on it at this moment. 

Regarding the traefik, we have created self-signed certificate and put in the traefik folder, referenced by traefik.toml file. 
BC Container is created with "-useTraefik". 

We will try to set $disableSslVerification manually to false in script.

**Comment by freddydk** [comment]
You need to set it to true (in order to disable verification)
The container doesn't know the certificate used by traefik, which is why it should not validate it.
What I would like to see are the last lines of the container generation with web client links before and after traefik.

**Comment by phenno1** [comment]
Freddy, 

we can confirm that with included script **it does not work** (as you commented that it will not work).
`-myscripts @( "https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/SetupCertificate.ps1" )`

Furthermore, we can confirm that with $disableSslVerification set to True on line 382 of Run-TestsInNavContainer **it works**.

**Comment by freddydk** [comment]
If you can provide me with the full printout of the container generation (on email) to freddyk at microsoft dot com - then I will know how to fix this.

Thanks

**Comment by phenno1** [comment]
Freddy, 

which version of container generation log should we send you? The original one (for which run-tests do not work afterwards), or one with custom -myscripts included, or one with $disableSslVerification used?

**Comment by phenno1** [comment]
Freddy, 

I have sent you an email with original scripts, 3.0.3. version.

**Comment by freddydk** [comment]
Thanks - the problem is indeed -forceHttpWithTraefik - I will fix Run-Tests etc. to cope with this case, thanks.

**Comment by phenno1** [comment]
👍 

Thanks!

**Comment by phenno1** [comment]
@freddydk, 

we tested new version 3.0.5 and it works with no additional code from us so, as far as I'm concerned this issues is now resolved and can be closed.

Thank you very much!
