### ISSUE TITLE
Run-ALValidation doesn't ignore pragmas

### ISSUE THREAD

**Issue by waldo1001** [microsoft/navcontainerhelper#2365]
**Describe the issue**
When I do a Run-ALValidation, the validation succeeds, while it doesn't succeed online.

Offline:
![image](https://user-images.githubusercontent.com/12088142/159660449-eddb775a-8b34-4881-9435-d27d1b93084e.png)

Online:
![image](https://user-images.githubusercontent.com/12088142/159660508-a8a0b8ac-3a75-4b1f-971b-bd7dc59f9ee7.png)

The reason for this is a pragma:
![image](https://user-images.githubusercontent.com/12088142/159660573-0acae351-333e-4e5a-b914-7a04269e7bf3.png)

So it's totally valid that id fails online, but shouldn't it fail when running it with BcContainerHelper as well?  (latest version)

**Comment by waldo1001** [comment]
Link to Yammer post: https://www.yammer.com/dynamicsnavdev/threads/1661749269020672

**Comment by freddydk** [comment]
This requires a change in ALC (a new parameter), which hopefully will be available shortly.
After that, I will add the parameter to ContainerHelper.

**Comment by waldo1001** [comment]
> This requires a change in ALC (a new parameter), which hopefully will be available shortly. After that, I will add the parameter to ContainerHelper.

Ok, makes sense :-)

**Comment by freddydk** [comment]
Shipped in 3.0.5
