### ISSUE TITLE
New Image Creation doesn't work after Windows Update

### ISSUE THREAD

**Issue by pzentner** [microsoft/navcontainerhelper#2367]
**Describe the issue**
When creating containers with process isolation on Windows 11 build 22000.556, you are going to run into errors. Similar to other times when there were OS updates, it seems that the issue is that we don't have the base images yet. So, I am trying to run it in hyperv isolation (which fixes the issue), but there is an issue in the BcContainerHelper that switches "isolation" back to "process", even though "hyperv" is defined. 

**Scripts used to create container and cause the issue**
Any variation of New-BcContainer -isolation hyperv

Issue in New-NavImage.ps1 - row 372:
The containerOsVersion picked has a lower version than the hostOsVersion, so it's setting it back to process isolation and doesn't only do that, if you did not define $isolation.

I am not sure, if this already is addressed in #2358, but I wanted to make sure that you know about it.

**Comment by TheDoubleH** [comment]
@pzentner  -  Look at #2360 - The preview version of BcContainerHelper _should_ resolve that issue for You.

(I had the same)

**Comment by freddydk** [comment]
thanks @TheDoubleH - this was indeed an error, which is fixed in the latest preview
