### ISSUE TITLE
Drop outdated description from Install-BcAppFromAppSource

### ISSUE THREAD

**Issue by TrippyZ** [microsoft/navcontainerhelper#2368]
Line 6 still refers to the old implement from before you moved to the API calls.

Please delete line 6 for improved clarity.

https://github.com/microsoft/navcontainerhelper/blob/6f8e7c2a3709b1e96b639b9db6364d446e3244a2/BcSaaS/Install-BcAppFromAppSource.ps1#L6

**Comment by freddydk** [comment]
Will do, thanks.
