### ISSUE TITLE
CleanUp Azure Applications after Remove-BcContainer

### ISSUE THREAD

**Issue by pri-kise** [microsoft/navcontainerhelper#2370]
**Describe the issue**
If I create a docker with Aad, there will be several azure app registrations that I created especially for that specific docker environment.
Now when the docker is removed the app registrations are still existing in our azure tenant.

Is there some easy way to cleanup the azure environment after I deleted the BcContainer?
Is there already a cmdlt that handles this cleanup steps?

**Comment by freddydk** [comment]
I do not have a specific Cmdlet, which cleans up the aad apps created.
Inside Create-AadAppsForBC, this command is used to remove apps if they already exists:

```
Get-AzureADMSApplication -All $true | Where-Object { $_.IdentifierUris -contains $appIdUri } | ForEach-Object { Remove-AzureADMSApplication -ObjectId $_.Id }
```
