### ISSUE TITLE
run bccontainerhelper without admin rights

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#2378]
**Describe the issue**
Going along with my company has proven that IT can take a complete development & service team down just by saying: _"you are no longer granted administrator rights on your dev machines. way to dangerous after 20 years of doing so! As an alternative we give you rights when ever you need them!_ " (BeyondTrust enters the tray bar: "hello! I'm your new enemy - and I'm here to stay - forever! *evillaugh*).

This might turn into a nightmare (in fact it did) - but wait! FreddyDK was thinking ahead and we have Check-permission -fix...that sorted out quite some issues. And we can run VS Code + PowerShell + AL all without being admin!

Almost...we are not there yet :) Our latest observation circles around the ssl certificate handling! Of course we run container with SSL and of course we have the switch -installCertificateOnHost turned on ...which in fact fails at this line:

`Import-Certificate -FilePath $certPath -CertStoreLocation "cert:\localMachine\Root"
`

now I do know that the navcontainerhelper scripts have some sort if "awareness" if they run as admin or not (at least there is a nice message in the logs about it!). So my request would be : instead of failing the script (I mean it still should try it) the statement could use some ifs and elses such that it can tell: "Poor little developer! You are not an administrator. Installing the certificate in the Root store is not possible. Please take care of this manually. Look, in the logs I have the download link for you. Go do what is needed."

This would help us, but also the actual script to continue running, as it fail hard and misses further things it should do after that step.

Hope this is enough for you to have a look ( what a frustrating week). If not let me know if you need more :) 

MvH
Kristof

**Screenshots**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/23500845/160854368-0ef8b31f-2993-4465-b60c-ee0bb0106535.png)

**Comment by freddydk** [comment]
bug/enhancement - will fix this and print out a nice message that this wasn't possible.

**Comment by KristofKlein** [comment]
Just curious - I am far away from understanding the consequences of being no administrator -but don't you think there could be a possibility for your Check-Pemission -fix script to also handle the access to "cert:\localMachine\Root" ?

**Comment by KristofKlein** [comment]
maybe an alternative Store could also work? (if even exists) like cert:\CurrentUser\Root ?! Not sure if VS Code would be happy enough with this or does it only work with localMachine\Root?!

**Comment by freddydk** [comment]
good idea - maybe store the cert in personal is possible - will investigate after Directions.

**Comment by KristofKlein** [comment]
I think you don't want to have something like this in that script?! 
`Start-Process Powershell -Verb runAs -ArgumentList "-command & {Import-certificate ...}" -Wait -PassThru` (if someone would have disabled the confirm prompts fo elvated sessions it wouldn't even disturb the process, I think). 

Just Curious: Is it VS Code or the AL extension that can not use the users store? Or even some more fancy windows logic itself? Quite a rabbit hole this certificate stores... and apperently using localmachine/root is too easy :D

**Comment by freddydk** [comment]
I guess we could add that if running as non-admin
After all - until recently it just failed - so I assume that most people are running as admin or not importing the cert.
All pipelines will be running elevated.

**Comment by KristofKlein** [comment]
Well if it is only me that has this issue I would love to get that feature in...Unfortunately we are no longer the same as "most of the people". Never had an issue with this so far, but now it bits my butt :D

**Comment by freddydk** [comment]
Will be in a pre-release later today

**Comment by KristofKlein** [comment]
Awesome! thank you so much!

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 3.0.11
