### ISSUE TITLE
Publish-PerTenantExtensionApps: Invoke-WebRequest : The remote server returned an error (400) Bad Request. 

### ISSUE THREAD

**Issue by IesMeulmeester** [microsoft/navcontainerhelper#2379]
As part of our release pipeline I am using Publish-PerTenantExtensionApps to publish the new version of the PTE. But the pubishing ends with error:
```
Invoke-WebRequest : The remote server returned an error: (400) Bad Request.
```
There is no any info what's wrong or why we get a Bad Request error on line 83. See attached printscreen:

![error1](https://user-images.githubusercontent.com/2750351/161046508-0b37de21-626f-4bc3-8b65-769c3d92eee9.png)

This line in script: Publish-PerTenantExtensionApps.ps1 will caused the error:
```
$getExtensions = Invoke-WebRequest -Headers $authHeaders -Method Get -Uri "$automationApiUrl/companies($companyId)/extensions" -UseBasicParsing
```

I have tried the URL to get the extensions in POSTMAN (with OAuth2 authentication) and than it works perfectly and return a json array with the extension data of the tenant.

I also have tried this in POWERSHELL  and then something strange happen... When I use the url from the script it fails with a Bad Request error:
```
$getExtensions = Invoke-WebRequest -Headers $authHeaders -Method Get -Uri "https://api.businesscentral.dynamics.com/v2.0/Sandbox_Qmaze/api/microsoft/automation/v1.0/companies(fbd2d0c0-f6f8-eb11-a1de-000d3ac280dd)/extensions" -UseBasicParsing
```
But when I do the same with the url without /extension it works and return 200/the company informatie (or companies)
```
$getExtensions = Invoke-WebRequest -Headers $authHeaders -Method Get -Uri "https://api.businesscentral.dynamics.com/v2.0/$environmentName/api/microsoft/automation/v1.0/companies($companyId)" -UseBasicParsing
```

Version of BcContainerHelper version 3.0.4
The user has Admin access to the tenant and has Superuser permissions (and for testing I also added D365 Automation and D365 Extension Mgt permission sets)

The strange thing is we run this script by several customers, but by only one it fails and give the above error.

**Comment by freddydk** [comment]
the fix for this seems to be the same as for #2371

**Comment by IesMeulmeester** [comment]
I already found the issue Freddy, unfortunately I use the wrong admin user. The user which I use is Global Admin in the tenant but hasn't a Business Central license.

The only strange thing is that the webrequest return a 500 Bad Request instead of a license error which is much clearer to reproduce the problem!

**Comment by freddydk** [comment]
I actually might be able to find a better error message (did that in another case) - will check that out.
Lets leave this open for that.

**Comment by freddydk** [comment]
you can try to grab the change I just checked in and test with the wrong user again and see what error message you get now
You have to manually download the file from my branch (or grab the change) and apply - I haven't checked into main yet.

**Comment by IesMeulmeester** [comment]
I have tested the change Freddy, it looks good! With the wrong account I get the following (much clearer) error message: 
```
The remote server returned an error: (400) Bad Request. {"error":{"code":"Application_DialogException","message":"You do not have the required permissions to install the selected app. 
Contact your Partner or system administrator to install the app or assign you permissions. 
```

**Comment by HazardMK** [comment]
@IesMeulmeester how did you resolved the issue? I am Global Admin and have a BC license assigned in the tenant.
