### ISSUE TITLE
Adding SynchronizeSchemaChanges parametar to Import-ObjectsToNavContainer

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/navcontainerhelper#238]
Hi,

Can you add optional **SynchronizeSchemaChanges** parameter (yes, no, force) to function **Import-ObjectsToNavContainer**? It can default to Force.

There seems to be an issue if we import large fob where we get an error during import:

````
The objects from the .fob file were imported, but they contain schema changes that cannot be synchronized to the database with the Microsoft Dynamics 365 Business Central 
Server instance.

...

The supplied field number '50000' cannot be found in the 'Gen. Journal Line' table.

````

This happens event though fob is valid and all references are there, and it seems like sync happens before everything is imported from fob file in the first place. 

The problem does not exist if the import is done without synchronizing schema at the same time (with SynchronizeSchemaChanges set to No). Synchronizing schema can be done after in separate function call or during compile.

**Comment by freddydk** [comment]
This is included in 0.4.0.1 and later versions
