### ISSUE TITLE
New-BCContainer gives error Test-Path : Illegal characters in path.

### ISSUE THREAD

**Issue by LejNaveksa** [microsoft/navcontainerhelper#2380]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**

Trying to download new DockerImage.

**Scripts used to create container and cause the issue**
```
Install-Module BcContainerHelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true
$accept_out  = $true

$containername = 'NAVEKSAnew'
$artifactUrl = Get-BCArtifactUrl -country dk -type OnPrem -select Latest

$appbacpacuri = ''
$tenantbacpacuri = ''
$bccontainerhelperconfig.bcartifactscachefolder = 'D:\bcartifacts.cache'

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated: $accept_out `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -auth Windows `
                 -alwaysPull `
                 -includeAL `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -additionalParameters $additionalParameters `
                 -licenseFile 'C:\Naveksa\5692763.flf'

Setup-BCContainerTestUsers -containerName $containername -password $credential.Password
```

**Full output of scripts**
```

PS C:\demo> C:\Users\vmadmin\Downloads\CreateBCSandbox_DK_Artefact.ps1
BcContainerHelper is version 3.0.4
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Download-Artifacts Telemetry Correlation Id: f51ad4a9-af41-4263-984e-844cb5780494
New-BCContainer Telemetry Correlation Id: b509cb67-4467-488d-8e5a-3bfd49b30195
Test-Path : Illegal characters in path.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.4\Misc\Download-Artifacts.ps1:43 char:15
+     if (-not (Test-Path $basePath)) {
+               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (D:\cartifacts.cache:String) [Test-Path], ArgumentException
    + FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.TestPathCommand```

**Screenshots**

**Additional context**
- does it happen all the time?
YES
- did it use to work?
YES

**Comment by freddydk** [comment]
You have a space after the colon in this line 

```
                 -accept_outdated: $accept_out `
```
That is likely causing the mess of parameters

**Comment by LejNaveksa** [comment]
Sorry. Didn't solve it.

**Script:**

Install-Module BcContainerHelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true
$accept_out  = $true

$containername = 'NAVEKSAnew'
#$artifactUrl = Get-BCArtifactUrl -version 17.0 -country dk -type OnPrem
$artifactUrl = Get-BCArtifactUrl -country dk -type OnPrem -select Latest

$appbacpacuri = ''
$tenantbacpacuri = ''
$bccontainerhelperconfig.bcartifactscachefolder = 'D:\bcartifacts.cache'

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-BCContainer -accept_eula:$accept_eula `
                 -accept_outdated:$accept_out `
                 -containername $containername `
                 -artifactUrl $artifactUrl `
                 -auth Windows `
                 -alwaysPull `
                 -includeAL `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -additionalParameters $additionalParameters `
                 -licenseFile 'C:\Naveksa\5692763.flf'

Setup-BCContainerTestUsers -containerName $containername -password $credential.Password

**Result:**

PS C:\demo> C:\Users\vmadmin\Downloads\CreateBCSandbox_DK_Artefact.ps1
Setting bcartifactsCacheFolder = D:cartifacts.cache
BcContainerHelper version 3.0.4
BcContainerHelper emits usage statistics telemetry to Microsoft
BcContainerHelper is version 3.0.4
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Download-Artifacts Telemetry Correlation Id: 6a2546fa-9315-4755-bc04-fd21992cd20e
New-BCContainer Telemetry Correlation Id: 33f5114d-e8ce-4190-88eb-db8fe7e1969f
Test-Path : Illegal characters in path.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.4\Misc\Download-Artifacts.ps1:43 char:15
+     if (-not (Test-Path $basePath)) {
+               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (D:\cartifacts.cache:String) [Test-Path], ArgumentException
    + FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.TestPathCommand

**Comment by freddydk** [comment]
Please copy/paste your bccontainerhelper.config.json here - it looks like you have an error in that.

**Comment by LejNaveksa** [comment]
Great :-)
Changing the c:\programdata\bccontainerhelper\bccontainerhelper.config.json file from
"bcartifactsCacheFolder": "D:\bcartifacts.cache" 
to
"bcartifactsCacheFolder": "D:\\bcartifacts.cache"
solved the issue.

Thanks a lot for quick response and support :-)

**Comment by LejNaveksa** [comment]
Well, what I meant to write was of course changing the value to
"bcartifactsCacheFolder": "D:\\bcartifacts.cache"

**Comment by LejNaveksa** [comment]
with a double backslash
