### ISSUE TITLE
Get-BcArtifactUrl does not return value

### ISSUE THREAD

**Issue by dkorinets** [microsoft/navcontainerhelper#2384]
Hello Freddy, 

The pipeline is failing due to the 
$artifactUrl = Get-BCArtifactUrl -country us -select nextmajor -sasToken $sasToken - returns an empty value

From debug session what I found -->
![image](https://user-images.githubusercontent.com/31474116/161520053-b289f833-6280-4c72-a83e-abe1ff83b8b0.png)
![image](https://user-images.githubusercontent.com/31474116/161520078-c2c29eb1-e14f-47d0-8d46-ee548fbf5688.png)

Seems like version 21.0 - still does not exist. 
Please advise.

**Comment by freddydk** [comment]
Next Major and Next Minor are broken right now, the team is looking to create a fix asap.

**Comment by BW-PA** [comment]
Was going to ask the same.  Following this for updates 👍🏻

**Comment by freddydk** [comment]
Just heard that the bug has been fixed and a new next major should become available soon.
The fix should also make it to next minor asap.

**Comment by freddydk** [comment]
Next Major is available now.

**Comment by BW-PA** [comment]
Can confirm that my scheduled nightly builds against nextminor and nextmajor completed successfully overnight.  Thanks Freddy.

**Comment by dkorinets** [comment]
Works! Thanks for the fast solution!
