### ISSUE TITLE
[Question] How to install prerequisite apps during the creation of a new container?

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#2386]
Hi Freddy,

Not sure if this is already implemented or if was already covered in some post.

The requirement is to install a number of Apps (prerequisites) during the creation of a BC Container. 
The files of these apps are in a folder in my repository.

I know how to create a script to install apps, I'm wander if already included in New-BcContainer /  Run-AlPipeline commands.

Thank you

**Comment by xtiche** [comment]
Use installApps param for Run-AlPipeline

**Comment by eclipses** [comment]
> Use installApps param for Run-AlPipeline

Please have you used this parameter? Any example? 
If I've understood well I should hardcode the full path of the files separated by comma.

**Comment by xtiche** [comment]
i use link to .zip with all my apps

**Comment by freddydk** [comment]
you can specify a string with a comma separated list of urls or paths - or an array of urls or paths.
Every url or path can point to an app or a number of apps in a .zip file.

**Comment by eclipses** [comment]
I love the idea of the zip file, tested and it works great for me. 
The only thing I did not manage is to use a path relative to the project. The path is declared in the settings.json file.

**Comment by thomasbook** [comment]
I've tried the flowing for two dependencies, but does not work, something I'm doing wrong?

    "installApps": ["eTicket/.alpackages/Bison Technology_Bison Libary_1.0.0.34.app",
                    "eTicket/.alpackages/Rand Group_Bison Services_1.1.10.21.app"] ,

 File not found: eTicket/.alpackages/Bison Technology_Bison Libary_1.0.0.34.app eTicket/.alpackages/Rand Group_Bison Services_1.1.10.21.app

**Comment by freddydk** [comment]
Did you try to specify full path to the files?
Looks like the default directory isn't what you expect

**Comment by thomasbook** [comment]
yes if either one of them is put in then is find them, when I add both it just added them together,

    "installApps": ["eTicket/.alpackages/Bison Technology_Bison Libary_1.0.0.34.app"],                    

  Publishing C:\ProgramData\BcContainerHelper\Extensions\etickettest-ci\4cd42560-de32-42ee-967d-543d8ad44a56\Bison Technology_Bison Libary_1.0.0.34.app
  Synchronizing Bison Libary on tenant default
  Installing Bison Libary on tenant default
  App Bison Technology_Bison Libary_1.0.0.34.app successfully published

**Comment by freddydk** [comment]
Sounds like a bug, will investigate

**Comment by freddydk** [comment]
@thomasbook - what version of containerhelper are you running?
also, what config file is this, what scripts? - can you share the output of your pipeline?
Just checked - AL-Go for GitHub works fine with a setting like this.

**Comment by freddydk** [comment]
Try to change your settings file to:

```
"installApps": "eTicket/.alpackages/Bison Technology_Bison Libary_1.0.0.34.app,eTicket/.alpackages/Rand Group_Bison Services_1.1.10.21.app",
```
meaning that you use a comma separated string instead of using a json array.
I think this is the way the old CI/CD scripts needed the setting.

I do recommend having a look at https://github.com/microsoft/AL-Go (see the scenaris in the readme section) which is the replacement of the "old" CI/CD HOL.

**Comment by thomasbook** [comment]
Ok,  I've have moved to the new AL-G0,  and was able to get a hello world working.  Moved it then over to my project and see that the app are installed, but not found when compiling apps?  Found this issue on another but I have apps I'm working with.

[logs_105.zip](https://github.com/microsoft/navcontainerhelper/files/8569636/logs_105.zip)
.

**Comment by freddydk** [comment]
strange - it downloads the symbols and everything looks to be good.
I assume Web RequestBSNLIB table should be in this app: Bison Technology_Bison Libary_1.0.0.34.app ?

Any chance that you can add me as a read role to your repo - then I can have a look?

**Comment by thomasbook** [comment]
@freddydk yes the symbols are in the app: Bison Technology_Bison Libary_1.0.0.34.app for all the BSNLIB.  I'm working in give you access to the repo.

**Comment by freddydk** [comment]
I cannot see anything but the public repos in your organization.
Feel free to email me information on freddyk at microsoft dot com on what repo I am looking for

**Comment by freddydk** [comment]
Did you manage to make everything work?

**Comment by eclipses** [comment]
Yes thank you, you can close this.
