### ISSUE TITLE
[Question] How to import and apply a number of configuration packages during the creation of a new container?

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#2387]
Hi Freddy,

Not sure if this is already implemented or if was already covered in some post.

The requirement is to import and apply a number of configuration packages (*.rapidstart) during the creation of a BC Container.
The files will be stored are in a folder in my repository. 

I know how to import and apply packages after the creation of the container, I'm wander if already included in New-BcContainer / Run-AlPipeline commands a parameter to do this task during the creation of the container, expecially if the container will be reused, so that the data will be part of the backup of the database. 

Thank you

**Comment by freddydk** [comment]
To Run-AlPipeline, you can provide a scriptblock called ImportTestDataInBcContainer.
In that script, you can invoke functions to import configuration packages.
The script will get three parameters:
-containerName
-tenant
-credential
This function will be called shortly after the container has been created to import data.

**Comment by eclipses** [comment]
If I've understood correctly the code you suggested should be like this:

`$ImportTestDataInBcContainer = {
    Param([Hashtable]$parameters) 
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -Credential $parameters.credential -configPackage "C:\Users\Developer\Documents\DevOps\BC Implementation\.config\PackageLSC.DEMO.PACK.NO1.rapidstart" -packageId "1"
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -Credential $parameters.credential -configPackage "C:\Users\Developer\Documents\DevOps\BC Implementation\.config\PackageLSC.DEMO.PACK.NO2.rapidstart" -packageId "2"
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -Credential $parameters.credential -configPackage "C:\Users\Developer\Documents\DevOps\BC Implementation\.config\PackageLSC.DEMO.PACK.NO3.rapidstart" -packageId "3"
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -Credential $parameters.credential -configPackage "C:\Users\Developer\Documents\DevOps\BC Implementation\.config\PackageLSC.DEMO.PACK.NO4.rapidstart" -packageId "4"
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -Credential $parameters.credential -configPackage "C:\Users\Developer\Documents\DevOps\BC Implementation\.config\PackageLSC.DEMO.PACK.NO5.rapidstart" -packageId "5"
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -Credential $parameters.credential -configPackage "C:\Users\Developer\Documents\DevOps\BC Implementation\.config\PackageLSC.DEMO.PACK.NO6.rapidstart" -packageId "6"
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $parameters.containerName -Credential $parameters.credential -configPackage "C:\Users\Developer\Documents\DevOps\BC Implementation\.config\PackageLSC.DEMO.PACK.NO7.rapidstart" -packageId "7"
}`

Is there anything that you can do to simplify this step? Maybe just passing the folder name that contains the files or a zip file with multiple configuration files, similarly to the installApps param for Run-AlPipeline?

I'm still teesting the code, I'm avaluating to create a backup of the database to use for the creation of the container rather than importing multiple files.

**Comment by eclipses** [comment]
Unfortunately the script fails at the first configuration file importation with the following error:

"Couldn't import configuration package, error is 
The package code specified on the configuration package must be the same as the package name in the imported package."

**Comment by freddydk** [comment]
Sorry didn't see this.
Did you make this work?

Your package id might be wrong?

On whether you could simplify this, you could use the strength of PowerShell and do stuff like:

```
Get-Item -path (Join-Path $path *.rapidstart") | % { UploadImportAndApply-ConfigPackageInBcContainer @parameters -configPackage $_.FullName }
```
