### ISSUE TITLE
BCContainerHelper module fails to load; requires deleting local Modules folder

### ISSUE THREAD

**Issue by buzzwick** [microsoft/navcontainerhelper#2409]
Issue:  Build pipeline periodically fails to find/install BCContainerHelper module

**Scripts used to create container and cause the issue**
```
    - task: PowerShell@2
      displayName: Install BCContainerHelper module
      inputs:
        targetType: inline
        script: >
          Install-Module -Name BCContainerHelper  -force

```

**Full output of scripts**
```
 ##[section]Starting: Install BCContainerHelper module
 ==============================================================================
 Task         : PowerShell
 Description  : Run a PowerShell script on Linux, macOS, or Windows
 Version      : 2.200.0
 Author       : Microsoft Corporation
 Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
 ==============================================================================
 Generating script.
 ========================== Starting Command Output ===========================
 ##[command]"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent\_work\_temp\3dc857f7-d7f9-4445-8181-fe0b572cfb19.ps1'"
 PackageManagement\Install-Package : Unable to find module providers (PowerShellGet).
 At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
 + ...          $null = PackageManagement\Install-Package @PSBoundParameters
 +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], E 
    xception
     + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
  
 ##[error]PowerShell exited with code '1'.
 ##[section]Finishing: Install BCContainerHelper module
...
```

**Additional context**
I am running my build agent for now on my local laptop, and starting manually as needed. The first time a pipeline is run against a newly-started agent, the build fails because the BCContainerHelper module fails to load. 

The solution is to delete the "Modules" folder located in C:\Documents\Windows PowerShell\, as described here: 
[https://docs.microsoft.com/en-us/answers/questions/257840/powershell-unable-to-find-module-providers-powersh.html](url)

My Documents folder is included in my OneDrive scope, as described in the forum post. 

Is there a way to eliminate the need to manually delete this folder? Thanks.

**Comment by freddydk** [comment]
When setting up new VMs with https://aka.ms/getbc, I typically run this code to ensure the right PowerShellGet module is loaded.

```
if (!(Get-PackageProvider -Name NuGet -ListAvailable -ErrorAction Ignore)) {
    AddToStatus "Installing NuGet Package Provider"
    Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.208 -Force -WarningAction Ignore | Out-Null
}
if (!(Get-Module powershellget | Where-Object { $_.Version -ge [version]"2.2.5" })) {
    AddToStatus "Installing PowerShellGet 2.2.5"
    Install-Module powershellget -RequiredVersion 2.2.5 -force
    Import-Module powershellget -RequiredVersion 2.2.5
}
```

**Comment by buzzwick** [comment]
Thank you. I would love to know why it is that the presence of a Modules folder, which gets re-created anyway, prevents the importing of the PS module. I will see if I can re-create the error so I can conclusively demonstrate that this gets around it.

**Comment by freddydk** [comment]
What OS are you using where you see this problem?
I seem to recall having seen this - but haven't run into this lately

**Comment by buzzwick** [comment]
The laptop running the agent is Windows 10 Pro.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by buzzwick** [comment]
So I had to re-install Docker locally (seems to happen frequently now), and re-started my local agent. Build pipeline failed with previously cited error. I inserted your code below, just before the call to install BCContainerHelper, and got this:

##[section]Starting: Install BCContainerHelper module
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
##[command]"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent\_work\_temp\47945313-bc16-491c-9eb6-abd15be3b214.ps1'"
AddToStatus : The term 'AddToStatus' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\agent\_work\_temp\47945313-bc16-491c-9eb6-abd15be3b214.ps1:7 char:3
+   AddToStatus "Installing PowerShellGet 2.2.5"
+   ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (AddToStatus:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
##[error]PowerShell exited with code '1'.
##[section]Finishing: Install BCContainerHelper module

**Comment by freddydk** [comment]
Remove the AddToStatus lines - these are only used in the Azure VMs to add information to the status file.

**Comment by buzzwick** [comment]
Removed the AddToStatus lines; had to reinstall and rebuild Docker on the build machine anyway (apparently restarting my PC now leaves Docker in a "Failed to Stop" state from which it cannot be resuscitated). This created the conditions for the original fail error:

`[section]Starting: Install BCContainerHelper module
==============================================================================
Task         : PowerShell
Description  : Run a PowerShell script on Linux, macOS, or Windows
Version      : 2.200.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
==============================================================================
Generating script.
========================== Starting Command Output ===========================
##[command]"C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent\_work\_temp\9e1574eb-2834-4513-a780-043217a8cab6.ps1'"
PackageManagement\Install-Package : Unable to find module providers (PowerShellGet).
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], E 
   xception
    + FullyQualifiedErrorId : UnknownProviders,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 
[error]PowerShell exited with code '1'.
[section]Finishing: Install BCContainerHelper module`

Deleted the folder "C:\users\dbaldwin\<OneDrive>\Documents\Modules". Ran the script again with the your package management code still in place (absent AddToStatus calls). Build succeeds. So the code does not cause errors, but apparently does not resolve the Modules folder issue. The modules folder contained subfolders for PackageManagement and BcContainerHelper, if that helps at all. After the build it is still gone.

**Comment by freddydk** [comment]
OK.
The issue is unrelated to BcContainerHelper, but I might have a solution for you anyway.
In the new AL-Go for GitHub, I actually do not install the module from PS Gallery, but instead download, unpack and import the module for the session.

You can try out this code:

```
function Expand-7zipArchive {
    Param (
        [Parameter(Mandatory = $true)]
        [string] $Path,
        [string] $DestinationPath
    )

    $7zipPath = "$env:ProgramFiles\7-Zip\7z.exe"

    $use7zip = $false
    if (Test-Path -Path $7zipPath -PathType Leaf) {
        try {
            $use7zip = [System.Diagnostics.FileVersionInfo]::GetVersionInfo($7zipPath).FileMajorPart -ge 19
        }
        catch {
            $use7zip = $false
        }
    }

    if ($use7zip) {
        Set-Alias -Name 7z -Value $7zipPath
        $command = '7z x "{0}" -o"{1}" -aoa -r' -f $Path, $DestinationPath
        Invoke-Expression -Command $command | Out-Null
    }
    else {
        Expand-Archive -Path $Path -DestinationPath "$DestinationPath" -Force
    }
}

function InstallContainerHelper {
    Param(
        [string] $bcContainerHelperVersion = "latest"
    )

    $tempName = Join-Path $env:TEMP ([Guid]::NewGuid().ToString())
    $webclient = New-Object System.Net.WebClient
    if ($BcContainerHelperVersion -eq "dev") {
        Write-Host "Downloading BcContainerHelper developer version"
        $webclient.DownloadFile("https://github.com/microsoft/navcontainerhelper/archive/dev.zip", "$tempName.zip")
    }
    else {
        Write-Host "Downloading BcContainerHelper $BcContainerHelperVersion version"
        try {
            $webclient.DownloadFile("https://bccontainerhelper.azureedge.net/public/$($BcContainerHelperVersion).zip", "$tempName.zip")
        }
        catch {
            $webclient.DownloadFile("https://bccontainerhelper.blob.core.windows.net/public/$($BcContainerHelperVersion).zip", "$tempName.zip")        
        }
    }
    Expand-7zipArchive -Path "$tempName.zip" -DestinationPath $tempName
    Remove-Item -Path "$tempName.zip"

    $BcContainerHelperPath = (Get-Item -Path (Join-Path $tempName "*\BcContainerHelper.ps1")).FullName
    . $BcContainerHelperPath

    $tempName
}

function CleanUpContainerHelper {
    Param(
        [string] $bcContainerHelperPath = ""
    )

    if ("$bcContainerHelperPath" -ne "" -and (Test-Path $bcContainerHelperPath -PathType Container)) {
        try {
            Write-Host "Removing BcContainerHelper"
            Remove-Module BcContainerHelper
            Remove-Item $bcContainerHelperPath -Recurse -Force
        }
        catch {}
    }
}

$bcContainerHelperPath = InstallContainerHelper
try {

    # your code

}
finally {
    CleanUpContainerHelper -bcContainerHelperPath $bcContainerHelperPath
}

```

You can also modify the code as you see fit.

As you can see - all BcContainerHelper versions are published to PowerShell Gallery AND also uploaded to a storage account, from which it can be downloaded and used.

**Comment by buzzwick** [comment]
I do agree that it does not have anything to do with BcContainerHelper--rather with the Import-Module command itself.   I will set this up on a test project and try that. I can at least test the code. I will have to wait until I have the error condition first however, to see if it is resolving anything. At this point I am not clear exactly when that Modules folder gets created, or at what point its presence causes the problem. Which--if I wanted to pursue those questions, on what forum should I be posting?  Thanks!

**Comment by freddydk** [comment]
I think the problem is on Install-Module, not Import-Module.
Install-Module uses PowerShellGet and PackageManagement to get the modules and I think that is the caveat,
The above code definitely resolves the issue on loading containerhelper - as I am not using the normal modules folders, powershellget etc. - I am just loading the module from a temp folder.
The above mechanism also allows two agents to use different versions of ContainerHelper (if for some reason one set of pipelines are using insider and another isn't)
Hope it works out for you.

**Comment by buzzwick** [comment]
Thanks very much.

**Comment by buzzwick** [comment]
In the end, this seems to have resolved the problem. I found it by digging through forum posts:

`  Install-PackageProvider -Name NuGet -Force -Scope CurrentUser;`
 `  Install-Module -Name BCContainerHelper -Scope CurrentUser -force;`

Just adding the Install-PackageProvider line made that problem stop happening. Apparently the -Scope CurrentUser is essential.

Windows Real-Time Scanning is fatal to docker builds, by the way.

**Comment by freddydk** [comment]
Thanks a million for this info.
I actually got the same problem yesterday - I ended up moving the content of the user modules folder to the \program files\windowspowershell\modules folder - then I could install modules again.

**Comment by freddydk** [comment]
Nope - I just moved it

**Comment by buzzwick** [comment]
No kidding. Okay, I will keep that in mind. We moved our build agent to a dedicated machine--with no OneDrive--so maybe we have dodged that bullet. Thanks.

**Comment by DimosthenisMichalopoulos** [comment]
this seem to solve problem for me : Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted
