### ISSUE TITLE
DELETE call to REST API fails for BC 18 and 19 container, works for BC 20

### ISSUE THREAD

**Issue by tfenster** [microsoft/navcontainerhelper#2417]
**Describe the issue**
When I try to make a DELETE call to the REST API of a container with the latest BC 18 and 19 W1 release, I get a `500 Internal Server Error`. If I do the same against the latest BC 20 W1 release, it works

**Scripts used to create container and cause the issue**
First, I set up a Windows Server 2019 through aka.ms/getbc. Then I use those three calls to create the containers
```
New-BcContainer -accept_eula -accept_outdated -containerName bcserver18 -artifactUrl (Get-BCArtifactUrl -type OnPrem -country w1 -version 18) -imageName mybc -auth NavUserPassword
New-BcContainer -accept_eula -accept_outdated -containerName bcserver19 -artifactUrl (Get-BCArtifactUrl -type OnPrem -country w1 -version 19) -imageName mybc -auth NavUserPassword
New-BcContainer -accept_eula -accept_outdated -containerName bcserver20 -artifactUrl (Get-BCArtifactUrl -type OnPrem -country w1 -version 20) -imageName mybc -auth NavUserPassword
```

When the containers have started, I use the following REST calls to:
1. Check that the connection works: GET call in lines 10-12
2. Create a new item: POST call in lines 16-22
3. Get the ID of the created item in line 25
4. Get the created item to validate that it was created: GET call in lines 28-30
5. Remove the created item: DELETE call in lines 33 and 34

Of course, you need to change the variables in lines 1-6 to match your environment

```
@MyUser = admin
@MyKey = Super5ecret!
@MyServiceName = bcserver19
@MyBaseUrl = https://problem-204.westeurope.cloudapp.azure.com/{{MyServiceName}}rest
@MyAPIVersion = v2.0
@MyCompany = CRONUS International Ltd.


### GET Items
GET {{MyBaseUrl}}/api/{{MyAPIVersion}}/companies(name='{{MyCompany}}')/items
Authorization: Basic {{MyUser}} {{MyKey}}
Content-Type: application/json

### POST Item  
# @name getItemId
POST {{MyBaseUrl}}/api/{{MyAPIVersion}}/companies(name='{{MyCompany}}')/items
Authorization: Basic {{MyUser}} {{MyKey}}
Content-Type: application/json

{
    "number": "TEST00011"
}

###
@DeleteMyitemId = {{getItemId.response.body.$.[id}}

### GET Item
GET {{MyBaseUrl}}/api/{{MyAPIVersion}}/companies(name='{{MyCompany}}')/items({{DeleteMyitemId}})
Authorization: Basic {{MyUser}} {{MyKey}}
Content-Type: application/json

### DELETE Item 
DELETE {{MyBaseUrl}}/api/{{MyAPIVersion}}/companies(name='{{MyCompany}}')/items({{DeleteMyitemId}})
Authorization: Basic {{MyUser}} {{MyKey}}
```

The result of the DELETE call in the end (step 5) for BC 20 looks like this:
```
HTTP/1.1 204 No Content
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Date, Content-Length, Server, OData-Version
Date: Thu, 21 Apr 2022 11:57:24 GMT
Request-Id: a74c431c-c51b-4408-abd4-32d85dfa85bf
Server: Microsoft-HTTPAPI/2.0
Connection: close
```

For BC 19 it looks like this:
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 21 Apr 2022 11:45:24 GMT
Content-Length: 21
Content-Type: text/plain; charset=utf-8
Connection: close

Internal Server Error
```

And for BC 18 it looks like this (`@MyAPIVersion` in line 5 needs to be `v1.0` in that case):
```
HTTP/1.1 500 Internal Server Error
Date: Thu, 21 Apr 2022 11:51:25 GMT
Content-Length: 21
Content-Type: text/plain; charset=utf-8
Connection: close

Internal Server Error
```

I don't see any entries in the container event logs at that time

**Full output of scripts**

[startup bc 18.txt](https://github.com/microsoft/navcontainerhelper/files/8530824/startup.bc.18.txt)
[startup bc 19.txt](https://github.com/microsoft/navcontainerhelper/files/8530825/startup.bc.19.txt)
[startup bc 20.txt](https://github.com/microsoft/navcontainerhelper/files/8530823/startup.bc.20.txt)

**Additional context**
- does it happen all the time? Yes
- did it use to work? Not sure

I have stopped the environment again, but would be happy to give you full access if needed as it is in a dev subscription, not connected to any customer or internal data

**Comment by freddymynavdemo** [comment]
Strange
Do you know whether this is a container problem, a traefik problem or a BC problem?

**Comment by tfenster** [comment]
looking at the fact that the exact same thing works on 20 and fails on 18 and 19, that would point at a BC problem for me, but of course it could be something else. I can try without traefik if you want?

**Comment by tfenster** [comment]
I enabled debug logging in traefik and it indeed seems to be connected. Something tries to do HTTP 2, but BC 18/19 can only do 1.1. BC 20 probably supports 2, so it works. That actually reminds me of #2169, which might be a way to solve this and which I completely forgot 😒

**Comment by tfenster** [comment]
ok, validated that this is indeed the case. If anyone comes across this issue: You need to go to traefik 2 and set e.g. `traefik.http.serversTransports.eaccb611018c.disableHTTP2=true`. As this overrides the standard serversTransport, you would also need to set `traefik.http.serversTransports.eaccb611018c.insecureSkipVerify=true`. And then you need to "link" the services to the serversTransport. e.g. `traefik.http.services.eaccb611018c.loadBalancer.serversTransport=eaccb611018c@docker`

I'll add this to #2169 as soon as I can find the time
