### ISSUE TITLE
Import-NavContainerLicense error

### ISSUE THREAD

**Issue by mmenninghaus** [Microsoft/navcontainerhelper#242]
I am not able to Import the License file. Output:

`NAVDevSample> Import-NavContainerLicense -containerName navcontainer -licenseFile ".\config\License.flf"
Copy .\config\License.flf to container navcontainer (c:\run\License.flf)
Copy-Item : The parameter is incorrect
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.4.0.0\Misc\Copy-FileToNavContainer.ps1:21 char:13
+             Copy-Item -Path $localPath -Destination $containerPath -T ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.CopyItemCommand`

**Comment by richardrobberse** [comment]
Try to specify the full path instead to the license file instead of .\

**Comment by mmenninghaus** [comment]
Yes, that worked. The original Problem is, that the License file is in a shared Folder. I copied it to my Desktop and copied it from there. Thank you!

**Comment by richardrobberse** [comment]
No problem 👍
