### ISSUE TITLE
Access to the path 'C:\Run\Collation.txt' is denied.

### ISSUE THREAD

**Issue by juanbo8** [microsoft/navcontainerhelper#2422]
We have problems with docker 4.7.1 and differents version of Windows 10 and Windows 11. It's not possible to create a container. We are using next script:

$ContainerName = 'namecontainer'
$imageName = 'bc'
$artifactUrl = Get-BCArtifactUrl -country 'es' -type "Sandbox" 
$licenseFile = 'C:\License.flf'

$UserName = 'name'
$Password = ConvertTo-SecureString "pass123" -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ($UserName, $Password)

New-BCContainer -accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -assignPremiumPlan `
                 -multitenant: $false `
                 -imageName $imageName `
                 -artifactUrl $artifactUrl `
                 -licenseFile $licenseFile `
                 -accept_outdated `
                 -updateHosts -isolation hyperv `
                 -additionalParameters @("--env CustomNavSettings=EnableThreadThrottling=False,EnablePrioritizedThreadThrottling=False") #para evitar errores en debugge

**Comment by mtaanquist** [comment]
I am seeing the same error after upgrading to BcContainerHelper 3.0.6. I managed to set up a container yesterday (with real-time protection disabled) with 3.0.5.

**Comment by juanbo8** [comment]
I finally uninstalled and installed docker again and it let me create the container. Thank you!
