### ISSUE TITLE
Export-ModifiedObjectsAsDeltas fails with Could not find a part of the path.

### ISSUE THREAD

**Issue by kimnoer** [microsoft/navcontainerhelper#2423]
**Describe the issue**
When running Export-ModifiedObjectsAsDeltas it fails with following

Export-ModifiedObjectsAsDeltas -containerName ba
Export Objects with filter 'Modified=1' to C:\ProgramData\BcContainerHelper\Extensions\ba\modified\objects.txt (container path)
Split C:\ProgramData\BcContainerHelper\Extensions\ba\modified\objects.txt to C:\ProgramData\BcContainerHelper\Extensions\ba\modified (container paths)
Copy original objects to C:\ProgramData\BcContainerHelper\Extensions\ba\original for all objects that are modified (container path)
Compare modified objects with original objects in C:\ProgramData\BcContainerHelper\Extensions\ba\original and create Deltas in C:\ProgramData\BcContainerHelper\Extensions\ba\delta (container paths)
Rename new objects to .TXT
Could not find a part of the path.
at <ScriptBlock>, <No file>: line 46
at <ScriptBlock>, <No file>: line 40
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.4\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 43
at Create-MyDeltaFolder, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.4\ObjectHandling\Create-MyDeltaFolder.ps1: line 41
at Export-ModifiedObjectsAsDeltas, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.4\ObjectHandling\Export-ModifiedObjectsAsDeltas.ps1: line 88
at <ScriptBlock>, <No file>: line 1
Export-ModifiedObjectsAsDeltas Telemetry Correlation Id: 64fa0149-b496-47e0-a770-a5e67fb5734d
Could not find a part of the path.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.4\ContainerHandling\Invoke-ScriptInNavContainer.ps1:44 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find a part of the path.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find a part of the path.
 

**Scripts used to create container and cause the issue**
$version = '11.0.27667.0' # platform
$artifacturl = Get-BCArtifactUrl -type OnPrem -version $version -country dk
New-BCContainer -useBestContainerOS -accept_eula -containerName $containerName -artifactUrl $artifacturl -auth UserPassword -Credential $credential -updateHosts -alwaysPull -includeCSide -shortcuts DesktopFolder -licenseFile C:\work\License\nav2018.flf -myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/override/SelfSignedCertificateEx/SetupCertificate.ps1")

Import-ObjectsToNavContainer -containerName ba -objectsFile C:\ba.fob -SynchronizeSchemaChanges Force -ImportAction Overwrite
Export-ModifiedObjectsAsDeltas -containerName $containerName

**Full output of scripts**
BcContainerHelper is version 3.0.4
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro - 21H2
Docker Client Version is 20.10.13
Docker Server Version is 20.10.13
Removing container ba
Removing ba from container hosts file
Removing ba-* from container hosts file
Removing C:\ProgramData\BcContainerHelper\Extensions\ba
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.20348.643
10.0.20348.643: Pulling from businesscentral
Digest: sha256:6109e8021486b29fae895410629867541a0f0515bd6228a06129f61a99906445
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.643
mcr.microsoft.com/businesscentral:10.0.20348.643
Using image mcr.microsoft.com/businesscentral:10.0.20348.643
Creating Container ba
Style: onprem
Multitenant: No
Version: 11.0.27667.0
Platform: 11.0.27667.0
Generic Tag: 1.0.2.1
Container OS Version: 10.0.20348.643 (ltsc2022)
Host OS Version: 10.0.22000.613 (21H2)
Using process isolation
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\ba\my\SetupCertificate.ps1
Using license file C:\work\License\nav2018.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\ba\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupCertificate.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container ba from image mcr.microsoft.com/businesscentral:10.0.20348.643
771f0ddd5c1a9eb3a13275aad804f5642ca1b1466faed48c074b51d4dbeb42fc
Waiting for container ba to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/11.0.27667.0/dk
Using installer from C:\Run\110
Copying Platform Artifacts
c:\dl\onprem\11.0.27667.0\platform
Copying Application Artifacts
Copying Database
Copying Installers
c:\dl\onprem\11.0.27667.0\dk\Installers
Copying ConfigurationPackages
c:\dl\onprem\11.0.27667.0\dk\ConfigurationPackages
Copying TestToolKit
c:\dl\onprem\11.0.27667.0\dk\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\11.0.27667.0\dk\UpgradeToolKit
Copying Extensions
c:\dl\onprem\11.0.27667.0\dk\Extensions
Installing NAV
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Determining Database Collation
Changing Database Server Collation to Danish_Greenlandic_100_CS_AS
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\DK\RTC\RoleTailoredClient.Local.Dk.msi
Skipping C:\NAVDVD\Installers\DK\WebHelp\WebHelp.Local.Dk.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 31 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.3.23 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.3.23 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.29.80.1 in container hosts file
Starting Container
Hostname is ba
PublicDnsName is ba
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint C7F2186DE9235CE624B7BC45D6BA741397F120CC
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Container IP Address: 172.29.90.95
Container Hostname  : ba
Container Dns Name  : ba
Web Client          : http://ba/NAV/
Dev. Server         : http://ba
Dev. ServerInstance : NAV
Setting ba to 172.29.90.95 in host hosts file

Files:
http://ba:8080/ALLanguage.vsix

Container Total Physical Memory is 31.7Gb
Container Free Physical Memory is 8.1Gb

Initialization took 33 seconds
Ready for connections!
remove C:\NAVDVD
Reading CustomSettings.config from ba
Creating Desktop Shortcuts for ba
Container ba successfully created

**Additional context**
It happens all the time,

**Comment by kimnoer** [comment]
This problem also repeats it self on a BC 14 container with Convert-ModifiedObjectsToAl - exactly the same issue. I believe it is caused by the objects. But exporting as text, importing as text + compile, doesn't change any change. Same error.

Puzzling indeed.

**Comment by freddydk** [comment]
Would it be possible to send the ba.fob to me (freddyk at microsoft dot com)  for repro?

**Comment by freddydk** [comment]
I tried without - no problem

**Comment by freddydk** [comment]
please reopen with repro files if I am to investigate this, thanks
