### ISSUE TITLE
Access to the path 'C:\Run\ServiceSettings.ps1' is denied

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#2425]
I'm getting a new error, when trying to create a new container:
_Initializing...
Access to the path 'C:\Run\ServiceSettings.ps1' is denied.
at <ScriptBlock>, C:\Run\navstart.ps1: line 22
at <ScriptBlock>, C:\Run\start.ps1: line 363
at <ScriptBlock>, <No file>: line 1_

It ran fine Monday, today it fails. I'm not specifying a ServiceSettings.ps1 file. I've updated BcContainerHelper to see this was not the issue. 

```
Creating Business Central image bhit/OnPrem:14.29.47804.0-w1 from artifact URL https://bcartifacts.azureedge.net/onprem/14.29.47804.0/w1...
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.19041.1415
...
BcContainerHelper is version 3.0.6
BcContainerHelper is running as administrator
Hyper-V is Enabled
Host is Microsoft Windows 10 Pro - 21H2
Docker Client Version is 20.10.14
Docker Server Version is 20.10.14

**Comment by freddydk** [comment]
And this was also not a matter of antivirus I guess?
If possible, could I get access to a machine, where this problem repro's then I will try to find a workaround for this and other issues like this.

**Comment by epernst** [comment]
No that seems to be a different problem!

I was trying to create something to repro it, but it worked on my other machines. So I deleted the base image bhit/OnPrem:14.29.47804.0-w1 and created it again. **And then it worked!**
So maybe it was related to the Docker Desktop update I made Friday...
