### ISSUE TITLE
Create Multiple Containers

### ISSUE THREAD

**Issue by Charlottesaliba** [microsoft/navcontainerhelper#2436]
Hi,

I'm not sure this is an issue but i'm curious on how can i make it work.

Is it possible to create 2 bc containers that can be accessed from outside of the azure VM Machine at the same time?
I managed to have 2 but only 1 can be on at a time.

MY Script:

$password = ConvertTo-SecureString "****" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential ("vmadmin", $password)
$country = "gb"
$containerName = "BC20$country"
$licenseFile = 'C:\key\BC19.bclicense'
$PublicDnsName = "****.westeurope.cloudapp.azure.com"
$auth = 'UserPassword'

$artifactUrl = Get-BCArtifactUrl -type Sandbox -select Current -country $country
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -updateHosts `
    -includeAL `
    -isolation hyperv `
    -dns '8.8.8.8' `
    -PublicDnsName $PublicDnsName `
    -PublishPorts 80,443,7045,7046,7047,7048,7049,8080 `
    -myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/override/issue2434/HelperFunctions.ps1")

**Comment by freddydk** [comment]
There are several ways to do this.
One way is to use f.ex. -WebClientPort 8081 -ODataServicesPort 7148 etc - and then publish these ports as well.
My preferred way is to use traefik.
If you go https://aka.ms/getbc and say yes to traefik and add an email address for letsencrypt - then you can have as many containers as you like and traefik works as a proxy in front of them.
