### ISSUE TITLE
Access to cloudfile denied

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#2437]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Trying to create a BC14 CU4, but it fails with a reference to cloudfile

**Scripts used to create container and cause the issue**
```
$containerName = 'bc14cu4'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version '14.4' -country 'dk' -select 'Latest'
$licenseFile = 'd:\nav\infar\udvikling\bc14.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'bc14cu4' `
    -licenseFile $licenseFile `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts
```

**Full output of scripts**
```
BcContainerHelper is version 3.0.2
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro - 21H2
Docker Client Version is 20.10.14
Docker Server Version is 20.10.14
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.20348.643
Building image bc14cu4:onprem-14.4.35602.0-dk based on mcr.microsoft.com/businesscentral:10.0.20348.643 with https://bcartifacts.azureedge.net/onprem/14.4.35602.0/dk
Pulling latest image mcr.microsoft.com/businesscentral:10.0.20348.643
10.0.20348.643: Pulling from businesscentral
Digest: sha256:6109e8021486b29fae895410629867541a0f0515bd6228a06129f61a99906445
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.643
mcr.microsoft.com/businesscentral:10.0.20348.643
Generic Tag: 1.0.2.1
Container OS Version: 10.0.20348.643 (ltsc2022)
Host OS Version: 10.0.22000.613 (21H2)
Using process isolation
Using license file d:\nav\infar\udvikling\bc14.flf
Files in D:\NAVData\Artifacts\25tnouxs.4do\my:
Copying Platform Artifacts
D:\NAVData\Artifacts\onprem\14.4.35602.0\platform
Copying Database
Copying Licensefile
Copying Installers
D:\NAVData\Artifacts\onprem\14.4.35602.0\dk\Installers
Copying ConfigurationPackages
D:\NAVData\Artifacts\onprem\14.4.35602.0\dk\ConfigurationPackages
Copying TestToolKit
D:\NAVData\Artifacts\onprem\14.4.35602.0\dk\TestToolKit
Copying UpgradeToolKit
D:\NAVData\Artifacts\onprem\14.4.35602.0\dk\UpgradeToolKit
Copying Extensions
D:\NAVData\Artifacts\onprem\14.4.35602.0\dk\Extensions
D:\NAVData\Artifacts\25tnouxs.4do
Sending build context to Docker daemon  1.165GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.20348.643
 ---> 7bf65e4ad9fe
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/14.4.35602.0/dk filesOnly=False
 ---> Using cache
 ---> 82d0bb99eb62
Step 3/6 : COPY my /run/
 ---> Using cache
 ---> 35b2185a4d5e
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 6a189c34e7e1
Step 5/6 : RUN \Run\start.ps1 -installOnly
 ---> Running in 8c8d7d599cd4
Using installer from C:\Run\130
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
New-Bcimage Telemetry Correlation Id: 6f2fb1bf-67bb-4aff-982e-899ef4309db8
New-BcContainer Telemetry Correlation Id: f17a0391-810a-4823-8f0e-9d655a78fd3b
Remove-Item : Adgang til cloudfilen blev nægtet
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.2\ContainerHandling\New-NavImage.ps1:646 char:17
+ ...             Remove-Item $buildFolder -Recurse -Force -ErrorAction Sil ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand...
```

Seems to be an intermittant issue. I have received the same error previously, and then when I try again later the same script will run just fine.

**Comment by freddydk** [comment]
How does your BcContainerHelper settings look?
It looks like you placed some of the folders you are sharing with containers on a onedrive or clouddrive - and that messes up things.

**Comment by Rukkulakki** [comment]
$bcContainerHelperConfig

Name                           Value                                                                                                                                                                                   
----                           -----                                                                                                                                                                                   
genericImageName               mcr.microsoft.com/businesscentral:{0}                                                                                                                                                   
useSharedEncryptionKeys        True                                                                                                                                                                                    
TraefikImage                   traefik:v1.7-windowsservercore-1809                                                                                                                                                     
defaultNewContainerParameters  {}                                                                                                                                                                                      
timeStampServer                http://timestamp.digicert.com                                                                                                                                                           
containerHelperFolder          C:\ProgramData\BcContainerHelper                                                                                                                                                        
baseUrl                        https://businesscentral.dynamics.com                                                                                                                                                    
TreatWarningsAsErrors          {}                                                                                                                                                                                      
SendExtendedTelemetryToMicr... False                                                                                                                                                                                   
defaultContainerName           bcserver                                                                                                                                                                                
TraefikUseDnsNameAsHostName    False                                                                                                                                                                                   
DOCKER_SCAN_SUGGEST            False                                                                                                                                                                                   
apiBaseUrl                     https://api.businesscentral.dynamics.com                                                                                                                                                
ObjectIdForInternalUse         88123                                                                                                                                                                                   
useVolumeForMyFolder           False                                                                                                                                                                                   
psSessionTimeout               0                                                                                                                                                                                       
digestAlgorithm                SHA256                                                                                                                                                                                  
sandboxContainersAreMultite... True                                                                                                                                                                                    
mapCountryCode                 @{ae=w1; ar=w1; bd=w1; dz=w1; cl=w1; pr=w1; eg=w1; fo=dk; gl=dk; id=w1; ke=w1; lb=w1; lk=w1; lu=w1; ma=w1; mm=w1; mt=w1; my=w1; ng=w1; qa=w1; sa=w1; sg=w1; tn=w1; ua=w1; za=w1}        
usePsSession                   True                                                                                                                                                                                    
MicrosoftTelemetryConnectio... InstrumentationKey=5b44407e-9750-4a07-abe9-30c3b853821b;IngestionEndpoint=https://southcentralus-0.in.applicationinsights.azure.com/                                                    
hostHelperFolder               C:\ProgramData\BcContainerHelper                                                                                                                                                        
use7zipIfAvailable             True                                                                                                                                                                                    
PartnerTelemetryConnectionS...                                                                                                                                                                                         
genericImageNameFilesOnly      mcr.microsoft.com/businesscentral:{0}-filesonly                                                                                                                                         
bcartifactsCacheFolder         D:\NAVData\Artifacts

**Comment by Rukkulakki** [comment]
BcContainerHelper.config.json
{
    "bcartifactsCacheFolder":  "D:\\NAVData\\Artifacts"
}

**Comment by Rukkulakki** [comment]
The only file, to my knowledge, that is stored anywhere close to the cloud is the scriptfile itself. 
That is stored among my documents on the company OneDrive
C:\Users\Svend\OneDrive - nav2day\Dokumenter\bc14cu4.ps1

**Comment by freddydk** [comment]
The problem is not that it cannot delete the folder - the problem is that it cannot start the SQL Server in the container.
The two things you can try is hyperv isolation and/or disable defender while creating the container.

**Comment by Rukkulakki** [comment]
-isolation 'hyperv' did the trick!

**Comment by freddydk** [comment]
Then my guess is that disabling defender would have done the same.
I will try to talk to the teams in Microsoft responsible for this behavior and see if we can find a solution.
