### ISSUE TITLE
[FEAUTRE] Get BC's instance logs from Windows Event Log 

### ISSUE THREAD

**Issue by mkilinskidev** [microsoft/navcontainerhelper#2438]
**Describe the issue**
It is not an issue, it's a feature proposition. It would be great if the BC's instance log will be available with a simple script. The application log is available in the Windows Event Log. Below you can find an example.

**Scripts used to create container and cause the issue**
```
Invoke-ScriptInBcContainer BC19 -scriptblock { Get-EventLog -LogName Application -Newest 1 -Source 'MicrosoftDynamicsNavServer$BC' | Format-Table -AutoSize -Wrap }
```

**Comment by freddydk** [comment]
Did you try 

Get-BcContainerEventLog -containerName BC19

?

**Comment by mkilinskidev** [comment]
Nope, I didn't know this function. But if I use it, I have an error
```
PS C:\Users\mkilinski> Get-BcContainerEventLog -containerName BC19
Getting event log for BC19
Get-BcContainerEventLog Telemetry Correlation Id: 16825536-45f7-4a91-b22d-1bdc68ed1130
Exception calling "Start" with "1" argument(s): "Class not registered"
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.2\ContainerInfo\Get-NavContainerEventLog.ps1:44 char:9
+         [Diagnostics.Process]::Start($eventLogName) | Out-Null
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : Win32Exception
```

**Comment by freddydk** [comment]
That's a new one - don't you have the event viewer on the host?
Maybe try to run the Event Viewer once before running the command?
The function will download an .evtx file and launch it.

**Comment by mkilinskidev** [comment]
I am using the Windows Server Core so yes - I can't run the Event Viewer.

**Comment by freddydk** [comment]
Ok, I see - then you would need to add -doNotOpen - then the function returns the .evtx name - and you can maybe copy that and open it on another machine?
You get the event log to see in the event viewer - which is much more useful than seeing pieces of the event log.

You can also start your container with -dumpEventLog and then use 

docker logs BC19 

to see the event log entries dumped.

**Comment by mkilinskidev** [comment]
Great, the -dumpEventLog switch will be enough. Thanks for the help!
