### ISSUE TITLE
Additional domain user

### ISSUE THREAD

**Issue by dkorinets** [Microsoft/navcontainerhelper#244]
Hello.
I have a small question.
Is it possible to add an additional domain user to BC navcontainer?

E.G.:
MyAdminUser/MyDomain : SUPPER PermissionSet
AdditionalUser/MyDomain : D365 BASIC  PermissionSet

**Comment by freddydk** [comment]
Containers are not domain joined, so I think you are out of luck here.
You might be able to add SID's - but you might also run into issues later.

**Comment by dkorinets** [comment]
Freddy, thank You for the reply.
