### ISSUE TITLE
Question: How to make BC available on localhost network

### ISSUE THREAD

**Issue by bsr203** [microsoft/navcontainerhelper#2441]
Hello,

I have setup an instances of BC with the help of BcContainerHelper. The service is available at URL in the host system as "http://mysandbox/BC". Is there a way I can  add a firewall rule to allow access it from other systems in local network. 

I am a windows newbie, and I couldn't find any port forwarded from container to host system to open up the port in firewall settings. The idea is to access BC instances on any device on local network instead of remote desktop.  Any help is greatly appreciated.

Thanks
bsr.

**Comment by freddydk** [comment]
When creating the container with New-BcContainer - you can publish ports.
-publishPorts @(443,8080,80,7048,7047)
you should also add
-usessl

if your computer is then accessible from the local network - it should work.

**Comment by bsr203** [comment]
thank you so much for the quick response. Will try it out and report. Thanks.
