### ISSUE TITLE
Error on executing NavContainerHelper functions/commands on Docker Container from Host

### ISSUE THREAD

**Issue by nkrTools4ERP** [Microsoft/navcontainerhelper#245]
Hey guys,

I'm struggling with performing commands on my running docker instance from my host and haven't been able to find anything that could solve my issue - been browsing here on the forums the past couple of hours while trying different things but still nothing works.
I am using NavContainerHelper to create my docker image, this works 100%. After I have created it, I want to execute a couple of commands that has to be executed in the order they are written in. It always fails on the execution of functions I loaded in from the first docker exec calling the navModelTools.ps1 script. Errors from these executions say that the called command / function does not exist.

I also tried with the command:
> Export-NAVContainerObjects -containerName $CONTAINER_NAME -objectsFolder "C:\ProgramData\NavContainerHelper\Extensions\$CONTAINER_NAME\my" -sqlCredential (get-credential -credential 'admin') -filter ""  

This one will Always fail and give an error on
> _The input ContainerId 45c55ead3f2ecfb2a66bdeedca4221b1e14587cce6cbe745aee24d33a7e95392 does not exist, or the corresponding container is not running_
![problemanvcontainer](https://user-images.githubusercontent.com/42603893/47906441-8cdd4f80-de89-11e8-85f8-67c2de1a5910.jpg)

So I am kinda at a loss of what to do. Below is a codesnip of the commands I execute, in same order:
> New-NavContainer @params -accept_eula -containerName $CONTAINER_NAME -imageName $imageName -includeCSide -doNotExportObjectsToText -licenseFile $licenseFilePath -credential $credentialge> me $imageName -includeCSide -doNotExportObjectsToText -licenseFile $licenseFilePath -credentia> $credential

> docker exec -ti $CONTAINER_NAME powershell -command$navModelToolsPath @params -NavIde $finSqlExePath

> docker exec -ti $CONTAINER_NAME powershell -command Export-NAVApplicationObject @params -DatabaseName $databaseName -Path $objectsFile  -DatabaseServer $databaseServer -Force | Out-Null 

> docker exec -ti $CONTAINER_NAME powershell -command Split-NAVApplicationObjectFile @params -Source $objectsFile -Destination $objectsFolder 

> docker exec -ti $CONTAINER_NAME powershell -command Remove-Item @params -Path $objectsFile -Force -ErrorAction Ignore

I recently re-tried the Export-NavContainerObjects approach and it would still provide same issue as seen in image above.

**Comment by nkrTools4ERP** [comment]
Solution: 
Thought I would give it a try to do a new install of the NavContainerHelper just to see if it would do anything for me. And so it did :) Fixed:
![problemanvcontainer](https://user-images.githubusercontent.com/42603893/47911891-04fe4200-de97-11e8-9302-34571aef1fd1.jpg)

**Comment by freddydk** [comment]
Thanks for the info
