### ISSUE TITLE
401 Error when using a OneDrive direct download link for license file

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/navcontainerhelper#2455]
https://github.com/microsoft/navcontainerhelper/blob/4bb91201343df88fa11b9e3d8e59ba379afd4ee8/ContainerHandling/New-NavImage.ps1#L468

The line mentioned leads to a 401 error when using a one drive direct download link to provide a license file to the AL-Go pipeline.
I can reproduce the error in a local powershell session.

The same download URL works with `Invoke-WebRequest` though.
Is there a specific reason to use `Download-File` ?

I generated the link by adding `&download=1` to the download link created in OneDrive.
See here:
https://techcommunity.microsoft.com/t5/onedrive-for-business/get-direct-download-link-of-a-file-in-onedrive-for-business/m-p/149766

**Comment by StefanMaron** [comment]
Thanks, that would help very much :)

**Comment by freddydk** [comment]
Any chance that you could place a file on a onedrive and send me a direct download URL in an email for that?
I cannot get the download=1 url to work on my machine at all.
Thanks

**Comment by freddydk** [comment]
@StefanMaron - any chance you can help out here?

**Comment by StefanMaron** [comment]
Oh, I have sent a link via mail. Did you not get it?

**Comment by freddydk** [comment]
it was in my Junk email folder - sorry

**Comment by StefanMaron** [comment]
I think that will work :) Thanks for implementing a solution, then I can just use my onedrive for those kind of static files and do not need to look into some other ways of storing them

**Comment by freddydk** [comment]
fix Included in the latest prerelease

**Comment by freddydk** [comment]
Shipped in 3.0.8

**Comment by StefanMaron** [comment]
Having the same issue still when passing in a One Drive link to the code signing certificate
https://github.com/microsoft/navcontainerhelper/blob/74bd262fc0af2296c571c3c6428b9aa1b48f5ec3/AppHandling/Sign-NavContainerApp.ps1#L52
