### ISSUE TITLE
Question: Permission error on NAV development environment  (v.14) while creating table

### ISSUE THREAD

**Issue by bsr203** [microsoft/navcontainerhelper#2458]
Hello,

Sorry for the beginner question but any suggestion would greatly help me.

I am starting with Dynamics, and the setup through Bccontainerhelper works great for AL development. But, when tried to create a table through NAV Development environment  (V.14, demo license), I get permission error.

<img width="613" alt="Screen Shot 2022-05-11 at 5 34 49 PM" src="https://user-images.githubusercontent.com/1966521/167961513-43d622a7-6e79-4393-9f99-e7246ed1b007.png">
 
Is there an admin user, other than  the credentials I gave during creation of the environment ?

Another quiuck qn. I am working to extend a feature, which has a table created through C/SIDE. I do not have access to the symbols and in my extension in AL, can I create the same table during development (in AL). When installing this extension, if the table exist at C/SIDE, will it cause a conflict. 

Thanks again for your time
bsr.

**Comment by bsr203** [comment]
I am not certain, but limitations of demo license is described [here](https://community.dynamics.com/nav/b/moxie4nav/posts/limitations-of-demo-amp-msdn-license).  Is it only applicable to NAV development, not BC ? 

Please also comment on C/SIDE, AL side by side development. Thanks.

**Comment by freddydk** [comment]
I would expect that you need a developer license to create a table in C/SIDE.

**Comment by bsr203** [comment]
@freddydk thank you so much for your response.
