### ISSUE TITLE
Introduction of [-useBestContainerOS] parameter prohitting running of images on Insiders OS Build

### ISSUE THREAD

**Issue by hsiungw** [Microsoft/navcontainerhelper#246]
I updated the NAVContainerHelper to the latest version and now hitting error while intend to run a new NAV image using command New-NAVContainer.

I am running Insider OS 19H1 build on my machine (Build no. 18272.1000)

**Comment by hsiungw** [comment]
>           What error are you getting?

![usebestcontaineros not used error](https://user-images.githubusercontent.com/16015694/47916107-030ca100-dee0-11e8-982e-c56b9b7af5c8.jpg)
![usebestcontaineros used error](https://user-images.githubusercontent.com/16015694/47916108-030ca100-dee0-11e8-8da9-49d060175d60.jpg)

**Comment by freddydk** [comment]
I have fixed this in the Dev. branch - will do a pull request later and update navcontainerhelper today.
Until then - you can install an older version of navcontainerhelper - or clone the depot and run the navcontainerhelper.ps1  (in the dev branch)

**Comment by hsiungw** [comment]
I will do a module update after  your update :)

**Comment by freddydk** [comment]
Thanks for reporting this.

**Comment by hsiungw** [comment]
You are welcomed :)

**Comment by freddydk** [comment]
fixed in this https://www.powershellgallery.com/packages/navcontainerhelper/0.4.0.2
