### ISSUE TITLE
New-BCContainerWizard: Not possible to select all country versions anymore

### ISSUE THREAD

**Issue by 365cycle** [microsoft/navcontainerhelper#2460]
**Describe the issue**
It's not possible to select all country versions anymore. I just tried to select "nl" (not "nlbe") for a NAV 2018 container, but New-BCContainerWizard refuses to let me choose this:

![image](https://user-images.githubusercontent.com/87028847/168028176-46755f93-7838-4b81-a5b9-63ebedf62e78.png)

Would imagine the same happens for "it" and "itch"

BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro 21H2 (build 22000.675)
Docker Version 4.4.2 (yes it needs an update)

**Additional context**
I don't remember ever having problems with choosing "nl", but haven't noticed "nlbe" being there either. Simply not sure why this is happening now. 
Saving the script and then editing this solved it of course.

**Comment by freddydk** [comment]
for now, select any country (gb) and get the script in the end - then replace gb with nl

**Comment by freddydk** [comment]
fix Included in the latest prerelease

**Comment by freddydk** [comment]
Shipped in 3.0.8
