### ISSUE TITLE
What is the best way to replace start.ps1 and navstart.ps1 in a container.

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#2472]
**Describe the issue**
Regarding #2466, is there a good way to replace start.ps1 and navstart.ps1 in one container?

I have a hunch that if I fix the two issues in start.ps1 (Get-CIMInstance fails) and navstart.ps1 (launching SQL browser fails) that these broken containers will work again. With docker start <container> run and behave normally.

**Comment by freddydk** [comment]
If you place a file called start.ps1 and navstart.ps1 in the my folder (c:\programdata\bccontainerhelper\extensions\containername\my) - then the container should pick these up when starting.
