### ISSUE TITLE
Disable SQL Browser and SQL Server VSS Writer?

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#2473]
**Describe the issue**
Is there any way to disable SQL Browser and SQL Server VSS Writer in the container?

In the background, we could improve resource usage and startup time a bit if we disable them. I only run the SQL Browser (SQLBrowser) when I have multiple SQL Server instances and don't use the SQL Server VSS Writer (SQLWriter) in general, since I don't do snapshots.

**Comment by freddydk** [comment]
there isn't a flag to do this and frankly, I think the gain of doing this is unmeasurable.
But you can download navstart.ps1 - modify it - and share it in -myscripts - then it would be good.
Just remember that grabbing a copy of navstart, means that you won't get other updates - it is not recommended.

**Comment by DanielGoehler** [comment]
Thanks.
