### ISSUE TITLE
Get-BCArtifactUrl current-1?

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#2474]
**Describe the issue**
Is there such a thing as `BCArtifactUrl` current-1? 

Our cloud customers are currently using BC 20.0 and the rollout of BC 20.1 has not started yet. Is there any way to select this version in `Get-BCArtifactUrl`?

```Powershell
Get-BCArtifactUrl -country DE -select Current -type Sandbox
``` 
gives me 20.1 (https://bcartifacts.azureedge.net/sandbox/20.1.39764.40733/de)

and 

```Powershell
Get-BCArtifactUrl -country DE -select SecondToLastMajor -type Sandbox
``` 
gives me 19.5 (https://bcartifacts.azureedge.net/sandbox/19.5.36567.40700/de)

**Comment by freddydk** [comment]
There isn't a flag for this, but you can do something like:

```
$allUs = Get-BCArtifactUrl -country us -select all
$latestVersion = [System.Version]($allUs | Select-Object -Last 1 | % { $_.Split('/')[4] })
$secondLatest = $allUs | Where-Object { $_.Split('/')[4] -notlike "$($latestVersion.Major).$($latestVersion.Minor).*" } | Select-Object -Last 1
```

**Comment by DanielGoehler** [comment]
Thanks
