### ISSUE TITLE
Could not find a part of the path 'C:\run\my\NAVWebClientManagement.psm1

### ISSUE THREAD

**Issue by waldo1001** [microsoft/navcontainerhelper#2478]
Freddy,

we encountered the above error while running ALOps pipelines.  We create the image with BCCH, but we start the container with our own parameters (not BCCH).

This was the issue on ALOps side...
https://github.com/HodorNV/ALOps/issues/510

It turned out that something was wrong concerning the my-folder in the (normal) generic image.  

By creating that folder during starting the container, all went well again.  Though - this obviously is a workaround that we can't sustain.

Most probably, it's because the assumption that the folder exists:
![image](https://user-images.githubusercontent.com/12088142/169025761-9d729f9f-cd9b-4459-ba4e-e40cbef00a3c.png)
but .. in the current image it doesn't.

We don't want to work with volumes (as that would also work around the problem) - because that would destabilize build-processes..

It would be nice that you can make sure the folder simply exists in the next generic images... .

**Comment by freddydk** [comment]
Generic image 1.0.2.7 (rolling out now) will create the my folder if it doesn't exist (meaning isn't shared).

**Comment by freddydk** [comment]
1.0.2.7 should be out for all windows versions

**Comment by waldo1001** [comment]
That's good news!  thanks!
