### ISSUE TITLE
Error creating NAV2017 container on server 2019

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/navcontainerhelper#2487]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I don't know what is causing this error:

> DockerDo : docker: Error response from daemon: hcsshim::ActivateLayer - failed failed in Win32: The I/O operation has been aborted because of either a thread exit or an application request. 
> (0x3e3).
> ExitCode: 125
> 

**Scripts used to create container and cause the issue**
```
$containerName = 'NAV2017server'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -country 'gb' -nav 2017 -select Latest
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -dns '10.100.2.24' `
    -isolation 'process' `
    -memoryLimit 6G `
    -updateHosts `
    -includeCSide `
    -doNotExportObjectsToText```

**Full output of scripts**
```
BcContainerHelper is version 3.0.8
BcContainerHelper is running as administrator
Hyper-V is Disabled
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 20.10.9
Docker Server Version is 20.10.9
Removing Desktop shortcuts
Downloading application artifact /onprem/10.0.30699.0/gb
Downloading C:\Users\tscott\AppData\Local\Temp\bc7efb56-cbda-4013-aca5-7242ba64003c.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /onprem/10.0.30699.0/platform
Downloading C:\Users\tscott\AppData\Local\Temp\1ee32168-2d8b-4c6c-858e-22b9fee2a80e.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\onprem\10.0.30699.0\platform\Prerequisite Components\Microsoft Report Viewer\ReportViewer.msi
Downloading c:\bcartifacts.cache\onprem\10.0.30699.0\platform\Prerequisite Components\Microsoft Report Viewer\SQLSysClrTypes.msi
Downloading c:\bcartifacts.cache\onprem\10.0.30699.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading c:\bcartifacts.cache\onprem\10.0.30699.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading c:\bcartifacts.cache\onprem\10.0.30699.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.17763.2928
Creating Container NAV2017server
Style: onprem
Multitenant: No
Version: 10.0.30699.0
Platform: 10.0.30699.0
Generic Tag: 1.0.2.7
Container OS Version: 10.0.17763.2928 (ltsc2019)
Host OS Version: 10.0.17763.2928 (ltsc2019)
Using process isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\NAV2017server\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container NAV2017server from image mcr.microsoft.com/businesscentral:10.0.17763.2928
13c496c9596cddc14bf1b5bf1d657e1672364bf642b811f6c609ebee96aa3d63
New-BcContainer Telemetry Correlation Id: df9724b5-6d30-495b-88df-cdb3c19d957a
DockerDo : docker: Error response from daemon: hcsshim::ActivateLayer - failed failed in Win32: The I/O operation has been aborted because of either a thread exit or an application request. 
(0x3e3).
ExitCode: 125
Commandline: docker run --dns 10.100.2.24 --volume "c:\bcartifacts.cache:c:\dl" --label nav=2017 --label cu=cu61 --env isBcSandbox=N --label version=10.0.30699.0 --label 
platform=10.0.30699.0 --label country=gb --env artifactUrl=https://bcartifacts.azureedge.net/onprem/10.0.30699.0/gb --env licenseFile="" --name NAV2017server --hostname NAV2017server --env 
auth=NavUserPassword --env username="admin" --env ExitOnError=N --env locale=en-GB --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume "C:\ProgramData\BcContainerHelper\Extensions\NAV2017server\my:C:\Run\my" --isolation process --restart 
unless-stopped --env filesOnly=False --memory 6G --env useSSL=N --volume "C:\ProgramData\BcContainerHelper\Extensions\NAV2017server\Program Files:C:\navpfiles" --volume 
"c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AE0AMgB3AEYAUABTAC8AWQAwADEAMAA3AEUAZABYAGQAOABpAG4ANgBmAGcAPQA9AHwAZgA2AGIAMgBiADcAM
wBjADcAYgAwADcAMwBkADkAZABkADQAOAA1ADQAOQBhADEANwBiADAAYgBjADIAZgA4ADYANQBjAGQAMgBmAGIAYwBmADQAZABhADgAMQAzAGMAYwA1AGIAMwA5ADUANAA4AGIANQAwADgAMQBlADMAMwA= --env 
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral:10.0.17763.2928
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.8\ContainerHandling\New-NavContainer.ps1:1836 char:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
- does it happen all the time?  
- did it use to work? First time trying to create a NAV2017 on this server

**Comment by tscottjendev** [comment]
I had just created a BC20 container immediately prior to trying the NAV2017 container and the BC20 container worked fine.

I ran the NAV2017 script again and it to have worked just fine. 

Not sure what happened the first time.

**Comment by freddydk** [comment]
Not sure either.
Thanks for the info
