### ISSUE TITLE
New-BcContainer error pulling images just started 

### ISSUE THREAD

**Issue by mcoNAV** [microsoft/navcontainerhelper#2491]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

Just started receiving this error with New-BcContainer on BCcontainer helper  v2.0.16

DockerDo : Error response from daemon: pull access denied for mybc18, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Script**

```
$containerName = 'bcserver'
$password = *
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = *
$licenseFile = *
$sasToken = *

$artifcatUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'us' -select 'Current' #Current Cloud

New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'mybc18' `
    -multitenant:$false `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -enableTaskScheduler:$false `
    -updateHosts  `       

```        

Setup-BcContainerTestUsers -containerName $containerName -Password $credential.Password -credential $credential`

**Script End**

**Output**

PS C:\Users\vmadmin> C:\DEMO\NewContainerServerError.ps1
BcContainerHelper is version 2.0.16
BcContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.14
Docker Server Version is 19.03.14
Fetching all docker images
Fetching all docker volumes
Pulling image mybc18:latest
DockerDo : Error response from daemon: pull access denied for mybc18, repository does not exist or may require 'docker login': denied: requested access to the 
resource is denied
ExitCode: 1
Commandline: docker pull  mybc18:latest
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\2.0.16\ContainerHandling\New-NavContainer.ps1:751 char:13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Output End**

**Comments**

It worked as recently as Tuesday or Wednesday and I've used this script to create and recreate containers for the last couple years.  Mirantis Container version (Server & client) are 19.03.14 which is old.  Could this have anything to do with the license changes?  I did try creating a new docker login id and using it for the pull with the same results.

**Comment by freddydk** [comment]
In your script - you set a variable called

`$artifcatUrl  (misspelled)
`
and use a variable called 

`$artifactUrl (correctly spelled)
`

**Comment by mcoNAV** [comment]
yep that would do it. - Sorry 

I'll go get this egg off my face and parameterize those scripts so I don't fat finger it again.
