### ISSUE TITLE
Update-Module BcContainerHelper throws error "Access to the cloud file is denied"

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#2495]
**Issue**
Since today I am getting the error "Access to the cloud file is denied" when executing the following PowerShell script

**Scripts used to create container and cause the issue**
```
Update-Module -Name bccontainerhelper -force
```
Last week I did not encounter this issue.

Searching for the error on the internet I cam across this post: https://docs.microsoft.com/en-us/answers/questions/328264/access-to-the-cloud-file-is-denied-when-install-az.html which led me to https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.2. From which I tried various things to see if that could fix it:

- https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.2#system-requirements
- https://docs.microsoft.com/en-us/powershell/scripting/gallery/installing-psget?view=powershell-7.2#installing-the-latest-version-of-powershellget
But all to no avail. Still getting the same error.

Not being a PowerShell geek I am out of options right now. SO, I decided to log this issue. Maybe not related to BCContainerHelper as such, but surely someone out here has a simple pointer on how to solve this. Thanx in advance.

**Comment by lvanvugt** [comment]
Executing one by one:

```
PS C:\Windows\system32> Remove-Module BcContainerHelper
Remove-Module : No modules were removed. Verify that the specification of modules to remove is correct and those module
s exist in the runspace.
At line:1 char:1
+ Remove-Module BcContainerHelper
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [Remove-Module], InvalidOperationException
    + FullyQualifiedErrorId : Modules_NoModulesRemoved,Microsoft.PowerShell.Commands.RemoveModuleCommand
```

```
PS C:\Windows\system32> UnInstall-Module BcContainerHelper -allversions
PackageManagement\Uninstall-Package : Access to the cloud file is denied
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:12733 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package],
   Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand,Mic
   rosoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage
```

**Comment by freddydk** [comment]
Ok, let's try a new one
Close all powershell sessions.
Open Windows Explorer and remove the BcContainerHelper folder from these 3 locations:

```
C:\Users\<username>\Documents\WindowsPowerShell\Modules
C:\Program Files\WindowsPowerShell\Modules
C:\Windows\system32\WindowsPowerShell\v1.0\Modules
```

**Comment by lvanvugt** [comment]
Thanx. Knew that I could remove some directories, but did not recall which.

Also ran `Update-Module -Name bccontainerhelper -force` gettting now a expected response
```
WARNING: The version '3.0.8' of module 'BcContainerHelper' is currently in use. Retry the operation after closing the applications.
```
