### ISSUE TITLE
Additional parameter to change Demo Folder on the Host?

### ISSUE THREAD

**Issue by elweilando** [Microsoft/navcontainerhelper#25]
I think it would be useful to have an additional parameter to change the Folder on the Host. At the moment the $demofolder c:\demo is hardcoded at some places.

**Comment by freddydk** [comment]
Correct it is totally hardcoded - I have it on my list to change it do c:\programdata\navcontainerhelper - I just need to investigate the consequences:-)

**Comment by freddydk** [comment]
Will be changed in next version

**Comment by freddydk** [comment]
folder is c:\programdata\navcontainerhelper in 0.2.1.0
