### ISSUE TITLE
Qn: Applying Cumulative Update to get a specific version while creating the container

### ISSUE THREAD

**Issue by bsr203** [microsoft/navcontainerhelper#2506]
**Describe the issue**
I want to make an instance of version `Platform 14.0.40464.0 + Application 29537 (US Dynamics NAV 14.0)`

When I tried with `Get-BcArtifactUrl -type 'OnPrem' -country 'na' -select 'Closest' -version '14.0.40464.0'`, it installs `Version: Platform 14.0.29530.0 + Application 29537 (US Dynamics NAV 14.0)`

This version is available as this [Cumulative Update](https://support.microsoft.com/en-us/topic/cumulative-update-09-for-microsoft-dynamics-365-business-central-april-19-on-premises-application-build-14-10-40471-platform-build-14-0-40464-320e28cd-1d8c-95f1-7565-1e743fc53bff)

Is there a way I can apply this Cumulative Update 09 while creating the container? Is it possible to apply it after creating the available version?

Thanks
bsr.

**Scripts used to create container and cause the issue**
```
$containerName = 'bc14-dev'
$password = 'Pa$$w0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $password
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'na' -select 'Closest' -version '14.0.40464.0'
New-BcContainer `
    	-accept_outdated `
    	-accept_eula `
    	-containerName $containerName `
    	-credential $credential `
    	-auth $auth `
    	-artifactUrl $artifactUrl `
    	-isolation hyperv `
    	-memoryLimit 8G `
    	-includeCSIDE `
    	-doNotExportObjectsToText `
	-WebClientPort 8082 `
	-FileSharePort 8280 `
	-ManagementServicesPort 7245 `
	-ClientServicesPort 7246 `
	-SoapServicesPort 7247 `
	-ODataServicesPort 7248 `
	-DeveloperServicesPort 7249 `
    	-updateHosts `
    	-publishPorts @(8082,8280,7245,7246,7247,7248,7249) `
```

**Comment by freddydk** [comment]
The artifacts are versioned by application version number - NOT platform version number.
Platform is just a reference inside the artifacts.

![image](https://user-images.githubusercontent.com/10775043/170319128-25bac6d9-8f04-460e-adc2-27d63095df05.png)

This is your artifact url:
https://bcartifacts.azureedge.net/onprem/14.0.29537.0/na

**Comment by freddydk** [comment]
Platform is the binaries (Server+Client), System module and also the System Application (I think)
Every application has a dependency on a specific platform version.
