### ISSUE TITLE
401 Error when using a OneDrive direct download link for certificate file

### ISSUE THREAD

**Issue by StefanMaron** [microsoft/navcontainerhelper#2518]
Similar to #2455 

Having the same issue still when passing in a One Drive link to the code signing certificate

https://github.com/microsoft/navcontainerhelper/blob/74bd262fc0af2296c571c3c6428b9aa1b48f5ec3/AppHandling/Sign-NavContainerApp.ps1#L52

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 3.0.11
