### ISSUE TITLE
When creating container (version 14.8) script continue looping

### ISSUE THREAD

**Issue by NubizPRLI** [microsoft/navcontainerhelper#2519]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

When trying to install a new BCContainer, it continue looping some of the lines in the script and it never stop / finish the script

Script used for creating the container:

$artifacturl = Get-BCArtifactUrl -type OnPrem -version 14.8.0.0 -country dk -select Closest
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'XXXXXXXXX' -AsPlainText -Force)
$containerName = 'pw'

New-BCContainer -accept_eula -containerName $containerName -artifactUrl $artifacturl -auth NavUserPassword -Credential $credential -updateHosts -alwaysPull -includeCSide -shortcuts Desktop -licenseFile "C:\Users\XXXXX\Documents\Business Central licenser\BC 20\7470982.flf" -myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/override/SelfSignedCertificateEx/SetupCertificate.ps1"

Output:

PS C:\WINDOWS\system32> C:\Users\XXXXX\Documents\PowerShell\Opret ny container BC14.8.ps1
WARNING: The names of some imported commands from the module 'BcContainerHelper' include unapproved verbs that might make them less disco
verable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approv
ed verbs, type Get-Verb.
BcContainerHelper is version 3.0.10
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Pro - 21H2
Docker Client Version is 20.10.16
Docker Server Version is 20.10.16
Removing Session pw
Removing container pw
Removing entries from hosts
Removing pw from container hosts file
Removing pw-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\pw
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.20348.707
10.0.20348.707: Pulling from businesscentral
Digest: sha256:ff37f262dec05d68de5e3169421f6e2d8cd020eaf47fbe0abf7b15af55661595
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.707
mcr.microsoft.com/businesscentral:10.0.20348.707
Using image mcr.microsoft.com/businesscentral:10.0.20348.707
Creating Container pw
Style: onprem
Multitenant: No
Version: 14.8.38658.0
Platform: 14.0.38650.0
Generic Tag: 1.0.2.7
Container OS Version: 10.0.20348.707 (ltsc2022)
Host OS Version: 10.0.22000.708 (21H2)
Using process isolation
WARNING: Using process isolation on Windows Desktop OS with generic image version prior to 1.0.2.4 or NAV/BC versions prior to 15.0, migh
t require you to use HyperV isolation or disable Windows Defender while creating the container
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\pw\my\SetupCertificate.ps1
Using license file C:\Users\PrebenLindahl\Documents\Business Central licenser\BC 20\7470982.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\pw\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupCertificate.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container pw from image mcr.microsoft.com/businesscentral:10.0.20348.707
d262323b45f039411fa19aa7a8faa02ba0d17ae0125b90e207d496ab551dca27
Waiting for container pw to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.8.38658.0/dk
Using installer from C:\Run\130
Copying Platform Artifacts
c:\dl\onprem\14.8.38658.0\platform
Copying Application Artifacts
Copying Database
Copying Installers
c:\dl\onprem\14.8.38658.0\dk\Installers
Copying TestToolKit
c:\dl\onprem\14.8.38658.0\dk\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\14.8.38658.0\dk\UpgradeToolKit
Copying Extensions
c:\dl\onprem\14.8.38658.0\dk\Extensions
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Using installer from 
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files

**Screenshots**

![image](https://user-images.githubusercontent.com/106659916/172316947-4eec437e-ba51-4208-9923-3f16baa945e6.png)

It seems to continue to loop the lines below, every time I try to create the container: 

Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server

Hope you have an answer

Thanks in advance

Best regards

Preben Lindahl

**Comment by freddydk** [comment]
Did you see the warning in the output:

WARNING: Using process isolation on Windows Desktop OS with generic image version prior to 1.0.2.4 or NAV/BC versions prior to 15.0, might require you to use HyperV isolation or disable Windows Defender while creating the container

**Comment by NubizPRLI** [comment]
Hi Freddy

Thank you

Added the command _-isolation hyperv_ and it worked

Best regards 
Preben
