### ISSUE TITLE
Access to DNS IP parameter

### ISSUE THREAD

**Issue by bmidutz** [microsoft/navcontainerhelper#2520]
When developing using a 3rd party app, i.e. Lanham EDI, in a Docker Container, registration of the app is required. The registration requires an external call to the app publisher's server. For this to function the DNS parameter must be set with the local DNS IP when the container is created. Prior to version 20* this was accomplished by manually setting it in C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.10\ContainerHandling\New-NavContainer.ps1 (see below)

With the updates from version 20 the script localdevenv.ps1 dynamic downloads the ContainerHandling code and objects and no longer calls the stored version where the updates were previously made. This causes the functionality of Lanham EDI to no longer work in a development environment. 

[string] $dns='', (OLD)
[string] $dns='192.168.0.1',  (UPDATED)

Lanham as stated this can only be fixed at this level and they cannot help.

We need a way to present the dns variable to the user to add it during creation.

**Comment by freddydk** [comment]
BcContainerHelper gives you the option to specify default parameters for New-BcContainer in the config file (or in session config).
in session config:
```
$bcContainerHelperConfig.defaultNewContainerParameters = @{ "dns" = "192.168.0.1" }
```
or in the config file (c:\programdata\bccontainerhelper\bccontainerhelper.config.json):
```
{
    "defaultNewContainerParameters": {
        "dns": "192.168.0.1"
    }
}
```
You should see a line in the output specifying this when loading BcContainerHelper:
![image](https://user-images.githubusercontent.com/10775043/172528539-13b3e003-317f-4c7d-b9ad-8dfb0ae54e3f.png)

When you state localdevenv.ps1 - I assume you are referring to AL-Go for GitHub.
In AL-Go for GitHub, you can specify ContainerHelper configurations in the AL-Go settings file, where you can specify the defaultNewContainerParameters (like in the containerhelper config file) in either the repo config file, the project config file or a user specific config file (if the setting is different from user to user).
