### ISSUE TITLE
New-BcContainerBcUser returns 'The Aggregate Permission Set does not exist.' on BC20

### ISSUE THREAD

**Issue by equisyscr** [microsoft/navcontainerhelper#2523]
**Describe the issue**
I am trying to generate users with special permission sets. It works like a charm for a BC19 container, but fails with a BC20 made in similar conditions.

`New-BcContainerBcUser -containerName $containerName -credential $credential4 -PermissionSetId 'D365 TEAM MEMBER' -ChangePasswordAtNextLogOn $false`

Note: I am NOT using a container set with newDatabase, and the permission set does exist in the Business Central UI and can be set manually.

The output being 
`Creating User teammember
Assigning Permission Set D365 TEAM MEMBER to teammember
The Aggregate Permission Set does not exist. Identification fields and values: Scope='System',App ID='{00000000-0000-0000-0000-000000000000}',Role ID='D365 TEAM MEMBER'
at <ScriptBlock>, <No file>: line 54
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 44
at New-BcContainerBcUser<Process>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\UserHandling\New-NavContainerNavUser.ps1: line 52
at <ScriptBlock>, C:\Users\****\Untitled1.ps1: line 9
The Aggregate Permission Set does not exist. Identification fields and values: Scope='System',App ID='{00000000-0000-0000-0000-000000000000}',Role ID='D365 TEAM MEMBER'
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\2.0.10\ContainerHandling\Invoke-ScriptInNavContainer.ps1:45 char:13
+             throw $_.Exception.Message
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The Aggregate P...65 TEAM MEMBER':String) [], RuntimeException
    + FullyQualifiedErrorId : The Aggregate Permission Set does not exist. Identification fields and values: Scope='System',App ID='{00000000-0000-0000-0000-000000000000}',Role ID='D365 TEAM MEMBER'`

How could I fix this?

**Comment by freddydk** [comment]
I can definitely repro this, also when connecting to the container and using the cmdlet:
![image](https://user-images.githubusercontent.com/10775043/174410079-54e3e739-18dc-415f-aaf0-bc0d17e81c58.png)
Have emailed the team behind this with a question on what to do

**Comment by freddydk** [comment]
I learned that from 20.x, appName and appPublisher is required parameters to New-NavServerUserPermissionSet.
I will add those to containerhelper and default to Base Application and Microsoft.

**Comment by freddydk** [comment]
NextMajor also verified that this fix works.
