### ISSUE TITLE
Calling Get-BCArtifactUrl for NextMinor returns the NextMajor artifact

### ISSUE THREAD

**Issue by amea20** [microsoft/navcontainerhelper#2527]
**Describe the issue**
When running the Get-BCArtifactUrl for the nextminor artifact, it returns the nextmajor version instead.

**Scripts used to create container and cause the issue**
```
Get-BCArtifactUrl -country w1 -select NextMinor -sasToken $sasToken
```

**Additional context**
- It happens all the time since 9th June 2022 3.20pm UK time.
- It used to return the 20.2 artifact when the current version was 20.1

**Comment by freddydk** [comment]
It looks like the 20.3 didn't start publishing - I have reported this to the team, who should look into this tomorrow first thing.

**Comment by amea20** [comment]
I see that 20.3 is now available. I'll close this ticket.
