### ISSUE TITLE
Breaking change for customers using Excel add-in

### ISSUE THREAD

**Issue by bogdanurse** [microsoft/navcontainerhelper#2532]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
The ARM template creates the Excel AddIn for each container we create. In order to work with it, in the manifest we have the property : replyUrlsWithType and a node inside of it is : https://az689774.vo.msecnd.net/dynamicsofficeapp/v1.3.0.0/* with type Web. 
This should be changed to type = SPA

**Scripts used to create container and cause the issue**
```
Create-AadAppsForNav
```

**Screenshots**
![image](https://user-images.githubusercontent.com/41284730/173567689-0e37cc81-d56e-4ad2-a9a0-6c2b488f6765.png)

**Comment by freddydk** [comment]
Do you know whether this is for all versions of BC - or only for 20.x?

**Comment by freddydk** [comment]
Today the Create-AadAppsForBC is using AzureAD powershell module
I assume that this fix requires a change to the graph api - which I might be able to look at late July / early August

**Comment by freddydk** [comment]
A new function is shipped in 5.0.0, named New-AadAppsForBC, which is using the Graph API to create the AAD apps.
The function contains a small bug, which causes the output of Connect-MgGraph to be included in the output - you need 5.0.1 (preview or release for it to work)

**Comment by freddydk** [comment]
https://aka.ms/getbc was updated today, using this new function and Edit in Excel works out of the box (after consent)
