### ISSUE TITLE
SSL Certificate Changes after "some Event" within the container - partially

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#2536]
**Describe the issue**
Today I had two developers knocking on my desk and complaining about the follow: 
D: "I have two days ago create a new container, using SSL. worked like a charm".
Me: "Cool, and?"
D: "Well, now after I did [mumbelingsounds] WindowsUpdate 21H2/Installed latest Docker Desktop/Machine restart the container is still running, but now I get an NET::ERR_CERT_AUTHORITY_INVALID in the webclient. Any Idea?"
Me: "No - but let's have a look".

So what I found was the following: the container was create like 13.06. and worked fine until "some Event" happened. after that it stopped. Now I connected to the container and checked the certificate.cer file there. and to my surprise it had a timestamp from 15.06 ... we went a bit deeper and compared the thumbprint of the imported certificate from 13.06 with this one. And to our surprise, it was different! So, of course I said to the Developer: 

Me: "See, you must have import somehow an old certificate or something, copy this one from the container, import on the host and you are good". 
D: "Thank you! You are my hero [starsinhiseyes]" (At least that what I believe what he wanted to say ...)

--- 15 Minutes later ---

D:  "#[prettypi**ed] Thank you! I can no longer publish any extension to my development environment! Error: The SSL connection could not be established, see inner exepection .... UntrustedRoot"
Me: "well, that was unexpected .... Might be that the port has a different binding on the IIS, and by that also uses a different certificate...do you still have the "wrong (first)" certificate? Try to also import that ..."
D: "Thank you! You are my hero [starsinhiseyes]" (Yepp, pretty sure)

And this also happened on a second machines as well. also with a container, made with me together, working just perfect. Until the restart in the morning. 

I don't have any script outputs, nor Version numbers from the two developers.

If I recall a file from you that said: certificates are made only once  when you first create the container. but not a start/stop/restart. So this is the best thing I can point at right now. Maybe you recall a change around that area that you did lately. 

What we could see: even the service tier thumbprint was updated with the latest certificate. I asked them to restart the machines onces more "like; redo your morning spin up routine". lets see if they get again another certificate. No results yet.

So, sorry, only a few details I can share here with you - but you might still have an idea what could have caused that ?! 
If you need more I can try to get some details from the developers machines.
my personal setup (same as the other two: just not using docker desktop but the pure docker service instead ) works, I don't have that issue. So I can not even tell you how to reproduce... :/ feels like something the generic image might cause this...but why would it only update the servicetier and not the binding of the dev service .... 

Thanks in advance! 

**Scripts used to create container and cause the issue**
Nothing special there, really. Only: useSSL, and ImportOnHost, using HyperV - BC v20.0.DE
both on 21H2, bccontainerhelper 3.0.10

**Comment by freddydk** [comment]
Thanks for the nice story telling here:-)
do you have a docker logs from one of the containers where this happened?

**Comment by KristofKlein** [comment]
Here you go: 

Initializing...
Setting host.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.48.1 in container hosts file
Starting Container
Hostname is BC20NBDE
PublicDnsName is BC20NBDE
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'C:\ProgramData\BcContainerHelper\DBbackup\database.bak'
Using database server localhost\SQLEXPRESS
Setting CompatibilityLevel for mydatabase on localhost\SQLEXPRESS
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 07A220B18DFB3D82A4D232B379F2F57CFEB8419D
DNS identity BC20NBDE
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
CertificateThumprint 07A220B18DFB3D82A4D232B379F2F57CFEB8419D
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer with SSL
Update configuration: navsettings.json
Done Configuring Web Client
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating ebrix as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Container IP Address: 172.19.49.239
Container Hostname  : BC20NBDE
Container Dns Name  : BC20NBDE
Web Client          : https://BC20NBDE/BC/
Dev. Server         : https://BC20NBDE
Dev. ServerInstance : BC
Setting BC20NBDE to 172.19.49.239 in host hosts file

Files:
http://BC20NBDE:8080/ALLanguage.vsix
http://BC20NBDE:8080/certificate.cer

WARNING: You are running a container which is 92 days old.
Microsoft recommends that you always run the latest version of our containers.

Container Total Physical Memory is 10.5Gb
Container Free Physical Memory is 7.8Gb

Initialization took 300 seconds
Ready for connections!
Initializing...
Setting host.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.48.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is BC20NBDE
PublicDnsName is BC20NBDE
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.19.54.244
Container Hostname  : BC20NBDE
Container Dns Name  : BC20NBDE
Web Client          : https://BC20NBDE/BC/
Dev. Server         : https://BC20NBDE
Dev. ServerInstance : BC
Setting BC20NBDE to 172.19.54.244 in host hosts file

Files:
http://BC20NBDE:8080/ALLanguage.vsix
http://BC20NBDE:8080/certificate.cer

Container Total Physical Memory is 10.5Gb
Container Free Physical Memory is 8.8Gb

Initialization took 81 seconds
Ready for connections!
Initializing...
Setting host.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.48.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is BC20NBDE
PublicDnsName is BC20NBDE
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.19.61.106
Container Hostname  : BC20NBDE
Container Dns Name  : BC20NBDE
Web Client          : https://BC20NBDE/BC/
Dev. Server         : https://BC20NBDE
Dev. ServerInstance : BC
Setting BC20NBDE to 172.19.61.106 in host hosts file

Files:
http://BC20NBDE:8080/ALLanguage.vsix
http://BC20NBDE:8080/certificate.cer

Container Total Physical Memory is 10.5Gb
Container Free Physical Memory is 8.8Gb

Initialization took 79 seconds
Ready for connections!
Initializing...
Setting host.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.48.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is BC20NBDE
PublicDnsName is BC20NBDE
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Initializing...
Setting host.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.48.1 in container hosts file
Restarting Container
Restart count 1
Hostname is BC20NBDE
PublicDnsName is BC20NBDE
Using NavUserPassword Authentication
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint D1D34DC1ED1548B15D928FDC072B35A613A150EF
DNS identity BC20NBDE
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
CertificateThumprint D1D34DC1ED1548B15D928FDC072B35A613A150EF
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Remove C:\inetpub\wwwroot\BC
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Removing existing application pool BC
Create website: NavWebApplicationContainer with SSL
Update configuration: navsettings.json
Done Configuring Web Client
Container IP Address: 172.19.57.76
Container Hostname  : BC20NBDE
Container Dns Name  : BC20NBDE
Web Client          : https://BC20NBDE/BC/
Dev. Server         : https://BC20NBDE
Dev. ServerInstance : BC
Setting BC20NBDE to 172.19.57.76 in host hosts file

Files:
http://BC20NBDE:8080/ALLanguage.vsix
http://BC20NBDE:8080/certificate.cer

Container Total Physical Memory is 10.5Gb
Container Free Physical Memory is 8.8Gb

Initialization took 142 seconds
Ready for connections!
Initializing...
Setting host.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.48.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is BC20NBDE
PublicDnsName is BC20NBDE
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.19.61.130
Container Hostname  : BC20NBDE
Container Dns Name  : BC20NBDE
Web Client          : https://BC20NBDE/BC/
Dev. Server         : https://BC20NBDE
Dev. ServerInstance : BC
Setting BC20NBDE to 172.19.61.130 in host hosts file

Files:
http://BC20NBDE:8080/ALLanguage.vsix
http://BC20NBDE:8080/certificate.cer

Container Total Physical Memory is 10.5Gb
Container Free Physical Memory is 8.9Gb

Initialization took 52 seconds
Ready for connections!

**Comment by freddydk** [comment]
I think I can see what the problem is.
this restart:
```
Initializing...
Setting host.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.178.99 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.19.48.1 in container hosts file
Restarting Container
Restart count 1
Hostname is BC20NBDE
PublicDnsName is BC20NBDE
Using NavUserPassword Authentication
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
```
doesn't say PublicDnsName is unchanged.

That means that it will create a new certificate - it thinks that the DNS name has changed.
Will investigate.

**Comment by KristofKlein** [comment]
Good morning!

Just wanted to share another observation that we have made: When this certificate replacement happened you can no longer use the http link from the logs to download it.

**Comment by KristofKlein** [comment]
Another info:
The developers also told me stories about issues to start docker desktop. So I checked with them and it is really like 7(+) tries to start docker desktop (it just shuts down, complains about could not stop/start). After looking into the way the generic scripts handles the restart "detection" ... could it be that process was started "half way" wrote a 1 (first restart) and based on that messed up the content on the file?  such that 1 <> HOSTNAME ?

**Comment by KristofKlein** [comment]
Good morning,

Number of developers is growing :) I now also faced the issue that the Restartcounter went above 2 - which makes the thing stuck completely  ... there we went into the container and changed the publicdnsFile content back to the container name. ... this helped for one developer to actually get the container starting up normal again (with two certificates), for another the setup was just messed up and he went along and made a new container. (We saw issues in the event log about Diskspace full (which was not the case) clrjit.dll access denied, ...)

**Comment by freddydk** [comment]
This is a bug in the generic image - will submit a fix over the weekend.

**Comment by freddydk** [comment]
Could you try to add this to your containers and see if that resolves the issue:
```
-myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/navstart.ps1")
```
This allows us to test this before re-generating all images, thanks

**Comment by KristofKlein** [comment]
I will ask them to redo the containers and have a check on the behavior. As I said, we can not really reproduce it in a way that it fails guaranteed ... so feedback might take a while...

**Comment by KristofKlein** [comment]
Went the dark side myself and also installed Docker Desktop to test this out. It (DD) also gives me starting issues every time I want to use it, but, with the new navstart.ps1 I have **not** seen any issue right now in terms of a restart counter in the logs (or the new file ;) ), and also **no** issues around the script thinking its going to change the name. 

I only see this :
```
Restarting Container
PublicDnsName unchanged
Hostname is BC20
PublicDnsName is BC20
```

While StartCount.txt content is: 0 

I will poke the Devs once more to also try it out! and collect the feedback. Until then: "Thank you! You are my hero [starsinhiseyes]" (That was predictable, wasn't it :P )

**Comment by KristofKlein** [comment]
couple of people are running with this new version now. Have not heard about any faulty rename since. Think this looks good :)

**Comment by freddydk** [comment]
Have one more issue in the generic layer to fix, then I will update all versions.

**Comment by freddydk** [comment]
New generic layers with this fix was published over the weekend
