### ISSUE TITLE
Docker container for Dominican Republic

### ISSUE THREAD

**Issue by bssienes** [microsoft/navcontainerhelper#2540]
I am trying to download a docker container for Dominican Republic. I used the following PowerShell script to do it, however I got the response saying “You have to specify artifactUrl or imageName when creating a new container.” If I replace the country code “do” with another one such as “us”, it works fine.

Is it possible to create a container with Dominican Republic localization?

```
$auth = …
$credential = …
$containerName = …
$licenseFile = …
$artifactUrl = Get-BCArtifactUrl -version 20 -country “do” -select Latest

New-BCContainer -accept_eula `
-containerName $containerName `
-artifactUrl $artifactUrl `
-auth $auth `
-credential $credential `
-isolation hyperv `
-accept_outdated `
-updateHosts `
-licenseFile $licenseFile `
```
BcContainerHelper is version 3.0.3
BcContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro
Docker v20.10.13

![image](https://user-images.githubusercontent.com/38301093/174189836-ac58c0f8-8bf0-42ab-82a1-4f72a208c617.png)

**Comment by freddydk** [comment]
Shipped in BcContainerHelper 3.0.11
