### ISSUE TITLE
Run-AlValidation failing due to signed app being seen as unsigned app

### ISSUE THREAD

**Issue by amea20** [microsoft/navcontainerhelper#2545]
**Describe the issue**
When running Run-AlValidation to validate our app against the current version, it fails due to the message "Publisher_DummyApp_1.1.0.0.app is not signed, result is UnknownError"

I created a separate container using New-BCContainer to publish the app, and it failed with the message "The certificate is not valid for the requested usage. (Exception from HRESULT: 0x800B0110)". After running the Sign-BcContainerApp to download and install the signing tools, it signed the app, but running Run-AlValidation with the re-signed app still failed.

**Scripts used to create container and cause the issue**
```
Run-AlValidation -apps "C:\apps\Publisher_DummyApp_1.1.0.0.app" `
                    -previousApps "C:\previousapps\Publisher_DummyApp_1.0.0.0.app" `
                    -countries "gb" `
                    -validateCurrent -throwOnError -affixes "ABC"
```

**Full output of scripts**
```
__      __   _ _     _       _   _               _____                _ _       
 \ \    / /  | (_)   | |     | | (_)             |  __ \              | | |      
  \ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__) |___ ___ _   _| | |_ ___ 
   \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  _  // _ \ __| | | | | __/ __|
    \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | \ \  __\__ \ |_| | | |_\__ \
     \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \_\___|___/\__,_|_|\__|___/

1 errors found in Publisher_DummyApp_1.0.0.0.app on https://bcartifacts.azureedge.net/sandbox/20.2.41144.42519/gb:
Publisher_DummyApp_1.0.0.0.app is not signed, result is UnknownError

  _____                          ___      __   _ _     _       _   _               ______    _ _                
 |  __ \                   /\   | \ \    / /  | (_)   | |     | | (_)             |  ____|  (_) |               
 | |__) |   _ _ __ ______ /  \  | |\ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__ __ _ _| |_   _ _ __ ___ 
 |  _  / | | | '_ \______/ /\ \ | | \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  __/ _` | | | | | | '__/ _ \
 | | \ \ |_| | | | |    / ____ \| |  \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | | (_| | | | |_| | | |  __/
 |_|  \_\__,_|_| |_|   /_/    \_\_|   \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \__,_|_|_|\__,_|_|  \___|

Run-AlValidation Telemetry Correlation Id: 5b44205c-3cdb-4178-8793-06486ae10ef4
1 errors found in Publisher_DummyApp_1.0.0.0.app on https://bcartifacts.azureedge.net/sandbox/20.2.41144.42519/gb:
Publisher_DummyApp_1.0.0.0.app is not signed, result is UnknownError
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\3.0.10\AppHandling\Run-AlValidation.ps1:577 char:5
+     throw ($validationResult -join "`n")
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (1 errors found ...s UnknownError
:String) [], RuntimeException
    + FullyQualifiedErrorId : 1 errors found in Publisher_DummyApp_1.0.0.0.app on https://bcartifacts.azureedge.net/sandbox/20.2.41144.42519/gb:
Publisher_DummyApp_1.0.0.0.app is not signed, result is UnknownError
...
```

**Additional context**
- It happens all the time
- It used to work

**Comment by catadumitru** [comment]
We have the same issue in our pipeline.
I tried to clear cache and remove all docker images - still failed.

**Comment by freddydk** [comment]
If you know the app is signed, you can add -skipverification to Run-AlValidation.
If possible, could you submit a download location where I can download the app and see why it triggers as not signed?
My email is freddyk at microsoft dot com

Thanks

**Comment by freddydk** [comment]
I can definitely repro the problem with your certificate.
When I try the same with my own app, I get:
![image](https://user-images.githubusercontent.com/10775043/175867493-b54b59d8-6f0d-44fb-8e9d-7e1ce8635438.png)

Using your app says:
![image](https://user-images.githubusercontent.com/10775043/175867784-9030d122-f856-43f1-a7b1-2f2538476b29.png)
UnknownError (which is the same error as reported above.

I have also tried to navigate to the container and use the signtool to verify the signature:
![image](https://user-images.githubusercontent.com/10775043/175872407-1d67179c-39af-4ffe-b916-ada5e98f65e1.png)

and your app:
![image](https://user-images.githubusercontent.com/10775043/175872456-f64c03fe-a4e2-4109-b03c-3550998d4f4a.png)

It seems like the code signing certificate is not right?

Did you try to submit for validation? does this work?

**Comment by amea20** [comment]
This is what's bizarre about the results:

1. I create a sandbox container using Run-AlPipeline command, and keep the container after successfully creating the app file
2. I run the Get-AuthenticodeSignature command in the container passing in the signed app file and received a **Valid** status
3. I run Run-AlValidation as shown above, passing in the signed app file, but returns UnknownError. I don't understand why a visibly signed app file is not appearing as signed, or maybe even trusted, when using a new container for AL validation. this worked ever since I introduced code-signing into the pipeline.

For now, if we need to validate our app with several countries, I will add -skipVerification to avoid this error from popping up.

**Comment by freddydk** [comment]
So, when you sign the app inside the container - you are able to validate the app.
But a new container cannot.
This would be the case with a self-signed certificate, but since you are passing validation, your app must be signed.

Strange...

**Comment by amea20** [comment]
So I have created a HelloWorld AppSource app, and using my certificate along with the Run-AlValidation command, it still fails due to an UnknownError. It could be determined that the certificate is the problem, but as it has been taken from DigiCert and is assumed to be trusted in the containers when signing or validating signed files.

**Comment by amea20** [comment]
I have resolved this from our side by switching the default timestamp server.

The following was used:
Import-Module BcContainerHelper
$bcContainerHelperConfig.timeStampServer = "http://timestamp.globalsign.com/tsa/r6advanced1"

**Comment by phenno1** [comment]
Hi All,

I would like to reopen this issue just to confirm if the issue is related to certificate itself or to process of signing of app maybe. We have this same problems as described in this issue: 
- we acquired Code Signing certificate from Sectigo
- our app is signed with Sign-BCContainerHelper
- our app can be installed to on-prem with signing verification included
- our app can be published to AppSource successfully 

Yet, both Get-AuthenticationSignature and Run-ALValidation are giving warning/error of UnknownError. 

We tried to change timeStampServer (both in ALValidation or in general setup) to no prevail. So, the question is what is the difference between BC instance (or AppSource) signing verification procedure and ALValidation signing verification procedure?

**Comment by kine** [comment]
Just want to add, we hit this too. Seems that the problem exists only "sometimes". We are using still same certificate, but sometime it fails and sometime it works. Will try to find the pattern.

**Comment by kine** [comment]
Odd is, that during one validation run, it shows these things for some countries:
```
Latest Supported Runtime Version: 10.1
XXX_20.1.96587.0.app is Signed with Authenticode certificate: CN=xxx, O=xxx, S=xxx, C=CZ
Extracting C:\ProgramData\BcContainerHelper\8b6ba962-0caf-446c-a9ae-b0290a6107dd\XXX_20.1.96587.0.app
```
and for another one (same run, same file):
```
Latest Supported Runtime Version: 10.1
XXX_20.1.96587.0.app is not signed, result is UnknownError
Extracting C:\ProgramData\BcContainerHelper\1a301c83-5075-4a17-8857-18b16292f845\XXX_20.1.96587.0.app
App Runtime Version is '9.0'
```
I can imagine that it fails on timestamp server call or something, because it fails e.g. 3 times in a row (3 countries in a row) and then it is ok again.

**Comment by phenno1** [comment]
We tried playing with timestamp as proposed earlier in this thread but
couldn't make it work. Based on your and previous replies it definitely has
something with timestamp but not sure what would be the stable solution.


S poštovanjem / Best regards
______________________________________

Davor Gelineo
*Sistem inžinjer | System Engineer*

Tel.: +387 33 563 177
E-mail: ***@***.***


*Bosnien Business Systems d.o.o. Sarajevo*Kranjčevićeva 39, 71000 Sarajevo,
BiH
Centrala: +387 33 563 150
Fax: +387 33 563 154
Web: www.bbs.ba
<https://www.facebook.com/bosnien.business.systems/>
<https://www.instagram.com/bbs.bih/>
<https://www.linkedin.com/company/bbs-bih/>

**Comment by kine** [comment]
Just hit this again yesterday. 3 validations of same app failed. Today, running same (same app file, same pipeline) on another agent, downloading actual modules and images, and works. Seems that it must be combination of some external things and may be some internal/platform thing.

**Comment by freddydk** [comment]
The way Run-AlValidation is checking whether the app is signed is using this code:

```
$tmpFolder = Join-Path $bcContainerHelperConfig.hostHelperFolder ([Guid]::NewGuid().ToString())
Copy-Item -path $appFile -Destination "$tmpFolder.app"
$signResult = Invoke-ScriptInBcContainer -containerName $containerName -scriptBlock { Param($appTmpFile)
    Get-AuthenticodeSignature -FilePath $appTmpFile
} -argumentList (Get-BcContainerPath -containerName $containerName -path "$tmpFolder.app")
Remove-Item "$tmpFolder.app" -Force
$signResult
```

If you create a container and run this code - what is the outcome?

**Comment by freddydk** [comment]
BTW - you can use Install-NAVSipCryptoProviderFromBcContainer to install the NAVSIP on your host (copied from the container)
