### ISSUE TITLE
Missing  generic image for 10.0.17763.3046

### ISSUE THREAD

**Issue by kguldbaek** [microsoft/navcontainerhelper#2546]
We have some issues in our pipelines when running hyper-v, so when is the generic image for 10.0.17763.3046 planned to be released?

**Comment by freddydk** [comment]
tonight

**Comment by freddydk** [comment]
BTW - until then, you should just be able to specify -isolation process - that should work most of the time.

**Comment by kguldbaek** [comment]
Perfect, it's working now, and thanks for the tip about process isolation.
