### ISSUE TITLE
Error: Install-BcContainerHelper

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#2547]
Starting this morning 5am we get an error within our pipelines while running Install-BcContainerHelper.ps1:

`##[error]Sort-Object : Cannot convert value ".AL-Go.project.settings.schema.json" to type "System.Version". Error: "Version 
string portion was too short or too long."`

Reason seems to be an update here, which was added at 5:15 this morning:
https://bccontainerhelper.azureedge.net/public?comp=list&restype=container

```<EnumerationResults ContainerName="https://bccontainerhelper.blob.core.windows.net/public">
  <Blobs>
    <Blob>
      <Name>.AL-Go.project.settings.schema.json</Name>
      <Url>https://bccontainerhelper.blob.core.windows.net/public/.AL-Go.project.settings.schema.json</Url>
      <Properties>
        <Last-Modified>Wed, 22 Jun 2022 05:14:37 GMT</Last-Modified>
        ...
```

**Comment by tobiaskluge** [comment]
Me, too. @freddydk ?

**Comment by freddydk** [comment]
Sorry - my bad - this is fixed now.
I needed a location to place an arbitrary file and didn't consider that this file would be seen as a containerhelper version.

Won't happen again

**Comment by freddydk** [comment]
Let me know if this is fixed or I need to cycle a cache somewhere, thanks

**Comment by tobiaskluge** [comment]
Local powershell works again. Our build server takes a bit longer...

**Comment by freddydk** [comment]
Thanks

**Comment by tobiaskluge** [comment]
Also Build Server installed BcContainerhelper again. Thanks a lot!
