### ISSUE TITLE
Icons missing on powershell and command prompt shortcuts

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [Microsoft/navcontainerhelper#255]
When using nav-arm-templates to create a virtual machine the shortcuts navserver PowerShell Prompt and navserver Command Prompt are missing icons.
Source of the problem - function New-DesktopShortcut: docker version 18.09.0 file docker.exe doesn't have an icon.
Possible solution - use icon from dockerd.exe

**Comment by freddydk** [comment]
Apparently this disappeared in the latest version of Docker.
Right now I am also trying to find out why the WebClient doesn't work on first deployment.
You have to run Replace-NavServerContainer before it works.

**Comment by freddydk** [comment]
There is a difference between the CE and EE version, so I decided to add the docker.ico file to the powershell module and use that.

**Comment by freddydk** [comment]
Shipped in 0.4.1.2
