### ISSUE TITLE
Publish-NAVContainerApp error : A drive with the name 'C' does not exist

### ISSUE THREAD

**Issue by lhtan-dev** [Microsoft/navcontainerhelper#256]
Environment is hosted from bcsandboxazure using latest-w1 build.

Upon running the Publish-NAVContainerApp and putting in the .app path file, hitting this error.

![image](https://user-images.githubusercontent.com/17727792/48611210-b38aa280-e9c0-11e8-97e9-a464ddbe4707.png)

When checking in NAV server powershell, i'm able to access c:\run.

**Comment by freddydk** [comment]
What is the full command you are running?

**Comment by lhtan-dev** [comment]
>           What is the full command you are running?

![image](https://user-images.githubusercontent.com/17727792/48614071-5266cd00-e9c8-11e8-8c18-27d1b149af9c.png)

**Comment by freddydk** [comment]
When you are supplying values as input, you shouldn't supply the '
you only supply that when supplying values on the cmdline

**Comment by lhtan-dev** [comment]
>           When you are supplying values as input, you shouldn't supply the '
> you only supply that when supplying values on the cmdline

Works now. My mistake. Closing the issue and appreciate the help Freddy.
