### ISSUE TITLE
includeCSIDE in template getbcext

### ISSUE THREAD

**Issue by tonyabriccomeske** [microsoft/navcontainerhelper#2584]
I am utilizing the https://aka.ms/getbcext template so I can restore a database using the SQL Developer edition (as my backup is over 10GB)
Is there a way to get the flag to includeCSIDE in the template

Otherwise, if there is a way to see the script being used to create the container/have it connected to a SQL developer instance on the host, I would greatly appreciate it.

**Comment by freddydk** [comment]
https://aka.ms/getnavext is for NAV and BC using C/AL - won't work for later versions of BC
I haven't tried it for a very long time.

You can also read https://freddysblog.com/2021/02/28/running-business-central-in-docker-using-sql-on-the-host/ to learn about how to run a container using SQL on the host.
There are several other blog posts on the subject on my blog.

**Comment by tonyabriccomeske** [comment]
Hi @freddydk - I was using both ARMs, so I accidently copied the wrong link in my request. 
https://aka.ms/getnavext installs NAV inside a container, and connects to the database on the host VM, but there are no shortcuts for inside the container to access C/SIDE. 
What I ended up doing was creating my own script to create a NAV container (on the VM), and it had the -includeCSIDE flag. 
Would be nice to have that in the ARM template so we could use it without having to create our own container after the fact.

**Comment by freddydk** [comment]
strange...
The parameter is defined here: https://github.com/microsoft/nav-arm-templates/blob/c694cfde1f1495af5461f0d8242a1bb08edfaf49/getnavext.json#L277
The variable is assigned here: https://github.com/microsoft/nav-arm-templates/blob/c694cfde1f1495af5461f0d8242a1bb08edfaf49/getnavext.json#L467
And transferred to initialize here: https://github.com/microsoft/nav-arm-templates/blob/c694cfde1f1495af5461f0d8242a1bb08edfaf49/getnavext.json#L1122
It is received as a parameter here: https://github.com/microsoft/nav-arm-templates/blob/c694cfde1f1495af5461f0d8242a1bb08edfaf49/initialize.ps1#L24
And the value is written into c:\demo\settings.ps1 here: https://github.com/microsoft/nav-arm-templates/blob/c694cfde1f1495af5461f0d8242a1bb08edfaf49/initialize.ps1#L128
Settings script is imported here: https://github.com/microsoft/nav-arm-templates/blob/c694cfde1f1495af5461f0d8242a1bb08edfaf49/SetupNavContainer.ps1#L17
The the parameter for New-NavContainer is set here: https://github.com/microsoft/nav-arm-templates/blob/c694cfde1f1495af5461f0d8242a1bb08edfaf49/SetupNavContainer.ps1#L308

So, somewhere, the chain breaks...
Could you check settings.ps1 - what is the line with includeCside - is it yes or no?
You could also try to modify c:\demo\SetupNavContainer.ps1 and insert a 
$params | out-host
right before the try statement in line 363 and see what parameters are transferred to new-navcontainer?

**Comment by freddydk** [comment]
Any more info on this?
