### ISSUE TITLE
Update container BC version

### ISSUE THREAD

**Issue by acardenaskma** [microsoft/navcontainerhelper#2589]
Is it posible to update the BC version of the container, instead of creating a new one?

Thanks!

**Comment by NAVspecialist** [comment]
The short answer is probably not, as it does not makes sense to do that in most cases. The longer answer is yes if you do a lot of powershell-commands where you download the newer version,, upgrade the database etc etc. then it SHOULD be possible - I guess that no-one has really tried.... 

The better answer is - If you really need to do stuff like this, then use Hyper-V manager or something similar, as you then have a full GUI and can see what is happening when it does not work.

Why do you want to be able to do that?

**Comment by alaincardenas** [comment]
Hello Palle,
I guess my short answer would be that I don't want to deal with all the Windows overhead!
It would be nice to preserve all data, settings, and deployed extensions by having a command to do an in-place upgrade.

Alain

**Comment by NAVspecialist** [comment]
Hi Alain

I fully understand. I am only using Hyper-V when absolutely necessary (normallay when I am doing upgrades NAV —> BC.

When we talk abort Docker and Containers the motto is always “Backup your powershell scripts”.  So in your case you need to:

1. Save the powershell script that creates the database with a backup of your data.
2. Save the powershell script that installs the extension

You can spin up a new container in less than 10 minutes, and you are up and running on a new version -compared to what? Hours of uninstall/download new version (as a ZIP-file), install a new version and running multiple configuration powershell commands with almost no option of finding out what is wrong if it afterwards does not work.

So please, don’t go down that road, it is a really bad idea.

Regards
Palle

**Comment by freddydk** [comment]
Agree with Palle.
You should not try to update the version of BC inside a container.
You should instead run a container using SQL Server on the host or SQL Server in another container.
Then you can kill a container and start a new container pointing to the database from the other container.

**Comment by alaincardenas** [comment]
Thanks, Palle and Freddy!
I get your point!

I like the idea of a separate container for the SQL Server and the BC instances.
I would still need a Hyper-V VM to test out in-place upgrades.

Thanks!
Alain
