### ISSUE TITLE
UploadImportAndApply-ConfigPackageInBcContainer ignores tenant parameter

### ISSUE THREAD

**Issue by scm6iwa** [microsoft/navcontainerhelper#2590]
Hi,

I have created a container with a tenant in it called mydata and the credentials for the mydata tenant is different to the default tenant but when I try to use UploadImportAndApply-ConfigPackageInBcContainer for the mydata tenant and the credentials for the mydata tenant it ignores the tenant I pass and uses the default tenant.

The script I've used is this:-

$securePassword = ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force
$credential = New-Object PSCredential -argumentList "test", $securePassword
$containerName = "bc-test"
$TestCompany = "test"
$tenantId = "mydata"

Write-Host "Run Rapidstart"
$packagePath = "C:\ProgramData\BcContainerHelper\packages\*.rapidstart"
Get-Item -Path $packagePath |ForEach-Object {
    Write-Host "Running RapidStartPackage $_"
    UploadImportAndApply-ConfigPackageInBcContainer -containerName $ContainerName -companyName $TestCompany -tenant $tenantId -configPackage $_.FullName -Credential $credential
}

And the output is this:-

Run Rapidstart
Running RapidStartPackage C:\ProgramData\BcContainerHelper\packages\01-PackageAC-TESTING-DIM.rapidstart
BcContainerHelper version 3.0.11
BcContainerHelper emits usage statistics telemetry to Microsoft
Using Basic Authentication
Invoke GET on http://172.20.141.25:7048/BC/api/v1.0/companies?$filter=name%20eq%20%27test%27&tenant=default
UploadImportAndApply-ConfigPackageInBcContainer Telemetry Correlation Id: 10717f3d-03f5-489b-a4bf-94c88612b085
Get-Item : The remote server returned an error: (401) Unauthorized.
At C:\Users\aldridgei\OneDrive - ADESA Europe\Docker scripts\Import rapid start.ps1:9 char:1
+ Get-Item -Path $packagePath |ForEach-Object {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Get-Item], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.GetItemCommand
 

As you can see in the invoke Get line it is using the tenant default where I'm passing mydata as the tenant id.

**Comment by freddydk** [comment]
You are absolutely right.

**Comment by freddydk** [comment]
Shipped in the latest prerelease

**Comment by freddydk** [comment]
Shipped in 4.0.3
