### ISSUE TITLE
How to access "Business Central Administration tool". (to enable API)

### ISSUE THREAD

**Issue by bsr203** [microsoft/navcontainerhelper#2592]
Hello,

I am following [this guide](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/api-reference/v1.0/enabling-apis-for-dynamics-nav) to Enable access to the APIs. 

For that, I need access to Business Central Administration tool. 

I do not see a link to this tool is created. I tried both v.14 & 20 images.

Please let me know a way to enable though command line if the tool is not available

I use below script to create containers.

Thanks
Bsr

```
$containerName = 'bc14-dev'
$password = 'Pas$Word!'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $password
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'na' -select 'Closest' -version '14.0.40464.0'
New-BcContainer `
    	-accept_outdated `
    	-accept_eula `
    	-containerName $containerName `
    	-credential $credential `
    	-auth $auth `
    	-artifactUrl $artifactUrl `
    	-isolation hyperv `
    	-memoryLimit 8G `
    	-includeCSIDE `
    	-doNotExportObjectsToText `
	-WebClientPort 8082 `
	-FileSharePort 8280 `
	-ManagementServicesPort 7245 `
	-ClientServicesPort 7246 `
	-SoapServicesPort 7247 `
	-ODataServicesPort 7248 `
	-DeveloperServicesPort 7249 `
    	-updateHosts `
    	-publishPorts @(8082,8280,7245,7246,7247,7248,7249) `
```

**Comment by dannoe** [comment]
You are looking for the ``ApiServicesEnabled`` setting.
You can extend your creation script from above with the following powershell lines after ``New-BcContainer``.

```powershell
Invoke-ScriptInBCContainer -containerName $containerName -scriptblock { 
     Set-NAVServerConfiguration -ServerInstance $serverInstance -KeyName "ApiServicesEnabled" -KeyValue "true" -Force
     Set-NAVServerInstance -ServerInstance $serverInstance -Restart
}
```

**Comment by freddydk** [comment]
ApiServicesEnabled should be enabled for all BC versions by default.
With the command above - you should be able to connect to APIs on port 7248 on the host (or on the container) using basic authentication.
