### ISSUE TITLE
Shortcut folder as parameter

### ISSUE THREAD

**Issue by kaspermoerch** [Microsoft/navcontainerhelper#26]
It would be nice if you could override the location where the shortcuts are placed. 

If you run multiple containers the desktop gets cluttered pretty fast - and if you do not use `Remove-NavContainer` they are never removed.

Another solution could be to place the shortcuts in a folder on the desktop named after the container.

**Comment by freddydk** [comment]
Noted.

**Comment by freddydk** [comment]
Next version you have an option to select: None, Desktop or StartMenu as location for shortcuts. Default is Desktop.

**Comment by freddydk** [comment]
-shortcuts (None, Desktop, StartMenu) is added in 0.2.1.0
