### ISSUE TITLE
Issue in resolve dependencies

### ISSUE THREAD

**Issue by bgestel** [microsoft/navcontainerhelper#2610]
Hi, 

When the Sort-AppFilesByDependencies gets called and the  .Parameter appFiles contains 2 versions of the same app the following line of code will return an array. , because it only checks for app id.

https://github.com/microsoft/navcontainerhelper/blob/d0a336f2052fd0fa8df9ae8a6985ecd9e2b55594/AppHandling/Sort-AppFilesByDependencies.ps1#L96

further down the line it then doesn't find the member dependencies 

https://github.com/microsoft/navcontainerhelper/blob/d0a336f2052fd0fa8df9ae8a6985ecd9e2b55594/AppHandling/Sort-AppFilesByDependencies.ps1#L113

this results in the dependencies not being included in the sortedappfiles.  And that in turn breaks the install apps step further down the pipeline

it might be nice to throw an error when it finds the same appid twice in the parameter appFiles.

That would have saved me a ton of debugging.  If it doesn't get changed I hope the next person facing this issue find this post :D 

Have a nice day and keep up the good work

**Comment by jonaswre** [comment]
I recently had a use case come up, that also had issues with old apps.


I solved this by not only sorting apps but actually creating representation of the graph. This allows to adhoc query dependencies and also dependents. I used this to update apps even if they have apps that depend on them installed.

With the better representation of the graph I can automate task to modify the graph to a desired state. For example clean up old versions or uninstall all dependencies that are not needed anywhere else. 

I thought about publishing this code here but I wasn't sure if there is a need for it. 
If there is I can create a PR.

**Comment by freddydk** [comment]
The issue checked in here resolves Issue #2600 - not #2610 - sorry for the confusion

**Comment by freddydk** [comment]
@jonaswre - Sounds like a nice function.

For this issue, I have done the following:

If multiple versions of the same app file exists, I will look at the latest (and add dependencies from that) AND write a warning that multiple versions of the same app exists.

Output of Sort-AppFiles was:
![image](https://user-images.githubusercontent.com/10775043/181248997-7e5ca097-4200-4099-82f6-5a0e45ed10c2.png)

and is now:
![image](https://user-images.githubusercontent.com/10775043/181248897-4a48ae0f-e6bb-4ba1-b987-8bbefe586905.png)

With this, you would have been able to find the problem faster I guess.

**Comment by bgestel** [comment]
@freddydk  , thank you, appreciate the quick response 👍
