### ISSUE TITLE
error during pull dynamics-nav:2018-de

### ISSUE THREAD

**Issue by elweilando** [Microsoft/navcontainerhelper#262]
If the scripts try to pull the dynamics-nav:2018-de image, it ends with 

> DockerDo : ExitCode: 1
> Commandline: docker pull  microsoft/dynamics-nav:2018-de
> In ....microsoft-navcontainerhelper\Container
> ps1:253 Zeichen:13
> +             DockerDo -command pull -imageName $imageName | Out-Null
> +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

after retrying to download some parts.

**Comment by freddydk** [comment]
If you update the navcontainerhelper - you should get a better error message, which might indicate what is wrong.
Might be that you need to run docker logout (have seen that a few times)

**Comment by elweilando** [comment]
Clean up my virtual machine resolves this issue.
It was not enough disk space for docker to pull the images.

**Comment by freddydk** [comment]
Ok, thanks for the info
