### ISSUE TITLE
How to Open Nav Web Client on another machine within the Network

### ISSUE THREAD

**Issue by Esanpons** [microsoft/navcontainerhelper#2624]
Good,

I am having the same problem as in the issue https://github.com/Microsoft/nav-docker/issues/226

When trying to solve the same as you advised, I get the following error:

DockerDo : docker: Error response from daemon: failed to create endpoint bc2022 on network nat: failed during hnsCallRawResponse: hnsCall failed in Win32: The process cannot access the file because it is
being used by another process. (0x20).
ExitCode: 125
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav= --env isBcSandbox=N --label version=20.2.41144.41423 --label platform=20.0.41086.41354 --label country=en --env
artifactUrl=https://bcartifacts.azureedge.net/onprem/20.2.41144.41423/en --env licenseFile="c:\run\my\license.flf" --name bc2022 --hostname bc2022 --env auth=NavUserPassword --env username="admin" --env
ExitOnError=N --env locale=es-ES --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume
"C:\ProgramData\BcContainerHelper\Extensions\bc2022\my:C:\Run\my" --isolation process --restart unless-stopped --env filesOnly=False --env enableApiServices=Y --env useSSL=N - -volume
"c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8ADcAcwBZAHAAcQAyAHoAegAyAEkAMgBIAHcAZQBZAG4ARABpADcAZQBmAGcAPQA9AHwAOQA3AMACADYAYQADkA5
AYQBiADYAMwA0ADQAZgBkADYAMgAxADIAYgBmADkANQAxADQAYgBkAGUAMABmADAANgA5ADEAZAA5ADAANwA5AGYAMgA1AGUANQA1ADYAMwA2ADcAZQBhADcAZgBjADMANgBiADUAZAA= --env passwordKeyFile="c:\run\my\aes.key" --env
removePasswordKeyFile=Y --publish 8080:8080 --env accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral:10.0.17763.2366
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.10\ContainerHandling\New-NavContainer.ps1: 1837 Character: 15
+ ... if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~
    + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

The docker script is as follows:
$containerName = 'bc2022'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'es' -select 'Latest'
$licenseFile = 'C:\Temp\license.flf'
$additionalParameters = @("--publish 8080:8080",
"--publish 80:80",
"--publish 7046-7049:7046-7049",
"--env publicFileSharePort=8080",
"--env PublicDnsName=$containerName",
"--env RemovePasswordKeyFile=N"
)

New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -additionalParameters $additionalParameters `
    -updateHosts

could you help me?

**Comment by freddydk** [comment]
It looks like some of the ports are allocated by a different container.
One port can be used by one container only - you can use traefik as a proxy for multiple containers as a workaround to this - or use transparent networking, allowing each container to get an IP address on the host network.
See also: https://github.com/microsoft/navcontainerhelper/issues/2607
