### ISSUE TITLE
Sign-BcContainerApp not signing .app properly

### ISSUE THREAD

**Issue by jdrco** [microsoft/navcontainerhelper#2625]
**Describe the issue**
After running Sign-BcContainerApp, I get an output saying that it successfully signed my .app in a docker shared local folder. But when I check to verify that it is digitally signed, the 'Digital Signatures' tab is missing, so it isn't actually signed yet I believe. I want to properly digitally sign my .app package and verify.

**Scripts used to create container and cause the issue**
```
$MyAppFile = "C:\ProgramData\BcContainerHelper\Extensions\26233f2adb05\my\AppSource\ContractManagement.app"
$MyPfx = "C:\ProgramData\BcContainerHelper\Extensions\26233f2adb05\my\AppSource\MyCertName.pfx"
$MyPassword = ConvertTo-SecureString "MyPassWord" -AsPlainText -Force
$MyContainerName = "26233f2adb05"

Sign-BcContainerApp -appFile $MyAppFile -pfxFile $MyPfx -pfxPassword $MyPassword -containerName $MyContainerName
```

**Full output of scripts**
```
Signing C:\ProgramData\BcContainerHelper\Extensions\26233f2adb05\my\AppSource\ContractManagement.app
Done Adding Additional Store
Successfully signed: C:\ProgramData\BcContainerHelper\Extensions\26233f2adb05\my\AppSource\ContractManagement.app
```

**Screenshots**
![10](https://user-images.githubusercontent.com/83478026/181428289-0e387b77-a641-4583-a7ca-0601e4c20ad6.png)

**Additional context**
As you can see from the screenshot, it does not show the 'Digital Signatures' tab as a property.

**Comment by freddydk** [comment]
I don't think you can see the Digital Signatures tab on a signed app unless you have the navsip crypto provider installed on the machine testing this on.
You can use Install-NAVSipCryptoProviderFromBcContainer to grab the crypto provider from a container and install it.

**Comment by freddydk** [comment]
You can test whether it is signed by creating a container and publish the app without the -skipverification flag.

**Comment by jdrco** [comment]
> Install-NAVSipCryptoProviderFromBcContainer

I get this error when running that install command:  **Container bcserver does not exist** 

Do I need to have Business Central On-Premise installed for this?

**Comment by freddydk** [comment]
Install-NAVSipCryptoProviderFromBcContainer -containerName <containerName>

**Comment by jdrco** [comment]
> You can test whether it is signed by creating a container and publish the app without the -skipverification flag.

May I get some resources on how to publish a .app to a BC sandbox running on a container, please? (kind of new to the Docker game).

Also, if the signature verification fails (via the method above), what are the likely causes of the failure?

**Comment by freddydk** [comment]
```
$artifactUrl = Get-BCArtifactUrl -country us
$licenseFile = $LicenseFileSecret.SecretValue | Get-PlainText
$auth = "UserPassword"
$containerName = "bcserver"
$credential = New-Object pscredential -ArgumentList 'admin', $PasswordSecret.SecretValue
New-BCContainer -containerName $containerName `
                -accept_eula `
                -Auth UserPassword `
                -artifactUrl $artifactUrl `
                -Credential $credential `
                -licenseFile $licenseFile
Publish-BcContainerApp -containerName $containerName -appFile $appfile -sync -install
```

The artifacts above are set to the latest available US sandbox artifacts.
Licensefile and password are taken from a keyvault - but can be hardcoded.

**Comment by freddydk** [comment]
As to likely causes - bad certificate or timestamp server down are the things I have seen - the latter very in-frequent.

**Comment by jdrco** [comment]
> As to likely causes - bad certificate or timestamp server down are the things I have seen - the latter very in-frequent.

Thank you Freddy, it was due to a bad cert.
