### ISSUE TITLE
Question for direction: how to expose port 7046 for Traefik to pick it up?

### ISSUE THREAD

**Issue by yrest** [microsoft/navcontainerhelper#2626]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Please advise how to access port 7046 redirected through Traefik

**Scripts used to create container and cause the issue**
```
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $databaseCredential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -databaseServer $databaseServer -databaseInstance $databaseInstance -databaseName $appDatabaseName `
    -databaseCredential $databaseCredential `
    -licenseFile $licenseFile `
    -multitenant `
    -usessl -installCertificateOnHost `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts `
```

**Full output of scripts**
```
Works like a charm, but only includes the following endpoints to access
 - Web
 - Soap
 - Rest
 - Dev
...
```

**Additional context**
We need to be able to access Windows client for debugging on version 14.

**Comment by freddydk** [comment]
Windows Client is not accessible through traefik.
@tfenster was working on traefik2 - which should enable this - current version cannot.

**Comment by cr998** [comment]
Traefik is built to work on  http protocol but NAV Windows Client connects to the service tier through a lower network layer (tcp), we would have to look for another alternative

**Comment by jonaswre** [comment]
As @freddydk said its possible using traefik2 which allows tcp and not just http. 
And i'had it working at one point and if you really want to you can script it yourself.  This PR by @tfenster might help https://github.com/microsoft/navcontainerhelper/pull/2169

But in the end we found it easier to rdp on the host If we needed to get in the rtc client.

**Comment by freddydk** [comment]
I won't be able to look at this.
