### ISSUE TITLE
Create-AlProjectFolderFromBcContainer does not create layout folder and copy rdlc files

### ISSUE THREAD

**Issue by peterz84** [microsoft/navcontainerhelper#2628]
When creating a Docker container:

```
$artifactUrl = Get-BCArtifactUrl -country "nl" -version "20.0" -storageAccount bcartifacts -type “OnPrem” 
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$containernameNL = "BC200NL"
$licenseFile = "C:\20.flf"
$tempFolder = "C:\temp\"

New-BcContainer `
    -accept_eula `
    -containerName $containernameNL `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -licenseFile $licenseFile `
    -updateHosts `
    -includeAL
```
and trying to create a project folder for it:
```
$projectFolder = $tempFolder + "nl\"
Create-AlProjectFolderFromBcContainer -alProjectFolder $projectFolder -containerName $containernameNL -useBaseAppProperties -credential $credential 

```
It does not include anything from the layouts folder:

```
Downloading app: Base Application
Url : http://192.168.138.7:7049/BC/dev/packages?publisher=Microsoft&appName=Base%20Application&versionText=20.0.37253.38230&tenant=default
C:\ProgramData\BcContainerHelper\Extensions\BaseApp-78f1eb1a-939b-4190-8c4e-6cddb22e3845.app
Extracting C:\ProgramData\BcContainerHelper\Extensions\BaseApp-78f1eb1a-939b-4190-8c4e-6cddb22e3845.app
Copying Al Source Files from C:\ProgramData\BcContainerHelper\Extensions\al-78f1eb1a-939b-4190-8c4e-6cddb22e3845\* to C:\temp\nl\
Al Project Folder Created
```
![image](https://user-images.githubusercontent.com/25202313/182398233-c6d8378d-db96-4de7-9ab9-cf16219b13c7.png)

any idea why? Because when I compile the create projectfolder, it will create new (almost empty) rdlc files for all reports!

Another annoying, but not most important thing, is that spaces in the folder names are replaced with %20:
![image](https://user-images.githubusercontent.com/25202313/182398415-376aa239-c630-4c3b-ad23-c188ff1f7d38.png)

**Comment by freddydk** [comment]
The Create-AlProjectFromBcContainer was really created to convert from C/AL to AL
I can see, that the function was extended to also extract the first versions of the base app and create a source folder - but wasn't really updated for the later versions - I don't think any partners are using this function anymore.
When specifying -includeAL - you also get the source in c:\programdata\bccontainerhelper\extensions\original...
or you can grab the source from the c:\applications or c:\applications.country folders inside the container.

Trying to fix this issue might just cause a lot of other problems I think.
