### ISSUE TITLE
Docker not starting after Certificate Expired

### ISSUE THREAD

**Issue by anwar0206** [Microsoft/navcontainerhelper#263]
HI,

We had a nav Containner running, the certificate got expired and the container stopped working.

I downloaded the certificate from the certificate security console (mmc)
Renewed the license with Renew-LetsEncryptCertificate powershell cmdlet.
The license got renewed, but my container is still not running.

AM I missing any further steps which needs to be taken post renewing the certificate.

Thanks & Regards
Anwar

**Comment by anwar0206** [comment]
Hi, One Update The docker is started but cannot use the webclient because the certificate is expired.

What is the procedure to renew the certificate in navcontainner.

Regards,
Anwar

**Comment by freddydk** [comment]
If you are running the Azure VMs, there is a script in c:\demo called something with renewletsencrypt, which renews and installs the cert.
If that doesn't work - then delete the VM and create a new one.
Recommendation is always to never have anything in containers which cannot easily be replaced.

**Comment by freddydk** [comment]
do you know why it says dsvcbcapp.southeastasia.cloudapp.azure.com?
earlier it looks like it should have been bcapp.....
can you email me the settings.ps1 in c:\demo?

**Comment by freddydk** [comment]
I was able to troubleshoot this issue and VMs created as of today should now also work when invoking

c:\demo\renewcertificate.ps1

You probably don't have this VM anymore, but if you have VMs created before today, you can replace the last two lines from:
```
Renew-LetsEncryptCertificate -publicDnsName $publicDnsName -certificatePfxFilename $certificatePfxFile -certificatePfxPassword $certificatePfxPassword
Restart-NavContainer -containerName navserver -renewBindings

```
with
```
$dnsAlias = "dns$(get-date -format yyyyMMddHHmm)"
Import-Module ACMESharp
New-ACMEIdentifier -Dns $publicDnsName -Alias $dnsAlias
Complete-ACMEChallenge -IdentifierRef $dnsAlias -ChallengeType http-01 -Handler iis -Force -HandlerParameters @{ WebSiteRef = "Default Web Site" }
Submit-ACMEChallenge -IdentifierRef $dnsAlias -ChallengeType http-01 -Force
sleep -s 60
Update-ACMEIdentifier -IdentifierRef $dnsAlias
Renew-LetsEncryptCertificate -publicDnsName $publicDnsName -certificatePfxFilename $certificatePfxFile -certificatePfxPassword $certificatePfxPassword -dnsAlias $dnsAlias
Restart-NavContainer -containerName navserver -renewBindings

```
and then run c:\demo\renewcertificate.ps1
