### ISSUE TITLE
UploadImportAndApply-ConfigPackageInBcContainer and taskscheduler

### ISSUE THREAD

**Issue by NAVFreak** [microsoft/navcontainerhelper#2650]
**Describe the issue**
As mentioned in #1982 you need to turn the taskscheduler in order for to work.
Can you please specify that in the command information. That would have saved me some time.

![image](https://user-images.githubusercontent.com/34970096/186853521-fd63bf48-6a1a-4a83-a40a-51c4458e4134.png)

**Comment by freddydk** [comment]
I have added this info to the help and issue a warning when running the function and the task scheduler is not enabled:
![image](https://user-images.githubusercontent.com/10775043/187027989-397033d6-67eb-4fea-aee3-77aa1e910120.png)

**Comment by NAVFreak** [comment]
That is even better! 😁
Thanks
