### ISSUE TITLE
Docker Build failed with exit code -1073740791

### ISSUE THREAD

**Issue by gonghwa** [microsoft/navcontainerhelper#2651]
running:
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'w1' -select 'Latest'
New-BcContainer `
>>     -accept_eula `
>>     -containerName $containerName `
>>     -credential $credential `
>>     -auth $auth `
>>     -artifactUrl $artifactUrl `
>>     -imageName 'bcimage' `
>>     -updateHosts

BcContainerHelper is version 3.0.12
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Pro - 21H2
Docker Client Version is 20.10.17
Docker Server Version is 20.10.17
Removing Desktop shortcuts
Downloading application artifact /onprem/20.4.44313.44365/us
Downloading C:\Users\adm\AppData\Local\Temp\bfb4ee17-e714-42ae-92c1-3cfbda9c49b7.zip
Unpacking application artifact to tmp folder using 7zip
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
WARNING: Unable to find matching generic image for your host OS. Using mcr.microsoft.com/businesscentral:10.0.20348.887
Building multitenant image bcimage:onprem-20.4.44313.44365-us-mt based on mcr.microsoft.com/businesscentral:10.0.20348.887 with https://bcartifacts.azureedge.net/onprem/20.4.44313.44365/us
Pulling latest image mcr.microsoft.com/businesscentral:10.0.20348.887
10.0.20348.887: Pulling from businesscentral
Digest: sha256:deedd9a1f097281924e761b225d384b296b92f0df01c0878536beea7a365eb7f
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.887
mcr.microsoft.com/businesscentral:10.0.20348.887
Generic Tag: 1.0.2.13
Container OS Version: 10.0.20348.887 (ltsc2022)
Host OS Version: 10.0.22000.856 (21H2)
Using process isolation
Files in c:\bcartifacts.cache\5bawqzzh.10j\my:
Copying Platform Artifacts
c:\bcartifacts.cache\onprem\20.4.44313.44365\platform
Copying Database
Copying Licensefile
Copying ConfigurationPackages
C:\bcartifacts.cache\onprem\20.4.44313.44365\us\ConfigurationPackages
Copying Applications
C:\bcartifacts.cache\onprem\20.4.44313.44365\us\Applications
c:\bcartifacts.cache\5bawqzzh.10j
Sending build context to Docker daemon  2.124GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.20348.887
 ---> 3f7731975b4d
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/20.4.44313.44365/us filesOnly=False
 ---> Running in 44f80ce9c020
Removing intermediate container 44f80ce9c020
 ---> 1e1d8cf15a2f
Step 3/6 : COPY my /run/
 ---> afccc6b2a7cd
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> ca5636d8c921
Step 5/6 : RUN \Run\start.ps1 -installOnly -multitenant
 ---> Running in b48cf718bded
c:\run\my folder doesn't exist, creating it
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
C:\NAVDVD\WebClient\Microsoft Dynamics NAV
Copying Client Files
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\systemFolder
Copying ModernDev Files
C:\NAVDVD
C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\NAVDVD\ConfigurationPackages
Copying Test Assemblies
C:\NAVDVD\Test Assemblies
Copying Applications
C:\NAVDVD\Applications
Copying dependencies
Copying ReportBuilder
The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; \Run\start.ps1 -installOnly -multitenant' returned a non-zero code: 3221226505
New-Bcimage Telemetry Correlation Id: dc02cb00-b362-4cd2-9190-73274d7ea7eb
New-BcContainer Telemetry Correlation Id: 5822d44a-f785-4214-a827-ea45e70d5d13
Docker Build failed with exit code -1073740791
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.12\ContainerHandling\New-NavImage.ps1:640 char:25
+ ...              throw "Docker Build failed with exit code $LastExitCode"
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Docker Build fa...ode -1073740791:String) [], RuntimeException
    + FullyQualifiedErrorId : Docker Build failed with exit code -1073740791

**Comment by freddydk** [comment]
Two things to try:
1. Remove the -imagename parameter
2. disable your antivirus / defender while running the command

**Comment by gonghwa** [comment]
Thanks. That works.
