### ISSUE TITLE
Run-AlPipeline: The tenant 'default' is not accessible.

### ISSUE THREAD

**Issue by Brunoalves5** [microsoft/navcontainerhelper#2653]
Hi, I'm following this old [workshop](https://bcdocker.blob.core.windows.net/public/cicd%20workshop.pdf) to learn how to create simple build pipelines for BC projects on Azure DevOps, but my build always fails when trying to compile because it doesnt seem to wait for the tenant to be available.

Is this a problem with the Run-AlPipeline function? The same happens if I run the script manually on my VM, but It works fine if I run the script while debugging and wait a little before letting the script proceed to compile the apps. But I cant modify the script to add a "sleep" or loop there.

Which suggests that the Run-AlPipeline function doesnt wait for the tenant to be available before trying to compile the apps.
It gives this error:
`The tenant 'default' is not accessible.`

Has this ever happened to anyone?

The script I'm using is the Local-DevEnv.ps1 in the original repository: 
https://github.com/BusinessCentralApps/Old.HelloWorld.AppSource
The pipeline uses the script DevOps-Pipeline.ps1, but both have the same issue while running Run-AlPipeline. 

This is the error I get:
![image](https://user-images.githubusercontent.com/108202003/187039564-c7cd8457-1f1b-40f5-b7fa-feb5145960a4.png)

**Comment by freddydk** [comment]
Sorry, but I don't support the old hands on lab scripts anymore.
My recommendation is to go with AL-Go for GitHub - and if you for some reason need to stay on Azure DevOps, then ALOps is my recommendation.
AL-Go for GitHub also uses Run-AlPipeline, and I have seen or heard of a problem like this, my assumption is that this has to do with the parameters given to the function.
I do not recommend trying to set something up manually - it will cost you a lot of time and stress.

**Comment by Brunoalves5** [comment]
That's what I feared :(
I will take a look at ALOps and AL-Go :)

**Comment by jonaswre** [comment]
I'm still running the scripts from the HelloWorld Repository in a couple of customer projects. Its still working good for us. But If you are not already heavly invested in DevOps you should consider switching to github. It's just alot easier to keep up to date. 

But if you still need to help you can contact me at jonas.wrede@beyondit.gmbh.
