### ISSUE TITLE
AAD login fails with CU1 omprem images due to lowercase reply URL 

### ISSUE THREAD

**Issue by AskeHolst** [Microsoft/navcontainerhelper#266]
When creating a new container and running Create-AadAppsForNav app registrations are created. This has worked fine in the past.
With the CU1 omprem images ADD login fails with a "Reply address did not match because of case sensitivity".
This is due to the sign-in url being lowercase.
```
    $ssoAdApp = New-AzureADApplication -DisplayName "NAV WebClient for $appIdUri" `
                                       -Homepage $publicWebBaseUrl `
                                       -IdentifierUris $appIdUri `
                                       -ReplyUrls @($publicWebBaseUrl, ($publicWebBaseUrl.ToLowerInvariant()+"SignIn"))
```

Removing the ToLowerInvariant() fixes the problem, but that of course could cause problems I'm not aware of. If it was a sure thing I would have made a pull-request :-)
```
    $ssoAdApp = New-AzureADApplication -DisplayName "NAV WebClient for $appIdUri" `
                                       -Homepage $publicWebBaseUrl `
                                       -IdentifierUris $appIdUri `
                                       -ReplyUrls @($publicWebBaseUrl, ($publicWebBaseUrl+"SignIn"))
```

So for me it is a solved, but something you might want to look into. Maybe it has to do with a change in another place.

**Comment by AskeHolst** [comment]
It is a bit of both, it's a VM with the NAV-ARM. But I continued using the SetupNavContainer.ps1 to create additional containers (just changing settings.ps1). It worked fine until I pulled a CU1 onprem container.
navcontainerhelper I updated as new versions came out.

**Comment by freddydk** [comment]
I am pretty sure that there is a reason for the tolower…
Will have to do some testing.
What you say is, that if you spin up a rtm version with the new navcontainerhelper then it works - and cu1 doesn't?
I would be surprised if they have changed anything in the client on this…

Thanks

**Comment by AskeHolst** [comment]
Yes, exactly. I have created lots of different containers on this VM both bcsandbox and onprem. Pulling an onprem now gives me the latest meaning a cu1 and that fails with ToLower in place.

**Comment by AskeHolst** [comment]
It could of course be something with the SetupNavContainer.ps1 but I do use the latest version from nav-arm-templates.

**Comment by AskeHolst** [comment]
Created a container with bcinsider.azurecr.io/bcsandbox and that needs the ToLower for AAD login to work.

**Comment by freddydk** [comment]
I have tried the latest bconprem - and that works fine.
Do you still have this issue?

**Comment by AskeHolst** [comment]
Turned out this was related to setting AzureActiveDirectoryClientId and AzureActiveDirectoryClientSecret which I tested when tying to get the Business Inbox working (the two lines commented out in SetupNavContainer) and I never set them back to being commented. You can close this.

**Comment by freddydk** [comment]
thanks
