### ISSUE TITLE
In BcContainerHelper - 'Get-NavCompany' is not recognized as the name of a cmdlet !!

### ISSUE THREAD

**Issue by TomHedegaardTrimit** [microsoft/navcontainerhelper#2671]
We have a pipeline running for some time, and suddenly today it's failing.
It runs on BcContainerHelper 4.0.

In our pipeline we use Get-CompanyInBCContainer in order to give us a list of companies, and the Get-CompanyInNavContainer.ps1 uses the cmdlet Get-NavCompany, which apparently is no longer available in BcContainerHelper 4.0.

NavContainerHelper is version 4.0
It worked on prior versions of NavContainerHelper
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5

Attached the complete log of the pipeline run..
[logs_4268.zip](https://github.com/microsoft/navcontainerhelper/files/9487985/logs_4268.zip)

**Comment by freddydk** [comment]
Which log file contains the failure?

**Comment by freddydk** [comment]
could you paste the content of this file here: DevOps\scripts\Run-Tests.ps1

**Comment by TomHedegaardTrimit** [comment]
[Run-Tests.zip](https://github.com/microsoft/navcontainerhelper/files/9488373/Run-Tests.zip)

**Comment by freddydk** [comment]
Could you try to insert a 

Start-Sleep -seconds 30 

after the Restart-BcContainer in line 36
Just to see whether this is a timing problem.

**Comment by TomHedegaardTrimit** [comment]
Same result with a sleep..

the pipeline always get the newest BcContainerHelper, så why cant it see the Get-NavCompany cmd ?

If I run with an old BcContainerHelper version, eg. 2.0.x.x, it works and the cmd is found..

**Comment by freddydk** [comment]
If I knew the answer, I would tell you:-)
I did some changes to session handling and that is probably what is causing this.
The session is killed and for some reason, the NAV Cmdlets are not loaded when establishing a new session.
I will try to figure out why.

In the meantime, you can switch to 3.0.12 or 3.0.11 and see whether that solves the issue for now.

**Comment by TomHedegaardTrimit** [comment]
My pipeline now succeeded, running on BcContainerHelper 3.0.10.
(3.0.12 failed)

**Comment by freddydk** [comment]
Found the problem - will fix this in 4.0.2

**Comment by freddydk** [comment]
Shipped in 4.0.3
