### ISSUE TITLE
Docker pull fails due to nonvalid image name

### ISSUE THREAD

**Issue by makuhn** [Microsoft/navcontainerhelper#268]
Docker image download fails if a specific container version is downloaded. The following script has been executed (NOTE: I removed the parameter -u and -p and added ********* instead):
```
$imagename = 'bcinsider.azurecr.io/bcsandbox-master:14.0.26322.0-de'

$containername = "NCHTest0420"
$navlicense = '..\..\Lizenz\2018-10-04.flf'


Install-Module navcontainerhelper -Force
docker login "bcinsider.azurecr.io" *********
New-NavContainer -accept_eula -alwaysPull -imageName $imagename -includeCSide -containerName $containername -licenseFile $navlicense
```
It seems that image name is erroneously extended by **ltsc2016**.

Error message:
![image](https://user-images.githubusercontent.com/38248390/49295286-b8b61a00-f4b5-11e8-8000-f5efb87dbf9a.png)

NavContainerHelper version: 0.4.2.0

**Comment by freddydk** [comment]
It is intentional that it adds the ltsc2016 - but it of course shouldn't do that unless the image exists.
I will fix this tonight - in the meantime you will have to revert back to navcontainerhelper 0.4.1.2 if you need to run the master image.

**Comment by freddydk** [comment]
I fixed the bug - update navcontainerhelper and you should be good to go.

**Comment by makuhn** [comment]
Thanks for the quick reaction. Now it works as expected.
