### ISSUE TITLE
New-BcContainerWizard doesn't seem to support Public Preview Versions

### ISSUE THREAD

**Issue by dnpb** [microsoft/navcontainerhelper#2681]
With `BcContainerHelper version 4.0.1` in the Wizard, I see only options to use latest released versions, or Insider previews.

Latest gets me BC 20.5. My Insider token has expired and I don't have a new one yet. And BC21 is Public Preview now, so I shouldn't require Insider access :-)

I have had to take a previously produced PS1 script and substitute the relevant `Get-BcArtifactUrl -storageAccount BcPublicPreview`.

Shouldn't the Wizard let us do this, without having to manually edit the resulting script?

Thanks!

![image](https://user-images.githubusercontent.com/63455896/189315039-98b663b0-3371-4e21-ae43-f9c480b608ff.png)

**Comment by freddydk** [comment]
Shipped in 4.0.3

**Comment by dnpb** [comment]
Thanks muchly!
