### ISSUE TITLE
Error creating Container  with Insider Builder

### ISSUE THREAD

**Issue by rickblommetjes** [microsoft/navcontainerhelper#2684]
**Describe the issue**
When installing the latest insider build using below call, the container cannot be created, the Latest Build BC20.05 can still be created.

Only after removing the parameters the insider build can be created.
   -installCertOnHost `
   -useSSL `

**Scripts used to create container and cause the issue**
New-BCContainer -accept_eula `
    -containerName $BCServerInstance `
    -auth NavUserPassword `
    -updateHosts `
    -includeAL `
    -licenseFile $licenseFile `
    -assignPremiumPlan `
    -installCertOnHost `
    -useSSL `
    -artifactUrl $BCArtifactUrl

**Full output of scripts**
Installing helper functions
Installing Latest version of the Module BCContainerHelper
Input the D365 BC Localisation [nl]: 
The Shared Access Signature token you need is valid until a certain date and can be downloaded at https://partner.microsoft.com/en-us/dashboard/collaborate/packages, section Working with Insider Build
Install D365 BC Major version [21.0]: 
Getting new BCInsider Sandbox Container artifactURL
Input the name of the new container instance [BC210]: BC210Error
Creating new Sandbox Container
BcContainerHelper is version 4.0.2
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Enterprise - Unknown/Insider build
Docker Client Version is 20.10.17
Docker Server Version is 20.10.17
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.20348.887
Creating Container BC210Error
Style: sandbox
Multitenant: Yes
Version: 21.0.46357.0
Platform: 21.0.46266.0
Generic Tag: 1.0.2.13
Container OS Version: 10.0.20348.887 (ltsc2022)
Host OS Version: 10.0.22622.590 (Unknown/Insider build)
Using process isolation
Using locale nl-NL
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file ..\resources\EasyStep2-6384999.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\BC210Error\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC210Error from image mcr.microsoft.com/businesscentral:10.0.20348.887
9e9ed4a9f633f24a96f27b352331f40b04db3a16d896ba9cbcf5712f9af55b65
Waiting for container BC210Error to be ready
Using artifactUrl https://bcinsider.azureedge.net/sandbox/21.0.46357.0/nl
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\21.0.46357.0\platform\ServiceTier\Program Files
c:\dl\sandbox\21.0.46357.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\21.0.46357.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\21.0.46357.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\21.0.46357.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\21.0.46357.0\platform
c:\dl\sandbox\21.0.46357.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\21.0.46357.0\nl\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\21.0.46357.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\21.0.46357.0\nl\Extensions
Copying Applications
C:\dl\sandbox\21.0.46357.0\platform\Applications
Copying Applications.NL
C:\dl\sandbox\21.0.46357.0\nl\Applications.NL
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 686 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.2.13 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.13 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.128.1 in container hosts file
Starting Container
Hostname is BC210Error
PublicDnsName is BC210Error
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 1F277BBF1A6051018F8A8C54CA88C0524A20052A
DNS identity BC210Error
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
CertificateThumprint 1F277BBF1A6051018F8A8C54CA88C0524A20052A
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer with SSL
WARNING: SetupWebClient failed, retrying...
CertificateThumprint 1F277BBF1A6051018F8A8C54CA88C0524A20052A
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Remove C:\inetpub\wwwroot\BC
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Removing existing application pool BC
Create website: NavWebApplicationContainer with SSL
Incorrect function. (Exception from HRESULT: 0x80070001)
at New-NavSiteWithBindings, C:\run\my\NAVWebClientManagement.psm1: line 680
at New-NavWebSite, C:\run\my\NAVWebClientManagement.psm1: line 630
at New-NAVWebServerInstance, C:\run\my\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 50
at <ScriptBlock>, C:\Run\navstart.ps1: line 191
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcinsider.azureedge.net/sandbox/21.0.46357.0/nl
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\21.0.46357.0\platform\ServiceTier\Program Files
c:\dl\sandbox\21.0.46357.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\21.0.46357.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\21.0.46357.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\21.0.46357.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\21.0.46357.0\platform
c:\dl\sandbox\21.0.46357.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\21.0.46357.0\nl\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\21.0.46357.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\21.0.46357.0\nl\Extensions
Copying Applications
C:\dl\sandbox\21.0.46357.0\platform\Applications
Copying Applications.NL
C:\dl\sandbox\21.0.46357.0\nl\Applications.NL
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 686 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.2.13 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.2.13 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.128.1 in container hosts file
Starting Container
Hostname is BC210Error
PublicDnsName is BC210Error
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 1F277BBF1A6051018F8A8C54CA88C0524A20052A
DNS identity BC210Error
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
CertificateThumprint 1F277BBF1A6051018F8A8C54CA88C0524A20052A
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer with SSL
WARNING: SetupWebClient failed, retrying...
CertificateThumprint 1F277BBF1A6051018F8A8C54CA88C0524A20052A
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Remove C:\inetpub\wwwroot\BC
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Removing existing application pool BC
Create website: NavWebApplicationContainer with SSL
Incorrect function. (Exception from HRESULT: 0x80070001)
at New-NavSiteWithBindings, C:\run\my\NAVWebClientManagement.psm1: line 680
at New-NavWebSite, C:\run\my\NAVWebClientManagement.psm1: line 630
at New-NAVWebServerInstance, C:\run\my\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 50
at <ScriptBlock>, C:\Run\navstart.ps1: line 191
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
New-BCContainer Telemetry Correlation Id: 7549aeaf-7d92-437a-8143-01ab0c3581f7
Initialization of container BC210Error failed
At C:\Users\RickBlom\Documents\WindowsPowerShell\Modules\BcContainerHelper\4.0.2\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...210Error failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC210Error failed

**Screenshots**

**Additional context**
- Current versions of BC articats can create a container, Insider Build can't

**Comment by freddydk** [comment]
Please, please, please do not include the insider SAS token in your issues here on GitHub.

**Comment by freddydk** [comment]
Please try using hyperv isolation and see whether that makes a difference

**Comment by freddydk** [comment]
I didn't notice the useSSL comment in your text, as you wrote that this only happens with insider builds.
You cannot run with SSL and process isolation on Windows 11 - see Issue #2203 
Windows team should be working on a fix.
