### ISSUE TITLE
Possible encoding error in New-AppSourceSubmission

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#2692]
I was just trying to get New-AppSourceSubmission to work. 

But it seems like there is an Issure with the encoding when posting or putting content. 

First error I recieved was in.
https://github.com/microsoft/navcontainerhelper/blob/7d5fbb4c0e14bdfbc278150606c44bb3f41816ed/AppSource/New-AppSourceSubmission.ps1#L151

If the filename has any special characters (äöü) then the request fails with `internal server error (500)`.
There is an easy workaround. I just renamed the file.  

But for the second problem there is no easy workaround. 

The following line "reuploads" the terms and services which need to have special characters. 

https://github.com/microsoft/navcontainerhelper/blob/7d5fbb4c0e14bdfbc278150606c44bb3f41816ed/AppSource/New-AppSourceSubmission.ps1#L221

Just because was curious i edited the terms and services to "Test". 

That "fixed" it. 

Just as a note the terms were correctly printed in the log which could mean the get works fine.

**Comment by freddydk** [comment]
Will investigate, thanks Jonas

**Comment by freddydk** [comment]
This is apparently a bug in PowerShell - if your body contains UTF-8 characters - you cannot transfer a json string - you need to transfer a byte[]

**Comment by jonaswre** [comment]
It seems like json and powershell are arch rivals. Thanks for the fix.

**Comment by freddydk** [comment]
Shipped in 4.0.3
