### ISSUE TITLE
403 Forbidden reported when running Get-BcEnvironments for BcSaaS

### ISSUE THREAD

**Issue by adejsy** [microsoft/navcontainerhelper#2694]
We are testing the BcSaaS parts of the bccontainerhelper. We are trying to do a simple call to Get-Environments and constantly receive 403 forbidden error message. We are testing using the OAuth2 flow. We have an App Registration in our Azure AD tenant and can call web services and other API's fine using this. Is there something we are missing in the setup to allow these API's to work for BcSaaS?

![image](https://user-images.githubusercontent.com/63508365/191456118-4c1e3991-2dbe-47d0-9eca-6a34519f725e.png)

![image](https://user-images.githubusercontent.com/63508365/191457275-52b11268-2406-4150-8324-d4b4ef26088e.png)

BcContainerHelper is version 4.0.2
BcContainerHelper is running as Administrator
Edition	Windows 11 Pro
Version	21H2
OS build	22000.978
Processor	Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz   2.40 GHz
Installed RAM	32.0 GB (31.8 GB usable)
System type	64-bit operating system, x64-based processor

Same errors are raised even for our tenant global administrator.

**Comment by adejsy** [comment]
Further update as it seems to work with Credentials.

![image](https://user-images.githubusercontent.com/63508365/191481735-3e279c4c-849f-46ce-8b2b-07b8162b9591.png)

**Comment by freddydk** [comment]
I don't think the admin center API supports S2S yet.
And when it does, you might need to specify scopes or resources to the New-BcAuthContext.

**Comment by adejsy** [comment]
That seems to be the issue. Automation API works fine for S2S but Admin API doesn't seem to - although, haven't tried messing around with any scopes outside .default

**Comment by freddydk** [comment]
The PM for this just told me that they expect S2S to be available for admin center late October / start November

**Comment by adejsy** [comment]
Awesome. Thank you for confirming.
