### ISSUE TITLE
Error DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by lvvagain** [microsoft/navcontainerhelper#2696]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Hi,
I am trying to build BC container. It seems to be running, but web client returns error DNS_PROBE_FINISHED_NXDOMAIN.
Originally I've built on Win 10 machine, but then I started from scratch and created 
Azure VM with Windows Server 2019 as mentioned in here http://aka.ms/getbc 
From <https://freddysblog.com/2020/10/12/troubleshooting-business-central-on-docker/> 

Still getting same error. Would you please advise what I am doing wrong?
I've tried with and without  -isolation hyperv

Thank you,
Lidia

**Scripts used to create container and cause the issue**
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'us' -select 'Latest'
$LicenseFile = "C:\TEMPLVV\D365BC_V20_5356620.flf"
$containerName = 'BC20-04'
$password = ************
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'lidia', $securePassword
$auth = 'UserPassword'
New-BcContainer -accept_eula `
 -licenseFile $LicenseFile `
 -containerName $containerName `
 -credential $credential `
 -auth $auth `
 -artifactUrl $artifactUrl `
 -includeTestToolkit `
 -includeAL `
 -isolation hyperv

**Full output of scripts**
BcContainerHelper is version 4.0.2
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 20.10.18
Docker Server Version is 20.10.17
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.17763.3406
Creating Container BC20-04
Style: onprem
Multitenant: No
Version: 20.5.45456.45889
Platform: 20.0.45448.45882
Generic Tag: 1.0.2.13
Container OS Version: 10.0.17763.3406 (ltsc2019)
Host OS Version: 10.0.17763.3406 (ltsc2019)
Using hyperv isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\TEMPLVV\D365BC_V20_5356620.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\BC20-04\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container BC20-04 from image mcr.microsoft.com/businesscentral:10.0.17763.3406
5a055cde8418ff55d91c7b0dd1b79e632306e24d685c41edaf7b2c859e5c940c
Waiting for container BC20-04 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/20.5.45456.45889/us
Using installer from C:\Run\150-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\20.5.45456.45889\platform\ServiceTier\Program Files
c:\dl\onprem\20.5.45456.45889\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\20.5.45456.45889\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\20.5.45456.45889\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\onprem\20.5.45456.45889\platform\WebClient\Microsoft Dynamics NAV
Copying Client Files
c:\dl\onprem\20.5.45456.45889\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\20.5.45456.45889\platform\LegacyDlls\program files\Microsoft Dynamics NAV
c:\dl\onprem\20.5.45456.45889\platform\LegacyDlls\systemFolder
Copying ModernDev Files
c:\dl\onprem\20.5.45456.45889\platform
c:\dl\onprem\20.5.45456.45889\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\20.5.45456.45889\us\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\20.5.45456.45889\platform\Test Assemblies
Copying Applications
C:\dl\onprem\20.5.45456.45889\us\Applications
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 260 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.26.192.1 in container hosts file
Starting Container
Hostname is BC20-04
PublicDnsName is BC20-04
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A1D63E3E4294C6DF9C57350E5CAE2F895460F53D
DNS identity BC20-04
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer without SSL
Update configuration: navsettings.json
Done Configuring Web Client
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating lidia as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements.
It should be at least 8 characters long and contain at least one uppercase
letter, one lowercase letter, and one number.
Container IP Address: 172.26.197.72
Container Hostname  : BC20-04
Container Dns Name  : BC20-04
Web Client          : http://BC20-04/BC/
Dev. Server         : http://BC20-04
Dev. ServerInstance : BC

Files:
http://BC20-04:8080/ALLanguage.vsix

Container Total Physical Memory is 8.5Gb
Container Free Physical Memory is 6.1Gb

Initialization took 75 seconds
Ready for connections!
Reading CustomSettings.config from BC20-04
Creating Desktop Shortcuts for BC20-04
Skipping app 'C:\Applications\TestFramework\TestLibraries\permissions mock\Microsoft_Permissions Mock.app' as it is already installed
Skipping app 'C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app' as it is already installed
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\37519cb8-9551-4046-819a-fa4ce560222e\Microsoft_Any.app
Synchronizing Any on tenant default
Installing Any on tenant default
App Microsoft_Any.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\cd9add6c-cf7a-417e-b18f-d9c016c39d67\Microsoft_Library Assert.app
Synchronizing Library Assert on tenant default
Installing Library Assert on tenant default
App Microsoft_Library Assert.app successfully published
Skipping app 'C:\Applications\TestFramework\TestLibraries\permissions mock\Microsoft_Permissions Mock.app' as it is already installed
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\cebe61e9-04e3-4c16-8122-95b5cfbfbdf7\Microsoft_Library Variable Storage.app
Synchronizing Library Variable Storage on tenant default
Installing Library Variable Storage on tenant default
App Microsoft_Library Variable Storage.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\74facae3-5c27-4301-a235-3ada5192007d\Microsoft_System Application Test Library
.app
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
App Microsoft_System Application Test Library.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\48114adf-1f63-4e67-a988-696e5ba8d8bf\Microsoft_Tests-TestLibraries.app
Synchronizing Tests-TestLibraries on tenant default
Installing Tests-TestLibraries on tenant default
App Microsoft_Tests-TestLibraries.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\faa15e19-14d5-4fce-b908-13c220a99b8e\Microsoft_Tests-Bank.app
Synchronizing Tests-Bank on tenant default
Installing Tests-Bank on tenant default
App Microsoft_Tests-Bank.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\fcd73d72-dd5e-47e5-8691-76677d2928c1\Microsoft_Tests-Cash Flow.app
Synchronizing Tests-Cash Flow on tenant default
Installing Tests-Cash Flow on tenant default
App Microsoft_Tests-Cash Flow.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\06180e24-a9e7-4e1f-8b08-af1dcc18d326\Microsoft_Tests-Cost Accounting.app
Synchronizing Tests-Cost Accounting on tenant default
Installing Tests-Cost Accounting on tenant default
App Microsoft_Tests-Cost Accounting.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\d650f92b-37e4-4e78-a8ab-22a599712c95\Microsoft_Tests-CRM integration.app
Synchronizing Tests-CRM integration on tenant default
Installing Tests-CRM integration on tenant default
App Microsoft_Tests-CRM integration.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\c386dc4c-8ce2-477b-97a0-160b1156677c\Microsoft_Tests-Data Exchange.app
Synchronizing Tests-Data Exchange on tenant default
Installing Tests-Data Exchange on tenant default
App Microsoft_Tests-Data Exchange.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\bf39ddcd-6067-4f78-8f6d-df22127fbbf4\Microsoft_Tests-Dimension.app
Synchronizing Tests-Dimension on tenant default
Installing Tests-Dimension on tenant default
App Microsoft_Tests-Dimension.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\b637136c-a2c2-4534-bc48-a8618ebc950b\Microsoft_Tests-ERM.app
Synchronizing Tests-ERM on tenant default
Installing Tests-ERM on tenant default
App Microsoft_Tests-ERM.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\45614599-cf21-4236-8792-ccfdc13bd1bc\Microsoft_Tests-Fixed Asset.app
Synchronizing Tests-Fixed Asset on tenant default
Installing Tests-Fixed Asset on tenant default
App Microsoft_Tests-Fixed Asset.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\e667c2a6-8235-4e94-b807-474541f2231e\Microsoft_Tests-General Journal.app
Synchronizing Tests-General Journal on tenant default
Installing Tests-General Journal on tenant default
App Microsoft_Tests-General Journal.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\07096482-c484-4903-9d12-c243ce51f3e5\Microsoft_Tests-Graph.app
Synchronizing Tests-Graph on tenant default
Installing Tests-Graph on tenant default
App Microsoft_Tests-Graph.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\d7d2cabf-7534-417d-a08a-b988aef3cb70\Microsoft_Tests-Integration.app
Synchronizing Tests-Integration on tenant default
Installing Tests-Integration on tenant default
App Microsoft_Tests-Integration.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\cced679e-4a14-4203-aafe-98aff7c6fab8\Microsoft_Tests-Invoicing.app
Synchronizing Tests-Invoicing on tenant default
Installing Tests-Invoicing on tenant default
App Microsoft_Tests-Invoicing.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\f1c80084-955c-4b83-b8ed-c06349285c49\Microsoft_Tests-Job.app
Synchronizing Tests-Job on tenant default
Installing Tests-Job on tenant default
App Microsoft_Tests-Job.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\0975ff6b-dace-4454-99ea-ac99a01fe623\Microsoft_Tests-Local.app
Synchronizing Tests-Local on tenant default
Installing Tests-Local on tenant default
App Microsoft_Tests-Local.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\1f1eef16-63bc-4981-9e43-5289642597d4\Microsoft_Tests-Marketing.app
Synchronizing Tests-Marketing on tenant default
Installing Tests-Marketing on tenant default
App Microsoft_Tests-Marketing.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\07b14438-0dc2-46a1-9922-17fbe351d023\Microsoft_Tests-Misc.app
Synchronizing Tests-Misc on tenant default
Installing Tests-Misc on tenant default
App Microsoft_Tests-Misc.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\caa18f07-01c3-487d-b851-c7923297998d\Microsoft_Tests-Monitor Sensitive Fields.
app
Synchronizing Tests-Monitor Sensitive Fields on tenant default
Installing Tests-Monitor Sensitive Fields on tenant default
App Microsoft_Tests-Monitor Sensitive Fields.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\a946938a-aa86-414d-b666-56c3ac16ecef\Microsoft_Tests-Permissions.app
Synchronizing Tests-Permissions on tenant default
Installing Tests-Permissions on tenant default
App Microsoft_Tests-Permissions.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\f73bcc43-8701-4c51-86eb-021174ae925f\Microsoft_Tests-Physical Inventory.app
Synchronizing Tests-Physical Inventory on tenant default
Installing Tests-Physical Inventory on tenant default
App Microsoft_Tests-Physical Inventory.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\b6f52590-9b17-493b-9ae1-3a59f94325d5\Microsoft_Tests-Prepayment.app
Synchronizing Tests-Prepayment on tenant default
Installing Tests-Prepayment on tenant default
App Microsoft_Tests-Prepayment.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\a9875bcd-02d6-4f1c-abd9-1201ccb83570\Microsoft_Tests-Rapid Start.app
Synchronizing Tests-Rapid Start on tenant default
Installing Tests-Rapid Start on tenant default
App Microsoft_Tests-Rapid Start.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\7dbd1be3-bd81-4487-b9c5-fd375d8e6d96\Microsoft_Tests-Report.app
Synchronizing Tests-Report on tenant default
Installing Tests-Report on tenant default
App Microsoft_Tests-Report.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\65ef0002-9b56-49df-85b8-ed7bb2c4824d\Microsoft_Tests-Resource.app
Synchronizing Tests-Resource on tenant default
Installing Tests-Resource on tenant default
App Microsoft_Tests-Resource.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\1d18b613-076b-4b49-934f-7f1701f71b88\Microsoft_Tests-Reverse.app
Synchronizing Tests-Reverse on tenant default
Installing Tests-Reverse on tenant default
App Microsoft_Tests-Reverse.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\a6185405-ebf5-49b3-9bbd-341b05db35ee\Microsoft_Tests-SCM.app
Synchronizing Tests-SCM on tenant default
Installing Tests-SCM on tenant default
App Microsoft_Tests-SCM.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\b306c7df-90fc-4b02-8df1-ff2696b66d5e\Microsoft_Tests-SMB.app
Synchronizing Tests-SMB on tenant default
Installing Tests-SMB on tenant default
App Microsoft_Tests-SMB.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\d6431002-cf72-49f1-84be-1f8f63ec1d83\Microsoft_Tests-Upgrade.app
Synchronizing Tests-Upgrade on tenant default
Installing Tests-Upgrade on tenant default
App Microsoft_Tests-Upgrade.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\a270d86c-efd1-4163-8015-190c785cc758\Microsoft_Tests-User.app
Synchronizing Tests-User on tenant default
Installing Tests-User on tenant default
App Microsoft_Tests-User.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\701fce3f-af7f-4407-99d7-d2a5d03de32d\Microsoft_Tests-VAT.app
Synchronizing Tests-VAT on tenant default
Installing Tests-VAT on tenant default
App Microsoft_Tests-VAT.app successfully published
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC20-04\1a7b5b9d-ef07-4cf6-989b-1608a1bbee20\Microsoft_Tests-Workflow.app
Synchronizing Tests-Workflow on tenant default
Installing Tests-Workflow on tenant default
App Microsoft_Tests-Workflow.app successfully published
TestToolkit successfully imported
Creating .net Assembly Reference Folder for VS Code

 Synchronization progress Starting synchronization process
 Synchronization progress Starting synchronization process
 Synchronization progress Starting synchronization process
 Synchronization progress Starting synchronization process
 Synchronization progress Starting synchronization process
 30 activities not shown...

Use:
Get-BcContainerEventLog -containerName BC20-04 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName BC20-04 to get debug information about the container
Enter-BcContainer -containerName BC20-04 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName BC20-04 to remove the container again
docker logs BC20-04 to retrieve information about URL's again

**Screenshots**
![image](https://user-images.githubusercontent.com/49447566/191608904-7bfe8f9a-a00c-4b85-bc8f-dece9d26b3fe.png)

**Comment by jonaswre** [comment]
Hi, 

This error points to a DNS problem. 

There is an option "updateHosts" which creates an entry within your host file. This allows window to resolve bc20-04 to the IP of the container. 

It might be worth to look at the hosts file and check if there is an entry for bc20-04. 

If that's not the case rerun the container with the updateHosts option. (check the documentation for the exact spelling) 

If that's the case the only explanation I have  is that the container somehow got a new IP assigned which doesn't match.

**Comment by lvvagain** [comment]
Thank you so much for your help. It did work, I see it from host VM.

**Comment by lvvagain** [comment]
Closing
