### ISSUE TITLE
Can not create NAV 2016 container.

### ISSUE THREAD

**Issue by nubizerha** [microsoft/navcontainerhelper#2706]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

I try to create a new NAV 2016 on docker, but i got this error:

DockerDo : docker: Error response from daemon: container 33ccae54bfdcbceccd4d29ea06614544e8a52ced96104f345950f17b7e897396 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or containe
r exited unexpectedly. (0xc0370106).

**Scripts used to create container and cause the issue**

$containerName = 'nav2016'
Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force
Update-Module BcContainerHelper
$artifacturl = Get-BCArtifactUrl -type OnPrem -version 9.0.45480.0 -country dk -select Closest
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String '@1234!' -AsPlainText -Force)
New-BCContainer -accept_eula -containerName $containerName -artifactUrl $artifacturl -auth NavUserPassword -Credential $credential -updateHosts -useBestContainerOS -alwaysPull -enableSymbolLoading -includeCSide -licenseFile C:\BC-kunde-Workspace\Licens\NAV2016.flf -shortcuts DesktopFolder -myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/override/SelfSignedCertificateEx/SetupCertificate.ps1")

**Full output of scripts**

BcContainerHelper is version 4.0.3
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Enterprise - 21H1
Docker Client Version is 20.10.17
Docker Server Version is 20.10.17
Removing entries from hosts
Removing nav2016 from container hosts file
Removing nav2016-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\nav2016
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Pulling image mcr.microsoft.com/businesscentral:10.0.19041.1415
10.0.19041.1415: Pulling from businesscentral
Digest: sha256:8f994521bb757c5c09687dd7484c8696b015ee4dde430fb141b1e560162bb6b0
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.19041.1415
mcr.microsoft.com/businesscentral:10.0.19041.1415
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container nav2016
Style: onprem
Multitenant: No
Version: 9.0.45480.0
Platform: 9.0.45480.0
Generic Tag: 1.0.2.13
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19043.2006 (21H1)
WARNING: Host OS is 21H1 and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
WARNING: Using process isolation on Windows Desktop OS with generic image version prior to 1.0.2.4 or NAV/BC versions prior to 15.0, might require you to use HyperV isolation or disable Windows Defender while creating the container
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\nav2016\my\SetupCertificate.ps1
Using license file C:\BC-kunde-Workspace\Licens\NAV2016.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\nav2016\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupCertificate.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container nav2016 from image mcr.microsoft.com/businesscentral:10.0.19041.1415
33ccae54bfdcbceccd4d29ea06614544e8a52ced96104f345950f17b7e897396
New-BCContainer Telemetry Correlation Id: ec5d77b8-83f8-41ee-8238-10c253e4e1d4
DockerDo : docker: Error response from daemon: container 33ccae54bfdcbceccd4d29ea06614544e8a52ced96104f345950f17b7e897396 encountered an error during hcsshim::System::Start: failure in a Windows system call: The virtual machine or containe
r exited unexpectedly. (0xc0370106).
ExitCode: 125
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav=2016 --label cu=cu6 --env isBcSandbox=N --label version=9.0.45480.0 --label platform=9.0.45480.0 --label country=dk --env artifactUrl=https://bcartifacts.azureedge.n
et/onprem/9.0.45480.0/dk --env licenseFile="c:\run\my\license.flf" --name nav2016 --hostname nav2016 --env auth=NavUserPassword --env username="admin" --env ExitOnError=N --env locale=da-DK --env databaseServer="" --env databaseInstance=""
 --volume "C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume "C:\ProgramData\BcContainerHelper\Extensions\nav2016\my:C:\Run\my" --isolation process --restart unless-stopped --env filesOnly=False --env useSSL=N --v
olume "C:\ProgramData\BcContainerHelper\Extensions\nav2016\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345MgB8AEIAcQArAEEARwBkAHoAQQBMAHkARABKADYALw
B0AFUAZQByAGwASwBTAGcAPQA9AHwAYQAyADEAOAAzAGIANwBkAGYAMQA3AGYANQAzAGIAZQAxAGMAMwA2ADIAYgBjADUAZgAwAGMAMQBmADUAMgA2AA== --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --de
tach mcr.microsoft.com/businesscentral:10.0.19041.1415
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.3\ContainerHandling\New-NavContainer.ps1:1917 char:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

![2022-09-27_10-21-18](https://user-images.githubusercontent.com/112636442/192473304-c5439a89-1c58-4b42-9d58-2ca8ba5dd11e.png)

**Comment by freddydk** [comment]
I assume that you also cannot create Business Central containers on that machine.
Typically, error 125 is machine specific and can often be resolved by adding -isolation hyperv
(or upgrading to Windows 11)
