### ISSUE TITLE
Get-BCArtifactUrl -select NextMajor -sasToken $sasToken returns empty string

### ISSUE THREAD

**Issue by phenno1** [microsoft/navcontainerhelper#2721]
Hello Freddy,

**Describe the issue**
Our pipelines are failing due to Get-BCArtifactUrl does not return value for NextMajor and supplied SaaS Token. It works for NextMinor returning 21.1.47318.0 but not for the NextMajor

**Scripts used to create container and cause the issue**
```
Get-BCArtifactUrl -sasToken $sasToken -select NextMajor
```

**Full output of scripts**
```
PS C:\WINDOWS\system32> Get-BCArtifactUrl -sasToken $sasToken -select NextMajor
PS C:\WINDOWS\system32>
```

**Additional context**
It started somewhere around new version BC21 is announced. BCContainerHelper is updated to the latest version: 4.0.5

**Comment by freddydk** [comment]
Correct, there is no NextMajor at the moment.
Should resume one of the next days
