### ISSUE TITLE
Run-AlValidation Failue

### ISSUE THREAD

**Issue by dkorinets** [microsoft/navcontainerhelper#2724]
Hi Freddy, 

BcContainerHelper 4.0.5 
BC21

My Run-AlValidation pipeline fails due to the reason: 
 error AL0126: No overload for method 
   ateCustomer\u0027 takes 1 arguments. Candidates: \u0027CreateCustomer()\u0027 defined in Table \u0027Contact\   
  u0027 by the extension Base Application by Microsoft (21.0.46256.47495)"

But the code itself is shielded by the preprocessor option. 

```
    local procedure CreateCustomerFromTemplate(Contact: record Contact; CustomerTemplateCode: Code[20]): code[20];
    begin
        If Context.IsCustomerTemplFeatureEnabled() then
            exit(Contact.CreateCustomerFromTemplate(CustomerTemplateCode));
#if not GreaterThanBC20
        exit(Contact.CreateCustomer(CustomerTemplateCode));
#endif
    end;
```

at the same time, marketplace validation works fine. 
![image](https://user-images.githubusercontent.com/31474116/194566612-e13d76c4-bc6e-4ef3-8bfc-36431110bee1.png)
Please advice.

**Comment by freddydk** [comment]
What is the application property in app.json?
Which parameters are you using when running Run-AlValidation? (full command)

**Comment by dkorinets** [comment]
Sent. 
Thanks

**Comment by freddydk** [comment]
Cannot repro this - preprocessor symbols should be used since 2.0.6 (issue #1704)

What parameters are you using in Run-AlValidation?

I tried with:
Run-AlValidation -apps $appFile -validateCurrent -countries "us" -affixes $affixes

and that returns success.

**Comment by freddydk** [comment]
@dkorinets do you still have this problem?

**Comment by dkorinets** [comment]
Hi @freddydk 
with 4.0.6-preview738 works

**Comment by freddydk** [comment]
Strange - I didn't change anything - must have been the parameters used to run the validation somehow.

**Comment by dkorinets** [comment]
The parameters are the same as before, the only difference in the version of BcContainerHelper, previously it was 4.0.5.
I'll let you know if happens again for some reason.
Thx
