### ISSUE TITLE
 Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/navcontainerhelper#2728]
we are getting this error on 21: Error: An error occurred while sending the request. The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel..

**Comment by freddydk** [comment]
I have absolutely no idea where, what, which command or how you get this.
I need much much more information if I need to look at this,

**Comment by shashiBssi** [comment]
Our app wants to make an API call to stripe.
In version 21 we get this error. In version 20 or lower we don't get any such error.
I can ping bing.com for om within the container.

**Comment by freddydk** [comment]
I don't think this is related to docker and it isn't something I would be able to troubleshoot from here.

**Comment by shashiBssi** [comment]
BcContainerHelper is version 3.0.11
BcContainerHelper is running as administrator
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Pro - 21H2
Docker Client Version is 20.10.13
Docker Server Version is 20.10.13
Removing entries from hosts
Removing atti2 from container hosts file
Removing atti2-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\atti2
Downloading application artifact /sandbox/21.1.47672.0/us
Downloading C:\Users\shashi\AppData\Local\Temp\0ca0260c-0a0d-4dfe-a017-a51979a1ec82.zip
Unpacking application artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/21.1.47672.0/platform
Downloading C:\Users\shashi\AppData\Local\Temp\ecda7b92-0266-40ed-a86d-fdea7107c92d.zip
Unpacking platform artifact to tmp folder using Expand-Archive
Could not rename 'c:\bcartifacts.cache\sandbox\21.1.47672.0\0pvq0put.onn' retrying in 5 seconds.
Retrying...
Could not rename 'c:\bcartifacts.cache\sandbox\21.1.47672.0\0pvq0put.onn' retrying in 5 seconds.
Retrying...
Could not rename 'c:\bcartifacts.cache\sandbox\21.1.47672.0\0pvq0put.onn' retrying in 5 seconds.
Retrying...
Could not rename 'c:\bcartifacts.cache\sandbox\21.1.47672.0\0pvq0put.onn' retrying in 5 seconds.
Retrying...
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\21.1.47672.0\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\O
penXMLSDKv25.msi
Downloading c:\bcartifacts.cache\sandbox\21.1.47672.0\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_
x64.msi
Downloading c:\bcartifacts.cache\sandbox\21.1.47672.0\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-Windo
wsHosting.exe
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container atti2
Style: sandbox
Multitenant: Yes
Version: 21.1.47672.0
Platform: 21.0.47658.0
Generic Tag: 1.0.2.13
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19044.2075 (21H2)
WARNING: Host OS is 21H1 and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation
 hyperv.
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file D:\BC-V20-September.flf
Files in C:\ProgramData\BcContainerHelper\Extensions\atti2\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container atti2 from image mcr.microsoft.com/businesscentral:10.0.19041.1415
0989f2614bebbed7ac4318e60864d5a6733c2c54c963aaa6719aeed0e75c2092
Waiting for container atti2 to be ready
Using artifactUrl https://bcinsider.azureedge.net/sandbox/21.1.47672.0/us
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\21.1.47672.0\platform\ServiceTier\Program Files
c:\dl\sandbox\21.1.47672.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\21.1.47672.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\21.1.47672.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\21.1.47672.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\21.1.47672.0\platform
c:\dl\sandbox\21.1.47672.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\21.1.47672.0\us\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\21.1.47672.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\21.1.47672.0\us\Extensions
Copying Applications
C:\dl\sandbox\21.1.47672.0\platform\Applications
Copying Applications.US
C:\dl\sandbox\21.1.47672.0\us\Applications.US
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 585 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.22.32.1 in container hosts file
Starting Container
Hostname is atti2
PublicDnsName is atti2
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint EBEC92889758F5D3A9C63B5698C40EA918BC5BED
DNS identity atti2
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer without SSL
Update configuration: navsettings.json
Done Configuring Web Client
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Dismounting Tenant
Mounting Tenant
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Creating http download site
Setting SA Password and enabling SA
Creating sv as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Assign Premium plan for SV
Container IP Address: 172.22.38.203
Container Hostname  : atti2
Container Dns Name  : atti2
Web Client          : http://atti2/BC/?tenant=default
Dev. Server         : http://atti2
Dev. ServerInstance : BC
Dev. Server Tenant  : default
Setting atti2 to 172.22.38.203 in host hosts file
Setting atti2-default to 172.22.38.203 in host hosts file
Setting atti2-default to 172.22.38.203 in container hosts file

Files:
http://atti2:8080/ALLanguage.vsix

WARNING: You are running a container which is 214 days old.
Microsoft recommends that you always run the latest version of our containers.

Container Total Physical Memory is 31.9Gb
Container Free Physical Memory is 6.5Gb

Initialization took 165 seconds
Ready for connections!
Reading CustomSettings.config from atti2
Creating Desktop Shortcuts for atti2
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Windows\Microsoft.NET\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\210\Service to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container atti2 successfully created

Use:
Get-BcContainerEventLog -containerName atti2 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName atti2 to get debug information about the container
Enter-BcContainer -containerName atti2 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName atti2 to remove the container again
docker logs atti2 to retrieve information about URL's again

**Comment by jonaswre** [comment]
Has the base image changed? 
The chain of trust seams to be broken. 
Maybe the CA is no longer trusted or the certificate uses a "bad" cipher.
You should get the same error when doing the request directly with powershell in the container.

**Comment by freddydk** [comment]
But then 20 would also fail, right?

**Comment by jonaswre** [comment]
If it changed between testing in 20 and testing 21. You might get the impression it worked in 20 and not in 21. 

I'm just trying to narrow it down. 

I suggested running the requests in PowerShell, that might give you a better error. And maybe helps narrowing it down. The OS validates the trust so I also don't think navcontainerhelper is responsible here.

**Comment by antonioaayala** [comment]
Hello,

I hace same issue but when I deploy my app on docker Onpremise container Client.Send works correctly, but whe i deploy to production or Sandox on SaaS, I got the error "Could not create SSL/TLS secure channel...."

My code is 

    var
        CB64: Codeunit "Base64 Convert";
        Client: HttpClient;

        Request: HttpRequestMessage;
        Content: HttpContent;
        Response: HttpResponseMessage;
        RequestHeaders: HttpHeaders;
        ContentHeaders: HttpHeaders;
        CertString: Text;
        ContentString: Text;
        ResponseString: Text;
        AuthString: Text;

    begin
        Clear(Client);


        Request.SetRequestUri('https');
        Request.Method := 'GET';

        AuthString := 'Basic xxxxxxxxxxxxxxxxxx';
        Client.DefaultRequestHeaders.Add('Authorization', AuthString);
        Client.DefaultRequestHeaders.Add('User-Agent', 'Dynamics 365');
        Client.Get('https', Response);


        Response.Content.ReadAs(ResponseString);
        Message(Format(Response.HttpStatusCode));
        message(ResponseString);
	end;


I have tried wiht Client.Send to


Thanks

**Comment by freddydk** [comment]
@antonioaayala - please do not reply to a closed topic.
If the solution in this topic didn't solve your issue, please create a new issue and include as much information as possible.
Based on the very brief information supplied, I cannot think of other things than you are trying to connect to an endpoint, which has a self-signed certificate, trusted by your container but not by the public cloud.
