### ISSUE TITLE
New-BcAuthContext error authenticating in Partner Center submission API

### ISSUE THREAD

**Issue by jose-lloret** [microsoft/navcontainerhelper#2729]
**Describe the issue**
I'm getting an error (refresh_token property does not exist) when I run the New-BcAuthContext command with the scope "https://api.partner.microsoft.com/.default" following the instructions in [Automatic AppSource Submission of Business Central apps](https://freddysblog.com/2022/09/22/automatic-appsource-submission-of-business-central-apps/) to publish our apps via PowerShell in the AppSource with the User Impersonation way.

**Scripts used to create container and cause the issue**

```
New-BcAuthContext `
   -includeDeviceLogin `
   -scopes "https://api.partner.microsoft.com/.default" `
   -tenantID "my-azure-aad-tenant-id"
```

**Full output of scripts**

```
Attempting authentication to https://api.partner.microsoft.com/.default using device login...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code DEVCODE to authenticate.
Waiting for authentication...
Authenticated from xxx.xxx.xxx..xxx as user My User Name (my@email.address)
New-BcAuthContext Telemetry Correlation Id: e66877e6-b032-417c-9a2a-dabbafe116f3
No se encuentra la propiedad 'refresh_token' en este objeto. Compruebe que existe.
En C:\Users\jlloret\Documents\WindowsPowerShell\Modules\BcContainerHelper\4.0.5\BcSaaS\New-BcAuthContext.ps1: 307 Carácter: 17
+                 $authContext += @{
+                 ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
...
```

**Additional context**

This is the line with the error:

```
                $authContext += @{
                    "AccessToken"  = $accessToken
                    "UtcExpiresOn" = [Datetime]::UtcNow.AddSeconds($TokenRequest.expires_in)
                    "RefreshToken" = $TokenRequest.refresh_token
                    "Credential"   = $null
                    "ClientSecret" = $null
                    "appid"        = ""
                    "name"         = $jwtToken.name
                    "upn"          = $jwtToken.unique_name
                }
```

And this is the value of the $TokenRequest variable while debugging the script:

```
$TokenRequest :
    token_type: "Bearer"
    scope: "https://api.partner.microsoft.com/user_impersonation https://api.partner.microsoft.com/.default"
    expires_in: 3891
    ext_expires_in: 3891
    access_token: "eyJ....vA"
    foci:1
```

**Comment by freddydk** [comment]
There is a copy/paste error in the blog post:-(
Have fixed that.
the New-BcAuthContext with refreshtoken should be:

```
$authcontext = New-BcAuthContext `
    -refreshToken $refreshtoken `
    -Scopes "https://api.partner.microsoft.com/user_impersonation offline_access" `
    -tenantID "<your AAD tenant>"
```

**Comment by jose-lloret** [comment]
Thanks Freddy!
Now it's working properly.

**Comment by dkorinets** [comment]
Hi Freddy, 

Adding the refresh token  doesn't work for me 
Script:
`$authcontext = New-BcAuthContext `
    -refreshToken $refreshtoken `
    -includeDeviceLogin `
    -Scopes "https://api.partner.microsoft.com/.default" `
    -tenantID "My AAD Tenant"`

Output: 
`New-BcAuthContext Telemetry Correlation Id: 3ddfb436-8478-4ab3-a60e-2d3a482da9d3
The property 'refresh_token' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.6\BcSaaS\New-BcAuthContext.ps1:307 char:17
+                 $authContext += @{
+                 ~~~~~~~~~~~~~~~~~~`
Debugging: 
![image](https://user-images.githubusercontent.com/31474116/198019990-26ce84f0-6ee5-4484-91e5-f740bed847c7.png)

Please advice

**Comment by dkorinets** [comment]
great, thanks
