### ISSUE TITLE
Latest docker image not working for Business central 2022 wave 2 (v21 version) 

### ISSUE THREAD

**Issue by hrvojesuta** [microsoft/navcontainerhelper#2733]
After creating new docker image for Business central 2022 wave 2 from scratch could not download symbols because it keeps telling that the code does not meet Universal Code requirement.

I have used the latest image for creating the docker container
$artifactUrl = Get-BCArtifactUrl -country w1 -type Sandbox -select Latest

After trying to download symbols I get error code not compliant with Universal Code requirement.
![image](https://user-images.githubusercontent.com/13482773/195531102-ec38cb98-da5f-4d66-af86-bef73cd11bd4.png)

Error message: 
[2022-10-13 09:29:56.78] The request for path /BC/dev/packages?publisher=Microsoft&appName=Base%20Application&versionText=20.0.0.0&appId=437dbf0e-84ff-417a-965d-ed2bb9650972&tenant=default failed with code InternalServerError. Reason: Sorry, we can’t sign you in because the following apps don’t meet our Universal Code requirement :

_Exclude_AnonymizedDataSharing_ by Microsoft
_Exclude_APIV1_ by Microsoft
_Exclude_APIV2_ by Microsoft
_Exclude_Bank Deposits by Microsoft
_Exclude_Connectivity Apps by Microsoft
_Exclude_Email Logging Using Graph API by Microsoft
_Exclude_Microsoft Dynamics 365 - SmartList by Microsoft
_Exclude_PlanConfiguration_ by Microsoft
_Exclude_ReportLayouts by Microsoft
Base Application by Microsoft
Business Central Cloud Migration - Previous Release by Microsoft
Business Central Intelligent Cloud by Microsoft
Company Hub by Microsoft
Email - Outlook REST API by Microsoft
Email - SMTP API by Microsoft
Email - SMTP Connector by Microsoft
Intelligent Cloud Base by Microsoft
Intrastat Core by Microsoft
Late Payment Prediction by Microsoft
Payment Links to PayPal by Microsoft
Recommended Apps by Microsoft
Sales and Inventory Forecast by Microsoft
Send remittance advice by email by Microsoft
Send To Email Printer by Microsoft
Shopify Connector by Microsoft
Simplified Bank Statement Import by Microsoft
System Application by Microsoft
Troubleshoot FA Ledger Entries by Microsoft
Universal Print Integration by Microsoft
VAT Group Management by Microsoft

You must either upgrade the apps to meet the requirement or license the non-Universal Code module that grants an exception to the requirement.

For more information, see https://aka.ms/bcUniversalCode.

**Comment by freddydk** [comment]
What license are you using?
You need a new license file for version 21, did you create a new license already?
If you did, it might be wrong, so please create a new one.

**Comment by hrvojesuta** [comment]
I'm using licence file v21 that was created 10 days ago.
I created per your instructions a new v21 licence and now it is working.
You were correct the licence file I was using was not working, after creating a new one everything is working.
![image](https://user-images.githubusercontent.com/13482773/195554016-119b4db1-b1b7-4f0d-aba1-0a0cf112db52.png)
![image](https://user-images.githubusercontent.com/13482773/195554287-a14dde36-3d73-494f-b713-d601c8fb0088.png)

Thank you.
