### ISSUE TITLE
New-BcContainer 'Sandbox'  NextMajor. The license file is corrupt.

### ISSUE THREAD

**Issue by dkorinets** [microsoft/navcontainerhelper#2734]
hi Freddy, 
Have an issue with my nextMajor pipeline.

"The license file is corrupt. Error Code: Unknown error." 
The dev license was generated today (13.10.22) for BC21. compatible with the current release and all other old BC releases. 

`$containerName = 'bc22-us'
$auth = 'UserPassword'
$navAdminUsername = "bc"
$securePassword = convertto-securestring "bc" -asplaintext -force
$credential = New-Object System.Management.Automation.PSCredential($navAdminUsername, $securePassword)
$sasToken = "?sv=....3D"
$artifactUrl = Get-BcArtifactUrl -country 'us' -type 'Sandbox' -select NextMajor -sasToken $sasToken
$licenseFileUri = "C:\...\Scripts\5331246.flf"
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -multitenant:$false `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -includePerformanceToolkit `
    -assignPremiumPlan `
    -licenseFile $licenseFileUri `
    -memoryLimit 8G `
    -includeAL -doNotExportObjectsToText `
    -vsixFile (Get-LatestAlLanguageExtensionUrl) `
    -updateHosts `
    -EnableTaskScheduler:$false`

`BcContainerHelper is version 4.0.5
BcContainerHelper is running as administrator 
Hyper-V is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 20.10.17
Docker Server Version is 20.10.17
Removing Session bc22-us
Removing container bc22-us
Removing entries from hosts
Removing bc22-us from container hosts file
Removing bc22-us-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\bc22-us
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.18363.1556
Creating Container bc22-us
Style: sandbox
Multitenant: No
Version: 22.0.47754.0
Platform: 22.0.47698.0
Generic Tag: 1.0.2.13
Container OS Version: 10.0.18363.1556 (1909)
Host OS Version: 10.0.18363.2274 (1909)
Using hyperv isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\bc22-us\Microsoft.VisualStudio.Services.VSIXPackage.vsix
Using license file C:\Work\Sana\Dev\NavExtension\Scripts\5331246.flf
Additional Parameters:
--env customNavSettings=EnableTaskScheduler=False
Files in C:\ProgramData\BcContainerHelper\Extensions\bc22-us\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc22-us from image mcr.microsoft.com/businesscentral:10.0.18363.1556
604a5957441bf7ff9db1046d3e294ec6928846c892212b68467e94be040a4ede
Waiting for container bc22-us to be ready
Using artifactUrl https://bcinsider.azureedge.net/sandbox/22.0.47754.0/us
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\22.0.47754.0\platform\ServiceTier\Program Files
c:\dl\sandbox\22.0.47754.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\22.0.47754.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\22.0.47754.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\22.0.47754.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\22.0.47754.0\platform
c:\dl\sandbox\22.0.47754.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\22.0.47754.0\us\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\22.0.47754.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\22.0.47754.0\us\Extensions
Copying Applications
C:\dl\sandbox\22.0.47754.0\platform\Applications
Copying Applications.US
C:\dl\sandbox\22.0.47754.0\us\Applications.US
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 129 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.31.43 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.31.43 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.30.64.1 in container hosts file
Starting Container
Hostname is bc22-us
PublicDnsName is bc22-us
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint AB4782AE3A9F60CD6870B00E85C0A52D7EA1F8BF
DNS identity bc22-us
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer without SSL
Update configuration: navsettings.json
Done Configuring Web Client
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
The license file is corrupt. Error Code: Unknown error.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 196
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcinsider.azureedge.net/sandbox/22.0.47754.0/us
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\22.0.47754.0\platform\ServiceTier\Program Files
c:\dl\sandbox\22.0.47754.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\22.0.47754.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\22.0.47754.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\22.0.47754.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\22.0.47754.0\platform
c:\dl\sandbox\22.0.47754.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\22.0.47754.0\us\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\22.0.47754.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\22.0.47754.0\us\Extensions
Copying Applications
C:\dl\sandbox\22.0.47754.0\platform\Applications
Copying Applications.US
C:\dl\sandbox\22.0.47754.0\us\Applications.US
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 129 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.31.43 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.31.43 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.30.64.1 in container hosts file
Starting Container
Hostname is bc22-us
PublicDnsName is bc22-us
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint AB4782AE3A9F60CD6870B00E85C0A52D7EA1F8BF
DNS identity bc22-us
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer without SSL
Update configuration: navsettings.json
Done Configuring Web Client
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
The license file is corrupt. Error Code: Unknown error.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 196
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
rReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... bc22-us failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc22-us failed`

**Comment by freddydk** [comment]
Could you email me your license file so that I can test it?
freddyk at microsoft dot com

**Comment by dkorinets** [comment]
sent

**Comment by freddydk** [comment]
@dkorinets thanks, I can repro that - but only with the .flf file.
The .bclicense file works.
Please try using the .bclicense file instead of the .flf file.

I have asked the team whether this is as expected or whether the .flf also should work.

**Comment by freddydk** [comment]
Version 22 only supports .bclicense is the answer

**Comment by dkorinets** [comment]
I see, good to kwow. 
Thank you
