### ISSUE TITLE
Business Central Docker NavUserPassword

### ISSUE THREAD

**Issue by marioolleshi** [microsoft/navcontainerhelper#2741]
Hello,
i have created a docker container in windows server 2019 on-premise.It works everything fine in local host. I want to create this docker container using navuserpassword and also expose the port 80 so the different users can login to business central from their own PC. Is this possible and how can i achieve this ?   Thank you.

**Comment by jonaswre** [comment]
Correct me if I'm wrong but navusernamepassword password uses SSL so try 443 from external

**Comment by freddydk** [comment]
Start your container with -useSSL and then have people download and install the certificate - then you should be good on https.
