### ISSUE TITLE
Runtime Package File Naming

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#2744]
When exporting runtime Packages with `Convert-BcAppsToRuntimePackages` Command the resulting file names contains the localization:
AwesomeCorp_AwesomeApp_1.2.3.4.runtime-20.6.47024.0-**_de_**.app

that the platform version should match [is known](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-creating-runtime-packages#limitations), but does this also affect the localization?

if not we should remove this from the filename to not cause confusion.

wouldn't it make more sense to use the platform version by default instead of the application (artifact) version?

https://github.com/microsoft/navcontainerhelper/blob/d04ba6aff03c2b547807a6c1bbb8e713170548a3/AppHandling/Convert-BcAppsToRuntimePackages.ps1#L123

**Comment by freddydk** [comment]
It is correct, that the code generation in the runtime package is dependent on the platform version - or actually the emit version (which is another hidden version).
Beside that, the compiled app is compiled against an app version and localization - and the app+localization identified uniquely which platform is used as well.
By specifying a platform version number, it becomes harder to check whether this is compatible.
I am working on functionality for 2023 wave 1, where runtime packages are stored in nuget and the right package can be extracted from the nuget package depending on what version you are installing it on.
I might change the function (add a parameter or 2) to cope with needed functionality when I get to that.

**Comment by ChrisBlankDe** [comment]
thanks for clarification and the look into the future :)
