### ISSUE TITLE
Database connection string not used in New-BcContainerWizard on Azure VM.

### ISSUE THREAD

**Issue by mortenbohmer** [microsoft/navcontainerhelper#2760]
Using the New-BcContainerWizard, we create Azure VM with Docker instance, we also set Database connection string to point to an AzureSQL database. The VM is deployed and docker fires, but it is still using SQLExpress with an  Cronus db. The connection string is not deployed to docker ? 

Running BCContainerHelper version 4.0.5

**Comment by mortenbohmer** [comment]
@freddydk do you have any idea if this should work automaticly or not ?

**Comment by freddydk** [comment]
Sorry for the very long delay.
The wizard doesn't transfer the connection string to the Azure VM and the GETBC ARM template doesn't support a connection string.
My fix for this will be to avoid the database question when targetting Azure VMs, sorry
