### ISSUE TITLE
Dotnet in Run-AlPipeline

### ISSUE THREAD

**Issue by FabioC34** [microsoft/navcontainerhelper#2762]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Hi, I have 3 dll used in my AL Application (OnPrem of course), from VSC I can compile the App without problem, since I copied the dll in BCContainer with the command Copy-FileToBcContainer into Add-Ins folder.
Since I'd like to use CI/CD, I don't know how to copy these files in the container created in the pipeline with Run-AlPipeline command

Thank you
Best Regards
Fabio

**Comment by freddydk** [comment]
The Run-AlPipeline has overrides for some functions. One of these is the New-BcContainer command, which you override like this:

```
Run-AlPipeline -parameter -parameter...  -NewBcContainer { Param([HashTable] $parameters
New-BcContainer @parameters
Copy-FileToBcContainer -containerName $parameters.ContainerName -...
}

```

**Comment by FabioC34** [comment]
Perfect Freddy, thank you very much!

Fabio
