### ISSUE TITLE
Unused param in Publish-BuildOutputToAzureFeed.ps1

### ISSUE THREAD

**Issue by cr998** [microsoft/navcontainerhelper#2765]
I think there is an unused parameter in this function, I think it should be removed if I'm not mistaken

<img width="309" alt="image" src="https://user-images.githubusercontent.com/6900835/199925647-55f9dace-c19a-4c4c-8ce8-88638bf58e1b.png">

https://github.com/microsoft/navcontainerhelper/blob/3626596a43ca04873b5b57dd1de226e327fca3a2/PackageHandling/Publish-BuildOutputToAzureFeed.ps1#L29

**Comment by jonaswre** [comment]
You are right it's currently not used. Left over from the earlier days. I using the Environment Variable now. 
But removing the parameter might break somebody's code. 

So I think it's better to actually use it here. But the pat should not be mandatory. 

I'll create a fix for this on sunday.
