### ISSUE TITLE
Question: Debugging Sandbox container

### ISSUE THREAD

**Issue by gntpet** [microsoft/navcontainerhelper#2768]
Hey @freddydk, 

Do you know if debugging limitations applies to a container created with sandbox artifacts as well?

![image](https://user-images.githubusercontent.com/16342128/200257589-2d2ab03f-d360-4dd4-b716-9362ee70b689.png)

https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-attach-debug-next#attach-support

If I spin container with onprem artifacts, I can debug background sessions. When I spin container with sanbox artifacts, I cannot debug background session.  I wonder if it's intended behavior, my configuration issue, or is it a bug?

My code creating container:
```
New-NavContainer `
-accept_eula `
-accept_outdated `
-containerName $containerName `
-artifactUrl $url `
-isolation 'hyperv' `
-Credential $cred `
-auth UserPassword `
-updateHosts `
-useBestContainerOS `
-shortcuts desktop `
-enableTaskScheduler
```

Best Regards, 
Gintautas

**Comment by freddydk** [comment]
You could try to add -runSandboxAsOnprem

**Comment by gntpet** [comment]
But then it looses the meaning of using sandbox artifacts, doesn't it? IsSaaS  will return false for me.

https://demiliani.com/2021/08/12/dynamics-365-business-central-sandbox-vs-onprem-docker-containers/
https://github.com/microsoft/navcontainerhelper/issues/1995

**Comment by freddydk** [comment]
Probably yes - but definitely not anything I can fix in Docker otherwise.
It would be something they would have to fix in BC platform or app.

**Comment by gntpet** [comment]
Thank you @freddydk, opened a [ticket ](https://github.com/microsoft/AL/issues/7232) on AL repo.
Was just hoping there's some secret setting for that :)

**Comment by freddydk** [comment]
Closing this issue here, assuming that if this gets fixed, it will also work for containers.
