### ISSUE TITLE
Export-NavContainerObjects deletes files

### ISSUE THREAD

**Issue by mmenninghaus** [Microsoft/navcontainerhelper#277]
https://github.com/Microsoft/navcontainerhelper/blob/479f73acef2469d8f13ccdb962f26599d9a04874/ObjectHandling/Export-NavContainerObjects.ps1#L53

Maybe the deletion of anything inside the given objects folder should at least be mentioned in the documentation. Why the deletion anyway? Couldn`t that decision be left to the user?

**Comment by freddydk** [comment]
It should definitely be mentioned in the documentation and maybe guarded with a -force parameter.
The reason for the behavior is that originally it was intended for usage inside Convert-ModifiedObjectsToAl - and there the folders needs to be clean. It was then extracted to a seperate function.
