### ISSUE TITLE
No User was created

### ISSUE THREAD

**Issue by pungggi** [microsoft/navcontainerhelper#2773]
Hello this is my script I always use to create a container.
But now I updated to 4.0.6 and no user was created:
Docker: 4.13.1

```
$containerName = 'bcamagno'
$auth = 'NavUserPassword'
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'de' -version "21" -select 'Latest'
$licenseFile = 'c:\aifile02\interne daten\lizenzen\AI NAV BC.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -includeTestToolkit `
    -includeTestFrameworkOnly `
    -licenseFile $licenseFile `
    -dns '8.8.8.8' `
    -memoryLimit 6G `
    -updateHosts `
    -isolation 'hyperv'
```

then no admin was there:
`Invoke-ScriptInNavContainer -containerName bcamagno -scriptblock {
>>  Get-NavServerUser -ServerInstance BC -Tenant default
>> }

PSComputerName               : 54c39b4492029994f3793805668be4a6a18b929ce5469317590de2be8e63f4a
                               f
RunspaceId                   : d6e2006a-17fd-419e-876a-a6d5de2da4f8
UserSecurityID               : caa67b75-51bf-4128-83c9-9fbe2301744d
UserName                     : MSOLSYNC
FullName                     : Microsoft Online Sync Daemon
State                        : Enabled
ExpiryDate                   : 1/1/0001 12:00:00 AM
WindowsSecurityID            :
ChangePassword               : False
LicenseType                  : ExternalUser
AuthenticationEmail          :
ContactEmail                 :
ExchangeIdentifier           :
ApplicationID                : 996def3d-b36c-4153-8607-a6fd3c01b89f
Password                     :
NameIdentifier               :
AuthenticationKey            :
WebServicesKey               :
WebServicesKeyExpiryDate     : 1/1/0001 12:00:00 AM
AuthenticationObjectID       :
DirectoryPermissionSetID     :
DirectoryPermissionSetIDList : System.Byte[]
TelemetryUserID              : a6852906-2208-45c3-a68f-5ce9d8236abe
ProfileID                    :
Company                      :
LanguageID                   :

`

I added the user manually:

`New-NavContainerNavUser -Credential admin -containerName bcamagno -PermissionSetId SUPER -ChangePasswordAtNextLogOn 0`

**Comment by freddydk** [comment]
Please supply the full output of the script above, thanks
