### ISSUE TITLE
Release 21.1

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/navcontainerhelper#2775]
Hey Freddy,
The artifacts that shipped with release 21.1  didn't match the last insider build.  Was wondering if there was a mix up.  We noticed that there was a feature to block Salesperson in the last insider but that feature didn't ship.

https://bcartifacts.azureedge.net/sandbox/21.1.48363.49032/us 
verses https://bcinsider.azureedge.net/sandbox/21.1.48820.0/us what was actually shipped 

Just wondering why there's a mismatch and what else could be missing?

**Comment by freddydk** [comment]
When you say: what was actually shipped - then the artifacts being released on bcartifacts are the ones that actually are being rolled out.
It might be that the feature was checked into our 21.x branch after we branched off to 21.1, but before we changed the version number to 21.2 - meaning that this feature will make it into 21.2 - I don't have insights in that.
It is our build team that is rolling out artifacts (and builds to online services)
