### ISSUE TITLE
[Question]: Publishing Test-Apps to AppSource

### ISSUE THREAD

**Issue by jonaswre** [microsoft/navcontainerhelper#2777]
Is there a plan for publishing Test-Apps in an AppSourceSubmissions?

I've looked at the other issues but didn't find anything.

**Comment by ChrisBlankDe** [comment]
Test Apps are not required for AppSOurce Submissions and Microsoft do not check or excecute them.
The upload possibilist is still in AppSource since the PartnerCenter/AppSource Team is not as fast as the BC Team 😆

**Comment by freddydk** [comment]
Correct - we do not plan to run your tests in AppSource validation.
The page in partner center will eventually disappear
