### ISSUE TITLE
Cannot publish app with Publish-NavContainerApp if published before with VS Code

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/navcontainerhelper#278]
Scenario:
1. Published an app with VS Code
2. Unpublish and publish the app again with navcontainerhelper (Unpublish-NavContainerApp / Publish-NavContainerApp)

On publishing the app with Publish-NavContainerApp I get this error message:

> This extension cannot be published into the global scope because it is currently or was previously published into the tenant scope. An extension cannot be published into multiple scopes at the
> same time. Also, you cannot change the scope for an extension, unless you make sure that it was unpublished, and you then restart the service.

The default value of Publish-NAVApp for the parameter Scope is Global. VS Code publishes the app by connecting to the developer port 7049. Apparently, the app is then installed with Scope = Tenant.

**Comment by freddydk** [comment]
Sounds like we should expose the scope parameter on publish-navcontainerapp.
Did you try to add -scope tenant in the navcontainerhelper code and see if this fixes it?

**Comment by ajkauffmann** [comment]
Yes, I have added the parameter and now it publishes with scope Tenant. Similar to VS Code.

But then you also have to use the -Tenant parameter with the Publish-NAVApp command, otherwise the Install-NAVApp will fail.

Do you want to me to create a pull request on the dev branch with the change?

**Comment by freddydk** [comment]
Please do, thanks:-)

**Comment by freddydk** [comment]
Fixed in 0.4.2.6
