### ISSUE TITLE
The Number of Downloads showing zero from the past 15 days

### ISSUE THREAD

**Issue by ashikivor** [microsoft/navcontainerhelper#2784]
![image](https://user-images.githubusercontent.com/28855499/202205685-8c8d62d3-e716-45e1-a940-f2baf00fd088.png)

The no. of downloads is zero even though many people have installed the latest version.

**Comment by freddydk** [comment]
Assuming that PowerShell Gallery has a counter problem - that has happened before.

**Comment by ashikivor** [comment]
Resolved 😊
