### ISSUE TITLE
BC-App in Outlook has several issues. BC on prem NO, W1, Docker issue?

### ISSUE THREAD

**Issue by DagPilaro** [Microsoft/navcontainerhelper#279]
Hi,
I have several times ran aka.ms/getbc (both no and w1) During week 40 and 41.
Full O365 integration, copy AAD users, letsencrypt.

1. Running With Internet Explorer, both directly on the VM and "Remote" on my desktop (W10 1809, Edge and IE).
1.1 - Getting "Sorry, Your session exppired. Please refresh the page to continue" on initial run of the app.
1.2 - Have to log in to the web Client, og back and try over, then the app is running for a short time before the same issue appeares.
1.3 - The routine wich is giving the match on a contact does not run at all. No "Do you want to make a New contact" ore matching the contact i have manually made.
1.4 - When trying to run the BC App in a "extended window" i always get: "Sign in failed due.....Security token signature.

2. Running With Chorme (wich always has been the "walkaround" if IE-issues appeares).
2.1 - Not possible to run the App in Chrome, on run the "Sign in failed due.....Security token signature" appeares. No "walkaround"..

I have ran this setup an ran the "flow" regarding the O365/AAD/PowerBI/Excel etc. based on aka.ms/getnav 10-15 times and are therefore quite shore that "my" setups are correct...

**Comment by DagPilaro** [comment]
FYI:
Ran a New aka.ms/betbc this morning. mcr.microsoft.com/businesscentral/onprem:cu1-no-ltsc2019.
A "fresh" O365 demo-tenant (est. this morning) used for this.
psedit navsettings.json
psedit hosting.json
Restarted navcontainer
Ran the assisted setup for "Set up Azure Active Directory", "Set up email", "Set up your Business Inbox in Outlook"
portal.office.com then Outlook.
Still the same issues 😢
This to be sure that there is no problems regarding old files and settings. Running a clean env...

**Comment by freddydk** [comment]
Yeah - I am swamped in high priority stuff, so this one has to be punted until my christmas vacation.
Sorry.

**Comment by DagPilaro** [comment]
Ok, but…. This is very high priority stuff if we want to win new customers 😉. This is the best «demokiller, icebreaker» we have when the prospective customer compares BC with other solutions…
Having another demo to day – have to run 2 different vms for this.

Do not use your christmas vacation for this 😉

Vennlig hilsen / Kind regards
Dag Fr. Salvesen
Løsningsarkitekt og Salg/Marked
M: +47 900 99 399

Fra: Freddy Kristiansen <notifications@github.com>
Sendt: mandag 10. desember 2018 10:36
Til: Microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Kopi: Dag Salvesen <dag.salvesen@pilaro.no>; Author <author@noreply.github.com>
Emne: Re: [Microsoft/navcontainerhelper] BC-App in Outlook has several issues. BC on prem NO, W1, Docker issue? (#279)


Yeah - I am swamped in high priority stuff, so this one has to be punted until my christmas vacation.
Sorry.

**Comment by freddydk** [comment]
Shipped in 0.4.3.1
