### ISSUE TITLE
Duplicate folders in downloaded artifacts (OnPrem)

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/navcontainerhelper#2790]
**Found duplicate folders in newly downloaded artifacts (OnPrem)**

- Started around July
- Used Download-Artifacts

In folder platform\ServiceTier there is again a folder ServiceTier containing the same files and folders except ServiceTier.

**Comment by freddydk** [comment]
Verified that this is true.
![image](https://user-images.githubusercontent.com/10775043/203140093-b2a82137-2fdf-4cf6-b7f6-9507d71ddcef.png)

Will file a bug in our internal bug system.

**Comment by MODUSCarstenScholling** [comment]
Wasn't sure if artifacts are related to ContainerHelper or not. Thank you, Freddy for passing this.
