### ISSUE TITLE
not able to create container for  Slovenia Region

### ISSUE THREAD

**Issue by BssiGitQA** [microsoft/navcontainerhelper#2797]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Not able to create container for  Slovenia Region

**Scripts used to create a container and cause the issue**
$auth = "NavUserPassword"
$credential = New-Object pscredential 'test', (ConvertTo-SecureString -String 'test' -AsPlainText -Force)
$containerName ="test"
$licenseFile = " License file path was mentioned"
$artifactUrl = Get-BCArtifactUrl -country sl -version 20.5 -select Latest

New-NavContainer -sasToken $sasToken `
-storageAccount bcinsider `
-accept_eula `
-containerName $containerName `
-artifactUrl $artifactUrl `
-auth $auth `
-credential $credential `
-licenseFile $licenseFile `
-dns 8.8.8.8 `
-updateHosts `
-accept_outdated `
-IncludeAL

**Full output of scripts**
```
**You have to specify artifactUrl or imageName when creating a new container.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\3.0.3\ContainerHandling\New-NavContainer.ps1:512 char:9
+         throw "You have to specify artifactUrl or imageName when crea ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You have to spe... new container.:String) [], RuntimeException
    + FullyQualifiedErrorId : You have to specify artifactUrl or imageName when creating a new container.**

**Comment by freddydk** [comment]
Please update your containerhelper - 3.0.3 is a very old version.
After that, **SL** is not the 2 letter country code for slovenia - that is **si**
(but you need the latest containerhelper for si to work)

**Comment by BssiGitQA** [comment]
Thank you Freddy , it worked.
