### ISSUE TITLE
Docker Container Creation Error BC21 - Access to the path 'C:\Run\Install' is denied.

### ISSUE THREAD

**Issue by MagicDrozdz** [microsoft/navcontainerhelper#2811]
Hello, 

by using following script:

        $path = "C:\LS Central 21.0 Docker"
        $containerName = "lsretail210"
        $username = "xx"
        $password = "xx"
        
        Install-Module BcContainerHelper -Force
        
        Set-ExecutionPolicy unrestricted -Scope CurrentUser
                                                                    
        $artifactUrl = "https://bcartifacts.azureedge.net/onprem/21.1.48363.48638/w1"
        $credential = New-Object System.Management.Automation.PSCredential -argumentList $username, (ConvertTo-SecureString -String $password -AsPlainText -Force)
        $licenseFile = $path + "\fin.flf"
        $localapp = $path + "\ls-retail_ls-central_21-0-0-1000312.app"
        $localsysapp = $path + "\ls-retail_ls-central_system_app_21-0-0-1000312.app"
        $bakFolder = $path
        
        $additionalPars = @('--volume "' + $bakFolder + ':c:\Backup"',
                            '--env bakfile="C:\Backup\ls-central-release.bak"')
        
        New-BCContainer `
        -accept_eula `
        -accept_outdated:$true `
        -artifactUrl $artifactUrl `
        -containerName $containerName `
        -updateHosts `
        -licenseFile $licenseFile `
        -Auth NavUserPassword `
        -Credential $credential `
        -enableTaskScheduler `
        -shortcuts DesktopFolder `
        -restart unless-stopped `
        -memoryLimit 12G `
        -myScripts @($localapp, $localsysapp) `
        -additionalParameters $additionalPars

I'm getting following output:

      BcContainerHelper version 4.0.7
      BcContainerHelper emits usage statistics telemetry to Microsoft
      BcContainerHelper is version 4.0.7
      BcContainerHelper is running as administrator
      Hyper-V is Enabled
      UsePsSession is True
      Host is Microsoft Windows 10 Enterprise - 22H2
      Docker Client Version is 20.10.21
      Docker Server Version is 20.10.21
      Removing entries from hosts
      Removing lsretail210 from container hosts file
      Removing lsretail210-* from container hosts file
      Removing Desktop shortcuts
      Removing C:\ProgramData\BcContainerHelper\Extensions\lsretail210
      Fetching all docker images
      Fetching all docker volumes
      INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
      Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
      Creating Container lsretail210
      Style: onprem
      Multitenant: No
      Version: 21.1.48363.48638
      Platform: 21.0.48357.48504
      Generic Tag: 1.0.2.13
      Container OS Version: 10.0.19041.1415 (2004)
      Host OS Version: 10.0.19045.2311 (22H2)
      WARNING: Host OS is Windows 10 21H1 or newer and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hype
      rv.
      Using process isolation
      Using locale en-US
      Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
      Using license file C:\LS Central 21.0 Docker\fin.flf
      Additional Parameters:
      --volume "C:\LS Central 21.0 Docker:c:\Backup" --env bakfile="C:\Backup\ls-central-release.bak"
      --env customNavSettings=EnableTaskScheduler=True
      Files in C:\ProgramData\BcContainerHelper\Extensions\lsretail210\my:
      - AdditionalOutput.ps1
      - license.flf
      - ls-retail_ls-central_21-0-0-1000312.app
      - ls-retail_ls-central_system_app_21-0-0-1000312.app
      - MainLoop.ps1
      - SetupVariables.ps1
      - updatehosts.ps1
      Creating container lsretail210 from image mcr.microsoft.com/businesscentral:10.0.19041.1415
      e45d85cd49224d629bdc4c3f94ed474e05fee674a422437f3d4d395d4398e87c
      Waiting for container lsretail210 to be ready
      Using artifactUrl https://bcartifacts.azureedge.net/onprem/21.1.48363.48638/w1
      Using installer from C:\Run\210-new
      Installing Business Central
      Installing from artifacts
      Starting Local SQL Server
      Starting Internet Information Server
      Copying Service Tier Files
      c:\dl\onprem\21.1.48363.48638\platform\ServiceTier\Program Files
      c:\dl\onprem\21.1.48363.48638\platform\ServiceTier\System64Folder
      Copying PowerShell Scripts
      c:\dl\onprem\21.1.48363.48638\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
      c:\dl\onprem\21.1.48363.48638\platform\WindowsPowerShellScripts\WebSearch
      Copying Web Client Files
      c:\dl\onprem\21.1.48363.48638\platform\WebClient\Microsoft Dynamics NAV
      Copying ModernDev Files
      c:\dl\onprem\21.1.48363.48638\platform
      c:\dl\onprem\21.1.48363.48638\platform\ModernDev\program files\Microsoft Dynamics NAV
      Copying additional files
      Copying ConfigurationPackages
      C:\dl\onprem\21.1.48363.48638\platform\ConfigurationPackages
      Copying Test Assemblies
      C:\dl\onprem\21.1.48363.48638\platform\Test Assemblies
      Copying Applications
      C:\dl\onprem\21.1.48363.48638\platform\Applications
      Copying dependencies
      Access is denied
      at <ScriptBlock>, C:\Run\navinstall.ps1: line 161
      at <ScriptBlock>, C:\Run\start.ps1: line 242
      at <ScriptBlock>, <No file>: line 1Error
      Using artifactUrl https://bcartifacts.azureedge.net/onprem/21.1.48363.48638/w1
      Using installer from C:\Run\210-new
      Installing Business Central
      Installing from artifacts
      Starting Local SQL Server
      Starting Internet Information Server
      Copying Service Tier Files
      c:\dl\onprem\21.1.48363.48638\platform\ServiceTier\Program Files
      c:\dl\onprem\21.1.48363.48638\platform\ServiceTier\System64Folder
      Copying PowerShell Scripts
      c:\dl\onprem\21.1.48363.48638\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
      c:\dl\onprem\21.1.48363.48638\platform\WindowsPowerShellScripts\WebSearch
      Copying Web Client Files
      c:\dl\onprem\21.1.48363.48638\platform\WebClient\Microsoft Dynamics NAV
      Copying ModernDev Files
      c:\dl\onprem\21.1.48363.48638\platform
      c:\dl\onprem\21.1.48363.48638\platform\ModernDev\program files\Microsoft Dynamics NAV
      Copying additional files
      Copying ConfigurationPackages
      C:\dl\onprem\21.1.48363.48638\platform\ConfigurationPackages
      Copying Test Assemblies
      C:\dl\onprem\21.1.48363.48638\platform\Test Assemblies
      Copying Applications
      C:\dl\onprem\21.1.48363.48638\platform\Applications
      Copying dependencies
      Access is denied
      at <ScriptBlock>, C:\Run\navinstall.ps1: line 161
      at <ScriptBlock>, C:\Run\start.ps1: line 242
      at <ScriptBlock>, <No file>: line 1
      New-BCContainer Telemetry Correlation Id: 8abcf615-531c-4f70-b48b-ba01bc136dc1
      Initialization of container lsretail210 failed
      In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.7\ContainerHandling\Wait-NavContainerReady.ps1:42 Zeichen:17
      + ...             throw "Initialization of container $containerName failed" ...
      +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          + CategoryInfo          : OperationStopped: (Initialization ...etail210 failed:String) [], RuntimeException
          + FullyQualifiedErrorId : Initialization of container lsretail210 failed

I could find out that it's coming from this place:

![image](https://user-images.githubusercontent.com/119611251/205101097-c67b66aa-e14d-47a0-8a15-719f8cae0dfa.png)

Finally, as the container is up and running I could check the access and got following:

![image](https://user-images.githubusercontent.com/119611251/205101377-80d369e3-feea-4b65-ae83-7f45dc7f13ab.png)

**Comment by freddydk** [comment]
Could you retry the operation with -isolation hyperv?

**Comment by MagicDrozdz** [comment]
Sorry, forgotten to mention... tried already. The same result...

**Comment by MagicDrozdz** [comment]
Hi Freddy, Flush didn't help but the script DID. Thank You!!

**Comment by freddydk** [comment]
Thanks for the heads-up - so it seems like the filesystem of docker was messed up.
Happy that it worked out.
