### ISSUE TITLE
Get-BcEnvironments fails with "The remote server returned an error: (403) Forbidden." but I can access Admin Center via the browser

### ISSUE THREAD

**Issue by BW-PA** [microsoft/navcontainerhelper#2812]
**Describe the issue**
I can access the Admin Center for the tenant via my microsoft CSP account yet using the same account to create the device login authcontext to pass to Get-BcEnvironments gives "The remote server returned an error: (403) Forbidden."

To be honest I don't know if this is a Get-BcEnvironments issue or not.  It doesn't feel like it is.  I decided to log it here since my account is able to access Admin Center via the web.

In addition, I used this account to get the list of environments successfully earlier this afternoon but now it fails consistently.  It's very weird.

Can you tell me if my understanding is correct, in that if my account can access Admin Center via the web I should also be able to use the same account to retrieve the list of Environments via Get-BcEnvironments?

**Scripts used to create container and cause the issue**
```
$authContext = New-BcAuthContext -includeDeviceLogin

$env = Get-BcEnvironments -bcAuthContext $authContext
```

**Full output of scripts**
```
BcContainerHelper version 4.0.7
BcContainerHelper emits usage statistics telemetry to Microsoft
Attempting authentication to https://api.businesscentral.dynamics.com/user_impersonation offline_access using device login...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code QW8CPU5UC to authenticate.
Waiting for authentication.....
Authenticated from <IP address redacted> as user <user redacted> (<user redacted>@<domain redacted>.onmicrosoft.com)
Authenticated to common, using tenant id <Tenant ID redacted>
Get-BcEnvironments Telemetry Correlation Id: 8120413a-fc39-4abf-a7c7-218aa05c1eb9
The remote server returned an error: (403) Forbidden.
Forbidden
 (ms-correlation-x = d3b5db41-5b50-404a-a5fa-cff684b5dcbc)
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.7\BcSaaS\Get-BcEnvironments.ps1:32 char:9
+         throw (GetExtendedErrorMessage $_)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The remote serv...a-cff684b5dcbc):String) [], RuntimeException
    + FullyQualifiedErrorId : The remote server returned an error: (403) Forbidden.
Forbidden
 (ms-correlation-x = d3b5db41-5b50-404a-a5fa-cff684b5dcbc)
 
...
```

**Screenshots**

**Additional context**
- It worked earlier this afternoon once.  Then tried using a refresh token authcontext and now not even devicelogin authcontext works anymore
- did it use to work? Yes, once.  Now not at all.

**Comment by freddydk** [comment]
Code works fine here (but your code doesn't print anything)

```
$authContext = New-BcAuthContext -includeDeviceLogin
$env = Get-BcEnvironments -bcAuthContext $authContext
$env.name
```
outputs

```
dirdemo2
dirdemo
PROD
FAT
QA
```

You might need to add -TenantId 'tenantid' to your get-bcauthcontext if your user has access to multiple tenants?

**Comment by BW-PA** [comment]
Thankyou Freddy.  Adding the -tenantID parameter to New-BcAuthContext was what I was missing.  The clue too was that without it, NewBcAuthContext returned 'Authenticated to common, using tenant Id: <tenant Id>.  And that Tenant was not the one I was attempting to query the list of Environments from.

Using your suggestion the following code works correctly.

```
$tenantID = '<The Tenant Id that contains the environment my microsoft CSP account has access to>'
$authContext = New-BcAuthContext -includeDeviceLogin -tenantID $tenantID 

$env = Get-BcEnvironments -bcAuthContext $authContext
$env.name
```
