### ISSUE TITLE
Deploy from VSC running on local computer to Docker Container on the server fails with error Bad Gateway and Container status is set to unhealthy

### ISSUE THREAD

**Issue by dz4pot** [microsoft/navcontainerhelper#2828]
Hi All, 

I have 2 issues:

1. Deployment from VSC to the Docker Container fails with error "Bad Gateway"
- As I am deploying code from VSC that runs locally on my laptop to the Docker Container that is installed on VM on server I get the error in VSC "Bad Gateway".
- it happens randomly, this means, that it works for several minutes (20-30 mins) and then error Bad Gateway pops in the VSC debugger window.
- Docker Container goes into the unhealthy state, even though Docker inspect does not report any issue (see attached file Damjan_error.txt)
- restart of container resolves the issue

2. Debugging of AL code is super slow when any parameter or table field is added in the Watcher window. This started to happen as we installed Docker and all containers on the Server.
- when the debugger is active and non parameter is added into the Watcher window inside VSC the debugger behaviour works as expected, takes about 1 second to go to the next line (F11) in the code.
- as any parameter or table field, etc is added in the Watcher window the responsiveness of the debugger becomes super slow (takes 3-6 seconds to jump to the next line in code), if Watcher window is hidden that it work again as expected.
 

System environment:
1. Virtual Machine ESXI Hypervisor, 128GB RAM, SSD, CPU 6-Cores, virtualization is enabled, Hyper-V is used for VMs
2. One Docker Desktop is installed on the server where 12 containers are deployed with BC19 (OnPrem)
4. 12 containers, each container has been dedicated of 12GB RAM
5. NGIX used as reverse proxy upstream to the containers and SSL termination for hosting multiple machines.
6. health check is enabled; default settings, which have been changed to 
7. VSC is running on local machine (laptop) - it works the same as on internal network as it does over the VPN (home office).

Logs from Docker and from the affected Docker Container (event logs) are attached.

Thank you
BR Damjan
[Logs.zip](https://github.com/microsoft/navcontainerhelper/files/10246287/Logs.zip)

**Comment by freddydk** [comment]
2 questions:
Does the container have a SSL certificate?
What authentication are you using?

**Comment by dz4pot** [comment]
1. container uses SSL certificate, but we are planning to use HTTP and SSL will be configured for NGINX
2. authentication type is set to NavUserPassword

**Comment by dz4pot** [comment]
I just read this thread https://github.com/microsoft/vscode-java-debug/issues/305
I have few JS in the project....not sure it this has anything to do with slow debugger

Thank you
BR Damjan

**Comment by freddydk** [comment]
I don't know whether that could be related.
Does all the containers work fine until you start debugging?
Can you repro this in a simpler setup - create a local container and debug?

**Comment by dz4pot** [comment]
Hi Freddy,
issue is resolved with this parameter: doNotCheckHealth = $true;
it works like a charm both in Google Chrome and FireFox. Debugger is super fast:), like an instant blink of an eye and it jumps in next line in the code, also all entries in the Watcher window are update at once as code is positioned on the next line.

for now, we will have enabled that parameter in the Container config. I hope that is fine.

Thank you
BR Damjan

**Comment by freddydk** [comment]
Which reminds me that when Tobias Fenster added Traefik support, he also added a new CheckHealth script:
https://github.com/microsoft/navcontainerhelper/blob/master/ContainerHandling/traefik/CheckHealth.ps1
Which is probably something like that you would need to make health checks work on the other side of NGINX.
Sorry for not seeing this earlier.

**Comment by dz4pot** [comment]
One more thing, I just found out we are running Docker Desktop and not Docker Enterprise. Does the version of Docker relate to issues we have, in particular we are having random errors as developers are deploying app from locally installed VSC (bad gateway).

**Comment by freddydk** [comment]
No
There is also nothing called Docker Enterprise anymore - it is Mirantis Container Runtime.
Personally, I use Docker Engine.
https://freddysblog.com/2021/10/30/docker-and-business-central/
