### ISSUE TITLE
New-NavContainer fails with version 0.4.2.4 when detecting hypervisor

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#283]
With version 0.4.2.3 I can create a container. See attached inspect.txt
[inspect.txt](https://github.com/Microsoft/navcontainerhelper/files/2664713/inspect.txt)
but with version 0.4.2.4 it fail with following text:

Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 18.09.0
Docker Server Version is 18.09.0
Using image bcinsider.azurecr.io/bcsandbox:13.2.26607.0-base-ltsc2016
Creating Nav container VSN-BCSANDBOX03
Using license file c:\users\vsts_server-pd14\foodware365_psmenus\Licenses\Foodware365BC.flf
Version: 13.2.26607.0-W1
Platform: 13.0.26394.0
Generic Tag: 0.0.8.1
Container OS Version: 10.0.14393.2608 (ltsc2016)
Host OS Version: 10.0.14393.2608 (ltsc2016)
Using hyperv isolation
Creating container VSN-BCSANDBOX03 from image bcinsider.azurecr.io/bcsandbox:13.2.26607.0-base-ltsc2016
e6abf00f7f7f94df15bd460742e318ecc07483c966a21e1c740c5c8f3f5cd6d6
docker.exe: Error response from daemon: CreateComputeSystem e6abf00f7f7f94df15bd460742e318ecc07483c966a21e1c740c5c8f3f5cd6d6: No hypervisor is present on this system.
[Event Detail: Cannot start Hyper-V Container 'e6abf00f7f7f94df15bd460742e318ecc07483c966a21e1c740c5c8f3f5cd6d6' since the hypervisor is not running in the host. Provider: 17103e3f-3c6e-4677-bb17-3b267eb5be57 EventID: 12001]

The Host version is still 1607 which wasn't a problem yet with NavContainerHelper 0.4.2.3

**Comment by freddydk** [comment]
So sorry, put in a defaulting of isolation mode shortly before publishing and I made a stupid mistake.
Fixed in 0.4.2.5
