### ISSUE TITLE
Ingestion API and properties including collections (Question)

### ISSUE THREAD

**Issue by Koubek** [microsoft/navcontainerhelper#2838]
**Describe the issue**
This is just a question - I would like to know if is it really necessary to include properties of Ingestion API return values (objects) as collections.

E.g. in `Get-AppSourceProduct`, the property `Property`. It's obviously just a single item that will be returned but you still define it as an array and I am not sure why. Maybe there is a point and I don't see it.

**Additional details**
I just want to tell this complicates parsing during .NET interop processing as we can just search properties like `product.Property.appVersion` but we had to go through array on `Property` property :)

https://github.com/microsoft/navcontainerhelper/blob/d909f750c48747898c0bd174d5ccf493d5f9f062/AppSource/Get-AppSourceProduct.ps1#L180

**Comment by freddydk** [comment]
I guess the question here is whether

Invoke-IngestionApiGetCollection -authContext $authContext -path "/products/$($product.Id)/properties/getByInstanceID(instanceID=$($branchesProperty[0].currentDraftInstanceID)

Can return an array - or it is always an object?

To be honest, I don't know and the documentation, but the reason for the code is that the swagger describes that the return value is an array:
https://ingestionapi-swagger.azureedge.net/#/Property/get_products__productID__properties_getByInstanceID_instanceID__instanceID__
(Which might not be used in BC terms though).

**Comment by Koubek** [comment]
Ok, I have resolved the problem somehow internally so I will close the case.
