### ISSUE TITLE
Problems provisioning docker using aka.ms/getbcext templates (BcContainerHelper 4.0.9)

### ISSUE THREAD

**Issue by CarlosAndreuLlaneras** [microsoft/navcontainerhelper#2844]
Yesterday I was able to provision new VMs, but today it's being impossible.
The process ends successfully, but when accessing BC the IIS shows a "404 - Not found" error.

I have tried different configurations and different templates (getbc, getbcext) with the same result.

Has anything changed in the last 24 hours? 
Could it have to do with ticket [#2842](https://github.com/microsoft/navcontainerhelper/issues/2842)?
Any suggestions?

Thanks

**Comment by freddydk** [comment]
Are you using traefik?

**Comment by CarlosAndreuLlaneras** [comment]
Yes I am using traefik.

**Comment by freddydk** [comment]
Will investigate

**Comment by freddydk** [comment]
Shipped in 4.0.10

**Comment by CarlosAndreuLlaneras** [comment]
Now it is working again!!!
Thanks
