### ISSUE TITLE
Initialization of container failed

### ISSUE THREAD

**Issue by stefaanbeernaert** [microsoft/navcontainerhelper#2849]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
keep getting this error :
throw "Initialization of container $containerName failed"
i used this script many times without problems

**Scripts used to create container and cause the issue**
```
New-BcContainer 
-accept_eula 
-alwaysPull 
-artifactUrl https://bcartifacts.azureedge.net/sandbox/21.3.51409.51871/be 
-assignPremiumPlan 
-auth NavUserPassword 
-containerName test 
-imageName mcr.microsoft.com/businesscentral:10.0.20348.1129 
-includeAL 
-includeTestToolkit 
-installCertificateOnHost 
-licenseFile "************************" 
-memoryLimit 8G 
-updateHosts 
-useSSL
```

**Full output of scripts**
```
BcContainerHelper is version 4.0.7
BcContainerHelper is running as administrator
Host is Microsoft Windows 11 Pro 64
Docker Client Version is v20.10.21
Docker Server Version is v20.10.21
...
```

**Screenshots**
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer with SSL
WARNING: SetupWebClient failed, retrying...
CertificateThumprint ***********************************
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Remove C:\inetpub\wwwroot\BC
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Removing existing application pool BC
Create website: NavWebApplicationContainer with SSL
Incorrect function. (Exception from HRESULT: 0x80070001)
at New-NavSiteWithBindings, C:\run\my\NAVWebClientManagement.psm1: line 680
at New-NavWebSite, C:\run\my\NAVWebClientManagement.psm1: line 630
at New-NAVWebServerInstance, C:\run\my\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 50
at <ScriptBlock>, C:\Run\navstart.ps1: line 191
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.docker.internal to *********** in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to ************** in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to ******** in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to ************ in container hosts file
Starting Container
Hostname is test
PublicDnsName is test
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint **********************
DNS identity groen
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
CertificateThumprint ***********************
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer with SSL
WARNING: SetupWebClient failed, retrying...
CertificateThumprint ********************************
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Remove C:\inetpub\wwwroot\BC
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Removing existing application pool BC
Create website: NavWebApplicationContainer with SSL
Incorrect function. (Exception from HRESULT: 0x80070001)
at New-NavSiteWithBindings, C:\run\my\NAVWebClientManagement.psm1: line 680
at New-NavWebSite, C:\run\my\NAVWebClientManagement.psm1: line 630
at New-NAVWebServerInstance, C:\run\my\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 50
at <ScriptBlock>, C:\Run\navstart.ps1: line 191
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
New-BcContainer Telemetry Correlation Id: 3a174a7e-84f3-4302-840f-ebb2f50a88b7
Initialization of container groen failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.7\ContainerHandling\Wait-NavContainerReady.ps
1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeExc 
   eption
    + FullyQualifiedErrorId : Initialization of container test failed

**Additional context**
- does it happen all the time? yes
- did it use to work? yes

**Comment by stefaanbeernaert** [comment]
just tested without the useSSL option and then it works so problem is with that setting...

**Comment by freddydk** [comment]
This is an error in Windows 11 and SSL - not anything I can fix.
I have created a bug on the Windows team.
I will however add a warning during the output of the container and write that this might/will fail.
