### ISSUE TITLE
Encryption key error

### ISSUE THREAD

**Issue by Bjarke848** [microsoft/navcontainerhelper#2850]
Hi Freddy,

We have this issue that Jeremy and I has this issue:
https://twitter.com/BjarkeVilladse1/status/1611352132409778181

This is the problem, it seems like the Encryption is enabled but I can't import or create the key for this.
![image](https://user-images.githubusercontent.com/57141525/211781552-88d0e118-0ba8-40da-8122-0677de96623b.png)

My Business Central is using follow artifactURL:
21.2.49946.49990/se

I have tried to do following
```
New-NAVEncryptionKey -KeyPath "C:\run\my\nav.key" -Password (Read-Host "Enter password for new key" -AsSecureString)
```
Also I have tried to export the encyrption key and then manually import it in the UI which gave me following error:
![image](https://user-images.githubusercontent.com/57141525/211781290-d4920558-69eb-4351-867b-df4584f7a24d.png)
After that i tried to delete it in both the folder "C:\ProgramData\.\.\.\Keys\BC.key" and directly in the database but this does not make any changes.

**Comment by JeremyVyska** [comment]
To add a bit, my testing varied a little - I could use the UI in the BC environment to use the **Enable Encryption** action OK (from the Data Encryption Management page, 9905), and that would enable the database encryption (plus download the file).

Curiously, however, when using PowerShell to create and import the key, it would fail to enable the encryption.  There would be no error (little info from -verbose), and no strange behavior in the Event Log of the Container.

For creation of the container, I used:

```Powershell
$containerName = 'docker-bc21-se'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'se' -select closest -version '21.2.49946.49990'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -multitenant:$false `
    -dns '8.8.8.8' `
    -memoryLimit 4G `
    -updateHosts
```

For trying to enable the Data Encryption using the On Prem (inside Docker) instance, I used:

```Powershell
Enter-BcContainer -containerName docker-bc21-se
New-NAVEncryptionKey -KeyPath "C:\run\my\nav.key" -Password (Read-Host "Enter password for new key" -AsSecureString)
Import-NAVEncryptionKey -ServerInstance BC -ApplicationDatabaseServer localhost -ApplicationDatabaseName CRONUS -KeyPath C:\run\my\nav.key -Password (Read-Host "Enter password for new key" -AsSecureString)
Restart-NAVServerInstance BC
```

I have a BC 21 for W1 on my local as an On-Prem (outside docker) and this functionality appears to work as expected using the above sequence, so I'm a bit baffled.

**Comment by freddydk** [comment]
I think we are talking about 2 different encryption keys here.
The "old" PowerShell cmdlets are for setting up encryption between Service Tier and database.
The Data Encryption Management module was (I think) not even part of NAV (when these cmdlets was created)
I did create an app, which would enable encryption on install. https://github.com/BusinessCentralApps/EnableEncryption - but maybe this doesn't work anymore.
You could however probably easily make something like it.

**Comment by freddydk** [comment]
No, this is clearly me, who misunderstood something here - will have a look on the above.

**Comment by freddydk** [comment]
Back at my first comment.


If I create a container using SQL Express inside the container - it doesn't have any encryption enabled between server and SQL.
Script:
```
$auth = "UserPassword"
$containerName = "bcserver"
$credential = New-Object pscredential -ArgumentList 'admin', $PasswordSecret.SecretValue
$artifactUrl = get-bcartifacturl -country se -type onprem -version 21.2 -select Latest
New-BCContainer -containerName $containerName `
                -accept_eula `
                -Auth 'UserPassword' `
                -artifactUrl $artifactUrl `
                -Credential $credential `
                -updateHosts
```
Page 9905 says:
![image](https://user-images.githubusercontent.com/10775043/212270969-5d235215-1a67-408c-8193-5d7fbf9fbae3.png)

I can now click Enable Encryption and it will tell me that it needs to create a key and then it enabled encryption, exports the key file and I am good.

If I create a container using SQL Server on the host, it does use SQL Encryption.
```
Script:
$password = $passwordSecret.SecretValue
$licenseFile = $licenseFileUrlSecret.SecretValue | Get-PlainText
$auth = "UserPassword"
$credential = New-Object pscredential -ArgumentList 'admin', $password
$artifactUrl =  Get-BCArtifactUrl -country se -version "21.2" -type Onprem

$containerName = "v21"

$databaseParams = @{
    "databaseServer" = 'host.containerhelper.internal'
    "databaseInstance" = ''
    "databasePrefix" = "$containerName-"
    "databaseName" = 'CRONUS'
    "databaseCredential" = New-Object pscredential 'sa', $password
    "multitenant" = $false
}

New-BcContainer @databaseParams -replaceExternalDatabases `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts
```
But still, Data Encryption is not enabled in page 9905 and the process of enabling is the same - it generates a key for me.

In both cases, I can publish and unpublish my EnableEncryption app and then I have encryption enabled, using this script:
```
Publish-BcContainerApp `
    -containerName $containerName `
    -appfile 'https://businesscentralapps.blob.core.windows.net/enableencryption/latest/apps.zip' `
    -credential $credential `
    -install `
    -sync `
    -skipVerification

```
and the result (in both containers) is:
![image](https://user-images.githubusercontent.com/10775043/212274362-9c8efe9b-e6f4-49fa-aa08-4b6065b93118.png)

If your situation is different - then I will need a repro scenario (like the one above), which can show me how you end up with encryption enabled and no key present.

**Comment by Bjarke848** [comment]
Hi again,

We have been able to do some testing today, and we have tried several thing.
- Install the Encryption app but it didn't work (Our guess is that it's because BC already thinks it is enabled)
- Changed your Encryption application to force Enable Encryption (by removing if statement)
- Changed the application to disable it, to test if we were able to force it to disable and hope that we could enable without issues.

When I recreate the BC it always start up this:
![image](https://user-images.githubusercontent.com/57141525/212718634-307bd753-57df-4889-96a7-8e46a56e37da.png)
So it might be a error in the database. But I haven't been able to fix it by directly removing it from the database neither. (Which the UI error message suggest)

The script I'm running when recreating BC:
````
$containerName      = 'KvikTestSE'
$licenseFileUri     = "C:\BC21\**.bclicense"
$authenticationEmail = "**"
$Credential         = [System.Management.Automation.PSCredential]::new('**', (ConvertTo-SecureString -String "**" -AsPlainText -Force))
$sqlCredential      = [System.Management.Automation.PSCredential]::new('**', (ConvertTo-SecureString -String "**" -AsPlainText -Force))
$bcartifact         = Get-BCArtifactUrl -type OnPrem -country "SE" -version "21.2" -select Latest
$ApplicationID = "**"
$tenantID = "**"

$databaseParams = @{
    "databaseServer" = '10.1.0.23'
    "databaseInstance" = ''
    "databasePrefix" = "$containerName-"
    "databaseName" = 'CRONUS'
    "databaseCredential" = $sqlCredential
}

$params = @{
    "auth" = 'AAD'
    "containerName" = $containerName
    "multitenant" = $false
    "isolation" = 'process'
    "artifacturl" = $bcartifact
    "licensefile" = $licenseFileUri
    "updateHosts" = $true
    "useTraefik" = $true
    "myscripts" = @("C:\Powershell Scripts\SetupCertificate.ps1", "C:\KvikIT\wildcard_kvik_com_2023.pfx")
    "publicDnsName" = 'bc.kvik.com'
    "authenticationEMail" = $authenticationEmail
}

New-BCContainer @databaseParams `
    @params `
    -accept_eula `
    -accept_outdated `
    -Credential $Credential `
    -doNotExportObjectsToText `
    -shortcuts CommonDesktopFolder `
    -AadAppId $ApplicationID
````

**Comment by freddydk** [comment]
Thanks
Using this script, you will be reusing the CRONUS database on that database server and my assumption is that the problem is inside that.
With my tests, I used a new database (both inside the container and external) and I had no issues at all.

Why do you think this is a container problem?
Can you make this work without containers?
Did you try to restore a new database? (this way I could have an end-2-end failing scenario which I can troubleshoot)

**Comment by Bjarke848** [comment]
We have been trying to solve this issue with a lot of diffrent approaches, but the end solution was to create a new empty database, enable encryption and then move all the companies.

So it had nothing to do with the bccontainerhelper. But it was an error in the database which we can't figure out.
