### ISSUE TITLE
Restoring backup from online Environment - dac missing assembly

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/navcontainerhelper#2880]
**Describe the issue**
We are trying to restore a backup from an online environment locally as suggested in 
[](https://freddysblog.com/2021/03/02/restoring-your-online-business-central-database-locally/
)
**Scripts used to create container and cause the issue**
```
$tenantId = $environment
$dacdll = Get-Item "C:\Program Files\Microsoft SQL Server\*\DAC\bin\Microsoft.SqlServer.Dac.dll"
if (!($dacdll)) {
    throw "DAC Framework is not installed"
}
Add-Type -path $dacdll.FullName
$databaseName = "$($databaseParams.databasePrefix)$tenantId"
$conn = @(
    "Data Source=localhost"
    "Initial Catalog=master"
    "Connection Timeout=0"
    "User Id=$($dbCredential.UserName)"
    "Password=$($dbCredential.Password|Get-PlainText)"
) -join ";"
Write-Host "Restoring Database from $backupFile as $databaseName"
$AppimportBac = New-Object Microsoft.SqlServer.Dac.DacServices $conn
$ApploadBac = [Microsoft.SqlServer.Dac.BacPackage]::Load($backupFile)
$AppimportBac.ImportBacpac($ApploadBac, $databaseName)
```

**Full output of scripts**
```
Restoring Database from C:\databases\XXX.bacpac as XXX-Production
Exception calling "ImportBacpac" with "2" argument(s): "Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."
At line:12 char:1
+ $AppimportBac.ImportBacpac($ApploadBac, $databaseName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
```

**Additional context**
- we are not able to install the missing assembly *System.Runtime.CompilerServices.Unsafe* locally

**Comment by freddydk** [comment]
How did you install the DAC tool?

**Comment by freddydk** [comment]
I would assume you get everything with sqlpackage - https://learn.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver16

**Comment by mmenninghaus** [comment]
I got the DAC tool by installing the sqlpackage - with the missing dependency it does not seem to be correctly build.

**Comment by freddydk** [comment]
Yeah, sorry - have never seen that before, but other people have:
https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe

**Comment by mmenninghaus** [comment]
Thank you, i already have been there and hoped for another solution. Anyway, will try to install the gacutil on the server and install the dependency. I will later post an update here.

**Comment by mmenninghaus** [comment]
I installed the gacutils and added the assembly for both .net 4 and 6
![image](https://user-images.githubusercontent.com/43880502/215534919-dc070beb-7d60-4b3f-b7bf-37a89c3756df.png)
Still, the error exists after reloading the power shell
```
Add-Type -AssemblyName System.Runtime.CompilerServices.Unsafe

Add-Type : Cannot add type. The assembly 'System.Runtime.CompilerServices.Unsafe' could not be found.
At line:1 char:1
+ Add-Type -AssemblyName System.Runtime.CompilerServices.Unsafe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (System.Runtime.CompilerServices.Unsafe:String) [Add-Type], Exception
    + FullyQualifiedErrorId : ASSEMBLY_NOT_FOUND,Microsoft.PowerShell.Commands.AddTypeCommand

Add-Type : Cannot add type. One or more required assemblies are missing.
At line:1 char:1
+ Add-Type -AssemblyName System.Runtime.CompilerServices.Unsafe
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Add-Type], InvalidOperationException
    + FullyQualifiedErrorId : ASSEMBLY_LOAD_ERRORS,Microsoft.PowerShell.Commands.AddTypeCommand

```
Which .net and powershell version are you using when executing the commands? Has anyone ever tested it on Windows Server 2019, i.e. an azure vm generated with aka.ms/getbcext ARM template?

**Comment by freddydk** [comment]
https://aka.ms/getbcext has two parameters (App BacPac Uri and Tenant Bacpac Uri) - and yes, these have been tested.
Problem is that software packages ship new versions and things that used to work might not work tomorrow.

I will see if I can get the time to try this out next week.

**Comment by mmenninghaus** [comment]
To get this clear: I did not use [](https://aka.ms/getbcext) to create the copy of the online environment but to set up the server on which i performed the scripts manually. My goal is to give my colleagues a easy to use script for building copys of online environment without using the whole ARM-template every time. 
Thank you!

**Comment by freddydk** [comment]
Got it - just stated that bacpac import used to work because you wrote whether anyone ever tested this.
And I am pretty sure that this is not a ContainerHelper nor ARM Template problem.

**Comment by tfenster** [comment]
Small comment: I am currently working on enabling SaaS restores within 4PS which is slightly more complicated than "normal" SaaS environments, but I can confirm that it technically works. We are not using the ARM templates, but a container for doing the conversion, so a different setup, but in general the same approach

**Comment by mmenninghaus** [comment]
The ARM template works fine, but does not allow the usage of a bacpac *and* an separate SQL server on the vm.
Any hint, why the ARM template does not allow both/ only allows the usage of a bacpac with SQL express variant?

**Comment by freddydk** [comment]
Likely because that functionality was never prioritized:-(
