### ISSUE TITLE
New-NavContainer fails if container exists before

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/navcontainerhelper#290]
Using New-NavContainer to refresh an already existing container. The container is then first removed, including the shared folder. But then I get this error message:

> Remove-Item : Cannot remove item C:\ProgramData\NavContainerHelper\Extensions\bcsandboxnl\my: The process cannot access the file 'C:\ProgramData\NavContainerHelper\Extensions\bcsandboxnl\my' because it is 
> being used by another process.

Can't continue, need to reboot first.

**Comment by freddydk** [comment]
Is that something you can repro?
I just tried with a Windows 10 and a Windows Server to create and recreate the same container 20 times - I didn't see this.
Typically I see the error if I have CSide open - then i close CSide and re-run the new-navcontainer and then it works.

**Comment by NAVspecialist** [comment]
Are portainer running? I have seen this once and in my case it was because portainer was running in a browser client.

**Comment by ajkauffmann** [comment]
Yes, it happens every time again:

Removing container bcsandbox
Removing bcsandbox from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bcsandbox
Remove-Item : Cannot remove item C:\ProgramData\NavContainerHelper\Extensions\bcsandbox\my: The process cannot access the file 'C:\ProgramData\NavContainerHelper\Extensions\bcsandbox\my' because it is being used by another process.

Portainer can't be the issue, it's running but not connected because of the problem that the IP address changes after every reboot.

Can't find another process that keeps a lock on the folder. Only a reboot helps, removing the folder right after the reboot works. I guess it's something local as others don't have the same issue. Just can't find out what that local issue would be.

**Comment by NAVspecialist** [comment]
I can help you with portainer :)

$ipAddress = (get-netadapter | Select-Object -First 1 | get-netipaddress | ? addressfamily -eq 'IPv4').ipaddress
docker run -d -p 9000:9000 --name portainer -h portainer --restart=always -v C:\Docker\Portainer:C:\Data portainer/portainer  --no-auth -H tcp://${ipAddress}:2375

# Remove existing portainer line
Set-Content -Path "$env:windir\System32\Drivers\etc\hosts" -Value (get-content -Path "$env:windir\System32\Drivers\etc\hosts" | Select-String -Pattern 'portainer' -NotMatch)

##add portainer ip:host mapping to host file
$ipadd = docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' portainer
Add-Content -Value "${ipadd} portainer" -Path "$env:windir\System32\Drivers\etc\hosts"

**Comment by freddydk** [comment]
Did you try https://docs.microsoft.com/en-us/sysinternals/downloads/procmon to check who locks the file?
Are you running Windows 10?
What date does your executable have?

**Comment by freddydk** [comment]
I was able to repro this and I assume that it is a timing issue.
Will be fixed in 0.4.3.1 - and I will close this when that ships.
Please reopen if this doesn't solve the issue.

**Comment by freddydk** [comment]
Shipped in 0.4.3.1
