### ISSUE TITLE
How to get failed submission from New-AppSourceSubmission.ps1 

### ISSUE THREAD

**Issue by fridrichovsky** [microsoft/navcontainerhelper#2900]
**Describe the issue**
I have problem with failed submissions. I am using function New-AppSourceSubmission.ps1 for submissions. My problem is that submission ends with error, but function do not raise error. Mentioned function write text "New AppSource submission failed" and return variable $sm. Member state from variable is "InProgress". Can you change write-host to write-error? Or somehow return information that it was failed (for example force state to failed in $sm variable)? 
```
        if ($failed) {
            Write-Host -ForegroundColor Red "New AppSource submission failed"
        }
        else {
            Write-Host -ForegroundColor Green "New AppSource submission succeeded"
        }
```

**Scripts used to create container and cause the issue**
```
$newSubmission = New-AppSourceSubmission -authContext $authContext -productId $aProduct.id -appFile $appFile -libraryAppFiles $libraryAppFiles -autoPromote -doNotWait -silent -doNotCheckVersionNumber -force -ErrorAction Stop
```

**Full output of scripts**
```
Automated validation......... Failure
New AppSource submission failed
Submission state: InProgress
```

**Additional context**
- it happens all the time?

**Comment by freddydk** [comment]
The result of the validation must be found in partner center or using telemetry.
I have not (yet) built anything into containerhelper to retrieve this.

**Comment by freddydk** [comment]
Thinking more about this - the validation results are part of App Insights and there are PowerBI dashboards, which gives you access to the validation results easily.
We am not going to add anything to BcContainerHelper for this.
We might add functionality in AL-Go for GitHub to query AppInsights - https://github.com/orgs/microsoft/projects/521/views/1?filterQuery=results&pane=issue&itemId=27506707
But this won't be in ContainerHelper - it will be a separate workflow/action
