### ISSUE TITLE
How to create new BC Container with SQL 2022

### ISSUE THREAD

**Issue by mkilinskidev** [microsoft/navcontainerhelper#2903]
Hey. I've downloaded my customer's backup file from Azure SQL Managed Instance and I need to create a local container, but there is a compatibility issue. Backup has been created from SQL 16.0 and container is working with internal SQL 15.0 server. Is it possible to update SQL in the container?

**Comment by MODUSCarstenScholling** [comment]
I recommend an external SQL server, on the host for example. This avoids such incompatibilities and is, in my opinion, more independent and flexible with regard to the database. Just my 2 cents :)

**Comment by freddydk** [comment]
> I recommend an external SQL server, on the host for example. This avoids such incompatibilities and is, in my opinion, more independent and flexible with regard to the database. Just my 2 cents :)

Agree - this is the way to go.
The size of the database inside the container is also limited due to SQL Express.

**Comment by mkilinskidev** [comment]
I've figured it out. In simple words you need to download a SQL Express/Developer 2022 Server, make an upgrade of existing SQL instance, add a new PowerShell Module path to PSModulePath environment variable and that's all :)

---
1. Create a clean container.
2. Download and unzip the SQL Express/Developer 2022 ISO and copy unzipped files to C:\bcartifacts.cache
3. Make some magic:
```
Enter-BcContainer -containerName somename
[somename] PS C:\Run> cd C:\dl\SQLServer2022-x64-ENU-Dev\
[somename] PS C:\dl\SQLServer2022-x64-ENU-Dev> .\setup.exe /q /ACTION=Upgrade /IACCEPTSQLSERVERLICENSETERMS /INSTANCENAME=SQLEXPRESS /INDICATEPROGRESS
```
4. Wait until done.
5. Make more magic:
```
[somename] PS C:\dl\SQLServer2022-x64-ENU-Dev> $env:PSModulePath = $env:PSModulePath+';C:\Program Files (x86)\Microsoft SQL Server\160\Tools\PowerShell\Modules\'
[somename] PS C:\dl\SQLServer2022-x64-ENU-Dev> exit
Restore-DatabasesInBcContainer -containerName somename -bakFile C:\bcartifacts.cache\backup\somename\onprem\database.bak
```
That's all. Simple, isn't it? :)

**Comment by freddydk** [comment]
Thanks for the explanation
