### ISSUE TITLE
Feature Request: Add -testAppFile to New-AppSourceSubmission

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/navcontainerhelper#2910]
Generally with each app updated we also provide an updated test app.
It would be nice, if this app could be uploaded when calling ```New-AppSourceSubmission``` as well, so we don't need to open Partner Center in the browser to upload the new test app version.

**Comment by freddydk** [comment]
The Test apps are not used in Partner Center - we are not running your tests.
In fact we have a feature request on the partner center team to remove that page totally.
This is the reason for that parameter not to be there,
