### ISSUE TITLE
Authentification Error using Registered App in New-BcAuthContext

### ISSUE THREAD

**Issue by YvesDesrumaux** [microsoft/navcontainerhelper#2911]
**The issue**
I am using a registered Application in Azure to publish new apps. the ```New-BcAuthContext``` seems to work fine.
But whatever the next function used I received a 401 not authorized error.
When I use my user authentification, it works fine.

**Full output of scripts**
```
$authcontext = New-BcAuthContext `
    -clientID "12345677-1234-4000-1234-000000000000" `
    -clientSecret "AaBbCcDdEeFf...." `
    -Scopes "https://api.partner.microsoft.com/.default" `
    -TenantID "00000000-0000-4000-0000-000000000000"
Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
Authenticated as app 12345677-1234-4000-1234-000000000000

Get-AppSourceProduct -authContext $authcontext -productName $ExtensionName -silent
Get-AppSourceProduct Telemetry Correlation Id: 0d5806ba-b40f-4205-844e-95e0b85539d8
Le serveur distant a retourné une erreur : (401) Non autorisé.
Unauthorized
Au caractère C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.14\AppSource\Invoke-IngestionAPI.ps1:69 : 17
+                 throw (GetExtendedErrorMessage $_)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Le serveur dist...
Unauthorized
:String) [], RuntimeException
    + FullyQualifiedErrorId : Le serveur distant a retourné une erreur : (401) Non autorisé.
Unauthorized
...
```

I guess I miss something in the app registration but I do not know where. I created 3 times the app registered and get the same error.
Any chance to have an idea of what I did wrong?

**Comment by freddydk** [comment]
Did you register the aad app inside Partner Center?

**Comment by YvesDesrumaux** [comment]
No, we took the aad app Id from Partner Center and then find it in AAD and add permission and secret.

**Comment by freddydk** [comment]
The app needs to be in Partner Center under Account Settings, like this:
![image](https://user-images.githubusercontent.com/10775043/220697740-eb0f16a5-fca6-4ebb-9623-73249521e7b3.png)

Not sure whether you are saying that it is - or not?

**Comment by kaezanted** [comment]
Hello there, i got the same issue but i don't have the "Azure AD Applications" tab under User management ?
I created application under the "App management" tab but I'm struggling to add the manager permission to the application.
