### ISSUE TITLE
CopySymbolsFromContainer in Compile doesn't copy enough (OnPrem)

### ISSUE THREAD

**Issue by lktraser** [microsoft/navcontainerhelper#2912]
**Describe the issue**
I switched to using filesOnly containers for my pipelines for performance reasons. I'm entirely doing my own dependency management offline. So I'm running compile in an OnPrem filesOnly container without auth to a saas tenant. Using -CopySymbolsFromContainer I would expect to have access to all Microsoft apps but sadly that's not the case for OnPrem artifacts. Could we get similar behavior as the as the saas artifacts are using?

My proposal would be something like:
![image](https://user-images.githubusercontent.com/76940360/218685673-6f7a63d1-9792-4253-a378-e718dfa46e38.png)

**Scripts used to create container and cause the issue**
```
```

**Full output of scripts**
```
```

**Comment by freddydk** [comment]
Will investigate what can be done for on-premises.

**Comment by lktraser** [comment]
It would be great to get an update on this topic as it blocks builds that for example depend on MS E-Mail Extensions.

**Comment by freddydk** [comment]
I think the code which should fix this is:
```
        Invoke-ScriptInBcContainer -containerName $containerName -scriptblock { Param($appSymbolsFolder) 
            if (Test-Path "C:\Extensions\*.app") {
                $paths = @(
                    "C:\Program Files\Microsoft Dynamics NAV\*\AL Development Environment\System.app"
                    "C:\Extensions\*.app"
                )
            }
            elseif (!(Test-Path "C:\Applications.*\*.app")) {
                $paths = @(
                    "C:\Program Files\Microsoft Dynamics NAV\*\AL Development Environment\System.app"
                    "C:\Applications\*\source\*.app"
                )
            }
            else {
                $paths = @(
                    "C:\Program Files\Microsoft Dynamics NAV\*\AL Development Environment\System.app"
                    "C:\Applications.*\Microsoft_Application_*.app,C:\Applications\Application\Source\Microsoft_Application.app"
                    "C:\Applications.*\Microsoft_Base Application_*.app,C:\Applications\BaseApp\Source\Microsoft_Base Application.app"
                    "C:\Applications.*\Microsoft_System Application_*.app,C:\Applications\System Application\source\Microsoft_System Application.app"
                )
            }
            $paths | ForEach-Object {
                $appFiles = $_.Split(',')
                $appFile = ""
                if (Test-Path -Path $appFiles[0]) {
                    $appFile = $appFiles[0]
                }
                elseif (Test-Path -path $appFiles[1]) {
                    $appFile = $appFiles[1]
                }
                if ($appFile) {
                    Get-ChildItem -Path $appFile -Recurse | ForEach-Object {
                        Write-Host "Copying $([System.IO.Path]::GetFileName($_.FullName)) from Container"
                        Copy-Item -Path $_.FullName -Destination $appSymbolsFolder -Force
                    }
                }
            }
        } -argumentList $containerSymbolsFolder
```

If you have a chance to test this, it would be great.

On a similar topic, the next containerhelper (i.e. currently in preview) introduces something called a compilerfolder, Which basically is containerless compiling (which I will use instead of filesonly in AL-Go for GitHub)
I do not have any docs yet, as this is work in progress.

**Comment by lktraser** [comment]
I'll try to test with that code. Thank you!

_On a similar topic, the next containerhelper (i.e. currently in preview) introduces something called a compilerfolder, Which basically is containerless compiling (which I will use instead of filesonly in AL-Go for GitHub)
I do not have any docs yet, as this is work in progress._

This sounds exactly like what I want for my build pipelines. Is there a preview of this feature? Will it also enable Runtime creation without an NST? This would reduce my deployment time by ~90%

**Comment by freddydk** [comment]
The runtime creation requires the ModernDev team to add this to the compiler first - but then yes.
Will get back with some docs on how you can do this.

**Comment by lktraser** [comment]
I just checked the repo and saw that it's all in there. I'll implement it for my CI/CD module today! This looks exciting, thanks as always.

**Comment by freddydk** [comment]
> I think the code which should fix this is:
> 
> ```
>         Invoke-ScriptInBcContainer -containerName $containerName -scriptblock { Param($appSymbolsFolder) 
>             if (Test-Path "C:\Extensions\*.app") {
>                 $paths = @(
>                     "C:\Program Files\Microsoft Dynamics NAV\*\AL Development Environment\System.app"
>                     "C:\Extensions\*.app"
>                 )
>             }
>             elseif (!(Test-Path "C:\Applications.*\*.app")) {
>                 $paths = @(
>                     "C:\Program Files\Microsoft Dynamics NAV\*\AL Development Environment\System.app"
>                     "C:\Applications\*\source\*.app"
>                 )
>             }
>             else {
>                 $paths = @(
>                     "C:\Program Files\Microsoft Dynamics NAV\*\AL Development Environment\System.app"
>                     "C:\Applications.*\Microsoft_Application_*.app,C:\Applications\Application\Source\Microsoft_Application.app"
>                     "C:\Applications.*\Microsoft_Base Application_*.app,C:\Applications\BaseApp\Source\Microsoft_Base Application.app"
>                     "C:\Applications.*\Microsoft_System Application_*.app,C:\Applications\System Application\source\Microsoft_System Application.app"
>                 )
>             }
>             $paths | ForEach-Object {
>                 $appFiles = $_.Split(',')
>                 $appFile = ""
>                 if (Test-Path -Path $appFiles[0]) {
>                     $appFile = $appFiles[0]
>                 }
>                 elseif (Test-Path -path $appFiles[1]) {
>                     $appFile = $appFiles[1]
>                 }
>                 if ($appFile) {
>                     Get-ChildItem -Path $appFile -Recurse | ForEach-Object {
>                         Write-Host "Copying $([System.IO.Path]::GetFileName($_.FullName)) from Container"
>                         Copy-Item -Path $_.FullName -Destination $appSymbolsFolder -Force
>                     }
>                 }
>             }
>         } -argumentList $containerSymbolsFolder
> ```
> 
> If you have a chance to test this, it would be great.
> 
> On a similar topic, the next containerhelper (i.e. currently in preview) introduces something called a compilerfolder, Which basically is containerless compiling (which I will use instead of filesonly in AL-Go for GitHub) I do not have any docs yet, as this is work in progress.

Did you ever have a chance to test this? - or did you switch to compilerfolder?

**Comment by lktraser** [comment]
Hi Freddy, I did not get to test it and already switched over to use compile folders by now. (BTW loving compile folders)

From my side this topic can be closed.
