### ISSUE TITLE
Export objects to text should not depend on creating CSide 

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/navcontainerhelper#292]
I use an external to to explore exported objects. E.g. where is an object used, what events and functions does an object have, etc. 

But why is exporting objects linked to the parameter includeCSide? I don't need CSide, I just want the exported objects. :-)

It isn't clear that the parameter doNotExportObjectsToText is linked to includeCSide. Wouldn't it be an idea to turn it into exportObjectsToText as a separate and individual parameter? Ok, that's breaking change, but still it would make much more sense to me.

**Comment by freddydk** [comment]
It probably would make a lot more sense. I will put that on the wish-list

**Comment by ajkauffmann** [comment]
If I may add one more wish to that list: please don't remove the full export file after the split. The tool I use is way faster with importing a full text export instead of importing a folder with 7000 files.

You also might consider to use a different export path, e.g. navcontainerhelper\objects instead of mixing them up with the container folders in the navcontainerhelper\extensions folder.

**Comment by freddydk** [comment]
BTW. I am not going to move the folders as this would be a breaking change for everybody using this.

**Comment by freddydk** [comment]
AJ, I looked at this.

With the future in mind, this is very tied to CSIDE. The exporting objects to text is old format and old functionality and will be deprecated when we switch to AL.

We might get new functions for exporting the AL (if possible), they will not share parameter name.

What you should do is really just to call export-navcontainerobjects after creating the container - with exportto set to "txt file" - then you get exactly what you want.

I won't change anything in New-Navcontainer for this.
