### ISSUE TITLE
Executing Run-TestsInNavContainer on a NAV2018 container is not working

### ISSUE THREAD

**Issue by codeunitone** [microsoft/navcontainerhelper#2920]
Hey,

I am running a NAV 2018  container (11.0.46360) and would like to execute tests via `Run-TestsInNavContainer`.

I am running following command

```PowerShell
Run-TestsInNavContainer `
  -containerName 'MyTestContainer' `
  -companyName 'xxx' `
  -testSuite REGR_INIT `
  -sqlCredential $sqlCredentials `
  -credential $NavUserCredentials `
  -testPage 130401
```

I am getting following error

```text
Connecting to http://'MyTestContainer'/NAV/cs?tenant=default&company=xxx
Run-Tests, open page 130401
UnhandledException : Invalid cast from 'System.String' to 'System.TimeSpan'.
at <ScriptBlock>, C:\ProgramData\BcContainerHelper\Extensions\MyTestContainer\PsTestTool\ClientContext.ps1: line 119
at InvokeInteractionAndCatchForm, C:\ProgramData\BcContainerHelper\Extensions\MyTestContainer\PsTestTool\ClientContext.ps1: line 268
at OpenForm, C:\ProgramData\BcContainerHelper\Extensions\MyTestContainer\PsTestTool\ClientContext.ps1: line 291
at Run-Tests, C:\ProgramData\BcContainerHelper\Extensions\MyTestContainer\PsTestTool\PsTestFunctions.ps1: line 535
at Run-TestsInBcContainer, C:\Users\user.name\Documents\WindowsPowerShell\Modules\BcContainerHelper\4.0.14\AppHandling\Run-TestsInNavContainer.ps1: line 329
at <ScriptBlock>, <No file>: line 1
Current Interaction: Microsoft.Dynamics.Framework.UI.Client.Interactions.OpenFormInteraction
Time spend: 0 seconds
```

The Url `http://MyTestContainer/NAV/cs?tenant=default&company=xxx` looks odd to me. If I am opening that Url in a browser I am getting a `Sorry, the page could not be found.` error. After I removed the `cs?tenant=default` from it, the WebClient is opening.

I checked the `Run-TestsInNavContainer` source code and I could not find any parameter that suppresses adding `cs?tenant=default` to the Url.

Am I doing something wrong? Is NAV2018 not compatible with the BcContainerHelper?

**Comment by freddydk** [comment]
Did you try to remove the testpage parameter?
Run-tests should use the right testpage for NAV 2018
(We are running tests for running tests on all versions since 2016, so it should work)
Test run from NAV 2018: https://github.com/microsoft/navcontainerhelper/actions/runs/4095140645/jobs/7061853332

**Comment by freddydk** [comment]
BTW Run-Tests use Client Services endpoint - not something you can open in a browser.

**Comment by codeunitone** [comment]
Thanks for the quick response.

If I'm removing the `-TestPage` parameter, I do get the error `The metadata object Page 130409 was not found.` 

The container I'm using is connected to a database located outside the container. That DB has already a Test Toolkit installed (from Product DVD) which does not contain any Page with ID 130409. The ID of the `CAL Test Tool` Page in out installation is `130409`

**Comment by codeunitone** [comment]
Here is the command I used to create the container where I would like execute the tests

```PowerShell
New-BcContainer `
  -accept_eula `
  -containerName 'MyTestContainer' `
  -databaseServer 'someserver' `
  -databaseInstance '' `
  -databaseName 'somedatabase' `
  -artifactUrl (Get-BCArtifactUrl -type OnPrem -country de -version 11.0.46360) `
  -databaseCredential $(Get-Credential) `
  -updateHosts `
  -auth NavUserPassword
```

**Comment by freddydk** [comment]
130401 is the "user friendly" page
130409 is the "API friendly" page

For these old versions, the page 130409 was not included in NAV, but is in a .fob file in ContainerHelper.
It should be automatically imported, not sure why this didn't happen.
The .fob files are here:
https://github.com/microsoft/navcontainerhelper/blob/master/AppHandling
and is called pstesttoolpage.fob (for NAV 2018)

If you remove the PsTestTool folder under c:\programdata\bccontainerhelper\extensions\<containername> and re-run Run-Tests - it should import the right .fob file.
(else you can do it manually)

**Comment by codeunitone** [comment]
I imported the Page and now it is working. Thanks a lot
