### ISSUE TITLE
Run-TestsInBCContainer: Performance gets prohibitive once -disabledTests parameter gets larger

### ISSUE THREAD

**Issue by VPaas2** [microsoft/navcontainerhelper#2924]
**Describe the issue**
Running the Run-TestsInBCContainer runs into severe performance issues once the -disabledTests parameter gets larger. Once the number of disabled tests is in the order of 100's or 1000's the performance is prohibitive and takes hours to process. For the lower number of tests it eventually did succeed but for larger amounts of disabled tests it took far too long and was an order of magnitude longer than running without excluded tests. Tried both with converting the disabled tests file to a PSObject and a hashtable but for both performance was prohibitive. Performance hangs at the start of the test suite, execution of actual tests is the same amount of time as usual.  

**Scripts used to create container and cause the issue**

```
$password = [password];
$credential = New-Object System.Management.Automation.PSCredential ("[user]", $password)

$containerName = "[Container]"
$app = Get-NavContainerAppInfo $containerName | Where-Object { $_.Name -eq "Tests-ERM" }
$BuildParameters = Get-Content "TestsToDisable.json" | ConvertFrom-Json

$tests = Get-TestsFromBCContainer `
    -containerName $containerName `
    -credential $credential `
    -extensionId $app.AppId `
    -ignoreGroups

$tests | ForEach-Object {
    Run-TestsInBCContainer `
        -containerName $containerName `
        -credential $credential `
        -detailed `
        -disabledTests $BuildParameters  
}

```
Format of TestsToDisable.json:
```
[
	{
		"codeunitName": "TestCodeunit1",
		"method": "Test1"
	},
	{
		"codeunitName": "TestCodeunit1",
		"method": "Test2"
	},
	{
		"codeunitName": "TestCodeunit2",
		"method": "Test3"
	}
]
(etc * 1000)
```

**Full output of scripts**
```
PS C:\WINDOWS\system32> C:\DisableTests.ps1
Connecting to http://localhost:8080/BC/cs?tenant=default
  Codeunit 51854 TestCodeunit1 Success (3.826 seconds)
    Testfunction Test1 Skipped
    Testfunction Test2 Success (0.143 seconds)
   ...
```

**Comment by freddydk** [comment]
I can imagine that 1000s of disabled tests will have a negative effect on performance.
It is really not designed for that. Why would you have 1000s of disabled tests?

My recommendation is to have a disabledtests file for every test app - and if you have 1000s of disabled tests in one test app, I think you should remove the test app or remove the tests.

If you are using disabledTests to control extensive and light testing, then my recommendation would be to have some test apps for light testing and other for comprehensive testing - and run only one or both based on what you need.

**Comment by ChrisBlankDe** [comment]
Hi Freddy
this use case is not that unusual. we also do this when we test our verticals.
we create a container and run all ms tests first. the failed ones we write to a disabledTests.json.
then we install our vertical and run all microsoft tests again with disabledTests.json.

this tells us which microsoft tests we break by our vertical.

**Comment by freddydk** [comment]
Are you using a disabledtests.json per test app? (or one big global one)?

**Comment by ChrisBlankDe** [comment]
a big global one since we do not execute the ms tests app by app. but that might already help.
@VPaas2 i think that would be worth a try.

**Comment by VPaas2** [comment]
Hi guys, I also benchmarked the performance after splitting up the disabledtests. The total performance is still problematic.

I benchmarked with 60,180 and 500 disabled tests in the JSON and for every case it takes an extra 0.21-0.23 seconds per test to process the disabled tests, which is longer than actually running the test in many cases. 

60 tests - 14 extra seconds
180 tests - 39 extra seconds
525 tests - 117 extra seconds

**Comment by freddydk** [comment]
Ok, this is really a shortcoming of the way the AL Test Runner implemented the disabledTests (I think)
@nikolakukrika - is there other ways they can do this?

**Comment by VPaas2** [comment]
@ChrisBlankDe This is indeed similar to what we do. The number of Microsoft tests is quite sizeable so any performance increase is welcome.

**Comment by freddydk** [comment]
Maybe one "easy" mechanism would be that instead of disabling the tests - run them all and compare whether the failing tests wheren't failing before?
