### ISSUE TITLE
Cannot find path 'C:\run\my\aes.key' because it does not exist. NAV 2016

### ISSUE THREAD

**Issue by TrippyZ** [microsoft/navcontainerhelper#2925]
Container startup error during creation for NAV 2016 GB cu 9

I get an interesting error if I do restart-bccontainer jnk;

Initializing...
Cannot find path 'C:\run\my\aes.key' because it does not exist.
at <ScriptBlock>, C:\Run\SetupVariables.ps1: line 64
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 25
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
Restart-BcContainer Telemetry Correlation Id: 99df4b92-46f2-4c4f-8bb0-1201bbec2f1a
Initialization of container jnk failed
At C:\Users\Chris.Watson\Documents\WindowsPowerShell\Modules\BcContainerHelper\4.0.10\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container jnk failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container jnk failed

=========
FULL SCRIPT
$containerName = 'jnk'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NAVArtifactUrl -country 'gb' -nav 2016 -cu 9
New-BcContainer `
    -accept_eula `
    -accept_outdated `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -includeCSIDE `
    -doNotExportObjectsToText `
    -isolation hyperv `
    -updateHosts 

==
SCRIPT OUTPUT

BcContainerHelper version 4.0.10
BC.HelperFunctions emits usage statistics telemetry to Microsoft
BcContainerHelper is version 4.0.10
BcContainerHelper is not running as administrator
UsePsSession is False
Host is Microsoft Windows 10 Enterprise - 22H2   
Docker Client Version is 20.10.22
Docker Server Version is 20.10.22
Removing Session jnk
Removing container jnk
Removing entries from hosts
Removing jnk from container hosts file
Removing jnk-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\jnk
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container jnk
Style: onprem
Multitenant: No
Version: 9.0.46290.0
Platform: 9.0.46290.0
Generic Tag: 1.0.2.14
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19045.2604 (22H2)
Using hyperv isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\jnk\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container jnk from image mcr.microsoft.com/businesscentral:10.0.19041.1415
6ff9b83fbc3a12e8b04913e8159900632e1f57df072e31b2718d8a4840c70624
Waiting for container jnk to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.46290.0/gb
Using installer from C:\Run\90
Copying Platform Artifacts
c:\dl\onprem\9.0.46290.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
c:\dl\onprem\9.0.46290.0\gb\Installers
Copying TestToolKit
c:\dl\onprem\9.0.46290.0\gb\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\9.0.46290.0\gb\UpgradeToolKit
Installing NAV
Starting Local SQL Server
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\GB\OlAddin\OutlookAddIn.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\RTC\RoleTailoredClient.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\Server\Server.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\WebClient\WebClient.Local.Gb.msi
Skipping C:\NAVDVD\Installers\GB\WebHelp\WebHelp.Local.Gb.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting NAV Service Tier
Importing CRONUS license file
Stopping NAV Service Tier
Installation took 149 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.240.1 in container hosts file
Starting Container
Hostname is jnk
PublicDnsName is jnk
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 9BEE6E997AD715C07B7A3BD7AE9D48B5522567AC
DNS identity jnk
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVDError
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.46290.0/gb
Using installer from C:\Run\90
Copying Platform Artifacts
c:\dl\onprem\9.0.46290.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
c:\dl\onprem\9.0.46290.0\gb\Installers
Copying TestToolKit
c:\dl\onprem\9.0.46290.0\gb\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\9.0.46290.0\gb\UpgradeToolKit
Installing NAV
Starting Local SQL Server
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\GB\OlAddin\OutlookAddIn.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\RTC\RoleTailoredClient.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\Server\Server.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\WebClient\WebClient.Local.Gb.msi
Skipping C:\NAVDVD\Installers\GB\WebHelp\WebHelp.Local.Gb.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting NAV Service Tier
Importing CRONUS license file
Stopping NAV Service Tier
Installation took 149 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.240.1 in container hosts file
Starting Container
Hostname is jnk
PublicDnsName is jnk
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 9BEE6E997AD715C07B7A3BD7AE9D48B5522567AC
DNS identity jnk
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVD
Initialization of container jnk failed
At C:\Users\Chris.Watson\Documents\WindowsPowerShell\Modules\BcContainerHelper\4.0.10\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container jnk failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container jnk failed

**Comment by freddydk** [comment]
Could you try this with the latest containerhelper?

**Comment by TrippyZ** [comment]
According to 'a' powershell window I though I already was running the latest.  However, I definetly am now.  With the same input script still the same error.  

Eventlog shows the following;

The description for Event ID 200 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

**Server instance: NAV
The service MicrosoftDynamicsNavServer$NAV failed to start. This could be caused by a configuration error. Detailed error information: System.ArgumentException: It is likely that certificate 'CN=jnk' may not have a private key that is capable of key exchange or the process may not have access rights for the private key. Please see inner exception for detail. ---> System.Security.Cryptography.CryptographicException: Invalid provider type specified.**

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.ServiceModel.Security.SecurityUtils.GetKeyContainerInfo(X509Certificate2 certificate)
   at System.ServiceModel.Security.SecurityUtils.CanKeyDoKeyExchange(X509Certificate2 certificate)
   at System.ServiceModel.Security.SecurityUtils.EnsureCertificateCanDoKeyExchange(X509Certificate2 certificate)
   --- End of inner exception stack trace ---
   at System.ServiceModel.Security.SecurityUtils.EnsureCertificateCanDoKeyExchange(X509Certificate2 certificate)
   at System.ServiceModel.Security.ServiceCredentialsSecurityTokenManager.CreateServerX509TokenProvider()
   at System.ServiceModel.Security.ServiceCredentialsSecurityTokenManager.CreateLocalSecurityTokenProvider(RecipientServiceModelSecurityTokenRequirement recipientRequirement)
   at System.ServiceModel.Security.ServiceCredentialsSecurityTokenManager.CreateSecurityTokenProvider(SecurityTokenRequirement requirement)
   at System.ServiceModel.Channels.SslStreamSecurityUpgradeProvider.CreateServerProvider(SslStreamSecurityBindingElement bindingElement, BindingContext context)
   at System.ServiceModel.Channels.ConnectionOrientedTransportChannelListener..ctor(ConnectionOrientedTransportBindingElement bindingElement, BindingContext context)
   at System.ServiceModel.Channels.TcpChannelListener..ctor(TcpTransportBindingElement bindingElement, BindingContext context)
   at System.ServiceModel.Channels.TcpTransportBindingElement.BuildChannelListener[TChannel](BindingContext context)
   at System.ServiceModel.Channels.SessionChannelDemuxer`2..ctor(BindingContext context, TimeSpan peekTimeout, Int32 maxPendingSessions)
   at System.ServiceModel.Channels.ChannelDemuxer.CreateTypedDemuxer(Type channelType, BindingContext context)
   at System.ServiceModel.Channels.ChannelDemuxer.GetTypedDemuxer(Type channelType, BindingContext context)
   at System.ServiceModel.Channels.ChannelDemuxer.BuildChannelListener[TChannel](BindingContext context, ChannelDemuxerFilter filter)
   at System.ServiceModel.Channels.ChannelBuilder.BuildChannelListener[TChannel]()
   at System.ServiceModel.Channels.ChannelBuilder.BuildChannelListener[TChannel](MessageFilter filter, Int32 priority)
   at System.ServiceModel.Channels.SecurityChannelListener`1.InitializeListener(ChannelBuilder channelBuilder)
   at System.ServiceModel.Channels.TransportSecurityBindingElement.BuildChannelListenerCore[TChannel](BindingContext context)
   at System.ServiceModel.Channels.ReliableChannelListener`3..ctor(ReliableSessionBindingElement binding, BindingContext context)
   at System.ServiceModel.Channels.ReliableListenerOverSession`5..ctor(ReliableSessionBindingElement binding, BindingContext context)
   at System.ServiceModel.Channels.ReliableListenerOverDuplexSession`2..ctor(ReliableSessionBindingElement binding, BindingContext context)
   at System.ServiceModel.Channels.ReliableSessionBindingElement.BuildChannelListener[TChannel](BindingContext context)
   at Microsoft.Dynamics.Nav.Types.Channels.ChunkingBindingElement.BuildChannelListener[TChannel](BindingContext context)
   at System.ServiceModel.Channels.Binding.BuildChannelListener[TChannel](Uri listenUriBaseAddress, String listenUriRelativeAddress, ListenUriMode listenUriMode, BindingParameterCollection parameters)
   at System.ServiceModel.Description.DispatcherBuilder.MaybeCreateListener(Boolean actuallyCreate, Type[] supportedChannels, Binding binding, BindingParameterCollection parameters, Uri listenUriBaseAddress, String listenUriRelativeAddress, ListenUriMode listenUriMode, ServiceThrottle throttle, IChannelListener& result, Boolean supportContextSession)
   at System.ServiceModel.Description.DispatcherBuilder.BuildChannelListener(StuffPerListenUriInfo stuff, ServiceHostBase serviceHost, Uri listenUri, ListenUriMode listenUriMode, Boolean supportContextSession, IChannelListener& result)
   at System.ServiceModel.Description.DispatcherBuilder.InitializeServiceHost(ServiceDescription description, ServiceHostBase serviceHost)
   at System.ServiceModel.ServiceHostBase.InitializeRuntime()
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.StartWcfServices()
   at Microsoft.Dynamics.Nav.WindowsServices.NavServerWindowsService.Start(String commandLineServiceInstanceName).

Element not found


=============
Full log again;
BcContainerHelper version 4.0.14
BC.HelperFunctions emits usage statistics telemetry to Microsoft
BcContainerHelper is version 4.0.14
BcContainerHelper is not running as administrator        
UsePsSession is False
Host is Microsoft Windows 10 Enterprise - 10.0.19045.2604
Docker Client Version is 20.10.22
Docker Server Version is 20.10.22
Removing Session jnk
Removing container jnk
Removing entries from hosts
Removing jnk from container hosts file
Removing jnk-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\jnk
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container jnk
Style: onprem        
Multitenant: No      
Version: 9.0.46290.0 
Platform: 9.0.46290.0
Generic Tag: 1.0.2.14
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19045.2604 (22H2)     
Using hyperv isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\jnk\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container jnk from image mcr.microsoft.com/businesscentral:10.0.19041.1415
04924b8b52cb4602a7570ef5624f62454ae4523e9040920edcfd10db60f06081
Waiting for container jnk to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.46290.0/gb
Using installer from C:\Run\90
Copying Platform Artifacts
c:\dl\onprem\9.0.46290.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
c:\dl\onprem\9.0.46290.0\gb\Installers
Copying TestToolKit
c:\dl\onprem\9.0.46290.0\gb\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\9.0.46290.0\gb\UpgradeToolKit
Installing NAV
Starting Local SQL Server
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\GB\OlAddin\OutlookAddIn.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\RTC\RoleTailoredClient.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\Server\Server.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\WebClient\WebClient.Local.Gb.msi
Skipping C:\NAVDVD\Installers\GB\WebHelp\WebHelp.Local.Gb.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting NAV Service Tier
Importing CRONUS license file
Stopping NAV Service Tier
Installation took 145 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.240.1 in container hosts file
Starting Container
Hostname is jnk
PublicDnsName is jnk
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 32D69B902C21C9F35572FBC6D79A4172104C49A1
DNS identity jnk
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVDError
Using artifactUrl https://bcartifacts.azureedge.net/onprem/9.0.46290.0/gb
Using installer from C:\Run\90
Copying Platform Artifacts
c:\dl\onprem\9.0.46290.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
c:\dl\onprem\9.0.46290.0\gb\Installers
Copying TestToolKit
c:\dl\onprem\9.0.46290.0\gb\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\9.0.46290.0\gb\UpgradeToolKit
Installing NAV
Starting Local SQL Server
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\GB\OlAddin\OutlookAddIn.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\RTC\RoleTailoredClient.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\Server\Server.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\WebClient\WebClient.Local.Gb.msi
Skipping C:\NAVDVD\Installers\GB\WebHelp\WebHelp.Local.Gb.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting NAV Service Tier
Importing CRONUS license file
Stopping NAV Service Tier
Installation took 145 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.8.155 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.240.1 in container hosts file
Starting Container
Hostname is jnk
PublicDnsName is jnk
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 32D69B902C21C9F35572FBC6D79A4172104C49A1
DNS identity jnk
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVD
New-BcContainer Telemetry Correlation Id: 0b071d0d-2230-4c74-9479-7ef617aad1ca
Initialization of container jnk failed
At C:\Users\obfuscated\Documents\WindowsPowerShell\Modules\BcContainerHelper\4.0.14\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container jnk failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container jnk failed

C:\Users\obfuscated\Documents\Customers\J & K Acquatics
PS >Restart-BcContainer jnk
Removing Session jnk
jnk
Waiting for container jnk to be ready

Initializing...
Cannot find path 'C:\run\my\aes.key' because it does not exist.
at <ScriptBlock>, C:\Run\SetupVariables.ps1: line 64
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 25
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1Error

Initializing...
Cannot find path 'C:\run\my\aes.key' because it does not exist.
at <ScriptBlock>, C:\Run\SetupVariables.ps1: line 64
at <ScriptBlock>, C:\Run\my\SetupVariables.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 25
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1

==========
Restart-BcContainer Telemetry Correlation Id: 3b633301-a474-4ce2-934b-a6737d5ff90d
Initialization of container jnk failed
At C:\Users\obfuscated\Documents\WindowsPowerShell\Modules\BcContainerHelper\4.0.14\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container jnk failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container jnk failed

**Comment by freddydk** [comment]
The first output showed 4.0.10 - second one says 4.0.14 (which is the newest)
But this is a different error - for old versions of NAV, you might need to add 

-myscripts @('https://raw.githubusercontent.com/microsoft/nav-docker/master/override/SelfSignedCertificateEx/SetupCertificate.ps1')

as the mechanism that works with newer versions doesn't work with older.

**Comment by TrippyZ** [comment]
Thank you very much.  That is working fine.

**Comment by aptMattKoe** [comment]
> The first output showed 4.0.10 - second one says 4.0.14 (which is the newest) But this is a different error - for old versions of NAV, you might need to add
> 
> ```
> -myscripts @('https://raw.githubusercontent.com/microsoft/nav-docker/master/override/SelfSignedCertificateEx/SetupCertificate.ps1')
> ```
> 
> as the mechanism that works with newer versions doesn't work with older.

helped me today. From one container creation to the next I got this error. No idea why but this helped.
(BC9 / NAV2016)
