### ISSUE TITLE
License File for 3rd Party Apps 

### ISSUE THREAD

**Issue by HinnackX1** [microsoft/navcontainerhelper#2927]
Hello Freddy, 

we have an app with a dependency to a 3rd party app. When we try to install this app, we get the error message "Your program license does not allow you to publish (Our Extension)". Why need a developer license for pipeline / docker container but not in development in cloud environment ? 

Kind regards

**Comment by freddydk** [comment]
I hope that we will be able to make the CRONUS license into a developer license (with which you can install and work with all apps (with the limitation that you only can work during 3 calendar months).
But until then, you need a license. The why is probably historic reasons more than anything else.

**Comment by HinnackX1** [comment]
Okay, thanks for your answer
