### ISSUE TITLE
Business Central Container certificate expired

### ISSUE THREAD

**Issue by bhavanimuppalmani** [microsoft/navcontainerhelper#2938]
Hello

Business Central Container certificate expired in our environments. We are getting the error below

**The Service Principal Name (Delegation) configuration has been set incorrectly. Server connect URL: "net.tcp://localhost:7046/BC/Service". SPN Identity: "DynamicsNAV/localhost:7046"
  The X.509 certificate (CN=BCCloudLatest; 6D23034CD2CA6D6C832867228F1A67BEA0E883B2) usage time is invalid.  The usage time '2/24/2023 9:05:44 AM' does not fall between NotBefore time '2/10/2022 1:37:09 PM' and NotAfter time '2/10/2023 1:57:09 PM'. The X.509
 certificate CN=BCCloudLatest; 6D23034CD2CA6D6C832867228F1A67BEA0E883B2 chain building failed. The certificate that was used has a trust chain that cannot be verified. Replace the certificate or change the certificateValidationMode. A required certificate is
 not within its validity period when verifying against the current system clock or the timestamp in the signed file.** 

How do we renew the certificate for a BC container?

Thanks
Bhavani

**Comment by mvajid** [comment]
You can do this by generating a new certificate and importing it to the container. I created a set of commands to achieve this.

#1.Copy the new certificate to the extension folder: "C:\ProgramData\BcContainerHelper\Extensions\<containername>\my"

#2.Remote into container:
`Enter-BcContainer -containerName $containername`

#3. Execute the Certificate Script from inside the container:
```
$certPfxFile = "c:\Run\my\star.tesdomain.com.p12"
$certPfxPassword = "**********"
$dnsidentity = "*.testdomain.com"
$publicDnsname = "www.testdomain.com"

$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2 -ArgumentList $certPfxFile,$certPfxPassword
$certificateThumbprint = $cert.Thumbprint

Write-Host "Certificate File Thumbprint $certificateThumbprint"
if (!(Get-Item "Cert:\LocalMachine\my\$certificateThumbprint" -ErrorAction SilentlyContinue)) {
    Write-Host "Import Certificate to LocalMachine\my"
    $certPfxSecurePassword = ConvertTo-SecureString -String $certPfxPassword -AsPlainText -Force
    Import-PfxCertificate -FilePath $certPfxFile -CertStoreLocation "cert:\localmachine\my" -Password $certPfxSecurePassword | Out-Null
}
```

#4. Get list of certificates:
`Get-ChildItem cert:\localmachine\my`

#5. Remove the expiring/expired certificate thumbprint:
`Remove-Item -Path Cert:\localmachine\My\0000000000000000000000000000000000000000`

#6. Pass certificate to a variable and bind information:
```
Import-Module WebAdministration
$cert = Get-ChildItem cert:\localmachine\my
$bindingInfo = "IIS:\SSLBindings\*!443"
$cert | Set-Item -Path $bindingInfo
```

#7. Restart IIS:
`iisreset /noforce`

#8. Update NAV/BC service instance with new certificate thumbprint and restart instance:
```
Set-NAVServerConfiguration BC -KeyName ServicesCertificateThumbprint -KeyValue 0000000000000000000000000000000000000000
Restart-NAVServerInstance BC
```

#9. Restart-BcContainer
```
Exit-PSSession
Restart-BcContainer -containername $containername
```
