### ISSUE TITLE
Add a switch to Import-BcContainerLicense to update c:\demo\settings.ps1

### ISSUE THREAD

**Issue by mjmatthiesen** [microsoft/navcontainerhelper#2940]
**Describe the issue**
As bc licenses expire I use the import command so the current container still works. Eventually the container is recreated with replace-bccontainer. The settings.ps2 file still uses a url to an old license file. It never gets updated. For me, it would be beneficial to update this every time I run import-bclicense, but I can see why some partners may not want this.
Would be great if the command got an additional flag so I don't run into the issue weeks later when the container is recreated.

**Scripts used to create container and cause the issue**
```
Replace-BcServerContainer
```

**Full output of scripts**
```
Using license file https://old-url.com/lic.flf
Downloading c:\bcartifacts.cache\teskhczu.n3d\my\license.flf
Using WebClient
Error downloading..., retrying in 6 seconds...
Using WebClient
New-Bcimage Telemetry Correlation Id: b2f7261f-5d66-4771-b9e1-1741c739c471
Container output
Error: No such container: bcserver
Replace-BcServerContainer Telemetry Correlation Id: 4ee18306-ed80-469d-8d88-1779ebe9d9e8
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
```

**Additional context**
- does it happen all the time? yes
- did it use to work? no

**Comment by freddydk** [comment]
I think a better fix would be to add a licensefile parameter to Replace-BcServerContainer (as that is ONLY used on Azure VMs and knows about c:\demo\settings.ps1)
In fact it already has an artifactUrl parameter which is basically the same.

**Comment by freddydk** [comment]
A licenseFileUri parameter is added to the Replace-BcServerContainer in the next version
