### ISSUE TITLE
Wrong BC version in artifacts for OnPrem 18.18

### ISSUE THREAD

**Issue by left-code** [microsoft/navcontainerhelper#2941]
Wrong artifact version for BC 18.18

**Scripts used to get artifacts**
```
Get-BCArtifactUrl -type OnPrem -country de -version 18.18
```

**Full output of scripts**
```
https://bcartifacts.azureedge.net/onprem/18.18.46920.0/de
```
Artifacts version **18.18.46920.0** and it's expected **18.18.49460** according to official information:
https://support.microsoft.com/en-us/topic/update-18-18-for-microsoft-dynamics-365-business-central-2021-release-wave-1-application-build-18-18-49460-platform-build-18-0-49352-9ad174b8-3cfd-468f-8bab-d29ca13febfe

It's same for all countries.

**Labels in image based on this artifact**
```
"platform": "18.0.46905.0",
"tag": "1.0.2.14",
"version": "18.18.46920.0"
```

**Additional context**
- does it happen all the time? Yes
- did it use to work? Not sure

**Comment by freddydk** [comment]
Looks like the artifacts are wrong and the documentation is correct.
We will work on getting the right version out there

**Comment by left-code** [comment]
@freddydk Any news regarding this issue?

**Comment by freddydk** [comment]
I have requested the right 18.18 version to be published and the old deleted, will notify here when done.

**Comment by freddydk** [comment]
Unfortunately, it isn't possible for the team to republish the 18.18 without significant work.

The workaround would be to download the DVD image and use that with New-BcContainer instead of the artifactUrl.
like:
```
New-BcContainer -accept_eula -NAVDVD 'c:\temp\DVD1818' -....
```

Sorry
