### ISSUE TITLE
Issue on using "UploadImportAndApply-ConfigPackageInBcContainer"

### ISSUE THREAD

**Issue by Bjerris1** [microsoft/navcontainerhelper#2945]
Hi

I'm trying to use the "UploadImportAndApply-ConfigPackageInBcContainer" command getting a Configuration package of ~53 mb into BC 21.4 Container (OnPrem install)
I can do it manually without any errors (after I've updated the "maxallowedcontentlength" on the IIS).

I can Import the file using the 
Invoke-ScriptInNavContainer -containername $containerName -scriptblock {Import-NAVConfigurationPackageFile -Path $ConfigPackage3 -ServerInstance 'BC' -force}
command, but from here I still need having the file applied, and cannot find a command other than the BCContainer command.

As far as I can see, then the issue is when it's trying to perform the "Upload" part of the command.

I've tried to update the "MaxStreamReadSize", but that doesn't solve the issue.

Is there some kind of Max for the upload?

PS C:\WINDOWS\system32> UploadImportAndApply-ConfigPackageInBcContainer -containerName $ContainerName -Credential $credential -companyName $CompanyName -configPackage $ConfigPackage3 -packageId 'LSC.DEMO.PACK.NO2'
Invoke GET on http://172.21.244.90:7048/BC/api/v1.0/companies?$filter=name%20eq%20%27CRONUS%20Danmark%20A%2FS%27&tenant=default
Deleting Configuration Package LSC.DEMO.PACK.NO2 (if exists)
Invoke DELETE on http://172.21.244.90:7048/BC/api/microsoft/automation/v1.0/companies(3127f3b4-daa1-ed11-988c-6045bd87d0d3)/configurationPackages('LSC.DEMO.PACK.NO2')?tenant=default
Creating Configuration Package LSC.DEMO.PACK.NO2
Invoke POST on http://172.21.244.90:7048/BC/api/microsoft/automation/v1.0/companies(3127f3b4-daa1-ed11-988c-6045bd87d0d3)/configurationPackages?tenant=default
Uploading Configuration Package LSC.DEMO.PACK.NO2
Invoke PATCH on http://172.21.244.90:7048/BC/api/microsoft/automation/v1.0/companies(3127f3b4-daa1-ed11-988c-6045bd87d0d3)/configurationPackages('LSC.DEMO.PACK.NO2')/file('LSC.DEMO.PACK.NO2')/content?tenant=default
UploadImportAndApply-ConfigPackageInBcContainer Telemetry Correlation Id: 528dd858-1235-4e56-8f91-ed5e9d873fbe
Invoke-RestMethod : Fjernserveren returnerede en fejl: (500) Intern serverfejl.
At C:\Users\lbj\OneDrive - RelateIT A S\Dokumenter\WindowsPowerShell\Modules\BcContainerHelper\4.0.14\Api\Invoke-NavContainerApi.ps1:175 char:5
+     Invoke-RestMethod -Method $Method -uri "$url" -Headers $headers @ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by Bjerris1** [comment]
@freddydk Any ideas to this?

**Comment by Bjerris1** [comment]
I get this error from the Event Log
[Event log.docx](https://github.com/microsoft/navcontainerhelper/files/11086993/Event.log.docx)

**Comment by Bjerris1** [comment]
These settings are already altered
Invoke-ScriptInNavContainer -containername $containerName -scriptblock {
    Set-NavServerConfiguration -ServerInstance BC -KeyName EnableTaskScheduler -KeyValue true
    Set-NavServerInstance -ServerInstance BC -restart
}

Invoke-ScriptInNavContainer -containername $containerName -scriptblock {
    Set-NavServerConfiguration -ServerInstance BC -KeyName ODataServicesMaxPageSize -KeyValue 200000
    Set-NavServerInstance -ServerInstance BC -restart
}

Invoke-ScriptInNavContainer -containername $containerName -scriptblock {
    Set-NavServerConfiguration -ServerInstance BC -KeyName MaxStreamReadSize -KeyValue 1000000000
    Set-NavServerInstance -ServerInstance BC -restart
}

Invoke-ScriptInNavContainer -containername $containerName -scriptblock {
    Set-NavServerConfiguration -ServerInstance BC -KeyName SOAPServicesMaxMsgSize -KeyValue 100000
    Set-NavServerInstance -ServerInstance BC -restart
}

**Comment by Bjerris1** [comment]
Further investigation shows me, that I'm getting this error in the Event log

### **_Message: The request's Content-Length 55020545 is larger than the request body size limit 30000000._**

But both my ClientServicesMaxUploadSize and ODataMaxBodySize are set to 350, so I'm unsure where this size limit is from.

**Comment by fridrichovsky** [comment]
May be I am wrong but I suppose that the limit goes from IIS where is maxAllowedContentLength. More is in
[MS documentation](https://learn.microsoft.com/en-us/iis/configuration/system.webserver/security/requestfiltering/requestlimits/)

**Comment by Bjerris1** [comment]
Hi - Yes, and I tried to alter it with this line
docker exec -it $ContainerName C:\Windows\system32\inetsrv\appcmd.exe set config "NavWebApplicationContainer" /section:requestfiltering /requestlimits.maxallowedcontentlength:107374182

But it doesn't seem to work

**Comment by Bjerris1** [comment]
Hi
I've tried with the script lines you send, but I'm still getting the error:

Server instance: BC
Tenant ID: 
Environment Name: 
Environment Type: 
Type: System.IO.IOException
Message: The request's Content-Length 55020545 is larger than the request body size limit 30000000.
StackTrace:

**Comment by fridrichovsky** [comment]
I do not know if it helps. I found this ODataMaxBodySize default value is 350, but I do not know unit of measure. It is paramater from BC so you can try set bigger number for this.

**Comment by Bjerris1** [comment]
Specifies the maximum request body size, in megabytes, supported in OData.

Default: 350
Dynamically Updatable: No

INTRODUCED IN: Version 21.0

**Comment by freddydk** [comment]
Did you manage to make this work - or do you still have a problem?
If you still have the problem, I would need a rapidstart package, with which I can repro the problem to see what happens.
Thanks

**Comment by Bjerris1** [comment]
Hi @freddydk 
Unfortunately not. 
I cannot upload a file bigger than 25 mb in this thread, so how should I send the rapidstart package to you?

**Comment by freddydk** [comment]
If you can place it in a dropbox, onedrive, storage account or like and send me a download URL in an email (freddyk at microsoft dot com)
Thanks

**Comment by freddydk** [comment]
I have a repro.

**Comment by freddydk** [comment]
This is a bug in BC.
It will be fixed and backported to 21 and 22 next CU

**Comment by freddydk** [comment]
On 21, we are looking for a version with a platform release 21.0.55964.0.
21.6 is using platform 21.0.54828.0, which means that it is not included in that.
![image](https://user-images.githubusercontent.com/10775043/236631047-97139a08-8f46-4c8f-8152-34f61d067b49.png)

I expect 21.7 to have this. Unfortunately, we do not push daily builds from 21, but I think 21.7 should be out in a week or 2.

**Comment by freddydk** [comment]
21.7 was shipped yesterday and I can confirm that the script you emailed me works with 21.7 (uploading the large rapidstart package)
