### ISSUE TITLE
Suggestion Getting Started Section in the README.md

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#2946]
**Describe the issue**
I'd like to add a Getting Started section to the README.md. What do you think about this?

### VM on Azure
- Follow the steps on https://aka.ms/bcsandbox

### Local Installation on Windows or Windows Server
This would be the Steps to install BCContainerHelper on Windows 11 or Windows Server 2022:
### Prepair Host
- Run PowerShell as Admin:
```PowerShell
Install-WindowsFeature Containers -Restart
```
Server restarts.

- Run PowerShell as Admin:
```PowerShell
Install-Module -Name DockerMsftProvider -Repository PSGallery –Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Force
$service = Get-Service "docker"
if ($service.Status -eq "Stopped")
{
  Start-Service -Name "docker"
}
```

### Install BCContainerHelper
- Run PowerShell as Admin:
```PowerShell
Install-PackageProvider -Name NuGet -Force
Install-Module BcContainerHelper -force
```

### Create you first container
- Run PowerShell as Admin:
```PowerShell
$url = Get-BCArtifactUrl -select Latest -type OnPrem -country W1
$cred = Get-Credential 
New-BcContainer -accept_eula -artifactUrl $url -Credential $cred -auth NavUserPassword
```

**Comment by freddydk** [comment]
You're very welcome

**Comment by freddydk** [comment]
I grabbed your section above and added it to https://github.com/microsoft/navcontainerhelper/blob/master/README.md#getting-started

(Did some small modifications though)

Thanks

If you want to add something or suggest changes, feel free to create a PR:-)

**Comment by DanielGoehler** [comment]
@freddydk Thanks.
