### ISSUE TITLE
Run-TestsInBcContainer: Unable to load one or more of the requested types.

### ISSUE THREAD

**Issue by CarlosAndreuLlaneras** [microsoft/navcontainerhelper#2949]
Hi, 
When executing a pipeline to run the tests in BC22 dockers, it fails with the following error message:

`Run-TestsInBcContainer -containerName $DockerInstance 
                       -credential $Credential 
                       -extensionId $AppId 
                       -detailed 
                       -XUnitResultFileName $ResultsFileName 
                       -AppendToXUnitResultFile 
                       -AzureDevOps "warning"`

`Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information`

![image](https://user-images.githubusercontent.com/53298196/227265885-8f1c480c-87a2-4f8d-ace8-27b6bcece653.png)

The docker has been deployed as singletenant and use traefik:
`New-BcContainer -accept_eula 
                -containerName "$ContainerName" 
                -credential $Credential 
                -auth "NavUserPassword" 
                -artifactUrl "$ArtifactUrl" 
                -licenseFile "$LicenseFile" 
                -updateHosts 
                -accept_outdated 
                -useTraefik 
                -useBestContainerOS 
                -includeTestToolkit 
                -includeTestLibrariesOnly 
                -multitenant:$false`

Any advice will be welcome.

Thanks

**Comment by esteinmann** [comment]
We faced this issue too with the latest BC22 artifacts (tests were running fine before the 22.x artifacts). In our case the likely cause was the version of the docker image. We still used an older preview of BcContainerHelper and a -dev version of the docker image was used. Installing the latest stable BcContainerHelper (4.0.15) seems to have solved this.

**Comment by CarlosAndreuLlaneras** [comment]
Hi @esteinmann , I updated bcontainerhelper to the latest version and now it is working OK.
Thanks.
