### ISSUE TITLE
Export-NavContainerDatabasesAsBacpac expose two new params

### ISSUE THREAD

**Issue by cvale** [Microsoft/navcontainerhelper#295]
We had an issue with Export-NavContainerDatabasesAsBacpac when creating BACPAC from tenant database with actual data. Since error output was really poor, I edited Export-NavContainerDatabasesAsBacpac.ps1and added following lines:

`            $arguments = @(
                ('/Action:Export'), 
                ('/TargetFile:"'+$targetFile+'"'), 
                ('/SourceDatabaseName:"'+$databaseName+'"'),
                ('/SourceServerName:"'+$databaseServer+'"'),
                ('/OverwriteFiles:True'),
                **('/Diagnostics:True'),  <<ADDED LINE
                ('/p:CommandTimeout=3600') <<ADDED LINE**

Can you please add those as params to Export-NavContainerDatabasesAsBacpac? Or, even better, add new parametar called DACArguments that would be joined with $arguments...

Thanks

**Comment by freddydk** [comment]
Will be included in next release

**Comment by freddydk** [comment]
Shipped in 0.4.3.0
