### ISSUE TITLE
Problems with Build Pipelines using NextMinor and NextMajor

### ISSUE THREAD

**Issue by DanielGoehler** [microsoft/navcontainerhelper#2960]
**Describe the issue**
We have additional ALOps Pipelines that check if our Solution will face any issue with upcoming NextMinor and NextMajor. Currently they fail because `Get-BCArtifactUrl` doesn't outputs any url. 
What would be the best way to deal with these issue until that new artifacts are created?

**Scripts used to create container and cause the issue**
```PowerShell
Get-BCArtifactUrl `
    -country de  `
    -select NextMinor
    -type Sandbox
    -sasToken "..." 
```

**Full output of scripts**
```
BcContainerHelper version 4.0.14
BC.HelperFunctions emits usage statistics telemetry to Microsoft
```

**Comment by freddydk** [comment]
Yeah, the reason for this is that 22.0 shipped today and we will resume next minor and next major shortly after.
and... - when I try now, I do get a nextmajor:
![image](https://user-images.githubusercontent.com/10775043/229560238-a49d8441-5a6f-4907-8ea4-df46357fb777.png)

and also a nextminor:
![image](https://user-images.githubusercontent.com/10775043/229560475-089b5e1d-9573-434c-95ec-fe2f87703c38.png)

with the right (new) insider sas token from collaborate

**Comment by freddydk** [comment]
I guess nextmajor and nextminor could fall back to current if no artifacts was found, but this might be better implemented in your pipelines. Not sure about the consequences of doing this in Get-BcArtifactUrl.
Need to think that through.

**Comment by DanielGoehler** [comment]
Thanks. I can't do this myself, but I have created an issue for ALOps (https://github.com/HodorNV/ALOps/issues/626).

This could also be addressed in AL Go for GitHub, if not already done.

**Comment by waldo1001** [comment]
> I guess nextmajor and nextminor could fall back to current if no artifacts was found, but this might be better implemented in your pipelines. Not sure about the consequences of doing this in Get-BcArtifactUrl. Need to think that through.

As I understand it, it's a "Get-BcArtifactUrl" issue when it doesn't return a result while it should?  🤔
Any other solution would just be a workaround .. 🤷‍♂️

**Comment by freddydk** [comment]
Get-BcArtifactUrl returns no result if there are no next major or next minor available.
At the time of release, we restart next major and next minors - which will give some hours delay.
Starting them early would also be a problem.

**Comment by NSilvergrund** [comment]
I have the same problem with my DevOps pipelines right now. Run-AlPipeline, can't get neither next minor or next major.

**Comment by freddydk** [comment]
That problem should have fixed itself in a few hours - today - both should work just fine

**Comment by NSilvergrund** [comment]
Still not working, any changes in the parameters that I've missed?

**Comment by freddydk** [comment]
@NSilvergrund the problem you have is not the same as the issue which opened this.
Next Minor builds and Next Major builds are flowing again, and you can see here:
https://github.com/BusinessCentralApps/BingMaps.AppSource/actions

That the workflows are running weekly.
Latest Minor build used was: /sandbox/22.1.55336.0/us
Latest Major build used was: /sandbox/23.0.10468.0/us

Please create a new issue with more information about what is failing, thanks
