### ISSUE TITLE
Question: Could it be that that dotnet is missing in .netpackages export when creating a container with -includeAL

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#2969]
So,

with BC22 the new dotnet 6 is coming around the corner and we are checking our dependencies - which we unfortunately still have. 
So in order to perform this transition it would be indeed helpful to get the dotnet folder also collected into the .netpackages while container creation. 

Unless you say it would  make more sense to install dotnet 6 on the developer machines ... ?! Not sure how the VS Code extensions is processing this (or the alc) .. while checking for the probing paths it has for sure the setup from the AL extension in mind, but it also checks the GACs ..
_C:\Windows\Microsoft.NET\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089, C:\Windows\Microsoft.NET\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089'_

does it also check for dotnet 6 installations? if not I am back to my question: can we get the dotnet assemblies from the container into .netpackages folder on the host? :) 

What would others say ?! 

(And yes: the obvious I know: get rid of this stuff in your app...we  are on it!)

**Comment by KristofKlein** [comment]
I can see you made your compiler run with the correct framework once it finds the "22" in AppHandling/Compile-AppWithoutDocker.ps1 ... so this piece here:

   if ($platformversion.Major -ge 22) {
        $probingPaths = @((Join-Path $dllsPath "OpenXML"), 'C:\Program Files\dotnet\Shared') + $probingPaths
    }
    else {
        $probingPaths = @((Join-Path $dllsPath "OpenXML"), 'C:\Windows\Microsoft.NET\Assembly') + $probingPaths

I my eyes it would make totally sense to get this also into the "includeAL" logic...those poor custom baseapp modifier must need this as well (luckily this we managed to get away with...)

**Comment by freddydk** [comment]
Yes, I will add this

**Comment by freddydk** [comment]
Shipped in 5.0.0
