### ISSUE TITLE
Cannot publish runtime apps due to image issue

### ISSUE THREAD

**Issue by jpreniers** [microsoft/navcontainerhelper#2977]
When I publish a runtime app created with a BC22 container I get a error:

The media object could not be loaded because it is not a valid image type, such as JPEG, GIF, or PNG.
Exception Script Stack Trace:

at <ScriptBlock>, <No file>: line 41

PowerShell Call Stack:

at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.16\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 71

at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.16\AppHandling\Publish-NavContainerApp.ps1: line 295

at Publish-BcContainerApp, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.16\AppHandling\Publish-NavContainerApp.ps1: line 146

at <ScriptBlock>, <No file>: line 3

 

Services in container bc220:

- MicrosoftDynamicsNavServer$BC is Running

- MSSQL$SQLEXPRESS is Running

 

Publish-BcContainerApp Telemetry Correlation Id: 2fd75da0-1f6b-4fae-97ec-36dd4c068acb

The media object could not be loaded because it is not a valid image type, such as JPEG, GIF, or PNG.

At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.16\ContainerHandling\Invoke-ScriptInNavContainer.ps1:112 char:13

    + throw $errorMessage

    + CategoryInfo          : OperationStopped: (The media objec...G, GIF, or PNG.:String) [], RuntimeException

    + FullyQualifiedErrorId : The media object could not be loaded because it is not a valid image type, such as JPEG, GIF, or PNG.

I've created the runtime app as I always do with the script:

$containerName = "bc"
$licenseFile = ''
$sasToken = ''
$artifactUrl = $artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -country 'nl' -select 'Latest'
Convert-BcAppsToRuntimePackages `
-skipVerification `
-containerName $containerName `
-artifact $artifactUrl `
-licenseFile $licenseFile `
-apps 'C:\temp\Runtime' `
-destinationFolder 'C:\BusinessCentral'

I can install in a BC22.0 Docker environment for example an “normal” app file. 
When I create a runtime package app from this “normal” app with Convert-BcAppsToRuntimePackages, I cannot publish this runtime app. I get the above error

When I change in the “normal” app file the .png file to a smaller .png file (from 520x512 pixels to 230x230 pixels) and create a new runtime package I can publish it without any problem! So something is going wrong when converting the app to a runtime app with the logo file.

Are there any new requirements for these logo files?

**Comment by thloke** [comment]
This is a known issue that has been fixed in 22.0.55450 of the platform.

There are no new requirements for the logo files, we just had a bug in how we packaged runtime packages. :(

**Comment by freddydk** [comment]
Thanks @thloke

BTW. The latest 22.0 artifacts are using platform 22.0.55661.0 (Get-BcContainerPlatformVersion)

**Comment by Mike-1984** [comment]
Hello,

We are using On-Prem images for Germany, and the latest available image has platform version 22.0.**55180**.0
Can we do anything at this point? 

BcContainerHelper version 5.0.0
```
Get-BCArtifactUrl -type OnPrem -country de -version 22 -select All 
https://bcartifacts.azureedge.net/onprem/22.0.54157.54635/de
https://bcartifacts.azureedge.net/onprem/22.0.54157.55195/de
```


```
BcContainerHelper is version 5.0.0
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Enterprise - 10.0.19044.2846
Docker Client Version is 20.10.21
Docker Server Version is 20.10.21
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container BC22-Aut-v1
Style: onprem
Multitenant: No
Version: 22.0.54157.55195
**Platform: 22.0.55180.0**

```

**Comment by freddydk** [comment]
You can either wait for 22.1 to ship or use a sandbox image and use -runsandboxasonprem (if that works for you)

**Comment by larswestman** [comment]
I got the same error in BC22.1 onprem (platform version 22.0.56191).
