### ISSUE TITLE
BcContainerHelper version 4.0.17-preview964 Cleanup Task fails with error "Get-ChildItem : Cannot find path 'C:\ProgramData\BcContainerHelper\compiler' because it does not exist."

### ISSUE THREAD

**Issue by BW-PA** [microsoft/navcontainerhelper#2979]
**Describe the issue**
Using preview of bccontainerHelper has been failing recently with the error

Get-ChildItem : Cannot find path 'C:\ProgramData\BcContainerHelper\compiler' because it does not exist.

![image](https://user-images.githubusercontent.com/78051738/231047927-af45c99e-72a3-4695-a305-f9661c104f68.png)

If I change settings.json to use the "latest" version of bcContainerHelper instead of "Preview" then the cleanup task succeeds

![image](https://user-images.githubusercontent.com/78051738/231048156-4eb81e1c-b6fc-406f-bc3f-634539a2bd64.png)

**Additional context**
- does it happen all the time? Consistently when using preview version.  Builds are completed on an Azure VMSS so clean machine per build.

- did it use to work? Yes, last successful run using the preview version was BcContainerHelper version 4.0.17-preview952 
![image](https://user-images.githubusercontent.com/78051738/231048577-a89e2358-201a-49aa-98ab-3ac19d44970c.png)

**Comment by kine** [comment]
I confirm that latest pre-release version solved the issue for us.

**Comment by BW-PA** [comment]
Can also confirm that a recent build using the preview version succeeded.  Will close this now.

![image](https://user-images.githubusercontent.com/78051738/231624134-ee2d7fbe-794d-4af7-b1a2-b56a9329b602.png)
