### ISSUE TITLE
InvalidSecurity Error if Host and Container OS have different Locale Settings

### ISSUE THREAD

**Issue by nitewhiz** [Microsoft/navcontainerhelper#298]
My Windows 10 (1809) is using German regional formats. When I try to create a NAV 2018 CU4 NA docker container it gives me this error when I run the win client (dev/web client works):

> The client could not establish a connection to the Microsoft Dynamics NAV Server.
> FaultCode = 'InvalidSecurity'
> Reason = 'An error occurred when verifying security for the message.'

I am quite sure that the reason for this is that the host local settings are not matching the container OS local settings. Here is also a post about this:

https://community.dynamics.com/nav/b/stefanodemiliani/archive/2018/04/28/dynamics-nav-and-the-strange-faultcode-invalidsecurity-error

I tried to change the container settings from within the container by:
Set-WinSystemLocale de-DE 

This did not work.
Any idea how I can fix this?

**Comment by rasmusskov** [comment]
Im having the same issue, and it seems like the time is off in your NAV container. My timezone is correct, but the time is off by 9 hours...
On my computer, this seems to be an issue with the generic image that is used when using the -useBestContainerOS switch...

**Comment by NAVspecialist** [comment]
When I use new-navcontainer -then in the docker logs theres a message saying:
(I am also using UseBestContainerOS  - DK-Version)

WARNING: Container starts with TimeZone = Rom, normaltid, which is not recognized in the list of TimeZones.

The Container works though

**Comment by rasmusskov** [comment]
Im not getting that warning, and the timezone in my container is the same as on my computer... Just the actual time itself is incorrect in the container...
Sede the two screenshots... First is from my local computer, and second from the container..  +9 hours in the container.. Trying to update the time in the container manually returns "A required privilege is not held by the client"

![image](https://user-images.githubusercontent.com/29218809/50634675-cb59be00-0f4f-11e9-90a5-44ef5c0ee97c.png)
![image](https://user-images.githubusercontent.com/29218809/50634792-107df000-0f50-11e9-90d0-2654b3150c21.png)

**Comment by nitewhiz** [comment]
Am am experiencing exactly the same rasmusskov does. The time zones are identical between host and container but the time is 9h ahead in the container. How did you try to update the time in the container?

**Comment by rasmusskov** [comment]
I tried both with powershell Set-Date, and good old dos command "date"..

**Comment by freddydk** [comment]
and this only happens if you are using -useBestContainerOS?
I know that there have been changes to datetime handling in windows server core 1803 and later - so this might be caused by that.
Could you try to run a standard windows server core image with docker run and check whether time is off in that as well?

Thanks

**Comment by rasmusskov** [comment]
The latest windows server core works fine with date/time, but running it with 1803 has the same time difference...    ex.   "docker run -it microsoft/windowsservercore:1803 cmd.exe".

Same if i run the microsoft/dynamics-nav:generic-1803..

**Comment by freddydk** [comment]
Are you saying that 1809 works? but not generic 1809?
and you have the latest generic 1809?

**Comment by rasmusskov** [comment]
no... both microsoft/windowsservercore:1803 and microsoft/dynamics-nav:generic-1803 has the time difference... And yes, i beleive im using the latest image...  Below from docker inspect

"microsoft/windowsservercore:1803"  "Created": "2018-12-11T14:09:09.6992138-08:00",

"microsoft/dynamics-nav:generic-1803" "Created": "2018-12-15T15:38:41.3343871Z",

**Comment by nitewhiz** [comment]
Hi Freddy,
I used the -useBestContainerOS option. Without that, I got the error that container operating system and host operating system don't match. My container is on 1803 and my host is on 1809.

**Comment by freddydk** [comment]
nitewiz - we don't ship any contianers on 1803???
What image are you using? - you should just be using the 1809 images directly (add -ltsc2019 to the image name)

rasmus - did you try on 1809?
I believe this is a bug in 1803.

**Comment by freddydk** [comment]
And you have the latest navcontainerhelper?

**Comment by nitewhiz** [comment]
Thanks Freddy. I think I had the latest version but I updated it anyway and also recreated the container with the -ltsc2019 option. It's working now :)

Thank's a lot! 
Rasmus - let us know if this works for you as well.

**Comment by rasmusskov** [comment]
@freddydk  do you mean the windowsservercode? When running that with ltsc2016, the time is as it should be

**Comment by freddydk** [comment]
@rasmusskov - No I am thinking - do you see this problem with other containers than 1803?

**Comment by rasmusskov** [comment]
@freddydk, no, i have not seen it with other containers than 1803... And thats the container my system is using when i use the -usebestcontaineros switch, since thats the windows version on my computer.
My "workaround" so far has been not to use the switch, but i have a theory that the containers is "lighter" when i dont have to use Hyper-v isolation.

**Comment by freddydk** [comment]
Any reason why you haven't installed 1809?
Then you will have the native ltsc2019 images - and you will be able to leverage process isolation when docker releases this.

**Comment by rasmusskov** [comment]
No specific reason.. .Windows update has not pushed it on my yet...

**Comment by freddydk** [comment]
Ok, you can force the update yourself if you like.

**Comment by rasmusskov** [comment]
Yes.. did that, and now it works with -usebestcontainerOS.. Thanks @freddydk
