### ISSUE TITLE
Sign-BcContainerApp not signing .app properly (2)

### ISSUE THREAD

**Issue by mishof** [microsoft/navcontainerhelper#2987]
Good Morning

I hope you can help me out
Sign-BcContainerApp is not working for me.
I've tried different timeservers, but without success.
Below the script I've been using to test this. My pipeline isn't signing the files either.

$PfxPassword = ConvertTo-SecureString -String $PfxPwd -AsPlainText -Force

Sign-BcContainerApp `
-containerName 'latest' `
-appFile $AppFile `
-PfxFile $PfxFileName `
-PfxPassword $PfxPassword

When I use the above, BC containerhelper tells me that my file has been signed successfully:

PS C:\Windows\system32> Sign-BcContainerApp `
-containerName 'latest' `
-appFile $AppFile `
-PfxFile $PfxFileName `
-PfxPassword $PfxPassword
Copying certificate file to container
Signing C:\Run\my\sign\my.app
Done Adding Additional Store
Successfully signed: C:\Run\my\sign\my.app

But when I check the file (in the file properties by gui there is nothing to bee seen, other downloaded .exe file for example do show up with the cert in the file properties. When I use or by using below powershell:

PS C:\Windows\system32> $IsSigned = Get-AuthenticodeSignature -FilePath "C:\Users\aa\Downloads\Cryptomator-1.7.2-x64.exe"

PS C:\Windows\system32> $IsSigned.Status
Valid

$IsSigned = Get-AuthenticodeSignature -FilePath $AppFile
$IsSigned.Status

PS C:\Windows\system32> $IsSigned.Status
UnknownError

Below the properties of my certificate:

EnhancedKeyUsageList     : {Code Signing (1.3.6.1.5.5.7.3.3)}
DnsNameList              : {aa}
SendAsTrustedIssuer      : False
EnrollmentPolicyEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
EnrollmentServerEndPoint : Microsoft.CertificateServices.Commands.EnrollmentEndPointProperty
PolicyId                 : 
Archived                 : False
Extensions               : {System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid, System.Security.Cryptography.Oid...}
FriendlyName             : 
IssuerName               : System.Security.Cryptography.X509Certificates.X500DistinguishedName
NotAfter                 : 28-10-2023 01:59:59
NotBefore                : 27-10-2020 01:00:00
HasPrivateKey            : True
PrivateKey               : 
PublicKey                : System.Security.Cryptography.X509Certificates.PublicKey
RawData                  : {48, 130, 5, 95...}
SerialNumber             : 00AF997E7E0A79A864691497C34C8F4014
SubjectName              : System.Security.Cryptography.X509Certificates.X500DistinguishedName
SignatureAlgorithm       : System.Security.Cryptography.Oid
Thumbprint               : 346Exxx
Version                  : 3
Handle                   : 1755xxx
Issuer                   : CN=Sectigo RSA Code Signing CA, O=Sectigo Limited, L=Salford, S=Greater Manchester, C=GB
Subject                  : CN=aa, OU=IT, O=bb, STREET=cc, L=dd, S=ee, PostalCode=ff, C=gg

**Comment by mishof** [comment]
The strange thing is that appsource submission log indicates the app file is signed, but it isn't signed the way it should be.
There are no special tools needed in windows to have the certificate show up in the file properties, and yet it is not showing up:
https://comodosslstore.com/resources/how-to-check-if-a-code-signing-certificate-has-been-applied-correctly/

**Comment by freddydk** [comment]
On that machine, if you download the app in this .zip file: https://businesscentralapps.blob.core.windows.net/bingmaps-appsource/preview/bingmaps-appsource-apps.zip

And watch properties - can you see whether it is signed or not?

**Comment by mishof** [comment]
I can not, but in comparison a signed file; there the properties on the same machine do show the cert:

![image](https://user-images.githubusercontent.com/23643843/232989403-1809c529-5a02-4a56-a4c9-1984843d08f8.png)

I used to sign the app file with signtool from sdk, but this tool seems to keep changing the way it works.
bc-container helper is a much more userfriendly way of signing files.

I am sure the apps I singed with signtool did show the digital signatures in the file properties of the app.
But maybe this all has changed in windows.  Probably there are different ways to sign a file.

**Comment by kine** [comment]
> I can not, but in comparison a signed file; there the properties on the same machine do show the cert: ![image](https://user-images.githubusercontent.com/23643843/232990875-f6b875e1-62d2-4306-9f3b-f609118ef2dc.png)
> 
> I used to sign the app file with signtool from sdk, but this tool seems to keep changing the way it works. bc-container helper is a much more userfriendly way of signing files.
> 
> I am sure the apps I singed with signtool did show the digital signatures in the file properties of the app in the past. I checked my app file that way before I uploaded it to the appstore. But maybe this all has changed in windows. Probably there are different ways to sign a file.

Check the property of the app inside the zip, not the zip itself...

**Comment by mishof** [comment]
Ah, sorry 🙂
But it isn't showing up. I have no doubt it is signed, but just not in the way I am used to have them signed.

![image](https://user-images.githubusercontent.com/23643843/233330414-f8070aad-cce0-470e-ad0c-fd26997f6050.png)

**Comment by freddydk** [comment]
Yes, my app is signed and on my machine, I can see the signature.
![image](https://user-images.githubusercontent.com/10775043/233482852-efb660f2-9124-4b25-9d76-c75902bb0de9.png)

I think you need to install the register the NAVSIP Crypto Provider DLL on the host in order to see the signature of .app files.
You should be able to use Install-NAVSipCryptoProviderFromBcContainer from containerhelper to achieve this.

**Comment by freddydk** [comment]
Assuming that this resolved the confusion.

**Comment by mishof** [comment]
It solved my problem (after running the command on some container, and restarting my pc). Thanks!

But my confusion still remans. 
Why do other application files do show the certificate without installing a specific software first?
The devil must be in the details, but I'm more than happy to settle for this solution.

Thanks again!

**Comment by freddydk** [comment]
Other application files (like .exe, .pdf and more) have this SIP DLL installed by default.
It needs to be installed per type.
