### ISSUE TITLE
Publish-NAVContainerApp fails if using -enableSymbolLoading

### ISSUE THREAD

**Issue by JuricaB** [Microsoft/navcontainerhelper#299]
One of our consultants reported error "Extension Compilation Failed" when publishing the app to container. 

After troubleshooting this, we found it was caused by using -enableSymbolLoading switch in New-NAVContainer command.

If this switch is not used, app is successfully published and can be used. 
E.g.:
New-NavContainer -containerName BC-20190107 -accept_eula -alwaysPull -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:nz -licenseFile C:\temp\lic.flf 

If switch is used, error happens during Publish process
E.g. 
New-NavContainer -containerName BC-20190108 -accept_eula -alwaysPull -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:nz -licenseFile C:\temp\lic.flf  -enableSymbolLoading

Error:
Extension compilation failed
src/codeunit/Cod70046.ACWMatchBankRecLines.al(14,33): error AL0185: Query 'Bank Rec. Match Candidates' is missing
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.4.2.6\AppHandling\Publish-NavContainerApp.ps1:67 char:5
+     Invoke-Command -Session $session -ScriptBlock { Param($appFile, $ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : 16638429c5cdbaa3658f07ae8ebca5a35d7cdc5786a0b7c91c2d05d834ae5270

Note:
Query 'Bank Rec. Match Candidates' is standard object, we verified it is in the database and is compiled.

Please let me know if you need any additional info.

**Comment by JuricaB** [comment]
I've done some further testing today. Recompiling all objects from CSide after creating the container with -enableLoadingSymbols and -IncludeCSide seems to resolve the issue (although I got a ton of errors for various DotNet components on other objects). 

It looks as if -enableLoadingSymbols somehow corrupts the pre-generated symbols in the database, and recompile (as expected) regenerates them?

**Comment by freddydk** [comment]
I have been investigating this and the problem really is, that using enablesymbolloading should actually unpublish the application and the test symbols from the container - it creates confusion about which symbols are the active ones (as you will actually have double symbols).
Next version of NavContainerHelper should fix this issue.

**Comment by freddydk** [comment]
Shipped in 0.5.0.5

**Comment by eknraw** [comment]
Just a heads up... this seems to be causing some grief (myself included).  Seems to have only started to be an issue with BC14 for some reason. 

[https://github.com/Microsoft/AL/issues/4881](https://github.com/Microsoft/AL/issues/4795)

[https://github.com/Microsoft/AL/issues/4881](https://github.com/Microsoft/AL/issues/4881)

This code: 
[https://github.com/Microsoft/navcontainerhelper/blob/25cb999af5a4659efbefbd5e20925c121561aa2a/ContainerHandling/New-NavContainer.ps1#L773](https://github.com/Microsoft/navcontainerhelper/blob/25cb999af5a4659efbefbd5e20925c121561aa2a/ContainerHandling/New-NavContainer.ps1#L773)
