### ISSUE TITLE
Multiple BC server instances

### ISSUE THREAD

**Issue by ernestasjuska** [microsoft/navcontainerhelper#2993]
Hi,

We would like to run multiple BC server instances in same container using port sharing.

Right now we are using BC instances with domain Windows authentication - one instance in each container. We need additional BC server instance along with its own web client instance for testing web services with NavUserPassword auth.

The only workaround we have right now is to create a separate container with NavUserPassword auth. But then we would have additional containers and additional ports we need to manage.

I tinkered with this problem a little. Port sharing works in container. External database also works (I reused existing encryption key). The only things I could not get working are: web server instance (for conveniently generating web service addresses) and after restarting container it would show error about not started server instance.

There should be commands for managing server instances inside container - it should do this in organized manner: it should setup port sharing by default, create separate web client instance, add firewall rule if needed, etc.

Something like this:
```powershell
New-BcContainerServerInstance -containerName $ContainerName -serverInstance $ServerInstance -auth NavUserPassword

# Plus management commands
Set-BcContainerServerInstance -containerName $ContainerName -serverInstance $ServerInstance [-restart] [-stop] [-start] [-configuration @{ ... }]
Remove-BcContainerServerInstance -containerName $ContainerName -serverInstance $ServerInstance
```

Automatically created variable $ServerInstance should be left as it is - it should point to the default instance.
I think port sharing should be enabled by default - it works with System account without changes in SMSvcHost.exe.config file.

Thanks.

**Comment by jonaswre** [comment]
> But then we would have additional containers and additional ports we need to manage.

To make managing ports easier you can checkout the traefik support. This will allow you to set up something like https://my.example.com/my_container which gets rid of all the port handling. 

If you have an "external" sql server and a reverse proxy. Multiple containers will basicly act like multiple instances with the added bonus that they are far better seperated from each other and this is something you can do today, without the need to wait for any changes @freddydk might or might not do.

**Comment by ernestasjuska** [comment]
Hi, our problem with Traefik was, and I don't know if it is fixed, that it did not properly pass Windows authentication information. When you have multiple users connecting to the same container, web client would correctly recognize the first connecting user, say SOFTERA\USER1, but the second user, say SOFTERA\USER2, would be still be recognized as SOFTERA\USER1.

The reason was that IIS was tracking web session according to the client IP - each client is a separate session. But Traefik has a single client IP, so from IIS perspective it would nearly always use the same session. Windows credentials are only sent once for the first request.
Trafik supports passing so X-Real-IP and X-Forwarded-Host headers but IIS ignored them.

Traefik did work correctly with NavUserPassword authentication, because then each request has user & password pair so each individual request is autenticated property.

And finally Traefik that comes with BcContainerHelper is outdated. There is this reverse proxy from Microsoft that probably should be used as a replacement: https://github.com/microsoft/reverse-proxy. YARP does not seem to have built-in support for docker, but it is programable, so that support can be added.

**Comment by freddydk** [comment]
This is not something I will have time to do.
You might be able to do this with Invoke-ScriptInBcContainer and then normal PowerShell commands - but it is not something I will add to ContainerHelper.

**Comment by ernestasjuska** [comment]
I see. I will try to find solution on my own then.

Thanks.
