### ISSUE TITLE
Problems logging in to the webclient

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/navcontainerhelper#3]
It's probably just me no knowing the entire module (just taking the first steps..).

I'm setting up a new container with this:

```
New-CSideDevContainer -containerName WaldoTest `
    -devImageName navdocker.azurecr.io/dynamics-nav:devpreview `
    -licenseFile "C:\Users\Administrator\Dropbox\Dynamics NAV\Licenses\2017 DEV License CRS.flf" `
    -vmAdminUsername vmadmin `
    -adminPassword 'waldo1234'
```
The entire script runs fine (so it seems):
![image](https://user-images.githubusercontent.com/12088142/31961677-b8869d80-b8fb-11e7-9450-7a02a3640283.png)

But I'm unable to log in - it doesn't accept the account.  I tried:
- just a new username/password
- the same username/password as my administrator of the host

**Comment by freddydk** [comment]
It is not you, it is a bug in october update.
Windows authentication doesn't work with docker.
If you need to run it now, you will have to download navcontainerhelper source and change it from Windows auth to NavUserPassword.
We are working on a fix.
I haven't tested, but it might work if you are using https

**Comment by waldo1001** [comment]
Aight - forking it is ;-)

**Comment by waldo1001** [comment]
It works as you suggested.
I created a new parameter in order to be able to do it with the function.  
See pull request: https://github.com/Microsoft/navcontainerhelper/pull/4
