### ISSUE TITLE
Create-SaasUrl not recognized

### ISSUE THREAD

**Issue by JeremiasBr** [microsoft/navcontainerhelper#3007]
**Description**
When calling function Get-BcEnvironments, the script runs into an error that "the term 'Create-SaasUrl' is not recognized as a name of a cmdlet...".
Tried other commands (e.g. "New-BcEnvironent"), all of them seem to call 'Create-SaaSUrl' and exit with the same error.

Tried with Version 4.0.16, 4.0.17-preview979 aswell as the current master branch (25.04.22 9.00 am CEST)
Host is Microsoft Windows 11 Enterprise - 22H2

**Scripts used and cause the issue**
```
Saas\Get-BcEnvironments.ps1
Saas\New-BcEnvironment.ps1
```

**Full output of scripts**
```
PS C:\temp $bcAuthContext = New-BcAuthContext -includeDeviceLogin
Attempting authentication to https://api.businesscentral.dynamics.com/user_impersonation offline_access using device login...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code **** to authenticate.
Waiting for authentication...
Authenticated from ***.***.***.*** as user ***, *** (***@***.de)
Authenticated to common, using tenant id *****
PS C:\temp Get-BcEnvironments -bcAuthContext $bcAuthContext
Get-BcEnvironments Telemetry Correlation Id: *****
Create-SaasUrl: C:\Users\[...]\PowerShell\Modules\BcContainerHelper\4.0.17\Saas\Get-BcEnvironments.ps1:33:50
Line |
  33 |  …       $bcAuthContext, $headers, $endPointURL = Create-SaasUrl -bcAuth …
     |                                                   ~~~~~~~~~~~~~~
     | The term 'Create-SaasUrl' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included,
     | verify that the path is correct and try again.
```

**Additional context**
- does it happen all the time? yes
- did it use to work? yes, last tested roughly around end of march this year

**Comment by freddydk** [comment]
The SaasHelperFunctions.ps1 wasn't included when importing BcContainerHelper

**Comment by freddydk** [comment]
That function is new in 4.0.17 preview though - so you wouldn't have gotten **this** error in 4.0.16

**Comment by JeremiasBr** [comment]
Indeed, in version 4.0.16 it works.
I must have made a mistake during the import...

**Comment by freddydk** [comment]
It's fixed in master now and in latest preview
