### ISSUE TITLE
New-BcCompilerFolder requires 7Zip

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#3014]
... else it can not handle the extract of the vsix file:
![image](https://user-images.githubusercontent.com/23500845/234887691-f5003298-9186-4bb3-9651-66c3084bd53f.png)

I understand it is mainly used in your pipelines, but I was curios to see what it does and how it works...
(It is not important for me, but I thought you might want to know this)

**Comment by KristofKlein** [comment]
fantastic solution :D 

"You are a zip!"
"No. I am not!"
*sigh* "rename"
"Oh look I am a zip!"

**Comment by freddydk** [comment]
CompilerFolder is shipped in 5.0.0 and is tested out on BaseApp (version 22), System App, all W1 1st party apps and a number of my own apps.
By setting "useCompilerFolder": true, AL-Go uses compilerFolder for building, but it will not speed things up, as it still needs a container for publishing and testing.
This will be seperated soon.
