### ISSUE TITLE
Remove-NavContainer fails "Access to path 'fisql.exe' is denied"

### ISSUE THREAD

**Issue by eclipses24** [Microsoft/navcontainerhelper#303]
Hi, 

I've create a new nav container with the followin script:

$mylicense = "C:\Users\scastelluccio\Desktop\NAV 2018.flf"
$imageName = "microsoft/dynamics-nav:2018-cu2-w1"
$containerName = "NAV2018CU2W1"

New-NavContainer -accept_eula `
                 -containerName $containerName `
                 -imageName $imageName `
                 -auth Windows `
                 -licensefile $mylicense `
                 -updateHosts `
                 -includeCSide `

Everything works well but when I try to remove it using this script
Remove-NavContainer NAV2018CU2W1

It fails with the following error:
Remove-Item : Cannot remove item C:\ProgramData\NavContainerHelper\Extensions\NAV2018CU2W1\Program Files\110\RoleTailored Client\finsql.exe: Access to the 
path 'finsql.exe' is denied.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.4.3.0\ContainerHandling\Remove-NavContainer.ps1:39 char:13
+             Remove-Item -Path $containerFolder -Force -Recurse
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (finsql.exe:FileInfo) [Remove-Item], UnauthorizedAccessException
    + FullyQualifiedErrorId : RemoveFileSystemItemUnAuthorizedAccess,Microsoft.PowerShell.Commands.RemoveItemCommand

Kind Regards
  Sergio Castelluccio

**Comment by freddydk** [comment]
This is likely because you had finsql.exe running while trying to remove the container.
Shut down finsql and try again.

**Comment by eclipses24** [comment]
Great thanks, it works
