### ISSUE TITLE
pull access denied for bc196, repository does not exist or may require 'docker login'

### ISSUE THREAD

**Issue by rvveldhuyzen** [microsoft/navcontainerhelper#3032]
I am trying to create a BC19.6 container but I run into an access denied error.

DockerDo : Error response from daemon: pull access denied for bc196, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

- Modified an existing script by only changing the BC version numbers. 
- Used the same script to pull a BC21.5 image and that worked fine.
- Containerhelper version 4.0.16. 
- No pending windows updates.

Issue looks like:
[#1055](https://github.com/microsoft/navcontainerhelper/issues/1055)
[#1158](https://github.com/microsoft/navcontainerhelper/issues/1158)
[#2353](https://github.com/microsoft/navcontainerhelper/issues/2353)
But I could not find the answer there. 

**Scripts used to create container and cause the issue**
```
$artifactUrl = Get-BCArtifactUrl -version 19.6 -country w1
Measure-Command { 
    New-BcContainer `
        -accept_eula `
        -containerName bc196 `
        -artifactUrl $artifactUrl `
        -Credential $credential `
        -licenseFile $licenseFile `
        -multitenant `
        -auth UserPassword `
        -updateHosts `
        -includeAL `
        -runSandboxAsOnPrem `
        -imagename bc196
        }
```
also tried a trimmed version:
```
$artifactUrl = Get-BCArtifactUrl -version 19.6 -country w1
Measure-Command { 
    New-BcContainer `
        -accept_eula `
        -containerName bc196 `
        -artifactUrl $artifactUrl `
        -credential $credential `
        -licenseFile $licenseFile `
        -auth UserPassword `
        -updateHosts `
        -imagename bc196
        }
```
**Full output of scripts**
```
$artifactUrl = Get-BCArtifactUrl -version 19.6 -country w1
Measure-Command { 
    New-BcContainer `
        -accept_eula `
        -containerName bc196 `
        -artifactUrl $artifactUrl `
        -Credential $credential `
        -licenseFile $licenseFile `
        -auth UserPassword `
        -updateHosts `
        -imagename bc196
        }

BcContainerHelper is version 4.0.16
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows Server 2019 Standard - 10.0.17763.4252
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
Pulling image bc196:latest
New-BcContainer Telemetry Correlation Id: ae44ad4c-64d4-461f-ada4-49c27612193b
DockerDo : Error response from daemon: pull access denied for bc196, repository does not exist or may require 'docker login': denied: requested access to the 
resource is denied
ExitCode: 1
Commandline: docker pull  bc196:latest
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\4.0.16\ContainerHandling\New-NavContainer.ps1:782 char:13
+             DockerDo -command pull -imageName $bestImageName | Out-Nu ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
 

PS C:\Users\Administrator> 
```

**Additional context**
- does it happen all the time?: Yep
- did it use to work?: Never pulled this image before

**Comment by freddydk** [comment]
The reason for this is the $artifactUrl is empty.
Then it tries to pull (download) the image.

This line:
$artifactUrl = Get-BCArtifactUrl -version 19.6 -country w1

Will try to get sandbox artifacts for 19.6, which doesn't exist.
If you want on-premises artifacts - add -type onprem to that line.

**Comment by rvveldhuyzen** [comment]
I have added the -type onprem and it is working like a charm! Somewhere I missed it that this parameter must be added.

Thanks alot for your help Freddy!
