### ISSUE TITLE
BC22 build gets huge number of erros and will not run

### ISSUE THREAD

**Issue by dmachanick** [microsoft/navcontainerhelper#3037]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I run the New-BCContainer (after getting current version).
It states it ran successflly..
When I try to run it either gives an error or this message:
A tenant was not specified, but is needed because the system has multiple tenants. Contact your system administrator.
When I look at the event log, it has a huge number of errors plus this message on every table:
Message No metadata has been found for application object with Table 37029300 and emit version 22005 in appgroup with id 0.

**Scripts used to create container and cause the issue**
```
New-BCContainer @parameters `
                -accept_eula `
                -containerName $ContainerName `
                -artifactUrl $artifactURL `
                -auth NAVUserPassword `
                -Credential $credential `
                -updateHosts `
                -assignPremiumPlan `
                -shortcuts StartMenu `
                -licenseFile $ContainerLicFile `
                -EnableTaskSchedule:$false `
                -memoryLimit 8G `
                -includeAL `
                -alwaysPull `
                -isolation hyperv 


Publish-BCContainerApp `
    -containerName $ContainerName `
    -appFile $appFile `
    -skipVerification `
    -sync `
    -install
```

**Full output of scripts**
```
NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 11 Enterprise - 22H2
Docker Client Version is 20.10.12

...
```

**Screenshots**

**Additional context**
- all the time with BC22
- worked with previous versions

**Comment by freddydk** [comment]
> A tenant was not specified, but is needed because the system has multiple tenants. Contact your system administrator.

You get this when you are missing ?tenant=default on the URL.
Without that - nothing works.

Let me know whether this is the problem

**Comment by dmachanick** [comment]
Thanks Freddy - that was it

**Comment by freddydk** [comment]
That was btw also a requirement in earlier versions when running multitenancy (which is the default)
