### ISSUE TITLE
BC V.22 container with AAD authentication

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#3041]
I am trying to setup an Azure Test VM using AAD and a v.22 container. 

But the container keps going into an unhealthy state. The setup/scripts worked fine with our old version 14 containers.
The event log of the container is full with "System.InvalidOperationException: AadApplicationId cannot be null or empty" errors.

Checking the https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/authenticating-users-with-azure-ad-openid-connect?tabs=multitenant%2Cadmintool page, it says that in v22 we must use "ADOpenIdMetadataLocation" instead of "ClientServicesFederationMetadataLocation" that had to be used in version older then v22.

I have checked nav-docker and it seems that ADOpenIdMetadataLocation is set, but shouldn't it also set ValidAudiences?

**Comment by freddydk** [comment]
My script for testing containers with AAD auth can be found as a response here:
https://github.com/microsoft/navcontainerhelper/issues/2990

**Comment by epernst** [comment]
Thanks, does this script have a guide how to run it?

**Comment by freddydk** [comment]
You need to replace my secrets with yours - there are 4 of those
```
$containerName = "bcserver"
$licenseFile = $LicenseFileUrlSecret.SecretValue | Get-PlainText
$credential = New-Object pscredential -ArgumentList 'admin', $PasswordSecret.SecretValue
$artifactUrl = Get-BCArtifactUrl -country us -type OnPrem
$aadCredential = New-Object pscredential -ArgumentList ($AadUserNameSecret.SecretValue | Get-PlainText), $AadPasswordSecret.SecretValue
```

**Comment by epernst** [comment]
Thanks. That part I did (eventually) figure out.

But how do I specify which Azure Subscription / Resource Group to use?
As a user-admin in our organization I need to specify the subscription where I'm allowed to do stuff like this. :)
Right now it's trying to do it somewhere where I cannot do stuff.

**Comment by freddydk** [comment]
Sorry, but as stated, that script is just my test script, and I provided that as such (not as a command or like).
You can also use https://aka.ms/getbc to get an Azure VM with AAD setup - I am doing some fixes to this (currently in https://aka.ms/getbc2), but if you want to extract the code and use it yourself - it is probably easier to look at and understand my test script.

You don't have to create the AAD apps in code - you can also create them manually - it was more for stating that using these parameters, New-BcContainer will create a container with 22, running AAD authentication that works.
The script does a lot more than that as well.

**Comment by freddydk** [comment]
https://aka.ms/getbc is now updated with all - and works with AAD and 22.

If your office account requires multi-factor authentication, the log (http://hostnameofvm/Status.aspx) of the VM will display a device code with which you need to login to your AAD account of your BC tenant in which the AAD Apps will be created.

**Comment by epernst** [comment]
Hi Freddy,
I hi-jacked one of our admins, and were able to run the script. It did fail on one of the later tasks, but it allowed me to log in.
Now I just need to figure out how to apply this to our VM image bake and build processes.

**Comment by freddydk** [comment]
You can easily reuse the same AAD Apps for all your VMs - you just need to have all Reply-To addresses inserted there (I think)
Then you don't need to create any AAD Apps - but just setup BC to use the existing ones and have all the clientIDs and secrets in a keyvault.
