### ISSUE TITLE
#Requires -PSEdition Desktop

### ISSUE THREAD

**Issue by jhoek** [Microsoft/navcontainerhelper#305]
Under the assumption that navcontainerhelper is not 100% PowerShell Core-compatible (or am I doing something wrong? The `New-PSSession` call in `Get-NAVContainerSessions` keeps throwing a null-reference exception), you may want to explicitly communicate that fact by adding `#Requires -PSEdition Desktop` to your psm1.

**Comment by freddydk** [comment]
Shipped in 0.4.3.1
