### ISSUE TITLE
Docker error "WARNING: Ignoring custom format, because both --format and --quiet are set."

### ISSUE THREAD

**Issue by ernestasjuska** [microsoft/navcontainerhelper#3054]
Hi,

New `docker ps` does not allow to specify both `--format` and `--quiet` parameters.

The problem is in this line:
https://github.com/microsoft/navcontainerhelper/blob/7d83310ef4de82fff94745b6206e462a34cac6c5/ContainerInfo/Test-NavContainer.ps1#LL29C15-L29C71

`--quiet` is not needed here anyway. From `docker ps` documentation (https://docs.docker.com/engine/reference/commandline/ps/):
![image](https://github.com/microsoft/navcontainerhelper/assets/53167314/aa30c84f-d237-477b-bbf8-4e43599dba9b)

Thanks:

```powershell
PS C:\Windows\system32> New-BcContainer -accept_eula -containerName bcserver -artifactUrl (Get-BCArtifactUrl -type OnPrem -country w1)
BcContainerHelper is version 5.0.2
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Enterprise - 10.0.22621.1702
Docker Client Version is 24.0.0
Docker Server Version is 24.0.0
New-BcContainer Telemetry Correlation Id: bc25b11a-78b0-4ea8-bc1b-ced3c2c89e91
docker : WARNING: Ignoring custom format, because both --format and --quiet are set.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.2\ContainerInfo\Test-NavContainer.ps1:29 char:15
+ ...       $id = docker ps $a -q --no-trunc --format "{{.ID}}/{{.Names}}"  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Ignori...-quiet are set.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by freddydk** [comment]
Installing 24.0.0

**Comment by freddydk** [comment]
Shipped in 5.0.3

**Comment by Matiusauce** [comment]
How do we gain access to this newer version/when will it be released? Do not see it in releases yet. Trying to move to a docker container for dev and currently receiving this error. BCContainerHelper is v4.0.7 so likely stuck till I can update.

**Comment by freddydk** [comment]
In PowerShell run::
```
Update-Module BcContainerHelper -force
```
and Restart Powershell  should do it.

Else, in PowerShell run:
```
Remove-Module BcContainerHelper
UnInstall-Module BcContainerHelper -allversions
```
Then restart PowerShell and run:
```
Install-Module BcContainerHelper -force
```

Should get rid of all prior installed versions and install the latest.

**Comment by 4ampro** [comment]
> In PowerShell run::
> Update-Module BcContainerHelper -force
> and Restart Powershell should do it.

Worked like a champ.
