### ISSUE TITLE
Remove-BcEnvironment status is null

### ISSUE THREAD

**Issue by JulianSchmidtkeGWS** [microsoft/navcontainerhelper#3061]
**Describe the issue**
When using Remove-BcEnvironment we get this output

```
The property 'status' cannot be found on this object. Verify that the property exists.
```

**Scripts used to create container and cause the issue**
```
Remove-BcEnvironment -bcAuthContext $authContext -environment $Environment
```

**Full output of scripts**
```
Submitting environment removal request for BusinessCentral/SandboxNextVersion
Environment removal request submitted
Removing..Remove-BcEnvironment Telemetry Correlation Id: 14fb5bfe-86ed-4dfc-a72a-7be475aec837
##[error]The property 'status' cannot be found on this object. Verify that the property exists.
...
```

**Additional context**
I think this line does not have a status at some point
https://github.com/microsoft/navcontainerhelper/blob/f5c4cd7165a69e60e2e9e00d0fdafaeb65a976ce/Saas/Remove-BcEnvironment.ps1#L63

**Comment by freddydk** [comment]
Could you share the full output of the job, either here or in an email to freddyk at microsoft dot com?

**Comment by JulianSchmidtkeGWS** [comment]
Hi Freddy,
sent you an email with detailed output.

**Comment by freddydk** [comment]
The new implementation of DELETE (softDelete) apparently breaks callers using the old API Version.
You can fix this (until the next version) by adding -apiVersion '2.18' or -doNotWait to the Remove-BcEnvironment call.
I will change the default apiVersion in ContainerHelper

**Comment by JulianSchmidtkeGWS** [comment]
Hi Freddy,
thank you!
You had a small typo in your comment - we need to set apiVersion to "v2.18" instead of "2.18".

Remove-BcEnvironment -bcAuthContext $authcontext -Environment <EnvName> -apiVersion 'v2.18' 
worked. Thanks!
