### ISSUE TITLE
Differing update window dates between Get-BcEnvironmentUpdateWindow and BC Admin Center

### ISSUE THREAD

**Issue by BW-PA** [microsoft/navcontainerhelper#3063]
**Describe the issue**
I'll preface this issue by saying I suspect this isn't bccontainer helper in the end.  Appears to be more likely the API bccontainerhelper is calling.  Wanted to raise it here just in case others come looking.  

Using Get-BcEnvironmentUpdateWindow gives different dates for the Update window than is reported by BC Admin Center UI

Reported date given by:
 - Get-BcEnvironmentUpdateWindow = 2023-05-22
 - BC Admin Center = 2023-06-06

The time appears to be correctly reported for both (18:00hrs)

**Scripts used to create container and cause the issue**
```
#Auth Context and Environment set prior to calling below
Get-BcEnvironmentUpdateWindow -bcAuthContext $authContext -environment $environment
```

**Full output of scripts**
![image](https://github.com/microsoft/navcontainerhelper/assets/78051738/ca1ea795-a105-4ae5-b374-19cf5f80d85b)

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/78051738/2345dafa-4c64-4710-82a3-e86645af6801)
![image](https://github.com/microsoft/navcontainerhelper/assets/78051738/027b84c7-732c-400e-8c3d-4a553a0f48a5)

**Additional context**
- does it happen all the time? Yes
- did it use to work? Not sure, this is the first time I've attempted to use the function 

AEST is 10hrs ahead of UTC.  Yet the difference in the date returned by Get-BcEnvironmentUpdateWindow is approximately 14days. I suspect this is more an issue with the API and not the module itself.  I wonder too if it's caused because I don't actually have a currently scheduled date set.  But in that case I would expect it to still return the same date that is shown by BC Admin Center.

**Comment by freddydk** [comment]
Well, the update Window is:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/439905c9-59b9-41db-abe8-1a144aac3634)
Which is what this function returns.

For a specific upgrade, I assume that Get-BcScheduledUpgrade can be used.

**Comment by BW-PA** [comment]
Thanks Freddy, I had confused Get-BcEnvironmentUpdateWindow with Get-BcScheduledUpgrade.  The latter does report the information I was looking for.  I understand now that Get-BcEnvironmentUpdateWindow returns the window of time in which the scheduled upgrade will occur within.
