### ISSUE TITLE
Question: Is it possible to setup traefik on a port other than 80/443?

### ISSUE THREAD

**Issue by BW-PA** [microsoft/navcontainerhelper#3073]
**Background:**
The machine I want to run traefik on already has a default website.  I initially tried the overrideDefaultBinding parameter which worked well after adjusting my urls to specify port 8180 instead.  So far so good,  _until_ users complained that they could no longer access the default website.  The users with the issue were connecting to the website via a VPN and 8180 is blocked on the firewall.

**Question:**
Is it possible to leave the default website as is and have traefik listening on another user specified port?  I see port 80 and 443 are hardcoded in the scripts.

Just wanted to ask before going down the path of resolving issues with the default website being on port 80.  The overrideDefaultBinding parameter doesn't immediately work because it is hardcoded to 8180 which is not in an open VPN port range.   I can potentially move this default website to a port within an open range for our VPN, but having traefik on another port would be the easier option (assuming it's possible).

**Comment by freddydk** [comment]
Sorry, but I don't know whether this is possible.
Not sure whether @tfenster every tried this or knows whether it is possible?

**Comment by tfenster** [comment]
I think it should be possible from the Traefik side, but the cmdlets and scripts in bccontainerhelper certainly weren't created with that in mind

**Comment by BW-PA** [comment]
Thanks both, I suspected as much after reviewing the cmdlets and scripts for bccontainerhelper.  I'll keep investigating via manually configuring traefik versus using bccontainerhelper to set it up.
