### ISSUE TITLE
Separate ZUP for finsql

### ISSUE THREAD

**Issue by kylehardin6** [Microsoft/navcontainerhelper#308]
Since finsql.exe runs as a normal process on the docker host, please change the command line for that desktop icon:

"C:\ProgramData\NavContainerHelper\Extensions\CKS\Program Files\110\RoleTailored Client\finsql.exe" servername=$containerName\SQLEXPRESS, Database=Cronusna

"C:\ProgramData\NavContainerHelper\Extensions\CKS\Program Files\110\RoleTailored Client\finsql.exe" servername=$containerName\SQLEXPRESS, Database=Cronusna, ID=$containerName

This way, if there is more than one NAV docker container, the Dev clients won't share the same ZUP file.

**Comment by freddydk** [comment]
I didn't know about the ID parameter. Excellent idea.

**Comment by freddydk** [comment]
Shipped in 0.4.3.1
