### ISSUE TITLE
Download-Artifacts doesn't terminate

### ISSUE THREAD

**Issue by lktraser** [microsoft/navcontainerhelper#3085]
**Describe the issue**
Since some time today Download-Artifacts stopped terminating and just runs endlessly. I get a short spike in network traffic and then nothing happens anymore. This issue might exist for a few days already because our build server has most of the version we need daily cached.

**Scripts used to create container and cause the issue**
```
Download-Artifacts -artifactUrl (Get-BCArtifactUrl -type OnPrem -country w1 -version 22.0)
```

**Full output of scripts**
```
BcContainerHelper version 5.0.3
Setting sandboxContainersAreMultitenantByDefault = False
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Downloading artifact /onprem/22.0.54157.55195/w1
Downloading C:\Users\lkn\AppData\Local\Temp\beadab07-1730-4c7f-815f-d2c7a58e4c59.zip
Downloading using WebClient
```

**Additional context**
- does it happen all the time? It seems to be all types/versions/countries
- did it use to work? Yes

**Comment by lktraser** [comment]
Thanks for the idea! I didn't think it was a network issue due to my build server and my local machine having the same problem.
Yes I can download from the URL but at speed of sub 100kbs (on a 500mbs connection). What's going on? I'm on a seperate network from my build server but the speeds are just in the dumpster then.

**Comment by lktraser** [comment]
Speeds sometimes spike into the mb/s for a short span and then slow down to a crawl again
![image](https://github.com/microsoft/navcontainerhelper/assets/76940360/dfd270d6-b9b5-40ff-a959-c7a287c13112)

**Comment by lktraser** [comment]
Speeds seem to have recovered now. I'll keep an eye on it tomorrow if I can't detect anymore problems I'll close this issue

**Comment by pri-kise** [comment]
We had similiar problems on all of our build agents yesterday for mostly the whole day.

**Comment by freddydk** [comment]
Thanks for the info @pri-kise - not sure from where this problem stems, but it isn't anything I can do much about in ContainerHelper.

**Comment by lktraser** [comment]
> Thanks for the info @pri-kise - not sure from where this problem stems, but it isn't anything I can do much about in ContainerHelper.

true but who can we go to? Who's in charge of reliability of the artifacts? Luckily yesterday it was not critical for us but it would be a shame if it is some day.

**Comment by freddydk** [comment]
Well, if there is anything wrong with the artifacts, you are in the right spot.

What you observed yesterday can be caused by Azure Storage account degraded performance, CDN degraded performance, your ISP degraded performance and probably many other things.
If (some day) there is an Azure Outage and you cannot get to the artifacts, there probably isn't much I can do either,

I will just mark this as unrelated if I cannot do anything about the problem in ContainerHelper.
That obviously doesn't mean that there isn't a problem, it just means that it isn't a problem in ContainerHelper.

**Comment by pri-kise** [comment]
Is there anything we can do in the future to find out what is the cause of the degraded performance?

It might be that the problem yesterday is caused by problems with the ISP, since I had some network outages locally, although our agents are on another network ...

**Comment by freddydk** [comment]
I don't think this is any different from any other download issue.
You can try on another machine in another network or create an issue here and I (or somebody else) will try:-)
