### ISSUE TITLE
NavSip.dll missing in SysWOW64 / Not able so sign App with SignTool.exe

### ISSUE THREAD

**Issue by DeFynancy** [microsoft/navcontainerhelper#3089]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

Hi,
I was trying to copy the NavSip.dll to the local machine with ""Install-NAVSipCryptoProviderFromBcContainer"" and get the error: 

`PS C:\Windows\system32> Install-NAVSipCryptoProviderFromBcContainer bcserver
Copy SIP crypto provider from container bcserver
Copy from container bcserver (C:\Windows\System32\NavSip.dll) to C:\Windows\System32\NavSip.dll
Copy from container bcserver (C:\Windows\SysWow64\NavSip.dll) to C:\Windows\SysWow64\NavSip.dll
Cannot find path 'C:\Windows\SysWow64\NavSip.dll' because it does not exist.

Exception Script Stack Trace:
bei Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.3\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Zeile 61
bei Copy-FileFromBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.3\Misc\Copy-FileFromNavContainer.ps1: Zeile 39
bei Install-NAVSipCryptoProviderFromBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.3\AppHandling\Install-NAVSipCryptoProviderFromNavContainer.ps1: Zeile 44
bei <ScriptBlock>, <Keine Datei>: Zeile 1

PowerShell Call Stack:
bei Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.3\ContainerHandling\Invoke-ScriptInNavContainer.ps1: Zeile 71
bei Copy-FileFromBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.3\Misc\Copy-FileFromNavContainer.ps1: Zeile 39
bei Install-NAVSipCryptoProviderFromBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.3\AppHandling\Install-NAVSipCryptoProviderFromNavContainer.ps1: Zeile 44
bei <ScriptBlock>, <Keine Datei>: Zeile 1

Container Free Physical Memory: 5.6Gb

Services in container bcserver:

- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running

C:\Windows\SysWow64\NavSip.dll doesn't exist.
C:\Windows\System32\NavSip.dll successfully registered.`

I originally tried so sign my BC App with the documentation from ssl.com: (can't sign the BC App with Powershell, since I the new certificate reglemantations don't let you export the private key and create a .pfx)

https://www.ssl.com/how-to/automate-ev-code-signing-with-signtool-or-certutil-esigner/

`“C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x86\signtool.exe” sign /fd sha256 /tr http://ts.ssl.com /td sha256 /sha1 XXXXXXX "C:\Users\Dell\Documents\Code\TEST\Default publisher_TEST_1.0.0.0.app"`

I get the following error: 

<img width="673" alt="image3" src="https://github.com/microsoft/navcontainerhelper/assets/117264403/71b083ae-0271-4487-9f44-ae8dc5c47d35">

Any ideas how I can proceed? Right now I don't know how to sign AppFiles. 

Thanks to anybode for help!

**Comment by freddydk** [comment]
Thanks
This is a regression caused by a change in the Copy-File function.
a Fix should be ready in pre-release in 1-2 hours.

**Comment by DeFynancy** [comment]
Hi Freddy, 
thank you for the the fix in the newest prerelease. Running the "NASip" Command works fine now. 

However my App File is still not being recognized by the Signtool.exe. I know this is slightly of topic, but do you have any idea what the issue could be? 
I am still locking for a way so sign app files without using a .pfx (and hence the container helper command to sign). 

Thank you!

**Comment by freddydk** [comment]
Shipped in 5.0.4

**Comment by datachef-david** [comment]
> Hi Freddy, thank you for the the fix in the newest prerelease. Running the "NASip" Command works fine now.
> 
> However my App File is still not being recognized by the Signtool.exe. I know this is slightly of topic, but do you have any idea what the issue could be? I am still locking for a way so sign app files without using a .pfx (and hence the container helper command to sign).
> 
> Thank you!

Same issue here after updating to 5.0.5.  

Install-NAVSipCryptoProviderFromBcContainer sandbox1

Remove existing C:\Windows\System32\NavSip.dll
Copy SIP crypto provider from container sandbox1
Copy from container sandbox13 (C:\Windows\System32\NavSip.dll) to C:\Windows\System32\NavSip.dll
Copy from container sandbox13 (C:\Windows\SysWow64\NavSip.dll) to C:\Windows\SysWow64\NavSip.dll
C:\Windows\SysWow64\NavSip.dll doesn't exist.
C:\Windows\System32\NavSip.dll successfully registered.

Then executing signtool.exe

SignTool Error: This file format cannot be signed because it is not recognized.
SignTool Error: An error occurred while attempting to sign:

**Comment by erikrijn** [comment]
What is the status of this issue?
I also haven't been able to use this command for a long time because of this.
