### ISSUE TITLE
AL0132 'Report Check' does not contain a definition for 'InitTextVariable'

### ISSUE THREAD

**Issue by HLBCdev1** [microsoft/navcontainerhelper#3096]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
A clear and concise description of what the issue is.

**Scripts used to create container and cause the issue**
```
New-BcContainer `
    -accept_eula `
    -imagename...
```

**Full output of scripts**
```
NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by HLBCdev1** [comment]
Error: AL0132 'Report Check' does not contain a definition for 'InitTextVariable'
  Error: AL0132 'Report Check' does not contain a definition for 'FormatNoText'
  Error: AL0132 'Report Check' does not contain a definition for 'FormatNoText'
  
  Compilation ended at '15:55:44.666'.
  
  App generation failed with exit code 1

**Comment by freddydk** [comment]
There are a million ways how an error occurs
If I am going to look at something, I will need a lot of information about how the error happened, not just the error.

**Comment by HLBCdev1** [comment]
I'm sorry for that please.

I was trying to do conversion of Amount in figures to Words using the standard report - 1401 'Check' with the procedures InitTextVariable() and FormatNoText(). If I publish directly to my Sandbox from VS Code it works fine but each time I push to GitHub it throws that error. 

Thanks Sir.

**Comment by HLBCdev1** [comment]
> There are a million ways how an error occurs If I am going to look at something, I will need a lot of information about how the error happened, not just the error.
I'm still expecting a feed back from you on my issue. Thanks

**Comment by freddydk** [comment]
Please provide a full script and a full output of a repro scenario.
Based on the above, I could spend many hours trying to reproduce this without succeeding.

**Comment by HLBCdev1** [comment]
> You might need to provide me with the report as well as the script.

Hi, here is a the code segment:

trigger OnAfterGetRecord()
            var
                RepCheck: Report Check;
                Amt: Decimal;
                NoText: array[2] of Text[80];
                NoText2: array[2] of Text[80];
                DeciNum: List of [Text];
                Fract: List of [Text];
                Kobo: Decimal;
                currencyNaira: Code[10];
                currencyKobo: Code[10];
            begin
                Amt := Round(Netpay, 0.01);
                currencyNaira := 'NGN';
                currencyKobo := 'KOBO';
                RepCheck.InitTextVariable();
                RepCheck.FormatNoText(NoText, Amt, currencyNaira);
                DeciNum := NoText[1].Split(' AND ');
                Evaluate(Kobo, (DeciNum.Get(2).Split('/').Get(1)));
                RepCheck.FormatNoText(NoText2, Kobo, currencyKobo);
                Fract := NoText2[1].Split(' AND ');
                AmountInWords := DeciNum.Get(1) + ' NAIRA AND ' + Fract.Get(1).Split('****').Get(2) + ' KOBO Only';
            end;

Please note that the above code is used in a report object (Netpay is a decimal value coming from a table) and below is the error I got when I pushed to GitHub:

<img width="929" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/126694148/18834070-05d7-4c01-a498-0f3e669c127a">

**Comment by HLBCdev1** [comment]
> > You might need to provide me with the report as well as the script.
> 
> Hi, here is a the code segment:
> 
> codeunit 50103 MyCodeunit { procedure convertAmtToWord(toConvert: Decimal): Text var RepCheck: Report Check; Amt: Decimal; NoText: array[2] of Text[80]; NoText2: array[2] of Text[80]; DeciNum: List of [Text]; Fract: List of [Text]; Kobo: Decimal; currencyNaira: Code[10]; currencyKobo: Code[10]; AmountInWords: Text; begin
> 
> ```
>     Amt := Round(toConvert, 0.01);
>     currencyNaira := 'NGN';
>     currencyKobo := 'KOBO';
>     RepCheck.InitTextVariable();
>     RepCheck.FormatNoText(NoText, Amt, currencyNaira);
>     DeciNum := NoText[1].Split(' AND ');
>     Evaluate(Kobo, (DeciNum.Get(2).Split('/').Get(1)));
>     RepCheck.FormatNoText(NoText2, Kobo, currencyKobo);
>     Fract := NoText2[1].Split(' AND ');
>     AmountInWords := DeciNum.Get(1) + ' NAIRA AND ' + Fract.Get(1).Split('****').Get(2) + ' KOBO Only';
>     Message(AmountInWords);
>     exit(AmountInWords);
> 
> end;
> ```
> 
> } Please note that the above code is used in a report object (Netpay is a decimal value coming from a table) and below is the error I got when I pushed to GitHub:
> 
> <img alt="image" width="957" src="https://user-images.githubusercontent.com/126694148/252647969-a1cf2ca0-4bd2-47c0-b03e-c1f09e2cef19.png">

@freddydk

**Comment by freddydk** [comment]
Sorry, I wasn't clear - I need all the files needed to build the app, basically all files and scripts needed in order for this to fail on my machine (without me having to spend multiple hours generating the same).
If you are not comfortable with uploading files here, you can send them to freddyk at microsoft dot com, but I need everything needed to do a repro.
