### ISSUE TITLE
 Error response from daemon: No such container

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/navcontainerhelper#31]
Hi Freddy,

I am trying to prepare some script using the navcontainerhelper. When I try to run this

```
$NAV_DOCKER_IMAGE = "microsoft/dynamics-nav:devpreview-finus"
$containername = "devpre112017con"
$LicenseFile = 'SOMEPATHTOSOMELICENSE'


New-NavContainer `
    -accept_eula `
    -containerName $containername `
    -imageName $NAV_DOCKER_IMAGE `
    -Credential (get-credential -credential $env:USERNAME) `
    -auth Windows `
    -memoryLimit 3G `
    -shortcuts Desktop `
    -alwaysPull `
    -includeCSide `
    -Verbose `
    -licenseFile $LicenseFile`
```

I get this error output:

```
Pulling docker Image microsoft/dynamics-nav:devpreview-finus
devpreview-finus: Pulling from microsoft/dynamics-nav
Digest: sha256:80373eeb38ac2ec347daa1a50cc32a67c7cb77d2f082bd88f3b331054653c1c8
Status: Image is up to date for microsoft/dynamics-nav:devpreview-finus
Creating Nav container devpre112017con
Using image microsoft/dynamics-nav:devpreview-finus
Using license file 'SOMEPATHTOSOMELICENSE'
NAV Version: 11.0.19097.0-finus
Generic Tag: 0.0.3.3
Creating container devpre112017con from image microsoft/dynamics-nav:devpreview-finus
Waiting for container devpre112017con to be ready, this shouldn't take more than a few minutes
Time:          ½              1              ½              2
.docker : Error response from daemon: No such container: devpre112017con
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.1.0\ContainerHandling\Wait-NavContainerReady.ps1:28 
Zeichen:21
+             $logs = docker logs $containerName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...devpre112017con:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

What did I do wrong?

**Comment by Koubek** [comment]
Could you try to shorten the container name (eg: put less than 10 chars)?

**Comment by freddydk** [comment]
Are you running Windows 10?
I tried your exact command under Windows Server 2016 - it works here.
what does
docker ps -a 
return?
Also - try to use a shorter name - not sure whether this is the issue - maybe Windows 10 has different name requirements as Windows Server

**Comment by freddydk** [comment]
You could also just try it again.
It looks like it fails immediately - and maybe the 2 seconds it waits after doing Docker run is not enough - maybe the contianer is not ready for docker logs yet.
I will insert a test-navcontainer before calling docker logs in the wait.

**Comment by RafaelKoch** [comment]
- The Container is not created. `docker container ls -a` -> all empty
- Using a Shorter Name `pre112017` -> same error
- I am running Windows 10. I Can successfully deploy using docker commands directly w/o containerhelper
- `docker ps -a` -> no containers found

All said I think trying a longer wait would be worth a try

**Comment by freddydk** [comment]
Very strange... If the wait was the problem, then the container would be there.
I would like to investigate this - if you have the time, shoot me an email and we can setup a skype for business call?

**Comment by freddydk** [comment]
We just had a troubleshooting session and found out, that the navcontainerhelper doesn't support spaces in usernames - and maybe the nav container also don't.
I will check up on this.

**Comment by freddydk** [comment]
navcontainerhelper 0.2.1.1 is on the PowerShell Gallery and supports spaces in usernames.
The Nav on Docker already did support this (as far as I have tested)

**Comment by RafaelKoch** [comment]
Tried the bugfix today, looking good now
