### ISSUE TITLE
BC14 C/AL Run Codeunit from Designer failes due to protocol mismatch

### ISSUE THREAD

**Issue by bennyvanlyssebettens** [microsoft/navcontainerhelper#3108]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Image: Latest BC14 Release

When running a codeunit directly from the Object Designer the client does not start

---------------------------
Microsoft Dynamics 365 Business Central
---------------------------
Cannot connect to the server because of a protocol mismatch. This can be caused by the client and server having incompatible credential settings (ClientServicesCredentialType). Contact your system administrator.
---------------------------
OK   
---------------------------

**Scripts used to create container and cause the issue**
```
#Base
$baseImage = Get-BestGenericImageName

#Business Central
$version = '14'
$country = 'w1'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -version $version -country $country -select 'Latest'
if ($artifactUrl.StartsWith('https://bcartifacts.azureedge.net')) {
    $tag = $artifactUrl.Substring(41)
    $tag = $tag.Substring(0,($tag.Length - 3))
} else {
    #Alternative url 
}
$imageName = "businesscentral/onprem:$($tag)-$($country)-$(($baseImage.Split(':'))[1])"
#New-BcImage -artifactUrl $artifactUrl -baseImage $baseImage -imageName $imageName

$licenseFile = 'C:\Users\Van Lyssebettens\Documents\Licenses\xxx.flf'
New-BcImage -artifactUrl $artifactUrl -baseImage $baseImage -imageName $imageName

#Container
$containerName = 'bc14w1'
$password = 'xxxx'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
New-BcContainer -accept_eula -accept_outdated -containerName $containerName -imageName $imageName -Credential $credential -auth $auth `
    -dns '8.8.8.8' -useSSL -installCertificateOnHost -updateHosts -licenseFile $licenseFile -includeCSide -doNotExportObjectsToText
...
```

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/38490754/f0dbbd12-e928-48ac-8b63-b539f1383fda)

**Starting the Windows Client itself Works**
This is the weird part... I can run the Windows Client

![image](https://github.com/microsoft/navcontainerhelper/assets/38490754/c9bc26d1-f6fa-4a4e-9f3e-2a7bc079722f)

And after entering the user name & password, I'm in

**Comment by freddydk** [comment]
I haven't looked at C/AL for many years and won't have time to dig into this.
If anybody else is using C/AL and knows what is going wrong here, feel free to chime in?

**Comment by bennyvanlyssebettens** [comment]
I know where it goes wrong. The issue is that on the moment you run a codeunit from the old C/AL designer, it fires up the RTC client. This session uses the ClientUserSettings.config to determine if it's Windows or NAVPassword. (Normal behaviour) It's not the one in "C:\ProgramData\BcContainerHelper\Extensions\bc14w1\Program Files\140\RoleTailored Client" like when you start the RTC on a normal way, with the icon on the desktop. Really no clue if somebody can solve this :)

**Comment by scm6iwa** [comment]
I've come across this issue the way I got round it is first login to the RTC client from your docker shortcuts and then when you run from the object designer it will use the current open RTC client which is connected to your docker BC.
