### ISSUE TITLE
Run-ALValidation failing [error at pulling generic image]

### ISSUE THREAD

**Issue by faranmahboob** [microsoft/navcontainerhelper#3118]
Hi, i am having issue while running **Run-AlValidation** for appSource extension.
I am able to create a new BC container but the Run-AlValidation commands get failed.
Can anyone help or have any idea by looking into the logs ?
thanks

**Command**
$validationResults = Run-AlValidation `
    -apps "D:\AppName.app" `
    -affixes "MDCSM" `
    -countries "dk"

**Error on Event Viewer**    

Handler for GET /v1.43/containers/3cdf23329194278b235c0677b8774638c9e4d290f141a0b19018e463ae2482ca/logs returned error: configured logging driver does not support reading

**Command Log on PowerShell**

```
PS C:\Windows\system32> 
$validationResults = Run-AlValidation `
    -apps "D:\AppName.app" `
    -affixes "MDCSM" `
    -countries "dk"
    -isolation hyperv `

```

```
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
  _____                               _                
 |  __ \                             | |               
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___ 
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Container name                  bcserver
Credential                      admin/Laly2980
MemoryLimit                     8G
validateVersion                 
validateCurrent                 False
validateNextMinor               False
validateNextMajor               False
SasToken                        Not Specified
countries                       dk
validateCountries               dk
affixes                         MDCSM
supportedCountries              
ObsoleteTagMinAllowedMajorMinor 
vsixFile                        
Install Apps
- None
Previous Apps
- None
Apps
- D:\AppName.app
  _____       _                      _                         _   _  __           _       
 |  __ \     | |                    (_)                       | | (_)/ _|         | |      
 | |  | | ___| |_ ___ _ __ _ __ ___  _ _ __   ___    __ _ _ __| |_ _| |_ __ _  ___| |_ ___ 
 | |  | |/ _ \ __/ _ \ '__| '_ ` _ \| | '_ \ / _ \  / _` | '__| __| |  _/ _` |/ __| __/ __|
 | |__| |  __/ |_  __/ |  | | | | | | | | | |  __/ | (_| | |  | |_| | || (_| | (__| |_\__ \
 |_____/ \___|\__\___|_|  |_| |_| |_|_|_| |_|\___|  \__,_|_|   \__|_|_| \__,_|\___|\__|___/
                                                                                           
Found https://bcartifacts.azureedge.net/sandbox/22.3.58346.58652/dk
Using https://bcartifacts.azureedge.net/sandbox/22.3.58346.58652/dk
  _____       _                      _       _                   _                           _                       
 |  __ \     | |                    (_)     (_)                 | |                         | |                      
 | |  | | ___| |_ ___ _ __ _ __ ___  _ _ __  _ _ __   __ _    __| | ___ _ __   ___ _ __   __| | ___ _ __   ___ _   _ 
 | |  | |/ _ \ __/ _ \ '__| '_ ` _ \| | '_ \| | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '_ \ / _` |/ _ \ '_ \ / __| | | |
 | |__| |  __/ |_  __/ |  | | | | | | | | | | | | | | (_| | | (_| |  __/ |_) |  __/ | | | (_| |  __/ | | | (__| |_| |
 |_____/ \___|\__\___|_|  |_| |_| |_|_|_| |_|_|_| |_|\__, |  \__,_|\___| .__/ \___|_| |_|\__,_|\___|_| |_|\___|\__, |
                                                      __/ |            | |                                      __/ |
                                                     |___/             |_|                                     |___/ 
Extracting C:\ProgramData\BcContainerHelper\ab2f26c6-89cc-4b68-b49d-574579839f61\AppName.app
Validating against Current Version (22.3)
Additionally validating against application dependency (17.0)

  _____       _ _ _                                          _        _                            
 |  __ \     | | (_)                                        (_)      (_)                           
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___ 
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |     
                          |___/   |___/                                                 |___/      

Pulling mcr.microsoft.com/businesscentral:10.0.19041.1415-filesonly
Run-AlValidation Telemetry Correlation Id: 46d7e5ac-1d41-4d80-8ba7-505c060ab6a2
docker : 
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1:314 char:39
+     $DockerPull = { Param($imageName) docker pull $imageName }
+                                       ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

PS C:\Windows\system32> 


```

**Comment by DavidHrbek** [comment]
We are suffering from a similar issue during the AL-Go for GitHub localDevEnv.ps1 script running. We suspect the new version of Docker from causing this issue. Could you tell me what version of Docker are you using?

**Comment by DavidHrbek** [comment]
> We are suffering from a similar issue during the AL-Go for GitHub localDevEnv.ps1 script running. We suspect the new version of Docker from causing this issue. Could you tell me what version of Docker you are using?

My colleague tried to downgrade the Docker Desktop on his machine to the version 4.20.0 and it seems it works with this version.

**Comment by freddydk** [comment]
What does docker version return?

```
PS C:\WINDOWS\system32> docker version
Client:
 Version:           24.0.4
 API version:       1.43
 Go version:        go1.20.5
 Git commit:        3713ee1
 Built:             Fri Jul  7 14:52:09 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.4
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.5
  Git commit:       4ffc614
  Built:            Fri Jul  7 14:51:02 2023
  OS/Arch:          windows/amd64
  Experimental:     false

```

**Comment by DavidHrbek** [comment]
In my case is the result of docker version following:
```
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.4
  Git commit:       659604f9
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          windows/amd64
  Experimental:     false
```

On my colleague's computer where everything works it is:
```
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.20.0 (109717)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.4
  Git commit:       659604f9
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Comment by faranmahboob** [comment]
PS C:\Windows\system32> docker version
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.4
  Git commit:       659604f9
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by freddydk** [comment]
and I assume, that on the machines where this fails, this command:

`docker pull mcr.microsoft.com/businesscentral:10.0.19041.1415-filesonly
`
fails?

**Comment by faranmahboob** [comment]
@freddydk  Yes, it fails at that line.
Just for information, I am able to make new container using New-BcContainer.
It can be computer's windows issue ?

**Comment by freddydk** [comment]
What is your Windows Version?
When you create a container, it create a container based on a different image (not the filesonly one).
Please try to reset your docker desktop to factory defaults and see whether you can pull the image then - something might be wrong in the filesystem of your docker.

You can also try the docker cleanup, explained here:
https://freddysblog.com/2018/12/11/clean-up-after-yourself-docker-your-mom-isnt-here/

**Comment by faranmahboob** [comment]
its, version 21H1 (OS Build 19043.1706).
I'll reset my docker desktop and will update here.
thanks

**Comment by faranmahboob** [comment]
Hi again,
I have reset the Docker by using ''Reset To Factory defaults'' option from desktop but still getting the same error.
Normally when I create container using  New-BcContainer, I had to use -isolation hyperv ` parameter.
Do I need to have similar parameter in Run-AlValidation as well ?
In my understanding, we dont need to have container created before running Run-AlValidation, Right?
Run-AlValidation will pull and create container itself.
thanks

**Comment by freddydk** [comment]
You need to use HyperV because there are no Windows Docker Images for your version of Windows.
Upgrading to Windows 11 would probably remove all problems as there are newer versions of the containers for that.
If you have a problem pulling a docker image - it has nothing to do with BcContainerHelper nor Isolation mode (it hasn't come to create the container yet).
The problem is either with your version of Windows and/or Docker Desktop.
If you colleague was able to downgrade and solve the issue, the problem seems to be Docker Desktop.

And..., you are right - Run-AlValidation will create something called a FilesOnly container - you don't need to create a container yourself.

**Comment by freddydk** [comment]
Can you still create an image using New-BcContainer?
In that case, please copy/paste the full log from that here

**Comment by Markus-HR** [comment]
We are running into a similar issue when running the "Run-AlPipeline".

during the "pulling generic image" phase, i get this error...

Pulling mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
##[error]What's Next?

Below i have the output for scouting the image that "fails" to pull (the image is showing up as an image in docker).
I also ran the docker version command if that helps. This issue started when i upgraded to the current docker version.

C:\WINDOWS\system32
PS >docker scout quickview mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
docker : INFO New version 0.19.0 available (installed version is 0.16.1)
At line:1 char:1
+ docker scout quickview mcr.microsoft.com/businesscentral:10.0.20348.1 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  + CategoryInfo          : NotSpecified: (INFO New versio...sion is 0.16.1):String) [], RemoteException
  + FullyQualifiedErrorId : NativeCommandError

  ...Storing image for indexing
  v Image stored for indexing
  ...Indexing
  v Indexed 358 packages

Your image  mcr.microsoft.com/businesscentral:10.0.20348.1850-dev  â”‚    7C    60H    14M     4L   

What's Next?
  Learn more about vulnerabilities â†’ docker scout cves mcr.microsoft.com/businesscentral:10.0.20348.1850-dev


C:\WINDOWS\system32
PS >docker version
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.24)
  Go version:       go1.20.4
  Git commit:       659604f9
  Built:            Thu May 25 21:52:13 2023
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by freddydk** [comment]
The problem seems to be with Docker Desktop. You could try to run

docker scout repo disable mcr.microsoft.com/businesscentral

or something like that to disable scout on our images?

(I don't run Docker Desktop - have never seen this before)

**Comment by freddydk** [comment]
You could also ask docker what this means:

docker : INFO New version 0.19.0 available (installed version is 0.16.1)

**Comment by Markus-HR** [comment]
After checking dockers documentation, i am pretty sure this is the version of docker scout. The weird thing is, i dont think your "Run-AlPipeline" script is scouting the image. So i am assuming that something is going wrong when the image is being pulled,

Right now im pulling the image via powershell, to see if i get any errors. Il get back to you once i get a better idea of whats going wrong.

**Comment by freddydk** [comment]
I assume that Docker Desktop invokes scout automatically.

Could you try the docker pull from PowerShell 7 or in an elevated command prompt?
It works fine here (I use Docker Engine - not Docker Desktop)
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/a8e3e01b-31b0-4d0c-9647-93140d4b914c)

**Comment by Markus-HR** [comment]
The previous pull i did was in powershell. This does indeed seem to be an issue with docker scout. As far as i can see, this is some early access version they are testing out. It was probably automatically added when i updated docker.

I will try and see if i can disable it, as the command you provided earlier didnt seem to exist. Hopefully that fixes this.

Here is the output in elevated cmd..
docker pull mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
10.0.20348.1850-dev: Pulling from businesscentral
Digest: sha256:01e8fb8f25225dd158e4d9a226154da34ba0a79404cc2d5dd65e32f1668fd27c
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
mcr.microsoft.com/businesscentral:10.0.20348.1850-dev

What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview mcr.microsoft.com/businesscentral:10.0.20348.1850-dev

**Comment by freddydk** [comment]
Was it in PS 5 or PS 7?
PS5 has different handling of error stream from docker I think.

After pulling the image in cmd - does it then work in Run-AlPipeline?

**Comment by faranmahboob** [comment]
Hi @freddydk @DavidHrbek,
I downgraded my docker desktop version to 4.20.1 and it worked.
Now it doesn't get failed at line
docker pull mcr.microsoft.com/businesscentral:10.0.19041.1415-filesonly.

Now I have another issue as windows Docker Images are not available for my windows version. Can I add -Isolation hyperv property in the Run-AlValidation command ?
or the only solution is I have to update my windows ?
can you suggest anything ?
thanks

**Comment by Markus-HR** [comment]
It was indeed using ps 5!

Pulling the image in cmd, had no affect though when re-running the pipeline. Which makes sense to me, since your script pulls the repo again...
```

  _____       _ _ _                                          _        _                            
 |  __ \     | | (_)                                        (_)      (_)                           
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___ 
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |     
                          |___/   |___/                                                 |___/      

'@

if (!$useGenericImage) {
    $Parameters = @{
        "filesOnly" = $filesOnly
    }
    $useGenericImage = Invoke-Command -ScriptBlock $GetBestGenericImageName -ArgumentList $Parameters
}

Write-Host "Pulling $useGenericImage"

Invoke-Command -ScriptBlock $DockerPull -ArgumentList $useGenericImage
```

so if this is a powershell version issue on my end, it would be triggered again when the pipeline is run.

**Comment by freddydk** [comment]
I think the main task here is to figure out why the new Docker Desktop doesn't work with our images.
I will create a machine and install Docker Desktop to see what the freak is going on.

**Comment by Markus-HR** [comment]
Thank you so much Freddy! :)

**Comment by freddydk** [comment]
You can also uninstall docker desktop and install docker engine instead:-)
I use this script: 
https://github.com/microsoft/nav-arm-templates/blob/master/InstallOrUpdateDockerEngine.ps1

I am pretty sure that will work.

**Comment by freddydk** [comment]
It looks like this is a PowerShell 5 only problem.
The reason is that docker pull will emit 

```
What's Next?
  View summary of image vulnerabilities and recommendations â†’ docker scout quickview mcr.microsoft.com/businesscentral:10.0.19041.1415-filesonly
```

on the error stream:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/e16e6f88-0239-4ae0-9545-0fc6e25fef99)

running the same on PowerShell 7 says:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/beddf5b2-2e28-4bc3-b143-6eccbc3904fe)

To show that this indeed is the reason, you can try to use this on PS5:
```
docker pull mcr.microsoft.com/businesscentral:10.0.19041.1415-filesonly 2> $NULL
```

which will pipe the error stream to null.

I will check how I can make BcContainerHelper ignore this error stream when pulling an image, stay tuned.

**Comment by freddydk** [comment]
Fix should be available in the latest BcContainerHelper preview

If anybody can validate the fix?

**Comment by Markus-HR** [comment]
Almost there! I think you need to add similar error handling for the "NewBcContainer" script.

Here is the output when i execute "Run-AlPipeline" with the preview version of BCContainerHelper...

```
   _____                _   _                               _        _                 
  / ____|              | | (_)                             | |      (_)                
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                     __/ |                                             
                                    |___/                                              

Creaing docker container
WARNING: Container name should not exceed 15 characters
BcContainerHelper is version 5.0.5-preview1054
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Pro - 10.0.22621.1992
Docker Client Version is 24.0.2
Docker Server Version is 24.0.2
Removing Desktop shortcuts
Downloading artifact /sandbox/20.5.45456.58790/no
Downloading C:\WINDOWS\TEMP\9f18c158-5e45-466a-8a4f-062e8e40c633.zip
Downloading using WebClient
Unpacking artifact to tmp folder using Expand-Archive
Downloading platform artifact /sandbox/20.5.45456.58790/platform
Downloading C:\WINDOWS\TEMP\da7842a0-56d1-496f-9ce9-d0eeb6870a67.zip
Downloading using WebClient
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\20.5.45456.58790\platform\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading using WebClient
Downloading c:\bcartifacts.cache\sandbox\20.5.45456.58790\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading using WebClient
Downloading c:\bcartifacts.cache\sandbox\20.5.45456.58790\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Downloading using WebClient
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building multitenant image bcimage:sandbox-20.5.45456.58790-no-mt based on mcr.microsoft.com/businesscentral:10.0.20348.1850-dev with https://bcartifacts.azureedge.net/sandbox/20.5.45456.58790/no
Pulling latest image mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
10.0.20348.1850-dev: Pulling from businesscentral
Digest: sha256:01e8fb8f25225dd158e4d9a226154da34ba0a79404cc2d5dd65e32f1668fd27c
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
Generic Tag: 1.0.2.14
Container OS Version: 10.0.20348.1850 (ltsc2022)
Host OS Version: 10.0.22621.1992 (22H2)
Using process isolation
Using license file ***
Downloading c:\bcartifacts.cache\iri4ttx2.0jd\my\license.bclicense
Downloading using WebClient
Files in c:\bcartifacts.cache\iri4ttx2.0jd\my:
- license.bclicense
Copying Platform Artifacts
c:\bcartifacts.cache\sandbox\20.5.45456.58790\platform
Copying Database
Copying Licensefile
Copying ConfigurationPackages
C:\bcartifacts.cache\sandbox\20.5.45456.58790\no\ConfigurationPackages
Copying Extensions
C:\bcartifacts.cache\sandbox\20.5.45456.58790\no\Extensions
Copying Applications.NO
C:\bcartifacts.cache\sandbox\20.5.45456.58790\no\Applications.NO
c:\bcartifacts.cache\iri4ttx2.0jd
Sending build context to Docker daemon  2.218GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.20348.1850-dev
 ---> f5e63eeb5900

Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/20.5.45456.58790/no filesOnly=False
 ---> Running in d8a2521a3632
Removing intermediate container d8a2521a3632
 ---> ccd1a7dd907c
Step 3/6 : COPY my /run/
 ---> 182a9edd5859
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> 261debbfb4a7
Step 5/6 : RUN \Run\start.ps1 -installOnly -multitenant
 ---> Running in 3496f685a101
c:\run\my folder doesn't exist, creating it
Using installer from C:\Run\150-new
Installing Business Central
Installing from DVD
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
C:\NAVDVD\ServiceTier\Program Files
C:\NAVDVD\ServiceTier\System64Folder
Copying PowerShell Scripts
C:\NAVDVD\WindowsPowerShellScripts\Cloud\NAVAdministration
C:\NAVDVD\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
C:\NAVDVD\WebClient\Microsoft Dynamics NAV
Copying Client Files
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\program files\Microsoft Dynamics NAV
C:\NAVDVD\LegacyDlls\systemFolder
Copying ModernDev Files
C:\NAVDVD
C:\NAVDVD\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\NAVDVD\ConfigurationPackages
Copying Test Assemblies
C:\NAVDVD\Test Assemblies
Copying Extensions
C:\NAVDVD\Extensions
Copying Applications
C:\NAVDVD\Applications
Copying Applications.NO
C:\NAVDVD\Applications.NO
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing CRONUS license file
Copying Database on localhost\SQLEXPRESS from tenant to default
Taking database tenant offline
Copying database files
Attaching files as new Database default
Putting database tenant back online
Mounting tenant database
Mounting Database for default on server localhost\SQLEXPRESS with AllowAppDatabaseWrite = False
Sync'ing Tenant
Tenant is Operational
Stopping Business Central Service Tier
Installation took 351 seconds
Installation complete
Removing intermediate container 3496f685a101
 ---> 0e47d2591b89
Step 6/6 : LABEL legal="http://go.microsoft.com/fwlink/?LinkId=837447"       created="202307180838"       nav=""       cu=""       multitenant="Y"       country="NO"       version="20.5.45456.58790"       platform="20.0.45448.58773"
 ---> Running in ce255d09060d
Removing intermediate container ce255d09060d
 ---> d5200a7e7aac
Successfully built d5200a7e7aac
Successfully tagged bcimage:sandbox-20.5.45456.58790-no-mt
##[error]What's Next?
  View summary of image vulnerabilities and recommendations → docker scout quickview
Building image took 738 seconds
```

**Comment by freddydk** [comment]
This isn't due to New-BcContainer, this is New-BcImage:-(
yeah, this is when an image is build just-in-time.
If you remove the -imageName parameter, then it should work.
Will check what I can do about this one

**Comment by freddydk** [comment]
> Almost there! I think you need to add similar error handling for the "NewBcContainer" script.
> 

This should be fixed in the next prerelease

**Comment by freddydk** [comment]
Shipped
