### ISSUE TITLE
"Docker Service not found / Docker is not installed" after Docker Desktop Update

### ISSUE THREAD

**Issue by nickrobbo** [Microsoft/navcontainerhelper#312]
Hi, 

I have found an issue after updating to the latest version of docker desktop.
I am running the following version of Docker Desktop :
Version: V2.0.0.2 (30215)
Channel: Stable
Build: 0b030e1 

I am running this on my Windows 10 machine. Version Details are as follows:
Version: 1809 (OS Build 17763.253)
OS: Windows 10 Pro

When running New-NavContainer, the system checks to see if docker is running using the following code:

`    $dockerService = (Get-Service docker -ErrorAction Ignore)
    if (!($dockerService)) {
        throw "Docker Service not found / Docker is not installed"
}`

It seems docker may have renamed the underlying service from "docker" to "com.docker.service".

![image](https://user-images.githubusercontent.com/35219805/51428665-3832b080-1bfe-11e9-8dbf-5034c37ba6a3.png)

**Comment by tfenster** [comment]
@nickrobbo `com.docker.service` is used for the Docker Desktop tooling and doesn't run the Docker engine itself. If you switch to Windows Containers, the `docker` service should appear

**Comment by nickrobbo** [comment]
@tfenster - thanks for this, rookie error! I re-installed docker through chocolately and forgot to switch to Windows Containers.
