### ISSUE TITLE
Run-ALValidation not detecting localization errors

### ISSUE THREAD

**Issue by buzzwick** [microsoft/navcontainerhelper#3122]
We ran Run-ALValidation against our latest release, and specifying the following countries: "US", "DE", "GB","MX","CA"
We got no errors, only "Run-ALValidation Success."
We then submitted the exact same .app file for AppSource validation, and it failed for every country except US:
`Severity level: Error, Message: (Version, country-region) validation completed with failures: version 21.4, country-region MX`

We are referred to our Azure Application Insights resource, which gives us all of the messages like the above, but no information as to the nature of the failure. Because the application is not yet actually running in Azure, we cannot find any more information about the errors.

We did notice that the AppSource validation seems to be using different platform/application versions than the ones used by Run-ALValidation (note the 21.4, above, for MX); we have no idea why.

Is there any way to get further information out of Run-ALValidation as to these localization issues, or are we missing something in our execution of that cmdlet?  Below is our script:

```
$validationResults = Run-AlValidation `
    -validateCurrent `
    -apps @( "C:\Users\dbaldwin\Downloads\CAI-Software-Precious-Metals-Solution-main-Apps-21.9.115.0\CAI Software_CAI Software Precious Metals Solution_21.9.115.0.app" ) `
    -countries @( "US","DE","GB","MX","CA" ) `
    -affixes @( "CAI" ) `
    -supportedCountries @( "US", "DE", "GB","MX","CA" ) `
    -containerName bcvalidation
$validationResults | Write-Host -ForegroundColor Red
```

**Comment by freddydk** [comment]
You could also provide me with your app (and previous app) then I can try this myself.

**Comment by freddydk** [comment]
Got it - send me a link (freddyk at microsoft dot com) where I can download the app file

**Comment by buzzwick** [comment]
This should work; you have access to the repo. Dropbox is not cooperating:

https://github.com/CAI-Software-Inc/CAI-Software-Precious-Metals-Solution/releases/download/21.9.115/CAI-Software-Precious-Metals-Solution-main-Apps-21.9.115.0.zip

**Comment by freddydk** [comment]
Got it - but maybe you should delete it if you don't want to share it with the world.

**Comment by buzzwick** [comment]
Delete from where? Those are the artifacts from the release. I almost put the link here; that would have been shared with the world--but the email? Isn't that the point of using email? The world does not have access to that repository, do they?

**Comment by freddydk** [comment]
You are right - I read dropbox and thought you sent a deep link.

**Comment by freddydk** [comment]
When you specify -validatecurrent - you validate ONLY against current version.
If you remove -validateCurrent - then Run-AlValidation will validate against the same version(s) that online validation will use and you will see:
```
Compilation started for project 'CAI Software Precious Metals Solution' containing '426' files at '22:27:52.965'.

C:\ProgramData\BcContainerHelper\4c0af776-35f3-4a44-a677-ecbc334776c9\src\src\src\report\CAISOShipNotInvoiced.Report.al(273,41): error AL0132: 'Codeunit Se
gManagement' does not contain a definition for 'FindInteractionTemplateCode'

Compilation ended at '22:27:59.840'.
```
Meaning that your app.json specifies 21.0 as dependency when you actually need a later version (maybe 22.0)

**Comment by buzzwick** [comment]
Aha. The old shoot yourself in the foot trick. Okay, validateCurrent comes out. 

So we thought that if the app.json specifed 21.0 for Application and Platform, that was a minimum, such that any later version would be okay. But it sounds like that is forcing validation against earlier versions? 
If so, we will change that to 22.0.

We think these errors are localization errors--that version is not critical, but certain US elements are simply not available in the GB, DE versions, etc.

**Comment by freddydk** [comment]
It is your minimum compatible version.
If you specify 21.0 - you specify that the app can be installed on 21.0 or later.
But your app has a dependency on a later BC version.

**Comment by buzzwick** [comment]
"But your app has a dependency on a later BC version."  -- And no doubt that dependency arises from the container(s) we are developing against--which are all version 22 and later. So downloaded symbols are all coming from there. I think I see the problem.

Does this explain why the MX version is being compiled by the AppSource validation against 21.4? Is that controlled by the manifest?

**Comment by freddydk** [comment]
AppSource validation uses the application dependency - as people with 21.x could potentially install this app.

**Comment by buzzwick** [comment]
Okay. Got it. Won't apply for us; we will go ahead and update the manifest to match the application & platform that we are actually developing against.  That should be our minimum version. Thanks very much.

**Comment by freddydk** [comment]
Exactly - application dependency should always be your actual BC application dependency.
