### ISSUE TITLE
Totally delete Test Toolkit before installation by parameter installTestFramework = $true

### ISSUE THREAD

**Issue by BennoVendrig** [microsoft/navcontainerhelper#3126]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
We use a database including testdata which is used for the automated tests. In this database the test toolkit is also installed for running the testscripts manually. If we use this database in the pipeline we receive error's like "A package with publisher 'Microsoft', name 'System Application', and a version compatible with '22.3.0.0' could not be loaded. Symbols for the requested app System Application by Microsoft 22.3.0.0 could not be found in the database.". We try to unpublish before the test toolkit is installed by the AIRunpipeline script but it seems not everything is deleted. Is there an easey way to clean up the database with the test toolkit so it will be installed automatically with the right version by using the ALRunPipeline script?

**Scripts used to create container and cause the issue**
```
```

**Full output of scripts**
```
NavContainerHelper is version 5.0.4
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2022 Datacenter
Docker Client Version is 24.0.4
Docker Server Version is 24.0.4
...
```

**Screenshots**

**Additional context**
- does it happen all the time? Yes
- did it use to work? Yes but not with BC22 anymore

**Comment by freddydk** [comment]
I assume that if you uninstall and unpublish with -doNotSaveData and -doNotSaveSchema, it should remove everything:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/6af358e4-685e-4d40-8fd6-7da0d293e0a8)

**Comment by BennoVendrig** [comment]
Thanks
