### ISSUE TITLE
Parameter Request for Import-TestToolkitToNavContainer

### ISSUE THREAD

**Issue by gunnargestsson** [Microsoft/navcontainerhelper#313]
Hi

Can you please add a parameter to this function.

-ignoreSymbolUpdate

or something similar.

I am using 

`Import-TestToolkitToNavContainer -containerName $BranchSettings.dockerContainerName -includeTestLibrariesOnly `

and it should not update symbols in the container as that will break the existing test symbols.

**Comment by freddydk** [comment]
-doNotUpdateSymbols is added to next version - you can download the next version by cloning the dev branch

**Comment by freddydk** [comment]
Shipped in 0.5.0.0
