### ISSUE TITLE
Publish-BCContainerApp not working headless because of dependencies

### ISSUE THREAD

**Issue by crazycga** [microsoft/navcontainerhelper#3146]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I'm feeling really stupid, but I haven't found documentation about this yet.  I'm hoping someone can help.  When I publish a PTE on a *fresh* Docker image on my test machine, I'm getting a request asking if I want to install Extension & Dependencies.  This won't work with a pipeline that I'm trying to set up to automatically keep my testing machine up to date with the latest images.

**Scripts used to create container and cause the issue**
```
 publish-bccontainerapp -containername "myDemo" -appfile '.\NameOfMyApp.1033.app' -credential $mycreds -skipVerification -install -upgrade -sync
```

**Full output of scripts**
```
Publishing C:\ProgramData\BcContainerHelper\Extensions\myDemo\<a_tenant_guid>\NameOfMyApp.1033.app Synchronizing NameOfMyApp on tenant default
Installing NameOfMyApp on tenant default                                                                                                                                                                                   MicrosoftDynamicsNavServer$BC/default
Dependencies found without -Force specified. \r\n Do you want to install Extension & Dependencies?
[Y] Yes  [N] No  [?] Help (default is "Y"):
```

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/22846280/7f37b692-5237-4088-af0a-b9e8d312f63a)

**Additional context**
- does it happen all the time?
- Answer: it only happens when I am installing on a fresh instance, obviously because the dependencies are already installed
- did it use to work?
- Answer: not on a fresh instance

I'm 100% sure that it's me not understanding something, but I haven't found documentation or any setting that allows me to do this, and the -Force setting is not propagated through the function, so it tells me to stuff myself when I try to specify -Force.

How do I get around this?  Thanks in advance.

**Comment by crazycga** [comment]
Curiousity...  Has this been replicated by anyone else?  I ask because 22.5 is coming out and it would be nice to not have to manually update my testing machine.

**Comment by freddydk** [comment]
Sorry for this - I never managed to make a repro.
Any chance you can supply me with the App File to repro this?
Also, what is the dependency from the app?

Thanks

**Comment by crazycga** [comment]
I hope you meant app.json?  It's attached (with minor modifications.)  
[modified app.json.txt](https://github.com/microsoft/navcontainerhelper/files/12528649/modified.app.json.txt)

**Comment by freddydk** [comment]
And what version of Business Central is your container?
Can you dump the full log of container creation and the error you get from Publish-BcContainerApp?

**Comment by crazycga** [comment]
It'll take me a bit to get that.  Just letting you know I've received this and will update when I get there.  Thanks.

**Comment by crazycga** [comment]
Hey there.  I've extracted the script that I use and done it step by step to ensure that I capture the output.  Here is it, in .TXT form, and I've taken out my client's name (replaced with %%NAMEOFMYCLIENT%%) for privacy reasons.

[Step by step.txt](https://github.com/microsoft/navcontainerhelper/files/12563355/Step.by.step.txt)

The BC Container Helper version is: 5.0.5

![image](https://github.com/microsoft/navcontainerhelper/assets/22846280/54a20c87-2c57-4e26-afcb-e4e27f058456)
[Container Creation Log.txt](https://github.com/microsoft/navcontainerhelper/files/12563388/Container.Creation.Log.txt)

The container version is:
22.5.59966.60395 (as taken from the Docker log.)

The full container creation log is also attached.

Again, to be clear, if I hit "yes" here, things progress fine.  But that doesn't help, because I'm trying to use this with a pipeline.  It says that -force wasn't specified, which I'd love to be able to do, but your function doesn't pass that through...

Anyway, thank you very much for looking into this.
-J

**Comment by crazycga** [comment]
And also, further to my last.  It only does this the FIRST TIME I install my app on a fresh machine.  Every time now it'll work just fine until I update again.  And while that's a workaround, I want to be able to update my test machine off-hours in an automated way.

**Comment by crazycga** [comment]
Incidentally, my workaround has now stopped working entirely.  Do you have an idea when the "ships in a future version" might become the "current version"?  👍 

Thank you for this amazing tool!

**Comment by freddydk** [comment]
If you download the prerelease version of BcContainerHelper - it should work.

**Comment by crazycga** [comment]
I'm running 5.0.6-preview1070 and no dice, the -Force parameter still comes up with "a parameter cannot be found that matches..."  Is that the wrong version?  It seems to be the latest...  Thanks.

PS it DOES seem like the PR isn't done yet?  https://github.com/microsoft/navcontainerhelper/pull/3184

Or am I misreading this?  (I'm an Azure DevOps guy, not a GitHub guy.)

**Comment by freddydk** [comment]
My bad - you are right - it wasn't approved - will ask for approval right away

**Comment by freddydk** [comment]
Preview should be released now - containing this fix.

**Comment by crazycga** [comment]
Just checked, this works beautifully in preview-1071.  Thank you!  Don't know what your workflow is, but this issue can be closed.  Thanks again!
