### ISSUE TITLE
Exception when downloading the artifacts: Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."

### ISSUE THREAD

**Issue by equisyscr** [microsoft/navcontainerhelper#3149]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Error when downloading the artifacts from url like 'https://bcartifacts.azureedge.net/onprem/19.4.35398.35482/gb'

**Scripts used to create container and cause the issue**
$credential = (New-Object pscredential 'admin', (ConvertTo-SecureString -String '123' -AsPlainText -Force))
New-BCContainer  -accept_eula `
                    -accept_outdated `
                    -artifactUrl 'https://bcartifacts.azureedge.net/onprem/19.4.35398.35482/gb' `
                    -auth NavUserPassword `
                    -containerName 'bcgb' `
                    -Credential $credential

**Full output of scripts**
BcContainerHelper is version 5.0.4
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Pro - 10.0.19045.3324
Docker Client Version is 18.09.11
Docker Server Version is 18.09.11
Removing Desktop shortcuts
Downloading artifact /onprem/19.4.35398.35482/gb
Downloading C:\Users\MyUser\AppData\Local\Temp\8a82b81d-255e-454d-891f-ccefa9b73f2d.zip
Downloading using WebClient
Could not download from CDN..., retrying from blob storage in 6 seconds...
Downloading using WebClient
Download-Artifacts Telemetry Correlation Id: d986c0c3-94b8-47a9-8048-0af636227c7f
New-BCContainer Telemetry Correlation Id: 4f49f4c4-bc12-4999-afb3-d6a716aed005
Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\Common\Download-File.ps1:98 char:17
+                 throw (GetExtendedErrorMessage $_)
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Exception calli...lient request.":String) [], RuntimeException
    + FullyQualifiedErrorId : Exception calling "DownloadFile" with "2" argument(s): "An exception occurred during a WebClient request."

**Screenshots**
NA

**Additional context**
- does it happen all the time? Yes
- did it use to work? Yes

**Comment by freddydk** [comment]
can you download the artifacts with a browser? (works fine from here)
it seems like there is something that prevents you from downloading the artifact
Can you download other artifacts?

**Comment by equisyscr** [comment]
Yes I can download from the browser indeed.

For other artifacts, trying to get new ones fails (not already downloaded previously).

**Comment by equisyscr** [comment]
Ok, found the issue: down to internet access micro cuts.
Changed my setup from wifi to RJ45, seems to do the trick
