### ISSUE TITLE
Function to Refresh NAV Database

### ISSUE THREAD

**Issue by eclipses24** [Microsoft/navcontainerhelper#315]
Hi, 

Is there a way to refresh the database only (remove customizations and replace with standard objects) wihout needed to Recreate the entire NAV-Container?

This could be useful in the CI.

Kind Regads
  Sergio Castelluccio

**Comment by freddydk** [comment]
For CI, I recommend recreating the container - it is less than 2 minutes and replacing the database really wouldn't be much faster.

**Comment by freddydk** [comment]
Not sure what agent you are using, but my suggestions on CI are all on my blog - at this time five posts ending with https://blogs.msdn.microsoft.com/freddyk/2018/11/17/developing-business-central-extensions-part-5/ (more to come)
Including the test toolkit import - it might take more than 2 minutes - and I typically remove the container and clean up after every build.
I will consider your suggestion - after all, it might speed up things, but it is also important for me that the same agents can be used for multiple versions of business central or nav.
thanks for the suggestion.

**Comment by freddydk** [comment]
You can actually do this very easily yourself...
Right after you create the container, you run this:
```
$containerName = "fkdev"
$config = Get-NavContainerServerConfiguration -ContainerName $containerName
Invoke-ScriptInNavContainer -containerName $containerName -scriptblock { Param($DatabaseServer, $DatabaseInstance, $DatabaseName, $NewDatabaseName)
    Copy-navDatabase -DatabaseServer $DatabaseServer -DatabaseInstance $DatabaseInstance -SourceDatabaseName $DatabaseName -DestinationDatabaseName $NewDatabaseName
} -argumentList $config.DatabaseServer, $config.DatabaseInstance, $config.DatabaseName, "backup"
```
When you need to restore, you can
```
$containerName = "fkdev"
$config = Get-NavContainerServerConfiguration -ContainerName $containerName
Invoke-ScriptInNavContainer -containerName $containerName -scriptblock { Param($DatabaseServer, $DatabaseInstance, $DatabaseName, $NewDatabaseName)
    Copy-navDatabase -DatabaseServer $DatabaseServer -DatabaseInstance $DatabaseInstance -SourceDatabaseName $DatabaseName -DestinationDatabaseName $NewDatabaseName
} -argumentList $config.DatabaseServer, $config.DatabaseInstance, "backup", $config.DatabaseName
```

**Comment by freddydk** [comment]
Well, that is almost what the script does - the only difference is, that it doesn't copy the database to the outside - but keeps it inside the container which I think is absolutely the smartest (this way you don't have to invent a naming algorithm for databases on which container they match).
First script will take a copy of the database.
Other script will replace the standard with that copy.
On my machine - these scripts takes less than 10 seconds.

**Comment by eclipses24** [comment]
ok, I closing this. Thanks again for your time and support
