### ISSUE TITLE
The virtual  machine could not be started because a required feature is not installed.

### ISSUE THREAD

**Issue by HennieBink** [microsoft/navcontainerhelper#3152]
**Describe the issue**
The virtual  machine could not be started because a required feature is not installed.

**Scripts used to create container and cause the issue**
Run-AlPipeline @parameters -outputFolder ".output/latest" -testResultsFile "$app/$pipelineName-latest.xml" -installTestLibraries:([bool]::Parse($enableTestFunctionality)) -installTestFramework:([bool]::Parse($enableTestFunctionality)) -doNotRunTests:([bool]::Parse(!$enableTestFunctionality)) -createRuntimePackages -enableCodeCop -enableAppSourceCop:([bool]::Parse($appSourceCop)) -buildArtifactFolder ".output/latest"

**Full output of scripts**
   _____                _   _                               _        _                 
  / ____|              | | (_)                             | |      (_)                
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                     __/ |                                             
                                    |___/                                              

Creaing docker container
WARNING: Container name should not exceed 15 characters
BcContainerHelper is version 5.0.6-preview1061
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows Server 2019 Datacenter - 10.0.17763.4737
Docker Client Version is 24.0.5
Docker Server Version is 24.0.5
Removing Desktop shortcuts
Downloading artifact /sandbox/22.4.59114.59592/us
Downloading C:\Users\Jenkins\AppData\Local\Temp\44185699-9335-4aac-9ced-f2627932158f.zip
Downloading using WebClient
Unpacking artifact to tmp folder using 7zip
Downloading platform artifact /sandbox/22.4.59114.59592/platform
Downloading C:\Users\Jenkins\AppData\Local\Temp\2b7e1995-6ba2-45cf-ba31-1291fd888a08.zip
Downloading using WebClient
Unpacking platform artifact to tmp folder using 7zip
Downloading Prerequisite Components
Downloading X:\BcArtifacts.cache\sandbox\22.4.59114.59592\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading using WebClient
Downloading X:\BcArtifacts.cache\sandbox\22.4.59114.59592\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Downloading using WebClient
INFO: Patching wrong version of Microsoft.IdentityModel.Clients.ActiveDirectory.dll in X:\BcArtifacts.cache\sandbox\22.4.59114.59592\platform\Applications\testframework\TestRunner\Internal\Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building multitenant image my:sandbox-22.4.59114.59592-us-mt based on mcr.microsoft.com/businesscentral:10.0.17763.4645-dev with https://bcartifacts.azureedge.net/sandbox/22.4.59114.59592/us
Pulling latest image mcr.microsoft.com/businesscentral:10.0.17763.4645-dev
10.0.17763.4645-dev: Pulling from businesscentral
Digest: sha256:13d27a66c56ae074b45217541a7148b3564cc9c5eb90d56c3b0f22bded36dbfd
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.17763.4645-dev
mcr.microsoft.com/businesscentral:10.0.17763.4645-dev
Generic Tag: 1.0.2.14
Container OS Version: 10.0.17763.4645 (ltsc2019)
Host OS Version: 10.0.17763.4737 (ltsc2019)
Using hyperv isolation
Using license file c:\JenkinsWorkspace\5465549.bclicense
Files in X:\BcArtifacts.cache\pculezua.obp\my:
Copying Platform Artifacts
X:\BcArtifacts.cache\sandbox\22.4.59114.59592\platform
Copying Database
Copying Licensefile
Copying ConfigurationPackages
X:\BcArtifacts.cache\sandbox\22.4.59114.59592\us\ConfigurationPackages
Copying Extensions
X:\BcArtifacts.cache\sandbox\22.4.59114.59592\us\Extensions
Copying Applications.US
X:\BcArtifacts.cache\sandbox\22.4.59114.59592\us\Applications.US
X:\BcArtifacts.cache\pculezua.obp
Sending build context to Docker daemon  2.528GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.4645-dev
 ---> cf881594d899
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/22.4.59114.59592/us filesOnly=False
 ---> Running in e5ba0c4c5918
Removing intermediate container e5ba0c4c5918
 ---> 4a02829f9054
Step 3/6 : COPY my /run/
 ---> 9633399f927a
Step 4/6 : COPY NAVDVD /NAVDVD/
 ---> e93d0baf87eb
Step 5/6 : RUN \Run\start.ps1 -installOnly -multitenant
 ---> Running in 154260b5a0d1
New-Bcimage Telemetry Correlation Id: 621b860b-df7e-4d33-916c-65826a71962b
New-BcContainer Telemetry Correlation Id: d208c2d8-9a8a-48c9-a9db-d2e04cce6894
Removing Desktop shortcuts
Run-AlPipeline Telemetry Correlation Id: 9bbf60b6-a0fe-4dbb-bbec-ec9f90bcd403
DockerDo : hcs::CreateComputeSystem 154260b5a0d1e2d5a13016434d36f38f7c2f32bdfd672e4c0606edd34c1faa69: The virtual 
machine could not be started because a required feature is not installed.
ExitCode: 1
Commandline: docker build --isolation=hyperv --memory 8G --no-cache --tag my:sandbox-22.4.59114.59592-us-mt 
X:\BcArtifacts.cache\pculezua.obp
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.6\ContainerHandling\New-NavImage.ps1:694 char:27
+ ...       if (!(DockerDo -command build -parameters @("--isolation=$isola ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
This is because your host was updated to the latest Windows Server version before our pipelines generated the corresponding Container OS. And the reson for this is that there is a bug in the pipeline generating generic container images, sorry for that.
Will be fixed today.
You could try to add -isolation process to see if that works - or wait until it suddenly works again.

**Comment by freddydk** [comment]
the generic container matching your host OS should be published now.

**Comment by HennieBink** [comment]
Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.4737-dev
 ---> 4296d95c40a7
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/22.4.59114.59607/us filesOnly=False
New-Bcimage Telemetry Correlation Id: a6592eae-fa4f-4ecc-835d-64cb868f9d7d
New-BcContainer Telemetry Correlation Id: b65f6720-cee1-4199-97d9-1eee7e14564e
Removing Desktop shortcuts
Run-AlPipeline Telemetry Correlation Id: 58be7afc-149d-4447-8115-725d63bae1d8
DockerDo : hcsshim::CreateScratchLayer failed in Win32: The system cannot find the path specified. (0x3)
ExitCode: 1
Commandline: docker build --isolation=process --memory 8G --no-cache --tag my:sandbox-22.4.59114.59607-us-mt 
X:\BcArtifacts.cache\qwfbhhmf.ul1
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.6\ContainerHandling\New-NavImage.ps1:694 char:27
+ ...       if (!(DockerDo -command build -parameters @("--isolation=$isola ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
