### ISSUE TITLE
Trying to Digitally sign our app - could not resolve: 'bcartifacts.azureedge.net

### ISSUE THREAD

**Issue by dkiehl** [microsoft/navcontainerhelper#3153]
**Describe the issue**
Trying to Digitally sign our app file for marketplace.  Getting error 
```
"The remote name could not be resolved: 'bcartifacts.azureedge.net'"
```

**Scripts used to create container and cause the issue**
Build container script
```
New-BCContainer `
    -accept_eula `
    -containerName $name `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -multitenant:$false `
    -updateHosts `
    -isolation hyperv `
    -licenseFile $localLicenseFile `
    -additionalParameters @('--volume "C:\temp:C:\temp"')
```
Signing script
```
$MyAppFile = "C:\Temp\ITA WMS Corp_myappfile_22.0.0.0.app"
$MyPfx = "C:\Temp\Server Certificate.pfx"
$MyPassword = ConvertTo-SecureString "<mypass>" -AsPlainText -Force
$MyContainerName = "MyBC22Container"

Sign-NavContainerApp -appFile $MyAppFile -pfxFile $MyPfx -pfxPassword $MyPassword -containerName $MyContainerName
```

**Full output of scripts**

```
Downloading Signing Tools
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'bcartifacts.azureedge.net'"

Container Free Physical Memory: 3.5Gb

Services in container BC22:
- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running

Sign-NavContainerApp Telemetry Correlation Id: fa1cc79d-f1d8-417c-a97c-34b4e193a018
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'bcartifacts.azureedge.net'"
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:285 char:25
+                         throw $errorMessage
+                         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Exception calli...azureedge.net'":String) [], RuntimeException
    + FullyQualifiedErrorId : Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'bcartifacts.azureedge.net'"
```

**Additional context**
- BCContainerhelper version 5.0.5
- Used to work - verified the code signing certificate
- used Flush-ContainerHelperCache - didn't help
- rebuilt container several times trying Sandbox and OnPrem versions with latest artifacts for version 22

```
Get-BCArtifactUrl -type Sandbox -country us -version 22 -select Latest
https://bcartifacts.azureedge.net/sandbox/22.4.59114.59597/us
```

**Comment by freddydk** [comment]
If you had included the full log of the container creation, I could have seen whether the problem is what I think it is.
It sounds like your your container doesn't have access to do DNS resolution.
You can try to add -dns 'hostdns' to your new-BcContainer to allow your container to use the same dns contiguration as your host.

**Comment by dkiehl** [comment]
I  recreated the container using -dns 'hostdns' - and the results were the same.  Here is the container output.  There is a line in there "WARNING: DNS resolution not working from within the container" which confirms your conclusion.  Not sure how to resolve it...

`
Downloading Artifacts
Downloading artifact /sandbox/22.4.59114.59607/us
Downloading C:\Users\dkiehl\AppData\Local\Temp\d07bea05-ef92-4363-8d3b-5d9d4bc46206.zip
Downloading using WebClient
Unpacking artifact to tmp folder using Expand-Archive
c:\bcartifacts.cache\sandbox\22.4.59114.59607\us
Downloading platform artifact /sandbox/22.4.59114.59607/platform
Downloading C:\Users\dkiehl\AppData\Local\Temp\f4067c43-11f3-4200-bd12-4ce36026d928.zip
Downloading using WebClient
Unpacking platform artifact to tmp folder using Expand-Archive
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\22.4.59114.59607\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading using WebClient
Downloading c:\bcartifacts.cache\sandbox\22.4.59114.59607\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Downloading using WebClient
INFO: Patching wrong version of Microsoft.IdentityModel.Clients.ActiveDirectory.dll in c:\bcartifacts.cache\sandbox\22.4.59114.59607\platform\Applications\testfram
ework\TestRunner\Internal\Microsoft.IdentityModel.Clients.ActiveDirectory.dll
c:\bcartifacts.cache\sandbox\22.4.59114.59607\platform
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Removing existing container...(if it exists)
Removing Session BC22
Removing container BC22
Removing entries from hosts
Removing BC22 from container hosts file
Removing BC22-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\BC22
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Building new container
BcContainerHelper is version 5.0.5
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Pro - 10.0.22621.2134
Docker Client Version is 24.0.5
Docker Server Version is 24.0.5
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.20348.1906
10.0.20348.1906: Pulling from businesscentral
7c76e5cf7755: Already exists
22a441455ace: Pulling fs layer
158b79dd1f5c: Pulling fs layer
c71edc7a1547: Pulling fs layer
59f7350c856c: Pulling fs layer
92e0d318a35c: Pulling fs layer
ef485af973c3: Pulling fs layer
4e1d5c6ee165: Pulling fs layer
84de218c9f9a: Pulling fs layer
c405de89078b: Pulling fs layer
92e0d318a35c: Waiting
ef485af973c3: Waiting
30628ff07013: Pulling fs layer
e643dd0e14ef: Pulling fs layer
c405de89078b: Waiting
cdb4f9bf9ab7: Pulling fs layer
84de218c9f9a: Waiting
df69cf8627e5: Pulling fs layer
9857d2162923: Pulling fs layer
30628ff07013: Waiting
4e1d5c6ee165: Waiting
cdb4f9bf9ab7: Waiting
e643dd0e14ef: Waiting
9857d2162923: Waiting
158b79dd1f5c: Verifying Checksum
158b79dd1f5c: Download complete
59f7350c856c: Verifying Checksum
59f7350c856c: Download complete
92e0d318a35c: Verifying Checksum
92e0d318a35c: Download complete
ef485af973c3: Verifying Checksum
ef485af973c3: Download complete
4e1d5c6ee165: Verifying Checksum
4e1d5c6ee165: Download complete
c71edc7a1547: Verifying Checksum
c71edc7a1547: Download complete
c405de89078b: Verifying Checksum
c405de89078b: Download complete
84de218c9f9a: Verifying Checksum
84de218c9f9a: Download complete
e643dd0e14ef: Verifying Checksum
e643dd0e14ef: Download complete
cdb4f9bf9ab7: Verifying Checksum
cdb4f9bf9ab7: Download complete
df69cf8627e5: Download complete
9857d2162923: Verifying Checksum
9857d2162923: Download complete
22a441455ace: Verifying Checksum
22a441455ace: Download complete
30628ff07013: Verifying Checksum
30628ff07013: Download complete
22a441455ace: Pull complete
158b79dd1f5c: Pull complete
c71edc7a1547: Pull complete
59f7350c856c: Pull complete
92e0d318a35c: Pull complete
ef485af973c3: Pull complete
4e1d5c6ee165: Pull complete
84de218c9f9a: Pull complete
c405de89078b: Pull complete
30628ff07013: Pull complete
e643dd0e14ef: Pull complete
cdb4f9bf9ab7: Pull complete
df69cf8627e5: Pull complete
9857d2162923: Pull complete
Digest: sha256:9a12bd9733c4bd49affddf5a8dbc0bf408551b50eb4a85a8f60efab4301184f4
Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.20348.1906
mcr.microsoft.com/businesscentral:10.0.20348.1906
Using image mcr.microsoft.com/businesscentral:10.0.20348.1906
Creating Container BC22
Style: sandbox
Multitenant: No
Version: 22.4.59114.59607
Platform: 22.0.59576.0
Generic Tag: 1.0.2.14
Container OS Version: 10.0.20348.1906 (ltsc2022)
Host OS Version: 10.0.22621.2134 (22H2)
Using hyperv isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file D:\Support\Licenses\BC22\5414366.bclicense
Additional Parameters:
--volume "C:\temp:C:\temp"
Files in C:\ProgramData\BcContainerHelper\Extensions\BC22\my:
- AdditionalOutput.ps1
- license.bclicense
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC22 from image mcr.microsoft.com/businesscentral:10.0.20348.1906
c6a9b51d3ce092b708c077d385f134ff607afe45072a154bdf0ffb6e211d37ee
Waiting for container BC22 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/sandbox/22.4.59114.59607/us
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\22.4.59114.59607\platform\ServiceTier\Program Files
c:\dl\sandbox\22.4.59114.59607\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\22.4.59114.59607\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\22.4.59114.59607\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\22.4.59114.59607\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\22.4.59114.59607\platform
c:\dl\sandbox\22.4.59114.59607\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\22.4.59114.59607\us\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\22.4.59114.59607\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\22.4.59114.59607\us\Extensions
Copying Applications
C:\dl\sandbox\22.4.59114.59607\platform\Applications
Copying Applications.US
C:\dl\sandbox\22.4.59114.59607\us\Applications.US
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 90 seconds
Installation complete
Initializing...
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.20.128.1 in container hosts file
Starting Container
Hostname is BC22
PublicDnsName is BC22
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint D56228A5CEE2107B0696609194A0A06E9A53ED8C
DNS identity BC22
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer without SSL
Update configuration: navsettings.json
Done Configuring Web Client
Enabling Financials User Experience
Using license file 'c:\run\my\license.bclicense'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating vmadmin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.20.136.173
Container Hostname  : BC22
Container Dns Name  : BC22
Web Client          : http://BC22/BC/
Dev. Server         : http://BC22
Dev. ServerInstance : BC
Setting BC22 to 172.20.136.173 in host hosts file

Files:
http://BC22:8080/ALLanguage.vsix

Container Total Physical Memory is 8.5Gb
Container Free Physical Memory is 5.5Gb

Initialization took 107 seconds
Ready for connections!
Reading CustomSettings.config from BC22
Creating Desktop Shortcuts for BC22
Cleanup old dotnet core assemblies
Container BC22 successfully created

Use:
Get-BcContainerEventLog -containerName BC22 to retrieve a snapshot of the event log from the container
Get-BcContainerDebugInfo -containerName BC22 to get debug information about the container
Enter-BcContainer -containerName BC22 to open a PowerShell prompt inside the container
Remove-BcContainer -containerName BC22 to remove the container again
docker logs BC22 to retrieve information about URL's again`

**Comment by dkiehl** [comment]
I added the dns option - and that resolved the issue (and the dns)

Thanks
DK
