### ISSUE TITLE
DockerDo : hcsshim::CreateScratchLayer failed in Win32: The system cannot find the path specified. (0x3)

### ISSUE THREAD

**Issue by HennieBink** [microsoft/navcontainerhelper#3157]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
DockerDo : hcsshim::CreateScratchLayer failed in Win32: The system cannot find the path specified. (0x3)

**Scripts used to create container and cause the issue**
Run-AlPipeline 

**Full output of scripts**

   _____                _   _                               _        _                 
  / ____|              | | (_)                             | |      (_)                
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                     __/ |                                             
                                    |___/                                              

Creaing docker container
WARNING: Container name should not exceed 15 characters
BcContainerHelper is version 5.0.6-preview1063
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows Server 2019 Datacenter - 10.0.17763.4737
Docker Client Version is 24.0.5
Docker Server Version is 24.0.5
Removing Desktop shortcuts
Downloading artifact /sandbox/22.4.59114.59697/us
Downloading C:\Users\Jenkins\AppData\Local\Temp\8c10520e-2b66-4266-9e35-e238e5a14b51.zip
Downloading using WebClient
Unpacking artifact to tmp folder using 7zip
Downloading platform artifact /sandbox/22.4.59114.59697/platform
Downloading C:\Users\Jenkins\AppData\Local\Temp\67effedc-4894-499e-b8de-4d7dab795c4c.zip
Downloading using WebClient
Unpacking platform artifact to tmp folder using 7zip
Could not rename 'X:\BcArtifacts.cache\sandbox\22.4.59114.59697\5gpp1n5l.lfa' retrying in 5 seconds.
Retrying...
Could not rename 'X:\BcArtifacts.cache\sandbox\22.4.59114.59697\5gpp1n5l.lfa' retrying in 5 seconds.
Retrying...
Could not rename 'X:\BcArtifacts.cache\sandbox\22.4.59114.59697\5gpp1n5l.lfa' retrying in 5 seconds.
Retrying...
Could not rename 'X:\BcArtifacts.cache\sandbox\22.4.59114.59697\5gpp1n5l.lfa' retrying in 5 seconds.
Retrying...
Downloading Prerequisite Components
Downloading X:\BcArtifacts.cache\sandbox\22.4.59114.59697\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading using WebClient
Downloading X:\BcArtifacts.cache\sandbox\22.4.59114.59697\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Downloading using WebClient
INFO: Patching wrong version of Microsoft.IdentityModel.Clients.ActiveDirectory.dll in X:\BcArtifacts.cache\sandbox\22.4.59114.59697\platform\Applications\testframework\TestRunner\Internal\Microsoft.IdentityModel.Clients.ActiveDirectory.dll
Fetching all docker images
Fetching all docker volumes
ArtifactUrl and ImageName specified
Building multitenant image my:sandbox-22.4.59114.59697-us-mt based on mcr.microsoft.com/businesscentral:10.0.17763.4737-dev with https://bcartifacts.azureedge.net/sandbox/22.4.59114.59697/us
Pulling latest image mcr.microsoft.com/businesscentral:10.0.17763.4737-dev
10.0.17763.4737-dev: Pulling from businesscentral
Digest: sha256:458d5f77cb897666bf6a37090790872f1e02afec78c77c3d0a0eb6ba2001c59a
Status: Image is up to date for mcr.microsoft.com/businesscentral:10.0.17763.4737-dev
mcr.microsoft.com/businesscentral:10.0.17763.4737-dev
Generic Tag: 1.0.2.14
Container OS Version: 10.0.17763.4737 (ltsc2019)
Host OS Version: 10.0.17763.4737 (ltsc2019)
Using process isolation
Using license file c:\JenkinsWorkspace\5465549.bclicense
Files in X:\BcArtifacts.cache\zuscejqq.yoe\my:
Copying Platform Artifacts
X:\BcArtifacts.cache\sandbox\22.4.59114.59697\platform
Copying Database
Copying Licensefile
Copying ConfigurationPackages
X:\BcArtifacts.cache\sandbox\22.4.59114.59697\us\ConfigurationPackages
Copying Extensions
X:\BcArtifacts.cache\sandbox\22.4.59114.59697\us\Extensions
Copying Applications.US
X:\BcArtifacts.cache\sandbox\22.4.59114.59697\us\Applications.US
X:\BcArtifacts.cache\zuscejqq.yoe
Sending build context to Docker daemon  2.532GB

Step 1/6 : FROM mcr.microsoft.com/businesscentral:10.0.17763.4737-dev
 ---> 4296d95c40a7
Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=Y artifactUrl=https://bcartifacts.azureedge.net/sandbox/22.4.59114.59697/us filesOnly=False
New-Bcimage Telemetry Correlation Id: cc8ad054-31e8-45b6-a0bd-98dc49de39b7
New-BcContainer Telemetry Correlation Id: 3e688554-9a68-4b84-a625-e224195fbc20
Removing Desktop shortcuts
Run-AlPipeline Telemetry Correlation Id: 436e68a0-ab66-4902-8410-72cf728b24d2
DockerDo : hcsshim::CreateScratchLayer failed in Win32: The system cannot find the path specified. (0x3)
ExitCode: 1
Commandline: docker build --isolation=process --memory 8G --no-cache --tag my:sandbox-22.4.59114.59697-us-mt 
X:\BcArtifacts.cache\zuscejqq.yoe
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.6\ContainerHandling\New-NavImage.ps1:694 char:27
+ ...       if (!(DockerDo -command build -parameters @("--isolation=$isola ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo
 
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
[GitHub Checks] GitHub check (name: Jenkins, status: completed) has been published.

GitHub has been notified of this commit’s build result

Finished: FAILURE

**Comment by freddydk** [comment]
Is X: a network share?
Something seems wrong with X:

**Comment by freddydk** [comment]
There was no fix for #3152 - that was just waiting for a new generic image to be created matching your host OS.
In general, I don't recommend using a server share for caching - I would assume that this is the cause of this problem.
