### ISSUE TITLE
Retrofit support for HSM backed keys

### ISSUE THREAD

**Issue by XVII** [microsoft/navcontainerhelper#3158]
**Describe the issue**
The GitHub actions have [support for HSM-backed keys](https://github.com/microsoft/AL-Go/blob/main/Actions/Sign/Sign.ps1) via Azure Key Vault and the AzureSignTool.
This functionality should exist in [NavContainerHelper](https://github.com/microsoft/navcontainerhelper/blob/master/AppHandling/Sign-NavContainerApp.ps1).

The current sign task in the GitHub actions relies on:
https://github.com/microsoft/AL-Go/blob/main/Actions/Sign/Sign.ps1

The current sign task in the BcContainerHelper is:
https://github.com/microsoft/navcontainerhelper/blob/master/AppHandling/Sign-NavContainerApp.ps1

**Comment by freddydk** [comment]
The AL-Go sign action uses the AZ powershell module to perform Az Sign - why would we replicate that to ContainerHelper when it exists in a different PowerShell module (which BcContainerHelper would have to download as well)

**Comment by ShadowXVII** [comment]
Just for simplicity for those still relying on BC container helper in DevOps. It uses AzureSignTool, I didn't think az was even involved (though I only use dotnet/sign usually).

Is navsip any closer to being natively supported in dotnet/sign ? AzureSignTool is the second best option. Might simplifying signing on the whole (unless the signing changes version to version).

**Comment by freddydk** [comment]
You are of course right. This is the code from AL-Go for GitHub
NavSip is needed and you can see in this module how it is registered:
https://github.com/microsoft/AL-Go/blob/main/Actions/Sign/Sign.psm1

Code used for registering and signing:

```
        Register-NavSip 
        AzureSignTool sign --file-digest $digestAlgorithm `
            --azure-key-vault-url "https://$AzureKeyVaultName.vault.azure.net/" `
            --azure-key-vault-client-id $AzureCredentials.clientId `
            --azure-key-vault-tenant-id $AzureCredentials.tenantId `
            --azure-key-vault-client-secret $AzureCredentials.clientSecret `
            --azure-key-vault-certificate $Settings.keyVaultCodesignCertificateName `
            --timestamp-rfc3161 "$TimestampService" `
            --timestamp-digest $digestAlgorithm `
            $Files

```

**Comment by freddydk** [comment]
I don't think we will have NavSip automatically supported.

**Comment by ShadowXVII** [comment]
The dotnet team seem open to it (https://github.com/dotnet/sign/issues/173). I've tagged you in this thread.

I'll implement manually for now.

**Comment by pwx24** [comment]
> You are of course right, AzureSignTool. This is the code from AL-Go for GitHub NavSip is needed and you can see in this module how it is registered: https://github.com/microsoft/AL-Go/blob/main/Actions/Sign/Sign.psm1
> 
> Code used for registering and signing:
> 
> ```
>         Register-NavSip 
>         AzureSignTool sign --file-digest $digestAlgorithm `
>             --azure-key-vault-url "https://$AzureKeyVaultName.vault.azure.net/" `
>             --azure-key-vault-client-id $AzureCredentials.clientId `
>             --azure-key-vault-tenant-id $AzureCredentials.tenantId `
>             --azure-key-vault-client-secret $AzureCredentials.clientSecret `
>             --azure-key-vault-certificate $Settings.keyVaultCodesignCertificateName `
>             --timestamp-rfc3161 "$TimestampService" `
>             --timestamp-digest $digestAlgorithm `
>             $Files
> ```

Do you plan in near future to implement this in Sign-NavContainerApp.ps1 (oraz another script) in BCContainerHelper? I think signing apps using Azure and HSM key will be standard for CI/CD purposes soon.

**Comment by freddydk** [comment]
We actually changed this to use dotnet sign instead (which in the latest beta has support for Business Central apps)
