### ISSUE TITLE
remove older versions of navcontainerhelper

### ISSUE THREAD

**Issue by TheovdVen** [Microsoft/navcontainerhelper#316]
Hi Freddy,

I have some simple questions: 
1. how can I see the current installed version of navcontainerhelper?
2. do I need to remove older versions of navcontainerhelper prior or after installing latest version and if yes how do I do that?
3. In Powershell ISE I see NavContainerHelper only once but every cmdlet several times. Probably one for every time I installed the latest version. How can I get rid of these duplicates?

![image](https://user-images.githubusercontent.com/16108697/51735012-7f99c080-2086-11e9-8597-de213c6a3e8e.png)

**Comment by freddydk** [comment]
Typically, I update a module using
update-module navcontainerhelper -force

what does get-module return?
you can probably use uninstall-module to uninstall the modules already there.

**Comment by TheovdVen** [comment]
I did it with install-module, that explains it.

Because get-module doesn't show the navcontainerhelper and get-module navcontainerhelper didn't show anything I didn't expect that I could uninstall the navcontainerhelper with the command uninstall-module. But it installs one version at a time. So I will run it several times and install latest version.
Thanks for your reply Freddy!

![image](https://user-images.githubusercontent.com/16108697/51735708-66920f00-2088-11e9-82ae-20a068a5da15.png)

**Comment by freddydk** [comment]
my bad - get-installedmodule

**Comment by TheovdVen** [comment]
Yep, thats it!
By the way the command update-module did add the duplicates again. Now I simply uninstall the module before I install the latest one.

**Comment by freddydk** [comment]
Update-module followed by restarting powershell should leave you with only one version.
