### ISSUE TITLE
Run-AlValidation Failing and Prompting for Username and Password

### ISSUE THREAD

**Issue by skkulla** [microsoft/navcontainerhelper#3161]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

I am trying to run Run-AlValidation on my app using the below script but it is keep prompting me to enter username and password. If I enter my windows username and pwd it is not accepting or cancel the prompt is not working

A clear and concise description of what the issue is.

**Scripts used to create container and cause the issue**
```
Run-AlValidation `
    -countries @("us", "ca") `
    -apps "C:\Users\SureshKulla\Downloads\Ternpoint Solutions LP_Advanced Direct Posting_1.0.16.0.app" `
    - ValidateNextMajor `
    - ValidateNextMinor
```
WARNING: Parameter ImageName is no longer used in Run-AlValidation, please remove the parameter
WARNING: Parameter LicenseFile is no longer used in Run-AlValidation, please remove the parameter
  _____                               _                
 |  __ \                             | |               
 | |__) |_ _ _ __ __ _ _ __ ___   ___| |_ ___ _ __ ___ 
 |  ___/ _` | '__/ _` | '_ ` _ \ / _ \ __/ _ \ '__/ __|
 | |  | (_| | | | (_| | | | | | |  __/ |_  __/ |  \__ \
 |_|   \__,_|_|  \__,_|_| |_| |_|\___|\__\___|_|  |___/

Container name                  -
Credential                      admin/Zuje3066
MemoryLimit                     8G
validateVersion                 
validateCurrent                 False
validateNextMinor               False
validateNextMajor               False
SasToken                        Not Specified
countries                       us,ca
validateCountries               us,ca
affixes                         
supportedCountries              
ObsoleteTagMinAllowedMajorMinor 
vsixFile                        
Install Apps
- None
Previous Apps
- None
Apps
- C:\Users\SureshKulla\Downloads\Ternpoint Solutions LP_Advanced Direct Posting_1.0.16.0.app
  _____       _                      _                         _   _  __           _       
 |  __ \     | |                    (_)                       | | (_)/ _|         | |      
 | |  | | ___| |_ ___ _ __ _ __ ___  _ _ __   ___    __ _ _ __| |_ _| |_ __ _  ___| |_ ___ 
 | |  | |/ _ \ __/ _ \ '__| '_ ` _ \| | '_ \ / _ \  / _` | '__| __| |  _/ _` |/ __| __/ __|
 | |__| |  __/ |_  __/ |  | | | | | | | | | |  __/ | (_| | |  | |_| | || (_| | (__| |_\__ \
 |_____/ \___|\__\___|_|  |_| |_| |_|_|_| |_|\___|  \__,_|_|   \__|_|_| \__,_|\___|\__|___/
                                                                                           
Found https://bcartifacts.azureedge.net/sandbox/22.4.59114.59801/us
Found https://bcartifacts.azureedge.net/sandbox/22.4.59114.59801/ca
Using https://bcartifacts.azureedge.net/sandbox/22.4.59114.59801/us
  _____       _                      _       _                   _                           _                       
 |  __ \     | |                    (_)     (_)                 | |                         | |                      
 | |  | | ___| |_ ___ _ __ _ __ ___  _ _ __  _ _ __   __ _    __| | ___ _ __   ___ _ __   __| | ___ _ __   ___ _   _ 
 | |  | |/ _ \ __/ _ \ '__| '_ ` _ \| | '_ \| | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '_ \ / _` |/ _ \ '_ \ / __| | | |
 | |__| |  __/ |_  __/ |  | | | | | | | | | | | | | | (_| | | (_| |  __/ |_) |  __/ | | | (_| |  __/ | | | (__| |_| |
 |_____/ \___|\__\___|_|  |_| |_| |_|_|_| |_|_|_| |_|\__, |  \__,_|\___| .__/ \___|_| |_|\__,_|\___|_| |_|\___|\__, |
                                                      __/ |            | |                                      __/ |
                                                     |___/             |_|                                     |___/ 
Extracting C:\ProgramData\BcContainerHelper\f24ae246-9489-4d6e-ad65-193c2844d831\Ternpoint Solutions LP_Advanced Direct Posting_1.0.16.0.app
Validating against Current Version (22.4)
Additionally validating against application dependency (20.0)

  _____       _ _ _                                          _        _                            
 |  __ \     | | (_)                                        (_)      (_)                           
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___ 
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |     
                          |___/   |___/                                                 |___/      

Pulling mcr.microsoft.com/businesscentral:10.0.20348.1906-filesonly

Pulling generic image took 3 seconds

   _____                _   _                               _        _                 
  / ____|              | | (_)                             | |      (_)                
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                     __/ |                                             
                                    |___/                                              

Creating container for country us
New-BcContainer Telemetry Correlation Id: 67da229e-2f6b-43dd-a47f-3ac790114e2c
Unexpected error while validating app. Error is: Container name should start with a letter (a-z)
at Check-BcContainerName, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\HelperFunctions.ps1: line 293
at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\ContainerHandling\New-NavContainer.ps1: line 351
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 320
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 466
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 445
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 429
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 393
at Run-AlValidation, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 391
at <ScriptBlock>, C:\Scripts\RunValidation.ps1: line 1

  _____                           _                _____            _        _                 
 |  __ \                         (_)              / ____|          | |      (_)                
 | |__) |___ _ __ ___   _____   ___ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | |____ (_) | | | | |_ (_| | | | | |  __/ |   
 |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                           __/ |                                               
                                          |___/                                                

Removing Desktop shortcuts

Removing container took 0 seconds
  _____       _                      _                         _   _  __           _       
 |  __ \     | |                    (_)                       | | (_)/ _|         | |      
 | |  | | ___| |_ ___ _ __ _ __ ___  _ _ __   ___    __ _ _ __| |_ _| |_ __ _  ___| |_ ___ 
 | |  | |/ _ \ __/ _ \ '__| '_ ` _ \| | '_ \ / _ \  / _` | '__| __| |  _/ _` |/ __| __/ __|
 | |__| |  __/ |_  __/ |  | | | | | | | | | |  __/ | (_| | |  | |_| | || (_| | (__| |_\__ \
 |_____/ \___|\__\___|_|  |_| |_| |_|_|_| |_|\___|  \__,_|_|   \__|_|_| \__,_|\___|\__|___/
                                                                                           
Found https://bcartifacts.azureedge.net/sandbox/20.0.37253.50766/us
Found https://bcartifacts.azureedge.net/sandbox/20.0.37253.50766/ca
Using https://bcartifacts.azureedge.net/sandbox/20.0.37253.50766/us

   _____                _   _                               _        _                 
  / ____|              | | (_)                             | |      (_)                
 | |     _ __ ___  __ _| |_ _ _ __   __ _    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 | |    | '__/ _ \/ _` | __| | '_ \ / _` |  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | |____| | |  __/ (_| | |_| | | | | (_| | | (__ (_) | | | | |_ (_| | | | | |  __/ |   
  \_____|_|  \___|\__,_|\__|_|_| |_|\__, |  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                     __/ |                                             
                                    |___/                                              

Creating container for country us
New-BcContainer Telemetry Correlation Id: a8a035bb-7b81-4893-917f-5b14ec9fc495
Unexpected error while validating app. Error is: Container name should start with a letter (a-z)
at Check-BcContainerName, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\HelperFunctions.ps1: line 293
at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\ContainerHandling\New-NavContainer.ps1: line 351
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 320
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 466
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 445
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 429
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 393
at Run-AlValidation, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.4\AppHandling\Run-AlValidation.ps1: line 391
at <ScriptBlock>, C:\Scripts\RunValidation.ps1: line 1

  _____                           _                _____            _        _                 
 |  __ \                         (_)              / ____|          | |      (_)                
 | |__) |___ _ __ ___   _____   ___ _ __   __ _  | |     ___  _ __ | |_ __ _ _ _ __   ___ _ __ 
 |  _  // _ \ '_ ` _ \ / _ \ \ / / | '_ \ / _` | | |    / _ \| '_ \| __/ _` | | '_ \ / _ \ '__|
 | | \ \  __/ | | | | | (_) \ V /| | | | | (_| | | |____ (_) | | | | |_ (_| | | | | |  __/ |   
 |_|  \_\___|_| |_| |_|\___/ \_/ |_|_| |_|\__, |  \_____\___/|_| |_|\__\__,_|_|_| |_|\___|_|   
                                           __/ |                                               
                                          |___/                                                

Removing Desktop shortcuts

Removing container took 0 seconds

AL Validation finished in 3 seconds
 __      __   _ _     _       _   _               _____                _ _       
 \ \    / /  | (_)   | |     | | (_)             |  __ \              | | |      
  \ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__) |___ ___ _   _| | |_ ___ 
   \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  _  // _ \ __| | | | | __/ __|
    \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | \ \  __\__ \ |_| | | |_\__ \
     \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \_\___|___/\__,_|_|\__|___/

Unexpected error while validating app. Error is: Container name should start with a letter (a-z)
Unexpected error while validating app. Error is: Container name should start with a letter (a-z)
  _____                          ___      __   _ _     _       _   _               ______    _ _                
 |  __ \                   /\   | \ \    / /  | (_)   | |     | | (_)             |  ____|  (_) |               
 | |__) |   _ _ __ ______ /  \  | |\ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__ __ _ _| |_   _ _ __ ___ 
 |  _  / | | | '_ \______/ /\ \ | | \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  __/ _` | | | | | | '__/ _ \
 | | \ \ |_| | | | |    / ____ \| |  \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | | (_| | | | |_| | | |  __/
 |_|  \_\__,_|_| |_|   /_/    \_\_|   \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \__,_|_|_|\__,_|_|  \___|

Unexpected error while validating app. Error is: Container name should start with a letter (a-z)
Unexpected error while validating app. Error is: Container name should start with a letter (a-z)

NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 11 Enterprise -22621
Docker Client Version is 4.20.1 (110738)

.

**Comment by skkulla** [comment]
![WindowsPrompt](https://github.com/microsoft/navcontainerhelper/assets/10641123/06667d17-47fb-4c3c-bedb-fb0b62c14118)

**Comment by freddydk** [comment]
There shouldn't be a space between the - and validatenextmajor in PowerShell

**Comment by skkulla** [comment]
Thank you Freddy that solved the issue but my app keep failing during app source submission, and looks like it is failing only for a specific version 22.4 and when i ran that query locally I am getting this error. This is just an update and never got any errors before in the previous versions.

I do have AppSourceCopJson with those properties.

{
    "mandatoryAffixes": [
        "TPS"
    ],
    "mandatoryPrefix": "TPS",
    "supportedCountries": [
        "US",
        "CA"
    ]
}

my script

Run-AlValidation `
    -countries @("us", "ca") `
    -apps "C:\Users\SureshKulla\Downloads\Ternpoint Solutions LP_Advanced Direct Posting_1.0.16.0.app" `
    -validateVersion "22.4"



\ \    / /  | (_)   | |     | | (_)             |  __ \              | | |      
  \ \  / /_ _| |_  __| | __ _| |_ _  ___  _ __   | |__) |___ ___ _   _| | |_ ___ 
   \ \/ / _` | | |/ _` |/ _` | __| |/ _ \| '_ \  |  _  // _ \ __| | | | | __/ __|
    \  / (_| | | | (_| | (_| | |_| | (_) | | | | | | \ \  __\__ \ |_| | | |_\__ \
     \/ \__,_|_|_|\__,_|\__,_|\__|_|\___/|_| |_| |_|  \_\___|___/\__,_|_|\__|___/

2 errors found in Ternpoint Solutions LP_Advanced Direct Posting_1.0.16.0.app on https://bcartifacts.azureedge.n
et/sandbox/22.4.59114.59801/us:
AppSourceCop.json(1,1): error AS0054: The AppSourceCop configuration must specify one of the following propertie
s: 'mandatorySuffix', 'mandatoryPrefix', or 'mandatoryAffixes'
App generation failed with exit code 1

2 errors found in Ternpoint Solutions LP_Advanced Direct Posting_1.0.16.0.app on https://bcartifacts.azureedge.n
et/sandbox/22.4.59114.59801/ca:
AppSourceCop.json(1,1): error AS0054: The AppSourceCop configuration must specify one of the following propertie
s: 'mandatorySuffix', 'mandatoryPrefix', or 'mandatoryAffixes'
App generation failed with exit code 1

**Comment by freddydk** [comment]
Run-AlValidation has a parameter called mandatoryAffixes - it will create the appsourcecop.json itself - it will not re-use what you have created.

**Comment by skkulla** [comment]
Freddy Thank I have used affixes parameter locally to get rid of that error and Run-AlValidation is success locally but it keeps failing on the app source with event ID LC0035 and this is happening for every other app. Nothing changed in terms of availability.

_The validation of the submission failed for 2 out of 33 tasks._

Please let me know if you want me to send the app I am trying to upload.

**Comment by freddydk** [comment]
If you remove -validateNextMajor and -validateNextMinor - it validates against the same versions as the online validation - maybe you will get an answer there.
Else, please use telemetry to find out what lies behind this.

**Comment by freddydk** [comment]
The information in telemetry contains everything, but it might be hard to find the right records.
Maybe download the ISV PowerBI app - that might be able to show you the info a little easier.

**Comment by skkulla** [comment]
I was able to find the issue in the Telemetry using KQL, it has something to do with breaking changes. Thanks for the help.
