### ISSUE TITLE
Error in Downloading Signing Tools when running Sign-BcContainerApp

### ISSUE THREAD

**Issue by FBakkensen** [microsoft/navcontainerhelper#3162]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I want to sign an app, I'm running docker desktop on Windows 11. The PC is fully updated

**Scripts used to create container and cause the issue**
```
Sign-BcContainerApp -containerName bcserver -appFile "C:\ProgramData\BcContainerHelper\Extensions\bcserver\my\9altitudes_9A Document Management_22.23.4.2.app" -pfxFile "C:\Users\flemm\AL\9altitudes.pfx" -pfxPassword $pass
```

**Full output of scripts**
```
Copying certificate file to container
Downloading Signing Tools
Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out."

Container Free Physical Memory: 11.6Gb

Services in container bcserver:
- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running

Sign-BcContainerApp Telemetry Correlation Id: 27d2304b-2152-4755-89f5-526c9b716554
Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out."
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\5.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1
:285 char:25
+                         throw $errorMessage
+                         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Exception calli...has timed out.":String) [], RuntimeException
    + FullyQualifiedErrorId : Exception calling "DownloadFile" with "2" argument(s): "The operation has timed out."

```

**Additional context**
- It does happen all the time, and I have the issue on several diffent BC versions, BC14, BC, 18, BC22
- Yes it used to work.
- It might be related to some First run of IE, which i can't do on a headless docker container.

**Comment by freddydk** [comment]
Sorry for the late response.
Did you manage to make this work?
I do have some workflows using Sign-BcContainerApp that still runs flawlessly - and they all run use containers with this, so I expect this to be a problem on your machine.
Maybe the container doesn't have access to DNS - the output from the container creation would tell me that.

In that case, you could try adding -dns "hostDNS" to your new-bccontainer command.
