### ISSUE TITLE
An object or column name is missing or empty

### ISSUE THREAD

**Issue by TheovdVen** [Microsoft/navcontainerhelper#317]
I am using Docker Desktop version 18.09.1 on Windows 10. See attached files.
The script I use to create my container is also attached in the files.

If I run this on my system I get an error (which you can see in the log.txt attached):
_**An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 155
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1**_

If I remove the option useBestContainerOS the container gets created without any problem.
I also have some other containers created with this option and no problems occur when creating these containers.

I also tried it with this option added and use hyperv isolation instead of process isolation but that didn't make a difference.

Any ideas how to solve this?

[log.txt](https://github.com/Microsoft/navcontainerhelper/files/2795317/log.txt)
[docker-version.txt](https://github.com/Microsoft/navcontainerhelper/files/2795318/docker-version.txt)
[inspect.txt](https://github.com/Microsoft/navcontainerhelper/files/2795319/inspect.txt)
[create container test v2.txt](https://github.com/Microsoft/navcontainerhelper/files/2795334/create.container.test.v2.txt)

**Comment by freddydk** [comment]
please remove the 2016 versions of your containers and try again

docker images

and then

docker rmi microsoft/dynamics-nav:2018-cu8-nl

you can also append -ltsc2019 to force 1809 images:

microsoft/dynamics-nav:2018-cu8-nl-ltsc2019

The problem here is that it will try to re-platform your 2016 images, I will change this logic going forward.

**Comment by TheovdVen** [comment]
will try that and let you know the result, thanks again!

**Comment by TheovdVen** [comment]
That worked! Hero!
