### ISSUE TITLE
Add/remove user permission set

### ISSUE THREAD

**Issue by larswestman** [Microsoft/navcontainerhelper#318]
When creating a user with New-NavContainerNavUser you can specify a permission set for the user. But what if I want more than one permission set added to the user? Wouldn't it be in place with two new functions such as:
- New-NavContainerUserPermissionSet
- Remove-NavContainerUserPermissionSet
The "remove" might not be needed, but the "new" would be nice.

**Comment by freddydk** [comment]
In the next version you will be able to do:
Invoke-NavContainerScript -containername test -scriptblock {
    New-NavServerUserPermissionSet - or any other cmdlet really
}

**Comment by larswestman** [comment]
Even better. Thanks!
