### ISSUE TITLE
SignTool stop working in  23.0.12034.12580

### ISSUE THREAD

**Issue by kguldbaek** [microsoft/navcontainerhelper#3190]
Since this morning, our pipelines that build against the preview BC23 images have been receiving this error:
**SignTool Error: This file format cannot be signed because it is not recognized.**

The error began occurring after we started using artifact 23.0.12034.12580. When using the previous version (23.0.12034.12546), everything worked fine.

**Comment by freddydk** [comment]
I can repro that - will investigate

**Comment by freddydk** [comment]
The reason for this is that the NavSip.dll in the new version have these dependencies:
    bcrypt.dll
    CRYPT32.dll
    KERNEL32.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll

In the old version, it was:
    bcrypt.dll
    CRYPT32.dll
    KERNEL32.dll
    MSVCR120.dll

I guess some of these are not installed by default in the container, will check this out.

**Comment by Koubek** [comment]
I would like to report the same problems on BC22.5 (sandbox artifacts for `22.5.59966.60701` were still okay but `22.5.59966.60734` is failing).

**Comment by freddydk** [comment]
With the latest ContainerHelper preview - that should be fixed (it JIT installs the dependency)

**Comment by BW-PA** [comment]
Can confirm it is fixed.  Ran a couple of pipelines this afternoon using the "preview" version of bccontainerhelper and they completed successfully.

**Comment by freddydk** [comment]
Will release to prod today or tomorrow

**Comment by petegonnella** [comment]
is this also causing prevalidation to flag app files to be unsigned when they are signed?

running Get-AuthenticodeSignature on host machine or container built with 22.5.59966.60728 or below returns status valid

**Comment by kguldbaek** [comment]
I can also confirm this is fixed. 
@freddydk Thank you for the fast assistance 👍

**Comment by freddydk** [comment]
Install new dependencies needed for navsip.dll on the fly:
https://github.com/microsoft/navcontainerhelper/commit/64b064f57fe89eba2b30ef02efb06402656f9f55

**Comment by freddydk** [comment]
> is this also causing prevalidation to flag app files to be unsigned when they are signed?
> 
> running Get-AuthenticodeSignature on host machine or container built with 22.5.59966.60728 or below returns status valid

Yes - it is the navsip.dll that requires this prereq: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by larswestman** [comment]
CI/CD working just fine again :-)

**Comment by freddydk** [comment]
> > > is this also causing prevalidation to flag app files to be unsigned when they are signed?
> > > running Get-AuthenticodeSignature on host machine or container built with 22.5.59966.60728 or below returns status valid
> > 
> > 
> > Yes - it is the navsip.dll that requires this prereq: https://aka.ms/vs/17/release/vc_redist.x64.exe
> 
> Is this part still to be resolved? Prevalidation still failing due to this.

What do you mean by prevalidation?

**Comment by petegonnella** [comment]
sorry, Run-AlValidation

**Comment by freddydk** [comment]
Got it - I guess one more fix is needed for this.

**Comment by petegonnella** [comment]
> Got it - I guess one more fix is needed for this.
this is now works in preview build

**Comment by freddydk** [comment]
Shipped in 6.0.5
