### ISSUE TITLE
Access to Service Tier Settings

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/navcontainerhelper#32]
Hi,
this might be a somewhat ...uninformed... question - so please forgive my lack of experience using PowerShell:

Is there any way to access the settings of the Service Tier inside a container? What I want to do is primarily activate th In-Client Designer and maybe also play around with other settings.

**Comment by freddydk** [comment]
Reading the containers customsettings.config from PowerShell on the docker host can be done with:

$config = docker exec -it test powershell "Get-Content -Path 'C:\Program Files\Microsoft Dynamics NAV\*\Service\CustomSettings.config'"

or using the navcontainerhelper

$session = Get-NavContainerSession -containerName test
$config = Invoke-Command -Session $session -ScriptBlock { 
    Get-Content -Path 'C:\Program Files\Microsoft Dynamics NAV\*\Service\CustomSettings.config' | Out-String
}

**Comment by RafaelKoch** [comment]
Many thanks!
W1 designer works as expected.
As for fiddling with ST Settings: In my case where I do not even want to script things I found that I can also use the shortcut to the container PowerShell You conveniently provide and then use the NAV cmdlets. In this case 
```powershell
Get-NAVServerConfiguration
```
to inspect and for example 
```powershell
Set-NAVServerConfiguration -ServerInstance NAV -KeyName EnableTaskScheduler -KeyValue true
``` 
to change.
