### ISSUE TITLE
AppSource/New-AppSourceSubmission.ps1

### ISSUE THREAD

**Issue by leegeurts** [microsoft/navcontainerhelper#3204]
When the Appsource Submission fails the scripts does not give an error. It only shows a line in the console that there was a failure.

![image](https://github.com/microsoft/navcontainerhelper/assets/44159740/1b3e0b1c-f89d-4921-9076-65da03fdb3fb)

Is it possible to add an error when then submission fails. 
Or is there another way to catch this failure in our pipeline? 

![image](https://github.com/microsoft/navcontainerhelper/assets/44159740/70197146-cc8c-4ec6-adca-be419969c4cb)

**Comment by leegeurts** [comment]
I found how to check it. Sorry for bothering you :)

**Comment by freddydk** [comment]
I cannot even remember how - if you could add your solution (for other people to find) and close the issue?

**Comment by leegeurts** [comment]
# new app version submission
  $submission = New-AppSourceSubmission -authContext $authContext `
                          -productId $product.Id `
                          -appFile $mainAppFilePath `
                          -libraryAppFiles $libraryFiles `
                          -autoPromote `
                          -doNotWait

  $submissionID = $submission.id

  if ($submissionID.substate -eq "Failed") {
    Write-Host  "##vso[task.LogIssue type=error;]Appsource submission $submission.id failed"
    Write-Error "Appsource submission $submission.id failed"
  }

**Comment by freddydk** [comment]
This will tell you if the submission failed - not if the validation failed - right?
