### ISSUE TITLE
Parallel Compiling

### ISSUE THREAD

**Issue by eclipses24** [Microsoft/navcontainerhelper#322]
I was thinking if could be interesting implement the parallel compiling to the Compile-ObjectsInNavContainer function. I'm not sure if it will work in the NAV Containers.

Reference:
https://blogs.msdn.microsoft.com/nav/2014/11/27/how-to-compile-a-database-twice-as-fast-or-faster/

**Comment by freddydk** [comment]
In the next navcontainerhelper - you can invoke:

invoke-scriptinnavcontainer -containername test -scriptblock {
   #write your code here
}

and then you will be able to do this as described.
I am not going to build this in, as this will require quite a lot of testing and is focused on C/AL.
The aim is not to be better at compiling C/AL - but AL - so if I were to find something that could make AL compiling faster - I am all over it:-)

**Comment by eclipses24** [comment]
Thanks. 

You are lucky that you can focus only on AL but as a partner unfortunately I will work with C/AL and AL for few years. 

When is planned to be release the new version?

**Comment by eclipses24** [comment]
Thanks for your work and support.
