### ISSUE TITLE
Sign in does not work after creating a container with an external database - No user in external database

### ISSUE THREAD

**Issue by Silentapproach** [microsoft/navcontainerhelper#3223]
Hi Freddy, 

just a quick question about the New-BcContainer command. We frequently create container with an external database. I recently stumped upon a piece of code in our repository that adds a BcUser after the container is initially created. 

I asked myself if it is possible to remove that code. After a few tests I figured that no user is present in the container after its initial creation by just using the New-BcContainer command with an external database. Is that by design or are we missing something?

We provide the databaseName, server, credential, in some cases the instance. Shouldn't the BcContainerHelper add a user to the database while creating the container? We use NavUserPassword as the auth method.

**Comment by freddydk** [comment]
If you use an external database, I assume that users and everything else is setup in that - I do not mess with the database at all.
By design - I think I can do more harm than good by trying to add users or other things.

**Comment by Silentapproach** [comment]
Ok, then we need to recheck our code at this point.
