### ISSUE TITLE
Add SynchronizeSchemaChanges parameter to Compile-ObjectsInNavContainer.ps1

### ISSUE THREAD

**Issue by eclipses24** [Microsoft/navcontainerhelper#323]
Hi,

I'd like if could be added SynchronizeSchemaChanges parameter to Compile-ObjectsInNavContainer.ps1.
Right now it is setup as Force without option to change it, if this become a parameter it could be set when calling the function.

It could be usefull also have a separated new function for SynchronizeSchemaChanges so that it could be a different step in the CI build.

**Comment by eclipses24** [comment]
Hi, 

I saw that you added the SynchronizeSchemaChanges parameter to Compile-ObjectsInNavContainer.ps1

Are you going to create a new function for SynchronizeSchemaChanges as well? 

I know how to do it:  
Invoke-ScriptInNavContainer -containerName $containerName -ScriptBlock { 
    Sync-NAVTenant -ServerInstance NAV -Mode Sync                                      
}

**Comment by freddydk** [comment]
Shipped in 0.5.0.0
I will create less new function wrappers when they are very easy
Thanks for the suggestions.
