### ISSUE TITLE
Restore online Business central database locally

### ISSUE THREAD

**Issue by Pratibha2176** [microsoft/navcontainerhelper#3230]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I am trying to restore BACPAC file from BC Online to a BC On-Premise and local SQL Server. I've used Freddy's script as a starting point for my script:

https://freddysblog.com/2021/03/02/restoring-your-online-business-central-database-locally/

I have the bacpac file restore on my computer. The docker container is created. Now I am running the script to restore the database in sql and then make a connection with docker. 

I am following step by step of freddy's blog.

**Scripts used to create container and cause the issue**
```
New-AzKeyVault `
    -ResourceGroupName "notmentioninghere" `
    -Name "notmentioninghere" `
    -Location "West Europe"

Set-AzKeyVaultSecret `
    -VaultName "notmentioninghere" `
    -Name "Password" `
    -SecretValue (ConvertTo-SecureString 'P@ssw0rd' -AsPlainText -Force)

if (!($licenseFileSecret)) {
    Write-Host -ForegroundColor Yellow "Reading Key Vault"
    Get-AzKeyVaultSecret $vaultName  | % {
        Write-Host $_.Name
        Set-Variable `
            -Name "$($_.Name)Secret" `
            -Value (Get-AzKeyVaultSecret $vaultName -Name $_.Name)
    }
}

Write-Host -ForegroundColor Yellow "SaaS Settings"
$environment = "Production"
$refreshToken = $BcSaasRefreshTokenSecret.SecretValue | Get-PlainText
$authContext = New-BcAuthContext -refreshToken $refreshToken
$bcEnvironment = Get-BcEnvironments `
    -bcAuthContext $authContext | Where-Object {
        $_.Name -eq $environment }
$baseApp = Get-BcPublishedApps `
    -bcAuthContext $authContext `
    -environment $environment | Where-Object { 
        $_.Name -eq "Base Application" }
$artifactUrl = Get-BCArtifactUrl `
    -country $bcEnvironment.countryCode `
    -version $baseApp.Version `
    -select Closest

```
**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/143513777/ea2e0eb7-1f59-475a-81ca-82a01be3eb75)

**Comment by freddydk** [comment]
You didn't declare the $vaultname variable - you should set that to the name of your KeyVault.

**Comment by Pratibha2176** [comment]
I did set the vaultname and is the name of keyvault, but not mentioning here openly.

**Comment by freddydk** [comment]
Correct - that part was only there to show how I would read secrets from a keyvault in order to not have hardcoded secrets in code - you are free to do this in a different way (i.e. temporarily have secrets in code).
