### ISSUE TITLE
Get-PlainText : Cannot bind argument to parameter 'SecureString' because it is null. Error

### ISSUE THREAD

**Issue by Pratibha2176** [microsoft/navcontainerhelper#3231]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Hi Freddy,

Please don't close this issue until the whole script is up and running.
I am following step by step procedure to understand but now stuck on this step.

**Scripts used to create container and cause the issue**
```
Write-Host -ForegroundColor Yellow "SaaS Settings"
$environment = "PROD"
$refreshToken = $BcSaasRefreshTokenSecret.SecretValue | Get-PlainText
$authContext = New-BcAuthContext -refreshToken $refreshToken
$bcEnvironment = Get-BcEnvironments `
    -bcAuthContext $authContext | Where-Object {
        $_.Name -eq $environment }
$baseApp = Get-BcPublishedApps `
    -bcAuthContext $authContext `
    -environment $environment | Where-Object { 
        $_.Name -eq "Base Application" }
$artifactUrl = Get-BCArtifactUrl `
    -country $bcEnvironment.countryCode `
    -version $baseApp.Version `
    -select Closest


**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/143513777/0059ebc0-dbeb-4f04-a1c1-7ea77675cca9)

**Comment by freddydk** [comment]
There is only one line, where something is piped into Get-PlainText.
I cannot see the screenshot, but that error means that $BcSaasRefreshTokenSecret.SecretValue is null

These errors are simple PowerShell errors - not anything to do with the blog post or the functionality at all.
