### ISSUE TITLE
Question: DNS resolving

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#3233]
This is one from the dark corners of the windows/container networking universe:

HI! 

Thanks to twist on how we work these days, I sit right now in my  small office at home. Besides that fact that it is small, it works pretty well. This also counts for the fact that I have decent speed and internet here! But not enough, I also work for a company that using modern stuff like AAD and SSO ...but is also a bit paranoid ...with no admin rights, firewalls and thinks....anyway :)

So today a I ended up in a riddle, that I wanted to address here, as it seems to be a bc container thing. Once I connect via VPN a BC container is no longer able to resolve names... a normal windows:core does the job just fine. ( how I found out: I had SSO enabled in the container and get a Error 500 on the UI as it can not resolve the name www.microsoft.com).

"Ha! add the dns parameter dummy!" Oh I did and --- it still does not work.

So what happens in the BC container such that a fundamental network component stops working while it still does on a regular windows container? disconnect the VPN and also the BC container gets happy again.
Pinging the IPs is all still working - If I am not mistaken also the VPN is not tunneling the complete traffic....so connectivity as such is not the issue...just the DNS portion won't work... :) 

Host is a Win10 - I don't expect a "solution" here (I am more as aware that it is a local network topic) - but maybe just some more insight into why it doesn't do what its really dump docker run --rm -it mcr.microsoft.com/windows/servercore:10.0.19041.1415 container twin handles without any issues...?! (for test I just curl www.microsoft.com)

And I am sorry for not bringing this in an awesome story with spaceships, explosion and drama and fantastic music ... you know, it's Friday - will try better again next time ;)

**Comment by freddydk** [comment]
Please try to use:
```
-dns "hostDNS"
```

this is a "magic" value, which makes your container use the hosts dns server setting.

**Comment by KristofKlein** [comment]
oki doki, I will try - still it leaves me a bit puzzled on the fact what is the bc container adding to the soup such that this just stops working, while a container with the "same" windows basement survives such things just without any damage :D

**Comment by freddydk** [comment]
Not sure.
I have the same problem when connected to the Microsoft Corporate Network.

**Comment by KristofKlein** [comment]
so not on purpose :) that is at least good to know :D 

Well, I gave -dns "hostDNS" a spin - and that is not working :(  

So I tried to just use a baremetal bc image and a simple docker run (no DNS in this at all) ,
`docker run --rm -it -p 1433:1433/tcp -p 443:443/tcp -p 7045:7045/tcp -p 7046:7046/tcp -p 7047:7047/tcp -p 7048:7048/tcp -p 7049:7049/tcp -p 7083:7083/tcp -p 80:80/tcp -p 8080:8080/tcp mcr.microsoft.com/businesscentral:10.0.19041.1415 powershell`

hyperV Isolation - can DNS
Process Isolation - can not DNS ... 

So back to this again ... what isolation should you chose. I really do prefer process, while hyperV has at the end of the day more pros as cons ....

Naah - let's see how far I get without VPN ... or I add the needed hosts to the container manually.. :D

**Comment by KristofKlein** [comment]
uhh maybe this will help me #1971
