### ISSUE TITLE
Load BACPAC Error

### ISSUE THREAD

**Issue by floyd-chan** [microsoft/navcontainerhelper#3244]
I am trying to restore BACPAC file from BC Online to BC On-Premise and local SQL Server. 

I've used this script as a starting point for my script:
https://freddysblog.com/2021/03/02/restoring-your-online-business-central-database-locally/

I've managed to run my script to the point where the BC On-Premise container is created and is successfully connected to the multi-tenant CRONUS database on the local SQL Server.

Where it fails is in the next step: loading the BACPAC file.

I realize this is not an issue with bccontainerhelper and more likely related to the DAC framework, but maybe you know the solution to this one?

I've simplified my script to focus on the error:

#-[ VARIABLES ]-----------------------
$saasEnvironmentName = "Academy"
$containerName = 'saas23'

$dbServer = '172.16.90.60'
$dbInstance = ''
$dbSaName = 'sa' 
$dbSaPassword = ConvertTo-SecureString 'XXXX' -AsPlainText -Force

#-[ PREREQUISITES ]-----------------------
$dacdll = Get-Item "C:\Program Files\Microsoft SQL Server\160\DAC\bin\Microsoft.SqlServer.Dac.dll"
if (-not($dacdll)) {
    throw "DAC Framework is not installed"
}
Add-Type -path $dacdll.FullName

Import-Module Az
Import-Module -Name bccontainerhelper

#-[ AUTHENTICATE ]-----------------------
#-[ Get BC Online Metadata ]-----------------------
#-[ Get BC Artifact URL ]-----------------------
#-[ Backup and Download BACPAC ]-----------------------
#-[ Get BC License ]-----------------------
#-[ Remove Multi-Tenant BC Container ]-----------------------
#-[ Create Multi-Tenant BC Container ]-----------------------
$dbCredential = New-Object pscredential `
    -ArgumentList $dbSaName, $dbSaPassword

$databaseParams = @{
    "databaseServer" = $dbServer
    "databaseInstance" = $dbInstance
    "databasePrefix" = "$($containerName)-"
    "databaseName" = "CRONUS"
    "databaseCredential" = $dbCredential
    "multitenant" = $true
}

#-[ Restore BACPAC file ]-----------------------
$bacpacFilepath = 'C\!!_TEMP\temp.bacpac'

$tenantId = $saasEnvironmentName
$dbName = "$($databaseParams.databasePrefix)$tenantId"
$conn = @(
    "Data Source=localhost"
    "Initial Catalog=master"
    "Connection Timeout=0"
    "User Id=$($dbCredential.UserName)"
    "Password=$($dbCredential.Password|Get-PlainText)"
) -join ";"

Write-Host ('')
Write-Host "Restoring BACPAC from $bacpacFilepath to $dbName" -ForegroundColor Yellow

$AppimportBac = New-Object Microsoft.SqlServer.Dac.DacServices $conn
$ApploadBac = [Microsoft.SqlServer.Dac.BacPackage]::Load($bacpacFilepath)
$AppimportBac.ImportBacpac($ApploadBac, $dbName)

The output:

Restoring BACPAC from C\!!_TEMP\temp.bacpac to saas23-Academy
Exception calling "Load" with "1" argument(s): "Could not load package from 'C\!!_TEMP\temp.bacpac'."
At W:\_REPOS\Qixas-Tools\Qixas Scripts\_Departments\Academy\Saas2Docker\2-Qixas Version\WIP\temp.ps1:56 char:1
+ $ApploadBac = [Microsoft.SqlServer.Dac.BacPackage]::Load($bacpacFilep ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DacServicesException
 
Exception calling "ImportBacpac" with "2" argument(s): "Value cannot be null.
Parameter name: package"
At W:\_REPOS\Qixas-Tools\Qixas Scripts\_Departments\Academy\Saas2Docker\2-Qixas Version\WIP\temp.ps1:57 char:1
+ $AppimportBac.ImportBacpac($ApploadBac, $dbName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException

**Comment by floyd-chan** [comment]
I forgot to mention that the BACPAC file appears to be fine

**Comment by floyd-chan** [comment]
Typo!

The error is here:
$bacpacFilepath = 'C!!_TEMP\temp.bacpac'

Should be: 
$bacpacFilepath = 'C:\!!_TEMP\temp.bacpac'

Now I get past the "load" command, but it is now failing at the ImportBacpac line. 
Here is the revised output:

Restoring BACPAC from C:\!!_TEMP\temp.bacpac to saas23-Academy
Exception calling "ImportBacpac" with "2" argument(s): "Could not import package."
At W:\_REPOS\Qixas-Tools\Qixas Scripts\_Departments\Academy\Saas2Docker\2-Qixas Version\WIP\temp.ps1:62 char:1
+ $dacService.ImportBacpac($dacPackage, $dbName)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DacServicesException

**Comment by freddydk** [comment]
Did you try to import the bacpac to the SQL Server manually?
Can you open a prompt inside the container and ping 172.16.90.60 ?
Is that database on the docker host or on a different machine on the network?
If this is on the docker host - you could try host.containerhelper.internal instead of the IP number.
I assume that sa is enabled on that sql instance?

**Comment by floyd-chan** [comment]
Did you try to import the bacpac to the SQL Server manually?
  - Yes, sort of. I ultimately ran into an "out-of-memory" error but it seemed to be working
Can you open a prompt inside the container and ping 172.16.90.60 ?
  - Yes 
Is that database on the docker host or on a different machine on the network?
  - SQL Server is on the Docker host
If this is on the docker host - you could try host.containerhelper.internal instead of the IP number.
  - Yep, just changed this in my script
I assume that sa is enabled on that sql instance?
  - Yes, sa is enabled.

To help home in on my problem, I wrapped my script with a try/catch:

$dacService = New-Object Microsoft.SqlServer.Dac.DacServices $dacConnection
if ($null -eq $dacService)
{
    Write-Host "Could not connect to DAC Service" -ForegroundColor Yellow    
    exit
}
$dacPackage = [Microsoft.SqlServer.Dac.BacPackage]::Load($bacpacFilepath)
try {
    $dacService.ImportBacpac($dacPackage, $dbName)    

    Write-Host ('')
    Write-Host "BACPAC restored to $dbName" -ForegroundColor Yellow
}
catch {
    Write-Output $_.Exception|Format-List -Force
}

The output revealed another hint:

Exception calling "ImportBacpac" with "2" argument(s): "Could not load file or assembly 'System.Resources.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified."

Digging around the internet for this error, I found another script example where there was an explicit load of the DLL:

$dacDll = Get-Item "C:\Program Files\Microsoft SQL Server\160\DAC\bin\Microsoft.SqlServer.Dac.dll"
if (-not($dacDll)) {
    throw "DAC Framework is not installed"
}
Add-Type -path $dacDll.FullName

[System.Reflection.Assembly]::LoadFrom($dacDll) | Out-Null

After making these changes and re-running the script .... my BACPAC restored!

At this point, I'm closing this issue.
