### ISSUE TITLE
BC23.0 Compile Container does not have .netCore DLLs

### ISSUE THREAD

**Issue by TheExample67** [microsoft/navcontainerhelper#3276]
I'm working on getting my solution running on BC23.0 but I keep running into the issue that the compiler shows alot of errors.
After looking a bit further I noticed that the compile Container does not copy out any *.dlls for .NetCore nor AspNetCore.
Am I missing anything?

My best guess is that my Image has the Generic Tag: 1.0.2.14, which I can only find in use with Version 24.
That then results in .NetCore not being installed.

**Scripts used to create container and cause the issue**

      #Creating Container
      $Param = @{
          accept_eula = $true
          accept_outdated = $true
          useSSL = $false
          filesOnly = $true
          includeAL = $true
          memoryLimit = "10G"
          containerName = "$containerName"
          additionalParameters = "--volume $(Split-Path $projectRoot):C:\al --volume $($outPath):$($outPath -replace '\w:\\','C:\') --volume C:\ProgramData\BcContainerHelper:C:\BcContainerHelper"
          imageName = "$imageName"
      }
      New-NavContainer @Param

      #Compiling Apps
      $noWarn = @()
      Get-Content "$PSScriptRoot\nowarn.txt" | ForEach-Object {
          $noWarn += "`"$_`""
      }
      $noWarn = $noWarn -join ","
      Compile-AppInBcContainer -containerName $containerName `
          -appProjectFolder "$projectRoot" `
          -appOutputFolder "$extensiondir" `
          -appSymbolsFolder "$extensiondir" `
          -credential $credential `
          -noWarn $noWarn `
          -GenerateReportLayout "No" `
          -TreatWarningsAsErrors "AL1026" `
          -AzureDevOps `
          -FailOn Error

**Full output of scripts**

Fetching all docker volumes
Using image <myRegistry>/dev:server-23.0-filesonly
Creating Container comp22
Style: onprem
Multitenant: No
Version: 23.0.12034.12841
Platform: 23.0.12831.0
Generic Tag: 1.0.2.14
Container OS Version: 10.0.17763.5122 (ltsc2019)
Host OS Version: 10.0.17763.5122 (ltsc2019)
Using process isolation
Using locale de-CH
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Additional Parameters:
--volume C:\agent_nsys-comp\_work\5\s:C:\al --volume C:\agent_nsys-comp\_work\5\s\bin:C:\agent_nsys-comp\_work\5\s\bin --volume C:\ProgramData\BcContainerHelper:C:\BcContainerHelper
Files in C:\ProgramData\BcContainerHelper\Extensions\comp22\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container comp22 from image s00-ch-nsysreg:443/dev:server-23.0-filesonly
3324539dd2ef818fe00c77b4d35f59fae745e739d18d91b043d00de3213ef5c3
Waiting for container comp22 to be ready
Ready for connections!
Reading CustomSettings.config from comp22
Cleanup old dotnet core assemblies
Creating .net Assembly Reference Folder
Copying DLLs from C:\Program Files\dotnet\Shared to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\230\Service to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Removing dotnet Framework Assemblies
Waiting for container comp22 to be ready
Ready for connections!

NavContainerHelper is version 6.0.3
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter
Docker version 20.10.9, build 591094d
...
```

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/45948912/da43e03f-6282-4c53-9d43-44e7bc94f4fa)


**Additional context**
- does it happen all the time?
   Yes, for BC23, our current verison on BC21.2 is running fine

**Comment by freddydk** [comment]
Please try and remove the -imagename parameter to see whether this is caused by the just-in-time generation of an image?

**Comment by TheExample67** [comment]
Thank you for your response. 
I replaced the imagename with a artifactURL and removed the docker images to make sure it gets pull fresh.
But I'm running still into the same issue. DotNet 6.0.13 Folder is not copied to the assembly path and does not show up in the container.  The other DotNet Folders show up for a moment, and are then properly deleted

### Creating Container
        $Param = @{
            accept_eula = $true
            accept_outdated = $true
            useSSL = $false
            filesOnly = $true
            includeAL = $true
            memoryLimit = "10G"
            containerName = "$containerName"
            additionalParameters = "--volume $(Split-Path $projectRoot):C:\al --volume $($outPath):$($outPath -replace '\w:\\','C:\') --volume C:\ProgramData\BcContainerHelper:C:\BcContainerHelper"
            #imageName = "$imageName"
            artifactUrl = "$(Get-BCArtifactUrl -type OnPrem -country ch -version "$($BcVersion)" -select Latest)"
        }
        New-NavContainer @Param
        #Wait-UntilContainerIsReady -containerName $containerName
        Wait-BcContainerReady -containerName $containerName -timeout (5*60)
###

### Labels from the downloaded image  
  "Labels": {
        "created": "202311291548",
        "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
        "filesonly": "yes",
        "maintainer": "Dynamics SMB",
        "osversion": "10.0.17763.5122",
        "tag": "1.0.2.14"
    },
###


### Log Creation of the compile container

Using image mcr.microsoft.com/businesscentral:10.0.17763.5122-filesonly
Creating Container comp22
Style: onprem
Multitenant: No
Version: 23.0.12034.12841
Platform: 23.0.12831.0
Generic Tag: 1.0.2.14
Container OS Version: 10.0.17763.5122 (ltsc2019)
Host OS Version: 10.0.17763.5122 (ltsc2019)
Using process isolation
Using locale de-CH
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Additional Parameters:
--volume C:\agent_nsys-comp\_work\5\s:C:\al --volume C:\agent_nsys-comp\_work\5\s\bin:C:\agent_nsys-comp\_work\5\s\bin --volume C:\ProgramData\BcContainerHelper:C:\BcContainerHelper
Files in C:\ProgramData\BcContainerHelper\Extensions\comp22\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container comp22 from image mcr.microsoft.com/businesscentral:10.0.17763.5122-filesonly
25cc84ed40c7b29a420661857bb3a0fd5650d1504ecaea046074a83ae39141b1
Waiting for container comp22 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/23.0.12034.12841/ch
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Copying Service Tier Files
c:\dl\onprem\23.0.12034.12841\platform\ServiceTier\Program Files
c:\dl\onprem\23.0.12034.12841\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\23.0.12034.12841\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\23.0.12034.12841\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\onprem\23.0.12034.12841\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\onprem\23.0.12034.12841\platform
c:\dl\onprem\23.0.12034.12841\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\23.0.12034.12841\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\23.0.12034.12841\platform\Test Assemblies
Copying Applications
C:\dl\onprem\23.0.12034.12841\ch\Applications
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 39 seconds
Installation complete
Ready for connections!
Reading CustomSettings.config from comp22
Cleanup old dotnet core assemblies
Creating .net Assembly Reference Folder
Copying DLLs from C:\Program Files\dotnet\Shared to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\230\Service to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Removing dotnet Framework Assemblies
Waiting for container comp22 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/23.0.12034.12841/ch
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Copying Service Tier Files
c:\dl\onprem\23.0.12034.12841\platform\ServiceTier\Program Files
c:\dl\onprem\23.0.12034.12841\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\onprem\23.0.12034.12841\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\onprem\23.0.12034.12841\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\onprem\23.0.12034.12841\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\onprem\23.0.12034.12841\platform
c:\dl\onprem\23.0.12034.12841\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\23.0.12034.12841\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\23.0.12034.12841\platform\Test Assemblies
Copying Applications
C:\dl\onprem\23.0.12034.12841\ch\Applications
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 39 seconds
Installation complete
Ready for connections!

###

**Comment by TheExample67** [comment]
I found a work around, I switched the Compiling Pipelines to full Cronus Container.
Takes a while longer to get ready and compile, but I at least get the necessary DLLs to be able to compile.

**Comment by freddydk** [comment]
Should work with filesonly as well - will use this bug to track this.

**Comment by freddydk** [comment]
Shipped in 6.0.5

**Comment by michvllni** [comment]
@freddydk 6.0.5 of what? Latest Version of ContainerHelper is 4.0.10. Could you please elaborate? This would save me a lot of work. Thanks!

**Comment by freddydk** [comment]
BcContainerHelper is 6.0.5 - 4.0.10 is from January 2023
See https://www.powershellgallery.com/packages/BcContainerHelper/6.0.5

**Comment by michvllni** [comment]
Ah I see. I only checked your github releases, not the module in the gallery
