### ISSUE TITLE
Run-ALCops uses wrong CodeAnalysis dll path, breaking all pipelines

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/navcontainerhelper#3277]
**Describe the issue**
Run-ALCops contains the wrong path to the Microsoft.Dynamics.NAV.CodeAnalysis.dll when running a 24.x container.
This breaks all of our pipelines.

`Add-Type -Path "C:\build\vsix\extension\bin\Microsoft.Dynamics.Nav.CodeAnalysis.dll" | Out-Null`

Keeping it short.

**Comment by MODUSCarstenScholling** [comment]
Fixed locally like this:

```PowerShell
$codeAnalysisDllPath = (Get-ChildItem -Path "C:\build\vsix\extension\bin\" -Filter "Microsoft.Dynamics.Nav.CodeAnalysis.dll" -Recurse | Select-Object -First 1).FullName;
Add-Type -Path $codeAnalysisDllPath | Out-Null;
```

**Comment by freddydk** [comment]
What version of BcContainerHelper are you using here?

**Comment by freddydk** [comment]
Found it - sorry.
