### ISSUE TITLE
Run-AlPipeline Fails while installing App

### ISSUE THREAD

**Issue by skkulla** [microsoft/navcontainerhelper#3282]
Our pipelines started failing for our app source apps for BC23; I have tried with earlier versions where this issue did not occur. The App has an install codeunit which calls another codeunit in the dependency app to create an entry, which worked fine earlier but with the new BC23 I am getting an error saying 

An object with that ID does not exist in the current application compiled with emit version 23033.

I have attached two logs where it is a success and where it fails. 
[NewLogFails.txt](https://github.com/microsoft/navcontainerhelper/files/13779227/NewLogFails.txt)
[OldLogSuccess.txt](https://github.com/microsoft/navcontainerhelper/files/13779228/OldLogSuccess.txt)

**Comment by freddydk** [comment]
The app is built fine and during publish you get an error in a new major, which you don't get in a prior major.
Problems like this is normally not related to BcContainerHelper, but more something you are doing in your app, which is no longer supported .
Have you tried compiling the apps and publishing them to a container yourself?
