### ISSUE TITLE
GenerateErrorLog Causes Pipeline to Fail

### ISSUE THREAD

**Issue by MattTraxinger** [microsoft/navcontainerhelper#3286]
**Describe the issue**
When running a pipeline in Azure DevOps with the generateErrorLog parameter set to true the pipeline fails with this error.

Copying error logs to C:\azagent\A04\_work\144\a\ErrorLogs
Run-AlPipeline Telemetry Correlation Id: 87cd2122-871d-49cb-a28a-3870e22a360e
##[error]ForEach-Object : The variable '$errorLogFiles' cannot be retrieved because it has not been set.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.3\AppHandling\Run-AlPipeline.ps1:1452 char:67
+ ... ders+$sortedTestAppFolders | Select-Object -Unique | ForEach-Object {
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (errorLogFiles:String) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,Microsoft.PowerShell.Commands.ForEachObjectCommand
##[error]PowerShell exited with code '1'.

<img width="406" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/2e481e5b-f7a8-4f50-98ba-1701fe007325">

**Comment by freddydk** [comment]
Shipped in 6.0.5
