### ISSUE TITLE
Sign-NavContainerApp Error

### ISSUE THREAD

**Issue by dpesch84** [microsoft/navcontainerhelper#3288]
Im trying to Codesign an app for the very first time.

I updated BCContainerhelper and used the command flush-containerHelperCache.

Following command is executed to Appsign:
`Sign-NavContainerApp -appFile $MyAppFile -pfxFile $MyPfx -pfxPassword $MyPassword -containerName $MyContainerName`

And i get following Error while it tries to download the signing tools i imagine?:
"DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'bcartifacts.azureedge.net'"

![image](https://github.com/microsoft/navcontainerhelper/assets/108931497/3de2c74d-92c0-4446-92f7-ae660f258919)

Is there anything that i might be doing wrong?

**Comment by dpesch84** [comment]
didn't know there was a new mechanism. finding infos about appsigning seems to tedious. The certificate is stored in an azure key vault? Do you mayb happen to have a link about appsigning with the "new" mechanism?

Many thx in advance

**Comment by freddydk** [comment]
New mechanism is not compatible with containers really.
We are using the AzureSignTool in AL-Go for GitHub - see https://github.com/microsoft/navcontainerhelper/issues/3158
