### ISSUE TITLE
New-NAVWebServerInstance inside the container

### ISSUE THREAD

**Issue by doughton** [Microsoft/navcontainerhelper#331]
I'm looking to have a second webserverinstance inside the container to connect to the single NAV service instance so that we can authenticate with the webclient via navusername as well as AAD.

After getting the container setup and running (multi-tenant with SQL on the host server), I tried the following:

$AADWebServerInstance = "aad"
#Create AAD Web Server instance
New-NAVWebServerInstance  -WebServerInstance $AADWebServerInstance -Server localhost -ServerInstance NAV -SiteDeploymentType subsite  -ClientServicesCredentialType AccessControlService -ClientServicesPort 7046 -DnsIdentity jfbcfall2018.justfooderp.com -PublishFolder "c:\inetpub\wwwroot\$AADWebServerInstance"

This would then be followed with a number of webservice configuration cmdlets to set different parameters.  But the statement doesn't work in the container - have tried running it several ways.  Mostly the errors revolve around file path addressing.  When it does finish with these errors, it does create the aad folder, but then there are a series of folders inside of it that don't appear like they should be there:
ie: 
c:\inetpub\wwwroot\aad\inetpub\wwwroot\aad  

I have run it several ways and get similar issues (including one where it went into a recursion of creating subdirectories on subdirectories)

Here's the first error I get:

copy-Item : Cannot find path 'C:\inetpub\wwwroot\aad' because it does not exist.

At C:\Program Files\Microsoft Dynamics NAV\130\Service\NAVWebClientManagement.psm1:547 char:5
+     Copy-Item $SourcePath -Destination $siteRootFolder -Recurse -Cont ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\inetpub\wwwroot\aad:String) [Copy-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.CopyItemCommand
 
Get-Acl : Cannot find path 'C:\inetpub\wwwroot\aad' because it does not exist.

**Comment by freddydk** [comment]
What container are you running here?
NAV / BC ?

**Comment by freddydk** [comment]
This works in my Business Central  Sandbox container:
```
$WebClientFolder = (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Web Client")[0]
$WebServerInstance = "XXX"
$ServerInstance = "NAV"
$auth = "NavUserPassword"
$clientServicesPort = 7046
$webClientPort = 80
$wwwRootPath = "c:\inetpub\wwwroot"

$certparam = @{}
if ($servicesUseSSL) {
    $certparam += @{CertificateThumbprint = $certificateThumbprint}
}

Write-Host "Creating DotNetCore Web Server Instance"
$publishFolder = "$webClientFolder\WebPublish"

$NAVWebClientManagementModule = "$webClientFolder\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1"
if (!(Test-Path $NAVWebClientManagementModule)) {
    $NAVWebClientManagementModule = "$webClientFolder\Scripts\NAVWebClientManagement.psm1"
}
Import-Module $NAVWebClientManagementModule
New-NAVWebServerInstance -PublishFolder $publishFolder `
                         -WebServerInstance "$WebServerInstance" `
                         -Server "localhost" `
                         -ServerInstance "$ServerInstance" `
                         -ClientServicesCredentialType $Auth `
                         -ClientServicesPort "$clientServicesPort" `
                         -WebSitePort $webClientPort @certparam

$navsettingsFile = Join-Path $wwwRootPath "$WebServerInstance\navsettings.json"
$config = Get-Content $navSettingsFile | ConvertFrom-Json
Add-Member -InputObject $config.NAVWebSettings -NotePropertyName "RequireSSL" -NotePropertyValue "true" -ErrorAction SilentlyContinue
$config.NAVWebSettings.RequireSSL = $false
Add-Member -InputObject $config.NAVWebSettings -NotePropertyName "PersonalizationEnabled" -NotePropertyValue "true" -ErrorAction SilentlyContinue
$config.NAVWebSettings.PersonalizationEnabled = $true
$config.NAVWebSettings.ManagementServicesPort = $ManagementServicesPort

$config | ConvertTo-Json | set-content $navSettingsFile
```
The code above is copy/paste parts of c:\run\SetupWebClient.ps1 (and then set some variables first)

**Comment by doughton** [comment]
I'll give this a shot - I'm running a BC-onprem container.

**Comment by doughton** [comment]
This one finished in my environment, but when I try to run it I get the following error:
[cid:image001.jpg@01D4B8AD.317BB1B0]

I haven’t had much time to look at it yet.

dan

**Comment by freddydk** [comment]
cannot see the image:-(

**Comment by freddydk** [comment]
Please follow my sample above - it includes a new import of a module, which includes a new New-NavWebServerInstance.

**Comment by julicht** [comment]
> Please follow my sample above - it includes a new import of a module, which includes a new New-NavWebServerInstance.

Okay, i tried it. 
Now the second instance has been created. But when i try to connect via Browser the following error occured:
![image](https://user-images.githubusercontent.com/47207078/52049653-a6f10180-254e-11e9-8e98-a86b454f2369.png)



The Default (/nav ) WebserverInstance is working fine.

**Comment by doughton** [comment]
Freddy - the error I end up with when trying to access the newly deployed web site is the same as what Julian put in his last post.

I looked at the event log and this is what is in the application log after trying to access the new web site:

The description for Event ID 1001 from source IIS AspNetCore Module cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Application 'MACHINE/WEBROOT/APPHOST/NAVWEBAPPLICATIONCONTAINER/AAD' started process '10660' successfully and is listening on port '29612'.

**Comment by freddydk** [comment]
If I run this script on my machine:
```
$credential = New-Object PSCredential -ArgumentList 'admin', (ConvertTo-SecureString 'P@ssword1' -AsPlainText -Force)
New-NavContainer -accept_eula -containerName test -imageName mcr.microsoft.com/businesscentral/onprem -auth NavUserPassword -updateHosts -Credential $credential
Invoke-ScriptInNavContainer -containerName test -scriptblock {
    $WebClientFolder = (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Web Client")[0]
    $WebServerInstance = "XXX"
    $ServerInstance = "NAV"
    $auth = "NavUserPassword"
    $clientServicesPort = 7046
    $ManagementServicesPort = 7045
    $webClientPort = 80
    $wwwRootPath = "c:\inetpub\wwwroot"
    
    $certparam = @{}
    $publishFolder = "$webClientFolder\WebPublish"
    
    $NAVWebClientManagementModule = "$webClientFolder\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1"
    if (!(Test-Path $NAVWebClientManagementModule)) {
        $NAVWebClientManagementModule = "$webClientFolder\Scripts\NAVWebClientManagement.psm1"
    }
    Import-Module $NAVWebClientManagementModule
    New-NAVWebServerInstance -PublishFolder $publishFolder `
                             -WebServerInstance "$WebServerInstance" `
                             -Server "localhost" `
                             -ServerInstance "$ServerInstance" `
                             -ClientServicesCredentialType $Auth `
                             -ClientServicesPort "$clientServicesPort" `
                             -WebSitePort $webClientPort @certparam
    
    $navsettingsFile = Join-Path $wwwRootPath "$WebServerInstance\navsettings.json"
    $config = Get-Content $navSettingsFile | ConvertFrom-Json
    Add-Member -InputObject $config.NAVWebSettings -NotePropertyName "RequireSSL" -NotePropertyValue "true" -ErrorAction SilentlyContinue
    $config.NAVWebSettings.RequireSSL = $false
    Add-Member -InputObject $config.NAVWebSettings -NotePropertyName "PersonalizationEnabled" -NotePropertyValue "true" -ErrorAction SilentlyContinue
    $config.NAVWebSettings.PersonalizationEnabled = $true
    $config.NAVWebSettings.ManagementServicesPort = $ManagementServicesPort
}
```
Then I can navigate to http://test/XXX and login and use the product.
Can you validate that this exact script fails on your machine?

**Comment by freddydk** [comment]
You need NavContainerHelper 0.5.0.1 to run this

**Comment by doughton** [comment]
Brilliant - that worked for me!  Thanks Freddy!  Now I just have to reconfigure the script for the actual Access controll stuff, but should be all good now that a second website is operational.
