### ISSUE TITLE
Error using external ruleset with Compile-AppInBcContainer

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/navcontainerhelper#3311]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When I try and use the Compile-AppInBcContainer command with an external ruleset, I get an error. I do not get the same error when I compile my app with the same external ruleset in VS Code.

**Scripts used to create container and cause the issue**

Before running below script:
- Create a valid BC container....version and localization does not matter
- Prepare a valid AL project folder in a folder shared with container
- Upload a valid ruleset to Blob storage

```
Compile-AppInBcContainer -appProjectFolder "C:\ProgramData\BcContainerHelper\Extensions\bc-nextminor\my\app" `
    -containerName bc-nextminor `
    -updateSymbols `
    -enableCodeCop `
    -enableExternalRulesets `
    -rulesetFile "https://xxxxxxxxx.blob.core.windows.net/default/rulesets/my.ruleset.json"
```

**Full output of scripts**

![image](https://github.com/microsoft/navcontainerhelper/assets/5204734/3e0df691-6d0a-4f10-992b-57ed17a08c8d)

**Additional context**
I have this exact setup in my AL workspace file to use the same external ruleset and it works as expected:

![image](https://github.com/microsoft/navcontainerhelper/assets/5204734/e4299edc-83f1-48de-947a-75892de9c305)

**Comment by freddydk** [comment]
The rulesetfile in Compile-AppInBcContainer doesn't support URL's
You would need to download the ruleset to f.ex. $bcContainerHelperConfig.HostHelperFolder and provide that path.
