### ISSUE TITLE
Strange error in Copy-BcEnvironment

### ISSUE THREAD

**Issue by horstoeko** [microsoft/navcontainerhelper#3313]
**Describe the issue**

We want to copy an environment using the `Copy-BcEnvironment` function. After removing the old Container or after copying to the new container we get the error message described in the script output section.

**Scripts used**
```
$bcAuthContent = New-BcAuthContext -clientID "clientID" -clientSecret "clientSecret" -tenantID "tenantID" -includeDeviceLogin
Copy-BcEnvironment -bcAuthContext $bcAuthContent -environment "destinationenvname" -sourceEnvironment "sourceEnvName"-environmentType Sandbox -force
```

**Full output of scripts**
```
Line |
  63 |  …      } while ($Operation.status -in "queued", "scheduled", "running")
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The property 'status' cannot be found on this object. Verify that the property exists.
```

**Additional Content**

We are using Version **6.0.3**

**Comment by freddydk** [comment]
When you say "After removing the old Container or after copying to the new container we get the error message described in the script output section." - what do you mean by Container?

Copy-BcEnvironment copies sandbox environments - has no connection to containers.

**Comment by freddydk** [comment]
Works fine here:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/f857f0a3-04c0-429f-ab12-097e5d194795)

Please include full output of your script instead of only the error.

**Comment by freddydk** [comment]
Got it - it is a bug.
You can get around this by specifying `-apiVersion "v2.19"` when calling Copy-BcEnvironment.
I will make that the default.

**Comment by horstoeko** [comment]
Thanks a lot for your support. We will add `-apiVersion "v2.19"` temporary to our script

Kind regards
