### ISSUE TITLE
Error creating NAV2017 container

### ISSUE THREAD

**Issue by tscottjendev** [microsoft/navcontainerhelper#3316]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Error: Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)

But it seems to have started it once before.

**Scripts used to create container and cause the issue**
```
Clear-Host
$containerName = 'nav2017'
$password = 'P@ssw0rd'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-NavArtifactUrl -nav '2017' -cu '4' -country 'gb'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -dns 'hostDNS' `
    -includeCSIDE -doNotExportObjectsToText `
    -updateHosts```

**Full output of scripts**
```
BcContainerHelper is version 6.0.0
BcContainerHelper is running as administrator
HyperV is Disabled
UsePsSession is True
Host is Microsoft Windows Server 2022 Standard - 10.0.20348.1547
Docker Client Version is 20.10.9
Docker Server Version is 20.10.9
Removing Session nav2017
Removing container nav2017
Removing entries from hosts
Removing nav2017 from container hosts file
Removing nav2017-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\nav2017
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.20348.1547
Adding DNS Servers from host: 10.100.2.14, 10.101.4.4
Creating Container nav2017
Style: onprem
Multitenant: No
Version: 10.0.15601.0
Platform: 10.0.15601.0
Generic Tag: 1.0.2.14
Container OS Version: 10.0.20348.1547 (ltsc2022)
Host OS Version: 10.0.20348.1547 (ltsc2022)
Using process isolation
Using locale en-GB
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\nav2017\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container nav2017 from image mcr.microsoft.com/businesscentral:10.0.20348.1547
09a012d8f3d20f282ba147411756694991177e9c563af246488dcbe4c89722ad
Waiting for container nav2017 to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/10.0.15601.0/gb
Using installer from C:\Run\100
Copying Platform Artifacts
c:\dl\onprem\10.0.15601.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
c:\dl\onprem\10.0.15601.0\gb\Installers
Copying TestToolKit
c:\dl\onprem\10.0.15601.0\gb\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\10.0.15601.0\gb\UpgradeToolKit
Copying Extensions
c:\dl\onprem\10.0.15601.0\gb\Extensions
Installing NAV
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\GB\OlAddin\OutlookAddIn.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\RTC\RoleTailoredClient.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\Server\Server.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\WebClient\WebClient.Local.Gb.msi
Skipping C:\NAVDVD\Installers\GB\WebHelp\WebHelp.Local.Gb.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting NAV Service Tier
Importing CRONUS license file
Stopping NAV Service Tier
Installation took 201 seconds
Installation complete
Initializing...
Setting vr2-jendevsql.internal to 10.100.2.166 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.21.160.1 in container hosts file
Starting Container
Hostname is nav2017
PublicDnsName is nav2017
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A49219AEA8A224F1797B52F3B6415D145E628991
DNS identity nav2017
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVDError
Using artifactUrl https://bcartifacts.azureedge.net/onprem/10.0.15601.0/gb
Using installer from C:\Run\100
Copying Platform Artifacts
c:\dl\onprem\10.0.15601.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Copying Installers
c:\dl\onprem\10.0.15601.0\gb\Installers
Copying TestToolKit
c:\dl\onprem\10.0.15601.0\gb\TestToolKit
Copying UpgradeToolKit
c:\dl\onprem\10.0.15601.0\gb\UpgradeToolKit
Copying Extensions
c:\dl\onprem\10.0.15601.0\gb\Extensions
Installing NAV
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Installing Url Rewrite
Installing SQL Clr Types
Installing Report Viewer
Installing OpenXML
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Restoring CRONUS Demo Database
Installing C:\NAVDVD\Installers\GB\OlAddin\OutlookAddIn.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\RTC\RoleTailoredClient.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\Server\Server.Local.Gb.msi
Installing C:\NAVDVD\Installers\GB\WebClient\WebClient.Local.Gb.msi
Skipping C:\NAVDVD\Installers\GB\WebHelp\WebHelp.Local.Gb.msi
Modifying NAV Service Tier Config File for Docker
Creating NAV Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting NAV Service Tier
Importing CRONUS license file
Stopping NAV Service Tier
Installation took 201 seconds
Installation complete
Initializing...
Setting vr2-jendevsql.internal to 10.100.2.166 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.21.160.1 in container hosts file
Starting Container
Hostname is nav2017
PublicDnsName is nav2017
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A49219AEA8A224F1797B52F3B6415D145E628991
DNS identity nav2017
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Microsoft Dynamics NAV Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 172
at <ScriptBlock>, C:\Run\start.ps1: line 384
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVD
New-BcContainer Telemetry Correlation Id: acd4bbf8-17b9-47c3-b9b9-95624bf267f8
Initialization of container nav2017 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.0\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... nav2017 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container nav2017 failed
```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
- does it happen all the time?  Yes
- did it use to work? New simple script.

**Comment by tscottjendev** [comment]
Works for the NAV2017 latest CU (61) and works for NAV2018 CU4.

**Comment by freddydk** [comment]
The reason might be this: https://github.com/microsoft/navcontainerhelper/issues/2264
(which also contains a workaround for the issue)

**Comment by tscottjendev** [comment]
Found this in the event log

> The service MicrosoftDynamicsNavServer$NAV failed to start. This could be caused by a configuration error. Detailed error information: System.ArgumentException: It is likely that certificate 'CN=nav2017' may not have a private key that is capable of key exchange or the process may not have access rights for the private key. Please see inner exception for detail. ---> System.Security.Cryptography.CryptographicException: Invalid provider type specified.

**Comment by tscottjendev** [comment]
Trying the work around now.

**Comment by tscottjendev** [comment]
looks to be working thank you
