### ISSUE TITLE
New-NavContainerTenant with SQL on Host OS

### ISSUE THREAD

**Issue by doughton** [Microsoft/navcontainerhelper#332]
The New-NAVContainerTenant looks like it should be able to work with external sql, as it has parameters for sqldbcredentials, however, I can't seem to get it to work. The first step is to backup a database called tenant on the sql server which exists. It uses copy-navdatabase cmdlet which I can't seem to find to dissect - but looks like it does a sql backup to c:\tenant.bak. It just waits for a bit then retries, and keeps retrying, never to start / finish. Inside the container at the root directory, I don't ever see that file getting created.

**Comment by doughton** [comment]
The New-NAVContainerTenant looks like it should be able to work with external sql, as it has parameters for sqldbcredentials, however, I can't seem to get it to work.  The first step is to backup a database called tenant on the sql server which exists.  It uses copy-navdatabase cmdlet which I can't seem to find to dissect - but looks like it does a sql backup to c:\tenant.bak.  It just waits for a bit then retries, and keeps retrying, never to start / finish.  Inside the container at the root directory, I don't ever see that file getting created.

**Comment by freddydk** [comment]
You can modify helperfunctions.ps1 and specify -myscripts @("your helperfunctions") to override and check why this fails.
You can also try to do the steps manually and let me know if I need to do anything to fix this.

**Comment by doughton** [comment]
Thanks Freddy!  will give it a go.

**Comment by doughton** [comment]
So it would appear to me with an External SQL - the hardcoded backup to c:\, restore to c:\ and the move commands for the database mdf / ldf files is a problem.  I have an secondary disk for sql data, and added a folder there, then changed these commands to use that folder and had no issues.
I've had this problem before where permissions from the OS don't like / allow writing to the c:\  root location.

So I'd suggest either making a folder that's not at the root and hardcoding that, or adding a parameter that you can specify the working location and end destination path for the databases.
