### ISSUE TITLE
Problem downloading NextMajor/Master

### ISSUE THREAD

**Issue by rdebath** [microsoft/navcontainerhelper#3327]
**Describe the issue**
Looks like we've only been getting 'core' versions since the 28th Jan.
I can only see Version 24 localised versions for 27th Jan and before.

**Scripts used to create container and cause the issue**
```
PS C:\Users\Administrator> Get-BCArtifactUrl -select NextMajor -country core -accept_insiderEula
https://bcinsider.azureedge.net/sandbox/24.0.15939.0/core
PS C:\Users\Administrator> Get-BCArtifactUrl -select NextMajor -country w1 -accept_insiderEula
https://bcinsider.azureedge.net/sandbox/24.0.15733.0/w1
PS C:\Users\Administrator> Get-BCArtifactUrl -select NextMajor -country dk -accept_insiderEula
https://bcinsider.azureedge.net/sandbox/24.0.15733.0/dk

PS C:\Users\Administrator> Get-BCArtifactUrl -select Latest -before '2024-01-31' -storageAccount bcinsider -accept_insiderEula -version '24.' -country w1
https://bcinsider.azureedge.net/sandbox/24.0.15733.0/w1
PS C:\Users\Administrator> Get-BCArtifactUrl -select Latest -before '2024-01-28' -storageAccount bcinsider -accept_insiderEula -version '24.' -country w1
https://bcinsider.azureedge.net/sandbox/24.0.15733.0/w1
PS C:\Users\Administrator> Get-BCArtifactUrl -select Latest -before '2024-01-27' -storageAccount bcinsider -accept_insiderEula -version '24.' -country w1
https://bcinsider.azureedge.net/sandbox/24.0.15728.0/w1
PS C:\Users\Administrator>
```

**Additional context**
Seems repeatable, DevOPS logs seem to have the same master version for the last few days.

**Comment by freddydk** [comment]
NextMajor has been broken since January 27th due to some changes with PowerShell.
core is not a country, that is just the compiler and some other stuff, which are not broken.
So,... - get-bcartifacturl with country us and select nextmajor will give you the latest good NextMajor (even though it is a week old)

**Comment by rdebath** [comment]
Unfortunately not, that version isn't good; it's been bad since about the 20th Jan due to a mess up with the compiler so the latest good is over two weeks old and I'd have to use `-before`, but that doesn't work for `NextMajor`. (It does with `master` though so I can fake it)

**Comment by freddydk** [comment]
Got it.
As part of our build validation (right before we generate artifacts), we test the artifacts by creating a container with Business Central and see that it can start and we can login - if this fails, no artifacts are generated.
We could add a compile to this step - but then again, I don't think the problem you have with the compiler would be caught by any simple test as my test next major pipelines still works fine: https://github.com/microsoft/bcsamples-bingmaps.pte/actions/runs/7770990198 (running on build 15733 that is)

**Comment by rdebath** [comment]
Morning Freddy,
According to our extension collection you have about a 5% chance of catching the 20th issue, over 95% of them (mostly trivial of course) build successfully. IMO the only realistic way Microsoft can catch it is the way it happened; we tell them they fix it and add a regression test.

I guess maybe you could add a "Known-Bad" filter so you can relabel the images later, but that sounds annoying to keep up to date. Even just simple date filtering them for NextMajor is likely a management chore that you really don't need and probably doesn't help us any because of the variability.

Though, I have done the latter myself adding an optional `-before` date to the pipeline build variables so I can hold `NextMajor` if I need to have it building more than I need to know when it gets fixed, perhaps something for AL-Go ?

**Comment by freddydk** [comment]
Not sure how you came to 5% chance - what I mention is that on top of all the tests running in BC and all the tests running on the compiler in their repo - I run a container test before publishing artifacts - these very very very seldomly fail - but when they do, they would have been hitting every single partner using artifacts (= a lot).
This is the reason for this test and the reason why artifacts in next major are delayed.
If there are bugs in the compiler or in BC - they must be handles elsewhere.
Sometimes, bugs stumble over each other and cause a longer than good delay in publishing artifacts - but that is not very often.

**Comment by rdebath** [comment]
I was agreeing with you, you could in theory create an extra extension and do various tests with that but with all those other tests there are some additional random posting is "very very very" unlikely to catch anything extra.

NB: The 5% was just how many of our little extensions failed because of the compiler issue.

**Comment by rdebath** [comment]
They're back! 🎉

Uhhhh, but the Microsoft tests don't load.
Works:   `-includeTestToolkit -includeTestLibrariesOnly`
Doesn't Work:   `-includeTestToolkit `

Hmm, you don't test that [here](https://github.com/microsoft/bcsamples-bingmaps.pte/actions/runs/7770990198/job/21191784477), I'm not sure if that's a problem ... ?

**Comment by freddydk** [comment]
The problem is with the Business Foundation Test Libraries, which are not automatically included.
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/356d30ce-47c9-48eb-882a-efd9b7612b1e)

That is a containerhelper bug - fix is on it's way.

**Comment by freddydk** [comment]
Shipped in preview now

**Comment by rdebath** [comment]
Got 6.0.6
