### ISSUE TITLE
Feature request: disable all present NAV users in SQL backup to be used for creating a new NAVcontainer

### ISSUE THREAD

**Issue by TheovdVen** [Microsoft/navcontainerhelper#333]
If I want to use a database backup received from a customer that has a license installed with less full users in it than there are setup in the database and even more than we have in our partner license it is not possible to use this database backup when creating a new navcontainer.

I know that the number of users in the customer database needs to be adjusted or the license to be extended and they will on short term. 

Customer already added all users during implementation phase and because of this now I need to restore the backup on some sql server, remove all NAV users with a script and create a new backup before I can start a new container that I need for developing an extension.

It would be very handy if a parameter would exist on new-navcontainer that would disable all NAV users present in the database so that no error occurs when creating the container. Is this a feature that could be added?

**Comment by freddydk** [comment]
Am I right in assuming that you have a .bak file and want to use that without the users?
I would create a file called SetupDatabase.ps1 looking like this:
```
. "c:\run\SetupDatabase.ps1"
Invoke-sqlcmd -serverinstance "$DatabaseServer\$DatabaseInstance" -Database $DatabaseName -query 'whatever SQL command you need to empty the user database'
```
and then add the path to that file in -myScripts @("full path to setupdatabase.ps1")
You can even place the SetupDatabase.ps1 in a github repo and reference the raw http in myscripts to have the script stored in a reusable location.
That should work.

**Comment by TheovdVen** [comment]
I can confirm that this works. 
On my first try I specified the path of the script to be executed as the path inside the container but I needed to specify the path on my machine from where I create the container.
