### ISSUE TITLE
New-NavImage.ps1: Invalid JSON primitive: failed (failed to get console mode for stdout: The handle is invalid)

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#3333]
I'm trying to create a new image, but it fails:
Invalid JSON primitive: failed.
at Get-BcContainerGenericTag, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.5\ContainerInfo\Get-NavContainerGenericTag.ps1: line 23
at New-BcImage, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.5\ContainerHandling\New-NavImage.ps1: line 345

Setting a break point and dividing line 23 ($inspect = docker inspect $imageName | ConvertFrom-Json) into
$inspect2 = docker inspect $imageName 
$inspect = $inspect2 | ConvertFrom-Json
In $inspect2 I could see that the first line contained "failed to get console mode for stdout: The handle is invalid." which cause the JSON error.

This error again directed me to this thread: https://github.com/docker/compose/issues/8186

If I run the script from Powershell ISE, then I'm not getting the error. I only get it when running it from VSCode.

I assume that the problem started after I update Docker Desktop to version 4.27.2 (137060) yesterday.

I have tried specifying the VSCode setting suggested in the thread:
    "terminal.integrated.env.windows": {
        "COMPOSE_DOCKER_CLI_BUILD": "0"
    }
But this did not work for me.

Have anyone else experienced this error?

**Comment by freddydk** [comment]
Same problem as #3326

**Comment by epernst** [comment]
I can confirm that updating Docker Desktop to version 4.28.0 has fixed the issue.
