### ISSUE TITLE
Expose Get-DefaultSqlCredential function

### ISSUE THREAD

**Issue by eclipses24** [Microsoft/navcontainerhelper#334]
I'm running the following script using the new function released Invoke-ScriptInNavContainer.

Invoke-ScriptInNavContainer -containerName $containerName -ScriptBlock {    
    Sync-NAVTenant -ServerInstance NAV -Mode Sync -Force                                     
}

The build stops there for long time and from the Event Viewer seems the issue is related to the credentials not passed. 

Looking in your code often is used this line before
$sqlCredential = Get-DefaultSqlCredential -containerName $containerName -sqlCredential $sqlCredential -doNotAskForCredential

I think Get-DefaultSqlCredential function should be exposed

**Comment by freddydk** [comment]
Sync-NavTenant doesn't require Sql credentials - no reason for asking for that.
If you connect to the container Open-NavContainer (or Enter-NavContainer) and type
Sync-NavTenant -serverinstance NAV -mode sync -force
what happens? (it seems like you are missing a tenant parameter)

You can also try to run 
Get-NAVTenant NAV | Sync-NavTenant -Mode ForceSync -Force

**Comment by eclipses24** [comment]
So, my preference is to use your new function because I do not need to import NAV Modules

I just run a test with this script
Invoke-ScriptInNavContainer -containerName $containerName -ScriptBlock {
    Get-NAVTenant NAV | Sync-NavTenant -Mode Sync -Force
}

It took more tha 6 minutes. No errors and no info in the Event Viewer. Is there anyway how to see why is taking so long?

Am I correct saying that if I use Open-NavContainer or Enter-NavContainer i have to import NAV Modules?

**Comment by freddydk** [comment]
No, both Open and Enter-NavContainer has imported the same modules as Invoke-Script.

**Comment by eclipses24** [comment]
I've just run a test using this script

Open-NavContainer $containerName
Get-NAVTenant NAV | Sync-NavTenant -Mode ForceSync -Force

and it failed "C:\agent\_work\1\git\Powershell\SyncSchemaChanges.ps1 : The term 'Get-NAVTenant' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

**Comment by freddydk** [comment]
Open-NavContainer opens a window - the Get-NavTenant needs to be executed in that window:
![image](https://user-images.githubusercontent.com/10775043/52126609-11c63980-2630-11e9-9b64-572d46704ae7.png)

**Comment by freddydk** [comment]
I am aware that you cannot use Open-NavContainer in scripting to execute your script - but you can test your script in there.
If it works there, it should also work in Invoke-ScriptInNavContainer.
This way you would have found the error with the first command easier.

**Comment by eclipses24** [comment]
No, I cannot do it, I'm working in a build script that is run thruough DevOps Agent in one of my servers.

**Comment by freddydk** [comment]
You should work on your scripts locally or connected and then test then on devops agents (IMO)

**Comment by eclipses24** [comment]
Yep I'm doing, testing both side :-D

I will let you know what I will find.

**Comment by eclipses24** [comment]
Done, the Sync-NAVTenant took few seconds
![image](https://user-images.githubusercontent.com/46592566/52127637-f01a8180-2632-11e9-909a-123221aacdb4.png)
Now the question is why is taking longer from the script using Invoke-ScriptInNavContainer

**Comment by eclipses24** [comment]
Quick Update:
I'm running the following command and not it is much faster

Invoke-ScriptInNavContainer -containerName $containerName -ScriptBlock {
    Sync-NAVTenant -ServerInstance 'MicrosoftDynamicsNavServer$NAV' -Mode Sync -Force
}

The only difference is the ServerInstance name.

The error related to the credentials is still showing in the Event Viewer but it is during the creation (everythign works but I have 2 errors for each run)
**Error 1**
exec's CreateProcess() failed [exec=a2c9aba2eef1dc352885074088bf4397cf21acd57cd88a9fd6ff917f71441819 module=libcontainerd namespace=moby error=container deb0ecdd0e80dd06579d64671b12c757dada687d84b6a9a1c105aef579dcc17c encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"CommandLine":"cmd.exe /C \"ECHO 10.1.2.30    host.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts \u0026 ECHO 10.1.2.30    gateway.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts\"","User":"Administrator","WorkingDirectory":"/","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","DatabaseName":"CRONUS","ExitOnError":"N","IsBcSandbox":"N","NAVDVDURL":"https://nav2016wswe0.blob.core.windows.net/dvd/13a89a5b-5a10-4bd0-a19a-1d424f4a9aa1","VSIXURL":"https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.16641.vsix","WebClient":"N","accept_eula":"Y","accept_outdated":"Y","auth":"NAVUserPassword","databaseInstance":"","databaseServer":"","enableSymbolLoading":"Y","httpSite":"N","licenseFile":"c:\\run\\my\\license.flf","locale":"en-US","passwordKeyFile":"c:\\run\\my\\aes.key","removePasswordKeyFile":"Y","securePassword":"76492d1116743f0423413b16050a5345MgB8AGgASgBoAEgARwBpAFQAVgBvAG8AVQBLAE8AWgBqAHYAYgBOAFoAcABDAGcAPQA9AHwANQBjAGIAYwA1ADIAZAAyADAAYwBjADgAMwA0ADkAYQAxADIANQA0ADYAMQBhAGIAOQBhADgAOAA4AGEAMABjAGYAMAA2AGEAOABlADEAOQA2AGMAMABlADgAOQBjAGUANABlADcAYgBjADgAOABlADMAYwAxADMANwA1ADkAMgA=","useSSL":"N","username":"admin"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]} container=deb0ecdd0e80dd06579d64671b12c757dada687d84b6a9a1c105aef579dcc17c]
**Error 2**
Error running exec a2c9aba2eef1dc352885074088bf4397cf21acd57cd88a9fd6ff917f71441819 in container: container deb0ecdd0e80dd06579d64671b12c757dada687d84b6a9a1c105aef579dcc17c encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e) extra info: {"CommandLine":"cmd.exe /C \"ECHO 10.1.2.30    host.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts \u0026 ECHO 10.1.2.30    gateway.docker.internal \u003e\u003e %systemroot%\\system32\\drivers\\etc\\hosts\"","User":"Administrator","WorkingDirectory":"/","Environment":{"COMPLUS_NGenProtectedProcess_FeatureEnabled":"0","DatabaseName":"CRONUS","ExitOnError":"N","IsBcSandbox":"N","NAVDVDURL":"https://nav2016wswe0.blob.core.windows.net/dvd/13a89a5b-5a10-4bd0-a19a-1d424f4a9aa1","VSIXURL":"https://nav2016wswe0.blob.core.windows.net/dvd/al-0.12.16641.vsix","WebClient":"N","accept_eula":"Y","accept_outdated":"Y","auth":"NAVUserPassword","databaseInstance":"","databaseServer":"","enableSymbolLoading":"Y","httpSite":"N","licenseFile":"c:\\run\\my\\license.flf","locale":"en-US","passwordKeyFile":"c:\\run\\my\\aes.key","removePasswordKeyFile":"Y","securePassword":"76492d1116743f0423413b16050a5345MgB8AGgASgBoAEgARwBpAFQAVgBvAG8AVQBLAE8AWgBqAHYAYgBOAFoAcABDAGcAPQA9AHwANQBjAGIAYwA1ADIAZAAyADAAYwBjADgAMwA0ADkAYQAxADIANQA0ADYAMQBhAGIAOQBhADgAOAA4AGEAMABjAGYAMAA2AGEAOABlADEAOQA2AGMAMABlADgAOQBjAGUANABlADcAYgBjADgAOABlADMAYwAxADMANwA1ADkAMgA=","useSSL":"N","username":"admin"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}

**Comment by eclipses24** [comment]
Last update for today:

The script is slow using the parameter -Mode Sync (more than 2 minutes) Same script using Force is fast (few seconds).

**Comment by freddydk** [comment]
The right serverinstance in the container is NAV - the name you use in the latest blog post is the service name running inside the container.
The way to do sync is:
Get-NAVTenant NAV | Sync-NavTenant -Mode ForceSync -Force
Which will work for both single and multi-tenant instances.
I have no idea why Sync is slow and ForceSync is faster - but probably because it will test everything first - has nothing to do whether you are running containers or not I guess.
As for the two errors above - they seem to occur when running  CMD.exe /C ECHO something - I don't think this has anything to do with the Sync-NavTenant - nor do I think it has anything to do with the NAV/BC containers - it must be something happening on your setup.
Will close this issue
