### ISSUE TITLE
Extended Demo Data in NavContainer 

### ISSUE THREAD

**Issue by dkatson** [Microsoft/navcontainerhelper#335]
Hi @freddydk ,
The task is to create premium sandbox with Extended Demo Data.

So what I'm doing. 
1) add `assignPremiumPlan` in the script
`New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -licenseFile $licenseFile `
                 -additionalParameters $additionalParameters `
                 -alwaysPull
`

2) Open Web Client : Company Information -> User Experience -> Change to 'Premium'
3) Open Web Client: Configuration Packages -> Import Predefined Package -> US.ENU.Extended (if that is US localization)
4) Open Web Client: Configuration Packages -> US.ENU.Extended -> Apply Package

So, this works. But take additional 15 minutes after container creation.

As I don't want to reinvent the wheel, my question is: 
- should I write script to automate this?
- or may be you already have that?
- or may be you have ready image for that, with some secret tag :) ?

Thanks!

**Comment by freddydk** [comment]
I do not have a script like that - I typically just use the onprem images with demo data.

**Comment by dkatson** [comment]
So, are there any onprem images with extended demo data available in
repositories?

Dmitry Katson,
MVP

My Blog <https://community.dynamics.com/nav/b/katsonsnavblog>
My Twitter <https://twitter.com/DmitryKatson>
My LinkedIn <https://www.linkedin.com/in/dmitry-katson/>

**Comment by freddydk** [comment]
mcr.microsoft.com/businesscentral/onprem:<country> - but I guess that is not extended demo data either, right?

/Freddy

**Comment by freddydk** [comment]
Thanks for the suggestion and the blog post - I will close this one.
