### ISSUE TITLE
The remote name could not be resolved: 'bcartifacts.azureedge.net'

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#3352]
I have tried from serveral different computers, but keep gettings this error:
The remote name could not be resolved: 'bcartifacts.azureedge.net'

Script: 
$Url = Get-BCArtifactUrl -type OnPrem -country w1 -version 14.44.49619.0 -select Latest
New-BcContainer -accept_eula -accept_outdated -artifactUrl $Url

_Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'bcartifacts.azureedge.net'"
at InstallPrerequisite, C:\Run\HelperFunctions.ps1: line 614
at <ScriptBlock>, C:\Run\navinstall.ps1: line 30
at <ScriptBlock>, C:\Run\start.ps1: line 316
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVD_

BCCH v6.0.6
Docker: 25.0.3

**Comment by freddydk** [comment]
Strange... - must be something with your firewall or like:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/c337d4cf-11c7-4587-a20b-6b6507ce9c16)

You can try to set $bcContainerHelperConfig.DoNotUseCdnForArtifacts to $false and retry the operation

**Comment by freddydk** [comment]
Please supply the full log - I saw now that the error comes from inside the container.
That is likely because the container doesn't have access to DNS.

**Comment by epernst** [comment]
The setting didn't help.

Here is the Powershell log (assuming that it's not the EventLog):
$Url = Get-BCArtifactUrl -type OnPrem -country w1 -version 14.44.49619.0 -select Latest
New-BcContainer -accept_eula -accept_outdated -artifactUrl $Url
BcContainerHelper is version 6.0.6
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Enterprise - 10.0.19045.4046
Docker Client Version is 25.0.3
Docker Server Version is 25.0.3
Removing Session bcserver
Removing container bcserver
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\bcserver
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container bcserver
Style: onprem
Multitenant: No
Version: 14.44.49619.0
Platform: 14.0.49616.0
Generic Tag: 1.0.2.15
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19045.4046 (22H2)
WARNING: Host OS is Windows 10 21H1 or newer and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
WARNING: Using process isolation on Windows Desktop OS with generic image version prior to 1.0.2.4 or NAV/BC versions prior to 15.0, might require you to use HyperV isolation or disable Windo
ws Defender while creating the container
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\bcserver\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatecontainerhosts.ps1
Creating container bcserver from image mcr.microsoft.com/businesscentral:10.0.19041.1415
f672d9a61aeaf92643b577e1590708bc193d7cd58d54ec5ee3b0723cf66245d7
Waiting for container bcserver to be ready
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.44.49619.0/w1
Using installer from C:\Run\130
Copying Platform Artifacts
c:\dl\onprem\14.44.49619.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Installing Business Central: InstallOnly=False
Downloading Url Rewrite
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'bcartifacts.azureedge.net'"
at InstallPrerequisite, C:\Run\HelperFunctions.ps1: line 614
at <ScriptBlock>, C:\Run\navinstall.ps1: line 30
at <ScriptBlock>, C:\Run\start.ps1: line 316
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVDError
Using artifactUrl https://bcartifacts.azureedge.net/onprem/14.44.49619.0/w1
Using installer from C:\Run\130
Copying Platform Artifacts
c:\dl\onprem\14.44.49619.0\platform
Copying Application Artifacts
Copying Database
Copy Licensefile
Installing Business Central: InstallOnly=False
Downloading Url Rewrite
Exception calling "DownloadFile" with "2" argument(s): "The remote name could not be resolved: 'bcartifacts.azureedge.net'"
at InstallPrerequisite, C:\Run\HelperFunctions.ps1: line 614
at <ScriptBlock>, C:\Run\navinstall.ps1: line 30
at <ScriptBlock>, C:\Run\start.ps1: line 316
at <ScriptBlock>, <No file>: line 1
remove C:\NAVDVD
New-BcContainer Telemetry Correlation Id: d78a94e3-70a7-4255-be34-34fc423b846b
Initialization of container bcserver failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.6\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...bcserver failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bcserver failed

**Comment by epernst** [comment]
That did not make a difference. Same error.

**Comment by freddydk** [comment]
-dns "8.8.8.8" ?

If that doesn't work, then try to open a prompt inside the container and 

ping 8.8.8.8
Do you get a reply?
ping bcartifacts.azureedge.net
Do you get a reply?
bcartifacts.blob.core.windows.net
Do you get a reply?

are these urls pingable from your host?

**Comment by epernst** [comment]
With -dns "8.8.8.8" it created the container without the error! THANKS!

Is that a settings we should use going forward or?

**Comment by freddydk** [comment]
Before bluntly saying YES (and for other people reading this), it is important to understand what happens.

By default, the container lives in a NAT network on your host.
You can change the network settings in docker, but that is a whole other story and not for this issue.

Apparently, your DNS, your network (or your host) doesn't allow the docker container on your host to use the DNS.
Without setting DNS, DNS is handled by the host, which forwards DNS requests to the network DNS, which didn't work (it also doesn't work on my laptop when I am on the Microsoft Corporate Network)
With DNS set to "hostDNS", ContainerHelper will grab the IP address of DNS on the host and forward this to your container, which  apparently was blocked by something. (this works on MS CorpNet)
With DNS set to 8.8.8.8, the container will use Google's public DNS server as DNS. (This doesn't work on MS CorpNet)

So, it is all a matter of how the network is configured and your Network administrator could probably tell you whether all of this is on purpose or whether it is coincidence.

**Comment by epernst** [comment]
Thanks. I just have a "follow-up problem". If I specify imageName (or run New-BcImage) then I'm also getting the error:

New-BcContainer -accept_eula -accept_outdated -artifactUrl $Url -dns "8.8.8.8" -imageName 'myimage'

It seems we cannot specify -dns for New-BcImage.

**Comment by freddydk** [comment]
That might be - that is not something I will have time to look into for the foreseeable future:-(
You are however welcome to add that to New-BcImage and create a PR on BcContainerHelper, if you can make it work.

**Comment by epernst** [comment]
I might just do that, as I tried to put the DNS: 8.8.8.8 into the Docker daemon.json, but that didn't work either.

**Comment by epernst** [comment]
It actually did work to update the windows-daemon.json file with:
"dns": ["8.8.8.8"]
