### ISSUE TITLE
Run-BCPTTestsInBcContainer always fails

### ISSUE THREAD

**Issue by JoergPernberg** [microsoft/navcontainerhelper#3361]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
Running Run-BCPTTestsInBcContainer in a container with 23.4.15643.15786 sandbox always throws an error

**Scripts used to create container and cause the issue**
```
Run-BCPTTestsInBcContainer `
    -containerName navserver `
    -tenant bcpt `
    -companyName BCPT `
    -testPage 149002 `
    -suiteCode 'Test' `
    -credential $Credential 

**Full output of scripts**
```
Invoke GET on https://192.168.244.78:7048/BC/api/v1.0/companies?$filter=name%20eq%20%27BCPT%27&tenant=bcpt
Using Company ID 7959e7d5-44cf-ee11-aaf0-f300c20e2f64
Using testpage 149002
Using Suitecode Test
Service Url http://localhost:80/BC/cs/?tenant=bcpt&company=BCPT
Running Performance Tests...
The passed path for -BCPTTestRunnerInternalFolderPath seem to be relative path, converting to absolute.
Absolute path is C:\Applications\testframework\TestRunner\Internal
Importing AL Test Runner from C:\Applications\testframework\TestRunner\Internal\BCPTTestRunnerInternal.psm1
WARNING: The names of some imported commands from the module 
'ALTestRunnerInternal' include unapproved verbs that might make them less 
discoverable. To find the commands with unapproved verbs, run the Import-Module
 command again with the Verbose parameter. For a list of approved verbs, type 
Get-Verb.
Installing MSAL.PS...
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."

Container Free Physical Memory: 5.2Gb

Services in container navserver:
- MicrosoftDynamicsNavServer$BC is Running
- MSSQL$SQLEXPRESS is Running

Run-BCPTTestsInBcContainer Telemetry Correlation Id: 2ef82eb8-4768-4127-a81d-c063bfc12074
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\6.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:288 char:25
                         throw $errorMessage
                         ~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : OperationStopped: (Exception calli... of an object.":String) [], RuntimeException
     FullyQualifiedErrorId : Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."

**Additional context**
It happens all the time and never worked before

**Comment by freddydk** [comment]
In a few versions, this was a problem - code in the artifacts wan't working.
Should be fixed now
