### ISSUE TITLE
"Get-WindowsOptionalFeature: Class not registered" on W11 with PowerShell 7.4.1

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#3378]
**Describe the issue**
I'm trying to create a new container, from VSCode running as an administrator (yes, I know I can do that while not running as Admin, but I got other permissions issues that I didn't have time to dive into right now).

In `New-BcContainer` there is a call to `Get-HypervState` if process is running as Admin.
In that function, the state of Hyper-V is checked via `Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online`
But on my W11 machine, running PowerShell 7.4.1, that results in the error (after a loooong time)
`Get-WindowsOptionalFeature: Class not registered
`

```
>$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Scripts used to create container and cause the issue**
Anything that calls `New-BcContainer` in an elevated mode.

**Full output of scripts**
Below is after I removed `Write-Host "HyperV is $(Get-HypervState)"` from `New-BcContainer`, otherwise I got stuck after the second line...
```
BcContainerHelper is version 6.0.7-preview1150
BcContainerHelper is running as administrator
UsePsSession is True
Host is Microsoft Windows 11 Enterprise - 10.0.22631.3155
Docker Client Version is 24.0.7
Docker Server Version is 24.0.7
```

**Additional context**
- does it happen all the time?
  - Always if running as admin (unless uncomment the `Write-Host` line mentioned above 😉)
- did it use to work?
  -  Yes, before I updated to PowerShell 7

**Comment by freddydk** [comment]
Strange
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/a533623e-8830-46ff-8764-6116ebf229d0)

Do you have Hyper-V installed?

**Comment by jwikman** [comment]
Yes, strange indeed.

It seems as if this issue is from `Get-WindowsOptionalFeature`, and not related to BcContainerHelper.
See https://github.com/PowerShell/PowerShell/issues/13866 for more info.

Even this fails: 
```
PowerShell 7.4.1
PS C:\Users\nabjohwik> Get-WindowsOptionalFeature -Online
Get-WindowsOptionalFeature: Class not registered
```

As a workaround this comment seems to help: https://github.com/PowerShell/PowerShell/issues/13866#issuecomment-1519066710

```
PowerShell 7.4.1
PS C:\Users\nabjohwik> Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online
Get-WindowsOptionalFeature: Class not registered
PS C:\Users\nabjohwik> Import-Module DISM -UseWindowsPowerShell
WARNING: Module DISM is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.
PS C:\Users\nabjohwik> Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online

FeatureName      : Microsoft-Hyper-V
DisplayName      : Hyper-V Platform
Description      : Provides the services that you can use to create and manage virtual machines and their resources.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
```

But I do not know if the side-effects mentioned is something that will affect other stuff... 😕


Would it make sense to try to catch this (and only this) error inside `Get-HypervState` function and default to blank, as is the default behavior if not running as admin?
And when this eventually is solved in PowerShell, this would just start to work.

Since you cannot repro this, I can create a PR for that try/catch, if you're open to that approach?

**Comment by freddydk** [comment]
Yes, I think resilience here is the right path. Please create a PR with this

**Comment by jwikman** [comment]
PR #3382 created.

**Comment by freddydk** [comment]
> PR #3382 created.

Thanks
