### ISSUE TITLE
New Container nextMajor Insider fails (The system cannot find the file specified)

### ISSUE THREAD

**Issue by ans-bar-bm** [microsoft/navcontainerhelper#3380]
**Describe the issue**
Running the following script to create a new container fails. It used to work for BC Version 23, and some of the past 24 Insider, but unfortunatly i don't know any exact dates/versions when the error started to occur.
I am not an expert on powershell or docker so apologies if this is just a simple user error on my part.

**Scripts used to create container and cause the issue**
```
$containerName   = "insider"
$licenseFile     = "C:\Users\...\mylicensefile.bclicense" 
$artifactUrl     = Get-BCArtifactUrl -country de -select nextMajor -type Sandbox -accept_insiderEula

# removes the existing container
Remove-BcContainer `
    -containerName $containerName

# sets up a new container
New-BcContainer `
    -accept_eula `
    -artifactUrl $artifactUrl `
    -containerName $containerName `
    -includeTestToolkit `
    -licenseFile $licenseFile `
    -shortcuts Desktop `
    -updateHosts `
    -enableTaskScheduler$false `
    -auth UserPassword `
    -accept_insiderEula

# imports the specified license file
Import-BcContainerLicense `
    -licenseFile $licenseFile `
    -containerName $containerName `
    -restart

# checks (and sets/fixes) permission on folders
Check-BcContainerHelperPermissions -Fix

```

**Full output of scripts**
```
Removing Session insider
Removing container insider
Removing entries from hosts
Removing insider from container hosts file
Removing insider-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\insider
BcContainerHelper is version 6.0.4
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Enterprise - 10.0.19045.4046
Docker Client Version is 25.0.3
Docker Server Version is 25.0.3
Removing Desktop shortcuts
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container insider
Style: sandbox
Multitenant: Yes
Version: 24.0.16561.0
Platform: 24.0.16518.0
Generic Tag: 1.0.2.13
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19045.4046 (22H2)
Patching prompt.ps1 due to issue #2891
WARNING: Host OS is Windows 10 21H1 or newer and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
Using locale de-DE
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\insider\my\Prompt.ps1
Downloading using WebClient
Using license file C:\Users\barthel\Documents\Dev\Docker\license\4944631.bclicense
Patching container to install dotnet 6.0.13
Downloading C:\ProgramData\BcContainerHelper\Extensions\insider\my\dotnet-win.exe
Downloading using WebClient
Patching container to install dotnet 8.0.0
Downloading C:\ProgramData\BcContainerHelper\Extensions\insider\my\dotnet-win8.exe
Downloading using WebClient
Files in C:\ProgramData\BcContainerHelper\Extensions\insider\my:
- AdditionalOutput.ps1
- dotnet-win.exe
- dotnet-win8.exe
- HelperFunctions.ps1
- license.bclicense
- MainLoop.ps1
- Prompt.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container insider from image mcr.microsoft.com/businesscentral:10.0.19041.1415
80223130cb86e2ad15942c68429833e9d3b792046310125f8b02645dbd5d8bf1
Waiting for container insider to be ready
Generic image is 1.0.2.13 or below, installing dotnet 6.0.13
Generic image is 1.0.2.14 or below, installing dotnet 8.0.0
Using artifactUrl https://bcinsider.azureedge.net/sandbox/24.0.16561.0/de
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.0.16561.0\platform\ServiceTier\Program Files
c:\dl\sandbox\24.0.16561.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\24.0.16561.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\24.0.16561.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\24.0.16561.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.0.16561.0\platform
c:\dl\sandbox\24.0.16561.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.0.16561.0\de\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.0.16561.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.0.16561.0\de\Extensions
Copying Applications
C:\dl\sandbox\24.0.16561.0\platform\Applications
Copying Applications.DE
C:\dl\sandbox\24.0.16561.0\de\Applications.DE
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
The system cannot find the file specified
at <ScriptBlock>, C:\Run\navinstall.ps1: line 206
at <ScriptBlock>, C:\Run\start.ps1: line 242
at <ScriptBlock>, <No file>: line 1Error
Generic image is 1.0.2.13 or below, installing dotnet 6.0.13
Generic image is 1.0.2.14 or below, installing dotnet 8.0.0
Using artifactUrl https://bcinsider.azureedge.net/sandbox/24.0.16561.0/de
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.0.16561.0\platform\ServiceTier\Program Files
c:\dl\sandbox\24.0.16561.0\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\24.0.16561.0\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\24.0.16561.0\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\24.0.16561.0\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.0.16561.0\platform
c:\dl\sandbox\24.0.16561.0\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.0.16561.0\de\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.0.16561.0\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.0.16561.0\de\Extensions
Copying Applications
C:\dl\sandbox\24.0.16561.0\platform\Applications
Copying Applications.DE
C:\dl\sandbox\24.0.16561.0\de\Applications.DE
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
The system cannot find the file specified
at <ScriptBlock>, C:\Run\navinstall.ps1: line 206
at <ScriptBlock>, C:\Run\start.ps1: line 242
at <ScriptBlock>, <No file>: line 1
New-BcContainer Telemetry Correlation Id: 86477fdf-2123-4623-842b-5e7e02531a20
Initialization of container insider failed
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.4\ContainerHandling\Wait-NavContainerReady.ps1:42 Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ... insider failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container insider failed
```

**Comment by IceOnly** [comment]
I got the same error message. But it seems the artifacts are defect.
An older version like https://bcinsider.azureedge.net/sandbox/24.0.16237.0/w1 works.

**Comment by freddydk** [comment]
Please grab the latest BcContainerHelper pre-release build and retry the operation

**Comment by ans-bar-bm** [comment]
Running the script with the latest pre-release build worked, thanks!

**Comment by MatthewMcCarthy7** [comment]
I'm still getting the error, and I am on the Preview version

PS C:\Users\Administrator> $securePassword = ConvertTo-SecureString -String "matt123" -AsPlainText -Force
$artifactUrl = Get-BCArtifactUrl -country us -type Sandbox -select NextMajor -accept_insiderEula
New-BCContainer `
    -doNotCheckHealth `
    -updateHosts `
    -containerName NextMajor `
    -artifactUrl $artifactUrl `
    -auth NavUserPassword `
    -Credential $credential `
    -memoryLimit 8g `
    -licenseFile "C:\License\License.bclicense" `
    -assignPremiumPlan `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -alwaysPull `
    -accept_eula `
    -accept_outdated `
    -accept_insiderEula
BcContainerHelper version 6.0.7-preview1151
BC.HelperFunctions emits usage statistics telemetry to Microsoft
BcContainerHelper is version 6.0.7-preview1151
BcContainerHelper is running as administrator
HyperV is Disabled
UsePsSession is True
Host is Microsoft Windows Server 2019 Standard - 10.0.17763.5122
Docker Client Version is 24.0.7
Docker Server Version is 24.0.7
Removing Session NextMajor
Removing container NextMajor
Removing entries from hosts
Removing NextMajor from container hosts file
Removing NextMajor-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\NextMajor
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:10.0.17763.5122-dev
10.0.17763.5122-dev: Pulling from businesscentral
Using image mcr.microsoft.com/businesscentral:10.0.17763.5122-dev
Disabling Health Check (always report healthy)
Creating Container NextMajor
Style: sandbox
Multitenant: Yes
Version: 24.0.16410.16912
Platform: 24.0.16775.0
Generic Tag: 1.0.2.14-dev
Container OS Version: 10.0.17763.5122 (ltsc2019)
Host OS Version: 10.0.17763.5122 (ltsc2019)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\License\VEL.bclicense
Patching container to install dotnet 8.0.2 and PowerShell 7.4.1
Downloading C:\ProgramData\BcContainerHelper\Extensions\NextMajor\my\dotnet-win8.exe
Downloading using WebClient
Downloading C:\ProgramData\BcContainerHelper\Extensions\NextMajor\my\powershell-7.4.1-win-x64.msi
Downloading using WebClient
Files in C:\ProgramData\BcContainerHelper\Extensions\NextMajor\my:
- AdditionalOutput.ps1
- dotnet-win8.exe
- HelperFunctions.ps1
- license.bclicense
- MainLoop.ps1
- powershell-7.4.1-win-x64.msi
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container NextMajor from image mcr.microsoft.com/businesscentral:10.0.17763.5122-dev
41b8c812006f66b1532bde584ca56e67990edd6e9676d8b96478408fa631615e
Waiting for container NextMajor to be ready
Installing dotnet 8.0.0
Installing PowerShell 7.4.1
Using artifactUrl https://bcinsider.azureedge.net/sandbox/24.0.16410.16912/us
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.0.16410.16912\platform\ServiceTier\Program Files
c:\dl\sandbox\24.0.16410.16912\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\24.0.16410.16912\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\24.0.16410.16912\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\24.0.16410.16912\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.0.16410.16912\platform
c:\dl\sandbox\24.0.16410.16912\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.0.16410.16912\us\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.0.16410.16912\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.0.16410.16912\us\Extensions
Copying Applications
C:\dl\sandbox\24.0.16410.16912\platform\Applications
Copying Applications.US
C:\dl\sandbox\24.0.16410.16912\us\Applications.US
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
The system cannot find the file specified
at <ScriptBlock>, C:\Run\navinstall.ps1: line 206
at <ScriptBlock>, C:\Run\start.ps1: line 242
at <ScriptBlock>, <No file>: line 1Error
Installing dotnet 8.0.0
Installing PowerShell 7.4.1
Using artifactUrl https://bcinsider.azureedge.net/sandbox/24.0.16410.16912/us
Using installer from C:\Run\210-new
Installing Business Central
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.0.16410.16912\platform\ServiceTier\Program Files
c:\dl\sandbox\24.0.16410.16912\platform\ServiceTier\System64Folder
Copying PowerShell Scripts
c:\dl\sandbox\24.0.16410.16912\platform\WindowsPowerShellScripts\Cloud\NAVAdministration
c:\dl\sandbox\24.0.16410.16912\platform\WindowsPowerShellScripts\WebSearch
Copying Web Client Files
c:\dl\sandbox\24.0.16410.16912\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.0.16410.16912\platform
c:\dl\sandbox\24.0.16410.16912\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.0.16410.16912\us\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.0.16410.16912\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.0.16410.16912\us\Extensions
Copying Applications
C:\dl\sandbox\24.0.16410.16912\platform\Applications
Copying Applications.US
C:\dl\sandbox\24.0.16410.16912\us\Applications.US
Copying dependencies
Copying ReportBuilder
Importing PowerShell Modules
Restoring CRONUS Demo Database
The system cannot find the file specified
at <ScriptBlock>, C:\Run\navinstall.ps1: line 206
at <ScriptBlock>, C:\Run\start.ps1: line 242
at <ScriptBlock>, <No file>: line 1
New-BCContainer Telemetry Correlation Id: 22ceb3f5-f972-49fa-9106-3205e51667c0
Initialization of container NextMajor failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.7\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...extMajor failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container NextMajor failed

**Comment by freddydk** [comment]
@MatthewMcCarthy7 please don't respond to already closed issues
The problem here seems to be that you are running an un-updated Windows Server version on the host.
If you install latest updates on the host, it should work.
