### ISSUE TITLE
[NextMajor] Processing dependency leads to an error

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#3383]
We are using your `DevOps-Pipeline.ps1` script for quite a while.

Starting from last monday (26.02.2024) with the NextMajor build [16561](https://bcinsider.azureedge.net/sandbox/24.0.16561.0/de) our pipelines show an error.
(latest BC23 build and NextMinor are fine...)

After compiling the main app, the dependent app cannot find the main app and attempts to download it:

Dependency App exists [before] -> Downloading symbols [now]
in both cases the BcContainerHelper is version 6.0.6

```
Compiling C:\a\1\s\IndustryDE
Using Symbols Folder: C:\a\1\s\.packages
Processing dependency Microsoft_Application_23.0.0.0 ()
Dependency App exists
Processing dependency Microsoft_System_23.0.0.0 ()
Dependency App exists
Processing dependency BE-terna_BE-terna Automotive_35.0.0.0 (bc455598-e208-4c92-bdff-5bbe6b9ed3c3)
Downloading symbols: BE-terna_BE-terna Automotive_35.0.0.0.app
Url : http://172.27.27.111:7049/BC/dev/packages?appId=bc455598-e208-4c92-bdff-5bbe6b9ed3c3&versionText=35.0.0.0&tenant=default
Downloading using WebClient
ERROR Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
```

before 26.02.2024:
```
Compiling C:\a\1\s\IndustryDE
Using Symbols Folder: C:\a\1\s\.packages
Processing dependency Microsoft_Application_23.0.0.0 ()
Dependency App exists
Processing dependency Microsoft_System_23.0.0.0 ()
Dependency App exists
Processing dependency BE-terna_BE-terna Automotive_35.0.0.0 (bc455598-e208-4c92-bdff-5bbe6b9ed3c3)
Dependency App exists
Compiling...
```

No idea...

**Comment by freddydk** [comment]
Right now, Next Major requires the latest prerelease of BcContainerHelper.
The log included above is very limited and shows the problem, but doesn't help resolving the problem.
If latest prerelease of BcContainerHelper doesn't solve the problem, then please include a full log of the script running
