### ISSUE TITLE
Next Major Compiler Folder - Pipeline Fails with Certain Dependent Apps 

### ISSUE THREAD

**Issue by MattTraxinger** [microsoft/navcontainerhelper#3394]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When using a compiler folder on a next major version and dependent apps, the process will sometimes fail. It does not fail on a current pipeline. This appears to be because "altool.exe" ships with the next major compiler folder, but not the current version compiler folder.

<img width="492" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/127848e5-ecb9-41ac-bca9-6d920d071690">

This is happening because the specific dependent app is still usind appId instead of Id.

<img width="406" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/e7a9364f-9284-4b01-bd39-feacb04127ec">

<img width="776" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/998f211a-515d-4785-85ac-78df4da8f608">

**Scripts used to create container and cause the issue**

The strange part is that I cannot reproduce this locally. In a pipeline, if I copy the exact Compile-AppWithBcCompilerFolder function, and associated functions from HelperFunctions, the pipeline will succeed, just using a blank id. But using the function within the existing BcContainerHelper, it fails.

<img width="617" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/ca9cb71c-a4e0-466c-bc16-76de02a48ce3">

I don't know if something like this is the best solution. I'm happy to do a PR if it is.

<img width="483" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/ef3d8ba2-8d78-4d39-82d6-7227d990c14c">

**Comment by freddydk** [comment]
BCContainerHelper 6.0.7 has shipped (with generic images 1.0.2.15 or above)
Also note that generic images 1.0.2.16 for the latest Windows versions has shipped.
