### ISSUE TITLE
Timeout issue encountered when calling OData V4 web services or calling APIs on BC24 containers

### ISSUE THREAD

**Issue by ReggieWang1** [microsoft/navcontainerhelper#3397]
**Describe the issue**

We are currently conducting compatibility testing for version BC 24 and have encountered an issue. 

When accessing our web services through OData or using APIs to retrieve data, we experience long wait times until the request times out without receiving the data. 

For example, 

OData:  GET http://bc24na:7048/BC/BC/ODataV4/Company('CRONUS USA, Inc.')/TRCSalesDocument?$top=1

API: GET http://bc24na:7048/BC/api/v1.0/companies(80deee0e-2619-ed11-b845-000d3a2b9eed)/salesOrders?$expand=salesOrderLines

However, the same request returns the expected data without issues in version 23. 

Additionally, when we use filter to reduce the fields and data returned (Ensuring the response is no more than 10 KB), the response returns successfully. 

I have tested several BC 24 containers, including US Business Central 24.0 (Platform 24.0.16251.0 + Application 24.0.16336.0) and US Business Central 24.1 (Platform 24.0.16775.0 + Application 24.1.16997.0). However, the results consistently lead to timeouts.

**Scripts used to create container and cause the issue**
```


$artifactUrl = "https://bcinsider.azureedge.net/sandbox/24.0.16336.0/us"

$credential = New-Object System.Management.Automation.PSCredential -argumentList "TCPDUser", (ConvertTo-SecureString -String "Password1" -AsPlainText -Force)


$accept_eula = $true

$containername = 'BC24NA'

# REM setup single tenant
$bcContainerHelperConfig.sandboxContainersAreMultitenantByDefault = $false

# REM config port exposure
 $additioanalParams = @(
 "-p 7671:80",
 "-p 7672:8080",
 "-p 7673:443",
 "-p 7677:7047",
 "-p 7678:7048",
 "-p 7679:7049")

New-BcContainer -accept_eula: $accept_eula `
                -containerName: $containername `
                -auth NavUserPassword `
                -Credential $credential `
                -alwaysPull `
                -doNotExportObjectsToText `
                -useSSL:$false `
                -updateHosts `
                -assignPremiumPlan `
                -shortcuts Desktop `
                -artifactUrl $artifactUrl `
                -licenseFile "xxbclicense" `
                -includeTestToolkit:$false `
                -isolation hyperv `
                -memoryLimit 5G `
                -additionalParameters $additioanalParams
```

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/162692411/54a8210e-e7df-4003-9808-579444fb26c7)

![image](https://github.com/microsoft/navcontainerhelper/assets/162692411/ecd078d5-aa2b-4c5c-83f2-edc0d76e664e)

**Comment by freddydk** [comment]
-memorylimit 5G might be the problem here - try assigning 8G or more

**Comment by ReggieWang1** [comment]
The issue was resolved by allocating 8GB for the -memorylimit and removing the -isolation hyperv. Thanks a lot!
