### ISSUE TITLE
Cannot get Windows and CSide clients connecting to container

### ISSUE THREAD

**Issue by hamishab** [Microsoft/navcontainerhelper#34]
Hi,

We have been attempting to set Docker up on a Windows 10 pc and cannot get the Windows or C/Side client shortcuts to connect but the web client works fine.

Error Message (Windows client)
>    The program could not create a connection to the server. Would you like to try again?

Error Message (CSide client)
> [Microsoft][SQL Server Native Client 11.0] SQL Server Network Interfaces: No credentials are available in the security package

> [Microsoft][SQL Server Native Client 11.0] Cannot generate SSPI content

Note that the prerequisite files have been installed on the host
   

**Images**
```
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
microsoft/dynamics-nav   2017-cu10           93d266bbc4f5        4 weeks ago         15GB 
```

**Containers**
```
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS                 PORTS                    
                            NAMES
7874b1402f30        microsoft/dynamics-nav:2017-cu10   "powershell -Comma..."   2 hours ago         Up 2 hours (healthy)   80/tcp, 443/tcp, 1433/tcp
, 7045-7049/tcp, 8080/tcp   nav2017cu10 
```

Log of the container

> Initializing...
> Hostname is nav2017cu10
> PublicDnsName is nav2017cu10
> Running Specific Image
> Using Windows Authentication
> Starting Local SQL Server
> WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
> start...
> Starting Internet Information Server
> Using Database Connection localhost/SQLEXPRESS [CRONUS]
> Modifying NAV Service Tier Config File for Docker
> Modifying NAV Service Tier Config File with Instance Specific Settings
> Start NAV Service Tier
> Using existing license file
> Creating Web Site
> Creating NAV Web Server Instance
> Creating http download site
> Creating Windows user
> Enabling SA
> Creating NAV user
> 
> (6132 rows affected)
> Container IP Address: 172.31.156.144
> Container Hostname  : nav2017cu10
> Container Dns Name  : nav2017cu10
> Web Client          : http://nav2017cu10/NAV/WebClient/
> 
> Files:
> 
> Ready for connections! 
> 

**List of running services in the container**

>

 Status   Name               DisplayName
> ------   ----               -----------
> Running  AppHostSvc         Application Host Helper Service
> Stopped  AppIDSvc           Application Identity
> Stopped  AppMgmt            Application Management
> Stopped  AppXSvc            AppX Deployment Service (AppXSVC)
> Stopped  aspnet_state       ASP.NET State Service
> Stopped  BFE                Base Filtering Engine
> Stopped  BITS               Background Intelligent Transfer Ser...
> Stopped  Browser            Computer Browser
> Stopped  CertPropSvc        Certificate Propagation
> Running  cexecsvc           Container Execution Agent
> Stopped  ClipSVC            Client License Service (ClipSVC)
> Stopped  COMSysApp          COM+ System Application
> Running  CoreMessagingRe... CoreMessaging
> Running  CryptSvc           Cryptographic Services
> Running  DcomLaunch         DCOM Server Process Launcher
> Stopped  defragsvc          Optimize drives
> Stopped  DeviceInstall      Device Install Service
> Running  Dhcp               DHCP Client
> Stopped  diagnosticshub.... Microsoft (R) Diagnostics Hub Stand...
> Running  DiagTrack          Connected User Experiences and Tele...
> Running  Dnscache           DNS Client
> Stopped  DPS                Diagnostic Policy Service
> Stopped  EapHost            Extensible Authentication Protocol
> Stopped  EFS                Encrypting File System (EFS)
> Running  EventLog           Windows Event Log
> Running  EventSystem        COM+ Event System
> Stopped  fdPHost            Function Discovery Provider Host
> Stopped  FontCache          Windows Font Cache Service
> Running  gpsvc              Group Policy Client
> Stopped  hidserv            Human Interface Device Service
> Stopped  HvHost             HV Host Service
> Stopped  IKEEXT             IKE and AuthIP IPsec Keying Modules
> Running  iphlpsvc           IP Helper
> Running  KeyIso             CNG Key Isolation
> Stopped  KPSSVC             KDC Proxy Server service (KPS)
> Stopped  KtmRm              KtmRm for Distributed Transaction C...
> Stopped  LanmanServer       Server
> Running  LanmanWorkstation  Workstation
> Stopped  lltdsvc            Link-Layer Topology Discovery Mapper
> Running  lmhosts            TCP/IP NetBIOS Helper
> Running  LSM                Local Session Manager
> Running  MicrosoftDynami... Microsoft Dynamics NAV Server [NAV]
> Stopped  MpsSvc             Windows Firewall
> Running  MSDTC              Distributed Transaction Coordinator
> Stopped  MSiSCSI            Microsoft iSCSI Initiator Service
> Stopped  msiserver          Windows Installer
> Running  MSSQL$SQLEXPRESS   SQL Server (SQLEXPRESS)
> Stopped  NcaSvc             Network Connectivity Assistant
> Stopped  Netlogon           Netlogon
> Stopped  netprofm           Network List Service
> Stopped  NetSetupSvc        Network Setup Service
> Stopped  NetTcpPortSharing  Net.Tcp Port Sharing Service
> Stopped  NlaSvc             Network Location Awareness
> Running  nsi                Network Store Interface Service
> Stopped  PerfHost           Performance Counter DLL Host
> Stopped  pla                Performance Logs & Alerts
> Stopped  PlugPlay           Plug and Play
> Stopped  PolicyAgent        IPsec Policy Agent
> Stopped  Power              Power
> Running  ProfSvc            User Profile Service
> Stopped  RasMan             Remote Access Connection Manager
> Stopped  RemoteAccess       Routing and Remote Access
> Stopped  RemoteRegistry     Remote Registry
> Running  RpcEptMapper       RPC Endpoint Mapper
> Running  RpcSs              Remote Procedure Call (RPC)
> Stopped  RSoPProv           Resultant Set of Policy Provider
> Stopped  sacsvr             Special Administration Console Helper
> Running  SamSs              Security Accounts Manager
> Stopped  SCardSvr           Smart Card
> Stopped  ScDeviceEnum       Smart Card Device Enumeration Service
> Running  Schedule           Task Scheduler
> Stopped  SCPolicySvc        Smart Card Removal Policy
> Stopped  seclogon           Secondary Logon
> Running  SENS               System Event Notification Service
> Running  SessionEnv         Remote Desktop Configuration
> Stopped  SharedAccess       Internet Connection Sharing (ICS)
> Stopped  smphost            Microsoft Storage Spaces SMP
> Stopped  SNMPTRAP           SNMP Trap
> Stopped  Spooler            Print Spooler
> Stopped  sppsvc             Software Protection
> Stopped  SQLAgent$SQLEXP... SQL Server Agent (SQLEXPRESS)
> Running  SQLBrowser         SQL Server Browser
> Stopped  SQLTELEMETRY$SQ... SQL Server CEIP service (SQLEXPRESS)
> Running  SQLWriter          SQL Server VSS Writer
> Stopped  SstpSvc            Secure Socket Tunneling Protocol Se...
> Stopped  StateRepository    State Repository Service
> Stopped  svsvc              Spot Verifier
> Stopped  swprv              Microsoft Software Shadow Copy Prov...
> Stopped  SysMain            Superfetch
> Running  SystemEventsBroker System Events Broker
> Running  TermService        Remote Desktop Services
> Stopped  TieringEngineSe... Storage Tiers Management
> Running  TimeBrokerSvc      Time Broker
> Stopped  TrustedInstaller   Windows Modules Installer
> Stopped  UALSVC             User Access Logging Service
> Stopped  UmRdpService       Remote Desktop Services UserMode Po...
> Running  UserManager        User Manager
> Stopped  UsoSvc             Update Orchestrator Service for Win...
> Stopped  VaultSvc           Credential Manager
> Stopped  vds                Virtual Disk
> Stopped  vmicguestinterface Hyper-V Guest Service Interface
> Stopped  vmicheartbeat      Hyper-V Heartbeat Service
> Stopped  vmickvpexchange    Hyper-V Data Exchange Service
> Stopped  vmicrdv            Hyper-V Remote Desktop Virtualizati...
> Stopped  vmicshutdown       Hyper-V Guest Shutdown Service
> Stopped  vmictimesync       Hyper-V Time Synchronization Service
> Stopped  vmicvmsession      Hyper-V PowerShell Direct Service
> Stopped  vmicvss            Hyper-V Volume Shadow Copy Requestor
> Stopped  VSS                Volume Shadow Copy
> Stopped  W32Time            Windows Time
> Stopped  w3logsvc           W3C Logging Service
> Running  W3SVC              World Wide Web Publishing Service
> Running  WAS                Windows Process Activation Service
> Stopped  WdiServiceHost     Diagnostic Service Host
> Stopped  WdiSystemHost      Diagnostic System Host
> Stopped  WdNisSvc           Windows Defender Network Inspection...
> Stopped  Wecsvc             Windows Event Collector
> Stopped  WerSvc             Windows Error Reporting Service
> Stopped  WinDefend          Windows Defender Service
> Running  WinHttpAutoProx... WinHTTP Web Proxy Auto-Discovery Se...
> Running  Winmgmt            Windows Management Instrumentation
> Running  WinRM              Windows Remote Management (WS-Manag...
> Stopped  wisvc              Windows Insider Service
> Running  wmiApSrv           WMI Performance Adapter
> Stopped  wuauserv           Windows Update
> Stopped  wudfsvc            Windows Driver Foundation - User-mo...

Thanks for any help you can provide!

Hamish

**Comment by freddydk** [comment]
Did you provide your host windows credentials when deploying the container?
It looks like you used a different set of credentials.

**Comment by Koubek** [comment]
Or maybe you are not inside your domain network and the credentials cannot be validated. I think I was able to connect WebClient out of the domain but this wasn\`t possible to achieve to in the case you I was entering C/SIDE.

**Comment by hamishab** [comment]
Thank you both. I think you are both correct. My laptop doesn't sit on a domain and instead uses Microsoft Online authentication.  Would there be a workaround for this scenario besides spinning up a domain controller and connecting to that?

**Comment by freddydk** [comment]
You could use NavUserPassword authentication for your container.
When connecting to CSide, you would have to use username=SA and the same password as your user (that should also work if you setup windows auth).
