### ISSUE TITLE
Create Container returns with Docker error: hcsshim::PrepareLayer failed in Win32: The system cannot find the path specified. (0x3)

### ISSUE THREAD

**Issue by Zoltero** [microsoft/navcontainerhelper#3400]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
A clear and concise description of what the issue is.

**Scripts used to create container and cause the issue**
```
New-BcContainer `
    -accept_eula `
    -imagename...
```

**Full output of scripts**
```
NavContainerHelper is version 0.6.5.7
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 2004
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
...
```

**Screenshots**

**Additional context**
- does it happen all the time?
- did it use to work?

**Comment by Zoltero** [comment]
Create BC Container on Win 11 Pro 23H2 fails with this error message.

Creating container bc234-w1 from image mcr.microsoft.com/businesscentral:10.0.20348.2322
71eb131eee94a795206adc7b49696ff447b9fdc7a12d8c81bb53f6a57cd73cb4
New-BCContainer Telemetry Correlation Id: a1e167ff-3efe-4351-b847-6762bb8e45e0
docker: Error response from daemon: hcsshim::PrepareLayer failed in Win32: The system cannot find the path specified. (0x3).
ExitCode: 125
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav= --env isBcSandbox=N --label version=23.4.15643.15715 --label platform=23.0.15712.0 --label country=w1 --env artifactUrl=https://bcartifacts.azureedge.net/onprem/23.4.15643.15715/w1 --env lice
nseFile="" --name bc234-w1 --hostname bc234-w1 --env auth=NavUserPassword --env username="admin" --env ExitOnError=N --env locale=en-US --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --v
olume "C:\ProgramData\BcContainerHelper\Extensions\bc234-w1\my:C:\Run\my" --isolation process --restart unless-stopped --env filesOnly=False --env enableApiServices=Y --env useSSL=N --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d
1116743f0423413b16050a5345MgB8AFAAYgB4AHYAOQBJAHYASQBlAE0ANgBxAEkAUAByAFgAdABBADgARwBKAFEAPQA9AHwAMwBiADYAOAA5ADcAZgAwAGEAZAA1ADcAYgAzADMAOQBlADEANwA5AGQAMABmAGEANgBhADcAOAA0AGEAZgAxAA== --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env a
ccept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral:10.0.20348.2322

**Comment by freddydk** [comment]
The error 125 normally indicates that your docker installation is broken.
You should install the latest containerhelper, flush your caches (Flush-ContainerHelperCache) and cleanup your docker installation - potentially like (https://freddysblog.com/2018/12/11/clean-up-after-yourself-docker-your-mom-isnt-here/) and then retry.

**Comment by freddydk** [comment]
BTW in the above - it looks like you are using NavContainerHelper which has been out of support for years - you should be using BcContainerHelper.

**Comment by Zoltero** [comment]
Thx for input. I will give it a try.

BTW:
I am using New-BCContainer command.

It gives me this information when I start the job:
"Latest BcContainerHelper is installed"

**Comment by freddydk** [comment]
OK - but your screenshot above:
![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/740c4b55-1f25-4332-886b-5f25ec5d5285)

Is then not what you are running - because that is years old.

Please include as much logs and info as possible when creating issues - too much is better than too little.

**Comment by Zoltero** [comment]
I tried you tips, but it does not help.

Here are more info:

Enter Container Name: bc234-w1
BcContainerHelper is version 6.0.7
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 11 Pro - 10.0.22631.3235
Docker Client Version is 25.0.3
Docker Server Version is 25.0.3
...
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:10.0.20348.2322
Creating Container bc234-w1
Style: onprem
Multitenant: No
Version: 23.5.16502.16757
Platform: 23.0.16746.0
Generic Tag: 1.0.2.15
Container OS Version: 10.0.20348.2322 (ltsc2022)
Host OS Version: 10.0.22631.3235 (23H2)
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\bc234-w1\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc234-w1 from image mcr.microsoft.com/businesscentral:10.0.20348.2322
New-BCContainer Telemetry Correlation Id: 54311d06-7e24-4763-a43e-a1aa5692d9fd
docker: Error response from daemon: hcsshim::ExpandScratchSize failed in Win32: The system cannot find the file specified. (0x2).
See 'docker run --help'.
ExitCode: 127

**Comment by freddydk** [comment]
Please try to add -isolation hyperv

**Comment by Zoltero** [comment]
Fantastic!!

It look like that the -Isolation hyperv did the trick.

Thx for your support  :)
