### ISSUE TITLE
New-BcContainerBcUser fails with 'Invoke-SqlCmd' error when running BC24

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/navcontainerhelper#3404]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When executing 'New-BcContainerBcUser' on an existing container, the command fails with the following error:

`The term 'Invoke-Sqlcmd' is not recognized as a name of a cmdlet, function, script file, or executable program.`

**Scripts used to create container and cause the issue**

After creating a container with user/password authentication, run the following script:

```
$containerName = 'mycontainer'
$tenant = 'default'
$password = ConvertTo-SecureString -String 'Pass@word1' -AsPlainText -Force

'user1','user2' | ForEach-Object {
    $credential = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $_, $password
    New-BcContainerBcUser -Credential $credential -containerName $containerName -tenant $tenant -assignPremiumPlan -ChangePasswordAtNextLogOn:$false
}
```

**Full output of scripts**
```
PS C:\WINDOWS\system32> D:\Downloads\CreateUser.ps1
Creating User user1
Assigning Permission Set SUPER to user1
Assigning Premium plan for USER1
The term 'Invoke-Sqlcmd' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Container Free Physical Memory: 8.1Gb

Services in container mycontainer:
New-BcContainerBcUser Telemetry Correlation Id: 3b850d78-fa1a-4870-9829-be7ede65263b
The term 'Invoke-Sqlcmd' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.8\ContainerHandling\Invoke-ScriptInNavContainer.ps1:304 char:25
+                         throw $errorMessage
+                         ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The term 'Invok... and try again.:String) [], RuntimeException
    + FullyQualifiedErrorId : The term 'Invoke-Sqlcmd' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
...
```

**Screenshots**
n/a

**Additional context**
- I am using BcContainerHelper 6.0.8
- This has broke in the past week as I have a similar script running every Saturday. It ran fine on March 2, and failed on March 9.
- I am creating a container with v24 artifacts (specifically, I am using the next-minor artifacts)
- I had a similar script I was running where I was using 'Invoke-ScriptInBcContainer' to call 'Invoke-SqlCmd' and it had the same error. I fixed that by adding '-usePwsh $false' to the 'Invoke-ScriptInBcContainer' call
- Seems related to #3330

**Comment by freddydk** [comment]
This is caused by the fact that invoke-scriptinBcContainer uses pwsh in BC 24+ instead of powerShell
Reason for this is that all BC commandlets in BC24 now need PowerShell 7.4.1 and running a bridge from PowerShell 5 to PowerShell 7 is very expensive.

**Comment by MikeGlue** [comment]
awesome, thanks Freddy!
