### ISSUE TITLE
NavContainerHelper 6.0.9 and 6.0.10 New-BcContainer error because HyperV

### ISSUE THREAD

**Issue by hvandenborn007** [microsoft/navcontainerhelper#3420]
[Freddy Kristiansen](https://www.yammer.com/dynamicsnavdev/#/users/1521778790) i have done all the windows updates, Restarted the VM,

 

Updated NavContainerHelper to 6.0.10 Still it finds my OS lower than the container OS and go's for HyperV (which is not installed and i do not want that)

BcContainerHelper version 6.0.10

BC.HelperFunctions emits usage statistics telemetry to Microsoft

Running on Windows, PowerShell 5.1.20348.1850

version: 23.5

nl

ArtifactURL: https://bcartifacts.azureedge.net/onprem/23.5.16502.16757/nl

BcContainerHelper is version 6.0.10

BcContainerHelper is running as administrator

HyperV is Disabled

UsePsSession is True

Host is Microsoft Windows Server 2022 Datacenter Azure Edition - 10.0.20348.1906

Docker Client Version is 24.0.4

Docker Server Version is 24.0.4

Removing Desktop shortcuts

Fetching all docker images

Fetching all docker volumes

ArtifactUrl and ImageName specified

Image bcimage:onprem-23.5.16502.16757-nlwith_db already exists

Image bcimage:onprem-23.5.16502.16757-nlwith_db was built for OS Version 10.0.20348.1906, should be 10.0.20348.2340

Building image bcimage:onprem-23.5.16502.16757-nlwith_db based on [mcr.microsoft.com/businesscentral:ltsc2022](https://mcr.microsoft.com/businesscentral:ltsc2022) with https://bcartifacts.azureedge.net/onprem/23.5.16502.16757/nl

Pulling latest image [mcr.microsoft.com/businesscentral:ltsc2022](https://mcr.microsoft.com/businesscentral:ltsc2022)

ltsc2022: Pulling from businesscentral

Digest: sha256:7473a1ca0616569f43a7b5e14add41f0a5fa8b4b5077abe86c5e4ade1af40d51

Status: Image is up to date for [mcr.microsoft.com/businesscentral:ltsc2022](https://mcr.microsoft.com/businesscentral:ltsc2022)

[mcr.microsoft.com/businesscentral:ltsc2022](https://mcr.microsoft.com/businesscentral:ltsc2022)

Generic Tag: 1.0.2.17

Container OS Version: 10.0.20348.2340 (ltsc2022)

Host OS Version: 10.0.20348.1906 (ltsc2022)

Using hyperv isolation

Using license file D:\Devops\Agent 1\_work\1059\s\Licenses\23.bclicense

Files in c:\bcartifacts.cache\geklxlr0.zhk\my:

Copying Platform Artifacts

c:\bcartifacts.cache\onprem\23.5.16502.16757\platform

Copying ConfigurationPackages

C:\bcartifacts.cache\onprem\23.5.16502.16757\nl\ConfigurationPackages

Copying Applications

C:\bcartifacts.cache\onprem\23.5.16502.16757\nl\Applications

Untagged: bcimage:onprem-23.5.16502.16757-nlwith_db

Deleted: sha256:e47e0612cf8f8f9d8feea13a50777a86ee3193a724db2e7c6ca63a6fdd106ea2

Deleted: sha256:33eb1eb508a5ec219ba2d56106842fce1df90643e36a95385f6fcb7afb9819e0

c:\bcartifacts.cache\geklxlr0.zhk

Sending build context to Docker daemon  1.597GB

 

Step 1/6 : FROM [mcr.microsoft.com/businesscentral:ltsc2022](https://mcr.microsoft.com/businesscentral:ltsc2022)

 ---> c4cd601a3c1b

Step 2/6 : ENV DatabaseServer=localhost DatabaseInstance=SQLEXPRESS DatabaseName=CRONUS IsBcSandbox=N artifactUrl=https://bcartifacts.azureedge.net/onprem/23.5.16502.16757/nl filesOnly=False

 ---> Running in c861529a3fe4

Removing intermediate container c861529a3fe4

 ---> 117dbf3d0e1c

Step 3/6 : COPY my /run/

 ---> fffd64156339

Step 4/6 : COPY NAVDVD /NAVDVD/

 ---> 4f6c39210cc1

Step 5/6 : RUN \Run\start.ps1 -installOnly

 ---> Running in 1475840589be

New-Bcimage Telemetry Correlation Id: 6a234335-bf5e-4cff-90f6-bc109cef64ab

New-BcContainer Telemetry Correlation Id: a2475628-e4eb-4324-8c8b-ec042dfd1aba

DockerDo : hcs::CreateComputeSystem 1475840589be96564d527b69b4e266b091dcb7c95d1aab2ca96849250b8ae43c: The request is 

not supported.

ExitCode: 1

Commandline: docker build --isolation=hyperv --memory 14G --no-cache --tag bcimage:onprem-23.5.16502.16757-nlwith_db 

c:\bcartifacts.cache\geklxlr0.zhk

At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.10\ContainerHandling\New-NavImage.ps1:715 char:27

+ ...       if (!(DockerDo -command build -parameters @("--isolation=$isola ...

+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

 

 

 

on a windows 2019 it runs with 6.0.9 and 6.0.10, there it says 

 

Status: Downloaded newer image for [mcr.microsoft.com/businesscentral:ltsc2019](https://mcr.microsoft.com/businesscentral:ltsc2019)

[mcr.microsoft.com/businesscentral:ltsc2019](https://mcr.microsoft.com/businesscentral:ltsc2019)

Generic Tag: 1.0.2.17

Container OS Version: 10.0.17763.5576 (ltsc2019)

Host OS Version: 10.0.17763.5458 (ltsc2019)

WARNING: Host OS and Base Image Container OS doesn't match and Hyper-V is not installed. If you encounter issues, you could try to install Hyper-V.

Using process isolation

 

its still not in sync but it still does ProcessIsolation wich is what it always have done and works. 

So why is it for 2022 different? 

 

we are now switching back to 6.0.8 else no build runs.

**Comment by freddydk** [comment]
For Windows Server 2019, the docker containers are only guaranteed to work with process isolation if it is the same version.
For Windows Server 2022, it is different.

But... - If HyperV is disabled - I guess a better option is to simply try process isolation than trying something that definitely doesn't work. I will change this.
