### ISSUE TITLE
Run-AlValidation  ERROR image operating system "windows" cannot be used on this platform

### ISSUE THREAD

**Issue by navmihaimarian** [microsoft/navcontainerhelper#3424]
**When I Run this command:**
Run-AlValidation  -apps

**Windows Configuration:**
![image](https://github.com/microsoft/AL-Go/assets/132066321/0177c50d-773f-45c4-b996-1c226148f871)
**I receive following error:**
  _____       _ _ _                                          _        _                            
 |  __ \     | | (_)                                        (_)      (_)                           
 | |__) |   _| | |_ _ __   __ _    __ _  ___ _ __   ___ _ __ _  ___   _ _ __ ___   __ _  __ _  ___ 
 |  ___/ | | | | | | '_ \ / _` |  / _` |/ _ \ '_ \ / _ \ '__| |/ __| | | '_ ` _ \ / _` |/ _` |/ _ \
 | |   | |_| | | | | | | | (_| | | (_| |  __/ | | |  __/ |  | | (__  | | | | | | | (_| | (_| |  __/
 |_|    \__,_|_|_|_|_| |_|\__, |  \__, |\___|_| |_|\___|_|  |_|\___| |_|_| |_| |_|\__,_|\__, |\___|
                           __/ |   __/ |                                                 __/ |     
                          |___/   |___/                                                 |___/      

Pulling mcr.microsoft.com/businesscentral:ltsc2019-filesonly
Run-AlValidation Telemetry Correlation Id: a16625b4-73d1-4db7-bddf-30a1b490ff6a
docker : image operating system "windows" cannot be used on this platform: operating system is not supported
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.11\AppHandling\Run-AlValidation.ps1:282 char:39
+ ...    $DockerPull = { Param($imageName) docker pull $imageName --quiet }
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (image operating...s not supported:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by freddydk** [comment]
Moved to BcContainerHelper repo as this doesn't have anything to do with AL-Go.
It looks like your docker is setup for Linux containers - you should switch to Windows containers.

**Comment by navmihaimarian** [comment]
Perfect. After switching to Windows containers, it work. many thanks!!
