### ISSUE TITLE
Invoke CodeUnit that's part of an extension

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#343]
I would like to invoke a codeunit (or page) that's part of an extension.
When using Invoke-NavContainerCodeunit and invoking an extension codeunit, I receive the error-message below.

When invoking a navision object, it works fine.
Does navContainerHelper support calling an extension codeunit object (or page like VS-Code does)
I would like to invoke my own object that's using the test-toolkit objects, to run my testscripts.
I hope I overlooked something.

Invoke-NavContainerCodeunit -containerName PD14-FDWBLDW1 -CompanyName "My Company" -Codeunitid "50101"

Attempted to divide by zero.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:9
+         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Invoke-NAVCodeunit], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/default,Microsoft.Dynamics.Nav.Management.Cmdlets.InvokeNavCodeunit

**Comment by freddydk** [comment]
You can call a codeunit in an extension using invoke-navcontainercodeunit.
Not sure what goes wrong in your case. I have tried to use a wrong method name or the wrong company name and in both cases, I get very describing error messages.
If you want to troubleshoot, you could do enter-navcontainer in ISE and then grab the code inside Invoke-scriptinnavcontainer (in invoke-navcontainercodeunit) and then run it (with the right parameters).

**Comment by mheijkant** [comment]
Thanks for the suggestion. 
It was a mistake on my side.
