### ISSUE TITLE
New-BcContainerWizard: Can`t convert "ltsc2022" to type "System.Version" 

### ISSUE THREAD

**Issue by cr998** [microsoft/navcontainerhelper#3432]
**Describe the issue**
When i use the command New-BcContainerWizard it opens new terminal and instantly closed, so i can view some red letters, if i run directly `& "C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.11\CreateScript.ps1"`, i can view an error 

`
No se puede convertir el valor "ltsc2022" al tipo "System.Version"
`

It seems an error parsing "ltsc2022" as System.Version

**Scripts used to create container and cause the issue**
```
New-BcContainerWizard
```

**Full output of scripts**
```
No se puede convertir el valor "ltsc2022" al tipo "System.Version". Error: "La parte de la cadena de versión es demasiad
En C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.11\CreateScript.ps1: 323 Carácter: 1
+ $bestContainerOsVersion = [System.Version]((Get-BestGenericImageName) ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
```

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/6900835/ad25c4c3-0fbf-4e35-a31e-147801f45ce3)

**Additional context**
BcContainerHelper Version 6.0.11

**Comment by freddydk** [comment]
This is a consequence of the latest generic image changes.
Will provide a fix for this one of the next days

**Comment by ERPG-AD** [comment]
Still an issue with this - Running: New-BCContainerWizard

![image](https://github.com/microsoft/navcontainerhelper/assets/128596150/877ceb69-8f01-4d3d-a8c9-ceccef68a58a)

**Comment by ERPG-AD** [comment]
> Still an issue with this - Running: New-BCContainerWizard
> 
> ![image](https://private-user-images.githubusercontent.com/128596150/317168340-877ceb69-8f01-4d3d-a8c9-ceccef68a58a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MjUyNjgsIm5iZiI6MTcxMTUyNDk2OCwicGF0aCI6Ii8xMjg1OTYxNTAvMzE3MTY4MzQwLTg3N2NlYjY5LThmMDEtNGQzZC1hOGM5LWNlY2NlZjY4YTU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QwNzM2MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGI4YjJmZmZjYzEwMGI4NmIxMmYzNDI2ODNhOWMzZTM2MzM0NjU3NDE3NGQ3YjU2MGM2MmUwMTNmZWU5MjhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0Eb6HGDzNSW-BqzlSEEaRXYB1uyyn41iYzDqJJ_MFAw)

**UPDATE**

I tried manually updating with the changes you've made, and i got further this time. 

Now i just get an error when the "Get-BcArtifactUrl" is called....

![image](https://github.com/microsoft/navcontainerhelper/assets/128596150/5cb0ae3e-0bc7-431b-a420-1138df0f53bf)

**Comment by freddydk** [comment]
Get-BcArtifactUrl is part of BcContainerHelper - it looks like the module isn't loaded somehow.
Anyway - 6.0.12 has just been released - if you upgrade to that - it should work (remember to restart powershell)

If something doesn't work - I will need a repro - meaning the reply you give to all questions in the wizard until it fails in a new issue - please don't reply to closed issues.
