### ISSUE TITLE
Container BC24 Preview - CoreClrClientWebSocketFactory error

### ISSUE THREAD

**Issue by f4n0** [microsoft/navcontainerhelper#3435]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
when creating a container for BC24, throws this error: 
`An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details.`

**Scripts used to create container and cause the issue**
```
PARAM :  -artifactUrl "https://bcpublicpreview.azureedge.net/sandbox/24.0.16410.16790/w1"

New-BcContainer $containerName `
  -artifactUrl $artifactUrl `
  -alwaysPull `
  -accept_eula `
  -auth NavUserPassword `
  -Credential $credential `
  -licenseFile $LicenseFile `
  -updateHosts `
  -dns 8.8.8.8 `
  -doNotExportObjectsToText `
  -includeTestToolkit `
  -includeTestLibrariesOnly `
  -assignPremiumPlan `
  -shortcut None `
  -accept_outdated
```

**Full output of scripts**
```
BcContainerHelper is version 6.0.11
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Pro - 10.0.19045.4170
Docker Client Version is 25.0.4
Docker Server Version is 25.0.4
Removing Session BC24
Removing container BC24
Removing entries from hosts
Removing BC24 from container hosts file
Removing BC24-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\BC24
Fetching all docker images
Fetching all docker volumes
Pulling image mcr.microsoft.com/businesscentral:ltsc2019
ltsc2019: Pulling from businesscentral
Digest: sha256:ca49064a275b9e95c8d3a0ae8264a4222cd7597a84dd6d007276151cfe6bebfa
Status: Image is up to date for mcr.microsoft.com/businesscentral:ltsc2019
mcr.microsoft.com/businesscentral:ltsc2019
Using image mcr.microsoft.com/businesscentral:ltsc2019
Creating Container BC24
Style: sandbox
Multitenant: Yes
Version: 24.0.16410.16790
Platform: 24.0.16743.0
Generic Tag: 1.0.2.17
Container OS Version: 10.0.17763.5576 (ltsc2019)
Host OS Version: 10.0.19045.4170 (22H2)
Using hyperv isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\_myTmp\develop.bclicense
Files in C:\ProgramData\BcContainerHelper\Extensions\BC24\my:
- AdditionalOutput.ps1
- HelperFunctions.ps1
- license.bclicense
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC24 from image mcr.microsoft.com/businesscentral:ltsc2019
1ece7a405869d4025ff7cd63b3b3093291d514ca60d7bc9ec3f193d8374a2233
Waiting for container BC24 to be ready
Using artifactUrl https://bcpublicpreview.azureedge.net/sandbox/24.0.16410.16790/w1
Using installer from C:\Run\240
Installing Business Central: multitenant=True, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\sandbox\24.0.16410.16790\w1, platformArtifactPath=c:\dl\sandbox\24.0.16410.16790\platform, databasePath=c:\dl\sandbox\24.0.16410.16790\w1\BusinessCentral-W1.bak, licenseFilePath=c:\dl\sandbox\24.0.16410.16790\w1\Cronus.bclicense, rebootContainer=True
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.0.16410.16790\platform\ServiceTier\Program Files
c:\dl\sandbox\24.0.16410.16790\platform\ServiceTier\System64Folder
Copying Web Client Files
c:\dl\sandbox\24.0.16410.16790\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.0.16410.16790\platform
c:\dl\sandbox\24.0.16410.16790\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.0.16410.16790\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.0.16410.16790\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.0.16410.16790\w1\Extensions
Copying Applications
C:\dl\sandbox\24.0.16410.16790\platform\Applications
Copying dependencies
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details.
at <ScriptBlock>, <No file>: line 15
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcpublicpreview.azureedge.net/sandbox/24.0.16410.16790/w1
Using installer from C:\Run\240
Installing Business Central: multitenant=True, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\sandbox\24.0.16410.16790\w1, platformArtifactPath=c:\dl\sandbox\24.0.16410.16790\platform, databasePath=c:\dl\sandbox\24.0.16410.16790\w1\BusinessCentral-W1.bak, licenseFilePath=c:\dl\sandbox\24.0.16410.16790\w1\Cronus.bclicense, rebootContainer=True
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\24.0.16410.16790\platform\ServiceTier\Program Files
c:\dl\sandbox\24.0.16410.16790\platform\ServiceTier\System64Folder
Copying Web Client Files
c:\dl\sandbox\24.0.16410.16790\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\24.0.16410.16790\platform
c:\dl\sandbox\24.0.16410.16790\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\24.0.16410.16790\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\24.0.16410.16790\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\24.0.16410.16790\w1\Extensions
Copying Applications
C:\dl\sandbox\24.0.16410.16790\platform\Applications
Copying dependencies
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for tenant on localhost\SQLEXPRESS
Exporting Application to CRONUS
Removing Application from tenant
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details.
at <ScriptBlock>, <No file>: line 15
at <ScriptBlock>, <No file>: line 1
New-BcContainer Telemetry Correlation Id: 0fa0e969-b4b9-4d34-b1fa-124131b71dab
Initialization of container BC24 failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.11\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container BC24 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC24 failed
```

**Screenshots**

**Additional context**
- does it happen all the time? yes, for bc24
- did it use to work? no

**Comment by freddydk** [comment]
Can you create the container without the -licensefile parameter?

**Comment by f4n0** [comment]
same error:
Importing CRONUS license file
An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details.

**Comment by f4n0** [comment]
it seems to be using the cmdlets to import the license, and that is failing

**Comment by freddydk** [comment]
I have retried this with the same generic image and settings, and I cannot repro this.
Could you try the same script on a different host machine?

**Comment by f4n0** [comment]
unfortunately yes, different hosts works as excpected. 
I've even deleted all images, flush bcch cache but nothings helps. 

I've also entered the container with powershell and try to load the new module for manage the service. but: 
![image](https://github.com/microsoft/navcontainerhelper/assets/36199751/c6139097-6d05-4493-ad76-de7496d973ed)

hopes this helps

**Comment by freddydk** [comment]
What does
`dotnet --list-runtimes`
show inside the container?

**Comment by f4n0** [comment]
Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by freddydk** [comment]
> unfortunately yes, different hosts works as excpected. I've even deleted all images, flush bcch cache but nothings helps.
> 
> I've also entered the container with powershell and try to load the new module for manage the service. but: ![image](https://private-user-images.githubusercontent.com/36199751/315299956-c6139097-6d05-4493-ad76-de7496d973ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzA4NDcsIm5iZiI6MTcxMTAzMDU0NywicGF0aCI6Ii8zNjE5OTc1MS8zMTUyOTk5NTYtYzYxMzkwOTctNmQwNS00NDkzLWFkNzYtZGU3NDk2ZDk3M2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE0MTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MGU0ZWVlZTFiYTY3MmFhM2JkYWNkNzM2Y2M3Mzk1MzdhNWIyMDQ4YzkzNjdhOTNlM2MzY2JlOTRiMDYzYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qCfiwo_DR01ykaZG5bPyttx45VHwZBMz21HFKsyQP3g)
> 
> hopes this helps

This error is because you are loading the module with PowerShell 5.
You need to run pwsh (use Open-BcContainer) in order to load the module.
This has nothing to do with your original problem.

**Comment by freddydk** [comment]
The original problem might be related to what #3437 is observing

**Comment by freddydk** [comment]
could you (on a failed container) use Get-BcContainerEventlog and submit the event log here?

**Comment by f4n0** [comment]
Type: System.InvalidOperationException Message: An error occurred when creating the WebSocket with the factory of type 'CoreClrClientWebSocketFactory'. See the inner exception for details. Source: System.Private.ServiceModel HResult: -2146233079 StackTrace: at System.ServiceModel.Channels.ClientWebSocketTransportDuplexSessionChannel.CreateWebSocketWithFactoryAsync(X509Certificate2 certificate, TimeoutHelper timeoutHelper) at System.ServiceModel.Channels.ClientWebSocketTransportDuplexSessionChannel.OnOpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade) at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) at generatedProxy_1.OpenAdminConnection(ConnectionRequest) at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Dynamics.Nav.Management.AdminServiceProxy.Invoke(MethodInfo targetMethod, Object[] args) at generatedProxy_2.OpenAdminConnection(ConnectionRequest) at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.DoOpenAdminConnection(IAdminService adminService) at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.OpenAdminConnection() at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.EstablishAdminConnection() at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.InternalValidate() at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord() StackTrace: at System.ServiceModel.Channels.ClientWebSocketTransportDuplexSessionChannel.CreateWebSocketWithFactoryAsync(X509Certificate2 certificate, TimeoutHelper timeoutHelper) at System.ServiceModel.Channels.ClientWebSocketTransportDuplexSessionChannel.OnOpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.OnOpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.OnOpenAsyncInternal(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.System.ServiceModel.IAsyncCommunicationObject.OpenAsync(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.OpenAsyncInternal(TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade) at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout) at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(MethodCall methodCall, ProxyOperationRuntime operation) at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(MethodInfo targetMethod, Object[] args) at generatedProxy_1.OpenAdminConnection(ConnectionRequest) at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor) at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr) at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at Microsoft.Dynamics.Nav.Management.AdminServiceProxy.Invoke(MethodInfo targetMethod, Object[] args) at generatedProxy_2.OpenAdminConnection(ConnectionRequest) at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.DoOpenAdminConnection(IAdminService adminService) at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.OpenAdminConnection() at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.EstablishAdminConnection() at Microsoft.Dynamics.Nav.Management.ServerInstanceConnection.InternalValidate() at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord() ---------------------------------- Type: System.Net.WebSockets.WebSocketException ErrorCode: 0 WebSocketErrorCode: Faulted NativeErrorCode: 0 Message: Unable to connect to the remote server Source: System.Net.WebSockets.Client HResult: -2147467259 StackTrace: at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options) at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken) at System.ServiceModel.Channels.CoreClrClientWebSocketFactory.CreateWebSocketAsync(Uri address, WebHeaderCollection headers, ICredentials credentials, WebSocketTransportSettings settings, TimeoutHelper timeoutHelper) at System.ServiceModel.Channels.ClientWebSocketTransportDuplexSessionChannel.CreateWebSocketWithFactoryAsync(X509Certificate2 certificate, TimeoutHelper timeoutHelper) StackTrace: at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options) at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken) at System.ServiceModel.Channels.CoreClrClientWebSocketFactory.CreateWebSocketAsync(Uri address, WebHeaderCollection headers, ICredentials credentials, WebSocketTransportSettings settings, TimeoutHelper timeoutHelper) at System.ServiceModel.Channels.ClientWebSocketTransportDuplexSessionChannel.CreateWebSocketWithFactoryAsync(X509Certificate2 certificate, TimeoutHelper timeoutHelper) ---------------------------------- Type: System.Net.Http.HttpRequestException HttpRequestError: ConnectionError Message: No connection could be made because the target machine actively refused it. (eos-sprimo1:8083) Source: System.Net.Http HResult: -2147467259 StackTrace: at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options) StackTrace: at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem) at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken) at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken) at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken) at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options) ---------------------------------- Type: System.Net.Sockets.SocketException Message: No connection could be made because the target machine actively refused it. SocketErrorCode: ConnectionRefused ErrorCode: 10061 NativeErrorCode: 10061 Source: System.Net.Sockets HResult: -2147467259 StackTrace: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken) StackTrace: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token) at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken) at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

**Comment by f4n0** [comment]
[log.zip](https://github.com/microsoft/navcontainerhelper/files/14696603/log.zip)

**Comment by freddydk** [comment]
Do you know what this is:
No connection could be made because the target machine actively refused it. (eos-sprimo1:8083)
Is that some kind of proxy server, which the container connects through???

**Comment by f4n0** [comment]
well. 
No, no proxies, no firewall rules
But why does a container, when uploading a license that is in the container FS need to connect to my host, it does not make any sense...

**Comment by freddydk** [comment]
eos-sprimo1 - is that your machine then?
what kind of network configuration are you using for the container?

**Comment by f4n0** [comment]
yes, that is my host. 
default network, the one that bcch will create (suppose a nat)

**Comment by freddydk** [comment]
And any configuration changes - or everything default?
(8083 is not default)

**Comment by freddydk** [comment]
Could you maybe grab customsettings.config and dump here?

**Comment by freddydk** [comment]
Do you have any port mapping or publish ports on the container creation?

**Comment by freddydk** [comment]
please run the following commands and display the output:

docker network ls

docker network inspect nat

**Comment by freddydk** [comment]
Also - anything in C:\ProgramData\Docker\config\daemon. json on the host?

**Comment by f4n0** [comment]
docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
e7ce43e629d9   nat       nat       local
18dce787fb7f   none      null      local

docker inspect nat
[
    {
        "Name": "nat",
        "Id": "e7ce43e629d95c2a5332790259205062ebed9808f781b1e2bd75721a2ea08abb",
        "Created": "2024-03-19T09:27:21.0558196+01:00",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.96.0/20",
                    "Gateway": "172.18.96.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "5b30cb503c42071269ae77d5f00718bc041c1c10653b77225cf3b75761af6d3b": {
                "Name": "BC23",
                "EndpointID": "c24caebb14d014c628b8f90ae1a6051516105a63a977a5a758b70d815b077806",
                "MacAddress": "00:15:5d:72:36:69",
                "IPv4Address": "172.18.103.178/16",
                "IPv6Address": ""
            },
            "d9ae9647a3a4a0f790f5c50db5e31c8bef65b47dcfd3f9deadbe50c47f60586e": {
                "Name": "BC24",
                "EndpointID": "cae6555f0a064616c5be98b01ae7c5d2c7494bf3e89b6e54f1e2e1088c1b5d30",
                "MacAddress": "00:15:5d:72:3f:87",
                "IPv4Address": "172.18.111.237/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "6EDC5DDB-7179-4141-B708-814369AC9432",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }
]
CustomSetting on container
[CustomSettings.txt](https://github.com/microsoft/navcontainerhelper/files/14697336/CustomSettings.txt)


Do you have any port mapping or publish ports on the container creation?
Nothing (the script is the same as the first issue)

Deamon.json
{
  "hosts": [
    "tcp://127.0.0.1:2375",
    "npipe://"
  ],
  "experimental": true
}


BC23 and lower, everything works as usual (never had problems)

**Comment by freddydk** [comment]
and docker inspect BC24

**Comment by f4n0** [comment]
[inspect.txt](https://github.com/microsoft/navcontainerhelper/files/14701293/inspect.txt)

**Comment by freddydk** [comment]
Inside the container, try this:

```
Invoke-RestMethod 'https://download.elifulkerson.com/files/tcping/0.39/x64/tcping64.exe' -outfile tcping64.exe
.\tcping64.exe -4 localhost 7086
```

**Comment by freddydk** [comment]
and...

Try recreating the container with this parameter:   -PublishPorts @(7086)

**Comment by f4n0** [comment]
thanks, but no need. 
I've made it works. 
don't remember when or why but I've set a proxy in docker config (under %userprofile%). 

the strange thing is that it never was a problem for <BC23!

**Comment by freddydk** [comment]
Well, a lot of things have changed in BC24 - including the connection to the admin service.
but... - good to know.

Thanks
