### ISSUE TITLE
Why is containerless compilation not supported for Version < BC16

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#3438]
i understand that bc14 is difficult to support because of the missing symbols, but what is the problem with bc15?

https://github.com/microsoft/navcontainerhelper/blob/f5784320e52bbfe295e717652a82e9c8399ea42d/CompilerFolderHandling/New-BcCompilerFolder.ps1#L57

**Comment by freddydk** [comment]
I believe it is because there are significant changes to the compiler - I cannot remember.
It isn't something I will be interested in pursuing though - there is a workaround - use a container:-)

**Comment by ChrisBlankDe** [comment]
i did not expected an fix, just wondered :)

**Comment by freddydk** [comment]
Yeah sorry, I cannot remember - CompilerFolder was really created in order to be able to compile under Linux - and that definitely doesn't work with older versions (might be the reason)
