### ISSUE TITLE
New-BCContainer:  hcsshim::ExpandScratchSize The system cannot find the file specified. --volume "c:\bcartifacts.cache:c:\dl"

### ISSUE THREAD

**Issue by 4ampro** [microsoft/navcontainerhelper#3440]
**Describe the issue**
The system cannot find the file specified.
This happens with other 'hcsshim' modules as well.
Unable to create container because of this.

**Scripts used to create container and cause the issue**
```
$artifactUrl = Get-BCArtifactUrl -country us -select Latest
$licenseFile = 'C:\Users\_[redacted]_\Downloads\_[redacted]_.bclicense'
$ContainerName = 'Container' #ServerName in launch.json
$UserName = 'admin' 
$Password = ConvertTo-SecureString '_[redacted]_' -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ($UserName, $Password)

New-BCContainer `
    -accept_eula `
    -containerName $ContainerName `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -auth NavUserPassword `
    -updateHosts `
    -Credential $Credential `
    -alwaysPull `
    -includeTestToolkit 
```

**Full output of scripts**
```
BcContainerHelper version 6.0.0
BC.HelperFunctions emits usage statistics telemetry to Microsoft
BcContainerHelper is version 6.0.0
BcContainerHelper is running as administrator
HyperV is Enabled
UsePsSession is True
Host is Microsoft Windows 10 Pro - 10.0.19045.4170
Docker Client Version is 25.0.3
Docker Server Version is 25.0.3
Removing entries from hosts
Removing Container from container hosts file
Removing Container-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\Container
Downloading artifact /sandbox/23.5.16502.17802/us
Downloading C:\Users\_[redacted]_\AppData\Local\Temp\b589a75d-1a3e-4ff2-945f-b84878a5b6a0.zip
Downloading using WebClient
Unpacking artifact to tmp folder using 7zip
Downloading platform artifact /sandbox/23.5.16502.17802/platform
Downloading C:\Users\_[redacted]_\AppData\Local\Temp\0702a883-b98f-4d6b-a09e-712a72646755.zip
Downloading using WebClient
Unpacking platform artifact to tmp folder using 7zip
Downloading Prerequisite Components
Downloading c:\bcartifacts.cache\sandbox\23.5.16502.17802\platform\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading using WebClient
Downloading c:\bcartifacts.cache\sandbox\23.5.16502.17802\platform\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Downloading using WebClient
Fetching all docker images
Fetching all docker volumes
INFO: Windows 10 21H1/21H2 images are not yet available, using 2004 as these are found to work better than 20H2 on 21H1/21H2
Pulling image mcr.microsoft.com/businesscentral:10.0.19041.1415
10.0.19041.1415: Pulling from businesscentral
295f12394c4f: Already exists
24b98dd3fbc4: Already exists
569a4c4f5ea8: Already exists
00dc665dbda6: Already exists
b3101e626b58: Already exists
75d57e33ed30: Already exists
79eeef77f5a9: Already exists
39a1f9b98c68: Already exists
ea5777e5bc5c: Already exists
cf4f64876b4a: Already exists
6f6166a41130: Already exists
6e2ea32c52ee: Already exists
16c75ecf23ce: Already exists
da5c63bc79fd: Already exists
757ce4d289fa: Already exists
Digest: sha256:ebacb499a2fac2cea24f47ebf710a06b177ee02b289c798760f97cf3f79920ab
Status: Downloaded newer image for mcr.microsoft.com/businesscentral:10.0.19041.1415
mcr.microsoft.com/businesscentral:10.0.19041.1415
Using image mcr.microsoft.com/businesscentral:10.0.19041.1415
Creating Container Container
Style: sandbox
Multitenant: Yes
Version: 23.5.16502.17802
Platform: 23.0.17743.0
Generic Tag: 1.0.2.15
Container OS Version: 10.0.19041.1415 (2004)
Host OS Version: 10.0.19045.4170 (22H2)
WARNING: Host OS is Windows 10 21H1 or newer and Container OS is 2004, defaulting to process isolation. If you experience problems, add -isolation hyperv.
Using process isolation
Using locale en-US
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\_[redacted]_\Downloads\7904694 (1).bclicense
Files in C:\ProgramData\BcContainerHelper\Extensions\Container\my:
- AdditionalOutput.ps1
- license.bclicense
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container Container from image mcr.microsoft.com/businesscentral:10.0.19041.1415
New-BCContainer Telemetry Correlation Id: a85a853f-57f6-4124-a826-c7aeb850d644
DockerDo : docker: Error response from daemon: hcsshim::ExpandScratchSize failed in Win32: The system cannot find the file specified. (0x2).
See 'docker run --help'.
ExitCode: 127
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav= --env isBcSandbox=Y --label version=23.5.16502.17802 --label platform=23.0.17743.0 --label country=US --env 
artifactUrl=https://bcartifacts.azureedge.net/sandbox/23.5.16502.17802/us --env multitenant=Y --env licenseFile="c:\run\my\license.bclicense" --name Container --hostname Container --env 
auth=NavUserPassword --env username="admin" --env ExitOnError=N --env locale=en-US --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume "C:\ProgramData\BcContainerHelper\Extensions\Container\my:C:\Run\my" --isolation process --restart 
unless-stopped --env filesOnly=False --env enableApiServices=Y --env useSSL=N --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b16050a5345Mg
B8AEIAdAB5AGgAUQAvAFkAWgBSAGcAaQArAEQAWQBLAEIAQQAxACsAUABXAGcAPQA9AHwAOAA3ADQAMgA0ADgANAA4AGQAOAAxADIAOQA3ADMAMwA4ADcAYgAxADgANQBmADEAOQA2ADEANQA0ADQANgAzADUAMAAyADAAMgBlAGQAMAA4AGUAYQBmAGYA
YgAzADUAYgAyAGQAYwAzAGIAMwBhAGQAOQBhADUAMAAzADAAYQA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach 
mcr.microsoft.com/businesscentral:10.0.19041.1415
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.0\ContainerHandling\New-NavContainer.ps1:1969 char:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo


PS C:\WINDOWS\system32> docker version
Client:
 Cloud integration: v1.0.35+desktop.11
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:13:02 2024
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 20:55:49 2024
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Screenshots**
n/a

**Additional context**
- does it happen all the time? YES
- did it use to work? YES

**Comment by freddydk** [comment]
Please update your containerhelper to the latest version and retry.

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: 4am Productions ***@***.***>
Sendt: Sunday, March 24, 2024 4:07:17 PM
Til: microsoft/navcontainerhelper ***@***.***>
Cc: Freddy Kristiansen ***@***.***>; Assign ***@***.***>
Emne: Re: [microsoft/navcontainerhelper] New-BCContainer: hcsshim::ExpandScratchSize The system cannot find the file specified. --volume "c:\bcartifacts.cache:c:\dl" (Issue #3440)


Assigned #3440<https://github.com/microsoft/navcontainerhelper/issues/3440> to @freddydk<https://github.com/freddydk>.

**Comment by 4ampro** [comment]
Hi Freedy:

### Container Helper: Removing and Installing
PS C:\WINDOWS\system32> Get-NavContainers | Remove-NavContainer
BcContainerHelper version 6.0.11
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.19041.4170
Removing Desktop shortcuts

PS C:\WINDOWS\system32> Uninstall-Module NavContainerHelper -Force -AllVersions
PackageManagement\Uninstall-Package : No match was found for the specified search criteria and module names 'NavContainerHelper'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2194 char:21
+ ...        $null = PackageManagement\Uninstall-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ninstallPackage:UninstallPackage) [Uninstall-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage
 

PS C:\WINDOWS\system32> Install-Module BcContainerHelper -Force

### Error details from Failed due to "bcUniversalCode"

Publishing C:\Applications.US\Microsoft_System Application Test Library_23.5.16502.17817.app
WARNING: This license is not compatible with this version of Business Central.
Sorry, we can't proceed with the operation for app 'System Application Test Library' by 'Microsoft' for tenant 'nav-systemapplication' because the app doesnâ€™t meet our Unive
rsal Code requirement.

You must either upgrade the app to meet the requirement or license the non-Universal Code module that grants an exception to the requirement.

For more information, see https://aka.ms/bcUniversalCode.
[91mInstallation failed
At C:\Run\start.ps1:399 char:9
+         throw "Installation failed"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Installation failed:String) [ 
   ], RuntimeException
    + FullyQualifiedErrorId : Installation failed
 
[0m
New-Bcimage Telemetry Correlation Id: 1f1d99f1-9380-49d7-863f-c6da933cfb77
New-BCContainer Telemetry Correlation Id: b9c27047-086e-413e-84ee-2cc35f53e985
DockerDo : The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; \Run\start.ps1 -installOnly -multitenant 
-includeTestToolkit' returned a non-zero code: 1
ExitCode: 1
Commandline: docker build --isolation=hyperv --memory 8G --no-cache --tag y:sandbox-23.5.16502.17817-us-mt c:\bcartifacts.cache\40s4tvjc.y4g
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.11\ContainerHandling\New-NavImage.ps1:711 char:27
+ ...       if (!(DockerDo -command build -parameters @("--isolation=$isola ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
Now, that is a completely new problem, right?
Sounds like the original problem was fixed and something is wrong with the license file here.
Please retry without the license file and create a new issue with script and full output if the problem persists.

**Comment by 4ampro** [comment]
Will do. And thank you very much.

**Comment by matucan** [comment]
First i got the problem that docker could not start the engine. So i uninstalled and installed it new. First i installed actual bccontainerhelper

then 
docker pull mcr.microsoft.com/windows/servercore:ltsc2019

and then my script

$containername = 'XXX'

$artifactUrl = Get-BCArtifactUrl onprem -country DE -version '25.1' -select Latest

$credential = New-Object pscredential 'XXX', (ConvertTo-SecureString -String 'XXX' -AsPlainText -Force)

$licencefile = 'XXX'

New-BcContainer `
    -accept_eula `
    -containerName $containername `
    -artifactUrl $artifactUrl `
    -Credential $credential `
    -auth UserPassword `
    -updateHosts `
    -includeAL `
    -assignPremiumPlan `
    -multitenant:$false `
    -memoryLimit 8G `
    -licencefile $licencefile
         

but get this

New-BcContainer Telemetry Correlation Id: b46f5795-54ca-49aa-886f-498873d78fa4
DockerDo : docker: Error response from daemon: hcsshim::ExpandScratchSize failed in Win32: Das System kann die angegebene Datei nicht finden. (0x2)
Run 'docker run --help' for more information
ExitCode: 125
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav= --env isBcSandbox=N --label version=25.1.25873.25900 --label platform=25.0.25866.0 --label country=de --env 
artifactUrl=https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/25.1.25873.25900/de --env licenseFile="" --name XXX-25-1 --hostname XXX-25-1 --env auth=NavUserPassword --env username="XXX" --env ExitOnError=N --env 
locale=de-DE --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume "C:\ProgramData\BcContainerHelper\Extensions\XXX-25-1\my:C:\Run\my" --isolation hyperv 
--restart unless-stopped --env filesOnly=False --memory 8G --env enableApiServices=Y --env useSSL=N --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env 
securePassword=76492d1116743f0423413b16050a5345MgB8AGcAWABiAEQAbQBnAFoAZQB0AFQAKwBNAHkAZABKAE8ARABVAFUAaQBBAEEAPQA9AHwANwAyADIAMwBmAGEAYgA2ADgANQAxADQAMwAxAGMANABlADIAYQBiADYANgA1ADAAOQAwADYAMQA1AGYAYQA3AA== --env 
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral:ltsc2019
In C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.19\ContainerHandling\New-NavContainer.ps1:2036 Zeichen:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by left-code** [comment]
I had similar issues with one build server today, switching to **hyperv** isolation was "solution" for me.
