### ISSUE TITLE
sqlcmd with ltsc2019 image errors - blocked by parental controls

### ISSUE THREAD

**Issue by ryanwwhittaker** [Microsoft/navcontainerhelper#346]
Hi,
I've updated my Win10 machine to 1809 and when I run: New-NavContainer -accept_eula -containerName "helloworld-dev" -auth NavUserPassword -imageName "microsoft/bcsandbox:us-ltsc2019" there seems to be an issue with permissions for sqlcmd.
Error I get is: Program 'SQLCMD.EXE' failed to run: The operation was blocked by parental controls.
The container is running and if I execute powershell in the container itself and simply issue 'sqlcmd' I get the same problem.
Forcing the use of ltsc2016 image succeeds without issue.
I'm using 0.5.0.2 navcontainerhelper.
Thanks
Ryan

**Comment by freddydk** [comment]
I must admit that I haven't tried to run docker containers under parental controls.
At best it will just slow down things.
I would see if I could disable this for containers - or maybe run as administrator (if that disables the thing totally).

**Comment by ryanwwhittaker** [comment]
Hi - I haven't done anything to run with parental controls.
Simply pulled latest image and executed the New-NavContainer command.
Perhaps I am missing doing something first?

**Comment by freddydk** [comment]
Based on the number of people who are using the ltsc2019 images on a daily basis on Windows 10, I assume that this is a problem on your setup.
Do you have parental control enabled?
If you could display the output of new-navcontainer, then I can see docker versions and other things.

**Comment by ryanwwhittaker** [comment]
Yes I did think the same thing.  But not sure what I have different.
I've attached the output - let me know if it is not available to you.
[output.txt](https://github.com/Microsoft/navcontainerhelper/files/2859583/output.txt)

**Comment by freddydk** [comment]
could you try to use mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 instead of microsoft/bcsandbox:us-ltsc2019 ?
Maybe your image was corrupted?

**Comment by ryanwwhittaker** [comment]
Tried removing all images and downloading the one you suggested but still same issue unfortunately.

**Comment by freddydk** [comment]
Unfortunately, I am out of options on this

**Comment by ryanwwhittaker** [comment]
No - I'm baffled and not sure where to go with it.
Very strange though that it is inside the container where I have the issue.
Is there any other container with the same base you could recommend which still has SQL at the same level as the BC container and I could see whether it has same errors?
Or any other troubleshooting approach you think I should take?

**Comment by freddydk** [comment]
I have never heard about this problem from anybody else, indicating that it might be something in your setup. Not sure whether other SQL images would hit the same, but you could try a SQL Express image for 1809 here: https://hub.docker.com/r/christianacca/mssql-server-windows-express/ (Microsoft doesn't provide SQL Express images for Windows on Docker).
I am not sure it would prove anything whether it fails or succeeds - but if you want to try, feel free.
In the end, I would reinstall docker or windows - or run Docker on Azure VMs.
Sorry for not being able to help here.

**Comment by ryanwwhittaker** [comment]
Quick update - Using that sql express image you mentioned I can run sqlcmd with no issue in the resultant container.
Guess next stage is either a VM or re-install docker.

**Comment by ryanwwhittaker** [comment]
Docker uninstalled & re-installed.
At least the error on trying to run your Local-sandbox.ps1 from your blog (https://blogs.msdn.microsoft.com/freddyk/2018/11/12/developing-business-central-extensions-part-2/) has changed now though :)
Now getting:
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: No connection could be made because the target machine actively refused it.

**Comment by ryanwwhittaker** [comment]
I think I've tracked it down to a change between version 0.4.2.6 (which works fine) and 0.4.3.0 which gives me the above sqlcmd connection refused error.
ie. I've hardcoded the version to use in the install-navcontinaerhelper.ps1 script and have it all running.

**Comment by freddydk** [comment]
The biggest change there was, that it now defaults to process isolation.
So, you could try to add -isolation hyperv when you run the latest version, then it probably works as well.
Running in hyperv will run inside a mini-VM which means that the host won't check permissions on the file, so that makes sense. (didn't think about that earlier)

**Comment by ryanwwhittaker** [comment]
Spot on!  Thanks Freddy.

**Comment by freddydk** [comment]
Cant believe I didnt think about that before.
It is still something strange with your setup, but thanks for digging deep here - this will be valuable if somebody else runs into the same.
