### ISSUE TITLE
Flush-ContainerHelperCache Deletes Images that Are Currently In Use

### ISSUE THREAD

**Issue by MattTraxinger** [microsoft/navcontainerhelper#3465]
**Describe the issue**
Flush-ContainerHelperCache is deleting images in the middle of pipelines.

Pipeline 1
<img width="278" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/789fa476-e6aa-4ce8-87ad-688228932866">

Pipeline 2
<img width="425" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/839d5912-7566-4627-be8f-080680ce3da4">

I'm guessing this is because the function isn't taking the new URLs into account.

<img width="617" alt="image" src="https://github.com/microsoft/navcontainerhelper/assets/10426547/c5b5d350-d860-4d17-ae8e-89ba17a86885">

If I'm running two pipelines simultaneously, one can finish and delete the image while the other still needs it.

**Scripts used to create container and cause the issue**
Flush-ContainerHelperCache -KeepDays 2

**Additional context**
This failed with the release today.

**Comment by freddydk** [comment]
It calculates the cachefolder wrongly - 6.0.14 will ship asap
