### ISSUE TITLE
Use Image ID Instead of Image Name

### ISSUE THREAD

**Issue by Kushal5** [Microsoft/navcontainerhelper#347]
I have an issue where I installed Business Central Image using New-Navcontainerhelper, I saved the image as a .tar file and loaded it as an image on another machine. The image name is the same as the package for Business Central Sandbox on Docker.

New-NavContainer -containerName MSDYNBC -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/bcsandbox:us -includeCSide -memoryLimit 3G -shortcuts Desktop -updateHosts

The issue is that even if I rename my image to something else, and remove -alwaysPull command:

New-NavContainer -containerName MSDYNBC -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -enableSymbolLoading -imageName testImage -includeCSide -memoryLimit 3G -shortcuts Desktop -updateHosts

This still goes and looks for the microsoft/bcsandbox:us and proceeds to download the entire thing off the internet. Which Is why I am suggested if we could use Image ID instead.

**Comment by freddydk** [comment]
I haven't used docker save before.
What are you trying to achieve here?

**Comment by Kushal5** [comment]
I am trying to reuse the Image(Download it once only). So I setup BC using the command above in one machine. I use docker image save to save the image in a tar file, and then I use docker load to load the image on another machine. I would like then, to use the same command as above to setup BC on that machine. However, instead of using the loaded image, it attempts to pull the image again from the internet. I have even renamed the image name and tags, but somehow it still attempts too pull from the docker package online.

The only solution I can think of is to have support for Image ID in New-NavContainer

**Comment by freddydk** [comment]
New-NavContainer should be able to do this.
Could you paste the output from new-navcontainer here?

**Comment by freddydk** [comment]
The mechanism used to determine whether it should force download the imagename is here:
```
    # Determine best container ImageName (append -ltsc2016 or -ltsc2019)
    $bestImageName = Get-BestNavContainerImageName -imageName $imageName

    if ($useBestContainerOS) {
        $imageName = $bestImageName
    }

    $imageExists = $false
    $bestImageExists = $false
    docker images -q --no-trunc | ForEach-Object {
        $inspect = docker inspect $_ | ConvertFrom-Json
        if ($inspect | % { $_.RepoTags | Where-Object { "$_" -eq "$imageName" -or "$_" -eq "${imageName}:latest"} } ) { $imageExists = $true }
        if ($inspect | % { $_.RepoTags | Where-Object { "$_" -eq "$bestImageName" } } ) { $bestImageExists = $true }
    }

    if (!($alwaysPull)) {
        if ($bestImageExists) {
            $imageName = $bestImageName
        } elseif ($imageExists) {
            Write-Host "NOTE: Add -alwaysPull or -useBestContainerOS if you want to use $bestImageName instead of $imageName."
        } else {
            $alwaysPull = $true
        }
    }
```

**Comment by Kushal5** [comment]
It works now. All I had to do was remove --alwaysPull from my command.
Thanks for your help Freddy.
