### ISSUE TITLE
[Feature Request] Keep SasToken for Get-BcArtifactUrl for custom storage accounts

### ISSUE THREAD

**Issue by lippertmarkus** [microsoft/navcontainerhelper#3484]
**Describe the issue**
We have some very very old legacy projects that currently build their images with New-BcImage based on custom artifacts that reside in our own storage account. To keep using them until the projects finally upgraded we would still need support for SasToken in combination with custom storage accounts.

**Scripts used to create container and cause the issue**
The following doesn't work anymore because sasToken is obsolete with the newest BCCH and is not sent along with the list request against the storage account:

```
Get-BCArtifactUrl -country de -sasToken "<sastoken>" -storageAccount cosmoartifacts -type onprem -version 16.0.1.2 

```

**Full output of scripts**
```
BcContainerHelper is version 6.0.14
Running on Windows, PowerShell 5.1.19041.1320

WARNING: Parameter 'sasToken' is obsolete. sasToken is no longer supported

Error querying artifacts. Error message was The remote server returned an error: (409) Conflict.
...
```

**Screenshots**
Request issued by BCCH:
![image](https://github.com/microsoft/navcontainerhelper/assets/1463140/d15674b3-17ea-4333-bd05-b7cb40c74809)

**Additional context**
- It worked until BCCH 6.0.12 but this version still uses the old CDN for the artifacts and therefore will stop working soon

**Comment by freddydk** [comment]
Hmmm
Why would you have custom artifacts?
Does this include a special database or?

**Comment by lippertmarkus** [comment]
Yes with modified base app

**Comment by freddydk** [comment]
So, you have a full copy of a BC artifact with a replaced database only?
I can reintroduce the sastoken - but it is only a matter of time before we do other things that will break you.
Why don't you just use standard artifacts and supply a .bak file as database?

**Comment by freddydk** [comment]
BTW - I am not removing the Azure CDN on Monday - we have time to find a solution.

**Comment by lippertmarkus** [comment]
I asked the colleagues to try with a bak file instead. It was long before my time at the company when they set up the custom storage account so theres no information anymore as to why they did it this way instead of using baks

**Comment by freddydk** [comment]
Let's setup a call when you have the results of this investigation, thanks.

**Comment by freddydk** [comment]
After discussing this yesterday, the need is not there.
