### ISSUE TITLE
NAV 2016 container, help is not working

### ISSUE THREAD

**Issue by mstjernfelt** [Microsoft/navcontainerhelper#349]
Hi,
Not sure if this is on my end or if you do not support the help section of the product. My question is, is it possible to enable the F1 help using navcontainerhelper?

//Mathias

**Comment by freddydk** [comment]
Unfortunately the Help Server has a dependency on Windows Search, which is a Desktop Feature and cannot run in Containers.
As a result of this (and to save space) help is not included in the containers.
