### ISSUE TITLE
Script to install BcContainerHelper fails

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#3499]
The script in the file "Install-BcContainerHelper.ps1" is failing with the following error:

_Exception calling "DownloadString" with "1" argument(s): "The remote name could not be resolved: 
'bccontainerhelper.azureedge.net'"_

Please do I need to change anything in this script or it is something you can fix from your side?

**Comment by RadoArvay** [comment]
Yes, I wanted to ask the same question. I use the "Hello World" pipeline script to install BCH for few years.
Is there any other path to download BCH directly or we need to use a general way to update PWS module?

**Comment by shashihubgit** [comment]
+1

**Comment by ralf-escher** [comment]
Same problem here.
All our pipelines show this error.

**Comment by BennoVendrig** [comment]
We also have this issue. All pipelines shows this error.

**Comment by freddydk** [comment]
Please replace the URL with bccontainerhelper.blob.core.windows.net instead of bccontainerhelper.azureedge.net

**Comment by ralf-escher** [comment]
Thanks. Is this a temporary solution?

**Comment by freddydk** [comment]
This is a permanent solution.
bccontainerhelper.azureedge.net is no more.

**Comment by freddydk** [comment]
sorry for the inconvenience - I totally forgot that one version of that script used this hostname,

**Comment by BennoVendrig** [comment]
I've changed the path and the pipeline is running again but still in progress. Thanks for the quick response and solution.

**Comment by eclipses** [comment]
I confirm that changing the url from `bccontainerhelper.azureedge.net` to `bccontainerhelper.blob.core.windows.net` fixed the issue.

**Comment by MUR-SDP** [comment]
Thanks very much and apologies for the duplicate.
