### ISSUE TITLE
A Compute System with the specified identifier already exists

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/navcontainerhelper#35]
Hi!

Regularly my nav container does not start at PC startup. 
docker -PS 
doesn't show any lines.

If I then try to start the container manually with 
docker run
It will show me the following error:
Error response from daemon: container 13fc6316941398ee797778dc879b52d3c11d109ada5d716c2dea264317468fb7 encountered an error during CreateContainer: failure in a Windows system call: **A Compute System with the specified identifier already exists.** (0xc037010f) extra info: {"SystemType":"Container","Name":"13fc6316941398ee797778dc879b52d3c11d109ada5d716c2dea264317468fb7","Owner":"docker","LayerFolderPath":"D:\\docker\\windowsfilter\\13fc6316941398ee797778dc879b52d3c11d109ada5d716c2dea264317468fb7","Layers":[{"ID":"1968356f-3168-5169-8c20-ee548f8260f6","Path":"D:\\docker\\windowsfilter\\8a7f19adf5a01381cf0d5152bb250cf38ede38d348527b434362843376637c40"},{"ID":"6adb6b18-ff4d-515c-b4d1-01478a5f5ee3","Path":"D:\\docker\\windowsfilter\\33a0cc365dc61989354e28acfd10688b18037b0cac4b8dc912b2d5ca63baf8e4"},{"ID":"2333c8fc-4bc3-5c98-bbb3-86f149e770ca","Path":"D:\\docker\\windowsfilter\\1435d89641c6a3f6adf5a00754767950c9e4da5a8cab92f1203b11b5d02f7cb1"},{"ID":"e5ecbda8-fd69-5390-9b2f-0c4ba608c188","Path":"D:\\docker\\windowsfilter\\a9654a0f8008db59def853a60cf0aea5aa293afd295fe6ae3869e842dab68b9c"},{"ID":"a418b7b8-d05c-511c-b63e-0222c7d98e07","Path":"D:\\docker\\windowsfilter\\d5a59aa9ca9a762229938b290006887706b9f1ebf7b876376db4d62e4e93ecb2"},{"ID":"309f9bf5-7208-5897-826f-d0fe6d07d863","Path":"D:\\docker\\windowsfilter\\6f48a8b49e1aed714f40d463d6ec164622d0e212cee85adc00f7614eb3877051"},{"ID":"f27125a3-0f40-5701-9b60-ee5c8e6f129e","Path":"D:\\docker\\windowsfilter\\10eb35a174d9fa860b104581b7c0928ae2f51f9bf00f92d8cb5a6fb0301adf83"},{"ID":"d829d8bf-3885-5b9e-a1a6-48b56982c830","Path":"D:\\docker\\windowsfilter\\cdad5b7ddbafdf400adf1d888dbd5ec1669a3d65569eab0e1bef60d1bcfa4426"},{"ID":"6086f294-9726-51e7-84d9-bb8cfcb7ead5","Path":"D:\\docker\\windowsfilter\\630f6c8976c24242c88fa06237e039d614822b4988ff4019896aadd7af814f99"},{"ID":"3170e737-2881-5a9d-bf9b-a7b5fc17eff6","Path":"D:\\docker\\windowsfilter\\d3239028e69ccbbcba96cd4fbcd26be0f2964cf008c3ee2dc5d22b2d2cf39268"},{"ID":"762e9134-4b76-533f-ad41-2c8477cae6f1","Path":"D:\\docker\\windowsfilter\\22acd897447a74de03f01a165db6f176e8845d05f0c0f097399a524c36830260"},{"ID":"25e63007-997c-5131-84b5-02f5ffd09be6","Path":"D:\\docker\\windowsfilter\\27471078466e6e5d64eab310d9ad1d21bb1d6bd16f679931502af8a0378ae296"},{"ID":"189bda4e-7403-52a6-9a8c-73600a414f25","Path":"D:\\docker\\windowsfilter\\d34cf91f2c847e5aafcd4ae199ae7568c9cb52097465f474c0c40648d356d40f"},{"ID":"7d4ade06-d6dc-5b8a-ac78-9e2b95074493","Path":"D:\\docker\\windowsfilter\\3178f79e27ccd19e65111e6bec407e1a6964373132520b245133c8e138fea331"},{"ID":"448ba8fa-fdb9-5c4f-b40b-24851316980b","Path":"D:\\docker\\windowsfilter\\85fe2ef3efeecad781e0eef1f7b19b8b04d1d5a3545062f4f097377819301573"},{"ID":"0962762f-5a1b-5b22-96f9-4cff5b57113d","Path":"D:\\docker\\windowsfilter\\371f2d837d2de3ca990f69f30c281ff8ef403bdc90df9fef5fb1140ce12f9fb8"},{"ID":"18fa76fa-f052-583d-8eec-9bbbb70fb784","Path":"D:\\docker\\windowsfilter\\145917a557d39d75a5676404cb0aef87b2f770be3cf6421e9bc9941e72ce417d"},{"ID":"13faaaa7-dcc1-5fa6-bb76-8a0ba669f66d","Path":"D:\\docker\\windowsfilter\\95034761ddce7c0857c7713eeb32432ecdc404f3ea2e21fd06badaa5ff083575"}],"MemoryMaximumInMB":4096,"HostName":"NavContainer","MappedDirectories":[{"HostPath":"c:\\demo\\extensions\\navcontainer\\program files","ContainerPath":"c:\\navpfiles","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\demo","ContainerPath":"c:\\demo","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\demo\\extensions\\navcontainer\\my","ContainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true,"EndpointList":["e7c2fc1b-913d-445d-8a5e-367fbe1442ea"],"HvRuntime":{"ImagePath":"D:\\docker\\windowsfilter\\145917a557d39d75a5676404cb0aef87b2f770be3cf6421e9bc9941e72ce417d\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}
Error: failed to start containers: 13fc

If I now reboot, usually the container is started together with docker at startup.
I cannot figure out what is the "Compute system" which already exists. Any ideas?

Thanks

**Comment by freddydk** [comment]
docker ps
or 
docker ps -a
(no such thing as docker -ps)

**Comment by janhofmann24** [comment]
Sorry, yes that is what I am doing. 
docker PS

You could also say the symptoms are that none of the ways of accessing the container is working.

**Comment by freddydk** [comment]
Did you try docker ps -a (to see whether there is a dead container)?

**Comment by RafaelKoch** [comment]
Do you stop your containers before shutting down Windows? I learned the hard way that this seems to break my containers if I don't. Since I figured that out I always make sure to stop them before shutdown and all is well next time I start them.

**Comment by Koubek** [comment]
@RafaelKoch Yes, I have seen this problem already before as well. It looks like some handles remain active etc.

**Comment by janhofmann24** [comment]
Yes, docker PS -a shows the not started container.

So far I am not stopping the container when i shut down windows. That might be a good tip. I will try if it helps.

**Comment by freddydk** [comment]
you can remove the stopped container with 
docker rm <id> -f
or start it using
docker start <id>
If you try to create another one with the same name - you will have issues.
The navcontainerhelper will automatically remove the old container for you when using the same name (that of course could be dangerous, but the idea is that NAV Containers never contain any important data).

**Comment by freddydk** [comment]
the navcontainerhelper btw. will set the restart option to always - meaning that the container will restart on windows restart.

**Comment by Koubek** [comment]
@freddydk I would use `unless-stopped` instead.
