### ISSUE TITLE
new-navcontainer with local SQL not working

### ISSUE THREAD

**Issue by tommyb1987** [Microsoft/navcontainerhelper#350]
When i try to create a new Navcontainer using the script below it all works.

New-NavContainer -containerName NAV2016-cu1-be  -accept_eula -accept_outdated  -assignPremiumPlan -auth Windows -clickonce -doNotExportObjectsToText -enableSymbolLoading -imageName microsoft/dynamics-nav:2016-cu1-be  -includeCSide -includeTestLibrariesOnly -includeTestToolkit -multitenant -navDvdCountry BE

BUT:
If I use the same script with my local SQL and add the parameters -databaseCredential sa -databaseInstance Docker -databaseName TestContainer -databaseServer Test-Laptop  

The Database instance is running on an SQL 2016 version. The Database is a database that exissets on the SQL instance but even if the database does not exisist the error is the same.

Error:

Import Encryption Key
Cannot establish a connection to the SQL Server/Database. 
  
This could be due to one of the following reasons:

* The SQL server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 122
at <ScriptBlock>, C:\Run\navstart.ps1: line 108
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container NAV2016-cu1-be failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.2\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...6-cu1-be failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container NAV2016-cu1-be failed

* The SQL server is not started. --> is started + the SQL Browser is up
* The database does not exist. --> even if it exists same error
* Proper permissions have not been given to the NAV Server Account. --> SA user so the SQL server should be aprochable.

**Comment by freddydk** [comment]
Your container probably cannot see your host computer on the network - or your machine has a firewall preventing the container to connect to SQL.
You can run a standard windows server container and see if you can ping the host computer or invoke SQL statements towards it.
