### ISSUE TITLE
Invoke-ScriptInBcContainer fails with error message "The variable '$containerFile' cannot be retrieved because it has not been set"

### ISSUE THREAD

**Issue by ajkauffmann** [microsoft/navcontainerhelper#3507]
**Describe the issue**
Invoice-ScriptInBcContainer fails with an error message "The variable '$containerFile' cannot be retrieved because it has not been set". This happens when it tries to use a session to invoke a script, but it fails because of not using SSL. Then the parameter $useSession is set to false, but the variables $file and $containerFile are not set anymore because they are only set in the beginning when $useSession is false. See screenshots below for a detailed explanation.

Version 6.0.16-preview1186

**Screenshots**
![image](https://github.com/microsoft/navcontainerhelper/assets/19155831/527a638b-4ba9-4834-945a-07a5a20e2b68)
![image](https://github.com/microsoft/navcontainerhelper/assets/19155831/301c7083-b9e5-4a8f-be6f-21d53857a414)

**Additional context**
![image](https://github.com/microsoft/navcontainerhelper/assets/19155831/b1d48ff1-94db-4660-89cf-d1744e2aa0ab)
![image](https://github.com/microsoft/navcontainerhelper/assets/19155831/ecd5c6f6-20e7-4f83-9b03-845fcb1a4f15)

In the pictures above:
* If $useSession is true, then lines 34 en 35 are not executed.
* Then line 43 will be executed, but this may fail (for example when SSL is not enabled)
* Then on line 52 $useSession is set to false
* But now it goes straight to line 114 where it fails because $containerFile is not set

I fixed it by adding those two lines (a little bit dirty, but it works):
![image](https://github.com/microsoft/navcontainerhelper/assets/19155831/0ce369b0-a342-44ef-b161-66dab06de7cf)

**Comment by freddydk** [comment]
Thanks @ajkauffmann - will fix asap.

**Comment by freddydk** [comment]
I have moved the lines later - as I might in the future have other situations where I revert from a session... - but thanks for the suggestion.

**Comment by freddydk** [comment]
Fixed in the latest preview
