### ISSUE TITLE
Create BC Sandbox

### ISSUE THREAD

**Issue by kalyankandimalla** [Microsoft/navcontainerhelper#351]
Hi,
I've tested "Host Locally" option for Container Sandbox Environment creation on Business Central Online.

1. In BC Online I go to >Search> Container Sandbox Environment (Preview) > Host Locally > Downloaded CreateBCSandbox.ps1 script
2. I've changed $accept_eula = $true
3. I've changed $containername = 'BCSandbox'
4. When I run script image, container gets created, installed
5. When i navigate to 'System Information' in Business Central the version is 13.2.27692 but the script installs BC Cu3 version.

I even tried pulling the image using 'microsoft/bcsandbox:13.2.27692-nl' and 'microsoft/bcsandbox:13.2.27692:nl' but not able to find the image

Even the build was not available in the list below.
https://mcr.microsoft.com/v2/businesscentral/sandbox/tags/list

Please help me on this issue

**Comment by freddydk** [comment]
We do not have all images available as containers - and if the specific image isn't available - it will just grab the latest version.

**Comment by kalyankandimalla** [comment]
Thanks Freddy.
Since it is pulling the available latest image, and not the specific one , we are not able to resolve intelligent cloud , schema issues.

**Comment by kalyankandimalla** [comment]
we have to make the schema equal in on premise to the one in BC sandbox.
don't know how we can resolve schema issues with intelligent cloud setup

**Comment by freddydk** [comment]
Docker is for development and test - not really for connecting to intelligent cloud setups.
Having said that, I do not know how you would achieve what you are looking for. I don't think docker is the answer, sorry.
(Did anybody tell you that or suggest that?)

**Comment by kalyankandimalla** [comment]
We are not making intelligent cloud connection using docker, but based on the image, container that is downloaded, we want to use the objects from that version and want to make the schema equal.

https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2019/01/02/troubleshooting-the-intelligent-cloud

we have used above link where it suggests us to bring each side to the same Business Central version. We are now having issues which are equal to the ones specified in the above link under section 'The schema does not match'

**Comment by freddydk** [comment]
Thanks. I will have a chat with Zech and see what we can do for you

**Comment by NAVspecialist** [comment]
The intelligent cloud functionality was made to move data from an OnPremise to Cloud.  And No-one would ever advice you to run an OnPremise installation using Docker! As Freddy says it is for Development and test only.. And it has been like this right from the start.

So your one and only solution for Intelligent Cloud Issue is to have a "real" installation of 365 BC and use that with you Intelligent Cloud. The right procedure, at least in my opinion is to download an "ISO-image" and install that one.

**Comment by kalyankandimalla** [comment]
Hi Freddy, Any update after your check with Zech.
We are trying to find a way in pulling an image which is equal to our BC Online. Creating a Container Sandbox Environment (Preview) locally does not help us. From 'System Information' I see we are on version 13.3(28820). How can we pull that specific image, container?
![system information bc saas 08032019](https://user-images.githubusercontent.com/29648396/54025514-c66bf180-41c0-11e9-8eba-9719641cb597.JPG)

The image is not in the list 
https://mcr.microsoft.com/v2/businesscentral/sandbox/tags/list

When our image is not listed , how can we extract a extension specific to our BC online version.

**Comment by freddydk** [comment]
The requirement to have exactly matching schemas should be lifted with the spring release.
I think your best option would be to wait for that.
At the same time we also strive at having docker images for more builds.

**Comment by kalyankandimalla** [comment]
Thanks for the update

**Comment by freddydk** [comment]
Spring release has been shipped, assuming that you can use that.
