### ISSUE TITLE
Can't start instance because of NavMetadataNotFoundException: Exception: NavMetadataNotFoundException The metadata object Table 27 was not found"

### ISSUE THREAD

**Issue by elweilando** [Microsoft/navcontainerhelper#352]
But I can't start the microsoft/dynamics-nav:2018-cu12-fi instance because of Message (NavMetadataNotFoundException): Exception: NavMetadataNotFoundException
The metadata object Table 27 was not found.

Table 27 is not compiled. I need to compile table 27 and do a schema sync.

I try to start the container in powershell session with Start-NAVServerInstance, but the instance will terminated immedealtiy. neither Compile-NavApplicationObject nor Sync-NavTenant works therefor. 

I set Set-NAVServerConfiguration NAV -KeyName CompileBusinessApplicationAtStartup -KeyValue false but that has no effect.

How can I fix this?

**Comment by freddydk** [comment]
How did you get into this situation?

**Comment by elweilando** [comment]
I had imported some objetcs as textfiles in my database. The "build application server objects" function left the TAB27 as error. the database need a schema sync because of the changes in the textfile.

I overlooked this error before I have shutdown the container. 

Now, I dont't have neighter the option to start the server, nor to compile this object.

**Comment by freddydk** [comment]
And you cannot open the classic client and compile the objects there?
Or create a new container?

**Comment by elweilando** [comment]
> I overlooked this error before I have shutdown the container.
That was wrong. I haven't shutdown the container. I have shutdown the Host of the container. After the start of the Host, the container was running again, but I can't start the instance.

Now, if I try to restart the container, I get the same issue during startup and the container doesn't exist.
I can start the container, if I remove the database and use the local container database.

I can start the classic client and I can connect to the custom database (AzureSQl SqlUserName + Password). I can save the object. But I can't compile the object from classic client. If I try to compile, classic clients tells me that no instance is available.

**Comment by freddydk** [comment]
I would remove the container and start a new one - importing the objects again.
I don't even know how you would get around this issue in a non-docker environment.

**Comment by elweilando** [comment]
I have now started a new container and I have connect the classic client from the new container to the AzureSQL Database. If I try to import the TAB27 as fob again, I get the same message, that no instance is available.

Same, if I try to import the fob with powershell

`Import-NAVApplicationObject -Path TAB27.fob -DatabaseName XXX -DatabaseServer YYY -Username User -Password password -ImportAction Overwrite  `

`Import-NAVApplicationObject : : [27590710] Unable to process table changes because the Microsoft Dynamics NAV Development Environment cannot connect to the specified Microsoft Dynamics NAV Server instance:`

> I don't even know how you would get around this issue in a non-docker environment.

In development it should not be a problem. but what happen, if this occurs in production?

Is it really the only way to drop the database, create a new one and importing the objects? What about the data in the tables?

Or Is there any option to start an instance without these metadata-checks?

**Comment by freddydk** [comment]
Sorry, I don't know.
I can asure you that people cannot import text files with objects to our Business Central SaaS environments, and we do not recommend people to do this on production environments either.
Lastly - I don't think this is related to docker at all, right?

**Comment by elweilando** [comment]
You're right, this is not related to docker. 
Thank you for your quick replies.
