### ISSUE TITLE
BUSINESS CENTRAL ADMIN

### ISSUE THREAD

**Issue by atay-afk** [microsoft/navcontainerhelper#3533]
Hey Freddy, thank you for this script it helps a lot i started learning al and im  using this container.
I have two questions; why my instance have a status stopped? when trying to start it i got  an error. And the second question is why the instance date is 2026? i think i cant call APIs with a wrong instance date.

i just started learning about BC, thank you for the clarification !

**Comment by freddydk** [comment]
Not sure what you mean with instance date?
And... - there might be a million reasons why a server instance has stopped - you would probably find the reason in the event log (which you can get from the container using Get-BcContainerEventLog)
