### ISSUE TITLE
New-AppSourceSubmission is missing out option to upload update/new testApp?

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/navcontainerhelper#3535]
I was reading through document for AppSource submission
https://freddysblog.com/2022/09/22/automatic-appsource-submission-of-business-central-apps/

And I noticed when submitting a new App I can upload my library apps but not the test app.
Am I missing something here, or should I do this still manually?

**Comment by freddydk** [comment]
Test apps are not being used by appsource validation and as such are not needed.

**Comment by RonKoppelaar** [comment]
Clear.
