### ISSUE TITLE
Publish-AppSource submission is throwing unexpected error

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/navcontainerhelper#3536]
I'm publishing app to appsource with following command:
New-AppSourceSubmission -authContext $AuthContext -productId $Product.id -appFile "C:\Users\ronkoppe\Downloads\Zig_Zig365 Insights Connector_23.23.0.1.app" 

Which fails with following error:
Unexpected error when trying to get status for submission. Please consult Partner Center UI.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppSource\New-AppSourceSubmission.ps1:255 char:17
+ ...             throw "Unexpected error when trying to get status for sub ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unexpected erro...tner Center UI.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unexpected error when trying to get status for submission. Please consult Partner Center UI.

Inspecting UI, I could see the new version of the app was published though. But the validation process was not re-triggered. Its still in error stage from previous deploy (manually).

Full log file:
PS C:\Windows\system32> New-AppSourceSubmission -authContext $AuthContext -productId $Product.id -appFile "C:\Users\ronkoppe\Downloads\Zig_Zig365 Insights Connector_23.23.0.1.app" 
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/setup
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions/1152921505697720674
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/branches/getByModule(module=Package)
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packageConfigurations/getByInstanceID(instanceID=e4d75488-f9e7-4780-9c0a-ce4cbf3ae5
2d)
POST https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packages
{
    "fileName":  "Zig_Zig365 Insights Connector_23.23.0.1.app",
    "resourceType":  "Dynamics365BusinessCentralAddOnExtensionPackage"
}
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packages/c3da668d-418c-4e4a-a060-bfe7859904a6
{
    "id":  "c3da668d-418c-4e4a-a060-bfe7859904a6",
    "fileName":  "Zig_Zig365 Insights Connector_23.23.0.1.app",
    "fileSasUri":  "https://ingestionpackagesprod1.blob.core.windows.net/file/3045084131585211525?sv=2018-03-28\u0026sr=b\u0026sig=HglCo4KSGbT5cF6VaCHq1DNBQLNILPyUF%2FArMd6lj2s%3D\u0
026se=2024-05-10T19%3A28%3A46Z\u0026sp=rwl",
    "resourceType":  "Dynamics365BusinessCentralAddOnExtensionPackage",
    "state":  "Uploaded",
    "@odata.etag":  "\"0b00fb8a-0000-0800-0000-663d206a0000\""
}
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packageConfigurations/e4d75488-f9e7-4780-9c0a-ce4cbf3ae52d
{
    "resourceType":  "Dynamics365BusinessCentralPackageConfiguration",
    "@odata.etag":  "\"bd00ac9e-0000-0800-0000-663d19380000\"",
    "packageType":  "AddOn",
    "id":  "e4d75488-f9e7-4780-9c0a-ce4cbf3ae52d",
    "packageReferences":  [
                              {
                                  "value":  "c3da668d-418c-4e4a-a060-bfe7859904a6",
                                  "type":  "Dynamics365BusinessCentralAddOnExtensionPackage"
                              }
                          ]
}
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/branches/getByModule(module=Property)
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/properties/getByInstanceID(instanceID=ce8adb7f-9935-6db8-69bd-8f7188c53e96)
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/properties/ce8adb7f-9935-6db8-69bd-8f7188c53e96
{
    "resourceType":  "AzureProperty",
    "hideKeys":  [

                 ],
    "categories":  [

                   ],
    "leveledCategories":  {
                              "OperationsSupplyChain":  [
                                                            "planning-purchasing-reporting"
                                                        ]
                          },
    "extendedProperties":  [

                           ],
    "@odata.etag":  "\"0500f3ce-0000-0800-0000-663d193a0000\"",
    "useEnterpriseContract":  false,
    "globalAmendmentTerms":  "",
    "id":  "ce8adb7f-9935-6db8-69bd-8f7188c53e96",
    "leveledIndustries":  {
                              "ProfessionalServices":  [
                                                           "RealEstate"
                                                       ]
                          },
    "termsOfUse":  "",
    "applicableProducts":  [

                           ],
    "industries":  [

                   ],
    "productTags":  [

                    ],
    "marketingOnlyChange":  false,
    "additionalCategories":  [

                             ],
    "appVersion":  "23.23.0.1",
    "submissionVersion":  "",
    "customAmendments":  [

                         ]
}
POST https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions
{
    "resources":  [
                      {
                          "type":  "Package",
                          "value":  "e4d75488-f9e7-4780-9c0a-ce4cbf3ae52d"
                      },
                      {
                          "type":  "Property",
                          "value":  "ce8adb7f-9935-6db8-69bd-8f7188c53e96"
                      }
                  ],
    "targets":  [
                    {
                        "type":  "Scope",
                        "value":  "preview"
                    }
                ],
    "resourceType":  "SubmissionCreationRequest"
}
New-AppSourceSubmission Telemetry Correlation Id: 5c369659-ebb9-4c31-84a8-5e54125c2c62
Unexpected error when trying to get status for submission. Please consult Partner Center UI.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppSource\New-AppSourceSubmission.ps1:255 char:17
+ ...             throw "Unexpected error when trying to get status for sub ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unexpected erro...tner Center UI.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unexpected error when trying to get status for submission. Please consult Partner Center UI.
 
Output in UI:
![image](https://github.com/microsoft/navcontainerhelper/assets/33791875/a5bb6f39-5110-4ac7-adf3-584e4934a56f)

Output in UI still shows the date 7/5 which is the moment I submitted previous version.

**Comment by RonKoppelaar** [comment]
Also tried with nowait option then the cmdlet succeeded.
resourceType       : Submission
state              : InProgress
substate           : InDraft
targets            : {@{type=Scope; value=Preview}}
resources          : {@{type=Package; value=e4d75488-f9e7-4780-9c0a-ce4cbf3ae52d}, @{type=Property; value=ce8adb7f-9935-6db8-69bd-8f7188c53e96}}
publishOption      : @{releaseTimeInUtc=0001-01-01T00:00:00; isManualPublish=False; isAutoPromote=False}
publishedTimeInUtc : 1601-01-01T00:00:00Z
pendingUpdateInfo  : @{updateType=Create; status=Running}
releaseNumber      : 1
friendlyName       : Submission 1
areResourcesReady  : True
id                 : 1152921505697732943

But when try getting the info from submission it still gives the resullt of the manual action
PS C:\Windows\system32> Get-AppSourceSubmission -authContext $authcontext -productId $Product.id -includeWorkflowDetails
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions/1152921505697720674
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions/1152921505697720674/workflowdetails


resourceType       : Submission
state              : InProgress
substate           : Failed
targets            : {@{type=Scope; value=Preview}}
resources          : {@{type=Availability; value=460b1b7f-4aa9-6eee-0731-3aa5c61f84da}, @{type=Listing; value=7f287f92-8093-4d04-e9a0-ff497b49441e}, @{type=Package; 
                     value=575518d8-7fb9-4390-8334-93d94dab922b}, @{type=Property; value=8a8d7c24-ba1f-6799-0c92-54ca4511a806}...}
publishedTimeInUtc : 1601-01-01T00:00:00Z
pendingUpdateInfo  : @{updateType=Create; status=Completed}
releaseNumber      : 1
friendlyName       : Submission 1
areResourcesReady  : True
id                 : 1152921505697720674
WorkflowDetails    : {@{type=Push; state=Failed; targetEnvironment=Preview; workflowSteps=System.Object[]; startDateTimeInUtc=2024-05-07T13:45:19.6062639; 
                     completeDateTimeInUtc=2024-05-07T13:49:35.9167391}, @{type=Push; state=NotStarted; targetEnvironment=Live; workflowSteps=System.Object[]; 
                     startDateTimeInUtc=0001-01-01T00:00:00; completeDateTimeInUtc=0001-01-01T00:00:00}}

**Comment by freddydk** [comment]
Assuming that you are trying to submit a new version (new version number and .app file)?
Did you try to submit the new version in the UI?

**Comment by RonKoppelaar** [comment]
I tried publish and review through UI which succeeded
![image](https://github.com/microsoft/navcontainerhelper/assets/33791875/06bc9110-0d6c-4c3f-80b3-bd16a3079f8c)

The app file ending with .1 was published using the API
After pressing review and publish button, it started the validation workflow again
![image](https://github.com/microsoft/navcontainerhelper/assets/33791875/1056dc13-b746-4673-bccf-3586f0c63948)

**Comment by freddydk** [comment]
Sorry - but this is very confusing - not sure what is failing and what not.

If you create a new version of the app and submit that with the command with -nowait
Does the command fail?
Does the app get validated and end up in the preview state?

Then create a new version of the app and submit without -nowait - and same questions?

**Comment by RonKoppelaar** [comment]
Rebuild the app (Version 23.23.0.2) without signing so it should fail as part of the workflow. But I guess that shouldnt matter for the test case as the problem is the workflow is not triggered. 

**Scenario 1 - Publish with option Wait**
```
New-AppSourceSubmission -authContext $AuthContext -productId $Product.id -appFile "C:\Users\ronkoppe\Downloads\Zig_Zig365 Insights Connector_23.23.0.2.app" 
```

**Comment by RonKoppelaar** [comment]
Rebuild the app to version "23.23.0.3"

Scenario 2 - With option doWait
```
New-AppSourceSubmission -authContext $AuthContext -productId $Product.id -appFile "C:\Users\ronkoppe\Downloads\Zig_Zig365 Insights Connector_23.23.0.3.app" -doNotWait -Verbose

GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/setup
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions/1152921505697735884
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/branches/getByModule(module=Package)
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packageConfigurations/getByInstanceID(instanceID=6f3c3add-8779-4e8c-ba18-15cd47fba1
f8)
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
POST https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packages
{
    "fileName":  "Zig_Zig365 Insights Connector_23.23.0.3.app",
    "resourceType":  "Dynamics365BusinessCentralAddOnExtensionPackage"
}
VERBOSE: POST with -1-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
VERBOSE: Transfer Summary
--------------------------------
Total:  1.
Successful: 1.
Failed: 0.
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packages/baf9975a-f428-4c86-964d-536db54cd8e5
{
    "id":  "baf9975a-f428-4c86-964d-536db54cd8e5",
    "fileName":  "Zig_Zig365 Insights Connector_23.23.0.3.app",
    "fileSasUri":  "https://ingestionpackagesprod1.blob.core.windows.net/file/3033989778139423888?sv=2018-03-28\u0026sr=b\u0026sig=1awMgLf4TEsfhSpEnnYs8MjKOzmOLx5uGQvjpPpSg0o%3D\u002
6se=2024-05-12T09%3A17%3A10Z\u0026sp=rwl",
    "resourceType":  "Dynamics365BusinessCentralAddOnExtensionPackage",
    "state":  "Uploaded",
    "@odata.etag":  "\"6f0038fa-0000-0800-0000-663f34120000\""
}
VERBOSE: PUT with -1-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/packageConfigurations/6f3c3add-8779-4e8c-ba18-15cd47fba1f8
{
    "resourceType":  "Dynamics365BusinessCentralPackageConfiguration",
    "@odata.etag":  "\"0e00b5fb-0000-0800-0000-663f30360000\"",
    "packageType":  "AddOn",
    "id":  "6f3c3add-8779-4e8c-ba18-15cd47fba1f8",
    "packageReferences":  [
                              {
                                  "value":  "baf9975a-f428-4c86-964d-536db54cd8e5",
                                  "type":  "Dynamics365BusinessCentralAddOnExtensionPackage"
                              }
                          ]
}
VERBOSE: PUT with -1-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/branches/getByModule(module=Property)
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/properties/getByInstanceID(instanceID=03f22c29-8b1e-3e41-5f3a-a6f535125762)
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
PUT https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/properties/03f22c29-8b1e-3e41-5f3a-a6f535125762
{
    "resourceType":  "AzureProperty",
    "hideKeys":  [

                 ],
    "categories":  [

                   ],
    "leveledCategories":  {
                              "OperationsSupplyChain":  [
                                                            "planning-purchasing-reporting"
                                                        ]
                          },
    "extendedProperties":  [

                           ],
    "@odata.etag":  "\"1700e46a-0000-0800-0000-663f30370000\"",
    "useEnterpriseContract":  false,
    "globalAmendmentTerms":  "",
    "id":  "03f22c29-8b1e-3e41-5f3a-a6f535125762",
    "leveledIndustries":  {
                              "ProfessionalServices":  [
                                                           "RealEstate"
                                                       ]
                          },
    "termsOfUse":  "",
    "applicableProducts":  [

                           ],
    "industries":  [

                   ],
    "productTags":  [

                    ],
    "marketingOnlyChange":  false,
    "additionalCategories":  [

                             ],
    "appVersion":  "23.23.0.3",
    "submissionVersion":  "",
    "customAmendments":  [

                         ]
}
VERBOSE: PUT with -1-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
POST https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions
{
    "resources":  [
                      {
                          "type":  "Package",
                          "value":  "6f3c3add-8779-4e8c-ba18-15cd47fba1f8"
                      },
                      {
                          "type":  "Property",
                          "value":  "03f22c29-8b1e-3e41-5f3a-a6f535125762"
                      }
                  ],
    "targets":  [
                    {
                        "type":  "Scope",
                        "value":  "preview"
                    }
                ],
    "resourceType":  "SubmissionCreationRequest"
}
VERBOSE: POST with -1-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8
New AppSource submission created


resourceType       : Submission
state              : InProgress
substate           : InDraft
targets            : {@{type=Scope; value=Preview}}
resources          : {@{type=Package; value=6f3c3add-8779-4e8c-ba18-15cd47fba1f8}, @{type=Property; value=03f22c29-8b1e-3e41-5f3a-a6f535125762}}
publishOption      : @{releaseTimeInUtc=0001-01-01T00:00:00; isManualPublish=False; isAutoPromote=False}
publishedTimeInUtc : 1601-01-01T00:00:00Z
pendingUpdateInfo  : @{updateType=Create; status=Running}
releaseNumber      : 1
friendlyName       : Submission 1
areResourcesReady  : True
id                 : 1152921505697738991
```

First step inspecting the submission instance based on ID 1152921505697738991
Get-AppSourceSubmission -authContext $authcontext -productId $Product.id -includeWorkflowDetails -submissionId 1152921505697738991
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions/1152921505697738991
GET https://api.partner.microsoft.com/v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions/1152921505697738991/workflowdetails


resourceType       : Submission
state              : InProgress
substate           : InDraft
targets            : {@{type=Scope; value=Preview}}
resources          : {@{type=Package; value=6f3c3add-8779-4e8c-ba18-15cd47fba1f8}, @{type=Property; value=03f22c29-8b1e-3e41-5f3a-a6f535125762}}
publishedTimeInUtc : 1601-01-01T00:00:00Z
pendingUpdateInfo  : @{updateType=Create; status=Failed; href=v1.0/ingestion/products/07dfa796-4234-4c06-9254-f8286cfb1a69/submissions/1152921505697738991/validations; 
                     failureReason=Active validation errors}
releaseNumber      : 1
friendlyName       : Submission 1
areResourcesReady  : True
id                 : 1152921505697738991
WorkflowDetails    : {}

Next I validate the UI to see if the validation process was triggered:
![image](https://github.com/microsoft/navcontainerhelper/assets/33791875/bb48a2a9-e541-4703-abe9-4fb5f91c29e8)

Still on 10th of May. So no validation was triggered. At least not visible in UI

Checked the App Version:
![image](https://github.com/microsoft/navcontainerhelper/assets/33791875/d34fe556-2c70-4f29-b92f-0966a6c58acf)

New version was published as draft

**Comment by freddydk** [comment]
So, wait or not wait doesn't have any influence on the end result - in both cases, the app is uploaded but it doesn't trigger the actual validation.

The parameter is called -doNotWait.

When you say without the wait option, I assume that you mean without -doNotWait - i.e. you are actually waiting for completion of the submission.

Meaning that the error occurs during the wait for the submission somehow - right?

This is probably not something I will be able to debug myself. There seem to be some kind of hick-up in the offer in partner center. If you do not have any customers live on this app yet - it would be easiest to delete the offer and create a new.

New-AppSourceSubmission is used by almost all partners who are automating appsource submissions, also indicating that something is special in this case.

**Comment by RonKoppelaar** [comment]
Indeed I mean the -DoNotWait switch in the cmdlet. 
Correct no customers live yet so it would be an option to delete...
As you mentioned both scenario's dont trigger the validation.

I'll go with your proposal to recreate the offering and get back to you.

**Comment by RonKoppelaar** [comment]
So I recreated the whole appSource publication (using the UI) except for uploading the app. This last step was performed through the API/PS:

```
New-AppSourceSubmission -authContext $AuthContext -productId $Product.id -appFile "C:\Temp\AppSource\Zig_Zig365 Insights Connector_23.23.12989.0.app" -doNotWait
```

This cmdlet was fully succesfull with following result output:
New AppSource submission created


resourceType       : Submission
state              : InProgress
substate           : InDraft
targets            : {@{type=Scope; value=Preview}}
resources          : {@{type=Package; value=52c5ea05-cb1e-4130-ba11-aca9f14e5b0c}, @{type=Property; value=dae1d766-293f-a426-74f6-204ef618d953}}
publishOption      : @{releaseTimeInUtc=0001-01-01T00:00:00; isManualPublish=False; isAutoPromote=False}
publishedTimeInUtc : 1601-01-01T00:00:00Z
pendingUpdateInfo  : @{updateType=Create; status=Running}
releaseNumber      : 1
friendlyName       : Submission 1
areResourcesReady  : True
id                 : 1152921505697797393

When navigating to the Marketplace in the browser I see again same behavior. The work flow for validation is not triggered:
![image](https://github.com/microsoft/navcontainerhelper/assets/33791875/fb43dd4a-1383-4e2d-a628-407950ced3a3)

So I checked through PS:
```
Get-AppSourceSubmission -authContext $authcontext -productId $Product.id 
```

Which doesnt give any results...
I'm kind of in the dark here.

**Comment by RonKoppelaar** [comment]
also tried submission without the -DoNotwait flag, Which failed with below error:

POST https://api.partner.microsoft.com/v1.0/ingestion/products/fd071c04-a41b-418b-bb48-1f834cfbcef6/submissions
{
    "resources":  [
                      {
                          "type":  "Package",
                          "value":  "52c5ea05-cb1e-4130-ba11-aca9f14e5b0c"
                      },
                      {
                          "type":  "Property",
                          "value":  "dae1d766-293f-a426-74f6-204ef618d953"
                      }
                  ],
    "targets":  [
                    {
                        "type":  "Scope",
                        "value":  "preview"
                    }
                ],
    "resourceType":  "SubmissionCreationRequest"
}
New-AppSourceSubmission Telemetry Correlation Id: 509ed938-941f-42f0-8b1d-a4f11285a9a1
Unexpected error when trying to get status for submission. Please consult Partner Center UI.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.17\AppSource\New-AppSourceSubmission.ps1:255 char:17
+ ...             throw "Unexpected error when trying to get status for sub ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Unexpected erro...tner Center UI.:String) [], RuntimeException
    + FullyQualifiedErrorId : Unexpected error when trying to get status for submission. Please consult Partner Center UI.

**Comment by RonKoppelaar** [comment]
After manually doing the submission I got following response from cmdlet: Get-AppSourceSubmission -authContext $authcontext -productId $Product.id 

resourceType       : Submission
state              : InProgress
substate           : Submitted
targets            : {@{type=Scope; value=Preview}}
resources          : {@{type=Availability; value=89c7db70-31ff-b561-5bbf-3eb285ca1388}, @{type=Listing; value=f5f53e61-07dc-0500-fd60-b688090b80af}, @{type=Package; 
                     value=52c5ea05-cb1e-4130-ba11-aca9f14e5b0c}, @{type=Property; value=dae1d766-293f-a426-74f6-204ef618d953}...}
publishedTimeInUtc : 1601-01-01T00:00:00Z
pendingUpdateInfo  : @{updateType=Create; status=Completed}
releaseNumber      : 1
friendlyName       : Submission 1
areResourcesReady  : True
id                 : 1152921505697797881

**Comment by RonKoppelaar** [comment]
Could it be I have to go end to end through manual validation first?

**Comment by RonKoppelaar** [comment]
If I check the submission id (created by the API) I get this output:
```
PS C:\Windows\system32> $productId = $Product.id 
$SubmissionId = "1152921505697799656" #Auto
#$SubmissionId = "1152921505697797881" #Manual
$Value = Invoke-IngestionApiGet -authContext $authContext -path "/products/$productId/submissions/$SubmissionId/validations" -Verbose
$Value.value

Attempting authentication to https://api.partner.microsoft.com/.default using clientCredentials...
VERBOSE: POST with -1-byte payload
VERBOSE: received 1327-byte response of content type application/json; charset=utf-8
Authenticated as app d10a50ad-2a9f-4a54-ae8e-3e2094f4abdb
GET https://api.partner.microsoft.com/v1.0/ingestion/products/fd071c04-a41b-418b-bb48-1f834cfbcef6/submissions/1152921505697799656/validations
VERBOSE: GET with 0-byte payload
VERBOSE: received -1-byte response of content type application/json; charset=utf-8

errorCode                 severity resource           
---------                 -------- --------           
Listing-20007             Error    Listing            
Availability-20007        Error    Availability       
SupplementalContent-20007 Error    SupplementalContent
```

Is therre any way to find out the errorcodes

**Comment by RonKoppelaar** [comment]
After manual submission without any errors I was able to use the cmdlets as expected.
