### ISSUE TITLE
Web Client Not Working.

### ISSUE THREAD

**Issue by GaneshVarahade** [Microsoft/navcontainerhelper#354]
Have Install Docker with below Version-
PS C:\WINDOWS\system32> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false

After Mapp Image in Docker.
PS C:\WINDOWS\system32> New-NavContainer -accept_eula -containerName MMSTESDS -imageName microsoft/bcsandbox:us -includeCSide -doNotExportObjectsToText -auth NavUserPassword
NavContainerHelper is version 0.5.0.2
Host is Microsoft Windows 10 Pro - ltsc2019
Docker Client Version is 18.09.1
Docker Server Version is 18.09.1
NOTE: Add -alwaysPull or -useBestContainerOS if you want to use microsoft/bcsandbox:us-ltsc2019 instead of microsoft/bcsandbox:us.
Using image microsoft/bcsandbox:us
Removing container GFMMS
Removing C:\ProgramData\NavContainerHelper\Extensions\GFMMS
Creating Nav container GFMMS
Version: 13.3.27233.0-US
Platform: 13.0.27183.0
Generic Tag: 0.0.9.0
Container OS Version: 10.0.14393.2665 (ltsc2016)
Host OS Version: 10.0.17763.107 (ltsc2019)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using hyperv isolation
Creating container GFMMS from image microsoft/bcsandbox:us
4ac12d3e67746d5b36bc6afc56602b1fa8de21e32f6c8fca0d58e316ebfc2cde
Waiting for container GFMMS to be ready
Initializing...
Starting Container
Hostname is GFMMS
PublicDnsName is GFMMS
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 0807B4F88C1EB8F56C0F139A17E39347FC7518F1
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user Admin
Setting SA Password and enabling SA
Creating Admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.20.110.233
Container Hostname  : GFMMS
Container Dns Name  : GFMMS
Web Client          : http://GFMMS/NAV/
Dev. Server         : http://GFMMS
Dev. ServerInstance : NAV

Files:
http://GFMMS:8080/al-2.1.79379.vsix

WARNING: You are running a container which is 61 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 139 seconds
Ready for connections!
Reading CustomSettings.config from GFMMS
Creating Desktop Shortcuts for GFMMS
Nav container GFMMS successfully created
PS C:\WINDOWS\system32>

All Working fine, i goto desktop and try run Container Web Client, then show below error on browser.

This site can’t be reached gfrmhcontainer took too long to respond.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_TIMED_OUT

Please help to run Docker and Map Application in Online.

**Comment by freddydk** [comment]
It seems like you have tried a few times - your command is creating a container called MMSTESDS, the output is from a container called GFMMS and you are trying to connect to the web client on gfrmhcontainer.
Assuming that all of these things are on purpose - i have two comments.

You are using a 2016 image on a 2019 server because you already have that downloaded (NOTE: Add -alwaysPull or -useBestContainerOS if you want to use microsoft/bcsandbox:us-ltsc2019 instead of microsoft/bcsandbox:us.) - this means that you can only use hyperv isolation. Add -useBestContainerOS to switch to use ltsc2019 images and use process isolation. That is likely not the problem though.

Try to add -updateHosts to your new-navcontainer to allow navContainerHelper to add the container name to the hosts file. This might very well be the problem.

**Comment by GaneshVarahade** [comment]
Thanks @freddydk  its working for me.
but after all, image mapping is done, build application its successfully but try run (F5) then getting bellow error can you help me for this.

[2019-02-22 01:52:25.16] Sending request to http://gfmms:7049/nav/dev/apps?SchemaUpdateMode=synchronize
[2019-02-22 01:52:27.75] The request for path /nav/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Your program license does not allow you to publish 'Package From Wet Harvest'.

Check attach image file.
![alerror](https://user-images.githubusercontent.com/1560560/53225025-af67c400-3644-11e9-9339-60cf584adfef.png)

Please help me with this issue.

**Comment by freddydk** [comment]
Seems like you are using an object range which you don't have license for.
I don't know much about licensing, so you would have to find the answer for this elsewhere.
Maybe AL issues.
