### ISSUE TITLE
[Improvement] - New Container User - Set State (Enabled, Disabled)

### ISSUE THREAD

**Issue by pri-kise** [microsoft/navcontainerhelper#3542]
**Describe the issue**
It would be useful to create an user with State "disabled".
https://learn.microsoft.com/en-us/powershell/module/microsoft.dynamics.nav.management/new-navserveruser?view=businesscentral-ps-24#-state

**Addtional Context**

Currently we create dockers with AAD Users. 
We use a script to fetch an aad group and  create BCUsers for all members of the group.

Now we try to use the cronus license for developement on customer projects. 
e.g. sometimes they use ISV solutions that we don't have licensed in our development license. (with cronus license we're able to develop)

The problem we have with the cronus license is the warning when there are more than 10 users enabled.
Therefore it would be useful to only enable the developer and the main reviewer for this docker at first.

**Comment by freddydk** [comment]
You are more than welcome to create a PR with this improvement - or you can simply use 

Invoke-ScriptInBcContainer -scriptblock {
New-NavServerUser -serverinstance...
}

which probably will be much simpler, as this doesn't have to cope with all versions and other special cases.
