### ISSUE TITLE
Error querying artifacts. Error message was Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by krishnaS08** [microsoft/navcontainerhelper#3543]
Error querying artifacts. Error message was Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
I'm encountering with this error in my powershell ,when I try to create a **BC24** new container.
![2024-05-17 22_03_53-Administrator_ Windows PowerShell ISE](https://github.com/microsoft/navcontainerhelper/assets/170123404/04b9cea1-da08-4c69-8182-1df28942b47d)
in below I'll attach my container creation script
```
$containerName = 'BC242W1'
$password = '1234'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'krishna', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -storageAccount 'bcinsider' -country 'Base' -select 'Latest' -accept_insiderEula
$licenseFile = "C:\Users\Ks\Downloads\5164953 10.bclicense"

New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -accept_insiderEula `
    -artifactUrl $artifactUrl `
    -multitenant:$false `
    -includeTestToolkit `
    -licenseFile $licenseFile `
    -updateHosts
```

can you please anyone to help on this?

**Comment by freddydk** [comment]
What is $artifactUrl after running that code?

**Comment by krishnaS08** [comment]
No if I retry also I'm getting the same error

![image](https://github.com/microsoft/navcontainerhelper/assets/170123404/6dbeee21-fe35-42d7-ad3d-df0379589e84)

**Comment by freddydk** [comment]
The problem is the error querying artifacts.

And if you run
```
Get-BcArtifactUrl -storageAccount 'bcinsider' -country 'Base' -select 'Latest' -accept_insiderEula
```
You probably get the same.

Where in the world are you located, what is your internet speed?

**Comment by krishnaS08** [comment]
I'm in India,here I attach my Internet speed

![image](https://github.com/microsoft/navcontainerhelper/assets/170123404/5dc8f582-7b51-45ac-90a0-eeb4633a54a8)

I downloaded the https://[bcinsider.blob.core.windows.net/sandbox/?comp=list&restype=container](https://bcinsider.blob.core.windows.net/sandbox/?comp=list&restype=container)

**Comment by freddydk** [comment]
What is the result of

```
Get-BcArtifactUrl -verbose -storageAccount 'bcinsider' -country 'Base' -select 'Latest' -accept_insiderEula
```

I will have to look into what can be done when having a fairly slow connection

**Comment by krishnaS08** [comment]
![image](https://github.com/microsoft/navcontainerhelper/assets/170123404/8a7dda2b-7e38-4dbb-bc8d-b0a46cd38b3d)
 
this is the result

**Comment by freddydk** [comment]
This is how this command looks on my machine:

![image](https://github.com/microsoft/navcontainerhelper/assets/10775043/ce741119-fcbb-40fb-808f-34ea217cff59)

You can try to set $artifactUrl to https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.19695.0/base instead of calling Get-BcArtifactUrl - but you probably also need to set

$bcContainerHelperConfig.artifactDownloadTimeout = 0

I assume 0 is no timeout - else you would need to use a very high number of seconds.

**Comment by krishnaS08** [comment]
ok I'll try this..thanks

@freddydk

**Comment by krishnaS08** [comment]
Now, I'm getting this error 

![image](https://github.com/microsoft/navcontainerhelper/assets/170123404/1a26e963-79ae-41d2-a110-abc0e877e0b1)


@freddydk

**Comment by freddydk** [comment]
Did you try to set timeout to 0?
I am afraid your internet connection might be too slow to download 1+ GB of artifacts.

**Comment by krishnaS08** [comment]
I tried with timeout setting it's worked @freddydk  thank you !!
