### ISSUE TITLE
Copy-AlSourceFiles.ps1 does not copy RDLC and DOCS Files with the new report layout definition

### ISSUE THREAD

**Issue by LukeJiricek** [microsoft/navcontainerhelper#3544]
**Describe the issue**
The **Copy-AlSourceFiles.ps1** procedure in BcContainerHelper is not correctly copying AL source files, specifically **RDLC** and **DOCX** layouts. This issue arises when reports in newer versions use the new way of declaring layouts as described in the [Microsoft documentation](https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-report-layout-declaration).

When a report omits the legacy layout declaration line but uses the rendering section instead. The associated RDLC/DOCX file is not copied by the procedure.

**Additional context**
- Example report: **Reminder.Report.al**
- Example layout: **Reminder.rdlc** and **DefaultReminderEmail.docx**
- The Reminder.Report.al does not include the legacy layout declaration line, but uses rendering section.
![image](https://github.com/microsoft/navcontainerhelper/assets/79200134/292cdc57-6550-4a9f-bede-1239b9a44dfc)
![image](https://github.com/microsoft/navcontainerhelper/assets/79200134/c62625ef-e61f-4c17-ae3c-819fdf90b339)
- `if ($line.Trim() -like "RDLCLayout = '*';" -or $line.Trim() -like "WordLayout = '*';")
` is never true
![image](https://github.com/microsoft/navcontainerhelper/assets/79200134/74b19c66-8370-499b-a6f2-d0322113a51a)
- As a result, **Reminder.rdlc** and **DefaultReminderEmail.docx** is not copied by Copy-AlSourceFiles.ps1.

I have reproduced this issue in the 6.0.17 release, and the prerelease version 6.0.18-preview1202 as well.

**Comment by freddydk** [comment]
Could you provide the code used to repro the issue?
Are you transferring a -alFileStructure scriptblock, then please supply that here, thanks.

**Comment by LukeJiricek** [comment]
The example of the -alFileStructure scriptblock:

```
$SourcePath = ''
$DestinationPath = ''
$myModifiedObjects = @()                         #Define set of modified standard objects, syntax Type+ID, e.g.: $myModifiedObjects = @("table18","codeunit80")

#Definition of the file structure and naming convention:
$alFileStructure = { Param ([string] $type, [int] $id, [string] $name)
    if ($myModifiedObjects.Contains("$type$id")) {
        $folder = "Modified"
    }
    elseif (($id -ge 50000 -and $id -le 99999) -or ($id -gt 1999999999)) {
        $folder = "customizations"
    }
    else {
        $folder = "src"
    }
    "$folder\$($name).$($type).al"
}

Copy-AlSourceFiles -alFileStructure $alFileStructure -Destination $DestinationPath -Path $SourcePath -Recurse
```

I am using slightly modified version (which I am not permitted to share), as this one is saving all files into one folder and, as .al files. But I have reproduced the issue with this scriptblock as well. The previously mentioned layout files, if their report is using the new layout declaration, are not copied. Hope this helps. Thank you.
