### ISSUE TITLE
Test succeed in client but failes when running with Run-TestsInBcContainer

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#3546]
**Describe the issue**
Simulating a client while executing Run-TestsInBcContainer seems not to be perfect.
Especially when it comes to reporting/printing, the simulation unfortunately does not work properly.

**Repro**
See this Repro: https://github.com/ChrisBlankDe/AL-Go-Reproduction/pull/4

We build an simple test which print an report.

```AL
codeunit 50121 "HelloWorld Test"
{
    Subtype = Test;
    SingleInstance = true;
    EventSubscriberInstance = Manual;

    [HandlerFunctions('SalesShipmentRequestPageHandler')]
    [Test]
    procedure FunctionNameTest()
    var
        SalesShipmentHeader: Record "Sales Shipment Header";
        ThisCodeunit: Codeunit "HelloWorld Test";
    begin
        if UnbindSubscription(ThisCodeunit) then; //Avoid error if subscription is not bound
        BindSubscription(ThisCodeunit);
        SalesShipmentHeader.FindFirst();
        SalesShipmentHeader.SetRecFilter();
        Report.Run(Report::"Sales - Shipment", true, false, SalesShipmentHeader);
    end;

    [RequestPageHandler]
    procedure SalesShipmentRequestPageHandler(var RequestPage: TestRequestPage "Sales - Shipment")
    begin
        RequestPage.Print().Invoke();
    end;

    [EventSubscriber(ObjectType::Codeunit, Codeunit::"Reporting Triggers", 'OnDocumentPrintReady', '', true, true)]
    local procedure OnDocumentPrintReady(ObjectType: Option "Report","Page"; ObjectId: Integer; ObjectPayload: JsonObject; DocumentStream: InStream; var Success: Boolean);
    begin
        // This code is not expected to be executed
        Error('OnDocumentPrintReady should not be called');
    end;
}

```

Test failes in pipeline but succeed when running manualy.

Result in PowerShell:
```
PS C:\ProgramData\bccontainerhelper> Run-TestsInBcContainer -containerName navserver -tenant cbl-dms -credential $cred -extensionId b2b3aa77-39bd-4813-8018-6ad978cdc942 -detailed
WARNING: TaskScheduler is running in the container, this can lead to test failures. Specify -EnableTaskScheduler:$false to disable Task Scheduler.
Connecting to https://localhost:443/BC/cs?tenant=cbl-dms
  Codeunit 50121 HelloWorld Test Failure (0.826 seconds)
    Testfunction FunctionNameTest Failure (0.826 seconds)
      Error:
        OnDocumentPrintReady should not be called
      Call Stack:
        HelloWorld Test(CodeUnit 50121).OnDocumentPrintReady line 2 - FailInPosh.Test by ChrisBlankDe
        Reporting Triggers(CodeUnit 2000000005).OnDocumentPrintReady(Event) line 2
```
Result in Client:
![image](https://github.com/microsoft/navcontainerhelper/assets/18051656/d26b137d-2941-45d1-9942-0e7fba7d87bc)

**Additional context**
- does it happen all the time? YES
- did it use to work? NO

**Comment by freddydk** [comment]
Not sure I can do anything about this.
Will send this to somebody in the team responsible for this part.

**Comment by freddydk** [comment]
Answer from the team:

This is not related to the client, but to the way we deal with different types of printers.

Windows/web print is disabled when you run test (to save the forest), but configured extension printers are not disabled, as this can easily be managed from the test setup.

If we disable extension print in platform during test, you would not be able to test the extension printers (like universal print or ...).

If you don't want to have the trigger invoked, then make sure that the test does not have printers selected or handle the print request in the trigger - they configure the printer, so they should also be able to validate that the job actually printed the documented they intended and that information is in the report payload provided to the trigger.
