### ISSUE TITLE
Question: What does *unstable* mean in your NuGetFeedClass SearchQueryService comment?

### ISSUE THREAD

**Issue by MODUSCarstenScholling** [microsoft/navcontainerhelper#3570]
Hi Freddy,

**Question**
In your [NuGetFeedClass implementation](https://github.com/microsoft/navcontainerhelper/blob/b2410696c2c9ce68b63f3ef1a65c0c09d0c58ed1/NuGet/NuGetFeedClass.ps1#L85) you have mentioned "GitHub support for SearchQueryService is unstable and is not usable".

I've done an implementation in AL and was not able to identify any issues using [prerelease and semVerLevel parameters](https://learn.microsoft.com/en-us/nuget/api/search-query-service-resource#search-for-packages).

Do you remember what exactly does not work as expected?

Thank you,
Carsten

**Comment by freddydk** [comment]
I think it was the search, which didn't return what I expected.
When searching for a GUID, it wouldn't find anything (as I recall) - I will re-test

**Comment by MODUSCarstenScholling** [comment]
Ok, I see what you mean. The [advanced search syntax](https://learn.microsoft.com/en-us/nuget/consume-packages/finding-and-choosing-packages#search-syntax) seems to return nothing or everything. Simple queries are working for author, but not for the name or guid...

- q=authors:MODUS%20Consult%20GmbH does not return anything
- q=MODUS%20Consult%20GmbH works
- q=MODUSM365Foundation returns zero entries
- q=d78da1d4-e45e-479e-9bb3-c368752fb48f finds an AL-Go entry but not the actual app package

Our AL implementation should work fine, because we only use full package names with Author.Name.AppId.

Thank you for the hint regarding parts of the package id.
