### ISSUE TITLE
Cannot Restore-BcDatabaseFromArtifacts because of SSL Provider issue

### ISSUE THREAD

**Issue by mkilinskidev** [microsoft/navcontainerhelper#3572]
Hi. I can't restore a database from artifacts on my external SQL because of issue "SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted".

Regarding this issue: https://github.com/microsoft/SQLServerPSModule/issues/35 there is a switch `-TrustServerCertificate` in the SQLServer module. Can you add that switch to the `Restore-BcDatabaseFromArtifacts` script?

```
PS C:\Users\mkilinski> Restore-BcDatabaseFromArtifacts -artifactUrl (Get-BCArtifactUrl -type OnPrem -country w1 -version 24 -select Latest) -databaseServer SRV-SQL-01 -databasePrefix 'MKI-' -databaseName 'TEST'
Starting Database Restore job from https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/24.2.20227.20424/w1
C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.15\Import-BcContainerHelper.ps1
BcContainerHelper version 6.0.15
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.22621.2506
Downloading Artifacts https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/24.2.20227.20424/w1
Importing PowerShell module C:\bcartifacts.cache\onprem\24.2.20227.20424\platform\ServiceTier\program files\Microsoft Dynamics NAV\240\Service\Management\Microsoft.Dynamics.Nav.Management.dll
Restore-BcDatabaseFromArtifacts Telemetry Correlation Id: a3c22923-895d-4b9f-8b3e-0c7e4e93c71d
A connection was successfully established with the server, but then an error occurred during the login process. (provid
er: SSL Provider, error: 0 - Łańcuch certyfikatów został wystawiony przez urząd, którego nie jest zaufany.)
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.15\Bacpac\Restore-BcDatabaseFromArtifacts.ps1:222 c
har:13
+             $job | Receive-Job
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExceptionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
    + PSComputerName        : localhost
```

**Comment by mkilinskidev** [comment]
The same situation when I am trying to create a new BC container with external SQL.
```
BcContainerHelper is version 6.0.18
BcContainerHelper is running as administrator
HyperV is Enabled
Host is Microsoft Windows Server 2022 Standard - 10.0.20348.2461
UsePsSession is True
UsePwshForBc24 is True
UseWinRmSession is allow
UseSslForWinRmSession is True
Docker Client Version is 26.1.4
Docker Server Version is 26.1.4
Removing Desktop shortcuts
New-BcContainer Telemetry Correlation Id: 5b18c24e-bb65-48cb-9260-bbb198da507d
Invoke-SqlCmd : A connection was successfully established with the server, but then an error occurred during the login
process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
At C:\Program Files\WindowsPowerShell\Modules\BCContainerHelper\6.0.18\Bacpac\Remove-BcDatabase.ps1:41 char:16
+     $dbFiles = Invoke-SqlCmd `
+                ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExceptionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
```

**Comment by freddydk** [comment]
Full script (that I can run and repro the problem) + full output please.
Thanks

**Comment by freddydk** [comment]
What SQL Server are you running on the host?
Does this work if you use BC23?
Does it work if you set `$bcContainerHelperConfig.usePwshForBc24 = $false` before you run the script?

**Comment by mkilinskidev** [comment]
SQL Server Standard, version 16.0.4105.2
Same issue after set  $bcContainerHelperConfig.usePwshForBc24 = $false.
With BC23 same situation. With SQL2019 (15.00.2000.05) still the same.

**Comment by freddydk** [comment]
Is your SQL Server installed with a self-signed certificate for SSL communication?
Could you remove that?

**Comment by mkilinskidev** [comment]
IDK how to check it. If I go to SQL Server Configuration Management, all encryptions etc. are turned off. Going through this article https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/configure-sql-server-encryption?view=sql-server-ver16 I didn't see, if the SQL have some certificates installed. I've checked the system register, even sp_configure T-SQL queries, nothing. I don't know, what can I do more, so why I am asking about add the TrustServerCertificate switch. I can fork the repository and make it by myself and then make a Pull Request.

**Comment by freddydk** [comment]
The problem is that the current implementation works for everyone else. Any change needs to be tested with various versions.
Feel free to create a pr, which works for you - then we can test

**Comment by freddydk** [comment]
Looking The reason for this is that you have a newer version of the SqlServer powershell module on your computer.
This obviously have to be supported - but without removing support for the old version of Invoke-SqlCmd.
Feel free to grab the changes from my PR and test it.

**Comment by freddydk** [comment]
Fixed in preview
