### ISSUE TITLE
Using Invoke-BcContainerApi method results an 404 error.

### ISSUE THREAD

**Issue by J-Juuh** [microsoft/navcontainerhelper#3578]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I am trying to use the Invoke API method to get a working API call in order to do some testing. However even though I use a sample command found in source code I get an 404 error. Probably issue is that I am doing something wrong.

**Scripts used to create container and cause the issue**
```
New-BcContainer 
-accept_eula
-containerName BCtest23-5 
-artifactUrl $url 
-Credential $cred 
-auth UserPassword 
-PublishPorts @(80, 443, 7048, 7049)
```
After the container is finished is write the following commands to powershell:

>>Invoke-BcContainerApi -containerName $containerName -CompanyId $companyId -APIVersion "beta" -Query "customers" -credential $credential
>>Select-Object -ExpandProperty value

**Full output of scripts**
```
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Invoke GET on http://###.##.###.###:7048/BC/api/beta/companies(e#####9-b###-e###-8###-6##########b)/customers?tenant=default
Invoke-BcContainerApi Telemetry Correlation Id: 2#######-####-4###-a###-c#########
Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.18\Api\Invoke-NavContainerApi.ps1:169
char:5
+     Invoke-RestMethod -Method $Method -uri "$url" -Headers $headers @ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMe
   thod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMetho
   dCommand
...
```

**Screenshots**

**Additional context**
This seems to happen every time

Thanks for the help!

**Comment by freddydk** [comment]
If you replace the APIVersion with "v2.0" it should work - I will modify the help text.
This script works for me:

```
$auth = "UserPassword"
$containerName = "bc23"
$credential = New-Object pscredential -ArgumentList 'admin', $PasswordSecret.SecretValue
$artifactUrl = Get-BcArtifactUrl -country us -version 23.5
New-BCContainer -containerName $containerName `
                -accept_eula `
                -Auth $auth `
                -artifactUrl $artifactUrl `
                -Credential $credential

Invoke-BcContainerApi -containerName $containerName -tenant 'Default' -APIVersion "v2.0" -Query "customers" -credential $credential
```

Please note that your -publishports parameter opens these ports for access from other computers to your container.

**Comment by J-Juuh** [comment]
Hi,

Thanks again, works like a charm!

And thanks for the note about the port publishing, but connecting the container from outside  the host machine is the idea. There are too many ports though, but this state is for testing.
