### ISSUE TITLE
Memory leak Issue after running long queries. 

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/navcontainerhelper#358]
Hi 
I’m running several ui tests in my nav container and it seems that I have stumbled into a memory leak issue.  In my test I copy a company which has no transactional data. I do this at the beginning of every test so that I can have an isolated test environment. I have found is that the after about 20 tests, I start to see Business Central slow down during the creation of the container.  My work around has been to stop and restart the service tier but still I have the problem. I have about 300 tests that I would like to be able to run.  I’m not sure if this is related to the logs.  The event log inside the container shows warnings Long Running SQL statement. Execution time at 4000 and then it increases with every test. I am running docker on Windows server.

**Comment by freddydk** [comment]
Do you have a powershell script, which can repro this?
It will be very hard for me to chase after a problem, which I do not know how to replicate, sorry.

**Comment by AmandaTest** [comment]
I've added these 2 parameters to my create container script which imports my database: 
   -myScripts @("C:\Temp\backup\mydb.bak") `
    -additionalParameters @('--env SqlTimeout="4000"','--env bakfile="c:\run\my\mydb.bak"') `
Without the timeout, my db would never load.
After the import , I run
Set-NAVServerConfiguration -KeyName SqlLongRunningThreshold -ServerInstance NAV -KeyValue "3000" (If I didn't do that, I would see tons of warning messages in the Eventlog)
You can use this to copy the company: 
Copy-NAVCompany -DestinationCompanyName WarmUp -ServerInstance NAV -SourceCompanyName Cronusna

After copying the company a few times, I see the following in the eventlog in the container:
The following information was included with the event: 

Server instance: NAV
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 4b346c1e-659a-47ae-811d-9b77d8dd6863
EventTime: 02/26/2019 13:38:42
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 12364 ms
  Threshold: 3000 ms
  Message: Long running SQL statement 
  Task ID: 3
  Connection ID: 5
  Database Name: mydatabase
  Statement: SELECT DISTINCT CT.SYS_CHANGE_VERSION, 0[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Object Metadata], @maxChangeTrackingNumberObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 1[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [Debugger Breakpoint], @maxChangeTrackingNumberDebuggerBreakpoint) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 2[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Add-in], @maxChangeTrackingNumberAddIn) CT WHERE CT.SYS_CHANGE_OPERATION = 'U'
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 3[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], CT.[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Object Metadata], @maxChangeTrackingNumberNavAppObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 4[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Tenant App], @maxChangeTrackingNumberNavAppTenantApp) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 5[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App], @maxChangeTrackingNumberNavApp) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 6[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Publish Reference], @maxChangeTrackingNumberNavAppPublishReference) CT

**Comment by freddydk** [comment]
I have repeatedly tried to repro this without luck:-(
Please reopen and provide script + demo database for me to reproduce the issue.
thanks
