### ISSUE TITLE
[Feature Request] Add Parameter "ImportAction" to Import-TestToolkitToNavContainer

### ISSUE THREAD

**Issue by NAVRockClimber** [Microsoft/navcontainerhelper#359]
Hi,

Can you please add a parameter to this function? That parameter should be passed down to the "Import-NAVApplicationObject" function in your Import-TestToolkitToNavContainer.

The parameter should reflect the same options as the parameter of the function Import-NAVApplicationObject.

Valid Options: Default, Overwrite, Skip

I am using your containers with our database and your example DevOps pipeline for migrating our solutions to AL. But the pipeline keeps failing due to we got a MenuSuite on the same ID like the Testtoolkit and developers forget to delete their Test Codeunits on regular basis.

Thank you!

**Comment by freddydk** [comment]
Will be included in next version - primarily as using skip will save 20+ seconds if the objects are already there.

**Comment by freddydk** [comment]
Shipped in 0.5.0.5

**Comment by RockClimber81** [comment]
Awesome! Thank you very much, @freddydk ! I will check it out as soon as I am back from my vacation.

**Comment by gintuoklis** [comment]
Hey @freddydk, 
sorry for hijacking the thread:) 
could not find any official documentation regarding option "Skip". If I choose option "Skip", will it import only new objects? or changed objects as well ? (changed means that it differs by parameters : name/date/time/modified)?
