### ISSUE TITLE
Question about custom API's

### ISSUE THREAD

**Issue by J-Juuh** [microsoft/navcontainerhelper#3598]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
I am trying to familiriase myself with Business Central API's. For this I decided to create few tables and API pages.

I followed this walkthrough:  https://learn.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-develop-custom-api

I copied all of the code with the publisher, API group etc. from the walkthrough in order to minimise the risk of having something wrong with the code. Published it from VScode so that I can see it in extension management but still I am unable to read the data using API.

I am testing the connection by typing the URL below to the browser:

http://{{containerIP}}:7048/BC/api/v2.0/CRONUS%20USA,%20Inc./api/bctech/demo/v1.0/companies({{companyID}})/carModels?tenant=default

Which results to error:
```
{
    "error": {
        "code": "BadRequest_NotFound",
        "message": "Resource not found for the segment 'CRONUS USA, Inc.'."
    }
}
```

'Invoke-BcContainerApi' doesn't work either but that's probably due to the fact that it is a custom API.

script:
```
$containerName = “BCtest”
$credential = Get-Credential


$result = Invoke-BcContainerApi -containerName $containerName -tenant 'Default' -APIVersion "v2.0" -Query "companies" -credential $credential
$company = $result.value | Where-Object { $_.name -eq 'CRONUS USA, Inc.' }
$companyid = $company | Select-Object -Property id


Invoke-BcContainerApi -containerName $containerName -CompanyId $companyid."id" -APIVersion "v1.0" -Query "carModels" -credential $credential | Select-Object -ExpandProperty value
$apiresult = Invoke-BcContainerApi -containerName $containerName -CompanyId $companyid."id" -APIVersion "v1.0" -Query "carModels" -credential $credential
$apiresult.'@odata.context' 
```
Output:
```
 PS C:\Users\Administrator> $containerName = “BCtest”
$credential = Get-Credential


$result = Invoke-BcContainerApi -containerName $containerName -tenant 'Default' -APIVersion "v2.0" -Query "companies" -credential $credential
$company = $result.value | Where-Object { $_.name -eq 'CRONUS USA, Inc.' }
$companyid = $company | Select-Object -Property id


Invoke-BcContainerApi -containerName $containerName -CompanyId $companyid."id" -APIVersion "v1.0" -Query "carModels" -credential $credential | Select-Object -ExpandProperty value
$apiresult = Invoke-BcContainerApi -containerName $containerName -CompanyId $companyid."id" -APIVersion "v1.0" -Query "carModels" -credential $credential
$apiresult.'@odata.context'
cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Invoke GET on http://192.###.###.###:7048/BC/api/v2.0/companies?tenant=Default
Invoke GET on http://192.###.###.###:7048/BC/api/v1.0/companies(0#######-####-####-####-6###########)/carModels?tenant=default
Invoke-BcContainerApi Telemetry Correlation Id: 9######-####-####-####-############
Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.19\Api\Invoke-NavContainerApi.ps1:169 char:5
+     Invoke-RestMethod -Method $Method -uri "$url" -Headers $headers @ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand 
```

**Scripts used to create container and cause the issue**
```
New-BcContainer 
-accept_eula 
-containerName BCtest
-artifactUrl $url 
-Credential $cred 
-auth UserPassword 
-PublishPorts @(80, 443, 7048, 7049)
```

**Full output of scripts**

**Screenshots**

**Additional context**
- does it happen all the time? YES
- did it use to work? NO

Frankly, I am not sure whether this is a container related issue or BC related issue, if I had to guess I'd say there is probably something wrong with URL that I am using. Standard API's work great only this custom one is giving me trouble.

Thanks for the help!

**Comment by freddydk** [comment]
This URL:
http://{{containerIP}}:7048/BC/api/v2.0/CRONUS%20USA,%20Inc./api/bctech/demo/v1.0/companies({{companyID}})/carModels?tenant=default

is definitely wrong.

The API in the documentation has these values:

    APIVersion = 'v1.0'
    APIPublisher = 'bctech'
    APIGroup = 'demo'

and the URL should be something like:

`http://<ip>:<port>/BC/api/<publisher>/<group>/<version>/<companies(companyId)>/<query>?tenant=Default`

So:

`http://<ip>:7048/BC/api/bctech/demo/v1.0/companies(companyId)/carModels?tenant=Default`

would be a better guess.

**Comment by freddydk** [comment]
and the companyId is retrieved by using:

```
$companyId = Get-BcContainerApiCompanyId -containerName bcserver -credential $credential
```

**Comment by J-Juuh** [comment]
Hi and sorry for the delayed response.

The URL you provided works great! Also got my own custom API to work with this advice.

Thanks again for the help!
