### ISSUE TITLE
Updating an existing container with a new version of the Image

### ISSUE THREAD

**Issue by janhofmann24** [Microsoft/navcontainerhelper#36]
Is there a way of updating a container with a newer version of the Image without losing the changes on it. 

Thanks,
Jan

**Comment by Koubek** [comment]
What changes do you mean exactly? The container should be practically stateless service. It gives you the possibility to kill it and create again from scratch. Of course, the is the data persistence problem. Maybe your ask was exactly about the data. There are multiple choices but generally, in a real environment you should be working against an external SQL instance (inside the container or the traditional one served as a standard service).

Sorry if you were asking something else and I haven\`t understood your question well.

**Comment by janhofmann24** [comment]
Yes, by changes I mean data. 
I have restored a custom DB to the SQL Server on the Container and converted it to the Containers NAV version.

Is it possible to preserve this DB or do I have to move it out of the Container before updating the Container?

**Comment by freddydk** [comment]
You should move the data out of the container and use a separate SQL Server. Very soon this will be very easy with a few parameters to the new-navcontainer or docker run.
Only data, which should reside in the container is demo data.
