### ISSUE TITLE
Hello there, i got the same issue but i don't have the "Azure AD Applications" tab under User management ?

### ISSUE THREAD

**Issue by kaezanted** [microsoft/navcontainerhelper#3600]
Hello there, i got the same issue but i don't have the "Azure AD Applications" tab under User management ?
I created application under the "App management" tab but I'm struggling to add the manager permission to the application.

_Originally posted by @kaezanted in https://github.com/microsoft/navcontainerhelper/issues/2911#issuecomment-2243021562_

**Comment by freddydk** [comment]
Sounds like you lack permissions - this step https://github.com/microsoft/AL-Go/blob/main/Scenarios/PublishToAppSource.md describes how to setup an AAD app and it links to https://learn.microsoft.com/en-us/partner-center/marketplace-offers/azure-app-apis where it describes how to register it.
