### ISSUE TITLE
HTTP Error 502.5 while accessing BC after Windows Update 

### ISSUE THREAD

**Issue by seesharp54** [microsoft/navcontainerhelper#3608]
After a Windows Update, some colleagues and me dont have any access to our BC which is installed by Docker, and Container Helper. This is concerning different Versions of BC, i have checked BC 18 and BC 24 and am concluding, that all other Versions have the same issue. When i am trying to access the BC via Webbrowser I am getting: 

HTTP Error 502.5 - Process Failure

Common causes of this issue:
The application process failed to start
The application process started but then stopped
The application process started but failed to listen on the configured port

Troubleshooting steps:
Check the system event log for error messages
Enable logging the application process’ stdout messages
Attach a debugger to the application process and inspect

I have tried to install new containers and still get the message, even in the new installed containers. It seems to be a problem with the ASP.NET Core Version which is also showed by the event log of the Container. I do not understand why a general Windows Update is harming a ASP.NET Installation within a isolated virtual Windows Container. So i dont updated a Windows Docker Container, i updated the host OS Windows. 
Atm we are trying to roll back the Windows Update which seems to be not as easy too. The BC Containers are starting without any troubles and the problem is showed only when accessing BC via webbrowser,

The Event Log is showing three error symptoms:

1.
Name der fehlerhaften Anwendung: Prod.Client.WebCoreApp.exe, Version: 18.0.22893.23773, Zeitstempel: 0xa7faf60d
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.20348.2400, Zeitstempel: 0x784b07c7
Ausnahmecode: 0xe0434352
Fehleroffset: 0x000000000003f19c
ID des fehlerhaften Prozesses: 0x1080c
Startzeit der fehlerhaften Anwendung: 0x01dae8ade9a2cfed
Pfad der fehlerhaften Anwendung: C:\inetpub\wwwroot\BC\Prod.Client.WebCoreApp.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 00e928b2-d3e5-43e5-b560-c3546e70c7d8
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

2.
Die Beschreibung für die Ereignis-ID "1026" aus der Quelle ".NET Runtime" wurde nicht gefunden. Entweder ist die Komponente, die dieses Ereignis auslöst, nicht auf dem lokalen Computer installiert, oder die Installation ist beschädigt. Sie können die Komponente auf dem lokalen Computer installieren oder reparieren.
 
Falls das Ereignis auf einem anderen Computer aufgetreten ist, mussten die Anzeigeinformationen mit dem Ereignis gespeichert werden.
 
Die folgenden Informationen wurden mit dem Ereignis gespeichert:
 
Application: Prod.Client.WebCoreApp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.Directory.InternalCreateDirectory(System.String, System.String, System.Object, Boolean)
   at System.IO.Directory.InternalCreateDirectoryHelper(System.String, Boolean)
   at Microsoft.AspNetCore.Hosting.Internal.HostingEnvironmentExtensions.Initialize(Microsoft.AspNetCore.Hosting.IHostingEnvironment, System.String, Microsoft.AspNetCore.Hosting.Internal.WebHostOptions)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(System.AggregateException ByRef)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Prod.Client.WebCoreApp.Program.Program.Main(System.String[])
 
 
Element nicht gefunden

3.
Die Beschreibung für die Ereignis-ID "1000" aus der Quelle "IIS AspNetCore Module" wurde nicht gefunden. Entweder ist die Komponente, die dieses Ereignis auslöst, nicht auf dem lokalen Computer installiert, oder die Installation ist beschädigt. Sie können die Komponente auf dem lokalen Computer installieren oder reparieren.
 
Falls das Ereignis auf einem anderen Computer aufgetreten ist, mussten die Anzeigeinformationen mit dem Ereignis gespeichert werden.
 
Die folgenden Informationen wurden mit dem Ereignis gespeichert:
 
Application 'MACHINE/WEBROOT/APPHOST/NAVWEBAPPLICATIONCONTAINER/BC' with physical root 'C:\inetpub\wwwroot\BC\' failed to start process with commandline '"C:\inetpub\wwwroot\BC\Prod.Client.WebCoreApp.exe" ', ErrorCode = '0x80004005 : ff.
 
Element nicht gefunden

Thanks for help.

**Comment by freddydk** [comment]
Is this existing containers, which stopped working?
Have you tried creating a new BC Container and check whether that has the same problem?

**Comment by seesharp54** [comment]
yes i ve tried to install a new container too, it shows the same error. All existing containers and all new installed containers are showing this error. In Docker they are functionally running without errors, but when accessing them via webbrowser, the docker windows is showing up that it cant start the ASP.NET Core.

**Comment by freddydk** [comment]
Are you using Windows Auth?
If Yes, did you try username / Password?

**Comment by seesharp54** [comment]
yes i ve just tried to set up a new one with userpassword auth. Problem consists, the authentication Dialogue isnt raised. The error occurs before i can authenticate.

**Comment by freddydk** [comment]
It isn't anything I can repro nor anything I have seen before.
You can post the full log of creating the container here for reference - but my assumption is that this is a problem on your machine, which I probably won't be able to resolve from here.

**Comment by seesharp54** [comment]
I agree its a local machine problem which comes by a windows update last week. Container log isnt showing anything special, everything is installed properly but ASP.NET Core isnt starting. Maybe the info by which update it shows up is more interesting:
![windowsupdates](https://github.com/user-attachments/assets/8e466a08-5b57-4f74-857f-5a55c30d5dec)

My system is:
Edition	Windows 11 Enterprise
Version	22H2
OS build	22621.3958
Leistung	Windows Feature Experience Pack 1000.22700.1026.0

**Comment by seesharp54** [comment]
I dont understand why an ASP.NET Core component which is separately installed to the container have this error -> we see in the event log, although the .NET Core update was applied to the host system. Is the host system running its own framework completely separated from the frameworks inside of the windows container or where is there a connection? Does the docker container uses frameworks from the host OS, is there any connection?

**Comment by freddydk** [comment]
When you specify imageName, it will create an image of the version and use that - you could try without that parameter to avoid the caching.

Also, you are using a very old docker version - maybe that is the problem - I have tried your exact command here (including imageName) and it works like a charm.

Make sure you have an updated Docker and an Updated Windows version
