### ISSUE TITLE
aka.ms/getbc fallback to NAVUserPassword because token expired when setting up SSO.

### ISSUE THREAD

**Issue by srttel** [microsoft/navcontainerhelper#3613]
**Describe the issue**
If you setup BC via aka.ms/getbc with a CDX demo tenant using Office365User Name, the setup fails because a token expired.

**Scripts used to create container and cause the issue**

Template fields:
```
Basics
Subscription Your Subscription
Resource group BCTestscript
Region North Europe
Vm Name BCTestscript
Timezone Id W. Europe Standard Time
Accept Eula Yes
Accept Insider Eula Yes
Remote Desktop Access *
Win RM Access -
Operating System Windows Server 2022
Vm Size Standard_D4s_v3
Container Name bcserver
Isolation Default
Vm Admin Username vmadmin
BC Admin Username admin
Admin Password **********
Artifact Url bcartifacts/onprem//w1/latest
BC Docker Image -
Test Toolkit No
Assign Premium Plan No
Create Test Users No
License File Uri -
Enable Task Scheduler Yes
Office365User Name admin@M365xXXXXXXXX.onmicrosoft.com
Office365Password **********
Create Aad Users No
Final Setup Script Url -
Bing Maps Key -
Run Windows Update No
Contact E Mail For Lets Encrypt whatever@whatever.org
Auto Shutdown Disabled
Auto Shutdown Time 20:00
Add Traefik No
```
**Screenshots**
![Error](https://github.com/user-attachments/assets/c47c1770-0c48-4b27-9932-98b8e9851f8e)

**Comment by freddydk** [comment]
I cannot see the screenshot

Remind me again - the password specified in Office365Password, is that an accesstoken or just the password?

It has been a very very long time since I last looked at this - some more context is appreciated?

**Comment by freddydk** [comment]
Looking at the code and trying a simple:
```
$authContext = New-BcAuthContext -includeDeviceLogin -scopes "https://graph.microsoft.com/.default" -deviceLoginTimeout ([TimeSpan]::FromSeconds(0))
```
Followed by
```
$authContext = New-BcAuthContext -deviceCode $authContext.deviceCode -deviceLoginTimeout ([TimeSpan]::FromMinutes(30))
```

I could repro this problem.

Must be a security change inside the Microsoft graph endpoint. I was pulling for a status every second, but the endpoint actually tells me to only pull for status every 5 seconds.

I will modify the New-BcAuthContext to pull for status based on the return value from the query endpoint.
