### ISSUE TITLE
How to open session list (to C/SIDE debuggger)

### ISSUE THREAD

**Issue by lvanvugt** [Microsoft/navcontainerhelper#362]
Probably a simple thing, but I cannot open the session list on a D365BC container installation.

Searching in Windows Client does not show _Sessions_ and when I select **Tools>Debugger>Debug Session** I get the following error:

> ---------------------------
> Cannot connect to the server because of a protocol mismatch. This can be caused by the client and server having incompatible credential settings (ClientServicesCredentialType). Contact your system administrator.
> ---------------------------

I am using: mcr.microsoft.com/businesscentral/onprem
And my credentialling is set to NavUserPassword

**Comment by tfenster** [comment]
Looks like your standard Windows Client is set to Windows or UserName auth. You can change that as described here https://docs.microsoft.com/en-us/dynamics-nav/configuring-the-windows-client#settings-in-the-clientusersettingsconfig-file

I hope I am not stating something you already know :)

**Comment by freddydk** [comment]
When launching Window Client from CSIDE it uses the dynamicsnav:// moniker - which wont grab the version of the Windows Client, which matches your container - but the one you have installed on the host.
Not sure how to create a parameterized shortcut to Windows Client through clickonce, sorry

**Comment by lvanvugt** [comment]
> When launching Window Client from CSIDE it uses the dynamicsnav:// moniker - which wont grab the version of the Windows Client, which matches your container - but the one you have installed on the host.

Clear and a pity, but that's how I understood it. But why don't I see _Sessions_ in the search box in Windows Client that "belongs" to the docker container?

**Comment by kine** [comment]
Because it is sandbox, thus, expecting multitenant environment, thus not offering you to see the sessions on the server because there will be sessions to other tenants too? ;-)

**Comment by lvanvugt** [comment]
Hope not. ;-)

**Comment by kine** [comment]
Just overlooked the image name. I think Tobias answered. Check the authentication protocol in ClientUserSettings.config in profile.

**Comment by freddydk** [comment]
Sorry for my answer earlier. When creating a container with IncludeCSide, it doesn't use clickonce, so my answer was off.
But... - CSide will indeed use dynamicsnav: moniker to launch the Windows Client.
DynamicsNav: is automatically updated to point to the last windows client you have launched (WinClient will update the value in the registry here: HKEY_CLASSES_ROOT\DYNAMICSNAV\Shell\Open\Command)
So, if the last windows client you used was using a different service tier/authentication - it will fail.
3 ways to mitigate:
1. Start the right WIndows Client and close it again
2. Copy the shortcut on the desktop, name it "WinClient Debugger" and add "DynamicsNAV:////debug" to the parameters - then you have a shortcut for the debugger.
3. run this powershell line:
`New-DesktopShortcut -Name "WinClient Debugger" -TargetPath (Get-Item "C:\ProgramData\NavContainerHelper\Extensions\$containerName\Program Files\*\RoleTailored Client\Microsoft.Dynamics.Nav.Client.exe").FullName -Arguments "-settings:ClientUserSettings.config ""DynamicsNAV:////debug""" -WorkingDirectory (Get-Item "C:\ProgramData\NavContainerHelper\Extensions\$containerName\Program Files\140\RoleTailored Client").FullName`

**Comment by freddydk** [comment]
Shipped in 0.5.0.5

**Comment by lvanvugt** [comment]
Thanx for adding the shortcut, Freddy. Appreciated.
