### ISSUE TITLE
expose multiple ports on my local network fail

### ISSUE THREAD

**Issue by ImRLopezAG** [microsoft/navcontainerhelper#3620]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When I try to expose the ports to my local network it only expose the 80 port and I want to have multiple containers of diferent versions

**Scripts used to create container and cause the issue**
```
Import-Module Microsoft.PowerShell.Security

$containerName = 'latest'
$password = '-'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'admin', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'w1' -select 'Latest'
$licenseFile = 'my license'

New-BcContainer `
    -accept_eula `
    -accept_outdated `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -imageName 'onprem' `
    -licenseFile $licenseFile `
    -memoryLimit 8GB `
    -publishports @(80,5454)`
    -updateHosts

```

**Screenshots**
- 80
![image](https://github.com/user-attachments/assets/d6519a01-1063-46f7-8e56-1a5faadd22fc)
- 5454
![image](https://github.com/user-attachments/assets/f6544629-5748-41a4-ab59-fcb5ce64f64c)

**Comment by freddydk** [comment]
Maybe you should explain what you would expect to find on port 5454?

PublishPorts just exposes ports from a container - and the container doesn't listen on 5454

**Comment by ImRLopezAG** [comment]
I'm just trying to create some containers that listens different ports to use in my local network as a centralized server

**Comment by freddydk** [comment]
Typically, people use traefik for that.
But you should be able to create one container with WebClientPort set to 80 and publishPorts set to 80 as well - then then create a new container with WebClientPort set to f.ex. 81 and publishPorts set to 81

**Comment by ImRLopezAG** [comment]
That helped  me, the issue it's done
