### ISSUE TITLE
New-AadAppsForBc shows "-includeEmailAadApp is deprecated. Use -includeOtherServicesAadApp instead." but includeOtherServicesAadApp  us not setting email permissions

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#3621]
**Describe the issue**
When I want to create Entra apps for onprem container with AAD auth through New-AadAppsForBc including app for connecting to Email, cmdlet shows this warning:
```
-includeEmailAadApp is deprecated. Use -includeOtherServicesAadApp instead.
```
But when I remove includeEmailAadApp and use only includeOtherServicesAadApp, the created app does not have permissions to access the email like when includeEmailAadApp is used. I have checked this even in the code and the part for  includeOtherServicesAadApp does not assign any permissions which are assigned in includeEmailAadApp part.

I want to know what is the reason for having the warning there, because it seems that it is there since the flag was added into this cmdlet, see commit f72c5cf37aa22ca2333e6d4d6b3e9be63fb9658f. Is it false positive and the switch includeEmailAadApp should still be used?

**Comment by freddydk** [comment]
I think the warning is a false positive.
It isn't only about the permissions - there are also differences to implicitgrantsettings in EMail compared to OtherServices.
The warning is also there on PowerBI, which seems to be correct.

I will remove the warning.
