### ISSUE TITLE
PublishBcContainerApp-Override not working for me in Run-ALPipeline

### ISSUE THREAD

**Issue by EsatSayinkaplanAccelent** [microsoft/navcontainerhelper#3624]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
We have a problem with a dependency throwing 
![image](https://github.com/user-attachments/assets/41dc870d-42dd-43e5-af6a-89206cba9059)
while the table it is looking for is already installed before that. So my Idea was to override the Publish-BcContainerApp in the AlPipeline run with ForceSync.

**Scripts used to create container and cause the issue**
```
-PublishBcContainerApp { Param([HashTable] $parameters)
        PublishBcContainerApp @parameters -sync -syncMode 'ForceSync' -Verbose
        Write-Host 'Published successfully with ForceSync'
    }
```

**Full output of scripts**
```
BcContainerHelper is version 6.0.21-preview1222
BcContainerHelper is running as administrator
HyperV is Disabled
Host is Microsoft Windows Server 2022 Standard - 10.0.20348.2655
UsePsSession is True
UsePwshForBc24 is True
UseWinRmSession is allow
UseSslForWinRmSession is True
Docker Client Version is 27.1.1
Docker Server Version is 27.1.1
...
```
![image](https://github.com/user-attachments/assets/408bbd5c-7281-4959-bfa0-8d58b53e7100)

My Write Host Function does not execute too? Did I use the override wrong?

**Comment by EsatSayinkaplanAccelent** [comment]
Seems to be related with https://github.com/microsoft/AL/issues/7625

**Comment by freddydk** [comment]
Your write-host is after the command and since the command fails, you never see it.
It looks like the problem is unrelated to containerhelper and the override
