### ISSUE TITLE
Not possible to see the code from a runtime packages even "includeSourceInSymbolFile": true 

### ISSUE THREAD

**Issue by cosminahristofor** [microsoft/navcontainerhelper#3627]
**1 .Describe the bug**
 When debugging OnPrem Customers is not possible to see code from runtime packages even "includeSourceInSymbolFile": true was used in function Get-BcContainerAppRuntimePackage.

**2. To Reproduce**

We are using the next configuration for resourceExposurePolicy
"resourceExposurePolicy": {
"allowDebugging": true,
"allowDownloadingSource": true,
"includeSourceInSymbolFile": true
}
I used this command to get the runtime package
 Get-BcContainerAppRuntimePackage -containerName $ContainerName -appName $AppName -appFile "$Destination\$PackageName" **-IncludeSourceInPackageFile:$true**

**3. Expected behavior**
Code should be included (exposed) in the symbols of a downloaded runtime package when the package was created with -IncludeSourceInPackageFile $true parameter

**4. Actual behavior**
After the runtime package is published, when downloading symbols the objects are missing the code, not possible to add brake points, see the code from functions in debug mode , etc.

**5. Versions:**
•	AL Language: v13.1.1065068
•	Business Central application:  "24.0.0.0",
•	List of Visual Studio Code extensions that you have installed:
AL Language

**Comment by cosminahristofor** [comment]
From PowerShell is working as expected if we fallow the next steps :

* Export the .app with Get-BcContainerAppRuntimePackage
* Unpublish/uninstall the app
* Install the runtime package resulted from Get-BcContainerAppRuntimePackage using , Publish-NAVApp, Sync-NAVApp and Install-NAVApp
* Create a PTE
* Download symbols 
* We can see the code - OK

We are using this command also part of the pipeline that is generating the environment, and in this case when we create a PTE and Download symbols  we are not able to see the code. 

Is any difference in using the function manually (by using a PTE described above) or from a pipeline?

**Comment by freddydk** [comment]
There is no difference whether you run code locally or in a pipeline.

I am not entirely sure what the difference is though - in both samples, you are using Get-BcContainerAppRuntimePackage to get the runtime package - are you saying that the runtime package you are getting is different???

In example #1 - are you trying to use the runtime package as symbols in the symbols folder in VS Code?

**Comment by cosminahristofor** [comment]
In the end I think is a problem in our pipeline, because when I do the steps manually is working fine.
