### ISSUE TITLE
Different symbols for tests compilation between VSCode & NavContainerHelper, usage of CodeUnit "Assert" and AL0265: Reference to object Assert is ambiguous.

### ISSUE THREAD

**Issue by megel** [Microsoft/navcontainerhelper#363]
Hi @freddydk, currently I don't know where the problem is located - VS Code or NavContainerHelper - and what could be a solution: 
https://github.com/Microsoft/AL/issues/4658

However, I found out, NavContainerHelper download everytime the newest version of symbols and this is in my opinion the right way. What I don't understand is, why a compilation with the older version of symbols can be published (only possible with VS Code).

In consequence, I can run Tests with VS Code, but not in Azure DevOps :(
BR / Michael

**Comment by freddydk** [comment]
I will write up a blog about how all of this works - it is rather confusing.
If you are running hybrid development - you should NOT have a test dependency in app.json and you should unpublish the application and the test symbols.
Next version of NavContainerHelper will do this for you.

**Comment by freddydk** [comment]
Shipped in 0.5.0.5
