### ISSUE TITLE
download extensions

### ISSUE THREAD

**Issue by kalyankandimalla** [Microsoft/navcontainerhelper#365]
Hi,

  How can I find the extensions (*.app files) installed in my container? is it possible to find them?
  I have created new Business central container locally , and it contains some default extensions installed.

   I am not able to find them in path 'C:\ProgramData\NavContainerHelper\Extensions'
   Is there a command which we can use, to download these extensions?

**Comment by freddydk** [comment]
There is a function to download a runtime package from the container. Beside that I think some of the extensions are in the container file system if you open a prompt in the container

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: kalyankandimalla <notifications@github.com>
Sendt: Wednesday, February 27, 2019 7:38:01 AM
Til: Microsoft/navcontainerhelper
Cc: Subscribed
Emne: [Microsoft/navcontainerhelper] download extensions (#365)


Hi,

How can I find the extensions (*.app files) installed in my container? is it possible to find them?
I have created new Business central container locally , and it contains some default extensions installed.

I am not able to find them in path 'C:\ProgramData\NavContainerHelper\Extensions'
Is there a command which we can use, to download these extensions?

**Comment by kalyankandimalla** [comment]
downloading run time package helped,Thanks Freddy.
