### ISSUE TITLE
suggestion: add "start container" desktop shortcut to start container

### ISSUE THREAD

**Issue by CanuckNav74** [Microsoft/navcontainerhelper#366]
Currently when New-NavContainer creates a container, it will create one or more shortcuts on the desktop (e.g. RTC, C/Side, container powershell, container cmd.exe, web client). 

It would be helpful if it could create two new shortcuts as well:

* Start container "container-name"
* Stop container "container-name"

As a docker developer myself, I often switch between Linux and Windows kernels. However, when I switch from windows, to linux, and back to windows, the NAV/BC container doesn't start up despite the docker daemon switching kernels without any issues. Short of rebooting, the only option is to execute docker run with a littany of cmdline parameters for the NAV/BC container. 

It would be great if such a docker run desktop shortcut could be automatically created when the container itself is created, since it would take otherwise take time on my part to manually hunt down all the relevant options to fill in the blanks for "docker run"

**Comment by freddydk** [comment]
When I switch to Linux containers - my windows containers keep running - you cannot really interact with them - but when I switch back - they are still running.
Beside that, not sure I understand the docker run piece?
Are you asking for is a shortcut which calls

docker start containername

and one that does

docker stop containername

?

**Comment by CanuckNav74** [comment]
I'll try to repro (I agree, the windows containers should continue to run regardless of switching between Linux and windows containeds).

I was unaware of Docker start / Docker stop. My bad. If that's all that's needed then you can close this issue.

**Comment by CanuckNav74** [comment]
@freddydk I think I see what the problem is. I could use your input. 

When my BC docker container recycles, the BC container is given a new virtual IP address every time it spins up. This renders the RDLC/WebClient/cside shortcuts useless. 

I'm running Docker CE 2.0.0.3 (31529) stable (build 8858db3) for Windows 10 Pro (1809)

Below is the command I'm running to create the container:

`New-NavContainer -containerName microsoft-bc-ca -updateHosts -includeCSide -doNotExportObjectsToText -memoryLimit 4G -licenseFile "path-to-flf" -accept_eula -imageName microsoft/bcsandbox:ca`

sure enough, the cmdlet adds an entry to `c:\windows\system32\drivers\ets\hosts` on the docker host machine (which is what -updateHosts does). The problem is that entry becomes stale as soon as the BC container is recycled. 

To repro:

1. create the BC container via New-NavContainer
2. shell into the newly created container and enter `ping /4 {containername}`. The IP address returned will be the same as what is found in `c:\windows\system32\drivers\ets\hosts` on the docker host machine. 
3. stop and start the container
4. Repeat step 2. You will notice that the container has a new IP but the hosts file still has the original entry. 

Thoughts? Is there any way to prevent the virtual IP from changing when the BC container recycles? Or is there something I'm missing?

**Comment by freddydk** [comment]
The NavContainerHelper actually does this when you specify -updateHosts.
in c:\run\my\AdditionalSetup.ps1 (in the container) you should find:
```
. (Join-Path $PSScriptRoot "updatehosts.ps1") -hostsFile "c:\driversetc\hosts" -hostname fkdev -ipAddress $ip
```
Which will update the hosts file when starting.
I find that sometimes, Windows 10 will cache the ip address and I have to use ipconfig /flushdns in order to re-read the hosts file.
In fact - even when I type the content of the hosts file, it isn't updated always - sometimes ping will refresh, other times I need ipconfig /flushdns:
```
PS C:\WINDOWS\system32> type .\drivers\etc\hosts
172.16.78.74 host.docker.internal
172.16.78.74 gateway.docker.internal
172.25.202.75 fkwin
172.25.202.21 fkdev

PS C:\WINDOWS\system32> docker restart fkdev
fkdev

PS C:\WINDOWS\system32> type .\drivers\etc\hosts
172.16.78.74 host.docker.internal
172.16.78.74 gateway.docker.internal
172.25.202.75 fkwin
172.25.202.21 fkdev

PS C:\WINDOWS\system32> ping fkdev

Pinging fkdev [172.25.192.253] with 32 bytes of data:
Reply from 172.25.192.253: bytes=32 time=13ms TTL=128
Reply from 172.25.192.253: bytes=32 time<1ms TTL=128
Reply from 172.25.192.253: bytes=32 time<1ms TTL=128
Reply from 172.25.192.253: bytes=32 time<1ms TTL=128

Ping statistics for 172.25.192.253:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 13ms, Average = 3ms

PS C:\WINDOWS\system32> type .\drivers\etc\hosts
172.16.78.74 host.docker.internal
172.16.78.74 gateway.docker.internal
172.25.202.75 fkwin
172.25.192.253 fkdev
```
So - retry your scenario and use ipconfig /flushdns after your restart and see if this is the reason?
Look at this:
```
PS C:\WINDOWS\system32> type .\drivers\etc\hosts
172.16.78.74 host.docker.internal
172.16.78.74 gateway.docker.internal
172.25.202.75 fkwin
172.25.192.253 fkdev

PS C:\WINDOWS\system32> type .\drivers\etc\hosts
172.16.78.74 host.docker.internal
172.16.78.74 gateway.docker.internal
172.25.202.75 fkwin
172.25.192.253 fkdev

PS C:\WINDOWS\system32> type .\drivers\etc\hosts
172.16.78.74 host.docker.internal
172.16.78.74 gateway.docker.internal
172.25.202.75 fkwin
172.25.192.253 fkdev

PS C:\WINDOWS\system32> ipconfig /flushdns

Windows IP Configuration

Successfully flushed the DNS Resolver Cache.

PS C:\WINDOWS\system32> type .\drivers\etc\hosts
172.16.78.74 host.docker.internal
172.16.78.74 gateway.docker.internal
172.25.202.75 fkwin
172.25.192.231 fkdev
```

**Comment by CanuckNav74** [comment]
my repro results (it works as you say, with a caveat):
```
PS C:\windows\system32> type .\drivers\etc\hosts
10.120.1.9 SCILIV
10.120.1.11 NT4021013
192.168.0.55 host.docker.internal
192.168.0.55 gateway.docker.internal
172.22.64.158 microsoft-bc-ca

docker stop microsoft-bc-ca
docker start microsoft-bc-ca

PS C:\windows\system32> type .\drivers\etc\hosts
10.120.1.9 SCILIV
10.120.1.11 NT4021013
192.168.0.55 host.docker.internal
192.168.0.55 gateway.docker.internal
172.22.70.89 microsoft-bc-ca
```
It seems the hosts file update is not very quick. That could explain a lot.  After starting the container it took almost 20 seconds for the IP change to bubble up to the hosts file. I would have expected it to happen much sooner and may explain some red herrings inherant with this git issue.

**Comment by freddydk** [comment]
And if you throw in an ipconfig /flushdns after docker start - I would expect it to be instant.

**Comment by CanuckNav74** [comment]
Will do!
