### ISSUE TITLE
Error querying artifacts. Error message was Remote server error: (409) Conflict.

### ISSUE THREAD

**Issue by Frailty01** [microsoft/navcontainerhelper#3664]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When try dot download the public preview of the BC 25, receve the error message **Error querying artifacts. Error message was Remote server error: (409) Conflict.**

**Scripts used to create container and cause the issue**
```
Get-BCArtifactUrl -storageAccount bcpublicpreview -select latest -country us
```

**Full output of scripts**
```
NavContainerHelper is version 6.0.22
NavContainerHelper is running as administrator
Host is Microsoft Windows 11
Docker Client Version is 27.2.0
Docker Server Version is 27.2.0
...
```

**Screenshots**

**Additional context**
Has anyone had the same problem and could indicate how to solve it? 
![errore](https://github.com/user-attachments/assets/41c6241b-589f-473a-a8ee-b97c48032046)
Thank you

**Comment by Jupentti1** [comment]
StorageAccount bcpublicpreview is no more, use 

Get-BCArtifactUrl -country us -select NextMajor -accept_insiderEula

Also if creating container remember to add -accept_insiderEula in New-BCContainer script.
