### ISSUE TITLE
Question: Which platform is used by the Run-AlValidation

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/navcontainerhelper#3668]
From yammer threads I understood the online appsource validation is now using BC25 as the validation platform.
Running the bccontainerhelper cmdlet Run-AlValidation is still running against BC24.4

How does the Run-AlValidation determines the correct version to use?
Or can we use/choose a version?

**Comment by freddydk** [comment]
Run-AlValidation by default validates against the latest released version.
You can specify -ValidateNextMajor if you want to validate against next major.
Default is to -validateCurrent (I think)

**Comment by RonKoppelaar** [comment]
Understood. If this remains ruling its clear to me.
