### ISSUE TITLE
Executing the Run-AIValidation commandlet is failing with runtime 13.0

### ISSUE THREAD

**Issue by mleclairVSI** [microsoft/navcontainerhelper#3672]
I've recently upgraded my VM to: US Business Central 24.5 (Platform 24.0.24251.0 + Application 24.5.23489.24322)

Now, when I run my powershell script which includes the following:
Run-AlValidation
        -previousApps @($PreviousApp) 
        -apps @($CurrentApp) 
        -affixes @("VSI") 
        -countries @("ca") 

**Run-AlValidation is returning the following errors:**
app.json(32,5): error AL0124: The property 'resourceExposurePolicy' cannot be used in this context
app.json(35,5): error AL0124: The property 'source' cannot be used in this context
app.json(38,5): error AL0124: The property 'build' cannot be used in this context
app.json(10,5): error AL1043: The runtime version '13.0' is not supported by the AL compiler.

I've upgraded my bccontainerhelper to version 6.0.22.  I've upgraded my AL Language Extension to the pre release version of "v15.0.1129943" hoping this might help, but it didn't.

I am able to package my app and publish it to my VM with no issues ("application":  "24.0.0.0", "platform": "24.0.0.0", "runtime": "13.0").

This was working just fine about two weeks ago and I've never encountered this issue before.  I've been running this script for nearly two years now.

I'm really not sure what the problem can be at this point.

Thanks in advance for any help you might be able to provide regarding this.

Mike

**Comment by freddydk** [comment]
How does your app.json look? (please format as code)

**Comment by mleclairVSI** [comment]
Good morning Freddy and thank you for taking a bit of time to help me with this.  Here is my app.json.  I've replaced some values with x's for privacy.  Looks like some formatting is lost once I paste it here.

{
   "id":"xxx-xxx-xxx-xxx",
   "name":"xxx for Dynamics 365 Business Central",
   "publisher":"xxx Inc",
   "version":"1.0.0.20",
   "brief":"xxx for Dynamics 365 BC",
   "description":"xxx for Dynamics 365 BC",
   "privacyStatement":"https://xxx.com/about/",
   "EULA":"https://xxx.com/about/",
   "help":"https://xxx.com/contact/",
   "url":"https://xxx.com/",
   "logo":"xxxLogo.jpg",
   "target":"Cloud",
   "application":"24.0.0.0",
   "dependencies":[
      
   ],
   "screenshots":[
      
   ],
   "platform":"24.0.0.0",
   "idRanges":[
      {
         "from":23081634,
         "to":23082633
      }
   ],
   "runtime":"13.0",
   "contextSensitiveHelpUrl":"https://xxx.com/help/",
   "resourceExposurePolicy":{
      "allowDebugging":false,
      "allowDownloadingSource":false,
      "includeSourceInSymbolFile":false
   },
   "features":[
      "TranslationFile"
   ]
}
