### ISSUE TITLE
Download of AL Language extension package fails when trying to publish an app via Publish-NavContainerApp.ps1

### ISSUE THREAD

**Issue by apt-berg** [microsoft/navcontainerhelper#3673]
PLEASE DO NOT INCLUDE ANY PASSWORDS OR TOKENS IN YOUR ISSUE!!!

**Describe the issue**
When trying to publish an app via the Publish-NavContainerApp.ps1-script the download of the AL Language extension package fails.
We are using a try/catch-logic where the script mentioned above is being called. Up until yesterday there was no issue with that part of the script and there where also no changes made to the code on our side.

**Scripts used to create container and cause the issue**
```
$containerName = "CUST_CONTAINER_NAME"
$multiTenant = $false
$dnsServer = "8.8.8.8"
$memoryLimit = "6G"

$securePassword = try { "pass" | ConvertTo-SecureString } catch { ConvertTo-SecureString -String "pass" -AsPlainText -Force }
$credential = New-Object PSCredential -ArgumentList "user", $SecurePassword
$auth = 'UserPassword'

$artifactType = "Sandbox"
$artifactCountry = "de"
$artifactSelect = "Latest"
$artifactVersion = ""

$tenantName = "default"

if($artifactVersion -ne "") {
    $artifactUrl = Get-BcArtifactUrl -type $artifactType -country $artifactCountry -version $artifactVersion -select $artifactSelect
} else {
    $artifactUrl = Get-BcArtifactUrl -type $artifactType -country $artifactCountry -select $artifactSelect
}
Write-Host "Container will be using artifact ""$artifactUrl""."

if(-Not (Test-BCContainer -containerName $containerName)){
    Write-Host "Container doesn't exist, creating container"
    New-BcContainer `
        -accept_eula `
        -containerName $containerName `
        -credential $credential `
        -auth $auth `
        -artifactUrl $artifactUrl `
        -multitenant:$multiTenant `
        -assignPremiumPlan `
        -dns $dnsServer `
        -isolation 'process' `
        -memoryLimit $memoryLimit `
        -updateHosts `
        -additionalParameters '--net="pub"' `
        @optionalParameter
        Write-Host "Creating backup"
        Backup-BCContainerDatabases -containerName $containerName -bakFolder $containerName -tenant $tenantName
}
```

**Full output of scripts**
```
BcContainerHelper is version 6.0.22
BcContainerHelper is running as administrator
HyperV is Disabled
Host is Microsoft Windows Server 2022 Standard Evaluation - 10.0.20348.2113
UsePsSession is True
UsePwshForBc24 is True
UseWinRmSession is allow
UseSslForWinRmSession is True
Docker Client Version is master-dockerproject-2022-03-26
Docker Server Version is master-dockerproject-2022-03-26
```

**Output of where Publish-NavContainerApp.ps1 is embedded**
```

Ignoring unchanged config setting apiBaseUrl
Ignoring unchanged config setting SendExtendedTelemetryToMicrosoft
Ignoring unchanged config setting addTryCatchToScriptBlock
Ignoring unchanged config setting useVolumeForMyFolder
Ignoring unchanged config setting TrustedNuGetFeeds
Ignoring unchanged config setting DOCKER_SCAN_SUGGEST
Ignoring unchanged config setting ObjectIdForInternalUse
Ignoring unchanged config setting DebugMode
Ignoring unchanged config setting MSSymbolsNuGetFeedUrl
Ignoring unchanged config setting WinRmCredentials
Ignoring unchanged config setting NoOfSecondsToSleepAfterPublishBcContainerApp
Ignoring unchanged config setting defaultContainerName
Ignoring unchanged config setting usePsSession
Ignoring unchanged config setting UseNewFormatForGetBcContainerAppInfo
Ignoring unchanged config setting psSessionTimeout
Ignoring unchanged config setting TraefikImage
Ignoring unchanged config setting digestAlgorithm
Ignoring unchanged config setting mapNetworkSettings
Ignoring unchanged config setting usePwshForBc24
Ignoring unchanged config setting useVolumes
Ignoring unchanged config setting DoNotUseCdnForArtifacts
Ignoring unchanged config setting useSslForWinRmSession
Ignoring unchanged config setting defaultNewContainerParameters
Ignoring unchanged config setting sandboxContainersAreMultitenantByDefault
Ignoring unchanged config setting RenewClientContextBetweenTests
Ignoring unchanged config setting IsGitHubActions
Ignoring unchanged config setting mapCountryCode
Ignoring unchanged config setting MSAppsNuGetFeedUrl
Ignoring unchanged config setting WarningPreference
Ignoring unchanged config setting PartnerTelemetryConnectionString
Ignoring unchanged config setting TreatWarningsAsErrors
Setting hostHelperFolder = C:\ProgramData\BcContainerHelper
Ignoring unchanged config setting use7zipIfAvailable
Ignoring unchanged config setting TraefikUseDnsNameAsHostName
Ignoring unchanged config setting MinimumDotNetRuntimeVersionUrl
Setting MicrosoftTelemetryConnectionString = 
Ignoring unchanged config setting MinimumDotNetRuntimeVersionStr
Ignoring unchanged config setting artifactDownloadTimeout
Ignoring unchanged config setting IsGitLab
Setting usePrereleaseAlTool = False
Ignoring unchanged config setting timeStampServer
Setting bcartifactsCacheFolder = c:\bcartifacts.cache
Ignoring unchanged config setting AddHostDnsServersToNatContainers
Running on Windows, PowerShell 5.1.20348.2110
Downloading AL Language Extension to C:\ProgramData\BcContainerHelper\alLanguageExtension\13.1.1065068.zip
Error downloading..., retrying in 3 seconds...
##[error]C:\ado\{CUSTOMER_NAME}\_work\1\s\Pipeline\Publish-AppsFromNugetPackages.ps1 : Couldn't publish app 
"C:\ado\{CUSTOMER_NAME}\_work\1\s\Packages\{CustomApp}.{CustomApp}.BC22.0.Core.8.1.0.273509\App\Core 8.1.0.273509 - 22.0 (BC 2023 Wave 1).app"
At C:\ado\{CUSTOMER_NAME}\_work\_temp\ec87ceb8-1a14-45f5-9b38-549b3a9d8d4e.ps1:4 char:1
+ . 'C:\ado\{CUSTOMER_NAME}\_work\1\s\Pipeline\Publish-AppsFromNugetPack ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Publish-AppsFromNugetPackages.ps1
##[error]PowerShell exited with code '1'.

```

**Screenshots**
No applicable screenshots besides the script outputs above.

**Additional context**
- does it happen all the time?
  It started happening this morning (20. Sep 2024 CEST-Zone). Before that there was no issue.
- did it use to work
  Yes up until today. No changes were made to the script
- impact
  currently this affects all our customers using this script to publish Third-Party-Apps

**Comment by freddydk** [comment]
did you retry to see whether this is a transient error?

**Comment by apt-berg** [comment]
Unfortunately it seems to not be a transient issue. We hoped that with the new BCContainerHelper Version 6.0.23 thes issue would go away but sadly it doesn't.
The error stays the same even with the latest Version.

**Comment by freddydk** [comment]
Could this be a virus scanner or like?
A blocked URL from your firewall?

Get-LatestAlLanguageExtensionUrl will give you the URL - try to download it manually?

**Comment by ferdmann98** [comment]
Hey freddy,
I'm a colleague of apt-berg. This is a good hint.

`Get-LatestAlLanguageExtensionUrl`
on my laptop returns
`https://ms-dynamics-smb.gallerycdn.vsassets.io/extensions/ms-dynamics-smb/al/13.1.1065068/1719990131247/Microsoft.VisualStudio.Services.VSIXPackage`

The manual download of this package (from a different network) works, so it could be a faulty network configuration. We will check that.

**Comment by apt-berg** [comment]
After checking the firewall settings aswell as the settings of our anti-virus software we saw that there is nothing that gets blocked by them so unfortnately this is not the issue either. As @ferdmann98 mentioned it is possible to open that link and download the package on any machine in the network.

**Comment by freddydk** [comment]
Ahhh - this is because you have a bccontainerhelper.settings.json full of settings which shouldn't be there - remove the settings file and only include the changed settings

**Comment by freddydk** [comment]
And you are right 13.1 is the latest version.
What is this: Publish-AppsFromNugetPackages.ps1 ?

**Comment by ferdmann98** [comment]
Yeah, our first assumption was that the prerelease version of the AL Language Extension was the cause of the error.
Thus I've set `usePrereleaseAlTool` to `false` in our scripts.
After setting that to false, version 13.1.1065068 has been downloaded. This download ran into the same error ("timeout downloading file")
After going through the code today, I've found out that Download-File.ps1 is invoked for downloading the AL Language Extension and initializes the `$timeout` variable with the setting `$bcContainerHelperConfig.defaultDownloadTimeout` which was set to 120 (seconds), see below.
I've increased that setting to 600 (seconds) and now everything works fine. It was just a timeout like the message said...

`PS C:\Users\erdmann\Desktop> $bcContainerHelperConfig | findstr defaultDownloadTimeout`
returned
`defaultDownloadTimeout         120`



![image](https://github.com/user-attachments/assets/d31e2552-8ab8-4e7b-887e-7a7f66872436)

**Comment by ferdmann98** [comment]
> And you are right 13.1 is the latest version. What is this: Publish-AppsFromNugetPackages.ps1 ?

This is one script in our build pipelines which is executed when third party apps need to be installed. The third party apps are fetched from our nuget feed.

**Comment by freddydk** [comment]
120 seconds to download the vsix seems like a lot.

**Comment by ferdmann98** [comment]
> 120 seconds to download the vsix seems like a lot.

Yup, we're currently updating from PowerShell 5.1.x to the current version. Maybe this will fix our other problem that we run into a timeout during container creation.
Thank you very much for your help!

**Comment by ferdmann98** [comment]
Hey @freddydk, a short update in this matter and to everyone reading this in the future:
We currently have a problem with our ISP (bandwidth), so that's probably the cause of the initial problem described here and also to our current problem that the download of the container images takes extremely long.
We got there by downloading the images from different networks. The bandwidth in our headquarter is currently very low.
