### ISSUE TITLE
Provisioning a (NextMajor) container on Azure using aka.ms/getbc fails when including TestToolkit

### ISSUE THREAD

**Issue by tinestaric** [microsoft/navcontainerhelper#3676]
As the title suggests, I'm trying to provision a new container on Azure using the template from aka.ms/getbc

The script fails when trying to run the container with the following error:
![image (1)](https://github.com/user-attachments/assets/90bde307-58a6-49f5-a614-d16c98bec571)

Here's the full configuration that fails:
![image](https://github.com/user-attachments/assets/cd265577-1e86-48b2-8fd3-cd08ef47e770)

I've noticed that the scripts don't fail if I don't include TestToolkit.

**Comment by freddydk** [comment]
I don't think this error has anything to do with test toolkit - it throws a not supported error, which typically is docker related and seems to fail before it gets the container created at all.
Standard_D4s_v3 does have hyperv support - so that is not the problem.
Any chance you could include the full log?

**Comment by tinestaric** [comment]
Here's the full log for the most recent run (with TestToolkit). 
I must have pasted an older error above, from the time when I was trying to create it with a different configuration than Standard_D3s_v3. Apologies for that. The error in this log is the error I have been receiving for the past few days, that led me to believe it had something to do with the test toolkit.

[View Landing Page](http://bc-shopify-new.northeurope.cloudapp.azure.com/)   [Disable refresh](http://bc-shopify-new.northeurope.cloudapp.azure.com/status.aspx?norefresh)

9:04:03 AM at , C:\demo\setupVm.ps1: line 347
9:04:03 AM at , C:\demo\SetupNavContainer.ps1: line 404
9:04:03 AM at New-BcContainer, C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\6.0.23\ContainerHandling\New-NavContainer.ps1: line 622
9:04:03 AM at New-BcImage, C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\6.0.23\ContainerHandling\New-NavImage.ps1: line 711
9:04:03 AM at DockerDo, C:\Program Files\WindowsPowerShell\Modules\bccontainerhelper\6.0.23\HelperFunctions.ps1: line 241
Commandline: docker build --isolation=process --memory 8G --no-cache --tag mybc:25.0.23364.24538-w1 c:\bcartifacts.cache\hryvjcnm.30e
ExitCode: 1
9:04:03 AM The command 'powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; \Run\start.ps1 -installOnly -multitenant -includeTestToolkit' returned a non-zero code: 1
9:04:03 AM Container output
8:43:14 AM Running container (this might take some time)
8:43:14 AM Locale en-US
8:43:14 AM Version 25.0.23364.24538
8:43:14 AM Country w1
8:43:14 AM Using artifactUrl https://bcinsider-fvh2ekdjecfjd6gk.b02.azurefd.net/sandbox/25.0.23364.24538/w1
8:39:14 AM Installing OpenXML 2.5
8:39:10 AM Installing SQL Native Client
8:38:59 AM Installing Visual C++ Redist
8:38:59 AM mcr.microsoft.com/businesscentral:ltsc2022
8:38:59 AM Status: Downloaded newer image for mcr.microsoft.com/businesscentral:ltsc2022
8:38:59 AM Digest: sha256:a4af04e32179fdd313304f54dcc120b4086fa3a59660b618a59d9d583d078073
8:38:59 AM 0e22a908e432: Pull complete
8:38:58 AM 392cc3c6de23: Pull complete
8:38:57 AM 6a8856696975: Pull complete
8:38:56 AM 7bce2fd94276: Pull complete
8:38:55 AM effc667e27f9: Pull complete
8:38:43 AM 52d5c44b8039: Pull complete
8:36:16 AM a2f315f19e3e: Pull complete
8:36:14 AM ad167495b313: Pull complete
8:36:14 AM 5d926e5f3a65: Pull complete
8:36:13 AM e46b0fb50af2: Pull complete
8:36:12 AM 508c6164f808: Pull complete
8:35:58 AM cb7bb12a50c4: Pull complete
8:35:58 AM 2534953f34d3: Pull complete
8:32:40 AM 52d5c44b8039: Download complete
8:32:40 AM 52d5c44b8039: Verifying Checksum
8:32:36 AM 2534953f34d3: Download complete
8:32:36 AM 2534953f34d3: Verifying Checksum
8:32:23 AM 0e22a908e432: Download complete
8:32:23 AM 0e22a908e432: Verifying Checksum
8:32:23 AM 392cc3c6de23: Download complete
8:32:23 AM 392cc3c6de23: Verifying Checksum
8:32:23 AM 6a8856696975: Download complete
8:32:23 AM 6a8856696975: Verifying Checksum
8:32:23 AM 7bce2fd94276: Download complete
8:32:23 AM 7bce2fd94276: Verifying Checksum
8:32:23 AM effc667e27f9: Download complete
8:32:23 AM effc667e27f9: Verifying Checksum
8:32:23 AM 508c6164f808: Download complete
8:32:23 AM 508c6164f808: Verifying Checksum
8:32:23 AM a2f315f19e3e: Download complete
8:32:23 AM a2f315f19e3e: Verifying Checksum
8:32:23 AM ad167495b313: Download complete
8:32:23 AM ad167495b313: Verifying Checksum
8:32:23 AM 5d926e5f3a65: Download complete
8:32:23 AM 5d926e5f3a65: Verifying Checksum
8:32:23 AM e46b0fb50af2: Download complete
8:32:23 AM e46b0fb50af2: Verifying Checksum
8:32:23 AM cb7bb12a50c4: Download complete
8:32:23 AM cb7bb12a50c4: Verifying Checksum
8:32:23 AM 0e22a908e432: Waiting
8:32:22 AM 392cc3c6de23: Waiting
8:32:22 AM 6a8856696975: Waiting
8:32:22 AM 7bce2fd94276: Waiting
8:32:22 AM effc667e27f9: Waiting
8:32:22 AM 52d5c44b8039: Waiting
8:32:22 AM a2f315f19e3e: Waiting
8:32:22 AM 0e22a908e432: Pulling fs layer
8:32:22 AM 392cc3c6de23: Pulling fs layer
8:32:22 AM ad167495b313: Waiting
8:32:22 AM 6a8856696975: Pulling fs layer
8:32:22 AM 7bce2fd94276: Pulling fs layer
8:32:22 AM effc667e27f9: Pulling fs layer
8:32:22 AM 5d926e5f3a65: Waiting
8:32:22 AM 52d5c44b8039: Pulling fs layer
8:32:21 AM e46b0fb50af2: Waiting
8:32:21 AM a2f315f19e3e: Pulling fs layer
8:32:20 AM ad167495b313: Pulling fs layer
8:32:20 AM 5d926e5f3a65: Pulling fs layer
8:32:20 AM e46b0fb50af2: Pulling fs layer
8:32:20 AM 508c6164f808: Pulling fs layer
8:32:20 AM cb7bb12a50c4: Pulling fs layer
8:32:20 AM 2534953f34d3: Pulling fs layer
8:32:20 AM ltsc2022: Pulling from businesscentral
8:32:20 AM Pulling mcr.microsoft.com/businesscentral:ltsc2022 (this might take some time)
8:32:18 AM Adding Landing Page to Startup Group
8:32:18 AM Add Import bccontainerhelper to PowerShell profile
8:32:18 AM Disabling Server Manager Open At Logon
8:32:18 AM Show hidden files and file types
8:32:18 AM Enabling Font Download in IE
8:32:18 AM Enabling File Download in IE
8:32:18 AM Starting docker
8:31:58 AM Using Lets Encrypt certificate
8:31:06 AM Installing ACME-PS PowerShell Module
8:30:44 AM SetupVm, User: vmadmin
8:30:32 AM Launch SetupVm
8:30:31 AM Register RestartContainers Task to start container delayed
8:29:04 AM Installing SqlServer module
8:16:01 AM Installing Microsoft.Graph module
8:15:47 AM Installing AzureAD module
8:08:53 AM Installing Az module
8:08:52 AM Using BcContainerHelper version 6.0.23
8:08:10 AM Installing Latest Business Central Container Helper from PowerShell Gallery
8:08:07 AM SetupStart, User: bc-shopify-new$
8:05:40 AM Restarting computer and start Installation tasks
8:04:04 AM Downloading C:\DEMO\InstallOrUpdateDockerEngine.ps1
8:04:04 AM Downloading C:\DEMO\Install-VS2017Community.ps1
8:04:04 AM Downloading c:\demo\restartContainers.ps1
8:04:04 AM Downloading c:\demo\SetupStart.ps1
8:04:04 AM Downloading c:\demo\SetupVm.ps1
8:04:04 AM Downloading c:\demo\SetupNavContainer.ps1
8:04:03 AM Downloading c:\demo\SetupDesktop.ps1
8:04:03 AM Downloading c:\myfolder\SetupWebClient.ps1
8:04:03 AM Turning off IE Enhanced Security Configuration
8:04:03 AM Creating Connect.rdp
8:04:03 AM Downloading C:\inetpub\wwwroot\web.config
8:04:03 AM Downloading C:\inetpub\wwwroot\Microsoft.png
8:04:03 AM Downloading C:\inetpub\wwwroot\line.png
8:04:02 AM Downloading C:\inetpub\wwwroot\status.aspx
8:04:02 AM Downloading C:\inetpub\wwwroot\default.aspx
8:01:28 AM Installing Internet Information Server (this might take a few minutes)
8:01:15 AM Installing PowerShellGet 2.2.5
8:01:13 AM Installing NuGet Package Provider
8:00:52 AM TemplateLink: https://raw.githubusercontent.com/Microsoft/nav-arm-templates/main/getbc.json
8:00:52 AM Initialize, user: bc-shopify-new$
8:00:52 AM Running Windows Server 2022 Datacenter
8:00:52 AM Starting initialization

**Comment by freddydk** [comment]
The reason for this is the generic image not knowing about the AI Test Toolkit.
It should do so now.

**Comment by freddydk** [comment]
Just finished my test - works now, thanks for reporting.

**Comment by freddydk** [comment]
Generic tag needs to be 1.0.2.46
