### ISSUE TITLE
Permission issue preveting posting on sandbox dockers

### ISSUE THREAD

**Issue by BMSPedro** [microsoft/navcontainerhelper#3680]
when creating containers from Sandbox artifacts, a permission error prevents certain transactions from being posted.

<img width="640" alt="image" src="https://github.com/user-attachments/assets/146bf94d-9ab5-42c2-80f3-d3d765033f1b">

**Comment by freddydk** [comment]
You need to give me a little more than this.
There are 1000s of containers started every day on sandbox artifacts, where this doesn't happen, so you need to at least provide script and output if you want any assistance.

**Comment by BMSPedro** [comment]
Hello Freddy

Thank you for your response and sorry for the delay in mine.
I have the feeling that the phenomenon occurs with all sandbox containers.

Scritp:
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String ***@***.***' -AsPlainText -Force)
New-BcContainer -accept_eula -containerName BC250W1T -artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.0.23364.25359/w1 -assignPremiumPlan -auth NavUserPassword -Credential $credential -isolation hyperv -shortcuts None -updateHosts
last artifact BC is used.
***@***.***

Thanks again,
Pedro

De : Freddy Kristiansen ***@***.***>
Envoyé : jeudi 10 octobre 2024 07:49
À : microsoft/navcontainerhelper ***@***.***>
Cc : PERERA AGUILA Pedro ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/navcontainerhelper] Permission issue preveting posting on sandbox dockers (Issue #3680)


Closed #3680<https://github.com/microsoft/navcontainerhelper/issues/3680> as completed.

-

**Comment by freddydk** [comment]
Yeah, well the error message leaves a lot for interpretation/guessing - which wastes a lot of time for people looking at this.
If you could describe what you are doing to provoke this - whether this happens in 24 versions as well and a lot more information, which makes it possible for us to run the script and do the same things - or maybe even say that this is expected with the license file used.

**Comment by BMSPedro** [comment]
Thanks a lot,
important to specify that this problem does not exist on on-prem artifacts

De : Freddy Kristiansen ***@***.***>
Envoyé : jeudi 10 octobre 2024 10:27
À : microsoft/navcontainerhelper ***@***.***>
Cc : PERERA AGUILA Pedro ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/navcontainerhelper] Permission issue preveting posting on sandbox dockers (Issue #3680)


Yeah, well the error message leaves a lot for interpretation/guessing - which wastes a lot of time for people looking at this.
If you could describe what you are doing to provoke this - whether this happens in 24 versions as well and a lot more information, which makes it possible for us to run the script and do the same things - or maybe even say that this is expected with the license file used.

-

**Comment by BMSPedro** [comment]
with BC24 there is the same problem.
We try to post a simple General Journal.
The license file used is that of demo, cronus by default.

Thanks Freddy for your answers.. (we get around the problem by using on-prem artifacts)

De : Freddy Kristiansen ***@***.***>
Envoyé : jeudi 10 octobre 2024 10:27
À : microsoft/navcontainerhelper ***@***.***>
Cc : PERERA AGUILA Pedro ***@***.***>; Author ***@***.***>
Objet : Re: [microsoft/navcontainerhelper] Permission issue preveting posting on sandbox dockers (Issue #3680)


Yeah, well the error message leaves a lot for interpretation/guessing - which wastes a lot of time for people looking at this.
If you could describe what you are doing to provoke this - whether this happens in 24 versions as well and a lot more information, which makes it possible for us to run the script and do the same things - or maybe even say that this is expected with the license file used.

-
