### ISSUE TITLE
[QUESTION] [warning]Free memory is lower than 5%; Currently used: 95.03%

### ISSUE THREAD

**Issue by akhileshekartha** [microsoft/navcontainerhelper#3681]
Hi, 
 
Our build pipeline is displaying the following warning:

 "[Warning] Free memory is lower than 5%; currently used: 95.03%." 

Could you please advise on how to resolve this issue? The build server has sufficient free space on the C drive and has 16 GB of RAM.

```


Run-AlPipeline  -containerName $ContainerName `
    -imageName 'bc' `
    -baseFolder $WorkFolder `
    -credential $credential `
    -keepContainer `
    -licenseFile $latest_License `
    -CreateRuntimePackages `
    -BuildArtifactFolder $WorkFolder\AppFiles `
    -accept_insiderEula `
    -previousApps $Previousapp `
    -installApps $a `
    -azureDevOps `
    -appFolders @("Project") `
    -AppRevision $AppRevision `
    -enablePerTenantExtensionCop `
    -AppBuild $buildID `
    -artifact $bcArtifacts 

```

**Screenshots**
![image](https://github.com/user-attachments/assets/0c733bb4-5c65-4765-956c-5afabda7b69c)

![image](https://github.com/user-attachments/assets/f4c87f0b-beb3-4bc1-b7ce-d9f05748c4e3)

![image](https://github.com/user-attachments/assets/04e4a53f-1eb8-401a-b4cc-32c091c46273)

**Comment by freddydk** [comment]
Add -memoryLimit 12G maybe?

**Comment by akhileshekartha** [comment]
@freddydk I have updated memoryLimit; it seems ok now. Thank you :)

**Comment by akhileshekartha** [comment]
![Image](https://github.com/user-attachments/assets/b227f2ad-d705-447d-b5a9-b90773a3ef5f)
