### ISSUE TITLE
Orphan log line in Azure DevOps pipeline grouped output

### ISSUE THREAD

**Issue by RadoArvay** [microsoft/navcontainerhelper#3684]
Recently (#3430), the groupping of output from pipeline was improved - now it works for Azure DevOps as well.
But there is one orphan line out of any group for `Run-AlPipeline` command. Would it be possible to move it into any group?
That line is: _70 Determining artifacts to use_

![image](https://github.com/user-attachments/assets/c30856b5-92f6-413a-8559-98d254ce12fe)
Note: there is the _Configurations_ group in the picture - it is ours and I believe/hope it does not cause this issue.

**Comment by freddydk** [comment]
It is correct that the Determining artifacts to use isn't part of any group - it is a stand-alone status text.
Would seem strange to have a group with one line - or?

**Comment by RadoArvay** [comment]
If it is meant that, then ok.
I did not think about creating a new group for this text. My question was more like if it shlould not be a part of Parameters or something like that...meant if it is not a bug.

**Comment by freddydk** [comment]
Not a bug
