### ISSUE TITLE
Support for AppSource preview in Install-BcAppFromAppSource

### ISSUE THREAD

**Issue by joandrsn** [microsoft/navcontainerhelper#3690]
**Describe the issue**
According to the [What's new: Developer tools](https://www.youtube.com/watch?v=tzeO0mc8RJo), customers should be able to access previews of AppSource-apps using the following URL:

```
https://businesscentral.dynamics.com/[TenantID]/?noSignUpCheck=1&filter='ID' IS '[AppID]' AND 'PreviewKey' IS '[PreviewKey]'&page=2503
```  

In the function `Install-BcAppFromAppSource`([Saas/Install-BcAppFromAppSource.ps1](https://github.com/microsoft/navcontainerhelper/blob/7eae9131ad3fcc9666022febc51278adac44c090/Saas/Install-BcAppFromAppSource.ps1)), I do not see any support for providing a PreviewKey.
Is installing previews of AppSource-apps not supported by BCContainerHelper? Or is the PreviewKey parameter simply skipped?

I am questioning this, because some of our developers wish to test a preview AppSource-app on our own sandbox before pressing the "Go Live" button in AppSource.

**Comment by freddydk** [comment]
Currently the API doesn't support installing preview apps - that is only supported in the UI.
Please request this functionality from the developer tools people (I have also done so) before we can add support here.

**Comment by joandrsn** [comment]
Thank you @freddydk. As for requesting the functionality from the developer tools people, where exactly do we do that?
On [BCIdeas](https://aka.ms/bcideas)?
