### ISSUE TITLE
Error creating BC25 container with database on host machine

### ISSUE THREAD

**Issue by petegonnella** [microsoft/navcontainerhelper#3695]
**Describe the issue**
Error creating BC25 container with database on host machine

**Scripts used to create container and cause the issue**
```
$setupDatabaseScript = @'
. 'C:\Run\SetupDatabase.ps1'
if (!$restartingInstance) {
    Copy-NavDatabase -databaseserver $DatabaseServer -databaseInstance $databaseInstance -databaseCredentials $databaseCredentials -sourcedatabaseName $databaseName -destinationDatabaseName "TestAppBC25-$tenantId"
    Copy-NavDatabase -databaseserver $DatabaseServer -databaseInstance $databaseInstance -databaseCredentials $databaseCredentials -sourcedatabaseName $databaseName -destinationDatabaseName "TestAppBC25-tenant"
}
'@

$setupTenantScript = @'
. 'c:\Run\SetupTenant.ps1'
if (!$restartingInstance) {
    Mount-NavDatabase -databaseserver $DatabaseServer -databaseInstance $databaseInstance -databaseCredentials $databaseCredentials -ServerInstance $ServerInstance -TenantId $TenantId -DatabaseName "TestAppBC25-$tenantId"
}
'@
$containerName = "TestAppBC25"


$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword101' -AsPlainText -Force)
$dbcredentials = New-Object PSCredential -ArgumentList 'REDACTED', (ConvertTo-SecureString -String 'REDACTED' -AsPlainText -Force)
$artifactUrl = Get-BCArtifactUrl -version 25 -country w1



$databaseName = 'TestAppBC25'

New-BCContainer `
    -accept_eula `
    -containerName $containerName `
    -artifactUrl $artifactUrl `
    -updateHosts `
    -auth UserPassword `
    -Credential $credential `
    -licensefile "e:\container\BC24.bclicense"  `
    -databaseServer 'host.containerhelper.internal' `
    -databaseInstance 'SQL2019' `
    -databaseName $databaseName `
     -PublicDnsName "REDACTED" `
    -memorylimit 32G `
    -databaseCredential $dbcredentials `
    -includeTestToolkit `
    -includePerformanceToolkit `
    -multitenant `
    -myScripts @(
        "https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/HelperFunctions.ps1"
        @{ "SetupDatabase.ps1" = $setupDatabaseScript }
        @{ "SetupTenant.ps1" = $setupTenantScript }
    )
```

**Full output of scripts**

```
BcContainerHelper is version 6.0.24
BcContainerHelper is running as administrator
HyperV is Disabled
Host is Microsoft Windows Server 2019 Standard - 10.0.17763.6293
UsePsSession is True
UsePwshForBc24 is True
UseWinRmSession is allow
UseSslForWinRmSession is True
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Removing Session TestAppBC25
Removing container TestAppBC25
Removing entries from hosts
Removing TestAppBC25 from container hosts file
Removing TestAppBC25-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\TestAppBC25
Fetching all docker images
Fetching all docker volumes
WARNING: useTraefik not specified, but Traefik container was initialized, using Traefik. Specify -useTraefik:$false if you do NOT want to use Traefik.
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image mcr.microsoft.com/businesscentral:ltsc2019
PublicDnsName is #REDACTED#
Creating Container TestAppBC25
Style: sandbox
Multitenant: Yes
Version: 25.0.23364.24925
Platform: 25.0.24850.0
Generic Tag: 1.0.2.20
Container OS Version: 10.0.17763.5696 (ltsc2019)
Host OS Version: 10.0.17763.6293 (ltsc2019)
WARNING: Host OS and Base Image Container OS doesn't match and HyperV is not installed. If you encounter issues, you could try to install HyperV.
Using process isolation
Using locale en-US
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\BcContainerHelper\Extensions\TestAppBC25\my\HelperFunctions.ps1
Using license file e:\container\BC24.bclicense
Additional Parameters:
--expose 5986
-e webserverinstance=TestAppBC25
-e publicdnsname=#REDACTED#
-l "traefik.protocol=https"
-l "traefik.web.frontend.rule=PathPrefix:/TestAppBC25"
-l "traefik.web.port=443"
-l "traefik.soap.frontend.rule=PathPrefix:/TestAppBC25soap;ReplacePathRegex: ^/TestAppBC25soap(.*) /BC$1"
-l "traefik.soap.port=7047"
-l "traefik.rest.frontend.rule=PathPrefix:/TestAppBC25rest;ReplacePathRegex: ^/TestAppBC25rest(.*) /BC$1"
-l "traefik.rest.port=7048"
-l "traefik.dev.frontend.rule=PathPrefix:/TestAppBC25dev;ReplacePathRegex: ^/TestAppBC25dev(.*) /BC$1"
-l "traefik.dev.port=7049"
-l "traefik.snap.frontend.rule=PathPrefix:/TestAppBC25snap;ReplacePathRegex: ^/TestAppBC25snap(.*) /BC$1"
-l "traefik.snap.port=7083"
-l "traefik.dl.frontend.rule=PathPrefixStrip:/TestAppBC25dl"
-l "traefik.dl.port=8080"
-l "traefik.dl.protocol=http"
-l "traefik.enable=true"
-l "traefik.frontend.entryPoints=https"
--env customNavSettings=PublicODataBaseUrl=https://#REDACTED#/TestAppBC25rest/odata,PublicSOAPBaseUrl=https://#REDACTED#/TestAppBC25soap/ws,PublicWebBaseUrl=https://#REDACTED#/TestAppBC25
Files in C:\ProgramData\BcContainerHelper\Extensions\TestAppBC25\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- CheckHealth.ps1
- HelperFunctions.ps1
- license.bclicense
- MainLoop.ps1
- SetupDatabase.ps1
- SetupTenant.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container TestAppBC25 from image mcr.microsoft.com/businesscentral:ltsc2019
bacfea6f53afa1ad508b7973705bd6c16f9a46cca80c840f95cf242615b6d735
Waiting for container TestAppBC25 to be ready
Using artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.0.23364.24925/w1
Using installer from C:\Run\240
Installing Business Central: multitenant=True, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\sandbox\25.0.23364.24925\w1, platformArtifactPath=c:\dl\sandbox\25.0.23364.24925\platform, databasePath=, licenseFilePath=c:\dl\sandbox\25.0.2
3364.24925\w1\Cronus.bclicense, rebootContainer=True
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\25.0.23364.24925\platform\ServiceTier\Program Files
c:\dl\sandbox\25.0.23364.24925\platform\ServiceTier\System64Folder
Copying Web Client Files
c:\dl\sandbox\25.0.23364.24925\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\25.0.23364.24925\platform
c:\dl\sandbox\25.0.23364.24925\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\25.0.23364.24925\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\25.0.23364.24925\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\25.0.23364.24925\w1\Extensions
Copying Applications
C:\dl\sandbox\25.0.23364.24925\platform\Applications
Copying dependencies
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 23 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.28.32.1 in container hosts file
Starting Container
Hostname is TestAppBC25
PublicDnsName is #REDACTED#
Using NavUserPassword Authentication
Import Encryption Key
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
at <ScriptBlock>, <No file>: line 15
at <ScriptBlock>, <No file>: line 1Error
Using artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.0.23364.24925/w1
Using installer from C:\Run\240
Installing Business Central: multitenant=True, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\sandbox\25.0.23364.24925\w1, platformArtifactPath=c:\dl\sandbox\25.0.23364.24925\platform, databasePath=, licenseFilePath=c:\dl\sandbox\25.0.2
3364.24925\w1\Cronus.bclicense, rebootContainer=True
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\sandbox\25.0.23364.24925\platform\ServiceTier\Program Files
c:\dl\sandbox\25.0.23364.24925\platform\ServiceTier\System64Folder
Copying Web Client Files
c:\dl\sandbox\25.0.23364.24925\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\sandbox\25.0.23364.24925\platform
c:\dl\sandbox\25.0.23364.24925\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\sandbox\25.0.23364.24925\platform\ConfigurationPackages
Copying Test Assemblies
C:\dl\sandbox\25.0.23364.24925\platform\Test Assemblies
Copying Extensions
C:\dl\sandbox\25.0.23364.24925\w1\Extensions
Copying Applications
C:\dl\sandbox\25.0.23364.24925\platform\Applications
Copying dependencies
Importing PowerShell Modules
Skipping restore of Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Installation took 23 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 172.28.32.1 in container hosts file
Starting Container
Hostname is TestAppBC25
PublicDnsName is #REDACTED#
Using NavUserPassword Authentication
Import Encryption Key
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)
```

**Additional context**
This happens all the time when creating BC25 container with external SQL database

**Comment by freddydk** [comment]
I think the problem here is PS5/PS7
I assume that your script also doesn't work with BC 24?

**Comment by petegonnella** [comment]
@freddydk BC24 is working fine, just tried with the https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.0.23364.25044/w1 artifacts.

**Comment by thomasguldstrand** [comment]
I have the same issue when trying to publish an app to a BC25 container.

**This is the script:**
`  
$containerName = 'BC25'
  $credential = Get-Credential -Message 'Please enter credentials for the container.'
  $auth = 'UserPassword'
  $artifactUrl = Get-BcArtifactUrl -version '25.0.99999.0' -country 'dk' -select 'Closest' -type OnPrem
  $LicenseFile = 'C:\Temp\Latest.bclicense' 
  
  New-BcContainer `
      -accept_eula `
      -accept_outdated `
      -containerName $containerName `
      -credential $credential `
      -auth $auth `
      -artifactUrl $artifactUrl `
      -licenseFile $licensFile `
      -dns '8.8.8.8' `
      -shortcuts DesktopFolder `
      -updateHosts `
      -assignPremiumPlan
`

**This is the output:**

`BcContainerHelper is version 6.0.24
BcContainerHelper is running as administrator
HyperV is Enabled
Host is Microsoft Windows 11 Enterprise - 10.0.22631.4169
UsePsSession is True
UsePwshForBc24 is True
UseWinRmSession is never
UseSslForWinRmSession is True
Docker Client Version is 25.0.2
Docker Server Version is 25.0.2
Removing Session BC25
Removing container BC25
Removing entries from hosts
Removing BC25 from container hosts file
Removing BC25-* from container hosts file
Removing Desktop shortcuts
Removing C:\ProgramData\BcContainerHelper\Extensions\BC25
Fetching all docker images
Fetching all docker volumes
Using image mcr.microsoft.com/businesscentral:ltsc2022
Creating Container BC25
Style: onprem
Multitenant: No
Version: 25.0.23364.24652
Platform: 25.0.24618.0
Generic Tag: 1.0.2.41
Container OS Version: 10.0.20348.2582 (ltsc2022)
Host OS Version: 10.0.22631.4169 (23H2)
WARNING: Container and host OS build is 20348 or above, defaulting to process isolation. If you encounter issues, you could try to install HyperV.
Using process isolation
Using locale da-DK
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\BcContainerHelper\Extensions\BC25\my:
- AdditionalOutput.ps1
- HelperFunctions.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC25 from image mcr.microsoft.com/businesscentral:ltsc2022
7cd5e46e6973b066859bda9bb46d8e98a9b73e883c3085d9090061a9ce278c30
Waiting for container BC25 to be ready
Using artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/25.0.23364.24652/dk
Using installer from C:\Run\240
Installing Business Central: multitenant=False, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\onprem\25.0.23364.24652\dk, platformArtifactPath=c:\dl\onprem\25.0.23364.24652\platform, databasePath=c:\dl\onprem\25.
0.23364.24652\dk\database\Demo Database BC (25-0).bak, licenseFilePath=c:\dl\onprem\25.0.23364.24652\dk\database\Cronus.bclicense, rebootContainer=True
Installing from artifacts
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
c:\dl\onprem\25.0.23364.24652\platform\ServiceTier\Program Files
c:\dl\onprem\25.0.23364.24652\platform\ServiceTier\System64Folder
Copying Web Client Files
c:\dl\onprem\25.0.23364.24652\platform\WebClient\Microsoft Dynamics NAV
Copying ModernDev Files
c:\dl\onprem\25.0.23364.24652\platform
c:\dl\onprem\25.0.23364.24652\platform\ModernDev\program files\Microsoft Dynamics NAV
Copying additional files
Copying ConfigurationPackages
C:\dl\onprem\25.0.23364.24652\dk\ConfigurationPackages
Copying Test Assemblies
C:\dl\onprem\25.0.23364.24652\platform\Test Assemblies
Copying Applications
C:\dl\onprem\25.0.23364.24652\dk\Applications
Copying dependencies
Importing PowerShell Modules
Restoring CRONUS Demo Database
Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Importing license file
Stopping Business Central Service Tier
Installation took 832 seconds
Installation complete
Initializing...
Setting host.containerhelper.internal to 192.168.0.1 in container hosts file
Starting Container
Hostname is BC25
PublicDnsName is BC25
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 11DC3432609C7C8078F5B25F40828E120DAEA089
DNS identity BC25
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using application pool name: BC
Using default container name: NavWebApplicationContainer
Copy files to WWW root C:\inetpub\wwwroot\BC
Create the application pool BC
Create website: NavWebApplicationContainer without SSL
Update configuration: navsettings.json
Done Configuring Web Client
Creating http download site
Setting SA Password and enabling SA
Creating dev as SQL User and add to sysadmin
Creating SUPER user
Assign Premium plan for DEV
Container IP Address: 192.168.6.95
Container Hostname  : BC25
Container Dns Name  : BC25
Web Client          : http://BC25/BC/
Dev. Server         : http://BC25
Dev. ServerInstance : BC
Setting BC25 to 192.168.6.95 in host hosts file

Files:
http://BC25:8080/ALLanguage.vsix

Container Total Physical Memory is 39.8Gb
Container Free Physical Memory is 10.1Gb

Initialization took 335 seconds
Ready for connections!
Reading CustomSettings.config from BC25
Creating Desktop Shortcuts for BC25
Cleanup old dotnet core assemblies
Container BC25 successfully created`

**This is the script to publish/install the app** 

`
Publish-BcContainerApp -appFile "C:\Users\tgu\Downloads\MyApp.app" -skipVerification -containerName $containerName -sync -install
`

**Outcome:**

`
Downloading AL Language Extension to C:\ProgramData\BcContainerHelper\alLanguageExtension\14.0.1161190.zip
using 7zip
Publishing C:\ProgramData\BcContainerHelper\Extensions\BC25\a1a9677a-0c36-4789-b4b2-c8a0c13c1d52\MyApp.app
Value cannot be null. (Parameter 'input')

Container Free Physical Memory: 9.5Gb
Disk C: Free 123Gb from 127Gb

Services in container BC25:
Publish-BcContainerApp Telemetry Correlation Id: 32162145-875f-4fe0-adae-29059b423c6d
Value cannot be null. (Parameter 'input')
At C:\Program Files\WindowsPowerShell\Modules\BCContainerHelper\6.0.24\ContainerHandling\Invoke-ScriptInNavContainer.ps1:301 char:25
                         throw $errorMessage
                         ~~~~~~~~~~~~~~~~~~~
    CategoryInfo          : OperationStopped: (Value cannot be...ameter 'input'):String) [], RuntimeException
    FullyQualifiedErrorId : Value cannot be null. (Parameter 'input')

`

**Comment by petegonnella** [comment]
> @freddydk BC24 is working fine, just tried with the https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.0.23364.25044/w1 artifacts.

I also tried executing using Powershell 7.4.5 on host machine, still doesn't work for BC25

**Comment by petegonnella** [comment]
> I have the same issue when trying to publish an app to a BC25 container using BCCH 6.0.24
> 
> **This is the script:**
> 
> ```
> $containerName = 'BC25'
>   $credential = Get-Credential -Message 'Please enter credentials for the container.'
>   $auth = 'UserPassword'
>   $artifactUrl = Get-BcArtifactUrl -version '25.0.99999.0' -country 'dk' -select 'Closest' -type OnPrem
>   $LicenseFile = 'C:\Temp\Latest.bclicense' 
>   
>   New-BcContainer `
>       -accept_eula `
>       -accept_outdated `
>       -containerName $containerName `
>       -credential $credential `
>       -auth $auth `
>       -artifactUrl $artifactUrl `
>       -licenseFile $licensFile `
>       -dns '8.8.8.8' `
>       -shortcuts DesktopFolder `
>       -updateHosts `
>       -assignPremiumPlan
> ```
> 
> **This is the output:**
> 
> ```
> BcContainerHelper is version 6.0.24
> BcContainerHelper is running as administrator
> HyperV is Enabled
> Host is Microsoft Windows 11 Enterprise - 10.0.22631.4169
> UsePsSession is True
> UsePwshForBc24 is True
> UseWinRmSession is never
> UseSslForWinRmSession is True
> Docker Client Version is 25.0.2
> Docker Server Version is 25.0.2
> Removing Session BC25
> Removing container BC25
> Removing entries from hosts
> Removing BC25 from container hosts file
> Removing BC25-* from container hosts file
> Removing Desktop shortcuts
> Removing C:\ProgramData\BcContainerHelper\Extensions\BC25
> Fetching all docker images
> Fetching all docker volumes
> Using image mcr.microsoft.com/businesscentral:ltsc2022
> Creating Container BC25
> Style: onprem
> Multitenant: No
> Version: 25.0.23364.24652
> Platform: 25.0.24618.0
> Generic Tag: 1.0.2.41
> Container OS Version: 10.0.20348.2582 (ltsc2022)
> Host OS Version: 10.0.22631.4169 (23H2)
> WARNING: Container and host OS build is 20348 or above, defaulting to process isolation. If you encounter issues, you could try to install HyperV.
> Using process isolation
> Using locale da-DK
> Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
> Files in C:\ProgramData\BcContainerHelper\Extensions\BC25\my:
> - AdditionalOutput.ps1
> - HelperFunctions.ps1
> - MainLoop.ps1
> - SetupNavUsers.ps1
> - SetupVariables.ps1
> - updatehosts.ps1
> Creating container BC25 from image mcr.microsoft.com/businesscentral:ltsc2022
> 7cd5e46e6973b066859bda9bb46d8e98a9b73e883c3085d9090061a9ce278c30
> Waiting for container BC25 to be ready
> Using artifactUrl https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/onprem/25.0.23364.24652/dk
> Using installer from C:\Run\240
> Installing Business Central: multitenant=False, installOnly=False, filesOnly=False, includeTestToolkit=False, includeTestLibrariesOnly=False, includeTestFrameworkOnly=False, includePerformanceToolkit=False, appArtifactPath=c:\dl\onprem\25.0.23364.24652\dk, platformArtifactPath=c:\dl\onprem\25.0.23364.24652\platform, databasePath=c:\dl\onprem\25.
> 0.23364.24652\dk\database\Demo Database BC (25-0).bak, licenseFilePath=c:\dl\onprem\25.0.23364.24652\dk\database\Cronus.bclicense, rebootContainer=True
> Installing from artifacts
> Starting Local SQL Server
> Starting Internet Information Server
> Copying Service Tier Files
> c:\dl\onprem\25.0.23364.24652\platform\ServiceTier\Program Files
> c:\dl\onprem\25.0.23364.24652\platform\ServiceTier\System64Folder
> Copying Web Client Files
> c:\dl\onprem\25.0.23364.24652\platform\WebClient\Microsoft Dynamics NAV
> Copying ModernDev Files
> c:\dl\onprem\25.0.23364.24652\platform
> c:\dl\onprem\25.0.23364.24652\platform\ModernDev\program files\Microsoft Dynamics NAV
> Copying additional files
> Copying ConfigurationPackages
> C:\dl\onprem\25.0.23364.24652\dk\ConfigurationPackages
> Copying Test Assemblies
> C:\dl\onprem\25.0.23364.24652\platform\Test Assemblies
> Copying Applications
> C:\dl\onprem\25.0.23364.24652\dk\Applications
> Copying dependencies
> Importing PowerShell Modules
> Restoring CRONUS Demo Database
> Setting CompatibilityLevel for CRONUS on localhost\SQLEXPRESS
> Modifying Business Central Service Tier Config File for Docker
> Creating Business Central Service Tier
> Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
> Starting Business Central Service Tier
> Importing license file
> Stopping Business Central Service Tier
> Installation took 832 seconds
> Installation complete
> Initializing...
> Setting host.containerhelper.internal to 192.168.0.1 in container hosts file
> Starting Container
> Hostname is BC25
> PublicDnsName is BC25
> Using NavUserPassword Authentication
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint 11DC3432609C7C8078F5B25F40828E120DAEA089
> DNS identity BC25
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Registering event sources
> Creating DotNetCore Web Server Instance
> Using application pool name: BC
> Using default container name: NavWebApplicationContainer
> Copy files to WWW root C:\inetpub\wwwroot\BC
> Create the application pool BC
> Create website: NavWebApplicationContainer without SSL
> Update configuration: navsettings.json
> Done Configuring Web Client
> Creating http download site
> Setting SA Password and enabling SA
> Creating dev as SQL User and add to sysadmin
> Creating SUPER user
> Assign Premium plan for DEV
> Container IP Address: 192.168.6.95
> Container Hostname  : BC25
> Container Dns Name  : BC25
> Web Client          : http://BC25/BC/
> Dev. Server         : http://BC25
> Dev. ServerInstance : BC
> Setting BC25 to 192.168.6.95 in host hosts file
> 
> Files:
> http://BC25:8080/ALLanguage.vsix
> 
> Container Total Physical Memory is 39.8Gb
> Container Free Physical Memory is 10.1Gb
> 
> Initialization took 335 seconds
> Ready for connections!
> Reading CustomSettings.config from BC25
> Creating Desktop Shortcuts for BC25
> Cleanup old dotnet core assemblies
> Container BC25 successfully created
> ```
> 
> **This is the script to publish/install the app**
> 
> `Publish-BcContainerApp -appFile "C:\Users\tgu\Downloads\MyApp.app" -skipVerification -containerName $containerName -sync -install`
> 
> **Outcome:**
> 
> ```
> Downloading AL Language Extension to C:\ProgramData\BcContainerHelper\alLanguageExtension\14.0.1161190.zip
> using 7zip
> Publishing C:\ProgramData\BcContainerHelper\Extensions\BC25\a1a9677a-0c36-4789-b4b2-c8a0c13c1d52\MyApp.app
> Value cannot be null. (Parameter 'input')
> 
> Container Free Physical Memory: 9.5Gb
> Disk C: Free 123Gb from 127Gb
> 
> Services in container BC25:
> Publish-BcContainerApp Telemetry Correlation Id: 32162145-875f-4fe0-adae-29059b423c6d
> Value cannot be null. (Parameter 'input')
> At C:\Program Files\WindowsPowerShell\Modules\BCContainerHelper\6.0.24\ContainerHandling\Invoke-ScriptInNavContainer.ps1:301 char:25
>                          throw $errorMessage
>                          ~~~~~~~~~~~~~~~~~~~
>     CategoryInfo          : OperationStopped: (Value cannot be...ameter 'input'):String) [], RuntimeException
>     FullyQualifiedErrorId : Value cannot be null. (Parameter 'input')
> ```

@thomasguldstrand  This looks like an issue that is different from what I have reported.

**Comment by thomasguldstrand** [comment]
@petegonnella I agree. I accidently posted my reply in the wrong issue. I have deleted my reply to this thread

**Comment by freddydk** [comment]
I tried this script on my machine:

```
$containerName = "bcserver"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$artifactUrl = Get-BCArtifactUrl -country us -select latest
$artifactLocation = Download-Artifacts -artifactUrl $artifactUrl -includePlatform
$licenseFile = (Get-ChildItem -Path $artifactLocation[0] -Recurse -Filter '*.bclicense')[0].FullName
$databaseSecurePassword = ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force

$databaseParams = @{
    "databaseServer" = 'host.containerhelper.internal'
    "databaseInstance" = ''
    "databasePrefix" = $containerName
    "databaseName" = '.containers.local'
    "databaseCredential" = New-Object pscredential 'sa', $databaseSecurePassword
    "multitenant" = $true
}

New-BcContainer @databaseParams -replaceExternalDatabases `
    -accept_eula `
    -artifactUrl $artifactUrl `
    -containerName $containerName `
    -auth UserPassword `
    -Credential $credential `
    -licenseFile $licenseFile `
    -enableTaskScheduler -alwaysPull
```

Which works fine - so there is nothing wrong with BC25, docker and SQL on the host.

You are however restoring the databases in a different way, which might cause this.
The problem might be that the SetupDatabase and SetupTenant scripts are running in PS5 inside the container - maybe you should do the database restore before creating the container and then just create a container pointing to the database.

**Comment by freddydk** [comment]
I can see you are using an old generic image for BC - please try to all -alwayspull

The next BcContainerHelper preview will include a mechanism to add -alwaysPull if the generic image isn't at least as new as BcContainerHelper.

**Comment by petegonnella** [comment]
> I can see you are using an old generic image for BC - please try to all -alwayspull
> 
> The next BcContainerHelper preview will include a mechanism to add -alwaysPull if the generic image isn't at least as new as BcContainerHelper.

thanks @freddydk  this was the solution 👍
