### ISSUE TITLE
Error when using -myScripts parameter

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#37]
I'm using the example below to create a navision container, but no matter what value  I use as parameter for -myScripts I receive the following error:

New-NavContainer : A positional parameter cannot be found that accepts argument 'True'.

When I ommit parameter -myScripts I can debug into command New-NavContainer, but it than fails because the command is expecting a value for parameter -myScripts.
Your sample's at https://github.com/Microsoft/navcontainerhelper/blob/master/ContainerHandling/New-NavContainer.ps1
show more or less the same sample as I'm using.
New-NavContainer -containerName test -imageName "navdocker.azurecr.io/dynamics-nav:2017" -myScripts @("c:\temp\AdditionalSetup.ps1") -AdditionalParameters @("-v c:\hostfolder:c:\containerfolder")

Same goes for parameter -AdditionalParameters.

example:

New-NavContainer -containerName $ContainerName `
                 -imageName $ImageName `
                 -licenseFile $Licensefile `
                 -Credential Admin `
                 -memoryLimit $MemoryLimit `
                 -auth $Auth `
                 -databaseServer $DatabaseServer `
                 -databaseInstance $DatabaseInstance `
                 -databaseName $DatabaseName `
                 -databaseCredential $DatabaseCredential `
                 -shortcuts $Shortcuts `
                 -includeCSide $true `
                 -updateHosts $true `
                 -accept_eula $true `
                 -doNotExportObjectsToText $true `
                 -myScripts @("AdditionalSetup.ps1")

**Comment by freddydk** [comment]
The problem is in the error.
-doNotExportObjectsToText is a switch and you should not add $true behind that.

**Comment by mheijkant** [comment]
Thanks, you're absolutely right.
