### ISSUE TITLE
issue creating new container

### ISSUE THREAD

**Issue by Bssivivek** [Microsoft/navcontainerhelper#370]
When i try to create new conainer using below command

New-NavContainer -containerName MEM-D365BC-US -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2016 -includeCSide -licenseFile "C:\Work\MEM-D365BC.flf"

I get below error message

![image](https://user-images.githubusercontent.com/38437776/53827912-0ddc4e80-3f31-11e9-8a44-26442c69ab6e.png)

Based on the error message when i try to run below command, i get following error

Import-Module navcontainerhelper
![image](https://user-images.githubusercontent.com/38437776/53827961-2c424a00-3f31-11e9-9608-312bb154b6d5.png)

Please help!!

**Comment by left-code** [comment]
@Bssivivek try to set execution policy to remote signed, using command:
Set-ExecutionPolicy RemoteSigned

**Comment by Bssivivek** [comment]
Thanks!!
When I execute the command, and get the list, I see the following
<img width="682" alt="image" src="https://user-images.githubusercontent.com/38437776/53838229-599af200-3f49-11e9-9844-15f613b3164a.png">

Now when I run below command, I am still getting following error
Import-Module navcontainerhelper -force
<img width="681" alt="image" src="https://user-images.githubusercontent.com/38437776/53838284-7fc09200-3f49-11e9-85c2-beb0ce1c70cf.png">

DO I need to restart the machine?

**Comment by left-code** [comment]
@Bssivivek please set execution policy for scope CurrentUser also:
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned

No need to restart machine.
And you don't need to import module, it should be already installed, you can just start using commands.

**Comment by Bssivivek** [comment]
Hi,
I was able to resolve that issue but I am not able to proceed further.
When I try to create a container using below command

New-NavContainer -containerName MEM -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2016 -licenseFile "C:\Work\MEM-D365BC.flf"

I am getting following error.
![image](https://user-images.githubusercontent.com/38437776/54061263-ea293a80-41b4-11e9-83e5-fefeabe373c9.png)

**Comment by freddydk** [comment]
You are running Windows 10 1803, you really only have 2 options:
1. upgrade to 1809
If you upgrade to 1809 - a lot of issues will get solved (amongst this problem) + you will be able to use ltsc2019 images (half the size of ltsc2016) + you will be able to run process isolation.
Read more here: https://freddysblog.com/2019/01/13/process-isolation-for-containers-in-windows-10/
and here: https://freddysblog.com/2018/12/01/nav-and-business-central-docker-images-now-available-for-windows-server-2019/
2. use -usebestcontaineros
https://freddysblog.com/2018/10/24/windows-10-and-docker-images-for-business-central-nav/

**Comment by Bssivivek** [comment]
hi thanks a lot.
I upgraded my OS to windows 10 1809.
I used below commands to download the latest image and create the container

docker pull mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019

install-module navcontainerhelper –force
New-NavContainer -containerName MEM -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -licenseFile "C:\Work\MEM-D365BC.flf" -updateHosts

iam getting below error when I try to create the container
<img width="734" alt="image" src="https://user-images.githubusercontent.com/38437776/54803285-1a98bc00-4c2c-11e9-814a-d1af1c12654d.png">

PS C:\WINDOWS\system32> New-NavContainer -containerName MEM -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -licenseFile "C:\Work\MEM-D365BC.flf" -updateHosts
NavContainerHelper is version 0.5.0.9
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Removing C:\ProgramData\NavContainerHelper\Extensions\MEM
Creating Nav container MEM
Using license file C:\Work\MEM-D365BC.flf
Version: 13.4.28874.29469-US
Platform: 13.0.28871.29362
Generic Tag: 0.0.9.2
Container OS Version: 10.0.17763.316 (ltsc2019)
Host OS Version: 10.0.17763.379 (ltsc2019)
Using process isolation
Creating container MEM from image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
733e9521d362f87af124911274224ef01c6dfdb3951fc4bde88d16f2b9425251
Waiting for container MEM to be ready
Initializing...
Starting Container
Hostname is MEM
PublicDnsName is MEM
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint CA8E91566A0B0AA92B1D9F32FDDBB8555D547E87
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user vivek.sarma
Setting SA Password and enabling SA
Creating vivek.sarma as SQL User and add to sysadmin
Incorrect syntax near '.'.
at <ScriptBlock>, C:\Run\SetupSqlUsers.ps1: line 30
at <ScriptBlock>, C:\Run\navstart.ps1: line 173
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is MEM
PublicDnsName is MEM
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint CA8E91566A0B0AA92B1D9F32FDDBB8555D547E87
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user vivek.sarma
Setting SA Password and enabling SA
Creating vivek.sarma as SQL User and add to sysadmin
Incorrect syntax near '.'.
at <ScriptBlock>, C:\Run\SetupSqlUsers.ps1: line 30
at <ScriptBlock>, C:\Run\navstart.ps1: line 173
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container MEM failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.9\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container MEM failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container MEM failed

**Comment by kine** [comment]
In most cases I have this errors when the user name is not filled in (e.g. I forgot to assign variables in the build pipeline).

**Comment by freddydk** [comment]
This is not a pipeline:-) - but I do agree it looks to be related to username.
It looks like you are using a username with a . inside - try to use another username.

**Comment by freddydk** [comment]
Indeed, usernames with a . is not supported in current containers.
is fixed in a later version.
If you want to use this now - you will need to add -myScripts @("https://raw.githubusercontent.com/Microsoft/nav-docker/master/generic/Run/SetupSqlUsers.ps1") to your new-navcontainer (that will override the SetupSqlUsers.ps1 with a new version, that fixes the issue)

**Comment by Bssivivek** [comment]
i was indeed using dot in my user ID. when I remove dot, I am getting below error
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/38437776/54888665-3e424900-4e5c-11e9-8123-fe41d3a848e8.png">

**Comment by Bssivivek** [comment]
I used below commands and its working fine now
docker pull mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019

install-module navcontainerhelper –force
New-NavContainer -containerName D365BC-US -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -licenseFile "C:\Work\MEM-D365BC.flf" -updateHosts
just curious to know the reason for above issue.
@freddydk thanks a lot for al your help. it should be great if you can help me with any document on how to debug the issues related to dockers/containers.

**Comment by freddydk** [comment]
The error with the retries is because it is trying to remove a folder and you probably have cside open.
The reason for the . problem is a bug in my scripts.
These lines:

Creating vivek.sarma as SQL User and add to sysadmin
Incorrect syntax near '.'.
at , C:\Run\SetupSqlUsers.ps1: line 30

I looked in the source here; https://raw.githubusercontent.com/Microsoft/nav-docker/master/generic/Run/SetupSqlUsers.ps1 and could see that in one case, the username was not embraced in [].

So, I tried to create a container with your username. Got the same error - fixed the bug and retried.

Now the bug isn't fixed until we have a new image and all images out there will have this bug until they are re-build.

The mitigation is not to use . or override SetupSqlUsers as described.

**Comment by NAVspecialist** [comment]
On your NewNAVcontainer you could just do a -useBestContainerOS then you do not need to do a 

docker pull mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 but just

New-NavContainer -containerName D365BC-US -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us -licenseFile "C:\Work\MEM-D365BC.flf" -updateHosts -UsebestContainerOS

I am currently myself doing it like this

$Licensefile = "C:\Docker\6197658.flf"
$ImageName = "microsoft/dynamics-nav:2018-dk"
$ContainerName = "NAV2018"
$PlainTextPw = "Passw0rd"
$Credential = New-Object -TypeName PSCredential -ArgumentList $env:USERNAME,(ConvertTo-SecureString -String $PlainTextPw -AsPlainText -Force)
New-NavContainer -containerName $ContainerName -memoryLimit "4g" -alwaysPull -accept_eula -accept_outdated -auth NavUserPassword -Credential $Credential -imageName $ImageName -licenseFile $Licensefile -includeCSide -shortcuts Desktop -useBestContainerOS -updateHosts -verbose

**Comment by Bssivivek** [comment]
thanks a lot!!
its fine and you can close this ticket.
