### ISSUE TITLE
Invoke-ScriptInBcContainer has Problem with Deserialize Output 

### ISSUE THREAD

**Issue by HeWessel** [microsoft/navcontainerhelper#3704]
**Describe the issue**
Currently we using the BC Containers with a central SQL Server and i currently facing a Problem with updating the Database.
To Update our Databases we normally create a own Container with the Target BC Version and then invoke the Database Update Script from this one.
Firstly i thought i have to change my Script. For further Investigation i checked the output of the BcContainerScripts and figured out that the Script was executed sucessfully but the output werent able to be parsed?

You should be able to reproduce the Error easy with the script.

**Scripts used to create container and cause the issue**
```
$Url = Get-BCArtifactUrlFromBCArtifact -BCArtifact $BCArtifact
New-BcContainer -accept_eula -containerName $databaseName -artifactUrl $url -Credential $Credentials 
try {
	Invoke-ScriptInBcContainer -containerName $databaseName -scriptblock {
		Param([string] $databaseserver,
			  [string] $databasename,
			  [PSCredential] $databaseCredentials) 
		if ($databaseCredentials -and ($databaseCredentials.UserName -ne ''))
		{
			$params += @{"ApplicationDatabaseCredentials" = $databaseCredentials}
		}
		Invoke-NAVApplicationDatabaseConversion -DatabaseServer $databaseserver -DatabaseName $databaseName @params -force   
	} -argumentList $databaseserver, $databasename, $databaseCredentials
}
finally {
	Remove-BcContainer $databaseName
}
```

**Full output of scripts**
```
BcContainerHelper version 6.0.25
Setting usePsSession = False
Setting hostHelperFolder = d:\ContainerHelper
Setting bcartifactsCacheFolder = d:\bcartifacts.cache
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.17763.6292
# here the successful output from the Create-Container
Invoke-ScriptInBcContainer : Ausnahme beim Aufrufen von "Deserialize" mit 1 Argument(en):  "Schlüssel ist im angegebenen Status nicht gültig.
"
In C:\Users\builduser\Desktop\Scripte\hw\DBConvert_BC25.ps1:16 Zeichen:1
+ Invoke-ScriptInBcContainer -containerName "hwbc25" -ErrorAction Silen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-ScriptInBcContainer], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicException,Invoke-ScriptInBcContainer
...
```
If you need further information let me know.
Greetings Hermann

**Comment by freddydk** [comment]
If I am to run the script above... - what are you using as databaseServer?
and what are you using as artifacts? (onprem or sandbox and which version?)
are you running the database in a container or on the host?
What generic image are you using?
I need the full output of the container generation to answer these and other questions.

But... - as far as I know, the Invoke-NavApplicationDatabaseConversion doesn't return anything - so I doubt that the problem is normal deserialization. I do however remember that you cannot return securestrings from Invoke-ScriptInBcContainer.

**Comment by freddydk** [comment]
It looks like the function does return some object and you obviously cannot deserialize that on the host if you don't have the DLLs with these objects installed.
You can probably just add `| Out-Null` after your Invoke-Nav.... call.
Then the invoke-script won't have anything to serialize.

**Comment by HeWessel** [comment]
so the Output of the Invoke-Nav call has changed from BC 24 to BC 25?
so i handle the whole Error inside the Script and just let the Output null for the whole Invoke-ScriptinBcContainer.
Thanks for your fast Support and have a good Start intho this Week

**Comment by freddydk** [comment]
> so the Output of the Invoke-Nav call has changed from BC 24 to BC 25?

Have no idea - but very likely a new version of the class

**Comment by freddydk** [comment]
> so i handle the whole Error inside the Script and just let the Output null for the whole Invoke-ScriptinBcContainer.

Error?
If the function is failing, it should raise an execption which should be forwarded to the host...

But else - return a string or a Json string from the invoke to the host - that always works.

**Comment by HeWessel** [comment]
> > so i handle the whole Error inside the Script and just let the Output null for the whole Invoke-ScriptinBcContainer.
> 
> Error? If the function is failing, it should raise an execption which should be forwarded to the host...
> 
> But else - return a string or a Json string from the invoke to the host - that always works.

Error is the false Word.
I just mean the complete Output.
But thats a good idea to format all in just a String and return to the host.
Thanks
