### ISSUE TITLE
Issue with mutex and windows 22

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/navcontainerhelper#3706]
Recently we created a new build machine (Self hosted Azure Devops, Windows 22). On this machine we host 3 agents. Every agent runs with its own user account. (Local admins .\agent1, .\agent2, .\agent3). Reason we use different accounts is because the PS modules used by the agent are installed on user level. This allows us to use different versions of the same PS module between the agents.

In the past we used W2019 servers, for which this worked just fine.
With Windows 22 we see following errors when containers are being created:
![image](https://github.com/user-attachments/assets/7fe74709-9063-44c9-883c-659f5930ffbb)

As far as I know the error is coming from this part:
![image](https://github.com/user-attachments/assets/c8f721ba-1b0b-44ce-bba8-0ea2084dd416)

PS Script: Artifacts\Download-Artifacts.ps1

**Comment by freddydk** [comment]
https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660 - says something about MSVCP140.dll being required by mutex - maybe this is missing on your machines.

**Comment by RonKoppelaar** [comment]
I narrowed done the issue with following test case:
- Setup W22 machine with 2 agents
- Each agent running as service with different local admin accounts
- Yml file for this build has 1 step (See below)
- When triggering two builds in parallel the 2nd build will run with following error:
New-Object : Exception calling ".ctor" with "2" argument(s): "Access to the path 'TestMutex' is denied."


```
  - task: PowerShell@2
    displayName: 'Create Container'
    inputs:
      TargetType: 'Inline'
      Script: |
        $appMutexName = "TestMutex"
        $appMutex = New-Object System.Threading.Mutex($false, $appMutexName)
        try {
            if (!$appMutex.WaitOne(1000)) {
                Write-Host "Waiting for other process downloading artifact '$($artifactUrl.Split('?')[0])'"
                $appMutex.WaitOne() | Out-Null
                Write-Host "Other process completed download"
            }
            Write-Host "start sleep"
            Start-Sleep -Seconds 30
            Write-Host "Completed"
        }
        catch [System.Threading.AbandonedMutexException] {
            Write-Host "Other process terminated abnormally"
        }
        $appMutex.ReleaseMutex()
    env:
      TOKEN: $(System.AccessToken)
```

**Comment by freddydk** [comment]
Strange.
Mutex isn't really a BcContainerHelper construct - it is a dotnet construct.
If it doesn't work - I don't expect BcContainerHelper to be able to solve that.
If you RDP into the W2022 machine and start two PowerShell instances - and run:

```
$appMutex = New-Object System.Threading.Mutex($false, 'TestMutex')
```

On both - and then run

```
$appMutex.WaitOne()
```

on both - one after the other - the second one should wait until you run

```
$appMutex.ReleaseMutex()
```

**Comment by RonKoppelaar** [comment]
Also read about this issue here: https://github.com/microsoft/navcontainerhelper/issues/3164
It seems to be an issue with network/ad accounts and services

If I ran the agent as local system account it does work. But running it as a local "admin user" it doesnt...

**Comment by RonKoppelaar** [comment]
Your test scenario with just two PS sessions works fine. The problem occurs when using windows services

**Comment by freddydk** [comment]
So I guess I had heard about this before... - totally forgot all about that other issue :-(
Anyway - you have your workaround - run as a local system account instead (which also is more secure).

**Comment by RonKoppelaar** [comment]
The local system account solves the problem with the mutex. But it introduce a new problem. If all agents run under the same account its hard to differentiate between PS module versions. Normally we install them with user scope. So modules are installed in %HOME%\Documents\Powershell Modules
If all agents run with same account this will not work...

**Comment by freddydk** [comment]
Understood, but this is a very specific problem and not something I will have the time to investigate.
You could run different runners for different versions maybe?
Or if you indeed find a way to fix this, feel free to create a PR on BcContainerHelper (if it is risk free).
