### ISSUE TITLE
Facing issue when trying to restart or adding user in local container 

### ISSUE THREAD

**Issue by VishnuVelmurugan** [microsoft/navcontainerhelper#3708]
Add new User to BC Container: UserName2
Creating User vv
ServerInstance 'MicrosoftDynamicsNavServer$BC' is not running.

Exception Script Stack Trace:
at <ScriptBlock>, <No file>: line 59

PowerShell Call Stack:
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.25\ContainerHandling\Invoke-ScriptInNavContainer.ps1: line 71
at New-BcContainerBcUser, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.25\UserHandling\New-NavContainerNavUser.ps1: line 60
at <ScriptBlock>, <No file>: line 9

Container Free Physical Memory: 2.5Gb
Disk C: Free 122Gb from 127Gb

Services in container bc18ap:
- MicrosoftDynamicsNavServer$BC is Stopped
- MSSQL$SQLEXPRESS is Running

New-BCContainerBCUser Telemetry Correlation Id: 7f3a1c56-d8db-4e08-9424-694aa1cf20bb
ServerInstance 'MicrosoftDynamicsNavServer$BC' is not running.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.25\ContainerHandling\Invoke-ScriptInNavContainer.ps1:113 char:13
+             throw $errorMessage
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ServerInstance ...is not running.:String) [], RuntimeException
    + FullyQualifiedErrorId : ServerInstance 'MicrosoftDynamicsNavServer$BC' is not running.
 
 Checked with license file it is updated one.
 @freddydk  Kindly assist with this.

**Comment by freddydk** [comment]
You need to share the script you are using and the full output of this script - else I cannot tell you why your service tier isn't running
You probably also need to download the event log from the container, using get-bccontainerEventlog

**Comment by VishnuVelmurugan** [comment]
PS C:\WINDOWS\system32> Restart-BcContainer -containerName bc22v
Removing Session bc22v
bc22v
Waiting for container bc22v to be ready

Initializing...
Setting host.docker.internal to 192.168.0.18 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.18 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.31.240.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is bc22v
PublicDnsName is bc22v
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 175
at <ScriptBlock>, C:\Run\start.ps1: line 390
at <ScriptBlock>, <No file>: line 1Error

Initializing...
Setting host.docker.internal to 192.168.0.18 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.18 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.31.240.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is bc22v
PublicDnsName is bc22v
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 175
at <ScriptBlock>, C:\Run\start.ps1: line 390
at <ScriptBlock>, <No file>: line 1
Restart-BcContainer Telemetry Correlation Id: d64378b3-a359-4ac7-a665-1e6c5d896fd5
Initialization of container bc22v failed
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.25\ContainerHandling\Wait-NavContainerReady.ps1:42 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container bc22v failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc22v failed

**Comment by VishnuVelmurugan** [comment]
PS C:\WINDOWS\system32> WARNING: The names of some imported commands from the module 'BcContainerHelper' include unapproved verbs that might m
ake them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a 
list of approved verbs, type Get-Verb.
Get-BcContainerEventLog -containerName bc22v -logname LogFile
Getting event log for bc22v
Failed to export log LogFile.

Exception Script Stack Trace:
at <ScriptBlock>, <No file>: line 2

PowerShell Call Stack:
at Invoke-ScriptInBcContainer, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.25\ContainerHandling\Invoke-ScriptInNavContain
er.ps1: line 71
at Get-BcContainerEventLog, C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.25\ContainerInfo\Get-NavContainerEventLog.ps1: li
ne 35
at <ScriptBlock>, <No file>: line 1

Container Free Physical Memory: 3.8Gb
Disk C: Free 122Gb from 127Gb

Services in container bc22v:
- MicrosoftDynamicsNavServer$BC is Stopped
- MSSQL$SQLEXPRESS is Running

Failed to export log LogFile.
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.25\ContainerHandling\Invoke-ScriptInNavContainer.ps1:113 char:13
+             throw $errorMessage
+             ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to export log LogFile.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to export log LogFile.

**Comment by freddydk** [comment]
Sorry, in order to help, I will need the script which is used to create the container and the full log from the container creation.
If you cannot share these info, I cannot help and I assume nobody else will be able to assist you here with this limited info.

**Comment by VishnuVelmurugan** [comment]
$containerName = 'bc2201'
$password = '01'
$securePassword = ConvertTo-SecureString -String $password -AsPlainText -Force
$credential = New-Object pscredential 'vv', $securePassword
$auth = 'UserPassword'
$artifactUrl = Get-BcArtifactUrl -type 'Sandbox' -version '22.1.55890.56394' -country 'us' -select 'Latest'
$licenseFile = 'C:\Users\vv\Downloads\BC License File.bclicense'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -multitenant:$false `
    -assignPremiumPlan `
    -licenseFile $licenseFile `
    -memoryLimit 16G `
    -updateHosts

**Comment by freddydk** [comment]
I have formatted your post as code.

That scripts creates a container - and if the license file is valid, it probably works just fine on my computer.
I will need the full log from running that script on your computer in order to assist you in any way.

and... - I will need whatever script you use to provoke any error you get subsequently (assuming that the above script is not what causes the error).

By not providing all this information, you are wasting a lot of my (and your) time having to write back and forth again and agian.

Please always provide as much information as possible if seeking for help.
