### ISSUE TITLE
Issue in devops pipeline step Compile Test App

### ISSUE THREAD

**Issue by peterz84** [Microsoft/navcontainerhelper#371]
First I created a devops Project and imported the repo: https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld 

Now I have a Main App and a Test App.

I created a BuildAgent following the guide on https://blogs.msdn.microsoft.com/freddyk/2018/11/12/developing-business-central-extensions-part-3/

This means the YAML pipeline will trigger my server (Windows 2019) to download my sources, spin up a container, compile the app, publish the app, import the testtoolkit and compile the **test**app. This last step fails with the following error:

![error](https://user-images.githubusercontent.com/25202313/53883987-d649d100-401a-11e9-8da9-d3676c46bd2c.png)

As you suggested in a comment on your blog, the new Container is started with the parameter -enableSymbolLoading. You also commented that I should:  unpublish the application symbols in the database. Not sure what you mean by this.

I'm using image mcr.microsoft.com/businesscentral/onprem:cu2-nl-ltsc2019

**Comment by kine** [comment]
If you are not using C/Side development, you can run the container without enableSymbolLoading but import the test toolkit and it should work. You only need to add line to your app.json "test":"13.0.0.0" which will tell AL to download test symbols...

**Comment by peterz84** [comment]
Tried that, but wasn't succesfull. It complained there was no application Test from Publisher Microsoft. 

Anyway, this issue seems to be fixed by the newest version of NAVContainerHelper. Except the fact that I get some other errors now: 

##[error]D:\Agent\_work\2\s\scripts\Create-Container.ps1 : The term '-useBestContainerOS' is not recognized as the name of a cmd…………...
after removing useBestContainerOS', now getting the next error:
[error]D:\Agent\_work\2\s\scripts\Create-Container.ps1 : The term '-shortcuts' is not recognized as the name of a cmdlet, func……………...

**Comment by peterz84** [comment]
Just tried with NAVContainerHelper 0.5.0.5, but still the same error.

**Comment by kine** [comment]
How are you importing the test toolkit?

**Comment by freddydk** [comment]
As Kamil says, the error above should disappear if you have a test rerefence in your app.json in your test app (if you did NOT start with -enablesymbolloading)
I am currently writing up a blog post on symbols and everything you need to know about them.

**Comment by freddydk** [comment]
Just tried a pipeline and get an error myself:

[error]Cannot index into a null array.
[error]At C:\Program 
[error]Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:9

Not the same as yours - but will investigate this.

**Comment by kine** [comment]
This is when you have disabled the WebClient in the container (I had this one before but I found that he webclient is disabled in my build pipeline to save some time...)

**Comment by freddydk** [comment]
Not the web client issue - but I can repro on my own machine now.
But this is a null array - not the same as peter gets.
(I got that as well - but then I added the test reference to the right app.json file)

**Comment by freddydk** [comment]
Note that by default - the scripts in my template repo does start up using -enablesymbolloading and as such will  NOT need the test reference.

**Comment by peterz84** [comment]
Indeed. But changed my app.json of the test app anyway to test the other approach too:
![image](https://user-images.githubusercontent.com/25202313/53890694-faacaa00-4028-11e9-8ffc-c0663c33aaa7.png)

Removed enableSymbomLoading in CreateContainer.ps1:
![image](https://user-images.githubusercontent.com/25202313/53890774-22037700-4029-11e9-9962-1edd83f706bb.png)

error:
![image](https://user-images.githubusercontent.com/25202313/53891178-16fd1680-402a-11e9-856c-f4a1b8ce393e.png)

**Comment by freddydk** [comment]
On the last screenshot - it does indeed download the test symbols - I will check if I can repro this

**Comment by freddydk** [comment]
Tried with microsoft/bcsandbox:us - worked fine - currently downloading the cu2-nl container

**Comment by peterz84** [comment]
[TestExtension2.zip](https://github.com/Microsoft/navcontainerhelper/files/2937011/TestExtension2.zip)

**Comment by freddydk** [comment]
It repros with the docker image you are using - stay tuned

**Comment by peterz84** [comment]
Is it bad to say I'm happy to hear that? :)

**Comment by freddydk** [comment]
Sorry to say that this was 60% my fault (and 40% Azure DevOps)
My mistaket was to checkin a line, which caused compile-appinnavcontainer to NEVER download test symbols.
Azure DevOps mistake is to reuse folders with 2 versions of the build - meaning that if you successfully had build before - then the test symbols where there.

I have fixed issue number one in 0.5.0.6 - already published.
I will have to find out what to do about issue no., 2 (which I only discovered because of issue no. 1) - I think that is a problem and I will have to find a way around that - folders should be clean with every build IMO.

Run your pipeline again - it should download symbols and compile.

**Comment by peterz84** [comment]
Yes it works now! So I should be able to remove the test: 13.0.0.0 and add EnableSymbolLoading again?

I'm not sure if I can follow you on the second one as devops (the yaml script) will spin up a new Container everytime you schedule a build?

**Comment by freddydk** [comment]
Correct - the build server doesn't totally clean up.

**Comment by freddydk** [comment]
Not sure if everything will work - the build server might have old symbols, which it doesn't overwrite. Will investigate this.

**Comment by freddydk** [comment]
Found out that this is a feature - you should set build.clean to all in your pipeline: 
![image](https://user-images.githubusercontent.com/10775043/53905240-4e7abb80-4048-11e9-9100-ad7f1129505a.png)
Then it cleans the directories, Will add that to the template...

**Comment by freddydk** [comment]
You can insert these lines as the first in CI.yml:

variables:
  build.clean: all
  platform: x64
