### ISSUE TITLE
Problem with publish app and enablesymbols version 0.5.0.5

### ISSUE THREAD

**Issue by NAVFreak** [Microsoft/navcontainerhelper#372]
When the new release was published my build agents started to fail on projects.

Our build agent can't no longer handle our hybrid environment since the last update.

```
$ImageName =   'mcr.microsoft.com/businesscentral/onprem:se' 
new-navcontainer `
           -accept_eula `
           -containername $ContainerName `
           -imageName $ImageName `
           -includecside `
           -licenseFile $DeveloperLicenseFile `
           -Credential $Credential `
           -auth NavUserPassword `
           -verbose `
           -enableSymbolLoading `
           -doNotExportObjectsToText

```

Downloaded symbols with VS Code
Skipped import of CSIDE object in this case. But it doesn't work either if you import some objects.

Created App with CTRL+F5

> Got this error:
> [2019-03-06 20:40:54.14] Sending request to http://dockermall:7049/NAV/dev/apps?SchemaUpdateMode=synchronize
> [2019-03-06 20:41:00.11] The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: Extension compilation failed
> PAG9852-EXT69925.AvailableLicenseObjects.al(22,41): error AL0118: The name 'rec' does not exist in the current context
> 

Compiled with following script
```
$containerpath = "C:\ProgramData\NavContainerHelper\Extensions\$containerName\my\CompileApp"

if (test-path -Path $containerpath) {
    Remove-Item -Path $containerpath -Force -recurse
}
copy-item -Container -path .\App -Recurse -Force -Destination $containerpath

Compile-AppInNavContainer -containerName $ContainerName `
    -appProjectFolder $containerpath `
    -appOutputFolder $containerpath `
    -UpdateSymbols `
    -credential $Credential

 Publish-NavContainerApp -containerName $ContainerName `
    -appFile  "C:\ProgramData\NavContainerHelper\Extensions\$containername\my\CompileApp\Company_MyApp_1.0.0.0.app" ` 
    -skipVerification 

```
The compilation worked but got the following from the publish:

> Using Symbols Folder: C:\ProgramData\NavContainerHelper\Extensions\DockerMall\my\CompileApp\.alpackages
> Downloading symbols: Microsoft_Application_13.0.27183.0.app
> Url : http://DockerMall:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=13.0.0.0&tenant=default
> Downloading symbols: Microsoft_System_13.0.12929.0.app
> Url : http://DockerMall:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=13.0.0.0&tenant=default
> Compiling...
> Microsoft (R) AL Compiler version 2.1.1.13845
> Copyright (C) Microsoft Corporation. All rights reserved
> 
> Compilation started for project 'MyApp' containing '1' files at '22:44:19.200'.
> 
> 
> Compilation ended at '22:44:23.44'.
> 
> C:\ProgramData\NavContainerHelper\Extensions\DockerMall\my\CompileApp\Company_MyApp_1.0.0.0.app successfully created in 15 seconds
> C:\ProgramData\NavContainerHelper\Extensions\DockerMall\my\CompileApp\Company_MyApp_1.0.0.0.app
> Publishing C:\ProgramData\NavContainerHelper\Extensions\DockerMall\my\CompileApp\Company_MyApp_1.0.0.0.app
> **Extension compilation failed**
> **PAG9852-EXT69925.AvailableLicenseObjects.al(22,41): error AL0118: The name 'rec' does not exist in the current context**
> At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:9
> +         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
> +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
>     + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp

The extension look like this:
```
pageextension 69925 "NBA Available License Objects" extends "Effective Permissions"
{
    layout
    {

    }

    actions
    {
        addlast(Processing)
        {
            action(AvailableLicensObjects)
            {
                ApplicationArea = All;
                CaptionML = ENU = 'Availabe License Objects', SVE = 'Tillgängliga licensobjekt';
                Promoted = true;
                PromotedIsBig = true;
                PromotedCategory = Process;
                Image = List;
                trigger OnAction()
                begin
                    CheckLicenseObjects(rec);
                end;
            }
        }
    }
    local procedure CheckLicenseObjects(var Permission: Record Permission)
    var
        Allobj: Record AllObj temporary;
        Window: Dialog;
        TotalCount: Integer;
        NumObjectsProcessed: Integer;
        PassedUserID: code[50];
        ObjectCounter: Integer;
    begin
        //CODE
    end;

}
```

**Comment by freddydk** [comment]
Could you try to add this:

variables:
  build.clean: all
  platform: x64

to the top of your CI.yml - and then upgrade to 0.5.0.6.
I found that unless you specify build.clean to all - then Azure DevOps will keep symbols and other things from other builds.

If you still get the error, then I will look into this.

**Comment by freddydk** [comment]
Wait a minute - you also cannot build this with VS Code?
Have you tried deleting all symbol files in .alpackages and try downloading symbols again?

**Comment by freddydk** [comment]
I can definitely repro this - but it doesn't make any sense...

I can use Rec. on a pageextension on the customer page - but apparently not on the effective permissions page.

It is included in the symbols (it can compile) but apparently the server doesn't know about it internally.

I will have to talk to the team tomorrow - until then you can force the use of 0.5.0.4

**Comment by freddydk** [comment]
So, there is a bug somewhere.
This only happens if the page extensions extends a page based on a system table.

**Comment by freddydk** [comment]
A possible workaround:
```
                trigger OnAction()
                var
                    MyRec: Record Permission;
                begin
                    CurrPage.GetRecord(MyRec);
                    CheckLicenseObjects(MyRec);
                end;
```
But I will of course try to find out why the other way isn't working.

**Comment by NAVFreak** [comment]
Since the page uses a temporary record and I need the reference to it this does unfortunately don´t work.

**Comment by freddydk** [comment]
Later versions of the NavContainerHelper includes these files (instead of downloading them), assuming that this fixed this issue.
