### ISSUE TITLE
New-BcContainer problem. Is it related to Windows 11 on ARM64, or something else?

### ISSUE THREAD

**Issue by floyd-chan** [microsoft/navcontainerhelper#3741]
Running New-BcContainer on a new Surface Pro 11 with Windows 11 on top of ARM64.

Getting an error:

DockerDo : docker.exe: Error response from daemon: hcsshim::CreateComputeSystem 
84c5b39df8b10c0a4820f5da645de912598025377fe7b3b02ea288be9f7a4b16: hcsshim: timeout waiting for notification
(extra info: {"SystemType":"Container","Name":"84c5b39df8b10c0a4820f5da645de912598025377fe7b3b02ea288be9f7a4b16","Owner":"docke 
r","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\84c5b39df8b10c0a4820f5da645de91259 
8025377fe7b3b02ea288be9f7a4b16","Layers":[{"ID":"fbe7b60d-dac9-5695-a5a3-75ffdbd4ac2a","Path":"C:\\ProgramData\\docker\\windows 
filter\\a4e3da035c766e8892bd014f61c26533251de7d8718ff79499017798e810906c"},{"ID":"74814561-b403-568b-9027-d098e67e9a49","Path": 
"C:\\ProgramData\\docker\\windowsfilter\\050afd16b7ce70d1894b5df8545c8c7042575665b7a059dfac4f089f408f975c"},{"ID":"8a27672a-717 
9-5ca0-8116-f49e2efcd4bb","Path":"C:\\ProgramData\\docker\\windowsfilter\\7c2fbb16865764bd4339da4c9f79ef8a71063276e5a1795a5c4cd 
a3856dc8001"},{"ID":"a8170f41-781e-5db4-910b-b296ceb2861e","Path":"C:\\ProgramData\\docker\\windowsfilter\\a4a302ed5b900f757647 
9d89fecfb7e8bd0d91065cd6728c5711900c32b518ad"},{"ID":"2b52a5a5-879b-5121-8bec-56d68a4730d7","Path":"C:\\ProgramData\\docker\\wi 
ndowsfilter\\81461003a76f345076c40236be21be39f295150684fa21f8b6f1000223dfdd63"},{"ID":"4e40de05-4f3a-5a6d-8b52-7185e0017948","P 
ath":"C:\\ProgramData\\docker\\windowsfilter\\51f9b8638af483ec6e0ee87ab761f0d49c4b0bc7eb6b1dc65cef262f88c4aa3b"},{"ID":"e0e0923 
d-18a1-5856-a43b-57ebc4ce0225","Path":"C:\\ProgramData\\docker\\windowsfilter\\44550318d802406cef762e5fa3d8f2edd632e62b256b9fdc 
a753f6ab6e864863"},{"ID":"b90c25a8-4c65-5109-bc30-d6045e49ffdc","Path":"C:\\ProgramData\\docker\\windowsfilter\\7ed08736f1d0c0b 
6d69be616a613463e818eb1d28f431fec7bab88bea75275e0"},{"ID":"1f4ff990-c9f9-5031-8f35-72e50b55bbee","Path":"C:\\ProgramData\\docke 
r\\windowsfilter\\814d93d6e7a8b2fc7ff271724c5b571e32368b13e6038a4240e7130a966f8ba4"},{"ID":"7e03f2d7-6113-5ba4-8ad4-8ac0de84e67 
6","Path":"C:\\ProgramData\\docker\\windowsfilter\\b2422f481432fbcda215b2968f630991ea6e0a74fd1878a186378ccb6bb3d08c"},{"ID":"58 
b716e9-a7b6-50a7-b4ac-916ea95d99a2","Path":"C:\\ProgramData\\docker\\windowsfilter\\6d10af3a9d21c479e446775bf0ebb56ce19f7510cc3 
fb766e27fe3bb21b86fb6"},{"ID":"1f8d404d-08a2-54aa-a055-0f7947e80bed","Path":"C:\\ProgramData\\docker\\windowsfilter\\f12f90a4ce 
508fadce6c841bee98924e48e134ecc9370e05d6a236da7f7dd376"},{"ID":"8c951802-7b95-5b22-8dd9-ae416c48b960","Path":"C:\\ProgramData\\ 
docker\\windowsfilter\\80ea1ba96d19e6187aaae0f3d9c7da9ed527924e62edfd0a9173e4fb3e78fc01"},{"ID":"8df795ba-b8ee-5617-a5d7-5060d8 
66abe6","Path":"C:\\ProgramData\\docker\\windowsfilter\\dab8d8bc7531531088990c0950d2a52d22c583224a0d4a7f09e6bc68f920d9d3"}],"Me 
moryMaximumInMB":8192,"HostName":"bcsandbox","MappedDirectories":[{"HostPath":"c:\\bcartifacts.cache","ContainerPath":"c:\\dl", 
"ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\windows\\system32\\drivers\\e 
tc","ContainerPath":"c:\\driversetc","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPat 
h":"c:\\programdata\\bccontainerhelper","ContainerPath":"c:\\programdata\\bccontainerhelper","ReadOnly":false,"BandwidthMaximum 
":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\bccontainerhelper\\extensions\\bcsandbox\\my","Con 
tainerPath":"c:\\run\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":true, 
"EndpointList":["1ad08566-4e48-4295-972c-10548ef75382"],"HvRuntime":{"ImagePath":"C:\\ProgramData\\docker\\windowsfilter\\80ea1 
ba96d19e6187aaae0f3d9c7da9ed527924e62edfd0a9173e4fb3e78fc01\\UtilityVM"},"AllowUnqualifiedDNSQuery":true}).
ExitCode: 125
Commandline: docker run --volume "c:\bcartifacts.cache:c:\dl" --label nav= --env isBcSandbox=Y --label
version=25.0.23364.26096 --label platform=25.0.26038.0 --label country=US --env
artifactUrl=https://bcartifacts-exdbf9fwegejdqak.b02.azurefd.net/sandbox/25.0.23364.26096/us --env multitenant=Y --env
licenseFile="c:\run\my\license.bclicense" --name bcsandbox --hostname bcsandbox --env auth=NavUserPassword --env
username="floyd" --env ExitOnError=N --env locale=en-US --env databaseServer="" --env databaseInstance="" --volume
"C:\ProgramData\BcContainerHelper:C:\ProgramData\BcContainerHelper" --volume
"C:\ProgramData\BcContainerHelper\Extensions\bcsandbox\my:C:\Run\my" --isolation hyperv --restart unless-stopped --env
filesOnly=False --memory 8G --env enableApiServices=Y --env useSSL=N --volume "c:\windows\system32\drivers\etc:C:\driversetc"   
--env securePassword=76492d1116743f0423413b16050a5345MgB8AHUAaQBLAHYASgB0AGUAdwBGAFEAbABSAE0AaABWAHoAeQBEAHAAOQBwAGcAPQA9AHwAZQ 
BlADAAYgBmAGEAZgAxADMAMwAxADgANgAxADkAYwA5ADkANABjADIAZAAzAGEAZQBhADUAYQBjADUAYwA1AA== --env
passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env customNavSettings=EnableTaskScheduler=True --env        
accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral:ltsc2022
At C:\Program Files\WindowsPowerShell\Modules\BcContainerHelper\6.0.26\ContainerHandling\New-NavContainer.ps1:1859 char:15
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by floyd-chan** [comment]
Hi Freddy!

This is a month-old machine and I have not yet been able to create and run a BC container on it yet.

I just tried creating a windows server core container and this is the result:

PS C:\Users\fchan> docker run -it mcr.microsoft.com/windows/servercore:ltsc2022 cmd
C:\Program Files\docker\docker.exe: Error response from daemon: container 4c415da55a5ba8e3f86f1140f77a1e784272ccb5b8e8376efdd0fea9bd2d4ec5 encountered an error during Start: failure in a Windows system call: The virtual machine or container exited unexpectedly. (0xc0370106).

**Comment by freddydk** [comment]
As far as I can find - ARM64 computers only supports IoT and Nano server, but not Windows Server Core (which is the OS we require to run BC).
Sorry
