### ISSUE TITLE
Using Replace-DependenciesInAppFile.ps1 ReplaceVersionNumber to check on breaking changes rules in AppSourceCop

### ISSUE THREAD

**Issue by SjoerddeClippelaar** [microsoft/navcontainerhelper#3748]
Dear Freddy,

We are using AppSourceCop in our pipelines to validate Pull Request on breaking changes. During the run we change to AppSourceCop.json file and run CompileAppInBCContainer, which works great.

BUT we also want to give errors on breaking changes locally, but we don't want to change the version from the app in de AppSourceCop.json file every time we complete a pull request.

In the BcContainerHelper you created this _Replace-DependenciesInAppFile_ function that we wanted to use to create a _major.minor.1.1_ app file. So we don't have to change the settings file. We can successfully create a app file with a new number, but AppSourceCop can't find the file anymore.

![Image](https://github.com/user-attachments/assets/952c1046-72a6-4ac2-b041-9d8c39aa772f)

Are we missing something? Or can you explain for what reason this ReplaceVersionNumber is used? Or do you expect it should work?

Thank you for your reply

**Comment by freddydk** [comment]
I don't understand why you would have to modify the version number in the previous release?
AL-Go for GitHub automatically grabs the latest released version and uses that for breaking changes check without any of those workarounds.

**Comment by SjoerddeClippelaar** [comment]
Hi Freddy, thank you for your fast reply. We would like to see breaking errors also in our VSCode when programming. If we don't change the versionnr. We need to change it in the AppSourceCop.json file everytime we run a CI build, that is unwanted, because it is not part of the original commit.

Like I said we already fixed it in our DevOps pipeline, so that works fine.

You think you can help us?

**Comment by freddydk** [comment]
The way we handle this in AL-Go is to update app.json with a new major or minor versoin whenever we release a version - and then we use the released version for breaking change validation. If the replace-dependencies with a version number change doesn't work for you, you could maybe change the release process yourself?

**Comment by SjoerddeClippelaar** [comment]
Yeah we do the same in the DevOps pipeline. Before we compile we have the previous version. Change the number in the AppSourceCop.json and check on breaking changes. But we didn't want to commit that change, because it is not part of the original commit the developer pushed. 

So we probably end up only checking for breaking changes in the DevOps pipeline and not locally in VSCode. Thank you.

**Comment by freddydk** [comment]
Your main branch should always have a higher major.minor than your latest release - so that you (in VS Code or in the pipeline) can download and use the latest release for breaking changes checks.
Else you will produce builds from your main pipeline / VS Code which conflicts with your released version.
