### ISSUE TITLE
Replace-NavServerContainer fails with developer preview during import of CreateTestUsers

### ISSUE THREAD

**Issue by megel** [Microsoft/navcontainerhelper#376]
Insider Docker Image: `bcinsider.azurecr.io/bcsandbox-master:14.0.28630.0-al`

![image](https://user-images.githubusercontent.com/15800069/54075004-eb806300-4299-11e9-9b66-7ec8e270ada8.png)

There is no C/Side base application :) … this means, some scripts must be changed in the future. 

A current solution is to disable creation of test users:
`$CreateTestUsers = "No"`

**Comment by freddydk** [comment]
Thanks, will have to create these things as apps:-)

**Comment by freddydk** [comment]
I have converted the create test users to an app and use publish, install and unpublish the app.
