### ISSUE TITLE
Need to provide parameter for which SQL PowerShell module to use

### ISSUE THREAD

**Issue by MattTraxinger** [microsoft/navcontainerhelper#3762]
**Describe the issue**
There can be issues when both SQLPS and the SQLServer PowerShell modules are both installed. Restore-BcDatabaseFromArtifacts will fail. Additionally I believe SQLPS is not the recommended module at this point.

**Scripts used to create container and cause the issue**
Following the scripts here: https://community.dynamics.com/blogs/post/?postid=cb3372ed-161f-4549-b935-7b4028e0cd72

Proposed PR coming shortly.

**Comment by freddydk** [comment]
Inside the container, SQLPS is only used in PS5 and the SQLServer module is only installed in PS7 (and is not compatible with PS5).
But... - that function should be working on both though as it doesn't run inside the container.

Will look at your PR when it arrives.

**Comment by freddydk** [comment]
SQLPS in PS5 is part of the SQL installation - will never exist on PS7.
SqlServer needs to be installed manually - can be installed globally (PS5 and PS7) or locally in PS7 only.
