### ISSUE TITLE
New-NavContainer in SetupNavUsers err: Windows account could not be mapped..

### ISSUE THREAD

**Issue by AndreasR2019** [Microsoft/navcontainerhelper#377]
I deploy BCOnprem in our dev team, all notebooks with windows 10 running, all users logged in same active directory with identical groups with one powershell-Script - see docker-dyn365bc-standard-cronus_install.txt).
On one Installation (out of four) I get an error that the container could not be initialized - see New-Nav Client Error.txt
Docker logs in docker logs.txt
[docker logs.txt](https://github.com/Microsoft/navcontainerhelper/files/2951722/docker.logs.txt)
[docker-dyn365bc-standard-cronus_install.txt](https://github.com/Microsoft/navcontainerhelper/files/2951723/docker-dyn365bc-standard-cronus_install.txt)
[New-Nav Client Error.txt](https://github.com/Microsoft/navcontainerhelper/files/2951724/New-Nav.Client.Error.txt)

Any idea? 
Thx 
Andreas

**Comment by freddydk** [comment]
The username is daniela.proeschle - is that really the username (whoami on the host)?

**Comment by AndreasR2019** [comment]
Yes, it is:
C:\Users\daniela.proeschle>whoami
ourdomainname\daniela.proeschle

C:\Users\daniela.proeschle>
09:10


Andreas Rohrbach, Bechtle AG, Phone: +49 7132 981 4727

Von: Freddy Kristiansen <notifications@github.com>
Gesendet: Montag, 11. März 2019 14:36
An: Microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Rohrbach, Andreas <andreas.rohrbach@bechtle.com>; Author <author@noreply.github.com>
Betreff: Re: [Microsoft/navcontainerhelper] New-NavContainer in SetupNavUsers err: Windows account could not be mapped.. (#377)


The username is daniela.proeschle - is that really the username (whoami on the host)?

**Comment by freddydk** [comment]
And does the other users (who are working) have similar ad names?
when you write whoami /user - do you get the same username and her SID?

**Comment by AndreasR2019** [comment]
Yes, the name convention is the same:
C:\Users\daniela.proeschle>whoami /user

BENUTZERINFORMATIONEN
---------------------

Benutzername              SID
========================= =============================================
xyz\daniela.proeschle S-1-5-21-1275210071-1220945662-839522115-1635

C:\Users\daniela.proeschle>

And this is mine:

PS C:\Windows\system32> whoami /user

BENUTZERINFORMATIONEN
---------------------

Benutzername             SID
======================== ===============================================
xyz\andreas.rohrbach S-1-5-21-1275210071-1220945662-839522115-229559

Von: Freddy Kristiansen <notifications@github.com>
Gesendet: Dienstag, 12. März 2019 09:24
An: Microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Rohrbach, Andreas <andreas.rohrbach@bechtle.com>; Author <author@noreply.github.com>
Betreff: Re: [Microsoft/navcontainerhelper] New-NavContainer in SetupNavUsers err: Windows account could not be mapped.. (#377)


And does the other users (who are working) have similar ad names?
when you write whoami /user - do you get the same username and her SID?

**Comment by AndreasR2019** [comment]
We stop using Docker image files with BC, I've done 4 installations on four different machines, each one with different problems. 3 of them I could solve, but when the user cannot login thats not useful. Too much time spent.
