### ISSUE TITLE
Get-BcNuGetPackageId name length limit

### ISSUE THREAD

**Issue by DominicSaladin** [microsoft/navcontainerhelper#3772]
**Describe the issue**
The function `Get-BcNuGetPackageId` cuts the name if the length of the package id is greater equals 100 instead of greater 100. So if it packageid is exactly 100 characters, it gets cut down to 99 characters.
Then when downloading the nuget package it fails, as the name isnt the same as Microsoft generates it for the AppSource symbols feed.

**Comment by DominicSaladin** [comment]
And another one with 123 characters:
https://dynamicssmb2.visualstudio.com/DynamicsBCPublicFeeds/_artifacts/feed/AppSourceSymbols/NuGet/GOBSoftwareSystemeGmbHCoKG.unitopEnhancedContactManagem.symbols.e9481a49-d1b2-443c-a8a1-5de24bc8c31d/overview/2024.9.20241127.66985

**Comment by freddydk** [comment]
Sounds like a bug
