### ISSUE TITLE
Web request gets LatestGenericTagVersion each time module is loaded

### ISSUE THREAD

**Issue by MaxFalcone** [microsoft/navcontainerhelper#3778]
**Describe the issue**
Web request is invoked every time module is loaded, but there is no reason to do this request.
See this [code block](https://github.com/microsoft/navcontainerhelper/blob/d44c7e728de7c6cdb45d8ba39418100402e03869/BcContainerHelper.psm1#L291)

It says `In Development mode only` but it runs every time module is loaded because it checks content of LatestGenericTagVersion.txt file. This file never updated on user machines. So version is always 0.0.0.0 and check is always performed.

**Scripts used to create container and cause the issue**
```pwsh
import-Module BcContainerHelper
```

**Full output of scripts**
```
BcContainerHelper version 6.0.28
BC.HelperFunctions emits usage statistics telemetry to Microsoft
Running on Windows, PowerShell 5.1.20348.2849
LatestGenericTagVersion is 1.0.2.51
WARNING: The names of some imported commands from the module 'BcContainerHelper' include unapproved verbs that might 
make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the 
Verbose parameter. For a list of approved verbs, type Get-Verb.
```
See the line saying 
LatestGenericTagVersion is 1.0.2.51

I suppose this file should have been filled by the pipeline that builds module or something.

**Comment by freddydk** [comment]
This file should be updated in the build process - will check.

**Comment by freddydk** [comment]
That only happened in the preview version.
Fixed in the next version
