### ISSUE TITLE
Get-NavContainerOsVersion does not work

### ISSUE THREAD

**Issue by epernst** [Microsoft/navcontainerhelper#378]
When running the Get-NavContainerOsVersion cmdlet, I'm getting this error:

_Get-NavContainerOsVersion : The property 'OsVersion' cannot be found on this object. Verify that the property exists.
At line:1 char:1
+ Get-NavContainerOsVersion -containerOrImageName MyServer
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-NavContainerOsVersion], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-NavContainerOsVersion_

NCH version: 0.5.0.6

**Comment by freddydk** [comment]
Right you are - not sure if that error has been there all the time, or the property has been removed in the base images.
Anyway - It will be fixed in the next version of NCH
The code for getting it now is:
        $inspect = docker inspect $containerOrImageName | ConvertFrom-Json
        return "$($inspect.Config.Labels.osversion)"

**Comment by epernst** [comment]
I'm quite sure that it worked previously.

**Comment by freddydk** [comment]
Yep - it did - maybe that property exists on Windows Server 2016 core images - and not on 2019 ?

**Comment by freddydk** [comment]
Fixed in 0.5.0.7
