### ISSUE TITLE
DNS not working 

### ISSUE THREAD

**Issue by JulianTillmann** [Microsoft/navcontainerhelper#379]
Hi Freddy, 

we're creating a new docker container with 
`new-navcontainer -accept_eula -containerName 'BC130' -imageName  'mcr.microsoft.com/businesscentral/onprem:cu2-de' -memory '4G' -licenseFile 'c:\temp\fin.flf' -auth NavUserPassword `

everything works fine, except the DNS. We only can reach the machine via DevelopmentPort & Webclient at the IP-Address, the name doesn't work at all. 

What are we doing wrong? 

Thanks a lot & Best Regards
Julian

**Comment by NAVspecialist** [comment]
Read the guide :)

You have to add the parameter -updateHosts

**Comment by JulianTillmann** [comment]
thanks for the quick answer, but which guide? It's all spread across GitHub, PowerShell Gallery and the Blog which isn't that clear in itself. I had a Major issue using "-useBestContainerOS" in the past on a different machine as well

But I'll try the updateHost-thing

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by JulianTillmann** [comment]
sorry for the missing Feedback. yeah, it seems to be working now. thanks. 

still, the documementation could be a little bit more clear :)

**Comment by freddydk** [comment]
Point taken - I think the best source of documentation for Docker would be to follow my blog.
The problem really is, that you cannot create one doc. that covers all aspects on how to setup docker.
