### ISSUE TITLE
WinClient Debugger shortcut not deleted in remove command

### ISSUE THREAD

**Issue by ashik-ivor** [Microsoft/navcontainerhelper#380]
When I remove a container with the help of Remove-NavContainer, it is not deleting the "WinClient Debugger" shortcut.

**Comment by barandeniz** [comment]
Yeah, i encountered this issue also. FYI.

**Comment by kine** [comment]
I confirm...

**Comment by lvanvugt** [comment]
:-) Just experienced this too.

**Comment by freddydk** [comment]
Fixed in 0.5.0.7
