### ISSUE TITLE
Error Calling Invoke-NavContainerCodeunit

### ISSUE THREAD

**Issue by jimmymcp** [Microsoft/navcontainerhelper#381]
We are importing and compiling a codeunit with Import-ObjectsToNavContainer and Compile-ObjectsInNavContainer to prep the test suite with the test codeunits and methods that we want to run with Run-TestsInNavContainer.

We want to invoke a method of that codeunit with Invoke-NavContainerCodeunit but it fails with the following.

(PowerShell output)
docker : Invoke-NAVCodeunit : The server "NAV" was unable to process the request. The 
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.6\ContainerHandling\Invoke-ScriptInNavContainer.ps1:80 char:13
+             docker exec $containerName powershell $file
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Invoke-NAVCodeu...e request. The :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

(docker logs output)
TimeGenerated : 3/14/2019 11:57:32 AM
EntryType     : Error
Message       : Type: System.ServiceModel.FaultException`1[[Microsoft.Dynamics.
                Nav.Types.ServerFault, Microsoft.Dynamics.Nav.Types, 
                Version=13.0.0.0, Culture=neutral, 
                PublicKeyToken=31bf3856ad364e35]]
                Action: http://www.microsoft.com/Dynamics/NAV/51/ServerFault
                Message: The server "NAV" was unable to process the request. 
                The application will close.
                StackTrace:
                  
                  Server stack trace: 
                     at System.ServiceModel.Channels.ServiceChannel.HandleReply
                (ProxyOperationRuntime operation, ProxyRpc& rpc)
                     at 
                System.ServiceModel.Channels.ServiceChannel.Call(String 
                action, Boolean oneway, ProxyOperationRuntime operation, 
                Object[] ins, Object[] outs, TimeSpan timeout)
                     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke
                Service(IMethodCallMessage methodCall, ProxyOperationRuntime 
                operation)
                     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke
                (IMessage message)
                  
                  Exception rethrown at [0]: 
                     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnM
                essage(IMessage reqMsg, IMessage retMsg)
                     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke
                (MessageData& msgData, Int32 type)
                     at Microsoft.Dynamics.Nav.Types.INCLAdminService.InvokeCod
                eunit(ConnectionRequest connectionRequest, Int32 codeunitId, 
                String methodName, String argument, String companyName, 
                InvokeCodeunitTimeZone invokeTimeZone)
                     at Microsoft.Dynamics.Nav.Management.Cmdlets.InvokeNavCode
                unit.InternalProcessRecord()
                     at 
                Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
                Source: mscorlib
                HResult: -2146233087
                StackTrace:
                  
                  Server stack trace: 
                     at System.ServiceModel.Channels.ServiceChannel.HandleReply
                (ProxyOperationRuntime operation, ProxyRpc& rpc)
                     at 
                System.ServiceModel.Channels.ServiceChannel.Call(String 
                action, Boolean oneway, ProxyOperationRuntime operation, 
                Object[] ins, Object[] outs, TimeSpan timeout)
                     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke
                Service(IMethodCallMessage methodCall, ProxyOperationRuntime 
                operation)
                     at System.ServiceModel.Channels.ServiceChannelProxy.Invoke
                (IMessage message)
                  
                  Exception rethrown at [0]: 
                     at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnM
                essage(IMessage reqMsg, IMessage retMsg)
                     at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke
                (MessageData& msgData, Int32 type)
                     at Microsoft.Dynamics.Nav.Types.INCLAdminService.InvokeCod
                eunit(ConnectionRequest connectionRequest, Int32 codeunitId, 
                String methodName, String argument, String companyName, 
                InvokeCodeunitTimeZone invokeTimeZone)
                     at Microsoft.Dynamics.Nav.Management.Cmdlets.InvokeNavCode
                unit.InternalProcessRecord()
                     at 
                Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
                

TimeGenerated : 3/14/2019 11:57:32 AM
EntryType     : Error
Message       : Server instance: NAV
                Tenant ID: 
                User: User Manager\ContainerAdministrator
                Type: System.NullReferenceException
                Message: Object reference not set to an instance of an object.
                StackTrace:
                     at Microsoft.Dynamics.Nav.Service.NSServiceBase.<>c__Displ
                ayClass14_0.<ValidateAndCreateSession>b__0()
                     at Microsoft.Dynamics.Nav.Service.NSServiceBase.ValidateAn
                dCreateSession(ConnectionRequest connectionRequest, Boolean 
                requireNavUser)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                CreateNewSessionCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, Boolean requireNavUser, 
                Object[] inputs, Object[]& outputs)
                Source: Microsoft.Dynamics.Nav.Service
                HResult: -2147467261
                StackTrace:
                     at Microsoft.Dynamics.Nav.Service.NSServiceBase.<>c__Displ
                ayClass14_0.<ValidateAndCreateSession>b__0()
                     at Microsoft.Dynamics.Nav.Service.NSServiceBase.ValidateAn
                dCreateSession(ConnectionRequest connectionRequest, Boolean 
                requireNavUser)
                     at Microsoft.Dynamics.Nav.Service.ServiceOperationInvoker.
                CreateNewSessionCombinator(ServiceOperation innerOperation, 
                NSServiceBase serviceInstance, Boolean requireNavUser, 
                Object[] inputs, Object[]& outputs)

**Comment by MikeGlue** [comment]
Just came to log this same issue. :)

**Comment by richardrobberse** [comment]
I guess you're also facing this issue on one of the bcinsider master builds?

**Comment by MikeGlue** [comment]
For me I'm pulling this image:
bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019

this is the version info from the image:
"platform": "14.0.28928.0",
"version": "14.0.29113.0"

This worked as recent as last week so something within the past build or 2 changed this I guess.

**Comment by jimmymcp** [comment]
We're seeing this in the latest mcr.microsoft.com/businesscentral/onprem image. Have just tested successfully in mcr.microsoft.com/businesscentral/onprem:13.2.26556.0-ltsc2019

**Comment by richardrobberse** [comment]
I discovered it on bcinsider.azurecr.io/bcsandbox:13.4.28391.0-w1 yesterday, with the exact same error.

**Comment by freddydk** [comment]
I think this is a license issue.
Invoke-NavContainerCodeunit uses invoke-NavCodeunit, which only works with Windows auth.

When running containers with navuserpassword, Invoke-NavContainerCodeUnit will try to create a Windows user and use that. Some of this stopped working.

I will try to investigate what I can do / who I can file a bug on, but that will be tomorrow while travelling to the US - no time today.

If anybody discovers a workaround - please let me know.
BTW - I think it works with windows auth.

**Comment by jimmymcp** [comment]
No, this definitely used to work with NavUserAuth (I've tested it this morning with 13.2.26556.0 and it worked). It looks like the problem has been introduced in recent images.

**Comment by freddydk** [comment]
Yes, it used to work with NavUserPassword auth.
and it isn't a license issue.
But... - it works with Windows auth.
Trying to find out what happened.

**Comment by freddydk** [comment]
This is a bug in the platform - they are looking into this

**Comment by freddydk** [comment]
I have created a workaround for the create test users in NavContainerHelper 0.5.0.7.
A fix, which is needed in the future anyway.
Instead of importing a .fob file and invoking a codeunit - I am publishing an app and running the code in the install rigger,
This is the mechanism we need to use when the app gets transformed to AL anyway.
Upgrade to NavContainerHelper 0.5.0.7 - then this should work.
Note there might be other places where Invoke-Codeunit is used - these will also be changed - AND the bug will be fixed in the platform and backportet.

**Comment by ichladil** [comment]
Instead of install triggers - my preference would be to move the FOBs to APIs published by apps . In such a way it can be run multiple times and it allows for multiple parameters.  
Invoke-RestMethod then works quite well with these.

However to better support this, it would be nice if we have in navcontainerhelper some new function like Invoke-NavContainerRestMethod so that we don't have to type all Auth and similar stuff every time. 

I am using this approach quite successfully when generating test suites for Run-TestsInNavContainer.

**Comment by freddydk** [comment]
I agree - that seems like a much nicer solution. Thanks for the idea.

**Comment by freddydk** [comment]
I have implemented this suggestion and described it here https://freddysblog.com/2019/03/27/navcontainerhelper-0-5-0-11/
Again, thanks for the suggestion.
