### ISSUE TITLE
Compile-AppInNavContainer cannot download symbols on containers without updated hosts

### ISSUE THREAD

**Issue by ichladil** [Microsoft/navcontainerhelper#382]
When running Compile-AppInNavContainer the symbols download is handled via container name. This doesn't work for me when I skip updateHosts option (or create docker via standalone docker run) .... 

If the symbols are downloaded using IP address retrieved instead via Get-NavContainerIpAddress $ContainerName I believe it shall work no matter if update hosts is present or not.

**Comment by freddydk** [comment]
Using the IP number wouldn't work if using https - then I would have to setup a function to ignore certificate errors. But maybe that is the weay forward - simply ue localhosty.

**Comment by freddydk** [comment]
I will change Compile-AppInNavContainer to do more inside the container and as such, it can use localhost instead of the host name or ip number.

**Comment by freddydk** [comment]
Implemented in NavContainerHelper 0.5.0.11
