### ISSUE TITLE
Azure Sandbox Deployment Errors Resource Not Supported 

### ISSUE THREAD

**Issue by cloudycanuck** [Microsoft/navcontainerhelper#383]
Hi, I am having difficulties when trying to deploy the Sandbox environment to Azure via Business Central. I ran the template & parameters through the Azure RM Template Validation and receive the following. 

arm | NotSupported |  
-- | -- | --
--  azuredeploy.json | NotSupported | NotSupported: Resource type 'firewallrules' NotSupported: Resource type 'databases' NotSupported: Resource type 'databases'

**Comment by freddydk** [comment]
Could you share some info on which template you use (aka.ms/???) and which selections you have done?

**Comment by cloudycanuck** [comment]
Hi Freddy,

I used the template (attached)  that is downloaded when you try to deploy an environment via the business central admin page.   As far as selections go I left it pretty well default. Using SQL Express, and allowing all IP to connect.

Josh

**Comment by cloudycanuck** [comment]
Freddy,

The errors that I was getting lead me to believe it was something to do with the Azure SQL items in the JSON template.

**Comment by freddydk** [comment]
That specific piece of the template will only be included if you select Azure SQL and if you select Azure SQL you also need to specify bacpacs for app and tenant database.

**Comment by cloudycanuck** [comment]
See that’s what I thought too, but I know I specified to use SQL Server

**Comment by cloudycanuck** [comment]
Not sure if this makes a difference but I’m logging into the BC environment using an @<clientdomain>.onmicrosoft.com account and deploying to an Azure subscription with my @work.com account.

**Comment by cloudycanuck** [comment]
I was able to get this working! Thanks for your help Freddy.
