### ISSUE TITLE
Unable to create Container - Outdated Image

### ISSUE THREAD

**Issue by Kushal5** [Microsoft/navcontainerhelper#384]
Hi, I am not able to create this container from an older image(8 weeks). Please refer below the output.

![image](https://user-images.githubusercontent.com/17171560/54508710-d642bd00-499a-11e9-8419-eea0b520aff7.png)

**Comment by Kushal5** [comment]
Hi, 

I noticed that the code was breaking on line 730

if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated -detach -imageName $imageName -parameters $parameters)) {
                return
            }

I assumed it was because I was running an older image. That is not the case, It was infact a paging issue in Windows 10. You have to select 'System Managed Size' as the paging option under Performance Options. That fixed my issue, and allowed me to create the container after restarting docker. 

I hope this thread helps other who may face similar issue.

**Comment by freddydk** [comment]
I noticed you are running Windows 10 1803.
If you upgrade to 1809, you will be able to use process isolation and the much smaller ltsc2019 images.
A lot of issues (like the one you mention here) goes away with 1809 - in fact the combination 1803 and ltsc2016 is the one that caused most problems with our containers.

**Comment by Kushal5** [comment]
Thanks for the heads-up, will save our team a great deal of effort knowing this :)
