### ISSUE TITLE
Run-TestsInNavContainer 'cannot open page 61266'

### ISSUE THREAD

**Issue by mmenninghaus** [Microsoft/navcontainerhelper#385]
I created a new container with

```new-navcontainer -accept_eula -licenseFile *** -containerName test -imageName mcr.microsoft.com/businesscentral/onprem -includeTestToolkit -includeTestLibrariesOnly -doNotExportObjectsToText -TimeZoneId (Get-TimeZone).Id -accept_outdated -includeCSide```

I start 

```Run-TestsInNavContainer test```

Although in CSide the page is imported and compiled

![2019-03-18 16_05_00-](https://user-images.githubusercontent.com/43880502/54540130-b5c53380-4997-11e9-890d-294ae43ed180.png)

I get

```Creating user manager\containeradministrator as user
Cannot open page 61266. You might need to import the page object here: http://aka.ms/pstesttoolfob
In C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.4\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30
Zeichen:9
+         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...s/pstesttoolfob:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 61266. You might need to import the page object here: http://aka.ms/p
   stesttoolfob```

**Comment by freddydk** [comment]
Not sure why this happens, but the latest version of navcontainerhelper references a different .fob file which is using object id 130409.

**Comment by mmenninghaus** [comment]
Updated to the latest Version 

```ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.5.0.6    navcontainerhelper                  {Add-FontsToNavContainer, Backup-NavContainerDatabases, Check-NavContainerHelperPermissions, Compile-AppInNavContainer...}

```

and get

```  Run-TestsInNavContainer test
Downloading C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\PsTestFunctions.ps1
Downloading C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\ClientContext.ps1
Downloading C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\PSTestToolPage.fob
Importing Objects from C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\PSTestToolPage.fob (container path)
Objects successfully imported
Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.6\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 Zeichen:9
+         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...testtoolpagefob:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob 

```

**Comment by freddydk** [comment]
Strange - maybe this happens because the container cannot see itself.
like this https://github.com/Microsoft/navcontainerhelper/issues/382
could you try to open the container prompt and see if you can ping test
you could also add -updatehosts

**Comment by mmenninghaus** [comment]
The ping works perfectly.
I also created a new container with -updatehosts. Still the same failure, now with page 130409, which is listed as compiled in CSide.

**Comment by freddydk** [comment]
If you open the Web Client - and remove everything after ? in the address bar - and then add page=130409 - what happens?

**Comment by mmenninghaus** [comment]
![2019-03-18 17_47_45-View - Test Tool - Dynamics 365 Business Central und 1 weitere Seite ‎- Microsof](https://user-images.githubusercontent.com/43880502/54547438-fd52bc00-49a5-11e9-840a-b0997c5e97d7.png)

**Comment by freddydk** [comment]
Could you try to recreate the container using NavUserPassword authentication?
and then specify credentials to run-tests

**Comment by freddydk** [comment]
I looked at the code and can see, that the actual error behind why the form couldn't open might be hidden.
If you retry (recreating the container), then the actual error should be printed.

**Comment by freddydk** [comment]
Example when running on my machine now:
PS C:\WINDOWS\system32> Run-TestsInNavContainer fkx -credential $credential
ERROR: You do not have the following permissions on Page PS Test Tool Page: Execute.

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '35'.

Page View - Test Tool has to close
Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
At C:\Users\freddyk\Documents\GitHub\Microsoft\navcontainerhelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:9
+         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...testtoolpagefob:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob

**Comment by mmenninghaus** [comment]
NavContainerHelper Version 5.0.8

New Container with

```
new-navcontainer -accept_eula -licenseFile ***' -containerName test -imageName mcr.microsoft.com/businesscentral/onprem -includeTestToolkit -includeTestLibrariesOn
ly -doNotExportObjectsToText -TimeZoneId (Get-TimeZone).Id -accept_outdated -includeCSide -updatehosts -Credential $credential -auth "NavUserPassword"
```

```
 Run-TestsInNavContainer -containerName test -credential $credential
```

results in

```
Downloading C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\PsTestFunctions.ps1
Downloading C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\ClientContext.ps1
Downloading C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\PSTestToolPage.fob
Importing Objects from C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool\PSTestToolPage.fob (container path)
Objects successfully imported
Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
In C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.8\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30
Zeichen:9
+         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...testtoolpagefob:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
````

**Comment by kine** [comment]
What you will get in fob when you try to download fob from this url: https://aka.ms/pstesttoolpagefob 

Which object is inside the fob? it should be page 130409. If not, that may be some problems with caching etc. could be the source of the problem.

**Comment by freddydk** [comment]
Strange indeed - I have a number of sessions today at the MVP summit here in Redmond - but I would like to look closer to your problem. Could you shoot me an email to freddyk at microsoft dot com, then we can try to setup a screen share so that I can see what is going on - maybe tomorrow?

**Comment by mmenninghaus** [comment]
I found the reason. I seem to have used the wrong licence. The licence I used will expire in 7 days, we just received our new dev licence with which everything works as expected. Thank you very much for your effort and sorry for any unconvenience. Still wondering why, compiling/publishing etc. in several CAL and AL projects worked with the old licence, but that is something completly different. Wishing a great MVP summit!

**Comment by freddydk** [comment]
Thanks for the info
and thanks for reporting this - I did find and fix one error based on this issue - so that was good:-)

**Comment by ichladil** [comment]
Just now I ran into the same issue and I also have the expiring license. My assumption is that the root cause will be in the warning when you try to open page 130409. going to http://containername/nav/?page=130409 results first in warning 

> Caution: Your program license expires in xx days. 

The page 130409 can be opened only once the warning is confirmed ...

**Comment by freddydk** [comment]
Sounds right - I don't think I have a license on which I can repro this - but I will try to see if I can find one.

**Comment by kine** [comment]
Do you want one expiring license? I have one and have same issue now...

**Comment by freddydk** [comment]
Have fixed the clientcontext script and updated it
I will also be including the scripts and fob in the navcontainerhelper module instead of downloading them every time.
