### ISSUE TITLE
Add ruleset Parameter to Compile-AppInNavContainer.ps1

### ISSUE THREAD

**Issue by marknitek** [Microsoft/navcontainerhelper#389]
We use rulesets in our extensions to manage warnings/errors. 
Now we would like to enforce these rulesets with our build pipelien which relies on navcontainerhleper. 

To accomplish this we would need another Parameter in `Compile-AppInNavContainer` for the Ruleset.

**Comment by freddydk** [comment]
Implemented in NavContainerHelper 0.5.0.11
