### ISSUE TITLE
Creating additional NAV instance inside container

### ISSUE THREAD

**Issue by fibbert** [Microsoft/navcontainerhelper#392]
Are there any special requirements to allow me to create a new NAV Instance inside the container?

We are connecting our container to an external (external to the container) SQL Database - and when we create a new instance using powershell we get all kinds of SQL Authentication errors. 

Am I missing a powershell step or setting that sets the account under which I should run the new instance service?

Any examples would be really helpful.

**Comment by freddydk** [comment]
That isn't a supported scenario. Create another container instead - if you are running process isolation that will be more or less the same thing.
