### ISSUE TITLE
Import-NavContainerLicense fails with "...does not exist." error

### ISSUE THREAD

**Issue by meilel** [Microsoft/navcontainerhelper#393]
Docker-Images: All. 
NavContainerHelper Version: 0.5.0.9

When I try to Import my Nav-License via NavContainerHelper, I get the following error:
![image](https://user-images.githubusercontent.com/46705270/54934457-d3a61180-4f1e-11e9-8c5a-e628120a72ba.png)

**Comment by freddydk** [comment]
How did you create the container?

**Comment by meilel** [comment]
> How did you create the container?

Via Docker run

**Comment by freddydk** [comment]
if you use new-navcontainer, it will automatically share a folder called c:\programdata\navcontainerhelper with the container.
When you use docker run but want to use the other functions of the containerhelper - you need to share that folder (something like -v c:\programdata\navcontainerhelper:c:\programdata\navcontainerhelper)
I recommend using new-navcontainer
