### ISSUE TITLE
“Network is unavailable” and “Session expired”

### ISSUE THREAD

**Issue by vasla** [Microsoft/navcontainerhelper#395]
I’m facing problem with future release image: random messages about “Network is unavailable” and “Session expired”. I report about it already in Yammer.

I've attached event log from navcontainer, last messages shows, that NAV service is crashed.
[navserver 2019-03-25 22.03.21.zip](https://github.com/Microsoft/navcontainerhelper/files/3005734/navserver.2019-03-25.22.03.21.zip)

You can reproduce it on clean azure VM:
1.	Create new Azure VM from template http://aka.ms/bcsandbox
2.	Specify image bcinsider.azurecr.io/bcsandbox-master (in my case platform version is 14.0.29478)
3.	Do not specify any license – using Cronus
4.	Wait until VM is initialized
5.	Start Web client
6.	Open My Company
7.	Goto Configuration packages
8.	Import predefined package W1.ENU.EVALUATION and apply it
9.	Open “Posted sales invoices” list
10.	Open First posted invoice Card
11.	Press “Goto next document of same type” button until you get error “Sorry, your session expired. Please refresh the page to continue.”

I get the error after 10-15 seconds.
Session really was closed, I can see it on “Session” table.

Also I get this message in other places and on long operations I got message “Network is unavailable”. For example, importing/appling configuration package, running tests.
Same behavior was also on earlier bcsandbox-master images, about two weeks ago. And not only on Azure VM, but also on local server.

**Comment by freddydk** [comment]
Try to unpublish the Microsoft Pay extension from the container - it looks like that extension is trying to communicate to an azure keyvault.

**Comment by freddydk** [comment]
This seems to be an IE related bug in the WebClient, unrelated to Docker.
I will make sure that Chrome is installed on all Azure VMs by default to mitigate this bug.

**Comment by freddydk** [comment]
I have discussed the issue with the Web Client guys and we found out that the docker images was missing a component (web-webSockets) - dependency was added to the webclient recently.
New generic images (0.0.9.3) has been created this morning and the latest of all docker images (bconprem + bcsandbox) is being rebuilt with this new generic image.
This should solve the IE problem.
When the container is starting - it displays the generic tag:

Version: 14.0.29537.29620-W1
Platform: 14.0.29530.29573
Generic Tag: 0.0.9.3
Container OS Version: 10.0.17763.379 (ltsc2019)
Host OS Version: 10.0.17763.379 (ltsc2019)
Using process isolation

Needs to be 0.0.9.3 or later.

**Comment by vasla** [comment]
Just installed container from image bcinsider.azurecr.io/bcsandbox:latest
Version: 14.0.29537.29654-W1
Platform: 14.0.29530.29573
Generic Tag: 0.0.9.3
On local windows server 2016

Web client working stable from IE and from Chrome.
Thank You!
