### ISSUE TITLE
Warning and error when create AAD

### ISSUE THREAD

**Issue by pebaume** [Microsoft/navcontainerhelper#398]
Hi, 

Run: aka.ms/getbc

Got the error:
9:21:46 AM The server "NAV" was unable to process the request. The application will close.

Tried then manual run SetupNavContainer.ps1
Got follow warning:
Creating Aad Apps for Office 365 integration
WARNING: MSG:UnableToDownload «https://oneget.org/nuget-2.8.5.208.package.swidtag» «»
WARNING: MSG:UnableToDownload «https://oneget.org/psl-1.0.0.210.package.swidtag» «»

And later in Script:
Importing Objects from c:\run\AzureAdAppSetup.fob (container path)
Objects successfully imported
The server "NAV" was unable to process the request. The application will close.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:9
+         Invoke-Command -Session $session -ScriptBlock $scriptblock -A ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (0:Int32) [Invoke-NAVCodeunit], FaultException`1
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/default,Microsoft.Dynamics.Nav.Management.Cmdlets.InvokeNavCodeunit
    + PSComputerName        : 2b261aa9751e8125be1b27746d2273a89aac8b420f62ac76e8ff33a39a981bb8

**Comment by pebaume** [comment]
https://www.oneget.org 
HTTP Error 503. The service is unavailable.

**Comment by freddydk** [comment]
Working on a fix - this is due to the invoke-navcodeunit not working in 13.4 or 14.0 business central containers.

**Comment by freddydk** [comment]
This should be fixed now - https://freddysblog.com/2019/03/27/navcontainerhelper-0-5-0-11/
