### ISSUE TITLE
[Run-TestInNavContainer] can -AzureDevOps error be written in stdErr ?

### ISSUE THREAD

**Issue by JulienDecottignies** [Microsoft/navcontainerhelper#402]
Hi,

In order to fail my pipeline task if one of my unit test fails, I added the "failOnStderr: true" into my yml file:
![image](https://user-images.githubusercontent.com/29598240/55229198-9a221e80-521c-11e9-968f-148b88df52ee.png)

The unit test is the one you gave in the helloworld project so there is a fail in it `Assert.AreEqual(2, 3)`

in the Run-Test.ps1 script:
At Run-TestInNavContainer, I set the -AzureDevOps parameter to "_error_".
`Run-TestsInNavContainer -containerName $containerName -XUnitResultFileName $TempTestResultFile -testSuite $testSuite -credential $credential -AzureDevOps error`

Doing that I was attempting the task to fail but it seems the _error_ is not written into the _stdErr_ as the task succeeded:
![image](https://user-images.githubusercontent.com/29598240/55229358-0dc42b80-521d-11e9-9179-5ebae9b40b65.png)

So I have no error in my Pipeline and the build succeeded.

I've tested by adding a Write-Error to force it:
![image](https://user-images.githubusercontent.com/29598240/55229801-4284b280-521e-11e9-8839-045bfa12a855.png)

And the task failed as expected:
![image](https://user-images.githubusercontent.com/29598240/55229822-5203fb80-521e-11e9-8ce4-781477656abf.png)

Is it possible to write the AzureDevops error into the stdErr in order to be able to use this with failOnStderr: true and fail the task ? Or this parameter has another purpose ?

Thanks

**Comment by freddydk** [comment]
If you specify 

failTaskOnFailedTests: true

in the Publish test results (not the test runner), then your pipeline will fail if you have failing tests.
I have included this in the template here: https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2FCI.yml (probably after you grabbed the sample)

**Comment by JulienDecottignies** [comment]
Hi Freddy,

Thanks for the solution :)
