### ISSUE TITLE
New-NAVContainer runs on error when image business central image is not W1

### ISSUE THREAD

**Issue by jeesus450** [Microsoft/navcontainerhelper#403]
When creating new container from non-W1 image it fails with multiple error messages:

Extracting Database Files
Downloading prerequisites
Downloading C:\ProgramData\NavContainerHelper\13.3.27233.0-de-Files\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading C:\ProgramData\NavContainerHelper\13.3.27233.0-de-Files\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading C:\ProgramData\NavContainerHelper\13.3.27233.0-de-Files\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Performing cleanup
Get-Item : Cannot find path 'C:\ProgramData\NavContainerHelper\13.3.27233.0-de-Files\databases\Cronusde Collation.txt' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Extract-FilesFromNavContainerImage.ps1:115 char:34
+ ...       Move-Item -Path (Get-Item "$path\databases\$Name\*.mdf").FullNa ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...e Collation.txt:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
 
The property 'FullName' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Extract-FilesFromNavContainerImage.ps1:115 char:17
+ ...             Move-Item -Path (Get-Item "$path\databases\$Name\*.mdf"). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
Get-Item : Cannot find path 'C:\ProgramData\NavContainerHelper\13.3.27233.0-de-Files\databases\Cronusde Collation.txt' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Extract-FilesFromNavContainerImage.ps1:116 char:34
+ ...       Move-Item -Path (Get-Item "$path\databases\$Name\*.ldf").FullNa ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\ProgramData\...e Collation.txt:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
 
The property 'FullName' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Extract-FilesFromNavContainerImage.ps1:116 char:17
+ ...             Move-Item -Path (Get-Item "$path\databases\$Name\*.ldf"). ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
 
Removing temp container
generic-1803: Pulling from microsoft/dynamics-nav
Using hyperv isolation
Creating container BC-DE-CU03-RC from image microsoft/dynamics-nav:generic-1803
1ff309b9cbeae3ca3a4862f26874605b35aa78e81a77cdfb2eef2526a64d481f
Waiting for container BC-DE-CU03-RC to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Copying Cronus database
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Copying Cronus database
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
Initialization of container BC-DE-CU03-RC failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.5.0.11\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...-CU03-RC failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC-DE-CU03-RC failed
###########################################################
After analyzing the issue I found out that database .MDF and .ldf files are in different folder thant in W1 image and that is not handled in Extract-FilesFromNAVContainerImage.ps1 script:

![image](https://user-images.githubusercontent.com/11912850/55333819-4f143f80-5498-11e9-84cd-472e9963d4d6.png)

I can reproduce this issue with mcr.microsoft.com/businesscentral/onprem:cu3-de-ltsc2016 image and with mcr.microsoft.com/businesscentral/onprem:dk-ltsc2016 image

**Comment by freddydk** [comment]
Easiest thing for you would be to upgrade to 1809 (october release of Windows 10) which will make it possible for you to use the 2019 images (which are much smaller and faster) in process isolation.
1803 (your windows version) is really the one we had most issues with.
Having said that, usebestcontaineros should create the file it is complaining about, but apparently there is a bug. I will investigate this, but it will probably not be before next week.

**Comment by freddydk** [comment]
Thanks for the info - I will still investigate why this happens - it should work and it is designed to help people who are running on OS versions with issues (which 1803 typically has).

**Comment by freddydk** [comment]
Included in 0.6.0.4
