### ISSUE TITLE
Run-TestsInNAVContainer: Other TestSuites than DEFAULT are not working

### ISSUE THREAD

**Issue by cmuris** [Microsoft/navcontainerhelper#404]
Hi,
I tried to run a custom TestSuite (not named DEFAULT) by using the param -testSuite in a CI build scenario, but no test inside the TestSuite was run nor any error came up that something is wrong. I believe the problem is with the Page 130409 that is imported during the runtime. The Page is set to Editable = false, which I guess leads to the script not being able to select the differing TestSuite Code. When I changed Editable to true the it runs the tests from custom TestSuite without any problems.

**Comment by freddydk** [comment]
Looks like you are right, I will update the page

**Comment by freddydk** [comment]
The page you download from http://aka.ms/pstesttoolpagefob has editable true.
I think i fixed this a while back (march 12th) - maybe you have a cached version?
Maybe try to delete the fob files in programdata\navcontainerhelper - and then retry?

**Comment by cmuris** [comment]
Ok, that's strange. I just ran Run-TestsInNavcontainer again with a newly created container for Business Central Spring Release (so no fob file existed before) and it still has a version of the page which has editable=no (Object Date is March 3rd). If I download the fob file from the link directly it is also the old version. I'm not sure what I can do differently especially when Powershell does the download in a newly created container? I will try to download the file directly from my personal laptop at home later, which has defintly never seen this file before

**Comment by freddydk** [comment]
Maybe you have a proxy or like, which keeps the file in a cache???

**Comment by cmuris** [comment]
I checked with our IT if we use something like that, but they claimed we don't. But to definetly rule that out I now created a new azure machine (western europe), installed docker and run the latest bconprem image. The page downloaded is the same that I get locally which has the editable=no. May be you could try the same or I could give you access to that machine if you like.

**Comment by freddydk** [comment]
Will try myself again

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: ChrisM <notifications@github.com>
Sendt: Thursday, April 4, 2019 9:50:10 AM
Til: Microsoft/navcontainerhelper
Cc: Freddy Kristiansen; Comment
Emne: Re: [Microsoft/navcontainerhelper] Run-TestsInNAVContainer: Other TestSuites than DEFAULT are not working (#404)


I checked with our IT if we use something like that, but they claimed we don't. But to definetly rule that out I now created a new azure machine (western europe), installed docker and run the latest bconprem image. The page downloaded is the same that I get locally which has the editable=no. May be you could try the same or I could give you access to that machine if you like.

**Comment by freddydk** [comment]
Not sure what went wrong on my machine - but you were right.
I have now fixed the fob.
Also in the next version of NavContainerHelper, the files will be part of the module and not downloaded.
