### ISSUE TITLE
The bc133\SQQLEXPRESS server cannot be found. Try again later or contact your system administrator

### ISSUE THREAD

**Issue by garynilsen** [Microsoft/navcontainerhelper#407]
So I spun up a new container using this command: New-NavContainer -containerName bc133 -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -imageName mcr.microsoft.com/businesscentral/onprem:13.3.27908.29339-na -includeCSide -navDvdCountry NA -updateHosts 

When I open up the CSID I get this error: The bc133\SQQLEXPRESS server cannot be found. Try again later or contact your system administrator.

It also won't allow me to open the windows client.  

Is there anything I need to do start up a service or start up a SQLExpress service?

Thanks,

Gary Nilsen

**Comment by freddydk** [comment]
Your command is fine - in fact, I copied it and ran the exact command on my machine - no problem.
These problems are typically because of operating system related issues, which are revealed if you copy paste the output of the command (version numbers, warnings, progress, everything)

**Comment by garynilsen** [comment]
Freddy, thank you so much.  Last night I noticed I was still on Windows 10 update 1803 so I upgraded to Window 10 update 1809 and now it is working.  Thank you.
