### ISSUE TITLE
Connection to External SQL Database

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#41]
Im having a local database running and try to connect the Docker-Navsion installation to this database/server. My question is what service account does the navision service run. And which parameters are essential when connection to a remote SQL-Server. 
My local SQL database is accessible when also using a local navsion installation.
I'm using the script showing below and I receive following Error.

Script: 

New-NavContainer -containerName $ContainerName `
                 -imageName $ImageName `
                 -licenseFile $Licensefile `
                 -Credential Admin `
                 -memoryLimit $MemoryLimit `
                 -auth $Auth `
                 -databaseServer $DatabaseServer `
                 -databaseInstance $DatabaseInstance `
                 -databaseName $DatabaseName `
                 -databaseCredential $DatabaseCredential `
                 -shortcuts $Shortcuts `
                 -includeCSide `
                 -updateHosts `
                 -accept_eula `
                 -doNotExportObjectsToText `
                 -myScripts $MyScripts

When running the script I have to add 2 passwords:

Windows PowerShell credential request
Enter your credentials.
Password for user Admin: **********
Windows PowerShell credential request
Enter your credentials.
Password for user SCHOUW\michel: ********

Error:

Initializing...
Hostname is DEVServer
PublicDnsName is DEVServer
Running Specific Image
Using NavUserPassword Authentication
Starting Internet Information Server
Using Database Connection VM-PD01/ [NAV_10_CU9_W1_Docker]
Modifying NAV Service Tier Config File for Docker
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 5010F89D5B742065E60EA8CFC5F1F991E60EB8D7
Modifying NAV Service Tier Config File with Instance Specific Settings
Start NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import NAV License
Microsoft Dynamics NAV Server is currently not ready to serve requests. Try again later, or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 51
at <ScriptBlock>, C:\Run\navstart.ps1: line 348
at <ScriptBlock>, C:\Run\start.ps1: line 18
at <ScriptBlock>, <No file>: line 1

TimeGenerated : 11/30/2017 1:11:58 PM
EntryType     : Error
Message       : Type: System.ServiceModel.FaultException`1[[Microsoft.Dynamics.
                Nav.Types.ServerFault, Microsoft.Dynamics.Nav.Types,
                Version=10.0.0.0, Culture=neutral,
                PublicKeyToken=31bf3856ad364e35]]
                Action: http://www.microsoft.com/Dynamics/NAV/51/ServerFault
                Message: <ii>Microsoft Dynamics NAV Server is currently not
                ready to serve requests. Try again later, or contact your
                system administrator.</ii>

[DBG]: [DBG]: PS C:\Users\michel\Foodware 365\Scripts\NAV Installation>
Initialization of container DEVServer failed
At C:\Program Files\WindowsPowerShell\Modules\NavContainerHelper\0.2.1.0\ContainerHandling\Wait-NavContainerReady.ps1:33 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...EVServer failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container DEVServer failed

TimeGenerated : 11/30/2017 1:11:58 PM
EntryType     : Error
Message       : Server instance: NAV
                <ii>Cannot establish a connection to the SQL Server/Database.

                This could be due to one of the following reasons:

                * SQL Server is not started.
                * The database does not exist.
                * Proper permissions have not been given to the NAV Server
                Account.

                Try again later or contact your system administrator.</ii>

**Comment by mheijkant** [comment]
I'm looking at your documentation reading following:

0.2.1.0
Added -databaseServer, -databaseInstance, -databaseName, -databaseCredential to new-navcontainer (Support for External SQL Server - generic tag 0.0.4.0 or later)

Also when running the script I read this output, "Generic Tag: 0.0.3.2". What does this mean and how to resolve this.

Creating Nav container DEVServer
Using image navdocker.azurecr.io/dynamics-nav:2017-cu9
Using license file C:\Users\michel\Foodware 365\Licenses\5164953 NAV2017.flf
NAV Version: 10.0.17972.0-W1
Generic Tag: 0.0.3.2
Removing container DEVServer
Removing Desktop Shortcuts for container DEVServer
Removing DEVServer from hosts
Successfully removed container DEVServer
Creating container DEVServer from image navdocker.azurecr.io/dynamics-nav:2017-cu9
Waiting for container DEVServer to be ready, this shouldn't take more than a few minutes
Time:          ½              1              ½              2
.................................................................................................................................................Error

**Comment by freddydk** [comment]
That means that the images with generic tag 0.0.4.0 are not published yet - they are being published as we speak, but it takes time.
Pull a new image in a few hours and it should work.

**Comment by mheijkant** [comment]
Thanks, the image with tag 0.0.4.0 seemed already available for 24 hours, But I overlooked the -alwaysPull parameter. Still I receive following error when debugging the New-NavContainer script, as showing below. I think these parameters are relevant to make a remote SQL connection. 
                 -databaseServer "VM-PD01"`
                 -databaseInstance "" `
                 -databaseName "NAV_10_CU9_W1_Docker" `
                 -databaseCredential "SCHOUW\michel" `

My SQL Server (default instance) that's running on VM-PD01 has de database installed and is accessible from a local installed navsion. I'm wondering if DNS-lookup works from insite the container if the navision service is looking for server "VM-PD01" or if I should use a sql-database login instead of a windows login or what service account is used for the nav service installation inside the container? 
I very much would like this to work. Thanks for any suggestions you can give.

message:

Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 63
at <ScriptBlock>, C:\Run\navstart.ps1: line 92
at <ScriptBlock>, C:\Run\start.ps1: line 38
at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
If you use -databaseCredential it needs to be a PSCredential object and yes, it needs to be database login.
If you want to use Windows login towards your database, you need to use gMSA and setup a service account in your AD.

**Comment by mheijkant** [comment]
Whatever I try, I keep getting the same error "Cannot establish a connection to the SQL Server/Database".
I've added the $parameters that's used to create the container. Can you please have a look at this. Perhaps you notice some mistake. Don't know why those double and triple quotationmarks?
![parameters](https://user-images.githubusercontent.com/30508071/33483413-05e6ca68-d69e-11e7-97f2-de7bcfcd3164.PNG)

**Comment by freddydk** [comment]
Could you open the container command prompt and see if you can ping the vm-pd01 from inside the container?

**Comment by mheijkant** [comment]
Used command "docker exec -it DEVServer cmd". 
But I could not ping VM-PD01 from inside the container.
But I could ping 10.0.3.111 (which is VM-PS01)

**Comment by freddydk** [comment]
so did you try to specify the ip number as your database server?

**Comment by mheijkant** [comment]
I tried this just now, with the same result. 
When I look in the Navision Service directory I can see the CustomSettings.config file is edited just now, but the settings still point to a SQL-Express Server installation. Hope I'm looking at the right place.

![customsettings](https://user-images.githubusercontent.com/30508071/33485652-7574cc0a-d6a7-11e7-974e-7578223c8768.PNG)
![dir](https://user-images.githubusercontent.com/30508071/33485653-758a0c8c-d6a7-11e7-8ed7-a16a060e72da.PNG)

**Comment by freddydk** [comment]
Could you send me an email with docker inspect of this container and docker logs to freddyk at microsoft dot com. Then lets take it direct and maybe have a quick skype call to find out what is wrong.

Thanks

**Comment by mheijkant** [comment]
I just did. Hope freddyk is correct in stead of freddydk.

**Comment by mheijkant** [comment]
Finally got a Navision connection to a remote SQL server. Started all over with a VM runnning Windows 2016 as you recommended. And also used a SQL-Developer Image. The problem we encountered with previous tries was the password that I used to connect to SQL. Instead of "michel1234" I now use "Michel1234" and added db_owner rights to the navision database  and master database. I was able to connect SMSS with "michel1234" but the Navision installation had a problem with this. Suppose some Security Policy was preventing this to work. Also returned to my previous WIN 10 VM (with 1709) but the sames issue kept occururing, so I'm abandoning working on a WIN10 VM. 

Remaining problem I have now is connection to the database. 
Connection CSide works but first defaults to Windows Authentication, that I can change to database auth.
Connection WebClient and Windows Client fail because "username ADMIN" or password is incorrect or you do not have a valid account in MS NAV.

**Comment by freddydk** [comment]
on CSide, you can launch cside with a parameter ntauthentication=0 (or something like that), you can also specify username on the cmdline.
On windows/web client - you will have to create the users in the database.

**Comment by mheijkant** [comment]
This also worked. thanks

**Comment by marknitek** [comment]
I'am experiencing the same issue. I already checked everything that was discussed here: 

- sql user has sysadmin rights, is db_owner on master & nav-db
- sql server is reachable from within the container (ping to host & ip works)
- tried connecting to sql server trough osql.exe (from inside container), works fine. 
- tried to set a complex password for sql user with upper case letters etc.

I'am on Win10 too. I would like to get this to work here before moving to Win Server Environment.  I don't see why this should only work on Win Server... (Considering that osql.exe can connect to the sql server without any issue)

This is my script:
`$sqlcreds = New-Object System.Management.Automation.PSCredential ( "sa", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force) )
$cred1 = New-Object System.Management.Automation.PSCredential ( "test", (ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force) )
New-NavContainer 
    -containerName test2018-NoDB 
    -imageName microsoft/dynamics-nav:2018-ch 
    -accept_eula  
    -includeCSide 
    -doNotExportObjectsToText 
    -licenseFile $licenseFile 
    -databaseServer 10.0.10.101 
    -databaseInstance NAVISION 
    -databaseName CronusCH 
    -databaseCredential $sqlcreds 
    -auth NavUserPassword 
    -Credential $cred1 
    -updateHosts 
    -useSSL:$false`

Any suggestions?

**Comment by freddydk** [comment]
What error do you get?
Is there anything in the eventlog? (Get-NavContainerEventlog will give you the eventlog from the container)

**Comment by marknitek** [comment]
I get the same error @mheijkant had:

Initializing...
Starting Container
Hostname is test2018-NoDB
PublicDnsName is test2018-NoDB
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Cannot establish a connection to the SQL Server/Database.

This could be due to one of the following reasons:

* SQL Server is not started.
* The database does not exist.
* Proper permissions have not been given to the NAV Server Account.

Try again later or contact your system administrator.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 105
at <ScriptBlock>, C:\Run\navstart.ps1: line 92
at <ScriptBlock>, C:\Run\start.ps1: line 102
at <ScriptBlock>, <No file>: line 1


TimeGenerated : 3/2/2018 3:16:29 PM
EntryType     : Warning
Message       : Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideException
                Remappable: True
                ErrorCode: 22924076
                ErrorNumber: 52012
                ModuleNumber: 93
                SuppressMessage: False
                DiagnosticsSuppress: False
                SuppressExceptionCreatedEvent: False
                FatalityScope: None
                Message:
                  <ii>Cannot establish a connection to the SQL Server/Database.
                  
                  This could be due to one of the following reasons:
                  
                  * SQL Server is not started.
                  * The database does not exist.
                  * Proper permissions have not been given to the NAV Server 
                Account.
                  
                  Try again later or contact your system administrator.</ii>
                StackTrace:
                     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnec
                tion(Int32 attemptCount)
                     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddS
                ystemTenant(String appDatabaseServerName, String 
                appDatabaseName, String appDatabaseUserName, 
                ProtectedDatabasePassword appDatabasePassword, Boolean 
                verifyConnection, String newEncryptionKey, 
                IDatabasePasswordPublicEncryptionKeyStorage keyStorage, 
                Boolean allowOverwritePublicKey, Boolean 
                verifyServerInstanceKey)
                     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncr
                yptionKey.HandleEncryptionKeyChangeInApplicationDatabase(String
                 newPublicKey)
                     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncr
                yptionKey.InternalProcessRecord()
                     at 
                Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
                Source: Microsoft.Dynamics.Nav.Ncl
                HResult: -2146233088

Event Log:

Type: Microsoft.Dynamics.Nav.Types.Exceptions.NavCSideException
Remappable: True
ErrorCode: 22924076
ErrorNumber: 52012
ModuleNumber: 93
SuppressMessage: False
DiagnosticsSuppress: False
SuppressExceptionCreatedEvent: False
FatalityScope: None
Message:
  <ii>Cannot establish a connection to the SQL Server/Database.
  
  This could be due to one of the following reasons:
  
  * SQL Server is not started.
  * The database does not exist.
  * Proper permissions have not been given to the NAV Server Account.
  
  Try again later or contact your system administrator.</ii>
StackTrace:
     at Microsoft.Dynamics.Nav.Runtime.NavDatabase.VerifyConnection(Int32 attemptCount)
     at Microsoft.Dynamics.Nav.Runtime.NavTenantCollection.AddSystemTenant(String appDatabaseServerName, String appDatabaseName, String appDatabaseUserName, ProtectedDatabasePassword appDatabasePassword, Boolean verifyConnection, String newEncryptionKey, IDatabasePasswordPublicEncryptionKeyStorage keyStorage, Boolean allowOverwritePublicKey, Boolean verifyServerInstanceKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.HandleEncryptionKeyChangeInApplicationDatabase(String newPublicKey)
     at Microsoft.Dynamics.Nav.Management.Cmdlets.ImportNavEncryptionKey.InternalProcessRecord()
     at Microsoft.Dynamics.Nav.Management.NavCommand.ProcessRecord()
Source: Microsoft.Dynamics.Nav.Ncl
HResult: -2146233088

**Comment by marknitek** [comment]
Ok so i found the Problem, there is an issue with the SetupDatabase.ps1 script.
I'am using a Named SQL Instance "NAVISION" but the Import-NAVEncryptionKey uses just the $databaseServer Variable for the **ApplicationDatabaseServer**

**Comment by freddydk** [comment]
Ok, I will fix this in the next version of the generic layer (combining is databaseinstance is not empty)
Thanks for your effort to find this - it saves me a lot of time.
