### ISSUE TITLE
Different system locales in containers created with the same image

### ISSUE THREAD

**Issue by mmenninghaus** [Microsoft/navcontainerhelper#410]
We are developing an Extension which exports and imports files. For testing, our containers must use the same codepage as the host system. Else, we get encoding problems.
On my local machine (Windows 10 Enterprise 1803) and an azure vm (Windows Server 2016 Datacenter 1607), with the same codepage 

```
Name  DisplayName      OEMCP  ACP
----  -----------      -----  ---
de-DE German (Germany)   850 1252
```

I start 
```
new-navcontainer -doNotExportObjectsToText -accept_eula -containerName test -imageName mcr.microsoft.com/businesscentral/onprem:de-ltsc2016
```

The codepage of the resulting container on the server is 850, but on my local machine it is:

```
Name  DisplayName             OEMCP  ACP
----  -----------             -----  ---
en-US English (United States)   437 1252

```

I am not able to figure out why. They use the very same image, and i get the same Business Central version with the expected language settings (german in both cases), but the codepage is still different.

**Comment by freddydk** [comment]
Any app exporting files today should not use code pages, but instead use Unicode. Business central is fully Unicode compliant and only for integration with ancient systems you would need codepages. You cannot rely on a code page in the online service.
I have had a few attempts to fix the code page issue and I don’t think it is possible.
This means that if you really need code page - it is only for on prem and you would have to use the dvds
Sorry

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: mmenninghaus <notifications@github.com>
Sendt: Thursday, April 4, 2019 4:33:16 PM
Til: Microsoft/navcontainerhelper
Cc: Subscribed
Emne: [Microsoft/navcontainerhelper] Different system locales in containers created with the same image (#410)


We are developing an Extension which exports and imports files. For testing, our containers must use the same codepage as the host system. Else, we get encoding problems.
On my local machine (Windows 10 Enterprise 1803) and an azure vm (Windows Server 2016 Datacenter 1607), with the same codepage

Name  DisplayName      OEMCP  ACP
----  -----------      -----  ---
de-DE German (Germany)   850 1252


I start

new-navcontainer -doNotExportObjectsToText -accept_eula -containerName test -imageName mcr.microsoft.com/businesscentral/onprem:de-ltsc2016


The codepage of the resulting container on the server is 850, but on my local machine it is:

Name  DisplayName             OEMCP  ACP
----  -----------             -----  ---
en-US English (United States)   437 1252



I am not able to figure out why. They use the very same image, and i get the same Business Central version with the expected language settings (german in both cases), but the codepage is still different.

**Comment by mmenninghaus** [comment]
Thank your for the very fast replay! As I feared - and yes, it is for Integration with ancient systems. At least, I do not have to search for an answer.

**Comment by freddydk** [comment]
Maybe you could internally in the function use Unicode and then convert back and forth from the necessary codepage - maybe in an azure function or using dotnet if possible.
https://stackoverflow.com/questions/12946974/c-sharp-encoding-convert-vs-c-multibytetowidechar shows how to do this in C#
