### ISSUE TITLE
Assign multiple user groups and/or roles to a container user.

### ISSUE THREAD

**Issue by FSharpCSharp** [Microsoft/navcontainerhelper#412]
We have the request to add new users within a container. So far you can only specify a single permission set when creating a new container user. This is a bit stupid in this case.

What we would need is either the possibility to assign several permission sets to one user, or to assign one user to groups and permission sets afterwards.

**Comment by freddydk** [comment]
Use

Invoke-ScriptInNavContainer -containername container -scriptblock {
   # Use the standard BC/NAV Cmdlets here
}

**Comment by freddydk** [comment]
Assuming that this solved the issue, I will close the issue.
