### ISSUE TITLE
Can't get Copy-CompanyInNavContainer to work!

### ISSUE THREAD

**Issue by tonryb** [Microsoft/navcontainerhelper#413]
Hi

When I invoke the function 'Copy-CompanyInNavContainer' I keep getting an error.

![image](https://user-images.githubusercontent.com/39899777/55829646-78c00d00-5b0f-11e9-8b5c-127c57e038dc.png)

Any ideas?

**Comment by freddydk** [comment]
Will be fixed in the next version

**Comment by tonryb** [comment]
Thank you. :-)

**Comment by tonryb** [comment]
Works like a charm! :-)

![image](https://user-images.githubusercontent.com/39899777/55938214-2e3baf00-5c3b-11e9-8d95-1b08f5bc32b3.png)
