### ISSUE TITLE
possible overflow with Windows logins >20 characters

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/navcontainerhelper#42]
Hi,

I have a script that, after Your latest fix, runs successfully on some Workstations but fails for one:

 ```
Creating container devprecontainer from image microsoft/dynamics-nav:devpreview
Waiting for container devprecontainer to be ready, this shouldn't take more than a few minutes
Time:          ½              1              ½              2
..................................Error
Initializing...
Starting Container
Hostname is devprecontainer
PublicDnsName is devprecontainer
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import NAV License
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user
Cannot validate argument on parameter 'Name'. The character length of the 21 argument is too long. Shorten the character length of the argument so it is fewer than or equ
al to "20" characters, and then try the command again.
at <ScriptBlock>, C:\Run\SetupWindowsUsers.ps1: line 11
at <ScriptBlock>, C:\Run\navstart.ps1: line 149
at <ScriptBlock>, C:\Run\start.ps1: line 38
at <ScriptBlock>, <No file>: line 1
Initialization of container devprecontainer failed
In <C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.1.2\ContainerHandling\Wait-NavContainerReady.ps1:33> Zeichen:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...ontainer failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container devprecontainer failed
``` 

Counting characters in my colleague's Windows login name: 21

So it seems there is an overflow that should not happen :-)

**Comment by freddydk** [comment]
What is the username of that person?
apparently new-localuser cannot accept names of more than 20 characters, I probably cannot do anything about that.

**Comment by RafaelKoch** [comment]
`GOB\Arndt Loermann`  which in AD should translate to `arndt.loermann@gob.de`
Really not a long name and no long company name too, so 1/3 of everybody cannot use Windows Logins.

**Comment by freddydk** [comment]
Well, you shouldn't have the domain name in the name you send to the container

**Comment by RafaelKoch** [comment]
Let's try that. Can I even influence that? This is what I do to grab the credentials:

```
New-NavContainer `
    -accept_eula `
    -containerName $containername `
    -imageName $NAV_DOCKER_IMAGE `
    -Credential (get-credential -credential $env:USERNAME) `
    -auth Windows `
    -memoryLimit 3G `
    -shortcuts Desktop `
    -alwaysPull `
    -includeCSide `
    -verbose `
    -licenseFile $LicenseFile `
    -doNotExportObjectsToText

```

**Comment by freddydk** [comment]
$cred = (get-credential -credential $env:USERNAME)
$cred.UserName

I don't get the domain name.
You can also remove the -credential parameter and say get-credential

**Comment by RafaelKoch** [comment]
I have some way to go yet in PowerShell it seems. Thanks for the Input. Now I Need to wait until my colleague can try again.

**Comment by RafaelKoch** [comment]
No luck, still does not work. 
Looking up <https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.localaccounts/new-localuser?view=powershell-5.1> I can see why You probably cannot do much about it, too. 
 
Looks like I will have to switch to Username/PW. I think this thread can be closed, maybe some day this restriction is lifted in a newer Version of PowerShell.

**Comment by freddydk** [comment]
If you take the following 5 lines and store them in a folder on your host (c:\temp)
if (($securePassword) -and $username -ne "") { 
    Write-Host "Creating Windows user $username"
    New-LocalUser -AccountNeverExpires -FullName $username -Name $username -Password $securePassword -ErrorAction Ignore | Out-Null
    Add-LocalGroupMember -Group administrators -Member $username -ErrorAction Ignore
}
and then start the new-navcontainer with -myscripts @("c:\temp\setupwindowsusers.ps1")
Is the domain name included there?

**Comment by RafaelKoch** [comment]
Where exactly do you expect this output to be? I ran it that way and see no additional info in the Output in my terminal or in the docker container log. So where do I need to look?

**Comment by freddydk** [comment]
docker logs : Creating Windows User <username>

**Comment by RafaelKoch** [comment]
just says: creating Windows user

**Comment by freddydk** [comment]
did you name the script setupwindowsusers.ps1 AND added it as -myscripts?

**Comment by RafaelKoch** [comment]
I named it differently and put it in another Folder and call it there. Does it matter?

**Comment by freddydk** [comment]
The name matters - putting a SetupWindowsUsers.ps1 in the my folder will override the SetupWindowsUsers from the run folder. If you name it differently, the runner won't know about it

**Comment by RafaelKoch** [comment]
Oh wait, got it. This is supposed to replace one of the base scripts... so naming matters a lot. Trying againg, sorry.

**Comment by RafaelKoch** [comment]
The domain name is not included in the output

**Comment by freddydk** [comment]
And your AD users doesn't have a Shortname?

**Comment by RafaelKoch** [comment]
It hasn't. (Also, it will eventually be replaced by Azure AD, so nobody will put effort into it any more) 
-> I am good now. Windows Authentication does not work and will not work so I use NavUserPassword which does.
Have a nice weekend and Keep up the good work :-)
