### ISSUE TITLE
Run-TestsInNavContainer -testCodeunit problem

### ISSUE THREAD

**Issue by ryancairnsy** [Microsoft/navcontainerhelper#420]
navcontainerhelper 0.6.0.2

I have a test codeunit 96002 generated as part of an extension. When I run

`Run-TestsInNavContainer -containerName $container -Credential $credential -detailed -testCodeunit 96002  -XUnitResultFileName "c:\ProgramData\NavContainerHelper\Extensions\$containername\results.xml"`

I don't get any output and after a couple of minutes an empty results file is generated (standard test codeunit IDs work fine)

If I add my test codeunit to a suite and specify the -testSuite parameter instead this works fine

**Comment by freddydk** [comment]
The testSuite is a global filter and Run-TestsInNavContainer per default runs the tests in the DEFAULT test suite, so even though you specify a codeunit id - you must also specify the test suite.
Could this be the reason?

**Comment by ryancairnsy** [comment]
Yes this makes sense! My test wasn't in the DEFAULT suite. So if I want to spin up a container, publish my app and run the test I will need to write and invoke a codeunit first to  create a suite add the test to a suite?

**Comment by ryancairnsy** [comment]
Actually I have just checked and you have updated https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld
since I last cloned it in early Feb! So I think I have everything I need thanks :)

**Comment by freddydk** [comment]
Yes, the idea is, that the test app will register its tests in an install codeunit (sample in the helloworld test app). You decide the test suite, and then you can run them without having to ever know codeunit ids or like in the CI script.
BTW - I am working on a v2 of the helloworld template (with the learnings from v1 and v1½:-))

**Comment by ryancairnsy** [comment]
Version 2! Fantastic - everything is moving so fast I am still getting to grips with version 1 and 1.5! :-) I look forward to this!
