### ISSUE TITLE
Run-TestsInNavContainer - test failing, when running through client - succeeded

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#428]
Hi,
I have now situation, where tests, triggered through Run-TestsInNavContainer are failing (3 of 12). If I run same test suite through web client, all are green.

Two errors are about "record... already exists"...
It leads me to one thing: how are the tests started? Isn't there some parallelism? Seems like it run both codeunits in the testsuite in parallel, not in serial like when started directly from UI.

**Comment by freddydk** [comment]
Run-TestsInNavContainer is running the tests through the UI - it is emulating a client and pressing the button one by one. In fact, if you run it with -detailed you will see the result for every test before the next is started.
What BC version is this?

**Comment by kine** [comment]
I am running it with -detailed...
Version: Platform 14.0.29530.29573 + Application 29654 (W1 14.0)

But thanks, the detail I needed is "pressing the button one by one". This is the difference. Running one by one is doing separate transaction per test, but running from UI with "run all" (which is default I am using when doing it manually) is doing transaction per codeunit (based on the isolation level of the test codeunit). There was dependency in my test making one to fail when running separately...

**Comment by richardrobberse** [comment]
Does "pressing the button" mean that each test function (not test codeunit) is executed separately, in a separate transaction?

**Comment by freddydk** [comment]
Thanks, sounds like I will have to refactor the method to run the codeunits unless you specify a specific testfunction.

**Comment by freddydk** [comment]
Looking at the code - that is how it should work. If you do not specify testFunction - it should run selected on each codeunit.

**Comment by freddydk** [comment]
@kine - do you specify testFunction?

**Comment by richardrobberse** [comment]
That's great, then I have no complaints at all :)

**Comment by freddydk** [comment]
This image:
![image](https://user-images.githubusercontent.com/10775043/56563771-d4c56f80-65ac-11e9-87a0-b1e92cbd10c9.png)
Shows that normally - the codeunits are run (-detailed just displays the functions as well) - if you specify -testFunction - the individual functions are run.
@kine - should we do a screen share session to investigate your issue?

**Comment by kine** [comment]
During the screen share session we found out that the problem was in my case that the powershell function is connecting to first company available, not the one set for the user, thus the tests were failing because existing data in demo company, but manually tested in empty company. 

There is no CompanyName parameter to run the powershell script for specific company or it should take the one set for the user, like when opening the client in standard way. Or both (if not specified, use the default one).

**Comment by freddydk** [comment]
This is actually caused by Windows Authentication - with NavUserPassword it worked exactly as you expected.
The problem with Windows Authentication is, that the powershell session is running inside the container and in order to make that work, I have to create another Windows Auth user (containeradministrator) and use that for the connection - I haven't found other ways of doing that.
I have fixed this by adding the CompanyName parameter and grabbing the company from the original Windows User if you didn't specify CompanyName.
If you specify CompanyName - it always takes precedence.

I do recommend using NavUserPassword for CI/CD scenarios:-)

**Comment by freddydk** [comment]
Included in 0.6.0.10
