### ISSUE TITLE
Error in Export-ModifiedAsDeltas

### ISSUE THREAD

**Issue by stryzhak** [Microsoft/navcontainerhelper#432]
Hi,

Using Export-ModifiedObjectsAsDeltas with parameter useNewSyntax lead to error  
![image](https://user-images.githubusercontent.com/29860849/56638784-afe9fe80-6677-11e9-96b5-5780368ff122.png)

navcontainerhelper 0.6.0.9 
container : dynamicsnav:2018-rtm-w1-ltsc2019

I found that issue lay down inside function Create-MyDeltaFolder 
```
$params = @{}
if ($useNewSyntax) {
    $params += @{ 'ExportToNewSyntax' = $true }
}
Compare-NAVApplicationObject @params -OriginalPath $myOriginalFolder -ModifiedPath $modifiedFolder -DeltaPath $myDeltaFolder | Out-Null
```

Since Compare-NAVApplicationObject for that version doesn't have that parameter process will interrupt every time.

**Comment by freddydk** [comment]
Correct, if the cmdlet in the container doesn't support useNewSyntax - you cannot use new syntax.
This is the reason for the function being built as is (if you do not specify the parameter, it isn't transferred).
Grab a newer version NAV or Business Central.
