### ISSUE TITLE
Getting error while creating container with NAVUserPassowrd

### ISSUE THREAD

**Issue by ashikivor** [Microsoft/navcontainerhelper#434]
Today I pulled the latest image and created container which was giving me an error when I was using NAVUserPassword.

I tried changing the password also, still the same error.

Image : mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
navcontainerhelper version 0.6.0.9

![image](https://user-images.githubusercontent.com/28855499/56660956-480ad680-66be-11e9-8cea-2d9a5e719e39.png)

But the Windows Authentication is working fine.

**Comment by freddydk** [comment]
If you set the password to something like P@ssword1 - then it works.
But this was an unintended complexity, which will be removed right away.

**Comment by NAVspecialist** [comment]
> But the Windows Authentication is working fine.

Yeah, but at least you know what is wrong... I clearly tells you what it is...

**Comment by freddydk** [comment]
It might also be the username 123 which is illegal.

**Comment by ashikivor** [comment]
P@ssword1 worked like a charm :) 

I tried username like demo, test also.
