### ISSUE TITLE
Backup and Restore a container

### ISSUE THREAD

**Issue by andrecavalcanti** [Microsoft/navcontainerhelper#435]
Is there any way I could back up and restore a container?

I have a container NAV 2018 CU8 NA with Windows Auth. I had to modify some objects and installed some apps which I created myself. 

Now I have to clean the docker because there is no more space on the disk.

**Comment by freddydk** [comment]
https://freddysblog.com/2019/04/12/placing-the-database-on-the-host/

explains how you can stop the container - copy the .mdf + .ldf to the host and place them in a folder under c:\programdata\navcontainerhelper - and then use these database files - if that is useful.

**Comment by andrecavalcanti** [comment]
That is what I was after. Thanks.

**Comment by freddydk** [comment]
Gr8 - good luck
