### ISSUE TITLE
Connect to BCInsider build CSIDE

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/navcontainerhelper#438]
Greetings - 

I used http://aka.ms/getbc to create an Azure VM with BC installed.  All good - i can open the "navserver CSIDE" shortcut to open the database using my azure VM admin user / password.  I then ran the script below to pull the latest BC Insider build.  This created a "bcsandbox CSIDE" shortcut, but i can't connect to the database - my admin credentials do not work.  I tried using Windows authentication as a parameter as well but that still wouldn't open the database...so i'm not sure how to connect to it?

$securePassword = ConvertTo-SecureString -String "bc#R9bcED1" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "admin", $securePassword
docker login "bcinsider.azurecr.io" -u "<Removed>" -p "<Removed>"
New-NavContainer `
    -accept_eula `
    -alwaysPull `
    -imageName "bcinsider.azurecr.io/bcsandbox:us" `
    -containerName "bcsandbox" `
    -Credential $credential `
    -memoryLimit 3G `
    -isolation hyperv `
    -updateHosts `
    -shortcuts Desktop `
    -includeCSide `
    -assignPremiumPlan `
    -auth NavUserPassword `
    -enableSymbolLoading `
    -includeTestToolkit `
    -doNotExportObjectsToText `
    -licenseFile "C:\Download\Epimatic.flf"

**Comment by freddydk** [comment]
Could you share the output of the new-navcontainer command?

**Comment by RHansenEpimatic** [comment]
Sure thing - here it is.

Login Succeeded
NavContainerHelper is version 0.6.0.11
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.4
Docker Server Version is 18.09.4
Pulling image bcinsider.azurecr.io/bcsandbox:us-ltsc2019
us-ltsc2019: Pulling from bcsandbox
Digest: sha256:4ede13ebf41fb3b821bb86c4e9fe00a34bf57b5d0b9e248c733211bd4acd2b47
Status: Image is up to date for bcinsider.azurecr.io/bcsandbox:us-ltsc2019
Using image bcinsider.azurecr.io/bcsandbox:us-ltsc2019
Removing container bcsandbox
Removing bcsandbox from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bcsandbox
Creating Nav container bcsandbox
Using license file C:\Download\Epimatic.flf
Version: 14.1.31718.0-US
Platform: 14.0.31670.0
Generic Tag: 0.0.9.5
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using hyperv isolation
Creating container bcsandbox from image bcinsider.azurecr.io/bcsandbox:us-ltsc2019
f9392fa3c3750147b3c7860d1ce95448e4d212f859f72c60ac97dce76a14dbe1
Waiting for container bcsandbox to be ready
Initializing...
Starting Container
Hostname is bcsandbox
PublicDnsName is bcsandbox
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 8F64D967D090FC7ACE4C62673518C5B74E2A7FB3
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Assign Premium plan for ADMIN
Container IP Address: 172.31.187.235
Container Hostname  : bcsandbox
Container Dns Name  : bcsandbox
Web Client          : http://bcsandbox/NAV/
Dev. Server         : http://bcsandbox
Dev. ServerInstance : NAV

Files:
http://bcsandbox:8080/al-3.0.118998.vsix

Initialization took 297 seconds
Ready for connections!
Reading CustomSettings.config from bcsandbox
Creating Desktop Shortcuts for bcsandbox
Importing Objects from C:\TestToolKit\CALTestCodeunits.US.fob (container path)
Importing Objects from C:\TestToolKit\CALTestLibraries.US.fob (container path)
TestToolkit successfully imported
Nav container bcsandbox successfully created

**Comment by freddydk** [comment]
If you open the bcsandbox web client (shortcut on the desktop) and login as admin / bc#R9bcED1 - doesn't that work?

**Comment by RHansenEpimatic** [comment]
Jeez...sorry.  It does.  I didn't notice that the script was specifying that password...i'm a rookie with this stuff and learning some of the new world tools after 20 years with NAV.  Sorry Freddy - thanks very much!
