### ISSUE TITLE
Import-ObjectsToNAVContainer

### ISSUE THREAD

**Issue by GreatScott000** [Microsoft/navcontainerhelper#439]
Continuing my question posted here: [Developing Business Central Extensions (part 2) – Repository/Environment](http://freddysblog.com/2018/11/12/developing-business-central-extensions-part-2/)

and your response:
> If your container is started with -enableSymbolLoading, then the Import-Objects above should rebuild the symbols for these objects.
> If this doesn’t happen, you might be able to just call compile-objectsinNavContainer with a filter identifying the objects you need to rebuild symbols for (you still need enablesymbolloading)
> 

I am using the Local-Sandbox.ps1 script from your Helloworld repository.  It calls `Create-Container.ps1`.  This script is unmodified and does contain the `-enableSymbolLoading` switch.
```
New-NavContainer @parameters `
                 -containerName $containerName `
                 -imageName $imageversion.containerImage `
                 -auth NAVUserPassword `
                 -Credential $credential `
                 -alwaysPull:$imageversion.alwaysPull `
                 -updateHosts `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -enableSymbolLoading ` <<<<<----------------------
                 -useBestContainerOS `
                 -shortcuts $shortcuts `
                 -licenseFile "$licenseFile" `
                 -additionalParameters $additionalParameters `
                 -myScripts $myscripts

```

**Comment by GreatScott000** [comment]
I have added the `Compile-ObjectsInNavContainer` command and that appears to resolve the issue without needing to regenerate the symbols.

I don't understand what the original problem was as it should have happened correctly from the start.

**Comment by freddydk** [comment]
Compile-Objects will regenerate symbols for the objects you compile.
I think it should happen during import as well - not sure why it doesn't.

**Comment by freddydk** [comment]
Also, please remember that the template project is a work in progress and ment to be a starting point for people to setup their CI/CD - it isn't something that is cast in cement and works for all.

Thanks
