### ISSUE TITLE
New-NavContainer will not pull spring release container and uses older release

### ISSUE THREAD

**Issue by kevindstanley1988** [Microsoft/navcontainerhelper#442]
I am trying to get the spring release of business central. I run the command New-NavContainer with mcr.microsoft.com/businesscentral/onprem:na as my image, you can see in the output below however it is pulling and using Version: 13.2.26556.0-na Platform: 13.0.26413.0. Is there any particular reason for this? I have run this exact same command on a different server and have had it pull the latest spring release. 

PS C:\WINDOWS\system32> New-NavContainer -accept_eula -accept_outdated -containerName bcspring -imageName "mcr.microsoft.com/businesscentral/onprem:na" -licenseFile "C:\ProgramData\NavContainerHelper\license\WG_BusinessCentral 20181212.flf" -shortcuts Desktop -includeCSide -enableSymbolLoading -useBestContainerOS -updateHosts -auth NavUserPassword 
NavContainerHelper is version 0.6.0.14
Host is Microsoft Windows 10 Pro - 1803
Docker Client Version is 18.09.0
Docker Server Version is 18.09.0
Using image mcr.microsoft.com/businesscentral/onprem:na-ltsc2016
Creating Nav container bcspring
Using license file C:\ProgramData\NavContainerHelper\license\WG_BusinessCentral 20181212.flf
Version: 13.2.26556.0-na
Platform: 13.0.26413.0
Generic Tag: 0.0.9.0
Container OS Version: 10.0.14393.2665 (ltsc2016)
Host OS Version: 10.0.17134.706 (1803)
A better Generic Container OS exists for your host (1803)
generic-1803: Pulling from microsoft/dynamics-nav
Digest: sha256:6772d993c627d4bf556d29235ec46af0fabebb787d7a35ae04ba3a586f6f619c
Using hyperv isolation
Creating container bcspring from image microsoft/dynamics-nav:generic-1803
51573e40021972984a1eb18ec7e69b3829f783da891afd8b712009f7ad33b6de
Waiting for container bcspring to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 197 seconds
Installation complete
Initializing...
Starting Container
Hostname is bcspring
PublicDnsName is bcspring
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 3CE0165209DBCAF79F6DE425EADF106982F7C1BA
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating kevin as SQL User and add to sysadmin
Creating SUPER user
Registering event sources
Container IP Address: 172.29.23.60
Container Hostname  : bcspring
Container Dns Name  : bcspring
Web Client          : http://bcspring/NAV/
Dev. Server         : http://bcspring
Dev. ServerInstance : NAV

Files:
http://bcspring:8080/al-2.1.69331.vsix

Initialization took 168 seconds
Ready for connections!
Reading CustomSettings.config from bcspring
Creating Desktop Shortcuts for bcspring
Nav container bcspring successfully created

**Comment by freddydk** [comment]
If you have that an image by that name from earlier - then new-navcontainer is not going to pull the image unless you specify -alwaysPull

I assume that fixes your issue.

**Comment by kevindstanley1988** [comment]
That worked, -alwaysPull fixed the problem. I must have run a BC docker on this computer previously. Thanks!
