### ISSUE TITLE
Error pulling bcinsider build

### ISSUE THREAD

**Issue by RHansenEpimatic** [Microsoft/navcontainerhelper#443]
Today I'm trying to use the script pasted below to pull the latest bcinsider build.  It has worked in the past.  Today it is erroring out...I'm pasting the output below as well.

$securePassword = ConvertTo-SecureString -String "DynamicsPath1!" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "admin", $securePassword
docker login "bcinsider.azurecr.io" -u "<removed>" -p "<removed>"
New-NavContainer `
    -accept_eula `
    -alwaysPull `
    -imageName "bcinsider.azurecr.io/bcsandbox:us" `
    -containerName "bcsandbox" `
    -Credential $credential `
    -memoryLimit 3G `
    -isolation hyperv `
    -updateHosts `
    -shortcuts Desktop `
    -includeCSide `
    -assignPremiumPlan `
    -auth NavUserPassword `
    -enableSymbolLoading `
    -includeTestToolkit `
    -doNotExportObjectsToText `
    -licenseFile "C:\Download\Epimatic.flf"

Login Succeeded
NavContainerHelper is version 0.6.0.11
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.4
Docker Server Version is 18.09.4
Pulling image bcinsider.azurecr.io/bcsandbox:us-ltsc2019
us-ltsc2019: Pulling from bcsandbox
Digest: sha256:983d8930a56eeab64a838f0a13635eecf2aeb56010f377c6c028ca1a70a1ae32
Status: Image is up to date for bcinsider.azurecr.io/bcsandbox:us-ltsc2019
Using image bcinsider.azurecr.io/bcsandbox:us-ltsc2019
Removing container bcsandbox
Removing bcsandbox from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bcsandbox
Creating Nav container bcsandbox
Using license file C:\Download\Epimatic.flf
Version: 14.1.31955.0-US
Platform: 14.0.31907.0
Generic Tag: 0.0.9.6
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.437 (ltsc2019)
Using hyperv isolation
Creating container bcsandbox from image bcinsider.azurecr.io/bcsandbox:us-ltsc2019
9a5cfb86fc2a76d1f9f8d52b08e903f9624c9a3f870a5cae6e3cd7a7d4e72c83
Waiting for container bcsandbox to be ready
Initializing...
Starting Container
Hostname is bcsandbox
PublicDnsName is bcsandbox
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint BAD877364F180042C0B4C7B84DDA0B11C2BC04EC
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Assign Premium plan for ADMIN
Container IP Address: 172.29.51.184
Container Hostname  : bcsandbox
Container Dns Name  : bcsandbox
Web Client          : http://bcsandbox/NAV/
Dev. Server         : http://bcsandbox
Dev. ServerInstance : NAV

Files:
http://bcsandbox:8080/al-3.0.124247.vsix

Initialization took 264 seconds
Ready for connections!
Reading CustomSettings.config from bcsandbox
Creating Desktop Shortcuts for bcsandbox
Importing Objects from C:\TestToolKit\CALTestCodeunits.US.fob (container path)
!
at Import-NAVApplicationObject<Process>, C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 147
at <ScriptBlock>, <No file>: line 35
at <ScriptBlock>, <No file>: line 22
!
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.11\ContainerHandling\Invoke-ScriptInNavContainer.ps1:31 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-NAVApplicationObject
    + PSComputerName        : 9a5cfb86fc2a76d1f9f8d52b08e903f9624c9a3f870a5cae6e3cd7a7d4e72c83

**Comment by RHansenEpimatic** [comment]
I just tried this again and it worked...but i didn't get a bcsandbox CSIDE shortcut?

**Comment by freddydk** [comment]
I ran your exact powershell command (except for the license of course) and it works fine.
Maybe disk space or other things locally?
maybe do a docker cleanup if strange problems persists - the script works and the container works.

**Comment by RHansenEpimatic** [comment]
Thanks Freddy.  Earlier i tried three times and got the error each time.  I tried again now and it worked fine...very strange...all on the same machine with 100GB free on the primary drive.
