### ISSUE TITLE
  it does not work when i open web client

### ISSUE THREAD

**Issue by eat110** [microsoft/navcontainerhelper#446]
i found the js file is not exist when i sign in.
http://bchk/NAV/Resources/Lang/zh-CN/Microsoft.Dynamics.Framework.Resource.js?pv=14.0.29530.31886&_v=14.0.29530.31886
net::ERR_ABORTED 404 (Not Found)
![1557416279(1)](https://user-images.githubusercontent.com/28883324/57467261-c8335d80-72b4-11e9-86ba-2e569773d6f7.jpg)

**Comment by freddydk** [comment]
You probably need to describe exactly how you created the container (incl. output) if you want anybody to help you.

**Comment by eat110** [comment]
New-NavContainer -ACCEPT_OUTDATED -accept_eula -containerName "bchk" -updateHosts -useBestContainerOS -auth NavUserPassword -doNotExportObjectsToText -includeCSide -includeTestToolkit -licenseFile "D:\abc.flf" -imageName mcr.microsoft.com/businesscentral/sandbox:hk-ltsc2019

docker inspect bchk
PS C:\Windows\system32> docker inspect bchk
[
    {
        "Id": "909eecb1185b235483a5a11e0c5da91cdff3bb9f386a04e58f068de4c431f970",
        "Created": "2019-05-09T15:13:39.9822587Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 11652,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-05-09T16:15:33.5545162Z",
            "FinishedAt": "2019-05-10T00:14:19.7479688+08:00",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2019-05-10T09:54:11.3763631+08:00",
                        "End": "2019-05-10T09:54:13.2703767+08:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-05-10T09:54:43.2930857+08:00",
                        "End": "2019-05-10T09:54:45.2800759+08:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-05-10T09:55:15.3027713+08:00",
                        "End": "2019-05-10T09:55:17.2214464+08:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-05-10T09:55:47.2410925+08:00",
                        "End": "2019-05-10T09:55:49.3926402+08:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-05-10T09:56:19.4327134+08:00",
                        "End": "2019-05-10T09:56:21.1823814+08:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:7a5ff7085a74487fc7811a4ad94a107f994a2b3a6a1b32dbe300dafcc2d01019",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "D:\\ProgramData\\Docker\\containers\\909eecb1185b235483a5a11e0c5da91cdff3bb9f386a04e58f068de4c431f970\\909eecb1185
b235483a5a11e0c5da91cdff3bb9f386a04e58f068de4c431f970-json.log",
        "Name": "/bchk",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\bchk\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\bchk\\Program Files:C:\\navpfiles"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "D:\\ProgramData\\Docker\\windowsfilter\\909eecb1185b235483a5a11e0c5da91cdff3bb9f386a04e58f068de4c431f970"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bchk\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bchk\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "bchk",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "accept_outdated=Y",
                "licenseFile=c:\\run\\my\\license.flf",
                "removePasswordKeyFile=Y",
                "enableApiServices=Y",
                "ExitOnError=N",
                "databaseServer=",
                "databaseInstance=",
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AHEAMwBJAE0ARQBlAEgAYQB4ADQAYQB5AGQAawBIAEgAMwBEADYAVQBnAGcAPQA9AH
wAYgA0ADcAOAA2AGQAYgA3ADgAZQBlAGYAMAA1AGIAZQBmAGUANABmADEAZAA5ADgANgA1AGQAZgBhADAAZABmADUAMABiAGMAOQA5AGQAYwA4ADUANgBjADYAYgA4AGUANwA3
ADkANQA2AGEAMQAyADAAZgAwADcANAA3AGEAOQA=",
                "accept_eula=Y",
                "auth=NavUserPassword",
                "locale=en-US",
                "username=bchk",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "DatabaseName=FinancialsHK",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/9943db87-021e-4f8e-8f0b-b4c74de27a91",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-3.0.106655.vsix",
                "IsBcSandbox=Y",
                "CountryCode=HK",
                "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/21d85aa6-39e2-4ec3-adb4-0c09f676b5f3"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "mcr.microsoft.com/businesscentral/sandbox:hk-ltsc2019",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "HK",
                "created": "201905021108",
                "cu": "",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.17763.437",
                "platform": "14.0.29530.31886",
                "tag": "0.0.9.6",
                "version": "14.0.29537.31961"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "909eecb1185b235483a5a11e0c5da91cdff3bb9f386a04e58f068de4c431f970",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "909eecb1185b235483a5a11e0c5da91cdff3bb9f386a04e58f068de4c431f970",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "31547aec593d5d5fd55baf2a0c83a84491318e4164cb50c7e2a9571214de4bcf",
                    "EndpointID": "73ea94ed3b344bb798f545a4080b32ff22fdc47acbbe1e36d38cc3752f1af5f5",
                    "Gateway": "172.18.160.1",
                    "IPAddress": "172.18.175.243",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:9b:c0:46",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by freddydk** [comment]
It is really the output from new-navcontainer which gives most information about what happens when the container starts.

**Comment by eat110** [comment]
PS C:\Windows\system32> New-NavContainer -ACCEPT_OUTDATED -accept_eula -containerName "bchk" -updateHosts -useBestContainerOS -auth NavUserPassword -doNotExportObjectsToText -includeCSide -includeTestToolkit -licenseFile "D:\NavLicense\123.flf" -imageName mcr.microsoft.com/businesscentral/sandbox:hk-ltsc2019
NavContainerHelper is version 0.6.0.15
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image mcr.microsoft.com/businesscentral/sandbox:hk-ltsc2019
Removing container bchk
Removing bchk from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bchk
Creating Nav container bchk
Using license file D:\NavLicense\Tectura HK - D365 Business Central OP Demo License - 2018.10.16.flf
Version: 14.0.29537.31961-HK
Platform: 14.0.29530.31886
Generic Tag: 0.0.9.6
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.475 (ltsc2019)
Using process isolation
Creating container bchk from image mcr.microsoft.com/businesscentral/sandbox:hk-ltsc2019
666906f1566e50fbbe79a69be23d4b8df6e307f6a1771cf47580907a5a6b3933
Waiting for container bchk to be ready
Initializing...
Starting Container
Hostname is bchk
PublicDnsName is bchk
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 054ECB2BBB51A00606270880D7EE4FCCC50074FB
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating bchk as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.18.165.18
Container Hostname  : bchk
Container Dns Name  : bchk
Web Client          : http://bchk/NAV/
Dev. Server         : http://bchk
Dev. ServerInstance : NAV

Files:
http://bchk:8080/al-3.0.106655.vsix

Initialization took 118 seconds
Ready for connections!
Reading CustomSettings.config from bchk
Creating Desktop Shortcuts for bchk
Importing Objects from C:\TestToolKit\CALTestCodeunits.W1.fob (container path)
Importing Objects from C:\TestToolKit\CALTestLibraries.W1.fob (container path)
Importing Objects from C:\TestToolKit\CALTestRunner.fob (container path)
TestToolkit successfully imported
Nav container bchk successfully created

**Comment by eat110** [comment]
RTC Is Work Well.

**Comment by freddydk** [comment]
It looks like it is looking for zh-CN (Chinese, Simplified, PRC)
That language doesn't seem to be available - zh-HK is.
How did you set the language - when I open my settings - I only have these languages available:
![image](https://user-images.githubusercontent.com/10775043/57565333-652cee00-73bc-11e9-8317-0deedd5b50f5.png)

**Comment by eat110** [comment]
Yes.it is looking for zh-CN (Chinese, Simplified, PRC).
But I have set the region of my pc to en-US.
it does not work still.
and It work well if I install it locally without using a container.
So I want to know how to get the language when creating a new container.

**Comment by freddydk** [comment]
So you say that if you install the DVD, then everything works.
I didn't think we ship sandbox versions as DVD.
Which DVD is that? Where did you get that?

Back to the container.
This has nothing to do with the container - it works fine on my machine.
The first time you connect to the Web Client, I think it grabs the language from the browser.
Which browser are you using.
You should change the language settings in your browser to en-us, create a new container and try again.

**Comment by eat110** [comment]
i installed the bc version was Dynamics.365.BC.Spring2019.29537.W1.DVD.
I also Got the same problem before I changed the Region.
yes. I had change the language settings in my browser to en-us and  create a new container.
but it does not work still.
Is there any way to view the internal folder structure of the container?
i want copy the js file to the container.
I tried to find the file path but always prompted that the path does not exist。

**Comment by freddydk** [comment]
After you have used New-NavContainer you have two shortcuts on the desktop to open a powershell prompt or a cmd prompt inside the container filesystem.
You can also use Invoke-ScriptInNavContainer to run a script inside the container and potentially copy the file automatically.
I have tried to repro here - but everything works on my machine, so my assumption is, that something is different on your machine.

**Comment by eat110** [comment]
Thank you for your reply.

**Comment by eat110** [comment]
I Copy the js file to the container folder zh-CN.
Now It is Work well.
Thank You.
