### ISSUE TITLE
Publish-NavContainerApp failes because of warnings

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#447]
Freddy,

I publish the spring release as an bigapp as shown in Kopenhagen with Redcarpet.
the compile of this bigapp goes fine, alot of warnings but MS already told us that there where around 800 warnings for now...

but when i publish it fails 
![image](https://user-images.githubusercontent.com/48794854/57467615-20ea0280-7283-11e9-9f83-8f93098291f1.png)

![image](https://user-images.githubusercontent.com/48794854/57467636-2e06f180-7283-11e9-827b-248a04dfd910.png)

![image](https://user-images.githubusercontent.com/48794854/57467664-3d863a80-7283-11e9-8e84-acf66c984f1c.png)

do you know how to ignore warnings during Publish? in the end we want to fix the warnings, but standard BC warnings must be fixed by MS themselfs.

**Comment by freddydk** [comment]
It shouldn't fail due to warnings - and the warnings are some that MS will fix.
Search the output for ": err" and you will probably find an error.
If you find the error and need help to resolve if, you will need to explain the steps done before and how you try to publish.

**Comment by freddydk** [comment]
Did you make this work - or did you find the errors blocking the publish?

**Comment by hvandenborn** [comment]
You are right,

found:
: error AL0451: An assembly named 'Microsoft.Dynamics.Nav.Client.CodeViewer, PublicKeyToken=null' could not be found in the assembly probing paths 'C:\Program Files\Microsoft Dynamics NAV\140\Service\Add-Ins, C:\Windows\TEMP\Microsoft Dynamics NAV\Add-Ins\14.0.31606.0, C:\Program Files\Microsoft Dynamics NAV\140\Service\, C:\Windows\Microsoft.NET\assembly\'

: error AL0417: Control add-in '"Microsoft.Dynamics.Nav.Client.CodeViewer"' not found

**Comment by hvandenborn** [comment]
Freddy,

It fixed the problem, only i have another question maby you know the answer.

![image](https://user-images.githubusercontent.com/48794854/57919045-48028e80-7898-11e9-834a-c74f6f6a358e.png)

how is it that an app of 20 mb  (i made the big app of the april release MS objects like around 6000)
how is it that it takes like 5,5 GB / 6GB for the NST during the publish..
is that normal?

**Comment by freddydk** [comment]
Sorry for the delay.
Spring release 2019 RTM is very very memory consuming (as you have found). CU1 (which comes out very soon) is better - but will still have a big memory footprint.
I am afraid that with RTM, what you see is normal - lets try this again with CU1 - or create an Azure VM with 32GB or memory using http://aka.ms/getbc and run it in there.
