### ISSUE TITLE
NAV BC on Azure Kubernetes Service YAML file

### ISSUE THREAD

**Issue by hussaynv** [microsoft/navcontainerhelper#448]
Hi, I have pushed the image onto a private Azure Container Register, from here I'm trying to create a deployment to an AKS cluster, from my basic understanding i need a yaml file to create this deployment.
I cant find anything relating to running this in AKS.
I have generated the following but its not working.

apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: businesscentral
spec: 
  template: 
    metadata: 
      labels: 
        app: businesscentral
    spec: 
      containers: 
      - name: businesscentral 
        image: <AKSNAME>.azurecr.io/businesscentral/onprem:v1
        ports:  
        - containerPort: 80
      imagePullSecrets: 
      - name: acr-auth 
---
apiVersion: v1
kind: Service
metadata:
  name: businesscentral-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: businesscentral

Likely this is not correct at all but any help would be very much appreciated, first if its possible to run on AKS, next if there is anything on the yaml file or template yaml file I would need to use, finally the contents of the yaml file and what I need to include in there to create a deployment.

Thanks

**Comment by freddydk** [comment]
I am sorry, but I have never tried Kubernetes and have no insight into how this can work. Maybe somebody else have?
