### ISSUE TITLE
Run-TestsInNavContainer - rerun failed tests

### ISSUE THREAD

**Issue by richardrobberse** [microsoft/navcontainerhelper#450]
I'm currently working together with two partners that are running the entire set of standard test codeunits every night and unfortunately, the test outcome is not predictable, so we're forced to either disable a whole lot of tests or to run the failed tests once again.

I went for the latter and I've built something that reruns failed tests if below a configurable amount of failures.
I now want to migrate to your way of running the tests (Run-TestsInNavContainer) instead of invoking the RTC but I can't find a way to achieve the rerun scenario.
The only option I see is to determine the failed tests and then call the Run-TestsInNavContainer again for every failed test function.

Any ideas?
Thanks in advance!

**Comment by freddydk** [comment]
I will discuss this with the team. We are currently changing the way we run tests to use the same mechanism internally, meaning that we should have a solution for this.

**Comment by richardrobberse** [comment]
Thanks, sounds promising!
Keep me posted ;)

**Comment by nikolakukrika** [comment]
The way how we do it internally is that we run all the tests one more time. For example if we run 10 codeunits and codeunit 7 has a failing test then we teardown the enviroment, set it up again and rerun all 10 codeunits. The key here is to do multiple test runs - e.g. do not run more than 30 minutes of tests at once. 

This is time consuming though. With the new runner you could run the failed codeunits one more time if you would like to save time.

The new runner I'm finishing is able to take an array of the codeunits to run so you can give it only the ones that have failed.

**Comment by freddydk** [comment]
I might then add a flag to run-testsinnavcontainer called -rerunfailedcodeunits :-)

**Comment by richardrobberse** [comment]
Sounds great, thanks for the quick follow-up.

**Comment by freddydk** [comment]
NavContainerHelper 0.6.2.1 is just released and I have modified a few things to allow better control over test execution.
I changed the default interaction timeout to 24 hours – meaning that your tests might just work now without changing anything but upgrading the version.
I also added interactionTimeout as a parameter so you can now control the timeout.

I also changed a few other things, if you want to take advantage of this:

You can now run every codeunit in their own session and control re-runs of codeunits and/or exception handling.
Take a look at this code:

$tests = Get-TestsFromBCContainer -containerName test -credential $credential
$first = $true
$tests.Codeunits | % {
    $allpassed = Run-TestsInBcContainer -containerName test `
                                        -credential $credential `
                                        -XUnitResultFileName 'c:\programdata\navcontainerhelper\results.xml' `
                                        -AppendToXUnitResultFile:(!$first) `
                                        -detailed `
                                        -testCodeunit $_.Id `
                                        -returnTrueIfAllPassed
    if (-not $allpassed) {
        # Rerun?
    }
    $first = $false
}

The AppendToXUnitResultFile determines whether or not the XUnitResultFile is deleted or appended to.
The ReturnTrueIfAllPassed determines whether Run-Tests will return a Boolean or not.
There is another parameter called -rerun, which determines that the result section in the XUnitResultFile will be replaced with the result of the rerun. If rerun is not specified, there will be two results of the same test codeunit.

Let me know if this solves your usage?
