### ISSUE TITLE
Creating Symbols Not Working

### ISSUE THREAD

**Issue by nitewhiz** [microsoft/navcontainerhelper#451]
When I generate symbols in my NAV 2018 cu16  container for a customer DB it does not complete. It just says "running script" and never finishes.   
I tested it with the latest BC container and it works fine there and for other developers it also works for this particular customer DB. 
Is there anything I can do to troubleshoot this?

**Comment by freddydk** [comment]
Have you checked the event log on the container?
You can get a local copy of the eventlog by using Get-NavContainerEventLog.
Could be a memory issue?
Are the containers started using process or hyperv isolation?
Is the memory available to the containers identical?

**Comment by nitewhiz** [comment]
I used the ltsc2019 option when creating the container and my PC is running Windows 10 (1809) so I guess the container is running Windows Server 2019 which always uses Hyper-V as far as I know. Is there a way I can confirm this?

The container (like the others) is running with 4GB of RAM. The host system has 16GB. I checked the memory and it does not seem to be the issue.

Another thing I noticed is that the container becomes unhealthy after the symbols creation was started and stopped. After I restart the container it shows as healthy again.

Here is a screenshot of the event log. I must have started the symbol creation around 15:00 yesterday and let it run for 2 or 3 hours. It only shows Information entries and then raised the marked warning event 705 at 16:51:20:
![NAVContainer EvenLog](https://user-images.githubusercontent.com/45852840/57837468-2edbde00-77c3-11e9-94a7-d1a1da743279.JPG)

**Comment by nitewhiz** [comment]
I tried it again this morning. It started with a few 705 events and then processed for a while with 113 events and then went back to 705. Here is a 705 dump:

The description for Event ID 705 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Server instance: NAV
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: 00000000-0000-0000-0000-000000000000
EventTime: 05/16/2019 08:23:49
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 10004 ms
  Threshold: 1000 ms
  Message: Long Running SQL statement Task ID:3, ConnectionId=3
    SELECT DISTINCT CT.SYS_CHANGE_VERSION, 0[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Object Metadata], @maxChangeTrackingNumberObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 1[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [Debugger Breakpoint], @maxChangeTrackingNumberDebuggerBreakpoint) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 2[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], '00000000-0000-0000-0000-000000000000'[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[Add-in], @maxChangeTrackingNumberAddIn) CT WHERE CT.SYS_CHANGE_OPERATION = 'U'
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 3[Change Type], CT.SYS_CHANGE_OPERATION, CT.[Object Type], CT.[Object ID], CT.[App Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Object Metadata], @maxChangeTrackingNumberNavAppObjectMetadata) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 4[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[App Package ID], CT.[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App Tenant App], @maxChangeTrackingNumberNavAppTenantApp) CT
UNION ALL
SELECT DISTINCT CT.SYS_CHANGE_VERSION, 5[Change Type], CT.SYS_CHANGE_OPERATION, 0[Object Type], 0[Object ID], CT.[Package ID], ''[Tenant ID] FROM CHANGETABLE(CHANGES [dbo].[NAV App], @maxChangeTrackingNumberNavApp) CT
ProcessId: 18248
Tag: 000007L
ThreadId: 6
CounterInformation:

**Comment by freddydk** [comment]
Sorry for the delay.
If you specify the command you use to create the container and the full output of the command, then we can see what isolation you are running and whether there are other things missing.

**Comment by nitewhiz** [comment]
I just sent you the script per mail.

**Comment by freddydk** [comment]
Seems like it was a memory problem.
Container was created with a -memorylimit 4g always - solution is to use process isolation (and remove the memorylimit) or increase the memorylimit.
