### ISSUE TITLE
Run-TestsInNavContainer - Tests are failing randomly sometimes

### ISSUE THREAD

**Issue by JulianSheeper** [microsoft/navcontainerhelper#453]
Run-TestsInNavContainer is failing randomly sometimes, even though we did not make any code changes. As you can see, the CI got triggered on the same commit (3e97b22) every time.
We also did not change the VM that executes the CI in any way.
But for some reason, the execution failed the fifth time as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/11839572/57939561-e4458900-78ca-11e9-9d22-b5e1f0ecf04a.png)

The error message looks as follows:

![image](https://user-images.githubusercontent.com/11839572/57939917-9d0bc800-78cb-11e9-8dc0-d61e5719a9ad.png)

**Environment:**
navcontainerhelper Version: 0.6.0.15
Business Central Image: mcr.microsoft.com/businesscentral/sandbox:13.3.27233.0-ltsc2019
OS: Windows Server 2019
Docker Version: 18.09.6

**Comment by freddydk** [comment]
In ContainerHelper 0.6.0.10 i fixed a bug to default the company better.
You have this fix, but for some reason, the company selection seems empty.
I assume you have multiple companies in the database.
Do you specify company on the commandline - or is the company defined on the user?
Or how is the company determined?

**Comment by JulianSheeper** [comment]
No, I just spin up a standard BC Image every time with the default settings. See the code below:

![image](https://user-images.githubusercontent.com/11839572/58537032-4ae37480-81f2-11e9-9e5e-eff218121e26.png)

I assume there is just one company in the database of the standard Image. Also, I never specify a company or a tenant on the commandline.
And as I said, it works 9/10 times so it is most likely a bug in the Run-TestsInNavContainer Script I suppose.

**Comment by freddydk** [comment]
Is it the same error as above each time?

**Comment by JulianSheeper** [comment]
Yes

**Comment by freddydk** [comment]
And what image are you using ?

**Comment by JulianSheeper** [comment]
I specify as imageName Parameter of NewNavContainer: mcr.microsoft.com/businesscentral/sandbox:13.3.27233.0-ltsc2019

**Comment by freddydk** [comment]
I have fixed a few things (see #450).
If any test codeunit would take more than 10 minutes, it would cause test execution to fail - that is fixed. And - now you are allowed better control of test execution.
