### ISSUE TITLE
Unable to download symbols

### ISSUE THREAD

**Issue by CBlasek** [microsoft/navcontainerhelper#454]
I am unable to download symbols when generating a container. I am using the following with output, it can ping the container and access the webclient.

PS C:\Windows\system32\WindowsPowerShell\v1.0> New-NavContainer -accept_eula `
-imageName microsoft/bcsandbox:us `
-containerName 'BCTest' `
-auth NavUserPassword `
-updateHosts `
-doNotExportObjectsToText `
-licenseFile c:\docker\kBC.flf `
-includeCSide `
-useSSL `
-useBestContainerOS `
-alwaysPull
NavContainerHelper is version 0.6.0.15
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Pulling image microsoft/bcsandbox:us-ltsc2019
us-ltsc2019: Pulling from microsoft/bcsandbox
Using image microsoft/bcsandbox:us-ltsc2019
Removing BCTest from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\BCTest
Creating Nav container BCTest
Using license file c:\docker\kBC.flf
Version: 14.0.29537.31808-US
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.107 (ltsc2019)
Using process isolation
Creating container BCTest from image microsoft/bcsandbox:us-ltsc2019
1c5cdcba231b71faa6702090d1c9011a98f28c4f0f2f2fea2586974b38daf4dc
Waiting for container BCTest to be ready
Initializing...
Starting Container
Hostname is BCTest
PublicDnsName is BCTest
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 11BFF5A50B55F453C615848E06ADF19966430B0C
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating super as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.23.0.29
Container Hostname  : BCTest
Container Dns Name  : BCTest
Web Client          : https://BCTest/NAV/
Dev. Server         : https://BCTest
Dev. ServerInstance : NAV

Files:
http://BCTest:8080/al-3.0.106655.vsix
http://BCTest:8080/certificate.cer

Initialization took 71 seconds
Ready for connections!
Reading CustomSettings.config from BCTest
Creating Desktop Shortcuts for BCTest
Nav container BCTest successfully created

PS C:\Windows\system32\WindowsPowerShell\v1.0> ping bctest

Pinging bctest [172.23.0.29] with 32 bytes of data:
Reply from 172.23.0.29: bytes=32 time<1ms TTL=128
Reply from 172.23.0.29: bytes=32 time<1ms TTL=128

When I try and download symbols in VS code using:
![image](https://user-images.githubusercontent.com/16197501/58020412-03643680-7ad6-11e9-9685-44ec103d72cc.png)

It sits there until it errors out saying:
![image](https://user-images.githubusercontent.com/16197501/58020462-28f14000-7ad6-11e9-89b9-93972c7ed32d.png)

![image](https://user-images.githubusercontent.com/16197501/58020513-56d68480-7ad6-11e9-8027-ff6f6aa375f4.png)

**Comment by freddydk** [comment]
You specified useSSL - and the output states that your dev. server is https://bctest
Yet you have http://bctest in your launch.json.

Try to add the s - or remove -usessl (really isn't needed when doing local development)

**Comment by CBlasek** [comment]
Thanks. I did not realize usessl, was on the development port, thought it was only on the web client.

**Comment by freddydk** [comment]
Thanks for a very detailed issue description - it makes it so much easier to help people with descriptions like this.
