### ISSUE TITLE
Suggestion: parameter for restart policy

### ISSUE THREAD

**Issue by RafaelKoch** [Microsoft/navcontainerhelper#46]
if i read `New-NavContainer.ps1` correctly and judging from my experience so far you set the restart policy for the containers to `always`.
This is sometimes killing my Windows 10 if i am careless enough to make 2 or more containers and not delete all but one before next reboot or next start of docker. What happens is they then all start up and I watch my laptop burn :-)
So I would love to be able to optionally set a restart policy in New-NavContainer because for me it would be best to set the restart policy to `no`.

**Comment by Koubek** [comment]
Or maybe `unless-stopped` would be also OK...

**Comment by freddydk** [comment]
I will fix this in an update very soon - the unless-stopped seems to leave the user in control.

**Comment by RafaelKoch** [comment]
Probably true @Koubek  -  `unless-stopped` would help me in this scenario and still restart containers when simply stopping/starting docker itself. 

Still, I would in my case go for `no` given a choice. Why? Because I already use VS Code docker extension to stop/start containers which I will probably mostly need for development anyway. So no trouble finding and starting what i need and I cannot fry my system the way i just did. 

@freddydk : An optional parameter would be my favourite, yet If you do not want to make this a parameter `unless-stopped` would help me too.

**Comment by freddydk** [comment]
Came to think of it - you can actually do this today.
add 
-additionalParameters @("--restart no")
and it will override the default restart option
I have added a -restart option to the new-navcontainer and it uses unless-stopped as default option.
You can clone the github repo and use that (or wait a few days until it hits the powershell gallery)

**Comment by RafaelKoch** [comment]
`-additionalParameters @("--restart no")` : tried it and it works fine.

Also I took a look at Your latest changes regarding the new parameter ([commit 6b7fede0d752f6758ee2695375ad96c1b5d68eea](https://github.com/Microsoft/navcontainerhelper/commit/6b7fede0d752f6758ee2695375ad96c1b5d68eea)) Looking nice too, will use that once it is on PS gallery.

Many thanks for for both!
