### ISSUE TITLE
Windows 1903, not able to create container

### ISSUE THREAD

**Issue by ashikkrux** [microsoft/navcontainerhelper#461]
I updated my Windows to 1903. 

navconatinerhelp - version 0.6.1.0
Windows - Version 1903 (OS Build 18362.116)
When I create a new container (using -useBestContainerOS) it's giving me an error "The container operating system does not match the host operating system". The image downloading was "mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019".

navconatinerhelp - version 0.6.0.15
Windows - Version 1903 (OS Build 18362.116)
With this version, the image downloading was "microsoft/dynamics-nav:latest-ltsc2019". Here also it was giving me an error "The container operating system does not match the host operating system".

**Comment by freddydk** [comment]
If you display the command and the full output of the command, I can tell you what you need to do different.

**Comment by ashikkrux** [comment]
Which version of navcontainerhelper should I use? 

version 0.6.1.0 or 0.6.0.15

**Comment by freddydk** [comment]
Newest - 0.6.1.0

**Comment by ashikkrux** [comment]
PS C:\WINDOWS\system32> New-NavContainer -containerName demo -accept_eula -auth NavUserPassword -doNotExportObjectsToText -includeCSide -isolation process -shortcuts Desktop -updateHosts -useBestContainerOS
NavContainerHelper is version 0.6.1.0
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
latest-ltsc2019: Pulling from businesscentral/onprem
Digest: sha256:27a13e118b9e00f5d18b71e1f636e97a59dfa1920a1de1dccbfade2d6e772a13
Status: Image is up to date for mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
Using image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
Removing demo from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\demo
Creating Nav container demo
Version: 14.0.29537.0-W1
Platform: 14.0.29530.0
Generic Tag: 0.0.9.5
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.18362.116 (1903)
Using process isolation
Creating container demo from image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
6efc89ab5aafd9808bb739a57bdfd726efd93a9920e272718ebd1be50ca83b53
DockerDo : docker.exe: Error response from daemon: CreateComputeSystem 
6efc89ab5aafd9808bb739a57bdfd726efd93a9920e272718ebd1be50ca83b53: The container operating system does not match the host 
operating system.
(extra info: {"SystemType":"Container","Name":"6efc89ab5aafd9808bb739a57bdfd726efd93a9920e272718ebd1be50ca83b53","Owner":
"docker","VolumePath":"\\\\?\\Volume{b5a00607-4f6b-4658-826d-8ba4ac69ff79}","IgnoreFlushesDuringBoot":true,"LayerFolderPa
th":"C:\\ProgramData\\Docker\\windowsfilter\\6efc89ab5aafd9808bb739a57bdfd726efd93a9920e272718ebd1be50ca83b53","Layers":[
{"ID":"96a79d8a-8edc-558e-bbf2-877dd35e6956","Path":"C:\\ProgramData\\Docker\\windowsfilter\\f1ac1fec1f93f989b3ecaf013085
263c500ed042c37a1c5a998dfc0c66ea974b"},{"ID":"d6a5e53b-4c81-5ab6-ba1c-20eaae8b79c2","Path":"C:\\ProgramData\\Docker\\wind
owsfilter\\2aef0d47dc2b89c2c18c795d63fcee2c8d6d8cdb7a3932a7410247bec8ed19b1"},{"ID":"c509849f-6fcb-55e8-8943-3af3967fb880
","Path":"C:\\ProgramData\\Docker\\windowsfilter\\722f11e79f034359335931653aba2dd1ed35669e7d0515d754fa956fd308ccc7"},{"ID
":"bf83b18b-1692-50f6-9030-aa8a6da1fff5","Path":"C:\\ProgramData\\Docker\\windowsfilter\\eceffbd9b6e478cb1d70f2f9077959a5
27493fc25ec2ca06b1d44036bb5f3c80"},{"ID":"4ba56baa-3692-5361-958a-3cf23037e419","Path":"C:\\ProgramData\\Docker\\windowsf
ilter\\2294753fecda9bbe42c499b7aa3eb7f3806b2b784a5b04dca126573bb53e3555"},{"ID":"b336d7f9-7a99-57af-a0f7-84fc1d13334a","P
ath":"C:\\ProgramData\\Docker\\windowsfilter\\f0b8fd0a922489a6f1ba126648e2945a87a67f3d318294c4779dceaaac7ba943"},{"ID":"e
5c4817e-6144-5114-8aa2-b6d4ec7cc5d8","Path":"C:\\ProgramData\\Docker\\windowsfilter\\de1e287c78fe73a774ef9934e46f05ed6f8c
4b4979ce130e34a2e2fae7639024"},{"ID":"ec4f6b00-4d71-578c-95d4-d6ddb6c5d539","Path":"C:\\ProgramData\\Docker\\windowsfilte
r\\921a0eddca097f6150d4f81788f245f39c04981239bf83cac12a4ddefac0df24"},{"ID":"9c20020b-1912-5ac2-b444-4172b8c30d91","Path"
:"C:\\ProgramData\\Docker\\windowsfilter\\73e63ce4ffb55f72cc6c1bcd149ac1d691e745fab7ba666c01368c51a81ed2d8"},{"ID":"d0639
df9-ddf0-59ea-87d0-37c8d9187efd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\8a2e3bea82556ca363b3efa7f34cdf9a1c8bac80
7077185989051e2015a48f95"},{"ID":"746b28d8-279b-5b80-9006-1de562ec5245","Path":"C:\\ProgramData\\Docker\\windowsfilter\\e
88ddfe01f2552735dd6b72869c796053de4e1df6bcf0d3ef50d24de1ce4bbd7"},{"ID":"99358d56-26ec-56a1-8244-9784295d1af3","Path":"C:
\\ProgramData\\Docker\\windowsfilter\\e7fed01adc5caf7f04a7758a9ea4a6216a4dea3b3b6fcff3440f31b85b2d0d56"},{"ID":"1398265f-
ec25-55a5-81e7-be2d70fc3bda","Path":"C:\\ProgramData\\Docker\\windowsfilter\\ef1fe876ed6547c990dacb7346eb6d6e79ab7b21b4ff
8181b9839cb02bc3f64a"},{"ID":"dc15a89e-1da9-5b14-b1d6-998da5ff9ffd","Path":"C:\\ProgramData\\Docker\\windowsfilter\\cd614
8cdfca64b9d9bea230cbda4bfb485b7c539736bc7822c63c86760ae13e8"},{"ID":"e9c1e501-b4c3-531a-b923-a24d5ce13167","Path":"C:\\Pr
ogramData\\Docker\\windowsfilter\\2db09eaf33177f074e783b77dbf49691efabd60de3cc15b01028962af382555c"},{"ID":"403ba5d0-19de
-525a-869e-4a2ef8a0e096","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7926cc9219bffc55d97bcb0d71cdfd894f2e3fb86ef68e70
5e0f16a5b41b352c"},{"ID":"6faa308b-32c0-5c50-8f7e-d4a0fbb11fcc","Path":"C:\\ProgramData\\Docker\\windowsfilter\\dfda54ed4
cc0a4e99bfc9d31f25e1dc412fd944a7c820f7dc7235d576550111b"},{"ID":"fb4d8521-3236-5aa6-a7a7-6eb9f824ecd1","Path":"C:\\Progra
mData\\Docker\\windowsfilter\\ad2b92f5901903cc775fcfbe8aab998b4cfa79ebc5f18e341e8f85557b06bb44"},{"ID":"bc3374cb-014b-55f
1-ba89-c1d036d0285f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\a17c11765186698b380bd3facec053980aacf2376e687b24b242
0ec3ec394511"},{"ID":"7bef25dc-84d8-5bc9-8e38-767b4b70df47","Path":"C:\\ProgramData\\Docker\\windowsfilter\\d38908ac05f8b
6514065b5e39fb2aa14da023911176cfa7f3a88d6932b548242"},{"ID":"2e03b230-4041-5f6f-8537-2b7d293865e2","Path":"C:\\ProgramDat
a\\Docker\\windowsfilter\\c2bd961747f88cdfc43ce5c8eab9b865d244669a7dee4bd4e7851574d3e56fd3"},{"ID":"7f55ceb4-258c-5050-a4
eb-a866c6dfe95f","Path":"C:\\ProgramData\\Docker\\windowsfilter\\7b46d0c1921cbb28abdf34990213268ee154560e310bbc1913dd79dc
11423deb"},{"ID":"52f036b4-f7aa-55c7-abb5-4b9b62a61294","Path":"C:\\ProgramData\\Docker\\windowsfilter\\38c170f51033ecf58
6eedcef27ef37708d1f2bb3f5e33f82902b2ecf08c6f0ef"},{"ID":"24bbaf56-f370-5d92-af5f-a34a3a81599e","Path":"C:\\ProgramData\\D
ocker\\windowsfilter\\8d04945852b1fa009bfac10ab24534dac86a7b13230712c7d4f0d77656c3688a"},{"ID":"bec59792-cf1f-54c6-b5d6-0
958ed0486e2","Path":"C:\\ProgramData\\Docker\\windowsfilter\\6ff0044f86d022a352bea92f47b85b172dee0adea9435aef25e8d656048e
f1c8"},{"ID":"fb412a61-dc36-5c82-9ce2-52ed866b53bf","Path":"C:\\ProgramData\\Docker\\windowsfilter\\5604903c238c8f2f56857
bd2ee0f72917f9e222f64d6f5327bf848a2f0501eb3"}],"HostName":"demo","MappedDirectories":[{"HostPath":"c:\\programdata\\navco
ntainerhelper\\extensions\\demo\\program files","ContainerPath":"c:\\navpfiles","ReadOnly":false,"BandwidthMaximum":0,"IO
PSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\windows\\system32\\drivers\\etc","ContainerPath":"c:\\driversetc
","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navconta
inerhelper","ContainerPath":"c:\\programdata\\navcontainerhelper","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"
CreateInUtilityVM":false},{"HostPath":"c:\\programdata\\navcontainerhelper\\extensions\\demo\\my","ContainerPath":"c:\\ru
n\\my","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0,"CreateInUtilityVM":false}],"HvPartition":false,"EndpointLis
t":["7E4CA000-2A77-4F2E-B345-A00ACD8A1831"],"AllowUnqualifiedDNSQuery":true}).
ExitCode: 125
Commandline: docker run --name demo --hostname demo --env auth=NavUserPassword --env username="demo" --env ExitOnError=N 
--env locale=en-US --env licenseFile="" --env databaseServer="" --env databaseInstance="" --volume 
"C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\demo\my:C:\Run\my" --isolation process --restart unless-stopped --env 
enableApiServices=Y --env useSSL=N --volume "C:\ProgramData\NavContainerHelper\Extensions\demo\Program 
Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d1116743f0423413b1
6050a5345MgB8AEIATABkAGQAeQBpACsAeQAyADQAdABYAGoARwBOAFYAQwBzADgAcQBkAHcAPQA9AHwANwA5AGYAYgBiAGQAOABiAGUAMABjADcAYwA4ADAA
MAA5ADIANwA5ADEANgBlADgAMwAxADkAMAAwADEAOABmAA== --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y 
--env accept_eula=Y --detach mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.0\ContainerHandling\New-NavContainer.ps1:964 
char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
Remove -isolation process
New-NavContainer will default to process isolation if possible - in your case, you cannot run process isolation because OS versions doesn't match.
You can also build a new generic image and re-platform the container using this mechanism: https://freddysblog.com/2019/05/01/windows-10-1903-and-business-central-containers/

**Comment by ashikkrux** [comment]
Thank You @freddydk. 
I am able to create a container now. 
Let me also try something new which the link provided :) :)

**Comment by freddydk** [comment]
hyperv works really well in Windows 10 1903 though - maybe not needed to re-platform

**Comment by ashikkrux** [comment]
Yes, Freddy, I read in the blog too. 
Working fast now.  :)
