### ISSUE TITLE
Issue publishing the app in new Container

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#464]
Hi - I used below command to create a container.
**New-NavContainer -containerName test -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -updateHosts**

Now, when i use below command to publish the app

**Publish-NavContainerApp -appFile “C:\work\Binary Stream Software Inc._Binary Stream Inc Monetization_1.0.4.3.app” -containerName test -install –packageType Extension –skipVerification**

I get below error saying, i dont have correct license. I am hoping that i should be able to publish the app with default license (developer)

![image](https://user-images.githubusercontent.com/38437776/58351946-08e7b680-7e1f-11e9-8301-94c44d4475df.png)

Can some one help me please.

**Comment by freddydk** [comment]
Only if your app is a runtime package.
You can publish the app with the right license and use Get-NavContainerAppRuntimePackage to get a runtime package.

**Comment by Bssivivek** [comment]
thanks for your quick response freedy.

I use below command to get the runtime package

**Publish-NavContainerApp -appFile “C:\work\Binary Stream Software Inc._Binary Stream Inc Monetization_1.0.4.3.app” -containerName Wipfli -licenseFile "C:\Work\MEM-D365BC.flf" -install –packageType Extension –skipVerification**

iam getting below error

![image](https://user-images.githubusercontent.com/38437776/58352552-bf986680-7e20-11e9-86bd-aec312f21590.png)

Evrn though my version is correct
![image](https://user-images.githubusercontent.com/38437776/58352581-d63ebd80-7e20-11e9-8be4-52fa0fd8198b.png)

**Comment by freddydk** [comment]
that error means that there is no parameter called version on that function.
Use help or intellisense to find the parameters.

(hint - it is -appVersion)

**Comment by Bssivivek** [comment]
@freddydk thanks for your time and help. This issue is resolved. you can close this ticket.
