### ISSUE TITLE
Cannot run un-elevated in 0.6.1.1

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#465]
Ever since I this morning updated to v. 0.6.1.1, then Create-NewContainer keeps failing on these lines, when running VsCode un-elevated:
    _$dockerOS = docker version -f "{{.Server.Os}}"
    if ($dockerOS -ne "Windows") {
        throw "Docker is running $dockerOS containers, you need to switch to Windows containers."_

Giving this error:
_error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/version: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
Docker is running  containers, you need to switch to Windows containers._

Running Check-NavContainerHelperPermissions -Fix also worked fine before Days of Knowledge, now it fails on the last check:
xx NOT have permissions to run docker commands.

**Comment by freddydk** [comment]
Did you also update your Windows or Docker Version?
Check-NavContainerHelperPermissions -fix should fix this by giving you permissions (probably will ask you for elevated access to do so).
But that doesn't happen?

**Comment by epernst** [comment]
No, have not updated Docker EE, since last Monday.
I run Check-NavContainerHelperPermissions -Fix

_Running as DOMAIN\username
Checking permissions to C:\ProgramData\NavContainerHelper
DOMAIN\username has the right permissions to C:\ProgramData\NavContainerHelper
Checking permissions to C:\WINDOWS\System32\drivers\etc\hosts
DOMAIN\username has the right permissions to C:\WINDOWS\System32\drivers\etc\hosts
Checking permissions to docker commands
docker : error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json: open //./pipe/docker_engine: Access is
denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that
the docker daemon is not running.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.1\Check-NavContainerHelperPermissions.ps1:134 char:19
+             $ps = docker ps 2> $tempFile
+                   ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error during co...is not running.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError


DOMAIN\username does NOT have permissions to run docker commands
Unable to determine docker deamon socket. Are you sure Docker is running and reachable?_

**Comment by freddydk** [comment]
And docker is running?
If you run a cmd prompt with elevate permissions you can do docker ps ?

**Comment by epernst** [comment]
Everything works fine, if I run it with elevated permissions. 

I just tried to run it at my computer at home. Same Windows 10 and Docker. Here initially I got the same error, something changed in the permissions. But here running Check-NavContainerHelperPermissions -Fix fixes it, after giving the Administrator warning and approval. Maybe the reason is that at work I have a normal account AND a personal admin account, to be used whenever I need elevated permissions (which makes elevated permissions even more annoying as it then saves the icon's on a different desktop).

**Comment by freddydk** [comment]
Ok, yes that might be.
Now, I think when you get back tomorrow - you should probably have the right permissions.

**Comment by epernst** [comment]
Morning Freddy,
I started by trying again via VSCode, and it failed again.

But then I tried via Powershell ISE instead. Here **the Fix worked** and prompted me for my admin login and were able to assign the correct permissions.

Problem solved. Thank you.
