### ISSUE TITLE
AD Integration

### ISSUE THREAD

**Issue by Pellic** [microsoft/navcontainerhelper#466]
Hi,
is there any sample script for the combined use of Nanvcontainerhelper and AD?
I would like to spin up a container usable from the group DevUser of the domain MyDomain, in a Docker host joined to MyDomain.
Actually I use the NavUserPassword authentication method, and it works like a charm with this script: https://github.com/Pellic/nav-docker/blob/master/generic/Pellic/BCOnPremContainerWithSQLDockerizedDB_.ps1

But now I would like to create the container in AD env

**Comment by freddydk** [comment]
containers cannot be domain joined. You will have to use gMSA to use AD, and I do not know whether groups are included in that.
