### ISSUE TITLE
Cannot Package - Build App 

### ISSUE THREAD

**Issue by gdrenteriag** [microsoft/navcontainerhelper#467]
Hello, I following this steps:
https://freddysblog.com/2019/04/15/c-al-to-al-code-customizations/

But when in Visual Studio Code I do:
AL:PACKAGE CTRL+SHIFT+B
I get this error:  AL0124: The property ‘AdditionalSearchTerms’ cannot be used in this context.
[Output.txt](https://github.com/microsoft/navcontainerhelper/files/3224789/Output.txt)

**Comment by freddydk** [comment]
It looks like you have an old version of the .vsix installed in VS Code.
I think 3.0.106655.0 is the one you get from the spring release container.

**Comment by gdrenteriag** [comment]
Thanks, I have another error and I created an issue.
