### ISSUE TITLE
Error: Compile-AppInNavContainer

### ISSUE THREAD

**Issue by gdrenteriag** [microsoft/navcontainerhelper#469]
I have an error when in Powershell run
Compile-AppInNavContainer -containerName "myal" -credential $credential -appProjectFolder "C:\ProgramData\NavContainerHelper\AL\DemoSolution"

Output:
PS C:\WINDOWS\system32> Compile-AppInNavContainer -containerName "myal" -credential $credential -appProjectFolder "C:\ProgramData\NavContainerHelper\AL\DemoSolution"
Using Symbols Folder: C:\ProgramData\NavContainerHelper\AL\DemoSolution\.alpackages
Compiling...
alc.exe /project:C:\ProgramData\NavContainerHelper\AL\DemoSolution /packagecachepath:C:\ProgramData\NavContainerHelper\AL\DemoSolution\.alpackages /out:C:\ProgramData\Nav
ContainerHelper\AL\DemoSolution\output\Default Publisher_myal_1.0.0.0.app /assemblyprobingpaths:"C:\ProgramData\NavContainerHelper\AL\DemoSolution\.netpackages","C:\Progr
am Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\140\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\wi
ndows\assembly"
El proceso en segundo plano notificó un error con el siguiente mensaje: "El proceso de destino de socket de Hyper-V ha terminado"..
en Invoke-ScriptInNavContainer, D:\OneDrive - Directorio predeterminado\Business Central\navcontainerhelper-master\ContainerHandling\Invoke-ScriptInNavContainer.ps1: líne
a 31
en Compile-AppInNavContainer, D:\OneDrive - Directorio predeterminado\Business Central\navcontainerhelper-master\AppHandling\Compile-AppInNavContainer.ps1: línea 252
en <ScriptBlock>, <sin archivo>: línea 1
El proceso en segundo plano notificó un error con el siguiente mensaje: "El proceso de destino de socket de Hyper-V ha terminado"..
En D:\OneDrive - Directorio predeterminado\Business Central\navcontainerhelper-master\ContainerHandling\Invoke-ScriptInNavContainer.ps1: 31 Carácter: 13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (c4eb614bd6e06eb...63771b84c858850:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : c4eb614bd6e06ebe7ea2dd46d0edb9891370ee50111df216363771b84c858850

**Comment by freddydk** [comment]
Have a hard time understanding spanish, sorry. 
But since it says something with Hyper-v, I think this is because of memory consumption. Default, Hyperv containers are given a memorylimit of 3 Gb.
Spring release RTM consumes a LOT of memory (CU1 and later should be much better), so you will have to add -memorylimit 10G - or even more.
running process isolation, it will be able to consume and free the memory from the host.

**Comment by gdrenteriag** [comment]
Sorry about the spanish,  I will try to avoid it in the future.  I have 16 GB but I think, my machine was working another tasks and they consume memory in the same time. 
I will try again more free of applications.
When you say me CU1 and later, it's about 13.0 or 14.0 (Spring). 
Thanks.

**Comment by freddydk** [comment]
14.1 - spring cu1 - not out yet - should be soon

**Comment by gdrenteriag** [comment]
Ah Ok, CU1 and futures release of 14.0 they are minor consumers of memory.
I will expected, Thanks Freddy I hope pass this compilation releasing resources.

**Comment by gdrenteriag** [comment]
Hi Freddy, 
I tried in my machine which has 16 GB but I cannot succefull,
I read this link, and this is in this way:
https://blogs.msdn.microsoft.com/freddyk/2019/01/13/process-isolation-for-containers-in-windows-10/

Can be that this "605.9 MB" is the problem in the container?, 

PS C:\WINDOWS\system32> docker top myal | where-object { $_.StartsWith("Microsoft.Dynamics.Nav.Server") }
Microsoft.Dynamics.Nav.Server.exe   2308                00:00:22.312        605.9MB

**Comment by NAVspecialist** [comment]
I think you need to give a little more info here. 

How does your Docker run/New-NAVcontainer look like ?
How much free space do you have on the drive where docker/image is installed?
What Windows version/build are you running?  (command prompt run: winver
Run a command prompt as administrator and type docker version and paste it to the mail.

Thanks,
Palle

**Comment by gdrenteriag** [comment]
Hi, good afternoon. 
I created the container with this command
# Settings
$imageName = "mcr.microsoft.com/businesscentral/onprem:1904-rtm"
$auth = "NavUserPassword"
$credential = New-Object pscredential 'administrador', (ConvertTo-SecureString -String 'A1b2c3d4.' -AsPlainText -Force)
$licenseFile = "D:\MCGBCv4.flf"

# Create Business Central container
New-NavContainer -accept_eula `
                 -imageName $imageName `
                 -containerName "myal" `
                 -licenseFile $licenseFile `
                 -auth $auth `
                 -Credential $Credential `
                 -updateHosts `
                 -includeAL

Drive C: I have 80 GB free. 

PS C:\WINDOWS\system32> [System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0       

PS C:\WINDOWS\system32> docker version
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.24)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:28:48 2019
  OS/Arch:          windows/amd64
  Experimental:     false

**Comment by freddydk** [comment]
If you could provide the output from New-NavContainer - it prints a lot of stuff, which helps us troubleshoot.

**Comment by gdrenteriag** [comment]
This help you?,  If not I should run again that script. 

PS C:\WINDOWS\system32> Get-NavContainerServerConfiguration -ContainerName myal
ContainerName                                   : myal
NetworkProtocol                                 : Default
DatabaseServer                                  : localhost
DatabaseInstance                                : SQLEXPRESS
DatabaseName                                    : CRONUS
EnableSqlConnectionEncryption                   : false
TrustSQLServerCertificate                       : false
ServerInstance                                  : NAV
EnableSqlInformationDebugger                    : true
AmountOfSqlStatementsInDebugger                 : 10
EnableLongRunningSqlStatementsInDebugger        : true
LongRunningSqlStatementsInDebuggerThreshold     : 500
ClientServicesPort                              : 7046
SOAPServicesPort                                : 7047
ODataServicesPort                               : 7048
ManagementServicesPort                          : 7045
ManagementServicesEnabled                       : true
ClientServicesEnabled                           : true
DeveloperServicesPort                           : 7049
DeveloperServicesEnabled                        : true
DeveloperServicesSSLEnabled                     : false
ExtensionAllowedTargetLevel                     : Internal
ReportPDFFontEmbedding                          : true
ReportAppDomainIsolation                        : true
EnableSaveToWordForRdlcReports                  : true
EnableSaveToExcelForRdlcReports                 : true
EnableSaveFromReportPreview                     : true
CompileBusinessApplicationAtStartup             : true
SOAPServicesEnabled                             : true
ODataServicesEnabled                            : true
ODataServicesV3EndpointEnabled                  : true
ODataServicesV4EndpointEnabled                  : true
SOAPServicesSSLEnabled                          : false
ODataServicesSSLEnabled                         : false
ODataMaxConnections                             : 0
ODataMaxConnectionsPerTenant                    : 0
DeltaServiceClientTimeout                       : 00:02:00
ODataServicesOperationTimeout                   : MaxValue
PublicODataBaseUrl                              : http://myal:7048/NAV/OData
PublicSOAPBaseUrl                               : http://myal:7047/NAV/WS
PublicWebBaseUrl                                : http://myal/NAV/
PublicWinBaseUrl                                : DynamicsNAV://myal:7046/NAV/
DefaultClient                                   : Web
ServicesOptionFormat                            : OptionCaption
ServicesLanguage                                : en-US
CalendarTwoDigitYearMax                         : -1
SOAPServicesMaxMsgSize                          : 1024
ServicesUseNTLMAuthentication                   : false
ServicesDefaultTimeZone                         : UTC
ServicesDefaultCompany                          : 
ODataServicesMaxPageSize                        : 1000
ClientServicesOperationTimeout                  : MaxValue
ClientServicesProtectionLevel                   : EncryptAndSign
MaxConcurrentCalls                              : 1000
ClientServicesMaxConcurrentConnections          : 500
ClientServicesReconnectPeriod                   : 00:10:00
ClientServicesMaxNumberOfOrphanedConnections    : 20
ClientServicesCompressionThreshold              : 64
ClientServicesMaxUploadSize                     : 150
EnableDebugging                                 : false
DebuggingAllowed                                : true
ClientServicesMaxItemsInObjectGraph             : 512
ClientServicesChunkSize                         : 28
ClientServicesProhibitedFileTypes               : ade;adp;asp;bas;bat;chm;cmd;com;cpl;csh;exe;fxp;gadget;hlp;hta;inf;i
                                                  ns;isp;its;js;jse;ksh;lnk;mad;maf;mag;mam;maq;mar;mas;mat;mau;mav;ma
                                                  w;mda;mdb;mde;mdt;mdw;mdz;msc;msi;msp;mst;ops;pcd;pif;prf;prg;pst;re
                                                  g;scf;scr;sct;shb;shs;url;vb;vbe;vbs;vsmacros;vss;vst;vsw;ws;wsc;wsf
                                                  ;wsh
ClientServicesAllowedFileTypes                  : 
NASServicesStartupCodeunit                      : 
NASServicesRunWithAdminRights                   : false
EnableDeadlockMonitoring                        : true
NASServicesStartupMethod                        : 
NASServicesStartupArgument                      : 
NASServicesEnableDebugging                      : false
ClientServicesCredentialType                    : NavUserPassword
UIElementRemovalOption                          : LicenseFileAndUserPermissions
ClientServicesTokenSigningKey                   : 
ClientServicesFederationMetadataLocation        : 
ServicesCertificateThumbprint                   : DB9AE042F2C8BC35CADF2A2CC3F3208816AD3062
ServicesCertificateValidationEnabled            : false
DisableTokenSigningCertificateValidation        : false
TokenSigningCertificateValidationMode           : IssuerNameValidation
DataCacheSize                                   : 10
SessionEventTableRetainInterval                 : 90.00:00:00
NonInteractiveSessionsLogRetainInterval         : 5.00:00:00
SqlCommandTimeout                               : 00:30:00
SqlConnectionTimeout                            : 00:01:30
BufferedInsertEnabled                           : true
DisableSmartSql                                 : false
EnableFullALFunctionTracing                     : false
Multitenant                                     : False
SqlConnectionIdleTimeout                        : 00:05:00
EnableALServerFileAccess                        : true
EnableApplicationChannelLog                     : true
EncryptionProvider                              : LocalKeyFile
ExchangeAuthenticationMetadataLocation          : 
AppIdUri                                        : 
WSFederationLoginEndpoint                       : 
AzureActiveDirectoryClientId                    : 
AzureActiveDirectoryClientSecret                : 
AzureActiveDirectoryClientCertificateThumbprint : 
EnableMembershipEntitlement                     : 
MaxRowsToExportToExcel                          : MaxValue
EnableTaskScheduler                             : false
TaskSchedulerMaximumConcurrentRunningTasks      : 10
ClientServicesKeepAliveInterval                 : 00:02:00
UseSimplifiedFilters                            : false
ExcelAddInAzureActiveDirectoryClientId          : 
DisableWriteInsideTryFunctions                  : true
ExtendedSecurityTokenLifetime                   : 0
ClientServicesIdleClientTimeout                 : MaxValue
ODataEnableExcelAddInAnnotations                : true
NavHttpClientMaxResponseContentSize             : 150
NavHttpClientMaxTimeout                         : 00:05:00
SqlParametersByOrdinal                          : true
ClientBuildRestriction                          : WarnClient
TraceLevel                                      : Normal
ExternalTraceLevel                              : Error
EnableDataExportImport                          : true
MaxStreamReadSize                               : 1000000
ValidAudiences                                  : 
DefaultLanguage                                 : 
SupportedLanguages                              : 
ApiServicesEnabled                              : True
ApiSubscriptionsEnabled                         : true
ApiSubscriptionExpiration                       : 3
ApiSubscriptionNotificationUrlTimeout           : 5000
ApiSubscriptionSendingNotificationTimeout       : 30000
ApiSubscriptionDelayTime                        : 30000
ApiSubscriptionMaxNumberOfNotifications         : 100
ApiSubscriptionMaxNumberOfSubscriptions         : 200
EnableSymbolLoadingAtServerStartup              : False
SqlLongRunningThreshold                         : 1000
SqlBulkImportBatchSize                          : 448
UseIncrementalCompanyDelete                     : true
TaskSchedulerSystemTaskStartTime                : 00:00:00
TaskSchedulerSystemTaskEndTime                  : 23:59:59
XmlMetadataCacheSize                            : 500
AllowSessionWhileSyncAndDataUpgrade             : false
SearchTimeout                                   : 00:00:10
OverwriteExistingTranslations                   : true
LockoutPolicyFailedAuthenticationCount          : 0
LockoutPolicyFailedAuthenticationWindow         : 0
ReplaceReportExecutionTimeWithClientTime        : true
UseFindMinusWhenPopulatingPage                  : true
DisableQueryHintOptimizeForUnknown              : false
DisableQueryHintForceOrder                      : true
DisableQueryHintLoopJoin                        : true
SecurityProtocol                                : Tls12
AzureKeyVaultClientId                           : 00000000-0000-0000-0000-000000000000
AzureKeyVaultClientCertificateStoreLocation     : LocalMachine
AzureKeyVaultClientCertificateStoreName         : My
AzureKeyVaultClientCertificateThumbprint        : 
AzureKeyVaultKeyUri                             :

**Comment by freddydk** [comment]
docker logs containername will output the log from when it started.

**Comment by gdrenteriag** [comment]
Thanks, here are. 
[LogMyAl.txt](https://github.com/microsoft/navcontainerhelper/files/3229525/LogMyAl.txt)

**Comment by NAVspecialist** [comment]
Have you tried to add 
-memoryLimit "3g" or -memoryLimit "4g"

**Comment by gdrenteriag** [comment]
Not really, I don't add this parameter. 
I only run this script. 

Compile-AppInNavContainer -containerName "myal" -credential $credential -appProjectFolder "C:\ProgramData\NavContainerHelper\AL\DemoSolution"

**Comment by NAVspecialist** [comment]
You have to add the parameter to your new-navcontainer

for instance my start looks like this

$Licensefile = "C:\Docker\NAVspecialist.flf"
$ImageName = "mcr.microsoft.com/businesscentral/onprem:dk"
$ContainerName = "spring"
$PlainTextPw = "Passw0rd"
$Credential = New-Object -TypeName PSCredential -ArgumentList $env:USERNAME,(ConvertTo-SecureString -String $PlainTextPw -AsPlainText -Force)
New-NavContainer -containerName $ContainerName -memoryLimit "3g" -alwaysPull -accept_eula -accept_outdated -auth NavUserPassword -Credential $Credential -imageName $ImageName -licenseFile $Licensefile -includeCSide -shortcuts Desktop -useBestContainerOS -updateHosts -verbose

and everything works quite fine - my docker-version and os is the same as yours.

**Comment by gdrenteriag** [comment]
I will run like yours script, thanks a lot, I tell you how it works

**Comment by freddydk** [comment]
For compiling the AL base app with spring release RTM you need a LOT more than 3G - more like 20G.
That is why process isolation is an advantage. I don't think you will be able to perform this on a machine with 16G without process isolation.

**Comment by gdrenteriag** [comment]
That process isolation, how it works?, what I need to perform it?.
If you say that so I need to find another solution and this means another machine, your experience tell me all.

**Comment by NAVspecialist** [comment]
Mine is running with process isolation perhaps that is why i have no issues.

**Comment by gdrenteriag** [comment]
Could you tell me, what I can do to get that?,

**Comment by freddydk** [comment]
If you specify memorylimit then you also won't be able to compile the base app.
I couldn't see anything from the log.
gdrenteriag - please re-run your new-navcontainer and copy/paste all output - here, then I can see what computer you have and how it works.

**Comment by gdrenteriag** [comment]
[LogMyAlversion2.txt](https://github.com/microsoft/navcontainerhelper/files/3229683/LogMyAlversion2.txt)

I send you that information.

**Comment by freddydk** [comment]
Yes, but I stated that I couldn't see enough information from the log - i need the full output.
I am on my way to bed, this is my last response.
You could go through the blog posts about navcontainerhelper from my blog and read about docker to understand these things more in detail - it is a steep learning curve and it might be worth the reading.
If your machine isn't big enough, you can use http://aka.ms/getbc to spin up a azure vm which runs docker in isolation mode and you can just specify 32gb ram - then everything works.

**Comment by gdrenteriag** [comment]
Thanks a lot Freddy,

**Comment by freddydk** [comment]
Update NavContainerHelper to 0.6.1.1 and remove -memorylimit in your new-navcontainer.

**Comment by freddydk** [comment]
Did this solve the issue?
