### ISSUE TITLE
Is There a Similar Function "Create-AlProjectFolderFromNavContainer" To OnPremise

### ISSUE THREAD

**Issue by gdrenteriag** [microsoft/navcontainerhelper#471]
Like this wonderful function Create-AlProjectFolderFromNavContainer, exists To work with  Local Database?

I means, Create-AlProjectFolderFromNAVDatabase, and this database isn't container, but in your machine installed.

I hope that I was clear. 

Thanks

**Comment by freddydk** [comment]
The reason for using containers is, that it makes it easier for me to describe how things are done (works the same way always) With on premises, I need to take care of database server versions, urls, locations etc. etc. it complicates things a lot.
Therefore, I can do much more when I can settle with containers. Having said that - everything is open source and you are welcome to decipher the functions and try to make them run without containers.

**Comment by gdrenteriag** [comment]
Totally clear, Ok. 
Thanks.
