### ISSUE TITLE
Debugging docker container from VS Code stops responding.

### ISSUE THREAD

**Issue by DavidRoys** [microsoft/navcontainerhelper#472]
NAV Container created with script as follows:

install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $true

$containername = 'BCNZ2'
$navdockerimage = 'microsoft/bcsandbox:nz'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using NavUserPassword Authentication. Please enter your credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters `
                 -licensefile "https://www.dropbox.com/somevalidlink.flf?dl=1"

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

Resonse from running the script is as follows...

PS C:\WINDOWS\system32> C:\Users\davidr\Downloads\Create-BCNZ.ps1
NavContainerHelper is version 0.6.1.1
Host is Microsoft Windows 10 Enterprise - 1703
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image microsoft/bcsandbox:nz-ltsc2016
nz-ltsc2016: Pulling from microsoft/bcsandbox
Digest: sha256:42645d0dce42173da187aa1fc649f780828c3b18a8f4c97c26a613ae6eee204c
Using image microsoft/bcsandbox:nz-ltsc2016
Removing C:\ProgramData\NavContainerHelper\Extensions\BCNZ2
Creating Nav container BCNZ2
Using license file https://www.dropbox.com/somevalidlink.flf?dl=1
Version: 14.0.29537.31808-NZ
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.15063.483 (1703)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using hyperv isolation
Downloading C:\ProgramData\NavContainerHelper\Extensions\BCNZ2\my\license.flf
Creating container BCNZ2 from image microsoft/bcsandbox:nz-ltsc2016
0ec7d766652f492c9f5057e30d260c93fb29cc8582f91ba686e24018a8f2f3bc
Waiting for container BCNZ2 to be ready
Initializing...
Starting Container
Hostname is BCNZ2
PublicDnsName is BCNZ2
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 334299499FCF56D8494C815BCEBD64DECF2427C2
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating DavidR as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Assign Premium plan for DAVIDR
Container IP Address: XXX.XXX.XXX.XXX
Container Hostname  : BCNZ2
Container Dns Name  : BCNZ2
Web Client          : http://BCNZ2/NAV/
Dev. Server         : http://BCNZ2
Dev. ServerInstance : NAV

Files:
http://BCNZ2:8080/al-3.0.106655.vsix

Initialization took 161 seconds
Ready for connections!
Reading CustomSettings.config from BCNZ2
Creating Desktop Shortcuts for BCNZ2
Nav container BCNZ2 successfully created
Downloading C:\Users\davidr\AppData\Local\Temp\CreateTestUsers.app
Copy C:\Users\davidr\AppData\Local\Temp\CreateTestUsers.app to container BCNZ2 (c:\run\CreateTestUsers.app)
Publishing c:\run\CreateTestUsers.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing CreateTestUsers on tenant default
Installing CreateTestUsers on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
You need to specify credentials when you are not using Windows Authentication
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.1\Api\Invoke-NavContainerApi.ps1:73 char:13
+             throw "You need to specify credentials when you are not u ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (You need to spe... Authentication:String) [], RuntimeException
    + FullyQualifiedErrorId : You need to specify credentials when you are not using Windows Authentication

Browser is Microsoft Edge 40.15063.0.0

VSCode 1.34.0. AL Language 3.0.126610 (from marketplace)

Windows 10 Enterprise 1703 build 15063.483 as host.

In order to reproduce this I set up a new container (as above and did an AL GO! completely clean project, then added some additional code to the hello world and set a breakpoint. I can send you a word document with details of what happened but basically the debugger will stop on the break point but stepping over causes the debugger to not go to the next command and the Web client stops responding.

**Comment by freddydk** [comment]
You are using a very very old Windows 10.
Any reason why this hasn't been updated? (Can it be updated? - 1809 or later uses images that only are half the size of ltsc2016)
Have you tried with other browsers?
Did you set the browser to use in VS Code - or is it the default browser?

Thanks

**Comment by shashiBssi** [comment]
Happening with me and one of my friends as well.

I am getting the same error in latest window 1903.it is using hyper v isolation.
I tried on latest build of 1809 also, it is also using hyper v isolation and the same issue is there.

I have not set the browser in vs code,it's default browser

Looks to me nst keep losing connection with debugger client in vs code.

**Comment by freddydk** [comment]
Shashi - please open a new issue and provide the same information as David (from your system)
Davids issue is likely caused by an old Windows and/or a wrong .vsix - we are investigating that and I want to be able to close this issue when Davids problem is solved.

**Comment by DavidRoys** [comment]
I tried updating Windows to a later version and this did not fix the issue. I applied the changes to my NAV Instance as suggested in [Freddy's blog post](https://community.dynamics.com/business/b/freddysblog/archive/2019/06/03/debugging-hangs-in-business-central-spring-2019-rtm-and-cu1) and this fixed the issue.
