### ISSUE TITLE
Initialization of Container failed.

### ISSUE THREAD

**Issue by KristofKlein** [microsoft/navcontainerhelper#473]
Hi,

I have some problems to spin up a new container:

> NavContainerHelper is version 0.6.1.1
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 19.03.0-beta3
Docker Server Version is 19.03.0-beta3
Using image bcinsider.azurecr.io/bcsandbox-master:14.0.28630.0-al-ltsc2019
Removing container BCIP
Removing BCIP from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\BCIP
Creating Nav container BCIP
Version: 14.0.28630.0-W1
Platform: 14.0.28496.0
Generic Tag: 0.0.9.1
Container OS Version: 10.0.17763.253 (ltsc2019)
Host OS Version: 10.0.17763.503 (ltsc2019)
Using process isolation
Creating container BCIP from image bcinsider.azurecr.io/bcsandbox-master:14.0.28630.0-al-ltsc2019
302f0df57dfec00915fc1a5ec627929547cd3084096b10751a49f33e6fef65c5
Waiting for container BCIP to be ready
Initializing... 

so far so good! But when it hits the line Startin Service Tier the followin error happens:
Service 'Dynamics 365 Business Central Server [NAV] (MicrosoftDynamicsNavServer$NAV)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$NAV on computer '.'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 137
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1

If I use in the same command prompt isolation hyperV everything is fine....
Also be aware of that it is the AL Version of BC. Would be nice to get some help. I struggle with this process isolation now for quite some time (due to various issues). 

Br. Kristof

**Comment by freddydk** [comment]
I assume that you specify -isolation process yourself above.
If you do not specify isolation, NavContainerHelper will investigate and default isolation.
In your case, it will default to process isolation (and fail), but it will write this warning:

WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv

Process isolation might fail when the host and container os doesn't match 100%.
Hyperv works fine - and in your case I would recommend using hyperv

having said that - why would you use the "old" AL container - that is very old and you wouldn't learn much from that.

**Comment by NAVspecialist** [comment]
Have you tried to do exactly the same on a docker 18.09.x version? ( I can see you are running the betaversion -  19.03.0-beta3) ?

**Comment by KristofKlein** [comment]
@NAVspecialist Don't ask why I'm running edge ... 
@freddydk you are right about the "warning" and the default isolation.

About the old container. This was just one that I found "fast". I think I actually picked it up from here:
https://community.dynamics.com/business/b/businesscentraldevitpro/archive/2019/02/26/developer-preview-february-2019.

**Comment by KristofKlein** [comment]
Hm - i just found out that I can not find out how to find out the correct AL only docker image!? Please en-light my oh great evangelist! I promise I will close the Issue afterwards  :)

**Comment by freddydk** [comment]
That is good.
Because they do not exist.
I have a blog post series on my blog freddysblog.com explaining how to convert a C/AL spring release container to an AL container - but that is what we have.
We will resume insider builds from master sometime in June (no promises given) where we are AL only.

**Comment by KristofKlein** [comment]
Thank you!
