### ISSUE TITLE
Installation Errors: Unable to resolve package source /  could not get response from query

### ISSUE THREAD

**Issue by Kowa63** [microsoft/navcontainerhelper#475]
I tried to update, and after failing in the attempt, to re-install the module on a notebook where 0.4.3.0 was installed, but neither method works, even after removing the old version. Any hints on how to get this off the ground again?

![grafik](https://user-images.githubusercontent.com/16236672/58761170-6f688500-8541-11e9-9a38-2925157addb6.png)

![grafik](https://user-images.githubusercontent.com/16236672/58761138-0b45c100-8541-11e9-9ab5-b49bb4317ced.png)

**Comment by Kowa63** [comment]
This seems to be the cause. 
https://github.com/PowerShell/PowerShell/issues/7827
https://github.com/PowerShell/PowerShellGet/issues/349

**Comment by freddydk** [comment]
Sorry, have never seen this before.
You can also get the containerhelper by cloning the git repository from this repo and run the NavContainerHelper.ps1 script from the root folder.

**Comment by Kowa63** [comment]
Two older PS add-ons seem to be the cause of this.
After deactivating both the script browser and the module browser in the profile file I finally got this working again.
https://devblogs.microsoft.com/scripting/a-favorite-powershell-ise-feature-script-browser/
https://www.microsoft.com/en-us/download/details.aspx?id=45885
