### ISSUE TITLE
Debugging docker container from VS Code stops responding.

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/navcontainerhelper#476]
NAV Container created with script as follows:

New-NavContainer -containerName Prod2 -accept_eula -auth NavUserPassword -doNotExportObjectsToText -imageName mcr.microsoft.com/businesscentral/sandbox:us -includeCSide   -licenseFile "D:\My-D365BC.flf" -updateHosts -useBestContainerOS

Resonse from running the script is as follows...

NavContainerHelper is version 0.6.1.0
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Creating Nav container Prod2
Using license file D:\My-D365BC.flf
Version: 14.1.32615.0-US
Platform: 14.0.32600.0
Generic Tag: 0.0.9.7
Container OS Version: 10.0.17763.503 (ltsc2019)
Host OS Version: 10.0.17763.529 (ltsc2019)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using hyperv isolation
Creating container Prod2 from image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
aa321785bda978a664994ea62b48784b76441ea16cdcf38cbf7a272e8b8703da
Waiting for container Prod2 to be ready
Initializing...
Starting Container
Hostname is Prod2
PublicDnsName is Prod2
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 81B5C07C5AFCCA6E31611927B3273FB6A0C436C0
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating sv as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: xxx.xx.XXX.XX
Container Hostname  : Prod2
Container Dns Name  : Prod2
Web Client          : http://Prod2/NAV/
Dev. Server         : http://Prod2
Dev. ServerInstance : NAV

Files:
http://Prod2:8080/al-3.0.124247.vsix

Initialization took 104 seconds
Ready for connections!
Reading CustomSettings.config from Prod2
Creating Desktop Shortcuts for Prod2
Nav container Prod2 successfully created

Browser is Chrome Version 74.0.3729.169

Version: 1.34.0   AL Language 3.0.126610 (from marketplace)
Windows 10 Enterprise 1809 build 17763.529 as host. (Same issue with 1903)

In order to reproduce this I set up a new container. Basically the debugger will stop on the break point but stepping over causes the debugger to not go to the next command and the Web client stops responding.

The app i published on another system with process isolation works perfectly fine.

**Comment by richardrobberse** [comment]
I'm having the exact same issue:
Windows 10 Pro: 1809 (17763.503)
AL Language:  3.0.126610 (from the marketplace), same issue with the VSIX from the container (3.0.124247)
Docker image: mcr.microsoft.com/businesscentral/onprem:14.1.32615.0-w1

**Comment by freddydk** [comment]
So after upgrading to Windows 1903 - it works again???

**Comment by richardrobberse** [comment]
Yes, I've upgraded to 1903 and recreated my container, not sure if Shasi also recreated the container.
I used the AppInsights app from the BCTech repository to repro, but I had the debugging issue with any app.

**Comment by shashiBssi** [comment]
I first got the issue on new pc with 1903.

Then I downgraded to 1803. Still the same issue.

**Comment by richardrobberse** [comment]
I will also upgrade my personal machine to 1903 when I have time, I'll let you know the outcome.
If there are any things you would like to test/check on that machine, please let me know.

**Comment by freddydk** [comment]
I think I have a repro now.

**Comment by freddydk** [comment]
Could you guys try to create your container with  -additionalParameters @('--cpu-count 4')

**Comment by shashiBssi** [comment]
@freddydk 

tested on Windows 10 Enterprise 1809 build 17763.529 as host.

Looks Good.

Hope will also solve on 1903.

**Comment by freddydk** [comment]
https://freddysblog.com/2019/06/03/debugging-hangs-in-business-central-spring-2019-rtm-and-cu1/
