### ISSUE TITLE
add app name parameter for Compile-AppInNavContainer

### ISSUE THREAD

**Issue by nlreturns** [microsoft/navcontainerhelper#477]
The company I am working at will soon be using the navcontainer for building .app files. Our company name is quite long, and we would rather use a shorter .app file. My work-around solution for now is to change my build scripts to empty the values in the app.json, which isn't ideal.

Can we get a --appname parameter for this function?

**Comment by freddydk** [comment]
Sounds like a reasonable suggestion. Will check with the modern dev. team whether they have any plans to do the same before going in a different direction, stay tuned.

**Comment by freddydk** [comment]
Shipped in 0.6.1.3
