### ISSUE TITLE
Issue with Permission set in Latest Container

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#478]
I created a container with standard license. Please find the powershell command below (I used to create the container)

New-NavContainer -containerName PSTest -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -updateHosts

I then installed my product runtime package in the container.
I went to the user card and assigned my product permission set and D365 BUSS FULL  permission set
![image](https://user-images.githubusercontent.com/38437776/58853498-61088f00-864f-11e9-8645-06979531f5e7.png)

In D365 BUS FULL ACCESS we have following permissions for table data – Sales Invoice Line (113)

![image](https://user-images.githubusercontent.com/38437776/58853529-86959880-864f-11e9-8a2e-3cc7813ffa16.png)

In our BSSI SB Permission Set we have following permission for table data – Sales Invoice Line (113)

![image](https://user-images.githubusercontent.com/38437776/58853574-a331d080-864f-11e9-9c11-84bfcc24d181.png)

Now we have extended table 113 to add a column.
Now when user create sales invoice and post the sales invoice, we have functionality in our extension, to update the value in that extended column in table 113.
Now, when user post the sales invoice, we are getting the below error

![image](https://user-images.githubusercontent.com/38437776/58853600-b775cd80-864f-11e9-96c1-5d6ec42dec48.png)

I get the same error when I replace the D365 BUS FULL permission set with super permission set

![image](https://user-images.githubusercontent.com/38437776/58853633-d5433280-864f-11e9-8f3f-647483c2b4fc.png)

How ever I don't get this error when I create the container with license file and follow the same steps

**New-NavContainer -containerName SB -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -licenseFile "C:\Work\SB-D365BC.flf" -updateHosts**

Please help me on this. 
I need to know the following

1) Can ISV permission set replace standard D365 BC permission to a specific table. IN this case, I was trying to give full access to 113 using my BSSI SB permission set
2) Ho to resolve this issue as I am getting the same error even with super permission set.

**Comment by freddydk** [comment]
I think what you see here is, that permission sets cannot give you access to anything your license doesn't.

**Comment by Bssivivek** [comment]
@freddydk thanks a lot for your response. I looked into it and this is what i found. Please confirm if i am right

1) 3rd party permission set with permission scope = Tenant cannot override system permission set.
2) If any object (ex: code unit) wants to read/insert/modify/delete any table where the permission is indirect, we need to explicitly  specify the permission for that table data in that code unit.

Please let me know if i am right.

**Comment by freddydk** [comment]
You might be, but this has nothing to do with containers and I do not have detailed knowledge into everything, sorry.

**Comment by Bssivivek** [comment]
@freddydk thanks a lot. I just added my comments/findings so that it might be useful for other developers facing same issue.
You can close this ticket.
