### ISSUE TITLE
Not able to create container with -bakFile

### ISSUE THREAD

**Issue by ashikkrux** [microsoft/navcontainerhelper#480]
I am unable to create a container when used with -bakFile tag. 

PS C:\WINDOWS\system32> New-NavContainer -containerName demo -accept_eula -auth NavUserPassword -bakFile "D:\Ashik Download\database.bak" -accept_outdated -alwaysPull -assignPremiumPlan -doNotExportObjectsToText -imageName mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019 -includeCSide -licenseFile "****" -shortcuts Desktop -updateHosts -additionalParameters ("--env CustomNavSettings=EnableThreadThrottling=False,EnablePrioritizedThreadThrottling=False")
NavContainerHelper is version 0.6.1.1
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Pulling image mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019
gb-ltsc2019: Pulling from businesscentral/sandbox
Digest: sha256:3abda4e6e129bace08ffaacf076aec8c27b0746f9b2e91fcc28a8a0774cf7524
Using image mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019
Removing container demo
Removing demo from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\demo
Creating Nav container demo
Using license file ******.flf
Version: 14.1.32615.0-GB
Platform: 14.0.32600.0
Generic Tag: 0.0.9.7
Container OS Version: 10.0.17763.503 (ltsc2019)
Host OS Version: 10.0.18362.116 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using hyperv isolation
Creating container demo from image mcr.microsoft.com/businesscentral/sandbox:gb-ltsc2019
b51db7eb57ba05ca42e0483fd57a248db61eb81d78a99a3a2e186b167fd54323
Waiting for container demo to be ready
Initializing...
Starting Container
Hostname is demo
PublicDnsName is demo
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'C:\ProgramData\NavContainerHelper\Extensions\demo\database.bak'
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 612DE2EB4A8642714256EEB5DC74178C43760AF1
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Creating EnableThreadThrottling and setting it to False
Creating EnablePrioritizedThreadThrottling and setting it to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 151
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is demo
PublicDnsName is demo
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'C:\ProgramData\NavContainerHelper\Extensions\demo\database.bak'
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 612DE2EB4A8642714256EEB5DC74178C43760AF1
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Creating EnableThreadThrottling and setting it to False
Creating EnablePrioritizedThreadThrottling and setting it to False
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 151
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container demo failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.1\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container demo failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container demo failed

**Comment by freddydk** [comment]
It is likely because the .bak file is of a different version.
Currently, it is trying to convert the .bak file upon container creation, but that fails if there are extensions installed (I think).
I might try to create a function, which can upgrade a database from one version to another.

**Comment by freddydk** [comment]
Did you make it work?

**Comment by JuditNavarro** [comment]
Hello @freddydk ,
I executed the first script of [this article](https://blogs.msdn.microsoft.com/freddyk/2018/03/20/navcontainerhelper-specify-your-own-database-backup-file-to-use-with-a-nav-container/)  to generate a new container but using my own database and adding property -accept_outdated: and it generates the same error. 

I paste the execution lines of my powershell to show the error (I removed the secure url used to the license file and the backfile):
> NavContainerHelper is version 0.6.0.15
> Host is Microsoft Windows 10 Enterprise - ltsc2019
> Docker Client Version is 18.06.1-ce
> Docker Server Version is 18.06.1-ce
> Pulling image microsoft/dynamics-nav:latest-ltsc2019
> latest-ltsc2019: Pulling from microsoft/dynamics-nav
> Digest: sha256:d9eb1c11dd752818b37377ea47083bb809c1ef9beb415ede3089a188258b8817
> Status: Image is up to date for microsoft/dynamics-nav:latest-ltsc2019
> Using image microsoft/dynamics-nav:latest-ltsc2019
> Removing container RestDatosBK
> Removing C:\ProgramData\NavContainerHelper\Extensions\RestDatosBK
> Creating Nav container RestDatosBK
> Using license file **(SECURE URL)**
> Version: 11.0.29745.0-W1
> Generic Tag: 0.0.9.3
> Container OS Version: 10.0.17763.379 (ltsc2019)
> Host OS Version: 10.0.17763.557 (ltsc2019)
> Using hyperv isolation
> Downloading C:\ProgramData\NavContainerHelper\Extensions\RestDatosBK\my\license.flf
> Creating container RestDatosBK from image microsoft/dynamics-nav:latest-ltsc2019
> c17e9f9b5d35709d09eb40b0e26a96c7d109fa7495c885dba24ad6704a33b24b
> Waiting for container RestDatosBK to be ready
> Initializing...
> Starting Container
> Hostname is RestDatosBK
> PublicDnsName is RestDatosBK
> WARNING: Container starts with TimeZone = Hora estÃ¡ndar GMT, which is not recognized in the list of TimeZones.
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Downloading database backup file **(SECURE URL)**
> The database restore operation failed due to the following error returned by SQL Server:
> The media family on device 'c:\Run\mydatabase.bak' is incorrectly formed. SQL Server cannot process this media family.
> RESTORE HEADERONLY is terminating abnormally.
> at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 48
> at <ScriptBlock>, C:\Run\navstart.ps1: line 108
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1Error
> Initializing...
> Starting Container
> Hostname is RestDatosBK
> PublicDnsName is RestDatosBK
> WARNING: Container starts with TimeZone = Hora estÃ¡ndar GMT, which is not recognized in the list of TimeZones.
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Downloading database backup file **(SECURE URL)**
> The database restore operation failed due to the following error returned by SQL Server:
> The media family on device 'c:\Run\mydatabase.bak' is incorrectly formed. SQL Server cannot process this media family.
> RESTORE HEADERONLY is terminating abnormally.
> at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 48
> at <ScriptBlock>, C:\Run\navstart.ps1: line 108
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1
> Initialization of container RestDatosBK failed
> En C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.15\ContainerHandling\Wait-NavContainerReady.ps1: 45 Carácter: 17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization ...tDatosBK failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container RestDatosBK failed

The database that I wanted to use was a backup of another container, created with the same image, so the SQL version it's the same one... And I previously restored it in the docker and it was restored correctly.

 If I can help with more information or some test to help you, just ask me, please.

**Comment by freddydk** [comment]
What technology do you use as secure URL?
Are you sure that the URL is a direct link? and not a link to a page, where you can download the file?

**Comment by JuditNavarro** [comment]
Hi again @freddydk,
I use [this article](https://blogs.msdn.microsoft.com/freddyk/2017/02/26/create-a-secure-url-to-a-file/) to create a secure URL via dropbox, but the script didn't work, so I try  [this tutorial](https://www.lmeservices.com/share-google-drive-files-via-url/ ) to make a secure URL via google drive and it didn't work too. Before use the secure urls, I tried them and they worked perflectly, so...

**Comment by freddydk** [comment]
With the google drive secure link - I don't think the URL is a direct download (database restore fails)
try to use
Download-File -SourceUrl <secureurl> -DestinationFile <filename>
I think you get a HTML file - this line needs to return the .bak file
The DropBox sample looks like it restores the correctly (i.e. the url is ok)
Try to use Get-NavContainerEventLog containername and get the eventlog to see what is wrong.
I assume the .bak file has a wrong version number or like.

**Comment by JuditNavarro** [comment]
Hello @freddydk,
I tried some tests: 
First, I use the command _Download-File -SourceUrl -DestinationFile_ with the backup file, and I put it on my dropbox to made the secure URL with it. I use it on the script and it showed the same error: 

> NavContainerHelper is version 0.6.0.15
> Host is Microsoft Windows 10 Enterprise - ltsc2019
> Docker Client Version is 18.06.1-ce
> Docker Server Version is 18.06.1-ce
> Pulling image microsoft/dynamics-nav:latest-ltsc2019
> latest-ltsc2019: Pulling from microsoft/dynamics-nav
> Digest: sha256:d9eb1c11dd752818b37377ea47083bb809c1ef9beb415ede3089a188258b8817
> Status: Image is up to date for microsoft/dynamics-nav:latest-ltsc2019
> Using image microsoft/dynamics-nav:latest-ltsc2019
> Removing container RestDatosBK
> Removing C:\ProgramData\NavContainerHelper\Extensions\RestDatosBK
> Creating Nav container RestDatosBK
> Using license file **(SECURE URL)**
> Version: 11.0.29745.0-W1
> Generic Tag: 0.0.9.3
> Container OS Version: 10.0.17763.379 (ltsc2019)
> Host OS Version: 10.0.17763.557 (ltsc2019)
> Using hyperv isolation
> Downloading C:\ProgramData\NavContainerHelper\Extensions\RestDatosBK\my\license.flf
> Creating container RestDatosBK from image microsoft/dynamics-nav:latest-ltsc2019
> 39d5bc859faecb30ac1368f74fb2b05e1a7019659e0e6ec2d454cd29292c282a
> Waiting for container RestDatosBK to be ready
> Initializing...
> Starting Container
> Hostname is RestDatosBK
> PublicDnsName is RestDatosBK
> WARNING: Container starts with TimeZone = Hora estÃ¡ndar GMT, which is not recognized in the list of TimeZones.
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Downloading database backup file  **(SECURE URL)**
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint 8D255CD928CD6D9FAB4AC1F8AF26F3FDED45094A
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Creating DotNetCore Web Server Instance
> Using license file 'c:\run\my\license.flf'
> Import License
> ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
> at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
> at <ScriptBlock>, C:\Run\navstart.ps1: line 151
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1Error
> Initializing...
> Starting Container
> Hostname is RestDatosBK
> PublicDnsName is RestDatosBK
> WARNING: Container starts with TimeZone = Hora estÃ¡ndar GMT, which is not recognized in the list of TimeZones.
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Downloading database backup file **(SECURE URL)**
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint 8D255CD928CD6D9FAB4AC1F8AF26F3FDED45094A
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Creating DotNetCore Web Server Instance
> Using license file 'c:\run\my\license.flf'
> Import License
> ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
> at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
> at <ScriptBlock>, C:\Run\navstart.ps1: line 151
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1
> Initialization of container RestDatosBK failed
> En C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.15\ContainerHandling\Wait-NavContainerReady.ps1: 45 Carácter: 17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization ...tDatosBK failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container RestDatosBK failed
>  

I use the command Get-NavContainerEventLog with the container that is generated by the script and I found 2 error messages:
![image](https://user-images.githubusercontent.com/44970454/60950278-bf7bf980-a2ee-11e9-8f8e-940b07770d77.png)

![image](https://user-images.githubusercontent.com/44970454/60950343-dc183180-a2ee-11e9-93a2-cff5da1865dd.png)

I understand that It's seems like it's a problem of the version number... I'm sure that the backup file is not corrupted, because some days ago, I conected to the docker server via SQL Server Management Studio thanks to its IPAddress, and I was able to restore the backup that I made manually in there because it has the same version, but I was not able to restore it locally in my pc

**Comment by freddydk** [comment]
The bak file is made by a different version of NAV (a newer version) - that is what it says.
You cannot mount a newer backup on an older NAV.

**Comment by JuditNavarro** [comment]
Sorry @freddydk but, I don't really understand, how is it possible that my backup has a newer version of NAV, if I used the same Image to create that backup and to generate the new container? They should be the same version because of that, isn't it?  

And as I said before, I was able to restore it manually in the docker's server, but not locally because of the version, so I don't see why it's saying that error it the different version is locally on my pc, not in the image that is using...

**Comment by freddydk** [comment]
If you are asking me to guess why this goes wrong, I can't.
I can however show you one of my tests:
```
# Settings
$imageName = Get-BestNavContainerImageName -imageName "mcr.microsoft.com/dynamicsnav:2018"
$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)

New-NavContainer -accept_eula `
                 -imageName $imageName `
                 -containerName nav `
                 -auth $auth `
                 -Credential $Credential `
                 -updateHosts `
                 -includeTestToolkit -includeTestLibrariesOnly

Backup-NavContainerDatabases -containerName nav -sqlCredential $credential -bakFolder C:\programdata\NavContainerHelper\mybak

New-NavContainer -accept_eula `
                 -imageName $imageName `
                 -containerName nav2 `
                 -auth $auth `
                 -Credential $Credential `
                 -updateHosts `
                 -bakFile "C:\ProgramData\NavContainerHelper\mybak\database.bak"
```

Which as you can see, spins up a container, creates a .bak file and spins up another container based on that .bak file - that works.

So whatever is wrong with the .bak file - I don't know.

**Comment by JuditNavarro** [comment]
I tried with your test but using the image that I was using (mcr.microsoft.com/businesscentral/onprem:es-ltsc2019) and when It's going to take the database.bak, it didn't found the path where the backup is saved, so maybe it's something related to business central image, I don't know... 

Even so, thank you for your help and for your patience, @freddydk  :)

**Comment by freddydk** [comment]
and is there anything in this folder then C:\programdata\NavContainerHelper\mybak

**Comment by freddydk** [comment]
Just tried to modify my script from above to use the image you suggest - it works fine.
You must be doing a typo or not including all information here.
Like, i have no idea what this: "when It's going to take the database.bak, it didn't found the path where the backup is saved, " refers to - which error do you get?
You are running a navcontainerhelper which isn't the newest, but I don't think anything has changed, that should cause this not to work.
