### ISSUE TITLE
Cannot connect webclient with hostname within and outside container

### ISSUE THREAD

**Issue by anwar0206** [microsoft/navcontainerhelper#491]
Hi, Created a fresh VM with http://aka.ms/getbc with following image
mcr.microsoft.com/businesscentral/onprem:1904-cu1-w1-ltsc2019 and **traefik** switch set to **Yes**

The VM is spin with all the necessary files, then executed setupVM.ps1 container is ready, 

But cannot access the webclient with publicdnsname within and outside the vm.

Can ping the container "navserver"
Can access the landing page within and outside the VM.
Can access the webclient with Container IP
Can access the RTC.

What could be the issue, all the necessary ports are configured in azure portal.
Is there anything needs to be done if using traefik switch.

Regards,

**Comment by freddydk** [comment]
0.6.1.2 of NavContainerHelper had an issue with traefik.
Issue should be fixed in 0.6.1.3 - testing this myself now.
