### ISSUE TITLE
Question : using traefik, allow more ports

### ISSUE THREAD

**Issue by vempathi4sir** [microsoft/navcontainerhelper#496]
Good Day
I would like to request your help regarding the additional ports on the IIS site using traefik.
I am currently multiple containers on a single host , along with the standard NAV ports, I would also like to add few more ports to be exposed on the container ,how do I add them to traefik file ,which labels do I need to edit

Thank you in advance.

**Comment by freddydk** [comment]
If you look in New-NavContainer around line 956 - it specifies a number of parameters to the container specifying which ports should be redirected.
I would assume you could add more in -additionalParameters - but I have not tried/had the need.

**Comment by vempathi4sir** [comment]
Thanks much freddy
I will give a try on this.
Have a nice Day
