### ISSUE TITLE
Unable to download symbols

### ISSUE THREAD

**Issue by Pellic** [microsoft/navcontainerhelper#497]
Hi,
I get an error when downloading Symbols:
[2019-06-15 08:44:07.06] Sending request to http://cap140-live:7349/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2019-06-15 08:44:07.37] Error: An error occurred while sending the request.
The remote server returned an error: (401) Unauthorized.
The target principal name is incorrect

web client and win client runs without issues and old dev with object designer is ok too.
I have created the container with the following script:

$databaseCredential = New-Object System.Management.Automation.PSCredential -argumentList $UserName, (ConvertTo-SecureString -String $Password -AsPlainText -Force)

#NAV SERVICE
$ClientServices = 7346
$SoapServices = 7347
$ODataServices = 7348
$DeveloperServices = 7349
$PublishPortParameters = " -p 8383:80 -p 8380:8080 -p 10445:443 -p ${ClientServices}-${DeveloperServices}:${ClientServices}-${DeveloperServices}"
$NavBuild = "140"
$imageName = "mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019"

#Public container for external access
$shortcuts = "Desktop"
$licenseFile = "E:\ContainerFiles\licenza\5165051.flf"
$ContainerName = $databaseName -replace "_","-"

#for gMSA
$gMSAParameter = "--security-opt credentialspec=file://venere_dcksql2017dev.json"
$additionalParameters = @("$gMSAParameter$PublishPortParameters")

New-NavContainer -accept_eula `
                 <#-useSSL#> `
                 -containerName $ContainerName `
                 -imageName $imageName `
                 -Auth Windows `
                 -Credential $navcredential `
                 -databaseServer $databaseServer `
                 -databaseInstance $databaseInstance `
                 -databaseName $databaseName `
                 -databaseCredential $databaseCredential `
                 -updateHosts `
                 -licenseFile $licenseFile `
                 <#-myScripts @(".\Amin\SetupCertificate.ps1", "C:\temp\navdemo.net.pfx")#> `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -shortcuts $shortcuts `
                 -additionalParameters $additionalParameters `
                 -ClientServicesPort $ClientServices `
                 -SoapServicesPort $SoapServices `
                 -ODataServicesPort $ODataServices `
                 -DeveloperServicesPort $DeveloperServices `
                 -enableSymbolLoading

The output shows:
PS C:\Windows\system32> \\tsclient\C\bkp pc lavoro\CegekaDockerEnv\Cegeka Docker Env\Scripts\CGK Dev Containers\CAP140-LIVE.ps1
NavContainerHelper is version 0.6.1.2
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Using image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
Removing container CAP140-LIVE
Removing CAP140-LIVE from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\CAP140-LIVE
Creating Container CAP140-LIVE
Using license file E:\ContainerFiles\licenza\5165051.flf
Version: 14.0.29537.32452-it
Platform: 14.0.29530.32339
Generic Tag: 0.0.9.7
Container OS Version: 10.0.17763.503 (ltsc2019)
Host OS Version: 10.0.17763.379 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using process isolation
Creating container CAP140-LIVE from image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
fc9531b845cdd72b41a6c48c1f187cd72544d5c305cd8d63d5f3c4066099638e
Waiting for container CAP140-LIVE to be ready
Initializing...
Starting Container
Hostname is CAP140-LIVE
PublicDnsName is CAP140-LIVE
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user Admin
Container IP Address: 172.30.250.159
Container Hostname  : CAP140-LIVE
Container Dns Name  : CAP140-LIVE
Web Client          : http://CAP140-LIVE/NAV/
Dev. Server         : http://CAP140-LIVE
Dev. ServerInstance : NAV

Files:
http://CAP140-LIVE:8080/al-3.0.106655.vsix

Initialization took 78 seconds
Ready for connections!
Reading CustomSettings.config from CAP140-LIVE
Creating Desktop Shortcuts for CAP140-LIVE
Container CAP140-LIVE successfully created

I have even tried to remove the ssl switch with the same result

**Comment by freddydk** [comment]
You have specified Windows authentication - and the user name is admin.
is your Windows Username really admin???
If using Windows Authentication you need to create the container with the same username/password as your AD user - AND you need to be on the network and able to contact the AD server.
Alternatively - shift to NavUserPassword auth. - it always works.

**Comment by Pellic** [comment]
Hi Freddy,
thankyou for the quick answer.
I remove the authentication section from my previous post
$NavUserName = "Admin"
$NavPassword = "1qaz!QAZ"
$navcredential = New-Object System.Management.Automation.PSCredential -argumentList $NavUserName, (ConvertTo-SecureString -String $NavPassword -AsPlainText -Force)

The docker host is win 2019 in Active Directory, I use gmsa for authentication and it works perfectly even outside the host with specific port mapping.
The DB is an external docker sql machine in the same host, and all services runs without issues.
I can connect to old object dev env, win client, debugger, ecc.
The only issue is with modern AL

**Comment by freddydk** [comment]
How does your launch.json look?

**Comment by Pellic** [comment]
hi,
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://cap140-live",
            "port": 7349,
            "serverInstance": "NAV",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true
        }
    ]
}
tried even with "authentication": "Windows"
, with "server": "http://localhost"
,with "server": <container IP>
and "server": <docker host IP>

**Comment by freddydk** [comment]
When you say you remove authentication - did you then specify NavUserPassword?
Every time you change something - please dump the full command and output here, thanks

**Comment by Pellic** [comment]
I was thinking about a porkaround and I would appreciate your opinion.
Is a reasonable solution to run another container in process isolation with the same db connection parameter and different authentication (Navuserpassword) just to expose dev port?

**Comment by Pellic** [comment]
sorry I was sayng that I have just remove the auth section from my previous post to avoid sharing internal password.
Anyway I shared the complete script:
#DATABASE:
$DockerSQL = "DCKSQL2017DEV"
$SqlIP = docker inspect --format '{{.NetworkSettings.Networks.nat.IPAddress}}' $DockerSQL
$databaseServer = $DockerSQL
$databaseInstance = ""
$databaseName = "CAP140-LIVE"
$UserName = "sa"
$Password = "1qaz!QAZ"
$databaseCredential = New-Object System.Management.Automation.PSCredential -argumentList $UserName, (ConvertTo-SecureString -String $Password -AsPlainText -Force)

#NAV SERVICE
$shortcuts = "Desktop"
$licenseFile = "E:\ContainerFiles\licenza\5165051.flf"
$ContainerName = $databaseName -replace "_","-"
$ClientServices = 7346
$SoapServices = 7347
$ODataServices = 7348
$DeveloperServices = 7349
$PublishPortParameters = " -p 8383:80 -p 8380:8080 -p 10445:443 -p ${ClientServices}-${ODataServices}:${ClientServices}-${OdataServices}"
$PublishPortParametersAL = " -p ${DeveloperServices}:${DeveloperServices}"
$NavBuild = "140"
$imageName = "mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019"
$NavUserName = "Admin"
$NavPassword = "1qaz!QAZ"
$navcredential = New-Object System.Management.Automation.PSCredential -argumentList $NavUserName, (ConvertTo-SecureString -String $NavPassword -AsPlainText -Force)
if ($navcredential -eq $null -or $navcredential -eq [System.Management.Automation.PSCredential]::Empty)
{
    $navcredential = get-credential -UserName "admin" -Message "Enter NAV Super User Credentials"
}

#Additional parameters examples
$workspaceFolder = (Get-Item (Join-Path $PSScriptRoot "..")).FullName
$additionalParameters = @("--volume ""${workspaceFolder}:C:\Source""") 
$additionalParameters = @("--env clickonce=Y")
$addInsFolder = "C:\temp\addins"
$additionalParameters = @("--volume ${addInsFolder}:c:\run\Add-Ins")

#Public container for external access
#for gMSA
"${ContainerName}.milano.brainforce.it" -ServicePrincipalNames "host/CAP140-DEV", "host/${ContainerName}.milano.brainforce.it" -PrincipalsAllowedToRetrieveManagedPassword "DockerHosts" -ErrorAction SilentlyContinue
$gMSAParameter = "--security-opt credentialspec=file://venere_dcksql2017dev.json"
$additionalParameters = @("$gMSAParameter$PublishPortParameters --volume E:\ContainerFiles\licenza:c:\license")
$additionalParametersAL = @("$PublishPortParametersAL --volume E:\ContainerFiles\licenza:c:\license")
$myScripts = @("C:\Users\emiliape\Desktop\CegekaDockerBC\Scripts\nav-docker-samples-grant-user-access\nav-docker-samples-grant-user-access\AdditionalSetup.ps1", "C:\Users\emiliape\Desktop\CegekaDockerBC\Scripts\nav-docker-samples-grant-user-access\nav-docker-samples-grant-user-access\setupDevDbAccess.ps1", "C:\Users\emiliape\Desktop\CegekaDockerBC\Scripts\nav-docker-samples-grant-user-access\nav-docker-samples-grant-user-access\setupDevNavUsers.ps1")#> `

New-NavContainer -accept_eula `
                 -useSSL `
                 -containerName $ContainerName `
                 -imageName $imageName `
                 -Auth Windows `
                 -Credential $navcredential `
                 -databaseServer $databaseServer `
                 -databaseInstance $databaseInstance `
                 -databaseName $databaseName `
                 -databaseCredential $databaseCredential `
                 -updateHosts `
                 -licenseFile $licenseFile `
                 <#-myScripts @(".\Amin\SetupCertificate.ps1", "C:\temp\navdemo.net.pfx")#> `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -shortcuts $shortcuts `
                 -additionalParameters $additionalParameters `
                 -ClientServicesPort $ClientServices `
                 -SoapServicesPort $SoapServices `
                 -ODataServicesPort $ODataServices `
                 -enableSymbolLoading

New-NavContainer -accept_eula `
                 <#-useSSL#> `
                 -containerName "AL-$ContainerName" `
                 -imageName $imageName `
                 -Auth NavUserPassword `
                 -Credential $navcredential `
                 -databaseServer $databaseServer `
                 -databaseInstance $databaseInstance `
                 -databaseName $databaseName `
                 -databaseCredential $databaseCredential `
                 -updateHosts `
                 -additionalParameters $additionalParametersAL `
                 -licenseFile $licenseFile `
                 -doNotExportObjectsToText `
                 -DeveloperServicesPort $DeveloperServices `
                 -enableSymbolLoading

#Set ClientUserSettings.config
$CustomConfigFile = "C:\ProgramData\NavContainerHelper\Extensions\${ContainerName}\Program Files\${NavBuild}\RoleTailored Client\ClientUserSettings.config"
Write-Host "Modifying NAV ClientUserSetting Config File for Docker"
Write-Host $CustomConfigFile
$CustomConfig = [xml](Get-Content $CustomConfigFile)
$customConfig.SelectSingleNode("//appSettings/add[@key='Server']").Value = "$ContainerName"
$CustomConfig.Save($CustomConfigFile)

and the output is:

PS C:\Windows\system32> \\tsclient\C\bkp pc lavoro\CegekaDockerEnv\Cegeka Docker Env\Scripts\CGK Dev Containers\BcGenericLast.ps1
NavContainerHelper is version 0.6.1.2
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Using image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
Removing container CAP140-LIVE
Removing CAP140-LIVE from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\CAP140-LIVE
Creating Container CAP140-LIVE
Using license file E:\ContainerFiles\licenza\5165051.flf
Version: 14.0.29537.32452-it
Platform: 14.0.29530.32339
Generic Tag: 0.0.9.7
Container OS Version: 10.0.17763.503 (ltsc2019)
Host OS Version: 10.0.17763.379 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using process isolation
Creating container CAP140-LIVE from image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
ae8c0cf27e277b3650109048d92f4c9b60b5928ec76d00fab71a2be33e958e8c
Waiting for container CAP140-LIVE to be ready
Initializing...
Starting Container
Hostname is CAP140-LIVE
PublicDnsName is CAP140-LIVE
Using Windows Authentication
Starting Internet Information Server
Import Encryption Key
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 98EB42ED97B8B565FB67EFCDCF3CB3C71FF01DD4
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user Admin
Container IP Address: 172.30.242.123
Container Hostname  : CAP140-LIVE
Container Dns Name  : CAP140-LIVE
Web Client          : https://CAP140-LIVE/NAV/
Dev. Server         : https://CAP140-LIVE
Dev. ServerInstance : NAV

Files:
http://CAP140-LIVE:8080/al-3.0.106655.vsix
http://CAP140-LIVE:8080/certificate.cer

Initialization took 81 seconds
Ready for connections!
Reading CustomSettings.config from CAP140-LIVE
Creating Desktop Shortcuts for CAP140-LIVE
Container CAP140-LIVE successfully created
NavContainerHelper is version 0.6.1.2
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Using image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
Removing container AL-CAP140-LIVE
Removing AL-CAP140-LIVE from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\AL-CAP140-LIVE
Creating Container AL-CAP140-LIVE
Using license file E:\ContainerFiles\licenza\5165051.flf
Version: 14.0.29537.32452-it
Platform: 14.0.29530.32339
Generic Tag: 0.0.9.7
Container OS Version: 10.0.17763.503 (ltsc2019)
Host OS Version: 10.0.17763.379 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using process isolation
Creating container AL-CAP140-LIVE from image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
46d985196e291b2279daf69ee22345551fb8178955e4510c3de3b56de4a94858
Waiting for container AL-CAP140-LIVE to be ready
Initializing...
Starting Container
Hostname is AL-CAP140-LIVE
PublicDnsName is AL-CAP140-LIVE
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 1FC1A0DAFD004E28C0CF00C7A56DC998435B16A2
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Container IP Address: 172.30.250.40
Container Hostname  : AL-CAP140-LIVE
Container Dns Name  : AL-CAP140-LIVE
Web Client          : http://AL-CAP140-LIVE/NAV/
Dev. Server         : http://AL-CAP140-LIVE
Dev. ServerInstance : NAV

Files:
http://AL-CAP140-LIVE:8080/al-3.0.106655.vsix

Initialization took 96 seconds
Ready for connections!
Reading CustomSettings.config from AL-CAP140-LIVE
Creating Desktop Shortcuts for AL-CAP140-LIVE
Container AL-CAP140-LIVE successfully created

even with this configuration it fails to download symbols with this launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://al-cap140-live",
            "port": 7349,
            "serverInstance": "NAV",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true
        }
    ]
}

**Comment by freddydk** [comment]
I would not go there (dual containers) - you probably face the fact, that the user is not created. When you specify a foreign database, the container doesn't create a user.
Just use username / password.
If it doesn't work - try to remove your port changes and other things to identify what the problem is.

**Comment by Pellic** [comment]
Following your suggestion I have removed the port publishing and mapping.
I have also removed the ssl option and now the output of VSCode  is

[2019-06-15 16:11:33.28] Using reference symbols cache path: c:\Users\emiliape\Documents\AL\ALProject1\./.alpackages
[2019-06-15 16:11:33.28] Targeting server 'http://al-cap140-live' and server instance 'nav'.
[2019-06-15 16:11:33.28] Please authenticate in the Visual Studio Code...
[2019-06-15 16:11:40.08] Using reference symbols cache path: c:\Users\emiliape\Documents\AL\ALProject1\./.alpackages
[2019-06-15 16:11:40.08] Targeting server 'http://al-cap140-live' and server instance 'nav'.
[2019-06-15 16:11:40.09] Using user name and password authentication. User name used is: 'sa'.
[2019-06-15 16:11:40.09] Sending request to http://al-cap140-live:7049/nav/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0
[2019-06-15 16:11:40.09] Sending request to http://al-cap140-live:7049/nav/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2019-06-15 16:11:40.17] The request for path /nav/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-06-15 16:11:40.17] The request for path /nav/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0 failed with code NotFound. Reason: No published package matches the provided arguments.
[2019-06-15 16:11:40.17] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

the launch.json is:
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://al-cap140-live",
            "port": 7049,
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true
        }

and the script to create the container:
New-NavContainer -accept_eula `
                 <#-useSSL#> `
                 -containerName $ContainerName `
                 -imageName $imageName `
                 -Auth NavUserPassword `
                 -Credential $navcredential `
                 -databaseServer $databaseServer `
                 -databaseInstance $databaseInstance `
                 -databaseName $databaseName `
                 -databaseCredential $databaseCredential `
                 -updateHosts `
                 -licenseFile $licenseFile `
                 -includeCSide `
                 -enableSymbolLoading `
                 -doNotExportObjectsToText `
                 -shortcuts $shortcuts 

 and the output:
NavContainerHelper is version 0.6.1.2
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Using image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
Creating Container AL-CAP140-LIVE
Using license file E:\ContainerFiles\licenza\5165051.flf
Version: 14.0.29537.32452-it
Platform: 14.0.29530.32339
Generic Tag: 0.0.9.7
Container OS Version: 10.0.17763.503 (ltsc2019)
Host OS Version: 10.0.17763.379 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using process isolation
Creating container AL-CAP140-LIVE from image mcr.microsoft.com/businesscentral/onprem:14.0.29537.32452-it-ltsc2019
8e5f8b06b99d1ab255852d7d079fe8da5c17e6465afb6880931ad00148f5fac7
Waiting for container AL-CAP140-LIVE to be ready
Initializing...
Starting Container
Hostname is AL-CAP140-LIVE
PublicDnsName is AL-CAP140-LIVE
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 15082329C79F0939DB80D744CCB98333884F2AB2
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Container IP Address: 172.30.247.195
Container Hostname  : AL-CAP140-LIVE
Container Dns Name  : AL-CAP140-LIVE
Web Client          : http://AL-CAP140-LIVE/NAV/
Dev. Server         : http://AL-CAP140-LIVE
Dev. ServerInstance : NAV

Files:
http://AL-CAP140-LIVE:8080/al-3.0.106655.vsix

Initialization took 98 seconds
Ready for connections!
Reading CustomSettings.config from AL-CAP140-LIVE
Creating Desktop Shortcuts for AL-CAP140-LIVE
Container AL-CAP140-LIVE successfully created

after that I create the user with :
New-NavContainerNavUser -ErrorAction Continue -containerName "AL-$ContainerName"  -Credential $navcredential -PermissionSetId SUPER -ChangePasswordAtNextLogOn $false

the created user successfully connect to the web client, win client, OD and the db with SSMS

**Comment by Pellic** [comment]
Hi Freddy I have investigated further following your suggestion and from what I have experienced my conclusion is that the problem  appears only when using external db.
I get another minor issue with the use of ssl:
[2019-06-15 19:10:38.14] Sending request to https://cap140-live:7349/nav/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2019-06-15 19:10:38.19] Error: An error occurred while sending the request.
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
The remote certificate is invalid according to the validation procedure.
Probably because of the auto generated self signed certificate.

**Comment by Pellic** [comment]
after dozen of other test the result is still the same:
Unable to download symbols when using external DBs outside the container

**Comment by freddydk** [comment]
As I stated earlier - I wouldn't go there. A container is a sandbox with everything inside. I know partners who are running with external SQL Servers - but I haven't done much in that area myself.

**Comment by Pellic** [comment]
Hi Freddy,
agree, but in my scenario, it was necessary to avoid the storage limitation of Sql Express.
Anyway finally comes the end of this sad little story:
After a the right amount of struggling, when I think I was lost, casually gave a look at the Get-NavAppInfo output of my target db and then, the embarrassing revelation:
PS C:\run> Get-NAVAppInfo Nav -SymbolsOnly

Id            : 76533a55-abbe-481c-8e3d-6191059ca367
Name          : Application
Version       : 13.3.27233.0
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global

Id            : 8874ed3a-0643-4247-9ced-7a7002f7135d
Name          : System
Version       : 13.0.12929.0
Publisher     : Microsoft
ExtensionType : ModernDev
Scope         : Global

the exteral db,  was converted from an earlier versionof BC and the internal App are from build 13!
Doh!
After extracting a new db from a bc 14 docker image everithing went right, just an ovverride of the script SetupDatabase.ps1 to enable the option "ServicesUseNTLMAuthentication" in the nav instance;

I close the post and thank you very much for the support and the patience even if I submit the issue in the weekend.
