### ISSUE TITLE
Problem with a SOAP Web Service

### ISSUE THREAD

**Issue by ignatiuspc** [microsoft/navcontainerhelper#498]
Hello

I've been looking for information about this problem, but I couldn't find it.

The problem is with a Web Service running in the docker. It's a simple Web Service to create a client, when I run the Web Service doesn't work for me, when I upload it to the customer's sandbox, it works correctly.

I think the problem comes from the fact that the docker does not have the ports mapped but I think I have used the New-NAVContainer well.

That's how I used it:

$additionalParameters = @("--publish 8080:8080",
                          "--publish 443:443", 
                          "--publish 7046-7049:7046-7049")

New-NavContainer -accept_eula -assignPremiumPlan -enableSymbolLoading -containerName navserver -useSSL -alwaysPull -imageName "bcinsider.azurecr.io/bcsandbox-master:es" -updateHosts -includeCSide -doNotExportObjectsToText -auth NavUserPassword -additionalParameters $additionalParameters

And this is the Web Service:

    procedure CreateMessage(codNo: Code[20]; txtMessage: Text)
    var
        Customer: Record Customer;
    begin
        Customer.Init();
        Customer."No." := codNo;
        Customer.Name := txtMessage;
        Customer.Insert();
    end;

can you help me?

Thanks

**Comment by freddydk** [comment]
How do you call the web service?

**Comment by ignatiuspc** [comment]
I use swagger for try the Web Service, when I try GET the Web Service runs correctly, but when I try POST with the body is when the error.

**Comment by freddydk** [comment]
Your additional parameters (--publish) are only if you are trying to expose the ports from the container to external machines (connecting to the host).
Web Services in a Docker Container works 100% like web services when Service Tier installed locally and if you can use GET against a Web Service your problem doesn't seem to be exposed ports or anything like that.

**Comment by ignatiuspc** [comment]
Oks, thank you Freddy, I have several examples, in several dockers, and in none it works, I will continue investigating.

**Comment by freddydk** [comment]
I'd be happy to help - but I need something from you, which I can run and repro.
With the information above, I stand the risk of using hours to repro the problem - and I (as well as you) have a ton of docker containers where Soap, OData and API's works just great.
There even is a method in NavContainerHelper to invoke an Api in a container, which is used all the time.

**Comment by freddydk** [comment]
Please reopen with more information if the solution was not solved.

**Comment by ignatiuspc** [comment]
Excuse me, Fredddy.

I try this in a VM Azure and I solved it. Thanks
