### ISSUE TITLE
Mobile App Access to (NAV) Azure Container Instance 

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/navcontainerhelper#500]
For a quick look, I want to share our actual development state as an Azure Container Instance. In our current project, nav should be accessed by the mobile, not the web client. I am having a hard time to access the container through the mobile app, while everything seems to be fine with the web client. 
The current steps are:

0. Create container and develop apps/customizations using navcontainerhelper
1. Create an image from our dev-container
2. Tag that image and upload it to our repository on azure
3. Create a new Azure Container Instance from the new Image
4. Access the container through the mobile client

 1-3 Work, 4 not. Accessing through the web client is not a Problem. I also tried to activate ssl and download the certificate to my iOS device, which does not change anything. What am I missing? Is it generally possible to accomplish the desired task?

**Comment by freddydk** [comment]
Which container are you using?
Which mobile app are you using?
What is the error?
The mobile app is "just" a wrapper around the Web Client, so you are likely seeing some version number problems or like. Will try to see if this works myself.

**Comment by freddydk** [comment]
Just tried myself - works fine.
Maybe you are using a self-signed certificate - that will not work - use letsencrypt.
I am guessing here - you need to provide more info.

**Comment by mmenninghaus** [comment]
Seems to be a problem of my personal iOS device, other iOS devices work using letsencrypt.
