### ISSUE TITLE
Publishing app with Publish-NavContainerApp

### ISSUE THREAD

**Issue by MarceeMarc** [microsoft/navcontainerhelper#501]
Getting the following error when trying to publish an app with a dependency. The below references the dependency app which is contained in the .alpackages folder, and the app compiles and package buils in VSCode without issue.

**Extension compilation failed
error AL1024: A package with publisher '*Publisher*', name '*Extension Name*', and a version compatible with '1.0.0.0' could not be loaded.**

Any advice? App declared in the dependency publishes independently without issue and the app with the dependency declared published fine prior to declaring the dependency.

**Comment by freddydk** [comment]
How did you publish the apps in the first place?

**Comment by MarceeMarc** [comment]
Seems to be it. Thanks. Had published the other apps via VS Code.
