### ISSUE TITLE
Publish-NavContainerApp -useDevEndpoint and NavUserPassword

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/navcontainerhelper#503]
If I do useDevEndpoint with NavUserPassword, I receive an undefined $credential variable error.

Publish-NavContainerApp : The variable '$Credential' cannot be retrieved because it has not been set.
At Docker.ps1:37 char:1
+ Publish-NavContainerApp `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Credential:String) [Publish-NavContainerApp], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,Publish-NavContainerApp

[script.txt](https://github.com/microsoft/nav-docker/files/3320828/script.txt)
[output.txt](https://github.com/microsoft/nav-docker/files/3320829/output.txt)

**Comment by freddydk** [comment]
Should be fixed in 0.6.2.1 - just released.

**Comment by kylehardin6** [comment]
Confirmed: This is now working in 0.6.2.1.

**Comment by freddydk** [comment]
Thanks
