### ISSUE TITLE
ForceHandleTrackingEvent 

### ISSUE THREAD

**Issue by SirBETE** [microsoft/navcontainerhelper#504]
**Describe the bug**
Just got the same problem as #5062 when trying to install my extension on a freshly made docker container.
Version: Platform 14.0.32600.0 + Application 32615 (BE Dynamics NAV 14.1)
tag: mcr.microsoft.com/businesscentral/sandbox:be

Manually installing the extension gives 'something went wrong' screen

using PS
```
PS C:\Windows\system32> Install-NavContainerApp -appName Drr -containerName Drr
Installing Drr on default
ForceHandleTrackingEvent failed to acquire a lock
at <ScriptBlock>, <No file>: line 12
ForceHandleTrackingEvent failed to acquire a lock
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.InstallNavApp
    + PSComputerName        : f035387ac20db8dea0b56ae75fdc7e1e752215fe9980601d0774f10853724807
```

Publish (F5) from VS Code gives the same error.
App compiles.

**Comment by atoader** [comment]
@freddydk can you help?

**Comment by freddydk** [comment]
https://github.com/microsoft/navcontainerhelper/issues/488 describes how to set that setting during creation of the container

**Comment by kine** [comment]
Hi @freddydk, when the fix will be released? To know if I should implement the workaround or it will be solved by new version of module. Thanks!

**Comment by freddydk** [comment]
I assume that this is fixed in CU2 - I wasn't planning on making a fix in the containerhelper for that specific version

**Comment by SirBETE** [comment]
Great, that other thread didn't showed up in google searches ... :(
Anyway:

CU2 is due for?

Tried it with 
-additionalParameters @("--env CustomNavSettings=MetadataLockTimeout=""00:11:00""")
(more than 10 min)
made new container of versions
Version: 14.1.33107.0-BE
Platform: 14.0.32600.33003
Generic Tag: 0.0.9.8
Container OS Version: 10.0.14393.3025 (ltsc2016)
Host OS Version: 10.0.14393.3053 (ltsc2016)

Let it run for half an hour:
[2019-06-26 09:18:44.68] Sending request to http://x:7049/NAV/dev/apps?SchemaUpdateMode=synchronize
[2019-06-26 09:55:43.66] The request for path /NAV/dev/apps?SchemaUpdateMode=synchronize failed with code 422. Reason: The following SQL error was unexpected:
Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
