### ISSUE TITLE
A parameter cannot be found that matches parameter name 'interactionTimeout'

### ISSUE THREAD

**Issue by marknitek** [microsoft/navcontainerhelper#505]
**Problem**

Today i had the following error message when i tried to execute my tests in a container that i have created a few weeks ago.

```
A parameter cannot be found that matches parameter name 'interactionTimeout'.
at <ScriptBlock>, <No file>: line 35
A parameter cannot be found that matches parameter name 'interactionTimeout'.
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 Zeichen:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-ClientContext], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-ClientContext
    + PSComputerName        : c212b1773a5b70a707a9b7218d28727209cccdaec746cce92221ac1c19124f63
```
It seems to me that with the newest update of navcontainerhelper, old containers do not work anymore with `Run-TestsInNavContainer`.

**Workaround**
I was able to recover from this state by simply deleting the PSTestTool Folder for that container:
```
C:\ProgramData\NavContainerHelper\Extensions\<ContainerName>\PsTestTool
```

Catching that situation would be nice, since we update to the lastest navcontainerhelper very often, but would like to keep containers if possible.
Otherwise this the workaround is here for reference.

**Comment by freddydk** [comment]
Good point - I will check that the PsTestTool folder exists and has the latest files in the next version.

**Comment by freddydk** [comment]
0.6.2.3 is out - and it uses a different foldername, meaning that if a test has already run - the new version will still be downloaded and used.
