### ISSUE TITLE
BC Contianer WIndws Authentication

### ISSUE THREAD

**Issue by hussaynv** [microsoft/navcontainerhelper#506]
I'm looking to setup a BC on prem container and connect that to an external sql server. I would like to run windows authentication so that users that exist in AD can access the BC container instance.
The documentation is a bit thin, it refers to setting up gMSA but no real detail about the specific steps required on the sql side and on the container setup side. Is this something that is actually possible given that the container cannot be domain joined and its not part of the same network, the container is on a host virtual network under the Container host vm?
any direction would be very useful.

**Comment by freddydk** [comment]
You might be able to find information on Tobias' blog:
https://www.axians-infoma.de/techblog/setting-up-windows-authentication-with-containers-connect-to-azure-ad-domain-services/
or maybe read this on how to set it up:
https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts
