### ISSUE TITLE
useDevEndpoint throws 422 error

### ISSUE THREAD

**Issue by MaxBelohoubek** [microsoft/navcontainerhelper#507]
Hey Freddy, on a new bcsandbox container created with navcontainerhelper I get following error message when trying to publish an extension using the new devEndpoint param:

![image](https://user-images.githubusercontent.com/31455503/60452906-f50a4e00-9c2f-11e9-8eac-7477e22ddbd0.png)

The nav instance and iis are using an let's encrypt cert; downloading symbols and publishing via vscode is working fine.
The extension doesn't have any dependencies and can be published / synced / installed using the default powershell way without a problem.

Command:
Publish-NavContainerApp -containerName $ContainerName -appFile $appFile -skipVerification -packageType Extension -useDevEndpoint -install -credential $credential

**Comment by freddydk** [comment]
Does it work if you try to do it from VS Code?

**Comment by freddydk** [comment]
I don't know if it can be this, but if you have published using powershell first - then you cannot use the dev endpoint afterwards. If you create a brand new container - does it then work?
UseDevEndpoint just publishes end app through the same endpoint as VS Code - it surprises me that one works and not the other.

**Comment by MaxBelohoubek** [comment]
This is a brand new container. Will create a new one anyway, maybe something went wrong when creating it.

**Comment by MaxBelohoubek** [comment]
Seems like recreating the container did the trick! Don't know why exactly because I didn't get any errors when creating the first container. Anyway, this issue can be closed.

**Comment by freddydk** [comment]
I will keep an eye out for this if it happens again.

**Comment by MaxBelohoubek** [comment]
Seems like it's related to the symbols. Will test that theory though.
