### ISSUE TITLE
BC14 and Get-BestNavContainerImageName

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/navcontainerhelper#508]
BC14 does not get a 1903 docker image chosen, and thus cannot do process isolation on a 1903 host.

[script.txt](https://github.com/microsoft/navcontainerhelper/files/3351951/script.txt)
[output.txt](https://github.com/microsoft/navcontainerhelper/files/3351956/output.txt)

**Comment by freddydk** [comment]
The Best Container Image Name for 1903 is still ltsc2019 - images are only built for ltsc2016 and ltsc2019.
If you want to run process isolation for 1903 - you need to specify -useBestContainerOS, which will use the generic 1903 image and re-platform the ltsc2019 image.

**Comment by kylehardin6** [comment]
That works exactly as advertized - thanks! Keep up the awesome work.
