### ISSUE TITLE
New-NavContainer when specifying "-auth aad" unhelpful description

### ISSUE THREAD

**Issue by CloudViking86** [microsoft/navcontainerhelper#509]
Hi,

When running "New-NavContainer" and specifying "-auth aad" the prompt that appears is;
`Using UserPassword Authentication. Please enter username/password for the Containter.`
since the code states;
`   if ($Credential -eq $null -or $credential -eq [System.Management.Automation.PSCredential]::Empty) {
        if ($auth -eq "Windows") {
            $credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
        } else {
            $credential = get-credential -Message "Using UserPassword Authentication. Please enter username/password for the Containter."
        }
        if ($Credential -eq $null -or $credential -eq [System.Management.Automation.PSCredential]::Empty) {
            throw "You have to specify credentials for your Container"
        }
    }`

The "if"-statement does not take into account "aad", when specifying "aad" you still get the prompt which is somewhat confusing (or was at least for us).

Best Regards

**Comment by freddydk** [comment]
Will fix the description in the next release.

**Comment by freddydk** [comment]
Message changed to Using AAD Authentication. Please enter username/password for the container.
Please note that the authenticationEmail address is specified in -authenticationEmail
