### ISSUE TITLE
New-NavContainer wrong version of NAV (typo)

### ISSUE THREAD

**Issue by CloudViking86** [microsoft/navcontainerhelper#511]
Row 641;
` if ($includeCSide -and ($version.Major -ge 15)) {
        throw "IncludeCSide is no longer supported in Dynamics 365 Business Central Fall 2019 release (1910 / 15.x)"
    }`
Row 907;
`if ($version.Major -ge 15) {
            $ServerInstance = "BC"
        }
        else {
            $ServerInstance = "NAV"
        }`

$version.Major should be -ge 13 instead of 15

Just a typo :)

**Comment by freddydk** [comment]
15 is the upcoming 2019 wave 2 release in which CSide is gone.
in 13 - CSide is still there.
