### ISSUE TITLE
Cannot Create  new container

### ISSUE THREAD

**Issue by anwar0206** [microsoft/navcontainerhelper#512]
Hi

I am executing below cmdlet and getting error

New-NavContainer -containerName navsrvr -accept_eula -accept_outdated -alwaysPull -assignPremiumPlan -auth NavUserPassword `
-ClientServicesPort 5046 -DeveloperServicesPort 5049 -FileSharePort 8181 -ManagementServicesPort 5045 -ODataServicesPort 5048 -SoapServicesPort 5047 `
-PublishPorts @(8181,5443,5046,5047,5048,5049) `
-bakFile c:\RUN\navtest.bak -Credential superuser -doNotExportObjectsToText -imageName microsoft/dynamics-nav:2016-cu9-w1-ltsc2019 -includeCSide `
-myScripts c:\run\my -PublicDnsName navsrvr.southeastasia.cloudapp.azure.com -restart unless-stopped -dumpEventLog -shortcuts Desktop -updateHosts -useBestContainerOS `
-useSSL 

and gets below error
Creating superuser as SQL User and add to sysadmin
Creating SUPER user
ServerInstance 'MicrosoftDynamicsNavServer$NAV' is not running.
at <ScriptBlock>, C:\Run\SetupNavUsers.ps1: line 20
at <ScriptBlock>, C:\Run\my\SetupNavUsers.ps1: line 2
at <ScriptBlock>, C:\Run\navstart.ps1: line 174
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container navsrvr failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.5\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of conta

powershell module version is 0.6.2.5

output of docker inspect
[
    {
        "Id": "7854a1ed07c89ba7ebab332a9f873ab3a045610ff850d953f8288cfe7afe6cfd",
        "Created": "2019-07-08T20:10:02.3322041Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 9980,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-07-08T20:10:07.7792535Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 13,
                "Log": [
                    {
                        "Start": "2019-07-09T03:15:46.2986803+07:00",
                        "End": "2019-07-09T03:15:56.308806+07:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (10s)"
                    },
                    {
                        "Start": "2019-07-09T03:16:26.3444631+07:00",
                        "End": "2019-07-09T03:16:36.3579183+07:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (10s)"
                    },
                    {
                        "Start": "2019-07-09T03:17:06.3881904+07:00",
                        "End": "2019-07-09T03:17:16.3895644+07:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (10s)"
                    },
                    {
                        "Start": "2019-07-09T03:17:46.46468+07:00",
                        "End": "2019-07-09T03:17:56.4678577+07:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (10s)"
                    },
                    {
                        "Start": "2019-07-09T03:18:26.5007219+07:00",
                        "End": "2019-07-09T03:18:36.5149773+07:00",
                        "ExitCode": -1,
                        "Output": "Health check exceeded timeout (10s)"
                    }
                ]
            }
        },
        "Image": "sha256:c511f722ef6d6988c032c0da18e980808dc3d308846a07d4d29abf071135ea67",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\7854a1ed07c89ba7ebab332a9f873ab3a045610ff850d953f8288cfe7afe6cfd\\7854a1ed07c
89ba7ebab332a9f873ab3a045610ff850d953f8288cfe7afe6cfd-json.log",
        "Name": "/navsrvr",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\navsrvr\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\navsrvr\\Program Files:C:\\navpfiles",
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "5046/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5046"
                    }
                ],
                "5047/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5047"
                    }
                ],
                "5048/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5048"
                    }
                ],
                "5049/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5049"
                    }
                ],
                "5443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5443"
                    }
                ],
                "8181/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8181"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\7854a1ed07c89ba7ebab332a9f873ab3a045610ff850d953f8288cfe7afe6cfd"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\navsrvr\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\navsrvr\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "navsrvr",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "5046/tcp": {},
                "5047/tcp": {},
                "5048/tcp": {},
                "5049/tcp": {},
                "5443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {},
                "8181/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ManagementServicesPort=5045",
                "bakfile=C:\\ProgramData\\NavContainerHelper\\Extensions\\navsrvr\\database.bak",
                "username=superuser",
                "locale=en-US",
                "useSSL=Y",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "FileSharePort=8181",
                "auth=NavUserPassword",
                "ExitOnError=N",
                "licenseFile=",
                "removePasswordKeyFile=Y",
                "accept_eula=Y",
                "SoapServicesPort=5047",
                "PublicDnsName=navsrvr.southeastasia.cloudapp.azure.com",
                "databaseServer=",
                "ClientServicesPort=5046",
                "ODataServicesPort=5048",
                "DeveloperServicesPort=5049",
                "databaseInstance=",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AEIASAA5AEwAagAvAHoAUQB3AEsAcQBSAEEASwA3AHkAQwA3ADgARgBmAHcAPQA9AH
wAMgBkADcAYwBhADcAZAA2ADIAZQA1ADEANgA3ADQAMgBkAGQANAAyAGIANQBkADkAOQAwAGYANgBkAGYAMwBhAGQAZQAyAGEAYQAwAGEAZgA2AGMANQA0AGIANwBmADAANQBh
ADYAOQA4AGEAYwA4ADYAMABkADkAMwAxADMANAA=",
                "accept_outdated=Y",
                "DatabaseName=CRONUS",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/7076a8cd-99a7-45c5-aa1b-6b7d98ab7d79",
                "VSIXURL=",
                "IsBcSandbox=N"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "microsoft/dynamics-nav:2016-cu9-w1-ltsc2019",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "W1",
                "created": "201903101916",
                "cu": "cu9",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=826604",
                "maintainer": "Dynamics SMB",
                "nav": "2016",
                "osversion": "10.0.17763.316",
                "tag": "0.0.9.2",
                "version": "9.0.46290.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "7854a1ed07c89ba7ebab332a9f873ab3a045610ff850d953f8288cfe7afe6cfd",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "5046/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5046"
                    }
                ],
                "5047/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5047"
                    }
                ],
                "5048/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5048"
                    }
                ],
                "5049/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5049"
                    }
                ],
                "5443/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5443"
                    }
                ],
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null,
                "8181/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8181"
                    }
                ]
            },
            "SandboxKey": "7854a1ed07c89ba7ebab332a9f873ab3a045610ff850d953f8288cfe7afe6cfd",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "dc861cb10de1d5f6b9e90e25e5e2e38630893ebcd63b04770437104c3574f28c",
                    "EndpointID": "fd805cea14bcd74a43064814976e65aa1b2a675314e385a41c2ef6da48616a5c",
                    "Gateway": "172.30.128.1",
                    "IPAddress": "172.30.141.118",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:22:a6:63",
                    "DriverOpts": null
                }
            }
        }
    }
]

The required ports are opened in Windows Firewall as well configured in Azure portal

**Comment by freddydk** [comment]
What is the complete output of the new-navcontainer?

**Comment by anwar0206** [comment]
Hi,
I copied upto the last line of the error message.

**Comment by freddydk** [comment]
Again - I need the complete output of New-NavContainer - there is a lot of info in the output, which is useful for troubleshooting. Alternatively I have to ask a million questions, which wastes my time, your time and everybody else reading this.

**Comment by freddydk** [comment]
Please re-open with a full output of new-navcontainer if the problem still exists.
