### ISSUE TITLE
Code page error while running Import-TestToolkitToNavContainer

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#514]
Hey Guys, 
Did something changed on with BC/Containers recently when it comes to the code page handling?

I suddenly receive this error message while importing TestToolkit objects

`Import-TestToolkitToNavContainer -containerName $containerName `

My script was working find with onprem:1904-rtm-w1 image, but just stopped working with onprem:1904-cu1-w1 version.

Anyone else experiencing similar cases?

```
 There is no system code page on your computer that matches the 1252 code page of the Latin1_General_100_CS_AS collation for the mydatabase database.
Your system code pages are: ANSI: 65001, OEM: 65001.
Ensure that the Regional Options of the computer use the correct system language and locale for the code pages to match.
You can also disable the 'Validate Collation' setting for this database. It is possible that certain text data will not be converted correctly when stored in the database
```

**Comment by freddydk** [comment]
Could you send me the full script and output?

In NavContainerHelper 0.6.2.3 - these changes was implemented (with .txt file handling)

0.6.2.3 
Added parameter locale to New-NavContainer to override the culture setting of the container 
BugFix: Export-NavContainerObjects in hyperv ltsc2019 containers caused destructive encoding of the object files 
Use different folder name for PsTestTool to avoid using old cached versions 
BugFix: Convert-Txt2Al, Create-MyDeltaFolder, Create-MyOriginalFolder (and Convert-ModifiedObjectsToAl and Export-ModifiedObjectsAsDeltas) in hyperv ltsc2019 containers caused destructive encoding of files

I don't think this has anything to to with import-testtoolkit though (imports .fob)
Could you try to uninstall navcontainerhelper and install 0.6.2.2 - just to validate whether this is the issue?

Thanks

**Comment by gintuoklis** [comment]
Seems that this was related to the #513. Once i managed to create container using generic image, the problem was resolved. I get no more code page error while importing the objects.

Here's the code for creating container:
```

New-NavContainer -accept_eula `
                 -containerName $containerName `
                 -imageName $imageName `
                 -additionalParameters @("--volume $lsinstallationdir\:$localpathoncontainer","--env bakfile=$backupfile", "--env locale=nl-NL") `
                 -includeCSIDE `
                 -doNotExportObjectsToText `
				 -myScripts @($additionalScripts) `
                 -licenseFile $licensefile `
                 -shortcuts Desktop `
                 -useBestContainerOS
```
