### ISSUE TITLE
Default Font RDLC Reports on OnPrem Docker Images 

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/navcontainerhelper#515]
We're using the mcr.microsoft.com/businesscentral/onprem Images for development. But the docker Images seem to have  a different Default Font than a regular Installation. 

We designed our own document set which is using the RDLC Default font Arial 10 

![image](https://user-images.githubusercontent.com/35929603/61057888-73b47780-a3f6-11e9-9027-ffd1577946db.png)

Every previous Version and all Business Central installations we did on Servers Show Arial 10 as we would expect. 

But on all docker OnPrem instances the font Looks very different 

![image](https://user-images.githubusercontent.com/35929603/61058027-bbd39a00-a3f6-11e9-9083-4ca954d3e4fe.png)

Can we Change the behaviour ourselves somewhere? And please provide docker Images which behave the same as installations otherwise development and testing will become very difficult.

**Comment by freddydk** [comment]
The docker images are limited to the fonts, which are in the Windows Server Core Docker image.
You can use Add-FontsToBcContainer from NavContainerHelper to add fonts from the host to the container (I cannot add them myself due to licensing)

**Comment by JulianTillmann** [comment]
And Arial is not part of the Core Image? seems a bit weird ;-) 

but thanks for the quick answer, I'll check it out.

**Comment by freddydk** [comment]
Why? If you think about it, why would an operating system, which doesn't contain any form of UI contain any fonts at all?
Looking in ltsc2019 servercore c:\windows\fonts - it contains only lucon.ttf.

**Comment by JulianTillmann** [comment]
okay, maybe not as part of the Server core, but the BC-docker is installing IIS which is for UI? It's the Little Things that make using docker so complicated. 

It worked after I installed the whole arial package and restarted the docker container. Thanks for the help

**Comment by freddydk** [comment]
Fonts are a licensed part of Windows, I cannot add them to Business Central containers.

**Comment by AbhishekPrajapati** [comment]
> okay, maybe not as part of the Server core, but the BC-docker is installing IIS which is for UI? It's the Little Things that make using docker so complicated.
> 
> It worked after I installed the whole arial package and restarted the docker container. Thanks for the help

Hello JulianTillmann,

I am also facing the same issue with the fonts of RDLC report. Can you please tell me how did you install Arial font package to docker image/container?

Thanks,
Abhishek Prajapati

**Comment by JulianTillmann** [comment]
@AbhishekPrajapati 
use can use the "Add-FontsToNavContainer" from NavContainerhelper for example like this
`Add-FontsToNavContainer -containerName $ContainerName -path "c:\windows\fonts\Arial\arial.ttf" -verbose`

hope this helps

**Comment by AbhishekPrajapati** [comment]
@JulianTillmann Thanks for your quick response. I have tried to run the mentioned command but I am getting an error. I think I have to do some prerequisites for NavContainerHelper in order to run this command.

![image](https://user-images.githubusercontent.com/9090896/72566999-dede8980-3904-11ea-8e0c-c343c835f997.png)

Anyways I am looking into it. Thanks

**Comment by freddydk** [comment]
Add-FontsToNavContainer only works if the container was created by new-navcontainer (or new-bccontainer).
If you create the container manually, you need to copy and install the fonts manually as well.
The source for the above function is here: https://github.com/microsoft/navcontainerhelper/blob/master/Misc/Add-FontsToNavContainer.ps1 if you want to see how things are done.

**Comment by AbhishekPrajapati** [comment]
> Add-FontsToNavContainer only works if the container was created by new-navcontainer (or new-bccontainer).
> If you create the container manually, you need to copy and install the fonts manually as well.
> The source for the above function is here: https://github.com/microsoft/navcontainerhelper/blob/master/Misc/Add-FontsToNavContainer.ps1 if you want to see how things are done.

Thanks for your reply but I need more clarity please. I have created docker image using docker commands and when I ran this image, container created automatically. Now are you saying I need to create navcontainer and run my docker image on that container? Am I correct?

Another question, with reference to this issue [553](https://github.com/microsoft/navcontainerhelper/issues/553), which values do I need to use in New-NavContainer command? Values like `-auth`, `-licensefile`. How will I get these values? 

It will be good if you give me reference link to do it step by step as I am new to this topic.

Thanks

**Comment by freddydk** [comment]
This is a good starting point: https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/
And there are quite a lot of blog posts on business central on docker there.

**Comment by GripService** [comment]
i am using docker linux container , my RDLC is also not working, is there any one who can help me ?

**Comment by freddydk** [comment]
> i am using docker linux container , my RDLC is also not working, is there any one who can help me ?
What are you using a linux container for?
BC doesn't run on Linux?
