### ISSUE TITLE
Cannot find path 'C:\Program Files (x86)\Microsoft Dynamics NAV\110\RoleTailored Client\navcommandresult.txt' because it does not exist.

### ISSUE THREAD

**Issue by skkulla** [microsoft/navcontainerhelper#516]
After creating the container, we have loaded some add-on's as .fob and I have used Generate-SymbolsInNavContainer to generate symbols but it is throwing the above error.

**Comment by freddydk** [comment]
Sorry, but this issue doesn't contain remotely enough information for me to do anything about it.
