### ISSUE TITLE
Target: (Extension/Internal) in app.json file

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#517]
Hi,
Currently we have our app in app store for D365 BC SaaS.
Currently we dont specify the target if it is Extension/Internal in app.json.
We publish the app in docker container and it works fine. We have also submitted the app and its in Microsoft app store.
Now, we were trying to publish the app in D365 BC on Premise.
So, **i created run time package** and installed D365 BC on premise (latest spring version) and i was able to publish the app successfully.
![image](https://user-images.githubusercontent.com/38437776/61086093-d69e1280-a3e6-11e9-8f79-4f040f924fd1.png)

But one of our end user who below version

![image](https://user-images.githubusercontent.com/38437776/61086153-f33a4a80-a3e6-11e9-9e0c-4c71cf588fce.png)

is getting following error when we try to publish the app using power shell.

![image](https://user-images.githubusercontent.com/38437776/61086169-0220fd00-a3e7-11e9-8c7a-6634694ef43b.png)

I tried changing the "Allowed Extension Target Level" to both Extension/Internal and i am still getting the same error

Please let me know how to deal with this? is this issue because they are using older version of D365 BC?
If we dont specify the target in app.json what is the default value?

I tried installing D365 BC on premise version 13.0.26413.0 and I can replicate this issue.
SO, do I need to run that container image 13.0.26413.0 and try creating runtime package? can some one help me out on this?

I get following error when i try to pull the image
![image](https://user-images.githubusercontent.com/38437776/61086241-30064180-a3e7-11e9-9dd2-409ac73da9bc.png)

Obviously the image doesn't exist but what is the closest image that i can download to provide the fix.

**Comment by freddydk** [comment]
It looks like you are trying to install a 14.x (spring 2019) app on a 13.x (fall 2018) Business Central, that won't work.
You will have to compile and create an app with 13.x if you want it to run on 13.x.
A 13.x app is more likely to run on 14.x

**Comment by Bssivivek** [comment]
Hi freedy
So do I need to download an image and create a container which is 13.x so that I can download the symbols and compile the app. Is this correct? If so, which version of container do I download. I tried downloading exact version (please check the last screen shot on the initial post) but it’s erroring out. Thanks in advance.

**Comment by freddydk** [comment]
I think 13.0 is mcr.microsoft.com/businesscentral/onprem:1810-rtm-ltsc2019
(Replace ltsc2019 with ltsc2016 if you are running Windows Server 2016 or Windows 10 prior to 1810)

**Comment by Bssivivek** [comment]
Thanks will follow the instruction.

**Comment by Bssivivek** [comment]
thanks for the feedback. the issue is because, I was trying to publish runtime package of version14.0 in D365 BC on premise version 13.2 and that's why its erroring out (as you rightly said). The error message was misleading and I thought it has something to do with target (internal/extension) that we specify in app.json file. you can close this ticket. thanks again!!

**Comment by freddydk** [comment]
Thanks
