### ISSUE TITLE
Rename the container instance

### ISSUE THREAD

**Issue by Neoduende** [microsoft/navcontainerhelper#522]
Is it possible to change the name of the NAV instance when creating the container?

For example:

I have a machine in Azure with a single name, if I change the name of 
the instance I could install several containers

xxxxx.cloudapp.azure.com/NAV
xxxxx.cloudapp.azure.com/NAV2

Thanks

**Comment by freddydk** [comment]
You cannot rename the instance and even if you could, you wouldn't be able to do what you are asking.
But... - this is what the traefik feature was made for:
https://www.axians-infoma.de/techblog/traefik-support-for-navcontainerhelper-the-nav-arm-templates-for-azure-vms-and-local-environments/
You should try that.

**Comment by Neoduende** [comment]
Thanks @freddydk 

I will try it!!!

**Comment by freddydk** [comment]
Lyder godt.

Jeg sidder i Grækenland uden mit NEMID, men er tilbage Torsdag morgen (hvis ikke Christian har godkendt den inden).
/Freddy
