### ISSUE TITLE
PSSession Error with New-NAVContainer 

### ISSUE THREAD

**Issue by Varun-Col132** [microsoft/navcontainerhelper#523]
Hi Experts,

Am trying to create new NAV Container using the NEW-NavContainer command from Power Shell ISE, but getting below PSSession error please help me.

![NAV Container Erro](https://user-images.githubusercontent.com/47139756/61580316-2e96f080-ab2e-11e9-8ff2-d77c52a21c25.png)

Command I used to create the new Container 
New-NavContainer -containerName VAMBC1 -accept_eula -assignPremiumPlan -auth Windows -includeCSide -isolation hyperv -licenseFile C:\License\D365BC.flf -memoryLimit 4GB -shortcuts Desktop -updateHosts

Thanks in Advance..

**Comment by freddydk** [comment]
Did you have a container with that name already?
could you copy/paste the full output of the command (instead of a screen shot)
Thanks

**Comment by Varun-Col132** [comment]
Hi Freddy, No I did not had any container with that name before.
please find below the command.

PS C:\WINDOWS\system32> New-NavContainer -accept_eula -containerName "NAVVAMBC" -auth NavUserPassword -includeAL -includeCSide -licenseFile C:\License\D365BC.flf -imageName "mcr.microsoft.com/businesscentral/onprem:na-ltsc2019"
NavContainerHelper is version 0.6.2.5
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 18.09.2
Docker Server Version is 18.09.2
Using image mcr.microsoft.com/businesscentral/onprem:na-ltsc2019
Creating Container NAVVAMBC
Using license file C:\License\D365BC.flf
Version: 14.1.32615.0-na
Platform: 14.0.32600.0
Generic Tag: 0.0.9.7
Container OS Version: 10.0.17763.503 (ltsc2019)
Host OS Version: 10.0.18362.30 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Overriding default functionality to dump eventlog in container log every 2nd second. (use -dumpEventLog to avoid this)
Files in C:\ProgramData\NavContainerHelper\Extensions\NAVVAMBC\my:
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
Creating container NAVVAMBC from image mcr.microsoft.com/businesscentral/onprem:na-ltsc2019
e221703a961b2229bfbbbb42ab48305af157144f0ad807825b3c19264034131d
Waiting for container NAVVAMBC to be ready
Initializing...
Starting Container
Hostname is NAVVAMBC
PublicDnsName is NAVVAMBC
WARNING: DNS resolution not working from within the container.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 1CA76F20C6E13C8ED5F5CE2083D03942AEB43560
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating babuv as SQL User and add to sysadmin
WARNING: Caution: Your program license expires in 9 days.
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: Caution: Your program license expires in 9 days.
WARNING: This license is not compatible with this version of Business Central.
WARNING: Caution: Your program license expires in 9 days.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 192.168.213.133
Container Hostname  : NAVVAMBC
Container Dns Name  : NAVVAMBC
Web Client          : http://NAVVAMBC/NAV/
Dev. Server         : http://NAVVAMBC
Dev. ServerInstance : NAV

Files:
http://NAVVAMBC:8080/al-3.0.124247.vsix

WARNING: You are running a container which is 71 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 355 seconds
Ready for connections!
Reading CustomSettings.config from NAVVAMBC
New-PSSession : [e221703a961b2229bfbbbb42ab48305af157144f0ad807825b3c19264034131d] An error has occurred which Windows PowerShell cannot handle. A 
remote session might have ended.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.5\ContainerHandling\Get-NavContainerSession.ps1:35 char:24
+ ...  $session = New-PSSession -ContainerId $containerId -RunAsAdministrat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.Manageme....RemoteRunspace:RemoteRunspace) [New-PSSession], PSRemotingDataStructureException
    + FullyQualifiedErrorId : PSSessionOpenFailed

**Comment by freddydk** [comment]
I assume that you are running PowerShell as administrator?
This should cause navcontainerhelper to use sessions - but apparently that can fail.
I will consider switching to not use sessions if creating the session fails.

**Comment by Varun-Col132** [comment]
Yes am running the Powershell as administrator.
What is the command for not using the session.

Thanks.

**Comment by freddydk** [comment]
At this time, you cannot, I will consider adding that.

You can run the containerhelper as non-administrator, but then you will have to run:
Check-NavContainerHelperPermissions -Fix
In order to give the user the correct permissions.

**Comment by freddydk** [comment]
The latest navcontainerhelper 0.6.2.8 will revert to docker exec if new-pssession fails - you can try again to see if this fixes your issue.
