### ISSUE TITLE
The socket connection was aborted |  when running Codeunit for 2 hours

### ISSUE THREAD

**Issue by hvandenborn** [microsoft/navcontainerhelper#524]
Freddy,

I have a devops task in my build that start our Automatic tests (we have alot) via Invoke-NavContainerCodeunit

Its fine if it runs less then 2 hours: (our small test suite) 
![image](https://user-images.githubusercontent.com/48794854/61632160-7469cb00-ac8c-11e9-8592-e2efd4a410d0.png)

but in some cases we run the big test suite (all tests) and then it will exceed the 2 hours. in builds outside docker (for version 11) it runs like 2.5 hours.
But in Docker i get this error: 
![image](https://user-images.githubusercontent.com/48794854/61632263-b561df80-ac8c-11e9-9bb2-aea985ea08c4.png)

the Devops timeout is 7 hours so that is not the issue here. Also i do not think its the script. but perhaps you do know what the problem is? 

is there some timeout for docker connections or something? can u help?

**Comment by hvandenborn** [comment]
By the Way: Container is created each time the build runs

**Comment by richardrobberse** [comment]
I can only advise you to run your tests with the Run-TestsInNavContainer function from the navcontainerhelper.
Running tests with Invoke-NAVCodeunit is a no-go since GuiAllowed is false and a lot of tests require UI

Using Run-TestsInNavContainer will also solve your issue ;)

**Comment by hvandenborn** [comment]
Thanks i will look into it.

"Running tests with Invoke-NAVCodeunit is a no-go since GuiAllowed is false and a lot of tests require UI" this is for us no problem we only test main flows not the UI.

**Comment by freddydk** [comment]
You might be able to solve the issue now and find a way to invoke your test codeunit - but somewhere down the road, you are probably looking at refactoring that test codeunit.
Tests will be invokable from VS Code and Invoke-NavCodeunit might not last forever.

Having said that, if you want to find out what is causing the timeout above, I can think of a few things, but I need to know whether your Invoke-NavContainerCodeunit is running as administrator or not.
If it is running as administrator, you will be creating a session through this function:
https://github.com/microsoft/navcontainerhelper/blob/master/ContainerHandling/Get-NavContainerSession.ps1
It doesn't provide any session timeout.
You could create the session on your own (providing a PSSessionOption) - run the same code (as in the Invoke-Command) and then run the standard NAV Invoke-NavCodeUnit inside the invoke-command.
You could also create a .ps1 file which loads the modules (like this):

```
$runPath = "c:\Run"
$myPath = Join-Path $runPath "my"

function Get-MyFilePath([string]$FileName)
{
    if ((Test-Path $myPath -PathType Container) -and (Test-Path (Join-Path $myPath $FileName) -PathType Leaf)) {
        (Join-Path $myPath $FileName)
    } else {
        (Join-Path $runPath $FileName)
    }
}

. (Get-MyFilePath "prompt.ps1") -silent | Out-Null
. (Get-MyFilePath "ServiceSettings.ps1") | Out-Null
. (Get-MyFilePath "HelperFunctions.ps1") | Out-Null

$txt2al = $NavIde.replace("finsql.exe","txt2al.exe")
Set-Location $runPath
```
and then invoke your codeunit - and then execute this with docker exec container powershell file

you might even be able to do this detached (docker exec --detach container powershell file)

You are welcome to report your findings here for other people to learn from, but you might not get first level support for this scenario in the containerhelper as you are heading down a path that we don't recommend.

Hope you understand.

**Comment by hvandenborn** [comment]
Thanks for pointing me the way!

We will indeed rebuild it when we are on vscode, and making a test app of it. but we are not there yet, 
Until then i just want to let it be as it was so i can put my effort into our addon converting it to AL.

**Comment by hvandenborn** [comment]
Freddy,

"If it is running as administrator, you will be creating a session through this function:"
the service account is a local admin. but if i create my own PSSession or i run the Get-NavContainerSession then i will get "The server has rejected the client credentials."

i also checked the $UsePSSession which came out empty, the $IsAdministrator comes out true.

Code:
![image](https://user-images.githubusercontent.com/48794854/61701757-f4506d80-ad3e-11e9-97c7-7a1f5eb369f3.png)

Result:
![image](https://user-images.githubusercontent.com/48794854/61701930-3a0d3600-ad3f-11e9-8200-2680206f7ba0.png)


it looks like the NAV server rejects the credentials, which is logical because i use NavUserPassword
so somehow i also need to give this invoke the credentials which are valid for nav.
but Invoke-NAVCodeunit does not take username of password. 
i read something about also creating an extra nav user: (New-NavContainerNavUser) for the agent account. (https://forum.mibuso.com/discussion/70753/invoke-navcodeunit-the-server-has-rejected-the-client-credentials) 
But here i get troubles with "The Windows account could not be mapped to a valid security identifier (SID)." does this mean i also need to create this user as windows user within docker?

its a whole search 😄

**Comment by hvandenborn** [comment]
mm found out that you tell somebody else here: https://github.com/Microsoft/navcontainerhelper/issues/381
that NavuserPassword is not working with invoke-navcodeunit and that you for that reason create a nav user. So i will try to use that way.

**Comment by hvandenborn** [comment]
Freddy,

You can close this one! tried the 
"I can think of a few things, but I need to know whether your Invoke-NavContainerCodeunit is running as administrator or not.
If it is running as administrator, you will be creating a session through this function:
https://github.com/microsoft/navcontainerhelper/blob/master/ContainerHandling/Get-NavContainerSession.ps1
It doesn't provide any session timeout.
You could create the session on your own (providing a PSSessionOption) - run the same code (as in the Invoke-Command) and then run the standard NAV Invoke-NavCodeUnit inside the invoke-command."

Done this and still after 2 hours it stops, had the same thing when publishing the app (with not enough memory, it will also crash after 2 hours like this, same error) 

Ill have to find another way i guess

**Comment by hvandenborn** [comment]
1 year later and it seems that the NST does have a default timeout of 2 hours:
its not adjustable in the MMC administration center but through powershell it is:

the keyname: ManagementServicesIdleClientTimeout is default 02:00:00.
Adjust it if needed, also with upgrade's:

Set-NAVServerConfiguration -ServerInstance $ServerInstanceName -KeyName "ManagementServicesIdleClientTimeout" -KeyValue "04:00:00"

**Comment by freddydk** [comment]
Thanks a million for sharing.
