### ISSUE TITLE
Generate-SymbolsInNavContainer raises unexpected

### ISSUE THREAD

**Issue by megel** [microsoft/navcontainerhelper#528]
![image](https://user-images.githubusercontent.com/15800069/61932876-b775b800-af84-11e9-8f28-398be1abc445.png)

**Comment by freddydk** [comment]
This error is because it is trying to print the content of the naverrorlog.txt - but doesn't do it right.
In the RTC folder - you can find naverrorlog.txt, which will describe what the real error was.
Next version - it will show the error instead.

**Comment by freddydk** [comment]
Shipped in 0.6.2.8
