### ISSUE TITLE
Question: Build new Container including NAV

### ISSUE THREAD

**Issue by glwr-gob** [Microsoft/navcontainerhelper#53]
Hi @freddydk,

we want to build a container without SQL Express and some own changes.
Maybe you want to share your documentation and scripts with me/us?

Best regards,
Gerrit

**Comment by freddydk** [comment]
Removing SQL Express would cause you to have to rebuild everything from scratch without any reason at all. If you start the container with database parameters, pointing out a foreign database, then the built in SQL Express will never start and never use any CPU cycles, nor any memory. It will only take up some MB's on disk (and that will be shared between all containers).
Adding layers to the images is easier - you can do that using docker build or docker commit, but I would not recommend rebuilding NAV containers from scratch

**Comment by glwr-gob** [comment]
Okay, this is a good objection.
First of all we want get some practice in building containers.
We establish a task force to push NAV docker installations in our company.

**Comment by freddydk** [comment]
The NAV on Docker images actually are so flexible that you probably can do everything on-the-fly when starting them. That said, it might still be a good idea to build new images, but every image will become a sidekick and you will have to rebuild it with new versions of the NAV on Docker image.
Overriding scripts might be a better course.
