### ISSUE TITLE
Create-AlProjectFolderFromNavContainer error with -includeAL parameter

### ISSUE THREAD

**Issue by Kowa63** [microsoft/navcontainerhelper#532]
Version: 0.6.2.6
**Scenario**
The current onprem image is used to create a new DE container with -includeAL. 
![grafik](https://user-images.githubusercontent.com/16236672/62050275-3f6ff200-b211-11e9-8f24-bf84ca65e42e.png)

When I apply _Create-AlProjectFolderFromNavContainer_ to that container, this error message comes up claiming that it was not started with -includeAL even though it was.
![grafik](https://user-images.githubusercontent.com/16236672/62050420-7e9e4300-b211-11e9-9994-0041d5e170b0.png)

**Comment by freddydk** [comment]
Copy/paste of the command and the full output is always best (screen shots only reveal very limited information and I have to guess a lot)

did you specify -doNotExportObjectsAstext?

**Comment by Kowa63** [comment]
Yes, -doNotExportObjectsAstext is set. I've used Create-AlProjectFolderFromNavContainer in conjunction with containers before that were spun up like this and never had any issues.

**Full parameters:** 
New-NavContainer -containerName bconprem0719 -imageName mcr.microsoft.com/businesscentral/onprem:de -accept_eula  -includeCSide -includeAL -updateHosts  -licenseFile  C:\temp\licence.flf -enableSymbolLoading -alwaysPull -doNotExportObjectsToText -auth Windows -assignPremiumPlan -Credential (get-credential -credential UserID)

navcontainerhelper\Create-AlProjectFolderFromNavContainer -alProjectFolder C:\Users\UserID\Documents\AL\ALProject8 -containerName bcsandbox0719

I've tried it without this parameter, then it works, but it takes much longer than before long because now the objects are exported twice, apart from the fact that the time to spin up a container is considerably increased.

**Comment by freddydk** [comment]
The exporting twice is due to includeCSIDE.
the objects for the version will be cached, but you have to export the objects at least once (starting with includeAL without donotexport)
So remove -includeCSIDE and remove -doNOtExport - then you should be good to go.

**Comment by freddydk** [comment]
I will change the error to 
Container $containerName was not started with -includeAL (or -doNotExportObjectsAsText was specified)
