### ISSUE TITLE
Report Development

### ISSUE THREAD

**Issue by BoAlexLarsen** [microsoft/navcontainerhelper#533]
Trying to development a report using VSC and a docker image.

In VSC I have my data items, columns etc. set up and compiled.
In RTC have added the report in the Custom Report Layouts as RDLC. However, when I try to edit the report, I run into 2 issues:
* Edit report looks into the registry database for MSReportBuilder.exe (codeunit 9652), but can't find it as the registry database it is looking into is the registry database on the host (my PC). I have solved this by modifying codeunit 9652 where I have hard coded the path to MSReportBuilder.exe. So far so good.
* The codeunit then generates a temporary file for the layout. The file is generated in a temp folder under my user on the host, and hence the report builder cant find the temp file as it is 

Is there af way to get around this issue?

Regard,
Bo Alex Larsen
BDL A/S

**Comment by freddydk** [comment]
Wouldn't you have to install Report builder on the host?

**Comment by BoAlexLarsen** [comment]
Report Builder is installed on the host and in the container.

The issue is, as I see it, that the file handling in the FileManagement codeunit happens outside the container, whereas working with the files happens inside the container.

I can see the temp files created in my host file system, however the container can't read them.

I was wondering if there is some sort of work around.

**Comment by BoAlexLarsen** [comment]
Hi again,
I have worked a little more on this. I discovered that the issue described wasn't an issue in BC 365 Spring release. Then I started installing different docker images. I installed BC 365 fall releases CU4 and CU9 and none of these images have the problem.
My conclusion is that the problem only relates to BC 365 fall release CU1 (and perhaps RTM, CU2 and CU3)

**Comment by freddydk** [comment]
Could it be a version number mismatch?`
Anyway - I will close the bug, I don't think it is related to NavContainerHelper / Docker (or rather, there is probably nothing I can do to fix it).
