### ISSUE TITLE
Error while  Publish-NewApplicationToNavContainer

### ISSUE THREAD

**Issue by bydynamics** [microsoft/navcontainerhelper#537]
PS C:\WINDOWS\system32> $imageName = "bcinsider.azurecr.io/bcsandbox-master:base-ltsc2019"
$containerName = "sandboxfuture"
$auth = "UserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "c:\temp\bcop14 - 5980913.flf"

New-BCContainer -accept_eula `
                -imageName $imageName `
                -containerName $containerName `
                -auth $auth `
                -credential $credential `
                -licenseFile $licenseFile `
                -updateHosts `
                -includeAL `
                -memoryLimit 6G

NavContainerHelper is version 0.6.2.6
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image bcinsider.azurecr.io/bcsandbox-master:base-ltsc2019
Removing container sandboxfuture
Removing sandboxfuture from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\sandboxfuture
Creating Container sandboxfuture
Using license file c:\temp\bcop14 - 5980913.flf
Version: 15.0.34648.0-W1
Platform: 15.0.34329.0
Generic Tag: 0.0.9.9
Container OS Version: 10.0.17763.557 (ltsc2019)
Host OS Version: 10.0.18362.267 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\sandboxfuture\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container sandboxfuture from image bcinsider.azurecr.io/bcsandbox-master:base-ltsc2019
70daa80753c84a098db0c24882013b56ac46d7e58558c3acda65656b5792701e
Waiting for container sandboxfuture to be ready
Initializing...
Starting Container
Hostname is sandboxfuture
PublicDnsName is sandboxfuture
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 97FE227ECC4BA04E3F82F4FC18E669DC2E40C824
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.24.18.133
Container Hostname  : sandboxfuture
Container Dns Name  : sandboxfuture
Web Client          : http://sandboxfuture/BC/
Dev. Server         : http://sandboxfuture
Dev. ServerInstance : BC

Files:
http://sandboxfuture:8080/AL-15.0.34329.0.vsix

Initialization took 82 seconds
Ready for connections!
Reading CustomSettings.config from sandboxfuture
Creating Desktop Shortcuts for sandboxfuture
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\150\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\150\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container sandboxfuture successfully created

PS C:\WINDOWS\system32> $alProjectFolder = "C:\ProgramData\NavContainerHelper\AL\BaseApp"
Create-AlProjectFolderFromNavContainer -containerName $containerName `
                                       -alProjectFolder $alProjectFolder `
                                       -useBaseLine `
                                       -addGIT

Copying Al Source Files from C:\ProgramData\NavContainerHelper\Extensions\Original-15.0.34648.0-W1-al\* to C:\ProgramData\NavContainerHelper\AL\BaseApp
Initializing Git repository
Initialized empty Git repository in C:/ProgramData/NavContainerHelper/AL/BaseApp/.git/
Adding files
Committing files
Al Project Folder Created

PS C:\WINDOWS\system32> $app = Compile-AppInNavContainer -containerName $containerName `
                                 -credential $credential `
                                 -appProjectFolder $alProjectFolder `
                                 -appOutputFolder $alProjectFolder

Using Symbols Folder: C:\ProgramData\NavContainerHelper\AL\BaseApp\.alpackages
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Downloading symbols: Microsoft_System_15.0.34329.0.app
Url : http://172.24.18.133:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=15.0.0.0&tenant=default
Downloading symbols: Microsoft_System Application_15.0.34648.0.app
Url : http://172.24.18.133:7049/BC/dev/packages?publisher=Microsoft&appName=System Application&versionText=1.0.0.0&tenant=default
Compiling...
alc.exe /project:C:\ProgramData\NavContainerHelper\AL\BaseApp /packagecachepath:C:\ProgramData\NavContainerHelper\AL\BaseApp\.alpackages /out:C:\ProgramData\NavContainerHelper\AL\BaseApp\Default Publisher_
sandboxfuture_1.0.0.0.app /assemblyprobingpaths:"C:\ProgramData\NavContainerHelper\AL\BaseApp\.netpackages","C:\Program Files (x86)\Microsoft Dynamics NAV\150\RoleTailored Client","C:\Program Files\Microso
ft Dynamics NAV\150\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\windows\assembly"
Microsoft (R) AL Compiler version 4.0.2.21925
Copyright (C) Microsoft Corporation. All rights reserved

Compilation started for project 'sandboxfuture' containing '5888' files at '22:17:3.352'.

C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataSyncStatus.Page.al(15,43): warning AL0269: The referenced page '"Data Migration Overview"' should be a list part or a card part. This warning will becom
e an error in a future release.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataSyncStatus.Page.al(20,38): warning AL0269: The referenced page '"Data Migration Error"' should be a list part or a card part. This warning will become a
n error in a future release.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataSyncStatus.Page.al(27,36): warning AL0269: The referenced page '"Data Migration Error"' should be a list part or a card part. This warning will become a
n error in a future release.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Page.al(1131,29): warning AL0547: The event 'OnCloseIncomingDocumentFromAction' should not expose global variables. This warning will becom
e an error in a future release.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocuments.Page.al(903,29): warning AL0547: The event 'OnCloseIncomingDocumentsFromActions' should not expose global variables. This warning will bec
ome an error in a future release.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\WorkflowWebhookNotification.Codeunit.al(111,29): warning AL0547: The event 'OnPostNotificationRequest' should not expose global variables. This warning will
 become an error in a future release.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\Staging\Assisted%2520Setup\AssistedSetup.Table.al(109,38): warning AL0432: Table 'Product Video Category' is marked for removal. Reason: Videos are not cate
gorized any more in this way. The Video module handles the full listing.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(423,35): warning AL0432: Field 'URL4' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 
1024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(423,28): warning AL0432: Field 'URL3' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 
1024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(423,21): warning AL0432: Field 'URL2' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 
1024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(433,9): warning AL0432: Field 'URL2' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 1
024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(434,9): warning AL0432: Field 'URL3' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 1
024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(435,9): warning AL0432: Field 'URL4' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 1
024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(438,13): warning AL0432: Field 'URL2' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 
1024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(440,13): warning AL0432: Field 'URL3' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 
1024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\IncomingDocument.Table.al(442,13): warning AL0432: Field 'URL4' is marked for removal. Reason: Unecessary field after increasing max text length of URL1 to 
1024
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassEvalDataCountry.Codeunit.al(196,81): warning AL0432: Field 'Picture' is marked for removal. Reason: Replaced by Image field
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(635,42): warning AL0432: Table 'Product Video Category' is marked for removal. Reason: Videos are not categorized any
 more in this way. The Video module handles the full listing.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(685,42): warning AL0432: Table 'Business Setup' is marked for removal. Reason: This table is being replaced by new ta
ble called Manual Setup.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(693,42): warning AL0432: Table 'Azure Machine Learning Usage' is marked for removal. Reason: Table 2003 replaces this
.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(869,42): warning AL0432: Table 'Journal Lines Entity Setup' is marked for removal. Reason: Became obsolete after refa
ctoring of the NAV APIs.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(870,42): warning AL0432: Table 'Account Entity Setup' is marked for removal. Reason: Became obsolete after refactorin
g of the NAV APIs.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1094,42): warning AL0432: Table 'MS-Event Emitter Event Codes' is marked for removal. Reason: Deprecated
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1095,42): warning AL0432: Table 'MS-QBO Customer' is marked for removal. Reason: replacing burntIn Extension tables w
ith V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1096,42): warning AL0432: Table 'MS-QBO Item' is marked for removal. Reason: replacing burntIn Extension tables with 
V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1097,42): warning AL0432: Table 'MS-QBO Invoice' is marked for removal. Reason: replacing burntIn Extension tables wi
th V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1098,42): warning AL0432: Table 'MS-QBO Modified Field List' is marked for removal. Reason: replacing burntIn Extensi
on tables with V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1099,42): warning AL0432: Table 'MS-QBO Setup' is marked for removal. Reason: replacing burntIn Extension tables with
 V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1100,42): warning AL0432: Table 'MS-QBO Synchronization Error' is marked for removal. Reason: replacing burntIn Exten
sion tables with V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1101,42): warning AL0432: Table 'MS-QBO Start Sync. Service' is marked for removal. Reason: replacing burntIn Extensi
on tables with V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1102,42): warning AL0432: Table 'MS-QBO Failed Syncs' is marked for removal. Reason: replacing burntIn Extension tabl
es with V2 Extension
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1154,42): warning AL0432: Table 'Profile Resource Import/Export' is marked for removal. Reason: Importing and exporti
ng profile resources is no longer supported. AL profiles and customizations should be used instead.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1337,42): warning AL0432: Table 'Email Attachment' is marked for removal. Reason: We are reverting the fix that was u
sing this table as it was not possible to solve the problem this way.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(1338,42): warning AL0432: Table 'Data Class. Notif. Setup' is marked for removal. Reason: Functionality moved on My N
otifications.
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(2747,75): warning AL0432: Field 'On Hold Due to Inactivity' is marked for removal. Reason: Functionality moved into n
ew job queue status
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(4887,59): warning AL0432: Field 'Picture' is marked for removal. Reason: Replaced by Image field
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(5799,57): warning AL0432: Field 'Picture' is marked for removal. Reason: Replaced by Image field
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\DataClassificationEvalData.Codeunit.al(5913,59): warning AL0432: Field 'Picture' is marked for removal. Reason: Replaced by Image field
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\NotificationEntryDispatcher.Codeunit.al(147,17): warning AL0432: Field 'URL2' is marked for removal. Reason: URL1 field size increased
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\NotificationEntryDispatcher.Codeunit.al(147,70): warning AL0432: Field 'URL2' is marked for removal. Reason: URL1 field size increased
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\Staging\Job%2520queue\JobQueueSendNotification.Codeunit.al(68,28): warning AL0432: Field 'URL2' is marked for removal. Reason: URL1 field size increased
C:\ProgramData\NavContainerHelper\AL\BaseApp\src\Staging\Job%2520queue\JobQueueSendNotification.Codeunit.al(68,103): warning AL0432: Field 'URL2' is marked for removal. Reason: URL1 field size increased

Compilation ended at '22:18:20.531'.

C:\ProgramData\NavContainerHelper\AL\BaseApp\Default Publisher_sandboxfuture_1.0.0.0.app successfully created in 89 seconds

PS C:\WINDOWS\system32> Publish-NewApplicationToNavContainer -containerName $containerName `
                                     -appDotNetPackagesFolder (Join-Path $alProjectFolder ".netpackages") `
                                     -appFile $app `
                                     -credential $credential `
                                     -useCleanDatabase
Uninstalling apps
WARNING: This license is not compatible with this version of Business Central.
Unpublishing apps
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Publishing Default Publisher_sandboxfuture_1.0.0.0.app to http://172.24.18.133:7049/BC/dev/apps?SchemaUpdateMode=synchronize
Status Code 422 : Unprocessable Entity
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.6\AppHandling\Publish-NavContainerApp.ps1:160 char:17
+ ...             throw "Status Code $($result.StatusCode) : $($result.Reas ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Status Code 422 : Unprocessable Entity:String) [], RuntimeException
    + FullyQualifiedErrorId : Status Code 422 : Unprocessable Entity
 

PS C:\WINDOWS\system32>

**Comment by freddydk** [comment]
It is likely a way of telling you that 6Gb isn't enough memory.
You can try to increase that to 8Gb - or you can try to remove the memorylimit flag altogether and use -useBestContainerOS (which causes docker to switch to process isolation and share memory with the host)

**Comment by bydynamics** [comment]
Hi Freddy. Thanks for the quick response. I used the following parameters (removed memory flag and used -useBestContainerOS) on your advise while creating the container. I can now publish successfully the base app. 

$imageName = "bcinsider.azurecr.io/bcsandbox-master:base-ltsc2019"
$containerName = "sandboxfuture"
$auth = "UserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "c:\temp\bcop14 - 5980913.flf"

New-BCContainer -useBestContainerOS `
                -accept_eula `
                -imageName $imageName `
                -containerName $containerName `
                -auth $auth `
                -credential $credential `
                -licenseFile $licenseFile `
                -updateHosts `
                -includeAL `      

PS C:\WINDOWS\system32> Publish-NewApplicationToNavContainer -containerName $containerName `
                                     -appDotNetPackagesFolder (Join-Path $alProjectFolder ".netpackages") `
                                     -appFile $app `
                                     -credential $credential `
                                     -useCleanDatabase

Uninstalling apps
WARNING: This license is not compatible with this version of Business Central.
Unpublishing apps
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Publishing Default Publisher_sandboxfuture_1.0.0.0.app to http://172.24.26.62:7049/BC/dev/apps?SchemaUpdateMode=synchronize
New Application successfully published to sandboxfuture
App successfully published
