### ISSUE TITLE
How to continue using navcontainerhelper for CAL

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#538]
Hi Freddy,

this is just a request of information, I've just noted that a function that I was using in a DevOps Pipeline "Convert-CALTestOutputToAzureDevOps" has been removed.

I'd like to understand what should be the correct approach to use navcontainerhelper for CAL (old projects) and AL (new projects).

Should I install an old version? 
Should maintain old functions that have been removed (i.e. Convert-CALTestOutputToAzureDevOps) locally? 
Can I have 2 versions of navcontainerhelper installed in same server and point through code which one to use? 

Thank you
  Sergio Castelluccio

**Comment by freddydk** [comment]
It wasn't my intention to remove anything that has to do with CAL.
The function you describe, was a big hack to convert an output of the test runner (text based when using invoke-codeunit or the client) to devops and was really replaced by functionality to run tests (run-testsInNavContainer).

If you need the function, you can grab it here (I would recommend to use
https://raw.githubusercontent.com/microsoft/navcontainerhelper/2ca7ac1f212d5427266b4c4997947251a2c18c79/AppHandling/Convert-CALTestOutputToAzureDevOps.ps1

I do recommend using run-testsin... - instead though

I am not planning to remove any other CAL based things - all the CAL functions are just testing whether the container is 15.x or newer and then throwing an error.

**Comment by eclipses** [comment]
Thank you for your swift reply, I didn't know about run-testsInNavContainer. 

I've just found a detailed post in your website (I've finally subscribed to it).

I will definitely use the new function.

Thanks again for your support

**Comment by freddydk** [comment]
The advantage of Run-Tests is that it also runs UI based tests with Test Pages etc.

**Comment by eclipses** [comment]
I faced this issue few days ago cause I had messages under the condition if guiallowed and actually now, thanks to your reply, I know how to fix it 😉
