### ISSUE TITLE
BC 15.x Invoke-RestMethod causes Remote Server Error 401 not authorized

### ISSUE THREAD

**Issue by Kowa63** [microsoft/navcontainerhelper#539]
![grafik](https://user-images.githubusercontent.com/16236672/62273255-61e65300-b43d-11e9-9be3-4117f6af585d.png)

PS C:\Users\administrator> New-NavContainer -containerName bcsdbxmasterde -imageName bcinsider.azurecr.io/bcsandbox-master:de -accept_eula  -includeAL -updateHosts  -licenseFile \\Swap\docker.flf -alwaysPull -auth Windows -Credential (get-credential -credential MyUser) -accept_outdated  
NavContainerHelper is version 0.6.2.9
Host is Microsoft Windows Server 2016 Standard - ltsc2016
Docker Client Version is 17.06.2-ee-7
Docker Server Version is 17.06.2-ee-7
Pulling image bcinsider.azurecr.io/bcsandbox-master:de-ltsc2016
de-ltsc2016: Pulling from bcsandbox-master
Using image bcinsider.azurecr.io/bcsandbox-master:de-ltsc2016
Removing C:\ProgramData\NavContainerHelper\Extensions\bcsdbxmasterde
Creating Container bcsdbxmasterde
Using license file \\HP_KK\Swap\docker.flf
Version: 15.0.34648.0-de
Platform: 15.0.34329.0
Generic Tag: 0.0.9.9
Container OS Version: 10.0.14393.3025 (ltsc2016)
Host OS Version: 10.0.14393.3025 (ltsc2016)
Using locale de-DE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\bcsdbxmasterde\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container bcsdbxmasterde from image bcinsider.azurecr.io/bcsandbox-master:de-ltsc2016
a952d2c16c4c8c41a0d382bc21c2fd6e38f67cf8f4942c53801b1c0090de487c
Waiting for container bcsdbxmasterde to be ready
Initializing...
Starting Container
Hostname is bcsdbxmasterde
PublicDnsName is bcsdbxmasterde
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user MyUser
Setting SA Password and enabling SA
WARNING: Caution: Your program license expires in 13 days.
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: Caution: Your program license expires in 13 days.
WARNING: This license is not compatible with this version of Business Central.
WARNING: Caution: Your program license expires in 13 days.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.xx.xxx.xxx

Container Hostname  : bcsdbxmasterde
Container Dns Name  : bcsdbxmasterde
Web Client          : http://bcsdbxmasterde/BC/
Dev. Server         : http://bcsdbxmasterde
Dev. ServerInstance : BC

Files:
http://bcsdbxmasterde:8080/AL-15.0.34329.0.vsix

Initialization took 217 seconds
Ready for connections!
Reading CustomSettings.config from bcsdbxmasterde
Creating Desktop Shortcuts for bcsdbxmasterde
Downloading app: BaseApp
Url : http://172.xx.xxx.xxx:7049/BC/dev/packages?publisher=Microsoft&appName=BaseApp&versionText=&tenant=default
Invoke-RestMethod : Der Remoteserver hat einen Fehler zurückgegeben: (401) Nicht autorisiert.
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.9\AppHandling\Get-NavContainerApp.ps1:101 Zeichen:5
    Invoke-RestMethod -Method Get -Uri $url @AuthParam -OutFile $appF
     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by freddydk** [comment]
This is likely because of Windows Authentication.
if you switch to userpassword, it probably just works.
I will try this with Windows Auth.

**Comment by richardrobberse** [comment]
This should work, I did the exact same last night, also with Windows authentication.
Did you specify the -UseDefaultCredentials switch for the Invoke-RestMethod call?

**Comment by freddydk** [comment]
Yes, the Get-NavContainerApp should do this
https://github.com/microsoft/navcontainerhelper/blob/master/AppHandling/Get-NavContainerApp.ps1
Kai, did you provide the hosts windows credentials when creating the container?

**Comment by Kowa63** [comment]
Yes, the first thing that comes up is this window where I type these in:
![grafik](https://user-images.githubusercontent.com/16236672/62275438-3fa30400-b442-11e9-9209-2274efc69681.png)

**Comment by Kowa63** [comment]
Solved: 
If I use my own personal credentials is works.
![grafik](https://user-images.githubusercontent.com/16236672/62278550-9b708b80-b448-11e9-869d-06a1ed3fb3fe.png)

At first created the container with a commonly shared user that we use internally so that anyone in the firm can access the container if required with a shared login, but this user is not part of the active directory. In older BC versions this method works, but apparently not anymore.

**Comment by freddydk** [comment]
Yes, so using Windows Auth. you need to use the currently logged on credentials.
