### ISSUE TITLE
Error Text with Invoke-ScriptInNavContainer

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#543]
Hey Guys, 
Is there a trick to see full error message while running Invoke-ScriptInNavContainer?

I'm running simple script to sync schema. If there's any error with it, it cuts the error message to the first 100 characters or so.

`Invoke-ScriptInNavContainer -containerName develop -scriptblock {Sync-NAVTenant NAV -Mode Sync -Confirm:$false -Force} `

Here's how it looks:
![image](https://user-images.githubusercontent.com/16342128/62429289-3bf6d200-b70d-11e9-9e1f-0dea7c52d0c1.png)

If i run the same command within the container's ps session, i get full description:

![image](https://user-images.githubusercontent.com/16342128/62429303-5a5ccd80-b70d-11e9-9ad2-40befe5b4d6e.png)

**Comment by freddydk** [comment]
It looks like you are running the invoke-script... as non-admin - does it make any difference if you run it as administrator? (in order to know where to look:-))

**Comment by freddydk** [comment]
Just tested myself - indeed, this is because you are running as non-admin.
Best bet right now is to do a try catch inside the invoke-script and return the exception (or $null if everything went well)
Could look like:
```
$exception = Invoke-ScriptInBCContainer -containerName test -scriptblock { 
    try {
        throw "Test "*50
        $null
    }
    catch {
        $_
    }
}

Write-Host $exception
```

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by gintuoklis** [comment]
Hey Freddy, 
It did not work this trick. I believe the reason for that is implementation of Invoke-ScriptInBCContainer. If i understand it correctly you are generating powrshell script file and executing it using docker command:

`docker exec $containerName powershell $file`

I have a feeling that docker shortens the error message.

On the other hand, if i run similiar just directly from host powershell, all works fine.

`docker exec develop powershell -command "& {Import-Module 'C:\Program Files\Microsoft Dynamics NAV\130\Service\NavAdminTool.ps1'; Sync-NAVTenant NAV -mode sync -force}"`

**Comment by freddydk** [comment]
It is the way PowerShell calls executables, that shortens the message (not whether it is a file or not) - running docker exec from a command prompt will work.
I recommend running NavContainerHelper with elevated privileges, which will cause the full error text to be transferred AND be way faster due to re-use of sessions.
