### ISSUE TITLE
New-NAVContainer with includeAL does not include translation files

### ISSUE THREAD

**Issue by hemisphera** [microsoft/navcontainerhelper#544]
I have updated my image of `bcsandbox-master` IT. Like this:

````
New-NavContainer bclocal15it -accept_eula -imageName bcinsider.azurecr.io/bcsandbox-master:it-ltsc2019 -includeAL -accept_outdated -auth UserPassword
````

The resuilting AL-project folder does not contain any translations. No XLIFF or similar. As posted on Yammer, the `.app` file does contain a `.lcl` file that contains the translations. This however does not seem to work with VS Code, as it expects the translations to be an XLIFF file.

**Comment by freddydk** [comment]
The current way -includeAL is working is only temporary. Eventually, I think the plan is that the source will be included on the DVD (and on Docker) - and includeAL will just grab that.

**Comment by freddydk** [comment]
In the latest version of NavContainerHelper, the .lcl file is now extracted.
Will discuss with the Modern Dev team how to handle translations in general before 15.x ships.

**Comment by freddydk** [comment]
In the latest docker image (15.0.35805.0) translation files are now extracted correctly
