### ISSUE TITLE
Adding Volume to \Add-Ins causes error, if the Add-In already exists

### ISSUE THREAD

**Issue by TheDoubleH** [microsoft/navcontainerhelper#545]
I have added a Volume that points to c:\run\Add-Ins the files are copied correctly. However, if one file already exists, the entire process fails. Could this be done file, by file - or default to an overwrite?

Working with a NAV2016 Project

**Comment by freddydk** [comment]
Unfortunately, this code is in the generic layer, meaning that if I want to change that, i would have to rebuild all images in order for it to work.

You do however have a number of options.
1. Put your add-ins in a folder called DoubleH in the Add-ins folder, then you wouldn't have the conflict.
2. Download the SetupAddins from here: https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/SetupAddIns.ps1 - add -force to both copy lines and append -myscripts @("your setupaddins.ps1")
3. You can share your folder directly to the service addins folder and the rtc addins folder: -additionalParameters @('-v "C:\temp\myaddins:c:\Program Files\Microsoft Dynamics NAV\90\Service\Add-Ins\DoubleH"','-v "C:\temp\myaddins:C:\Program Files (x86)\Microsoft Dynamics NAV\90\RoleTailored Client\Add-ins\DoubleH"')

**Comment by freddydk** [comment]
Did you make this work?

**Comment by TheDoubleH** [comment]
Yes and No -

I created a 'blank' Docker Image for my `NAV2016-CU32-NA` database and removed the Add-Ins that are copied to the `C:\ProgramData\NavContainerHelper\Extensions\NAV2016CU32NA\Program Files\90\RoleTailored Client\Add-ins` folder and removed them from my GitHub Repository - Which I think is fair enough to do.

So for now, I got it to work, but I still ran into an issue today, where the Add-Ins didn't copy correctly - Not sure if and when You are going to rebuild the images; But I would still like to see Overwrite Add-Ins when copying c:\my\Add-Ins.

It would be a nice bonus if You add details of what add-ins were copied - just like you do for the `C:\ProgramData\NavContainerHelper\Extensions\NAV2016CU32NA\my` folder

> Files in C:\ProgramData\NavContainerHelper\Extensions\NAV2016CU32NA\my:
> - AdditionalOutput.ps1
> - AdditionalSetup.ps1
> - license.flf
> - MainLoop.ps1
> - SetupWebClient.ps1
> - updatehosts.ps1
> 

As for the setupAddIns script, I have yet to look into that.

**Comment by freddydk** [comment]
I am not going to fix it, because it is a wrong fix.
If you add a DLL with the same name, but different version - then you would break the baseapp by overwriting and break your app by not overwriting.
The only right thing to do - is for you to copy your dlls into a subfolder - and then both dlls would be ther (suggestion #1 above)
