### ISSUE TITLE
-assignPremiumPlan does not appear to work for AL-only image

### ISSUE THREAD

**Issue by MikeGlue** [microsoft/navcontainerhelper#549]
I created a new container using the AL-only insider image. I used the '-assignPremiumPlan' switch but when I go into the system (in CRONUS) to enable the premium experience I get the following:

![image](https://user-images.githubusercontent.com/5204734/62550079-9db35b00-b837-11e9-966e-e6d21a729599.png)

**Comment by freddydk** [comment]
Fixed in 0.6.2.92
