### ISSUE TITLE
Export-NavContainerObjects fails with tag mismatch

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#55]
When using Export-NavContainerObjects I receive the messsage below.
All Objects are exported, and when this is done the message is shown.
When I ommit -exportToNewSyntax:$false, no objects are exported and the message is immediately shown.
I can't debug to see where the error exactly happens because there's an Invoke-Command in the script.
I'm using a NAV2017 CU9 Navision installation with an external sqlserver and NON-Cronus database.
Also exported the txt file outside the container an did a split-object. There's no difference in the split files.
What could be wrong.

Command:

Export-NavContainerObjects `
-containerName "DEVServer" `
-objectsFolder "c:\temp\objects\ORIGINAL" `
-sqlCredential $MyDatabaseCredential `
-filter "" `
-exportToNewSyntax:$false

Message:

Export Objects to c:\original.txt
Split c:\original.txt to c:\original
There is a mismatch between the tag specified in the request and the tag present in the reparse point
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.1.3\ObjectHandling\Export-NavContainerObjects.ps1:35 char:5
+     Invoke-Command -Session $session -ScriptBlock { Param($filter, $o ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by freddydk** [comment]
Could you post the docker logs <name> and the docker inspect <name> on your container?
Thanks

**Comment by Koubek** [comment]
Or maybe just a result of `Get-NavContainerDebugInfo` (but I am not sure if this has been already published).

**Comment by freddydk** [comment]
Isn't yet, but good point Jakub - need to publish an update.
Just wanted to include a few more bug fixes:-)

**Comment by freddydk** [comment]
Ok, I found out why this is happening
Export-navcontainerhelper uses a quick-and-dirty way of emptying a folder (remove the folder and create it again).
Problem is, that the folder to which you export is shared directly using -v c:\temp\objects\original:c:\original - this means that I remove the shared folder.
You can fix this right now by using -v c:\temp\objects:c:\objects to share the base folder - or you can wait until I publish a new navcontainerhelper where I use a better way to empty the folder.

**Comment by freddydk** [comment]
Fixed in 0.2.2.0
https://www.powershellgallery.com/packages/navcontainerhelper/0.2.2.0

**Comment by mheijkant** [comment]
Thanks, this work well.
