### ISSUE TITLE
C/SIDE ODBC Error

### ISSUE THREAD

**Issue by JulianTillmann** [microsoft/navcontainerhelper#552]
Since BC14 CU2 / "mcr.microsoft.com/businesscentral/onprem:14.3.34444.0-de" I've been getting an ODBC error with C/SIDE. 

![image](https://user-images.githubusercontent.com/35929603/62619199-7a131200-b916-11e9-956c-fc9d62529a90.png)

**Comment by freddydk** [comment]
Looks like you are missing the pre-requisites for finsql as found here:
https://freddysblog.com/2017/10/29/troubleshooting-nav-on-docker/

**Comment by JulianTillmann** [comment]
thanks
