### ISSUE TITLE
Providing Testapp in navContainer

### ISSUE THREAD

**Issue by MJECloud** [microsoft/navcontainerhelper#568]
Hey Freddy, 

we face the issue that we can't personalize the webclient. 
As a workaround we found this: https://github.com/Microsoft/AL/issues/4877#issuecomment-507991544

But the containerimage doesn't contain any test.app file. 
Can you put this into the container?
We don't want to download it from the navdvd everytime a new CU is released.

**Comment by freddydk** [comment]
And you need to use enableSymbolLoading (which is the mother of the problem here)?

I think it can be any test.app - you can basically provide an empty test.app yourself and always import that into the container. Then it doesn't conflict with the symbols of the imported test toolkit later on.

**Comment by MJECloud** [comment]
We removed the switch from our scripts and now it works. 
But we don't understand why the test.app and personalization are connected. 

Anyway, thanks for the quick help!

**Comment by freddydk** [comment]
Thanks.
The connection is that when you create a personalization, the Web Client will (behind the scenes) create an extension. That extension will get a dependency on all published apps (including the test app).
If you use enablesymbolloading - the test symbols are part of the application symbols (see https://freddysblog.com/2019/03/16/symbols-demystified/) thus the test app needs to be removed and personalization will fail.
so, it is a bug in the web client basically.
