### ISSUE TITLE
Unable to assign premiumplan to bcinsiderpreview with de-tag

### ISSUE THREAD

**Issue by DavidFeldhoff** [microsoft/navcontainerhelper#569]
I'm able to create a bcinsider image with the following command-line:
```
$imageName = 'bcinsider.azurecr.io/bcsandbox-master:base'
$containerName = 'bcpreview'
New-BCContainer -accept_eula -containerName $containerName -imageName $imageName -assignPremiumPlan
```

But when I change the tag from 'base' to 'de' then the super user could not log in to business central.
So both images are created and started, but in the german one I am not able to log in. This is the script:
```
$imageName = 'bcinsider.azurecr.io/bcsandbox-master:de'
$containerName = 'bcpreview'
New-BCContainer -accept_eula -containerName $containerName -imageName $imageName -assignPremiumPlan
```

Further information:
If I add further users that don't have an entry in the 'user plan'-table, then everything is fine and they can log in. The login fails only for users which have the 'user plan'-table-entry, so I'm not able to test the premium mode in the de-version.
Don't know if this is an error in the navcontainerhelper or in the de-image itself?!

**Comment by DavidFeldhoff** [comment]
btw the image 'mcr.microsoft.com/businesscentral/sandbox:de' works with assignpremiumplan (login is possible)

**Comment by freddydk** [comment]
What version of NavContainerHelper are you running?

**Comment by DavidFeldhoff** [comment]
I'm using version 0.6.2.95

**Comment by freddydk** [comment]
What error do you get when trying to open the web client?
Have you tried adding -updateHosts?
Could you display the full output of new-navcontainer?
(I tried to copy/paste your script - and I can login)

**Comment by DavidFeldhoff** [comment]
- I tried adding -updatehost
- I tried using username/password
- I tried another containername (9 to be exactly ^^)
- Here you can see the error in the webclient:
![Uploading bcpreview webclient.png…]()

- Here is the log: (The warning message in the first line exists because of my 'docker login' command to use the bcinsider registry)
```
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
Anforderung für Windows PowerShell-Anmeldeinformationen.
Using Windows Authentication. Please enter your Windows credentials.
Password for user xgwsdfe: ***************
NavContainerHelper is version 0.6.2.95
Host is Microsoft Windows 10 Pro - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image bcinsider.azurecr.io/bcsandbox-master:de-ltsc2019
Removing bcpreview from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bcpreview
Creating Container bcpreview
Version: 15.0.35375.0-de
Platform: 15.0.35129.0
Generic Tag: 0.0.9.91
Container OS Version: 10.0.17763.615 (ltsc2019)
Host OS Version: 10.0.17763.678 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale de-DE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\bcpreview\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupNavUsers.ps1
- updatehosts.ps1
Creating container bcpreview from image bcinsider.azurecr.io/bcsandbox-master:de-ltsc2019
2ce63bc0f70cd7c20e676db9e4f4e99ab21ebd3ec8ab8235b9f6338d00a2b42a
Waiting for container bcpreview to be ready
Initializing...
Starting Container
Hostname is bcpreview
PublicDnsName is bcpreview
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user xgwsdfe
Setting SA Password and enabling SA
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Assign Premium plan for BCPREVIEW\XGWSDFE
Container IP Address: 172.20.70.25
Container Hostname  : bcpreview
Container Dns Name  : bcpreview
Web Client          : http://bcpreview/BC/
Dev. Server         : http://bcpreview
Dev. ServerInstance : BC

Files:
http://bcpreview:8080/al-4.0.161867.vsix

Initialization took 73 seconds
Ready for connections!
Reading CustomSettings.config from bcpreview
Creating Desktop Shortcuts for bcpreview
Container bcpreview successfully created

```

**Comment by freddydk** [comment]
The Web Client is a Javascript app, which inside the browser stores state.
It looks like the Web Client has some state stored from connecting to the base instance and somehow this conflicts when connecting to the de instance.
If you remove cookies etc. - or maybe run in private, it might solve the issue.

**Comment by freddydk** [comment]
Btw - the latest version is 15.0.34855.0-de - which is somewhat newer than your container. Maybe your base version is newer and somehow the web client state or other things conflicts.

**Comment by DavidFeldhoff** [comment]
Hi Freddy, why is 34855 the latest version? Am I checking the wrong source?
I am using this command to see the tags:
`az acr repository show-tags --name 'bcinsider' --repository 'bcsandbox-master' --username [username] --password [password] --top 500 --orderby time_desc --detail -o table`
There I can see that
- 15.0.34855.0-de was created on 2019-08-04T13:04:42.4899847Z
- 15.0.35005.0-de was created on 2019-08-09T09:17:00.085222Z
- 15.0.35178.0-de was created on 2019-08-13T13:05:22.3668238Z
- 15.0.35375.0-de was created on 2019-08-17T12:53:10.8193982Z

As you can see in the log I am using the 35375 version. Is there something like a release-process which I missed so that we all shouldn't use the >35005 tags at this time?

**Comment by freddydk** [comment]
My bad 35375 is the newest, you are right.
I am still convinced that this is a problem on your box, probably in the web client, I cannot reproduce the problem.

**Comment by DavidFeldhoff** [comment]
I just checked your suggestions and started in the edge-private mode. In addition I tried to use the chrome browser and chrome-private mode. It always results in the error.

I am wondering why it works for you because I can clearly reproduce this phenomenon, so let me please explain once again how I do this:
I will create two containers. The first one I create with the following script:
```
docker login -u [username] -p [password]
$imageName = 'bcinsider.azurecr.io/bcsandbox-master:de'
$containerName = 'bcpreview'
$secretPassword = ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force
$credential = New-Object pscredential 'david', $secretPassword

New-BCContainer -accept_eula `
                -containerName $containerName `
                -auth UserPassword `
                -Credential $credential `
                -imageName $imageName `
                -assignPremiumPlan `
                -updateHosts

docker cp "C:\temp\SetupNavUsers.ps1" bcpreview:"C:\Run"
docker exec bcpreview powershell -command "C:\Run\SetupNavUsers.ps1"
```

This is the Script: [SetupNavUsers.ps1.txt](https://github.com/microsoft/navcontainerhelper/files/3524005/SetupNavUsers.ps1.txt). It just adds another user 'freddy' without the premium plan.
The result is that user 'david' (has premium plan) could not log in - user 'freddy' (has not the premium plan) can log in.

Then I create another 'bcpreview2'-container, so that user 'freddy' gets also the premium plan with the following script (just added the -myscript-parameter instead of the docker exec command):
```
docker login -u [username] -p [password]
$imageName = 'bcinsider.azurecr.io/bcsandbox-master:de'
$containerName = 'bcpreview2'
$secretPassword = ConvertTo-SecureString -String "P@ssword1" -AsPlainText -Force
$credential = New-Object pscredential 'david', $secretPassword

New-BCContainer -accept_eula `
                -containerName $containerName `
                -auth UserPassword `
                -Credential $credential `
                -imageName $imageName `
                -assignPremiumPlan `
                -updateHosts `
                -myScripts @("c:\temp\SetupNavUsers.ps1")
```

Result: No user can log in because both have the premium plan.
As I just said I have the problem only when I use the de-version. The w1-version is fine..
Btw I create the containers on a new Azure-VM (Win10), so I doubt it is the environment..
But the more I test the more I think it's the image itself and not a problem with the navcontainerhelper.. :/

**Comment by freddydk** [comment]
Ok, I can definately reproduce the issue now.
Sorry that I wasn't able to do this before, but was me running on an old image, which works.
The reason is, that all localizations in the latest builds have an empty Plan table, meaning that it is a platform bug.
A fix is on the way and I will answer on this thread when a docker image with this fix is available.
Until then, AssignPremiumPlan with local sandbox builds is not working.
Sorry for the inconvenience, sorry that it took so much time for me to make a repro and thanks for being persistent:-)

**Comment by freddydk** [comment]
New images created with a new build (15.0.35879.0), which solves this problem.
