### ISSUE TITLE
Get-NavContainerAppInfo can return one app multiple times

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#570]
I have situation, where I am using container with only one tenant, but the command

` Get-NavContainerAppInfo -containerName XXX -tenantSpecificProperties -sort None
`
is returning one app, one version multiple times. Seems that it is added as standard app and even as dependency of another app. I will dig more to find the problem and potentially do the bugfix, but I am not sure if I will enough time till next week.

**Comment by kine** [comment]
Additional info:
Result is duplicated even when -tenantSpecificProperties is not use nor None is changed to anything else.

**Comment by freddydk** [comment]
If you enter a powershell command in the container, then Get-NavAppInfo must also duplicate them.
Are all instances installed and published?

**Comment by kine** [comment]
No, it was in situation, that not all app versions were installed and published. Get-NAVAppInfo is giving each app/version only once. I think that it is because multiple version of one app exists, thus it will take the dependencies again and put them into list again. I will try to do more research when I will find some time. Right now I solved it with using

`Select-Object -Unique -Property *`

on the result...

**Comment by kine** [comment]
Ok, tested it now (cannot leave it without testing for now :-))

If there is only one instance of the app- all is ok
If I published older version to have two version of same app - returns 4 apps - each version 2 times
If I published another older version - returns 9 apps, each version 3 times...

The app do not need to have dependencies. Just any app with multiple different versions published.

**Comment by freddydk** [comment]
Any chance you can email me a .bak file and a imagename that has this problem?

**Comment by kine** [comment]
Email on the way...

**Comment by freddydk** [comment]
Fixed in 0.6.3.4
