### ISSUE TITLE
Extract-FilesFromNavContainerImage /Extract-FilesFromBCContainerImage

### ISSUE THREAD

**Issue by kalyankandimalla** [microsoft/navcontainerhelper#576]
Running this command does not generate filesrelated to Upgrade toolkit, Test toolkit

**_Extract-FilesFromBCContainerImage -extract all -imageName bcinsider.azurecr.io/bcsandbox-master:15.0.34648.0-nl-ltsc2016 -path D:\AL\BCFall\Files_**

**Comment by freddydk** [comment]
Upgradetoolkit and testtoolkit wasn't available in the containers you specify up there.
TestToolkit is available in the latest in the form of 3 apps.

**Comment by kalyankandimalla** [comment]
thanks, will that be added in next updates.

**Comment by freddydk** [comment]
TestToolkit is there in the latest (except for a few bugs) - not sure what the idea with upgradetoolkit is - but that will be added when I get it

**Comment by kalyankandimalla** [comment]
okay Freddy, thanks for the update.
