### ISSUE TITLE
You are trying to run a container which is more than 90 days old.

### ISSUE THREAD

**Issue by StijnBt** [microsoft/navcontainerhelper#578]
This is the actual situation from which I start, the actual image was just downloaded a couple of minutes ago and there are no running containers based on this image or another.

![image](https://user-images.githubusercontent.com/37275572/63804887-745a8c00-c918-11e9-8af1-4d54dfccba25.png)

```powershell
Write-Host "Creating container..." 
$imageName = "mcr.microsoft.com/businesscentral/onprem:14.0.29537.0-be"
New-NavContainer $containername -imageName $imageName -accept_eula  -doNotCheckHealth
    -accept_outdated -licenseFile "C:\TMP\lic.flf" -auth "Windows" -updateHosts -doNotExportObjectsToText -useBestContainerOS

Write-Host "Container running" -ForegroundColor Green
```

This results in:
> Hostname is demodevext1
> PublicDnsName is demodevext1
> You are trying to run a container which is more than 90 days old.
>     Microsoft recommends that you always run the latest version of our containers.
> PublicDnsName is demodevext1
> You are trying to run a container which is more than 90 days old.
>     Microsoft recommends that you always run the latest version of our containers.
>     Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
> at <ScriptBlock>, C:\Run\navstart.ps1: line 54
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1
> Initialization of container demodevext1 failed
> At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.1\ContainerHandling\Wait-> NavContainerReady.ps1:45 char:17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization ...odevext1 failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container demodevext1 failed
> 
Kind of strange since the container is just created this instant moment and can't be 90d old. The image itself might (here not the case) be, but that can't be the problem.

navcontainerhelper version: 0.6.3.1

**Comment by tfenster** [comment]
@StijnBt the error is indeed a bit misleading, the problem actually is that the image is older than 90 days

**Comment by StijnBt** [comment]
So I ran it again and started from the situation as below:
![image](https://user-images.githubusercontent.com/37275572/63808923-5c3b3a80-c921-11e9-8ed5-2349c23de398.png)

Yet I get the same error, in this specific case I want to have docker environment based on mcr.microsoft.com/businesscentral/onprem:14.0.29537.0-be. If this image is "old" and newer CU's exist that's fine, but it should still be possible to run "older" images/cu's for testing purposes. Certainly in OnPrem scenarios or am I missing something obvious completely.

**Comment by tfenster** [comment]
@StijnBt yes, you can do that as the error message also says: `Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.` I missed the fact that you have already used `-accept_outdated`, so this actually should work and seems to me like a bug

**Comment by freddydk** [comment]
I agree, the error is misleadning.
If the script above is an exact copy/paste, then it is missing the tilde (`) at the end of the new-navcontainer and therefore the second line is not seen as a continuation of the first (https://freddysblog.com/2019/08/04/powershell-for-non-experts/).
If that is not the case, please copy/paste the full command and the full output of the new-navcontainer command.
thanks

**Comment by StijnBt** [comment]
> I agree, the error is misleadning.
> If the script above is an exact copy/paste, then it is missing the grave symbol (`) at the end of the new-navcontainer and therefore the second line is not seen as a continuation of the first (https://freddysblog.com/2019/08/04/powershell-for-non-experts/).
> If that is not the case, please copy/paste the full command and the full output of the new-navcontainer command.
> thanks

Yep... rookie mistake. My bad,
