### ISSUE TITLE
Check if extension is running at Saas returning wrong value!

### ISSUE THREAD

**Issue by EasyStep2Lean** [microsoft/navcontainerhelper#579]
When calling the following function CU9002 PermisionManager.SoftwareAsAService() to verify if I'm running in SaaS I'm getting True as return value when running in a Docker enviroment.

Microsoft_Application_14.3.34444.35040.app
Microsoft_System_14.0.34973.0.app

<img width="362" alt="Errror_Message" src="https://user-images.githubusercontent.com/17320737/63088315-e0221980-bf54-11e9-97b0-699c1100f548.png">

<img width="923" alt="Errror_Message" src="https://user-images.githubusercontent.com/17320737/63088332-ec0ddb80-bf54-11e9-839c-c9686e40c4c1.png">

**Comment by atoader** [comment]
As far as I know, there are two docker images:
- OnPrem, which comes with OnPrem demo data and uses license and permissions to determine what the users have access to. 
- Sandbox, which comes with sandbox demo data and uses entitlements and user plans to determine what the users have access to. 

As far as I can see, you are using the sandbox one which is configured to be as close as possible to the cloud sandbox i.e. it pretends it is SaaS. 

@freddydk can correct me on this.

**Comment by freddydk** [comment]
Correct.
The sandbox containers thinks that they are SaaS, that is the purpose of the sandbox containers.
Else you could have to use the mcr.microsoft.com/businesscentral/onprem:nl container.
The result of this is, that edit in excel and other things doesn't work in sandbox containers (they will try to connect to online tenants)

**Comment by freddydk** [comment]
The SoftwareAsAService function returns its value based on the content of **Membership Entitlements** table. You could delete all records in this table and restart the container - or add this to your new-navcontainer:

-myScripts @{ "AdditionalSetup.ps1" = 'Invoke-SqlCmd -Query "DELETE FROM [$databaseName].[dbo].[Membership Entitlement]"' }

Which basically adds a script to the bootstrap sequence, which deletes the content of the table.
If you want to avoid that the sandbox thinks it is a sandbox environment, you can set the environment variable IsBcSandbox to N using

-additionalParameters @("--env IsBcSandbox=N")

I don't know whether these things have other sideeffects.
