### ISSUE TITLE
Export-NavContainerObjects date and time issue

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#58]
We have most of our Workstations and Servers using Dutch Locale Settings. So when exporting objects the date time in the text files have dutch notation. When using Export-NavContainerObjects the notation is US or ENG, which causes a difference when comparing objects.
So  our objects look like this:
    Date=29-09-17;
    Time=12:00:00;
And the Export-NavContainerObjects exported objects look like this
    Date=09/29/17;
    Time=12:00:00 PM;
Do you have any solution or considerations to prevent this.
Can the navision container locale settings be  set to dutch locale settings.
Solution for now or mayby the preferred solution might be to start working with the same US or ENG settings? But our objects that we keep within VSTS already have Dutch notation, so changing that and let everyone start working with US Local settings might be a little tricky.

**Comment by freddydk** [comment]
try -additionalParameters @("-e locale=nl-NL")
it defaults the locale to the country you are installing, meaning that installing the NL version it should be nl-NL

**Comment by mheijkant** [comment]
Thanks again. This works well.
