### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by syssolmarketing** [microsoft/navcontainerhelper#582]
We are trying to test our D365 apps based off of the instructions Microsoft gave us. We are getting the following error and don't know why or how to fix it. 

{
  "telemetryId": "6ae4a6a6-813b-466c-9b94-f15e9fe41342",
  "bladeInstanceId": "Blade_e5cd5ed1b7ae4ebbbc9b0e5be013a2bb_0_0",
  "galleryItemId": "Microsoft.Template",
  "createBlade": "DeployToAzure",
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment 'Microsoft.Template' is not valid according to the validation procedure. The tracking id is '354858b8-0d4e-475e-9a24-7e29096d2964'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.",
  "details": [
    {
      "code": "TemplateFailedPrevalidation",
      "message": "The template request has multiple validation failures involving one or more Microsoft.Network resources. Please check details for information about each resource.",
      "details": [
        {
          "code": "InvalidResourceName",
          "message": "Resource name System Solutions LLC_pip is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."
        },
        {
          "code": "InvalidResourceName",
          "message": "Resource name System Solutions LLC_nic is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."
        }
      ]
    }
  ]
}

Thanks!

**Comment by freddydk** [comment]
Sorry, I cannot see anything from this.
If you start from scratch and describe what you are doing and what instructions you are following, then we might be able to figure out what's wrong

**Comment by freddydk** [comment]
and the sandbox link you got was?

**Comment by freddydk** [comment]
Ok, I just did exactly what you suggested
Added a resource group fkxx
vmname fkxx
Deploying:
![image](https://user-images.githubusercontent.com/10775043/63860937-46258c80-c9aa-11e9-8897-acd3e4c373d6.png)

It is likely because you don't have permissions to create resources in the subscription selected.

**Comment by freddydk** [comment]
Or maybe you are using names with special characters as resource group names or vm names.

**Comment by freddydk** [comment]
Probably the latter based on the error above (invalid resource name)

**Comment by freddydk** [comment]
That subscription is fine.
Can you tell me what the failing vmname and/or resource group name was - then I can make a check for that?

**Comment by freddydk** [comment]
Ok, probably the space.
Will see if I can create a better error message for stuff like this.
Thanks
