### ISSUE TITLE
Cannot open 365 BC web client installed on docker after some day

### ISSUE THREAD

**Issue by Waseemdk** [microsoft/navcontainerhelper#583]
Hi,
I was using this script to install:
New-NavContainer -accept_eula -containerName "bcsandbox" -auth NavUserPassword -imageName "mcr.microsoft.com/businesscentral/sandbox:dk" -alwaysPull -updatehosts

Installation was succesfull. It has been working fine for the last 4-5 days, but today I am not able to open my 365 BC web client. What is causing that container cannot be reach, maybe that is why I am not able to open my 365 BC web client.

![image](https://user-images.githubusercontent.com/53815948/63915816-4455da80-ca37-11e9-99f0-cad60005763d.png)
docker version:
![image](https://user-images.githubusercontent.com/53815948/63915868-5fc0e580-ca37-11e9-9510-8213b59e7705.png)
docker info:
![image](https://user-images.githubusercontent.com/53815948/63915910-76ffd300-ca37-11e9-85de-aeedb9aab244.png)
docker ps -a
![image](https://user-images.githubusercontent.com/53815948/63915961-95fe6500-ca37-11e9-9920-ad918ce0c175.png)
docker inspect bcsandbox
PS C:\WINDOWS\system32> docker inspect bcsandbox
[
    {
        "Id": "5a91d1e9aabf19f19451aa52905049c8b8719773b7c7770a074100c1fff65dcf",
        "Created": "2019-08-24T21:18:56.2257821Z",
        "Path": "powershell",
        "Args": [
            "-Command",
            "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
            ".\\Run\\start.ps1"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1304,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2019-08-24T21:19:09.8781171Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "healthy",
                "FailingStreak": 0,
                "Log": [
                    {
                        "Start": "2019-08-28T16:00:17.9309964+02:00",
                        "End": "2019-08-28T16:00:18.7807072+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-08-28T16:00:48.8071667+02:00",
                        "End": "2019-08-28T16:00:49.7558702+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-08-28T16:01:19.7910978+02:00",
                        "End": "2019-08-28T16:01:20.4623961+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-08-28T16:01:50.4916053+02:00",
                        "End": "2019-08-28T16:01:51.1089215+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    },
                    {
                        "Start": "2019-08-28T16:02:21.1334463+02:00",
                        "End": "2019-08-28T16:02:22.0978828+02:00",
                        "ExitCode": 0,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:f4874dcc9659db60ecbdb5123096c2871d9475bc903f191cd98162a51d9d3808",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\Docker\\containers\\5a91d1e9aabf19f19451aa52905049c8b8719773b7c7770a074100c1fff65dcf\\5a91d1e9aabf19f19451aa52905049c8b8719773b7c7770a074100c1fff65dcf-json.log",
        "Name": "/bcsandbox",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\bcsandbox\\my:C:\\Run\\my"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\Docker\\windowsfilter\\5a91d1e9aabf19f19451aa52905049c8b8719773b7c7770a074100c1fff65dcf"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bcsandbox\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "bcsandbox",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "ExitOnError=N",
                "locale=da-DK",
                "databaseInstance=",
                "enableApiServices=Y",
                "auth=NavUserPassword",
                "username=admin",
                "licenseFile=",
                "databaseServer=",
                "useSSL=N",
                "securePassword=76492d1116743f0423413b16050a5345MgB8AEMAYQA1AE4AcgBKAHgAcAA5AE8ALwB4AGEALwA1AFUARQBEADQANAB5AHcAPQA9AHwAMwA5AGYAZAAyADgAZAAwADYAOAAxADAAMAAyAGIAZABiADIANAA2AGIANQBiADIAOABlAGIANgAwADYANAA4AGUAMwA
3ADAAMQBkAGQANQAwADUAYgAwAGYAOAA1ADcAOQA1ADcAYgBiAGQANAA5AGMAZABhADAAMgAyAGMAYQA=",
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "removePasswordKeyFile=Y",
                "accept_eula=Y",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                "DatabaseName=FinancialsDK",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/2a8564b3-2e6d-43e2-83d0-75327b9f7199",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-3.0.150570.vsix",
                "IsBcSandbox=Y",
                "CountryCode=DK",
                "DEVPREVIEWURL=https://nav2016wswe0.blob.core.windows.net/dvd/97767bc6-9db8-495b-9c67-587acbdcfbc9"
            ],
            "Cmd": [
                "powershell",
                "-Command",
                "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';",
                ".\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "mcr.microsoft.com/businesscentral/sandbox:dk-ltsc2019",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "DK",
                "created": "201908191241",
                "cu": "update27",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.17763.615",
                "platform": "14.0.35358.0",
                "tag": "0.0.9.91",
                "version": "14.3.34444.35404"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "5a91d1e9aabf19f19451aa52905049c8b8719773b7c7770a074100c1fff65dcf",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "5a91d1e9aabf19f19451aa52905049c8b8719773b7c7770a074100c1fff65dcf",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "4a4022779311273ef401f57cf0bf1295257a3587a98cdbf62e204bed1eb1900a",
                    "EndpointID": "cbc6d46e2742a45aaeb17e20833c7a9665ab5629cab3c33d6b844323630618e8",
                    "Gateway": "192.168.176.1",
                    "IPAddress": "192.168.180.155",
                    "IPPrefixLen": 24,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:58:ed:94",
                    "DriverOpts": null
                }
            }
        }
    }
]
If you need any more information to find out what is causing that I am not able to logon to 365 BC webclient again. Please let me know.

**Comment by Waseemdk** [comment]
Ping results:
![image](https://user-images.githubusercontent.com/53815948/63916698-3bfe9f00-ca39-11e9-8dc0-558f293002c2.png)

**Comment by freddydk** [comment]
I think you have a Zombie container.
https://freddysblog.com/2019/08/07/zombie-containers-skip-this-build/
You can fix it by following the suggestion in the comments

**Comment by Waseemdk** [comment]
Thanks for your quick answer. Last time it was caused because docker desktop version 2.1.0.0 had a bug. Do you the new updated docker desktop 2.1.0.1 also has a bug?

**Comment by freddydk** [comment]
The Zombie bug hasn't been fixed yet - waiting for a release that fixes it.
I also created a script, which restarts zombie containers - use at own risk
https://raw.githubusercontent.com/microsoft/nav-arm-templates/master/RestartContainers.ps1

**Comment by Waseemdk** [comment]
Thanks Freddy.
