### ISSUE TITLE
Creating BC OnPrem based on image mcr.microsoft.com/businesscentral/onprem:1904-cu3-dk-ltsc2019 fails after 10 min

### ISSUE THREAD

**Issue by kasperdj** [microsoft/navcontainerhelper#584]
On Windows 10 version 1903 and running Docker Desktop 2.1.0.1 I run the following script:

New-NavContainer -isolation process -auth NavUserPassword -updateHosts -accept_outdated -enableSymbolLoading -doNotExportObjectsToText -includeCSide -containerName $ContainerName -imageName "mcr.microsoft.com/businesscentral/onprem:$(1904-cu3-dk)" -accept_eula -licenseFile $LicensFile.FullName -includeTestToolkit -restart no -useBestContainerOS

The scripts runs for approx 10 minutes and then it fails. 
Below you will find the output data and I have verified that the license used has not expired and is for Business Central 365 OnPrem version 14:

Looking for update to module: NavContainerHelper

Import Module NavContainerHelper

Creating Container: SVS-14-CU3-DK
NavContainerHelper is version 0.6.3.1
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Pulling image mcr.microsoft.com/businesscentral/onprem:1904-cu3-dk-ltsc2019
1904-cu3-dk-ltsc2019: Pulling from businesscentral/onprem
65014b3c3121: Already exists
e7a74de96ddd: Pulling fs layer

pulling lines squashed in this output...

98b7f364024f: Pull complete
Digest: sha256:ce272724ce0ed6cf7ef526ac6c36f1bff1f8789d168fc2c180079bfb9af33e0a
Status: Downloaded newer image for mcr.microsoft.com/businesscentral/onprem:1904-cu3-dk-ltsc2019
Using image mcr.microsoft.com/businesscentral/onprem:1904-cu3-dk-ltsc2019
Creating Container SVS-14-CU3-DK
Using license file \\ev-filsrv01\Navision\EV Internal Tools\Powershell\License\Udvikler MS Dynamics 365 BC_incl ISV_V14_050719.flf
Version: 14.4.35602.0-dk
Platform: 14.0.35570.0
Generic Tag: 0.0.9.92
Container OS Version: 10.0.17763.678 (ltsc2019)
Host OS Version: 10.0.18362.295 (1903)
A better Generic Container OS exists for your host (1903)
Creating temp container from mcr.microsoft.com/businesscentral/onprem:1904-cu3-dk-ltsc2019 and extract necessary files
Extracting Service Tier and WebClient Files
Extracting Windows Client Files
Extracting Configuration packages
Extracting Test Assemblies
Extracting Test Toolkit
Extracting Upgrade Toolkit
Extracting Extensions
Extracting Applications
Extracting Files from Run folder
Extracting Database Files
Downloading prerequisites
Downloading C:\ProgramData\NavContainerHelper\14.4.35602.0-dk-Files\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading C:\ProgramData\NavContainerHelper\14.4.35602.0-dk-Files\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.ms
i
Downloading C:\ProgramData\NavContainerHelper\14.4.35602.0-dk-Files\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Performing cleanup
Removing temp container
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Pulling image mcr.microsoft.com/dynamicsnav:generic-1903
generic-1903: Pulling from dynamicsnav
Digest: sha256:8ede5835811505be10d1bdc118a4c9281fdf6acb8900d356f45171cce5d416af
Generic Container OS Version: 10.0.18362.295 (1903)
Generic Tag of better generic: 0.0.9.92
Using locale da-DK
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\SVS-14-CU3-DK\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container SVS-14-CU3-DK from image mcr.microsoft.com/dynamicsnav:generic-1903
705982e6f34cdd07dea1b9f5b46ec8b69abf43b90fdbeac1bdd28b383faec300
Waiting for container SVS-14-CU3-DK to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Danish_Greenlandic_100_CI_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improv
e the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 115 seconds
Installation complete
Initializing...
Starting Container
Hostname is SVS-14-CU3-DK
PublicDnsName is SVS-14-CU3-DK
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 0A9997D50C9F0F623641AAB23AB24FAA75147CAB
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
The server "NAV" was unable to process the request. The application will close.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Danish_Greenlandic_100_CI_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improv
e the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 115 seconds
Installation complete
Initializing...
Starting Container
Hostname is SVS-14-CU3-DK
PublicDnsName is SVS-14-CU3-DK
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 0A9997D50C9F0F623641AAB23AB24FAA75147CAB
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
The server "NAV" was unable to process the request. The application will close.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1

An Error Occurred:
Initialization of container SVS-14-CU3-DK failed

Press Key To Continue!

**Comment by kasperdj** [comment]
Container Event Log attached
[SVS-14-CU3-DK.zip](https://github.com/microsoft/navcontainerhelper/files/3555380/SVS-14-CU3-DK.zip)

**Comment by freddydk** [comment]
If you leave out the licensefile parameter - does it work then?

**Comment by kasperdj** [comment]
It works without the license parameter, but just gives some warnings about incompatible license in the container. See details below.

BC License details:

Microsoft Software License Information
Copyright (C) 2007-2018 Microsoft Corporation. All rights reserved
****************************************************************************
VOICE Kontonummer       : 4944540
Licensed to             : Elbek & Vejrup A/S
                          Tangen 6
                          
                          
                          rhus N
                          84
                          8200
                          Denmark

Produktlinie            : Microsoft Dynamics 365 Business Central on premises
Produktudgave           : Unspecified
Produktversion	        : 14
Land                    : Denmark
Sprog                   : Danish
Oprettet Dato           : 05-07-2019 00:37:55 (-07:00)
Udl>ber                 : 03-10-2019
Konfiguration           : BC365
****************************************************************************
Navn                                                                   Antal
----------------------------------------------------------------- ----------
Country Code: Denmark                                                      1
Demo/Dev Named User                                                      150
Dyn365 Business Central Team Members                                     300
Partner Demo/Dev Module                                                    1
Product Specialist                                                         1
Solution Developer                                                         1

****************************************************************************


Container details (take 2 without license parameter):

Creating Self Signed Certificate
Self Signed Certificate Thumbprint 7BA0A3F7245F60E89636413FBDCAA9B661277540
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Setting SA Password and enabling SA
Creating krj as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.20.168.177
Container Hostname  : SVS2-14-CU3-DK
Container Dns Name  : SVS2-14-CU3-DK
Web Client          : http://SVS2-14-CU3-DK/NAV/
Dev. Server         : http://SVS2-14-CU3-DK
Dev. ServerInstance : NAV

Files:
http://SVS2-14-CU3-DK:8080/al-3.0.154634.vsix

Initialization took 97 seconds
Ready for connections!
Reading CustomSettings.config from SVS2-14-CU3-DK
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Creating Desktop Shortcuts for SVS2-14-CU3-DK
Importing Objects from C:\TestToolKit\CALTestCodeunits.DK.fob (container path)
Importing Objects from C:\TestToolKit\CALTestLibraries.DK.fob (container path)
Importing Objects from C:\TestToolKit\CALTestRunner.fob (container path)
Adding SQL-Server credentials for authentication
Creating application symbols in SVS2-14-CU3-DK
[0] [29-08-19 14:11:42] The command completed successfully in '371' seconds.
Symbols successfully generated
TestToolkit successfully imported
Container SVS2-14-CU3-DK successfully created

Clone: https://bitbucket.org/ElbekVejrup/svane-shipping.git

Copy Add-ins

Welcome to the Server Admin Tool Shell!
For a complete list of Server cmdlets type

Get-Command -Module Microsoft.Dynamics.Nav.Management, Microsoft.Dynamics.Nav.Apps.Management

VERBOSE: Performing the operation "Set-NAVServerInstance" on target "ServerInstance = MicrosoftDynamicsNavServer$NAV, Start = False, Stop = False,
 Restart = True".
VERBOSE: Attempting to stop service MicrosoftDynamicsNavServer$NAV
VERBOSE: Service MicrosoftDynamicsNavServer$NAV is stopped
VERBOSE: Service HTTP is already running
VERBOSE: Attempting to start service MicrosoftDynamicsNavServer$NAV
VERBOSE: Service MicrosoftDynamicsNavServer$NAV is running

Open VS Code

Done

**Comment by freddydk** [comment]
How do you specify the license parameter?
Is it a URL or is it a local file?

**Comment by kasperdj** [comment]
It will be copied from UNC Share to local folder and used as parameter, See full script here and check about line 70-76 for details:

$ContainerName = 'SVS2-14-CU3-DK'
$BCTag = '1904-cu3-dk'
$GitRepository = 'https://bitbucket.org/ElbekVejrup/svane-shipping.git'
if (-not ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {   
    $Arguments = "& '" + $myinvocation.mycommand.definition + "'"
    if (!$myinvocation.MyCommand.Definition.StartsWith("\\")) {
        $DriveInfo = New-Object System.IO.DriveInfo($myinvocation.MyCommand.Definition)
        $DriveInfo.drivetype | Out-Null
        If ($DriveInfo.drivetype -ne "Fixed") {
            $DrivePrefix = $myinvocation.MyCommand.Definition.Substring(0, 2);
            $ManagementObject = New-Object System.Management.ManagementObject("Win32_LogicalDisk='$($DrivePrefix)'")
            $UNCPrefix = $ManagementObject["ProviderName"].ToString()
            $Arguments = $Arguments.Replace($DrivePrefix, $UNCPrefix)
        }
    }
    Start-Process powershell -Verb runAs -ArgumentList $Arguments
    Break
}
Clear-Host
$ContinueInstall = $true
Try {
    $ContainerIds = docker ps -a --filter name=$ContainerName --format '{{.Names}};{{.ID}};{{.Status}}' --no-trunc 
    $ContainerIds | ForEach-Object {
        if ($_.Split(';').Item(0).ToUpper() -eq $ContainerName.ToUpper()) {
            $ContainerId = $_.Split(';').Item(1)
            $IsRunning = ($_.Split(';').Item(2).SubString(0,2).ToUpper() -eq "UP")
        }
    }
    if ($ContainerId) {
        Write-Host
        Write-Host -ForegroundColor Red "Container " -NoNewline
        Write-Host -ForegroundColor Green $ContainerName -NoNewline
        Write-Host -ForegroundColor Red " is allready created do you want to overwrite (Y/N) " -NoNewline
        $ContinueInstall = (Read-host).ToUpper() -eq 'Y'
        if (!$ContinueInstall) {
            if (!$IsRunning) {
                Write-Host
                Write-Host -ForegroundColor Green "Start Container: $ContainerName"
                docker start $ContainerId
            }
        }
    }
    if ($ContinueInstall) {
        $Module = "NavContainerHelper"
        $ModuleExist = Get-Module -Name $Module -ListAvailable
        if (!($ModuleExist)) {
            Write-host
            Write-Host -ForegroundColor Green "Install $Module (Y/N)" -NoNewline
            $Install = (Read-host).ToUpper()
            if ($Install -eq 'Y') {
                Write-Host
                Write-Host -ForegroundColor Green "Installing $Module"
                Install-Module -Name $Module -Force
                Import-Module -Name $Module
            }
        }
        else {
            Write-Host
            Write-Host -ForegroundColor Green "Looking for update to module: $Module" 
            $NewVersion = $(Find-Module $Module) | Select-Object Version
            $CurrentVersion = $ModuleExist[0] | Select-Object Version
            if ($NewVersion.Version -gt $CurrentVersion.Version) {
                Write-Host
                Write-Host -ForegroundColor Green "Update $Module from: $($CurrentVersion.Version) to: $($NewVersion.Version)"
                Update-Module $Module -Force
                Get-InstalledModule $Module -RequiredVersion $CurrentVersion.Version | Uninstall-Module
            }
            Write-Host
            Write-Host -ForegroundColor Green "Import Module $Module"
            Import-Module -Name $Module -WarningAction SilentlyContinue
        }
        Write-Host
        $LicensFile = Get-Item "\\ev-filsrv01\Navision\EV Internal Tools\Powershell\License\*BC*.flf" | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($LicensFile) {
            Copy-Item -Path $LicensFile -Destination (Join-Path "$env:ProgramData\NavContainerHelper" "BC.flf") -Force -Recurse 
        } else {
            $LicensFile = Get-Item "$env:ProgramData\NavContainerHelper\BC.flf" -ErrorAction SilentlyContinue
        }
        if (!$LicensFile) {
            Throw "No Licens File Exist! ($($env:ProgramData)\NavContainerHelper\BC.flf)"
        }
        Write-Host -ForegroundColor Green "Creating Container: $ContainerName"
        # New-NavContainer -isolation process -auth NavUserPassword -updateHosts -accept_outdated -enableSymbolLoading -doNotExportObjectsToText -includeCSide -containerName $ContainerName -imageName "mcr.microsoft.com/businesscentral/onprem:$($BCTag)" -accept_eula -licenseFile $LicensFile.FullName -includeTestToolkit -restart no -useBestContainerOS
        New-NavContainer -isolation process -auth NavUserPassword -updateHosts -accept_outdated -enableSymbolLoading -doNotExportObjectsToText -includeCSide -containerName $ContainerName -imageName "mcr.microsoft.com/businesscentral/onprem:$($BCTag)" -accept_eula -includeTestToolkit -restart no -useBestContainerOS
    }
    if (($GitRepository -ne '') -and ($GitRepository)) {
        $LocalRepoFolder = (Join-Path $([Environment]::GetFolderPath("MyDocuments")) "Al")
        if ((Test-Path $LocalRepoFolder) -ne $true) {
            New-Item -Path $LocalRepoFolder -ItemType Directory
        }
        $RepoFolder = (Join-Path $LocalRepoFolder $([System.IO.Path]::GetFileNameWithoutExtension($($GitRepository.Split('/') | Select-Object -Last 1))));
        if ((Test-Path $RepoFolder) -ne $true) {
            Push-Location $LocalRepoFolder -StackName "Default"
            Write-Host
            Write-Host -ForegroundColor Green "Clone: $GitRepository"
            Start-Process Git -ArgumentList "clone $GitRepository" -Wait
            Pop-Location -StackName "Default"
        }
        Push-Location $RepoFolder
        if (Test-Path .\App\Add-ins) {
            Write-Host
            Write-Host -ForegroundColor Green "Copy Add-ins"
            $CopySession = New-PSSession -ContainerId (Get-NavContainerId $ContainerName) -RunAsAdministrator
            $AddinsFolder = Invoke-Command -Session $CopySession -ScriptBlock {
                return Get-Item 'C:\Program Files\Microsoft Dynamics NAV\*\Service\Add-ins\'
            }
            Copy-Item -ToSession $CopySession -Path ".\App\Add-ins\*" -Destination $AddinsFolder -Recurse -Force
            Invoke-Command -Session $CopySession -ScriptBlock {
                Import-Module 'C:\Program Files\Microsoft Dynamics NAV\*\Service\NavAdminTool.ps1' | Out-Null
                $CurrentServerInstance = Get-NAVServerInstance -ServerInstance NAV
                $CurrentServerInstance | Set-NAVServerInstance -Restart -Verbose
            }
            Remove-PSSession $CopySession
        }

        Write-Host
        Write-Host -ForegroundColor Green "Open VS Code"
        if (Test-Path (Join-Path $RepoFolder App)) {
            Code (Join-Path $RepoFolder App)
        }
        else {
            Code $RepoFolder
        }
    }
} Catch {
    if ($CopySession) {
        Remove-PSSession $CopySession
    }
    Write-Host
    Write-Host -ForegroundColor Red "An Error Occurred:"
    Write-Host -ForegroundColor Red $_
    Write-Host
    Write-Host -ForegroundColor Green "Press Key To Continue!" -NoNewline
    Read-Host
} 
Write-Host
Write-Host -ForegroundColor Green "Done"
Start-Sleep -Seconds 2

**Comment by freddydk** [comment]
Could the file be marked as blocked?
before new-navcontainer you could call unblock-file $licensefile.fullname  - don't know if that changes anything

**Comment by kasperdj** [comment]
The file is not in quarantine by Windows and the GPO for preserving zone info when files are copied over the network is disabled on my pc.

When I copy the file manually and check the file properties on the destination it is not blocked either.

I will implement your suggestion in our script and manually install our dev license into the container.

I will be out of office until tuesday, but have enough input/inspiration to handle this situation. Thank for your input.

**Comment by kasperdj** [comment]
Just as information. 

The issue I had with using the license file from UNC share was not an issue my colleagues had even though we have the same permissions to the UNC share and are running same version of NAV-containerhelper.

Anyways; it works for everybody if we copy the license file from the UNC share to $env:ProgramData\NavContainerHelper\BC.flf and pass on this local path as the parameter for the container creation.
