### ISSUE TITLE
Question : Issue after windows 10 update

### ISSUE THREAD

**Issue by vempathi4sir** [microsoft/navcontainerhelper#587]
Good Day 
I was using a NAV BC image based on LTSC 2019 
mcr.microsoft.com/businesscentral/onprem:ltsc-2019

After windows 10 update last month to Version 1903 (OS Build 10.0.18362.295) from version 1809 (OS Build 17763.720), I cannot no longer use my earlier image.

Error message "The container operating system does not match the host operating system"

Can you guide if it possible to still use the earlier image .

**Comment by freddydk** [comment]
If you would provide the full command you are using (and the full output), I would probably be able to answer the question.
The output would show which image you have, whether you are running process or hyperv isolation etc. etc.
My guess is that you have -isolation process specified - remove that and you will get hyperv.
If hyperv isn't running you can add -usebestcontaineros.
But that is me guessing - provide the command and the output and I would be more confident.

**Comment by vempathi4sir** [comment]
Good Day Freddy
Thank you very much for coming back

first below is the command I am running

New-NavContainer -containerName "incadeadms" -accept_eula -clickonce -auth Windows -additionalParameters @(' --env exitonerror=N') -shortcuts Desktop -isolation process -updateHosts -imageName incadea.n.7.3.0_preview:august2019
![Docker_Container_error](https://user-images.githubusercontent.com/45388763/64102585-90bf5400-cd70-11e9-9575-3960b7374e6a.jpg)


I am using Process isolation at the moment, I don't wish to go for Hyper V , 

this image is prepared based on mcr.microsoft.com/businesscentral/onprem:ltsc2019 ( we replaced the demo database and add some more websites)

this command was working fine before the windows 10 update, the windows 10  was updated to 1903 (OS Build 18362.295) from 1809 (Build 17763.720) 

I have attached the error message along with this message.

**Comment by freddydk** [comment]
You cannot run a 1809 image on 1903 with process isolation - the operating systems are not compatible.
If you replaced the image - you would have to create a 1903 version of the image.
I normally recommend doing these changes Just-In-Time, this means that -useBestContainerOS would be able to do a just-in-Time replatform as well.

**Comment by vempathi4sir** [comment]
Okie 
I will get the latest version ( 1903) version and do the chanages as you have suggested.
thank you 
have a nice day

**Comment by freddydk** [comment]
Remember that we do NOT create images for minor windows releases - 1903 only has the generic image.

**Comment by vempathi4sir** [comment]
Thank you
Is there already an generic image 
like mcr.microsoft.com/dynamics-nav:generic-1903 to pull  or do I have to customize from your build script

**Comment by freddydk** [comment]
Yes, the generic 1903 is available
