### ISSUE TITLE
Export-bccontainerdatabaseasbacpac should not remove license

### ISSUE THREAD

**Issue by eivindgiske** [microsoft/navcontainerhelper#588]
When deploying to Azure SQL, NST will not start, nor will Dev Env allow logon when the License field is NULL in $ndo$dbproperty. One of the prereq's for deploying to Azure is that there is a per database license in place before BACPAC extraction.

Thus, the code line: Invoke-Sqlcmd @params -Query "USE [$DatabaseName] UPDATE [dbo].[`$ndo`$dbproperty] SET [license] = NULL"
should be disabled, or a parameter to skip it, provided.

**Comment by freddydk** [comment]
Might be a good idea to add a parameter, but when you say deploying to Azure - how are you doing this?
I am thinking that very frequently, the license you want to use during deployment and during development are different, meaning that there should be a way to override or insert the license during deployment anyway.

**Comment by eivindgiske** [comment]
Hi Freddy, I'm taking the bacpac, and using the Azure Portal to "Import Database" (from bacpac). After that I'm installing BC on a VM, like normal. This makes the NST stop immediately upon start, with a reference to missing stuff in the DB in Event Log (not a very descriptive error message), and the Dev Env won't connect either with an error regarding License per database. So I'm stuck with a DB that is not accessible from the BC tools. Only option then is to store the license data in the $ndo$dbproperty table via SQL tools, and everything's back on track.

**Comment by freddydk** [comment]
Marking as won't fix - the workaround to add the license file seems ok.
