### ISSUE TITLE
Issue creating Purchase invoice - only on latest docker image

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#589]
Hi - I downloaded the latest image and created new container. When I open purchase invoice, I am getting following error
<img width="1" alt="image" src="https://user-images.githubusercontent.com/38437776/64042384-8a35a000-cb16-11e9-924b-08643ee87823.png">
when I click OK to ignore the message, after 2 mins session times out.
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/38437776/64042413-99b4e900-cb16-11e9-894c-dc2e8b68abf9.png">

Please note: this issue happens only in docker image but not in business central prod/sandbox.

**Comment by freddydk** [comment]
You have to specify the command you use and the full output of that command in order for me to have a chance of helping you.

**Comment by Bssivivek** [comment]
Please find the command below

New-NavContainer -containerName sb1 -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -includecside -licenseFile "C:\Work\SB-D365BC.flf" -updateHosts

Please find the full output below

PS C:\WINDOWS\system32> New-NavContainer -containerName sb1 -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019 -includecside -licenseFile "C:\Work\SB-D365BC.flf" -updateHosts
NavContainerHelper is version 0.6.3.3
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Creating Container sb1
Using license file C:\Work\SB-D365BC.flf
Version: 14.3.34444.35087-US
Platform: 14.0.35036.0
Generic Tag: 0.0.9.91
Container OS Version: 10.0.17763.615 (ltsc2019)
Host OS Version: 10.0.17763.678 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\sb1\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container sb1 from image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
d13a31304e13171a358b3395e58116dc0d889c0ab0756547a63c34fc0768bae6
Waiting for container sb1 to be ready
Initializing...
Starting Container
Hostname is sb1
PublicDnsName is sb1
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 77E2F85CF043DFE51B5B1B0520061EFD6195EAE1
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating viveksarma as SQL User and add to sysadmin
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.27.18.174
Container Hostname  : sb1
Container Dns Name  : sb1
Web Client          : http://sb1/NAV/
Dev. Server         : http://sb1
Dev. ServerInstance : NAV

Files:
http://sb1:8080/al-3.0.150570.vsix

Initialization took 72 seconds
Ready for connections!
Reading CustomSettings.config from sb1
Creating Desktop Shortcuts for sb1
Container sb1 successfully created

**Comment by freddydk** [comment]
And when you get the error - could you use Get-NavContainerEventlog sb1 - and see if there are any error entries?

**Comment by freddydk** [comment]
The bug comes from some extensions behaving badly.
If you unpublish these after creating the container:
```
UnPublish-BCContainerApp -containerName sb1 -publisher Microsoft -unInstall -doNotSaveData -force -version 14.4.35602.0 -appName "Dynamics GP History Smartlists"
UnPublish-BCContainerApp -containerName sb1 -publisher Microsoft -unInstall -doNotSaveData -force -version 14.4.35602.0 -appName "Dynamics GP Intelligent Cloud"
UnPublish-BCContainerApp -containerName sb1 -publisher Microsoft -unInstall -doNotSaveData -force -version 14.4.35602.0 -appName "Dynamics GP Data Migration"
UnPublish-BCContainerApp -containerName sb1 -publisher Microsoft -unInstall -doNotSaveData -force -version 14.4.35602.0 -appName "Sales and Inventory Forecast"
```
then you should be good.
Will report this as a bug internally for an upcoming version

**Comment by freddydk** [comment]
This is a bug in the above applications - will be fixed in a future build

**Comment by Bssivivek** [comment]
Thanks a lot!! it works fine now after i uninstall/unpublish these apps.
