### ISSUE TITLE
Building DevPreview image fails

### ISSUE THREAD

**Issue by SShadowS** [Microsoft/navcontainerhelper#59]
**Info:**
Client:
 Version:      17.11.0-ce
 API version:  1.34
 Go version:   go1.8.4
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:30:11 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.11.0-ce
 API version:  1.34 (minimum version 1.24)
 Go version:   go1.8.5
 Git commit:   1caf76c
 Built:        Mon Nov 20 18:34:19 2017
 OS/Arch:      windows/amd64
 Experimental: true

Ekstra info:
Did this before starting:
`install-module navcontainerhelper -force`

**When running the following:**
`New-NavContainer -accept_eula -containerName DevPreview -imageName microsoft/dynamics-nav:devpreview`

**This happens...**

PS C:\WINDOWS\system32> New-NavContainer -accept_eula -containerName DevPreview -imageName microsoft/dynamics-nav:devpreview
Pulling docker Image microsoft/dynamics-nav:devpreview
devpreview: Pulling from microsoft/dynamics-nav
3889bb8d808b: Pull complete
8df8e568af76: Pull complete
2358a8661e1b: Pull complete
73b652de1af8: Pull complete
4aa3b2881668: Pull complete
1501480f7dbc: Pull complete
c493efeaca48: Pull complete
86e2c8832925: Pull complete
b6a197b62223: Pull complete
466f89b12fad: Pull complete
235fa8b41209: Pull complete
ed22543788c3: Pull complete
ddb2126058bb: Pull complete
417901b29c94: Pull complete
3190d5332972: Pull complete
ccc310df96d8: Pull complete
4f45e5a6665b: Pull complete
Digest: sha256:5b58b1013e36be1f7384a978636413a157c95785f4cc89c7f50b1398bdcf31c5
Status: Downloaded newer image for microsoft/dynamics-nav:devpreview
Creating Nav container DevPreview
Using image microsoft/dynamics-nav:devpreview
NAV Version: 11.0.19585.0-W1
Generic Tag: 0.0.4.3
Creating container DevPreview from image microsoft/dynamics-nav:devpreview
Waiting for container DevPreview to be ready, this shouldn't take more than a few minutes
Time:          ½              1              ½              2
.......................................................................................................................................................Error

Initialization of container DevPreview failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.0\ContainerHandling\Wait-NavContainerReady.ps1:3
3 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...vPreview failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container DevPreview failed

**Comment by freddydk** [comment]
try
docker ps -a
to see if the container is started - if not, try to set memory to 2G (-memoryLimit 2G)
if it is there - send docker logs and docker inspect here?

thanks

**Comment by SShadowS** [comment]
`docker ps -a`
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS                                                NAMES
fdbd3a1c76e8        microsoft/dynamics-nav:devpreview   "powershell -Command…"   22 minutes ago      Created             80/tcp, 443/tcp, 1433/tcp, 7045-7049/tcp, 8080/tcp   DevPreview

`docker logs fdbd3a1c76e8`
No result

`docker inspect fdbd3a1c76e8 > inspect.txt`
[inspect.txt](https://github.com/Microsoft/navcontainerhelper/files/1551428/inspect.txt)

**Comment by freddydk** [comment]
Sounds like you should try the -memoryLimit 2G

**Comment by SShadowS** [comment]
`new-navcontainer -accept_eula -containerName test -imageName microsoft/dynamics-nav:devpreview -memoryLimit 2G`

PS C:\WINDOWS\system32> new-navcontainer -accept_eula -containerName test -imageName microsoft/dynamics-nav:devpreview -memoryLimit 2G
Creating Nav container test
Using image microsoft/dynamics-nav:devpreview
NAV Version: 11.0.19585.0-W1
Generic Tag: 0.0.4.3
Creating container test from image microsoft/dynamics-nav:devpreview
Waiting for container test to be ready, this shouldn't take more than a few minutes
Time:          ½              1              ½              2
.......................................................................................................................................................Error

Initialization of container test failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.0\ContainerHandling\Wait-NavContainerReady.ps1:33 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container test failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container test failed

**Comment by SShadowS** [comment]
Inspect gives the following error:
...
container fdbd3a1c76e8529c3a8e1d73535ed6c728a01949fef59aa754882b28cf0e69cb encountered an error during CreateContainer: failure in a Windows system call: Beskrivelsesstrengen for parameterreferencen (%1) blev ikke fundet. 
...

**Comment by freddydk** [comment]
Could you try to follow this:
https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/
Sounds like you cannot start containers at all?
I need to fix new-navcontainer to be better at showing how to troubleshoot.
