### ISSUE TITLE
License error importing Microsoft_Test Runner.app

### ISSUE THREAD

**Issue by paul-interdyn** [microsoft/navcontainerhelper#590]
Using NavContainerHelper version 0.6.3.2, I created a new container using:

new-bccontainer -accept_eula -containerName wave2 -imageName bcinsider.azurecr.io/bcsandbox-master:us -updateHosts -doNotExportObjectsToText -includeTestToolkit -includeTestLibrariesOnly -includeAL -alwaysPulldocker

But when it got to Publishing C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app, it output the following error:

Your program license does not allow you to publish 'AL Test Suite'.
at <ScriptBlock>, <No file>: line 13
Your program license does not allow you to publish 'AL Test Suite'.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : f3172e9c22914e2512a388eba948a76cf2403b24a4c8c0619d5d217b5813ad55

The Version and Platform reported during the container creation process are:
Version: 15.0.35805.0-us
Platform: 15.0.35510.0

**Comment by freddydk** [comment]
Current version requires you to specify a license to do this.
Will check whether we can change the apps to runtime packages, which will make it possible to publish the apps without.

**Comment by paul-interdyn** [comment]
Oh ok. Where do I get a v15 license then? Didn’t see one in the Ready to go area of Collaborate and can only generate through 14 in Business Center. Using v14 kind of works but generates a lot of incompatible license warnings (and still fails to import one of the test apps).

**Comment by freddydk** [comment]
Use the 14 license - the failing app must be something else

**Comment by freddydk** [comment]
Had another partner with this issue (not warnings, but errors) - he pulled a new license and it works now. Will assume the same solves this issue. If not, reopen the issue and we should investigate

**Comment by MJECloud** [comment]
@paul-interdyn we fix this with refreshing our license. Maybe it works for you too. 😊

**Comment by paul-interdyn** [comment]
That didn't fix it for me :( I created a new Business Central SPA/Demo license from Business Center (for Business Central on-premises as that is the only related option) and get the following output when importing the test libraries:

Initialization took 99 seconds
Ready for connections!
Reading CustomSettings.config from wave2
Creating Desktop Shortcuts for wave2
Publishing C:\Applications\TestFramework\TestLibraries\Any\Microsoft_Any.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Any on tenant default
Installing Any on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Publishing C:\Applications\TestFramework\TestLibraries\Assert\Microsoft_Library Assert.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Library Assert on tenant default
Installing Library Assert on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Publishing C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Test Runner on tenant default
Installing Test Runner on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Publishing C:\Applications\System Application\Test\Microsoft_System Application Test Library.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Publishing C:\Applications\BaseApp\Test\Microsoft_Tests-TestLibraries.app
WARNING: This license is not compatible with this version of Business Central.
Extension compilation failed
LibraryService.Codeunit.al(909,9): error AL0135: There is no argument given that corresponds to the required formal parameter 'ShowReservationForm' of 'AutoReserve(Boolean)'
at <ScriptBlock>, <No file>: line 13
Extension compilation failed
LibraryService.Codeunit.al(909,9): error AL0135: There is no argument given that corresponds to the required formal parameter 'ShowReservationForm' of 'AutoReserve(Boolean)'
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.2\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : f07b7eb0cfd78e72c47efec5adc64ecb715f68330617bfe41c0cb4d697578ff8

**Comment by freddydk** [comment]
This is a different issue, which was fixed in 0.6.3.3 

from https://www.powershellgallery.com/packages/navcontainerhelper/0.6.3.3:
0.6.3.3 
Import-TestToolkit to use local apps when using local sandbox builds

your version is trying to deploy w1 apps to nz container.

**Comment by paul-interdyn** [comment]
Ok fair, but I'm still getting the license warnings.

**Comment by freddydk** [comment]
Everybody gets the license warnings until we ship and are able to create 15.x licenses.

**Comment by paul-interdyn** [comment]
Got it. Thanks!
