### ISSUE TITLE
Run-TestsInNavContainer parameter -testGroup undocumented

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/navcontainerhelper#594]
It seems like the `testGroup` parameter is undocumented for procedure `Run-TestsInNavContainer`.
I assume this is for test groups in the C/AL Test Runner, which don't seem to be there in the AL Test Runner anymore though.

**Comment by freddydk** [comment]
Correct.

**Comment by freddydk** [comment]
I will document and describe that it is only supported in C/AL tests

**Comment by freddydk** [comment]
Shipped in 0.6.4.1
