### ISSUE TITLE
NavContainerHelper fails on New-Navcontainer after Windows 10 update

### ISSUE THREAD

**Issue by TheovdVen** [microsoft/navcontainerhelper#597]
Last week my laptop was updated (Windows 10 Pro, build 1903) and after that my containers didn't work because of this, understandable. So I just wanted to recreate the container I was trying to use but it didn't succeed. It throws an error during execution of the script 'navinstall.ps1' around the lines where it states it is copying the Cronus database. I didn't specify a database and wanted to use the Cronus database so that is okay.

**Copying Cronus database
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error**

The container itself is started succesfully but it cannot install NAV apparently.

I ran the Powershell command for the container and looked into navinstall.ps1 where I noticed that it trying to copy or read some files from 'C:\NAVDVD\databases'. This is an empty folder!

Tried several options but it comes down to the same problem everytime.

Could you help me out? I attached the script used, the output, the inspect.log.
Thanks in advance.

**_SCRIPT USED_**
Clear-Host

$containerName = "m2p-18nl-cu08"

$imageName = "mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019"
$databaseBackupFileName = "20190704 m2printing_pv_prd SQL2017 full backup.bak"
$NAVLicenseFileName = "5164947 - NAV2018 - 5 users - geldig tot 03-06-2020.flf"
$NAVLicensePath = "C:\DATA\Docker\Licenses\2018"
$AddinSubFolderName = "NAV2018"

$shortcuts = 'None'

$mylicense = Join-Path $NAVLicensePath $NAVLicenseFileName
$containerRoot = "C:\DATA\Docker"
$addInsFolder = Join-Path $containerRoot (Join-Path "add-in" $AddinSubFolderName)
$sourceFolder = Join-Path $containerRoot (Join-Path "Containers" (Join-Path "$containerName" "Source"))
$databaseBackupFolder = Join-Path $containerRoot (Join-Path "db-backups" $containerName)
$scriptsFolder = Join-Path $containerRoot (Join-Path "scripts" "in-container")
$exportFilter = ""

New-Item -ItemType Directory -Force -Path $addInsFolder | out-null
New-Item -ItemType Directory -Force -Path $scriptsFolder | out-null
New-Item -ItemType Directory -Force -Path $sourceFolder | out-null
New-Item -ItemType Directory -Force -Path $databaseBackupFolder | out-null

$additionalParameters = @("-v ""${scriptsFolder}:c:\run\myscripts""",
                          "-v ""${addInsFolder}:c:\run\Add-ins""",
                          "-v ""${sourceFolder}:c:\run\Sources""",
                          "-v ""${databaseBackupFolder}:c:\temp""")

docker pull $imageName

New-NavContainer -accept_eula `
                 -accept_outdated `
                 -containerName $containerName `
                 -imageName $imageName `
                 -memoryLimit 8GB `
                 -auth NavUserPassword `
                 -useBestContainerOS `
                 -updateHosts `
                 -includeCSide `
                 -shortcuts $shortcuts `
                 -enableSymbolLoading `
                 -doNotExportObjectsToText 

**_OUTPUT_**
2018-cu8-nl-ltsc2019: Pulling from dynamicsnav
Digest: sha256:712fa0c5a7e6dad45a3e4aacd29cc84cd558b6fdca066513ee0e1ff6660e54b8
Status: Image is up to date for mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019
mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019
NavContainerHelper is version 0.6.3.3
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019
Removing m2p-18nl-cu08 from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\m2p-18nl-cu08
Creating Container m2p-18nl-cu08
Version: 11.0.23572.0-nl
Generic Tag: 0.0.9.2
Container OS Version: 10.0.17763.316 (ltsc2019)
Host OS Version: 10.0.18362.295 (1903)
A better Generic Container OS exists for your host (1903)
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Generic Container OS Version: 10.0.18362.295 (1903)
Generic Tag of better generic: 0.0.9.92
Using locale nl-NL
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\m2p-18nl-cu08\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container m2p-18nl-cu08 from image mcr.microsoft.com/dynamicsnav:generic-1903
5f2492c0401ab1b54c957362e33f965a355a890fe24ec018508549a42e2c5d70
Waiting for container m2p-18nl-cu08 to be ready
Installing NAV
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Copying Cronus database
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error
Installing NAV
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Copying Cronus database
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
Initialization of container m2p-18nl-cu08 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.3\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...8nl-cu08 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container m2p-18nl-cu08 failed
 
**_INSPECT LOG_**
{
    "Id": "5f2492c0401ab1b54c957362e33f965a355a890fe24ec018508549a42e2c5d70",
    "Created": "2019-09-02T14:01:32.2730554Z",
    "Path": "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1",
    "Args": [],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 13116,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2019-09-02T14:01:34.380593Z",
        "FinishedAt": "0001-01-01T00:00:00Z",
        "Health": {
            "Status": "unhealthy",
            "FailingStreak": 22,
            "Log": [
                {
                    "Start": "2019-09-02T16:10:40.1066548+02:00",
                    "End": "2019-09-02T16:10:40.6170056+02:00",
                    "ExitCode": 1,
                    "Output": "Get-service : Cannot find any service with service name \r\n'MicrosoftDynamicsNavServer$NAV'.\r\nAt C:\\Run\\CheckHealth.ps1:17 char:14\r\n+         if ((Get-service -name \"$NavServiceName\").Status -eq 'Running ...\r\n+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (MicrosoftDynamicsNavServer$NAV: \r\n   String) [Get-Service], ServiceCommandException\r\n    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell. \r\n   Commands.GetServiceCommand\r\n \r\n"
                },
                {
                    "Start": "2019-09-02T16:11:10.6368754+02:00",
                    "End": "2019-09-02T16:11:10.9222376+02:00",
                    "ExitCode": 1,
                    "Output": "Get-service : Cannot find any service with service name \r\n'MicrosoftDynamicsNavServer$NAV'.\r\nAt C:\\Run\\CheckHealth.ps1:17 char:14\r\n+         if ((Get-service -name \"$NavServiceName\").Status -eq 'Running ...\r\n+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (MicrosoftDynamicsNavServer$NAV: \r\n   String) [Get-Service], ServiceCommandException\r\n    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell. \r\n   Commands.GetServiceCommand\r\n \r\n"
                },
                {
                    "Start": "2019-09-02T16:11:40.934964+02:00",
                    "End": "2019-09-02T16:11:41.3513135+02:00",
                    "ExitCode": 1,
                    "Output": "Get-service : Cannot find any service with service name \r\n'MicrosoftDynamicsNavServer$NAV'.\r\nAt C:\\Run\\CheckHealth.ps1:17 char:14\r\n+         if ((Get-service -name \"$NavServiceName\").Status -eq 'Running ...\r\n+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (MicrosoftDynamicsNavServer$NAV: \r\n   String) [Get-Service], ServiceCommandException\r\n    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell. \r\n   Commands.GetServiceCommand\r\n \r\n"
                },
                {
                    "Start": "2019-09-02T16:12:11.3656256+02:00",
                    "End": "2019-09-02T16:12:11.6466432+02:00",
                    "ExitCode": 1,
                    "Output": "Get-service : Cannot find any service with service name \r\n'MicrosoftDynamicsNavServer$NAV'.\r\nAt C:\\Run\\CheckHealth.ps1:17 char:14\r\n+         if ((Get-service -name \"$NavServiceName\").Status -eq 'Running ...\r\n+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (MicrosoftDynamicsNavServer$NAV: \r\n   String) [Get-Service], ServiceCommandException\r\n    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell. \r\n   Commands.GetServiceCommand\r\n \r\n"
                },
                {
                    "Start": "2019-09-02T16:12:41.6574082+02:00",
                    "End": "2019-09-02T16:12:41.9875361+02:00",
                    "ExitCode": 1,
                    "Output": "Get-service : Cannot find any service with service name \r\n'MicrosoftDynamicsNavServer$NAV'.\r\nAt C:\\Run\\CheckHealth.ps1:17 char:14\r\n+         if ((Get-service -name \"$NavServiceName\").Status -eq 'Running ...\r\n+              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ObjectNotFound: (MicrosoftDynamicsNavServer$NAV: \r\n   String) [Get-Service], ServiceCommandException\r\n    + FullyQualifiedErrorId : NoServiceFoundForGivenName,Microsoft.PowerShell. \r\n   Commands.GetServiceCommand\r\n \r\n"
                }
            ]
        }
    },
    "Image": "sha256:61cd3d8fa6470201c0cf021f39351a68e02435cc25e66c612fb5654aaa3f1d9a",
    "ResolvConfPath": "",
    "HostnamePath": "",
    "HostsPath": "",
    "LogPath": "C:\\ProgramData\\Docker\\containers\\5f2492c0401ab1b54c957362e33f965a355a890fe24ec018508549a42e2c5d70\\5f2492c0401ab1b54c957362e33f965a355a890fe24ec018508549a42e2c5d70-json.log",
    "Name": "/m2p-18nl-cu08",
    "RestartCount": 0,
    "Driver": "windowsfilter",
    "Platform": "windows",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "c:\\windows\\system32\\drivers\\etc:C:\\driversetc",
            "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
            "C:\\ProgramData\\NavContainerHelper\\Extensions\\m2p-18nl-cu08\\my:C:\\Run\\my",
            "C:\\ProgramData\\NavContainerHelper\\Extensions\\m2p-18nl-cu08\\Program Files:C:\\navpfiles",
            "C:\\ProgramData\\NavContainerHelper\\11.0.23572.0-nl-Files:c:\\NAVDVD"
        ],
        "ContainerIDFile": "",
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "NetworkMode": "default",
        "PortBindings": {},
        "RestartPolicy": {
            "Name": "unless-stopped",
            "MaximumRetryCount": 0
        },
        "AutoRemove": false,
        "VolumeDriver": "",
        "VolumesFrom": null,
        "CapAdd": null,
        "CapDrop": null,
        "Capabilities": null,
        "Dns": [],
        "DnsOptions": [],
        "DnsSearch": [],
        "ExtraHosts": null,
        "GroupAdd": null,
        "IpcMode": "",
        "Cgroup": "",
        "Links": null,
        "OomScoreAdj": 0,
        "PidMode": "",
        "Privileged": false,
        "PublishAllPorts": false,
        "ReadonlyRootfs": false,
        "SecurityOpt": null,
        "UTSMode": "",
        "UsernsMode": "",
        "ShmSize": 0,
        "ConsoleSize": [
            0,
            0
        ],
        "Isolation": "process",
        "CpuShares": 0,
        "Memory": 8589934592,
        "NanoCpus": 0,
        "CgroupParent": "",
        "BlkioWeight": 0,
        "BlkioWeightDevice": [],
        "BlkioDeviceReadBps": null,
        "BlkioDeviceWriteBps": null,
        "BlkioDeviceReadIOps": null,
        "BlkioDeviceWriteIOps": null,
        "CpuPeriod": 0,
        "CpuQuota": 0,
        "CpuRealtimePeriod": 0,
        "CpuRealtimeRuntime": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "Devices": [],
        "DeviceCgroupRules": null,
        "DeviceRequests": null,
        "KernelMemory": 0,
        "KernelMemoryTCP": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "MemorySwappiness": null,
        "OomKillDisable": false,
        "PidsLimit": null,
        "Ulimits": null,
        "CpuCount": 0,
        "CpuPercent": 0,
        "IOMaximumIOps": 0,
        "IOMaximumBandwidth": 0,
        "MaskedPaths": null,
        "ReadonlyPaths": null
    },
    "GraphDriver": {
        "Data": {
            "dir": "C:\\ProgramData\\Docker\\windowsfilter\\5f2492c0401ab1b54c957362e33f965a355a890fe24ec018508549a42e2c5d70"
        },
        "Name": "windowsfilter"
    },
    "Mounts": [
        {
            "Type": "bind",
            "Source": "c:\\programdata\\navcontainerhelper",
            "Destination": "c:\\programdata\\navcontainerhelper",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        },
        {
            "Type": "bind",
            "Source": "c:\\programdata\\navcontainerhelper\\extensions\\m2p-18nl-cu08\\my",
            "Destination": "c:\\run\\my",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        },
        {
            "Type": "bind",
            "Source": "c:\\programdata\\navcontainerhelper\\extensions\\m2p-18nl-cu08\\program files",
            "Destination": "c:\\navpfiles",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        },
        {
            "Type": "bind",
            "Source": "c:\\programdata\\navcontainerhelper\\11.0.23572.0-nl-files",
            "Destination": "c:\\navdvd",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        },
        {
            "Type": "bind",
            "Source": "c:\\windows\\system32\\drivers\\etc",
            "Destination": "c:\\driversetc",
            "Mode": "",
            "RW": true,
            "Propagation": ""
        }
    ],
    "Config": {
        "Hostname": "m2p-18nl-cu08",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "1433/tcp": {},
            "443/tcp": {},
            "7045/tcp": {},
            "7046/tcp": {},
            "7047/tcp": {},
            "7048/tcp": {},
            "7049/tcp": {},
            "80/tcp": {},
            "8080/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "licenseFile=",
            "enableSymbolLoading=Y",
            "accept_eula=Y",
            "accept_outdated=Y",
            "username=rainbow",
            "databaseServer=",
            "securePassword=76492d1116743f0423413b16050a5345MgB8AE4AdwBTAEEAcwBDAG0AZABUAGYAegBWAGkAMABRAHoARgBpADEAaQBvAFEAPQA9AHwANQAxADYANQA4ADcAMQBhADEANwAzADkAOQAwADcAZQBhADMAZAA2ADQANQAxADYAZQA3ADQAMgAyADgAMQBkADQANQA4ADMAZQAwADMANQA1ADQANgBhAGIAMwA2AGQAMgA4AGEAOABlADgANQAwAGEAMwA1AGIAMAA4ADEAZgA=",
            "locale=nl-NL",
            "databaseInstance=",
            "auth=NavUserPassword",
            "ExitOnError=N",
            "useSSL=N",
            "passwordKeyFile=c:\\run\\my\\aes.key",
            "removePasswordKeyFile=Y",
            "COMPLUS_NGenProtectedProcess_FeatureEnabled=0"
        ],
        "Cmd": [
            "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1"
        ],
        "Healthcheck": {
            "Test": [
                "CMD",
                "powershell",
                ".\\Run\\HealthCheck.ps1"
            ],
            "Interval": 30000000000,
            "Timeout": 10000000000
        },
        "ArgsEscaped": true,
        "Image": "mcr.microsoft.com/dynamicsnav:generic-1903",
        "Volumes": null,
        "WorkingDir": "",
        "Entrypoint": null,
        "OnBuild": null,
        "Labels": {
            "country": "nl",
            "created": "201908221002",
            "cu": "cu8",
            "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
            "maintainer": "Dynamics SMB",
            "nav": "2018",
            "osversion": "10.0.18362.295",
            "tag": "0.0.9.92",
            "version": "11.0.23572.0"
        }
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "5f2492c0401ab1b54c957362e33f965a355a890fe24ec018508549a42e2c5d70",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "1433/tcp": null,
            "443/tcp": null,
            "7045/tcp": null,
            "7046/tcp": null,
            "7047/tcp": null,
            "7048/tcp": null,
            "7049/tcp": null,
            "80/tcp": null,
            "8080/tcp": null
        },
        "SandboxKey": "5f2492c0401ab1b54c957362e33f965a355a890fe24ec018508549a42e2c5d70",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "",
        "Gateway": "",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "",
        "IPPrefixLen": 0,
        "IPv6Gateway": "",
        "MacAddress": "",
        "Networks": {
            "nat": {
                "IPAMConfig": null,
                "Links": null,
                "Aliases": null,
                "NetworkID": "5fe75c1228278fa9b8857e717fb104c9e90ea0b8ad269ee2e9aaed2246ca518a",
                "EndpointID": "df087e021a224272c78b445546a04a5d398d8fb21e99f3aaf8651901353ed8ca",
                "Gateway": "192.168.128.1",
                "IPAddress": "192.168.134.186",
                "IPPrefixLen": 24,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "00:15:5d:0b:4d:61",
                "DriverOpts": null
            }
        }
    }
}

**Comment by TheovdVen** [comment]
Additional information: even if I try to specify a SQL backup file to be used, I get the same error!

**_SCRIPT USED:_**
Clear-Host

$containerName = "m2p-18nl-cu08"

$imageName = "mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019"
$databaseBackupFileName = "20190704 m2printing_pv_prd SQL2017 full backup.bak"
$NAVLicenseFileName = "5164947 - NAV2018 - 5 users - geldig tot 03-06-2020.flf"
$NAVLicensePath = "C:\DATA\Docker\Licenses\2018"
$AddinSubFolderName = "NAV2018"

$shortcuts = 'None'
$mylicense = Join-Path $NAVLicensePath $NAVLicenseFileName
$containerRoot = "C:\DATA\Docker"
$addInsFolder = Join-Path $containerRoot (Join-Path "add-in" $AddinSubFolderName)
$sourceFolder = Join-Path $containerRoot (Join-Path "Containers" (Join-Path "$containerName" "Source"))
$databaseBackupFolder = Join-Path $containerRoot (Join-Path "db-backups" $containerName)
$scriptsFolder = Join-Path $containerRoot (Join-Path "scripts" "in-container")
$exportFilter = ""

New-Item -ItemType Directory -Force -Path $addInsFolder | out-null
New-Item -ItemType Directory -Force -Path $scriptsFolder | out-null
New-Item -ItemType Directory -Force -Path $sourceFolder | out-null
New-Item -ItemType Directory -Force -Path $databaseBackupFolder | out-null

$additionalParameters = @("-v ""${scriptsFolder}:c:\run\myscripts""",
                          "-v ""${addInsFolder}:c:\run\Add-ins""",
                          "-v ""${sourceFolder}:c:\run\Sources""",
                          "-v ""${databaseBackupFolder}:c:\temp""")

docker pull $imageName

New-NavContainer -accept_eula `
                 -accept_outdated `
                 -containerName $containerName `
                 -imageName $imageName `
                 -memoryLimit 8GB `
                 -auth NavUserPassword `
                 -useBestContainerOS `
                 -updateHosts `
                 -includeCSide `
                 -shortcuts $shortcuts `
                 -enableSymbolLoading `
                 -doNotExportObjectsToText `
                 -licensefile $mylicense `
                 -AdditionalParameters $additionalParameters `
                 -bakFile (Join-Path $databaseBackupFolder $databaseBackupFileName) 

**_OUTPUT:_**
2018-cu8-nl-ltsc2019: Pulling from dynamicsnav
Digest: sha256:712fa0c5a7e6dad45a3e4aacd29cc84cd558b6fdca066513ee0e1ff6660e54b8
Status: Image is up to date for mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019
mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019
NavContainerHelper is version 0.6.2.95
Host is Microsoft  - 1903
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image mcr.microsoft.com/dynamicsnav:2018-cu8-nl-ltsc2019
Removing container m2p-18nl-cu08
Removing m2p-18nl-cu08 from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\m2p-18nl-cu08
Creating Container m2p-18nl-cu08
Using license file C:\DATA\Docker\Licenses\2018\5164947 - NAV2018 - 5 users - geldig tot 03-06-2020.flf
Version: 11.0.23572.0-nl
Generic Tag: 0.0.9.2
Container OS Version: 10.0.17763.316 (ltsc2019)
Host OS Version: 10.0.18362.295 (1903)
A better Generic Container OS exists for your host (1903)
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Generic Container OS Version: 10.0.18362.295 (1903)
Generic Tag of better generic: 0.0.9.94
Using locale nl-NL
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\m2p-18nl-cu08\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container m2p-18nl-cu08 from image mcr.microsoft.com/dynamicsnav:generic-1903
7a13b2f1cdb794cfc1b2a94e21a8ebea72d331c7541f262b3db5ee248086c869
Waiting for container m2p-18nl-cu08 to be ready

Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Copying Cronus database
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error

Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Copying Cronus database
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at <ScriptBlock>, C:\Run\navinstall.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
Initialization of container m2p-18nl-cu08 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.95\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...8nl-cu08 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container m2p-18nl-cu08 failed

**Comment by freddydk** [comment]
I am not sure I understand what you are trying to achieve, so lets start from scratch.

What are you trying to achieve?
Do you have something in an existing container which you need to restore?
So, in clear language (not PS:-)), explain what you need to do?

Thanks

**Comment by TheovdVen** [comment]
Okay, sorry if I am unclear about what I am trying to achieve. Will try to explain.

I was having a running container with NAV2018 CU08 NL using a SQL backup from the customer environment. This container was created using a PS-script and all was running okay.

After installing the windows 10 update last week the container didn't run anymore. It showed errors and the main one was that the host system was changed. So I just wanted to recreate the container using the PS-script I already ran more times in the past.

When running the PS-script it started to download some newer images and at the end it showed the error:
An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.
at , C:\Run\navinstall.ps1: line 156
at , C:\Run\start.ps1: line 114
at , : line 1Error

The only thing I am trying to achieve is to get the container recreated again using the SQL backup file I used before. Because that didn't work I was trying the same but then with the Cronus database.

Tried all kinds of stuff. Even deleted  all images from mcr.microsoft.com/dynamicsnav that I had downloaded. Nothing seems to help and I got stuck now.

Is this more clear to you Freddy?

**Comment by freddydk** [comment]
Ok, so you don't need to restore anything you had in any containers - you are "just" stuck with a docker installation which gives strange errors.
I would right click the docker icon, Select settings, Reset, Reset to factory defaults - and start from scratch.

**Comment by TheovdVen** [comment]
Will try that. The other containers I have are not starting too and need to be recreated as well so that is no problem. Will let you  know the results.

**Comment by TheovdVen** [comment]
Unfortunately, the same problem occurs.
Any other suggestions?

**Comment by freddydk** [comment]
Hmmm - that did it for me (https://freddysblog.com/2019/05/01/windows-10-1903-and-business-central-containers/) - but maybe reset to factory defaults, uninstall, remove programdata\docker, reinstall. If that doesn't do it, email me at freddyk at microsoft dot com and we could maybe do a quick screen share session and see if I can help you out of this situation.

**Comment by TheovdVen** [comment]
Hi Freddy,

Did the following but without any success, so the same error is there again.

1. removed all containers
2. removed all images
3. reset Docker Desktop to factory defaults
4. uninstalled Docker Desktop
5. disabled Hyper-V feature entirely in Windows 10
6. disabled Containers feature in Windows 10
7. restarted laptop
8. removed %programdata%\DockerDesktop folder and contents
9. removed %programdata%\Docker folder and contents
10. enabled Containers feature in Windows 10
11. enabled Hyper-V feature entirely in Windows 10
12. installed latest stable version 2.1.0.1 (37199) of Docker Desktop again

I wasn't able to delete the %programdata%\Docker folder that easily. 
Renamed and redirected the folder but still security errors were shown when trying to delete.
Tried to change the owner and permissions via the properties but it didn't let me.
Not even while I am administrator on my machine.

The solution to not being able to delete this folder and its contents for me was this:
1. Open a command-prompt as administrator
2. go into to %programdata%\Docker folder (or the folder you moved and renamed it to)
3. execute the following commands:
	takeown /R /F *
	icacls * /T /Q /C /RESET
4. after this I was able to delete the folder and contents without problems.

I will send  you an email and if you can help me with a quick screen share session that would be great.

Thanks in advance

**Comment by TheovdVen** [comment]
The problems consisted of two issues:

1. A BIOS update enabled the 'deep sleep' option in Power Management in the BIOS which caused the Hyper-V options to be enabled but grayed out. After disabling the 'deep sleep' option the Hyper-V options were no longer grayed out. This probably caused problems when creating a new container were Hyper-V isolation is to be used.

**Comment by TheovdVen** [comment]
The problems consisted of two issues:

1. A BIOS update enabled the 'deep sleep' option in Power Management in the BIOS which caused the Hyper-V options to be enabled but grayed out. After disabling the 'deep sleep' option the Hyper-V options were no longer grayed out. This probably caused problems when creating a new container were Hyper-V isolation is to be used.

2. Something seems not to be working correctly when using the 'useBestContainerOS' option (in combination with specifying a SQL backup file). In that case process isolation is being used. By removing this option from your command it will use hyper-v isolation and then the container is created okay and running. Freddy will investigate the problem.

For now I can continue my work using the Hyper-V isolation. 

Many thanks to Freddy for assisting me with this problem!
