### ISSUE TITLE
AddAccessRule" with "1" argument(s): "Some or all identity references could not be translated.

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#60]
After several times running my script without any trouble, but after a server reset.
My script starts giving this error: "AddAccessRule" with "1" argument(s): "Some or all identity references could not be translated."

I can't recall making any breaking  changes causing this.

Message:

Waiting for container DEVServer to be ready, this shouldn't take more than a few minutes
Time:          ½              1              ½              2
..........Error
Initializing...
Starting Container
Hostname is DEVServer
PublicDnsName is DEVServer
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A3D7CF934271A90C592F75F95583203835099E44
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Creating Web Site
Creating NAV Web Server Instance
Exception calling "AddAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 167
at <ScriptBlock>, C:\Run\navstart.ps1: line 132
at <ScriptBlock>, C:\Run\start.ps1: line 92
at <ScriptBlock>, <No file>: line 1
[inspect.txt](https://github.com/Microsoft/navcontainerhelper/files/1552222/inspect.txt)
[logs.txt](https://github.com/Microsoft/navcontainerhelper/files/1552238/logs.txt)

**Comment by freddydk** [comment]
Could you specify the new-navcontainer function all (parameters etc)
and can you tell me whether this directory exists in the container (open a container powershell prompt)
C:\ProgramData\Microsoft\Microsoft Dynamics NAV\100\Web Client\NAV\WebClient\Resources\ExtractedResources

**Comment by freddydk** [comment]
Strange

Can you do the simplest docker run -e accept_eula=Y microsoft/dynamics-nav:tag on that image?

**Comment by mheijkant** [comment]
used: "docker run -e accept_eula=Y microsoft/dynamics-nav:2017-cu9"
Even stranger. Same message here.

**Comment by freddydk** [comment]
I just tried the same on my machine - and this works.
What does winver say? what update do you have?

**Comment by mheijkant** [comment]
found it. I worked at home last 2 days. And because I use a UK keyboard at home, I added an extra language/keyboard definition. This is causing the message. Now it's working again.

**Comment by freddydk** [comment]
Wow - so due to an extra keyboard definition, it cannot create the Web Client...
Thanks for the info.

**Comment by mheijkant** [comment]
To be sure I repeated this issue. Notice that when you add the extra region setting it still works. 
But only after restarting the server (or mayby new logon), the message occures again.
Also added my region settings with the extra UK setting that caused the message.

![regionsettings](https://user-images.githubusercontent.com/30508071/33928604-baf337f6-dfe6-11e7-9312-b2e2efd99353.PNG)

**Comment by freddydk** [comment]
Thanks for the repro - will try to do the same here.

**Comment by mheijkant** [comment]
Sorry if this might cause some confusion, but again I receive the same message. Really don't know what's going on. I'm 100% sure this worked twice. Things I did next.
1. restart the server and immediately started "docker run -e accept_eula=Y microsoft/dynamics-nav:2017-cu9". Didin't work.
2. remove all containers and run script, didn't work.
3. remove navison images and containers, didn't work.
4. aksed my system administrator if anything changed on windows updates or group policies. wasn't the case.

So I'm kind of stuck here. Only thing I did'nt try is doing the same thing on a different server.

![createcontainer after new image 2](https://user-images.githubusercontent.com/30508071/33938428-c2ec6632-e007-11e7-949f-7438082f16fd.PNG)

**Comment by freddydk** [comment]
if you copy the SetupWebClient.ps1 out from the image to the host in a folder called c:\myfolder and add -v c:\myfolder:c:\run\my to your docker run, then you will override the default setupwebclient.
Then you can modify c:\myfolder\setupwebclient.ps1 on the host and maybe add a few write-host statements here:
$ResourcesFolder = "$WebClientFolder".Replace('C:\Program Files\', 'C:\ProgramData\Microsoft\')
$user = New-Object System.Security.Principal.NTAccount("NT AUTHORITY\Everyone")
$rule = New-Object System.Security.AccessControl.FileSystemAccessRule($user, "ReadAndExecute", "ContainerInherit, ObjectInherit", "None", "Allow")
Write-Host $resourcesFolder
Write-Host $user
Write-Host $rule
$acl = Get-Acl -Path $ResourcesFolder
Set-Acl -Path $ResourcesFolder $acl
$acl = $null
$acl = Get-Acl -Path $ResourcesFolder
$acl.AddAccessRule($rule)
Set-Acl -Path $ResourcesFolder $acl
$acl = $null

**Comment by mheijkant** [comment]
Can't get it to work.
tried also something different by adding this parameter.
-AdditionalParameters @("-v c:\temp\objects\ORIGINAL:c:\original")
then I receive the expected message "AddAccessRule"
But when I try
-AdditionalParameters @("-v c:\temp\myfolder:c:\run\my")
I See:
    ½              2
.Error response from daemon: No such con

Placed the myfolder first in c:\ but that didn't work.
Also removed the SetupWebClient.ps1 from the myfolder with the same result.

**Comment by freddydk** [comment]
Sorry, my bad.
When using the navcontainerhelper - you specify override scripts in -myscripts @("c:\temp\setupwebclient.ps1") - new-navcontainer already shares a my folder and you cannot interfere in that.
If you update the navcontainerhelper to 0.2.2.1 - then you might get some more error output.

**Comment by mheijkant** [comment]
I've added the logging and the setupwebclient.ps1 file that i've edited. The error seems to happen on line 173 $acl.AddAccessRule($rule), 

[inspect.txt](https://github.com/Microsoft/navcontainerhelper/files/1564798/inspect.txt)
[logs.txt](https://github.com/Microsoft/navcontainerhelper/files/1564799/logs.txt)
[SetupWebClient.txt](https://github.com/Microsoft/navcontainerhelper/files/1564800/SetupWebClient.txt)

**Comment by freddydk** [comment]
What Windows Version are you running?
Run winver (incl. updates) thanks

**Comment by mheijkant** [comment]
![winver](https://user-images.githubusercontent.com/30508071/34096590-3ac8f7a2-e3d6-11e7-86d7-687bbcd62ff8.PNG)

**Comment by freddydk** [comment]
Any chance you can email me at freddyk at microsoft dot com, so we could setup a quick skype call.
I would like to investigate a few things in this case.
I think this is related to running Windows Server 2016 with a different windows language. I haven't been able to change language on my Windows Server. So if we can have a look and test a few things, that would be awesome.
Thanks

**Comment by freddydk** [comment]
So, it seems like NT AUTHORITY\Everyone is translated when the Windows Language is not English.
Changed the code to use SID S-1-1-0 instead, should work from generic tag version 0.0.4.4
Images will be rebuild on that over Christmas

**Comment by Koubek** [comment]
That is true - in Spain I have seen many times on localized platforms "Todos" instead of "Everyone" :(

**Comment by freddydk** [comment]
generic image 0.0.4.4 was released yesterday and all specific images will be rebuilt on 0.0.4.4 today/tomorrow.

**Comment by ajaychary** [comment]
Hi All,

I am using IIS web application it is accessible for my Offshore team and it is unable to access for onshore team only the users who are sitting in onshore site. we are getting belo error

![image](https://user-images.githubusercontent.com/42070536/43650038-64643fcc-9704-11e8-9613-386ddb3afe00.png)
