### ISSUE TITLE
Error Conecting to Virtual machine

### ISSUE THREAD

**Issue by syssolmarketing** [microsoft/navcontainerhelper#603]
Hi, we have successfully set up the virtual machine with the BC Docker image of mcr.microsoft.com/businesscentral/sandbox.  

It works perfectly for me but our developer is experiencing an issue when trying to connect. It is giving him an error 
![RDC error](https://user-images.githubusercontent.com/54630609/64266839-4ae6c500-cf03-11e9-9997-13123d63f5c4.png) 

The VM is running and I can successfully log in. Thanks for you help.

**Comment by freddydk** [comment]
How did you create the VM.
If you used http://aka.ms/getbc, then you will have a landing page.
On that - it tells you, that if you cannot login, you need to add your IP number to the network security group.
One of the settings in the ARM template behind getbc is the IP addresses you want to be able to connect from - or * to allow all. Default is your IP number only.

**Comment by syssolmarketing** [comment]
We created from http://aka.ms/bcsandbox

**Comment by syssolmarketing** [comment]
If that is the case with us where can I go to change the default settings?

**Comment by freddydk** [comment]
https://freddysblog.com/2019/07/26/the-arm-templates-for-dynamics-365-business-central-and-microsoft-dynamics-nav/ - search for remote desktop.
When you have created the VM and want to change it - you need to login to portal.azure.com, find the resource group, find the network security group and add a rule.

**Comment by syssolmarketing** [comment]
Thanks Freddy. Found where to create an incoming security rule. Can you advise on the various fields? How do we allow anyone with the rdp file to connect?
![azure security rule](https://user-images.githubusercontent.com/54630609/64361353-5f49c100-cfda-11e9-8995-e77e8f9e80be.png)

**Comment by freddydk** [comment]
Sure, although this has absolutely nothing to do with NavContainerHelper, Docker or the ARM templates:-)

Source = IP Address
Then a field pops up with ip addresses
Destination port ranges 3389
protocol tcp
priority some unused priority
name some name

should work.

or you can remove the VM and create one with *

**Comment by syssolmarketing** [comment]
Thank you!
