### ISSUE TITLE
error creating container using bcinsider image

### ISSUE THREAD

**Issue by lgtrrez** [microsoft/navcontainerhelper#604]
Here are some of the results form executing the command:
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
NavContainerHelper is version 0.6.0.15
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019
...

Cannot find path 'C:\Run\ClientUserSettings.config' because it does not exist.
at <ScriptBlock>, C:\Run\my\AdditionalSetup.ps1: line 11
at <ScriptBlock>, C:\Run\navstart.ps1: line 198
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container ODTRM-LAURA failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.15\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...RM-LAURA failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container ODTRM-LAURA failed

**Comment by freddydk** [comment]
You need to provide the command you use (new-navcontainer) and the full output - I cannot see anything from the above.

**Comment by lgtrrez** [comment]
Here is the command:
$imageNameFuture = "bcinsider.azurecr.io/bcsandbox-master:us"
$containerName = "ODTRM-LAURA"
$licenseFile = "C:\Docker\DEV_DEMO_BC_V14.flf"
New-NavContainer -containerName $containerName -imageName $imageNameFuture -accept_eula -shortcuts Desktop -doNotExportObjectsToText -restart unless-stopped -licenseFile $licenseFile -accept_outdated -updatehosts -includeCSide -credential (get-credential -credential $env:USERNAME)

The result:
Login Succeeded
NavContainerHelper is version 0.6.0.15
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.1
Docker Server Version is 19.03.1
Using image bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019
Removing ODTRM-LAURA from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\ODTRM-LAURA
Creating Nav container ODTRM-LAURA
Using license file C:\Docker\DEV_DEMO_BC_V14.flf
Version: 15.0.35881.0-us
Platform: 15.0.35855.0
Generic Tag: 0.0.9.94
Container OS Version: 10.0.17763.678 (ltsc2019)
Host OS Version: 10.0.17763.720 (ltsc2019)
Using process isolation
Creating container ODTRM-LAURA from image bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019
2315694f100e7d90b9001f8bec7bf98b551fcb8be8c1b2c32cab5ec685781821
Waiting for container ODTRM-LAURA to be ready
Initializing...
Starting Container
Hostname is ODTRM-LAURA
PublicDnsName is ODTRM-LAURA
WARNING: DNS resolution not working from within the container.
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user laura
Setting SA Password and enabling SA
WARNING: Caution: Your program license expires in 11 days.
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: Caution: Your program license expires in 11 days.
WARNING: This license is not compatible with this version of Business Central.
WARNING: Caution: Your program license expires in 11 days.
WARNING: This license is not compatible with this version of Business Central.
Cannot find path 'C:\Run\ClientUserSettings.config' because it does not exist.
at <ScriptBlock>, C:\Run\my\AdditionalSetup.ps1: line 11
at <ScriptBlock>, C:\Run\navstart.ps1: line 198
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is ODTRM-LAURA
PublicDnsName is ODTRM-LAURA
WARNING: DNS resolution not working from within the container.
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user laura
Setting SA Password and enabling SA
WARNING: Caution: Your program license expires in 11 days.
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: Caution: Your program license expires in 11 days.
WARNING: This license is not compatible with this version of Business Central.
WARNING: Caution: Your program license expires in 11 days.
WARNING: This license is not compatible with this version of Business Central.
Cannot find path 'C:\Run\ClientUserSettings.config' because it does not exist.
at <ScriptBlock>, C:\Run\my\AdditionalSetup.ps1: line 11
at <ScriptBlock>, C:\Run\navstart.ps1: line 198
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container ODTRM-LAURA failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.15\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...RM-LAURA failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container ODTRM-LAURA failed

I still get the warnings for license when creating container using image "mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019", but no errors and the container works as expected; there is though one difference between the license warnings when using insider version which I don't get when using this other image, I got a couple of lines with the message "WARNING: This license is not compatible with this version of Business Central.".

**Comment by freddydk** [comment]
Remove -includeCSIDE - CSIDE is no longer supported. pretty sure that is what causes this.
Will fix it so that it comes with a nicer warning instead, but please only use the options on new-navcontainer you need.

**Comment by lgtrrez** [comment]
That worked, although there is still an error shown after initialization completed:
Reading CustomSettings.config from ODTRM-LAURA
Get-NavContainerServerConfiguration : The property 'configuration' cannot be found on this object. Verify that the property exists.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.0.15\ContainerHandling\New-NavContainer.ps1:824 char:21
+ ... tomConfig = Get-NavContainerServerConfiguration -ContainerName $conta ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-NavContainerServerConfiguration], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-NavContainerServerConfiguration

**Comment by freddydk** [comment]
Not sure what this error is, but you need a newer navcontainerhelper. With 15.x containers a lot of things changed that needed change in the helper as well as also described here:
https://freddysblog.com/2019/07/31/preview-of-dynamics-365-business-central-2019-release-wave-2/

**Comment by freddydk** [comment]
Also, in the latest version you would have gotten this error when using includeCSIDE:

IncludeCSide is no longer supported in Dynamics 365 Business Central 2019 wave 2 release (1910 / 15.x)"
