### ISSUE TITLE
Import-TestToolkitToNavContainer

### ISSUE THREAD

**Issue by pzentner** [microsoft/navcontainerhelper#606]
When running this script for 2019 Wave 2, it will always import the tests from the C:\Applications folder. If you specify the -testToolkitCountry (or a new flag), IMHO it should use the local test, for instance, C:\Applications.us. 

Currently, it will import both the Application and Application.us tests. And I am getting errors relating to removed fields when importing. I can't skip those tests, so I also am not sure, if this actually would solve anything, if we can ONLY import the local tests or not. 

It might also only be an issue that the tests are broken for now.

**Comment by freddydk** [comment]
What version of containerhelper are you using?

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: pzentner <notifications@github.com>
Sendt: Thursday, September 5, 2019 4:57:16 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] Import-TestToolkitToNavContainer (#606)


When running this script for 2019 Wave 2, it will always import the tests from the C:\Applications folder. If you specify the -testToolkitCountry (or a new flag), IMHO it should use the local test, for instance, C:\Applications.us.

**Comment by pzentner** [comment]
I updated to 0.6.3.4. Using the latest insider build. 

When I am running the ImportTestToolkitToNavContainer script, I am running into errors that cannot import the base tests, since some don't work for the US local. I am then renaming the test app in the applications folder, import the one from the applications.us folder manually, and then move on and that works. 

So, what I am thinking is that any test apps that exist in the local applications directory should only be imported from there and not from the generic Applications directory.

And some need to be imported first from the local applications directory, since some in the base directory are dependent on those apps.

It mainly seems to be an issue with the actual tests and not navcontainerhelper itself, but we need somehow a workaround I guess.

For now, the apps that don't work from Applications are:
Microsoft_Tests-TestLibraries
Microsoft_Tests-ERM
Microsoft_Tests-Invoicing

And I am working on more

**Comment by pzentner** [comment]
Interesting issue - restarted laptop, killed container and recreated it, and it started working now. I have no idea what was going on, since it was not working before and it was running the same navcontainerhelper version as before. 

Sorry about that

**Comment by freddydk** [comment]
Containerhelper should look for a similar app in the applications.us folder and grab that.

                $apps | % {
                    $appFile = Get-ChildItem -path "c:\applications.*\*.*" -recurse -filter ($_.Name).Replace(".app","_*.app")
                    if (!($appFile)) {
                        $appFile = $_
                    }
