### ISSUE TITLE
Issue with image 14.4.35602.0

### ISSUE THREAD

**Issue by auzhhv** [microsoft/navcontainerhelper#607]
I'm having trouble with the latest BC image.

Same error for sandbox and onprem.

Previous image 14.3.34444 works fine.

I have tried removing all containers and images and reinstalled docker, but with no luck.

Suggestions?

![image](https://user-images.githubusercontent.com/46031720/64370720-4fa09b80-d01f-11e9-9b8f-e1fa8bb07492.png)

SCRIPT:

install-module navcontainerhelper -force

$accept_eula = $true

$containername = 'bcno'
#$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:14.3.34444.35600-no'
$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:14.4.35602.0-no-ltsc2019'
#$navdockerimage = 'mcr.microsoft.com/businesscentral/onprem:no'
$appbacpacuri = ''
$tenantbacpacuri = ''
$license = 'REPLACE WITH LICENCE LOCATION'

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
$additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula -containername $containername -auth NavUserPassword -Credential $credential -includeCSide -alwaysPull -doNotExportObjectsToText -usessl:$false -updateHosts -assignPremiumPlan -shortcuts Desktop -imageName $navdockerimage -additionalParameters $additionalParameters -licenseFile $license -usebestcontaineros

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

**Comment by freddydk** [comment]
Just copy/pasted your script and it seems to work fine.
I suspect that the docker file system is corrupt - and you might need to reset to factory defaults (which removes all images and containers) - and then try again

**Comment by auzhhv** [comment]
I tried factory reset, but still same error. I have also tried uninstalling and running this script:
https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10
Still the same problem.
It seems like it has to do with my computer, as i tested it on a colleague's computer, and it worked.
But another colleague had the same problem earlier this week and for him it helped to reinstall. 
Do you have another suggestion? If not, I will try to reinstall again.

**Comment by freddydk** [comment]
Very very very very strange
Could you post the full output of the container creation here?
(then I can see various version numbers)

**Comment by auzhhv** [comment]
Give me a minute, I'll just run the script again :)

**Comment by auzhhv** [comment]
PS C:\WINDOWS\system32> C:\Sharepoint\Auzilium AS\Gruppeområde - Dokumenter\Løsninger\Kom i gang\CreateDockerContainer.ps1
NavContainerHelper is version 0.6.3.4
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 18.09.0
Docker Server Version is 18.09.0
Pulling image mcr.microsoft.com/businesscentral/sandbox:14.4.35602.0-no-ltsc2019
14.4.35602.0-no-ltsc2019: Pulling from businesscentral/sandbox
Digest: sha256:e47d4b7e7856b96f99c21ce3daa666ec028ae84f173c56334b53cbe2f7adad92
Using image mcr.microsoft.com/businesscentral/sandbox:14.4.35602.0-no-ltsc2019
Removing container bcno
Removing bcno from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bcno
Creating Container bcno
Using license file C:\Sharepoint\Auzilium AS\Gruppeområde - Dokumenter\Løsninger\Kom i gang\AuziliumLicense.flf
Version: 14.4.35602.0-NO
Platform: 14.0.35570.0
Generic Tag: 0.0.9.92
Container OS Version: 10.0.17763.678 (ltsc2019)
Host OS Version: 10.0.18362.295 (1903)
A better Generic Container OS exists for your host (1903)
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Pulling image mcr.microsoft.com/dynamicsnav:generic-1903
generic-1903: Pulling from dynamicsnav
Digest: sha256:010767c45e06fd4d59a005a3e5e4ce47cb3f4e7994b4b9f7a208e2d018e6e0ca
Generic Container OS Version: 10.0.18362.295 (1903)
Generic Tag of better generic: 0.0.9.94
Using locale nb-NO
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\bcno\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- updatehosts.ps1
Creating container bcno from image mcr.microsoft.com/dynamicsnav:generic-1903
b178bb1f1b88d1a4cf0f3126724aa0d87c3dc3c2e1a6e12051d5fd7676dbeb04
Waiting for container bcno to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Norwegian_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 121 seconds
Installation complete
Initializing...
Starting Container
Hostname is bcno
PublicDnsName is bcno
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 255959AD2AA4E3610CAF5670A92A2E3931BC942D
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 152
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Norwegian_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 121 seconds
Installation complete
Initializing...
Starting Container
Hostname is bcno
PublicDnsName is bcno
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 255959AD2AA4E3610CAF5670A92A2E3931BC942D
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 152
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bcno failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.3.4\ContainerHandling\Wait-NavContainerReady.ps1:45 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container bcno failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bcno failed
 

PS C:\WINDOWS\system32>

**Comment by auzhhv** [comment]
The error:
![image](https://user-images.githubusercontent.com/46031720/64406294-c5d5ea00-d081-11e9-8668-059a0ab9a140.png)

**Comment by freddydk** [comment]
Did you add other parameters (like isolation hyperv) to the command?
(that is not in the sample above)

**Comment by auzhhv** [comment]
Same script, only license location that is different:

install-module navcontainerhelper -force

$accept_eula = $true

$containername = 'bcno'
#$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:14.3.34444.35600-no'
$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:14.4.35602.0-no-ltsc2019'
#$navdockerimage = 'mcr.microsoft.com/businesscentral/onprem:no'
$appbacpacuri = ''
$tenantbacpacuri = ''
$license = 'C:\Sharepoint\Auzilium AS\Gruppeområde - Dokumenter\Løsninger\Kom i gang\AuziliumLicense.flf'

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
$additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula -containername $containername -auth NavUserPassword -Credential $credential -includeCSide -alwaysPull -doNotExportObjectsToText -usessl:$false -updateHosts -assignPremiumPlan -shortcuts Desktop -imageName $navdockerimage -additionalParameters $additionalParameters -licenseFile $license -usebestcontaineros

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

**Comment by freddydk** [comment]
could you try to remove the -usebestcontaineros

**Comment by freddydk** [comment]
I see that the reason why it selects hyperv isolation is that you are running docker 18.09.0.
That version and all versions before only supports process isolation of windows server.
You should really reset to factory again (sorry for the download needed afterwards) and update docker to 19.03.2
and then try again.

**Comment by auzhhv** [comment]
Removing -usebestcontaineros worked :)

I updated the docker on a previous attempt, but I probably selected an earlier installation file when I tried again. I'll see if it still works after updating.

**Comment by freddydk** [comment]
-usebestcontaineros will allow you to run process isolation on newer versions of docker.
Not sure why it would cause this problem - but good if it works.

**Comment by freddydk** [comment]
Just tried to run the same and force hyperv - still works here...

**Comment by auzhhv** [comment]
It still works after I updated the docker, without -usebestcontaineros. Hard to say what's wrong when it works for most people. Thanks for the help :)

**Comment by freddydk** [comment]
Gr8
