### ISSUE TITLE
is it safe to update Docker on Windows 10

### ISSUE THREAD

**Issue by anwar0206** [microsoft/navcontainerhelper#609]
Hello Everybody,

Is it safe to update Docker on Windows 10 with 2.1.0.2 (37877) version.

Did this solve the zombie container issue and will not create issue with navcontainerhelper.

**Comment by freddydk** [comment]
As explained on my Blog, 2.1.0.2 fixes the zombie issue. Remove all containers before updating is the safest thing to do

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: anwar0206 <notifications@github.com>
Sendt: Monday, September 9, 2019 11:06:21 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] is it safe to update Docker on Windows 10 (#609)


Hello Everybody,

Is it safe to update Docker on Windows 10 with 2.1.0.2 (37877) version.

Did this solve the zombie container issue and will not create issue with navcontainerhelper.

**Comment by anwar0206** [comment]
Thanks @freddydk for your guidance
