### ISSUE TITLE
Import-ObjectsToNavContainer fails but I can import manually

### ISSUE THREAD

**Issue by nickrobbo** [microsoft/navcontainerhelper#610]
Hi, forgive me if this is an issue with my machine but I am not sure what else to try.  I have a container based on the following image: "microsoft/dynamics-nav:2017-cu5-gb".

I am restoring a BAK file to the container on creation, which has the following collation:  "Latin1_General_100_CI_AS".  This backup is CRONUS, where we have created a new company and then deleted the default company, so it is completely empty.  We use this as our base backup file, which we then import setup data to for development.

I create the container, and then try to import all our objects from our source code repository as .txt files.  This is where I run into an issue.  If I use the following code:

`Import-ObjectsToNavContainer -containerName $ContainerName -objectsFile $File.FullName`

Then I get this error:
`There is no system code page on your computer that matches the 1252 code page of the Latin1_General_100_CI_AS collation for the mydatabase database.  Your system code pages are: ANSI: 65001, OEM: 65001.  Ensure that the Regional Options of the computer use the correct system language and locale for the code pages to match.  You can also disable the 'Validate Collation' setting for this database. It is possible that certain text data will not be converted correctly when stored in the database.  Click OK to disable the 'Validate Collation' setting and continue to use the database, or click Cancel to exit.`

Strangely, I can open up CSIDE using the shortcuts and then import the objects without issue?

I have run the `Get-Culture` command in the container & on my machine and in both cases it uses "2057 en-GB". 

If I run `[System.Text.Encoding]::Default` it returns the following:

My Laptop:
![image](https://user-images.githubusercontent.com/35219805/64598824-49f4de00-d3b0-11e9-8fd0-0affc49b0301.png)

Container:
![image](https://user-images.githubusercontent.com/35219805/64598855-55e0a000-d3b0-11e9-8b4d-4d03ed7f8b0d.png)

If this is an issue with my machine then forgive me, it just seems strange that I can import the objects manually, without any issue.

**Comment by freddydk** [comment]
Could you try to use -useBestContainerOS when creating the container. This should cause the container to be created with process isolation and the problem should disappear.

**Comment by nickrobbo** [comment]
Thank you very much, this works perfectly!

**Comment by freddydk** [comment]
The problem here is, that ltsc2019 hyperv containers are using a strange and non-existing codepage. I have had to do a number of conversions in some situations in the containerhelper due to this - some things like this, cannot really be fixed without running process.
