### ISSUE TITLE
renumber createtestusers.app

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#612]
In the App which is used to create test users, page 50000 is used.
This leads to an error on container creation if two bacpac files are specified (which already contain P50000) and test users should be created.

Since Microsoft is Publisher of this extension, a corresponding number range should be used.

https://github.com/microsoft/navcontainerhelper/blob/9bef83afbd49fafd546bf7a5a99766e1fc747cea/UserHandling/Setup-NavContainerTestUsers.ps1#L65

**Comment by freddydk** [comment]
I get it that this can be annoying, but this app + AzureAdAppSetup and other (which are part of containerhelper and/or arm templates) all uses 50000 as they are not part of the baseapp - they are part of a setup bootstrapping - I cannot really assign object IDs in the baseapp area to this.
The source is here: https://dev.azure.com/businesscentralapps/_git/CreateTestUsers and it is faily easy to download the source, modify the ID, compile and publish (even as part of a CI/CD process)
