### ISSUE TITLE
Bak Cache folder naming

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#613]
If using the new (cool) BakFolder Cache feature from v0.6.4.1 there could be an issue with the folder naming:
when i create a w1 container and a base container both cache folders will be named `sandbox-15.0.35903.0-W1-bakFolders`.
Since the databases differ, I think the W1 should be _base_ on a container based on a base image.

**Comment by freddydk** [comment]
Yeah - the sandbox base is actually more like onprem w1 database - but I am not sure I can detect the difference between w1 and base safely - will have to check

**Comment by freddydk** [comment]
I don't have a good way of checking this and to be honest, the base version was never really supposed to be used, but people use this because w1 doesn't have demo data.
So I actually think that people using the base - uses that instead of w1 - not at the same time.
