### ISSUE TITLE
Create-AlProjectFolderFromBcContainer ParameterBindingException

### ISSUE THREAD

**Issue by plagijat** [microsoft/navcontainerhelper#618]
Hi,

I am using version 0.6.4.1 and running this command:

`Create-AlProjectFolderFromBcContainer -alProjectFolder $alProjectFolder -containerName $bcW1LatestContainerName -useBaseLine -AddGIT`

with variables for parameters are set like this:

```
$bcW1LatestContainerName = "zm-bc-w1-latest"
$alProjectFolder = "C:\ProgramData\NavContainerHelper\AL\zm-bc-w1-latest"
```
gives me the following error:

```
Create-AlProjectFolderFromNavContainer : Der Parametersatz kann mit den angegebenen benannten Parametern nicht aufgelöst werden.
In Zeile:1 Zeichen:1
+ Create-AlProjectFolderFromBcContainer -alProjectFolder $alProjectFold ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Create-AlProjectFolderFromNavContainer], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Create-AlProjectFolderFromNavContainer
```
It seems to me that the Parameter list is an issue somehow but I cannot figure out what/why.
I haven't had this issue before when creating AL folder and this exact command.

What am I missing?

Thanks,
Zoran M.

**Comment by freddydk** [comment]
The AL project created needs an id, name, publisher and version.
First version of the function created a random ID and set some default values if you didn't provide them.
Second version of the function supported to use the existing BaseApp properties as id, name, publisher and version as default values, which kind of conflicts with the original.
So, you need to specify what you want.
add -useBaseAppProperties to use existing baseapp properties
add -useBaseAppProperties:$false to use random guid, etc.
add -id, -name, -publisher and -version to add your own properties.

**Comment by plagijat** [comment]
Works!

Thanks Freddy. :)

Zoran M.
