### ISSUE TITLE
System table $ndo$dbproperty is missing

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#623]
Hallo

i try to use a azure sql database but i get the error:
`System table $ndo$dbproperty is missing or database agent-DB is not a Dynamics 365 Business Central application database.
at <ScriptBlock>, C:\Run\SetupDatabase.ps1: line 132
at <ScriptBlock>, C:\Run\navstart.ps1: line 113
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container agent failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.1\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container agent failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container agent failed`

**my script looks like this:**
New-BCContainer -accept_eula `
                    -containerName $containerName `
                    -auth NAVUserPassword `
                    -Credential $databaseCred `
                    -imageName $imageName `
                    -additionalParameters $additionalParameters `
                    -includeTestToolkit `
                    -licenseFile $licensefile `
                    -shortcuts $shortcuts `
                    -assignPremiumPlan `
                    -databaseServer $databaseServer `
                    -databaseName $database `
                    -databaseCredential $databaseCred `
                    -useCleanDatabase

the azure sql is an empty database.
how do i get the right database into my azure sql database?

**Comment by freddydk** [comment]
You would need to export your database to bacpac - and import that to azure sql.
(export-navcontainerdatabasesasbacpac I think is the function for that - or you can use ssms)

**Comment by Spycoclown** [comment]
Yes it workes, i export the bacpac and import it to azure sql and then i create a new container with the paramerter and it worked. Thx
