### ISSUE TITLE
Generate BC User with web access key

### ISSUE THREAD

**Issue by fommo** [microsoft/navcontainerhelper#626]
Hi,

We have created an automized script based on the NavContainerHelper scripts to create a new docker container, compile and package our AL extension (using the awesome Compile-AppInBCContainer script) and then publish with Publish-BCContainerApp. All this works flawlessly and is a great way to test the compile and publish to different country versions and also different builds of BC when needed.
However, we would like to take this a step further. Our extension is based on ODATA and SOAP functions. To access these we need a user with a Web Service Access Key.
When a user is created with the New-NavContainerNavUser I cannot see how we can either generate or set the web service access key. Is there a way to do that?
This is the only thing stopping us from having to complete script to create docker containers and run our unit tests on a daily bases to ensure quality.

Do you know a way to accomplish this?

**Comment by freddydk** [comment]
You could use
Invoke-ScriptInNavContainer -containername $containername -scriptblock {
    # put your code here
}
and add code in there using standard PowerShell Cmdlets from NAV to do this.
Alternatively, I think with userpassword authentication, you can connect with the password as well as the web service key.

**Comment by fommo** [comment]
Awesome! Thank you so much. I never thought about that solution. :)
