### ISSUE TITLE
Wrong dependency in Microsoft_PSTestToolPage_15.0.0.0

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#627]
The dependency in Microsoft_PSTestToolPage_15.0.0.0 is using "BaseApp", but we should now use "Base Application".

This breaks the -testPage 130409 functionality for BC15, since this app cannot be published.

**Comment by freddydk** [comment]
for 15.x you should not use page 130409 (remove the testpage parameter)
It automatically selects 130455 (which is built in)
The only reason for the Microsoft_PSTestToolPage_15.0.0.0 was actually before the page was in the system - but you are right that it should work.

**Comment by jwikman** [comment]
I just noticed that right now no tests are executed when our pipelines are running against BC15.

I want to move forward with the new tool, but until I refactored everything I wanted to use the old test page in the pipelines... That would have been a quick fix if Microsoft_PSTestToolPage_15.0.0.0  had worked.

Just created #628 to sort things out on how to automate against page 130455 :)

**Comment by freddydk** [comment]
Shipped in 0.6.4.2
