### ISSUE TITLE
How to automate AL Test Tool?

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#628]
In our pipelines I'm using an approach based on your test suite sample here: https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld?path=%2Ftest&version=GBmaster

Are there any recommended approach to automate the AL Test Tool instead, since the old tool is going away?

Should I just set a dependency to the Test Runner app (23de40a6-dfe8-4f80-80db-d70f83ce8caf) and populate the new tables as we did before (OnInstallApp)? Or are there a more sophisticated way to call the AL Test Tool from PowerShell (or API)?

Populating the tables OnInstall is great when we run the tests manually in the web client, but I rather have a function where I specify the codunit(s) (filter on Id) and TestFunction (filter possibility as well) for what tests I want to run. That would be easier to automate imo.

Maybe this is already documented somewhere, but I haven't found it...

**Comment by freddydk** [comment]
https://freddysblog.com/2019/08/30/running-tests-in-15-x-insider-containers/

**Comment by jwikman** [comment]
Yes, but you populate the tables manually - not automated... Or do I miss something?

**Comment by freddydk** [comment]
I would do it in OnInstallApp - sometime in the future, this code can go away - and tests will just be available (due to the attributes)

**Comment by freddydk** [comment]
To the new tables - the old tables (and with that 130409) will be removed

**Comment by jwikman** [comment]
Ok, then I'll just change our OnInstall code to put data in the new tables instead.

**Comment by freddydk** [comment]
That would be the change for now - I think next change is when you can remove the trigger (maybe 16.x or 17.x)

**Comment by jwikman** [comment]
Got it, thanks.

You might want to add the Test Runner app (23de40a6-dfe8-4f80-80db-d70f83ce8caf) to the list of dependencies in your blog? And maybe a few lines about above... :)

**Comment by freddydk** [comment]
Updated the blog post and fixed the .app file

**Comment by gintuoklis** [comment]
> I would do it in OnInstallApp - sometime in the future, this code can go away - and tests will just be available (due to the attributes)

Hey @freddydk , is there another way for populating DEFAULT Test Suite (BC14) without using OnInstallApp pattern?

**Comment by freddydk** [comment]
I haven't documented any other way - but of course there are. From AL it is easy, from PS I think there are ways in the new PS cmdlets on the DVD - I haven't looked yet.
