### ISSUE TITLE
Question : Host Extension folder

### ISSUE THREAD

**Issue by calcifieddeveloper** [microsoft/navcontainerhelper#631]
Hi,

Is there any way that I can specify where the extension folder lives on the host machine.  

For example if I don't want it to be in C:\ProgramData\NavContainerHelper\Extensions to something like C:\excludedfromavdir\NavContainerHelper ?

Have I not googled enough ?

**Comment by freddydk** [comment]
You have googled enough - and you have come to the right place.
Unfortunately, there are no way to move it, unless you clone the navcontainerhelper folder and change it yourself - but I have done no effort to make it movable (might happen in the future though).

You can however cleanup in the new containerhelper using:
Flush-NavContainerCache - which will remove all the cache folders.

**Comment by calcifieddeveloper** [comment]
Thanks Freddy.
