### ISSUE TITLE
Run-TestsInNavContainer no longer works in container for BC 15

### ISSUE THREAD

**Issue by FSharpCSharp** [microsoft/navcontainerhelper#632]
Our automatic tests are based on your published procedure, which you also published [here](https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld?path=%2Fscripts%2FRun-Tests.ps1&version=GBmaster) in DevOps. 

It also calls the Run-TestsInNavContainer cmdlet. It doesn't throw an error, but it doesn't run the tests into the container anymore, and the returned XML file is also empty.

Could you please check this and correct the code in the DevOps repository linked above?

**Comment by freddydk** [comment]
I am updating the sample as we speak - should be done before we ship 15.x
The reason why it doesn't work can be found here: https://freddysblog.com/2019/08/30/running-tests-in-15-x-insider-containers/

**Comment by FSharpCSharp** [comment]
Thank you for your quick answer! I've tried to do the same now. It was also no problem. The only thing I'm failing at the moment is the fact that the Get-TestsFromNavContainer cmdlet doesn't work. Unlike your example, I get absolutely no response from the container. But there is not even an error message, although there are definitely tests.

**Comment by freddydk** [comment]
and if you add -testpage 130409 - does that change the result from Get-Tests?

**Comment by FSharpCSharp** [comment]
Then at least I get an error message, but I can't do anything with that.

```
ERROR: Cannot build the page 130409.
The metadata object Page 130409 was not found.
Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
```

**Comment by freddydk** [comment]
Are you using the latest containerhelper?

**Comment by FSharpCSharp** [comment]
I use the following stand of the container helper:

```
Name                           Version          Source           Summary                                                                                            
----                           -------          ------           -------                                                                                            
navcontainerhelper             0.6.4.3          PSGallery        PowerShell module   
```

**Comment by FSharpCSharp** [comment]
Here again the complete error message including affected files and versions.

```
ERROR: Cannot build the page 130409.
The metadata object Page 130409 was not found.
Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
at Get-Tests, C:\ProgramData\NavContainerHelper\Extensions\BDC15\PsTestTool-3\PsTestFunctions.ps1: line 101
at <ScriptBlock>, <No file>: line 36
Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.3\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 Char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...testtoolpagefob:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130409. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
```

**Comment by freddydk** [comment]
That might be because you already ran the function without this parameter.
Try to remove the PSTestTool folder under c:\programdata\navcontainerhelper\extensions\BD15

**Comment by FSharpCSharp** [comment]
Thanks for the hint, now that I have removed the folder, a new extension for PowerShell has been released in the database.

The command now also returns test routines. But it looks like only the old C/AL test suite with the name "Default". I have created my own test suite with a new name in the AL Test Tool. But strangely enough this name is not shown to me.

And if I now execute the command without the parameter "testpage", then I don't get an answer. It only works with this parameter, but also only C/AL Seitig. I am now slightly confused.....

**Comment by freddydk** [comment]
This means that you are populating the old C/AL test tables and not the AL test pages.
This will work in 15 - but at some point in time in the future, the objects will be removed.
Open the web client and have a look at the pages to see where your tests are inserted.

**Comment by FSharpCSharp** [comment]
No, that's not true! I have built everything into the new Test Tool. I also see the Test Suite in the page 130451 as well as 130455 everything is displayed correctly. I don't have any old dependencies. But I get it when I execute the command in the PowerShell not even an empty object, nothing happens, and that's what makes me suspicious.

**Comment by freddydk** [comment]
Ok
I assume this means that things works now - you just have to specify testsuite?
right?

**Comment by FSharpCSharp** [comment]
Good news! All scripts also run with each other if you include the name of the Test Suite. I was just confused that there was no return of the function.
