### ISSUE TITLE
Sign-NavContainerApp "Cannot locate signtool.exe after installation"

### ISSUE THREAD

**Issue by mmenninghaus** [microsoft/navcontainerhelper#633]
Signing our apps with Sign-NavContainerApp runs perfect locally (Windows 10 Enterprise 1809, Docker version 19.03.2, build 6a30dfc), but the same scripts fail on our build-server (Windows Server 2019 Datacenter 1809, Docker version 19.03.2, build c92ab06ed9)  with

![image](https://user-images.githubusercontent.com/43880502/65583226-194f9f80-df7f-11e9-851d-c956e7d9bc75.png)

Using navcontainerhelper 0.6.4.3
Using Image mcr.microsoft.com/businesscentral/onprem:14.3.34444.0-de
Manually executing the Installation of the signtool inside the container does not work, either and does not caues any warnings or errors. Any ideas? Thank you!

**Comment by freddydk** [comment]
It sounds like your container cannot access the internet maybe?
I have pipelines running on 2019 azure vm (like yours) signing apps on 13.x, 14.x and 15.x
Check the output of creating the container to see if there are any warnings?

**Comment by freddydk** [comment]
Closing the issue, please reopen with more info if the issue persists

**Comment by mmenninghaus** [comment]
Indeed a very strange setting in the firewall for the certain server. Needed some time for the fix and communication with our IT dep.. Not an issure in the navcontainerhelper. For anyone who encounters the same issue: the download uses different ip adresses and ranges, not a certain ones.

**Comment by gregoral** [comment]
This happened to me today.
winsdksetup.exe was downloaded without any issues.
But it just did not run.
I tried running it manually inside the container, but it just silently exited.

```
Downloading Signing Tools
Installing Signing Tools
Cannot locate signtool.exe after installation
```
I  copied winsdksetup.exe out of the container to the host and signtool.exe was installed without issues.
winsdksetup.exe version: 10.1.17763.1

I resolved the issue by:
- installing signtool.exe on the host.
- copied the WinSdk to RunMy folder
- updated the Sign-NavContainerApp.ps1 script to copy from C:\run\my first ( if exists )

**Comment by freddydk** [comment]
This issue was resolved - if your issue isn't the same, you should open a new issue instead of adding to an already resolved issue.
Please also include information about how the container was created and the full output (contains a lot of debug info)
