### ISSUE TITLE
Missing function "New-NAVServerUserPermissionSet"

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#636]
navcontainerhelper don't support the function "New-NAVServerUserPermissionSet"

So i have to enter the container with "Enter-BCContainer" then import the NavAdminTool and then i can use the function.

In the Azure DevOps Pipeline i have the problem that it dont work with the "Enter-BCContainer".

Or maybe you have an other way how to set the PermissionsSetIds from my APPs to test them.

**Comment by freddydk** [comment]
You should be able to use
```
Invoke-ScriptInBCContainer -containername container -scriptblock {
    # this code will run in container and admin tool is loaded
}
```

**Comment by Spycoclown** [comment]
Thx
