### ISSUE TITLE
Cannot open page 130455 Run-Tests.ps1 Pipeline 

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#637]
Hello,

I build an Agent with BC 150 latest build (german location) and the navcontainerhelp needs a page that is not in the standard application or the test toolkit.

`Page Edit - Command Line Test Tool has to close.
Cannot open page 130455. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
at Get-Tests, C:\ProgramData\NavContainerHelper\Extensions\Agent\PsTestTool-3\PsTestFunctions.ps1: line 101
at <ScriptBlock>, <No file>: line 42
##[error]Cannot open page 130455. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
##[error]At C:\Program 

##[error]Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.4\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13

##[error]+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...

##[error]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

##[error]    + CategoryInfo          : OperationStopped: (Cannot open pag...testtoolpagefob:String) [], RuntimeException

##[error]    + FullyQualifiedErrorId : Cannot open page 130455. You might need to import the page object here: http://aka.ms/ps 

##[error]   testtoolpagefob

##[error]`

**Comment by Spycoclown** [comment]
using 
BC: bcinsider.azurecr.io/bcsandbox-master:de Version: 15.0.36145.0-de
Docker Server Version is 19.03.1
NavContainerHelper is version 0.6.4.4

**Comment by freddydk** [comment]
Please provide full script + full output (and please use the small insert code button in the toolbar)

**Comment by Spycoclown** [comment]
```
``
`Param(
    [ValidateSet('AzureDevOps','Local','AzureVM')]
    [Parameter(Mandatory=$false)]
    [string] $run = "AzureDevOps",
    [Parameter(Mandatory=$false)]
    [string] $testSuite = "Default",

    [Parameter(Mandatory=$true)]
    [pscredential] $credential,

    [Parameter(Mandatory=$true)]
    [string] $testResultsFile,

    [switch] $reRunFailedTests
)

$settings = (Get-Content (Join-Path $PSScriptRoot "..\settings.json") | ConvertFrom-Json)
$containerName = "$($settings.docker)"

$TempTestResultFile = "C:\ProgramData\NavContainerHelper\Extensions\$containerName\Test Results.xml"

$tests = Get-TestsFromBCContainer -containerName $containerName `
                                  -credential $credential `
                                  -ignoreGroups `
                                  -testSuite $testSuite `
                                  -usePublicWebBaseUrl:($run -eq "AzureVM")

$azureDevOpsParam = @{}
if ($run -eq "AzureDevOps") {
    $azureDevOpsParam = @{ "AzureDevOps" = "Warning" }
}

$rerunTests = @()
$failedTests = @()
$first = $true
$tests | % {
    if (-not (Run-TestsInBcContainer @AzureDevOpsParam -containerName $containerName `
                                     -credential $credential `
                                     -XUnitResultFileName $TempTestResultFile `
                                     -AppendToXUnitResultFile:(!$first) `
                                     -testCodeunit $_.Id `
                                     -returnTrueIfAllPassed `
                                     -usePublicWebBaseUrl:($run -eq "AzureVM") `
                                     -restartContainerAndRetry)) { $rerunTests += $_ }
    $first = $false
}
if ($rerunTests.Count -gt 0 -and $reRunFailedTests) {
    Restart-BCContainer -containerName $containername
    $rerunTests | % {
        if (-not (Run-TestsInBcContainer @AzureDevOpsParam -containerName $containerName `
                                         -credential $credential `
                                         -XUnitResultFileName $TempTestResultFile `
                                         -AppendToXUnitResultFile:(!$first) `
                                         -testCodeunit $_.Id `
                                         -returnTrueIfAllPassed `
                                         -usePublicWebBaseUrl:($run -eq "AzureVM") `
                                         -restartContainerAndRetry)) { $failedTests += $_ }
        $first = $false
    }
}

Copy-Item -Path $TempTestResultFile -Destination $testResultsFile `-Force``
``
```

```
`
Generating script.
Formatted command: . 'C:\agent\_work\2\s\scripts\Run-Tests.ps1' -credential ([PSCredential]::new("Agent", (ConvertTo-SecureString -String "gws2Admin" -AsPlainText -Force))) -TestResultsFile (Join-Path "C:\agent\_work\2\s" "TestResults.xml") -testsuite "CLP" -run "AzureVM"
========================== Starting Command Output ===========================
"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'C:\agent\_work\_temp\d503609c-b0f5-4c8d-a523-14840c1102f3.ps1'"
ERROR: You do not have the following permissions on TableData 130451: Read.

To view details about your permissions, see the Effective Permissions page. To report a problem, refer to the following server session ID: '61'.

Page Edit - Command Line Test Tool has to close.
Cannot open page 130455. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
at Get-Tests, C:\ProgramData\NavContainerHelper\Extensions\Agent\PsTestTool-3\PsTestFunctions.ps1: line 101
at <ScriptBlock>, <No file>: line 42
##[error]Cannot open page 130455. You might need to import the page object here: http://aka.ms/pstesttoolpagefob
##[error]At C:\Program 

##[error]Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.4\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13

##[error]+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...

##[error]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

##[error]    + CategoryInfo          : OperationStopped: (Cannot open pag...testtoolpagefob:String) [], RuntimeException

##[error]    + FullyQualifiedErrorId : Cannot open page 130455. You might need to import the page object here: http://aka.ms/ps 

##[error]   testtoolpagefob

##[error] 

##[error]PowerShell exited with code '1'.
Finishing: Run Tests
`
```

**Comment by Spycoclown** [comment]
The permission problem i already solved.

**Comment by freddydk** [comment]
It looks like you have grabbet the sample HelloWorld Repo today - I am working on this exact piece - checking in within an hour

**Comment by Spycoclown** [comment]
yeah that's true, but i work with the new insider bc 15.0.36145.0-de

**Comment by freddydk** [comment]
Yes, and i am making changes to master to work with 15.x
there is now a HelloWorld 14.x repo for 14.x
and a HelloWorld 13.x (hybrid) for 13.x with hybrid = true

**Comment by Spycoclown** [comment]
ok it work well for me only the think with the page don't work.

**Comment by freddydk** [comment]
That is probably because you haven't imported the test toolkit (a series of apps) when you started the container.

**Comment by Spycoclown** [comment]
you mean this:
``Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Any_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Any on tenant default
Installing Any on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Library Assert_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQL
BakCreater\_Microsoft_Library Assert_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Library Assert_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Library Assert on tenant default
Installing Library Assert on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app) to C:\ProgramData\NavContainerHelper\Extensio
ns\SQLBakCreater\_Microsoft_Test Runner.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Test Runner.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Test Runner on tenant default
Installing Test Runner on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_System Application Test Library_15.0.36145.0.app) to C:\ProgramData\NavContainerHelp
er\Extensions\SQLBakCreater\_Microsoft_System Application Test Library_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_System Application Test Library_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-TestLibraries_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extension
s\SQLBakCreater\_Microsoft_Tests-TestLibraries_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-TestLibraries_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-TestLibraries on tenant default
Installing Tests-TestLibraries on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Bank_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakC
reater\_Microsoft_Tests-Bank_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Bank_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Bank on tenant default
Installing Tests-Bank on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Cash Flow_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQ
LBakCreater\_Microsoft_Tests-Cash Flow_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Cash Flow_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Cash Flow on tenant default
Installing Tests-Cash Flow on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Cost Accounting_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensi
ons\SQLBakCreater\_Microsoft_Tests-Cost Accounting_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Cost Accounting_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Cost Accounting on tenant default
Installing Tests-Cost Accounting on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-CRM integration_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensi
ons\SQLBakCreater\_Microsoft_Tests-CRM integration_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-CRM integration_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-CRM integration on tenant default
Installing Tests-CRM integration on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Data Exchange_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extension
s\SQLBakCreater\_Microsoft_Tests-Data Exchange_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Data Exchange_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Data Exchange on tenant default
Installing Tests-Data Exchange on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Dimension_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQ
LBakCreater\_Microsoft_Tests-Dimension_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Dimension_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Dimension on tenant default
Installing Tests-Dimension on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-DotNet_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBa
kCreater\_Microsoft_Tests-DotNet_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-DotNet_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-DotNet on tenant default
Installing Tests-DotNet on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-ERM_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakCr
eater\_Microsoft_Tests-ERM_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-ERM_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-ERM on tenant default
Installing Tests-ERM on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Fixed Asset_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\
SQLBakCreater\_Microsoft_Tests-Fixed Asset_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Fixed Asset_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Fixed Asset on tenant default
Installing Tests-Fixed Asset on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-General Journal_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensi
ons\SQLBakCreater\_Microsoft_Tests-General Journal_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-General Journal_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-General Journal on tenant default
Installing Tests-General Journal on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Graph_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBak
Creater\_Microsoft_Tests-Graph_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Graph_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Graph on tenant default
Installing Tests-Graph on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Integration_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\
SQLBakCreater\_Microsoft_Tests-Integration_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Integration_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Integration on tenant default
Installing Tests-Integration on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Invoicing_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQ
LBakCreater\_Microsoft_Tests-Invoicing_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Invoicing_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Invoicing on tenant default
Installing Tests-Invoicing on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Job_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakCr
eater\_Microsoft_Tests-Job_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Job_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Job on tenant default
Installing Tests-Job on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Local_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBak
Creater\_Microsoft_Tests-Local_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Local_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Local on tenant default
Installing Tests-Local on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Misc_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakC
reater\_Microsoft_Tests-Misc_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Misc_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Misc on tenant default
Installing Tests-Misc on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-MOCKSERVICETESTS_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extens
ions\SQLBakCreater\_Microsoft_Tests-MOCKSERVICETESTS_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-MOCKSERVICETESTS_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-MOCKSERVICETESTS on tenant default
Installing Tests-MOCKSERVICETESTS on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-NATIVEINVOICINGTEST_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Ext
ensions\SQLBakCreater\_Microsoft_Tests-NATIVEINVOICINGTEST_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-NATIVEINVOICINGTEST_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-NATIVEINVOICINGTEST on tenant default
Installing Tests-NATIVEINVOICINGTEST on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Permissions_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\
SQLBakCreater\_Microsoft_Tests-Permissions_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Permissions_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Permissions on tenant default
Installing Tests-Permissions on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Physical Inventory_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Exte
nsions\SQLBakCreater\_Microsoft_Tests-Physical Inventory_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Physical Inventory_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Physical Inventory on tenant default
Installing Tests-Physical Inventory on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Prepayment_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\S
QLBakCreater\_Microsoft_Tests-Prepayment_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Prepayment_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Prepayment on tenant default
Installing Tests-Prepayment on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Rapid Start_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\
SQLBakCreater\_Microsoft_Tests-Rapid Start_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Rapid Start_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Rapid Start on tenant default
Installing Tests-Rapid Start on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Report_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBa
kCreater\_Microsoft_Tests-Report_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Report_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Report on tenant default
Installing Tests-Report on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Resource_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQL
BakCreater\_Microsoft_Tests-Resource_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Resource_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Resource on tenant default
Installing Tests-Resource on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Reverse_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLB
akCreater\_Microsoft_Tests-Reverse_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Reverse_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Reverse on tenant default
Installing Tests-Reverse on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-SCM_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakCr
eater\_Microsoft_Tests-SCM_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-SCM_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-SCM on tenant default
Installing Tests-SCM on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-SMB_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakCr
eater\_Microsoft_Tests-SMB_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-SMB_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-SMB on tenant default
Installing Tests-SMB on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-SMTP_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakC
reater\_Microsoft_Tests-SMTP_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-SMTP_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-SMTP on tenant default
Installing Tests-SMTP on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-User_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakC
reater\_Microsoft_Tests-User_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-User_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-User on tenant default
Installing Tests-User on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-VAT_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQLBakCr
eater\_Microsoft_Tests-VAT_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-VAT_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-VAT on tenant default
Installing Tests-VAT on tenant default
WARNING: This license is not compatible with this version of Business Central.
App successfully published
Copy from container SQLBakCreater (C:\Applications.de\Microsoft_Tests-Workflow_15.0.36145.0.app) to C:\ProgramData\NavContainerHelper\Extensions\SQL
BakCreater\_Microsoft_Tests-Workflow_15.0.36145.0.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\SQLBakCreater\_Microsoft_Tests-Workflow_15.0.36145.0.app
WARNING: This license is not compatible with this version of Business Central.
Synchronizing Tests-Workflow on tenant default
Installing Tests-Workflow on tenant default
WARNING: This license is not compatible with this version of Business Central.``

**Comment by Spycoclown** [comment]
![image](https://user-images.githubusercontent.com/7090519/65694148-ad039780-e075-11e9-805d-1f17b4e1dec3.png)
the permissionset is not yet full implemented in the 15.x version

**Comment by freddydk** [comment]
The code+pipeline checked in now runs...
![image](https://user-images.githubusercontent.com/10775043/65694673-85f99580-e076-11e9-8b47-7e02e461b03f.png)

**Comment by freddydk** [comment]
You imported all MS tests as well as the framework.
There are options to cache the database for next time - so things will be faster when run again.

**Comment by Spycoclown** [comment]
but you run with SUPER permission, i try it with the "D365 FULL ACCESS", "LOCAL", "TEST TOOL" and my Permissionset from the helloworld.

**Comment by freddydk** [comment]
Got it.
If there are permission problems, you will have to file a bug through standard channels, I cannot transfer github issues to bugs.

**Comment by Spycoclown** [comment]
Ok thx, will do it.
