### ISSUE TITLE
Convert-ModifiedObjectsToAl fails

### ISSUE THREAD

**Issue by JeppeDueHansen** [microsoft/navcontainerhelper#638]
When using Convert-ModifiedObjectsToAl with AlFilestructure parameter, the call fails with an error if there is a standard object that is modifyed.

Container has been created with

$Version = "mcr.microsoft.com/businesscentral/onprem:14.0.29537.0-dk"
$securePassword = ConvertTo-SecureString -String "xxx" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "yyy", $securePassword

New-NavContainer -containerName "MyContainer" `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -accept_eula  `
                 -imageName $Version `
                 -memoryLimit '4G' `
                 -includeCSide `
                 -includeAL `
                 -licenseFile $License `
                 -enableSymbolLoading `
                 -updateHosts `
                 -alwaysPull `
                 -accept_outdated 

Then executing this command

Convert-ModifiedObjectsToAl -containerName "MyContainer" -alProjectFolder 'C:\temp\Test' -alFileStructure $alFileStructure

and $Alfilestructure is (copy pasted from your blog post)

$alFileStructure = { Param ([string] $type, [int] $id, [string] $name) 

    if ($myModifiedObjects.Contains("$type$id")) {
        $folder = "Modified"
    }
    elseif (($id -ge 50000 -and $id -le 99999) -or ($id -gt 1999999999)) {
        $folder = "My"
    }
    else {
        $folder = "BaseApp"
    }

    switch ($type) {
        "page"     { "$folder\Pages\$($name).$($type).al" }
        "table"    { "$folder\Tables\$($name).$($type).al" }
        "codeunit" { "$folder\Codeunits\$($name).$($type).al" }
        "query"    { "$folder\Queries\$($name).$($type).al" }
        "report"   { "$folder\Reports\$($name).$($type).al" }
        "xmlport"  { "$folder\XmlPorts\$($name).$($type).al" }
        "profile"  { "$folder\Profiles\$($name).$($type).al" }
        "dotnet"   { "$folder\$($name).al" }
        ".rdlc"    { "$folder\Layouts\$($name).rdlc" }
        ".docx"    { "$folder\Layouts\$($name).docx" }
        ".xlf"     { "$folder\$($name).xlf" }
        default { throw "Unknown type '$type'" }
    }
}

When its just new objects it works fine, but if a standard object is changed it fails with the error message

ForEach-Object : Exception calling "Substring" with "2" argument(s): "Længden må ikke være mindre end nul.
Parameternavn: length"
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.5\AppHandling\Copy-AlSourceFiles.ps1:28 char:159
+ ... .HasFlag([System.IO.FileAttributes]::Directory)) } | ForEach-Object {
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ForEach-Object], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentOutOfRangeException,Microsoft.PowerShell.Commands.ForEachObjectCommand

I think that is has something to do with the naming of the converted al objects:
Modification  - Currency(Table 4).al
Codeunit 50202 - Customer Mgt.al

**Comment by freddydk** [comment]
I am pretty sure that bug was solved in a later version of NavContainerHelper - 0.6.2.5 is 3 months old.

**Comment by JeppeDueHansen** [comment]
Upgraded to latest version - now the type for standard object changes are returned as TableExtensions and PageExtensions. Thanks
