### ISSUE TITLE
Create-AlProjectFolderFromBCContainer

### ISSUE THREAD

**Issue by jeffgit** [microsoft/navcontainerhelper#639]
I got the following error when running Create-AlProjectFolderFromBCContainer. The parameters are copied from the documentation. I've already installed the latest build of navcontainerhelper. Am I missing anything?
![image](https://user-images.githubusercontent.com/2955741/65812525-0b676d80-e17d-11e9-9578-acd0e8333df0.png)

**Comment by freddydk** [comment]
add the parameter -useBaseAppProperties - or specify -appid, -publisher, etc.

**Comment by freddydk** [comment]
(will update the blog posts)

**Comment by jeffgit** [comment]
Thanks Freddy for the quick reply. I added it in, but found another issue. 
![image](https://user-images.githubusercontent.com/2955741/65812613-356d5f80-e17e-11e9-9b2a-df08a459c9a8.png)

I am pretty sure I had -includeAL, and didn't have -doNotExportObjectsAsText when creating the container. Here below is the script I used for creating the container.

$additionalParameters = @("--publish  8080:8080",
                          "--publish  443:443", 
                          "--publish  7046-7049:7046-7049", 
                          "--env publicFileSharePort=8080",
                          "--env PublicDnsName=$publicdnsName",
                          "--env RemovePasswordKeyFile=N",
                          "--storage-opt size=100GB",
			  "-v c:\temp:c:\temp"
			)
New-NavContainer -containerName "bcserver" `
-imageName "bcinsider.azurecr.io/bcsandbox-master:us-ltsc2019" `
-accept_eula `
-additionalParameters $additionalParameters `
-multitenant `
-useSSL `
-includeAL `
-updateHosts `
-assignPremiumPlan `
-auth NavUserPassword `
-memoryLimit 10G `
-licenseFile "c:\temp\nav2018.flf"

**Comment by freddydk** [comment]
Try to run Flush-ContainerHelperCache - some folders might be wrongly created - and then create the container again

**Comment by jeffgit** [comment]
Flush-ContainerHelperCache didn't do the trick. Let me recreate the container and see if it works. Thanks Freddy.

**Comment by freddydk** [comment]
As I said - you need to create the container again (after flushing the cache)

**Comment by jeffgit** [comment]
Mostly worked, but got the following error, and not sure what is causing it.
![image](https://user-images.githubusercontent.com/2955741/65812988-afecae00-e183-11e9-902c-87d4cfe723f8.png)

**Comment by freddydk** [comment]
Don't know either - you can remove the -addGIT and do that manually if you need GIT.
GIT has a strange way of using exceptions to tell people information - not sure whether this is an error or an information.

**Comment by jeffgit** [comment]
Have another error if I use $alFileStructure parameter.
![image](https://user-images.githubusercontent.com/2955741/65813198-9b5de500-e186-11e9-916a-3d225bc43ce3.png)

**Comment by freddydk** [comment]
Did you create the myModifiedObjects class?
Remember that the code in blogs is something you need to understand and take ownership over. It works at the time the blogpost is written, but might not work anymore.
When you understand the full blog post it is typically no problem to fix it.
See also here: https://demiliani.com/2019/09/24/dynamics-365-business-central-wave-2-customizing-the-base-application/

**Comment by freddydk** [comment]
Did you manage to make this work?

**Comment by freddydk** [comment]
Will close the issue, please reopen with additional info if the issue persists
