### ISSUE TITLE
New-BCContainer command successfully creates container, but it is not accessible

### ISSUE THREAD

**Issue by danny-situ** [microsoft/navcontainerhelper#641]
I tried to create the new BC container using the command "New-BCContainer" and the container has been successfully created as follows:

![image](https://user-images.githubusercontent.com/55975911/65867292-ba3bc180-e3a8-11e9-8463-8bb1d9587025.png)

However, when I ran it, I had error me that the "this site can't be reach".

![image](https://user-images.githubusercontent.com/55975911/65867496-1ef71c00-e3a9-11e9-9af6-b7c1ffb7e3dd.png)

Anybody knows what's wrong the container creation?

**Comment by freddydk** [comment]
Could you include the command used and the full output of the command

**Comment by NAVspecialist** [comment]
Some time ago (1 month or so - I had the same issue on a DK version - it did not work for 3 days - When I checked the code it was due to base application code problems/and a missing Accounting Company in the database.

**Comment by danny-situ** [comment]
Dear Freddy,

I use the following command:

New-BCContainer -accept_eula -containerName "D365BC-Test" -auth NavUserPassword -imageName "mcr.microsoft.com/businesscentral/sandbox:au"

and I use Windows 10 Professional machine.

**Comment by freddydk** [comment]
You probably just need to add -updateHosts (see https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/)

**Comment by danny-situ** [comment]
This is the full output of the command:

NavContainerHelper is version 0.6.4.5
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
NOTE: Add -alwaysPull or -useBestContainerOS if you want to use mcr.microsoft.com/businesscentral/sandbox:au-ltsc2019 instead of mcr.m
icrosoft.com/businesscentral/sandbox:au.
Using image mcr.microsoft.com/businesscentral/sandbox:au
Creating Container D365BC-Test
Version: 14.5.35970.36441-AU
Style: sandbox
Platform: 14.0.36166.0
Generic Tag: 0.0.9.95
Container OS Version: 10.0.14393.3204 (ltsc2016)
Host OS Version: 10.0.18362.356 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-AU
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\D365BC-Test\my:
- MainLoop.ps1
Creating container D365BC-Test from image mcr.microsoft.com/businesscentral/sandbox:au
012d6d15e3be76dece2c7dc283ef37ace4ceade3b2c9c525604968170cf0f6ff
Waiting for container D365BC-Test to be ready
Initializing...
Starting Container
Hostname is D365BC-Test
PublicDnsName is D365BC-Test
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint A0BA4022681590400BEA290BFF9F236EEE4CA025
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Setting SA Password and enabling SA
Creating sa as SQL User and add to sysadmin
Initializing...
Restarting Container
PublicDnsName unchanged
Hostname is D365BC-Test
PublicDnsName is D365BC-Test
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.18.37.115
Container Hostname  : D365BC-Test
Container Dns Name  : D365BC-Test
Web Client          : 
Dev. Server         : http://D365BC-Test
Dev. ServerInstance : NAV

Files:
http://D365BC-Test:8080/al-3.0.154634.vsix

Initialization took 26 seconds
Ready for connections!
Reading CustomSettings.config from D365BC-Test
Creating Desktop Shortcuts for D365BC-Test
Container D365BC-Test successfully created

**Comment by NAVspecialist** [comment]
Sorry I agree with Freddy. -UpdateHosts  is the solution. In my case it was something with "ooups something went wrong..."

**Comment by danny-situ** [comment]
Thanks guys. I will try it again and let you know the result.

**Comment by danny-situ** [comment]
Thanks guys, It is working now after I added the parameter -UpdateHosts. Thank you very much for everybody's help.
