### ISSUE TITLE
Invoke-NavContainerCodeunit unusable in BC15

### ISSUE THREAD

**Issue by lksg** [microsoft/navcontainerhelper#642]
Because of AssumeNavContainer it is currently impossible to use. 
`if ($version.Major -ge 15) {
        throw "Container $containerOrImageName does not support the function $functionName"
}`
We are able to use the functionality if the check for BC15 is disabled. Is there a specific reason this functionality was disabled for bc15?

**Comment by freddydk** [comment]
I cannot remember why I inserted the check. We did have some problems earlier in some versions and a future safe mechanism to use would be APIs (like described here https://freddysblog.com/2019/03/27/navcontainerhelper-0-5-0-11/) - but I guess I could remove the AssumeNavContainer

**Comment by freddydk** [comment]
Fix shipped in 0.6.4.7
