### ISSUE TITLE
Get-TestsFromBCContainer - WARNING: This license is not compatible with this version of Business Central.

### ISSUE THREAD

**Issue by eknraw** [microsoft/navcontainerhelper#643]
Trying to use Get-TestFromNavContainer but it looks like Get-Test is returning, " WARNING: This license is not compatible with this version of Business Central." as the first element in the array.  

This is causing the | ConvertFrom-Json to fail.  

https://github.com/microsoft/navcontainerhelper/blob/5d0416973977504a1abd4de011b49d2698260165/AppHandling/Get-TestsFromNavContainer.ps1#L162

![image](https://user-images.githubusercontent.com/5561726/65940134-57204e00-e3ed-11e9-9b4e-90b1b27244d2.png)

I can alter the Get-TestFromNavContainer to give me output I can work with but is there a better way to do this with the licenses?   I need to load our license to publish an app but could I switch back to the default container license for the tests?

**Comment by freddydk** [comment]
This is because you are running as non-admin.
But - of course, it should work - I will look into this.

**Comment by eknraw** [comment]
Thanks for the quick commit!  I've integrated it into my test builds and it functions just fine.

**Comment by freddydk** [comment]
Fix shipped in 0.6.4.7
