### ISSUE TITLE
Warning if -useCleanDatabase or -useNewDatabase but not -includeAL on New-BCContainer

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#644]
the useCleanDatabase switch gets ignored when includeAL  is not set.
i think container creation should return a warning or an error in that case.
Same problem exists with the useNewDatabase switch.

https://github.com/microsoft/navcontainerhelper/blob/76cc350134aab54528893022b4dee76c184bb8be/ContainerHandling/New-NavContainer.ps1#L1364
https://github.com/microsoft/navcontainerhelper/blob/76cc350134aab54528893022b4dee76c184bb8be/ContainerHandling/New-NavContainer.ps1#L1398

**Comment by freddydk** [comment]
Fix shipped in 0.6.4.7
