### ISSUE TITLE
Setup-NavContainerTestUsers

### ISSUE THREAD

**Issue by pzentner** [microsoft/navcontainerhelper#649]
I just noticed that our build pipelines start failing in various countries, but not in all. It is always failing with the following error message:

Setup-NavContainerTestUsers : Cannot convert value "15.0.36560.36626-ca" to type "System.Version". Error: "Input string was not in a correct format."

Now, this works for Austria, but not for Australia or Canada. Is there an issue with the version number for those or is there an issue in the script? 

This is called during the New-NavContainer command in the -finalizeDatabasesScriptBlock, using the current docker image for BC15 sandbox and using NavContainerhelper 0.6.4.6

**Comment by freddydk** [comment]
That's a regression - sorry - I will publish 0.6.4.7 as asap

**Comment by freddydk** [comment]
Fix shipped in 0.6.4.7

**Comment by pzentner** [comment]
Just wanted to confirm that all build pipelines ran through successfully again. Thank you very much for fixing this so quickly - especially on a weekend and before Directions EMEA.
