### ISSUE TITLE
Getting CU number from the container

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#65]
Right now I am able to get the build no. (NAV Version) of the container through Get-NAVContainerNAVVersion. Is there some way how to get the CU no.? I want to automatize update of our git repository with objects and I want to know the CU no. to put it into commit. 

I want to be able to re-download exactly same CU later, when the latest version of nav version is different. 

Right now I am pulling image e.g. :2017-cz and I want to be able to do :2017-cu11-cz in future in my scripts.

**Comment by freddydk** [comment]
There isn't a function to get this yet, but you can do:
(docker inspect nav | ConvertFrom-Json).Config.Labels.cu

**Comment by kine** [comment]
Thanks! I was looking into the inspect but have overlooked the Labels. Solved.

**Comment by Koubek** [comment]
I can see the issues has been closed but I have some functions in the examples:

https://github.com/Koubek/nav-docker-examples/tree/master/helpers

[Get-NavVersionMajor.ps1](https://github.com/Koubek/nav-docker-examples/blob/master/helpers/Get-NavVersionMajor.ps1)
[Get-NavVersion.ps1](https://github.com/Koubek/nav-docker-examples/blob/master/helpers/Get-NavVersion.ps1)
[Get-NavVersionDir.ps1](https://github.com/Koubek/nav-docker-examples/blob/master/helpers/Get-NavVersionDir.ps1)
+ I use this one for example for the following: `-v $PSScriptRoot\Add-ins:"C:\Program Files\Microsoft Dynamics NAV\$navVersionDir\Service\Add-ins\Docker-Share" `
