### ISSUE TITLE
New-NAVContainer switch useTraefik those not work properly

### ISSUE THREAD

**Issue by Spycoclown** [microsoft/navcontainerhelper#653]
Hallo,

because of the code:
`if (!($PSBoundParameters.ContainsKey('useTraefik'))) {
        $traefikForBcBasePath = "c:\programdata\navcontainerhelper\traefikforbc"
        if (Test-Path -Path (Join-Path $traefikForBcBasePath "traefik.txt") -PathType Leaf) {
            Write-Host "WARNING: useTraefik not specified, but Traefik container was initialized, using Traefik. Specify -useTraefik:$false if you do NOT want to use Traefik."
            $useTraefik = $true
        }
    }`

the switch -useTraefik don't work properly.

We have on our server multi docker sessions from bc with -useTraefik but for the pipeline Agents we use docker sessions without -useTraefik. so now i have to change all my codes to "-useTraefik:$false" so i dont get that error.

**Comment by freddydk** [comment]
it is correct that defaulting of useTraefik changed in 0.6.4.8 to use true if traefik was enabled on the host.
In 0.6.4.9 run-tests and get-tests default usepublicwebbaseurl to true if traefik is on the contianer - with that CI/CD pipelines can also run using usetraefik - I do that myself.
This defaulting has significant advantages when using VMs as container hosts - I can run the same script on any machine and it just works - and it also should work in pipelines.
and yes, you will have to add -useTraefik:$false to avoid this (as the warning states)

**Comment by Spycoclown** [comment]
I did it thx
