### ISSUE TITLE
Different Culture (e.g. en-GB) when running test using Run-TestsInNavContainer

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#657]
Hi, 

We are making development for a Client that uses the culture en-GB (UK) and we are producing automated tests related to import data using Data Exchange Framework. 

I've seen that in PsTestFunctions.ps1 and ClientContext.ps1 the culture is hardcoded "en-US", our issue is that running the tests using PowerShell command Run-TestsInNavContainer some of the tests fails on the Format mismatch and when we run the Client the RTC to troubleshoot we have different results (complicating the troubleshoot).

I know that we could create tests using the "en-US" culture but to be more realistic in our tests we think that it is important to use the same date format used by the Customer. 

It would be great if could be possible to pass the culture as a parameter and allow test in cultures different than "en-US".

Thanks
  Sergio

**Comment by Spycoclown** [comment]
Hallo Sergio,

I do this task by using diffrent users with the right cultures, so i can test in every cultures i need. 

Hope it helped.

**Comment by eclipses** [comment]
Thank you Leonhard for sharing, I was not adding users so I did not consider this option, I will run som tests.

Thanks
  Sergio

**Comment by Spycoclown** [comment]
The good thing of using diffrent users you can even test with diffrent permissionssets.
Leo

**Comment by eclipses** [comment]
Hi Leonhard,

Could you please confirm if you are running the tests using Run-TestsInNavContainer command?

I've just done this test:
1) Created a new NAV Container and imported our customization and tests
2) Opened the RTC using the same user as from the creation of the container
3) Navigate to User Personalization
4) Changed the Language ID from 1033 to 2057
5) Restarted the RCT
6) Run all tests from Test Toolkit

I'm receiving the following error message:
![image](https://user-images.githubusercontent.com/3910615/66553148-e561a600-eb4a-11e9-80cf-63b940f17248.png)
If I run the tests from PowerShell all of them passed without issue.

Please let me know where do you specify the user to run the tests and if I'm doing something wrong.

Thanks
Sergio

**Comment by Spycoclown** [comment]
I just use in the Pipeline the powershell command, but i know that we use the Client Toolkit in the Team aswell.
But we have all the error check labels translatet, maybe you have to do it, even if en-US = en-GB.
Because the Toolkit maybe compare the error messages with the Labels in en-GB and if the translation is not there it give this error.

I am on the emea, i will try ask my team if they could check up it again. But i can't promis.

**Comment by eclipses** [comment]
Hi Leonhard,

Thanks again for your support, don't worry I applied a workaround so it is not urgent.

Enjoy EMEA ;-)

**Comment by Spycoclown** [comment]
What was the workaround?

**Comment by eclipses** [comment]
Just a function to adjust data format, it's temporarily to proceed with the development

**Comment by freddydk** [comment]
I don't think this is something I can fix in the containerhelper, right?

**Comment by eclipses** [comment]
Hi Freddy,

No, the workaround is just code to change the format when reading a date. 

I think you could add the culture as parameter in the creation of nav container, I saw that in the Instance Configuration there is en-US, and also when running the tests.

**Comment by freddydk** [comment]
I could, but I am pretty sure that the test runner behind (what you saw in the winclient) requires en-us - or?

**Comment by eclipses** [comment]
I don't think so, the RTC was complaining about missing captions. I will try to run some standard tests from a GB localized image using a user with en-GB in the profile and see if I will get any error.

**Comment by freddydk** [comment]
You can try to modify c:\program files\windowspowershell\modules\navcontainerhelper\apphandling\run-testsinnavcontainer and add the parameter (and transfer it to run-tests) to see whether this works.

**Comment by eclipses** [comment]
Ok, I will try in the next days and I will let you know.

**Comment by freddydk** [comment]
Did you ever manage to find out whether you can change the locale?

**Comment by eclipses** [comment]
I started the changes and I got lost... 
Currently, I added a new step in my build pipeline to verify that the Regional Settings in the agent is the same as the one we are using for the development.

**Comment by freddydk** [comment]
I had a german container for some test tests - and tried to run tests using de-DE and the framework supports this - but a lot of the Microsoft tests fail - they are written for en-US.
I will add the -culture parameter to run-tests and get-tests and default it to en-US (to ensure non-breaking behavior).

**Comment by eclipses** [comment]
I'd like to know how Microsoft internally manages these failing tests when working in a different localization or maybe the build process runs only with en-US culture.

**Comment by freddydk** [comment]
our build processes always runs en-US

**Comment by eclipses** [comment]
Thanks for your confirmation, I will follow same method

**Comment by freddydk** [comment]
Released in 0.6.4.22
