### ISSUE TITLE
Cannot create new container with DB backup

### ISSUE THREAD

**Issue by paul-interdyn** [microsoft/navcontainerhelper#658]
On version 0.6.4.9, I'm not able to create containers using my own backup. I'm running a script that has worked previously, so something must have changed in the code. Also, I think it's just aliases, but I get the same result using new-navcontainer or new-bccontainer. The database version and requested docker version are the same.

new-navcontainer -accept_eula -accept_outdated -containerName dev-wkep -imageName mcr.microsoft.com/businesscentral/onprem:cu2-w1 -updateHosts -includeCSIDE -enableSymbolLoading -doNotExportObjectsToText -licenseFile "\\fs1\FTPRoot\BCDevLicenses\13.flf" -includeTestToolkit -includeTestLibrariesOnly -additionalParameters @('--storage-opt size=40G', '--volume c:\temp:c:\temp', '--env bakfile="c:\temp\WKEPDev.bak"')
NavContainerHelper is version 0.6.4.9
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Using image mcr.microsoft.com/businesscentral/onprem:cu2-w1-ltsc2019
Removing dev-wkep from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\dev-wkep
Creating Container dev-wkep
Version: 14.3.34444.0-W1
Style: onprem
Platform: 14.0.34251.0
Generic Tag: 0.0.9.9
Container OS Version: 10.0.17763.557 (ltsc2019)
Host OS Version: 10.0.18362.356 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file \\fs1\FTPRoot\BCDevLicenses\13.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\dev-wkep\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container dev-wkep from image mcr.microsoft.com/businesscentral/onprem:cu2-w1-ltsc2019
d5fbebf6073109032008f03ba37713ea9adebbba09e46442451c5428c516ab16
Waiting for container dev-wkep to be ready
Initializing...
Starting Container
Hostname is dev-wkep
PublicDnsName is dev-wkep
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'c:\temp\WKEPDev.bak'
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is dev-wkep
PublicDnsName is dev-wkep
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Using Database .bak file 'c:\temp\WKEPDev.bak'
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Failed to start service 'Dynamics 365 Business Central Server [NAV] (MicrosoftDynamicsNavServer$NAV)'.
at <ScriptBlock>, C:\Run\navstart.ps1: line 142
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container dev-wkep failed
At C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.9\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...dev-wkep failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container dev-wkep failed

**Comment by paul-interdyn** [comment]
Actually... just realized that it isn't pulling the same version. Apparently the cu2 tag isn't pulling the cu2 image listed on the Release Cumulative Updates page. https://support.microsoft.com/en-us/help/4470116/released-cumulative-updates-for-microsoft-dynamics-365-business. Trying again know with the explicit version tag (13.2.26556.0)...

**Comment by paul-interdyn** [comment]
Yep. The issue was in the cu2 tagging. Starts fine with the right image. Still, though, would be nice to know *why* the service tier failed to start.

**Comment by freddydk** [comment]
When you have this scenario, you can probably use Get-NavContainerEVentlog to extract the event log and see the reasoning there.
If you want to make sure you get the right version, you should add 1810-cu2-dk or 1904-cu2-dk - these will always end up in the same version.

**Comment by paul-interdyn** [comment]
Ah, thanks. What does the 1810 and 1904 tie to? In general, I really find figuring out the right versions of things extremely confusing with BC, since the version numbers displayed in the application don't seem to tie to the released build numbers.
