### ISSUE TITLE
Getting incompatible image

### ISSUE THREAD

**Issue by BrianThorChristensen** [microsoft/navcontainerhelper#659]
Hi,

It seems that the generic image for 1903 doesn't work.
When I try to install the image BCsandbox:dk, I get the message "The container operating system does not match the host operating system".

I use the command:
New-BCContainer -containerName 'VER15' -accept_eula -licenseFile 'C:\mylicense.flf' -alwaysPull -imageName 'bcinsider.azurecr.io/bcsandbox:dk' -memoryLimit '4G' -updateHosts -useBestContainerOS -isolation 'process' -includeTestToolkit -includeTestLibrariesOnly

the output I get is:
NavContainerHelper is version 0.6.4.9
Host is Microsoft Windows 10 Enterprise - Unknown/Insider build
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Pulling image bcinsider.azurecr.io/bcsandbox:dk-ltsc2019
dk-ltsc2019: Pulling from bcsandbox

... but the after the image has been downloaded I get:
A better Generic Container OS exists for your host (1903)
Creating temp container from bcinsider.azurecr.io/bcsandbox:dk-ltsc2019 and extract necessary files
... and ...
Removing temp container
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Pulling image mcr.microsoft.com/dynamicsnav:generic-1903
... and finally:
DockerDo : docker.exe: Error response from daemon: hcsshim::CreateComputeSystem c936868a1c25e0d46dfee00a520a371d7b32d193cb77c58f1e5243ead6f838ae: The container operating system does not match the host operating system.

I have tried to remove the -UseBestContainerOS switch, but I get the same result.

My version of Windows is:
Windows 10 Enterprise
Version 1903
Build 18999.1

Will it be possible to use process isolation with this build?

**Comment by NAVspecialist** [comment]
If you are trying to get the lastest public version you should use

"mcr.microsoft.com/businesscentral/sandbox:dk"

and not the insider-link.

**Comment by freddydk** [comment]
Remove -usebestcontaineros - you are running an unknown windows build - you cannot use process isolation

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Palle Arentoft <notifications@github.com>
Sendt: Thursday, October 10, 2019 11:21:07 AM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: Re: [microsoft/navcontainerhelper] Getting incompatible image (#659)


If you are trying to get the lastest public version you should use

"mcr.microsoft.com/businesscentral/sandbox:dk"

and not the insider-link.

**Comment by freddydk** [comment]
I will fix new-bccontainer so that -usebestcontainer won't select an invalid image.

**Comment by freddydk** [comment]
Actually NavSpecialist is 100% correct - when you specify --isolation Process, then I will not determine the isolation - and you will get what you ask for.
-usebestcontaineros will select the image closest - but will default to hyperv because the OS doesn't match, but then you specify --isolation process and then you get that.
NavSpecialist is also correct as to where you find the images.
