### ISSUE TITLE
IncludeTestToolkit is called after objects are exported

### ISSUE THREAD

**Issue by kine** [Microsoft/navcontainerhelper#66]
When I use IncludeTestToolkit switch when creating the container, the toolkit is imported after the objects were exported into txt file in Original-xxxx. I expect that it will be in oposite - import testtoolkit and then export the objects.

**Comment by freddydk** [comment]
I will reverse the order

**Comment by freddydk** [comment]
Actually that is not true, the import is done before the export, but if you already have run the export once for a container with that version, then it won't re-export the objects.

**Comment by kine** [comment]
Ok, thanks. Seems ok in current version.
