### ISSUE TITLE
Run-TestsInBCContainer -AppendToXUnitResultFile

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#661]
Related to issue #660 using `Run-TestsInBCContainer` I try to save my results of several test codeunits to a XUnit result file.

Therefore I am going to use -`XUnitResultFileName` for my first codeunit:
`PS C:\BE-terna\PowerShell> Run-TestsInBCContainer -containerName Industry27 -companyName TESTMANDANT -testCodeunit 5043081 -XUnitResultFileName C:\automotive\result.xml`
  Codeunit 5043081 Automotive Test Basic Success (0.223 seconds)
_this is successful_

And `-AppendToXUnitResultFile` for the remaining codeunits:
`PS C:\BE-terna\PowerShell> Run-TestsInBCContainer -containerName Industry27 -companyName TESTMANDANT -testCodeunit 5043082 -AppendToXUnitResultFile C:\automotive\result.xml`
which results in an error: the result file variable is somehow used as TenantID:
_Cannot bind parameter 'Tenant'. Cannot convert value "C:\automotive\result.xml" to type "Microsoft.Dynamics.Nav.Types.TenantId"._ 

Maybe my idea is the wrong approach?

Remark: this time I tried the routine as non-adminstrator and administrator. Both times the error occurs.

**Comment by freddydk** [comment]
The appendto... is a switch - not a string parameter

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Ralf Escher <notifications@github.com>
Sendt: Friday, October 11, 2019 10:06:15 AM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] Run-TestsInBCContainer -AppendToXUnitResultFile (#661)


Related to issue #660<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fnavcontainerhelper%2Fissues%2F660&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C32c08bce8d8c4f795ebe08d74e21e3c9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637063779768120075&sdata=liUmF0lBhBW0swDsOXdGrdAy48p6I%2BkTCemN4Gbiyy0%3D&reserved=0> using Run-TestsInBCContainer I try to save my results of several test codeunits to a XUnit result file.

Therefore I going to use -XUnitResultFileName for my first codeunit:
PS C:\BE-terna\PowerShell> Run-TestsInBCContainer -containerName Industry27 -companyName TESTMANDANT -testCodeunit 5043081 -XUnitResultFileName C:\automotive\result.xml\result.xml
Codeunit 5043081 Automotive Test Basic Success (0.223 seconds)
this is successful

And -AppendToXUnitResultFile for the remaining codeunits:
PS C:\BE-terna\PowerShell> Run-TestsInBCContainer -containerName Industry27 -companyName TESTMANDANT -testCodeunit 5043082 -AppendToXUnitResultFile C:\automotive\result.xml
which results in an error: the result file variable is somehow used as TenantID:
Cannot bind parameter 'Tenant'. Cannot convert value "C:\automotive\result.xml" to type "Microsoft.Dynamics.Nav.Types.TenantId".

Maybe my idea is the wrong approach?

Remark: this time I tried the routine as non-adminstrator and administrator. Both times the error occurs.

**Comment by ralf-escher** [comment]
My fault.
Thanks for the fast reply!
