### ISSUE TITLE
Export-NavContainerDatabasesAsBacpac in multitenant container throw error: the database does not exist

### ISSUE THREAD

**Issue by g-franck** [microsoft/navcontainerhelper#662]
Hi,

I do some tests on a container with multitenant, using Export-NavContainerDatabasesAsBacpac script and I have an issue and suddenly some questions similar to #98 .

Before explaining my issue, let's take a look to this simple case:
If I create a container using the standard script file CreateBCSandbox.ps1 by adding the parameter -multitenant as below:

`$accept_eula = $true
$containername = 'myContainer'
$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:15.0.36590.0-fr-ltsc2019'
$appbacpacuri = ''
$tenantbacpacuri = ''
$licenseFile = "C:\_Disk\Licences\myLicense.flf"

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$user = 'admin'
$password = 'P@ssword1'
$securePassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$adminCredential = New-Object PSCredential $user, $securePassword

New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -credential $adminCredential `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -licenseFile $licenseFile `
                 -multitenant `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -credential $adminCredential`

The script create 3 databases: Financialsfr, default (as a mounted tenant), and tenant.
**Question :**
What is this "tenant" database for ?
Is it a database that can be mounted afterwards, or a "temporary" database useful for the script ?

Now, let's take a look to my issue:

1. 
I create a container using the standard script file CreateBCSandbox.ps1 (without multitenant) as below:

`$accept_eula = $true
$containername = 'myContainer'
$navdockerimage = 'mcr.microsoft.com/businesscentral/sandbox:15.0.36590.0-fr-ltsc2019'
$appbacpacuri = ''
$tenantbacpacuri = ''
$licenseFile = "C:\_Disk\Licences\myLicense.flf"

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$user = 'admin'
$password = 'P@ssword1'
$securePassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$adminCredential = New-Object PSCredential $user, $securePassword

New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -credential $adminCredential `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -licenseFile $licenseFile `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -credential $adminCredential`

At this step, the script create one database "Financialsfr"

2. 
Now, I run the script below inside the container in order to convert it to multitenant:

`$serviceTierFolder = (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service").FullName
Import-Module "$serviceTierFolder\Microsoft.Dynamics.Nav.Management.psm1"

$CustomConfigFile =  Join-Path $ServiceTierFolder "CustomSettings.config"
$CustomConfig = [xml](Get-Content $CustomConfigFile)

$navServerInstance = $CustomConfig.SelectSingleNode("//appSettings/add[@key='ServerInstance']").Value
$databaseServer = $CustomConfig.SelectSingleNode("//appSettings/add[@key='DatabaseServer']").Value
$databaseInstance = $CustomConfig.SelectSingleNode("//appSettings/add[@key='DatabaseInstance']").Value
$databaseServerInstance = "$databaseServer\$databaseInstance"
$databaseName = $CustomConfig.SelectSingleNode("//appSettings/add[@key='DatabaseName']").Value
$applicationDatabaseName = 'Business Central App'
$user = 'admin'
$password = 'P@ssword1'
$securePassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$adminCredential = New-Object PSCredential $user, $securePassword
$tenant = 'myTenant'

Stop-NAVServerInstance –ServerInstance $navServerInstance
Invoke-sqlcmd -ServerInstance $databaseServerInstance -Database $databaseName -query 'CREATE USER "NT AUTHORITY\SYSTEM" FOR LOGIN "NT AUTHORITY\SYSTEM";'
Export-NAVApplication –DatabaseServer $databaseServer –DatabaseInstance $databaseInstance –DatabaseName $databaseName –DestinationDatabaseName $applicationDatabaseName -ServiceAccount 'NT AUTHORITY\SYSTEM' | Remove-NAVApplication –DatabaseName $databaseName -Force
Set-NAVServerConfiguration –ServerInstance $navServerInstance –element appSettings –KeyName 'DatabaseName' –KeyValue ''
Start-NAVServerInstance –ServerInstance $navServerInstance
Mount-NAVApplication –ServerInstance $navServerInstance –DatabaseServer $databaseServerInstance –DatabaseName $applicationDatabaseName -Force
Mount-NAVTenant –ServerInstance $navServerInstance -Tenant $tenant –DatabaseServer $databaseServerInstance -DatabaseName $databaseName -OverwriteTenantIdInDatabase
Sync-NAVTenant -Tenant $tenant -Mode ForceSync -ServerInstance $navServerInstance -Force
Restart-NAVServerInstance –ServerInstance $navServerInstance`

At this step, the script create a new database "Business Central App"

3. 
Now, I run the script below in order to generate .bacpac files:

`$containerName = "myContainer"
$user = 'admin'
$password = 'P@ssword1'
$securePassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$adminCredential = New-Object PSCredential $user, $securePassword
$bacpacFolder = "C:\ProgramData\NavContainerHelper\Extensions\$containerName\Bacpac"
$tenant = "myTenant"

Export-NavContainerDatabasesAsBacpac -containerName $containerName -sqlCredential $adminCredential -bacpacFolder $bacpacFolder -tenant $tenant`

At this step, the script created a new database "tempBusiness Central App" to create the app.bacpac file but threw an error during the _tenant_.bacpac file creation.
Below the detail:

`Copying Database on localhost\SQLEXPRESS from myTenant to tempTenant
Taking database myTenant offline
Warning, exception when running: ALTER DATABASE [myTenant] SET OFFLINE WITH ROLLBACK IMMEDIATE
Waiting... - retrying
Warning, exception when running: ALTER DATABASE [myTenant] SET OFFLINE WITH ROLLBACK IMMEDIATE
Waiting...... - retrying
Error when running: ALTER DATABASE [myTenant] SET OFFLINE WITH ROLLBACK IMMEDIATE
Putting database myTenant back online
Warning, exception when running: ALTER DATABASE [myTenant] SET ONLINE
Waiting... - retrying
Warning, exception when running: ALTER DATABASE [myTenant] SET ONLINE
Waiting...... - retrying
Error when running: ALTER DATABASE [myTenant] SET ONLINE
User does not have permission to alter database 'myTenant', the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
at Invoke-SqlCmdWithRetry, C:\Run\HelperFunctions.ps1: line 420
at Copy-NavDatabase, C:\Run\HelperFunctions.ps1: line 203
at <ScriptBlock>, <No file>: line 228
at <ScriptBlock>, <No file>: line 219
User does not have permission to alter database 'myTenant', the database does not exist, or the database is not in a state that allows access checks.
ALTER DATABASE statement failed.
Au caractère C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.9\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 : 13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation : (:) [Invoke-Sqlcmd], SqlPowerShellSqlExecutionException
    + FullyQualifiedErrorId : SqlError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
    + PSComputerName        : 9a75635fbadf38de970ed0368a67e35f154da2a5ad4a72b3f149423215338877`

The script expect a database called "myTenant" that does not exist.
The workaround I found is to name the tenant as the database
If in the step 2 I change:

`$tenant = 'myTenant'`
by
`$tenant = $databaseName`

And in the step 3:

`$tenant = 'myTenant'`
by
`$tenant = 'Financialsfr'`

All works fine, I have my 2 .bacpac files.

So, am I wrong in my process ? Or is it a real issue ?

Thanks a lot.
Franck

**Comment by freddydk** [comment]
First - your question.
The tenant database is a template database, used for creating new tenants.
default is a copy of tenant and is mounted.
New-NavContainerTenant will copy the tenant database and mount this.

When you create a multitenant container with -multitenant - you will find that the database name is always the same as the tenant name. That is a prerequisite for the other functions, so if you switch to multitenancy manually, you need to follow the same principle (which is the reason for export bacpac to fail)

**Comment by g-franck** [comment]
Hi Freddy,
Thank you for this quick and clear answer.
Cordially.
