### ISSUE TITLE
Error with Get-NavContainerServerConfiguration with BC14 containers

### ISSUE THREAD

**Issue by gintuoklis** [microsoft/navcontainerhelper#667]
Hey Guys, 
I receive the following error while running simple powershell command: 

**Get-NavContainerServerConfiguration -ContainerName ALProject10-bld**

```
Get-NavContainerServerConfiguration : The property 'configuration' cannot be found on
 this object. Verify that the property exists.
At line:1 char:1
+ Get-NavContainerServerConfiguration -ContainerName ALProject10-bld
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-NavContainerServerConfiguration
   ], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-NavContainerServerConfigura
   tion
```
container is built using this image "mcr.microsoft.com/businesscentral/onprem:1904-cu4-w1-ltsc2019" with navcontainerhelper 0.6.4.10

Best Regards. 
Gintautas

**Comment by freddydk** [comment]
It always helps to have the command used to create the container and the full output.

I can guess that it might be because you are running as non-admin and you maybe get license warnings or like.

What does this return: 

Invoke-ScriptInNavContainer -containerName $containerName -ScriptBlock{
    Get-NAVServerConfiguration -ServerInstance $ServerInstance -AsXml
}

**Comment by gintuoklis** [comment]
I found the cause. It's again full disk issue :(

**Comment by freddydk** [comment]
Ok, thanks for the info.
FYI
Flush-ContainerHelperCache can cleanup redundant cache information from containerhelper.
Reset docker to defaults will cleanup images.
