### ISSUE TITLE
consistent location for license file

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#668]
License should always be copied into the same folder.
Else this process wont work:
 * Create Container with Database from Cache
 * Import License
 * Clean Database

Use of My-Dir:

https://github.com/microsoft/navcontainerhelper/blob/8f59a47f6b97b292f8a4f9618f27bbca1ff8879e/ContainerHandling/New-NavContainer.ps1#L864

https://github.com/microsoft/navcontainerhelper/blob/8f59a47f6b97b292f8a4f9618f27bbca1ff8879e/AppHandling/Clean-BcContainerDatabase.ps1#L46

Use of Run-Dir:
https://github.com/microsoft/navcontainerhelper/blob/8f59a47f6b97b292f8a4f9618f27bbca1ff8879e/ContainerHandling/Import-NavContainerLicense.ps1#L39

**Comment by freddydk** [comment]
The import should put it in the my folder.

**Comment by freddydk** [comment]
Shipped in 0.6.4.14
