### ISSUE TITLE
CommunicationError : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#669]
**Scenario:**
Created a new nav container using the image microsoft/dynamics-nav:2018-cu3-gb
Imported the TestToolkit and run all of them.
The process fails when testing the codeunit 134383

So I ran the following script to test only that codeunit
`Run-TestsInNavContainer -containerName "SCA-CD" -companyName "CRONUS UK Ltd." -credential ([PSCredential]::new("admin", (ConvertTo-SecureString -String "P@ssW0rd!" -AsPlainText -Force))) -testCodeunit 134383 -detailed`

This is the result:
`Codeunit 134383 ERM Sales/Purch Status Error CommunicationError : Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
CommunicationError InnerException : Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.<>c__DisplayClass15_0.<EndInvokeInteractions>b__0() in S:\Depot\NAV110\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\
JsonHttpClient.cs:line 293
   at Microsoft.Dynamics.Framework.UI.Client.JsonHttpClient.ConvertExceptions[T](Func`1 action) in S:\Depot\NAV110\Platform\Client\ClientService\Prod.Client.ClientService.Client\Service\ServiceClients\JsonHttpClient\JsonHttpClient.c
s:line 168
ClientSession in Error
at AwaitState, C:\ProgramData\NavContainerHelper\Extensions\SCA-CD\PsTestTool-3\ClientContext.ps1: line 157
at InvokeInteraction, C:\ProgramData\NavContainerHelper\Extensions\SCA-CD\PsTestTool-3\ClientContext.ps1: line 170
at InvokeAction, C:\ProgramData\NavContainerHelper\Extensions\SCA-CD\PsTestTool-3\ClientContext.ps1: line 370
at Run-Tests, C:\ProgramData\NavContainerHelper\Extensions\SCA-CD\PsTestTool-3\PsTestFunctions.ps1: line 290
at <ScriptBlock>, <No file>: line 47
ClientSession in Error
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.10\AppHandling\Run-TestsInNavContainer.ps1:263 char:17
+                 throw $_.Exception.Message
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ClientSession in Error:String) [], RuntimeException
    + FullyQualifiedErrorId : ClientSession in Error`

Then I opened the RTC and tested the same codeunit from there and no errors.
After if I run again the previous command via powershell no errors.

I suppose the Newtonsoft dll does not load properly using Run-TestsInNavContainer command.

**Comment by freddydk** [comment]
Newtonsoft is a fundamental part of the connection, if that doesn't load / doesn't exist, the error will be immediate.

ClientSession in error is typically a service tier error causing the session to fail on the server and thus the client session to be left without a server session.

Get-NavContainerEventLog might give an indication of what went wrong on the server.

BTW. please note that microsoft/dynamics-nav is no longer updated with docker images - the location is mcr.microsoft.com/dynamicsnav - all images are here. (This is not the cause of your error though)

**Comment by eclipses** [comment]
What is strange is that I receive the error using Run-TestsInNavContainer but not using the RTC

**Comment by freddydk** [comment]
Does the eventlog reveal anything?

**Comment by eclipses** [comment]
I'm going to reproduce it and I will let your know

**Comment by eclipses** [comment]
Unfortunately no events

**Comment by eclipses** [comment]
Additional information is that if I run ALL the tests using Run-TestsInNavContainer it starts correctly executing the tests till arriving to the codeunit 134383 where it fails.

**Comment by freddydk** [comment]
I will see if I can repro, thanks for the info.

**Comment by freddydk** [comment]
Pretty sure that I found the reason for this - and this should work now.

**Comment by eclipses** [comment]
Let me test and I will let you know

**Comment by eclipses** [comment]
I confirm that now it works. Thanks
