### ISSUE TITLE
Direct deploy to Azure Container Instance

### ISSUE THREAD

**Issue by Sven-Niehus** [microsoft/navcontainerhelper#670]
Hi,

is it possible to use the navcontainerhelper to directly deploy to a new [Azure Container Instance](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-overview)?

**Comment by freddydk** [comment]
No, not at this time.

**Comment by equisyscr** [comment]
Currently facing some multi environment testing that this feature would help with, so adding my voice for this requirement.

**Comment by freddydk** [comment]
I am using Azure VMs with traefik, which allows you to have any number of containers running isolation mode on a VM accessible from outside automatically.
and you can run powershell and containerhelper on the vm.
Blog post coming up.

**Comment by Sven-Niehus** [comment]
The problem with using Azure VMs is the high price and relatively high maintenance amount compared to using Azure Container Instances so it would be really helpful if the navcontainerhelper could directly deploy to ACIs.

**Comment by freddydk** [comment]
Not sure you have calculated the ACI pricing correctly.
it is $0.0000135 a second per vCPU, which is $35 a month.
+ $0.0000015 a second per GB, which is $4 a month.

a VM with 4 vCPU machine and 16GB is $128 a month.
the same ACI is $204

In the VM you could host some containers and share the memory/CPUs - the ACI you should at least have 2 vCPU and 8GB per container.

The VM can even be shut down at night which would cut the price in half - ACI's could do the same - but they loose everything on shutdown.

This is actually the reason why I decided not to follow this path - it is too expensive for the need we have.

**Comment by freddydk** [comment]
And BTW - ACIs are really designed as build containers for various build tasks. The issue however is that the BC images are fairly large and it takes a long time to download (and you pay for that time).
I might work on allowing ACIs for build if I can get the ACI team to cache the latest and current BC images.

**Comment by equisyscr** [comment]
Thanks for the insight, very appreciated.

However, Microsoft view of only supporting the last 2 releases, which I definitely adopt when possible, is not realistic for smaller companies like us. As long as OnPrem users exists, we will need to support them, therefore having an easy access to the images for hotfixes.

Therefore, our way to go will probably to have our own build machine that will cache the images. I may talk quickly and generalise our case, but I guess it reduces the intensive of you lobbying for this feature, saving you a bit of time.

Best,
Cyrille

**Comment by freddydk** [comment]
Yep, thanks

Fortunately you can have onprem build agents - or online - a palette of options (which also requires people to investigate and decide:-))
