### ISSUE TITLE
Fails to initialise ADMIN user on BC13 image

### ISSUE THREAD

**Issue by equisyscr** [microsoft/navcontainerhelper#672]
When trying to deploy a BC 13 image, the process fails at creating the SUPER user:
![image](https://user-images.githubusercontent.com/39130724/66923962-abe4db00-f021-11e9-9677-949b0147c345.png)

It was tested with both the old sandbox (microsoft/bcsandbox:13.0.24630.0-gb) and the onprem containers (mcr.microsoft.com/businesscentral/onprem:13.0.24630.0-gb-ltsc2019).
It was tested with both a licence dedicated to BC 15 and BC 13.

Any clue on how to fix this? Currently blocking our hotfixes.

**Comment by freddydk** [comment]
I have never seen a situation where a license file error wasn't caused by a license file error. It was always (until now?) a wrongly provided license file.
How do you provide the license file?
As a local file or a URL?

**Comment by equisyscr** [comment]
Hi Freddy

The license is a local file, it is provided exactly the same way for BC14 and BC15 containers, which works ok.

The licenses files themselves are from https://mbs2.microsoft.com with Product Line "Microsoft Dynamics 365 Business Central on premises" and versions 15 or 13.

Should I PM the licence files ?

**Comment by freddydk** [comment]
You are welcome to send me the license file to freddyk at microsoft dot com with the command used to run the container and I will give it a try.
