### ISSUE TITLE
Can download Microsoft_Application symbols

### ISSUE THREAD

**Issue by garynilsen** [microsoft/navcontainerhelper#673]
I just downloaded a new version 14 BC doc container 14.6.36463.0-na and when I download the symbols all that I get is Microsoft_System_14.0.36457.0.app.  It won't download the Microsoft_Application_14.0.36457.0.app.  Is there anything I need to do to get that symbol to download?
In the app.json
  "version": "1.0.0.14",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [],
  "screenshots": [],
  "platform": "14.0.0.0",
  "idRanges": [
    {
      "from": 60000,
      "to": 60099
    }
  ],
  "showMyCode": true,
  "runtime": "3.2"
}

My launch.json is:
{
    "version": "0.2.0",
    "configurations": [
        
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://newbc14",
            "serverInstance": "nav",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "schemaUpdateMode": "ForceSync"
        }
    ]
}

**Comment by freddydk** [comment]
You need to turn the app.json into a 15.x app.json.
Use AL Go - create a new app for runtime 4.0 and see what you need to change (dependencies)

**Comment by garynilsen** [comment]
Thank you that helped me.
