### ISSUE TITLE
Create-AlProjectFolderFromNavContainer failing while using -alFileStructure

### ISSUE THREAD

**Issue by ashikivor** [microsoft/navcontainerhelper#675]
This command fails only while using the command -alFileStructure.

![image](https://user-images.githubusercontent.com/28855499/67021855-94c8ea80-f100-11e9-9522-5065306cf3d1.png)

Also, noticed that if there are any files or folder in "-alProjectFolder", the files and folder are getting deleted. 

Using version 0.6.4.10.
docker image: mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019

**Comment by freddydk** [comment]
I need a LOT more info than this.

**Comment by ashikivor** [comment]
![image](https://user-images.githubusercontent.com/28855499/67024797-4a963800-f105-11e9-873d-1737b9ca5be1.png)

Exactly what is happening.

**Comment by freddydk** [comment]
the alfilestructure should be a function, which returns the location of the file - not { $true }
Read more here: https://freddysblog.com/2019/08/02/organizing-your-al-files/

**Comment by freddydk** [comment]
Assuming that this fixed the issue.
