### ISSUE TITLE
AppSourceCop.json with Compile-AppInNavContainer

### ISSUE THREAD

**Issue by pmoison** [microsoft/navcontainerhelper#676]
It seems that AppSourceCop.json is ignored by Compile-AppInNavContainer.
Does exist a workaround ?

**Comment by freddydk** [comment]
It would help if you would specify what parameters you use when using Compile-AppInNavContainer, then I could see whether you specify -enableAppSourceCop.

**Comment by pmoison** [comment]
Last version of NavContainerHelper

Compile-AppInNavContainer -credential $Credential -containerName $ContainerName -appProjectFolder $_ -appOutputFolder $_  -EnableCodeCop:$false -EnableUICop:$false -EnableAppSourceCop -EnablePerTenantExtensionCop:$false

![image](https://user-images.githubusercontent.com/43445162/67067476-caa8b600-f176-11e9-9802-300d3b73af06.png)

AppSourceCop.json in folder App of container:

![image](https://user-images.githubusercontent.com/43445162/67067583-24a97b80-f177-11e9-93a9-d7955c69fe7e.png)

AppSourceCop.json content:

{
    "mandatoryAffixes": ["CAGxx"]
}

Works fine when compiling from VS Code:

![image](https://user-images.githubusercontent.com/43445162/67067731-b4e7c080-f177-11e9-89d9-b5a697cf0b22.png)

**Comment by freddydk** [comment]
Just tried the same - and it seems to work:
![image](https://user-images.githubusercontent.com/10775043/67118940-4e4dbb80-f1e6-11e9-9185-7275f0ca9ce3.png)
But I can see that I am using 15.x containers - and you have a 14.x container. Did you try with 15?

**Comment by pmoison** [comment]
Just tested with 15.x container and indeed it works.
Still not working with 14.x container (mcr.microsoft.com/businesscentral/onprem:14.1.32615.0-fr image)
normal?

**Comment by freddydk** [comment]
Will ask the team whether something needs to be done differently in 14.x

**Comment by pmoison** [comment]
New update after some other tests (NavContainerHelper  0.6.4.14)
The subject of the issue can be requalified because all analyzers don't work with containers 14.x with recent versions of NavContainerHelper.

**Comment by freddydk** [comment]
thanks - will have a look.

**Comment by pmoison** [comment]
Any feedback?

**Comment by pmoison** [comment]
New update after some other tests (several runs for each) with containers 14.x.
Tested with container image mcr.microsoft.com/businesscentral/onprem:1904-rtm-fr : Failed
Tested with container image mcr.microsoft.com/businesscentral/onprem:14.1.32615.0-fr : Failed
Tested with container image mcr.microsoft.com/businesscentral/onprem:1904-cu1-fr : Failed
Tested with container image mcr.microsoft.com/businesscentral/onprem:1904-cu1-w1 : Failed
Tested with container image mcr.microsoft.com/businesscentral/onprem:1904-cu2-fr : Succeeded
Tested with container image mcr.microsoft.com/businesscentral/onprem:1904-cu3-fr : Succeeded

**It seems that the issue is related to the container image v14 before CU2...**

**Comment by freddydk** [comment]
Thanks for investigating.
Do you know whether this has ever worked with 14.x cu1 and earlier?
(I mean whether this is a regression in containerhelper or it is something that just wasn't working before cu2)

**Comment by pmoison** [comment]
Visibly not a regression in containerhelper. Just tested with an older version (0.6.2.5) and doesn't work.

**Comment by freddydk** [comment]
Ok, so it is something that has never worked with 14.cu1 and earlier.
This is a huge help for me, but at the same time puts the priority down.
Is this something that is needed for older versions - or can we live with the fact that it works now?

**Comment by pmoison** [comment]
We can live with the fact that it works with more recent versions. For projects based on earlier versions which it doesn't work, we will arrange our code checking processes...

**Comment by freddydk** [comment]
Agree, thanks for the assistance.
