### ISSUE TITLE
[Feature Request] Get-NavContainerHelperVersion

### ISSUE THREAD

**Issue by ThomasBrendel** [microsoft/navcontainerhelper#677]
Hello,

maybe you should consider to request the NavContainerHelper version that is currently "in use".
Or just print out the currently active version in the welcome-text. 
If you download a new version and have an old version active, you cant be sure which version is active NOW. Or your Install command gets failed.

So better would be a more transparent information about active version.

Thanks

**Comment by freddydk** [comment]
When creating a new container, it displays a number of things:
```
Create bingmaps-bld from mcr.microsoft.com/businesscentral/onprem:1910-rtm-w1
NavContainerHelper is version 0.6.4.10
Host is Microsoft Windows 10 Enterprise - 1903
Docker Client Version is 19.03.2
Docker Server Version is 19.03.2
Using image mcr.microsoft.com/businesscentral/onprem:1910-rtm-w1-ltsc2019
```
Which can help during troubleshooting - but also show the user the version number.
This is one of the reasons for always requesting the command used to create the container and the full output.

**Comment by ThomasBrendel** [comment]
Hello Freddy,

but we not always make a new container. We just do an update of the navcontainerhelper when there is a new version, to get newest corrections.
So we cant get this containercreationmessage.

Best regards
Thomas Brendel



MODUS Consult AG
James-Watt-Straße 6
D-33334 Gütersloh
E-Mail contact@modusconsult.de
Internet www.modusconsult.de

Vorstand: Stefan Sagowski, Klaus Wagner
Aufsichtsratsvorsitzender: Dr. Thomas Olemotz

Amts­ge­richt Güters­loh, HRB 7786
USt-ID-Nr. DE257988856

Entdecken Sie unsere Webinare für Business-IT und treffen Sie uns live vor Ort: https://www.modusconsult.de/unternehmen/modus-consult-live
Bleiben Sie auf dem aktuellsten Stand und erhalten Sie mit unserem Newsletter alle Neuigkeiten aus unserem Unternehmen: https://www.modusconsult.de/unternehmen/newsletter
Haben Sie Lust auf eine neue Herausforderung? https://www.modus-karriere.de

Wir nehmen das Thema Datenschutz sehr ernst. Deswegen informieren wir Sie über die Verarbeitung Ihrer personenbezogenen Daten durch die MODUS Consult AG und die Ihnen nach dem Datenschutzrecht zustehenden Rechte auf https://www.modusconsult.de/datenschutz.

Die 1995 gegründete MODUS Consult AG bietet integrative, ganzheitliche Leistungen aus einer Hand. Von ERP und CRM über DMS und BI bis zu Systemberatung und -technik basieren unsere Lösungen und unser Know-how auf der Erfahrung von über 20 Jahren erfolgreicher Zusammenarbeit mit über 1.000 Kunden. Mit unseren zertifizierten Branchenlösungen auf Basis von Microsoft Dynamics setzen wir als Microsoft Gold Partner höchste Qualitätsansprüche an uns und an die gemeinsam mit unseren Partnern geschaffenen Lösungen.
Die MODUS Consult AG ist ein Unternehmen der Bechtle Gruppe.


Von: Freddy Kristiansen <notifications@github.com>
Gesendet: Freitag, 18. Oktober 2019 10:16
An: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Brendel, Thomas <Thomas.Brendel@modusconsult.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/navcontainerhelper] [Feature Request] Get-NavContainerHelperVersion (#677)


When creating a new container, it displays a number of things:

Create bingmaps-bld from mcr.microsoft.com/businesscentral/onprem:1910-rtm-w1

NavContainerHelper is version 0.6.4.10

Host is Microsoft Windows 10 Enterprise - 1903

Docker Client Version is 19.03.2

Docker Server Version is 19.03.2

Using image mcr.microsoft.com/businesscentral/onprem:1910-rtm-w1-ltsc2019

Which can help during troubleshooting - but also show the user the version number.
This is one of the reasons for always requesting the command used to create the container and the full output.

**Comment by freddydk** [comment]
Got it 
Are you suggesting a function or that the version number is displayed in various places?

**Comment by freddydk** [comment]
Doesn't 

Get-InstalledModule NavContainerHelper

not provide that information?

**Comment by ThomasBrendel** [comment]
You are right,

thats the correct version info…close my issue



MODUS Consult AG
James-Watt-Straße 6
D-33334 Gütersloh
E-Mail contact@modusconsult.de
Internet www.modusconsult.de

Vorstand: Stefan Sagowski, Klaus Wagner
Aufsichtsratsvorsitzender: Dr. Thomas Olemotz

Amts­ge­richt Güters­loh, HRB 7786
USt-ID-Nr. DE257988856

Entdecken Sie unsere Webinare für Business-IT und treffen Sie uns live vor Ort: https://www.modusconsult.de/unternehmen/modus-consult-live
Bleiben Sie auf dem aktuellsten Stand und erhalten Sie mit unserem Newsletter alle Neuigkeiten aus unserem Unternehmen: https://www.modusconsult.de/unternehmen/newsletter
Haben Sie Lust auf eine neue Herausforderung? https://www.modus-karriere.de

Wir nehmen das Thema Datenschutz sehr ernst. Deswegen informieren wir Sie über die Verarbeitung Ihrer personenbezogenen Daten durch die MODUS Consult AG und die Ihnen nach dem Datenschutzrecht zustehenden Rechte auf https://www.modusconsult.de/datenschutz.

Die 1995 gegründete MODUS Consult AG bietet integrative, ganzheitliche Leistungen aus einer Hand. Von ERP und CRM über DMS und BI bis zu Systemberatung und -technik basieren unsere Lösungen und unser Know-how auf der Erfahrung von über 20 Jahren erfolgreicher Zusammenarbeit mit über 1.000 Kunden. Mit unseren zertifizierten Branchenlösungen auf Basis von Microsoft Dynamics setzen wir als Microsoft Gold Partner höchste Qualitätsansprüche an uns und an die gemeinsam mit unseren Partnern geschaffenen Lösungen.
Die MODUS Consult AG ist ein Unternehmen der Bechtle Gruppe.


Von: Freddy Kristiansen <notifications@github.com>
Gesendet: Freitag, 18. Oktober 2019 11:45
An: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Brendel, Thomas <Thomas.Brendel@modusconsult.de>; Author <author@noreply.github.com>
Betreff: Re: [microsoft/navcontainerhelper] [Feature Request] Get-NavContainerHelperVersion (#677)


Doesn't

Get-InstalledModule NavContainerHelper

not provide that information?
