### ISSUE TITLE
Container created but Icons are not

### ISSUE THREAD

**Issue by fibbert** [microsoft/navcontainerhelper#687]
This is a weird problem.
Windows Server 2019
latest New-NavContainer or New-BCContainer

On the user who installed the Docker and NavContainerHelper's login the software works fine.

On other users who are on the server, administrators of the local server, the containers are created but the script fails with an error creating the icons.

Same script for both users - different results.  Tried running from Elevated Powershell ISE.  Any suggestions?

Script is

> PS C:\Windows\system32> #$credential = get-credential
> $licensefolder = "D:\Development\Licenses"
> $mylicense = "BC14 On Prem - Sept 11 - 2019.flf"
> $imageName = "mcr.microsoft.com/businesscentral/onprem:cu4-na-ltsc2019"
> $containerName = 'bcsndbx14'
> $mylicense = join-path $licensefolder $mylicense
> 
> 
> New-BCContainer  -accept_eula -containerName $containerName -imageName $imageName -assignPremiumPlan -updateHosts -auth NavUserPassword -includeCSide -enableSymbolLoading -licenseFile $mylicense

See output of the New-BCContainer script

> NavContainerHelper is version 0.6.4.10
> Host is Microsoft Windows Server 2019 Standard - ltsc2019
> Docker Client Version is 19.03.3
> Docker Server Version is 19.03.3
> Using image mcr.microsoft.com/businesscentral/onprem:cu4-na-ltsc2019
> Removing container bcsndbx14
> Removing bcsndbx14 from hosts
> Removing C:\ProgramData\NavContainerHelper\Extensions\bcsndbx14
> Creating Container bcsndbx14
> Version: 14.5.35970.0-na
> Style: onprem
> Platform: 14.0.35916.0
> Generic Tag: 0.0.9.94
> Container OS Version: 10.0.17763.678 (ltsc2019)
> Host OS Version: 10.0.17763.805 (ltsc2019)
> WARNING: The container operating system matches the host operating system, but the revision is different.
> If you encounter issues, you might want to specify -isolation hyperv
> Using locale en-US
> Using process isolation
> Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
> Using license file D:\Development\Licenses\BC14 On Prem - Sept 11 - 2019.flf
> Files in C:\ProgramData\NavContainerHelper\Extensions\bcsndbx14\my:
> - AdditionalOutput.ps1
> - AdditionalSetup.ps1
> - license.flf
> - MainLoop.ps1
> - SetupNavUsers.ps1
> - updatehosts.ps1
> Creating container bcsndbx14 from image mcr.microsoft.com/businesscentral/onprem:cu4-na-ltsc2019
> 28aedc44f8d4e3ee345aa1f88842daf6ee6f18368316e4ffa247f1f0210f04d9
> Waiting for container bcsndbx14 to be ready
> Initializing...
> Starting Container
> Hostname is bcsndbx14
> PublicDnsName is bcsndbx14
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint 3480D34956352926CA1309C9E32FECFDEB36505F
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Registering event sources
> Creating DotNetCore Web Server Instance
> Using license file 'c:\run\my\license.flf'
> Import License
> Creating http download site
> Setting SA Password and enabling SA
> Creating admin as SQL User and add to sysadmin
> Creating SUPER user
> Assign Premium plan for ADMIN
> Container IP Address: 172.18.80.46
> Container Hostname  : bcsndbx14
> Container Dns Name  : bcsndbx14
> Web Client          : http://bcsndbx14/NAV/
> Dev. Server         : http://bcsndbx14
> Dev. ServerInstance : NAV
> 
> Files:
> http://bcsndbx14:8080/al-3.0.154634.vsix
> 
> Initialization took 163 seconds
> Ready for connections!
> Reading CustomSettings.config from bcsndbx14
> Creating Desktop Shortcuts for bcsndbx14
> New-DesktopShortcut : Unable to save shortcut "C:\Users\SrdanG\Desktop\bcsndbx14 Web Client.lnk".
> At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.10\ContainerHandling\New-NavContainer.ps1:1183 char:13
>  '+             New-DesktopShortcut -Name "$containerName Web Client" -Ta ...
>  '+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (:) [New-DesktopShortcut], DirectoryNotFoundException
>     + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,New-DesktopShortcut

**Comment by freddydk** [comment]
Does the folder exist?

C:\Users\SrdanG\Desktop

**Comment by freddydk** [comment]
Tried to create another user on an Azure VM - works fine.
All the script does is to create shortcuts using this function: https://github.com/microsoft/navcontainerhelper/blob/master/Misc/New-DesktopShortcut.ps1
Which should be using the right functions to find the right folder and create the shortcut.

**Comment by fibbert** [comment]
The user has a special ASCII character (I don't think it's unicode) in his login user name.  So the d is actually a đ so we're changing the user name, deleting the profile and trying again.  It does seem like the script is replacing the đ with a d.

Not sure if that is a bug or a known limitation.

**Comment by fibbert** [comment]
Changed the user name and deleting the user profile.  This seemed to fix the issue.
