### ISSUE TITLE
Shared Folders & Import-ObjectsToNavContainer

### ISSUE THREAD

**Issue by NAVFreak** [Microsoft/navcontainerhelper#69]
Hi,
This issue seems to be related to #49.

Same problem "Error response from daemon: filesystem operations against a running Hyper-V container are not supported"

But then I realised that I could copy the file to the shared folder:
"C:\DEMO\Extensions\$containername\my"

But then I get the following error:
_____________________________________________________________________________________________
`C:\GIT\Back-Order-Management-Extension> Import-ObjectsToNavContainer 
        -objectsFile ".\NAV Dev Tools\ObjectLauncher\Page 69923 - Object Launcher v2017 v1.2.txt" 
        -containerName $containername 
        -sqlCredential $credential
Copy .\NAV Dev Tools\ObjectLauncher\Page 69923 - Object Launcher v2017 v1.2.txt to container NAV2018CU00 (c:\run\Page 69923 - Object Launcher v2017 v1.2.txt)
Error response from daemon: filesystem operations against a running Hyper-V container are not supported
Importing Objects from c:\run\Page 69923 - Object Launcher v2017 v1.2.txt
Cannot find path 'C:\run\Page 69923 - Object Launcher v2017 v1.2.txt' because it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.0.1\ObjectHandling\Import-ObjectsToNavContainer.ps1:35 char:5
+Invoke-Command -Session $session -ScriptBlock { Param($objectsFil ...
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\run\Page 699... v2017 v1.2.txt:String) [Get-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand`
______________________________________________________________________________________________________
What I can see is that it tries to import the file from c:\run instead of c:\run\my
and c:\run is not a shared for folder.

If it tried to import from the shared folder that I copied the file to it would find it ;)

**Comment by freddydk** [comment]
Do you have the newest version of the Navcontainerhelper?
This bug should have been fixed a while back.

**Comment by NAVFreak** [comment]
Doh! *face palm*.  You are right, sorry about that.

**Comment by freddydk** [comment]
No problem
