### ISSUE TITLE
"The Type [System.IO.Packaging.Package] could not be found" when using -replaceDependencies

### ISSUE THREAD

**Issue by cstuber** [microsoft/navcontainerhelper#692]
We are trying to use the -replaceDependencies parameter to publish a custom Base Application and then import the TestToolkit. 

```
Publish-NewApplicationToBCContainer `
    -containerName $containerName `
    -appDotNetPackagesFolder (Join-Path $alProjectFolder ".netpackages") `
    -appFile $app `
    -credential $credential `
    -useNewDatabase `
    -restoreApps Yes `
    -doNotUseDevEndpoint `
    -replaceDependencies $replaceDependencies

Import-TestToolkitToBcContainer `
    -containerName $containerName `
    -includeTestLibrariesOnly `
    -credential $credential `
    -replaceDependencies $replaceDependencies
```

This throws the error "The Type [System.IO.Packaging.Package] could not be found.".

```
NavContainerHelper is version 0.6.4.14
Host is Microsoft Windows 10 Enterprise - ltsc2019
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Pulling image mcr.microsoft.com/businesscentral/onprem:1910-de-ltsc2019
1910-de-ltsc2019: Pulling from businesscentral/onprem
Using image mcr.microsoft.com/businesscentral/onprem:1910-de-ltsc2019
Disabling Health Check (always report healthy)
Removing container Industry27B
Removing Industry27B from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\Industry27B
Creating Container Industry27B
Version: 15.0.36560.0-de
Style: onprem
Platform: 15.0.36510.0
Generic Tag: 0.0.9.95
Container OS Version: 10.0.17763.737 (ltsc2019)
Host OS Version: 10.0.17763.805 (ltsc2019)
[...]
Checking dependencies in C:\ProgramData\NavContainerHelper\Extensions\Industry27B\Extensions\Microsoft_ELSTER VAT Localization for Germany_15.0.36560.0.app
Copy from container Industry27B (C:\Applications\Elster\Source\Elster.app) to C:\ProgramData\NavContainerHelper\Extensions\Industry27B\_Elster.app
Checking dependencies in C:\ProgramData\NavContainerHelper\Extensions\Industry27B\_Elster.app
WARNING: Could not publish :Elster.app - The Type [System.IO.Packaging.Package] could not be found.
Copy from container Industry27B (C:\Applications\TestFramework\TestLibraries\Any\Microsoft_Any.app) to C:\ProgramData\NavContainerHelper\Extensions\Industry27B\_Microsoft_Any.app
Checking dependencies in C:\ProgramData\NavContainerHelper\Extensions\Industry27B\_Microsoft_Any.app
Publish-NavContainerApp : The Type [System.IO.Packaging.Package] could not be found.
In C:\Users\christoph.stuber\OneDrive - BE-terna GmbH\Dokumente\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.14\O
bjectHandling\Import-TestToolkitToNavContainer.ps1:152 char:13
+             Publish-NavContainerApp -containerName $containerName -ap ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.IO.Packaging.Package:TypeName) [Publish-NavContainerApp], Runt
   imeException
    + FullyQualifiedErrorId : TypeNotFound,Publish-NavContainerApp
```

**Comment by freddydk** [comment]
You have removed a large part of the output [...], which might be relevant, could you include that?
It looks like the problem is in publish-newapp and not in import-tests?
Is the elster app a runtime package?

**Comment by cstuber** [comment]
The complete output is in the attachment [output.txt](https://github.com/microsoft/navcontainerhelper/files/3777486/output.txt)
The Elster app and other default apps are probably runtime packages.

**Comment by freddydk** [comment]
I at first thought that this was due to runtime packages, but probably not.
You could try to add this right before calling publish-newapplication... :
```
Invoke-scriptinnavContainer -containername <container> -scriptblock { 
    add-type -path (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service\system.io.packaging.dll").FullName
}
```

**Comment by cstuber** [comment]
Neither running as administrator nor adding your suggested code resulted in a different output.

**Comment by freddydk** [comment]
Did you try this on other machines (maybe non-german host machines)?
also, Could you share the script you use?

**Comment by cstuber** [comment]
The script is attached [Create-IndustryBaseApp.txt](https://github.com/microsoft/navcontainerhelper/files/3784096/Create-IndustryBaseApp.txt) (some information is obfuscated)

This error can be reproduced on three different machines, but all three are german.

**Comment by cbrandemann** [comment]
I have the same issue when I am importing the TestToolKit in a build pipeline (with replace dependecies). The build agent is running on my local machine. Outside the build pipeline I have no issues with replace dependecies.
[Import-TestToolkit.zip](https://github.com/microsoft/navcontainerhelper/files/3789001/Import-TestToolkit.zip)

**Comment by freddydk** [comment]
So you are saying that if you run the pipeline on your machine it fails - if you run it manually it works?
What user is the pipeline running as?
is that running elevated?

**Comment by cbrandemann** [comment]
Yes, that is what I am saying. I am running the agent in the command prompt as Administrator (as discribed in the "cicd workshop.pdf"

This is the error message:
Copy from container IEM15W1-bld (C:\Applications\TestFramework\TestLibraries\Any\Microsoft_Any.app) to C:\ProgramData\NavContainerHelper\Extensions\IEM15W1-bld\_Microsoft_Any.app
Checking dependencies in C:\ProgramData\NavContainerHelper\Extensions\IEM15W1-bld\_Microsoft_Any.app
##[error]Publish-NavContainerApp : Unable to find type [System.IO.Packaging.Package].
##[error]At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.15\ObjectHandling\Import-TestToolkitToNavContain
er.ps1:152 char:13

I have skipped the removal of the container in the build pipeline to test the import of the testtoolkit manually. Now the testtoolkit is imported without any issues. (same docker container)

**Comment by freddydk** [comment]
I found the bug - will release a fix today.

**Comment by cbrandemann** [comment]
My problem is solved with this fix

**Comment by freddydk** [comment]
Thanks

**Comment by cstuber** [comment]
Runs without problems now. Thanks

**Comment by freddydk** [comment]
Thanks for reporting this and sorry for not seeing the problem immediately
