### ISSUE TITLE
Get-TestsFromBCContainer: -companyName

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#693]
Hi @freddydk,
I examined your example [Run-Tests.ps1](https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2FRun-Tests.ps1&version=GBmaster)

While `Run-TestsInBCContainer` offers -companyName as a parameter, 
`Get-TestsFromBCContainer` does not. 

Since I usally run my tests in a test company this would be a nice feature ;-)
Or do I miss something?

**Comment by freddydk** [comment]
fixed in 0.6.4.15
