### ISSUE TITLE
Question: Where can I raise issues regarding HelloWorld?

### ISSUE THREAD

**Issue by achim-t** [microsoft/navcontainerhelper#694]
I noticed some minor problems in the scripts at https://dev.azure.com/businesscentralapps/_git/HelloWorld 

Where can I raise these issues?

**Comment by freddydk** [comment]
right here:-)

**Comment by achim-t** [comment]
1. AzureVM-Sandbox.ps1 Line 12
```
$azureVmCredential = New-Object PSCredential $azureVM.Username, ($azureVM.Password | ConvertTo-SecureString)
```
should be changed to 
``` 
$securePassword = try { ($azureVM.Password | ConvertTo-SecureString) } catch { ($azureVM.Password | ConvertTo-SecureString -AsPlainText -Force) }
$azureVmCredential = New-Object PSCredential $azureVM.Username, $securePassword
```
Otherwise a plain password will lead to an error.

2. Deploy-App.ps1 Line 46

The Target to deploy to a AzureVM is hardcoded in the script. It should be a parameter, IMO.

3. Deploy-App.ps1 Lines 82-87

`Publish-NavContainerApp`, `Start-NavContainerAppDataUpgrade` and `Install-NavContainerApp` should be replaced by their BC equivalents. 

4. SessionFunctions.ps1 Line 11

```
Invoke-Command -Session $vmSession -ScriptBlock ([ScriptBlock]::Create([System.IO.File]::ReadAllText($filename))) -ArgumentList $argumentList
```
should be changed to 
```
Invoke-Command -Session $session -ScriptBlock ([ScriptBlock]::Create([System.IO.File]::ReadAllText($filename))) -ArgumentList $argumentList
```
Because the parameter for the function is called `$session` not `$vmSession`

Same thing for Line 28

**Comment by freddydk** [comment]
Thanks - will go through those and fix the template.

**Comment by achim-t** [comment]
On that note, how can I be alerted of changes to the hello world repository? Is there something more convenient than manually checking?

**Comment by freddydk** [comment]
Have been through these comments and included all suggestions - thanks a million
