### ISSUE TITLE
Test automation, Number of tests to be executed

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/navcontainerhelper#695]
We followed Freddys repository on https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld?path=%2Fscripts%2FRead-Settings.ps1&version=GBmaster

and included it our solution. My question is that there is only 3219 tests in all dependencies from Microsoft. In previous version onPrem there were more than 20k of tests. Is this normal or?

P.S i can mention that when creating a new container on the end i get this errors and warnings:

![image](https://user-images.githubusercontent.com/53824412/67576143-4fc73880-f73e-11e9-97e2-d02f468c54b3.png)

Scripts are basically the same as we used on version 13 with all dependency included in test tool for baseapp, this is testtool app.json:

{
  "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "name": "TRASER DMS Business Central Test Automations",
  "publisher": "TRASER Software GmbH",
  "version": "1.19.09.00",
  "brief": "",
  "description": "TRASER Dealer Management System 365 Test Automations",
  "privacyStatement": "",
  "EULA": "",
  "help": "https://docs.traser-software.de",
  "helpBaseUrl": "https://docs.traser-software.de/{0}",
  "supportedLocales": ["de-DE", "en-US"],
  "url": "http://www.traser-software.de/",
  "dependencies": [
    {
      "name": "TRASER DMS Business Central",
      "publisher": "TRASER Software GmbH",
      "version": "1.19.9.0",
      "appId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "15.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    },
    {
      "appId": "dd0be2ea-f733-4d65-bb34-a28f4624fb14",
      "publisher": "Microsoft",
      "name": "Library Assert",
      "version": "15.0.0.0"
    },
    {
      "appId": "e7320ebb-08b3-4406-b1ec-b4927d3e280b",
      "publisher": "Microsoft",
      "name": "Any",
      "version": "15.0.0.0"
    },
    {
      "appId": "9856ae4f-d1a7-46ef-89bb-6ef056398228",
      "publisher": "Microsoft",
      "name": "System Application Test Library",
      "version": "15.0.0.0"
    },
    {
      "appId": "5d86850b-0d76-4eca-bd7b-951ad998e997",
      "publisher": "Microsoft",
       "name": "Tests-TestLibraries",
       "version": "15.0.0.0"
    },    
    {
      "appId": "23de40a6-dfe8-4f80-80db-d70f83ce8caf",
      "publisher": "Microsoft",
       "name": "Test Runner",
       "version": "15.0.0.0"
    }       
  ],
  "screenshots": [],
  "platform": "15.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://Test.com/help/",
  "showMyCode": true,
  "runtime": "4.0",
  "target": "OnPrem"
}

Thanks you in advance.

**Comment by freddydk** [comment]
It would help if you would include information about how you got this number.

Like: If I run this script:
```
$imageName = "bcinsider.azurecr.io/bcsandbox:de-ltsc2019"
$auth = "NavUserPassword"
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "C:\temp\build.flf"
$containerName = "bcde"

New-BCContainer -accept_eula `
                -imageName $imageName `
                -containerName "bcde" `
                -licenseFile $licenseFile `
                -auth $auth `
                -Credential $credential `
                -updateHosts `
                -doNotCheckHealth `
                -includeTestToolkit
```
and open the test toolkit page and select all tests, I get:
![image](https://user-images.githubusercontent.com/10775043/67652940-8fad3c00-f947-11e9-92d2-ecd050638223.png)

Which clearly is more than 3219 tests.

**Comment by VladimirVeljovic** [comment]
Hi Freddy
i just changed your link to $imageName = "mcr.microsoft.com/businesscentral/sandbox:de" and it worked like a charm with all test codeunits include. I think my problem is in another script when choosing image, it created container out of mcr.microsoft.com/dynamicsnav:generic-1903 which is wrong and doesnt include all the tests.

I can close this issue and thank you again

**Comment by freddydk** [comment]
This is why it is so important for me to get the full commands used and the output.
What you probably see here is, that when you use -useBestContainerOS (replatforming containers) something happened.
Since some apps are there, I almost assume that the cache containing files from images has errors (or maybe part filled from disk full).
You could try to use Flush-ContainerHelperCache to flush all caches and start again.

**Comment by freddydk** [comment]
Had a quick look - when using -useBestContainerOS with local sandbox containers, the folder with the local tests isn't transferred to the new container - this is probably what you see here.
Will fix this for the next generic image.

**Comment by VladimirVeljovic** [comment]
I have deleted -useBestContainerOS ` and changed -isolation from "Process" to "hyperv" and then it worked with no errors like in first post. all tests are included

Tnx Freddy U R D Legend! :)

**Comment by freddydk** [comment]
Next version of the generic image will fix this so that also -useBestContainerOS will get local applications folders transferred.

**Comment by freddydk** [comment]
Generic image 0.0.9.96 was shipped today, this should fix the issue
