### ISSUE TITLE
How to setup Traefik on host that is not exposed to internet

### ISSUE THREAD

**Issue by ernestasjuska** [microsoft/navcontainerhelper#699]
Hi,

I am trying to setup Traefik on test server that is not exposed to internet (so it cannot complete ACME challenge). Our company has wildcard TLS certificate that should apply to all computers within the domain.

I'm not sure how to change template_traefik.toml file so traefik would instead use company's certificate.

I looked at https://docs.traefik.io/https/tls/ which suggests to use *.crt and *.key file pair (not sure how to get them yet). Maybe Setup-TraefikContainerForBCContainers cmdlet could also have parameter to provide certificate files, or at least have additionalParameters like New-BCContainer?

But anyway this will be a test environment with many BC containers, I could do even with self-signed certificate.

**UPDATE** I realized that Setup-TraefikContainerForBCContainers can also take certificate files as parameters. :) Now what remains is to figure out how to change toml file.

Thanks.

**Comment by tfenster** [comment]
@ernestasjuska if you can live with self-signed, then you actually don't need to do anything. Traefik will generate a self-signed cert if the ACME challenge fails. The usage of your own certs is roughly described here, almost at the end: https://www.axians-infoma.com/techblog/traefik-support-for-navcontainerhelper-the-nav-arm-templates-for-azure-vms-and-local-environments/

**Comment by ernestasjuska** [comment]
Somehow missed your article when I was searching. Thanks.
I managed to make it work using company's certificate. Browser accepts the certificate.


I get this error occasionally (I set up gMSA and Windows auth, not sure if this is related).
![image](https://user-images.githubusercontent.com/53167314/67855995-45c97f00-fb1c-11e9-87a1-565076fc5d55.png)
And it is impossible to connect from Microsoft Edge, browser keeps asking for credentials. Firefox works.

Also container event log has these errors:
 The provided antiforgery token was meant for a different claims-based user than the current user.
 The specified application ID 'FIN' is different from the application the user was authorized: 'NAV'

Docker image: mcr.microsoft.com/businesscentral/sandbox:lt

**Comment by ernestasjuska** [comment]
Turns out that was a configuration issue. :)

SPN were added to host computer, but not gMSA service account. So our host had SPN but only when not using full name with domain. Something like that anyway.

With that this got fixed as well:

> And it is impossible to connect from Microsoft Edge, browser keeps asking for credentials. Firefox works.

Thanks.
