### ISSUE TITLE
remapping containerports

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#70]
I've been looking into remapping navision container ports to make a Navison 2017 CU-9 container accessible from a local network. This seems to work when adding -p hostport:containerport to
New-NavContainer -AdditionalParameters
I have some general questions about these exposed navsion ports. I see exposed ports:
80, 8080, 443, 1433, 7045-7049.
I'm able to remap ports 80 and 7045-7049
Port 8080, 443 and 1433 can be remapped, but don't seem to work
what's Port 8080 and 1433 used for or has this no particular function in NAV 2017 (like port 7049)
I expected that Port 443 should work in the standard installation, because this can be usefull when connecting the Microsoft Navsion App (from the Microsoft Store). But it doesn't. Is this intensional or a mistake on my part.

**Comment by freddydk** [comment]
1433 is SQL
8080 is the fileshare (certificate, .vsix file)
If you remap 443 you also need to set the publicwebclientport parameter as additionalparameter (I think)

**Comment by mheijkant** [comment]
Thanks,
simply overlooked that 1433 is sql.
Can you confirm that for instance on a standard nav container installation "https:/<myserver>/nav/webclient/" from the host, should work. because on my installation it doesn't.

**Comment by freddydk** [comment]
Well you need the container name in there.

https://containername/nav/webclient

usually works - if not it is typically due to dns resolution.
try to add -updateHosts to new-navcontainer, then your containers name is added to the hosts file.

**Comment by mheijkant** [comment]
I tried both suggestion but that won't solve this.
For now i will be waiting for Microsoft to release Generic Tag: 0.0.4.4, because creating a default Navision Container on my machine won't work for me because of a language isue #60

**Comment by freddydk** [comment]
Generic image 0.0.4.4 has been released yesterday
All specific images are being rebuilt on 0.0.4.4 today/tomorrow
