### ISSUE TITLE
Error New-NAVContainer

### ISSUE THREAD

**Issue by jiwanovski87** [Microsoft/navcontainerhelper#71]
Hi everyone,

I want to recreate my docker container with New-NavContainer (see https://community.dynamics.com/nav/b/navericwauters/archive/2017/11/08/docker-waldo-updating-my-local-environment) and I have an issue with parameter $navDvdPath. 

Everytime I call New-NavContainer the parameter $navDvdPath has the value "true".
When I change the value of $navDvdPath manually to $null in debugger the script is okay.

This is my example:

`find-module 'navcontainerhelper' | install-module`
`.(Join-Path $PSScriptRoot '_Settings.ps1') -ErrorAction Stop`

`New-NavContainer `
`  -accept_eula $true`
 `  -containerName $DEVServer`
`  -imageName $DockerImage`
`  -licenseFile $LicenseFile`
`  -updateHosts`
`  -auth NavUserPassword`
`  -includeCSide`
`  -alwayspull $true`
`  -Verbose`

**Comment by freddydk** [comment]
-accept_eula is a switch - you should not have $true after that (like updatehosts and includecside).
If you are using the azure vms - the easiest way to recreate your navserver container is to invoke
replace-navservercontainer
