### ISSUE TITLE
New-BCContainer with Traefik fails when PublicDnsName doesn't have a dot

### ISSUE THREAD

**Issue by achim-t** [microsoft/navcontainerhelper#710]
Our PublicDnsName is "lvserver19". NewBCContainer -useTraefik fails with "The length mustn't be less than 0".

https://github.com/microsoft/navcontainerhelper/blob/539f06039283c5dad1fb73e265b64fed7861e261/ContainerHandling/New-NavContainer.ps1#L1151

**Comment by freddydk** [comment]
Should probably be changed to

 $traefikHostname = $publicDnsName.Split('.')[0]

**Comment by freddydk** [comment]
Shipped in 0.6.4.17
