### ISSUE TITLE
Install-BCContainerApp can't be found (0.6.4.16)

### ISSUE THREAD

**Issue by achim-t** [microsoft/navcontainerhelper#711]
Typing "Install-B{Tab}" auto-completes to the correct command, but afterwards the command can't be found.

**Comment by freddydk** [comment]
Right you are... - a typo

**Comment by freddydk** [comment]
Install-BCContainerApp is just an alias for Install-NavContainerApp - same functionality and you can use that until next version.

**Comment by freddydk** [comment]
Shipped in 0.6.4.17
