### ISSUE TITLE
TestTool, number of failed tests

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/navcontainerhelper#713]
We have set all up with clean container and with no extensions installed. So cleanest BC as possible. Then we have run all the test codeunits and we have a lot of failed standard tests:

![2019-10-28 at 17 32 32](https://user-images.githubusercontent.com/53824412/68188451-780a2f00-ffa9-11e9-92ff-176eb2686e0e.jpeg)

What should we expect from running all MS tests, failed 0 or there is something we should be aware of.

Thank you in advance

**Comment by freddydk** [comment]
You should probably raise this issue on Yammer as it isn't really related to Docker nor the containerhelper.
I do know that more tests will fail on sandbox containers than onprem containers - and I know that some integration tests requires special setup in order to work.
