### ISSUE TITLE
AD Windows Account Auth

### ISSUE THREAD

**Issue by jan-machacek** [Microsoft/navcontainerhelper#72]
Hi,
I have problem with run client (web, RTC) when use external SQL server and Windows auth.
(Win Server 2016)

I run next script in PS with navcontainerhelper module installed (last version).

```
New-NavContainer -accept_eula `
                 -containerName NAV2016_DOCK_CU26_W1 `
                 -imageName "microsoft/dynamics-nav:2016-cu26" `
                 -licenseFile "C:\license.flf" `
                 -updateHosts `
                 -auth 'Windows' `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -databaseServer di-nt12 `
                 -databaseInstance sql2014 `
                 -databaseName NAV2016_DOCK_CU26_W1
```

When I run this, I enter my user name (without domain - I found somewhere this information) and password. After that i have created my NAV container and I can run C/SIDE Development Environment with my domain account.

But when I want run web/RTC client I get error (The program could not create a connection to the server.). When I looking for mistake, I found in event log that it want to run client with local windows account "containername"\machacekj instead of my domain account CDL\machacekj.

Is there any parameter/script/option which make it running with AD windows account?

Thank you
JM

**Comment by kine** [comment]
Because the container "machine" is not within domain, you will need to use gMSA (https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/manage-serviceaccounts). The trick with windows authentication in case when DB is inside container works, because it will use local user account with same name and password. But it is not working when the container connects to something outside...

**Comment by jan-machacek** [comment]
Thank you for your response. 
I'll try create gMSA account and run it again under this account, it make it sense.

JM

**Comment by freddydk** [comment]
You can run Windows Auth without gMSA, this might be another problem.
If you are using IE, then you shouldn't use underscores in the hostnames.
Underscores are not allowed in DNS names and IE saves cookies wrongly when they are used in hostnames.

**Comment by freddydk** [comment]
Did you manage to make this work?
