### ISSUE TITLE
Export-NAVEncryptionKey Error in BC15 CU1

### ISSUE THREAD

**Issue by git-no** [microsoft/navcontainerhelper#723]
```powershell
Export-NAVEncryptionKey -ServerInstance BC -KeyPath "C:\Keys\nav.key"
```
does not work and breaks with error, something like "An encryption key is required to complete the request".

Original error message in german language:
```powershell
Zum Fertigstellen der Anforderung ist ein Verschlüsselungsschlüssel erforderlich.
```

Command did work in BC14 CU 6.  
Seems to me the secret key is not added/imported before.

navcontainerhelper command used:

```powershell
  New-NavContainer -imageName "mcr.microsoft.com/businesscentral/onprem:15.1.37793.0" `
  -containerName BC15 `
  -auth NavUserPassword `
  -updateHosts `
  -accept_eula -accept_outdated -useBestContainerOS `
```

**Comment by freddydk** [comment]
I think the encryption key is only created when using a foreign database (not with localhost).
When you say it works with BC14 CU6 - is that then the exact same new-navcontainer statement (with 14.x) - or do you have other parameters?

**Comment by freddydk** [comment]
Just did a test. Running this:
```
$credential = New-Object PSCredential -ArgumentList 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
New-NavContainer -imageName "mcr.microsoft.com/businesscentral/onprem:1904" `
  -containerName BC15 `
  -auth NavUserPassword `
  -Credential $credential `
  -updateHosts `
  -accept_eula `
  -accept_outdated

Invoke-ScriptInNavContainer -containerName BC15 -scriptblock {
    Export-NAVEncryptionKey -ServerInstance $serverinstance -KeyPath "C:\run\my\nav.key"
}
```
Fails with 1904 (14.x) and 1910 (15.x) as expected.
No encryptionkey is created in the container unless you specify a database connection or in other way create an encryption key.
