### ISSUE TITLE
Status Code 422 : Unprocessable Entity

### ISSUE THREAD

**Issue by georgii01** [microsoft/navcontainerhelper#724]
I use "Releases" functionality in DevOps.
I want to deploy an application on test servers. When I start Publish-NavContainerApp from the Pipeleine, I get the error "Status code 422: Unprocessable Entity".
If I got the error, I can no longer install / update the application. I have to install the application with the -syncMode Clean option

If I run the script from my local PC, I have no problem.
Traefic is installed on the servers and for deployment I use the DevEndpoint option.

Based on this description, something wrong with the request.
A 422 status code occurs when a request is well-formed, however, due to semantic errors it is unable to be processed

_Invoke-Command -Session $session  -ScriptBlock { 
                                    Param($appFile, $containerName, [PSCredential] $credential)
                                        Publish-NavContainerApp -containerName $containerName -appFile $appFile -skipVerification -useDevEndpoint -credential $credential
                                    } -ArgumentList (Join-Path $destFolder $appFileName), $_, $credentialUser 

Publishing _Tests App 01_1.0.0.0.app to http://172.21.10.54:7049/BC/dev/apps?SchemaUpdateMode=synchronize&tenant=default
2019-11-06T11:02:35.8636389Z Status Code 422 : Unprocessable Entity
2019-11-06T11:02:35.8636864Z At D:\a\_temp\ff1f1a5b-2d61-4bf9-a78b-80746ca6beeb.ps1:46 char:9
2019-11-06T11:02:35.8637432Z +         Invoke-Command -Session $session  -ScriptBlock {
2019-11-06T11:02:35.8637521Z +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-11-06T11:02:35.8637663Z     + CategoryInfo          : OperationStopped: (Status Code 422 : Unprocessable Entity:String) [], RuntimeException
2019-11-06T11:02:35.8637705Z     + FullyQualifiedErrorId : Status Code 422 : Unprocessable Entity
2019-11-06T11:02:35.8637740Z  
2019-11-06T11:02:36.0281941Z ##[error]PowerShell exited with code '1'.

**Comment by freddydk** [comment]
If you could give me a reproducable scenario, that would save me a great amount of time.
If I create the container, I might not use the same parameters and thus might not see the problem and end up spending days in reproing something that might be because the container doesn't have enough memory (yes, I tried exactly this).
So please add a full script, which shows the error on your machine.
Thanks

**Comment by georgii01** [comment]
Thanks Freddy for the quick reply.
Is it ok for you if I create a test environment (exactly the same as mine), reproduce the error and provide you the psh script and access to this environment?

**Comment by freddydk** [comment]
That would be awesome

**Comment by georgii01** [comment]
Ok. I'll let you know when I'm ready.

**Comment by freddydk** [comment]
You can email freddyk at microsoft dot com.

**Comment by epernst** [comment]
We were getting the same error with our build. But when we checked the app after the error, then it had actually published the extension correctly.
But it required that we we ran the app upgrade, before we were able to install it correctly. So we encapsulated the call to Publish-NavContainerApp in a try-catch, and ran data upgrade and manual install if it failed.
Maybe the same with you?

**Comment by freddydk** [comment]
Thanks Erik

couldn't you just pubish (without -install), run data upgrade and then install

**Comment by epernst** [comment]
Tried with and without sync/install, but the only thing I got working was putting it into a try/catch and a check of the status code 422, before upgrade and install.

**Comment by freddydk** [comment]
Assuming that this blog post describes the reason for this error:
https://freddysblog.com/2019/12/09/having-demo-data-while-developing-business-central-apps-with-docker/
we now found a few more reasons for unprocessible entity:-)
