### ISSUE TITLE
Where to enable EXPERIMENTAL future on VM on Azure

### ISSUE THREAD

**Issue by BozidarP** [microsoft/navcontainerhelper#725]
![think about this](https://user-images.githubusercontent.com/44054400/68398342-dc2d1e80-0174-11ea-8678-0641076079ba.PNG)
Hello, 
How to enable EXPERIMENTAL future  (I need to install traefik) on Azure Windows Server 2016 with containers server.
Cannot find config file, I want to add
![image](https://user-images.githubusercontent.com/44054400/68398985-f3b8d700-0175-11ea-9b04-1c88a0b5e375.png)

Thanks in advance

**Comment by staedter** [comment]
You can configure the docker daemon on Windows Server via a configuration file located in  'C:\ProgramData\Docker\config\daemon.json'. If the file does not exist you have to create it yourself.

This is documented here:  https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#configure-docker-with-a-configuration-file
However the "experimental" flag seems not to be included in the Microsoft Docs. 

But I just tried it on one of our hosts and at least the Service started without problems after I added 

> "experimental": true,

 to the config. So I guess that although undocumented it nonetheless is supported on Windows Server.

Good Luck.

**Comment by freddydk** [comment]
Why would you need experimental for running traefik?
http://aka.ms/getbc sets up traefik without (I think)

**Comment by BozidarP** [comment]
When I try to pull traefik:
![image](https://user-images.githubusercontent.com/44054400/68507605-a0758000-026c-11ea-90c1-28afbd706760.png)
Same issue with my NoteBook where is windows 10, I change to experimental, and working fine, can pull.

On Azure VM, cannot change to Experimental = true, or you can suggest another way :)

**Comment by freddydk** [comment]
@staedter already described how to enable experimental - but not sure that is what you want?

Maybe you should explain what you are trying to achieve?

Also, I asked how you created the Azure VM?

http://aka.ms/getbc will create a VM, and setup traefik automatically.
The code for doing this is here: https://github.com/microsoft/nav-arm-templates/blob/master/initialize.ps1

It uses this navcontainerhelper cmdlet: https://github.com/microsoft/navcontainerhelper/blob/master/ContainerHandling/Setup-TraefikContainerForNavContainers.ps1

and it doesn't use experimental - it just works.

**Comment by NAVspecialist** [comment]
It the problem not that this Windows 10 versions is VERY old???

**Comment by freddydk** [comment]
@NAVspecialist - the azureVM is running Windows Server and thus docker enterprise instead of docker desktop.
@staedter has described how to enable Experimental.
Also, we are using stefanscherer/traefik-windows:v1.7.12 image in the setup-traefik (created by @tfenster) not the library/traefik image.
