### ISSUE TITLE
Container name contains invalid characters.

### ISSUE THREAD

**Issue by bkdjayh** [microsoft/navcontainerhelper#727]
In the HelloWorld build scripts, Read-Settings.ps1 uses the agent name to create a container name. When using a Microsoft hosted build agent, for example with this setting in CI.yml
```
    pool:
      vmImage: 'windows-2019'
```
The agent name has a space in it, resulting in a container name of Hosted Agent-build
```
Set appFolders = app
Set testFolders = test
Set imageName = mcr.microsoft.com/businesscentral/sandbox:15.0.36590.0-us
Set alwaysPull = False
Set reuseContainer = True
Set containerName = Hosted Agent-build
Async Command Start: Update Build Number
Update build number to 15.0.11.0 for build 763
Async Command End: Update Build Number
Finishing: Reading Settings
```
The space causes Create-Container.ps1 to fail
```
Create Hosted Agent-build from mcr.microsoft.com/businesscentral/sandbox:15.0.36590.0-us
WARNING: Container name should not exceed 15 characters
##[error]Container name contains invalid characters. Allowed characters are letters (a-z), numbers (0-9) and dashes (-)
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.17\HelperFunctions.ps1:179 char:13
+             throw "Container name contains invalid characters. Allowe ...

+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : OperationStopped: (Container name ... and dashes (-):String) [], RuntimeException

    + FullyQualifiedErrorId : Container name contains invalid characters. Allowed characters are letters (a-z), number 

   s (0-9) and dashes (-)
##[error]PowerShell exited with code '1'.

```

**Comment by freddydk** [comment]
Have changed the line in read-settings.ps1 to
`$containerName = "$($ENV:AGENT_NAME.Replace(' ',''))-$containerName"
`
You can still have special characters in the agentname - then you would need to modify this further.
Please also note that using the hosted agents might not work as it takes a long time to download the images.

**Comment by bkdjayh** [comment]
That works.
A simple extension with no tests has been taking 20-30 minutes to complete, which fits under the 60 minute time limit for hosted agents.

I do see the warning Container name should not exceed 15 characters, but that didn't fail the build, and I should be able to work around that by specifying a really short conatinerName in settings.json

Thanks.

**Comment by freddydk** [comment]
It is only a warning, you should have no problem.
