### ISSUE TITLE
Add CommonDesktop as valid option for $shortcuts

### ISSUE THREAD

**Issue by JeroenHems** [microsoft/navcontainerhelper#728]
I've developed a training lab environment based on an ARM template, that gets finalized using a Powershell Script Extension. When deploying the NAV container, the profile for the trainee doesn't exist apparently as the finished VM has the container running, but shortcuts don't exist yet.

This can probably easily be solved by adding CommonDesktop to the ValidateSet in New-NavContainer.

**Comment by freddydk** [comment]
Shipped in 0.6.4.18

**Comment by JeroenHems** [comment]
Thanks!
