### ISSUE TITLE
run traefik container with isolation=process

### ISSUE THREAD

**Issue by marknitek** [microsoft/navcontainerhelper#729]
I have the problem described here: https://github.com/StefanScherer/dockerfiles-windows/issues/383 on Windows 10.

docker logs on traefik container:
**Failed to retrieve information of the docker client and server host: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: message readmode pipes not supported In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.**

According to this issue, running the traefik contaienr with proceses isolation should fix the problem.
Can we change the `Setup-TraefikContainerForNavContainers.ps1` to use `--isolation=process`?

Edit: I tested it and can confirm that --isolation=process solves the issue

@freddydk i did not make a PR because i don't know if you would prever to make a switch or use the same logic of new-navcontainer to determine if process isolation is possible.

**Comment by freddydk** [comment]
Shipped in 0.6.4.18
