### ISSUE TITLE
Language/Region related issue with navison image Tag 0.0.4.4

### ISSUE THREAD

**Issue by mheijkant** [Microsoft/navcontainerhelper#73]
Still have a Language/Region issue related to #60 with navison image Tag 0.0.4.4.
Issue #60 is resolved now, but running a standard command like
"docker run -e accept_eula=Y microsoft/dynamics-nav:2017-cu9" still gives me 
Exception calling "AddAccessRule" with "1" argument(s): "Some or all identity references could not be translated."

On issue #60 I could add parameter -myscripts @("c:\temp\setupwebclient.ps1") to command New-NavContainer, to overwrite the default script.
How can I do this according with #60, with the default docker command I mentioned, to check if there is still an issue there.

This issue is important to me, because I would like to know is there's a website running on port 443 in a default created container, because on my New-NavContainer created container only the website on port 80 but not on port 443 is running. So I would like to know if there's also a https website inside the navison container running by default.

[inspect.txt](https://github.com/Microsoft/navcontainerhelper/files/1611071/inspect.txt)
[logs.txt](https://github.com/Microsoft/navcontainerhelper/files/1611072/logs.txt)

**Comment by freddydk** [comment]
you override scripts with docker run by putting the files in a folder (ex. c:\myfolder) and add this parameter:
-v c:\myfolder:c:\run\my
Very strange that the error is still there. I have just double-checked that the bug fix we tested on your machine actually is included....
$objSID = New-Object System.Security.Principal.SecurityIdentifier("S-1-1-0")
$user = $objSID.Translate( [System.Security.Principal.NTAccount])
Maybe we have to have another session.
You did remember to do docker pull microsoft/dynamics-nav:2017-cu9 right?

**Comment by mheijkant** [comment]
Running the default script now works. I really have no clue why this works now.
Any how, I can see now that theres a https://.. WebClient/ instead of a http.
I can continue now with further looking into remappping ports.
Please consider this issue clossed.

**Comment by freddydk** [comment]
https is default when using navuserpassword auth
http is default when using Windows Auth
-e usessl=N will force http (or -usessl:$false in navcontainerhelper)
