### ISSUE TITLE
Create-AlProjectFolderFromBcContainer Parameter set cannot be resolved using the specified named parameters

### ISSUE THREAD

**Issue by MBK75** [microsoft/navcontainerhelper#737]
Hi Freddy, I am trying to export the al files from a version 15.0.36590.0-us image, and I am receiving an error.  I am using navcontainerhelper 0.6.4.18 (I uninstalled what I had installed and did a fresh install but run into the same error).

Command: 
`Create-AlProjectFolderFromBcContainer -alProjectFolder "D:\Base NAV Code\15.0.36590.0\" -containerName TaxJar -useBaseLine -userBaseAppProperties`

The error returned is:
`Create-AlProjectFolderFromNavContainer : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
Create-AlProjectFolderFromBcContainer -alProjectFolder "D:\Test\Base  ...
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CategoryInfo          : InvalidArgument: (:) [Create-AlProjectFolderFromNavContainer], ParameterBindingException
FullyQualifiedErrorId : AmbiguousParameterSet,Create-AlProjectFolderFromNavContainer`

**Comment by freddydk** [comment]
remove the wrong r in -useBaseAppProperties

**Comment by MBK75** [comment]
Hi Freddy, my apologies... long morning!  Gross oversight on my part
