### ISSUE TITLE
Question: Activating Premium Plan 

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/navcontainerhelper#738]
Is there a way to activate the Premium experience of a container? AFAIK the flag `-assignPremiumPlan` for `new-navcontainer` or `new-navcontainernavuser` only assigns the ability to switch experience to Premium. To actually do switch the experience in the client one user has to log in and do the switch (-> Page Company Information). 

Am I missing something? And what? :-)

**Comment by freddydk** [comment]
I don't know what it takes to switch experience - you could look in the company information page to see what it takes.
Maybe company Information is available as an API and you could do the switch by invoking an API?

**Comment by RafaelKoch** [comment]
Okay, so no magic flag in navcontainerhelper I was simply missing out on :-)

There is a way to do it inside an extension, I do not thing it is exposed as an API. Will do it in some install code of a CI/CD helper extension, then. 

Thanks!
