### ISSUE TITLE
Using container with enableSymbolLoading to publish app in Hybrid mode (C/Side + AL)

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/navcontainerhelper#74]
I am using navcontainerhelper to create new **dynamics-nav:2018-cu1-na** container, then importing and compiling **.txt file with new fields to tables**, and then publishing **app with pageextensions to add new fields to pages**. 

However, I'm not able to publish the app to container since it does not see custom fields in tables that are added in Hybrid mode. I'm getting the error when running Publish-NavContainerApp saying:

````
Extension compilation failed
MyExtension.al(12,41): error AL0118: The name 'Custom Field' does not exist in the current context
````

My PS script looks like this:
````
$image = 'microsoft/dynamics-nav:2018-cu1-na'
$containername = 'demo-cu1-na'

New-NavContainer -accept_eula `
                 -containerName $containername `
                 -imageName $image `
                 -updateHosts `
                 -Credential $cred  `
                 -doNotExportObjectsToText `
                 -enableSymbolLoading `
                 -licenseFile "c:\myfolder\mylicense.flf"  `
                 -memoryLimit 3G  `
                 -auth Windows

Import-ObjectsToNavContainer -containerName $containername -objectsFile 'myObjects.txt'
Compile-ObjectsInNavContainer -containerName $containername -filter 'Compiled=No'

Publish-NavContainerApp -containerName $containername -appFile $appfile –SkipVerification 
````
Script breaks at Publish-NavContainerApp with . Seems like symbols should've been updated during Compile-ObjectsInNavContainer for the app to see them. 

Tried also with Restarting service tier within container but without result - same error even after restart. 

I am using external myObjects.txt file as well as app extension file with goal to add to this new container. Any ideas why Publish-NavContainerApp is not working in this scenario?

**Comment by richardrobberse** [comment]
When creating a container the symbols of standard NAV are present, however the symbols of the imported objects are not present.
I think you should generate the symbols by using finsql.exe with command=generatesymbolreference and then download the symbols in VS Code.

**Comment by freddydk** [comment]
In docker images with generic tag 0.0.5.2 or later, the symbols have been generated correctly during build.
and if you specify enableSymbolLoading, you can now do dual development.
Compile-ObjectsInNavContainer will generate symbols for the objects you compile.
Same if you compile in CSIde
[E2E - Get your solution up running on Docker.docx](https://github.com/Microsoft/navcontainerhelper/files/1785717/E2E.-.Get.your.solution.up.running.on.Docker.docx)
The attached document describes an end 2 end experience of doing dual development. This will become a whitepaper when it is done. Comments are welcome.
