### ISSUE TITLE
Issue with License file when Installing run time package on prem

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#741]
HI,
We have our app in app store. We created runtime package and I was able to install it successfully on-prem when we have standard license. how ever when we use our license, its erroring out. Please find the error message and license file attached
![image](https://user-images.githubusercontent.com/38437776/68777141-11f35c80-05e6-11ea-9bcc-e5b7a8aa74d7.png)
![image](https://user-images.githubusercontent.com/38437776/68777158-16b81080-05e6-11ea-9f9b-5bd1073bf670.png)
Can you please help!!

**Comment by freddydk** [comment]
I am not a licensing expert and this is likely not related to docker at all, but...
product version 13 - shoudln't that be 14 or 15?

**Comment by Bssivivek** [comment]
The screen shot is just an example to show what module we have access. but we did import license file for V14/V15.

**Comment by freddydk** [comment]
You should post the question on Yammer or create a support case - I don't think this has anything to do with Docker/ContainerHelper. That codeunit id seems to be missing in the license (which I again have absolutely no idea about).

**Comment by Bssivivek** [comment]
Sorry about that. Posted the same question in yammer. thanks!!
