### ISSUE TITLE
W10 1909

### ISSUE THREAD

**Issue by larswestman** [microsoft/navcontainerhelper#744]
Windows 1909 are supposed to be able to "run down-level containers on up-level for process (Argon) isolation". When i create a container after upgrading to 1909 I still get hyper-v isolation if i don't use useBestContainerOS. Is that because navcontainerhelper enforces that? Should this be changed if that's the case?

**Comment by freddydk** [comment]
It is because containerhelper enforces that.
But you can override it by specifying -isolation process
but... - unfortunately it doesn't work - I don't know if that is what they mean by that statement, but I have asked the people on our internal teams channel.

**Comment by freddydk** [comment]
Tried this on 1909:

```
docker run --isolation process mcr.microsoft.com/windows/servercore:ltsc2019 cmd
```

gives the same error as when trying to run a BC Container with process isolation on 1909.
As soon as this works, I will look into how this can be brought to work with the containerhelper.

**Comment by freddydk** [comment]
It actually works with 1903 - but since we are also not building 1903 images, that doesn't really help.
