### ISSUE TITLE
TestToolKit import only includes 2 of the 5 Apps

### ISSUE THREAD

**Issue by syssolmarketing** [microsoft/navcontainerhelper#745]
We are running into an issue when importing the TestToolKit to test our apps for BC15.  We read here, https://freddysblog.com/2019/08/30/running-tests-in-15-x-insider-containers/ that there should be 5 apps that are imported. We are only seeing two. Any help would be appreciated. Thanks!
![Test Tool Kit Issue](https://user-images.githubusercontent.com/54630609/68951493-31c48500-078c-11ea-9517-0bfb77651af9.png)

**Comment by freddydk** [comment]
This is because some of the test apps are missing in the latest insider builds.
@atoader is on it.

**Comment by syssolmarketing** [comment]
Thank you Freddy and @atoader We are not using an insider build (That I know of) we are using BC Docker Image: mcr.microsoft.com/businesscentral/sandbox:us

**Comment by freddydk** [comment]
Ok, that one should contain all.
Just tried the latest sandbox using this script:
```
$credential = New-Object PSCredential -ArgumentList 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$containerName = "test"
$licensefile = "c:\temp\license.flf"
New-BCContainer `
    -accept_eula `
    -imageName mcr.microsoft.com/businesscentral/sandbox:us `
    -alwaysPull `
    -containerName $containerName `
    -auth UserPassword `
    -Credential $credential `
    -updateHosts `
    -licenseFile $licensefile `
    -includeTestToolkit -includeTestLibrariesOnly
```

Seems to work just fine.

You will need to provide the commands you use and the full output of all commands (and in a better quality than the screen shot provided) if we should see what's wrong.
Also - running Flush-ContainerHelperCache removes caches - maybe one of these have been partially populated.

**Comment by syssolmarketing** [comment]
Thanks for the help Freddy. Running the flush command ended up fixing it.
