### ISSUE TITLE
Error in creating business central container

### ISSUE THREAD

**Issue by zeeahmed-16** [microsoft/navcontainerhelper#746]
I am trying to create a business central sandbox container using this command:

**new-navcontainer -accept_eula -updatehosts -container 'bcsandbox' -image 'microsoft/bcsandbox' -usebestcontaineros**

Getting following output with error:

NavContainerHelper is version 0.6.4.18
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Using image microsoft/bcsandbox:latest-ltsc2016
Creating Container bcsandbox
Version: 14.0.29537.31808-W1
Style: sandbox
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.14393.970 (ltsc2016)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\bcsandbox\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container bcsandbox from image microsoft/bcsandbox:latest-ltsc2016
781b89909f455d16fc01097e052256b4d7fe41205a49b4bb5cc544d1333b700c
Waiting for container bcsandbox to be ready
Initializing...
Setting host.containerhelper.internal to 172.28.160.1 in container hosts file
Starting Container
Hostname is
PublicDnsName is bcsandbox
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 54
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.containerhelper.internal to 172.28.160.1 in container hosts file
Starting Container
Hostname is
PublicDnsName is bcsandbox
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 54
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bcsandbox failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.18\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...csandbox failed:String) [], RuntimeException

I have the following image:
![image](https://user-images.githubusercontent.com/57131756/69012958-d3babc00-099c-11ea-8043-a479d9638af6.png)

**Comment by freddydk** [comment]
Two blog posts you should read:
https://freddysblog.com/2019/07/26/you-are-running-a-container-which-is-xx-days-old/
https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/

**Comment by zeeahmed-16** [comment]
Thanks Freddy for the reply. Before pulling the latest image from mcr, I used -accept_outdated  

new-navcontainer -accept_eula -updatehosts -accept_outdated -container 'bcsandbox' -image 'microsoft/bcsandbox' -usebestcontaineros

**Comment by zeeahmed-16** [comment]
Thanks Freddy for the reply. I used -accept_outdated in my command:

new-navcontainer -accept_eula -updatehosts -accept_outdated -container 'bcsandbox' -image 'microsoft/bcsandbox' -usebestcontaineros

Now I have this output:

NavContainerHelper is version 0.6.4.18
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Using image microsoft/bcsandbox:latest-ltsc2016
Removing container bcsandbox
Removing bcsandbox from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\bcsandbox
Creating Container bcsandbox
Version: 14.0.29537.31808-W1
Style: sandbox
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.14393.970 (ltsc2016)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\bcsandbox\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container bcsandbox from image microsoft/bcsandbox:latest-ltsc2016
013c91706e84c65f99b7b023c76607d27096d25887240defe4303c4e8bec0069
Waiting for container bcsandbox to be ready
Initializing...
Setting host.containerhelper.internal to 172.28.160.1 in container hosts file
Starting Container
Hostname is
PublicDnsName is bcsandbox
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Creating http download site
Creating Windows user Zeeshan
Setting SA Password and enabling SA
WARNING: This license is not compatible with this version of Business Central.
Creating SUPER user
WARNING: This license is not compatible with this version of Business Central.
WARNING: This license is not compatible with this version of Business Central.
Container IP Address: 172.28.171.55
Container Hostname  :
Container Dns Name  : bcsandbox
Web Client          : http://bcsandbox/NAV/
Dev. Server         : http://bcsandbox
Dev. ServerInstance : NAV
Setting bcsandbox to 172.28.171.55 in host hosts file

Files:
http://bcsandbox:8080/al-3.0.106655.vsix

WARNING: You are running a container which is 206 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 106 seconds
Ready for connections!
Reading CustomSettings.config from bcsandbox
Creating Desktop Shortcuts for bcsandbox
Container bcsandbox successfully created

When I am trying to open 'bcsandbox Web Client' that is created on my Desktop I am getting this error:

![image](https://user-images.githubusercontent.com/57131756/69013401-28f8cc80-09a1-11ea-99eb-5920d1bb599b.png)

Is it because any of the warnings during the container creation. What should I do.

**Comment by freddydk** [comment]
No, that should work.
The sandbox image you are running is very very old - but should work.
What is the address in the browser? what browser do you use?
You can get the event log using get-navcontainereventlog - to see if anything can explain this?

**Comment by zeeahmed-16** [comment]
The link in the browser is: http://bcsandbox/NAV/
I am trying to open this in both Chrome and IE browser. IE is giving this message:

This page can't be displayed
•Make sure the web address http://bcsandbox is correct.
•Look for the page with your search engine.
•Refresh the page in a few minutes.

I have checked the log using get-navcontainereventlog and there are multiple warning I can see that generated during the container creation. Almost all warnings start with this message:

**The description for Event ID 202 from source MicrosoftDynamicsNavServer$NAV cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.**

**Comment by freddydk** [comment]
in a cmd prompt - what does:
ping bcsandbox
say?

**Comment by zeeahmed-16** [comment]
Here it is:
PS C:\Windows\system32> ping bcsandbox

Pinging bcsandbox [172.28.171.55] with 32 bytes of data:
Reply from 172.28.171.55: bytes=32 time<1ms TTL=128
Reply from 172.28.171.55: bytes=32 time<1ms TTL=128
Reply from 172.28.171.55: bytes=32 time<1ms TTL=128
Reply from 172.28.171.55: bytes=32 time<1ms TTL=128

Ping statistics for 172.28.171.55:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms

**Comment by freddydk** [comment]
You are using Windows Auth - did you enter your windows credentials when new-navcontainer asked for it - or did you use other credentials?
You could try -auth UserPassword to switch to username password auth.

**Comment by zeeahmed-16** [comment]
New-NavContainer did ask the credentials and I provided my windows user credentials that have administrator rights.

**Comment by freddydk** [comment]
Windows Authentication requires you to be on the network where your AD server is.
https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/

You should try username password auth.

**Comment by freddydk** [comment]
Closing the issue as I haven't heard any more.
