### ISSUE TITLE
Unable to create container bcinsider.azurecr.io/bcsandbox-master

### ISSUE THREAD

**Issue by AndriusAndrulevicius** [microsoft/navcontainerhelper#747]
After latest update creation of container fails with the following error:
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 152
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1

**Comment by freddydk** [comment]
latest update of what? which image? what command? full output?

**Comment by freddydk** [comment]
I guess I can see the image in the title sorry.
I guess this is an issue with the insider master branch, which I assume will get fixed soon.

**Comment by AndriusAndrulevicius** [comment]
Here's the full output:
NavContainerHelper is version 0.6.4.5
Host is Microsoft Windows 10 Pro - Unknown/Insider build
Docker Client Version is 18.09.3
Docker Server Version is 18.09.3
Pulling image bcinsider.azurecr.io/bcsandbox-master:base-ltsc2019
base-ltsc2019: Pulling from bcsandbox-master
Digest: sha256:d4c26d7f509e677aa7bc83d7a13b394946a708929f2c1725107bfebfc568a99c
Using image bcinsider.azurecr.io/bcsandbox-master:base-ltsc2019
Disabling Health Check (always report healthy)
Removing container d365bc-master
Removing d365bc-master from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\d365bc-master
Creating Container d365bc-master
Version: 16.0.10499.0-W1
Style: sandbox
Platform: 15.0.38056.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.18363.476 (Unknown/Insider build)
A better Generic Container OS exists for your host (1903)
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Pulling image mcr.microsoft.com/dynamicsnav:generic-1903
generic-1903: Pulling from dynamicsnav
Digest: sha256:4b67e267736bb0ef383e751e7839775dc68b4a2871a50357716b5f70ee984b0e
Generic Container OS Version: 10.0.18362.418 (1903)
Generic Tag of better generic: 0.0.9.96
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Agent\_work\_temp\DockerLicense
Files in C:\ProgramData\NavContainerHelper\Extensions\d365bc-master\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container d365bc-master from image mcr.microsoft.com/dynamicsnav:generic-1903
00aad1200b3c6d70e549391dacccc389a89f9e980aa6873262f57b5cd286d3fe
Waiting for container d365bc-master to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more abo
ut SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 329 seconds
Installation complete
Initializing...
Starting Container
Hostname is d365bc-master
PublicDnsName is d365bc-master
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6BBE78A6BD0EFFFD2E88067AC580ABB7168E6E1F
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 152
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
WARNING: Waiting for service 'SQL Server (SQLEXPRESS) (MSSQL$SQLEXPRESS)' to 
start...
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more abo
ut SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 329 seconds
Installation complete
Initializing...
Starting Container
Hostname is d365bc-master
PublicDnsName is d365bc-master
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 6BBE78A6BD0EFFFD2E88067AC580ABB7168E6E1F
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 152
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container d365bc-master failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.5\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...c-master failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container d365bc-master failed

**Comment by freddydk** [comment]
You are using Windows 10 1909 with a version of ContainerHelper, which is older than 1909.
I added support for 1909 (finding the right generic image) later than this.
Not sure this fixes the issue - but you should update containerhelper and try again.
Again - this might be a regression in insider master - then it will be fixed in a few days (I cannot test myself as my hotel connection here @ techdays isn't quite fast enough to download a new insider image)

**Comment by Renee0312** [comment]
Hi Freddy,
    I have faced the same issue as well.

    About 2 months ago that I used the below script with navcontainerhelper 0.6.3.4 it was worked fine.
    -------------------------------------------------------------------------------------
    New-BCContainer -accept_eula `
                -imageName "bcinsider.azurecr.io/bcsandbox-master:w1" `
                -containerName "D365BC-V3-W1" `
                -auth Windows `
                -credential $credential `
                -licenseFile "C:\Temp\BC14wISV-KS.flf" `
                -updateHosts
     -------------------------------------------------------------------------------------

    But I would like to run the same script on the same computer today, it shows the "Initialization of container D365BC-V3-W1 failed" in the end.

    So I have uninstall the navcontainerhelper and intall the lastest verion of navcontainerhelper 0.6.4.20 and change my script as below but in the end I got the same issue.   

    ====================================================
    PS C:\Windows\system32> New-BCContainer -accept_eula `
>>                 -alwaysPull `
>>                 -imageName "microsoft/bcsandbox:w1" `
>>                 -containerName "D365BC-V3-W1" `
>>                 -auth Windows `
>>                 -credential $credential `
>>                 -licenseFile "C:\Temp\BC14wISV-KS.flf" `
>>                 -updateHosts
NavContainerHelper is version 0.6.4.20
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 17.06.2-ee-14
Docker Server Version is 17.06.2-ee-14
Pulling image microsoft/bcsandbox:w1-ltsc2016
w1-ltsc2016: Pulling from microsoft/bcsandbox
Using image microsoft/bcsandbox:w1-ltsc2016
Creating Container D365BC-V3-W1
Version: 14.0.29537.31808-W1
Style: sandbox
Platform: 14.0.29530.31705
Generic Tag: 0.0.9.6
Container OS Version: 10.0.14393.2906 (ltsc2016)
Host OS Version: 10.0.14393.3326 (ltsc2016)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Temp\BC14wISV-KS.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\D365BC-V3-W1\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container D365BC-V3-W1 from image microsoft/bcsandbox:w1-ltsc2016
dd597cfec7eab811870188ea40a6cf3fb50b2967de42984b21b083e80b70a80a
Waiting for container D365BC-V3-W1 to be ready
Initializing...
Setting host.containerhelper.internal to 172.20.224.1 in container hosts file
Starting Container
Hostname is
PublicDnsName is D365BC-V3-W1
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 54
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.containerhelper.internal to 172.20.224.1 in container hosts file
Starting Container
Hostname is
PublicDnsName is D365BC-V3-W1
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.
at <ScriptBlock>, C:\Run\navstart.ps1: line 54
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container D365BC-V3-W1 failed
At C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.20\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...BC-V3-W1 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container D365BC-V3-W1 failed

PS C:\Windows\system32>
    =====================================================

**Comment by freddydk** [comment]
Sorry, but that is not the same issue.

This actually tells you that you are running an outdated image from microsoft/bcsandbox and you should set accept_outdated to Y (or with containerhelper add -accept_outdated.

But you should use images from mcr.microsoft.com/ - not microsoft/ (and you might still need -accept_outdated).

https://freddysblog.com/2019/07/26/you-are-running-a-container-which-is-xx-days-old/

**Comment by Renee0312** [comment]
Hi Freddy,
    Sorry about that ^^.

    But how about my new script that I from bcinsider that will be the next major version, but I still got the issue in the end.

       PS C:\Windows\system32> New-BCContainer -accept_eula `
>>                 -alwaysPull `
>>                 -imageName "bcinsider.azurecr.io/bcsandbox-master:w1" `
>>                 -containerName "D365BC-V3-W1" `
>>                 -auth Windows `
>>                 -credential $credential `
>>                 -licenseFile "C:\Temp\BC14wISV-KS.flf" `
>>
NavContainerHelper is version 0.6.4.20
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 17.06.2-ee-14
Docker Server Version is 17.06.2-ee-14
Pulling image bcinsider.azurecr.io/bcsandbox-master:w1-ltsc2016
w1-ltsc2016: Pulling from bcsandbox-master
Digest: sha256:32688c61667fa3d5d98fac2d9b60a569a144b104bfc4da00eb3c784a4d6d8fc6
Status: Image is up to date for bcinsider.azurecr.io/bcsandbox-master:w1-ltsc2016
Using image bcinsider.azurecr.io/bcsandbox-master:w1-ltsc2016
Removing container D365BC-V3-W1
Removing D365BC-V3-W1 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\D365BC-V3-W1
Creating Container D365BC-V3-W1
Version: 16.0.10541.0-w1
Style: sandbox
Platform: 15.0.38209.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.14393.3274 (ltsc2016)
Host OS Version: 10.0.14393.3326 (ltsc2016)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Temp\BC14wISV-KS.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\D365BC-V3-W1\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupWebClient.ps1
Creating container D365BC-V3-W1 from image bcinsider.azurecr.io/bcsandbox-master:w1-ltsc2016
9e3980d0a00f7d76b13a0392e9c2a029d3846b249c303d0f47641e4ccacf1e44
Waiting for container D365BC-V3-W1 to be ready
Initializing...
Starting Container
Hostname is D365BC-V3-W1
PublicDnsName is D365BC-V3-W1
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Your program license has expired.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is D365BC-V3-W1
PublicDnsName is D365BC-V3-W1
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Your program license has expired.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 156
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container D365BC-V3-W1 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.20\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...BC-V3-W1 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container D365BC-V3-W1 failed

**Comment by AndriusAndrulevicius** [comment]
I think you have an issue with your license - it expired

**Comment by freddydk** [comment]
@Renee0312 - I have removed your issues from this issue. Please read the error messages and compare whether you have the same issue. If it isn't 100% the same issue, then please open a new issue.
Else we will loose focus on the original issue.

**Comment by freddydk** [comment]
@AndriusAndrulevicius did you manage to make this work?
