### ISSUE TITLE
Add App Name to the Output File

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/navcontainerhelper#748]
It would be handy, if we could have the Test Tool (ATT) test XML output file show the name of the test app as part of the results.

**Comment by freddydk** [comment]
Agree - will look at this after Tech Days

**Comment by AmandaTest** [comment]
I didn’t see the build version either and that would also help.

**Comment by freddydk** [comment]
I looked at this and it isn't as easy as it might seem.
1. If I change any values, I will break existing CI/CD pipelines which might compare tests etc. - this could be handled with a parameter.
2. and more important - building the test output file I actually do not have information about which extension the codeunit belongs to. Yes, I could probably make a hacky workaround - but I actually think that if you are using run-testsinNavContainer with extension ids - then you could create an xunit output file per extension (with the name and version number of the extension) - you have the information at this time and it would structure your tests run files nicely.

/Freddy

**Comment by AmandaTest** [comment]
OK Freddy,
Thanks for looking into this. I do have each of the app names in the files. The files don’t include the method name, they only have the code unit name.  I am pulling the info into power BI. with multiple failures in each codeunit, it is time consuming to track the error in the file as opposed to seeing them in the AL Test Tool UI page. Each time I run a test against a new app, the previous results are cleared from the UI. Have you got any suggestions for me?

**Comment by freddydk** [comment]
Not sure I understand.
Are you using the Run-TestInNavContainer powershell function?

**Comment by AmandaTest** [comment]
Yes I am. I guess I’m looking for a way to compare the output for each run and track if we caused a regression. I don’t how to do this through the build pipeline.

**Comment by freddydk** [comment]
So you have a lot of failing tests already – and just want to see if additional tests are failing?

**Comment by AmandaTest** [comment]
Yes

**Comment by freddydk** [comment]
couldn't you disable the failing tests with the disabledtests.json functionality?
I guess Azure DevOps would be nicer to look at if failure means failure and success means success?

**Comment by AmandaTest** [comment]
When I ran the MS tests in the Canada Company I had over 4000 failures. I was only able to get 12000 tests out of the 30000 running

**Comment by freddydk** [comment]
Ok
In that case, I guess you could read through the old tests file in PowerShell and for all succeeding tests, check whether it still succeeds.

**Comment by freddydk** [comment]
these lines:
```
$results = [xml](Get-Content -Path $resultsFileName)
$results.SelectNodes('//test') | Where-Object { $_.Result -ne "Pass" }
```
will give you the failing tests.
This script:
```
$resultsFileName = "c:\Programdata\navContainerhelper\results.xml"
$disabledTestsFileName = "c:\ProgramData\NavContainerHelper\DisabledTests.json"
$disabledTests = @()
$results = [xml](Get-Content -Path $resultsFileName)
$results.SelectNodes('//test') | Where-Object { $_.Result -ne "Pass" } | % { $disabledTests += [ordered]@{ "codeunitName" = $_.name.Split(':')[0]; "method" = $_.method } }
$disabledTests | ConvertTo-Json -Depth 99 | Set-Content $disabledTestsFileName
```
will store all failing or skipped tests in a file.

The $disabledTests can be added to run-tests as a parameter: -disabledTests - then these tests will be skipped next time.

**Comment by AmandaTest** [comment]
Very cool. Thanks Freddy! 😀


On Dec 11, 2019, at 3:53 PM, Freddy Kristiansen <notifications@github.com<mailto:notifications@github.com>> wrote:


these lines:

$results = [xml](Get-Content -Path $resultsFileName)
$results.SelectNodes('//test') | Where-Object { $_.Result -ne "Pass" }


will give you the failing tests.
This script:

$resultsFileName = "c:\Programdata\navContainerhelper\results.xml"
$disabledTestsFileName = "c:\ProgramData\NavContainerHelper\DisabledTests.json"
$disabledTests = @()
$results = [xml](Get-Content -Path $resultsFileName)
$results.SelectNodes('//test') | Where-Object { $_.Result -ne "Pass" } | % { $disabledTests += [ordered]@{ "codeunitName" = $_.name.Split(':')[0]; "method" = $_.method } }
$disabledTests | ConvertTo-Json -Depth 99 | Set-Content $disabledTestsFileName


will store all failing or skipped tests in a file.

The $disabledTests can be added to run-tests as a parameter: -disabledTests - then these tests will be skipped next time.
