### ISSUE TITLE
-alwaysPull gets two images

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/navcontainerhelper#749]
Script:
$imageName = 'mcr.microsoft.com/businesscentral/sandbox:us'
$licenseFile = 'C:\Workshop\BC 15 License.flf'
$ContainerName = 'mysandbox' 
$UserName = 'denster' 
$Password = ConvertTo-SecureString 'Navision4ever!' -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ($UserName, $Password)

New-BCContainer `
    -accept_eula `
    -containerName $ContainerName `
    -imageName $imageName `
    -licenseFile $licenseFile `
    -auth NavUserPassword `
    -alwaysPull `
    -updateHosts `
    -Credential $Credential

First, it does:
Pulling image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
and then when that is done, it also does:
Pulling image mcr.microsoft.com/businesscentral/sandbox:us

I did update-module before running New-NavContainer. It does create a good container, but obviously it doesn't need two images. I suppose I could specify ltcs2019 in my script, but I like how it determines the platform itself so I can use the same script on multiple Windows versions

**Comment by TheDenSter** [comment]
Another observation: To recreate the situation for this issue, I had cleaned up all of my images before running new-navcontainer. At some point I got this error:
![image](https://user-images.githubusercontent.com/23434319/69195035-ebeb2200-0ae7-11ea-8963-0704e143ae90.png)
Since I have never gotten an out of disk space error, I looked at the images and got this:
![image](https://user-images.githubusercontent.com/23434319/69195062-01f8e280-0ae8-11ea-83c8-a7af3ca6c77f.png)
It appears that it has downloaded even more images. I have never specified anything like 'update26' so I really don't know where that is coming from. 

It's purging again now, and I'll specify the ltsc2019 tag next to see if that will complete properly, but something's definitely going on there...

**Comment by freddydk** [comment]
Will investigate after techdays - it of course shouldn't download the 2016 image which is never uses.

**Comment by TheDenSter** [comment]
Thanks Freddy, take your time. I did change the script to specify ltsc2019 in the tag and it only pulled that one image, and the container works perfectly.

**Comment by freddydk** [comment]
If you have the full output of the new-navcontainer - then I might be able to see what is going on instead of trying to repro?

**Comment by NAVspecialist** [comment]
I have seen it before.. when I was using -UseBestContainerOS -when I switched back to -Isolation HyperV it stopped happening.

I can see if I can repro it?

**Comment by freddydk** [comment]
UseBestContainerOS will download both the image and the new generic.
In Daniels case - it downloads 2016 (huge image) and never uses it.
Any repro and full output is vey helpful.

**Comment by NAVspecialist** [comment]
I had the same issue when helping Peik this sunday. It downloaded the 4G image but was not used.

We tried to do a docker run like this one and it fetched the 4g OS image and two BC-images

docker run --name test `
           -h test `
           -e accept_eula=Y `
           -m 4G `
           -e clickonce=Y `
           -e usessl=Y `
           -e username="admin" `
           -e password="Passw0rd" `
           -e accept_outdated=Y `
           -e memory=4g `
           -e isolation=process `
           mcr.microsoft.com/businesscentral/onprem:rtm-w1 `
           from mcr.microsoft.com/windows/nanoserver:10.0.17763.437

**Comment by TheDenSter** [comment]
> If you have the full output of the new-navcontainer - then I might be able to see what is going on instead of trying to repro?

Sorry I don't have that one anymore. I did a full purge right after I took the screenshot of the image list and it got rid of 85GB of image data.

**Comment by freddydk** [comment]
@NAVspecialist - what construction is this:
`docker run ... yyy from xxx
`
What does it do?

and 
`-e isolation=process
`
will set an environment variable named isolation to process - it will not enable process isolation.

I have tried running the above scripts on Windows Server 2019 and Windows 10 1909 - I cannot get it to download an image like you describe.
I have also looked through the code and cannot find any way, that it can download a 2016 image.

As long as you only use new-navcontainer - you should be good.

if your script use docker pull manually - then it will collect the 2016 image unless you specify -ltsc2019 - and it might cause what you mention here.

**Comment by TheDenSter** [comment]
I just got rid of all my images, updated navcontainerhelper and ran the script again. Only one image was pulled. Seems like I can't repro it anymore either. 

Here's my entire output:

PS C:\Windows\system32> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

PS C:\Windows\system32> Update-Module navcontainerhelper

PS C:\Windows\system32> $imageName = 'mcr.microsoft.com/businesscentral/sandbox:us'
$licenseFile = 'C:\Workshop\BC 15 US.flf'
$ContainerName = 'mysandbox'
$UserName = 'denster'
$Password = ConvertTo-SecureString 'Navision4ever!' -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ($UserName, $Password)

New-BCContainer `
    -accept_eula `
    -containerName $ContainerName `
    -imageName $imageName `
    -licenseFile $licenseFile `
    -auth NavUserPassword `
    -alwaysPull `
    -updateHosts `
    -Credential $Credential
NavContainerHelper is version 0.6.4.19
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Pulling image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
us-ltsc2019: Pulling from businesscentral/sandbox
65014b3c3121: Pulling fs layer
12c8dbabfd62: Pulling fs layer
20a241d3dcb7: Pulling fs layer
0c8cd8494916: Pulling fs layer
f5c7aa76950f: Pulling fs layer
da39bc56303e: Pulling fs layer
a70d956f624d: Pulling fs layer
f9cb7b385db0: Pulling fs layer
9a04db93575e: Pulling fs layer
cf45f280a83f: Pulling fs layer
f5da805e60d4: Pulling fs layer
9f423bed5b38: Pulling fs layer
67f9efd02ab5: Pulling fs layer
054029725a4d: Pulling fs layer
edaf1e2b2e2e: Pulling fs layer
990d71282088: Pulling fs layer
0c8cd8494916: Waiting
5356e57056a6: Pulling fs layer
a70d956f624d: Waiting
18b2e557830a: Pulling fs layer
421ae99f395c: Pulling fs layer
f9cb7b385db0: Waiting
9a04db93575e: Waiting
cf45f280a83f: Waiting
f5da805e60d4: Waiting
c71fcc65f816: Pulling fs layer
9c2b84b701a3: Pulling fs layer
2459bfca08b7: Pulling fs layer
ee109df69491: Pulling fs layer
d0f5e87ef62b: Pulling fs layer
c78e66da3ceb: Pulling fs layer
03224dcc54ce: Pulling fs layer
669caae1cabf: Pulling fs layer
7122ff6cdad3: Pulling fs layer
fc1171e3a2fa: Pulling fs layer
0cc815badba2: Pulling fs layer
f7b3d84079a1: Pulling fs layer
95d24e1d8585: Pulling fs layer
9fcddfb1b790: Pulling fs layer
7bcc044b33b4: Pulling fs layer
99a715d4242b: Pulling fs layer
42b77539cd1a: Pulling fs layer
9f423bed5b38: Waiting
67f9efd02ab5: Waiting
054029725a4d: Waiting
edaf1e2b2e2e: Waiting
990d71282088: Waiting
5356e57056a6: Waiting
18b2e557830a: Waiting
421ae99f395c: Waiting
c71fcc65f816: Waiting
9c2b84b701a3: Waiting
2459bfca08b7: Waiting
ee109df69491: Waiting
d0f5e87ef62b: Waiting
c78e66da3ceb: Waiting
03224dcc54ce: Waiting
669caae1cabf: Waiting
7122ff6cdad3: Waiting
fc1171e3a2fa: Waiting
0cc815badba2: Waiting
f7b3d84079a1: Waiting
95d24e1d8585: Waiting
9fcddfb1b790: Waiting
7bcc044b33b4: Waiting
99a715d4242b: Waiting
42b77539cd1a: Waiting
f5c7aa76950f: Waiting
da39bc56303e: Waiting
20a241d3dcb7: Verifying Checksum
20a241d3dcb7: Download complete
12c8dbabfd62: Verifying Checksum
12c8dbabfd62: Download complete
f5c7aa76950f: Verifying Checksum
f5c7aa76950f: Download complete
0c8cd8494916: Verifying Checksum
0c8cd8494916: Download complete
a70d956f624d: Download complete
f9cb7b385db0: Verifying Checksum
f9cb7b385db0: Download complete
9a04db93575e: Verifying Checksum
9a04db93575e: Download complete
cf45f280a83f: Verifying Checksum
cf45f280a83f: Download complete
da39bc56303e: Verifying Checksum
da39bc56303e: Download complete
9f423bed5b38: Verifying Checksum
9f423bed5b38: Download complete
67f9efd02ab5: Verifying Checksum
67f9efd02ab5: Download complete
054029725a4d: Download complete
edaf1e2b2e2e: Verifying Checksum
edaf1e2b2e2e: Download complete
990d71282088: Verifying Checksum
990d71282088: Download complete
5356e57056a6: Verifying Checksum
5356e57056a6: Download complete
f5da805e60d4: Verifying Checksum
f5da805e60d4: Download complete
18b2e557830a: Verifying Checksum
18b2e557830a: Download complete
c71fcc65f816: Verifying Checksum
c71fcc65f816: Download complete
421ae99f395c: Verifying Checksum
421ae99f395c: Download complete
9c2b84b701a3: Verifying Checksum
9c2b84b701a3: Download complete
2459bfca08b7: Verifying Checksum
2459bfca08b7: Download complete
ee109df69491: Verifying Checksum
ee109df69491: Download complete
d0f5e87ef62b: Verifying Checksum
d0f5e87ef62b: Download complete
03224dcc54ce: Verifying Checksum
03224dcc54ce: Download complete
c78e66da3ceb: Verifying Checksum
c78e66da3ceb: Download complete
669caae1cabf: Verifying Checksum
669caae1cabf: Download complete
fc1171e3a2fa: Verifying Checksum
fc1171e3a2fa: Download complete
0cc815badba2: Verifying Checksum
0cc815badba2: Download complete
f7b3d84079a1: Verifying Checksum
f7b3d84079a1: Download complete
95d24e1d8585: Verifying Checksum
95d24e1d8585: Download complete
9fcddfb1b790: Verifying Checksum
9fcddfb1b790: Download complete
7bcc044b33b4: Verifying Checksum
7bcc044b33b4: Download complete
99a715d4242b: Verifying Checksum
99a715d4242b: Download complete
42b77539cd1a: Verifying Checksum
42b77539cd1a: Download complete
65014b3c3121: Verifying Checksum
65014b3c3121: Download complete
7122ff6cdad3: Verifying Checksum
7122ff6cdad3: Download complete
65014b3c3121: Pull complete
12c8dbabfd62: Pull complete
20a241d3dcb7: Pull complete
0c8cd8494916: Pull complete
f5c7aa76950f: Pull complete
da39bc56303e: Pull complete
a70d956f624d: Pull complete
f9cb7b385db0: Pull complete
9a04db93575e: Pull complete
cf45f280a83f: Pull complete
f5da805e60d4: Pull complete
9f423bed5b38: Pull complete
67f9efd02ab5: Pull complete
054029725a4d: Pull complete
edaf1e2b2e2e: Pull complete
990d71282088: Pull complete
5356e57056a6: Pull complete
18b2e557830a: Pull complete
421ae99f395c: Pull complete
c71fcc65f816: Pull complete
9c2b84b701a3: Pull complete
2459bfca08b7: Pull complete
ee109df69491: Pull complete
d0f5e87ef62b: Pull complete
c78e66da3ceb: Pull complete
03224dcc54ce: Pull complete
669caae1cabf: Pull complete
7122ff6cdad3: Pull complete
fc1171e3a2fa: Pull complete
0cc815badba2: Pull complete
f7b3d84079a1: Pull complete
95d24e1d8585: Pull complete
9fcddfb1b790: Pull complete
7bcc044b33b4: Pull complete
99a715d4242b: Pull complete
42b77539cd1a: Pull complete
Digest: sha256:39ef0ff32c5db89ddffa785cb89d60a5c3ea23079cac27335da966696fd46c5c
Status: Downloaded newer image for mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Using image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Creating Container mysandbox
Version: 15.1.37881.38709-us
Style: sandbox
Platform: 15.0.37865.38662
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.17763.529 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Workshop\BC 15 US.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\mysandbox\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container mysandbox from image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
3578d9ab566fa97f52f66659118eefc614189e2f68037f4293a33edd7ccd3fea
Waiting for container mysandbox to be ready
Initializing...
Setting host.containerhelper.internal to 172.20.16.1 in container hosts file
Starting Container
Hostname is 
PublicDnsName is mysandbox
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint D8B281BAA28E621FFFED879584D01D37126522E8
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating denster as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.20.25.30
Container Hostname  : 
Container Dns Name  : mysandbox
Web Client          : http://mysandbox/BC/
Dev. Server         : http://mysandbox
Dev. ServerInstance : BC
Setting mysandbox to 172.20.25.30 in host hosts file

Files:
http://mysandbox:8080/al-4.0.194000.vsix

Initialization took 76 seconds
Ready for connections!
Reading CustomSettings.config from mysandbox
Creating Desktop Shortcuts for mysandbox
Container mysandbox successfully created

PS C:\Windows\system32> docker images
REPOSITORY                                  TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/businesscentral/sandbox   us-ltsc2019         0da6040797bb        3 hours ago         12.6GB

PS C:\Windows\system32>
