### ISSUE TITLE
Function Import-DeltasToNavContainer feature request

### ISSUE THREAD

**Issue by JeppeDue** [Microsoft/navcontainerhelper#75]
I would like to use this function a bit more like the object import is working.
We already have a complete set of Delta file of our product, and i would like to import it "unmodifyed" in the database that is already on the docker image.
Today our procedure for this is (not running on docker)
 - Export the complete database as txt
 - Merging the Delta into it
 - Creating a "Changed only" file
 - Importing the "Changed only" file 
 - Compile all uncompiled objects

To support this, i think that the function should be extended with 
 - possible to do it "inside the docker image" (i dont need to have any files locally - yet)
 - possible to export all objects, and not just the modifyed objects
 - parameter to control if modifyed should be set to true

**Comment by freddydk** [comment]
if you create your container with -includecside it will actually export all objects as text (under c:\programdata\navcontainerhelper\extensions\...) and make the directory, which import-deltas expects in order to do what you describe.
The only thing from above that isn't supported is the controlling whether or not modified should be set to true.

**Comment by JeppeDue** [comment]
That helped. Thanks
Would it still be possible to set the modifyed flag as a parameter?
Maybe as a new switch in the function – then it wont break other peoples scripts

**Comment by JeppeDue** [comment]
The goal is to use docker to spin up any given combination of Nav / CU / Country with
 - Standard Navision (in that version)
 - our Add on (in that Nav version and whatever version we are on)
At this point of the build proces, we have added our core code, and it should be kept "as is"
Then its possible to go in and modify it to meet local requirement. after this, we would like to export all changes to deltas, so we can update it into VSO. 
If we do it like this, we should be capable of reusing previous "build delta versions" when MS is releasing a new CU.

Whats needed in the function is simply a switch to avoid that the modifyed flag is set on the object when we import the delta into the database. 
When compiling, we will instead use a filter like "Compiled=0" (maybe a 2nd request to make a multithreaded job for compiling all uncompiled objects in the database - i can create a 2nd request for that if you like the idea, i have the ps code for it if you want it)

**Comment by freddydk** [comment]
The Compile-ObjectsInNavContainer takes a filter parameter, which defaults to modified=Yes, but can easily be changed to compiled=0 - I actually think that would be a better default.
I would very much like your contribution to navcontainerhelper - but I would have to have it as a Pull Request to the project https://github.com/microsoft/navcontainerhelper. It probably should be build into the Compile-ObjectsInNavContainer.
I will look into adding a flag to avoid setting the modified flag on import.

**Comment by freddydk** [comment]
I changed the Compile-ObjectsInNavContainer to compile the uncompiled objects instead o the modified objects, but I didn't find a mechanism to set the modified flag as a parameter.
