### ISSUE TITLE
BC container on Android APP

### ISSUE THREAD

**Issue by BozidarP** [microsoft/navcontainerhelper#750]
I have BC container with Public IP. We can access from outside, working fine.
Question is , can I access that address from Business Central android  - from PlayStore APP?
Is there any tutorial for this?
I already setup this on NAV many times, but w/o containers.

**Comment by freddydk** [comment]
If your container is exposed to the internet with a public IP, then it is the same as if you have installed the DVD and expose the service tier and web client to the internet.
You probably need a SSL certificate and I don't know whether you can use a self-signed cert - haven't worked with the android app.

**Comment by freddydk** [comment]
If you use the NAV ARM templates, you can enable letsencrypt certificates - either alone or with traefik, which should work as well.
