### ISSUE TITLE
Extend Get-NavContainers with additional information

### ISSUE THREAD

**Issue by ThomasSig75** [microsoft/navcontainerhelper#751]
Additional information returned from Get-NavContainers.ps1 would be nice.

Suggestion:
Return a set of object with additional information about the containers.
- ContainerName
- ContainerVersion
- ContainerState (Running/Stopped/...)
- Nav/BC Version numbers
- Other relevant infomations

**Comment by freddydk** [comment]
Added a parameter: -includelabels, which includes labels

**Comment by freddydk** [comment]
Fixed in 0.6.4.21
