### ISSUE TITLE
Feature Request: Group Shortcut / Desktop Icons in a Directory on New-NAVContainer

### ISSUE THREAD

**Issue by git-no** [microsoft/navcontainerhelper#752]
**Situation**:
Command `New-NAVContainer` creates icon shortcuts, e.g. on the Windows desktop (or none or on the startmenu depending of the parameter `-shortcuts`).
With more containers more icons shortcuts are on the desktop (or startmenu). It gets unsorted, less overview, to much icons.

**Request**:
1. Collect all shortcuts of a container into a directory, maybe named by the container name.

**Benefit**:
This solution would improve the overview and handling of NAV/BC Containers.

**Comment by freddydk** [comment]
Fixed in 0.6.4.21 - DesktopFolder or CommonDesktopFolder are new options.
