### ISSUE TITLE
The device is not ready. (0x15)

### ISSUE THREAD

**Issue by yrest** [microsoft/navcontainerhelper#757]
Following https://freddysblog.com/2019/11/24/upgrading-to-15-x-from-14-x-c-al-our-nav-techdays-2019-demo/comment-page-1 on local machine went smoothly, but in Azure VM from aka.ms/getbcext is failing for me on 

New-NavContainer `
    -accept_eula `
    -accept_outdated `
    -imageName $imageName14 `
    -auth UserPassword `
    -Credential $credential `
    -containerName $dev14containerName `
    -licenseFile $licenseFile `
    -updateHosts `
    -useBestContainerOS `
    -includeAL -runTxt2AlInContainer $dev15containerName `
    -includeCSide

with the following error

DockerDo : docker.exe: Error response from daemon: hcsshim::PrepareLayer - failed failed in Win32: The device is not ready. (0x15).
ExitCode: 125
Commandline: docker run --env licenseFile="c:\run\my\license.flf" --name bc14 --hostname bc14 --env auth=NavUserPassword --env username="admin" --env ExitOnError=N --env locale=en-US --env 
databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\bc14\my:C:\Run\my" --isolation process --restart unless-stopped --env enableApiServices=Y --env useSSL=N --volume 
"C:\ProgramData\NavContainerHelper\Extensions\bc14\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=none --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y --env accept_eula=Y --env accept_outdated=Y --detach 
mcr.microsoft.com/businesscentral/onprem:1904-cu6-w1-ltsc2019
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.19\ContainerHandling\New-NavContainer.ps1:1241 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

Any ideas?

**Comment by freddydk** [comment]
Please copy/paste full output and not only the error.

**Comment by yrest** [comment]
Installed SSMS to check the credentials, restarted VM, rerun the script with same result.

   _____      _   _   _                 
  / ____|    | | | | (_)                
 | (___   ___| |_| |_ _ _ __   __ _ ___ 
  \___ \ / _ \ __| __| | '_ \ / _` / __|
  ____) |  __/ |_| |_| | | | | (_| \__ \
 |_____/ \___|\__|\__|_|_| |_|\__, |___/
                               __/ |    
                              |___/     
   _____ _                              
  / ____| |                             
 | |    | | ___  __ _ _ __  _   _ _ __  
 | |    | |/ _ \/ _` | '_ \| | | | '_ \ 
 | |____| |  __/ (_| | | | | |_| | |_) |
  \_____|_|\___|\__,_|_| |_|\__,_| .__/ 
                                 | |    
                                 |_|    
Removing bc14 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\bc14
Removing container bc15
Removing bc15 from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\bc15
Removing container prod
Removing prod from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\prod
Dropping database Prod (if it exists)
Removing Database files c:\databases\Prod.* (if they exist)
Removing folder c:\ProgramData\NavContainerHelper\TechDays\bc14original (if it exists)
Removing folder c:\ProgramData\NavContainerHelper\TechDays\bc15original (if it exists)
Removing folder c:\ProgramData\NavContainerHelper\TechDays\bc14mybaseapp (if it exists)
Removing folder c:\ProgramData\NavContainerHelper\TechDays\bc15mybaseapp (if it exists)
Removing folder c:\ProgramData\NavContainerHelper\TechDays\bc15myapp (if it exists)
   _____                _                             _                   _                                      _   
  / ____|              | |                           | |                 (_)                                    | |  
 | |     _ __ ___  __ _| |_ ___   _ __  _ __ ___   __| |   ___ _ ____   ___ _ __ ___  _ __  _ __ ___   ___ _ __ | |_ 
 | |    | '__/ _ \/ _` | __/ _ \ | '_ \| '__/ _ \ / _` |  / _ \ '_ \ \ / / | '__/ _ \| '_ \| '_ ` _ \ / _ \ '_ \| __|
 | |____| | |  __/ (_| | |_  __/ | |_) | | | (_) | (_| | |  __/ | | \ V /| | | | (_) | | | | | | | | |  __/ | | | |_ 
  \_____|_|  \___|\__,_|\__\___| | .__/|_|  \___/ \__,_|  \___|_| |_|\_/ |_|_|  \___/|_| |_|_| |_| |_|\___|_| |_|\__|
                                 | |                                                                                 
                                 |_|                                                                                 
Creating temp container from mcr.microsoft.com/businesscentral/onprem:1904-cu6-w1-ltsc2019 and extract necessary files
Extracting Database Files
Performing cleanup
Removing temp container
Attaching files as new Database Prod
NavContainerHelper is version 0.6.4.19
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Using image mcr.microsoft.com/businesscentral/onprem:1904-cu6-w1-ltsc2019
Creating Container prod
Version: 14.7.37609.0-W1
Style: onprem
Platform: 14.0.37587.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.17763.864 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\prod\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container prod from image mcr.microsoft.com/businesscentral/onprem:1904-cu6-w1-ltsc2019
3672c2d98f521f6b5fc55d199c42d8b997c6dc52221e5c9ae0ae8828bf02ce3b
Waiting for container prod to be ready
Initializing...
Setting host.containerhelper.internal to 172.19.240.1 in container hosts file
Starting Container
Hostname is 
PublicDnsName is prod
Using NavUserPassword Authentication
Starting Internet Information Server
Import Encryption Key
Creating Self Signed Certificate
Self Signed Certificate Thumbprint CDCCB9788594780C4DAD68F693E163753D117485
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Container IP Address: 172.19.242.18
Container Hostname  : 
Container Dns Name  : prod
Web Client          : http://prod/NAV/
Dev. Server         : http://prod
Dev. ServerInstance : NAV
Setting prod to 172.19.242.18 in host hosts file

Files:
http://prod:8080/al-3.0.191521.vsix

Initialization took 58 seconds
Ready for connections!
Reading CustomSettings.config from prod
Creating Desktop Shortcuts for prod
Container prod successfully created
Copying license file 'c:\Docker\fin.flf' to container
Importing License C:\ProgramData\NavContainerHelper\Extensions\prod\my\license.flf
Creating User admin
Assigning Permission Set SUPER to admin
Importing Objects from C:\ProgramData\NavContainerHelper\RewardsAppcode.txt (container path)
Objects successfully imported
Compiling objects with compiled=0
Objects successfully compiled
Publishing C:\ProgramData\NavContainerHelper\BingMaps14.app
Synchronizing BingMaps on tenant default
Installing BingMaps on tenant default
App successfully published
   _____                _                         _        _                     
  / ____|              | |                       | |      (_)                    
 | |     _ __ ___  __ _| |_ ___    ___ ___  _ __ | |_ __ _ _ _ __   ___ _ __ ___ 
 | |    | '__/ _ \/ _` | __/ _ \  / __/ _ \| '_ \| __/ _` | | '_ \ / _ \ '__/ __|
 | |____| | |  __/ (_| | |_  __/ | (__ (_) | | | | |_ (_| | | | | |  __/ |  \__ \
  \_____|_|  \___|\__,_|\__\___|  \___\___/|_| |_|\__\__,_|_|_| |_|\___|_|  |___/

NavContainerHelper is version 0.6.4.19
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Using image mcr.microsoft.com/businesscentral/onprem:1910-cu1-w1-ltsc2019
Creating Container bc15
Version: 15.1.37881.38071-W1
Style: onprem
Platform: 15.0.37898.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.17763.864 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file c:\Docker\fin.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bc15\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container bc15 from image mcr.microsoft.com/businesscentral/onprem:1910-cu1-w1-ltsc2019
df9a45d57c2944b6d5b3b723ec6c386640db98b964bf428582f7000584eeac03
Waiting for container bc15 to be ready
Initializing...
Setting host.containerhelper.internal to 172.19.240.1 in container hosts file
Starting Container
Hostname is 
PublicDnsName is bc15
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint DFCF3B613C811E9FFD831A21E667CB11A0AE9F1B
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.19.249.131
Container Hostname  : 
Container Dns Name  : bc15
Web Client          : http://bc15/BC/
Dev. Server         : http://bc15
Dev. ServerInstance : BC
Setting bc15 to 172.19.249.131 in host hosts file

Files:
http://bc15:8080/al-4.0.194000.vsix

Initialization took 66 seconds
Ready for connections!
Reading CustomSettings.config from bc15
Creating Desktop Shortcuts for bc15
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\150\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\150\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container bc15 successfully created
NavContainerHelper is version 0.6.4.19
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Using image mcr.microsoft.com/businesscentral/onprem:1904-cu6-w1-ltsc2019
Creating Container bc14
Version: 14.7.37609.0-W1
Style: onprem
Platform: 14.0.37587.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.17763.864 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file c:\Docker\fin.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bc14\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container bc14 from image mcr.microsoft.com/businesscentral/onprem:1904-cu6-w1-ltsc2019
6ac32331ad2cec65e4dd460748dc951a52147bb0ba6390457a3990c3a90ef2f2
DockerDo : docker.exe: Error response from daemon: hcsshim::PrepareLayer - failed failed in Win32: The device is not ready. (0x15).
ExitCode: 125
Commandline: docker run --env licenseFile="c:\run\my\license.flf" --name bc14 --hostname bc14 --env auth=NavUserPassword --env username="admin" --env ExitOnError=N 
--env locale=en-US --env databaseServer="" --env databaseInstance="" --volume "C:\ProgramData\NavContainerHelper:C:\ProgramData\NavContainerHelper" --volume 
"C:\ProgramData\NavContainerHelper\Extensions\bc14\my:C:\Run\my" --isolation process --restart unless-stopped --env enableApiServices=Y --env useSSL=N --volume 
"C:\ProgramData\NavContainerHelper\Extensions\bc14\Program Files:C:\navpfiles" --volume "c:\windows\system32\drivers\etc:C:\driversetc" --env securePassword=76492d111674
3f0423413b16050a5345MgB8AFEANwBKAFEAUABEAEgAawBpADIAawBMAGEAcwBmAFEAaABDAGsAOQBlAEEAPQA9AHwAMgBiAGQAYwAzADMAOQA1AGYAZAA2AGQAYwBkADcAYQAxAGMAMQBhADMAZgAxAGIAMQA1AGMANQBiA
GQAMAAyAGEAMQAyADYAMgA3ADcAYgBhAGEAYwAzAGQAMgBiAGEAZgBkADgANgBhADkANgAxAGMAYQA4AGIAOABkADIAMQA= --env passwordKeyFile="c:\run\my\aes.key" --env removePasswordKeyFile=Y 
--env accept_eula=Y --env accept_outdated=Y --detach mcr.microsoft.com/businesscentral/onprem:1904-cu6-w1-ltsc2019
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.19\ContainerHandling\New-NavContainer.ps1:1241 char:19
+ ...       if (!(DockerDo -accept_eula -accept_outdated:$accept_outdated - ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,DockerDo

**Comment by freddydk** [comment]
What size is the VM?
Memory/Cores?

**Comment by yrest** [comment]
Ah, will try tomorrow... It's default 4/16.

**Comment by freddydk** [comment]
It is very likely just exhausted.
You could also change the prodContainerName to navserver, which would remove the existing navserver container when working - but you would probably still need 32Gb ram.

**Comment by yrest** [comment]
Thanks Freddy! You were right, resizing VM to 4/32 allows to complete the process... What's interesting is that during the entire run VM RAM utilization does not go above 40%. Will attempt live run later...
