### ISSUE TITLE
Publish-NavContainerApp failing

### ISSUE THREAD

**Issue by AalundSQ** [microsoft/navcontainerhelper#759]
PS C:\WINDOWS\system32> Publish-NavContainerApp -containerName "49689252ced1" -appFile C:\temp\WMS180.app -skipVerificat
ion -sync -install
Copy-Item : Could not find a part of the path 'C:\ProgramData\NavContainerHelper\Extensions\49689252ced1\_WMS180.app'.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.19\AppHandling\Publish-NavContainerApp.ps1:103 c
har:17
+                 Copy-Item -Path $appFile -Destination $sharedAppFile
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Copy-Item], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.CopyItemCommand

**Comment by freddydk** [comment]
is 49689252ced1 really the name of your container?
or is it the ID?

**Comment by AalundSQ** [comment]
yes, here is the name from Docker Run 
Dev. Server         : https://49689252ced1

**Comment by AalundSQ** [comment]
Container IP Address: 172.27.180.59
Container Hostname  : 49689252ced1
Container Dns Name  : 49689252ced1

**Comment by freddydk** [comment]
If you want to use functions in the containerhelper, you need to create the container using new-navcontainer. New-NavContainer will setup shared folders and a lot of other things to make the functions work, which you haven't done using docker run.
if you use docker run, you can open a PSSession to the container and do everything manually.

**Comment by AalundSQ** [comment]
Okay, thanks. That make sense. I will try that.
