### ISSUE TITLE
License File is Corrupt

### ISSUE THREAD

**Issue by johndcollins** [Microsoft/navcontainerhelper#76]
I'm trying to use New-NavContainer with a dropbox license link, but I get and error:

The license file is corrupt. Error Code: -200.
at <ScriptBlock>, C:\Run\SetupLicense.ps1: line 29
at <ScriptBlock>, C:\Run\navstart.ps1: line 125
at <ScriptBlock>, C:\Run\start.ps1: line 98
at <ScriptBlock>, <No file>: line 1

Seems maybe it's not waiting for the download of the license file maybe.

**Comment by freddydk** [comment]
You probably need to say dl=1 instead of dl=0 in your dropbox link.

**Comment by johndcollins** [comment]
Thanks Freddy, I'll give that a try.
