### ISSUE TITLE
Import-TestToolkitToNavContainer fails on v15

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#760]
Hi Freddy,

I am getting an error when using Import-TestTookitToNavContainer (NCH 0.6.4.19 + Onprem:1910-CU1):

Failing error message: The tenant 'default' is not accessible, because it is in state Mounting. 
            at <ScriptBlock>, <No file>: line 29

Whenever I debug the code, then I have no problem, but when running our automated build it fails.

The reason is, as far as I can see, line 100 (Set-NavServerInstance $serverInstance -restart).
For a short moment the state is here "Mounting" (we are using a multi-tenant server), which causes the attempt to publish the test extensions to fail.

I have experienced the same issue (state Mounting) in other situations (mostly when mounting), but there I'm able to insert a "Wait Until" command, but I cannot see how I can do this with your function.

**Comment by freddydk** [comment]
QQ - are you using process isolation?
I will insert a wait for tenant in the import function.

In the meantime, you could do this before calling the import function.
```
Invoke-scriptinNavContainer {
    $mockAssembliesPath = "C:\Test Assemblies\Mock Assemblies"
    if (Test-Path $mockAssembliesPath) {
        $serviceTierAddInsFolder = (Get-Item "C:\Program Files\Microsoft Dynamics NAV\*\Service\Add-ins").FullName
         if (!(Test-Path (Join-Path $serviceTierAddInsFolder "Mock Assemblies"))) {
             new-item -itemtype symboliclink -path $serviceTierAddInsFolder -name "Mock Assemblies" -value $mockAssembliesPath | Out-Null
            Set-NavServerInstance $serverInstance -restart
            Start-sleep -seconds 5
        }
    }
}
```

**Comment by freddydk** [comment]
Updated the sample with a wait loop, waiting for not mounting

**Comment by epernst** [comment]
Thanks, I actually did the same in a temporary version of it, except I also used -ForceRefresh, where the results are always correct. 
And while we are at the -ForceRefresh param, then it's a shame you don't include that one in Get-NavContainerTenant, I use it all the time.

**Comment by freddydk** [comment]
I guess I can add that.

**Comment by freddydk** [comment]
like 
                    while (Get-NavTenant $serverInstance -forcerefresh | Where-Object { $_.State -eq "Mounting" }) {
                        Start-Sleep -Seconds 1
                    }

**Comment by freddydk** [comment]
Removed forcerefresh again as some of my tests on the containerhelper failed due to this.
forcerefresh is for readng a single tenant - in all my samples, I read all.
forcerefresh also doesn't have any effect on mounting or mounted - it only updates whether the tenant is operational or not.

**Comment by freddydk** [comment]
should work in 0.6.4.20
