### ISSUE TITLE
New-BCContainer fails because db needs conversion

### ISSUE THREAD

**Issue by yrest** [microsoft/navcontainerhelper#764]
Hi Freddy, is there perhaps a parameter, that I'm missing, that would allow to automatically perform technical upgrade on db I'm trying to attach to the container? Getting the following error: The target  database on the host server must be converted by Microsoft Dynamics NAV Development Environment before you can use it with this version of Dynamics 365 Business Central

**Comment by yrest** [comment]
In the end I was able to pull out matching build using correct tag from https://mcr.microsoft.com/v2/businesscentral/onprem/tags/list

**Comment by freddydk** [comment]
You cannot mount a newer database on an older version.

If you want to mount a database on a newer version - you would always need to uninstall+unpublish all apps (using the old version) - and then re-publish and re-install on the new version.
