### ISSUE TITLE
Convert-AlcOutputToAzureDevOps fails on new AppSourceCop rules

### ISSUE THREAD

**Issue by jwikman** [microsoft/navcontainerhelper#765]
Convert-AlcOutputToAzureDevOps fails for the new AppSourceCop warning 
`warning AS0055: The AppSourceCop configuration must specify the list of countries targeted by the application.`

This error is thrown:
`##[error]Convert-ALCOutputToAzureDevOps : Cannot bind argument to parameter 'Path' because it is null.
`

A PR is coming your way soon... ;-)

**Comment by freddydk** [comment]
Fixed in 0.6.4.21
