### ISSUE TITLE
Compile-AppInNavContainer multi-folder workspace

### ISSUE THREAD

**Issue by JanneRon** [microsoft/navcontainerhelper#767]
I have multi-folder workspace which contains TestApp and MainApp and I try to compile the MainApp with command Compile-AppInNavContainer. When I point the -appProjectFolder parameter to the root folder where TestApp and MainApp are located I get error "could not find file app.json". When I point the -appProjectFolder inside MainApp folder I get messages from objects missing for definition for certain fields. and get .app-file with size 1kb.

Everything compiles fine with VSCode and the used container. Is there support for multi-folder workspace in the command or how to get over the issue?

**Comment by kine** [comment]
Multi-root workspace is just VSCode concept. You need to compile first the MainApp by using the MainApp folder. If there are some errors about missing objects, question is, where they are? in Another App? How you are working with dependencies then? AL compiler is working with one folder for one app only. In symbol cache folder you need to have all symbols and dependencies needed to compile the app. The command will download them from the server, if they are there...

**Comment by JanneRon** [comment]
Thanks for the help! I got the issue solved by changing the docker image version.

**Comment by freddydk** [comment]
Strange that changing the image would resolve the issue you describe.
When compiling multiple projects using the function would would need to compile them one by one as @kine describes.
The ci/cd sample uses a function to sort the folders in order to determine the order.
https://dev.azure.com/businesscentralapps/_git/HelloWorld?path=%2Fscripts%2FCompile-App.ps1

**Comment by JanneRon** [comment]
The exact error was from missing value on enumeration. Thanks for the sample project. I will check that out.
