### ISSUE TITLE
AL1032 error building package for OnPrem customized base app

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/navcontainerhelper#769]
**Describe the bug**
Building the package for modified base app results in an error message:
![image](https://user-images.githubusercontent.com/23434319/69500971-730c1180-0ebd-11ea-9094-41dcd998e2f1.png)

**To Reproduce**
It's actually difficult to reproduce. I get the error just once, only for a brand new container. It only seems to show the error message when I delete any existing packages. The next time I build the package it does not specify the error in the output window, but it does fail. 
- New BC OnPrem container
- Create AL Project file: Create-AlProjectFolderFromNavContainer
- Run Package from the command palette

**Expected behavior**
I'd expect to be able to build the package with the AL project folder that is exported from the container. When I remove all translations files, it does compile. 

**5. Versions:**
 - AL Language: 4.0.199169
 - Business Central: NA Business Central 15.1 (Platform 15.0.37898.0 + Application 15.1.38071.0)
- Docker image: mcr.microsoft.com/businesscentral/onprem:na-ltsc2019

**Comment by TheDenSter** [comment]
I had seen the -usebaseline switch but did not see that it also creates the AL folder. I'll look for it because that's probably the best option anyway.

Still leaves the faulty error message :) but that's not yours to fix. Thanks for the follow up!

**Comment by freddydk** [comment]
Fixed in 0.6.4.21

**Comment by NKarolak** [comment]
I was wrong about one detail: 
the name check applies to the "main" file *.g.xlf only. 
The actual translation files do not need to be renamed.

**Comment by freddydk** [comment]
@NKarolak - are you saying that the fix doesn't work?

**Comment by NKarolak** [comment]
@freddydk Not at all :-) (but I did not check neither, since I am not the originator of this issue).
I was only referring to [my earlier post(s)](https://github.com/microsoft/navcontainerhelper/issues/769#issuecomment-558686960).

**Comment by freddydk** [comment]
Ok. 
Thanks
