### ISSUE TITLE
Possible to set culture in New-NavContainer

### ISSUE THREAD

**Issue by JeppeDue** [Microsoft/navcontainerhelper#77]
When using the function New-NavContainer, in different countries, the export of the objects are done in each docker containers local format. That means that if exporting objects from a W1 database, the date format is 12/31/17, where the same object from a DK database will be 31-12-17.

It would be nice with an extra parameter on New-NavContainer to be able to set the locale of the new container. The line in the powershell code should be something like
Set-Culture 'da-DK'

If this is added, the exported objects would have same dateformat, as well as if an partner has used locale characters (god forbid it), They can still be used in object operations later (eg Compile of objects)

**Comment by freddydk** [comment]
The docker container does have a locale parameter, which you can set to da-DK or en-US.
By default the locale is dictated by the localization you install, danish becomes danish.
If you want to override this default behavior with navcontainerhelper, add this parameter to new-navcontainer:
-e additionalparameters @("-e locale=en-US")

**Comment by JeppeDue** [comment]
Its working perfectly. Thank you.
