### ISSUE TITLE
alc.exe /generatereportlayout

### ISSUE THREAD

**Issue by kylehardin6** [microsoft/navcontainerhelper#777]
/generatereportlayout[+|-]    Specifies whether report layouts should be created and or updated with the dataset. (Default: Enabled)

Because this option is enabled by default, it has two bad side effects. First, it makes a full compile (say, on a devops build server) take twice as long.  Second, even developing locally and publishing from VSC, it takes the time to touch each and every report layout file in the project. 

My suggestion is to change the behavior in Compule-AppInNavContainer to alc.exe /generatereportlayout-

![image](https://user-images.githubusercontent.com/31069850/70255227-6b1d5e80-1754-11ea-93d8-b9ede73b68cb.png)

**Comment by kylehardin6** [comment]
VSIX is al-4.0.176004.vsix for BC15.CU0

**Comment by freddydk** [comment]
Will check with the team what the consequence is to make this change.,

**Comment by freddydk** [comment]
Got confirmation from the ModernDev team that we should disable by default and have a switch parameter called GenerateReportLayout on Compile-BcContainerApp to enable the generation.
Will be included in the next release.

**Comment by freddydk** [comment]
I will add the parameter, but default to NotSpecified (meaning default ALC behavior) in order not to break anybody.
You should be able to always specify **-GenerateReportLayout No** and it will not add the parameter if BC/NAV is pre 14.x

**Comment by freddydk** [comment]
Released in 0.6.4.22
