### ISSUE TITLE
Case Sensitive parameters

### ISSUE THREAD

**Issue by NAVspecialist** [Microsoft/navcontainerhelper#78]
I just noticed that the commands

New-NAVcontainer and Remove-NAVcontainer is case sensitive when it comes to
 -containerName 

Which means that  if I use -containerName TEST

Then it does not remove the desktop-icons when i do a 

Remove-NavContainer test 
I have to do it as Remove-NavContainer TEST

Furthermore if i split the parameter out on several lines like

New-NavContainer `
    -containerName $ContainerName `
    -accept_eula `
    -accept_outdated `
    -auth NavUserPassword `

and there is a space after the `-sign then the command on the following lines says that the command does not exist. Is this normal when splitting parameters into several lines?

Thanks
Palle

**Comment by freddydk** [comment]
I don't understand the second part of your question.
When splitting a command on several lines, you have to end all lines with ` - like:

New-NavContainer -containerName $ContainerName `
-accept_eula -accept_outdated `
-auth NavUserPassword

That is standard PowerShell - I am not sure what you are trying to do here?

**Comment by NAVspecialist** [comment]
@freddydk - My bad.

 I didn't know that the ` (back-tick )-sign was throwing an error by powershell in the following two cases: 
 
- There should NOT be any space (or inline comment) AFTER the back-tick and
-The space in FRONT of the back-tick is required

 #learned-the-hard-way

**Comment by freddydk** [comment]
On the case sensitive thing - the bug is in get-navcontainerid, which is case sensitive.
I will fix that in the next version.
