### ISSUE TITLE
Unable to pull Dynamics NAV Images for Docker

### ISSUE THREAD

**Issue by alhaddad77** [microsoft/navcontainerhelper#780]
Hi,

I am not able to pull older container images for Dynamics NAV (e.g for 2018 or 2017). I am using the right tags, however, I always get the latest BC image. Below is my PS script:

```
Set-ExecutionPolicy RemoteSigned -Force
install-module navcontainerhelper -force

$accept_eula = $true
$containername = 'NAV2018'
$bcDockerImage = 'mcr.microsoft.com/dynamicsnav'

$userName = "admin"
$password = ConvertTo-SecureString -String "xxxxxxx" -AsPlainText -Force

$licenseFileUri = 'DevLicense.flf'

$credential = New-Object -TypeName "System.Management.Automation.PSCredential" -ArgumentList $userName, $password

New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -Credential $credential `
                 -licenseFile $licenseFileUri `
                 -includeCSide `
                 -alwaysPull `
                 -usessl:$false `
                 -updateHosts `
                 -shortcuts Desktop `
                 -imageName $bcdockerimage `

```                 
When I run this in PS ISE, I get this output:

```
PS C:\WINDOWS\system32> C:\Docker\Setup NAV 2018 On-Prem Container.ps1
NavContainerHelper is version 0.6.4.21
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
latest-ltsc2019: Pulling from businesscentral/onprem
Using image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
Removing C:\ProgramData\NavContainerHelper\Extensions\NAV2018
Creating Container NAV2018
Version: 15.1.37881.38071-W1
Style: onprem
Platform: 15.0.37898.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.18362.476 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
IncludeCSide is no longer supported in Dynamics 365 Business Central 2019 wave 2 release (1910 
/ 15.x)
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.21\ContainerHandling\New
-NavContainer.ps1:778 char:9
+         throw "IncludeCSide is no longer supported in Dynamics 365 Bu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (IncludeCSide is...e (1910 / 15.x):String) [], 
    RuntimeException
    + FullyQualifiedErrorId : IncludeCSide is no longer supported in Dynamics 365 Business Cen 
   tral 2019 wave 2 release (1910 / 15.x)
```
 
 
Even if I change the container to something else -for example 'mcr.microsoft.com/dynamicsnav:2018-cu5-gb', I get the same result

Would appreciate any thoughts or insight on this. Thanks.

**Comment by freddydk** [comment]
somehow it doesn't get the imagename you specify - if you do not specify an imagename, it defaults to bc onprem.
Unfortunately, you didn't mark the code above as code, meaning that I cannot see if you are missing special characters.
I would look for a simple POwerShell mistake in the code above.
You are welcome to post the code once more and format as code (button in the tool bar)

**Comment by alhaddad77** [comment]
Thanks Freddy! I've edited my comment above to add the code formatting. I also noticed that, if I leave the $bcDockerImage empty, or even if I don't declare it/assign at all, I still get the same results!! Not sure what causes this override of image specification ...

**Comment by freddydk** [comment]
Only strange thing in your script is that you terminate the last line with a grave symbol - meaning that the command continues on the next line, but since that is empty it shouldn't matter.

When I copy/paste the script above into ISE and run it, I get;

```
NavContainerHelper is version 0.6.4.21
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.4
Docker Server Version is 19.03.4
Pulling image mcr.microsoft.com/dynamicsnav:latest-ltsc2019
latest-ltsc2019: Pulling from dynamicsnav
Digest: sha256:fa513854c7a37d651920e625482eb59d0efae16fec9d401836a33cb6c753f76e
Status: Downloaded newer image for mcr.microsoft.com/dynamicsnav:latest-ltsc2019
Using image mcr.microsoft.com/dynamicsnav:latest-ltsc2019
...
```

Clearly dynamicsnav.
There isn't anything wrong with the script above.

**Comment by alhaddad77** [comment]
Hi Freddy,

Yes - our msgs almost crossed. Yes the script is fine. I think figured it out why it didn't work before. For some reason, Powershell and navcontainerhelper was using the parameters for an existing previous container for BC on my PC. not sure why. Once I've deleted those containers, along with the related setup folders under C:\ProgramData\NavContainerHelper\Extensions\, I am able to pull the right Dynamics NAV image now.

Thanks again for your prompt assistance. Above and beyond!

**Comment by freddydk** [comment]
Sounds strange that old images would affect the image you get (looked through the code).
But, happy you solved your issue, closing this one.
