### ISSUE TITLE
Compile-Objects - throws Code page error

### ISSUE THREAD

**Issue by sweikelt** [microsoft/navcontainerhelper#781]
Hi,

i hope i'm on the right place here.

I'm trying to `Compile-ObjectsInNavContainer -containerName XXX -sqlCredential $databaseCredential`

But i get some CodePage-Error

`: [6146889] There is no system code page on your computer that matches the 1252 code page of the Latin1_General_100_CS_AS collation for the XXX_DEV database.
Your system code pages are: ANSI: 65001, OEM: 65001.
Ensure that the Regional Options of the computer use the correct system language and locale for the code pages to match.
You can also disable the 'Validate Collation' setting for this database. It is possible that certain text data will not be converted correctly when stored in the database.
Click OK to disable the 'Validate Collation' setting and continue to use the database, or click Cancel to exit.

at Compile-NAVApplicationObject, C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 610
at <ScriptBlock>, <No file>: line 30
: [6146889] There is no system code page on your computer that matches the 1252 code page of the Latin1_General_100_CS_AS collation for the Beyersdorf_DEV database.
Your system code pages are: ANSI: 65001, OEM: 65001.
Ensure that the Regional Options of the computer use the correct system language and locale for the code pages to match.
You can also disable the 'Validate Collation' setting for this database. It is possible that certain text data will not be converted correctly when stored in the database.
Click OK to disable the 'Validate Collation' setting and continue to use the database, or click Cancel to exit.

In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.2.91\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 Zeichen:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Compile-NAVApplicationObject`

My Container is build with this params:
`New-navcontainer -accept_eula `
                 -containerName $containerName `
                 -Auth NavUserPassword `
                 -imageName mcr.microsoft.com/businesscentral/onprem:cu2-de-ltsc2016 `
                 -Credential $navCred `
                 -databaseServer $databaseServer `
                 -databaseInstance $databaseInstance `
                 -databaseName $databaseName `
                 -databaseCredential $databaseCredential `
                 -enableSymbolLoading `
                 -accept_outdated `
                 -doNotExportObjectsToText `
                 -includeCSIDE `
                 -updateHosts `
                 -memoryLimit 4G `
                 -useBestContainerOS `
                 -additionalParameters @("--env locale=de-DE") `

i found "some" Codepage-Errors here, but don't know how to resolve this

PS: using docker on a Win10 maschine

PPS: any1 here to show me, how to post correct "code" , so that it is readable? ....that's just meehhhh

**Comment by freddydk** [comment]
A button in the toolbar is called "insert code" that allows you to format code as code.
If you add the output of the container creation, when I can see which versions you are running and whether you are running process isolation or hyperv.

**Comment by sweikelt** [comment]
thnx freddy, i used "insert code" - the result is what you see :D

--> Using hyperv isolation

`NavContainerHelper is version 0.6.2.91
Host is Microsoft Windows 10 Pro - Unknown/Insider build
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/onprem:cu2-de-ltsc2016
Removing Bey from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\xxx
Creating Container xxx
Version: 14.3.34444.0-de
Platform: 14.0.34251.0
Generic Tag: 0.0.9.9
Container OS Version: 10.0.14393.3025 (ltsc2016)
Host OS Version: 10.0.18363.476 (Unknown/Insider build)
A better Generic Container OS exists for your host (1903)
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Generic Container OS Version: 10.0.18362.418 (1903)
Generic Tag of better generic: 0.0.9.96
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale de-DE
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\xxx\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- MainLoop.ps1
- updatehosts.ps1
Creating container xxxfrom image mcr.microsoft.com/dynamicsnav:generic-1903
b88eabc5fb352f913b3cc1c7830d2f696b77849f26b018a9862027be7f335391
Waiting for container xxxto be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CI_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data 
processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 176 seconds
Installation complete
Initializing...
Starting Container
Hostname is xxx
PublicDnsName is xxx
WARNING: Container starts with TimeZone = Mitteleuropäische Zeit, which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Import Encryption Key
Stopping local SQL Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint D2C78364737B4F7FD863B1CBC6BD0B822F2F0CA9
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Container IP Address: 192.168.152.170
Container Hostname  : xxx
Container Dns Name  : xxx
Web Client          : http://xxx/NAV/
Dev. Server         : http://xxx
Dev. ServerInstance : NAV`

**Comment by freddydk** [comment]
Please Update the NavComtainerHelper and try again

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Stephan Weikelt <notifications@github.com>
Sendt: Tuesday, December 10, 2019 7:59:54 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Comment <comment@noreply.github.com>
Emne: Re: [microsoft/navcontainerhelper] Compile (#781)


thnx freddy, i used "insert code" - the result is what you see :D

--> Using hyperv isolation

`NavContainerHelper is version 0.6.2.91
Host is Microsoft Windows 10 Pro - Unknown/Insider build
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/onprem:cu2-de-ltsc2016
Removing Bey from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\xxx
Creating Container xxx
Version: 14.3.34444.0-de
Platform: 14.0.34251.0
Generic Tag: 0.0.9.9
Container OS Version: 10.0.14393.3025 (ltsc2016)
Host OS Version: 10.0.18363.476 (Unknown/Insider build)
A better Generic Container OS exists for your host (1903)
Using generic image mcr.microsoft.com/dynamicsnav:generic-1903
Generic Container OS Version: 10.0.18362.418 (1903)
Generic Tag of better generic: 0.0.9.96
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale de-DE
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\xxx\my:

  *   AdditionalOutput.ps1
  *   AdditionalSetup.ps1
  *   MainLoop.ps1
  *   updatehosts.ps1
Creating container xxxfrom image mcr.microsoft.com/dynamicsnav:generic-1903
b88eabc5fb352f913b3cc1c7830d2f696b77849f26b018a9862027be7f335391
Waiting for container xxxto be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CI_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data
processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 176 seconds
Installation complete
Initializing...
Starting Container
Hostname is xxx
PublicDnsName is xxx
WARNING: Container starts with TimeZone = Mitteleuropäische Zeit, which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Import Encryption Key
Stopping local SQL Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint D2C78364737B4F7FD863B1CBC6BD0B822F2F0CA9
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Container IP Address: 192.168.152.170
Container Hostname : xxx
Container Dns Name : xxx
Web Client : http://xxx/NAV/
Dev. Server : http://xxx
Dev. ServerInstance : NAV`

**Comment by sweikelt** [comment]
thnx freddy - after updating navcontainerhelper it worked (first time i updated a module o_O)

**Comment by freddydk** [comment]
Yeah, for the record on this bug - if somebody needs to run hyperv containers (for some reason cannot run process) - then the ltsc2016 containers should work with the right codepage.
Codepage problems occur with ltsc2019 and hyperv (and containers pre 15.x) - when you work with C/AL.
