### ISSUE TITLE
Question: specific cu for bcsandbox

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/navcontainerhelper#783]
Hi,

I am trying to obtain a specific CU for a bcsandbox. I can find no suitable combination of tags to do this, what am I missing or is it really not possible?

I am using `"mcr.microsoft.com/businesscentral/sandbox:15.1.37881.38071-de-ltsc2019` as image now. That works, BUT the build and revision is fixed that way. That is not what I want, because these will change over time. In this example they have already progressed.

**Comment by freddydk** [comment]
for sandbox images we are using another naming convension as sandbox images are not tied to spring and fall releases.
15.1 is called update31
mcr.microsoft.com/businesscentral/sandbox:update31-de-ltsc2019 should give you the latest 15.1 image
I hope that answers the question.

**Comment by RafaelKoch** [comment]
Thanks! That settles it very nicely :-)
