### ISSUE TITLE
Status Code 422 : Unprocessable Entity

### ISSUE THREAD

**Issue by ioneladanielap** [microsoft/navcontainerhelper#784]
I want to deploy an application on local container. Here is the script:
Publish-NewApplicationToNavContainer -appFile $appFile `
                                     -containerName $containername `
                                     -saveData `
                                     -credential $credential
At the end I get the following error, but the application is published and installed in container:
Status Code 422 : Unprocessable Entity
**At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.21\AppHandling\Publish-NavContainerApp.ps1:191 char:17
+ ...             throw "Status Code $($result.StatusCode) : $($result.Reas ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Status Code 422 : Unprocessable Entity:String) [], RuntimeException
    + FullyQualifiedErrorId : Status Code 422 : Unprocessable Entity**

If I uninstall from the webclient and then try again, the same error, but this time the app it's just published, not installed. What could be the problem?
Thanks!

**Comment by freddydk** [comment]
Publish-NewApplicationToNavContainer is actually designed to publish a new base Application.
the function you want to use is
Publish-BCContainerApp
A few examples here: https://freddysblog.com/2019/12/09/having-demo-data-while-developing-business-central-apps-with-docker/ on how it is used.

**Comment by ioneladanielap** [comment]
Hi,

Same error using this script 

Publish-BCContainerApp -appFile $appFile `
                                     -containerName $containername `
                                     -credential $credential `
                                     -usedevendpoint `
                                     -install `
                                     -skipverification `
                                     -sync

And the app is installed.

**Comment by freddydk** [comment]
In the blog post I mention that if the app is already there, you will get that error.
Please post a full end 2 end script, which shows all commands used to get the error - AND the full output.
Please use the Insert Code formatting for the script.

**Comment by ioneladanielap** [comment]
Thank you! The issue can be closed.
