### ISSUE TITLE
BC 365 Wave2 Web Client error: bc365wave2w1’s server IP address could not be found.

### ISSUE THREAD

**Issue by sco0909** [microsoft/navcontainerhelper#789]
Hi 
I created a container by using the following scripts.
But when I ran 365 BC Wave2 Web Client, I got the following error:
bc365wave2w1’s server IP address could not be found.
Could you please give me a help? Thanks.

///////////////////////////////////////////////////////////////////////////////////////////////
$imageName = "mcr.microsoft.com/businesscentral/onprem"
$containerName = "BC365Wave2W1"
$auth = "UserPassword"
$credential = New-Object PSCredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "c:\temp\Cronus.flf"

New-BCContainer -accept_eula
                -imageName $imageName
                -containerName $containerName
                -auth $auth
                -Credential $credential
                -licenseFile $licenseFile
                -updateHosts
                -assignPremiumPlan

///////////////////////////////////////////////////////////////////////////////////////////////

cmdlet New-NavContainer at command pipeline position 1
Supply values for the following parameters:
containerName: BC365Wave2W1
NavContainerHelper is version 0.6.4.23
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
latest-ltsc2019: Pulling from businesscentral/onprem
Digest: sha256:7a4991a29078a6b6e30088543708b27c4268f390d93ea9ee9d73d228d2981b87
Using image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
Creating Container BC365Wave2W1
Version: 15.1.37881.38071-W1
Style: onprem
Platform: 15.0.37898.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.18362.535 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\BC365Wave2W1\my:
- AdditionalOutput.ps1
- MainLoop.ps1
- SetupWebClient.ps1
Creating container BC365Wave2W1 from image mcr.microsoft.com/businesscentral/onprem:latest-ltsc2019
b0571e448475ce178892bbee83fb1d0df906c7da8c5ebb84c8595df2a67d6803
Waiting for container BC365Wave2W1 to be ready
Initializing...
Starting Container
Hostname is BC365Wave2W1
PublicDnsName is BC365Wave2W1
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user XXXXX
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.18.216.207
Container Hostname  : BC365Wave2W1
Container Dns Name  : BC365Wave2W1
Web Client          : http://BC365Wave2W1/BC/
Dev. Server         : http://BC365Wave2W1
Dev. ServerInstance : BC

Files:
http://BC365Wave2W1:8080/al-4.0.194000.vsix

Initialization took 109 seconds
Ready for connections!
Reading CustomSettings.config from BC365Wave2W1
Creating Desktop Shortcuts for BC365Wave2W1
Container BC365Wave2W1 successfully created

**Comment by freddydk** [comment]
If you use the "insert code" formatting here on github when on your code and script, then github won't remove characters and reformat things.
My assumption is that you are missing a grave symbol after the containername or you have an extra space after the grave symbol:
https://freddysblog.com/2019/08/04/powershell-for-non-experts/ (search for "The Grave")

The reason why I think it is that location is, that it uses windows authentication when starting the container meaning that it also didn't get the -auth parameter, but it does get the containername parameter.

**Comment by sco0909** [comment]
Hi freddydk, 
Yes, you are correct. It is working now. Thanks a lot.
