### ISSUE TITLE
Change the location of the shortcut files

### ISSUE THREAD

**Issue by NAVspecialist** [Microsoft/navcontainerhelper#79]
It would be very cool if it would be possible to change the location of the generated shortcutfiles to e.g. a subfolder on the desktop as a parameter.

/Palle

**Comment by freddydk** [comment]
You can specify -shortcuts to new-navcontainer and specify None, Desktop or StartMenu.
StartMenu will place the shortcuts in a folder called navcontainerhelper in the startmenu, which is the closest to what you are asking for here

**Comment by NAVspecialist** [comment]
Thanks. Didn't notice that
