### ISSUE TITLE
Treafik: Unable to connect to container

### ISSUE THREAD

**Issue by bvbeek** [microsoft/navcontainerhelper#790]
We used this script to setup the Treafik container: https://github.com/tfenster/TraefikForBC
Thanks to Tobias!

```
Import-Module C:\TraefikforBC\TraefikForBC.psd1 -force
Initialize-TraefikForBC -email own@mailaddress.nl -externaldns own.dns.com
Start-Traefik

```
And we use this to create a container:
Thanks to Freddy!
```
New-BcContainer `
        -accept_eula `
        -alwaysPull `
        -accept_outdated `
        -containerName $ContainerName `
        -imageName $ImageName `
        -licenseFile $container.LicenseFile `
        -assignPremiumPlan `
        -Credential $Credentials `
        -auth NavUserPassword `
        -updateHosts `
        -isolation process `
        -additionalParameters $AdditionalParameters `
        -shortcuts None `
        -doNotCheckHealth `
        -includeAL `
        -memoryLimit $MemoryLimit `
        -useTraefik `
        -PublicDnsName 'own.dns.com'
```

Container is succesfully created:
![image](https://user-images.githubusercontent.com/28626283/71158014-66bc6f80-2243-11ea-99ea-cafdcd4b1c84.png)

Traefik is running:
![image](https://user-images.githubusercontent.com/28626283/71158521-65d80d80-2244-11ea-8d52-72571546c0b9.png)

Using the url:
`https://own.dns.com/latest-w1`

But the links are not working:
![image](https://user-images.githubusercontent.com/28626283/71158147-b438dc80-2243-11ea-9ead-07963af55ba6.png)

Container IP is also unreachable:
![image](https://user-images.githubusercontent.com/28626283/71158910-0d554000-2245-11ea-8be0-24a4057be1b6.png)

What are we doing wrong?
Please can anyone help us with this?

**Comment by freddydk** [comment]
@tfenster - do you know?

**Comment by tfenster** [comment]
@bvbeek I created those scripts before I added support for navcontainerhelper, so I am not sure if those work anymore. Could you retry with the navcontainerhelper scripts? Also, please share the full output of all commands as it otherwise is very difficult to find out what happens
