### ISSUE TITLE
Network-related or instance-specific error on creating new Container with options -useNewDatabase or -useCleanDatabase

### ISSUE THREAD

**Issue by aho81** [microsoft/navcontainerhelper#791]
When creating a new Container wie New-BCContainer with the parameters useNewDatabase or useCleanDatabase I get the following error:

A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
at <ScriptBlock>, <No file>: line 7
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)
At Z:\Resources\Repository\navcontainerhelper\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Invoke-Sqlcmd], SqlException
    + FullyQualifiedErrorId : SqlExectionError,Microsoft.SqlServer.Management.PowerShell.GetScriptCommand
    + PSComputerName        : 10e5fc537d175eb87cde2b83659aa5dcceb93468e16898aedad811b89ebcf0ee

**Comment by freddydk** [comment]
shipped in 0.6.4.24
