### ISSUE TITLE
Cannot use -enableTaskScheduler $false

### ISSUE THREAD

**Issue by larswestman** [microsoft/navcontainerhelper#793]
When running tests in the container with Run-TestsInBCContainer [containerName] -testSuite [testSuite] -credential $credential I get a warning saying: "WARNING: TaskScheduler is running in the container. Please specify -EnableTaskScheduler:$false when creating container."

When I try to do that I get an error when creating the container: "Cannot find path 'C:\Windows\system32\False\ServiceTier\program files\Microsoft Dynamics NAV' because it does not exist"

PS C:\Windows\system32> $image = 'mcr.microsoft.com/businesscentral/sandbox:'
$containerBaseName  = 'ltc-test'
$licenseFile = "C:\MyLicense.flf"
$password = ConvertTo-SecureString -String "p@ssword" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "MyUser", $password
$appVersion = '15.1.0.0'
$runTests = $true

$imageTag = 'se'
$containerName = $containerBaseName + '-se'

New-NavContainer `
    -Credential $credential `
    -accept_eula `
    -accept_outdated `
    -useBestContainerOS `
    -containerName $containerName `
    -auth NAVUserPassword `
    -imageName $image$imageTag `
    -updateHosts `
    -licenseFile $licenseFile `
    -alwaysPull `
    -includeTestToolkit `
    -doNotCheckHealth `
    -enableTaskScheduler $false

NavContainerHelper is version 0.6.4.23
NavContainerHelper is running as administrator
Host is Microsoft  - 1909
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image mcr.microsoft.com/businesscentral/sandbox:se-ltsc2019
se-ltsc2019: Pulling from businesscentral/sandbox
Digest: sha256:a3dd81ba994f60e96339f0376d77db8a684aa251c0eb64f40b9e3328c2bcb4c5
Using image mcr.microsoft.com/businesscentral/sandbox:se-ltsc2019
Disabling Health Check (always report healthy)
Removing C:\ProgramData\NavContainerHelper\Extensions\ltc-test-se
Get-Item : **Cannot find path 'C:\Windows\system32\False\ServiceTier\program files\Microsoft Dynamics NAV' because it does not exist.**
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.23\ContainerHandling\New-NavContainer.ps1:553 char:28
+ ... vversion = (Get-Item -Path "$dvdPath\ServiceTier\program files\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Windows\syst...ft Dynamics NAV:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

**Comment by freddydk** [comment]
You have specified -enableTaskScheduler $false - the error says you should specify -enableTaskScheduler:$false
(it is a switch parameter)
https://freddysblog.com/2019/08/04/powershell-for-non-experts/ (search switch vs boolean)

**Comment by larswestman** [comment]
Me noob :-)

Thanks!
