### ISSUE TITLE
Sugestion: option to keep Control Add-Ins data while using -useNewDatabase on publishing

### ISSUE THREAD

**Issue by AcererakTheLich** [microsoft/navcontainerhelper#794]
Hi,

The same way it has been done on Entitlement tables recently (and it's great !), do you think it would be possible to have possibility to keep Control Add-ins table records while using -useNewDatabase in Publish-NewApplicationToBCContainer function?

When creating our environment packages this could greatly help us saving time and avoid mistakes.
I don't have in mind if there are any other general setup tables that could be included in this process too, but the general idea is to keep a fully setup (technical setup part) and usable database even if App was published as a Base Application replacement.

**Comment by freddydk** [comment]
Sounds like a good idea

**Comment by RonKoppelaar** [comment]
Today we found out also the permissionset table got lost... When upgrading from 14x to 15x the upgrade CU 104030 kicks in. This CU will try to create some of those permission sets. However if in multi tenancy you don't have write access to the app DB (like in SaaS) it will fail.

**Comment by freddydk** [comment]
I will add a parameter called -copyTables in which you can specify table names, which content will be copied over (like entitlements).
This is for app database tables only.
I assume that adding  -copyTables @('Add-in','Permission','Permission Set') will include add-ins and permissions.
When performing this change I found, that the current way of copying the table didn't create keys in the destination database.
I have changed the method to NOT drop and recreate, to just copy content (without timestamp)

**Comment by freddydk** [comment]
shipped in 0.6.4.24
