### ISSUE TITLE
Suggestion: "-includeAL" should include source code from any published extension in the container

### ISSUE THREAD

**Issue by frankmortensen** [microsoft/navcontainerhelper#796]
Would it be possible to have "-includeAL" also include any published/installed extension from the container?
Example: Microsoft has published some of their own danish extensions in the "-dk" images from mcr.microsoft.com, and if one is to extend these extensions from visual studio code, it would be nice to be able to see inside the code that is being extended.

**Comment by freddydk** [comment]
-includeAL is only for baseapp
You can use extract-appfiletofolder if you want to extract app files to .al files.
When specifying a file name, you can specify :c:\applications\xxx\name.app (: before the name) to indicated that the file name refers to a name inside the container.

**Comment by frankmortensen** [comment]
When executing from Powershell ISE:
Extract-AppFileToFolder -appFilename C:\Extensions\FIK.app -appFolder C:\Temp\FIK -generateAppJson
I get this error:
The variable '$binaryReader' cannot be retrieved because it has not been set.

![Unavngivet](https://user-images.githubusercontent.com/5450124/71355108-4f042480-257e-11ea-9495-b4f5f6ee390d.png)

**Comment by freddydk** [comment]
If I am to repro this, I need to know more about what app it is, where you get it from, what version etc.

**Comment by frankmortensen** [comment]
I am using this image: "mcr.microsoft.com/businesscentral/sandbox:14.5.35970.37991-dk"
The app comes preinstalled with the image.
The app is "Payment and Reconciliation Formats (DK)", version 14.5.35970.37991, App-ID 644f7e5b-a81c-408a-aaa2-766e655a80a3.
The app-file is named FIK.app and can be found in the folder C:\Extensions\

**Comment by freddydk** [comment]
You need to copy the file out from the container.

```
Copy-FileFromBCContainer -containerName "test" -containerPath "C:\Extensions\FIK.app" -localPath "C:\ProgramData\NavContainerHelper\FIK.app"
Extract-AppFileToFolder -appFilename "C:\ProgramData\NavContainerHelper\FIK.app" -appFolder "C:\ProgramData\NavContainerHelper\FIK" -generateAppJson
```

**Comment by frankmortensen** [comment]
Thanks

**Comment by freddydk** [comment]
remember that apps are in different locations in 15.x and 14.x in the container (and on the DVD).
You can also download the app from the container by using Get-NavContainerApp - that is the same in 14.x and 15.x
```
Get-NavContainerAppInfo -containerName test -tenantSpecificProperties | % {
    if ($_.isinstalled) {
        Write-Host $_.name
        Get-NavContainerApp -containerName test -credential $credential -publisher $_.publisher -appName $_.name -appVersion $_.Version -appFile "c:\temp\$($_.name).app"
    }
}
```
Remember also that if apps have ShowMyCode = false - then you of course cannot extract the source code.
