### ISSUE TITLE
Traefik containers - Azure - cannot access from outside

### ISSUE THREAD

**Issue by BozidarP** [microsoft/navcontainerhelper#798]
I folow directions from 
https://www.axians-infoma.de/techblog/traefik-support-for-navcontainerhelper-the-nav-arm-templates-for-azure-vms-and-local-environments/?unapproved=214&moderation-hash=1100477dc0a9de12845d36aea6a6e2f1#comment-214

When I setup traefik I get this :
Picture1.
![traifk port](https://user-images.githubusercontent.com/44054400/71445032-7b52a900-2716-11ea-8e92-638750d76739.PNG)
Outside:
![web site outsides](https://user-images.githubusercontent.com/44054400/71445038-83124d80-2716-11ea-9fa6-882a28d8d5b5.PNG)

Containers outpoot when are created:

PS C:\Users\vmadmin> New-NavContainer -accept_eula -containerName bc01 -imageName mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1-ltsc2019 -useTraefik
NavContainerHelper is version 0.6.4.24
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1-ltsc2019
PublicDnsName is testbcbc.westeurope.cloudapp.azure.com
Creating Container bc01
Version: 15.1.37881.38071-W1
Style: onprem
Platform: 15.0.37898.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.17763.914 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\bc01\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- MainLoop.ps1
- SetupWebClient.ps1
Creating container bc01 from image mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1-ltsc2019
02a944521ab2144fb13138c391e1579f6a5cf4e35d0e6201a79538ce32276bb9
Waiting for container bc01 to be ready
Initializing...
Starting Container
Hostname is testbcbc
PublicDnsName is testbcbc.westeurope.cloudapp.azure.com
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 8EC9DFD13B7823FCC1EC5D846EC50DDF5A6BA07C
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting PublicODataBaseUrl to https://testbcbc.westeurope.cloudapp.azure.com/bc01rest/odata
Setting PublicSOAPBaseUrl to https://testbcbc.westeurope.cloudapp.azure.com/bc01soap/ws
Setting PublicWebBaseUrl to https://testbcbc.westeurope.cloudapp.azure.com/bc01
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user vmadmin
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.23.58.204
Container Hostname  : testbcbc
Container Dns Name  : testbcbc.westeurope.cloudapp.azure.com
Web Client          : https://testbcbc.westeurope.cloudapp.azure.com/bc01/
Dev. Server         : https://testbcbc.westeurope.cloudapp.azure.com
Dev. ServerInstance : BC
---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------
Trafeik.toml

debug = false
defaultEntryPoints = ["https","http"]
 
[web]
address = ":8080"
 
[docker]
domain = "testbcbc.westeurope.cloudapp.azure.com"
watch = true
endpoint = "npipe:////./pipe/docker_engine"
 
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "c:/etc/traefik/traefik.crt"
    keyFile = "c:/etc/traefik/traefik.key"

-------------------
Iam not using email for letsencript, beacuse the Tobias says non need.

**Comment by freddydk** [comment]
On the landing page it looks like traefik is setup and everything is working.
Are you running Setup-TraefikContainer a second time? why?

**Comment by BozidarP** [comment]
Only looks it is working fine :(
I dont remmeber I run second time, it is affect the traefik works?

What can I rechek?
---------------------------------------------------------------------------------------------
This mistake is also made on first "run" Setup-TraefikContainer
 
\Program Files\Docker\docker.exe: Error response from daemon: failed to create endpoint xenodochial_gagarin on network nat: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20).

**Comment by BozidarP** [comment]
Here is link :
https://ad2019bc.westeurope.cloudapp.azure.com/
Working on that, I give Bind port and 443, now go further, but not connect with container.

**Comment by freddydk** [comment]
The VM seems damaged.
How did you create the VM in the first place?
did you use http://aka.ms/getbc? - and did you set Use Traefik to Yes?
or did you say no to usetraefik - and then tried to add it afterwards?

If you did said Yes to Use Traefik - everything is automatic - VMs will automatically be exposed on the landing page.

You should never need to run any Setup commands and no need to do anything special - everything should just work.

I would recommend removing the VM and recreating it with Use Traefik = Yes

**Comment by BozidarP** [comment]
Yes, I setup with use traefik.
I will recreate VM.

**Comment by BozidarP** [comment]
![kontainer](https://user-images.githubusercontent.com/44054400/71448464-7f91bd00-273c-11ea-81e6-b2c59d5617fe.PNG)

I did again, with Use Traefik Yes , but when want to vreate container he give me error, and demand to Setup-TraefikContainerForNavContainers before -UseTraefik.

What do I wrong?

**Comment by BozidarP** [comment]
I see from status what was problem, I solve that.
Now I have this issue:
![connect](https://user-images.githubusercontent.com/44054400/71449025-82dd7680-2745-11ea-9a29-157348efa5ff.PNG)


Status tell this:
![status](https://user-images.githubusercontent.com/44054400/71449027-8ffa6580-2745-11ea-9e30-4465cd09a44a.PNG)

**Comment by BozidarP** [comment]
Internal Server error

![image](https://user-images.githubusercontent.com/44054400/71449063-1151f800-2746-11ea-8492-bb8620a3d08c.png)

**Comment by BozidarP** [comment]
debug = false
defaultEntryPoints = ["https","http"]
insecureSkipVerify = true

[api]

# Check https://docs.traefik.io/v1.7/configuration/api/#security
# to enable authentication on the dashboard for extra security

[docker]
domain = "adactabc2019.westeurope.cloudapp.azure.com"
watch = true
endpoint = "npipe:////./pipe/docker_engine"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[acme]
email = "bozidar.pavlicevic@adacta.rs"
storage = "c:/etc/traefik/acme.json"
entryPoint = "https"
[acme.httpChallenge]
entryPoint = "http"
[[acme.domains]]
   main = "adactabc2019.westeurope.cloudapp.azure.com"

[file]
[backends]
  [backends.host]
    [backends.host.servers.server1]
       url = "http://10.0.0.4:8180"

 [frontends]
  [frontends.host]
    backend = "host"
    [frontends.host.routes.route1]
      rule = "PathPrefix:/"

**Comment by freddydk** [comment]
the download error above is because the url for the license file is bad - it tries to download your license file - nothing to do with traefik.

**Comment by BozidarP** [comment]
Thanks @freddydk, I see now.
Can you see, why I can not access?
![image](https://user-images.githubusercontent.com/44054400/71466150-00919880-27bf-11ea-8db9-8302b9a0344b.png)
It is my traefik.toml file OK, or what you think is issue?

**Comment by freddydk** [comment]
I have no idea, but I had a look at the status on the above server and it ends with the download error.
This means that the initialization is NOT complete.
Delete the VM, create a new one with correct parameters and see that initialization completes and you can connect to the navserver container from the outside before running a single command inside the VM.
When all of that works - you can create other containers and they will automatically appear on the landing page.
It takes a long time to troubleshoot something where the status tells you that you did something wrong and I don't think it is worth the effort, I hope you understand this.

**Comment by BozidarP** [comment]
I recreate again VM: **navserver** is working working fine.
I make new container, but again same error
-Internal Server Error-

I make new container with:
 New-NavContainer -accept_eula -containerName BC001-imageName mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1-ltsc2019 -useTraefik

container output:
PS C:\Users\vmadmin> New-NavContainer -accept_eula -containerName BC001 -imageName mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1-ltsc2019 -useTraefik
NavContainerHelper is version 0.6.4.24
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Using image mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1-ltsc2019
PublicDnsName is adbc2019.westeurope.cloudapp.azure.com
Creating Container BC001
Version: 15.1.37881.38071-W1
Style: onprem
Platform: 15.0.37898.0
Generic Tag: 0.0.9.96
Container OS Version: 10.0.17763.805 (ltsc2019)
Host OS Version: 10.0.17763.914 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Files in C:\ProgramData\NavContainerHelper\Extensions\BC001\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- MainLoop.ps1
- SetupWebClient.ps1
Creating container BC001 from image mcr.microsoft.com/businesscentral/onprem:15.1.37881.38071-w1-ltsc2019
c5c6dd83635fdbe6420c565f11cb9ae602672558cc4d58e8eac7ecd2df2068ac
Waiting for container BC001 to be ready
Initializing...
Starting Container
Hostname is adbc2019
PublicDnsName is adbc2019.westeurope.cloudapp.azure.com
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 77B983549947FBAAADD41EEC4BCD69CA1FA80494
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting PublicODataBaseUrl to https://adbc2019.westeurope.cloudapp.azure.com/BC001rest/odata
Setting PublicSOAPBaseUrl to https://adbc2019.westeurope.cloudapp.azure.com/BC001soap/ws
Setting PublicWebBaseUrl to https://adbc2019.westeurope.cloudapp.azure.com/BC001
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user vmadmin
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.22.69.206
Container Hostname  : adbc2019
Container Dns Name  : adbc2019.westeurope.cloudapp.azure.com
Web Client          : https://adbc2019.westeurope.cloudapp.azure.com/BC001/
Dev. Server         : https://adbc2019.westeurope.cloudapp.azure.com
Dev. ServerInstance : BC

Files:
http://adbc2019.westeurope.cloudapp.azure.com:8080/al-4.0.194000.vsix
http://adbc2019.westeurope.cloudapp.azure.com:8080/certificate.cer

Initialization took 76 seconds
Ready for connections!
Reading CustomSettings.config from BC001
Creating Desktop Shortcuts for BC001
Container BC001 successfully created
Because of Traefik, the following URLs need to be used when accessing the container from outside your Docker host:
Web Client:        https://adbc2019.westeurope.cloudapp.azure.com/BC001
SOAP WebServices:  https://adbc2019.westeurope.cloudapp.azure.com/BC001soap
OData WebServices: https://adbc2019.westeurope.cloudapp.azure.com/BC001rest
Dev Service:       https://adbc2019.westeurope.cloudapp.azure.com/BC001dev
File downloads:    https://adbc2019.westeurope.cloudapp.azure.com/BC001dl

**Comment by BozidarP** [comment]
I compare bc services 
-navserver
-bc001
They same.

**Comment by BozidarP** [comment]
When create NUP service, and restart windows server is working :)

THANKS FREDDY A LOT :)

**Comment by freddydk** [comment]
NUP service?
