### ISSUE TITLE
Creating Nav Container

### ISSUE THREAD

**Issue by armela1981** [microsoft/navcontainerhelper#799]
Hi all.
I had an issue with my last image running on Docker and I wanted to recreate a new version of my NAV 2019 Spring release.
I have the following running on the Windows Powershell. It is a Ps1 file.

install-module navcontainerhelper -force

# set accept_eula to $true to accept the eula found here: https://go.microsoft.com/fwlink/?linkid=861843
$accept_eula = $True

$containername = 'MyBizCentralApp'
$navdockerimage = 'mcr.microsoft.com/businesscentral/onprem:14.3.34444.0-na'
$appbacpacuri = ''
$tenantbacpacuri = ''

$additionalParameters = @()
if ($appbacpacuri -ne '' -and $tenantbacpacuri -ne '') {
    $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth NavUserPassword `
                 -Credential $credential `
                 -includeCSide `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters

Setup-NavContainerTestUsers -containerName $containername -password $credential.Password

I get the following error though. Any ideas ?

![error](https://user-images.githubusercontent.com/39662533/71496558-82aeab00-2819-11ea-9a3e-efcfbb922b0d.png)

**Comment by armela1981** [comment]
I resolved the issue. It was looking at prior container files. Once I got rid of those I was able to go further but received the following error message. I don't understand why though as I am trying to install a version where Cside existed.
Any ideas ?
![error](https://user-images.githubusercontent.com/39662533/71499884-2a32da00-2828-11ea-9868-6d24ab8248cd.png)

**Comment by freddydk** [comment]
In your screenshot I cannot see the full script and in the message above where you pasted the script, you didn't format it using the "Insert Code" formatting (like bold, italic), meaning I cannot see the script.
You are probably missing a grave in one of the lines (or have a space after a grave) - look here https://freddysblog.com/2019/08/04/powershell-for-non-experts/ - search for grave - meaning that the part with the imagename is seen as part of another line and it uses the default imagename.
