### ISSUE TITLE
Connect VS code to BC sandbox and debug

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#800]
currently we have our product on the app source where we dont show our source code. When user download our app, report an issue, we ask them to copy the PROD into sandbox and give us access to it so that we can replicate the issue, find the root cause of the issue and fix it.

Now during this process, we might have to connect our VS code to the sandbox and debug the code to find the root cause of this issue. We have few doubts and issues dong that

We get the same version of code thats on the app source and then change the app.json to point to cloud sandbox. 
Please note showmycode in app.json is false.
now we click CTRL+SHIFT+F5 in VS code to publish the code without source code.
Now when we keep the break point, we see that it doesnt hit the break point.

can you please help!!

**Comment by NAVspecialist** [comment]
Hi there 
I am sure that you does not mean app.json but the launch.json that you are changing in order to debug your app.

Do you have more than one sandbox??

did you add the following to your launch.json ?

“sandboxName”: “SandboxDebug”, //# Your sandbox name
“tenant”: “XXXX-XXXXXXX-XXXXX-XXXXX” //#Your tenant id

**Comment by Bssivivek** [comment]
Hi,
Thanks a lot for your quick response.
Yes, I did add the tenant in launch.json.
I also modified app.json to show the code.
![image](https://user-images.githubusercontent.com/38437776/71691119-5cc66080-2d5b-11ea-9ae3-30628ffed10c.png)

Now when I publish the app in debug mode (F5), I am getting below error in VS code
![image](https://user-images.githubusercontent.com/38437776/71691166-7cf61f80-2d5b-11ea-842f-f176667b77ec.png)
 then I need to go to the sandbox then install the app in extension management. I am not able to run it in debug mode to debug the code. Please help
