### ISSUE TITLE
Visual Studio Code Settings for traefik-instance

### ISSUE THREAD

**Issue by elweilando** [microsoft/navcontainerhelper#802]
I start a mcr.microsoft.com/businesscentral/sandbox:15.1.37881.38071-de-ltsc2019 image with useTraefik. I can access from docker host and outside the instance with the listed Web Client, OData WebServices, SOAP WebServices with the urls from the navcontainerhelper output.

But I can't publish from Visual Studio Code to the Dev Service. Which configurations should I use? Visual Studio Code trys allways the 7049 port. But I can't set this to the dev service url.

**Comment by tfenster** [comment]
Use port 443. Are you using a VM generated by Microsoft's templates or is this something else? Because on the generated VM's landing page, you get the working settings

**Comment by elweilando** [comment]
With port 443 I receive. I use a Microsoft Template.

```
[2020-01-03 12:52:00.67] Error: Fehler beim Senden der Anforderung.
Die zugrunde liegende Verbindung wurde geschlossen: Für den geschützten SSL/TLS-Kanal konnte keine Vertrauensstellung hergestellt werden..
Das Remotezertifikat ist laut Validierungsverfahren ungültig.
```
I installed the certificate into root. chrome and IE shows "not secure" but the webclient works

**Comment by tfenster** [comment]
Then something goes wrong with the letsencrypt setup of traefik. What does the output of the traefik container show? Did you provide a valid eMail-address?

**Comment by elweilando** [comment]
Yes. I provide a valid eMail. How can I show the output?
Needs the letyencrypt setup a specific port in the firewall for requesting a certificate?

**Comment by tfenster** [comment]
> Yes. I provide a valid eMail. How can I show the output?

docker logs <name_of_the_container>

> Needs the letyencrypt setup a specific port in the firewall for requesting a certificate?

port 80, but that is open by default on the templates

Did you do anything after running the template?

**Comment by elweilando** [comment]
Probarly I don't use a Microsoft Template. This was my misunderstanding.
I use a Azure VM (Windows Server 2019 Datacenter) for development with containers and the latest navcontainerhelper. After opening port 80 and setup traefik again, I have no more certificate issues.
But VS Code can't still publish. 
I use the Dev Service URL and receive the follwing from VC Code

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "testbc",
            "server": "https://_url_.westeurope.cloudapp.azure.com/testbcdev",
            "serverInstance": "BC",
            "authentication": "UserPassword",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "schemaUpdateMode": "ForceSync",
            "port":443
        }
    ]
}
```


```
[2020-01-04 01:24:43.39] Publishing AL application using launch configuration 'testbc'.
[2020-01-04 01:24:43.81] Targeting server 'https://_url_.westeurope.cloudapp.azure.com/testbcdev' and server instance 'BC'.
[2020-01-04 01:24:43.84] Using user name and password authentication. User name used is: 'admin'.
[2020-01-04 01:24:43.86] Sending request to https://_url_.westeurope.cloudapp.azure.com/BC/dev/metadata
[2020-01-04 01:24:44.94] Error: a server-side error occured while processing the request.
Request ID: 7aa27024-96b3-418d-ab92-b4b8edd25f61
Session ID: bc4e511a-4ac3-4d1e-bc61-86e36834c1a1

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-01-04 01:24:44.96] The request for path /BC/dev/metadata failed with code BadGateway. Reason: Bad Gateway
```
Same with download symbols. 
Webclient, Soap and OData works as expected

**Comment by freddydk** [comment]
I think the server url is the server without the containername and the serverinstance is the containername.

            "server": "https://_url_.westeurope.cloudapp.azure.com/",
            "serverInstance": "testbcdev",

**Comment by elweilando** [comment]
`I think the server url is the server without the containername and the serverinstance is the containername.`
Yes. It works now. Thank you.
