### ISSUE TITLE
Unable to download files from traefik file download url 

### ISSUE THREAD

**Issue by elweilando** [microsoft/navcontainerhelper#803]
I start a mcr.microsoft.com/businesscentral/sandbox:15.1.37881.38071-de-ltsc2019 image with useTraefik. I can access from docker host and outside the instance with the listed Web Client, OData WebServices, SOAP WebServices with the urls from the navcontainerhelper output.

File Downloads shows me a list of downloadble files, but if I try to download these files I receive allwas a "Bad Gateway" in browser.

**Comment by tfenster** [comment]
I think I remember that something goes wrong with the generated URLs and you need to manually adjust them. Could you try to compare the URL for the list and the URL of the individual files?

**Comment by elweilando** [comment]
None of the listed URLs work
From navcontainerhelper files-list : http://host.name:8080/certificate.cer - Not Found
From https://host.name/InstanceNamedl: https://host.name/certificate.cer (Bad Gateway)
https://host.name:8080/certificate.cer - not found
http://host.name/certificate.cer - not found
http://localhost:8080/certificate.cer - 404 not found

Only http://ip-adress:8080/certificate.cer works

**Comment by tfenster** [comment]
> File Downloads shows me a list of downloadble files
What is the URL of the file list itself?

**Comment by elweilando** [comment]
Von den Links die als Directory Listing unter https://_host.name_/_InstanceName_dl angezeigt werden ist das https://_host.name_/certificate.cer. Hier kommt ein Bad Gateway.
Wenn das navcontainerhelper Script am Ende die Zusammenfassung anzeigt, dann wird dort auf die Zertifikatsdatei mit http://_host.name_:8080/certificate.cer verwiesen.

**Comment by tfenster** [comment]
Try e.g. https://host.name/_InstanceName_dl/certificate.cer

**Comment by elweilando** [comment]
https://host.name/_InstanceName_dl/certificate.cer works. Thank you.
