### ISSUE TITLE
Move-Item Problem with multiple containers

### ISSUE THREAD

**Issue by lksg** [microsoft/navcontainerhelper#804]
Hi, 

I encounter a problem regularly when running multiple containers with signing on my build machine. 
![image](https://user-images.githubusercontent.com/44197501/71716975-d3746400-2e16-11ea-9766-22ed5200f300.png)

Basically the NavSip.dll cannot be moved because it already exists. Is there a way to avoid this behavior or should the script be changed into something like:
Copy-Item
Remove-Item
or alternatively test if the file already exitsts.
I gathered from the PS documentation that -Force on Move-Item aparently only suppresses dialog unlike on Copy-Item where it forces the action.

Regards Leon

**Comment by freddydk** [comment]
What is the script you are trying to run?
When I sign apps I use the Sign-AppInNavContainer, which does everything inside the container and never copy files out.

**Comment by lksg** [comment]
My script uses  Install-NAVSipCryptoProviderFromBCContainer - from what your comment it sounds like this step is not nessecary. Is that the correct conclusion?

**Comment by freddydk** [comment]
Correct - the Install-NavSip... will install the crypto provider on the host from the container - that is if you want to do signing on the host.
I always recommend doing things inside the container to avoid contaminating the host. I thought I blogged about the signing - but cannot find it. I found a post from Dennis Fredborg: https://www.linkedin.com/pulse/extension-code-signing-dennis-fredborg/

**Comment by lksg** [comment]
Thanks a lot I'll implement that into our pipelines. Have a good day.
