### ISSUE TITLE
Improvement: Filter compiler output before it outputs to DevOps

### ISSUE THREAD

**Issue by RonKoppelaar** [microsoft/navcontainerhelper#808]
When using cmdlet "Compile-AppInNavConatiner" for building the BaseApp, you end up with 800+ warnings. These warning are related to std. NAV objects in which we don't have any footprint.
Having all those warnings make the compiler output less useful. We still want to see our warnings.
 As an improvement for the cmdlet a regex (or collection of regex) must be added as a parameter. This regex can be used to exclude specific lines of the compiler output. For example:
- Ignore all warnings in sources of folder ./original/**

This way can eliminate all the warnings which we can't and won't fix. And still see warnings we introduced.

**Comment by freddydk** [comment]
Next version of NavContainerHelper, I have added a parameter to Compile-AppInBcContainer:
`-outputFunction
`Default value is
`{ Param($line) Write-Host $line }
`which also gives the same output as today.
If you use -AzureDevOps you can add a parameter like:
`-outputFunction { Param($line) if ($line -notlike "*sourcepath=$orgFilesPath\*") { Write-Host $line } }
`to exclude errors from files underneath the $orgFilesPath.
You just get the ALC output line by line (converted when you use -AzureDevOps)

**Comment by freddydk** [comment]
Shipped in 0.6.4.26
