### ISSUE TITLE
Issue #755 Sort-AppFoldersByDependencies doesn't support "id" in dependencies

### ISSUE THREAD

**Issue by JayDashti** [microsoft/navcontainerhelper#809]
I believe the subject issue had been reported as fixed in release 0.6.4.20 but I am using version 0.6.4.24 and still getting same error. Could you please let me know if I am missing anything?

Error Log:

ForEach-Object : The property 'id' cannot be found on this object. Verify that the property exists.
At C:\Program 
Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.24\AppHandling\Sort-AppFoldersByDependencies.ps1:91 char:26
     $script:sortedApps | ForEach-Object {
                          
    CategoryInfo          : NotSpecified: (:) [ForEach-Object], PropertyNotFoundException
    FullyQualifiedErrorId : PropertyNotFoundStrict,Microsoft.PowerShell.Commands.ForEachObjectCommand

**Comment by freddydk** [comment]
It is impossible for me to help without knowing version numbers and a lot lot more.
I prefer the script used to repro the problem and full output of these.

**Comment by JayDashti** [comment]
I have attached the script here. NavContainerHelper version I am using is 0.6.4.24. Thanks.

[Compile-App.zip](https://github.com/microsoft/navcontainerhelper/files/4031136/Compile-App.zip)

**Comment by JayDashti** [comment]
Hi Freddy, did you have a chance to look into this?

**Comment by JayDashti** [comment]
Figured it out. Copied your functions to a local PS and tracked the code and saw some illegal chars in app.json that VSC was not showing!!

![image](https://user-images.githubusercontent.com/43972342/72116822-55292d80-3300-11ea-933d-a992b3cf75e9.png)
