### ISSUE TITLE
On Export Delta files, they are renamed from .Delta to .TXT.

### ISSUE THREAD

**Issue by JeppeDue** [Microsoft/navcontainerhelper#81]
When using function Export-ModifyedObjectAsDelta, it calls Create-MyDeltaFolder. This function renames new Delta files to .txt.
It would be nice to either change it, so its keeping the original extension, or a parameter to choose if it should do it or not

**Comment by freddydk** [comment]
I think the reason for this is that the txt2al will create page extensions of .delta files and page objects of .txt files, but I cannot remember

**Comment by freddydk** [comment]
No change planned here.
