### ISSUE TITLE
Setup-NavContainerTestUsers

### ISSUE THREAD

**Issue by pzentner** [microsoft/navcontainerhelper#810]
NavContainerHelper version 0.6.4.24

I am running a BC 14 container that was created this way:
New-NavContainer -accept_eula -accept_outdated -containerName testbc14 -imageName "mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-na" -licenseFile 'licensefile.flf' -Credential $credential -updateHosts -alwaysPull -useBestContainerOS -auth NavUserPassword -includeTestToolkit

Once that is done, I am trying to create test users in this container using:

Setup-NavContainerTestUsers -containerName testbc14 -Password $SecureStringPassword -credential $credential

This is the output with an error:

Downloading C:\Users\pzentner\AppData\Local\Temp\CreateTestUsers.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\testbc14\_CreateTestUsers.app
Synchronizing CreateTestUsers on tenant default
Installing CreateTestUsers on tenant default
App successfully published
Invoke GET on http://172.28.180.52:7048/NAV/api/beta/companies?$filter=name%20eq%20'CRONUS%20Canada%2C%20Inc.'&tenant=default
Invoke POST on http://172.28.180.52:7048/NAV/api/Microsoft/Setup/beta/companies(5b9d41b7-5bf9-4681-ad41-8766c1eef2a1)/testUsers?tenant=default
Uninstalling CreateTestUsers from tenant default
Unpublishing CreateTestUsers
App successfully unpublished
Uninstalling System Application Test Library from tenant default
Cannot find the extension 'System Application Test Library' because it is not published.
at <ScriptBlock>, <No file>: line 11
Cannot find the extension 'System Application Test Library' because it is not published.
At C:\Program
Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.24\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37
char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Uninstall-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$NAV/default,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.Un
   installNavApp
    + PSComputerName        : 4bf2e4e54b933b6af4fc0d9dcc237fe010cb6008c3c8208e9cbf628dacb7d2f9

Looking at Setup-NavContainerTestUsers.ps1, it seems that you should determine, if the app was actually installed originally, because it might not find that app. 

One solution could be to change the following lines to this:

original:
        UnPublish-NavContainerApp -containerName $containerName -appName "CreateTestUsers" -unInstall
        if (!($systemAppTestLibrary)) {
            UnPublish-NavContainerApp -containerName $containerName -appName "System Application Test Library" -unInstall
        }

changed:

        UnPublish-NavContainerApp -containerName $containerName -appName "CreateTestUsers" -unInstall
        $systemAppTestLibrary = get-navcontainerappinfo -containername $containerName | Where-Object { $_.Name -eq "System Application Test Library" }
        if (($systemAppTestLibrary)) {
            UnPublish-NavContainerApp -containerName $containerName -appName "System Application Test Library" -unInstall
        }

**Comment by freddydk** [comment]
Thanks. I think a better fix is
        if ((([System.Version]$version).Major -ge 15) -and (!($systemAppTestLibrary))) {
meaning that it will only uninstall that app, if the code above actually added it.
Will be fixed in next version (coming out today)

**Comment by pzentner** [comment]
You are correct, I was doing a "quick and dirty", since it stopped our pipelines. Thanks!

**Comment by freddydk** [comment]
Fix shipped in 0.6.4.25
