### ISSUE TITLE
MSVCP120.dll is missing, and some other issues

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#815]
On a completely clean machine (It only has Windows, office and Docker installed) I have used the navcontainerhelper to install 1904-CU4 and there seems to be some things missing. Not sure if the problem is inside the container/image or if there is some dependencies on what is expected on my machine.

Anyhow; I've run the "New-NavContainer -containerName Customer -imageName mcr.microsoft.com/businesscentral/onprem:1904-cu4-dk -accept_eula -Credential sh -doNotExportObjectsToText -auth Windows -includeCSide -accept_outdated" command and it completes, and says it is up and running.

But when I try to connect using the Windows client, it says that it cannot find the server. Same with web client.
When trying to run the CSIDE shortcut, I get an error saying that msvp120.dll is missing. Where is it supposed to be?
Both Powershell and cmd prompts are working. And "net start" indicates that everything is running as expected.

C:\>net start
These Windows services are started:

   Application Host Helper Service
   CNG Key Isolation
   COM+ Event System
   Connected User Experiences and Telemetry
   Container Execution Agent
   CoreMessaging
   Cryptographic Services
   DCOM Server Process Launcher
   DHCP Client
   Distributed Transaction Coordinator
   DNS Client
   Dynamics 365 Business Central Server [NAV]
   Group Policy Client
   IP Helper
   Local Session Manager
   Network Store Interface Service
   Remote Desktop Configuration
   Remote Desktop Services
   Remote Procedure Call (RPC)
   RPC Endpoint Mapper
   Security Accounts Manager
   SQL Server (SQLEXPRESS)
   SQL Server Browser
   SQL Server VSS Writer
   System Event Notification Service
   System Events Broker
   Task Scheduler
   TCP/IP NetBIOS Helper
   Time Broker
   User Manager
   User Profile Service
   Windows Event Log
   Windows Management Instrumentation
   Windows Process Activation Service
   Windows Remote Management (WS-Management)
   WinHTTP Web Proxy Auto-Discovery Service
   Workstation
   World Wide Web Publishing Service

The command completed successfully.
C:\>

Please advise

**Comment by freddydk** [comment]
https://freddysblog.com/2017/10/29/troubleshooting-nav-on-docker/

**Comment by Rukkulakki** [comment]
Thank you. It was nr 4 :) -updateHosts did the trick
Installing SQL server took care of the rest.

**Comment by freddydk** [comment]
Yeah, there is also a link to the DLL installation if you just needed the DLLs.
Thanks
