### ISSUE TITLE
Container is not ready - cannot connect to SQL server

### ISSUE THREAD

**Issue by yrest** [microsoft/navcontainerhelper#816]
It is not an issue as such, just looking for direction because cannot figure it out.
After resetting docker on Windows 10 machine, network seems to had been reset too.
Now when trying to create new container it fails updating hosts to my router IP rather than pc.

Initializing...
Setting host.containerhelper.internal to **192.168.1.1** in container hosts file (copy from host hosts file)
Setting host.docker.internal to 192.168.1.105 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.105 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Starting Container

Staring at updatehosts.ps1 I cannot find out where it takes my router ip from.

**Comment by yrest** [comment]
Gateway and host IPs seem to be switched for some reason. On wireless connection similar story.
1.1 is network gateway and 1.116 is actually nic ip. But it thinks host is the gateway...

Initializing...
Setting host.containerhelper.internal to 192.168.1.1 in container hosts file (copy from host hosts file)
Setting host.docker.internal to 192.168.1.105 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.105 in container hosts file (copy from host hosts file)
Setting host.docker.internal to 192.168.1.116 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.116 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Starting Container

**Comment by freddydk** [comment]
The part where it sets the host is this

```
    if ($sethost) {
        $gateway = (ipconfig | where-object { $_ –match "Default Gateway" } | foreach-object{ $_.Split(":")[1] } | Where-Object { $_.Trim() -ne "" } )
        if ($gateway -and ($gateway -is [string])) {
            Write-Host "Setting host.containerhelper.internal to $($gateway.Trim()) in container hosts file"
            UpdateHostsFile -hostsFile $myhostsFile -theHostname "host.containerhelper.internal" -theIpAddress $gateway.Trim() | Out-Null
        }
    }
```

It should work if you use NAT - the gateway from the container is the host and SQL Server listens to that if default configured. Described under updatehosts here: https://freddysblog.com/2019/11/04/using-sql-server-on-the-host/

**Comment by yrest** [comment]
Thanks Freddy, the nat seems to be setup, but docker is not using it for some reason.... Prior to last reset it was assigning addresses in 172.* range to all containers and now it's all 192.168.* 
Can I force to use nat maybe through additional parameters?

PS C:\WINDOWS\system32> docker network list
NETWORK ID          NAME                                                                        DRIVER              SCOPE
b4051b332d1a        Default Switch                                                              ics                 local
e7208f0d6821        Intel(R) Dual Band Wireless-AC 7260 Virtual Switch                          transparent         local
b47fa707d85a        Realtek PCIe GbE Family Controller Virtual Switch                           transparent         local
dfda06277a4e        nat                                                                         nat                 local
f8e41478747a        none                                                                        null                local
d25fe1317906        vEthernet (Intel(R) Dual Band Wireless-AC 7260 Virtual Switch)              ics                 local
59a064266d49        vEthernet (Internal Ethernet Port Windows Phone Emulator Internal Switch)   ics                 local
b3d15eb682eb        vEthernet (Realtek PCIe GbE Family Controller Virtual Switch)               ics                 local

**Comment by freddydk** [comment]
How does your docker deamon configuration look?

**Comment by yrest** [comment]
Ah yes, that's another change I did along with reset...
As was advised by somebody in yammer, to save space moved graph off from system drive.

{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": true,
  "graph": "L:\\Docker"
}

**Comment by freddydk** [comment]
That shouldn't cause the default network to change...

Anyway - you can add -additionalparameters @('--network nat') to specify that you want to use nat.
You can also add your local IP to your hosts hosts file (ending with .internal), then -updatehosts will automatically copy that to the container.
Or you can use some of the docker internal addresses (which I haven't quite figured out yet what are/can).

**Comment by yrest** [comment]
Cant get my head around this...
The following command 

$imageName14 = 'mcr.microsoft.com/businesscentral/onprem:14.7.37609.0-gb-ltsc2019'
New-NavContainer `
    -accept_eula `
    -accept_outdated `
    -imageName $imageName14 `
    -auth UserPassword `
    -Credential $credential `
    -containerName $prodContainerName `
    -licenseFile $licenseFile `
    -updateHosts `
    -useBestContainerOS `
    -includeAL `
    -includeCSide `
    -enableSymbolLoading `
    -databaseServer $dbServer `
    -databaseInstance $dbInstance `
    -databaseName $dbName `
    -databaseCredential $dbcredentials `
    -additionalParameters @('--net=nat')

Reports following output and fails to connect because 192.168.1.1 if my switch:

Initializing...
Setting host.containerhelper.internal to 192.168.1.1 in container hosts file (copy from host hosts file)
Setting host.docker.internal to 192.168.1.116 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.116 in container hosts file (copy from host hosts file)
Setting host.docker.internal to 192.168.1.105 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.105 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Starting Container
Hostname is bc14
PublicDnsName is bc14

But 
PS C:\WINDOWS\system32> docker network inspect nat
[
    {
        "Name": "nat",
        "Id": "dfda06277a4e5e132a587cbac136d478ace154d8f50aadff1e602a68ad4452eb",
        "Created": "2020-01-13T07:09:42.9765204Z",
        "Scope": "local",
        "Driver": "nat",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.16.0/20",
                    "Gateway": "172.17.16.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "af6f584a20715fb3c234ae7759f2d12adb44c58175756136935e12759a157da0": {
                "Name": "bc14",
                "EndpointID": "07d3fe7faf51eb16e83e74c2af42527162f32d51b38dd64ed81b6e872b832da1",
                "MacAddress": "00:15:5d:7e:d4:71",
                "IPv4Address": "172.17.27.226/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "A6382342-2760-4A45-A741-172ABD9ECF92",
            "com.docker.network.windowsshim.networkname": "nat"
        },
        "Labels": {}
    }
]

And
PS C:\WINDOWS\system32> docker container inspect bc14
[
    {
        "Id": "af6f584a20715fb3c234ae7759f2d12adb44c58175756136935e12759a157da0",
        "Created": "2020-01-13T16:20:42.0608572Z",
        "Path": "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1284,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-01-13T16:20:44.6144995Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 5,
                "Log": [
                    {
                        "Start": "2020-01-13T16:21:14.617239Z",
                        "End": "2020-01-13T16:21:15.0062388Z",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2020-01-13T16:21:45.0378493Z",
                        "End": "2020-01-13T16:21:45.4343405Z",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2020-01-13T16:22:15.4597115Z",
                        "End": "2020-01-13T16:22:15.8232557Z",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2020-01-13T16:22:45.8577046Z",
                        "End": "2020-01-13T16:22:46.1936401Z",
                        "ExitCode": 1,
                        "Output": ""
                    },
                    {
                        "Start": "2020-01-13T16:23:16.2247124Z",
                        "End": "2020-01-13T16:23:16.591308Z",
                        "ExitCode": 1,
                        "Output": ""
                    }
                ]
            }
        },
        "Image": "sha256:c5f0694b800543ebc88514c014a92d37cf45c23e89942d9d0dde5f5eb345fbed",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "L:\\Docker\\containers\\af6f584a20715fb3c234ae7759f2d12adb44c58175756136935e12759a157da0\\af6f584a20715fb3c234ae7759f2d12adb44c58175756136935e12759a157da0-json.lo
g",
        "Name": "/bc14",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "C:\\ProgramData\\NavContainerHelper:C:\\ProgramData\\NavContainerHelper",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\bc14\\my:C:\\Run\\my",
                "C:\\ProgramData\\NavContainerHelper\\Extensions\\bc14\\Program Files:C:\\navpfiles",
                "c:\\windows\\system32\\drivers\\etc:C:\\driversetc"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "nat",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "hyperv",
            "CpuShares": 0,
            "Memory": 4294967296,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "L:\\Docker\\windowsfilter\\af6f584a20715fb3c234ae7759f2d12adb44c58175756136935e12759a157da0"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper",
                "Destination": "c:\\programdata\\navcontainerhelper",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bc14\\my",
                "Destination": "c:\\run\\my",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\extensions\\bc14\\program files",
                "Destination": "c:\\navpfiles",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\windows\\system32\\drivers\\etc",
                "Destination": "c:\\driversetc",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "bc14",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "1433/tcp": {},
                "443/tcp": {},
                "7045/tcp": {},
                "7046/tcp": {},
                "7047/tcp": {},
                "7048/tcp": {},
                "7049/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "passwordKeyFile=c:\\run\\my\\aes.key",
                "licenseFile=c:\\run\\my\\license.flf",
                "databaseInstance=",
                "enableApiServices=Y",
                "useSSL=N",
                "databaseServer=host.containerhelper.internal",
                "securePassword=mypass",
                "accept_outdated=Y",
                "ExitOnError=N",
                "locale=en-GB",
                "databaseUsername=sa",
                "encryptionSecurePassword=mypass",
                "removePasswordKeyFile=Y",
                "databaseSecurePassword=mypass",
                "accept_eula=Y",
                "auth=NavUserPassword",
                "username=admin",
                "databaseName=mydb",
                "enableSymbolLoading=Y",
                "COMPLUS_NGenProtectedProcess_FeatureEnabled=0",
                "NAVDVDURL=https://nav2016wswe0.blob.core.windows.net/dvd/e938a2ba-ed5b-49fa-93c7-8f5e160a1b7e",
                "VSIXURL=https://nav2016wswe0.blob.core.windows.net/dvd/al-3.0.191521.vsix",
                "IsBcSandbox=N",
                "CountryCode=gb",
                "COUNTRYURL=https://nav2016wswe0.blob.core.windows.net/dvd/d33e8ee7-6a46-4b49-a5b9-92199adba492"
            ],
            "Cmd": [
                "powershell -Command $ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue'; .\\Run\\start.ps1"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD",
                    "powershell",
                    ".\\Run\\HealthCheck.ps1"
                ],
                "Interval": 30000000000,
                "Timeout": 10000000000
            },
            "ArgsEscaped": true,
            "Image": "mcr.microsoft.com/businesscentral/onprem:14.7.37609.0-gb-ltsc2019",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "country": "gb",
                "created": "201911060510",
                "cu": "cu6",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.17763.805",
                "platform": "14.0.37587.0",
                "tag": "0.0.9.96",
                "version": "14.7.37609.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "af6f584a20715fb3c234ae7759f2d12adb44c58175756136935e12759a157da0",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "1433/tcp": null,
                "443/tcp": null,
                "7045/tcp": null,
                "7046/tcp": null,
                "7047/tcp": null,
                "7048/tcp": null,
                "7049/tcp": null,
                "80/tcp": null,
                "8080/tcp": null
            },
            "SandboxKey": "af6f584a20715fb3c234ae7759f2d12adb44c58175756136935e12759a157da0",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "dfda06277a4e5e132a587cbac136d478ace154d8f50aadff1e602a68ad4452eb",
                    "EndpointID": "07d3fe7faf51eb16e83e74c2af42527162f32d51b38dd64ed81b6e872b832da1",
                    "Gateway": "172.17.16.1",
                    "IPAddress": "172.17.27.226",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "00:15:5d:7e:d4:71",
                    "DriverOpts": null
                }
            }
        }
    }
]

Both seem to be using correct IPs, as if host.containerhelper.internal is the inly incorrect piece.

**Comment by yrest** [comment]
But of course in my local host hosts file I find whole bunch of entries one of which is 
192.168.1.1 host.containerhelper.internal
:( 

Thanks Freddy!
