### ISSUE TITLE
Please add -IncludePC to allow install perquisite components on host

### ISSUE THREAD

**Issue by worldofthenavcraft** [microsoft/navcontainerhelper#817]
Please add -IncludePC PC stand here prerequisite components. It should allow to install perquisite components on host side. 

Use case: Report development.

Actually, this feature has currently known workaround, but this works only to BC14 because -clickonce is part of the windows client. As we know -clickonce put beautiful and simple webpage inside container. This webpage contain possibility to install prerequisite components as well. Good enough to make dockerized process available for developers.

**Comment by freddydk** [comment]
It definitely shouldn't be part of new-navcontainer, because it is a one-time thing.
I could make a function called: Install-NavPrerequisites, but I am not sure that is the right approach.
I will think about the idea

**Comment by freddydk** [comment]
I think an easy to find blog post with links to pre-requisites is a better approach, IMO people need to know what they are installing on their machines.
