### ISSUE TITLE
[NT AUTHORITY\NETWORK SERVICE]  in tenant database

### ISSUE THREAD

**Issue by epernst** [microsoft/navcontainerhelper#818]
I was getting an error that [NT AUTHORITY\NETWORK SERVICE] user does not exist in the server when I use Export-NAVApplication inside a container. I'm using the databases created by navcontainerhelper.

Looking at the database with SQL Management Studio I can see that the [NT AUTHORITY\NETWORK SERVICE] user is created in tenant/default database but not in CRONUS. And it in fact not one the server users. 
At the same time [NT AUTHORITY\SYSTEM] exists in all databases.

If I add the NetworkService to the users before exporting the application, then there is no problem.

Is that the intended behavior? 

(onprem:14.5.35970.0-w1 + nch 0.6.4.25

**Comment by freddydk** [comment]
Could you submit a repro script?

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Erik P. Ernst <notifications@github.com>
Sendt: Tuesday, January 14, 2020 4:35:48 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] [NT AUTHORITY\NETWORK SERVICE] in tenant database (#818)


I was getting an error that [NT AUTHORITY\NETWORK SERVICE] user does not exist in the server when I use Export-NAVApplication inside a container. I'm using the databases created by navcontainerhelper.

Looking at the database with SQL Management Studio I can see that the [NT AUTHORITY\NETWORK SERVICE] user is created in tenant/default database but not in CRONUS. And it in fact not one the server users.
At the same time [NT AUTHORITY\SYSTEM] exists in all databases.

If I add the NetworkService to the users before exporting the application, then there is no problem.

Is that the intended behavior?

(onprem:14.5.35970.0-w1 + nch 0.6.4.25

**Comment by freddydk** [comment]
I don't know your scenario, but I remember that it wasn't possible to run NST as NETWORK SERVICE under docker at the time when building the container and I had to use SYSTEM, in navinstall.ps1 you can see:

```
# Creating Business Central Service
Write-Host "Creating Business Central Service Tier"
$serviceCredentials = New-Object System.Management.Automation.PSCredential ("NT AUTHORITY\SYSTEM", (new-object System.Security.SecureString))
$serverFile = "$serviceTierFolder\Microsoft.Dynamics.Nav.Server.exe"
$configFile = "$serviceTierFolder\Microsoft.Dynamics.Nav.Server.exe.config"
New-Service -Name $NavServiceName -BinaryPathName """$serverFile"" `$$ServerInstance /config ""$configFile""" -DisplayName "Dynamics 365 Business Central Server [$ServerInstance]" -Description "$serverInstance" -StartupType manual -Credential $serviceCredentials -DependsOn @("HTTP") | Out-Null
```

Which is why the SYSTEM user exists.
Export-NavApplication is hardcoded to use network-service, which is why, in SetupDatabase.ps1 - this is how I change a single database setup to multitenancy:

```
    Copy-NavDatabase -SourceDatabaseName $databaseName -DestinationDatabaseName "tenant"
    Remove-NavDatabase -DatabaseName $databaseName
    Write-Host "Exporting Application to $DatabaseName"
    Invoke-sqlcmd -serverinstance "$DatabaseServer\$DatabaseInstance" -Database tenant -query 'CREATE USER "NT AUTHORITY\SYSTEM" FOR LOGIN "NT AUTHORITY\SYSTEM";'
    Export-NAVApplication -DatabaseServer $DatabaseServer -DatabaseInstance $DatabaseInstance -DatabaseName "tenant" -DestinationDatabaseName $databaseName -Force -ServiceAccount 'NT AUTHORITY\SYSTEM' | Out-Null
    Write-Host "Removing Application from tenant"
    Remove-NAVApplication -DatabaseServer $DatabaseServer -DatabaseInstance $DatabaseInstance -DatabaseName "tenant" -Force | Out-Null
```

So without knowing why you are asking or what you need - I guess it is by design.
