### ISSUE TITLE
Display issue with new-bccontainer

### ISSUE THREAD

**Issue by Update-Mark** [microsoft/navcontainerhelper#819]
This has been happening for a while and is **totally low priority**. 
When creating a new container, after the "waiting for container <name> to be ready statement the powershell display starts doing this:
![powershell_ise_2020-01-21_08-24-34](https://user-images.githubusercontent.com/35524409/72783792-8a4e4d80-3c27-11ea-826f-b6535edc08bb.png)

The container builds fine without issue, just is annoying.

**Comment by freddydk** [comment]
These are Ansi codes.
Are you using PowerShell ISE or just PowerShell?
What is your host - are you remoting into something?

**Comment by Update-Mark** [comment]
Using powershell ISE, and it happens if I remote into our docker server or on my local machine.

**Comment by freddydk** [comment]
And what OS is that?

You can try in PowerShell ISE to run this command:
![image](https://user-images.githubusercontent.com/10775043/72794988-2cc4fb80-3c3d-11ea-87ac-69dc7a74ed81.png)

On your machine - this probably becomes ansi escape codes, right?

**Comment by Update-Mark** [comment]
yep!
![powershell_ise_2020-01-21_11-05-06](https://user-images.githubusercontent.com/35524409/72795440-ef14a280-3c3d-11ea-9d69-57bfd6a057e7.png)

**Comment by freddydk** [comment]
Are you running as administrator?

**Comment by Update-Mark** [comment]
Yes sir!

**Comment by freddydk** [comment]
What is the new-navcontainer you run which provokes this?
And can you provide the full output - then I can see host version numbers and more.
Thanks

**Comment by Update-Mark** [comment]
`New-BCContainer -accept_eula -accept_outdated -alwaysPull -useBestContainerOS $ContainerName -shortcuts DesktopFolder -licenseFile $LicPath -updateHosts -imageName $ImageName -memoryLimit 4g -includeAL -includeCSide -auth NavUserPassword -Credential $LocalCredential -databaseServer $SqlServer -databaseInstance $SQLInstance -databaseName $DatabaseName -doNotExportObjectsToText -additionalParameters "-it --network=networkname"`

if you copy and paste to notepad++ you can see the special characters that it is creating.  See attached file.
[PS - characters.txt](https://github.com/microsoft/navcontainerhelper/files/4090635/PS.-.characters.txt)

(yes, I know that the container is not being created correctly, I am looking into that)

**Comment by freddydk** [comment]
I will have a look

**Comment by Update-Mark** [comment]
no worries.  like i said low priority. its just weird.

**Comment by freddydk** [comment]
The problem is the t in additionalparameters, which means that the container allocates a pseudo tty.

![image](https://user-images.githubusercontent.com/10775043/75176737-0101cd80-5735-11ea-88e0-44f9f9a7edcd.png)

Replace -it with -i
but... - why are you adding -i (interactive)?

**Comment by Update-Mark** [comment]
Thanks @freddydk - removed those and it worked as expected.  We had the -it there as part of just trying to get networking to work properly and we never thought to remove it. If it is not broken.... :)
