### ISSUE TITLE
New-CSideDevContainer: Cannot index into a null array

### ISSUE THREAD

**Issue by mrabus** [Microsoft/navcontainerhelper#82]
Hi Docker gurus,

I am struggeling in creating a container using the navcontainerhelper (latest version).

I use the following command:
$containername = 'nav2017cu12'
New-CSideDevContainer `
    -containerName nav2017cu12`
    -ImageName microsoft/dynamics-nav:2017-cu12-de `
    -Credential $credential `
    -memoryLimit 4G `
    -updateHosts `
    -auth NavUserPassword `
    -accept_eula `
    -accept_outdated `
    -doNotExportObjectsToText `
    -licenseFile "\\10.10.1.31\Tools\lic.flf" 

![grafik](https://user-images.githubusercontent.com/2485163/35101480-ffa043ea-fc5f-11e7-8c28-d749736993fa.png)

I don't have any clue what is happening there. Has anybody seen this behavior before?

**Comment by freddydk** [comment]
I assume (based on the output) that the password you are specifying doesn't meet the minimum requirements, meaning that the creation of a user in NAV fails. This probably leads to the user table being empty later in the script.
Try again and specify a good password.

**Comment by mrabus** [comment]
Thanks for the hint, but that didn't solve it. I used a suitable password. The warning is gone now but the error (everything below he line (6365 lines affected)) remains as it was before.

**Comment by freddydk** [comment]
Ok, looking at the source, it looks like your container here:
https://github.com/Microsoft/nav-docker/blob/master/Run/navstart.ps1
I can see that like 167 is:
$ip = (Get-NetIPAddress | Where-Object { $_.AddressFamily -eq "IPv4" -and $_.IPAddress -ne "127.0.0.1" })[0].IPAddress
Can it be, that your container doesn't get an IP address?
can you send docker inspect?
Thanks

**Comment by mrabus** [comment]
Thanks, freddy. There was an issue with my docker network, after recreating it the error is solved.
