### ISSUE TITLE
ClickOnce Client for C/Side not working

### ISSUE THREAD

**Issue by jonwrede** [microsoft/navcontainerhelper#826]
The error `<entryPoint>-Spezifikation is invalid` is returned when executing the 
[Finsql.application.txt](https://github.com/microsoft/navcontainerhelper/files/4116316/Finsql.application.txt). 

There is an error in the following lines in the `Finsql.exe.manifest` file.
`<entryPoint>
    <assemblyIdentity name="Microsoft.Dynamics.Nav.Client" version="14.0.0.0" publicKeyToken="31BF3856AD364E35" language="neutral" processorArchitecture="msil" />
    <commandLine file="Microsoft.Dynamics.Nav.Client.exe" parameters="" />
</entryPoint>`

The `Finsql.exe` should be executed. 

The [SetupClickOnce.ps1](https://github.com/microsoft/nav-docker/blob/master/generic/Run/130/SetupClickOnce.ps1) is trying to modify the `Finsql.exe.manifest`. But is not succeeding. See [Finsql.exe.manifest.txt](https://github.com/microsoft/navcontainerhelper/files/4116317/Finsql.exe.manifest.txt)

The image `mcr.microsoft.com/businesscentral/onprem:14.9.39327.0-de-ltsc2019` is causing the error.
`mcr.microsoft.com/businesscentral/onprem:14.1.32615.0-de-ltsc2019` it is working.

**Comment by freddydk** [comment]
Looks like some files might have been replaced in 14.9 - will investigate.

**Comment by freddydk** [comment]
For now, if you add 
`-myscripts @("https://raw.githubusercontent.com/microsoft/nav-docker/master/generic/Run/130/SetupClickOnce.ps1")`
when you create the container - then it will grab a new version of SetupClickOnce.ps1 and fix the issue.
I will create a new generic layer for the next CUs, which means that 14.10 should be fine. I might even rebuild 14.9 if possible.

**Comment by ChrisBlankDe** [comment]
> I will create a new generic layer for the next CUs, which means that 14.10 should be fine. I might even rebuild 14.9 if possible.

Do I understand correctly that you are only planning to fix this for new (+ one old) CUs?
may i ask you to recreate all images where this is a problem?
We, as well as many other partners, have a central infrastructure for container creation where we do not distinguish between the versions (...,2017,2018). If we had to use the workaround for older versions, this would mean a lot of work and potential errors.

**Comment by freddydk** [comment]
I think the problem has been there for a very long time for a lot of version?
Or is this only for the latest CUs?

In all cases, adding the -myscripts above to your script should fix it for all.

**Comment by ChrisBlankDe** [comment]
As said in the referenced ticket we have the problem with nav 2018 cu 23. so the issue exist at least since november.

**Comment by freddydk** [comment]
Yeah, it is impossible for me to rebuild all versions back in time.
A new generic image is now shipped. This means that -useBestContainerOS or -useGenericImage will replatform and use the new generic image and as such, should work.
