### ISSUE TITLE
App cannot be build some time after new upgrade from docker

### ISSUE THREAD

**Issue by VladimirVeljovic** [microsoft/navcontainerhelper#827]
Hi,
we have notice several issues i cannot conclude what is the problem. I suspect it is after new build from docker(therefore i put the issue in navcontainerhelper git). For example yesterday was everithing fine. jumping from branch to branch recreate branches etc, NO BUILD problems. Today for no reason we got for example this:
![image](https://user-images.githubusercontent.com/53824412/73343539-12180580-4281-11ea-8f13-ae0857797ed0.png)
then i have to delete docker container and recreate again and everithing works like a charm.
Other collegue had a same problem but for example last message was "There is no record in General Ledger Setup"  but there is. after he recreated container everithing worked fine.
I tried, restarting container, analyze, everithing is fine on that side. Only recreate container fix the issue.
Could you check on your side what should be the problem

**Comment by freddydk** [comment]
Sounds like a data problem - @atoader is this something you guys have seen before?

Could you try to do a backup-navcontainerdatabases after creating the container - and then when you see this error - do a restore-navcontainerdatabases.

If that fixes the error, then the problem is in the database.

**Comment by NemanjaKutlesic** [comment]
Here is the evidence that it also fails with code 422 for General Ledger Setup even though is instanced and it exist!
![image](https://user-images.githubusercontent.com/54843470/73353247-3bda2800-4293-11ea-9bd5-57a6ac4ce379.png)
Only possible thing from this point is to recreate container. Changing company does not help, opening General Ledger Setup, and so on.

Possibility to recreate this is to publish App, then go to Test app and do some modifications, then go back to the main app and do some modifications and try to publish, then error occurs.

**Comment by freddydk** [comment]
When you say test app and main app - I assume that this is your test app and main app - right?
I have never seen this before and will have a hard time reproing without knowing which docker image you are using nor which app you are trying to run/debug
I think it is running some upgrade code when you publish - have you double checked that this upgradecode cannot cause this?
You could also try to remove all upgrade code to see whether this is causing the issue.

**Comment by atoader** [comment]
We've never seen this issue before. @NemanjaKutlesic  if you can provide a self-contained repro, we can debug the service on our side.

**Comment by freddydk** [comment]
Please reopen with a repro script if the problem persists.
