### ISSUE TITLE
Unable to connect to remote SQL server

### ISSUE THREAD

**Issue by jiraffex** [Microsoft/navcontainerhelper#83]
Hi, we've been trying to start a 2018 instance using a pre existing sql database image from an exsisting SQL server.

It looks like it is starting the server properly, however the farthest we have been able to get is to the login screen where it says our credentials are wrong. With slightly different parameters, we also get that it couldn't connect to the DB or it wasn't started.

``New-NavContainer -accept_eula `
                 -containerName $containername `
                 -imageName $image `
                 -includeCSide `
                 -databaseServer $databaseServer `
                 -databaseInstance $databaseInstance `
                 -databaseName $dbName `
                 -databaseCredential $cred1 `
                 -Credential $cred  `
                 -updateHosts `
                 -doNotExportObjectsToText `
                 -licenseFile "c:\myfolder\mylicense.flf"  `
                 -auth Windows `
                 -memoryLimit 3G``

We have tried changing the -auth, the -databaseCredential, -credential, etc. Also tried using the IP for the SQL server in case it is a docker DNS issue. SQL server is pingable from the docker container's command line.

**Comment by freddydk** [comment]
Is the SQL Server on the docker host - or is it another Docker Container or something different?

**Comment by jiraffex** [comment]
It's on a seperate non-docker sql server.

**Comment by freddydk** [comment]
Did you manage to get this to work?

**Comment by jiraffex** [comment]
Hi Freddy,

Unfortunately no, not yet. The instance looks to start up without errors in docker, and looks like it is using the external database, however it doesn't seem to allow the users that exist in the SQL table to be able to connect, nor any that we try adding.

This is what I've been trying:

> New-NavContainer `
    -containerName my2018 `
    -imageName navdocker.azurecr.io/dynamics-nav:11.0.19281.0-finus `
    -accept_eula `
    -accept_outdated `
    -databaseServer $databaseServer `
    -databaseInstance $databaseInstance `
    -updatehosts `
    -databaseName $dbName `
    -Credential $cred  `
    -auth Windows `
    -licensefile "C:\Altus\License\dev 2018 v3 - with ISV insert rights.flf" `
    -includecside

**Comment by freddydk** [comment]
If you open a powershell prompt in the container (Enter-navcontainer) and use Get-NavserverUser NAV - do you then get the list of users?

**Comment by jiraffex** [comment]
Yes I do get a list of all of them.

**Comment by freddydk** [comment]
Ok, then your problem is really not the database - the problem is that Docker only supports Windows Authentication if you setup gMSA.
You can use Windows Auth with a single user, running on the same box as the container (dev scenario) but else you probably should set it up for NavUserPassword and then add a user with a password to the database.
