### ISSUE TITLE
Visual Studio Code Error

### ISSUE THREAD

**Issue by syssolmarketing** [microsoft/navcontainerhelper#838]
Visual Studio Code is giving us the following error message, 
“Error: An error occurred while sending the request.
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
The remote certificate is invalid according to the validation procedure.”
 
This coincided with our encryption expiring. Since then we have successfully re-encrypted but are still getting the error. 

The launch.json (part of it) it's using is this:

"name": "Your own server",
"server": "https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fbc15exttester.eastus2.cloudapp.azure.com&amp;data=02%7C01%7Crweigel%40microsoft.com%7C22ec9f7c4780422aad9508d7abe3dacb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637166867878551616&amp;sdata=lEpCn7T%2BpwHzccuckOApuQNfgWWwu4Xti3iuuvvsQfY%3D&amp;reserved=0",
"serverInstance": "BC",
"authentication": "UserPassword",

**Comment by freddydk** [comment]
That is definitely not the right server url.
It looks like you have rightclicked a link in outlook and selected copy link.
looking at the url - it probably should be https://bc15exttester.eastus2.cloudapp.azure.com

**Comment by syssolmarketing** [comment]
Yes that must be what I did, https://bc15exttester.eastus2.cloudapp.azure.com is the url being used. Error is still occurring.

**Comment by freddydk** [comment]
and where did you get the url from?
How did you create it?
Are you sure that it is correct?
there doesn´t seem to be a server on that url?

**Comment by syssolmarketing** [comment]
![WINWORD_t1hSK9lE2D](https://user-images.githubusercontent.com/54630609/74060305-b0117b80-49b7-11ea-9d08-3319c86961c1.png)
We got that url from the landing page that pops up when logging into the vm.

**Comment by freddydk** [comment]
So created through aka.ms/getbc - with letsencrypt, right?
I cannot connect to the URL?
Do you get the same error now?
what is the full launch.json?

**Comment by Telapantela** [comment]
![20200211_135558](https://user-images.githubusercontent.com/60202307/74238576-5cb06d80-4cd6-11ea-93fd-9317fc952620.jpg)



Pls guys, could you help me fix this issue?

**Comment by syssolmarketing** [comment]
![OUTLOOK_nxSWwk0y1M](https://user-images.githubusercontent.com/54630609/74248905-50b4b380-4cb6-11ea-9adc-5902ebc14af2.png)
aka.ms/getbcext - image tag used: mcr.microsoft.com/businesscentral/sandbox:us
We are still getting the same error, full launch.json is attached

**Comment by freddydk** [comment]
When you are saying you are still getting the same error - are you really getting this???

“Error: An error occurred while sending the request.
The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
The remote certificate is invalid according to the validation procedure.”

**Comment by syssolmarketing** [comment]
Yes, attached is a screenshot. 
![mstsc_IpZvFmXmYy](https://user-images.githubusercontent.com/54630609/74250755-1698e100-4cb9-11ea-9d58-83ed6562cc62.png)

**Comment by freddydk** [comment]
Was this machine created today - or is this the same machine you had earlier, where you renewed the certificate?
If this is the old machine, something apparently went wrong during cert. renewal.
You can connect to the VM, start ISE and run Replace-NavServerContainer - or (if that doesn't work) you can remove the VM and recreate it.

**Comment by syssolmarketing** [comment]
This is an old machine that we needed to do a cert renewal for. I will try those options. thanks.

**Comment by syssolmarketing** [comment]
Thanks @freddydk running the replace-navservercontainer fixed this issue!
