### ISSUE TITLE
New-NavContainer FR Version

### ISSUE THREAD

**Issue by AntoineTal** [microsoft/navcontainerhelper#839]
Hello, 

I've successfully start a NAVContainer with 

`
New-NavContainer -containerName Test6 -auth Userpassword -licensefile "pathtolicenseBC15" -accept_eula -imageName mcr.microsoft.com/businesscentral/sandbox -includeAL -accept_outdated -doNotExportObjectsToText
`

I can use it and develop on it, great! However I can't publish my extensions since they are for the french version, therefore I'm trying to use this command : 

`New-NavContainer -containerName Test6 -auth Userpassword -licensefile "pathtolicenseBC15" -accept_eula -imageName mcr.microsoft.com/businesscentral/sandbox:fr-ltsc2019 -includeAL -accept_outdated -doNotExportObjectsToText`

But i'm hit with an error 

> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Service 'Dynamics 365 Business Central Server [BC] (MicrosoftDynamicsNavServer$BC)' cannot be started due to the following error: Cannot start service MicrosoftDynamicsNavServer$BC on computer '.'.
> at <ScriptBlock>, C:\Run\navstart.ps1: line 147
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1
> Initialization of container Test11 failed
> Au caractère C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Wait-NavContainerReady.ps1:44 : 17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization ...r Test11 failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container Test11 failed
> 
> 

I've tried without License, but it's still the same.

Do you have any idea why this image isn't working? Am I targeting the wrong one? 

UPDATE : Apparently the first command doesn't work anymore, the only thing I did between the two was delete some containers & images... 
A simple command as "New-BCContainer -accept_eula -containerName 'test'" don't work now :(

**Comment by freddydk** [comment]
Reset your docker to factory defaults and try again
![image](https://user-images.githubusercontent.com/10775043/74087292-fd125200-4a8a-11ea-87c3-3a297d0a2156.png)

**Comment by AntoineTal** [comment]
Reset to factory defaults, also uninstall & reinstall Docker but doesn't change this error. Would this come from Docker and not navcontainer?

**Comment by freddydk** [comment]
I don't know.
You could try and use Get-NavContainerEventLog <containerName> to see if there is anything in the eventlog. Remember to remove the eventlog from the event viewer and close the event viewer - else it will have a lock on the shared file.

**Comment by AntoineTal** [comment]
Well, couldnt make it work on my personnal machine but successfully worked on another machine, so I guess it's an issue with Docker, i'll close this ticket, thanks for the help!
