### ISSUE TITLE
Convert-ModifiedObjectsToAl doesn't create Page Extensions

### ISSUE THREAD

**Issue by TimothyWatkins** [Microsoft/navcontainerhelper#84]
Convert-ModifiedObjectsToAl  in version 11.0.20258.0 does not convert page modifications.

It worked previously in 11.0.19394.0.

**Comment by freddydk** [comment]
I didn't change anything - it should work.
maybe the objects wasn't exported for the baseline?

**Comment by TimothyWatkins** [comment]
Looking further, I think the issue is related to the Txt2Al.exe
Using the command directly from the container with the same file/folder structure...

Results from version 11.0.19394.0
------------------------------------------------
Warning: Unsupported feature: PropertyChange. Please convert manually.
Writing: C:\ProgramData\NavContainerHelper\Extensions\NAV11020258\target-alsyntax\Modification  - Blanket Sales Orders(Page 9303).al
Total Time: 0:00:02.2471573
Errors: 0
------------------------------------------------
Results from version 11.0.20258.0
----ERROR----
Error converting file:C:\ProgramData\NavContainerHelper\Extensions\NAV11020258\delta-newsyntax\PAG9303.DELTA
The delta file was not generated with ExportToNewSyntax flag
Total Time: 0:00:01.4570543
Errors: 76

**Comment by freddydk** [comment]
This is fixed in the version of navcontainerhelper shipped today.
The problem was that Compare-NavApplicationObject got a new parameter -ExportToNewSyntax and the navcontainerhelper didn't set that.
