### ISSUE TITLE
Restore bacpac to New Container

### ISSUE THREAD

**Issue by AntoineTal** [microsoft/navcontainerhelper#842]
Hello,

Quick context, we want to step away from SaaS as it is barely usable this days with insane response time and somestimes random crash on the Sandbox.

But in order to fully switch to Docker, we need to be able to restore a database from a Production environment on SaaS to a Sandbox on Docker. 

I've exported a .bacpac file from my Prod using Azure Storage, is there absolutely no way to restore a database/create a container with a bacpac file? 

Can't find anything in the documentation, and trying those commands didn't help.

`New-NavContainer -containerName testAntoine4 -auth Userpassword -licensefile "C:\Users\AntoineTALIERCIO\Desktop\Docker\BC15.flf" -accept_eula -imageName mcr.microsoft.com/businesscentral/sandbox:fr-ltsc2019 -includeAL -accept_outdated -doNotExportObjectsToText -additionalParameters @('--env tenantbacpac="C:\Users\AntoineTALIERCIO\Desktop\Docker\Production_20200210_01.bacpac"')`
(tried with --env appbacpac aswell) 

`Restore-DatabasesInNavContainer -containerName testAntoine4 -bakfile "C:\ProgramData\NavContainerHelper\Extensions\testAntoine4\database.bacpac"`

If anyone is able to give me information about this, i'm all ears !

**Comment by freddydk** [comment]
Are you talking about switching your production environment or only sandbox/development?
Note that Docker is not supported for production yet, but you should read those blog posts:
https://freddysblog.com/2019/11/12/mounting-a-database-from-my-online-environment-using-sql-server-on-the-host/
https://freddysblog.com/2019/11/12/mounting-a-database-backup-from-my-online-environment-inside-a-container/

**Comment by freddydk** [comment]
There are also a lot of other blog posts describing how to do things with docker.

**Comment by AntoineTal** [comment]
I'm only talking about our development side. Our Production stays on SaaS but we develop on Docker in order to save time.
Must be blind then, can't find anything related to docker business central + bacpac, I guess I can take that as a "It's not possible"  then!

**Comment by freddydk** [comment]
? 
Right above there are two links, which explains exactly what you are looking for.

**Comment by AntoineTal** [comment]
100% my bad. Apologies. I definitely might be blind! 

Thanks for the help and sorry for the trouble...
