### ISSUE TITLE
Error creating a container after install the last Winsows 10 update

### ISSUE THREAD

**Issue by ftornero9** [microsoft/navcontainerhelper#844]
Hello,

After installing the last Windows 10 update:

![image](https://user-images.githubusercontent.com/12720964/74369869-69b48600-4dd6-11ea-9c2c-d72a1c9cdea5.png)

I get the next error when cerating a new container:

```
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 623
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 609
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\110\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 483
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 157
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container nav2018b failed
En C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Wait-NavContainerReady.ps1: 44 Carácter: 17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...nav2018b failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container nav2018b failed	
```

This is an example for a NAV2018 container but the same error happens with a BC one.

It happens when using the -UseBestContainerOS option and it works ok when I set also -isolation hyperv.

Regards.

**Comment by MikeGlue** [comment]
I get the same error :(

**Comment by freddydk** [comment]
Yeah - will check, but the only option right now is to use hyperv isolation.

**Comment by freddydk** [comment]
Could you display which windows version you are running (winver)

**Comment by YvesDesrumaux** [comment]
I have the same error.
winver 18363.657
docker 19.03.5

I found a workaround using NavContainerHelper version 0.6.4.18

**Comment by ftornero9** [comment]
This is my Windows 10 version

![image](https://user-images.githubusercontent.com/12720964/74383891-60d0ae00-4df0-11ea-9580-b34981f8524a.png)

**Comment by richardrobberse** [comment]
Similar issues on Windows Server 2019 1809 17763.1039.
Found two different issues so far:
- Service Tier crashes with error 'cannot process the request, service will close' when importing the license
- The container is created and it seems to be healthy, however, importing the test toolkit gives the error: '!' (See image below)
![image](https://user-images.githubusercontent.com/29714289/74436820-60272e80-4e67-11ea-93a7-f3e501b4e7b8.png)

**Comment by richardrobberse** [comment]
@freddydk Please let me know if you need anything.
I have a few customers suffering from this issue atm.

**Comment by freddydk** [comment]
I have a windows server 2019 1039 VM now – and I can repro.
Apparently -isolation hyperv solves the issue.
I don’t know if I will be able to fix the issue – but I will try.

/Freddy

Fra: Richard Robberse <notifications@github.com>
Sendt: 13. februar 2020 14:49
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Mention <mention@noreply.github.com>
Emne: Re: [microsoft/navcontainerhelper] Error creating a container after install the last Winsows 10 update (#844)


@freddydk<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffreddydk&data=02%7C01%7Cfreddy.kristiansen%40microsoft.com%7C8900ff8fedf94121d62208d7b08b7fb1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637171985542533204&sdata=SlSi2LC10TgB1MO7fZm7AXg9R3YoHh%2Fzb2JPI5XbM2M%3D&reserved=0> Please let me know if you need anything.
I have a few customers suffering from this issue atm.

**Comment by richardrobberse** [comment]
Alright, I'll use the Hyper-V workaround for now. Thanks!

**Comment by richardrobberse** [comment]
It's important to mention that not all Azure VM Sizes support nested virtualization which is required in order to use Hyper-V isolation.
It seems that only Dv3 and Ev3 VM's support it.

**Comment by pmoison** [comment]
Hi,
Experienced the same issue. All containers created with isolation process encounter somme issues.
Is there a way to change isolation  of a container without to recreate it with isolation hyperv ?

**Comment by freddydk** [comment]
You cannot change isolation mode on a running container, no - you need to recreate it.

**Comment by freddydk** [comment]
A bit more detail here: https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/

**Comment by lvanvugt** [comment]
@freddydk in your post you mention:

> you need to pull new ones. Latest master build (next major) is 16.0.11119.0

On a today newly create Azure VM (Windows Server 2019) it seems to pull an older one:

> Creating Container D365BC16NavUser
> Version: 16.0.11154.0-us
> Style: sandbox
> Platform: 16.0.11116.0

What need I do to get 16.0.11119.0?

My script is calling this image: $bcdockerimage = 'bcinsider.azurecr.io/bcsandbox-master:us'

**Comment by freddydk** [comment]
The version number is always the app version number as multiple app builds might share the same platform version number.
Meaning that 16.0.11154.0 is newer than 16.0.11119.0, so you are good.

**Comment by lvanvugt** [comment]
Thanx, so not the plaform.

Any tips on the error? Or in general: what might be the reason that my container is not getting created with -isolation hyperv?

**Comment by freddydk** [comment]
If you could share the script and the output from that, then I could probably tell you quickly why.

**Comment by lvanvugt** [comment]
Here you go:

> $accept_eula = $true
> $accept_outdated = $true
> 
> $licenseFile = ...
> 
> $containerName = 'D365BC16NavUser'
> $bcdockerimage = 'bcinsider.azurecr.io/bcsandbox-master:us'
> docker login "bcinsider.azurecr.io" -u .... -p ...
> 
> $login = ...
> $password = ...
> $securepassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
> $credential = New-Object System.Management.Automation.PSCredential($login, $securepassword)
> 
> New-BCContainer -accept_eula:$accept_eula `
>                 -containerName $containerName `
>                 -imageName $bcdockerimage `
>                 -includeTestToolkit `
>                 -licenseFile $licenseFile `
>                 -auth NavUserPassword `
>                 -credential $credential `
>                 -accept_outdated:$accept_outdated `
>                 -EnableTaskScheduler:$false `
>                 -isolation hyperv

Have "anonymized" using _three dots_.

**Comment by freddydk** [comment]
Could you mark the code as code (insert code above) then I can see whether all lines are terminated by a tilde. and other special characters. The character you have after enabletaskscheduler looks to be wrong.

**Comment by lvanvugt** [comment]
Sorry, touched the wrong action (insert a quote). Note that if I leav out the -isolation hyperv the error occurs. The enableTaskScheduler part wasn't an issue before.

**Comment by freddydk** [comment]
Yes, the character at the end of the line determines whether the next line is included and without hyperv - the error occurs.
Note that if you are using C/AL and objects - you might be better off uninstalling the february update - hyperv might cause issues with non-unicode apps (C/SIDE)

**Comment by lvanvugt** [comment]
> Yes, the character at the end of the line determines whether the next line is included and without hyperv - the error occurs.

Nope when I leave out the `-isolation hyperv` part including the character at the preceding line everything goes fine (except I cannot access the container, which I recon is due to the security update).
When I include  the `-isolation hyperv` part (including the character at the preceding line) I get the error as listed above.
> Note that if you are using C/AL and objects - you might be better off uninstalling the february update - hyperv might cause issues with non-unicode apps (C/SIDE)

Yep, thanx. Ran into that straight away last Thursday (see my reply to your tweet including the screenshot of our Azure Devops dashboard)

**Comment by freddydk** [comment]
hyper-v might be enabled, but your VM might not support it.
Robberse's blog post describes this scenario too - looks like that is the issue here.

**Comment by richardrobberse** [comment]
@freddydk @lvanvugt Freddy is right, it seems that your VM doesn't support nested virtualization.

**Comment by lvanvugt** [comment]
Read the post and as described above

> On a today newly create Azure VM (Windows Server 2019 with hyperv active) ...

Probably I do not understand the message of the blogpost, but this is what my VM shows me, and I would say it has HyperN active:

![image](https://user-images.githubusercontent.com/18466198/74638744-cc0ddd80-516c-11ea-90e6-2c61ae032015.png)

**Comment by richardrobberse** [comment]
I think it can be installed even though the VM doesn't support it.
A reboot might be required, have you tried rebooting the server?

**Comment by freddydk** [comment]
What Azure machine size did you select ?

**Comment by lvanvugt** [comment]
> 
> 
> I think it can be installed even though the VM doesn't support it.
> A reboot might be required, have you tried rebooting the server?

Yes, has been rebooted. And BTW: Hyper was already installed.

**Comment by lvanvugt** [comment]
> What Azure machine size did you select ?

![image](https://user-images.githubusercontent.com/18466198/74639061-7b4ab480-516d-11ea-8dfa-a5629345cbba.png)

**Comment by freddydk** [comment]
I don't think v2 machines doesn't support nested virtualization
I think you need v3

**Comment by richardrobberse** [comment]
You'll need v3 indeed:
[(https://docs.microsoft.com/nl-nl/azure/virtual-machines/windows/acu)]

**Comment by lvanvugt** [comment]
OK, clear. Had a hard interpreting that info. Thanx for your input, gents.

**Comment by pkoutsogilas** [comment]
Is this also going to be the solution [https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im](https://support.microsoft.com/en-us/help/4542617/you-may-encounter-issues-when-using-windows-server-docker-container-im) for eventually running NAV/BC dockers in -isolation process? Or is isolation not going to be supported by NAV/BC dockers going forward? Or is the solution in the link not applicable for NAV/BC dockers?

**Comment by freddydk** [comment]
You might have noticed that NavContainerHelper for quite some time has displayed a warning if the container OS revision number and the host OS revision number doesn't match. The Warning states, that if you encounter issues, you should try Hyperv isolation.
That kind of matches what they state in the article. I will update the container OS in the generic image and new images - but old images will not be updated monthly.
Process isolation will still be possible, but hyperv is probably more stable.

**Comment by pkoutsogilas** [comment]
Thank you Freddy, for the quick answer as always! Yes I noticed that. I will switch to Hyper-V for the time being.
