### ISSUE TITLE
Question: How to set up a container for encryption?

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/navcontainerhelper#845]
Hi Freddy,

we just got caught by an unexpected difference between a sandbox container and a real environment in SaaS.

Running this code in a sandbox container (latest)
```cal
if CryptographyManagement.IsEncryptionEnabled() and 
    CryptographyManagement.IsEncryptionPossible() then
         Value := CryptographyManagement.Encrypt(Value);
```
does not attempt to encrypt anything. 

The same code running in our solution on AppSource does attempt to encrypt. It fails there, I suppose because of a platform error, but that is of no concern here.

I assume we should have made sure our container is as closely resembling a true environment. In this case it was not properly configured for encryption.

**So, question:** what is the best way to enable encryption in a container as close to the real service as possible?

(Normally our automated tests would have failed right away if the sandbox container would also have attempted encryption. That way this code would never have gone to production, we would have filed a bug ages ago instead. The joy of hindsight... :-) )

**Comment by freddydk** [comment]
Will check with the team

**Comment by freddydk** [comment]
Had a quick look, I guess this https://divyeshchittenavbc.wordpress.com/2019/10/27/how-to-enable-data-encryption-in-business-central-wave-2-release-msdyn365bc/ explains how to set it up, right?
Not sure how to automate this.

**Comment by RafaelKoch** [comment]
I set that up last time about 2 years ago - but it sounds about right.
BUT I tried to do just that now and the page is not editable on a sandbox container.

From my menory, might not be true: I think there has to be some setup on the Service Tier before that page becomes editable.

Anyway: It would be superb if sandbox containers would support this right away, because we want to use them for testing as close to the service as possible, Yet I guess there would be no need to retain that encryption key file. Any container will be discarded anyway and nobody should require to retain its database data,

**Comment by WaelAbuSeada** [comment]
Encryption is enable on SaaS tenants by default. 

For OnPrem/Container, you would need to follow this:
https://docs.microsoft.com/en-us/dynamics-nav/how-to-enable-and-disable-encryption-keys

**Comment by RafaelKoch** [comment]
thanks, but I am afraid this adds nothing to this issue.

**Comment by freddydk** [comment]
Rafael as a test, could you try to call:

CryptoManagement.EnableEncryption(True); 

after setting up the container

**Comment by RafaelKoch** [comment]
I did and it appears to work!

Cryptography Management is set to be active and testing a too long string goes to the expected error which it would not otherwise.

So the answer to my question is: a helper app needs to do this. Are You going to teach containerhelper the trick? Easy enough to cater for this need myself, but other people will not be aware and on a sandbox I guess switching it on should be a default. 

![image](https://user-images.githubusercontent.com/25029667/74451112-6c1eea80-4e7f-11ea-89fa-c04e2b22c56c.png)

**Comment by freddydk** [comment]
I tend to agree - will see what I can do.
Thanks for proving that this works.
Will keep the issue open until I fix this or decide that I can't.

**Comment by freddydk** [comment]
These two lines:
```
Publish-NavContainerApp -containerName bingmaps-dev -appFile "https://bcdocker.blob.core.windows.net/public/Microsoft_EnableEncryption_15.0.0.0.app" -skipVerification -sync -install
UnPublish-NavContainerApp -containerName bingmaps-dev -appName EnableEncryption -unInstall -force
```
Will enable encryption by publishing an app, which does the trick and removing it again.

**Comment by freddydk** [comment]
App is here https://dev.azure.com/businesscentralapps/_git/EnableEncryption

**Comment by RafaelKoch** [comment]
So the way finally is to do this by helper app - fine for me, will work. 
We will implement this into our pipelines and be done. Hope not too many others stumble over it :)

**Comment by freddydk** [comment]
I might add a parameter or a function to make it easier, but that will do the above.
like creating test users, I cannot really do it in other ways.
