### ISSUE TITLE
Sign-NavContainerApp "Cannot locate signtool.exe after installation" resurfacing again

### ISSUE THREAD

**Issue by gregoral** [microsoft/navcontainerhelper#846]
This is the exact same issue as #633.
Appeared to us today.

Sandbox Image: mcr.microsoft.com/businesscentral/sandbox:14.5.35970.37681-w1
Navtoolbox: 0.6.4.26  ( NavContainerHelper 0.6.4.26 is installed )

winsdksetup.exe was downloaded without any issues, but it just did not run inside the container.
I tried running it manually inside the container, but it just silently exits.

```
Downloading Signing Tools
Installing Signing Tools
Cannot locate signtool.exe after installation
at <ScriptBlock>, <No file>: line 20
##[error]Get-ChildItem : Cannot locate signtool.exe after installation
```
I  copied winsdksetup.exe out of the container to the host and signtool.exe was installed without issues.
winsdksetup.exe version: 10.1.17763.1

I resolved the issue by:
- installing signtool.exe on the host.
- copying the WinSdk folder from host to container just after the container is created
- if signtool is there, signing works without issues

The VM where the agent runs is installed in azure cloud.
There were no problems like this up to this point.

I was able to execute the build pipeline at one point.
Then after server restarted I was not able to run it again.

We have not changed anything between runs.
Were the docker images updated for some reason?
I see that our 15.0.36590.0 has been pulled again.
( this seems strange, we build against this image every day )

A windows update might have been installed between the successful and unsuccessful runs.

```

Docker Server Version is 18.09.2
Pulling image mcr.microsoft.com/businesscentral/sandbox:w1-ltsc2019
w1-ltsc2019: Pulling from businesscentral/sandbox
Using image mcr.microsoft.com/businesscentral/sandbox:w1-ltsc2019
Creating Container bld-1910
Version: 15.2.39558.40594-w1
Style: sandbox
Platform: 15.0.39461.40546
Generic Tag: 0.0.9.98
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1039 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\vstsAgent\_w\_temp\!AD.BC15.onprem - AdLoc+AdMfg+AdInv+AdPay on 13M range - 150.user valid until 2020 03 22.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bld-1910\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
```

**Comment by freddydk** [comment]
The symptom is the same as #633, but the cause is probably that you got an windows update overnight.
I have seen a few others have problems with the latest Windows Update - and adding -isolation hyperv solved all other problems.
Are you running windows 10 or windows server 2019 - I will try to repro.

**Comment by gregoral** [comment]
We're using windows server 2019.

The issue is that WinSdk does not install.
If I install it before the Sign-NavContainerApp.ps1 runs, then the build process completes successfully.
I don't see any errors if I try to install the sdk from powershell, but it just does nto install.

Networking appears to work without any issues.
I can ping from the container, winsdk gets downloaded, ...
I wasn't able to find any apparent issue with networking.
Could it be something with the container OS not trusting the winsdksetup.exe?
Maybe some signature checking issue?

Why do you think -isolation hyperv might solve the issue?
I will try to test, but it is not easy, the script to create the build container is in our build tools repository.

I will try to replicate / test outside the build agent pipeline.

**Comment by freddydk** [comment]
a few days ago, update 1039 to windows server 2019 has shipped and this has caused issues for people running BC/NAV containers - a lot of different problems. (I can see above that you are running 1039). Apparently hyperv isolation solves a lot of the issues.
I am investigating the root cause - and will check the sign issue as well.

**Comment by freddydk** [comment]
Managed to get a windows server 2019 update 1039 created and yes, I can repro this problem.
Running with hyperv isolation solves the issue on my machine.

I don't know what has happened - but I might need to talk to somebody from the Windows team to see whether they have increased some security settings or like, this might take some time.

**Comment by freddydk** [comment]
This was indeed because of the Security Update. Read more about it here: https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/
You can use Hyperv or uninstall the February Security Update,

**Comment by gregoral** [comment]
Using -isolation hyperv appears to help.

However there are issues with it:
- builds appear to take much longer
- build on 14.5 fails with:
  ##[error]Invalid reference module: Exception of type 'System.OutOfMemoryException' was thrown.

This is why I hate forced windows updates.
I will test more, but our builds are not stable even with hyperv isolation.

**Comment by freddydk** [comment]
Containerhelper will limit the memory to 3gb when using hyperv. You can change this with -memorylimit

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Gregor Alujevic <notifications@github.com>
Sendt: Monday, February 17, 2020 12:21:24 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Freddy Kristiansen <Freddy.Kristiansen@microsoft.com>; Comment <comment@noreply.github.com>
Emne: Re: [microsoft/navcontainerhelper] Sign-NavContainerApp "Cannot locate signtool.exe after installation" resurfacing again (#846)


Using -isolation hyperv appears to help.

However there are issues with it:

  *   builds appear to take much longer
  *   build on 14.5 fails with:
##[error]Invalid reference module: Exception of type 'System.OutOfMemoryException' was thrown.

This is why I hate forced windows updates.
I will test more, but our builds are not stable even with hyperv isolation.
