### ISSUE TITLE
Error creating container for BC 2019 Spring Release CU 9

### ISSUE THREAD

**Issue by JJODonovan** [microsoft/navcontainerhelper#847]
I am unable to create a container for the latest BC 2019 Spring Release Cumulative Update 9 release.  I get the same "Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time." error (SetupSqlUsers.ps1: line 13) on the W1 and the NL versions.   

I have pasted the full output below for reference: 

NavContainerHelper is version 0.6.4.26
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1903
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/onprem:14.10.40471.0-nl-ltsc2019
Removing BC14-10-40471-nl from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\BC14-10-40471-nl
Creating Container BC14-10-40471-nl
Version: 14.10.40471.0-nl
Style: onprem
Platform: 14.0.40464.0
Generic Tag: 0.0.9.98
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.18362.592 (1903)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale nl-NL
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file ...
Files in C:\ProgramData\NavContainerHelper\Extensions\BC14-10-40471-nl\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container BC14-10-40471-nl from image mcr.microsoft.com/businesscentral/onprem:14.10.40471.0-nl-ltsc2019
415d0f3622e810b5dadcddf10cd2318cf2bf47a136d0c2cbcab048fa0d80f8e3
Waiting for container BC14-10-40471-nl to be ready
Initializing...
Setting host.docker.internal to 192.168.1.33 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.33 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.20.16.1 in container hosts file
Starting Container
Hostname is BC14-10-40471-nl
PublicDnsName is BC14-10-40471-nl
WARNING: DNS resolution not working from within the container.
WARNING: Container starts with TimeZone = West-Europa (standaardtijd), which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 5038AC7FDAAEF1285CA4D98D9883B5AEB1BC0DD0
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to re
spond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=27721; handshake=18063; 
at <ScriptBlock>, C:\Run\SetupSqlUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 183
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.docker.internal to 192.168.1.33 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.33 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.20.16.1 in container hosts file
Starting Container
Hostname is BC14-10-40471-nl
PublicDnsName is BC14-10-40471-nl
WARNING: DNS resolution not working from within the container.
WARNING: Container starts with TimeZone = West-Europa (standaardtijd), which is not recognized in the list of TimeZones.
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 5038AC7FDAAEF1285CA4D98D9883B5AEB1BC0DD0
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to re
spond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=27721; handshake=18063; 
at <ScriptBlock>, C:\Run\SetupSqlUsers.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 183
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container BC14-10-40471-nl failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...40471-nl failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container BC14-10-40471-nl failed

**Comment by freddydk** [comment]
2 things to try out:
- Make sure DNS resolution works from within the container (search dns here: https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/)
- Not sure which password you used - but if it was a very simple password, that might be the reason

If these doesn't work - please provide the PS command you used to create the container (and the output above)

**Comment by JJODonovan** [comment]
I don't think it's the password as I don't use a simple string. 
I've added the dns switch to the script I use to create the container but still get a warning that DNS resolution is not working from within the container.  I also get this warning when creating a container for older versions and these are created without any issues.  I have included my script below for reference.  (I am able to successfully run this for $MainReleaseNo = 14, $CumulUpdateNo = 9, $NAVVersionNo  = 39327, $CountryCode = "nl")

$MainReleaseNo = 14
$CumulUpdateNo = 10
$NAVVersionNo  = 40471
$CountryCode = "nl"

$imagename = "mcr.microsoft.com/businesscentral/onprem:" + $MainReleaseNo + "." + $CumulUpdateNo + "." + $NAVVersionNo + ".0-" + $CountryCode
$containerName = "BC" + $MainReleaseNo + "-" + $CumulUpdateNo + "-" + $NAVVersionNo + "-" + $CountryCode

$credential = get-credential -UserName "admin" -Message "Enter NAV Super User Credentials"

docker rm $containerName -f
New-NavContainer -containerName $ContainerName `
       -accept_eula `
       -accept_outdated `
       -auth NavUserPassword `
       -credential $credential `
       -dns '8.8.8.8' `
       -doNotExportObjectsToText `
       -imageName $imagename `
       -includeCSide `
       -updateHosts

**Comment by freddydk** [comment]
I try to repro, thanks

**Comment by freddydk** [comment]
We are looking for something that is specific to your machine. Run your exact script:
![image](https://user-images.githubusercontent.com/10775043/74438187-e6447480-4e69-11ea-936f-5f9cc6bbbbfa.png)
If you are on a corporate network, using 8.8.8.8 as dns might not work - you could try the dns from the host.
Are you (or have you been) able to create other containers on that machine?

**Comment by JJODonovan** [comment]
I've managed to get it to work using 8.8.8.8 as the dns while logged in on my domain network.  It doesn't work from my home network (which is what I was using this morning).  What I don't understand is why this would matter as the sql server is located within the docker container in this instance...  But thanks for your help on this - I'm glad that it's working now.

**Comment by freddydk** [comment]
I don't know sorry.
You can enter DNS' for home+work you use in the daemon configuration, then it will work both places (without the parameter on new-navcontainer)
