### ISSUE TITLE
Compile-NAVApplicationObjects throw error

### ISSUE THREAD

**Issue by StefanMartinEnjoy** [microsoft/navcontainerhelper#849]
Hey,

I hope  I'm right here.

Up to this week I get the error message:
!
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Compile-NAVApplicationObject

when I run Compile-NAVApplicationObject -DatabaseName Cronusde -NavServerInstance $containername -Recompile -SynchronizeSchemaChanges Force on NAV 2016 or NAV 2017 on docker images.

I tried to restart the images and also the host computer. I updated NAVContainerHelper.
But, I don't know why there is a WriteErrorExeption

**Comment by freddydk** [comment]
If you can provide a full script, which reproduces the problem, then I might be able to help

Hent Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: Stefan Martin <notifications@github.com>
Sendt: Friday, February 14, 2020 12:08:44 PM
Til: microsoft/navcontainerhelper <navcontainerhelper@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Emne: [microsoft/navcontainerhelper] Compile-NAVApplicationObjects throw error (#849)


Hey,

I hope I'm right here.

Up to this week I get the error message:
!
+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Compile-NAVApplicationObject

when I run Compile-NAVApplicationObject -DatabaseName Cronusde -NavServerInstance $containername -Recompile -SynchronizeSchemaChanges Force on NAV 2016 or NAV 2017 on docker images.

I tried to restart the images and also the host computer. I updated NAVContainerHelper.
But, I don't know why there is a WriteErrorExeption

**Comment by StefanMartinEnjoy** [comment]
Hey Freedy,

the Skript contain only two lines, which I run line per line.

Enter-NAVContainer -containername navserver

Compile-NAVApplicationObject -DatabaseName Cronusde -NavServerInstance navserver -Recompile -SynchronizeSchemaChanges Force

**Comment by StefanMartinEnjoy** [comment]
Hey Freedy,

I did the same and also for several other docker containers the last 6 month. Allways, it works fine.
But since this week I get that error message and also for several docker containers.

Regards
Stefan

**Comment by freddydk** [comment]
Ok, that is probably caused by the February 11th Security Update for Windows then.
https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue

**Comment by richardrobberse** [comment]
This is indeed caused by the security update.

**Comment by freddydk** [comment]
Options are to use HyperV or uninstall February Security Update. Using HyperV will cause issues with non-unicode apps and a lot has been done in navContainerHelper to make sure that non-unicode C/AL text files are handled correctly, but you might get other issues,
If you are using C/AL - my recommendation is to uninstall February Security Update.
