### ISSUE TITLE
Error with Compile-ObjectsInNavContainer command

### ISSUE THREAD

**Issue by Oufaraj** [microsoft/navcontainerhelper#850]
Hi,

 It's my first time that I'm working with NavContainerHelper, I'm trying to compile modified objects by executing the command : "Compile-ObjectsInNavContainer -containername navserver -SynchronizeSchemaChanges Yes" where navserver is my server name but I'm getting the error : 

Compiling objects with compiled=0
Generating symbols for objects compiled
!
at Compile-NAVApplicationObject, C:\Program Files (x86)\Microsoft Dynamics NAV\140\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 610
at <ScriptBlock>, <No file>: line 30
!
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.1.5\ContainerHandling\Invoke-ScriptInNavContainer.ps1:30 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Compile-NAVApplicationObject
    + PSComputerName        : c56f86632ba94bba3fc81f41f5cb11e573b0d22d4b1ab8977e66dcf8e44b3df0

when Im restarting the navcontainer I get the warning : You are running a container which is 274 days old. it could be the origin of the problem ?

**Comment by freddydk** [comment]
If you only get a warning - that's fine - you must have started the container using accept_outdated.
I am afraid you are hit by https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/ - I saw another issue around writeerror, which was caused by this. You could uninstall the february security update and retry.

**Comment by Oufaraj** [comment]
it works after uninstalling the february security, Thanks Freddydk.
