### ISSUE TITLE
 Compile-ObjectsInNavContainer command in NavContainerhelper

### ISSUE THREAD

**Issue by Oufaraj** [microsoft/navcontainerhelper#851]
Hi,

 I'm trying to compile objects by running the Compile-ObjectsInNavContainer command command but I'm getting the error : 

: [27590710] Unable to process table changes because the Microsoft Dynamics NAV Development Environment cannot connect to the specified Microsoft Dynamics NAV Server instance:
Server Name:
Server Instance:
Management Port: 0
Microsoft Dynamics NAV Development Environment will detect a running server automatically.
Check that:
. The Microsoft Dynamics NAV Server is running
. The management service is configured
. The firewall is open for the management port if remote
. The server is running with only one tenant
. Microsoft Dynamics NAV Development Environment is running as Administrator, or
. UAC is turned off.

  As you can see the Server name and the Server instance are empty, it could be the source of the error ? if yes how can I configure these parameters in the container ?

**Comment by freddydk** [comment]
In order to be able to help, I need a lot more information than just the error,
If possible, a simplified PS script, which shows the problem, and the full output of that command. like:
```
$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
$licenseFile = "c:\temp\license.flf"
New-NavContainer -accept_eula -accept_outdated -containerName test -imageName mcr.microsoft.com/dynamicsnav:2018 -updateHosts -auth UserPassword -Credential $credential -licenseFile $licenseFile
Compile-ObjectsInNavContainer -containerName test -sqlCredential $credential -filter 'Type=Codeunit'

NavContainerHelper is version 0.6.4.27
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/dynamicsnav:2018-ltsc2019
Removing container test
Removing test from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\test
Creating Container test
Version: 11.0.40505.0-W1
Style: onprem
Generic Tag: 0.0.9.98
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.18363.657 (1909)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale en-US
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file c:\temp\license.flf
Downloading C:\ProgramData\NavContainerHelper\Extensions\test\my\license.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\test\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container test from image mcr.microsoft.com/dynamicsnav:2018-ltsc2019
6131602fec0bffa17ffd7e85ddb0664669ad2f0f8a9353f2bd335dd5a77bc7aa
Waiting for container test to be ready
Initializing...
Setting host.docker.internal to 192.168.0.16 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.16 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.18.32.1 in container hosts file
Starting Container
Hostname is test
PublicDnsName is test
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FD610D6840EB1A34C01DC601EE8FF4D8F3AD1C54
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.18.41.126
Container Hostname  : test
Container Dns Name  : test
Web Client          : http://test/NAV/
Dev. Server         : http://test
Dev. ServerInstance : NAV
Setting test to 172.18.41.126 in host hosts file

Files:
http://test:8080/al-0.13.195601.vsix

Initialization took 43 seconds
Ready for connections!
Reading CustomSettings.config from test
Creating Desktop Shortcuts for test
Container test successfully created
Compiling objects with Type=Codeunit
Objects successfully compiled
```
This shows me which authentication method you are using, which isolation mode the container is running, which image you are using etc etc etc. - and it gives me an option to repro and see whether the issue is local to your machine - or you are looking at a problem in the script.

**Comment by Oufaraj** [comment]
Hi, 
 Here the result : 
NavContainerHelper is version 0.6.1.5
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Pulling image mcr.microsoft.com/dynamicsnav:2018-ltsc2019
2018-ltsc2019: Pulling from dynamicsnav
65014b3c3121: Already exists
edbd72df76b4: Pulling fs layer
c874897f6f76: Pulling fs layer
587a89803944: Pulling fs layer
.....
.....
.....

Still waiting for the last command.

**Comment by Oufaraj** [comment]
Hi,
Here the result, Objects successfully compiled : 

NavContainerHelper is version 0.6.1.5
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.6
Docker Server Version is 18.09.6
Using image mcr.microsoft.com/dynamicsnav:2018-ltsc2019
Removing C:\ProgramData\NavContainerHelper\Extensions\test
Creating Container test
Using license file c:\temp\license.flf
Version: 11.0.40505.0-W1
Generic Tag: 0.0.9.98
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.973 (ltsc2019)
Using process isolation
Creating container test from image mcr.microsoft.com/dynamicsnav:2018-ltsc2019
5f1845de99456f75185706bd006d1bef4f6122b98afb6bcf4d7eb0df462ac50c
Waiting for container test to be ready
Initializing...
Starting Container
Hostname is test
PublicDnsName is test
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint AC6F159B1E7C2A0DDA747F12EDD86060D1968590
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements.
It should be at least 8 characters long and contain at least one uppercase
letter, one lowercase letter, and one number.
Container IP Address: 172.24.**.***
Container Hostname  : test
Container Dns Name  : test
Web Client          : http://test/NAV/
Dev. Server         : http://test
Dev. ServerInstance : NAV

Files:
http://test:8080/al-0.13.195601.vsix

Initialization took 88 seconds
Ready for connections!
Starting EventLog Monitor
Reading CustomSettings.config from test
Creating Desktop Shortcuts for test
Container test successfully created
PS C:\ProgramData\navcontainerhelper> Compile-ObjectsInNavContainer -containerName test -sqlCredential $credential -filter 'Type=Codeunit'
Compiling objects with Type=Codeunit
Objects successfully compiled

**Comment by freddydk** [comment]
So, there seems to be nothing wrong with your machine. Now you need to find out what the difference is to your script and make it work.
