### ISSUE TITLE
Web client URL is redirected

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#852]
Having created a new container (see details below) I am wanting to run the web client using the "container shortcut" on the desktop. It launches the web browser that clearly shows the expected URL with the following format (as is defined as the target of the shortcut):

`http://<container name>/<service tier name>/`

But the web client does not open and (/as?) the browser gets redirected to:

`http://www.<container name>.com/<service tier name>/`

The browser displays the _Server not _found error__.

What is going wrong and why? (Or what am I doing wrong?)

**Container details**
- BC16 insider image
- HyperV isolation set
- NavUserPassword
- same VM as discssued on #844, HyperV now working

**Comment by freddydk** [comment]
If you provide the script - it is easier to check what you are missing.
https://freddysblog.com/2019/08/20/business-central-on-docker-for-non-experts/
My guess is that you are missing -updateHosts

**Comment by lvanvugt** [comment]
Sorry, for not having shared the script here. It's the same as the obe I shared on #843 

```
$accept_eula = $true

$accept_outdated = $true

$licenseFile = ...

$containerName = 'D365BC16NavUser'
$bcdockerimage = 'bcinsider.azurecr.io/bcsandbox-master:us'
docker login "bcinsider.azurecr.io" -u .... -p ...

$login = ...
$password = ...
$securepassword = (ConvertTo-SecureString -String $password -AsPlainText -Force)
$credential = New-Object System.Management.Automation.PSCredential($login, $securepassword)

New-BCContainer -accept_eula:$accept_eula `
                -containerName $containerName `
                -imageName $bcdockerimage `
                -includeTestToolkit `
                -licenseFile $licenseFile `
                -auth NavUserPassword `
                -credential $credential `
                -accept_outdated:$accept_outdated `
                -enableTaskScheduler:$false `
                -isolation hyperv
```
-UpdateHost indeed is not part of it. Rerunning the script now with this parameter. The reason why it was not in the script, was that it worked without another my previous VM.
Will let you know the outcome soon.

**Comment by lvanvugt** [comment]
Update: is working right, now. Thanx @freddydk. Still makes me wonder why one -UpdateHost is not needed in all cases.
