### ISSUE TITLE
Creation of container failed includeTestToolkit parameter

### ISSUE THREAD

**Issue by eclipses** [microsoft/navcontainerhelper#853]
Hi Freddy,

I'm creating a new BC container with the image mcr.microsoft.com/businesscentral/onprem:13.7.31809.0-gb, the creation of the container works but after when importing the testtoolkit objects is failing 

`!
at Import-NAVApplicationObject<Process>, C:\Program Files (x86)\Microsoft Dynamics NAV\130\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 147
at <ScriptBlock>, <No file>: line 35
at <ScriptBlock>, <No file>: line 21
!
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-NAVApplicationObject

**Comment by freddydk** [comment]
Pretty sure you are hurt by https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/

**Comment by eclipses** [comment]
Hi Freddy, 

I was aware of the issue with windows update but it does not seem my case.

Running the creation with isolation hyperv it does not work in my server, docker returns an error "The request is not supported."

With isolation and empty string, it fails at the step that I told you.

Could you please verify if you can reproduce using same image and -includeTestToolkit?

It's an old image, should I delete it and pull it again? Do anything with the installation of docker?

**Comment by freddydk** [comment]
If you send me the full command - and the full output from your machine - then I can run and compare.

**Comment by eclipses** [comment]
Sure, this is the script:

`$containerName = 'SCA'
$containerImage = 'mcr.microsoft.com/businesscentral/onprem:13.7.31809.0-gb'
$licenseFile = "C:\BC Licenses\BC15W1.flf"

New-NavContainer -accept_eula `
                 -accept_outdated `
                 -containerName $containerName `
                 -imageName $containerImage `
                 -auth 'NAVUserPassword' `
                 -updateHosts `
                 -includeCSide `
                 -doNotExportObjectsToText `
                 -enableSymbolLoading `
                 -includeTestToolkit `
                 -useBestContainerOS `
                 -licenseFile "$licenseFile" `

this is the output:

`NavContainerHelper is version 0.6.4.26
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/onprem:13.7.31809.0-gb-ltsc2019
Creating Container SCA
Version: 13.7.31809.0-gb
Style: onprem
Platform: 13.0.31719.0
Generic Tag: 0.0.9.6
Container OS Version: 10.0.17763.437 (ltsc2019)
Host OS Version: 10.0.17763.1039 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-GB
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\NAV BC Licenses\BC15W1.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\SCA\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container SCA from image mcr.microsoft.com/businesscentral/onprem:13.7.31809.0-gb-ltsc2019
0cbbc231ff6efdd7d8c345e2b041022f3426d2eb7d3e5b75132e0503be9d484e
Waiting for container SCA to be ready
Initializing...
Setting host.containerhelper.internal to 172.26.160.1 in container hosts file
Starting Container
Hostname is SCA
PublicDnsName is SCA
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint FBB00B44896E75B7ACF6B700E5D8F8B666E002DB
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.26.162.189
Container Hostname  : SCA
Container Dns Name  : SCA
Web Client          : http://SCA/NAV/
Dev. Server         : http://SCA
Dev. ServerInstance : NAV
Setting SCA to 172.26.162.189 in host hosts file

Files:
http://SCA:8080/al-2.1.119251.vsix

WARNING: You are running a container which is 298 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 81 seconds
Ready for connections!
Reading CustomSettings.config from SCA
Creating Desktop Shortcuts for SCA
Importing Objects from C:\TestToolKit\CALTestCodeunits.GB.fob (container path)
Generating Symbols while importing
!
at Import-NAVApplicationObject<Process>, C:\Program Files (x86)\Microsoft Dynamics NAV\130\RoleTailored Client\Microsoft.Dynamics.Nav.Ide.psm1: line 147
at <ScriptBlock>, <No file>: line 35
at <ScriptBlock>, <No file>: line 21
!
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-NAVApplicationObject
    + PSComputerName        : 0cbbc231ff6efdd7d8c345e2b041022f3426d2eb7d3e5b75132e0503be9d484e`

**Comment by freddydk** [comment]
I don't need to try this.

Host OS Version: 10.0.17763.1039 (ltsc2019)
+
Using process isolation

Does not work.

Either uninstall february security update - or use hyperv

**Comment by eclipses** [comment]
Hi Freddy, 

It worked in my pc, I cannot test in the servers because the virtualization is not enabled yet. I'm closing this issue, thanks again for your support.
