### ISSUE TITLE
[Question] Creating Database in Business Central with customized Base Application (On-Prem)

### ISSUE THREAD

**Issue by g-franck** [microsoft/navcontainerhelper#854]
Hi,

I posted this [question](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb/issues/997) on [dynamics365smb-devitpro-pb](https://github.com/MicrosoftDocs/dynamics365smb-devitpro-pb) repository but I'm not sure it's the best place.
My question is close to navcontainerhelper, Publish-NewApplicationToBcContainer etc... context, on which I have already worked these last months.
So that's why I'm putting it back here, hoping a life-saving response.

I followed the [Creating Databases in Business Central](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/devenv-create-databases) documentation to build a Dynamics 365 Business Central wave 2 On-Premises environment with my own customized **Base Application** (with own id).
I also used [Provisioning the Business Central Server Service Account](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/provision-server-account) documentation to create my server instance, together with [Setting Up Multiple Business Central Web Server Instances Using PowerShell](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/deployment/configure-multiple-web-server-instances) documentation to create the corresponding web server instance.
I can access to this new environment with the WebClient, no problem.

### Question:
Are these documentations recommended/enough for building this kind of environment with an own customized **Base Application**, or should I take into consideration others best practices / documentations ?

My environment works but as you can imagine, my database is empty, application tables (ex: Permission Set, _only SUPER_, etc...), business tables, and my own customized **Base Application** tables (ex: Customer, Item, etc...) have no data.
I would like to include data, as Cronus, but I didn't find any rapidstart package in the install DVD zip.
So I used those from the closest sandbox image.

### Question:
What are the best practices / documentations to reach this goal (ex: full Permission Set list, etc... as Cronus, and Customer, Item, etc... as we can find in standard, evaluation or extended packages) ?

I hope you understand what I "expect", something like this really useful documentation, [Publishing a New Base Application](https://freddysblog.com/2019/09/19/publishing-a-new-base-application/), but for an On-Premises context.

For the moment I only had technical local issues, but soon we will have to ask ourselves questions about customers environments (Dev, Test, Prod), apps dependencies (ex: APIV1, Intelligent Cloud etc...), then later on migration to V16 and more.

I know that extensions model is the only right way, but in my case, they don't give me the choice, so, as much do things right.

Thanks a lot for your feedback.
Cordially

**Comment by freddydk** [comment]
If you are publishing a new base application for on-premises, you could just reuse name and appid from MS baseapp - and your data should still be there (an upgrade from MS base app to your base app).
It is kind of like importing a .fob file in the "old" days.
wrt rapidstart - everything on the docker images comes from the DVD - there should be a folder called configurationPackages on the DVD as far as I remember.

**Comment by g-franck** [comment]
Hi Freddy,
Thanks for your feedback.
To be clearer, my company is part of Ready To Go (Mega App) Microsoft program.
Our ISV solution is already on Saas with a customized Base App.
This app has her own id, name, publisher (Microsoft recommandations).

So, do you mean if we want to install this .app "as is" for an On-Prem context, we only have to keep id, name and publisher from MS Base App ?
Cordially.

**Comment by freddydk** [comment]
For SaaS we require own id, name and publisher.
For on-prem I don't think we do and it sounds like it would be easier to avoid. Having said that, if you already have the app for SaaS - wouldn't you have demo data there?

**Comment by NAVspecialist** [comment]
As far as I know the Object-range for OnPrem and SAAS cannot be the same.

https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/devenv-object-ranges

So there is more to than just the ID, Name and Publisher..

**Comment by freddydk** [comment]
You are right for normal apps.
If they have a code customized base app with added objects in the partner range - it could be the same.

**Comment by g-franck** [comment]
Indeed, as it stands I could retrieve the demo data from the Saas through the configuration packages, for example.
But that doesn't solve the problem for application tables other than Permissions, Permission Sets, does it ?

But as you say, the easiest way is to manage the .app with the MS Base App id, name and publisher.
This seems to solve many problems in an On-Prem context.
Once again thanks a lot for your time and advices.

**Comment by g-franck** [comment]
I think I also should look deeper into [Application version for aliasing base application](https://docs.microsoft.com/en-us/dynamics365-release-plan/2020wave1/dynamics365-business-central/application-version-aliasing-base-application).

**Comment by freddydk** [comment]
Yes, that will be released in 15.3 (soon to be delivered), but won't help you on the demo data.

**Comment by MikeGlue** [comment]
We're also in the embed app program. For solving the data, I create a new demo company and then load in the (extended) CRONUS demo data using the Configuration Package API.

Freddy's blog covers this quite nicely: https://freddysblog.com/2019/12/09/having-demo-data-while-developing-business-central-apps-with-docker/

This will load all of the core data (customers, items, vendors, etc.) but not the out of box app data. That's my current struggle is how to get that sample data.

Having to change the base app ID has caused no shortage of struggles to our process. :(
