### ISSUE TITLE
WebClient and  SOAP service not available when creating sandbox container.

### ISSUE THREAD

**Issue by ThierryPermentier** [microsoft/navcontainerhelper#857]
Hi Freddy,

We create a docker container using NavContainerHelper as follow:

<pre><code>$accept_eula = $true
$containername = "MyContainer"
$navdockerimage = "mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be"
$appbacpacuri = ""
$tenantbacpacuri = ""

$additionalParameters = @()
if ($appbacpacuri -ne "" -and $tenantbacpacuri -ne "") {
  $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = get-credential -UserName $env:USERNAME -Message "Using Windows Authentication. Please enter your Windows credentials."
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth Windows `
                 -Credential $credential `
                 -licenseFile C:\License.flf `
                 -includeAL `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters
</code></pre>

The image = mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be

The container is created. But the WebClient and the SOAP service is not reachable. The ODATA and DEV services are available. We can publish apps and download symbols. The ports are open end the services are enabled. 

When we take a look to the event viewer from inside the container a error shows up (see ErrorLog.txt)

[EventLog.txt](https://github.com/microsoft/navcontainerhelper/files/4225146/EventLog.txt)

What are we missing? Do we need to setup something else? Use some extra options?

Best regards.

**Comment by freddydk** [comment]
Could you mark the scripts above with insert code from the toolbar

`Like this.
`
Thanks

**Comment by ThierryPermentier** [comment]
Scripts are marked as requested. File with error attached.

Thanks.

**Comment by freddydk** [comment]
It is likely because you are using Windows Authentication.
Try to change to UserPassword auth.

**Comment by ThierryPermentier** [comment]
Creating the container with option UserPassword auth does not solve the problem.

**Comment by freddydk** [comment]
Could you include the full output of the new-navcontainer - it contains a lot of debug info.

**Comment by ThierryPermentier** [comment]
<pre><code>NavContainerHelper is version 0.6.4.26
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be-ltsc2019
Creating Container MyContainer
Version: 15.2.39558.40594-be
Style: sandbox
Platform: 15.0.39461.40546
Generic Tag: 0.0.9.98
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1039 (ltsc2019)
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale nl-BE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\License.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\MyContainer\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container MyContainer from image mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be-ltsc2019
557df0844eabe502fdc48f58bb2080cb30d72b629c40a1ab8863fd7fc14bb29b
Waiting for container MyContainer to be ready
Initializing...
Setting host.containerhelper.internal to 172.26.240.1 in container hosts file
Starting Container
Hostname is MyContainer
PublicDnsName is MyContainer
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 85B5ADDBB3945185DCE38983C7F4F538445F139C
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating TP as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.26.244.73
Container Hostname  : MyContainer
Container Dns Name  : MyContainer
Web Client          : http://MyContainer/BC/
Dev. Server         : http://MyContainer
Dev. ServerInstance : BC
Setting MyContainer to 172.26.244.73 in host hosts file

Files:
http://MyContainer:8080/al-4.0.206840.vsix

Initialization took 131 seconds
Ready for connections!
Reading CustomSettings.config from MyContainer
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\150\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\150\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container MyContainer successfully created
</code></pre>

**Comment by freddydk** [comment]
I can see you are running process isolation and the host has February security update applied (host OS release 1039). This is known to cause strange issues (although I haven't seen this specific issue before).
Could you try to add -isolation hyperv to your new-navcontainer statement?
Thanks
(You can read more about the February security update here: https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/)

**Comment by ThierryPermentier** [comment]
Adding -isolation hyperv as option to new-navcontainer does not solve the problem.

**Comment by freddydk** [comment]
When you have changed something (added -isolation), you need to send me a new output, so that I can see whether anything changed.

I tried this:
```
$accept_eula = $true
$containername = "MyContainer"
$navdockerimage = "mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be"
$appbacpacuri = ""
$tenantbacpacuri = ""

$additionalParameters = @()
if ($appbacpacuri -ne "" -and $tenantbacpacuri -ne "") {
  $additionalParameters = @("--env appbacpac=""$appbacpacuri""","--env tenantBacpac=""$tenantbacpacuri""")
}

$credential = New-Object pscredential 'admin', (ConvertTo-SecureString -String 'P@ssword1' -AsPlainText -Force)
New-NavContainer -accept_eula:$accept_eula `
                 -containername $containername `
                 -auth UserPassword `
                 -Credential $credential `
                 -licenseFile C:\temp\license.flf `
                 -includeAL `
                 -alwaysPull `
                 -doNotExportObjectsToText `
                 -usessl:$false `
                 -updateHosts `
                 -isolation hyperv `
                 -assignPremiumPlan `
                 -shortcuts Desktop `
                 -imageName $navdockerimage `
                 -additionalParameters $additionalParameters
```
With this output:
```
NavContainerHelper is running as administrator
Host is Microsoft  - 1909
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be-ltsc2019
15.2.39558.40594-be-ltsc2019: Pulling from businesscentral/sandbox
Digest: sha256:c022e5ba2c2352600fe1548b34661f1c2bf207741e2c8611361cef82a90c1908
Using image mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be-ltsc2019
Removing C:\ProgramData\NavContainerHelper\Extensions\MyContainer
Creating Container MyContainer
Version: 15.2.39558.40594-be
Style: sandbox
Platform: 15.0.39461.40546
Generic Tag: 0.0.9.98
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.18363.657 (1909)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale nl-BE
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\temp\license.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\MyContainer\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupNavUsers.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container MyContainer from image mcr.microsoft.com/businesscentral/sandbox:15.2.39558.40594-be-ltsc2019
789ac011644d10a96479b27a9c59b3a45f01ddf8928d6b0cc868ab204e509d3e
Waiting for container MyContainer to be ready
Initializing...
Setting host.docker.internal to 192.168.0.16 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.0.16 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.18.32.1 in container hosts file
Starting Container
Hostname is MyContainer
PublicDnsName is MyContainer
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 86C9CA6CE2826872FA3E5F88017DEE61F56164DA
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
Assign Premium plan for ADMIN
Container IP Address: 172.18.34.50
Container Hostname  : MyContainer
Container Dns Name  : MyContainer
Web Client          : http://MyContainer/BC/
Dev. Server         : http://MyContainer
Dev. ServerInstance : BC
Setting MyContainer to 172.18.34.50 in host hosts file

Files:
http://MyContainer:8080/al-4.0.206840.vsix

Initialization took 143 seconds
Ready for connections!
Reading CustomSettings.config from MyContainer
Creating Desktop Shortcuts for MyContainer
Creating .net Assembly Reference Folder for VS Code
Copying DLLs from C:\Windows\assembly to assemblyProbingPath
Copying DLLs from C:\Program Files\Microsoft Dynamics NAV\150\Service to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Microsoft Dynamics NAV\150\RoleTailored Client to assemblyProbingPath
Copying DLLs from C:\Test Assemblies\Mock Assemblies to assemblyProbingPath
Copying DLLs from C:\Program Files (x86)\Open XML SDK to assemblyProbingPath
Container MyContainer successfully created
```
and WebClient:
![image](https://user-images.githubusercontent.com/10775043/74937288-0c2ec380-53ec-11ea-9d00-6a3cd03b5efc.png)

and SOAP:
![image](https://user-images.githubusercontent.com/10775043/74937377-2ff20980-53ec-11ea-87f1-5c31b457ec55.png)

Works fine...

**Comment by ThierryPermentier** [comment]
Problem was fixed by downloading the latest image of mcr.microsoft.com/windows/servercore:ltsc2019 according to [https://support.microsoft.com/en-ie/help/4542617/you-might-encounter-issues-when-using-windows-server-containers-with-t](url). which contains a resolution for the problem caused by KB4537764 (February Security Update)

**Comment by freddydk** [comment]
Very strange - just by downloading that?
You are not using it. All Docker images are build on a different version and you are using hyperv, meaning you shouldn't be hurt by the February update.
My assumption is that something else made it work.
But... - it works - and that is the main thing.
