### ISSUE TITLE
Question: Installing navcontainerhelper version 0.2.2.5

### ISSUE THREAD

**Issue by ivandjordjevic** [Microsoft/navcontainerhelper#86]
Hi,

Is the 0.2.2.5 version, with multitenancy support released yet?

Installing navcontainerhelper will install only previous version: 0.2.2.4

``
Install-module navcontainerhelper -force
``

Running...
``
Install-Module navcontainerhelper -RequiredVersion 0.2.2.5
``
...will return: _PackageManagement\Install-Package : No match was found for the specified search criteria..._

**Comment by richardrobberse** [comment]
Hey Ivan,

If you check the PowerShelll gallery you can see that 0.2.2.4 is the latest version:
https://www.powershellgallery.com/items?q=navcontainerhelper&x=0&y=0

**Comment by ivandjordjevic** [comment]
Thanks. Any ideas when 0.2.2.5 will be released?

**Comment by richardrobberse** [comment]
I have no idea, I'm not involved in that at all.
Maybe @freddydk can help you with that.

**Comment by freddydk** [comment]
It is not.

You can uninstall and remove it, clone the github project and run the navcontainerhelper.ps1 script, then you have it (you still need access to special build images too.

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ivandjordjevic** [comment]
Great, looking forward to it. Can't wait to try it. Thanks!
