### ISSUE TITLE
Clean-BCContainerDatabase: Error with current BCMaster

### ISSUE THREAD

**Issue by cmuris** [microsoft/navcontainerhelper#863]
When running Clean-BCContainerDatabase on a current BCMaster Container it fails with the following error:
![image](https://user-images.githubusercontent.com/20341187/75029392-4195e880-54a2-11ea-8925-3466c7ddf308.png)

I analyzed this issue and the error occurs in the following code block 

        $installedApps = Get-NavContainerAppInfo -containerName $containerName -tenantSpecificProperties -sort DependenciesLast | Where-Object { $_.Name -ne "System Application" }

        $installedApps | % {
            $app = $_
            Invoke-ScriptInBCContainer -containerName $containerName -scriptblock { Param($app, $SaveData, $onlySaveBaseAppData)
                if ($app.IsInstalled) {
                    Write-Host "Uninstalling $($app.Name)"
                    $app | Uninstall-NavApp -Force -doNotSaveData:(!$SaveData -or ($Name -ne "BaseApp" -and $Name -ne "Base Application" -and $onlySaveBaseAppData))
                }
            } -argumentList $app, $SaveData, $onlySaveBaseAppData
        }

It looks like, that uninstall-navapp does not get the correct tenant information through piping when  tenant is "Default". When you run uninstall-navapp by itself it works perfectly.
I added/changed the code as follows to make it work

        Write-Host "Uninstalling $($app.Name)"
        $tenant = "default"
        if ($app.Tenant)
        {
          $tenant = $app.Tenant
        }

        $app | Uninstall-NavApp -Tenant $tenant -Force -doNotSaveData:(!$SaveData -or ($Name -ne "BaseApp" -and $Name -ne "Base Application" -and $onlySaveBaseAppData))

I didn't test this with a multitenancy container.

**Comment by freddydk** [comment]
Thanks for the very detailed bug and I agree with the suggested fix.

**Comment by freddydk** [comment]
Shipped in 0.6.4.30
