### ISSUE TITLE
Issue in Insider Image

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#864]
Hi,

I download the insider image and create the container. Everything worked fine.
When I try to download the symbol, I got below error
<img width="669" alt="image" src="https://user-images.githubusercontent.com/38437776/75078822-8ed28400-54bb-11ea-863c-47be3ed39142.png">

I have super permission set assigned.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/38437776/75078880-b295ca00-54bb-11ea-82cb-5310b8d9d226.png">

Please help!!

**Comment by freddydk** [comment]
A users permissions are given by the license combined with given user permissions.
As you have SUPER assigned, this must be the license, you probably just need to pull a new license.

**Comment by Bssivivek** [comment]
ok I will check and let you know. Thanks Freedy!!

**Comment by Bssivivek** [comment]
Do we need to generate the new license for Version 16?

**Comment by freddydk** [comment]
Yes

**Comment by TheDenSter** [comment]
https://www.hougaard.com/you-do-not-have-the-following-permissions-on-tabledata-published-application-indirectread/
