### ISSUE TITLE
Export-NavContainerObjects "The folder X is not shared with container Y ..."

### ISSUE THREAD

**Issue by CptBlaubart** [Microsoft/navcontainerhelper#87]
The function Export-NavContainerObjects apparently needs the -objectFolder to be shared with the container. Which makes sense. Unfortunately i was not able to aquire any information in any documentation how to set this up properly. Most blogs are about Linux containers who happen to have completely different way to share folders with docker for windows. And all the tries about sharing the solution for windows containers ended up in unresolved or very confusing troubleshooting.

Can someone help me with this and may i suggest some kind of implemented help with this in this module?

**Comment by CptBlaubart** [comment]
I'm still having issues.
I'm triing to get the Application Objects from NAV 2017-cu9-ch to process it with the NavModelTools.
Here are my commands (I didn't really know what to set in Containerfolder):

New-NavContainer -containerName NAV2017-CU9-CH -imageName microsoft/dynamics-nav:2017-cu9-ch -additionalParameters @("-v c:\temp\X\Docker_share\2017-cu9-ch:c:\temp\share") -accept_eula -licenseFile "X:\myLicense.flf"

Export-NavContainerObjects -containerName NAV2017-CU9-CH -exportTo 'txt file' -objectsFolder C:\temp\X\Docker_share\2017-cu9-ch

Now, I get this error: (sorry, german - It complains that the Container Id doesn't exit... but it does. "docker ps -no-trunc" returns the exact same ID)
Die Eingabe-ContainerId 2a755cd15e7b6f4a80e00cefc500b70ae599963a2abf133f900684fbc0fa17d2 ist nicht vorhanden, oder der entsprechende Container wird nicht ausgeführt.
In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.2.2.4\ContainerHandling\Get-NavContainerSession.ps1:35 Zeichen:24
+ ...  $session = New-PSSession -ContainerId $containerId -RunAsAdministrat ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-PSSession], PSInvalidOperationException
    + FullyQualifiedErrorId : CreateRemoteRunspaceForContainerFailed,Microsoft.PowerShell.Commands.NewPSSessionCommand

Btw i get a very simular error-message if i try to use New-NavContainer with -licenseFile and -includeCSide at the same time. - Should i create another issue for this?

**Comment by garynilsen** [comment]
So I am new to Docker and Navcontainer.  I already downloaded an container and was trying to run Export-NavContainerObjects but it always says: 
PS C:\WINDOWS\system32> Export-NavContainerObjects -containerName BC133 -objectsFolder C:\data -exportTo "txt folder"
The path C:\data is not shared with the container BC133 (nor is any of it's parent folders) 
I was hoping to make a folder available with the container I already have setup, but I can't find any information on that. Is there a way to do this? Or do I need to create a new container with the -v option?
So I figured I would try to create a new container with the -v option.  But I don't understand what to put in the folders. The bolded part is what I don't understand.  I want to use C\data to where I can export the files. Here is what I tried: 
New-NavContainer -containerName newbc133 -accept_eula -alwaysPull -assignPremiumPlan -auth NavUserPassword -doNotExportObjectsToText -imageName mcr.microsoft.com/businesscentral/onprem:13.3.27908.29339-na -includeCSide -navDvdCountry NA -updateHosts -useSSL -v c:\data:**c:\ProgramData\NavContainerHelper\Extensions\newbc133**

Any help on this would be appreciated.
Thanks,

Gary Nilsen

**Comment by freddydk** [comment]
-v is a parameter for docker run.
NavContainerHelper is an abstraction on top of docker run and it already shares c:\programdata\navcontainerhelper with the container - so if you select a folder for your objects underneath that folder (ex. c:\programdata\navcontainerhelper\myobjects) then you get them there.
You can read a lot about navcontainerhelper here: https://freddysblog.com/category/navcontainerhelper/
