### ISSUE TITLE
Error when restoring Database for a new container

### ISSUE THREAD

**Issue by AndreasGloeckner** [microsoft/navcontainerhelper#871]
Hi,

sometimes we got an error when creating our docker container with a backup. The following error is thrown, but not always. We have 4 agents on one virtual machine and nearly every agent throw this error once since they exist.

Using navcontainerhelper: 0.6.4.25

> C:\ProgramData\NavContainerHelper\bakFolder\Agent-03\sandbox1523955839825de\database.bak
> Removing Database mydatabase from localhost\SQLEXPRESS
> Warning, exception when running: ALTER DATABASE [mydatabase] SET OFFLINE WITH ROLLBACK IMMEDIATE
> Waiting... - retrying
> Warning, exception when running: ALTER DATABASE [mydatabase] SET OFFLINE WITH ROLLBACK IMMEDIATE
> Waiting...... - retrying
> Error when running: ALTER DATABASE [mydatabase] SET OFFLINE WITH ROLLBACK IMMEDIATE
> ALTER DATABASE is not permitted while a database is in the Restoring state.
> ALTER DATABASE statement failed.
> at Invoke-SqlCmdWithRetry, C:\Run\HelperFunctions.ps1: line 424
> at Remove-NavDatabase, C:\Run\HelperFunctions.ps1: line 311
> at Restore, <No file>: line 19
> at <ScriptBlock>, <No file>: line 57

Executed by:
>     try {
>         Restore-DatabasesInBCContainer -containerName $containerName -bakFolder $bakName
>     }
>     catch {
>         $restoreDb = $false
>     }

**Comment by freddydk** [comment]
Could you share the command used to create the container (before restoring databases)?
and the output of that?

**Comment by AndreasGloeckner** [comment]
Actually, we just test if the container still exist. If it exists, restore the database, if not set up a new container with a backup.
```
write-host $testPath
$restoreDb = Test-BCContainer -containerName $containerName
if ($restoreDb -and $bakFile -and -not $NoBackUp) {
    try {
        Restore-DatabasesInBCContainer -containerName $containerName -bakFolder $bakName
    }
    catch {
        $restoreDb = $false
    }
} else {
// Some more source code, but in general:
if(-not $NotSQLBak){
    New-BCContainer -accept_eula `
                    -containerName $containerName `
                    -auth NAVUserPassword `
                    -Credential $databaseCred `
                    -imageName $imageName `
                    -additionalParameters $additionalParameters `
                    -licenseFile $licensefile `
                    -shortcuts $shortcuts `
                    -doNotUseRuntimePackages `
                    -assignPremiumPlan `
                    -updateHosts `
                    -useTraefik:$false `
                    -EnableTaskScheduler:$false `
                    -usebestcontaineros `
                    -bakFile $bakFile
  } else {
    New-BCContainer -accept_eula `
                    -containerName $containerName `
                    -auth NAVUserPassword `
                    -Credential $databaseCred `
                    -imageName $imageName `
                    -additionalParameters $additionalParameters `
                    -licenseFile $licensefile `
                    -shortcuts $shortcuts `
                    -assignPremiumPlan `
		    -includeTestToolkit `
                    -updateHosts `
                    -EnableTaskScheduler:$false `
                    -useTraefik:$false
  }
}
```

Btw. I just turned off 2 of our 4 agents and so far the error didn't occur.

**Comment by freddydk** [comment]
Does the containername depend on the agent name?

**Comment by freddydk** [comment]
It looks like one agent is trying to restore a database in a container where another agent is restoring...

**Comment by AndreasGloeckner** [comment]
> Does the containername depend on the agent name?

Yes, the container's names are the same as the agent names. All are different:
Agent: Agent-01, Docker: Agent-01
Agent: Agent-02, Docker: Agent-02
Agent: Agent-03, Docker: Agent-03
Agent: Agent-04, Docker: Agent-04

When starting the pipeline a variable `containerName: $(Agent.Name)` is set. This variable is used during the docker creation with `$containerName = $ENV:CONTAINERNAME`.
Just checked the "Name" in the agent's capabilities and all are different.

Why do you think so and any ideas how to figure that out?

**Comment by freddydk** [comment]
Because of this:
Error when running: ALTER DATABASE [mydatabase] SET OFFLINE WITH ROLLBACK IMMEDIATE
ALTER DATABASE is not permitted while a database is in the Restoring state.

**Comment by freddydk** [comment]
BTW - I would change the script so that if restoring the DB fails - then it should revert to recreate the container. The container can be contaminated or be of a different version or whatever.

**Comment by AndreasGloeckner** [comment]
> Because of this:
> Error when running: ALTER DATABASE [mydatabase] SET OFFLINE WITH ROLLBACK IMMEDIATE
> ALTER DATABASE is not permitted while a database is in the Restoring state.

Well, obvious. Still don't know how, how this situation can occur.

> BTW - I would change the script so that if restoring the DB fails - then it should revert to recreate the container. The container can be contaminated or be of a different version or whatever.

At the moment, all containers have the same BC version, so that wouldn't be a problem right now, but maybe in the future. I will give it a try in the next days and will let you know.

**Comment by AndreasGloeckner** [comment]
Hey Freddy,

you were right. I changed the script, so that it only restores if the version matches. If not, create a new container.

We are restoring the container because it saves us time.

Nevertheless, thanks for your help!
