### ISSUE TITLE
New-NavContainer without SQL Express

### ISSUE THREAD

**Issue by AntoineTal** [microsoft/navcontainerhelper#879]
Hello,

I'm trying to create a container with a .bacpac in order to work with client data (export with excel/rapid start would be too long, with so many data)

The database is about 18 GO. 

When creating a container with New-NavContainer, it's using SQL Express which doesn't work with database bigger than 10go. 

Is there an option to use something else? I looked into the doc of New-NavContainer but didn't saw anything except the use of an external database (which I mean, could be a solution but if I can avoid doing this... that would be exceptionnal) 

Sorry if I missed something in the doc, I tried to look everywhere. 

Have a good day!

**Comment by freddydk** [comment]
You should place large databases on a SQL server on the host (or another machine) and connect to the DB on the host: https://freddysblog.com/2019/11/04/using-sql-server-on-the-host/

**Comment by AntoineTal** [comment]
I was wishing there was another way, but I understand why. Thanks for taking the time to answer, I'll try to use a SQL server asap.
