### ISSUE TITLE
Remove the "Welcome to the NAV Container PowerShell prompt"

### ISSUE THREAD

**Issue by waldo1001** [Microsoft/navcontainerhelper#88]
I use the navcontainerhelper in my "DockerHost" module, but every time I call code from the navcontainerhelper, I get this:

![image](https://user-images.githubusercontent.com/12088142/35830608-1beae8f0-0ac7-11e8-89d6-931eb0918438.png)

Is there a way to silence it? :-)

**Comment by freddydk** [comment]
With the latest version of navcontainerhelper you can add -silent to Get-NavContainerSession

**Comment by waldo1001** [comment]
Ok - I didn't know that :-).
Thanks!

**Comment by freddydk** [comment]
It's new.
I will probably remove this from the get-navcotainersession anyway
