### ISSUE TITLE
Create a Device User

### ISSUE THREAD

**Issue by RafaelKoch** [microsoft/navcontainerhelper#880]
Hi Freddy,

is it somehow possible to create a Device User in a container? Entering the container and trying this did not work:

```powershell
New-NAVServerUser -LicenseType DeviceOnly -UserName "MDE01" -State Enabled -Password (ConvertTo-SecureString -String "********" -AsPlainText -Force) -ServerInstance *** -Force
```

![image](https://user-images.githubusercontent.com/25029667/75344398-d598f300-589a-11ea-8924-47fe3c3cb6bd.png)

Which is odd because the licensing guide clearly says that this should be supported. I rather suspect we need a canny way around the actual portal to create users just as `new-navcontaineruser` does?

**Comment by freddydk** [comment]
new-navcontaineruser also just uses New-NavServerUser inside the container.
Which docker image are you using and where do you find the information that this should be possible?
Also, does it work if you are using onprem images?

**Comment by RafaelKoch** [comment]
The information is in the Dynamics 365 Business Central Licensing Guide, page 5 and 6: <https://go.microsoft.com/fwlink/?LinkId=871590&clcid=0x409>

Image used (last night): `mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019`

But anyway, as `new-navcontaineruser` uses the standard `New-NavServerUser` this is most likely unrelated to navcontainerhelper and I will have to got through regular support, I guess.

**Comment by freddydk** [comment]
Did you try the onprem images?
the sandbox images thinks they are saas tenants and that might obstruct something,

**Comment by RafaelKoch** [comment]
Will test with an on-prem image tomorrow. Strange stuff... I am betting this will take a looong support call to sort out :-)

**Comment by freddydk** [comment]
This works fine with onprem containers, as assumed this is somehow blocked because the container thinks it is an online tenant.

If you need a device user, you might be able to create it in code, like I do with the test users here. This of course won't work in SaaS
```
https://dev.azure.com/businesscentralapps/_git/CreateTestUsers?path=%2Fapp%2Fapi%2050000%20-%20CreateTestUsers.al
```

**Comment by RafaelKoch** [comment]
Good Morning!
Thanks for being quicker than me :-) And as always thanks for helping!

I will close this issue because there is nothing wrong with containerhelber obviously. I will try and get clarification through regular BC support what the correct way to obtain device users is supposed to be or if the licensing guide needs updating.
