### ISSUE TITLE
useBestContainerOS and external db

### ISSUE THREAD

**Issue by gunnargestsson** [microsoft/navcontainerhelper#881]
I am using the following 
 
    New-BCContainer `
        -useBestContainerOS `
        -accept_eula `
        -accept_outdated `
        -containerName $ContainerName `
        -imageName $ImageName `
        -useTraefik `
        -PublicDnsName erpdocker.ossur.com `
        -auth NavUserPassword `
        -useSSL `
        -Credential $Credential `
        -databaseServer $sqlHost `
        -databaseName $ContainerName `
        -updateHosts `
        -licenseFile $license `
        -shortcuts None `
        -alwaysPull `
        -restart no `
        -additionalParameters @('--security-opt "credentialspec=file://ossur_gmsa-erpdocker.json"')   
 
The external database server does not disable the SQL jobs in -useBestContainerOS and in the end the container build fails.  Can I give you any more details?
 
NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 18.09.11
Docker Server Version is 18.09.11
Enabling SSL as otherwise all clients will see mixed HTTP / HTTPS request, which will cause problems e.g. on the mobile and modern windows clients
Pulling image mcr.microsoft.com/businesscentral/onprem:14.10.40471.0-na-ltsc2019
14.10.40471.0-na-ltsc2019: Pulling from businesscentral/onprem
Using image mcr.microsoft.com/businesscentral/onprem:14.10.40471.0-na-ltsc2019
PublicDnsName is erpdocker.ossur.com
Creating Container bhalldorsson
Version: 14.10.40471.0-na
Style: onprem
Platform: 14.0.40464.0
Generic Tag: 0.0.9.98
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1039 (ltsc2019)
A better Generic Container OS exists for your host (mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic)
Creating temp container from mcr.microsoft.com/businesscentral/onprem:14.10.40471.0-na-ltsc2019 and extract necessary files
Extracting Service Tier and WebClient Files
Extracting Windows Client Files
Extracting Configuration packages
Extracting Test Assemblies
Extracting Test Toolkit
Extracting Upgrade Toolkit
Extracting Extensions
Extracting Applications
Extracting Applications.na
Extracting Files from Run folder
Extracting Database Files
Downloading prerequisites
Downloading C:\ProgramData\NavContainerHelper\14.10.40471.0-na-Files\Prerequisite Components\IIS URL Rewrite Module\rewrite_2.0_rtw_x64.msi
Downloading C:\ProgramData\NavContainerHelper\14.10.40471.0-na-Files\Prerequisite Components\Open XML SDK 2.5 for Microsoft Office\OpenXMLSDKv25.msi
Downloading C:\ProgramData\NavContainerHelper\14.10.40471.0-na-Files\Prerequisite Components\DotNetCore\DotNetCore.1.0.4_1.1.1-WindowsHosting.exe
Performing cleanup
Removing temp container
Using generic image mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic
Pulling image mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic
10.0.17763.1040-generic: Pulling from dynamicsnav
b5405b758079: Pull complete
ac56c610af03: Pull complete
d8d61c2ababf: Pull complete
0ed57babb001: Pull complete
c8a0f45b3421: Pull complete
45a5e51f11bd: Pull complete
26327d2d1283: Pull complete
7cf0b6478528: Pull complete
6b10a851aed8: Pull complete
f08414901ec8: Pull complete
d8c9747a07c1: Pull complete
28cc02b8e623: Pull complete
42141538cfb6: Pull complete
d5df98d7779c: Pull complete
961cf351c5ba: Pull complete
e04afa40bfc7: Pull complete
Digest: sha256:6d2222b76109031d3e162575727c29783427323900eab2e0c925a02db589850b
Status: Downloaded newer image for mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic
Generic Container OS Version: 10.0.17763.1040 (ltsc2019)
Generic Tag of better generic: 0.0.9.99
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale en-US
Using process isolation
Adding special CheckHealth.ps1 to enable Traefik support
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file f:\license\6433432-14Ossur.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bhalldorsson\my:
- AdditionalOutput.ps1
- CheckHealth.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bhalldorsson from image mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic
91141679f388cc2104f776d4cf1ba73dbe4e981279e5226b28939efd1443e35f
Waiting for container bhalldorsson to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CI_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Ser
ver 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correc
t and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The remote computer refused the network connection.)
at <ScriptBlock>, C:\Run\navinstall.ps1: line 159
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1Error
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Windows Client Files
Copying PowerShell Scripts
Copying Test Assemblies
Copying TestToolKit
Copying UpgradeToolKit
Copying Extensions
Copying ClientUserSettings
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CI_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Ser
ver 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correc
t and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - The remote computer refused the network connection.)
at <ScriptBlock>, C:\Run\navinstall.ps1: line 159
at <ScriptBlock>, C:\Run\start.ps1: line 114
at <ScriptBlock>, <No file>: line 1
Initialization of container bhalldorsson failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.0\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...ldorsson failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bhalldorsson failed

**Comment by tfenster** [comment]
Just a guess, maybe https://github.com/microsoft/nav-docker/issues/373 hit you

**Comment by freddydk** [comment]
In this case it is during install and probably trying to install the db on the server (which obviously is wrong). Will have a look and apply a fix.

**Comment by freddydk** [comment]
@tfenster might be right - could you try to set the databaseInstance as well?

**Comment by gunnargestsson** [comment]
@tfenster is usually right!

If I use 

    New-BCContainer `
        -isolation hyperv `
        -accept_eula `
        -accept_outdated `
        -containerName $ContainerName `
        -imageName $ImageName `
        -useTraefik `
        -PublicDnsName erpdocker.ossur.com `
        -auth NavUserPassword `
        -useSSL `
        -Credential $Credential `
        -databaseServer $sqlHost `
        -databaseName $ContainerName `
        -updateHosts `
        -licenseFile $license `
        -shortcuts None `
        -alwaysPull `
        -restart no `
        -additionalParameters @('--security-opt "credentialspec=file://ossur_gmsa-erpdocker.json"') 

then I get the container working fine.  Adding database instance and executing

    New-BCContainer `
        -isolation hyperv `
        -accept_eula `
        -accept_outdated `
        -containerName $ContainerName `
        -imageName $ImageName `
        -useTraefik `
        -PublicDnsName erpdocker.ossur.com `
        -auth NavUserPassword `
        -useSSL `
        -Credential $Credential `
        -databaseServer $sqlHost `
        -databaseInstance MSSQLSERVER `
        -databaseName $ContainerName `
        -updateHosts `
        -licenseFile $license `
        -shortcuts None `
        -alwaysPull `
        -restart no `
        -additionalParameters @('--security-opt "credentialspec=file://ossur_gmsa-erpdocker.json"') 

fails.  The database configuration for the nav service seem to be incorrect - pointing to localhost\sqlexpress.  See attached event log.

    New-BCContainer `
        -userBestContainerOS `
        -accept_eula `
        -accept_outdated `
        -containerName $ContainerName `
        -imageName $ImageName `
        -useTraefik `
        -PublicDnsName erpdocker.ossur.com `
        -auth NavUserPassword `
        -useSSL `
        -Credential $Credential `
        -databaseServer $sqlHost `
        -databaseInstance MSSQLSERVER `
        -databaseName $ContainerName `
        -updateHosts `
        -licenseFile $license `
        -shortcuts None `
        -alwaysPull `
        -restart no `
        -additionalParameters @('--security-opt "credentialspec=file://ossur_gmsa-erpdocker.json"')

failes with the same error as the first.

**Comment by freddydk** [comment]
strange

Tobias' bug (above) describes that you have to specify databaseinstance to make it work - that doesn't work for you.

Will have to see if I can repro.

**Comment by freddydk** [comment]
I think this is the same as #907
