### ISSUE TITLE
useBestContainerOS uses wrong version

### ISSUE THREAD

**Issue by pzentner** [microsoft/navcontainerhelper#884]
Experienced in NavContainerHelper 0.6.5.0. 

I noticed that our build pipeline failed with some weird message that I could not repro locally. We are using the same scripts to create the docker containers and build (locally and pipeline). The only difference is that I locally run windows 10 and the build server is running on Server 2019.

Here is the image that we tried to use: 

`Using Image mcr.microsoft.com/dynamicsnav:2018-cu6-na`

The following output happened (notice last line):

```
NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as ***istrator
Host is Microsoft Windows Server 2019 Datacenter - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/dynamicsnav:2018-cu6-na-ltsc2019
Creating Container creditcardbuild
Version: 11.0.22292.0-na
Style: onprem
Generic Tag: 0.0.9.2
Container OS Version: 10.0.17763.316 (ltsc2019)
Host OS Version: 10.0.17763.1039 (ltsc2019)
A better Generic Container OS exists for your host (mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic)
Using generic image mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic
```

As you can see, we were building for NAV 2018 and it switched us to NAV 2017. I can obviously prevent this when removing "UseBestContainerOS", but I would think that it should work either way.

**Comment by freddydk** [comment]
mcr.microsoft.com/dynamicsnav:10.0.17763.1040-generic is a generic image for 10.0.17763.1040 which is correct from what I see.
What goes wrong?

**Comment by pzentner** [comment]
I honestly have no idea. I was getting weird errors that indicated there is something wrong with the NAV version being installed, but trying it manually on the build server seems to be working now after restarting it. I am monitoring it right now, but this might have been a fluke. It somewhat seemed like the generic image was introducing some issues, but right now it seems that it's working

**Comment by freddydk** [comment]
Will close this for now. I am looking at ways to improve these things
