### ISSUE TITLE
Compilation error when installation Microsoft_Tests-TestLibraries.app

### ISSUE THREAD

**Issue by larswestman** [microsoft/navcontainerhelper#885]
"-includeTestToolkit" and "includeTestLibrariesOnly" works in mcr.microsoft.com/businesscentral/sandbox:se, but not when I try with :dk, :gb or :us

Output from dk

PS C:\Windows\system32> $image = 'mcr.microsoft.com/businesscentral/sandbox:dk'
$containerName = 'test-dk'
$password = ConvertTo-SecureString -String "p@ssword" -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential -argumentList "admin", $password
$licenseFile = "C:\Users\me\mylicense.flf"

New-NavContainer `
    -Credential $credential `
    -accept_eula `
    -accept_outdated `
    -containerName $containerName `
    -auth NAVUserPassword `
    -imageName $image `
    -updateHosts `
    -licenseFile $licenseFile `
    -includeTestToolkit `
    -includeTestLibrariesOnly `
    -alwaysPull `
    -doNotCheckHealth `
    -EnableTaskScheduler:$false `
    -useBestContainerOS
NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image mcr.microsoft.com/businesscentral/sandbox:dk-ltsc2019
dk-ltsc2019: Pulling from businesscentral/sandbox
Digest: sha256:df739721c56b99ee821aed0b7b1a90af145b13ccf484c23ac3b3175d8a6d233d
Using image mcr.microsoft.com/businesscentral/sandbox:dk-ltsc2019
Disabling Health Check (always report healthy)
Removing container test-dk
Removing test-dk from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\test-dk
Creating Container test-dk
Version: 15.3.40074.40889-dk
Style: sandbox
Platform: 15.0.40073.40881
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.18363.657 (1909)
A better Generic Container OS exists for your host (mcr.microsoft.com/dynamicsnav:10.0.18363.658-generic)
Using generic image mcr.microsoft.com/dynamicsnav:10.0.18363.658-generic
Pulling image mcr.microsoft.com/dynamicsnav:10.0.18363.658-generic
10.0.18363.658-generic: Pulling from dynamicsnav
Digest: sha256:98c6a9cc10009a509cfa44223a83267556344767d4a95b35cca56198e7fa4e4a
Generic Container OS Version: 10.0.18363.658 (1909)
Generic Tag of better generic: 0.0.9.99
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale da-DK
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\lars\OneDrive - Goprowe AB\Goprowe Developer BC.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\test-dk\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container test-dk from image mcr.microsoft.com/dynamicsnav:10.0.18363.658-generic
a389cb6e51d97dc8d132689ec909e6e805d8a2b87b4be09e2c5fb08ae77eab47
Waiting for container test-dk to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Extensions
Copying Applications
Copying ReportBuilder
Changing Database Server Collation to Latin1_General_100_CS_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Sta
tement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 185 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.1.188 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.1.188 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.20.240.1 in container hosts file
Starting Container
Hostname is test-dk
PublicDnsName is test-dk
Using NavUserPassword Authentication
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 9522DAA3F7FDC694C45CDEAEDD33559BDE7ABE54
Modifying Service Tier Config File with Instance Specific Settings
Modifying Service Tier Config File with settings from environment variable
Setting EnableTaskScheduler to False
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Enabling Financials User Experience
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating admin as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements. 
It should be at least 8 characters long and contain at least one uppercase 
letter, one lowercase letter, and one number.
Container IP Address: 172.20.240.239
Container Hostname  : test-dk
Container Dns Name  : test-dk
Web Client          : http://test-dk/BC/
Dev. Server         : http://test-dk
Dev. ServerInstance : BC
Setting test-dk to 172.20.240.239 in host hosts file

Files:
http://test-dk:8080/al-4.0.231354.vsix

Initialization took 51 seconds
Ready for connections!
Reading CustomSettings.config from test-dk
Creating Desktop Shortcuts for test-dk
Copy from container test-dk (C:\Applications\TestFramework\TestLibraries\Any\Microsoft_Any.app) to C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Any.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Any.app
Synchronizing Any on tenant default
Installing Any on tenant default
App successfully published
Copy from container test-dk (C:\Applications\TestFramework\TestLibraries\Assert\Microsoft_Library Assert.app) to C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Library Assert.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Library Assert.app
Synchronizing Library Assert on tenant default
Installing Library Assert on tenant default
App successfully published
Copy from container test-dk (C:\Applications\TestFramework\TestRunner\Microsoft_Test Runner.app) to C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Test Runner.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Test Runner.app
Synchronizing Test Runner on tenant default
Installing Test Runner on tenant default
App successfully published
Copy from container test-dk (C:\Applications\System Application\Test\Microsoft_System Application Test Library.app) to C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_System Application Test Library.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_System Application Test Library.app
Synchronizing System Application Test Library on tenant default
Installing System Application Test Library on tenant default
App successfully published
Copy from container test-dk (C:\Applications\BaseApp\Test\Microsoft_Tests-TestLibraries.app) to C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Tests-TestLibraries.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\test-dk\_Microsoft_Tests-TestLibraries.app
Extension compilation failed
LibraryGraphSync.Codeunit.al(251,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(261,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(270,77): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(140,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(326,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(150,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(347,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(161,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(177,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(421,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(214,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(294,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(311,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(334,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(354,117): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(370,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(380,114): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(396,152): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(513,81): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(814,117): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1054,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1446,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1499,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1514,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(728,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphMgt.Codeunit.al(637,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
TestVATContent.Codeunit.al(14,26): error AL0135: There is no argument given that corresponds to the required formal parameter 'XMLPartID' of 'ArchiveSubmissionMessage(Option, Code[20], Codeunit "Temp Blob", Guid)'
LibraryApplicationArea.Codeunit.al(626,39): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
LibraryApplicationArea.Codeunit.al(830,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
LibraryApplicationArea.Codeunit.al(839,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
AssistedSetupMockEvents.Codeunit.al(42,23): warning AL0432: Method 'Complete' is marked for removal. Reason: ExtensionID is not required. Please use the function with the same name without this parameter..
LibraryApplicationArea.Codeunit.al(849,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
LibraryApplicationArea.Codeunit.al(858,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
AssisCompSetupPlatTests.Codeunit.al(112,23): warning AL0432: Method 'IsComplete' is marked for removal. Reason: ExtensionID is not required. Please use the function with the same name without this parameter..
LibraryGraphDocumentTools.Codeunit.al(663,87): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(669,95): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(699,87): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(705,95): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
at <ScriptBlock>, <No file>: line 12
Extension compilation failed
LibraryGraphSync.Codeunit.al(251,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(261,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(270,77): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(140,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(326,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(150,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(347,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(161,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(177,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphSync.Codeunit.al(421,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(214,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(294,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(311,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(334,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(354,117): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(370,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(380,114): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(396,152): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(513,81): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(814,117): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1054,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1446,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1499,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryCRMIntegration.Codeunit.al(1514,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(728,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphMgt.Codeunit.al(637,35): warning AL0432: Table 'Integration Record' is marked for removal. Reason: This functionality will be replaced by the systemID field.
TestVATContent.Codeunit.al(14,26): error AL0135: There is no argument given that corresponds to the required formal parameter 'XMLPartID' of 'ArchiveSubmissionMessage(Option, Code[20], Codeunit "Temp Blob", Guid)'
LibraryApplicationArea.Codeunit.al(626,39): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
LibraryApplicationArea.Codeunit.al(830,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
LibraryApplicationArea.Codeunit.al(839,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
AssistedSetupMockEvents.Codeunit.al(42,23): warning AL0432: Method 'Complete' is marked for removal. Reason: ExtensionID is not required. Please use the function with the same name without this parameter..
LibraryApplicationArea.Codeunit.al(849,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
LibraryApplicationArea.Codeunit.al(858,40): warning AL0432: Field 'Invoicing' is marked for removal. Reason: Microsoft Invoicing is not supported on Business Central.
AssisCompSetupPlatTests.Codeunit.al(112,23): warning AL0432: Method 'IsComplete' is marked for removal. Reason: ExtensionID is not required. Please use the function with the same name without this parameter..
LibraryGraphDocumentTools.Codeunit.al(663,87): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(669,95): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(699,87): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
LibraryGraphDocumentTools.Codeunit.al(705,95): warning AL0432: Field 'Id' is marked for removal. Reason: This functionality will be replaced by the systemID field.
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.0\ContainerHandling\Invoke-ScriptInNavContainer.ps1:37 char:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Management.Cmdlets.PublishNavApp
    + PSComputerName        : a389cb6e51d97dc8d132689ec909e6e805d8a2b87b4be09e2c5fb08ae77eab47

**Comment by larswestman** [comment]
It works when I use Hyper-V. My hosts local is sv-SE and I guess that's why the swedish version (only) works

**Comment by freddydk** [comment]
Thanks for the info, will have a look to see whether anything can be done

**Comment by ralf-escher** [comment]
Yesterday BC16 was released and I downloaded the german version:
`mcr.microsoft.com/businesscentral/onprem:2004-de-ltsc2019`

I get now almost the same error message.
Then I tried it with HyperV isolation with the same result (did not work for me).

```
Copy from container Industry28 (C:\Applications\BaseApp\Test\Microsoft_Tests-TestLibraries.app) to C:\ProgramData\NavContainerHelper\Extensions\Industry28\_Microsoft_Tests-TestLibraries.app
Publishing C:\ProgramData\NavContainerHelper\Extensions\Industry28\_Microsoft_Tests-TestLibraries.app
Extension compilation failed
LibraryCosting.Codeunit.al(350,61): warning AL0432: Table 'Purchase Price' is marked for removal. Reason: Replaced by the new implementation (V16) of price calculation.. Tag: 16.0.
LibraryCosting.Codeunit.al(393,55): warning AL0432: Table 'Sales Price' is marked for removal. Reason: Replaced by the new implementation (V16) of price calculation.. Tag: 16.0.
LibraryCosting.Codeunit.al(407,64): warning AL0432: Table 'Sales Price Worksheet' is marked for removal. Reason: Replaced by the new implementation (V16) of price calculation.. Tag: 16.0.
[...]  lot's of warnings
LibraryJob.Codeunit.al(1107,22): warning AL0603: An implicit conversion is being performed from a value of type 'Enum
"Service Line Type"' to a value of type 'Integer'. This conversion can lead to unexpected runtime issues. This warning
will become an error in a future release.
In C:\Users\ralf.escher\Documents\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.26\ContainerHandling\Invoke-Script
InNavContainer.ps1:37 Zeichen:13
+             Invoke-Command -Session $session -ScriptBlock $scriptbloc ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Publish-NAVApp], InvalidOperationException
    + FullyQualifiedErrorId : MicrosoftDynamicsNavServer$BC/nav-systemapplication,Microsoft.Dynamics.Nav.Apps.Manageme
   nt.Cmdlets.PublishNavApp
    + PSComputerName        : bce1f3ada564c90d23edc3d8d60ddc0223831ea32a5a15f651f5a113974f86c2
```

**Comment by freddydk** [comment]
The original problem here is not related to the bug in 16.0 RTM onprem.
@larswestman - you wrote that it only worked with se - is this still a problem if you are not using hyperv?

**Comment by larswestman** [comment]
BC16 and hyperv works just fine.

**Comment by freddydk** [comment]
Will close this and keep this in mind if other people report similar experience.
