### ISSUE TITLE
Cannot download Symbols from docker image

### ISSUE THREAD

**Issue by Mesomorf** [microsoft/navcontainerhelper#887]
**This is my script for creating the container**
$repo = 'mcr.microsoft.com/businesscentral/onprem:'
$ver = 'dk-ltsc2019'
$licens = 'C:\Workspace\Code\BC365\licens.flf'
New-BCContainer -imageName $repo$ver -updateHosts -accept_eula -accept_outdated -containerName 'dev' -licenseFile $licens -auth Windows -useBestContainerOS

**This is the result after creating the container**
Generic Container OS Version: 10.0.18363.658 (1909)
Generic Tag of better generic: 0.0.9.99
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale da-DK
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Workspace\Code\BC365\licens.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\dev\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container dev from image mcr.microsoft.com/dynamicsnav:10.0.18363.658-generic
a13ec5778b6b2461c362bc9b65ae7dc7412c0716a3c68973ce75b363eb220dcd
Waiting for container dev to be ready
Installing Business Central
Installing Url Rewrite
Installing OpenXML
Installing DotNetCore
Starting Local SQL Server
Starting Internet Information Server
Copying Service Tier Files
Copying Web Client Files
Copying Client Files
Copying ModernDev Files
Copying PowerShell Scripts
Copying ConfigurationPackages
Copying Test Assemblies
Copying Applications
Copying ReportBuilder
Changing Database Server Collation to Danish_Greenlandic_100_CI_AS
SQL Server 2017 transmits information about your installation experience, as well as other usage and performance data, to Microsoft to help improve the product. To learn more about SQL Server 2017 data processing and privacy controls, please see the Privacy Statement.
Copying Cronus database
Modifying Business Central Service Tier Config File for Docker
Creating Business Central Service Tier
Installing SIP crypto provider: 'C:\Windows\System32\NavSip.dll'
Starting Business Central Service Tier
Installation took 163 seconds
Installation complete
Initializing...
Setting host.docker.internal to 192.168.10.11 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.10.11 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.24.192.1 in container hosts file
Starting Container
Hostname is dev
PublicDnsName is dev
Using Windows Authentication
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user Jesper
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.24.198.4
Container Hostname  : dev
Container Dns Name  : dev
Web Client          : http://dev/BC/
Dev. Server         : http://dev
Dev. ServerInstance : BC
Setting dev to 172.24.198.4 in host hosts file

Files:
http://dev:8080/al-4.0.231354.vsix

Initialization took 43 seconds
Ready for connections!
Reading CustomSettings.config from dev
Creating Desktop Shortcuts for dev
Container dev successfully created

I installed the http://dev:8080/al-4.0.231354.vsix and uninstalled all other AL Language extensions.

I can access the web client using http://dev/BC/

Created a new project in Visual Studio Code using AL:Go

This is my lanch.json file
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://dev",
            "serverInstance": "BC",
            "port": 7049,
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true
        }
    ]
}

This is my app.json

{
  "id": "b08307ce-4738-4dd5-bc12-a51206336e5a",
  "name": "Transsoft - Vehicle",
  "publisher": "Default publisher",
  "version": "1.0.0.0",
  "brief": "",
  "description": "",
  "privacyStatement": "",
  "EULA": "",
  "help": "",
  "url": "",
  "logo": "",
  "dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "15.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    }
  ],
  "screenshots": [],
  "platform": "15.0.0.0",
  "idRanges": [
    {
      "from": 50100,
      "to": 50149
    }
  ],
  "contextSensitiveHelpUrl": "https://Transsoft-Vehicle.com/help/",
  "showMyCode": true,
  "runtime": "4.0"
}

**Problem**
When I try to download the symbols I get the following in the Visual Studio Code output console

[2020-03-05 08:19:58.58] Using reference symbols cache path: c:\Workspace\Code\BC365\Transsoft.Workspace\Transsoft - Vehicle\./.alpackages
[2020-03-05 08:19:58.58] Sending request to http://dev:7049/BC/dev/packages?publisher=Microsoft&appName=System&versionText=15.0.0.0
[2020-03-05 08:19:58.58] Sending request to http://dev:7049/BC/dev/packages?publisher=Microsoft&appName=System Application&versionText=15.0.0.0
[2020-03-05 08:19:58.58] Sending request to http://dev:7049/BC/dev/packages?publisher=Microsoft&appName=Base Application&versionText=15.0.0.0
[2020-03-05 08:19:58.58] Error: a server-side error occured while processing the request.
Request ID: 70c66f3a-8064-4247-8d5b-0412aebefb07
Session ID: d0824f70-1740-4c5c-b8de-a982f2c599af

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-03-05 08:19:58.58] Error: a server-side error occured while processing the request.
Request ID: 74fc668c-4da1-4fb1-bdaf-de12a10af396
Session ID: d0824f70-1740-4c5c-b8de-a982f2c599af

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-03-05 08:19:58.58] The request for path /BC/dev/packages?publisher=Microsoft&appName=System%20Application&versionText=15.0.0.0 failed with code ServiceUnavailable. Reason: Service Unavailable
[2020-03-05 08:19:58.58] The request for path /BC/dev/packages?publisher=Microsoft&appName=System&versionText=15.0.0.0 failed with code ServiceUnavailable. Reason: Service Unavailable
[2020-03-05 08:19:58.59] Error: a server-side error occured while processing the request.
Request ID: 3b3212d7-3173-4c9b-9f33-76cc02da6551
Session ID: d0824f70-1740-4c5c-b8de-a982f2c599af

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-03-05 08:19:58.59] The request for path /BC/dev/packages?publisher=Microsoft&appName=Base%20Application&versionText=15.0.0.0 failed with code ServiceUnavailable. Reason: Service Unavailable
[2020-03-05 08:19:58.59] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

**Comment by freddydk** [comment]
Could you try UserPassword authentication when creating the container and in launch.json.
Windows auth is frequently the cause of issues

**Comment by Mesomorf** [comment]
Hi freddydk

I can reproduce the problem on another machine. If you name the container "dev" then the problem occures. I have tested this on 3 different machines.

**Comment by freddydk** [comment]
So this only happens if the container is named dev?

**Comment by Mesomorf** [comment]
Yes, if I gave the container another name. Then it works

**Comment by freddydk** [comment]
Apparently some names will be forced to https - not sure where/how this happens.
If you create the container with -useSSL and add these lines:
```
$containerName = "dev"
Copy-FileFromNavContainer -containerName $containerName -containerPath "c:\run\certificate.cer" -localPath "C:\ProgramData\NavContainerHelper\Extensions\$containerName\certificate.cer"
Import-Certificate -FilePath "C:\ProgramData\NavContainerHelper\Extensions\$containerName\certificate.cer" -CertStoreLocation "cert:\localMachine\Root"
```
Then you should be able to use the container even if it is named dev.

**Comment by freddydk** [comment]
Next version of NavContainerHelper adds a parameter to new-navcontainer called -installcertonhost - this will install the created self-signed certificate on the host and this your scenario should start working if you add -usessl.

**Comment by Mesomorf** [comment]
Thanks. I ended up with using another container name.
