### ISSUE TITLE
Latest problems with the Feb update?

### ISSUE THREAD

**Issue by mattkeyeswc** [microsoft/navcontainerhelper#889]
I have used Docker Containers for BC for 1 - 2 years without too many issues.  However, over the past week, I have not been able to log into BC with Chrome (I saw that on another issue).

As a result, I tried updating Docker for Windows and cleaning out my images to download fresh ones.

When I try the -useBestContainerOS parameter, I get this error:

`Creating Self Signed Certificate
Self Signed Certificate Thumbprint 952D9A984EB78A159298FAD8811256D0DF05F0CF
Modifying Service Tier Config File with Instance Specific Settings
Restarting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
WARNING: SetupWebClient failed, retrying in 10 seconds
Registering event sources
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1:
 line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\150\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501

at <ScriptBlock>, C:\run\setupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\my\SetupWebClient.ps1: line 7
at <ScriptBlock>, C:\Run\navstart.ps1: line 157
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container MYCONTAINER failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.19\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...MYCONTAINERfailed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container MYCONTAINER failed`

If I try without the useBestContainerOS parameter, then the Container will initialize and start but I cannot get past the login page (it does nothing).  I am in the process of trying it now without the switch to see if other browsers work, but something seems to have changed recently.  I have lost a day of productivity due to this problem.

**Comment by freddydk** [comment]
The problem you have when using -useBestContainerOS seems to be february update, and by updating your navcontainerhelper, that should be fixed (it should select a better generic image).
The Chrome problem, I will investigate.

**Comment by freddydk** [comment]
I still need to find out whether the problem with Chrome only happens with new container images - or also with old.
f.ex. try to create a container, which you know worked some months ago using hyperv - and if Chrome also fails on that, then this must be a new Chrome specific problem. (which I assume since other browsers works)

**Comment by kevindstanley1988** [comment]
For me the chrome login issue, it is happening with old and new containers for me.

**Comment by freddydk** [comment]
Somebody wrote to me that it might be related to the container name. What name do you use and could you try with another name?

**Comment by kevindstanley1988** [comment]
I have tried with 5 or 6 different names, the most basic is just called 'cronus' they don't get much more complicated than that. One is called 'masterupdate' and that doesn't work either.
