### ISSUE TITLE
Docker Hub 

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#892]
Hi
The Docker Hub (https://hub.docker.com/r/microsoft/dynamics-nav/tags) page for the Dynamics NAV images still refers to the old source:

> docker pull microsoft/dynamics-nav:2017

instead of 

> mcr.microsoft.com/dynamicsnav:2017

Do you have any "pull" to get this updated?

**Comment by freddydk** [comment]
Will try to get that fixed.

**Comment by freddydk** [comment]
Finally - this is changed...
https://hub.docker.com/r/microsoft/dynamics-nav
