### ISSUE TITLE
Parallel compilation of apps

### ISSUE THREAD

**Issue by MJECloud** [microsoft/navcontainerhelper#893]
Hi Freddy, 

would it be possible to implement the _parallel_ and _maxdegreeofparallelism_ option in Compile-AppInNavContainer?

We think it could speed up the compilation time in our builds.

**Comment by freddydk** [comment]
The word from the ModernDev team is that parallel compilation is automatically enabled and the parameters are used to limit that - not enable it.
You can add -additionalparameters @("--cpus=4") to use 4 cpus. Not sure how much it helps.

**Comment by MJECloud** [comment]
Alright we'll try it, thank you freddy :)
