### ISSUE TITLE
Traefik w/ OwnCertificate

### ISSUE THREAD

**Issue by achim-t** [microsoft/navcontainerhelper#894]
Our docker server is in a private network and therefore not reachable from the internet. Consequently, a Let's Encrypt certificate won't work. 

When trying to setup traefik: 
`Setup-TraefikContainerForBCContainers -PublicDnsName "xxx.intranet" -IP 192.168.0.1 -recreate -CrtFile "C:\Users\docker\Documents\xxx.crt" -crtKeyFile "C:\Users\docker\Documents\xxx.key"`

`docker logs` produces this error message: 
```2020/03/10 10:51:35 Using high precision timer
time="2020-03-10T10:51:41+01:00" level=error msg="Unable to obtain ACME certificate for domains \"xxx.intranet\" : unable to generate a certificate for the domains [xxx.intranet]: acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for \"xxx.intranet\": Domain name does not end with a valid public suffix (TLD), url: "
```

Apparently, the provided .crt and .key are ignored? Am I doing something wrong?

**Comment by tfenster** [comment]
That scenario unfortunately is not supported ootb. You need to add something like this
```
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
    certFile = "c:/etc/traefik/certificate.crt"
    keyFile = "c:/etc/traefik/certificate.key"
```
to the traefik.toml file and remove the `[acme]` part

**Comment by achim-t** [comment]
Would I have to restart the traefik container?

Would I have to recreate the BC containers?

**Comment by tfenster** [comment]
> Would I have to restart the traefik container?

Yes

> Would I have to recreate the BC containers?

No

**Comment by achim-t** [comment]
Thanks, that worked like a charm.

**Comment by freddydk** [comment]
Thanks @tfenster, much appreviated.
