### ISSUE TITLE
Gitlab CI: Invoke Codeunit

### ISSUE THREAD

**Issue by RReckmann** [microsoft/navcontainerhelper#895]
We are currently developing extensions for BC and would like to use the _Invoke-NavContainerCodeunit_ function inside a powershell Gitlab CI runner for automated testing purposes.
Unfortunately, we found no way to redirect the output of this function to a variable which should then be used to evaluate if the resulting string contains the word "FAILURE", thus exiting with code 1, or if there is a match with "SUCCESS", thus exiting with code 0.

All we get when calling the _Invoke-NavContainerCodeunit_ function is direct text output to the console, leaving the variable empty (both environment variables and usual powershell variables lead to the same behaviour). Redirecting the output to a text file does not work either, nor does the Powershell _Transcript_ cmdlet help in this case. All of this works perfectly fine directly on Windows, but just not in the above mentioned Gitlab Powershell Runner setting. 

Any help would be appreciated :)

This is the .gitlab-ci.yml file we are currently using:

> stages:
>   - test
>
> test-powershell:
>   tags:
>     - windows
>     - shell
>   variables:
>     TEST_USERNAME: admin
>     TEST_PASSWORD: P@ssword1
>     CONTAINER_NAME: tmp
>     TEST_CODEUNIT_ID: 50104
>     TEST_COMPANY: "CRONUS AG"
>   stage: test
>   before_script:
>     - Install-Module navcontainerhelper -Force
>     - Get-Command -Module navcontainerhelper
>     - $credential = New-Object PSCredential $env:TEST_USERNAME,  (ConvertTo-SecureString $env:TEST_PASSWORD -AsPlainText -Force)
    - $volumeFolder =  '--volume ' + '"' + (Join-Path $pwd ":c:\share") + '"'
>     - Set-TimeZone -Name "UTC-02"
>     - New-NavContainer `
>         -imageName "mcr.microsoft.com/businesscentral/onprem:14.7.37609.0-de-ltsc2019" `
>         -containerName $env:CONTAINER_NAME `
>         -accept_eula `
>         -accept_outdated `
>         -auth NavUserPassword `
>         -credential $credential `
>         -updateHosts `
>         -doNotExportObjectsToText `
>         -additionalParameters @($volumeFolder,'--env CustomNavSettings=DisableWriteInsideTryFunctions="false"')
  script:
>     - Invoke-ScriptInNavContainer -containerName $env:CONTAINER_NAME -scriptblock{Invoke-Sqlcmd -query "USE [master] RESTORE DATABASE [Syn-Tabelle] FROM DISK = N'c:\share\SynTabelle.bak' WITH REPLACE, FILE = 1, NOUNLOAD, STATS = 5"}
>     - Compile-AppInBCContainer -containerName $env:CONTAINER_NAME -credential $credential -appProjectFolder $pwd -appOutputFolder $pwd -appName "bc1.app" -UpdateSymbols
>     - Publish-NavContainerApp -containerName $env:CONTAINER_NAME -appFile (Join-Path $pwd "bc1.app") -skipVerification -sync -install
>     - $TEST_RESULT = Invoke-NavContainerCodeunit -containerName $env:CONTAINER_NAME -CompanyName $env:TEST_COMPANY -CodeunitId $env:TEST_CODEUNIT_ID
>     - if ($TEST_RESULT -match "FAILURE") { $exitCode = 1 } elseif ($TEST_RESULT -match "SUCCESS") { $exitCode = 0 } else { $exitCode = 2 }
>     - exit $exitCode
>   after_script:
>     - Remove-NavContainer -containerName $env:CONTAINER_NAME

**Comment by freddydk** [comment]
There are functions designed to run tests - and in 15.x they can even run all tests in a test app.
There are a few posts on my blog about this:
https://freddysblog.com/2019/04/13/running-tests-in-containers/
https://freddysblog.com/2019/10/22/running-tests-in-containers-2/
https://freddysblog.com/2019/08/30/running-tests-in-15-x-insider-containers/

**Comment by freddydk** [comment]
Did you make this work?

**Comment by RReckmann** [comment]
Hi, first of all thank's for your help. As of now we are still waiting for our partner to update the license, as the old one does not allow us to use the test toolkit for some reason. That's also why we wanted to use the Invoke-NavContainerCodeunit function in the first place. Once we get the new license I will post an update here.

**Comment by freddydk** [comment]
Thanks

**Comment by freddydk** [comment]
I will close the issue. Please open another issue if you have issues with running tests, thanks
