### ISSUE TITLE
log-level configuration is ignored when health checking

### ISSUE THREAD

**Issue by bjarkihall** [microsoft/navcontainerhelper#896]
Hi and thanks for your work on the navcontainerhelper.
I've noticed that the Event View gets a bunch of information logs:
![image](https://user-images.githubusercontent.com/8615374/76999128-16da6b00-694e-11ea-9d11-3fff18b21890.png)
I think it's because of the health checks done every 30 seconds, while I could use -doNotCheckHealth, I thought it would be nice to keep the restarting feature if the container wasn't healthy 3 times in a row.
I assumed the following would work:
![image](https://user-images.githubusercontent.com/8615374/76999316-5903ac80-694e-11ea-90a2-92f01111517d.png)
But I still seem to get Information logs from my containers, could you possibly know what I might be doing wrong?
I'm using the containers for local development, so would it therefor just be easiest to use the -doNotCheckHealth flag? I'm not sure when the health checks would be necessary, are there typical use cases where the containers become unhealthy? It's just the event logs that are in my way, rather than [CPU usage](https://freddysblog.com/2019/07/06/cpu-usage-in-business-central-containers/).

**Comment by freddydk** [comment]
The Health check is only for your convenience - no automatic recovery is done on unhealthy containers so you can safely turn it off.
You could add an issue for docker to solve on the event log - that isn't something I can fix in containerhelper.

**Comment by bjarkihall** [comment]
Okay thanks for the clarification Freddy. :)
