### ISSUE TITLE
SecureString in Sign-NavContainerApp

### ISSUE THREAD

**Issue by TheDenSter** [microsoft/navcontainerhelper#899]
Sign-NavContainerApp is a wonderful Cmdlet. One issue I had was an error message:

Sign-NavContainerApp : Cannot process argument transformation on parameter 'pfxPassword'. Cannot convert the "my password with spaces" value of type "System.String" 
to type "System.Security.SecureString".
At line:4 char:18
*     -pfxPassword $MyPassword `
*                  ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Sign-NavContainerApp], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Sign-NavContainerApp

I was able to make it work by converting the string to securestring before passing it into the Cmdlet. This worked:
$MyAppFile = "C:\ProgramData\NavContainerHelper\Extensions\Publisher_AppName_1.0.0.0.app"
$MyPfx = "C:\ProgramData\NavContainerHelper\Extensions\CodeSignCert.pfx"
$MyPassword = ConvertTo-SecureString "my password with spaces" -AsPlainText -Force
$MyContainerName = "MySandbox"

Sign-NavContainerApp `
    -appFile $MyAppFile `
    -pfxFile $MyPfx `
    -pfxPassword $MyPassword `
    -containerName $MyContainerName

**Comment by freddydk** [comment]
This is very much by design.
All password parameters in NavContainerHelper for all purposes are securestrings.
If not - PowerShellGallery will fail validation.

**Comment by TheDenSter** [comment]
Ah ok never mind then. Easy enough to send in a securestring. I've closed the issue
