### ISSUE TITLE
New-BCContainer - initialization failed HRESULT: 0x8007000D

### ISSUE THREAD

**Issue by dNsl9r** [microsoft/navcontainerhelper#900]
**navcontainerhelper 0.6.5.0**
**Windows 10 Enterprise - 1803**
**Image: mcr.microsoft.com/businesscentral/onprem:14.11.41204.0**
Creating container with: 
`New-BCContainer -accept_eula -containerName bc14cutest -imageName mcr.microsoft.com/businesscentral/onprem:14.11.41204.0 -licenseFile C:\_Repos\devbc15.flf -auth NavUserPassword`

Output of the Log:

> NavContainerHelper is version 0.6.5.0
> NavContainerHelper is running as administrator
> Host is Microsoft Windows 10 Enterprise - 1803
> Docker Client Version is 19.03.8
> Docker Server Version is 19.03.8
> Using image mcr.microsoft.com/businesscentral/onprem:14.11.41204.0-ltsc2016
> Removing container bc14cutest
> Removing C:\ProgramData\NavContainerHelper\Extensions\bc14cutest
> Creating Container bc14cutest
> Version: 14.11.41204.0-W1
> Style: onprem
> Platform: 14.0.41143.0
> Generic Tag: 0.0.9.99
> Container OS Version: 10.0.14393.3443 (ltsc2016)
> Host OS Version: 10.0.17134.1304 (1803)
> The container operating system does not match the host operating system, forcing hyperv isolation.
> Using locale en-US
> Using hyperv isolation
> Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
> Using license file C:\_Repos\devbc15.flf
> Files in C:\ProgramData\NavContainerHelper\Extensions\bc14cutest\my:
> - AdditionalOutput.ps1
> - license.flf
> - MainLoop.ps1
> Creating container bc14cutest from image mcr.microsoft.com/businesscentral/onprem:14.11.41204.0-ltsc2016
> 82d389b811fc2c7f87285e83e00c76825fc541f015bfed29c37618a8f1890048
> Waiting for container bc14cutest to be ready
> Initializing...
> Starting Container
> Hostname is bc14cutest
> PublicDnsName is bc14cutest
> WARNING: Container starts with TimeZone = Mitteleurop├ñische Zeit, which is not recognized in the list of TimeZones.
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint A1FE53BBAA14DBCCA6999A4162B90FFDEE2090C7
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Registering event sources
> Creating DotNetCore Web Server Instance
> The data is invalid. (Exception from HRESULT: 0x8007000D)
> at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
> at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
> at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
> at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
> at <ScriptBlock>, C:\Run\navstart.ps1: line 157
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1Error
> Initializing...
> Starting Container
> Hostname is bc14cutest
> PublicDnsName is bc14cutest
> WARNING: Container starts with TimeZone = Mitteleurop├ñische Zeit, which is not recognized in the list of TimeZones.
> Using NavUserPassword Authentication
> Starting Local SQL Server
> Starting Internet Information Server
> Creating Self Signed Certificate
> Self Signed Certificate Thumbprint A1FE53BBAA14DBCCA6999A4162B90FFDEE2090C7
> Modifying Service Tier Config File with Instance Specific Settings
> Starting Service Tier
> Registering event sources
> Creating DotNetCore Web Server Instance
> The data is invalid. (Exception from HRESULT: 0x8007000D)
> at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
> at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
> at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\140\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
> at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
> at <ScriptBlock>, C:\Run\navstart.ps1: line 157
> at <ScriptBlock>, C:\Run\start.ps1: line 121
> at <ScriptBlock>, <No file>: line 1
> Initialization of container bc14cutest failed
> In C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.0\ContainerHandling\Wait-NavContainerReady.ps1:44 Zeichen:17
> + ...             throw "Initialization of container $containerName failed" ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : OperationStopped: (Initialization ...bc14cutest failed:String) [], RuntimeException
>     + FullyQualifiedErrorId : Initialization of container bc14cutest failed

**Comment by freddydk** [comment]
Windows 10 1803 has been known to cause a lot of issues with NAV/BC containers.
I recommend 1809 or higher for running NAV/BC containers.

**Comment by dNsl9r** [comment]
Okay, as out IT department has not released the usage of a newer version than Windows 10 1803 I'll stuck with the problem for a long time. Thanks @freddydk - I'll close the ticket..

**Comment by freddydk** [comment]
Dangerous strategy since I guess security updates etc. are not shipped for Windows Versions that are not supported, but of course not much I can do about that.
You could try to download a new containerhelper in a few hours 0.6.5.1 and add -useBestContainerOS to the statement above - that might work.

**Comment by freddydk** [comment]
I discovered that the ltsc2016 version of this image probably was created with an error - and I will recreate this. The new image might work on 1803. Sorry for the inconvenience.
