### ISSUE TITLE
Sort-AppFoldersByDependencies throws PropertyNotFoundException if one of the app.json files does not have a dependencies property

### ISSUE THREAD

**Issue by rvanbekkum** [microsoft/navcontainerhelper#901]
Hi NavContainerHelper contributors,

I ran into the issue that `Sort-AppFoldersByDependencies` throws an exception, if one of my apps does not have a `dependencies` property in the `app.json` file.
That is, targeting BC16, I have replaced the dependencies on the Base and System Application with the `application` property in the `app.json` file in my 'main' app.
I was able to easily resolve this adding an empty list to the `app.json` file:
```json
"dependencies": [],
```
I am reporting it here anyway, because it might be good to have it fixed, as others might run into it as well.

**Comment by freddydk** [comment]
Thanks, will have a look.

**Comment by freddydk** [comment]
Fixed in 0.6.5.1 and 0.6.5.2
