### ISSUE TITLE
Export-ModifiedObjectsAsDeltas error

### ISSUE THREAD

**Issue by barandeniz** [microsoft/navcontainerhelper#902]
Hello, i am getting the error below when i run this command: **Export-ModifiedObjectsAsDeltas**

![image](https://user-images.githubusercontent.com/6250904/77086004-2c18cd80-6a12-11ea-85d8-4510d7dcd4dc.png)

**Comment by freddydk** [comment]
You are not giving us a lot to work with?
What image, which host version, which container version etc. etc.
Best thing is to include the full script to repro the problem (including the output from it), that includes a lot of debug info.

**Comment by barandeniz** [comment]
$containerName = "bc1411-dev"

$imageName = "mcr.microsoft.com/businesscentral/onprem:14.11.41204.0-w1"
$licenseFile = "C:\20200220 - BC14 Development Licence ISV Rights Included.flf"
$credential = New-Object pscredential 'infotek', (ConvertTo-SecureString -String 'Inf123++' -AsPlainText -Force)
 
$auth = "UserPassword"

New-NavContainer -containerName $containerName -accept_eula -accept_outdated -auth UserPassword -Credential $credential -doNotExportObjectsToText -imageName $imageName -includeCSide -isolation process -licenseFile $licenseFile -PublicDnsName $containerName -shortcuts Desktop -updateHosts -locale "tr-TR" -memoryLimit 3G

=============================================================

NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Using image mcr.microsoft.com/businesscentral/onprem:14.11.41204.0-w1-ltsc2019
PublicDnsName is bc1411-dev
Removing C:\ProgramData\NavContainerHelper\Extensions\bc1411-dev
Creating Container bc1411-dev
Version: 14.11.41204.0-W1
Style: onprem
Platform: 14.0.41143.0
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.1039 (ltsc2019)
Using locale tr-TR
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\20200220 - BC14 Development Licence ISV Rights Included.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bc1411-dev\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container bc1411-dev from image mcr.microsoft.com/businesscentral/onprem:14.11.41204.0-w1-ltsc2019
35d9e88b69992310746187ce4bf7cfff9788fb01f3c0a30fe1bff7b181c30653
Waiting for container bc1411-dev to be ready
Initializing...
Setting host.docker.internal to 192.168.16.70 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.16.70 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.20.112.1 in container hosts file
Starting Container
Hostname is bc1411-dev
PublicDnsName is bc1411-dev
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint C00CB1D1B99E862949C1F519BAC4E15654EC5F7A
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Setting SA Password and enabling SA
Creating infotek as SQL User and add to sysadmin
Creating SUPER user
Container IP Address: 172.20.121.47
Container Hostname  : bc1411-dev
Container Dns Name  : bc1411-dev
Web Client          : http://bc1411-dev/NAV/
Dev. Server         : http://bc1411-dev
Dev. ServerInstance : NAV
Setting bc1411-dev to 172.20.121.47 in host hosts file

Files:
http://bc1411-dev:8080/al-3.0.193882.vsix

Initialization took 306 seconds
Ready for connections!
Reading CustomSettings.config from bc1411-dev
Creating Desktop Shortcuts for bc1411-dev
Container bc1411-dev successfully created

**Comment by freddydk** [comment]
Looks like the February update problem.
https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/
https://freddysblog.com/2020/02/26/the-world-after-february-18th/

**Comment by barandeniz** [comment]
Trying the same scenario with hyperv and will close the issue if it solved the issue, thank you very much with your fast responses :)

**Comment by freddydk** [comment]
hyperv might cause issues with non-unicode apps (which C/AL and finsql is).
-useBestContainerOS takes longer, but should work in your case.

**Comment by barandeniz** [comment]
If it doesn't work with only hyperv next thing i am going to try with -useBestContainerOS. Thanks again.

**Comment by barandeniz** [comment]
I do not know if the problem was isolation but i tried same cmdlt on my local computer (on container ofc.) it worked. At least i know the problem is server specific. Thank you for your help.

**Comment by freddydk** [comment]
Your local machine probably is using Windows 10 1909 - which then causes hyperv to be default.
