### ISSUE TITLE
BC15 15.4.41345 Image

### ISSUE THREAD

**Issue by andrecavalcanti** [microsoft/navcontainerhelper#905]
Hi,

I cannot pull BC15 15.4.41345 Image.

![image](https://user-images.githubusercontent.com/6551266/77268223-a0a27500-6c7b-11ea-8fd4-26a7380aabc7.png)

If I try docker pull mcr.microsoft.com/businesscentral/onprem:1910-na-ltsc2019 I get only CU2 and not CU4

**Comment by ralf-escher** [comment]
It's `mcr.microsoft.com/businesscentral/onprem:15.4.41023.41345-na-ltsc2019`

Beginning with 15.3 they changed the version string _(I posted a corresponding question in the yammer insider forum, but no replies yet)_

**Comment by freddydk** [comment]
and

```
docker pull mcr.microsoft.com/businesscentral/onprem:1910-na-ltsc2019
docker inspect mcr.microsoft.com/businesscentral/onprem:1910-na-ltsc2019
```
reveals:
```
            "Labels": {
                "country": "na",
                "created": "202003171517",
                "cu": "cu4",
                "eula": "https://go.microsoft.com/fwlink/?linkid=861843",
                "legal": "http://go.microsoft.com/fwlink/?LinkId=837447",
                "maintainer": "Dynamics SMB",
                "nav": "",
                "osversion": "10.0.17763.973",
                "platform": "15.0.40939.41271",
                "tag": "0.0.9.99",
                "version": "15.4.41023.41345"
            },
```

**Comment by andrecavalcanti** [comment]
I get CU2 from docker inspect mcr.microsoft.com/businesscentral/onprem:1910-na-ltsc2019

I was able to get CU4 from mcr.microsoft.com/businesscentral/onprem:15.4.41023.41345-na-ltsc2019

![image](https://user-images.githubusercontent.com/6551266/77306160-a0cb6080-6ccd-11ea-87f4-505a15f4f97e.png)

**Comment by freddydk** [comment]
If you do docker pull the exact same thing - you get cu4.
You might have pulled the ltsc2016 version and inspected the 2019 version.

**Comment by andrecavalcanti** [comment]
You are right. Thanks for your help

![image](https://user-images.githubusercontent.com/6551266/77313318-01609a80-6cda-11ea-963b-30f18e7a5056.png)
