### ISSUE TITLE
Recreate Extensions folder content

### ISSUE THREAD

**Issue by fvet** [Microsoft/navcontainerhelper#91]
When using the New-CSideDevContainer commandlet, a folder structure for the container is created at 
C:\ProgramData\NavContainerHelper\Extensions with all RTC files.

For some reason, I have been (wrongfully) referring to this folder as 'shared' folder to test some export related commandlets, resulting in a deletion of all contents of the Extensions folder. 

Is there an easy way to recreate the contents of the Extension subfolder for a given container? Same could also apply for recreating the shortcuts.

**Comment by freddydk** [comment]
Unfortunately only by re-creating your containers:-(
