### ISSUE TITLE
Traefik configuration error although -useTraefik is not set

### ISSUE THREAD

**Issue by elweilando** [microsoft/navcontainerhelper#911]
` New-NavContainer  -doNotExportObjectsToText  -containerName: v14onprem -memoryLimit: 6G -useBestContainerOS -includeCSide -accept_eula -alwaysPull -imageName: mcr.microsoft.com/businesscentral/onprem:14.9.39327.0-de  -updateHosts`

Throws a configuration error although -useTrafik is not set

```
Using Traefik only makes sense if you allow external access, so you have to provide the public DNS name (param
-PublicDnsName)
In C:\develop\v14-201904-wave1-onprem\nav-docker-environment\microsoft-navcontainerhelper\ContainerHandling\New-NavCont
ainer.ps1:376 Zeichen:13
+             throw "Using Traefik only makes sense if you allow extern ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Using Traefik o...-PublicDnsName):String) [], RuntimeException
    + FullyQualifiedErrorId : Using Traefik only makes sense if you allow external access, so you have to provide the
   public DNS name (param -PublicDnsName)
```

**Comment by freddydk** [comment]
You are having colons after a number of the parameters

-memoryLimit: 6G

that is wrong.
Beside that - I am fixing #907 right now, which causes local onpremises containers to fail with useBestContainerOS

**Comment by elweilando** [comment]
> You are having colons after a number of the parameters
Sorry. Copy & Paste Error. The error throws also without colons 

`New-NavContainer -doNotExportObjectsToText -containerName v14onprem -memoryLimit 6G -useBestContainerOS -includeCSide -accept_eula -alwaysPull -imageName mcr.microsoft.com/businesscentral/onprem:14.9.39327.0-de -updateHosts`

I can fix this by adding -useTraefik:$false. 

Traefik container was initialized. The log tells me that
`WARNING: useTraefik not specified, but Traefik container was initialized, using Traefik. Specify -useTraefik:$false if you do NOT want to use Traefik.`

It's a little bit confusing. If the traefik container is initialized, the container use automatically Traefik, although it's not an option in the New-NavContainer params.

**Comment by freddydk** [comment]
That is correct and by design to allow build servers and other things to use the same scripts whether or not traefik is running. The workaround is (as you found) to specifically say you don't want traefik.
