### ISSUE TITLE
New-

### ISSUE THREAD

**Issue by mboon75** [microsoft/navcontainerhelper#913]
New-NavContainer fails with an error on Download file since version 0.6.5.1.
IT works in version 0.6.5.0

##[command]. 'F:\DevOps\Agent1\_work\2\s\Nav\BuildScripts\Create-Nav-Container' -ContainerName "MSBUILD101" -ImageName "mcr.microsoft.com/businesscentral/onprem:1904-cu5-nl-ltsc2016" -credential ([PSCredential]::new("Build", (ConvertTo-SecureString -String "WyS0lnt!0u" -AsPlainText -Force))) -ContainerStoragePath "C:\ProgramData\NavContainerHelper\Extensions\MSBUILD101\"
MemoryLimit set to 6G
NavContainerHelper is version 0.6.5.1
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2016 Datacenter - ltsc2016
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Pulling image mcr.microsoft.com/businesscentral/onprem:1904-cu5-nl-ltsc2016
1904-cu5-nl-ltsc2016: Pulling from businesscentral/onprem
Using image mcr.microsoft.com/businesscentral/onprem:1904-cu5-nl-ltsc2016
Creating Container MSBUILD101
Version: 14.6.36463.0-nl
Style: onprem
Platform: 14.0.36457.0
Generic Tag: 0.0.9.95
Container OS Version: 10.0.14393.3204 (ltsc2016)
Host OS Version: 10.0.14393.3542 (ltsc2016)
A better Generic Container OS exists for your host (mcr.microsoft.com/dynamicsnav:10.0.14393.3506-generic)
Patching navinstall.ps1 for 13.x and 14.x (issue #907)
Using generic image mcr.microsoft.com/dynamicsnav:10.0.14393.3506-generic
Pulling image mcr.microsoft.com/dynamicsnav:10.0.14393.3506-generic
10.0.14393.3506-generic: Pulling from dynamicsnav
Generic Container OS Version: 10.0.14393.3506 (ltsc2016)
Generic Tag of better generic: 0.0.9.99
WARNING: The container operating system matches the host operating system, but the revision is different.
If you encounter issues, you might want to specify -isolation hyperv
Using locale nl-NL
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Downloading C:\ProgramData\NavContainerHelper\Extensions\MSBUILD101\my\navinstall.ps1
##[error]Download-File : Exception calling "DownloadFile" with "2" argument(s): "The underlying connection was closed: An 
unexpected error occurred on a send."
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.1\ContainerHandling\New-NavContainer.ps1:826 
char:17
+ ...             Download-File -sourceUrl $_ -destinationFile $destination ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Download-File], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Download-File
 

##[error]Process completed with exit code 1 and had 1 error(s) written to the error stream.
##[section]Finishing: PS - Create Nav Container

**Comment by freddydk** [comment]
that is likely because your container cannot connect to the outside - often due to dns resolution not working. try to add -dns "8.8.8.8" (or set dns in Docker Deamon config)

**Comment by mboon75** [comment]
It stopped working after the download of NavContainerhelper 0.6.5.1. Before it worked.

**Comment by freddydk** [comment]
I still think it is because the dns isn't found - earlier you just might not need it (until some day...)
Could you set requiredversion to 0.6.5.0 and then submit the output of building that?
My assumption is that it doesn't re-platform. You can avoid this by removing -usebestcontaineros.

**Comment by mboon75** [comment]
ok, i'll try that out. But the last succesfull build was 45 minutes earlier. 16:13 today, then 17:02 we started a new build that pulled ContainerHelper 0.6.5.1 in, so that's why I find it a bit suspicious :)
After 17:02 all builds are failing...

**Comment by freddydk** [comment]
line 826 is trying to download a patch for navinstall, which fails for a number of 13.x and 14.x containers - it needs to be able to resolve dns for that.
14.6 (as you are using here) might have worked in 0.6.5.0 - but 14.10 and 14.11 didn't.

**Comment by mboon75** [comment]
Ok, i think it might be blocked by the firewall.

**Comment by freddydk** [comment]
Then you would have to use containerhelper 0.6.5.0 until new generic images have been deployed (in a few weeks)

**Comment by mboon75** [comment]
Ok, thanks for your super fast responses Freddy. Case can be closed.
