### ISSUE TITLE
Can't create sandbox container after latest update

### ISSUE THREAD

**Issue by MaxBelohoubek** [microsoft/navcontainerhelper#914]
Hey Freddy,

we get this error when creating new containers since you pushed the last update:
 
![image](https://user-images.githubusercontent.com/31455503/77528820-d9fefe80-6e8e-11ea-97e6-3a8b968a8889.png)

We think it could correlate with the fix to avoid the double image download.

This is the command used to create the container:

`New-NavContainer -accept_eula -alwaysPull -accept_outdated -containerName bc15 -auth NavUserPassword -shortcuts Desktop -includeTestToolkit -includeTestLibrariesOnly -doNotUseRuntimePackages -imageName mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019 -licenseFile $License -Credential $Credential -additionalParameters $EnvironmentVariables -myScripts $Scripts -useSSL -useBestContainerOS -updateHosts -restart always -includeAL -assignPremiumPlan
`

**Comment by freddydk** [comment]
Thanks - will have a look.
If you manually download the image - does it then work?

**Comment by freddydk** [comment]
docker pull mcr.microsoft.com/dynamicsnav:10.0.17763.914-generic

**Comment by MaxBelohoubek** [comment]
![image](https://user-images.githubusercontent.com/31455503/77532140-8f808080-6e94-11ea-9386-2c6f4aaa9da5.png)

Image was up-to-date. Same Error when creating a container.

**Comment by freddydk** [comment]
The issue is, that i try to get the generic tag before pulling the image.
Will fix this asap.

**Comment by MaxBelohoubek** [comment]
Thanks freddy!

**Comment by freddydk** [comment]
0.6.5.2 has been released, sorry for the inconvenience.
