### ISSUE TITLE
[Question] 2 Questions about New-NavContainer cmdlt.

### ISSUE THREAD

**Issue by barandeniz** [microsoft/navcontainerhelper#916]
Hello,
1) Can i change containers database name like CRONUS -->BC1411-DEV etc. etc. The reasong i am asking is we are trying to use docker environment for our C/SIDE developments. We have a container which includes customers objects. But every customers container database name becomes CRONUS hence its hard to see which customers database you are working with.

2) How can i install languages packages to docker containers for on prem installations? (the .msi files that are created from building translated resx files located in partnertranslationtoolkit relased by micrsoft)

**Comment by freddydk** [comment]
For the first one - you could place the database on the host or a standalone SQL Server and use that.
If you want to do it in the container, you can easily override the SetupDatabase.ps1 and use whatever name you want.

for 2 - I haven't tried, but I guess you should be able to install the .msi files silently (no UI) in the container (use Invoke-ScriptInNavContainer)
