### ISSUE TITLE
Cann not copy files from host to container

### ISSUE THREAD

**Issue by Mesomorf** [microsoft/navcontainerhelper#917]
I'm trying the copy a folders content from the host to the container using the following code.

`$licens_file = 'C:\licens.flf'`
`$addtional = @("-v c:\temp:c:\temp")`

`New-BCContainer -imageName $image -updateHosts -accept_eula -accept_outdated -containerName 'mod' -auth Windows -licenseFile $licens_file -additionalParameters $additional`

It's result in the following error

NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Pro for Workstations - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Using image mcr.microsoft.com/businesscentral/onprem:15.4.41023.41345-dk-ltsc2019
Removing container mod
Removing mod from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\mod
Creating Container mod
Version: 15.4.41023.41345-dk
Style: onprem
Platform: 15.0.40939.41271
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.18363.720 (1909)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale da-DK
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Workspace\Code\BC365\work\.local\licens.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\mod\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container mod from image mcr.microsoft.com/businesscentral/onprem:15.4.41023.41345-dk-ltsc2019
e47ea8de95a83877dd798682c565c1063b0ce2e2d24281ad5b5de1aee1c98b37
Waiting for container mod to be ready
docker : I n t e r n a l   W i n d o w s   P o w e r S h e l l   e r r o r .     L o a d i n g   m a n a g e d   W i n d o w s   P o w e r S h e l l   f a i l e d   w i t h   e r r o r   8 0 0 7 0 0 0 2 . 
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.0\ContainerHandling\Wait-NavContainerReady.ps1:32 char:21
+             $logs = docker logs $containerName
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (I n t e r n a l... 0 7 0 0 0 2 . :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

If I remove the -additionalParameters, I can deploy the image to the container.

**Comment by freddydk** [comment]
the -v parameter doesn't copy - it shares a folder to the container - meaning that the content of c:\temp on the host will be accessible as c:\temp in the container.
if the above script is exactly what you run, then you misspelled $additional when assigning the variable: $addtional = @("-v c:\temp:c:\temp")
