### ISSUE TITLE
Sign-NavContainerApp.ps1: Migration of Legacy VeriSign and Symantec Time Stamping Services

### ISSUE THREAD

**Issue by achim-t** [microsoft/navcontainerhelper#918]
According to this:
https://knowledge.digicert.com/alerts/migration-of-legacy-verisign-and-symantec-time-stamping-services.html

The timestamp url should no longer be `http://timestamp.verisign.com/scripts/timestamp.dll` but `timestamp.digicert.com?alg=sha1` instead. 

Otherwise signing is no longer possible.

**Comment by freddydk** [comment]
Aparently the above is not true, signing works fine with the old.
Will purchase a certificate myself again and add signing to my tests in order to see when/if things changes.
