### ISSUE TITLE
Get-NavContainers

### ISSUE THREAD

**Issue by bgbak** [Microsoft/navcontainerhelper#92]
A Get-NavContainers would be nice, to list all runing and stopped NAV containers.
Having output compatible with Remove-NavContainer would make cleanup of containers very easy.

**Comment by freddydk** [comment]
It was added in 0.2.2.0 and I think it works as you suggest (that was the intention)

**Comment by freddydk** [comment]
https://www.powershellgallery.com/packages/navcontainerhelper

**Comment by bgbak** [comment]
Great! :)
I see it now when I get comands from the module.
It's not listed when first importing the module, so that must be why I thought it was missing.

**Comment by bgbak** [comment]
Just to clarify.
I was working with version 0.2.2.2, and I see everything I thought was missing is now present the repo.
