### ISSUE TITLE
TimeZones and Globalization

### ISSUE THREAD

**Issue by ChrisBlankDe** [microsoft/navcontainerhelper#920]
We Should use `Get-TimeZone` to Get the TimeZone from the Docker Host.
This PowerShell function returns the TimeZone in the Client Language which is often not the same as the Docker Container.
This could result in warnings like this:

> WARNING: Container starts with TimeZone = Mitteleurop├ñische Zeit, which is not recognized in the list of TimeZones.

If you read the Value from the Registry we always get the english name of a time zone:
`Get-ItemPropertyValue -Path "HKLM:\SYSTEM\CurrentControlSet\Control\TimeZoneInformation\" -Name "TimeZoneKeyName"`
Response on a german system: `W. Europe Standard Time`

What do think about?

**Comment by freddydk** [comment]
The reason for the warning is really that running tests wouldn't work if this warning was present.
I managed to fix this - and really, I don't think there is any reason for this warning anymore - I can just remove it.

**Comment by freddydk** [comment]
The warning is happening in navstart.ps1 (in the generic layer).
I will consider removing the warning in the future
