### ISSUE TITLE
Microsoft.PowerShell.Commands.WriteErrorException,Import-NAVApplicationObject

### ISSUE THREAD

**Issue by JSebastianN** [microsoft/navcontainerhelper#922]
Failing to import Test Toolkit from the Image itself.
Begun today, worked yesterday :)

Perhaps it's and image problem and not NAVContainerHelper issue...

**Comment by JSebastianN** [comment]
Okay, this might be related to hyperV and security updates.

https://freddysblog.com/2020/02/26/the-world-after-february-18th/
https://freddysblog.com/2020/02/14/hyperv-isolation-to-the-rescue/

**Comment by freddydk** [comment]
Love it when issues solve themselves:-)
