### ISSUE TITLE
BC16 container creation fails

### ISSUE THREAD

**Issue by ysoldati** [microsoft/navcontainerhelper#923]
BC16 container creation fails:

VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_OperatingSystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
NavContainerHelper is version 0.6.4.9
Host is Microsoft Windows Server 2016 Standard - ltsc2016
Docker Client Version is 18.09.0
Docker Server Version is 18.09.0
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_OperatingSystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
Using image mcr.microsoft.com/businesscentral/onprem:16.0.11240.12076-be-ltsc2016
Disabling Health Check (always report healthy)
Removing container bc16
Removing bc16 from hosts
Removing C:\ProgramData\NavContainerHelper\Extensions\bc16
Creating Container bc16
Version: 16.0.11240.12076-be
Style: onprem
Platform: 16.0.11233.12061
Generic Tag: 0.0.9.99
Container OS Version: 10.0.14393.3443 (ltsc2016)
Host OS Version: 10.0.14393.3443 (ltsc2016)
Using locale nl-BE
Using process isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\NAV\License\bc16.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\bc16\my:
- AdditionalOutput.ps1
- license.flf
- MainLoop.ps1
- updatehosts.ps1
Creating container bc16 from image mcr.microsoft.com/businesscentral/onprem:16.0.11240.12076-be-ltsc2016
2cbba98181fd83d47862bbb712a4343ce3be2a13bf107314fa64cd1899ae76aa
Waiting for container bc16 to be ready
Initializing...
Starting Container
Hostname is bc16
PublicDnsName is bc16
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 057A6654379CE4EACEAAAEBA2B49C76923093EEF
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 157
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Starting Container
Hostname is bc16
PublicDnsName is bc16
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint 057A6654379CE4EACEAAAEBA2B49C76923093EEF
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
The data is invalid. (Exception from HRESULT: 0x8007000D)
at Set-NavSiteAuthenticationSettings, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 654
at New-NavWebSite, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 631
at New-NAVWebServerInstance, C:\Program Files\Microsoft Dynamics NAV\160\Web Client\Modules\NAVWebClientManagement\NAVWebClientManagement.psm1: line 501
at <ScriptBlock>, C:\Run\SetupWebClient.ps1: line 26
at <ScriptBlock>, C:\Run\navstart.ps1: line 157
at <ScriptBlock>, C:\Run\start.ps1: line 121
at <ScriptBlock>, <No file>: line 1
Initialization of container bc16 failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.4.9\ContainerHandling\Wait-NavContainerReady.ps1:44 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization of container bc16 failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container bc16 failed

**Comment by freddydk** [comment]
Looks strange - will investigate

**Comment by ysoldati** [comment]
Thanks,
I've created bc14 and bc15 containers with the script without problems today and yesterday

**Comment by freddydk** [comment]
I the onprem containers for ltsc2016 have been created with an error.
New ones will be created asap.

**Comment by freddydk** [comment]
Should be ready now, sorry for the inconvenience.

**Comment by ysoldati** [comment]
Perfect it is working.
Thx
