### ISSUE TITLE
BC16 - Compile App failed: Cannot bind argument to parameter 'AlcOutput' because it is null.

### ISSUE THREAD

**Issue by AndreasGloeckner** [microsoft/navcontainerhelper#924]
Our pipelines failes during the compilation with the following error:

```
Compiling...
alc.exe /project:C:\agent-W1\_work\2\s\<Repo>\app /packagecachepath:C:\agent-W1\_work\2\s\<Repo>\.alPackages /out:C:\agent-W1\_work\2\a\app\<AppFile> /assemblyprobingpaths:"C:\Program Files (x86)\Microsoft Dynamics NAV\160\RoleTailored Client","C:\Program Files\Microsoft Dynamics NAV\160\Service","C:\Program Files (x86)\Open XML SDK\V2.5\lib","c:\windows\assembly","C:\Test Assemblies\Mock Assemblies"
##[error]Compile-AppInBCContainer : Cannot bind argument to parameter 'AlcOutput' because it is null.
At C:\agent-W1\_work\2\s\Pipeline\Build-App\Compile-App.ps1:42 char:5
+     Compile-AppInBCContainer -containerName $containerName -credentia ...

+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : InvalidData: (:) [Compile-AppInNavContainer], ParameterBindingValidationException

    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Compile-AppInNavContainer
##[error]PowerShell exited with code '1'.
```
Compile command:
`Compile-AppInBCContainer -containerName $containerName -credential $adminCredentials -appProjectFolder $appProjectFolder -appSymbolsFolder $buildSymbolsFolder -appOutputFolder (Join-Path $buildArtifactFolder $_) -UpdateSymbols:$updateSymbols -AzureDevOps:$true -CopyAppToSymbolsFolder
`

The version is version: 16.0.11240.11946-de (pulled by "mcr.microsoft.com/businesscentral/sandbox:de").
Next insider minor ("bcinsider.azurecr.io/bcsandbox:de" - v15.5.41963.0-de) works.
Next insider major ("bcinsider.azurecr.io/bcsandbox-master:de" - v16.0.11240.12052-de) does not work.

The way we create our container:

$additionalParameters = @("--volume ""$($sharedFolder):$($sharedFolder)""")

```
New-BCContainer -accept_eula `
    -containerName $containerName `
    -auth NAVUserPassword `
    -Credential $adminCredentials `
    -imageName $bcImage `
    -additionalParameters $additionalParameters `
    -licenseFile $licensefile `
    -shortcuts $shortcuts `
    -includeTestToolkit:$testToolKit `
    -doNotUseRuntimePackages `
    -assignPremiumPlan `
    -bakFile $backupFile `
    -accept_outdated `
    -enableTaskScheduler:$false `
    -alwaysPull `
    -updateHosts `
    -useTraefik `
    -PublicDnsName $env:DNSNAME `
    -Restart always 
```

Do you need any other information?

Using navconainerhelper 0.6.5.2

**Comment by freddydk** [comment]
Did you find a solution to this problem?
I cannot repro this.

**Comment by freddydk** [comment]
Looking further - the only place this can happen is if the output from the compiler is blank - then Convert-ALCOutputToAzureDevOps will give this message.
I will make the function more resilient towards an empty result.

**Comment by freddydk** [comment]
Shipped in 0.6.5.6

**Comment by AndreasGloeckner** [comment]
Just wanted to let you know that it worked and fixed the issue.

**Comment by freddydk** [comment]
Thanks Andreas
