### ISSUE TITLE
Container running but I can't access it with Dev, RTC or WebClient

### ISSUE THREAD

**Issue by KFrellsen** [Microsoft/navcontainerhelper#93]
Hi.

I've created a new navcontainer of NAV 2018 DK CU2. It completed without errors and are running. However, I can't access the database/server through the Dev. client, RTC Client or Web Client.

I am able to open the Command and Powershell prompt on the container.

I am using this New-Navcontainer with these parameters:

new-navcontainer -accept_eula -containername dk2018cu2 -imageName microsoft/dynamics-nav:2018-cu2-dk -includecside -memorylimit 3G

When opening the WebClient i get the following error in IE:

"The DNS name does not exist.
Error Code: INET_E_RESOURCE_NOT_FOUND"

**Comment by freddydk** [comment]
and what URL are you trying to open in the WebClient?
What is the output of new-navcontainer?

**Comment by KFrellsen** [comment]
I'm connecting to this url: http://dk2018cu2/NAV/

The output was that it completed succesfully. I can run powershell commands in the container, so it is up and running.

I've also run net start in the container and both the SQLExpress services and the NAV server service are started.

**Comment by freddydk** [comment]
There is a lot of info in the output, that could help me troubleshoot the issue and this would save me and you time to get all the info possible.
But I can start guessing, try to use -updatehosts when you use new-navcontainer.

**Comment by KFrellsen** [comment]
Updatehosts didn't help much, unfortunately.

The output from New-NavContainer is:
Creating container dk2018cu2 from image microsoft/dynamics-nav:2018-cu2-dk
Waiting for container dk2018cu2 to be ready
Initializing...
Starting Container
Hostname is dk2018cu2
PublicDnsName is dk2018cu2
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying NAV Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import NAV License
Creating DotNetCore NAV Web Server Instance
Creating http download site
Creating Windows user SomeUser
Setting SA Password and enabling SA
Creating NAV user

(6937 rows affected)
Container IP Address: 172.31.253.144
Container Hostname  : dk2018cu2
Container Dns Name  : dk2018cu2
Web Client          : http://dk2018cu2/NAV/
Dev. Server         : http://dk2018cu2
Dev. ServerInstance : NAV

Files:
http://dk2018cu2:8080/al-0.12.16641.vsix

Initialization took 528 seconds
Ready for connections!
Reading CustomSettings.config from dk2018cu2
Creating Desktop Shortcuts for dk2018cu2
Nav container dk2018cu2 successfully created

**Comment by freddydk** [comment]
What springs into my eyes here is 528 seconds, normally this is 45 - 60 seconds.
Is your host exhausted?
Another thing, can you connect to http://<ip>/NAV?

**Comment by KFrellsen** [comment]
Hi again,

I cannot connect to http:///NAV either. 

It does take quite some time to install. Should I try to re-install Docker?

**Comment by freddydk** [comment]
If you open the container powershell prompt and type:
Get-NAVServerInstance NAV
you can see whether NAV is running or not.
If it is, then I expect your issues to be related to a anti-virus software or like that is preventing you from accessing the container.
You might be able to find some help here: https://blogs.msdn.microsoft.com/freddyk/2017/10/29/troubleshooting-nav-on-docker/
(I am on my way to board a plane now, won't be online for a number of hours)

**Comment by KFrellsen** [comment]
Hi Freddy.

Thanks for your big help. 

It works now - I did a couple of different things. First the HyperV network adapter needed to be updated, which i did and then i (although I've restarted several times) force closed the Docker from the task manager and now I'm able to connect.
