### ISSUE TITLE
Request to add a function to generate symbols

### ISSUE THREAD

**Issue by ajkauffmann** [Microsoft/navcontainerhelper#94]
It would be nice to have an extra command to generate symbol files in the container. The process is now quite cumbersome, could not really find the correct way how to do it inside the container using finsql.

**Comment by freddydk** [comment]
All images with generic tag 0.0.5.3 will have symbols generated and can be used for true dual development. Next version of containerhelper will have the command you are looking for

Få Outlook til iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Koubek** [comment]
Until that moment you can check the following link: https://www.linkedin.com/feed/update/urn:li:activity:6335434943841341440

**Comment by ajkauffmann** [comment]
Thanks Jakub. I know about C/SIDE and the flag to update symbols. But does it also work for importing objects using PowerShell script? I'm afraid it doesn't work in that scenario. That's why a command to generate symbols would be nice.
What would even be better is that the development endpoint on the NAV server can accept a command to generate symbols. Because of the compilation process that would probably not possible, but I'll suggest it anyway. ;-)

**Comment by freddydk** [comment]
If you take a new devpreview image (tag 0.0.5.3) I think you can import txt objects and compile them, then they should come available in VS Code.

**Comment by freddydk** [comment]
in 0.2.6.6 you can call Compile-NavContainerObjects -containername test -filter "compiled=1" to compile all objects and create symbols for all objects. It will create symbols for all objects compiled, but please note that all new containers do have symbols generaed for all objects.

**Comment by freddydk** [comment]
this is now live
