### ISSUE TITLE
Latest VSIX Analyzer DLL paths have changed

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/navcontainerhelper#940]
Using the latest VSIX file (Version 5.0.0+) has moved the analysers within a container from 
`C:\build\vsix\extension\bin\win32\Analyzers`
to
`C:\build\vsix\extension\bin\Analyzers`

It's assume in this line:https://github.com/microsoft/navcontainerhelper/blob/bef4ae2181f4be511df66767a9065eda151ab98e/AppHandling/Compile-AppInNavContainer.ps1#L367 that the path is a sibling of alc.exe, which still remains in the win32 directory.

**Comment by freddydk** [comment]
Regression - will be fixed right away, sorry.

**Comment by ShadowXVII** [comment]
Haha no worries -- I was blaming the VSIX team ;) 
Will keep an eye out for 0.6.5.6, thanks!

**Comment by freddydk** [comment]
We ran some tests on using the dotnetcore compiler and it is significantly faster and uses less memory. My tests just didn't include the analyzers:-(

**Comment by freddydk** [comment]
Shipped in 0.6.5.6
