### ISSUE TITLE
Error while fetch the Latest BC Image 

### ISSUE THREAD

**Issue by VAIBHAV-NAGAR** [microsoft/navcontainerhelper#942]
Hi,

While fetching the latest image, I am getting the below error:

![image](https://user-images.githubusercontent.com/58846308/78965680-55151580-7b1b-11ea-9c5d-72b5ed77a52e.png)
If anyone knows the solution and can help me out , it would be great

Thanks
Vaibhav

**Comment by freddydk** [comment]
That is likely a local problem on your machine.
Reset to factory defaults and try again (note that this will remove all images AND containers)
![image](https://user-images.githubusercontent.com/10775043/78969814-30fc0900-7b08-11ea-873c-1dc9771bc2dd.png)

**Comment by yrest** [comment]
we also had issues until Windows 10 has been updated to 1909.

**Comment by freddydk** [comment]
@VAIBHAV-NAGAR - did you manage to reset and make it work?

**Comment by VAIBHAV-NAGAR** [comment]
Hi Freddy 
I have updated my Windows to 1909 and the the error is resolved. 
Thank you

**Comment by freddydk** [comment]
Thanks for the info
