### ISSUE TITLE
Problems with symbols in container

### ISSUE THREAD

**Issue by Rukkulakki** [microsoft/navcontainerhelper#943]
I have created a danish 14 CU 8 image, and then added an old add-on (fob files).
I have then used Generate-SymbolsInNavContainer on the image (and even restarted the image). 

But when I try to download the new symbol files I get an error:
[2020-04-13 18:07:55.29] Targeting server 'http://PW/' and server instance 'NAV'.
[2020-04-13 18:07:55.29] Using Windows authentication.
[2020-04-13 18:07:55.30] Sending request to http://pw:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0
[2020-04-13 18:07:55.33] Sending request to http://pw:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2020-04-13 18:08:07.44] Error: a server-side error occured while processing the request.
Request ID: 68873d0a-ace3-4c6d-a6e0-4c92f2c525ff
Session ID: 3a60f3a8-6cfe-414e-bf61-432700736a2a

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-04-13 18:08:07.45] The request for path /NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0 failed with code ServiceUnavailable. Reason: The tenant 'default' is not accessible.
[2020-04-13 18:08:09.31] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

If I then try again, VS Code will download the old files. (Without the objects in the fob file).

I've also tried generating the symbols from the command prompt. It gives the same error (different GUIDs on the Request and Session IDs) and then redownload will download files without references to the additional/new objects.

Any advise?

**Comment by freddydk** [comment]
Please supply script and full output from container generation.
Also check event log (get-navcontainereventlog can be used) to see if that reveals anything.

**Comment by Rukkulakki** [comment]
PS C:\Windows\system32> $Containername = 'PW'
$Credentials = 'sh'
$ImageName = 'mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-dk'
$LicenseFile = 'C:\Nav\infar\5413194 Udviklerlicens BC 14 20200319.flf'

# Create NAV image 
$additionalParameters = @("--publish 8080:8080",
                          "--publish 443:443", 
                          "--publish 7046-7049:7046-7049")
New-NavContainer -containerName $Containername -accept_eula -accept_outdated -auth Windows -Credential $Credentials -doNotExportObjectsToText -imageName $ImageName -includeCSide -shortcuts DesktopFolder -updateHosts -licenseFile $LicenseFile -additionalParameters $additionalParameters

NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Using image mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-dk-ltsc2019
Removing container PW
Removing PW from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\PW
Creating Container PW
Version: 14.8.38658.0-dk
Style: onprem
Platform: 14.0.38650.0
Generic Tag: 0.0.9.97
Container OS Version: 10.0.17763.914 (ltsc2019)
Host OS Version: 10.0.18363.720 (1909)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale da-DK
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Nav\infar\5413194 Udviklerlicens BC 14 20200319.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\PW\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container PW from image mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-dk-ltsc2019
87770ca9590e363b720a1a03ad10a1b841c10f2ea57d15a9df2511e3be3a94d3
Waiting for container PW to be ready
Initializing...
Setting host.docker.internal to 10.4.20.74 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.20.74 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.23.224.1 in container hosts file
Starting Container
Hostname is PW
PublicDnsName is PW
WARNING: Container starts with TimeZone = Rom, normaltid, which is not recognized in the list of TimeZones.
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user sh
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.23.231.129
Container Hostname  : PW
Container Dns Name  : PW
Web Client          : http://PW/NAV/
Dev. Server         : http://PW
Dev. ServerInstance : NAV
Setting PW to 172.23.231.129 in host hosts file

Files:
http://PW:8080/al-3.0.193882.vsix

WARNING: You are running a container which is 121 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 78 seconds
Ready for connections!
Reading CustomSettings.config from PW
Creating Desktop Shortcuts for PW
Container PW successfully created

PS C:\Windows\system32> Import-ObjectsToNavContainer -containerName PW -objectsFile d:\Shared\pm.fob -ImportAction Overwrite -SynchronizeSchemaChanges Yes
Copy d:\Shared\pm.fob to container PW (c:\run\pm.fob)
Importing Objects from c:\run\pm.fob (container path)
Objects successfully imported

PS C:\Windows\system32> Generate-SymbolsInNavContainer -containerName PW
Creating application symbols in PW
[0] [13-04-20 18:58:37] The command completed successfully in '163' seconds.
Symbols successfully generated

Then opened the extension with launch:
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "al",
            "request": "launch",
            "name": "Your own server",
            "server": "http://PW/",
            "serverInstance": "NAV",
            "authentication": "Windows",
            "startupObjectId": 22,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true
        }
    ]
}

"Download symbols" This time slightly different in that I do not get the error; but still only get the old symbolfiles.

Example:
pageextension 51900 "Bank Acc. Recon. (PM) Ext" extends "Bank Acc. Reconciliation (PM)"
{
    actions
    {
        addafter("Import Account Statement")
        {
            action(ImportAltaPay)
            {
                Caption = 'Import AltaPay Statement';
                Ellipsis = true;
                Image = Import;
                Promoted = true;
                PromotedCategory = Process;
                ToolTipML = ENU = 'Importer AltaPay';
                trigger OnAction()
                var
                    BankStatmnt: Record "Bank Account Statement PM";
                    AltaPaySettImport: XmlPort "AltaPay Settlement Import";
                    BankAccRecon: Codeunit "Bank Acc. Recon. (PM)";
                begin
                    IF NOT MODIFY THEN
                        INSERT;

                    Commit();

                    BankStatmnt := Rec;
                    BankStatmnt.SETRECFILTER;
                    AltaPaySettImport.SetData(BankStatmnt);
                    AltaPaySettImport.Run();

                    BankAccRecon.Reconcile(BankStatmnt);

                    Commit();

                    CurrPage.UPDATE(FALSE);
                end;
            }
        }
    }
}

{
	"resource": "/d:/Git/PW/Economy/PageExtensions/BankAccReconPM.PageExt.al",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "AL0247",
	"severity": 8,
	"message": "The target Page \"Bank Acc. Reconciliation (PM)\" for the extension object is not found",
	"source": "AL",
	"startLineNumber": 1,
	"startColumn": 57,
	"endLineNumber": 1,
	"endColumn": 88
}



get-navcontainereventlog reveales a couple of warning, but no error. All warnings similar

Beskrivelsen af hændelses-id'et 705 fra kilden MicrosoftDynamicsNavServer$NAV blev ikke fundet. Enten er den komponent, der fremkalder denne hændelse, ikke installeret på den lokale computer, eller også er installationen beskadiget. Du kan installere eller reparere komponenten på den lokale computer.

Hvis hændelsen stammer fra en anden computer, skulle visningsoplysningerne være gemt samme med hændelsen.

Hændelsen indeholdt følgende oplysninger: 

Server instance: NAV
Category: Sql
ClientSessionId: 00000000-0000-0000-0000-000000000000
ClientActivityId: 00000000-0000-0000-0000-000000000000
ServerSessionUniqueId: 00000000-0000-0000-0000-000000000000
ServerActivityId: fddbfeee-4c83-404b-93ab-247de7d1bd4f
EventTime: 04/13/2020 16:58:20
Message Action completed successfully, but it took longer than the given threshold.
  Execution time: 10009 ms
  Threshold: 1000 ms
  Message: Long running SQL statement 
  Task ID: 3
  Connection ID: 4
  Database Name: Cronusdk
  Current Company Name: 
  Statement: SELECT "2000000071"."Metadata" FROM "SQLDATABASE".dbo."Object Metadata" "2000000071"  WITH(REPEATABLEREAD)  WHERE ("2000000071"."Object Type"=@0 AND "2000000071"."Object ID"=@1)
  
ProcessId: 2468
Tag: 000007L
ThreadId: 56
CounterInformation:

**Comment by freddydk** [comment]
I think you need to start the container with -enableSymbolLoading in order to regenerate symbols, and that should happen automatically in Import-ObjectsToNavContainer.
Could you try this (and then skip the generate-symbols line)

**Comment by Rukkulakki** [comment]
Unfurtunately it did not help.
Steps taken:
1. Regenerated the image with -enableSymbolLoading 
2. Imported the fob file. 
3. Download symbols in VS Code (error due to unknown object)
4. Restart container
5. Download symbols (Error: Server-side error....)

Script and resulting log below:

PS C:\Windows\system32> Import-Module navcontainerhelper
WARNING: The names of some imported commands from the module 'navcontainerhelper' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import
-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

PS C:\Windows\system32> $Containername = 'PW'
$Credentials = 'sh'
$ImageName = 'mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-dk'
$LicenseFile = 'C:\Nav\infar\5413194 Udviklerlicens BC 14 20200319.flf'

$additionalParameters = @("--publish 8080:8080",
                          "--publish 443:443", 
                          "--publish 7046-7049:7046-7049")
New-NavContainer -containerName $Containername -accept_eula -accept_outdated -auth Windows -Credential $Credentials -doNotExportObjectsToText -imageName $ImageName -includeCSide -enableSymbolLoading -shortcuts DesktopFolder -updateHosts -licenseFile $LicenseFile -additionalParameters $additionalParameters

NavContainerHelper is version 0.6.5.0
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Using image mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-dk-ltsc2019
Removing container PW
Removing PW from host hosts file
Removing C:\ProgramData\NavContainerHelper\Extensions\PW
Error removing C:\ProgramData\NavContainerHelper\Extensions\PW (attempts: 1)
Please close any apps, prompts or files using this folder
Retrying in 10 seconds
.
. (I wan't monotoring the process)
.
Removing C:\ProgramData\NavContainerHelper\Extensions\PW
Error removing C:\ProgramData\NavContainerHelper\Extensions\PW (attempts: 9)
Please close any apps, prompts or files using this folder
Retrying in 10 seconds
Removing C:\ProgramData\NavContainerHelper\Extensions\PW
Creating Container PW
Version: 14.8.38658.0-dk
Style: onprem
Platform: 14.0.38650.0
Generic Tag: 0.0.9.97
Container OS Version: 10.0.17763.914 (ltsc2019)
Host OS Version: 10.0.18363.720 (1909)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale da-DK
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Nav\infar\5413194 Udviklerlicens BC 14 20200319.flf
Files in C:\ProgramData\NavContainerHelper\Extensions\PW\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- updatehosts.ps1
Creating container PW from image mcr.microsoft.com/businesscentral/onprem:14.8.38658.0-dk-ltsc2019
1de96ec4b5203b34678fd370b52f3e03c6291b69e6ee20e2e32d6071197c4bb6
Waiting for container PW to be ready
Initializing...
Setting host.docker.internal to 10.4.20.74 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.20.74 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.23.224.1 in container hosts file
Starting Container
Hostname is PW
PublicDnsName is PW
WARNING: Container starts with TimeZone = Rom, normaltid, which is not recognized in the list of TimeZones.
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Modifying Service Tier Config File with Instance Specific Settings
Starting Service Tier
Registering event sources
Creating DotNetCore Web Server Instance
Using license file 'c:\run\my\license.flf'
Import License
Creating http download site
Creating Windows user sh
Setting SA Password and enabling SA
Creating SUPER user
Container IP Address: 172.23.230.105
Container Hostname  : PW
Container Dns Name  : PW
Web Client          : http://PW/NAV/
Dev. Server         : http://PW
Dev. ServerInstance : NAV
Setting PW to 172.23.230.105 in host hosts file

Files:
http://PW:8080/al-3.0.193882.vsix

WARNING: You are running a container which is 122 days old.
Microsoft recommends that you always run the latest version of our containers.

Initialization took 79 seconds
Ready for connections!
Reading CustomSettings.config from PW
Creating Desktop Shortcuts for PW
Container PW successfully created

PS C:\Windows\system32> Import-ObjectsToNavContainer -containerName PW -objectsFile d:\Shared\pm.fob -ImportAction Overwrite -SynchronizeSchemaChanges Yes
Copy d:\Shared\pm.fob to container PW (c:\run\pm.fob)
Importing Objects from c:\run\pm.fob (container path)
Objects successfully imported

PS C:\Windows\system32> Restart-NavContainer -containerName PW
PW
Waiting for container PW to be ready

Initializing...
Setting host.docker.internal to 10.4.20.74 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.4.20.74 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.23.224.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is PW
PublicDnsName is PW
Using Windows Authentication
Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.23.226.56
Container Hostname  : PW
Container Dns Name  : PW
Web Client          : 
Dev. Server         : http://PW
Dev. ServerInstance : NAV
Setting PW to 172.23.226.56 in host hosts file

Files:
http://PW:8080/al-3.0.193882.vsix

Initialization took 6 seconds
Ready for connections!

PS C:\Windows\system32> 


VS Code Output after restart:
[2020-04-14 17:02:52.79] Using reference symbols cache path: c:\Users\sh\Documents\AL\ALProject3\./.alpackages
[2020-04-14 17:02:52.79] Sending request to http://pw:7049/NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0
[2020-04-14 17:02:52.79] Sending request to http://pw:7049/NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0
[2020-04-14 17:02:52.87] Error: a server-side error occured while processing the request.
Request ID: a3cf4200-2b3a-4b2d-9818-cfdddce3e4f9
Session ID: 2cd4525e-141b-4904-b78d-21e0fcf59c24

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-04-14 17:02:52.87] The request for path /NAV/dev/packages?publisher=Microsoft&appName=System&versionText=14.0.0.0 failed with code ServiceUnavailable. Reason: The tenant 'default' is not accessible.
[2020-04-14 17:02:52.87] Error: a server-side error occured while processing the request.
Request ID: 43ee258e-355f-4edb-b07e-8a12a7ab82cd
Session ID: 2cd4525e-141b-4904-b78d-21e0fcf59c24

If you are targeting a cloud instance, supply these IDs if contacting Microsoft support.
[2020-04-14 17:02:52.87] The request for path /NAV/dev/packages?publisher=Microsoft&appName=Application&versionText=14.0.0.0 failed with code ServiceUnavailable. Reason: The tenant 'default' is not accessible.
[2020-04-14 17:02:52.87] Could not download reference symbols. Please ensure that:
1. The correct server name and instance are specified in the launch.json file.
2. The correct application version is specified in the app.json file.
3. The dependencies are correctly specified in the app.json file.

Eventlog attached

[PW 2020-04-14 17.11.12.evtx.log](https://github.com/microsoft/navcontainerhelper/files/4476117/PW.2020-04-14.17.11.12.evtx.log)

**Comment by Rukkulakki** [comment]
Error 40 :( 

Seems there was some problems in the fob file I had received. When trying to run the objects straight from the Development client, I got a Schema synchronization error.
After synchronizing, I was able to download the symbols with the additional objects.

**Comment by Rukkulakki** [comment]
But perhaps some sort of control/errormessage (if possible) in the Import-ObjectsToNavContainer part.

PS C:\Windows\system32> Import-ObjectsToNavContainer -containerName PW -objectsFile d:\Shared\pm.fob -ImportAction Overwrite -SynchronizeSchemaChanges Yes
Copy d:\Shared\pm.fob to container PW (c:\run\pm.fob)
Importing Objects from c:\run\pm.fob (container path)
Objects successfully imported

This indicates that everything is OK. But since there was a problem in my fob file, I had to synchronize manually, and then Generate symbolfiles.
Granted, if the fob file had been all good, there probaby wouldn't have been any problem :)

**Comment by freddydk** [comment]
Thanks, will try to repro and see if I can surface an error if possible.

**Comment by freddydk** [comment]
I won't have time to fix this
