### ISSUE TITLE
1903 and Process isolation

### ISSUE THREAD

**Issue by larshaedersdal** [microsoft/navcontainerhelper#945]
I have a container based on microsoft/dynamics-nav:2016-dk-ltsc2019 that I cannot start. 
Its an old container created in 2019 when my windows 10 machine was not updated. I have rolled back the windows updates as fare as I could and windows is now on 1903.  When I start the container now it gives me this error

`docker : Error response from daemon: hcsshim::CreateComputeSystem: The container operating system does not match the host operating system.`

When I inspect the container I can see that it runs in "process isolation" and I guess that's why I couldn't start it in windows version 1909. 

My question is: Is there any way to get this up and running again? I, of course, have c/al code in the container that is not backed up :-(

**Comment by freddydk** [comment]
Ouch.
You can try
```
docker cp "containername:c:\databases\Cronusdk\Demo Database NAV (9-0)_Data.mdf" "c:\temp\Demo Database NAV (9-0)_Data.mdf"
docker cp "test:c:\databases\Cronusdk\Demo Database NAV (9-0)_Log.ldf" "c:\temp\Demo Database NAV (9-0)_Log.ldf"
```
from a command prompt to copy the database out. (don't know if this works).
With that, I guess you can attach the database to a SQL Server - open the DB with the classic client and export your objects.

**Comment by larshaedersdal** [comment]
Nice one Freddy that worked like a charm, just the trick I was looking for :-)

**Comment by freddydk** [comment]
A good rule to live by: Never try to keep containers alive - save the script to regenerate the container.
:-)
In case of C/AL - it might be a good idea to have the database outside the container.,

**Comment by larshaedersdal** [comment]
Jep, lesson learned :-)
