### ISSUE TITLE
Traefik exited

### ISSUE THREAD

**Issue by BozidarP** [microsoft/navcontainerhelper#946]
I have installed all environment, have 6-7 containers in VM on Azure:

I use: http://aka.ms/getbc, use traeffik and specify an email for letsencrypt.

Its works great, until today, I cannot start traefik .
Any suggest what to do?
![image](https://user-images.githubusercontent.com/44054400/79375426-e7bd1680-7f58-11ea-968f-b4251350c600.png)
![image](https://user-images.githubusercontent.com/44054400/79375451-f0ade800-7f58-11ea-84db-dd43918157cc.png)

**Comment by BozidarP** [comment]
Output 
docker inspect 
PS C:\Users\vmadmin> docker inspect 92
[
    {
        "Id": "92e4095676fb9e831a717d7089a5b64a91250ca953c82b7b888e327163f72fc3",
        "Created": "2019-12-26T10:19:18.2380695Z",
        "Path": "/traefik",
        "Args": [
            "--docker.endpoint=npipe:////./pipe/docker_engine"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 3221225786,
            "Error": "failed to create endpoint naughty_jepsen on network nat: hnsCall failed in Win32: The process cannot access the file because it is being used by another process. (0x20)",
            "StartedAt": "2020-04-08T12:11:31.5087949Z",
            "FinishedAt": "2020-04-15T17:20:36.1590525+02:00"
        },
        "Image": "sha256:93bc9a495e51a6b92b4fc64359dd53de76b1e6d27c24dd8161c838e469b4ea72",
        "ResolvConfPath": "",
        "HostnamePath": "",
        "HostsPath": "",
        "LogPath": "C:\\ProgramData\\docker\\containers\\92e4095676fb9e831a717d7089a5b64a91250ca953c82b7b888e327163f72fc3\\92e4095676fb9e831a717d7089a5b64a91250ca953c82b7b888e327163f72fc3-json.log",
        "Name": "/naughty_jepsen",
        "RestartCount": 0,
        "Driver": "windowsfilter",
        "Platform": "windows",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "c:\\programdata\\navcontainerhelper\\traefikforbc\\config:c:/etc/traefik",
                "\\\\.\\pipe\\docker_engine:\\\\.\\pipe\\docker_engine"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {
                "443/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "443"
                    }
                ],
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "80"
                    }
                ],
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8080"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 0,
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "process",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": [],
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": null,
            "ReadonlyPaths": null
        },
        "GraphDriver": {
            "Data": {
                "dir": "C:\\ProgramData\\docker\\windowsfilter\\92e4095676fb9e831a717d7089a5b64a91250ca953c82b7b888e327163f72fc3"
            },
            "Name": "windowsfilter"
        },
        "Mounts": [
            {
                "Type": "npipe",
                "Source": "\\\\.\\pipe\\docker_engine",
                "Destination": "\\\\.\\pipe\\docker_engine",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "c:\\programdata\\navcontainerhelper\\traefikforbc\\config",
                "Destination": "c:\\etc\\traefik",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "92e4095676fb",
            "Domainname": "",
            "User": "containeradministrator",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "443/tcp": {},
                "80/tcp": {},
                "8080/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TRAEFIK_VERSION=1.7.12"
            ],
            "Cmd": [
                "--docker.endpoint=npipe:////./pipe/docker_engine"
            ],
            "Image": "stefanscherer/traefik-windows:v1.7.12",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": [
                "/traefik"
            ],
            "OnBuild": null,
            "Labels": {
                "org.label-schema.description": "A modern reverse-proxy",
                "org.label-schema.docker.schema-version": "1.0",
                "org.label-schema.name": "Traefik",
                "org.label-schema.url": "https://traefik.io",
                "org.label-schema.vendor": "Containous",
                "org.label-schema.version": "v1.7.12"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "92e4095676fb9e831a717d7089a5b64a91250ca953c82b7b888e327163f72fc3",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "92e4095676fb9e831a717d7089a5b64a91250ca953c82b7b888e327163f72fc3",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "nat": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "b5318a5d3bad41a5af563e616e2ccd376bd0e6c39d72a1a81a81411a3d25716e",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }

**Comment by freddydk** [comment]
Is this a new VM - or an old running VM that got the update?

**Comment by BozidarP** [comment]
I solve issue, thanks Freddy for answering.

**Comment by freddydk** [comment]
Please let people know here what the issue was (in case other people run into the same issue)

**Comment by BozidarP** [comment]
First I resarch many hours ...in that time I paste some commands from internet from people who have same issue,(sorry but not saving, next time I will)

What solve issue?
JusI uninnstaled last Windows update from 15.04.2020, and stop all updates.
After restart Windows -  traefik  - container work successfully.

Because I know this is not permanent solution my plan is to do next:
- for VM where is containers hosted  is very important to be LIVE 24/7, 
I will setup new VM from backup and try on that "reserve" to see what exactly problem with update.

I will get back on this after few days.

**Comment by dNsl9r** [comment]
Any detailed information why this happens? We've got the same issue - but no windows installed the last few days..
