### ISSUE TITLE
Azure SQL "Database requires a Per Database license to be openend on SQL Azure"

### ISSUE THREAD

**Issue by elweilando** [Microsoft/navcontainerhelper#95]
I migrate a database from on-premise to azure SQL. If I try to start CSIDE I got the issue:

"The DatabaseName on the DatabaseServer requires a Per Database license to be opened on SQL Azure".

I fix it trough this workaround: https://ricardomoinhos.com/error-importing-nav-license-in-azuresql-database

It is possible to include this workaround? Or is a option already available?

**Comment by freddydk** [comment]
Could you tell me how you run the container?
if you specify a license file to the new-navcontainer, it should import the license file to the database.

**Comment by elweilando** [comment]
I run the container with New-NavContainer


    New-NavContainer -accept_eula 
        -containerName $containerName 
        -imageName $dockerImage 
        -licenseFile $licenseFile 
        -memoryLimit 4G 
        -includeCSide 
        -doNotExportObjectsToText 
        -Credential $hostCredentials 
        -alwaysPull 
        -updateHosts 
        -auth 'Windows' 
        -additionalParameters $additionalParameters 
        -myScripts $myScripts 
        -databaseServer $databaseServer 
        -databaseName $databaseName 
        -databaseCredential $databaseCredentials

**Comment by freddydk** [comment]
I can see, that the setuplicense script is only running when using the local database server.
I will have a look at what the right approach is here.

**Comment by freddydk** [comment]
This is fixed in new docker containers based on generic layer 0.0.5.5
