### ISSUE TITLE
New-NavContainer Error for BC16 On Prem- Get-NavContainerCountry : The property 'Config' cannot be found on this object. 

### ISSUE THREAD

**Issue by ryancairnsy** [microsoft/navcontainerhelper#950]
Hi Freddy - I am getting this error trying to create a BC16 On Prem container - I have tried W1 and GB versions - same error.

_NavContainerHelper is version 0.6.5.6
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Pulling image  mcr.microsoft.com/businesscentral/onprem:2004-w1
2004-w1: Pulling from businesscentral/onprem
Using image  mcr.microsoft.com/businesscentral/onprem:2004-w1
Removing C:\ProgramData\NavContainerHelper\Extensions\BC16W1
**Error: No such object:  mcr.microsoft.com/businesscentral/onprem:2004-w1
Get-NavContainerCountry : The property 'Config' cannot be found on this object. Verify that the property exists.**
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.6\ContainerHandling\New-NavContainer.ps1:**570 char:23**
+ ... devCountry = Get-NavContainerCountry -containerOrImageName $imageName
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-NavContainerCountry], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,Get-NavContainerCountry_

Thanks

**Comment by freddydk** [comment]
What is the script you are using?

**Comment by ryancairnsy** [comment]
New-NavContainer `
    -containerName $ContainerName `
    -accept_eula `
    -auth NavUserPassword `
    -Credential $credential `
    -restart no `
    -imageName $ImageName `
    -licenseFile $LicenceFile `
    -useBestContainerOS `
    -accept_outdated `
    -updateHosts `
    -alwaysPull

**Comment by freddydk** [comment]
It looks like you have pulled the ltsc2016 version of the image.
Try to use mcr.microsoft.com/businesscentral/onprem:2004-w1-ltsc2019
In the meantime, I will try using the 2016 version to repro (takes some time to pull though)

**Comment by ryancairnsy** [comment]
Same error with ltsc2019. I am just testing with onprem:1910-w1-ltsc2019 now. I'll report back on this. Thanks

**Comment by freddydk** [comment]
What does this command return:
`Get-NavContainerCountry -containerOrImageName  mcr.microsoft.com/businesscentral/onprem:2004-w1-ltsc2019`

**Comment by ryancairnsy** [comment]
> What does this command return:
> 
> ```
> Get-NavContainerCountry -containerOrImageName  mcr.microsoft.com/businesscentral/onprem:2004-w1-ltsc2019
> ```

W1

onprem:1910-w1-ltsc2019 - also generated the same error. I'm going to keep testing different images as I have been creating different containers lots last week. I can't be sure if I had -alwayspull set though

**Comment by freddydk** [comment]
Ok, so this hasn't anything to do with the images - it has something to do with your script - some of the values are off - I cannot see which.

**Comment by ryancairnsy** [comment]
What does the "Error: No such object: mcr.microsoft.com/businesscentral/onprem:2004-w1" suggest?

**Comment by freddydk** [comment]
The error comes from this line: 
https://github.com/microsoft/navcontainerhelper/blob/8d3e76d03940de0398150ec9d94176e6835c20d2/ContainerHandling/New-NavContainer.ps1#L570

and if the image name is correct, it shouldn't.
the get-navcontainercountry is doing:

```
$inspect = docker inspect $containerOrImageName | ConvertFrom-Json
if ($inspect.Config.Labels.psobject.Properties.Match('nav').Count -eq 0) {
```
and the error is the Config isn't part of the inspect.

Maybe your imagename has a space appended or prefixed?

**Comment by freddydk** [comment]
Just tried - if your imagename starts with a space or a special character = garbage - then you could get an error like this.

**Comment by ryancairnsy** [comment]
Where's that face palm emoji!! Yes I have a space at the start of the image name - I am so sorry for wasting your time. Thanks for the help though I would not have spotted that.
