### ISSUE TITLE
Run-TestsInBcContainer returns error - "The field with ID = 2116990794 is not found on the page"

### ISSUE THREAD

**Issue by BillJay1821** [microsoft/navcontainerhelper#951]
Using NavContainerHelper 0.6.4.26.

Run-TestsInBcContainer returns error - "The field with ID = 2116990794 is not found on the page" as well as in the web client using 130455, but when running the same test using 130401, it returns the expected Assert.AreEqual result.

I used HelloWorld from GitHub and added test 50134 that's also attached to this issue.

```
C:\> Get-InstalledModule -Name NavContainerHelper

Version    Name                                Repository           Description                                                                                                                                                         
-------    ----                                ----------           -----------                                                                                                                                                         
0.6.4.26   navcontainerhelper                  PSGallery            PowerShell module 

C:\> Run-TestsInBcContainer -containerName navserverus -extensionId '00000000-0000-0000-0000-000000000002' -credential $credential -testSuite 'Default' -debugMode -testCodeunit 50134 -returnTrueIfAllPassed -detailed
Setting Extension Id 00000000-0000-0000-0000-000000000002
  Codeunit 50134 HelloWorld Replicate Failure (3.438 seconds)
    Testfunction TestHelloWorldReplicateMessage Failure (3.05 seconds)
      Error:
        The field with ID = 2116990794 is not found on the page.
      Call Stack:
        "HelloWorld Replicate"(CodeUnit 50134).ReplicateVerifySalesInvoiceTest5 line 13 - Default Test App Name by Default Publisher
        "HelloWorld Replicate"(CodeUnit 50134).TestHelloWorldReplicateMessage line 3 - Default Test App Name by Default Publisher
        "Test Runner - Mgt"(CodeUnit 130454).RunTests - Test Runner by Microsoft
        "Test Runner - Isol. Codeunit"(CodeUnit 130450).OnRun - Test Runner by Microsoft
        "Test Suite Mgt."(CodeUnit 130456).RunTests - Test Runner by Microsoft
        "Test Suite Mgt."(CodeUnit 130456).RunSelectedTests - Test Runner by Microsoft
        "Command Line Test Tool"(Page 130455)."RunSelectedTests - OnAction" - Test Runner by Microsoft

```

[Codeunit 50134 - HelloWorld Replicate.al.txt](https://github.com/microsoft/navcontainerhelper/files/4505571/Codeunit.50134.-.HelloWorld.Replicate.al.txt)

**Comment by freddydk** [comment]
130455 is using the AL Test Framework from 15.x
130401 is the C/AL Test Framework for pre 15.x (which still exists in 15.x and 16.x - but probably not in 17.x)
When using Run-TestsInBcContainer with extensionid, then you typically won't use testsuite as well. The system will locate the tests in the extension with that extensionid. That GUID btw - looks like a hardcoded one - we don't recommend inventing guids yourself.
Sounds like you haven't imported the AL test framework.

**Comment by BillJay1821** [comment]
I am using image mcr.microsoft.com/businesscentral/sandbox:16.0.11240.11946-us-ltsc2016, so this is BC 16.x.

In our main app which is receiving the same error, the developers are running the tests using the current test page 130401, but the error we're receiving is coming from 130455 and therefore from PowerShell when using Run-TestsInBcContainer because our tests need to also execute properly in a pipeline.

![image](https://user-images.githubusercontent.com/21239493/79792577-236f2c00-831d-11ea-89fe-9808b0c644f9.png)

The GUID was provided by the test app in the HelloWorld app on GitHub which I thought was created by @freddydk, so it was not provided by me.
![image](https://user-images.githubusercontent.com/21239493/79792427-ddb26380-831c-11ea-9986-55c059b71688.png)

The container was created by NavContainerHelper and then Import-TestToolkitToNavContainer was used to import the testing APPs.

`Import-TestToolkitToNavContainer -containerName navserverus -sqlCredential $credential
`

**Comment by freddydk** [comment]
That repo is used for the Hands On Lab and that one states that you should replace the GUIDs with "real" GUIDs:-)
But... - that isn't the problem here.
Could you give me the URL you have cloned?
Sounds like you have a 14.x test app and you are trying to run it in 16.x.
If you remove -extensionid and add -testpage 130409 then it will maybe run.
Then you would need to change things to use the AL Test framework instead.

**Comment by BillJay1821** [comment]
[https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld](url)

Unfortunately the test fails even harder when using 130409, but the core of the issue is probably that the test app was not completely upgraded from 14.x to 16.x, but given that I replicated the error using an extremely simple test and I am not the person doing the development, I can't comment on whether the code below is compatible with 16.x testing standards myself.

`Run-TestsInBcContainer -containerName navserverus -credential $credential -testPage 130409 -testCodeunit 50134 -debugMode -returnTrueIfAllPassed -detailed`

When using 130455, it was erroring on assert.AreEqual line.

```
procedure ReplicateVerifySalesInvoiceTest5()
    var
        SalesHeader: record "Sales Header";
        SalesLine: Record "Sales line";
        SalesInvoice: TestPage "Sales Invoice";
    begin
        SalesHeader.Reset();
        SalesHeader.SetFilter(SalesHeader."Document Type", '=%1', SalesHeader."Document Type"::Invoice);
        SalesHeader.FindFirst();
        SalesLine.Setfilter("Document No.", SalesHeader."No.");
        SalesLine.FindFirst();
        SalesInvoice.OpenEdit();
        SalesInvoice.GoToRecord(SalesHeader);
        assert.AreEqual(0, SalesInvoice.SalesLines.Type.AsInteger(), ValueIncorrectErr);
    end;
```

**Comment by freddydk** [comment]
The repo above should be 15.x - but there is also a 14.x version.
But... - you need to be running the tests using 130455.

What are the dependencies in your app.json from the test app?
BTW - You could probably also run the tests from VS Code by calling the test function manually and debug why this happens.

**Comment by BillJay1821** [comment]
> The repo above should be 15.x - but there is also a 14.x version

[https://dev.azure.com/businesscentralapps/HelloWorld/_git/HelloWorld](url)

Are you saying that the HelloWorld app, which runs it's own test (50133) successfully in 16.x is not compatible with 16.x?

I am NOT saying that I used the HelloWorld app as a base for our app, I am saying that I am using the HelloWorld app as written and added a single test to enable replication of the reported issue.

[Codeunit 50134 - HelloWorld Replicate.al.txt](https://github.com/microsoft/navcontainerhelper/files/4509391/Codeunit.50134.-.HelloWorld.Replicate.al.txt)

mcr.microsoft.com/businesscentral/sandbox:16.0.11240.11946-us-ltsc2016

We're doing 16.x development and all the tests are running successfully in 16.x's Test Tool (?page=130401) and most of the tests are running successfully in PowerShell using Run-TestsInBcContainer and all the ones that are failing are failing with some variant of the "field with ID = xxxx is not found on the page", so I extracted and adapted one failing test and implemented it in the HelloWorld app found on GitHub.

> What are the dependencies in your app.json from the test app?

Since I used the HelloWorld app from GitHub and just added test number 50134, there is no change in dependencies.

> BTW - You could probably also run the tests from VS Code by calling the test function manually and debug why this happens.

When executing the ReplicateVerifySalesInvoiceTest5 procedure in test 50134 and using 130455, it's reaching Assert.AreEqual and instead of doing the comparison as it does in the interactive web test tool, it's failing with the error reported about a missing field.

Below is the full text of the procedure that's only failing on the Assert.AreEqual line when the test is being executed in PowerShell using Run-TestsInBcContainer - this same test runs without the error using ?page=130401 in the web client.

```
procedure ReplicateVerifySalesInvoiceTest5()
    var
        SalesHeader: record "Sales Header";
        SalesLine: Record "Sales line";
        SalesInvoice: TestPage "Sales Invoice";
    begin
        SalesHeader.Reset();
        SalesHeader.SetFilter(SalesHeader."Document Type", '=%1', SalesHeader."Document Type"::Invoice);
        SalesHeader.FindFirst();
        SalesLine.Setfilter("Document No.", SalesHeader."No.");
        SalesLine.FindFirst();
        SalesInvoice.OpenEdit();
        SalesInvoice.GoToRecord(SalesHeader);
        assert.AreEqual(0, SalesInvoice.SalesLines.Type.AsInteger(), ValueIncorrectErr);
    end;
```

**Comment by freddydk** [comment]
I am saying that 130401 is the wrong page.
That is C/AL Test Framework and will likely disappear in a not so distant future.
I am saying that the HelloWorld project has dependencies on:

```
"dependencies": [
    {
      "appId": "63ca2fa4-4f03-4f2b-a480-172fef340d3f",
      "publisher": "Microsoft",
      "name": "System Application",
      "version": "15.0.0.0"
    },
    {
      "appId": "437dbf0e-84ff-417a-965d-ed2bb9650972",
      "publisher": "Microsoft",
      "name": "Base Application",
      "version": "15.0.0.0"
    },
    {
      "appId": "dd0be2ea-f733-4d65-bb34-a28f4624fb14",
      "publisher": "Microsoft",
      "name": "Library Assert",
      "version": "15.0.0.0"
    },
    {
      "appId": "e7320ebb-08b3-4406-b1ec-b4927d3e280b",
      "publisher": "Microsoft",
      "name": "Any",
      "version": "15.0.0.0"
    },
    {
      "appId": "9856ae4f-d1a7-46ef-89bb-6ef056398228",
      "publisher": "Microsoft",
      "name": "System Application Test Library",
      "version": "15.0.0.0"
    },
    {
      "appId": "5d86850b-0d76-4eca-bd7b-951ad998e997",
      "publisher": "Microsoft",
       "name": "Tests-TestLibraries",
       "version": "15.0.0.0"
    },    
    {
      "appId": "23de40a6-dfe8-4f80-80db-d70f83ce8caf",
      "publisher": "Microsoft",
       "name": "Test Runner",
       "version": "15.0.0.0"
    },    
    {
      "name": "Default App Name",
      "publisher": "Default Publisher",
      "version": "1.0.0.0",
      "appId": "00000000-0000-0000-0000-000000000001"
    }
  ],
```

which is the AL Test Framework - and it sounds like you maybe are using the C/AL version of some of these.

So - you need to get it to work using 130455 - then I guess Run-Tests will work as well.

**Comment by freddydk** [comment]
The only way I can help further is probably by getting something with which I can repro your problem.

**Comment by BillJay1821** [comment]
> The only way I can help further is probably by getting something with which I can repro your problem.

From the first post, I have stated that this can be replicated by using the HelloWorld app that can be cloned from GitHub and adding a single test, 50134, that is already part of this issue, but I'll add it again below.

[Codeunit 50134 - HelloWorld Replicate.al.txt](https://github.com/microsoft/navcontainerhelper/files/4509904/Codeunit.50134.-.HelloWorld.Replicate.al.txt)

I've also included the Docker BC repo, mcr.microsoft.com/businesscentral/sandbox:16.0.11240.11946-us-ltsc2019. but I don't think this issue is specific to this BC version.

The container was created using New-NavContainer in NavContainerHelper and the test toolkit imported using Import-TestToolkitToNavContainer and the test(s) run in PowerShell using Run-TestsInBcContainer.

```
New-NavContainer  `
 -accept_eula `
 -accept_outdated `
 -containerName navserverus `
 -PublicDnsName navserverus `
 -imageName mcr.microsoft.com/businesscentral/sandbox:16.0.11240.11946-us-ltsc2019 `
 -auth NAVUserPassword `
 -Credential $credential `
 -memoryLimit 8G `
 -isolation "hyperv" `
 -updateHosts `
 -EnableTaskScheduler:$false `
 -doNotExportObjectsToText `
 -shortcuts "None" `
 -licenseFile C:\WS\license.flf `

Import-TestToolkitToNavContainer -containerName navserverus -sqlCredential $sqlCredential

Run-TestsInBcContainer -containerName navserverus -credential $credential -testCodeunit 50134 -debugMode -returnTrueIfAllPassed -detailed
```
What am I missing? What else do you need?

**Comment by freddydk** [comment]
The rest of your test project - app.json at least

**Comment by BillJay1821** [comment]
> The rest of your test project - app.json at least

I don't understand how I can make this any more clear - use the HelloWorld app that you created that's on GitHub and add the one test I added - it includes everything you need, including the app.json.

**Comment by freddydk** [comment]
Please realize that there are 100s of partners who are successfully running tests on 16.x containers. 

This means that I am obviously looking for a typo somewhere in your setup.

As stated before - if you cannot run the tests in the AL test framework (page 130455) - then that is the problem, this is not a problem with Run-Tests cmdlet. I would try to put a debugger on and call the test from an action so that you can debug where it fails.

Could you please paste the complete output of container generation, importing of test toolkit etc. here, then I will have a look at that before spending hours to repro this.

Thanks

**Comment by BillJay1821** [comment]
I can at least see your point that if this issue occurs in the web client using 130455, then it is not really a NavContainerHelper issue with Run-TestsInBcContainer, so this is not the appropriate place for this.

**Comment by freddydk** [comment]
FYI - I changed the container to 16 in my pipeline and reran it:
![image](https://user-images.githubusercontent.com/10775043/79875451-f8064300-83e9-11ea-8fc1-791239649b23.png)
