### ISSUE TITLE
FailOn in Compile-AppInNavContainer does not fail compilation as stated in description

### ISSUE THREAD

**Issue by janicechewyc** [microsoft/navcontainerhelper#952]
```
.Parameter Failon
  Specify if you want Compilation to fail on Error or Warning (Works only if you specify -AzureDevOps)
```

As per the description in Compile-AppInNavContainer, FailOn param does not actually fail the compilation if the flags warning/error and -AzureDevOps are set. It seems like it only writes to the console. 

How should this FailOn flag used?

**Comment by freddydk** [comment]
FailOn is only for Azure DevOps, and this will signal to the pipeline that the task failed.
Azure DevOps picks up the messages written to the console.

**Comment by janicechewyc** [comment]
Thank you for the explanation @freddydk 
It seems like Compile-AppInNavContainer does not throw the error/warning messages and I need to fail the build for certain error/warning codes. 
I've tried using InformationVariable but the error/warning messages doesn't get passed into the stream. 

Do you know if there's anyway I can obtain the error/warning messages from the calling function so that I can then build a logic on what to do with the error/warning codes?
Thanks in advance.

**Comment by freddydk** [comment]
As far as I know, only way is to look at the output of the function.
Inside the function I call the ALC.EXE which also works by just printing out things.
Using -azuredevops sends the output through some regular expressions developed by @kine and becomes Azure DevOps consumable output.

**Comment by freddydk** [comment]
There is also a parameter called -outputTo, which is a scriptblock.
You can specify another scriptblock to that one and decipher the output from ALC.
It is mostly build for devops, but you could do the same as in the convert-ALCOutputToAzureDevOps

**Comment by janicechewyc** [comment]
Thank you @freddydk for the suggestions. Really appreciate it. 
I try not to modify the navcontainerhelper scripts, that's why I'm trying to see if there's a way to build the logic from the calling function based on the output from Compile-AppInNavContainer.

**Comment by freddydk** [comment]
You don't have to modify the containerhelper.
Compile-AppInBcContainer takes a parameter called -outputTo, which you can use like:
```
$global:lineno = 0
Compile-AppInBCContainer -containerName test2 -appProjectFolder "c:\programdata\navcontainerhelper\OIOUBL-Food\OIOUBL-Food" -credential $credential -outputTo { Param($line)
    $global:lineno++
    Write-Host "$($global:lineno) $line"
    if ($line.Contains('ended')) {
        throw "it all ended!"
    }
}
```
Basically the scriptblock is executed for every line output from alc.exe

**Comment by janicechewyc** [comment]
Thank you @freddydk ! Your sample works perfectly
