### ISSUE TITLE
Install-Module navcontainerhelper fails

### ISSUE THREAD

**Issue by orjanbrun** [microsoft/navcontainerhelper#954]
An error message is triggered when trying to install a new version of the navcontainerhelper (see screenshot). Any idea what could cause the problem? Thanks in advance.

![image](https://user-images.githubusercontent.com/43063136/79987427-b0e18600-84ad-11ea-86a7-cf143b993162.png)

**Comment by NAVspecialist** [comment]
Are you running CMD as admin or should you by any chance be running Powershell v7?

Powershell v7 gives the same error but running CMD as admin does work.

**Comment by orjanbrun** [comment]
Thank you for feedback! I am running it from PowerShell ISE (Run as administrator).

![image](https://user-images.githubusercontent.com/43063136/79993293-e5a50b80-84b4-11ea-9bd8-d6dc7f8317f3.png)

**Comment by NAVspecialist** [comment]
you should try to run a command prompt as administrator and do the following (this worked for me)

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
Install-Module -Name navcontainerhelper -Force

**Comment by orjanbrun** [comment]
I am getting the same error message,, if trying to run the Install-Module command from Windows PowerShell CMD, as Administrator (see screenshot).

![image](https://user-images.githubusercontent.com/43063136/80002492-02930c00-84c0-11ea-8a04-d5d6eb4fe5d8.png)

**Comment by NAVspecialist** [comment]
Run Set-ExecutionPolicy -ExecutionPolicy RemoteSigned as administrator
EXIT the command prompt
Start a new command prompt as administrator and then run
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
EXIT
and then finally do a 
Install-Module -Name navcontainerhelper -Force (without the requiredversion)

**Comment by orjanbrun** [comment]
Thanks for Your help! However this is the outcome of you recommendations.

The first command results in an error message (see below). Apparently the command executes, but is overridden. 
![image](https://user-images.githubusercontent.com/43063136/80003637-9913fd00-84c1-11ea-81e4-5d4ddfa56e77.png)

If I igore that message and opens a new cmd window and execute the 2:nd command, this is executed without any message.

However, executing the 3:rd command, the very same error occurs again. (see below)
![image](https://user-images.githubusercontent.com/43063136/80003905-f6a84980-84c1-11ea-8407-d9ef9784d174.png)

**Comment by freddydk** [comment]
wouldn't you have to use 

Set-ExecutionPolicy -ExecutionPolicy unrestricted

NavContainerHelper is not signed.

**Comment by orjanbrun** [comment]
Thanks for your feedback! Now, I tried once more, with the new suggested ExecutionPolicy. This is the outcome: The execution policy now seems to be honored, but the "Powershellgallery" source location is still considered "not valid". Please view screenshots below. As requested, I have also attached a "systeminfo.txt"-file.

![image](https://user-images.githubusercontent.com/43063136/80065889-319a9380-853b-11ea-8897-274b4cb78698.png)

![image](https://user-images.githubusercontent.com/43063136/80065924-4414cd00-853b-11ea-9698-d5d0a477c9e7.png)

![image](https://user-images.githubusercontent.com/43063136/80065948-4f67f880-853b-11ea-9b28-8d3a619a32d6.png)

[systeminfo.txt](https://github.com/microsoft/navcontainerhelper/files/4520596/systeminfo.txt)

**Comment by freddydk** [comment]
Maybe it is a TLS 1.2 problem?
https://techcommunity.microsoft.com/t5/windows-powershell/warning-source-location-https-www-powershellgallery-com-api-v2/m-p/1294648

**Comment by orjanbrun** [comment]
Spot on, it solved the problem. Thank you all for helping!

This is the command for installing Tls12 support:
![image](https://user-images.githubusercontent.com/43063136/80071548-1b91d080-8545-11ea-996d-85967ae3902e.png)

After installing Tls12, it was no problem to execute the command for installing the new navcontainerhelper module:
![image](https://user-images.githubusercontent.com/43063136/80071678-53007d00-8545-11ea-853b-824c40abd90f.png)

Verifying that the module is installed:
![image](https://user-images.githubusercontent.com/43063136/80071782-7fb49480-8545-11ea-8f2d-a36f74b459db.png)

**Comment by freddydk** [comment]
you can uninstall-module navcontainerhelper a number of times and then install the latest to avoid version number confusion

**Comment by orjanbrun** [comment]
thanks for your help! yes, I noticed that several versions were installed and were thinking about whether to clean them up. but glad to have solved the first problem, I did not want to ask more questions ... However, a few commands later, it looks better...
![image](https://user-images.githubusercontent.com/43063136/80073819-9c9e9700-8548-11ea-933e-3869b7348575.png)

**Comment by orjanbrun** [comment]
Problem solved. Thanks all for helping!
