### ISSUE TITLE
New-NavContainer Initialization of container failed

### ISSUE THREAD

**Issue by orjanbrun** [microsoft/navcontainerhelper#955]
Hi everyone, I am getting this error message (see screenshot below) as I try to create a new container for NAV 2018 CU5. My previous troubleshooting led me to a thread that suggested that the problem was corrected in a later version of navcontainerhelper, but despite upgrading to the latest version 0.6.5.6, the problem persists. I would be grateful for any help.
![image](https://user-images.githubusercontent.com/43063136/80077422-c60df180-854d-11ea-8a16-3d05215dee03.png)

**Comment by freddydk** [comment]
You will need to share the script you are using to run the container and the full output - not only the error, else we will be guessing.

**Comment by orjanbrun** [comment]
Thanks for your feedback! I have tried to capture the console output to a textfile, but I do not succeed. According to the postings I have found, this command (see screenshot) should capture the debug output to a file, but when I run it the file is created but empty. Any suggestions?
![image](https://user-images.githubusercontent.com/43063136/80109094-616a8b00-857d-11ea-983b-d12d50c309b4.png)

**Comment by freddydk** [comment]
Just use Ctrl+A, Ctrl+C and paste it here - and mark the text as "insert code" in the toolbar.

**Comment by orjanbrun** [comment]
`Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> cd \temp
PS C:\temp> .\MET2018CU5SE.ps1
NavContainerHelper is version 0.6.5.6
NavContainerHelper is running as administrator
Host is Microsoft Windows 10 Enterprise - 1803
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
NOTE: Add -alwaysPull or -useBestContainerOS if you want to use microsoft/dynamics-nav:2018-cu5-se-ltsc2016 instead of microsoft/dynamics-nav:2018-cu5-se.
Using image microsoft/dynamics-nav:2018-cu5-se
Creating Container MET2018CU5SE
Version: 11.0.21836.0-se
Style: onprem
Generic Tag: 0.0.6.3
Container OS Version: 10.0.14393.2312 (ltsc2016)
Host OS Version: 10.0.17134.407 (1803)
The container operating system does not match the host operating system, forcing hyperv isolation.
Using locale sv-SE
Using hyperv isolation
Disabling the standard eventlog dump to container log every 2 seconds (use -dumpEventLog to enable)
Using license file C:\Users\orjbru\OneDrive - Orango AB\licens\Orango Utv.licens NAV 2018 giltig 2020-07-31 (4922229).flf
Files in C:\ProgramData\NavContainerHelper\Extensions\MET2018CU5SE\my:
- AdditionalOutput.ps1
- AdditionalSetup.ps1
- license.flf
- MainLoop.ps1
- SetupVariables.ps1
- SetupWebClient.ps1
- updatehosts.ps1
Creating container MET2018CU5SE from image microsoft/dynamics-nav:2018-cu5-se
9b74987446cb8083aedbd24700aeecf0611a5da3d5d372c9960310b445ac33de
Waiting for container MET2018CU5SE to be ready
Initializing...
Setting host.docker.internal to 192.168.68.116 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.68.116 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.192.1 in container hosts file
Starting Container
Hostname is MET2018CU5SE
PublicDnsName is MET2018CU5SE
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B053538F7D23F916CC9F091DBC6CD08DBC4C43EE
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import License
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user SUPPORT
Setting SA Password and enabling SA
Creating SUPPORT as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements.
It should be at least 8 characters long and contain at least one uppercase
letter, one lowercase letter, and one number.
Cannot set "value" because only strings can be used as values to set XmlNode properties.
at <ScriptBlock>, C:\Run\my\AdditionalSetup.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 167
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1Error
Initializing...
Setting host.docker.internal to 192.168.68.116 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 192.168.68.116 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 192.168.192.1 in container hosts file
Starting Container
Hostname is MET2018CU5SE
PublicDnsName is MET2018CU5SE
Using NavUserPassword Authentication
Starting Local SQL Server
Starting Internet Information Server
Creating Self Signed Certificate
Self Signed Certificate Thumbprint B053538F7D23F916CC9F091DBC6CD08DBC4C43EE
Modifying Service Tier Config File with Instance Specific Settings
Starting NAV Service Tier
Using license file 'c:\run\my\license.flf'
Import License
Registering event sources
Creating DotNetCore Web Server Instance
Creating http download site
Creating Windows user SUPPORT
Setting SA Password and enabling SA
Creating SUPPORT as SQL User and add to sysadmin
Creating SUPER user
WARNING: The password that you entered does not meet the minimum requirements.
It should be at least 8 characters long and contain at least one uppercase
letter, one lowercase letter, and one number.
Cannot set "value" because only strings can be used as values to set XmlNode properties.
at <ScriptBlock>, C:\Run\my\AdditionalSetup.ps1: line 13
at <ScriptBlock>, C:\Run\navstart.ps1: line 167
at <ScriptBlock>, C:\Run\start.ps1: line 107
at <ScriptBlock>, <No file>: line 1
Initialization of container MET2018CU5SE failed
At C:\Program Files\WindowsPowerShell\Modules\navcontainerhelper\0.6.5.6\ContainerHandling\Wait-NavContainerReady.ps1:4
4 char:17
+ ...             throw "Initialization of container $containerName failed" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Initialization ...018CU5SE failed:String) [], RuntimeException
    + FullyQualifiedErrorId : Initialization of container MET2018CU5SE failed

PS C:\temp>
[MET2018CU5SE.zip](https://github.com/microsoft/navcontainerhelper/files/4523257/MET2018CU5SE.zip)

`

**Comment by orjanbrun** [comment]
Thanks for the help! I don't understand why one should make it more complicated than necessary ... However, I have now sent the log file and script that I run to create the nav container.

**Comment by freddydk** [comment]
I still don't see the script you are using?

new-navcontainer -? 

Basically I need to be able to run the same script in order to see whether the problem is on your machine or in your script.

I need script and all variables (except for secrets).

**Comment by orjanbrun** [comment]
Thank you for feedback! I did attach the script, using drag&drop along with the logfile, but I am not used with this forum so mybe something went wrong, sorry... Anyway here it comes.

`# --- Parameters
$username = "SUPPORT"
$password = "support2018"
$secureStringPwd = $password | ConvertTo-SecureString -AsPlainText -Force
$creds = New-Object System.Management.Automation.PSCredential -ArgumentList $username, $secureStringPwd
$sqlCreds = $sqlCredential = New-Object System.Management.Automation.PSCredential ('sa',$creds.Password)
$ContName = "MET2018CU5SE"

# --- NAV2018
$LicenseFile = "C:\Users\orjbru\OneDrive - Orango AB\licens\Orango Utv.licens NAV 2018 giltig 2020-07-31 (4922229).flf"

New-NavContainer -imagename microsoft/dynamics-nav:2018-cu5-se -accept_eula -accept_outdated -containerName $ContName -licenseFile $LicenseFile -credential $creds -memoryLimit 4G -updateHosts -useSSL -includeCSide -doNotExportObjectsToText -auth NavUserPassword -enableSymbolLoading

`

**Comment by freddydk** [comment]
The problem is that the image you are using is very old.
almost a year ago, the images was moved (see here: https://freddysblog.com/2019/07/14/nav-and-business-central-docker-images-moved-to-microsoft-container-registry/)
You should use mcr.microsoft.com/dynamicsnav:2018-cu5-se instead.

**Comment by orjanbrun** [comment]
Yes, I can now confirm that, with the new image address, the nav-container was created without any problems. I'm sorry I wasn't more observant about it being moved. Thanks so much for all your help in this issue!
![image](https://user-images.githubusercontent.com/43063136/80213401-68ef6a00-8639-11ea-8eee-273251c1c6d7.png)

**Comment by freddydk** [comment]
I am sorry that I haven't gotten the docker hub information site updated yet, will work on that.
