### ISSUE TITLE
Issue signing app with Sign-BCContainerApp -- outdated navsip.dll?

### ISSUE THREAD

**Issue by ShadowXVII** [microsoft/navcontainerhelper#958]
I'm trying to diagnose an issue where a specific app won't sign correctly -- trying manually on latest image also.

I suspect this might be something similar to the included VSIX issue from a little while ago (#903) -- is it possible to somehow get the latest navsip.dll when building for older images?

I'm still trying to isolate this issue, but would it be possible to output the version of the navsip.dll?

![image](https://user-images.githubusercontent.com/446329/80330027-5f5b4180-8887-11ea-8754-97dc5ada9a7a.png)

I guess this could happen in **microsoft/nav-docker**:
https://github.com/microsoft/nav-docker/blob/717027295bbe925fa2703efa05787f015361bcf1/generic/Run/HelperFunctions.ps1#L469

**Comment by ShadowXVII** [comment]
Actually, seems the version just matches platform, which makes sense.
Strange that on a new version I'm getting different signing results... continuing to test...

![image](https://user-images.githubusercontent.com/446329/80330918-ed382c00-8889-11ea-8d0e-e536ade17ce8.png)

**Comment by ShadowXVII** [comment]
I'll close this for now. Seems to be some deeper issues with the signing.

**Comment by freddydk** [comment]
FYI
The Sign-NavContainerApp signs the app inside the container.
Did you check whether the container is capable of internet connection? signing requires the container to connect to the internet. During startup of the container it will write a warning if internet connection isn't working (something with DNS lookup not possible)
Install-navsip... - installs navsip on the host.

**Comment by ShadowXVII** [comment]
Hi Freddy, tes, our other apps sign fine. I think it's actually on the publish side -- the verification seems to be failing despite the SignTool saying the signature is valid. Maybe trying to publish to an older version perhaps? Or maybe the Publish package error is actually something else?

I'm still digging, will post back if I find anything.

**Comment by freddydk** [comment]
Ok thanks.
