### ISSUE TITLE
"The property 'application' cannot be found on this object" error in Compile-AppInNavContainer

### ISSUE THREAD

**Issue by kine** [microsoft/navcontainerhelper#959]
Hi,
have it this bug:

When I use the new property "applicationInsightsKey" in the app.json, the compilation ends with the error

````
The property 'application' cannot be found on this object ....
````
which originates on line 184 of the Compile-AppInNavContainer:

````
if (([bool]($appJsonObject.PSobject.Properties.name -match "application")) -and $appJsonObject.application)
    {
        $dependencies += @{"publisher" = "Microsoft"; "name" = "Application"; "version" = $appJsonObject.application }
    }
````

It is because the -match "application" match this line too... I recommend to use -eq instead -match if the property name should be exactly "application".

**Comment by freddydk** [comment]
Shipped in 0.6.5.7
