### ISSUE TITLE
Web Client is not working BC14

### ISSUE THREAD

**Issue by skkulla** [microsoft/navcontainerhelper#969]
The web client is not working and it is empty when it starts container.  Other container web clients are working fine but not sure what is causing for this  below is the log 

Starting Local SQL Server
Starting Internet Information Server
Starting Service Tier
Container IP Address: 172.30.161.204
Container Hostname  : HOSK
Container Dns Name  : HOSK
Web Client          : 
Dev. Server         : http://HOSK
Dev. ServerInstance : NAV
Setting HOSK to 172.30.161.204 in host hosts file

Files:
http://HOSK:8080/al-3.0.154634.vsix
Initialization took 17 seconds
Ready for connections!
Initializing...
Setting host.docker.internal to  in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to  in container hosts file (copy from host hosts file)
Setting host.docker.internal to 10.0.0.7 in container hosts file (copy from host hosts file)
Setting gateway.docker.internal to 10.0.0.7 in container hosts file (copy from host hosts file)
Setting kubernetes.docker.internal to 127.0.0.1 in container hosts file (copy from host hosts file)
Setting host.containerhelper.internal to 172.30.160.1 in container hosts file
Restarting Container
PublicDnsName unchanged
Hostname is HOSK
PublicDnsName is HOSK
Using NavUserPassword Authentication
Container IP Address: 172.30.167.210
Setting HOSK to 172.30.167.210 in host hosts file
Container IP Address: 172.30.168.88
Setting HOSK to 172.30.168.88 in host hosts file
Initialization took 21 seconds
Setting host.containerhelper.internal to 172.31.224.1 in container hosts file
Container IP Address: 172.31.229.155
Setting HOSK to 172.31.229.155 in host hosts file
Initialization took 27 seconds

**Comment by freddydk** [comment]
What script leads to this output?

**Comment by skkulla** [comment]
New-BCContainer `
    -accept_eula `
    -containerName $containerName `
    -imageName mcr.microsoft.com/businesscentral/onprem:14.4.35602.0-na-ltsc2019 `
    -licenseFile 'C:\Users\skulla\OneDrive - ArcherPoint, Inc\Documents\Licenses\APDEV-BC.flf' `
    -memoryLimit 8G `
    -Verbose `
    -shortcuts Desktop `
    -updateHosts `
    -includeCside `
    -enableSymbolLoading `
    -includeAL `
    -auth navuserpassword `
    -accept_outdated 


First time it works but after a day or two the web client stopped working, one time in the log i got the message like you don't have permission denied to the path Microsoft.AI.Agent.ntercept.dll at New-NAVWebSite but that even disappeared after couple of restarts and is blank

**Comment by freddydk** [comment]
Some important information there in the second reply, but I would also need the full output.
I cannot see what isolation mode you are running, what windows version the host is etc. etc.
and please mark script and output with "insert code" in the toolbar - then it is formatted better.
Also, does this happen all the time - or did this happen maybe due to a windows update?
Typically if I get all these info in the first iteration, I can answer questions in a few minutes and it saves me and you precious time.

**Comment by freddydk** [comment]
Closing this bug. Please reopen with sufficient information for us to be able to see what is going on, else troubleshooting will be guesswork.
