### ISSUE TITLE
Get-NavContainerCountry/Get-LocaleFromCountry issue

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/navcontainerhelper#97]
When creating a container based on for example a financialsNL docker image, the cmdlet Get-NavContainerCountry is called in the New-NavContainer cmdlet, then the locale is retrieved based on this value.
In case of a financialsNL image this will return finNL, this value is then passed into the Get-LocaleFromCountry cmdlet and this returns nothing.

Further on in the actual docker scripts the locale is used to retrieve the CultureInfo and RegionInfo, if the locale is empty this might lead to unexpected DateTime properties when exporting objects.

I know this can be solved by specifying the locale myself in the additional parameters but I bet this is solve-able in a proper way.

**Comment by freddydk** [comment]
Yes, I can see that I haven't updated the getlocale function since the other countries where shipped - it only has 
    $locales = @{
        "finus" = "en-US"
        "finca" = "en-CA"
        "fingb" = "en-GB"
        "findk" = "da-DK"
        "at"    = "de-AT"
        "au"    = "en-AU" 
        "be"    = "nl-BE"
        "ch"    = "de-CH"
        "cz"    = "cs-CZ"
        "de"    = "de-DE"
        "dk"    = "da-DK"
        "es"    = "es-ES"
        "fi"    = "fi-FI"
        "fr"    = "fr-FR"
        "gb"    = "en-GB"
        "in"    = "en-IN"
        "is"    = "is-IS"
        "it"    = "it-IT"
        "na"    = "en-US"
        "nl"    = "nl-NL"
        "no"    = "nb-NO"
        "nz"    = "en-NZ"
        "ru"    = "ru-RU"
        "se"    = "sv-SE"
        "w1"    = "en-US"
        "us"    = "en-US"
        "mx"    = "es-MX"
        "ca"    = "en-CA"
        "dech"  = "de-CH"
        "frbe"  = "fr-BE"
        "frca"  = "fr-CA"
        "frch"  = "fr-CH"
        "itch"  = "it-CH"
        "nlbe"  = "nl-BE"
    }
Will be fixed in next update.

**Comment by freddydk** [comment]
This is probably the best fix:
    $country = $country.ToLowerInvariant()
    if ($country.StartsWith("fin")) { $country = $country.Substring(3) }

    $locales = @{
        "at"    = "de-AT"
        "au"    = "en-AU" 
        "be"    = "nl-BE"
        "ch"    = "de-CH"
        "cz"    = "cs-CZ"
        "de"    = "de-DE"
        "dk"    = "da-DK"
        "es"    = "es-ES"
        "fi"    = "fi-FI"
        "fr"    = "fr-FR"
        "gb"    = "en-GB"
        "in"    = "en-IN"
        "is"    = "is-IS"
        "it"    = "it-IT"
        "na"    = "en-US"
        "nl"    = "nl-NL"
        "no"    = "nb-NO"
        "nz"    = "en-NZ"
        "ru"    = "ru-RU"
        "se"    = "sv-SE"
        "w1"    = "en-US"
        "us"    = "en-US"
        "mx"    = "es-MX"
        "ca"    = "en-CA"
        "dech"  = "de-CH"
        "frbe"  = "fr-BE"
        "frca"  = "fr-CA"
        "frch"  = "fr-CH"
        "itch"  = "it-CH"
        "nlbe"  = "nl-BE"
    }

    return $locales[$country]

**Comment by richardrobberse** [comment]
I agree, thanks for the quick reply.

**Comment by freddydk** [comment]
fixed in 0.2.7.1
