### ISSUE TITLE
Can not Upload *.rapidstart file 198mb

### ISSUE THREAD

**Issue by BozidarP** [microsoft/navcontainerhelper#973]
I have

BC: Version: W1 16.0 (Platform 16.0.11233.12078 + Application 16.0.11240.12085)

I used docker/container in Azure environment (with traefik and let's encrypt), from Your template.

I have issue with upload *.rapidstart file, I get error:

The file could not be uploaded because it was too large. The maximum file size that can be uploaded is 950 MB.

I setup on BC service: ClientServicesMaxUploadSize  to 950.

---------------------------------------------------------------------
I setup on BC service: ClientServicesMaxUploadSize to 2047MB, I get error:

The file could not be uploaded because it was too large. The maximum file size that can be uploaded is 2047 MB.
 

The real size of *.rapid file is 198Mb.
I try so many solution, but unsuccessfully.

**Comment by freddydk** [comment]
Did you restart the service tier after changing the ClientServicesMaxUploadSize ?

**Comment by freddydk** [comment]
Of course you did, else you wouldn't get the error with the maximum file size that can be uploaded.

I don't think this has anything to do with Docker or NavContainerHelper and I think you would get the same error if installing the product manually. I would raise an issue with support, who might have seen this before, sorry.
