### ISSUE TITLE
Question: support for PowerShell 7

### ISSUE THREAD

**Issue by ralf-escher** [microsoft/navcontainerhelper#977]
Hi @freddydk!

Is there an update/support for PowerShell 7 planned?
`#Requires -PSEdition Desktop `

Thanks
Ralf

**Comment by freddydk** [comment]
https://github.com/microsoft/navcontainerhelper/issues/957

I don't think PS 7 support is just removing this line. I am thinking it is a larger task which I will have to have a look at.

**Comment by ralf-escher** [comment]
Thanks for the quick anwser!
Haven't see the existing issue.

**Comment by freddydk** [comment]
No problem - but yes, we definitely have to work on this...:-)
