### ISSUE TITLE
Export-NavContainerDatabasesAsBacpac uses hardcoded databasename 'tenant'

### ISSUE THREAD

**Issue by richardrobberse** [Microsoft/navcontainerhelper#98]
When using the Export-NavContainerDatabasesAsBacpac cmdlet on a multi tenant container, errors will occur when it tries to alter the database 'tenant'.

This happens because the database tenant does not exist, this should be the name of the tenant database (for example financials<locale>, cronus<locale> or mydatabase in case of a bak file)
![2018-03-13 09_55_00-export-navcontainerdatabasesasbacpac ps1 - navcontainerhelper - visual studio co](https://user-images.githubusercontent.com/29714289/37333877-b110d04e-26aa-11e8-8e89-1ba5414010dc.png)

**Comment by freddydk** [comment]
I will have a look after Directions.
There should always be a tenant database - this is the tenant default, which isn't mounted.
I assume that you have used bakfile and multitenant - I am not sure that works at this time.

**Comment by richardrobberse** [comment]
Yes I have used my own bakfile and converted my container to multi-tenancy by creating a script based on the steps described here: https://docs.microsoft.com/en-us/dynamics-nav/how-to--export-the-application-tables-to-a-dedicated-database

I have replaced the "tenant" value by the name of my tenant database for testing purposes and it works like a charm, I'll now test if I can create another container based on those bacpacs.

**Comment by freddydk** [comment]
Ok - yes that should be automatic if you specify -bakfile and -multitenant.
The scripts require the tenant db in order for the new-navcontainertenant to work

**Comment by richardrobberse** [comment]
Ok, thanks a lot.
I didn't know it was possible to create the container as multi tenant straight away, I'm completely fine with this and I have no problem with the hard coded database name in this scenario.

Have fun at directions :)
