### ISSUE TITLE
Issue creating new container

### ISSUE THREAD

**Issue by Bssivivek** [microsoft/navcontainerhelper#982]
I use below poweshell comamnd to pull the latest image
docker pull mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019

Whe i try to use below command to create new container, i got below error

New-NavContainer -containerName sbmem -accept_eula -auth NavUserPassword -imageName mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019  -licenseFile "C:\Work\D365BC-V15.flf" -updatehosts -includeAL

![image](https://user-images.githubusercontent.com/38437776/81506955-b9f49480-92ae-11ea-80e8-86ddeec17d79.png)

WIndows OS information:
Edition: Windows 10 Enterprise
Version: 1903

please help!!

**Comment by freddydk** [comment]
Reset your docker installation to factory defaults and try again would be my suggestion.

**Comment by Bssivivek** [comment]
Hi fredy - iam still getting the same error.
I did factory reset and also uninstalled everything and reinstalled it again. I am still getting te same error.
It says - required feature is not installed but it doesnt say whats the feature that it is missing.
if you can point me in right direction, that should be great.

**Comment by freddydk** [comment]
Did it use to work on this machine?
Can you start other containers?
Could you paste the full output of the container generation here?
Is HyperV installed?

**Comment by AndriusAndrulevicius** [comment]
this one is caused by HyperV not being enabled on the machine (99% of the time)
