### ISSUE TITLE
Direction in appropriate BC container/service 

### ISSUE THREAD

**Issue by BozidarP** [microsoft/navcontainerhelper#983]
Hello, 

I have issue with services.

My environment:

I used docker/container in Azure environment (with traefik and let's encrypt), from template.
BC: Version: W1 16.0 (Platform 16.0.11233.12078 + Application 16.0.11240.12085)

How to setup right service, when I want to use SOAP to upload Data in to container.

When use regular service, I cannot pull/push data, just can see.
![image](https://user-images.githubusercontent.com/44054400/81548208-36ee3f80-937d-11ea-8192-5dae7a732309.png)

Because the serviceis same for all containers:

![image](https://user-images.githubusercontent.com/44054400/81548361-774dbd80-937d-11ea-9f7f-bf4ae2fbb92e.png)

**Comment by tfenster** [comment]
@BozidarP This is a known issue with the Traefik-based setup. You need to replace everything before "/WS" in the URL with the base URL that you already are using. So "https://...westeurope.cloudapp.azure.com:7047/BC/WS/..." needs to be changed to "https://...westeurope.cloudapp.azure.com/Eurolabsoap/WS/...".

**Comment by freddydk** [comment]
Exactly. Unfortunately, the URL's inside SOAP and OData output doesn't follow the PublicSoapBaseUrl and PublicODataBaseUrl.
@henrikwh - isn't this something we should fix in the product?

**Comment by BozidarP** [comment]
@freddydk 
Can I manually modify link?

**Comment by freddydk** [comment]
At this time, you cannot make BC return the right thing - you need to download and modify the xml yourself. If you are using this from a third party app, which uses these links, then you need to setup a proxy (which you make yourself) or like.

**Comment by henrikwh** [comment]
I think this is something we need to look into. I will make sure it gets into the backlog.

**Comment by BozidarP** [comment]
Thanks to all.

**Comment by freddydk** [comment]
Will close this one here - it isn't anything I can do anything about, sorry.
