### ISSUE TITLE
Incorrect Warning on creating new container

### ISSUE THREAD

**Issue by ashikivor** [microsoft/navcontainerhelper#988]
I pulled the latest image and also used the tag -alwaysPull while creating the container. Still, I get the "WARNING: You are running a container which is 89 days old.
Microsoft recommends that you always run the latest version of our containers."

![image](https://user-images.githubusercontent.com/28855499/81879238-7e95e680-958a-11ea-8546-28b206f1dc1b.png)

NavContainerHelper is version 0.6.5.10
 Microsoft Windows 10 Pro - 1909
Docker Client Version is 19.03.8
Docker Server Version is 19.03.8
Pulling image mcr.microsoft.com/businesscentral/sandbox:de-ltsc2019

**Comment by TheDenSter** [comment]
Same here, mine was downloaded just 5 minutes ago and it tells me the container is 77 days old.

New-BCContainer `
    -accept_eula `
    -containerName $MySettings.DevContainerName `
    -imageName $MySettings.ImageName `
    -licenseFile $MySettings.LicenseFile `
    -auth NavUserPassword `
    -assignPremiumPlan `
    -updateHosts `
    -useBestContainerOS `
    -Credential $Credential
NavContainerHelper is version 0.6.5.10
NavContainerHelper is running as administrator
Host is Microsoft Windows Server 2019 Standard - ltsc2019
Docker Client Version is 19.03.5
Docker Server Version is 19.03.5
Using image mcr.microsoft.com/businesscentral/sandbox:us-ltsc2019
Creating Container MySandbox
Version: 16.1.12629.12805-us
Style: sandbox
Platform: 16.0.12630.12758
Generic Tag: 0.0.9.99
Container OS Version: 10.0.17763.973 (ltsc2019)
Host OS Version: 10.0.17763.107 (ltsc2019)
A better Generic Container OS exists for your host (mcr.microsoft.com/dynamicsnav:10.0.17763.437-generic)
Using generic image mcr.microsoft.com/dynamicsnav:10.0.17763.437-generic
Patching navinstall.ps1 to stop the Service Tier for reconfiguration
Generic Container OS Version: 10.0.17763.437 (ltsc2019)
Generic Tag of better generic: 0.0.9.99

**Comment by freddydk** [comment]
This is caused by the generic image not having had any updates for a long time (base of new images). You will have to use -accept_outdated to start the containers. Will update the generics asap

**Comment by ashikivor** [comment]
The container is working fine :) 
It's only about the warning, and also noticed this warning for NavContainerHelper is version 0.6.5.9

**Comment by freddydk** [comment]
I know why this happens.
When the February update of Windows 10 was released, the containers were incompatible with earlier versions of the host.
That means that if I changed the containers to use the new base image, all hosts would stop working until updated.
I decided to postpone that and wait until everybody got February or later on the host.
It looks like I waited too long.

Will see what I can do - in the meantime -accept_outdated makes sure that you can run the container.

**Comment by freddydk** [comment]
Latest NavContainerHelper automatically attaches the accept_outdated.
A more permanent solution is on it's way
