### ISSUE TITLE
Has arguments list description for New-BCContainer disappeared

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#989]
Hey Freddy,

Maybe it's me old set of brains that cannot find the listing of the arguments of New-BCContainer. Sorry to ask if it's so obvious that I should not have asked.

**Comment by freddydk** [comment]
help new-bccontainer -detailed

**Comment by lvanvugt** [comment]
Makes sense. Thanx. It's only a pity that it is not searchable and the list is not alphabetacally order. You keep on scrolling up and down.

**Comment by freddydk** [comment]
help new-bccontainer -detailed > help.txt
notepad help.txt

**Comment by freddydk** [comment]
the argument list is also available in ps
![image](https://user-images.githubusercontent.com/10775043/81914039-0f8fb080-95d1-11ea-8761-ce365ce9d3e7.png)

**Comment by lvanvugt** [comment]
True, but no descpriton.

**Comment by TheDenSter** [comment]
> help new-bccontainer -detailed

This feels familiar (probably from the PowerShell training in the basement of the Lindner hotel that I took years ago) but thanks for the reminder :)
