### ISSUE TITLE
On includeTestToolkit in context of BC15 and BC16

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#990]
Freddy,

You know am a huge fan of using the standard tests. As such I often need a container with standard test in them, so I apply the argument includeTestToolkit. With pre BC15 containers that was not a big thing to do with respect to the extra time in creating a container. But since BC 15, now all tests have nicely ben distributed over quite a number of extensions, it takes IMHO much too long to set up a container. Isn't there a way to have includeTestToolkit lt me specify which test apps I want to be included?

**Comment by freddydk** [comment]
You can specify -includeTestLibrariesOnly and then manually publish the tests you want.

You get the available tests using:
```
$existingTests = Invoke-ScriptInBCContainer -containerName test -scriptblock {
    Get-ChildItem -Path "C:\Applications\BaseApp\test\*.app"
}
```

You can publish them using:
```
Publish-BCContainerApp -containerName test -appFile ":C:\Applications\BaseApp\test\Microsoft_Tests-VAT.app" -skipVerification -sync -install
```
(Note the : in front of the path, which indicates that the path is a path inside the container and not on the host)

**Comment by lvanvugt** [comment]
Clear and thanx.

**Comment by freddydk** [comment]
You can also use the -backupFolder parameter to backup the database after publishing the tests and reuse the backup when launching the next container as described here: https://freddysblog.com/2019/09/08/containerhelper-0-6-4-1/
