### ISSUE TITLE
-includeTestLibrariesOnly argument for New-BCContainer seems not to work

### ISSUE THREAD

**Issue by lvanvugt** [microsoft/navcontainerhelper#991]
Maybe I am overlooking something, but just now build a new BC16 container (see script below) with -includeTestLibrariesOnly. When including the following library in my app,json it is not download:
```
    {
      "id":  "5d86850b-0d76-4eca-bd7b-951ad998e997",
      "name":  "Tests-TestLibraries",
      "publisher":  "Microsoft",
      "version":  "16.0.0.0"
    }
```
Get-NAVApp shows indeed that that library extension has not been installed. What I am missing?

> Id            : 8b3609cf-3947-44c3-9f20-ce6edc6da33f
> Name          : _Exclude_ClientAddIns_
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : 334ef79e-547e-4631-8ba1-7a7f18e14de6
> Name          : Business Central Intelligent Cloud
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : 8c972578-fe72-4aa5-ae51-cc5575fef2ea
> Name          : Send To Email Printer
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : c1335042-3002-4257-bf8a-75c898ccb1b8
> Name          : Application
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : 3d5b2137-efeb-4014-8489-41d37f8fd4c3
> Name          : Late Payment Prediction
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : e97bbbc7-16b6-470b-9428-376baa778970
> Name          : Send remittance advice by email
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : 63ca2fa4-4f03-4f2b-a480-172fef340d3f
> Name          : System Application
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : d09fa965-9a2a-424d-b704-69f3b54ed0ce
> Name          : PayPal Payments Standard
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : 437dbf0e-84ff-417a-965d-ed2bb9650972
> Name          : Base Application
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : c526b3e9-b8ca-4683-81ba-fcd5f6b1472a
> Name          : Sales and Inventory Forecast
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> Tenant        :
> 
> Id            : 58623bfa-0559-4bc2-ae1c-0979c29fd9e0
> Name          : Intelligent Cloud Base
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> 
> Id            : 2a89f298-7ffd-44a5-a7ce-e08dac98abce
> Name          : Essential Business Headlines
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> 
> Id            : 8afe7b40-8c87-4beb-ada0-451d1761bf95
> Name          : _Exclude_APIV1_
> Version       : 16.0.11240.12076
> Publisher     : Microsoft
> ExtensionType : ModernDev
> Scope         : Global
> 
> Id            : eaed498c-bb05-4fda-8310-41b22a23434e
> Name          : Blocking Deletion of Warehouse Shipment Lines (app)
> Version       : 1.0.0.0
> Publisher     : fluxxus.nl
> ExtensionType : ModernDev
> Scope         : Tenant

As it seems no test library at all.

**BTW**
This is my New-BCContainer script
```
New-BCContainer -accept_eula:$accept_eula `
                -containerName $containerName `
                -imageName $bcdockerimage `
                -includeTestLibrariesOnly `
                -licenseFile $licenseFile `
                -auth NavUserPassword `
                -credential $credential `
                -accept_outdated:$accept_outdated `
                -enableTaskScheduler:$false `
                -isolation hyperv `
                -updateHosts
```

**Comment by freddydk** [comment]
you need -includeTestToolkit (AND -includeTestLibrariesOnly)

**Comment by lvanvugt** [comment]
Ok. That's counter intuitive. But yes, now rereading the help that's what it says.
