### ISSUE TITLE
Pipeline fails when running multiple tests

### ISSUE THREAD

**Issue by AmandaTest** [microsoft/navcontainerhelper#992]
Hi there.
I created a build pipeline to run a series of ATT tests for BC16.0.  There are 8 extensions (test apps) which run one after the other.  The pipeline succeeds, however, I notice that results of the XUnit file for the third and forth app are not correct.   I have checked my powershell scripts to see if I had inadvertently called the wrong extension, but they all looks correct to me.  It looks like the previous tests do not cleared from the AL test page and the current tests do not get loaded. I end up with the same results file (different name) for extension 4, 5, 6

**Comment by freddydk** [comment]
I would need to see the script and see which parameters you are using for running the tests.

**Comment by freddydk** [comment]
I would also very much like to see the full output with -debugmode of the running tests (assuming that you have the latest containerhelper)

**Comment by AmandaTest** [comment]
here you go. 
[CIS.yml.txt](https://github.com/microsoft/navcontainerhelper/files/4631494/CIS.yml.txt)

**Comment by freddydk** [comment]
That is a pipeline.
I need scripts and full output - and you need to include -debugmode on the run-tests for the output you provide.

**Comment by AmandaTest** [comment]
Thanks Freddy.  After running with debugmode, I discovered that the 2 test apps weren't published, so looks like the system just ran what was already loaded in the AL test tool page (which was from the previous test app). I guess it would be nice if it cleared the table prior to loading it.  That way we would know that the correct tests are showing up.

**Comment by freddydk** [comment]
Thanks for that info - will check that

**Comment by freddydk** [comment]
I cannot repro this.
Calling Run-Tests with an extensionid that doesn't exists gives an error:

```
Validation errors occured. Error is: {
    "Severity":  0,
    "Description":  "There is no NAV App Installed App within the filter.\r\n\r\nFilters: App ID: {00000000-0016-0003-0005-000000000000}",
    "DescriptionShort":  null,
    "IsLocal":  false,
    "OriginatingControlPath":  null
}
at Run-Tests, C:\ProgramData\NavContainerHelper\Extensions\test\PsTestTool-6\PsTestFunctions.ps1: line 552
at <ScriptBlock>, <No file>: line 57
```

If you share your script and the full output, we could fix this to make sure that you and other doesn't run into this.
