### ISSUE TITLE
You are trying to run a container which is more than 90 days old.     Microsoft recommends that you always run the latest version of our containers.     Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.

### ISSUE THREAD

**Issue by shashiBssi** [microsoft/navcontainerhelper#995]
You are trying to run a container which is more than 90 days old.
    Microsoft recommends that you always run the latest version of our containers.
    Set the environment variable ACCEPT_OUTDATED to 'Y' if you want to run this container anyway.

have the latest sandbox image

**Comment by freddydk** [comment]
This is because the underlying generic image hasn't been updated since february.
You will have to specify accept_outdated.
I have changed navcontainerhelper to do this automatically yesterday - update to 0.6.5.11

**Comment by shashiBssi** [comment]
means now on it will not recommend to get latest containers.

**Comment by freddydk** [comment]
It will still give the warning unless you use -useBestContainerOS
A more permanent solution is on its way.
