### ISSUE TITLE
CICD Workshop improvement

### ISSUE THREAD

**Issue by GreatScott000** [microsoft/navcontainerhelper#999]
I chose to name my local agent the same name as my computer (seemed natural), this caused an error and a warning that maybe could be addressed in the CICD workshop document so that other don't have the same issues I had.  A note to state that the build agent name must start with a letter and that it should be  less than equal to 9 characters long would work.

In the Read-Settings.ps1 script the container name is defaulted to the build agent name plus "-build"  Unfortunately my computer name starts with a number (it is the HP tag number by default) so Create-Container.ps1 fails because container names have to start with a letter.

So if the computer name was prefixed (build-<computerName>) that would eliminate that error.  

Also it would appear that there is a 15 character "soft" limit on container names.  My computer name plus the "-build" suffix is longer than that (again HP default tag is 10 characters).  So maybe the container name should be truncated to eliminate that warning.

**Comment by freddydk** [comment]
Thanks - I will add a warning to the HOL document.

**Comment by freddydk** [comment]
I have changed the helloworld repo to use a prefix instead of postfix as suggested
